### ISSUE TITLE
brand-logo text wrap

### ISSUE THREAD

**Issue by elabsir** [Dogfalo/materialize#1000]
i have long brand-logo text and this text not responsive. in med size, text get bad wrapping.

![long-text](https://cloud.githubusercontent.com/assets/251942/6819201/fc39af2c-d2da-11e4-9b5f-942d1c0a0ae7.jpg)

![long-text-wrapp](https://cloud.githubusercontent.com/assets/251942/6819202/fdf134fc-d2da-11e4-83d6-493355f33a13.jpg)

is this bug ?

**Comment by Dogfalo** [comment]
Please recreate this in the Codepen on the Readme

**Comment by kampfkeks** [comment]
I know the issue. Just add this to your css file:
@media only screen and (max-width : 992px) {
nav .brand-logo {
position: relative;
display: block;
text-align: center;
}
}

This should fix it for 320px or larger.

**Comment by Dogfalo** [comment]
Fixed in d54c38ec808ab107a6f9fd7e7adbdc4e7c50e872
