### ISSUE TITLE
Request: <select multiple>

### ISSUE THREAD

**Issue by zion822** [Dogfalo/materialize#1002]
I would like to use ```<select multiple>``` similar to Chosen (http://harvesthq.github.io/chosen/). I managed to style Chosen somewhat like materialize but it still looks off. 

Any chance you will including the ```<select multiple>``` to the framework?

**Comment by ianvieira** [comment]
I created a similar solution using selectize.js, I don't know if I can do a pull request for it or should I create a new project just with it.

**Comment by crokobit** [comment]
@ianvieira  May you shared your solution ? I find everywhere but can not find any good solution yet :cry: .

**Comment by allthesignals** [comment]
I'm interested as well. I mostly just like how Chosen provides a nice built-in typeahead.

**Comment by DmitrySharikov** [comment]
hope, you guys know how to solve it 😓

**Comment by lmerotta** [comment]
Still nothing going on with this issue ? It would be great if this could be done !
