### ISSUE TITLE
Meteor two selects rendered.

### ISSUE THREAD

**Issue by rubs** [Dogfalo/materialize#1005]
Hi, Im having two selects rendered by the same html code in meteor:
![screen shot 2015-03-25 at 16 05 06](https://cloud.githubusercontent.com/assets/1469142/6827644/edc1d554-d308-11e4-826b-cc53a76bf800.png)

This is the markup for this select within the template:

```
<template name="newMatch">
 <div class="col s6 m6 l6" data-required="true">
	<select id="levelPicker">
	<option value="1" selected>Nivel 1</option>
	<option value="2">Nivel 2</option>
	<option value="3">Nivel 3</option>
	<option value="4">Nivel 4</option>
	<option value="5">Nivel 5</option>
	</select>
        <span class="help-block"></span>
</div>
</template>
```

And this is the initialisation:
```
Template.newMatch.rendered = function(){
    this.$('#levelPicker').material_select();
}
```
If anybody could help that would be nice ;)

**Comment by Dogfalo** [comment]
You must have overriden a display none on <select>

**Comment by rubs** [comment]
Thx for opening my eyes, I had a nice:

```
select {
   displey: block;
}
```

in my styles.css ^

**Comment by Dogfalo** [comment]
Good to hear you got it solved.
