### ISSUE TITLE
Input activation

### ISSUE THREAD

**Issue by the-new-sky** [Dogfalo/materialize#1006]
Hello, I have a problem with the input (text type) to materialize:
when that clicks on an input (the label), another field of another form is active but not one where I clicked.
I have this problem on Chrome and IE. Do you know how to solve it?
Sorry for the bad english, I'm french and I use Google translation (no comment ...), I put you my message in French if needed :

Bonjour, j'ai un problème avec les input (type texte) de materialize :
lorsque que clique sur un input (le label), un autre champ d'un autre formulaire s'active mais pas sur celui sur lequel j'ai cliqué. 
J'ai ce problème sur Chrome et IE. Savez vous comment le résoudre ?

**Comment by ciencia** [comment]
Try to use [CodePen] (http://codepen.io/Dogfalo/pen/xbzPQV) to reproduce your problem.

Be sure you use unique ID for each input, and the associated label has the correct "for" attribute for the input.

**Comment by the-new-sky** [comment]
Thank you for you answer ! The problem was the ID of the input !
