### ISSUE TITLE
Dynamically Add Collapsible Items

### ISSUE THREAD

**Issue by pcorey** [Dogfalo/materialize#1007]
Currently, if a new li is added to a collapsible ul, the newly added item will not be expandable. Only the collapsible-header will be shown.

If .collapsible() is called again on the ul after the new li has been added, all items within the collapsible list will collapse.

The collapsible plugin should correctly being called multiple times to support the addition of new items to the list, while ideally maintaining the active status of the current items in the list.

**Comment by erikwu** [comment]
The fix has a regression in the following code which let the collapsible-body extends and closes immediately.  

if (object.hasClass('active')) {
          object.parent().addClass('active');
}
else {
          object.parent().removeClass('active');
}

I think it should be

if (!object.hasClass('active')) {
          object.parent().addClass('active');
        }
else {
          object.parent().removeClass('active');
}
