### ISSUE TITLE
Date Picker not work

### ISSUE THREAD

**Issue by missjewel** [Dogfalo/materialize#1014]
in my html : 
<input type="date" class="datepicker">

in javascript:
$('.datepicker').pickadate({
    selectMonths: true, // Creates a dropdown to control month
    selectYears: 15 // Creates a dropdown of 15 years to control year
  });

And I give a error: 
![error datepicker](https://cloud.githubusercontent.com/assets/11300452/6857259/c03b9b04-d3d7-11e4-94e1-94b1fe5f3fb5.PNG)

**Comment by acburst** [comment]
This usually means you aren't including jQuery correctly
