### ISSUE TITLE
Question: Default Color

### ISSUE THREAD

**Issue by boustanihani** [Dogfalo/materialize#1015]
Is there a way to set a default base-color that gets applied to all components when no other color is specified?

**Comment by kampfkeks** [comment]
@boustanihani :

The base-color is defined in a sass file.
You have to download the framework with the sass files (there should be then a folder called "sass").
Then go into the sass/components.
There should be a file called _variables.scss.
There are all variables defined, after changing it you have to compile it again.

**Comment by boustanihani** [comment]
Thanks
