### ISSUE TITLE
Can a modal load another page instead of an existing div ID?

### ISSUE THREAD

**Issue by MattgyverHub** [Dogfalo/materialize#1016]
I'm probably missing something really simple, but can a modal load another page by passing an a href="otherpage.html" class="modal-trigger" instead of a href="#elementonthispage" class="modal-trigger". If the answer is no, would anyone be able to nudge me in the right direction or post a code snippet with the best way to do this? Thanks in advance.

**Comment by MattgyverHub** [comment]
The answer is basically no. The modal used here is a super lightweight one called <a href="http://leanmodal.finelysliced.com.au/" target="_blank"> leanModal </a>. It's about as bare as it gets; no ajax support, no urls, no iframes, etc. It excels at simply showing hidden div content on the page. One would have to roll their own or incorporate a more robust modal.

**Comment by vincentmorneau** [comment]
Anyone has an alternative?

**Comment by MattgyverHub** [comment]
Yes, use one of these: http://vodkabears.github.io/remodal/ or http://dimsemenov.com/plugins/magnific-popup/ Both are good, responsive, and can support just about anything you need to do.

**Comment by razzbee** [comment]
Actually I have been able it in a little strange way look at the example below 

` <script>
 $(function(){
 $(".in_iframe_modal").on("click",function(evt){
	 evt.preventDefault();
	 
	 btnDom = $(this);
	 
	 url = btnDom.attr("href") || btnDom.data("modal-frame-src");
	 
	 //lets get the modal title 
	 modalTitle = btnDom.data('modal-title') || btnDom.attr("title");
	 
	 
	 modal = $("#iframe_modal");
	 
	 modal.find("#modal-title").text(modalTitle);
	 
	 
	 winHeight = $(window).innerHeight()-70;
	 
	 modal.css({
		 "height" : winHeight+"px",
		 "max-height" : winHeight+"px",
	 });
	 
	 //close modal first 
	  //$("#iframe_modal").closeModal();
	  modal.openModal();
	  
	  frame =  $("#iframe_modal iframe");
	 
	 frame.css("height",winHeight);
	 
	 //change iframe modal src 
	 frame.attr("src",url);
     
	 
 });
	 
 });
 </script>
 
 <div class="modal modal-fixed-footer" id='iframe_modal'  style='width:98%;background:#ECEFF1;'>
    <div class="modal-content">
      <h5 id='modal-title'></h5>
      <iframe style='width:100%;border:none;'></iframe>
    </div>
    <div class="modal-footer">
      <a href="#!" class="modal-action modal-close waves-effect waves-green btn red">Close</a>
    </div>
  </div>
`

Then you will add the class ".in_iframe_modal" to every link or button you wish to use the modal with ,
to supply the modal title you will add the data-modal-title or simply the title attribute to the link or button, incase of button supply the url with data-modal-frame-src , 
Not the best but I solved my problem , example of link to trigger it 

`<a class='in_iframe_modal'  data-modal-title="Iframe Modal" href="http://example.com"> Open Iframe Modal</a>`

**Comment by thebiltheory** [comment]
Hi, 

I came accros this issue and thought about sharing a similar approach. 

```javascript
// Store downloaded requested files
var contentCache = {};

// Modal
$('.modal').modal({
     dismissible: true, // Modal can be dismissed by clicking outside of the modal
     opacity: .7, // Opacity of modal background
     inDuration: 300, // Transition in duration
     outDuration: 200, // Transition out duration
     startingTop: '4%', // Starting top style attribute
     endingTop: '10%', // Ending top style attribute

     /**
     * @function ready fires on modal trigger
     * @param {Object} Modal target window
     * @param {Object} Trigger of the modal window
     */     
     ready: function(modal, trigger) {

        // Check if contentCache already has the files
        if (contentCache[modal[0].id]) {
            $("#" + modal[0].id + " .modal-content").html(contentCache[modal[0].id]).fadeIn();
        } else {
            // Ajax request file
            // Ex id="abc" > file name: abc.html
            $.get('/' + modal[0].id + '.html', function(data){
                contentCache[modal[0].id] = data;
                $("#" + modal[0].id + " .modal-content").html(data).fadeIn();
            });
        }

        // Disable cut copy paste
       $('.modal-content').bind('cut copy paste', function (e) {
           e.preventDefault();
       });

        // Disable mouse right click
        $('.modal-content').on("contextmenu",function(e){
            return false;
        });
    }
   }
 );
```

Cheers
