### ISSUE TITLE
Waves overflows the button's border-radius or doesn't match it.

### ISSUE THREAD

**Issue by imjoeybrennan** [Dogfalo/materialize#1019]
![waves-overflow](https://cloud.githubusercontent.com/assets/1739106/6874861/01a605b6-d491-11e4-8b1e-a28f3f2ea4f3.gif)
As seen at https://www.straphq.com on iOS Chrome and Safari desktop. Also seems to be a problem with https://github.com/callemall/material-ui and LumX, but not a problem with Angular Material.

**Comment by imjoeybrennan** [comment]
So check this from Angular Material's button.scss 
https://github.com/angular/material/search?utf8=%E2%9C%93&q=the+following+hack

I can't seem to get this to work for materialize, though :'(

**Comment by jracollins** [comment]
I just tried the link you posted and it solved the issue, does it still not work if you add this to your css file? 

`.waves-effect {
        -webkit-mask-image: url('data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAIAAACQd1PeAAAAGXRFWHRTb2Z0d2FyZQBBZG9iZSBJbWFnZVJlYWR5ccllPAAAAA5JREFUeNpiYGBgAAgwAAAEAAGbA+oJAAAAAElFTkSuQmCC');
}`

**Comment by Dogfalo** [comment]
This removes the box-shadow from the element.

**Comment by jracollins** [comment]
I guess for those that still want a box-shadow, they can just wrap the button in another "btn-floating btn-large" ? - Just tried it and it works

**Comment by Dogfalo** [comment]
You should open this issue here (https://github.com/fians/Waves)
