### ISSUE TITLE
Feature Request: Same Width Buttons

### ISSUE THREAD

**Issue by boustanihani** [Dogfalo/materialize#1022]
Could you possibly provide the ability to let a stack of Buttons have all the same width?

For example the width of the biggest button in the group or maybe block style buttons that take the full width of their container...

Imagine a screen with 2 buttons in the center, Register & Login, vertically distributed and horizontaly centered... it would look nicer if they have the same width :)

**Comment by osleg** [comment]
Totally agree, looking for this as well. 
I think it should automatically resize to the width of parent <div class='col'> just like input fields do

**Comment by kampfkeks** [comment]
@boustanihani @osleg :

https://github.com/kampfkeks/materializeplusplus

Just clone this repo and import /dist/css/materialize-addon.css
Then you have class called button-group.
Just wrap your buttons in a div and apply the class to it.

**Comment by boustanihani** [comment]
@kampfkeks Nice work, are you planning to merge your repo with the official one?

I mean do you think the materialize-team could be interested in pulling your extensions?

**Comment by kampfkeks** [comment]
sure but just wanted to provide a quick way of handling it

**Comment by boustanihani** [comment]
Wow :+1: this was really quick :)

**Comment by boustanihani** [comment]
I'll keep this open until we get some feedback from the materialize team regarding your pull request...

**Comment by keyscores** [comment]
Is there no way to adjust the width of buttons, at all?

**Comment by HenriBeck** [comment]
@keyscores 

.some-class {
width: 70px;
}

<a href="#!" class="some-class btn">Some Button</a>

**Comment by boustanihani** [comment]
@acburst Will this feature get into the next release?
