### ISSUE TITLE
Feature Request: Fixed TabBar

### ISSUE THREAD

**Issue by boustanihani** [Dogfalo/materialize#1024]
This could be an extension of the included tabs component: http://materializecss.com/tabs.html

Just allow the tabs to be fixed top or bottom for navigation purposes on mobile devices, one could then replace a NavBar with a TabBar (with icon/text content)...

Similar to this (http://ionicframework.com/docs/components/#icon-top-tabs)

A very nice example is this site, which automatically pops in a (fixed-bottom) TabBar on small screens, try changing the window size: http://www3.hbc.com/

![www3 hbc com mobile](https://cloud.githubusercontent.com/assets/4227548/6880431/cb59ba98-d530-11e4-9ae7-c63852cbfd23.jpg)

**Comment by kampfkeks** [comment]
@boustanihani :

https://github.com/kampfkeks/materializeplusplus

Just clone this repo and import /dist/css/materialize-addon.css

Then just put this at the end of your main section:
<ul class="bottom-bar">
+			<li class="item">
+				<a>
+					<i class="mdi-navigation-menu"></i>
+					<span>Text 1</span>
+				</a>
+			</li>
+			<li class="item">
+				<a>
+					<i class="mdi-navigation-menu"></i>
+					<span>Text 2</span>
+				</a>
+			</li>
+			<li class="item">
+				<a>
+					<i class="mdi-navigation-menu"></i>
+					<span>Text 3</span>
+				</a>
+			</li>
+		</ul>

**Comment by boustanihani** [comment]
@kampfkeks could you possibly do a pull request for this too :) ?

**Comment by kampfkeks** [comment]
Working on it

**Comment by tomscholz** [comment]
Check this out https://github.com/jossiwolf/js_bottom_tabs. Please Close

**Comment by tomscholz** [comment]
@boustanihani Check [this](https://github.com/jossiwolf/js_bottom_tabs/) out
