### ISSUE TITLE
More than 3 grid breakpoints?

### ISSUE THREAD

**Issue by bobrocke** [Dogfalo/materialize#1026]
Is there a way to set up more than the three existing media breakpoints for grids (s, m and l)? Sometimes a design needs to change at more places to look good.

**Comment by kampfkeks** [comment]
Well there is no support for that, you would have to add this by your own.

And where would you set the min and max width of each breakpoint?

**Comment by bobrocke** [comment]
The breakpoints would depend to some extent on the nature of the design. It may require a different layout or other styles at various places,

**Comment by kampfkeks** [comment]
Well right now you would just have to add this by your own because it depends on the layout and the 3 grid breakpoints is generally good one.

**Comment by acburst** [comment]
We'll think about this for the future, but for now the best way would be to write your own breakpoints in Sass.

**Comment by isaachinman** [comment]
Hi there, can someone give an example of adding another breakpoint via the existing sass system, wherein classes apply media queries? Suppose I wanted a breakpoint under "small" called "tiny" that is anything under 400px.
