### ISSUE TITLE
SideNav shows only first list item and becomes darkened

### ISSUE THREAD

**Issue by hexturtle** [Dogfalo/materialize#1028]
I am using this basic structure to produce a SideNav and navigation bar:

```html
        <nav>
            <div class="nav-wrapper">
                <a href="/" class="brand-logo">Logo</a>
                <ul class="right hide-on-med-and-down">
                    <li><a href="#!">First Sidebar Link</a></li>
                    <li><a href="#!">Second Sidebar Link</a></li>
                </ul>
                <ul id="slide-out" class="side-nav">
                    <li><a href="#!">First Sidebar Link</a></li>
                    <li><a href="#!">Second Sidebar Link</a></li>
                </ul>
                <a data-activates="slide-out" class="button-collapse"><i class="mdi-navigation-menu"></i></a>
            </div>
        </nav>
```
I have applied this custom css:
```css
nav {
    position: relative;
    z-index: 1;
}
```

Without the css, the SideNav works as expected. However, with the css, the SideNav functions the same, except it only displays the first list item. i.e. the rest of the SideNav is not visible. Likewise, the list item that is visible is darkened.

I increased the z-index to 999 as was suggested in a previous issue. However, this only made it so that both the first list item and the nav bar would not be darkened, which does not solve either problem.

This is an example based on the code above:
![image](https://cloud.githubusercontent.com/assets/9427813/6882624/52afe34c-d562-11e4-80bc-38d08ef62bda.png)

As you can see, I am rendering a Google Maps map immediately below the navigation. The reason I need to increase the z-index of `<nav>` is so the `box-shadow` will appear over the map rather than being hidden by it.
Instead of styling `<nav>`, I also tried setting the map canvas to have a lower `z-index`. However, this produced significant difficulties. i.e. the map would not work

Thus, increasing the `z-index` for `<nav>` solves my issue with the shadow, but has the unintended consequence of messing with the SideNav.

What is the recommended way of increasing the `z-index` of `<nav>` without creating these problems for the SideNav?

**Comment by Dogfalo** [comment]
This is a bug in the latest release which can be fixed be removing `overflow: hidden` from <nav>

**Comment by hexturtle** [comment]
from what?

**Comment by hexturtle** [comment]
I've set `overflow: visible` for `<nav>` and this makes the rest of the SideNav appear. However, the SideNav is still darkened. Increasing the `z-index` for `<nav>` to 998+ allows for both the SideNav and the top navbar to not be darkened, though this is not the desired effect.
