### ISSUE TITLE
parallax images not always filling container

### ISSUE THREAD

**Issue by larsbrix** [Dogfalo/materialize#1029]
the parallax images dont seem to load correctly on init.
on scroll or resize it gets fixed.

im using angular and init everything after the dom is rendered.
the images are way too big for the page, so that may be the issue

here's an image:
![](http://i.imgur.com/M6namBC.png)

should look like
![](http://i.imgur.com/gHkXoBF.png)

**live:**
http://128.199.32.92/s/posts/2

also there's an issue with mousewheel scrolling, but i think there's already a few issues open regarding that.

**Comment by larsbrix** [comment]
it looks like the parallax handler does not get refreshed when you switch tabs.  
because of this the image in the 'new' tab has the position of the image in the 'old' tab.

firing a reflow with 
```
$(window).scroll();
```
in the click handler just before the 
```
e.preventDefauld()
```
in tabs.js (line 103) seems to do the job

**Comment by acburst** [comment]
We are currently reworking parallax so hopefully in the next release it will be much better with less bugs
