### ISSUE TITLE
Color classes don't work with buttons

### ISSUE THREAD

**Issue by rbozan** [Dogfalo/materialize#103]
All color classes (like .red) don't work with .btn

**Comment by anselmh** [comment]
May I ask why you add such a high specificity to every single color? This prevents devs from overriding any of the values without customizing the toolkit itself (which then can’t be fetched via npm/bower and be versioned). I also see no point in doing that as the initial issue mentioned here can be solved differently by adding a higher specificity without using the `!important` statement.
