### ISSUE TITLE
something with a 'tweensContainer' needs to exist

### ISSUE THREAD

**Issue by jrood** [Dogfalo/materialize#1031]
I wish I could give you really specific feedback, but honestly I just get this pretty randomly in the javascript console.
Uncaught TypeError: Cannot read property 'tweensContainer' of undefined
It doesn't seem to break anything.
It's hard to pinpoint what causes it.

I don't know what the heck a tweensContainer is...lol

**Comment by Dogfalo** [comment]
You likely have some scripts trying to run on null objects. In any case, I don't think this is a materialize problem.

**Comment by jaminellis** [comment]
That is most likely an issue with Velocity working on elements that have been removed from the DOM.

**Comment by patrickjaja** [comment]
I just ran into the same error (newest chrome - win7 x64), and solved this using the button-trigger.

`Uncaught TypeError: Cannot read property 'tweensContainer' of undefined`
`e @ materialize.js:221`

Seems like the modal js trigger is not working properly with the materialize collection.
When you try http://materializecss.com/modals.html#button-trigger outside the collection a link its working for you? Can you drop us your snipped (modal-trigger + div)?

**Comment by Dahkon** [comment]
Same problem for me.
Not everytime but it appends on some Toast disapearing.

Here in the minified code :
if("start"===C){var E;g(f).tweensContainer

Probably the object is removed from other scripts I'm using (backbone, handlebars, jquery...) at some point but a test of "g(f)" should correct the problem for every situation.

**Comment by sfcgeorge** [comment]
I also get this error when opening modals, but only sporadically.

**Comment by sfcgeorge** [comment]
I found a fix for my case. The `tweensContainer` error is coming from Velocity that Materialize uses for animation. The error happens if you remove an element that is being animated before the animation is finished. So I called `.velocity("finish").velocity("stop")` on the element being animated before removing it. Here's my example code with the "stop" bits added:

```javascript
$ ->
  $.rails.allowAction = (link) ->
    return true unless link.attr('data-confirm')
    $.rails.showConfirmDialog(link) # look bellow for implementations
    false # always stops the action since code runs asynchronously

  $.rails.confirmed = (link) ->
    link.removeAttr('data-confirm')
    $('#confirmationDialog').velocity("finish").velocity("stop")
    $('#confirmationDialog').remove()
    link.trigger('click.rails')

  # Materialize

  $.rails.showConfirmDialog = (link) ->
    $('#confirmationDialog').velocity("finish").velocity("stop")
    $('#confirmationDialog').remove()
    message = link.attr 'data-confirm'
    cancel = link.attr('data-cancel') || 'cancel'
    ok = link.attr('data-ok' ) || 'ok'
    html = """
           <div id="confirmationDialog" class="modal">
            <div class="modal-content">
              <p>#{message}</p>
            </div>
            <div class="modal-footer">
              <a href="#!" class=" modal-action modal-close waves-effect waves-green btn-flat">#{cancel}</a>
              <a href="#!" class=" modal-action modal-close waves-effect waves-green btn confirm ok-confimation-button">#{ok}</a>
            </div>
          </div>
           """
    $('body').append(html)
    $("#confirmationDialog").openModal
      ready: ->
        $('#confirmationDialog .confirm').on 'click', ->
          $.rails.confirmed(link)
        $('#confirmationDialog .modal-close').on 'click', ->
          $('#confirmationDialog').remove()
        $(".ok-confimation-button").focus()
```

**Comment by innovative1** [comment]
This issue should be reopened. This is a materialize bug. The solution proposed by sfcgeorge  above fixes this. Since materialize uses velocity internally, users shouldn't have to call velocity explicitly. Materialize should be calling `$(element).velocity("finish").velocity("stop")` before removing animated elements.

I have seen this with not only dialogs, but also tooltips and toasts.

**Comment by sfcgeorge** [comment]
Yeah it sporadically causes our integration tests to fail which is a pain, so I've wrapped tests to disable velocity... and jQuery animations, but there are still issues occasionally.

**Comment by blapsley** [comment]
Is this going to be re opened / addressed?  I still have this issue and have no way of removing it without saving and editing the file to make sure g(f) isn't undefined.  I'm not really even sure what this function is doing as it doesn't seem to break my page at all in its functionality.

I do not have any explicit DOM objects being removed so this explicit velocity call doesn't help me.

**Comment by newlarry** [comment]
Please re-open... I don't know what velocity is, only materialize. I'm getting this error sporadically.

**Comment by dbarison** [comment]
same here. Please re-open

**Comment by stewx** [comment]
Ditto, please re-open this. I get this error in my app when there are animations and elements are being removed.

**Comment by smileytechguy** [comment]
All the way in 2018, still asking to be reopened.

**Comment by Dogfalo** [comment]
This was an error message created by velocity which was removed in 1.0 alpha so this issue is deprecated

**Comment by shardy613** [comment]
The version installed when a user runs `npm i --save materialize-css` is `0.100.2`  ... Can this be reopened so that those that do install (for instance myself today) do not take this bug with them. Unfortunately after review I had to remove the package because this bug breaks other packages that use tween animations.

What is stopping a fix being implemented in the current release? I believe there is a solution posted above, do you guys accept PR's?

**Comment by smileytechguy** [comment]
@shardy613 if you want to install `1.0.0-beta` you may use `npm i --save materialize-css@1.0.0-beta` per the [version list](https://www.npmjs.com/package/materialize-css#versions) (click "22 versions" near the top-right) and [this SO thread on installing a specific version from NPM](https://stackoverflow.com/a/15892076/4236490).

**Comment by shardy613** [comment]
Thanks. Users can also user `npm install --save materialze-css@next` for a nightly release.

**Comment by shardy613** [comment]
Just to confirm, it is advised to use the 1.0.0-***beta*** version in production environments?

**Comment by Dogfalo** [comment]
While there are still some things we need to iron out, we do believe that 1.0.0-beta is in a more stable state than the old version (0.100.2), purely from the large number of bugs fixed. In addition, it is easier to use form a developer standpoint, especially inside Single Page apps

**Comment by shardy613** [comment]
Okay, thanks for taking time to confirm. 

Cheers.

**Comment by jrood** [comment]
Wow, I filed this issue 3 years ago yesterday. I'm glad you guys are figuring something out. :-D

**Comment by smileytechguy** [comment]
happy issueversay :P
