### ISSUE TITLE
jQuery Autocomplete works in card-panel but not in modal (displays autocomplete behind modal)

### ISSUE THREAD

**Issue by harryn** [Dogfalo/materialize#1033]
Hey!

I am trying use jQuery's autocomplete in a modal. The autocomplete uses a previously created array.
It works fine in a card-panel but when I put the exact same thing into a modal it isn't autocompleting anymore.
Does anybody have any ideas or suggestions of how to continue?
Or do you have any other ways to have an input field that suggests a value based on what the user has written into that field?

Thanks!

Edit:
I found out that it does display the suggestions... but behind the modal. How am I supposed to make it so that the suggestions are showed on modal not behind it?

**Comment by kampfkeks** [comment]
Set the z-index to 1001.
This should fix it.

**Comment by harryn** [comment]
Thanks! But z-index of what?

Modal:
<div id="newModal" class="modal new-modal">
    <div class="modal-content">
        <input id="tags">
    </div>
</div>
JS:
$( "#tags" ).autocomplete({source: arrayOfItems});

**Comment by kampfkeks** [comment]
@harryn :

.ui-front {
  z-index:1001;
}

**Comment by harryn** [comment]
It works, thanks! Had to use !important as well.
