### ISSUE TITLE
Color Suggestion

### ISSUE THREAD

**Issue by MageGenius** [Dogfalo/materialize#1038]
Add the black and white background colors from the stylesheet to the colors page.  Also, add a "color" class for transparent.  I've created a demo for the ideas at the bottom of this page: http://material.magegenius.com/fabric-color-palette

**Comment by acburst** [comment]
If you want you can add this to our documentation files and compile everything into a pull request

**Comment by MageGenius** [comment]
Another idea for the colors would be to include the ability to add hover colors with the Material color palette. 

Meaning for each color on http://materializecss.com/color.html add those same colors to hover states.  For example, here is a current snippet of the Red color:

.red {
  background-color: #F44336 !important; }

.red-text {
  color: #F44336 !important; }

Using a similar naming format as the 'red-text' if developers wanted to use these same colors for hover colors, these could be updated to:

.red, .red-hover:hover {
  background-color: #F44336 !important; }

.red-text, .red-text-hover:hover {
  color: #F44336 !important; }

Could be useful for hovering over elements that already have a background color or colored text links.  If this is something that would be a good addition to the project I can create the CSS and do a pull request if you like.

**Comment by acburst** [comment]
Merged 950aa8cd1064dbcb5b4e1b0ed344c9a1cb0967f6
