### ISSUE TITLE
Fixed header not working with left side menu in mobile devises

### ISSUE THREAD

**Issue by CBETOBuT** [Dogfalo/materialize#1043]
If open left side menu in mobile devises we have this:

![Error Image](https://leto13g.storage.yandex.net/rdisk/b549d27e2aa1828bc8fe52fe25114725e701b09cc478e781348184a0ed412090/inf/pnOdR-M0rvTleRQLZOh-i-MDshf1_3HdGrceSX4B9Vu8DG6u4D4yvPK5NCbcuJO3MEq_EkVmA6u8z55jE1Q8vA==?uid=0&filename=2015-03-30-13-30-55_751x698.png&disposition=inline&hash=&limit=0&content_type=image%2Fpng&tknv=v2&rtoken=876553fcd08c3e4d9acc94b407c85688&force_default=no)

We fixed this just adding class:

.navbar-fixed {
position: relative;
z-index: 998;
position: fixed;
width:100%;
}       
![Fixed Image](https://leto18f.storage.yandex.net/rdisk/9393b4f2ba94ca87cf9baea1e5949eae461cface00dfa73d7faad465085e85ac/inf/6vCRMeex84M7hGqq02nCm4vi5BO_5qyNvmmBTP3-CUPoCAdHOANuKx0pxWYvX7PNDDo7fnA0nRQvmBKKjRswWA==?uid=0&filename=2015-03-30-13-31-24_747x602.png&disposition=inline&hash=&limit=0&content_type=image%2Fpng&tknv=v2&rtoken=8d5214a9b1088613412fb6f15625096c&force_default=no)

**Comment by Dogfalo** [comment]
Fixed in the latest release.
