### ISSUE TITLE
Black background square on hover fixed button

### ISSUE THREAD

**Issue by Krazitchek** [Dogfalo/materialize#1044]
Look at the right bottom button, there is a black background square on hover.
It's new, previous version was good on this point.

Tested on Ubuntu Mate 14.04.02/Firefox 36.0.4 with last downloaded archive of Materialize from Github.

![screenshot](https://cloud.githubusercontent.com/assets/11500208/6896454/d325318c-d6eb-11e4-8480-759d757d6d0a.png)

**Comment by acburst** [comment]
Fixed in 4d740bcb928819686daa78f20b592335523b1c29
