### ISSUE TITLE
File input button is missing

### ISSUE THREAD

**Issue by Krazitchek** [Dogfalo/materialize#1045]
The file input button on form page is missing.
It's new, previous version was ok.

Tested on Ubuntu Mate 14.04.02/Firefox 36.0.4 with last downloaded archive of Materialize from Github.

![screenshot-1](https://cloud.githubusercontent.com/assets/11500208/6896543/bd2d732a-d6ec-11e4-8d42-f0e418c167c3.png)

**Comment by acburst** [comment]
Fixed in 40daaadc7c2ff51ec8114ce5c3a89b5e8b21c5a0
