### ISSUE TITLE
Background color button on hover

### ISSUE THREAD

**Issue by Krazitchek** [Dogfalo/materialize#1046]
It's not an issue, but the grey background color on hover button (Wave) is.. hum, ugly to me, all the customized colors on "wave page" (web site and archive from github) are  not really visible with this new behavior... too dark, previous behavious was ok, visible, clean.

New:
![screenshot](https://cloud.githubusercontent.com/assets/11500208/6896690/541a1152-d6ee-11e4-8873-50198b814fc7.png)

Previous:
![screenshot-1](https://cloud.githubusercontent.com/assets/11500208/6896691/5b6a6a2e-d6ee-11e4-9755-11a357a81d8b.png)

**Comment by acburst** [comment]
Yes this was an issue with button hover changes that should be fixed here:
40daaadc7c2ff51ec8114ce5c3a89b5e8b21c5a0
