### ISSUE TITLE
Scrolling cut off with fixed footer modal in Firefox.

### ISSUE THREAD

**Issue by AndrewCarterUK** [Dogfalo/materialize#1047]
I have the issue on my own project, but I managed to recreate it using the modal demo on the website:

http://materializecss.com/modals.html

Simply launch the fixed footer modal and vertically resize Firefox so that it forces the modal content to show a vertical scroll bar. At this point the bottom of the modal content will be cut off by the footer.

The only browsers I have access to are Chrome and Firefox, and I can only recreate this bug in Firefox (Chrome works fine).

The full sized modal:
![image 1](https://cloud.githubusercontent.com/assets/6486835/6896868/7e156c74-d6e7-11e4-81f1-17b2ba668998.png)

The modal with scrolling (mid-scroll):
![image 2](https://cloud.githubusercontent.com/assets/6486835/6896963/17f39456-d6e8-11e4-97a1-c49d1f116c0e.png)

The modal at the bottom of the scroll with the scroll bar and a significant portion of the modal content cut off by the footer:
![image 3](https://cloud.githubusercontent.com/assets/6486835/6896888/9ba437ac-d6e7-11e4-822f-e45d97076a73.png)

Thanks

**Comment by Dogfalo** [comment]
We're looking into the issue, I've discovered that adding a padding to the last child seems to solve the problem. But we'll see what we can do to fix this on Firefox.

**Comment by Dogfalo** [comment]
This is fixed now
