### ISSUE TITLE
Ability to stop or pause slider once user interacts with it?

### ISSUE THREAD

**Issue by MattgyverHub** [Dogfalo/materialize#1050]
Is there a method or function that can be called to stop the slider once a user has interacted with it? So triggering the next slide or previous slide from the nav bullets will make the slider stop auto-advancing?

**Comment by acburst** [comment]
Can you describe what you want more? So if when does it start up again. I'm just a little confused on what you are asking

**Comment by MattgyverHub** [comment]
A user interacting with the gallery in any way would stop the timer. Basically would like a way to kill the timer. 

Here's a scenario:

1) Let's say 5 slides will be shown.
2) One of the slides is a link/trigger that opens a modal.
Desired behavior:
The slider (now under the modal overlay) should no longer rotate.

Another scenario:

1) 5 slides again, each is has a paragraph or more of text content.
2) A user selects slide #3 from the navigation bullets.
3) They are not given enough time to read the slide before it advances to the next slide.
4) Selecting slide #3 again, they still don't have enough time to finish reading before it advances.
Desired behavior:
They learned how to use the slider from selecting the bullets, the timed transition is no longer needed; can freely choose the whichever slide they want.

How would one stop the timer?
Thanks!

**Comment by acburst** [comment]
Added stop and pause methods in d0d00789f9196211dc13b2fae688cb0cefde9064

You will have to add the functionality yourself with javascript.
