### ISSUE TITLE
valign and columns

### ISSUE THREAD

**Issue by steelcowboy** [Dogfalo/materialize#1051]
I am trying to vertically align images within a column. However, when I get the valign working like this:
```
<div class="container">
         <div class="row valign-wrapper">
              <div class="col s12 l4">
                    <p class="white-text flow-text center-align">Some text</p>
              </div>
              <div class="col s12 l8">
                    <div class="center-align">
                         <img class="responsive-img valign" src="pictures/picture.jpg">
                     </div>
              </div>
       </div>
</div>
```
The columns cease to work -- no matter what size there's always two columns. I've tried separating the valign wrapper into its own div, placing it in the column div, all with no avail.

**Comment by Dogfalo** [comment]
it probably won't work because col doesn't have a height inherently.

**Comment by jjalonso** [comment]
What the solution then?

For example I want to have a responsive image that should be valigned but the responsive-img have to be inside a col s6 m3 to change the size depend of the screen.

**Comment by sakulstra** [comment]
Is there any solution for the problem? I currently work with hide-on-... and have parts of the page 3 times duplicated :/

**Comment by famagusta** [comment]
I am facing the same issue - replicating code seems hacky (doing it because there is no other option)

**Comment by buzzb0x** [comment]
This should get fixed. It makes it so that it's not possible to valign something when you want to have it responsive.

**Comment by FelisPhasma** [comment]
Same problem. How have you all handled it? @buzzb0x @famagusta @sakulstra @jjalonso @steelcowboy

**Comment by kirtan403** [comment]
Anyone made this work?
