### ISSUE TITLE
White color on white background in Mobile Collapse Button

### ISSUE THREAD

**Issue by Krazitchek** [Dogfalo/materialize#1054]
On Mobile Collapse Button, when navbar is resized and hamburger icon appears, if you click on hamburger icon to show the links, all links are written in white color on white background. You can only see them on hover because a grey background appear.

See screenshot please.

Tested on Ubuntu Mate 14.04.02/Firefox 36.0.4 with Materializecss downloaded from Github commit 9cd401d3e8.

![navbar](https://cloud.githubusercontent.com/assets/11500208/6922512/f5b0b790-d7cb-11e4-9acf-ed9263151334.png)

**Comment by acburst** [comment]
Fixed in a6e96e325043da419c67ff84b1b169b20c6d9af3
