### ISSUE TITLE
Navbar Dropdown Menu the dropdown menu is contained in the navbar

### ISSUE THREAD

**Issue by Krazitchek** [Dogfalo/materialize#1055]
On Navbar Dropdown Menu the dropdown menu is contained in the navbar, so, only the first option is visible.

See screenshot please.

Tested on Ubuntu Mate 14.04.02/Firefox 36.0.4 with Materializecss downloaded from Github commit 9cd401d3e8.

![navbar2](https://cloud.githubusercontent.com/assets/11500208/6922551/46f0a700-d7cc-11e4-9e09-4b4f1c219640.png)

**Comment by mylastof** [comment]
I think, you need to setting the dropdown at http://materializecss.com/dropdown.html

**Comment by Krazitchek** [comment]
Maybe i'm wrong but i test every release of Materialize from github, this behaviour is new to me.

**Comment by Dogfalo** [comment]
Its just a old style that we had in our site style and not in materialize. I removed it however, 55942bee51989d10e02efd8fd8e017db7c322c45
