### ISSUE TITLE
Feature request: SideNav

### ISSUE THREAD

**Issue by signumcode** [Dogfalo/materialize#1059]
Great project guys!
Is it possible to add some more functionality to the SideNav?
Ex.
1. $('#someBtn').closeSlidebar('#idOfSomeSideBar');
2. $('#someBtn').closeSlidebar('#idOfSomeSideBar');
3.Also, can you(I already did) add possibility to use side bar within any HTML , not only ```<ul>``` tag, like
```
 <div id="authorization-out" class="side-nav">
    <div class="container">
               ...
    </div>
</div>
```
?

**Comment by HenriBeck** [comment]
@signumcode 

1. + 2. $('#someBtn').sidenav('hide') or $('#someBtn').sidenav('show')

3. Yeah they could but you would have to add to every tag a class.

**Comment by signumcode** [comment]
Sorry
1. $('#someBtn').showSlidebar('#idOfSomeSideBar');
    do it  $('#someBtn').sidenav('show') but for a particular sidebar idOfSomeSideBar ib the case if i have two side bars on the page(left and wright) 

2. $('#someBtn').closeSlidebar('#idOfSomeSideBar'); --same thing but for close particular sidebar

**Comment by Cedriking** [comment]
I'm also looking for something similar, example:
```javascript
$(".button-collapse").sideNav('#settings');
```

And in the HTML that way we can have multiple sidenavs, and not show only a sidenav of the nav that is already there (if we dont want to hide them on mobile, because of two icons, example).

```html
 <a href="#" data-activates="mobile-demo" class="button-collapse">Settings</a>
      <ul id="settings" class="right hide">
        <li><a href="sass.html">Sass</a></li>
        <li><a href="components.html">Components</a></li>
        <li><a href="javascript.html">Javascript</a></li>
        <li><a href="mobile.html">Mobile</a></li>
      </ul>
```

I think this is a very required feature.
Thank you guys.

**Comment by Dogfalo** [comment]
See [this](materializecss.side-nav.html#variations)
