### ISSUE TITLE
requestjs FIX Request

### ISSUE THREAD

**Issue by timothynode** [Dogfalo/materialize#1061]
Just Remove some error components like 
`
   "js/jquery.hammer.js",
   "js/date_picker/picker.js",
   "js/date_picker/picker.date.js"`
in Gruntfile.js (see this commit https://github.com/timothynode/materialize/commit/10305a87c04b2c9831b0d031cc5bdd1e37342563)
and build a requestjs version
this might be the fastest way to fix requestjs problem

**Comment by Dogfalo** [comment]
I'm not sure what requestjs is, but doing this will break a lot of functionality for most users.

**Comment by timothynode** [comment]
my mistake. it's require.js.
you can publish another release specially for require.js
