### ISSUE TITLE
Select - callback or event on select?

### ISSUE THREAD

**Issue by ganySA** [Dogfalo/materialize#1062]
Hi

I am currently using meteor + materlize, i see the select UL IDs are autogenerated, how would i get a callback or function when changing the value. Or where is the value being set....

Thanks.

**Comment by Dogfalo** [comment]
Add an ID to the original select, then add a change handler to it in Meteor. I have a Meteor app myself in which I do this.

**Comment by clemsos** [comment]
Actually, I don't think this is solved. I have the same behavior in my current app with an ID added to the select

**Comment by clemsos** [comment]
Well, it works now. I had an old jquery left in a folder that was auto-loaded by Meteor...
