### ISSUE TITLE
Update materialize package on atmosphere

### ISSUE THREAD

**Issue by ganySA** [Dogfalo/materialize#1064]
Hi

The version on atmosphere is 0.93 v the latest 0.95 which i am hoping has a fix to the select recreate behaviour in version 0.93 calling material_select() does nothing in 0.93 when called twice.

Is there any better alternative way to do this without waiting for the push to atmosphere? i tried copying over the materialize js files in the packages folder but that did not work.

**Comment by jonwhittlestone** [comment]
bump, thanks

**Comment by Dogfalo** [comment]
I am unsure of how to manually update libraries inside Meteor, but maybe someone more knowledgable about Meteor can help

**Comment by Kestanous** [comment]
Are you all sure you are using the correct page? See https://atmospherejs.com/materialize/materialize

> Current Version : v0.96.0

The reason why [auto-publish](http://autopublish.meteor.com/) is so amazing is because it uses GitHub hooks to auto update the atmo package.

**Comment by ganySA** [comment]
Yes, guess this was a timing issue. It is now up to date.
