### ISSUE TITLE
Narbar Toggle feature

### ISSUE THREAD

**Issue by louishugens** [Dogfalo/materialize#1067]
Hello Guys,

Have you implemented navbar-toggle feature as well like in Bootstrap. It transforms the navbar entries in a dropdown button when the screen become small.

//Thanks

**Comment by dhawken** [comment]
Scroll to the bottom of the docs on the navbar - there's the mobile collapse section.  This fires at a slightly bigger screen than i would like, but I think that's what you're looking for.

**Comment by louishugens** [comment]
Thanks dhawken! It was it. But it didn't behave exactly how i wanted. It seems it will create a side nav bar. I want it in the same page.

**Comment by dhawken** [comment]
Oh, like push the content down like the bootstrap behaviour?   I don't know of a way to do that off the top of my head, but perhaps one of the developers has a slick way to make the Side nav do that.

**Comment by Dogfalo** [comment]
I don't think this is something we want to do. The more material way to do this is definitely in a sidenav. Although you can use other js plugins to add this behavior.
