### ISSUE TITLE
background "overflow" on hover navbar item

### ISSUE THREAD

**Issue by Krazitchek** [Dogfalo/materialize#1068]
I compiled materialize.css with sass without changing the configuration of scss files.
	On hover item on navbar the hover background "overflow" on the shadow under the navbar.

	Same effect on Icon link example from Github archive.

	See screenshots please.

![capture](https://cloud.githubusercontent.com/assets/11500208/6946751/cf3d8bd8-d8a2-11e4-8c00-903d44a33150.png)

![2](https://cloud.githubusercontent.com/assets/11500208/6946755/d5c42c32-d8a2-11e4-99bc-b2070897015b.png)

**Comment by carlosperate** [comment]
Can confirm the issue in `navbar.html` from the current master (https://github.com/Dogfalo/materialize/commit/a56d8e66e99086eb46c3a5ca1a835dc7d571f57e) under win8.1 with all three firefox, chrome and IE11

**Comment by Dogfalo** [comment]
Fixed in 0fe3a1a22760b8754293a15e55467c3a29f24634
