### ISSUE TITLE
Tex with icon in navbar cuases overflow in IE

### ISSUE THREAD

**Issue by carlosperate** [Dogfalo/materialize#1073]
Tested IE11 on win8.1.

Taken from http://materializecss.com/navbar.html

![navbar](https://cloud.githubusercontent.com/assets/4189262/6954935/654e33ee-d8cf-11e4-9aac-3db296026049.png)

Somewhat similar to closed issue: https://github.com/Dogfalo/materialize/issues/618

**Comment by Dogfalo** [comment]
I just tested this in IE 11 too on Win 8.1. and I'm not seeing that.

**Comment by carlosperate** [comment]
You need to mouse over the "dropdown" and "link with Right" text for the overflow to happen when the area is highlighted,

**Comment by Dogfalo** [comment]
This has been fixed probably since 1e2cde9391f7ad16f5e9fab1cb74133d95f61569
