### ISSUE TITLE
Long sidebar (with scroolbar) gets cut out bottom in IE

### ISSUE THREAD

**Issue by carlosperate** [Dogfalo/materialize#1074]
Tested in IE11 on Windows 8.1

When the sidebar is long enough to scroll (like the http://materializecss.com/ sidebar) the bottom part gets cut out of the viewport (showcase link is inaccessible):

![sidebar](https://cloud.githubusercontent.com/assets/4189262/6955038/ab945a80-d8d0-11e4-8aae-17c264ea3a3a.png)

The scrollbar also behaves as if the sidenav element is larger than 100% and continues below the viewport. This effect is also present in Chrome, but the bottom-padding of 60px (https://github.com/Dogfalo/materialize/blob/master/bin/materialize.css#L6730) allows the all the contents to be displayed.

**Comment by jsduffy** [comment]
I've also noticed that the scroll bar for modal dialogs does not appear in IE (seems to be fine in Chrome).  Scrolling is still possible with the mouse wheel, seems like it's an issue with modal dialog width.

**Comment by serkandurusoy** [comment]
+1 for both issues!

Any known fix for these?

**Comment by fabyeah** [comment]
I encountered the same problem. Didn't find this thread back then, so I created #2112

**Comment by tomscholz** [comment]
Closed for cleanup purposes. Use https://github.com/Dogfalo/materialize/issues/2112 for comments and discussion instead.
