### ISSUE TITLE
Select: choose option on tab key press (like browser default)

### ISSUE THREAD

**Issue by sentenza80** [Dogfalo/materialize#1077]
Select fileds seems to work differently when materialized. If you focus on them and use keyboard to select an option you have to press enter. Browser default accepts tab key too instead.
Is there a workaround? 
The example here has this problem: http://materializecss.com/forms.html

Thanks

**Comment by TyrionGraphiste** [comment]
This is fixed now.

**Comment by NewBo1234** [comment]
Hey,

Great news.

...
...
...
So what was the fix?  What do we need to do?

?????

**Comment by jakoooob** [comment]
It used to work in < v1.0.0 . 
It does not seem to work anymore. I think this should be opened again.
