### ISSUE TITLE
Scrollspy target is not accurate anymore (0.96.0)

### ISSUE THREAD

**Issue by vincentmorneau** [Dogfalo/materialize#1080]
Self-explanatory, see screenshot:

![image](https://cloud.githubusercontent.com/assets/5391291/6963825/64928c7e-d911-11e4-8ffb-75067b055503.png)

There is a big gap when clicking on any Scrollspy link.

**Comment by Dogfalo** [comment]
It is actually meant to be like that so the item is more centered and will not conflict with any type of fixed header.

**Comment by vincentmorneau** [comment]
Thank you for the answer. Unfortunately I don't think it is natural. I will look for a way to bring it back below my fixed header.

**Comment by Dogfalo** [comment]
We will add it in as an option

**Comment by TheAdamGalloway** [comment]
Any idea how one would fix this? It's essentially ruined the relative links on our frontpage.

**Comment by TheAdamGalloway** [comment]
Fixed it... For anybody who was wondering, you must change the ScrollTop option for scrollspy in the javascript file.

**Comment by vincentmorneau** [comment]
Yup. As of 0.96.0, I had to put these values in comment in scrollspy.js :

![image](https://cloud.githubusercontent.com/assets/5391291/7036745/f1c1e0ec-dd65-11e4-9c7e-5f078b9d5d8f.png)

![image](https://cloud.githubusercontent.com/assets/5391291/7036752/0f71cfee-dd66-11e4-995f-eba24adb5dc9.png)

Works perfectly, until Dogfalo adds it as an option.

**Comment by whoiskjl** [comment]
I'm glad that this has been mentioned. How about a callback option? instead of scrollfire. Because I want to fire callbacks more than once.

**Comment by RichardLindhout** [comment]
+1 add this as an option! Thanks @vincentmorneau and @TheAdamGalloway!

**Comment by filippolcr** [comment]
Thanks Saved My life!

**Comment by limzykenneth** [comment]
I'm using the materialize ruby gem so editing the JS is not really an option for me. Any idea what can I do?

**Comment by TheAdamGalloway** [comment]
Over a year on, this is still an issue for me. I have to edit the JS file each time I update.

**Comment by vincentmorneau** [comment]
@TheAdamGalloway Me too...

**Comment by gratcliff** [comment]
Thanks for the tips guys! Worked perfectly :)

**Comment by NitroBAY** [comment]
What do you guys think of my PR ?

**Comment by kmmbvnr** [comment]
Yeah, I never was able to use ScrollSpy.

**Comment by TheAdamGalloway** [comment]
Looks good to me, @NitroBAY
