### ISSUE TITLE
Collapsible header click handling

### ISSUE THREAD

**Issue by milt** [Dogfalo/materialize#1081]
It looks like elements inside the header have the click handler attached, but the event target is the clicked element itself, and this has the "active" class added to it. To reproduce, click one of the icons in the collapsible demo, it will have the class "active" added to it.
Relevant code:

https://github.com/Dogfalo/materialize/blob/master/js/collapsible.js#L79

**Comment by acburst** [comment]
Fixed in 2362539070e9bbabdffe4d31e2a405fe14d47bad
