### ISSUE TITLE
Select dropdown "disabled" items cursor shouldn't be pointer

### ISSUE THREAD

**Issue by wongalvis** [Dogfalo/materialize#1086]
http://materializecss.com/forms.html
In a select dropdown menu, those with "disabled" shouldn't have pointer as the cursor, instead it should be set to initial.

**Comment by wongalvis** [comment]
https://github.com/Dogfalo/materialize/pull/1087

**Comment by Dogfalo** [comment]
Fixed in 1da02426e9d7d0249eea2da9f73af28aafa74046
