### ISSUE TITLE
Add input range implementation

### ISSUE THREAD

**Issue by Dogfalo** [Dogfalo/materialize#109]

**Comment by CoDEmanX** [comment]
I really like this implementation of a range slider:

http://ghusse.github.io/jQRangeSlider/demo.html

It supports manual number input, date ranges, steps and so on. You can also drag the left handle past the right one and vice versa.

**Comment by wagstorm** [comment]
+1 "implement range sliders that can select intervals by using two sliders"

**Comment by tchaecker** [comment]
+1 Would be a great addition range sliders (for price ranges for example) with defined steps and manual number input

**Comment by Kestanous** [comment]
:+1: for the polymer style implementation.

**Comment by xphoenix** [comment]
:+1: for the range slider

**Comment by francot** [comment]
+ 1 for the price  range sliders

**Comment by fabyeah** [comment]
+1 for a range slider with steps that can be individually set. E.g. "<10 , 10, 20, 30, 40, 50, >50"

**Comment by Dogfalo** [comment]
Added in 9f1298a
