### ISSUE TITLE
Feature request - hide the header by swiping/scolling down

### ISSUE THREAD

**Issue by digitalcraftsman** [Dogfalo/materialize#1090]
A very common effect in material apps, especially mobile ones, is the hiding of the header (an image or title) by swiping or scolling down. It's somehow like your parallx-demo.

Here is an gif to illustrate the effect:

![](https://d13yacurqjgara.cloudfront.net/users/577/screenshots/2002789/shot.gif)

**Comment by Dogfalo** [comment]
You can already do this using push pin.

**Comment by ecuanaso** [comment]
Dogfalo, Can you provide an example how to do this though?
