### ISSUE TITLE
content after fullscreen slider

### ISSUE THREAD

**Issue by louishugens** [Dogfalo/materialize#1092]
Hello Guys,

I'm new using materialize, so sorry :). I'm trying to add text after fullscreen slider but it apears under the slider. Any idea? Thanks.

**Comment by Dogfalo** [comment]
You might have changed the CSS on something

**Comment by louishugens** [comment]
The materialize.css file you mean?

**Comment by Dogfalo** [comment]
Can you produce your problem in the codepen on the README?

**Comment by martinmasignano** [comment]
Hey guys, I have the same problem here. When I try to add some additional content after the full screen slider, i.e. a div container, not shown below, but behind. That is, the slider hides the rest of the content. Any ideas?

**Comment by Shukichi** [comment]
Perhaps, try using z-index to move the element stack order?

**Comment by martinmasignano** [comment]
But I need to show content below, not behind

**Comment by Ethaan** [comment]
Did you guys find a solution to this?

**Comment by jomarbarnobal** [comment]
i come up with this. i wrapped my content in slider div like this
<div class="slider fullscreen">
   
  <div class="slides">
      <ul> <li> image_tag ' ' </li></ul>
  </div>

  <div class="yourcontent">
     
  </div>
</div>

**Comment by eleumas** [comment]
someone has solved this problem? The div, is under the "fullscreen slider"...

**Comment by JanG85** [comment]
Hi Guys!
Same Problem! Googleing around --> no solution!

My solution:

the problem is cause by the fullscreen class.

Do the following steps:

1. remove fullscrenn class after slider class
2: insert that into your style.css:

.slider {
    height: 100vh;
    top: -74px;
}

.slider .indicators {
  z-index: 9999;
  bottom: 30px;
}

3. insert this in your main.js:

$('.slider').slider({
        height: '100%'
    });

It works for me. Hope it works for you too

**Comment by anshap1719** [comment]
Or can wrap everything after the fullscreen slider in a div (say with id
content) and set css as follows :

#content {
    position: relative;
    top : 100vh;
}

Thats what I did!

**Comment by JanG85** [comment]
Thanks a lot!

your solution works much better on mobile.

thumb up! ;-)

**Comment by eleumas** [comment]
@anshap1719 Please, can you post your snippet for the fullscreen slideshow? I have tried your solution but i have some problem. Thanks.

**Comment by Rubel-hossain** [comment]
Thanks JanG85 , i am facing the same problem and solved by your given tips. But The Problem Should be solved By materialize.

**Comment by jomarbarnobal** [comment]
lets wait for materializecss developer to make it happen, for now use that step to use in your page, i only use full screen slider in sigle page app or landing page.

**Comment by kartikchauhan** [comment]
@anshap1719 thank you so much, that trick worked like a charm.

**Comment by diegofsousa** [comment]
Fantastic resolution! thanks!

**Comment by wiille** [comment]
still not solved? I´m facing the same problem.

**Comment by khushbuthakur** [comment]
I have got very simple solution i.e.

 **# $('.slider').slider({
         "height": $(window).height()
     });**
Remove fullscreen class from slider and write the above code in js.
This makes slider fullscreen and doesn't even hides content after slider. :)

**Comment by misterpola** [comment]
The problem is that the .fullscreen class gives the slider an absolute position.
If you wrap the slider in a div with width:100% and height: 100vh  it will work as intended.
