### ISSUE TITLE
Errors loading fonts

### ISSUE THREAD

**Issue by fvgs** [Dogfalo/materialize#1093]
I'm receiving the following errors in the console when trying to load a page. I'm running Chrome 41.0.2272.118 (64-bit). Not really sure what I can do about this.

![image](https://cloud.githubusercontent.com/assets/9427813/6990580/47d13aa4-da3d-11e4-8e3b-ba0b4adbbbbd.png)

**Comment by Dogfalo** [comment]
Some of the fonts did not upload to the CDN service properly. We'll work on fixing this as soon as possible

**Comment by Dogfalo** [comment]
Does anyone know what CDNJS pulls files from? Is it done manually?

**Comment by iceburg1991** [comment]
Maybe this documentation can help you :-) https://github.com/cdnjs/cdnjs. There is also an CDNJS import tool which may be useful: https://github.com/IonicaBizau/cdnjs-importer

**Comment by getupkid203** [comment]
Safer to install ur fonts to ur server. Ive never relied on CDN
