### ISSUE TITLE
Meteor compat with meteor and Materlialize namespace

### ISSUE THREAD

**Issue by ganySA** [Dogfalo/materialize#1094]
Hi

Declaring the meteor namespace as:

    ;var Materialize = {};

Makes it incompatible with meteor use as meteor will wrap this in its own closure (function()....)() which means the items would not be accessible

if you declare it without the "var" keyword meteor will make it a global namespace.

    Materialize = {};

Thoughts please? It shouldn't have any impacts?

Thanks

**Comment by Dogfalo** [comment]
Ah, I was under the impression just by exporting it in package.js it would work. Is it confirmed working after the change you referenced?

**Comment by ganySA** [comment]
Hi

I have not tried this for Materlialize, but on other js libs i use its generally the same problem. I just looked at the source and saw the var word which i know doesnt work.

You can read the following stackover flow (its also in meteor docs somewhere as well, but will need to scratch around)

http://stackoverflow.com/questions/27509125/global-variables-in-meteor

Cheers

**Comment by Kestanous** [comment]
I can confirm this issue. Unfortunately you must place `Materlialize` in the global space and then have `api.export('Materialize', 'client');` in your package js (which you have and is done correctly). I am using your current code, via clone, and it works. Can we get a patch so the atmo package will update?

**Comment by Kestanous** [comment]
Also I believe `this. Materialize` will also work if you define it in the global space. This could add some clarity for those looking at the code, instead of assuming it was a typo.

**Comment by Dogfalo** [comment]
I removed the var from Materialize, so it should work properly once the release is updated.

**Comment by Kestanous** [comment]
Sounds good. For those that need this now, you can clone this repository into a `packages/` directory. The name of the cloned directory will not matter and it should just work automatically.

**Comment by Dogfalo** [comment]
Fixed with v0.96.1

**Comment by Kestanous** [comment]
I can confirm this fix. Thanks!

**Comment by mibcadet** [comment]
I got this issue on 0.97.1 with Meteor 1.2 (newest update).
