### ISSUE TITLE
feature request: input field formats

### ISSUE THREAD

**Issue by steelcowboy** [Dogfalo/materialize#1099]
I was trying to use [formatter] (http://firstopinion.github.io/formatter.js/) so that an input field would force number in a specific format; it worked fine on a test page but fails when I try on a page that imports materialize.min.js. It would be cool if you guys could implement something similar to this directly into Materialize! Thanks!

**Comment by Dogfalo** [comment]
Can you be more specific about what you mean?

**Comment by steelcowboy** [comment]
So I wanted to have it so using the provided form classes, when I went to type a phone number it would only allow numbers and automatically format it to 999-999-9999 in the input box. I found that the formatter js that I linked up there worked when I created a html page only containing a text box and the script; however, when I import the materialize js (i.e. to use the framework) the formatter doesn't work. It seems something in materialize conflicts; since this is a nice feature anyways, maybe in the next version you could include the formatter in the materialize.js in a way that it doesn't conflict -- I don't know enough Javascript to do this myself (yet).

**Comment by Dogfalo** [comment]
Do you have an example of this?

**Comment by steelcowboy** [comment]
On my site: http://steelcowboy.me/test.html. Notice you can only type numbers and it will auto format to a phone number

**Comment by Dogfalo** [comment]
I mean when it is not working. That way I can see what is wrong.

**Comment by steelcowboy** [comment]
http://steelcowboy.me/test.php

I noticed in the log:
> Uncaught TypeError: $(...).mask is not a function

I tried only importing the materialize.min.js and it still worked, so I'm thinking it's a jQuery conflict

**Comment by steelcowboy** [comment]
I am actually using this I just realized: http://igorescobar.github.io/jQuery-Mask-Plugin/

**Comment by Dogfalo** [comment]
Looks like you included jquery twice

**Comment by steelcowboy** [comment]
Hmmmm, I did. Just removed it though, no effect.

**Comment by Dogfalo** [comment]
well you also included jquery mask before jquery was imported.

**Comment by steelcowboy** [comment]
Ahhh there we go, that fixed it... thanks!
