### ISSUE TITLE
Toast predefined html

### ISSUE THREAD

**Issue by Kestanous** [Dogfalo/materialize#1100]
Instead of using: ` Materialize.toast('I am a toast!', 3000)`

I would like to be able to do:
```js
   Materialize.toast('#myToast', 3000)
```
```html
<div id='myToast' class='toast'>
  Freshly toasted <a href='#'>Cheers</a>
</div>
```

The reason for this is related to Meteor JS. In Meteor we get a lot of really cool DOM manipulation but it must be rendered with the Blaze engine. There is no way to link a string of html rendered by the current toast to Blaze. (Ok, there are ways but they don't work in this context). Doing the above would let the meteor community hook up events and reactivity to make some really cool toasts.

**Comment by steelcowboy** [comment]
Having trouble with id, but to use it with a class:

> <p class="myToast">This will work fine!</p>

><script>
>       var x = document.getElementsByClassName("myToast")[0].textContent;
>       console.log(x);
></script>

><a class="btn" onclick="Materialize.toast(x, 4000)">Toast!</a>

**Comment by Kestanous** [comment]
Clever as it is, this trick will not work for me. What I want to happen is toast with a undo button. If the user clicks the undo button then the text changes to 'canceled' and the button goes away. Additionally I need event hooks to know that the button was clicked.

In this example `Materialize.toast(x, 4000)` is still only using a string and once fired there is no way of changing it.

**Comment by steelcowboy** [comment]
So the button turns to "cancelled" and then disappears? If you can put the x declaration in between where it changes to "cancelled" (x would store "cancelled") and before the button disappears, it should work fine.

**Comment by Kestanous** [comment]
I am not sure I fully understand what you mean, but it is also late for me. I will review in the morning and see if I can grok it. Will update should I figure this out.

**Comment by steelcowboy** [comment]
Alright, sorry I', not entirely sure how Meteor works either lol. My thought is you had to specify a function to change the button to cancelled, and then another to make it disappear; if Meteor does that all in one step, however, I see your problem.

And what do you want the toast to say exactly? What's wrong with it being static?

**Comment by Kestanous** [comment]
So what I have a table with a delete item button. When then click it the item is removed from the table. A request came in for confirmation beyond just being removed, thus the toast. However this gives us the ability to "undo" a deletion. Most of the app give feedback as soon as you do something. But in the case of the toast I can not hook events or change the context of the toast when the user interacts with it. The code I want to use would like something like this:


```html
<body>
 {{> myExampleToast}}   <!-- add the template html to the app -->
  <!-- the rest of my app-->
</body>

<template name='myExampleToast'>
  <div id='myToast' class='toast'>
  {{#if canceled}}
    Canceled, putting it back now
  {{else}}
    Goodbye data! <a class='cancel'>UNDO</a>
  {{/if}}
  </div>
</template>
``` 

```js
Template.myExampleToast.onCreated(function () {
  this.canceled = New ReactiveVar(false)
})
Template.myExampleToast.helpers({
  canceled: function () {
    return this.canceled.get()
  }
})
Template.myExampleToast.event({
  'click .cancel': function (event, template) {
    Template.instance().canceled.set(true)
    //cancel the deletion
  }
})
Materialize.toast('#myToast', 3000)
```
However at the moment none of this work, not even the events.

**Comment by Kestanous** [comment]
Side note, I added that code for other meteor devs and so everyone can see the full nature of my need. I am willing to use workarounds if necessary, this is my ideal.

**Comment by steelcowboy** [comment]
Ah, well what I was suggesting was something like:
```javascript
Template.myExampleToast.helpers({
  canceled: function () {
    return this.canceled.get()
    var x = document.getElementsByClassName("myToast")[0].textContent;
  }
})
``` 
so that immediately after it sets the button to cancelled it stores the new HTML content as `x`. Not sure if this is legal in what you want to do, and you said none of the code is working anyway, but something to that extent

**Comment by chazsolo** [comment]
I ran into the same issue, and am hoping that there is a way we can use something more _native_ in the future, but here is my workaround for now:

Make a Meteor Method in `/lib/methods.js`

````javascript
Meteor.methods({
    'test': function( data ) {
        console.log(data);
    }
});
````

Call toast normally 

````javascript
//...
Materialize.toast(Blaze.toHTMLWithData(Template.undoPurchase, this), delay);
//...
````

In your template, call the meteor method using an inline handler

````html
<template name="undoPurchase">
    <span>Bought {{name}}</span>
    <a class="btn undo" href="#" onclick="Meteor.call('test', '{{purchaseId}}');">Undo</a>
</template>
````

This will call the `test` method, passing in the `purchaseId` as data.  One problem is that this exposes any data to the client, so that should be put into consideration.

**Comment by delvedor** [comment]
Same problem here!
@chazsolo your solution works very well, thanks!

**Comment by Dogfalo** [comment]
Added in 771a291
