### ISSUE TITLE
Feature : Auto-Complete input

### ISSUE THREAD

**Issue by Mulix** [Dogfalo/materialize#1101]
Hi !

Is it possible to add the Auto-Complete feature on text_field like http://www.google.com/design/spec/components/text-fields.html#text-fields-auto-complete-text-field . It might be a input with a data-list attribute :+1: 

thx

**Comment by steelcowboy** [comment]
jQuery already has a plugin for this :) You can either do it with a static, predefined JS array or even build the array from pulling your data from a database via a php backend!

https://jqueryui.com/autocomplete/

**Comment by Dogfalo** [comment]
There are plenty of existing libraries for auto complete. It would be better to let developers use whatever they are familiar with.

**Comment by persyquiroz** [comment]
# ## ### 

> 

> 

> ddssd

> 

> [adadadad[](url)]([url]([url]([url]([url]([url](

- 

- [ ] 1. url

))))))
