### ISSUE TITLE
Add customization option for toast container by allowing class appending

### ISSUE THREAD

**Issue by rohu1990** [Dogfalo/materialize#1102]
Just like we pass class for the toast, give an option to pass toast container class. This should behave like different container for different classes so that every toast is appended to respecting containers.

Eg:

Format:  Materialize.toast(message, time, container classes,toast classes);

Working:
Materialize.toast('Something went wrong ', 4000, 'notification',error');
Materialize.toast('Warning toast', 4000, 'notification sticky','warning');
Materialize.toast('Successful 1', 4000, 'notification','success');
Materialize.toast('Successful 2', 4000, 'notification','success');

This should out put something like this 

<div class="toast-container notification">
     <div class="toast error" style="top: 0px; opacity: 1;">Something went wrong</div>
     <div class="toast success" style="top: 0px; opacity: 1;">Successful 1</div>
     <div class="toast success" style="top: 0px; opacity: 1;">Successful 2</div>
</div>
<div class="toast-container notification sticky">
     <div class="toast warning" style="top: 0px; opacity: 1;">Warning toast</div>
</div>

Possible issues : Toasts containers may overlap, but user can avoid this using custom styling

**Comment by acburst** [comment]
This is actually already an option

// Materialize.toast(message, displayLength, className, completeCallback);

**Comment by rohu1990** [comment]
but this classes are attached to only toast not to the toast-wrapper, so you cant style toast-wrapper, like if you want some of the toast-wrapper to appear on center some to the right and some to the bottom, it is not possible since we have a common post wrapper class

**Comment by rohu1990** [comment]
Also on my issue actual html was not being displayed, now I have corrected please take a look

**Comment by dcworldwide** [comment]
I'm also programatically calling toast(). With this approach, the doc's don't say how to control the position of the toast. It would be a great help if you could add some info. Thanks
