### ISSUE TITLE
Click events with dropdown no longer works

### ISSUE THREAD

**Issue by Kestanous** [Dogfalo/materialize#1103]
I was using jQuery to bind a click event to dropdown elements, via Meteor JS but is the same difference. Now it no longer bubbles up and I get a console log of:
```
d    materialize.js:2
```
That is all the description I am given. Using v0.96.0.

**Comment by acburst** [comment]
Can you give a specific example? We are having trouble recreating this

**Comment by Kestanous** [comment]
I am also having trouble recreating this outside the context of meteor, so it may be an issue on my end. That said it used to work and broke with the newest update.

The exact code is as follows, hopefully it is self explanatory:
```html
<template name='MasterLayoutGear'>
  <li>
    <a class="dropdown-button" data-activates="gearDropdown">
      <i class="mdi-navigation-apps"></i>
    </a>
  </li>
</template>

<template name='MasterLayoutGearItems'>
    <ul id="gearDropdown" class="dropdown-content"> 
      {{#if showSession}}
      <li><a href="/session">Session</a></li>
      {{/if}}
      <li class="profile"><a>Profile</a></li>
      <li class="divider"></li>
      <li class="logout"><a>Sign Out</a></li>
    </ul>
</template>
```

```js
Template.MasterLayoutGear.onRendered(function () {
  if (Meteor.user()) {
    this.$(".dropdown-button").dropdown({ //this is just a scoping tool
      alignment: 'right',
      constrain_width: false,
      hover: false
    })
  }
});

Template.MasterLayoutGearItems.events({
  'click .profile': function () { $('#profile').openModal() },
  'click .logout': function () { AccountsTemplates.logout() }
});
```

The `href="/session"` actually works but all three print the above issue to the console.

**Comment by Kestanous** [comment]
Update:  as of v0.96.1 the 'd' is no longer logged. The issue remains.

**Comment by qnub** [comment]
Seems like events in SideNav not works too…

**Comment by qnub** [comment]
@Kestanous also i found that `click` event in dropdown not generates if `.dropdown-content` block placed wrong. I.e. when i place it in same `li` element as `.dropdown-button` — events generates, in other places events can be not fired. Once i placed this block in `ul.side-nav` but not in `li` and events has been missed.

**Comment by Kestanous** [comment]
@qnub I don't believe that event scoping was my issue, but it is possible. Regardless it seems I am the only one having this issue. Additionally I am no longer actively working on the codebase that has this issue. Closing.
