### ISSUE TITLE
'datepicker' in 'collapsible' does not appear goes full

### ISSUE THREAD

**Issue by mylastof** [Dogfalo/materialize#1104]
![mater](https://cloud.githubusercontent.com/assets/2387514/7000707/18f34e4c-dc55-11e4-9784-83c9f1a54b7e.png)
datepicker not full view of screen ...

**Comment by Dogfalo** [comment]
This is expected behavior as the datepicker is created in its context in the dom

**Comment by mylastof** [comment]
yeah, but I need form in collapsible,
and the result like that ...

**Comment by acburst** [comment]
We want to make an inline datepicker in the future

**Comment by Dogfalo** [comment]
You can either try to resize the collapsible or move the form out of the collapsible.

**Comment by mibcadet** [comment]
If I have form in collapsible how I can move datepicker out?

**Comment by Dogfalo** [comment]
Search the closed issues for datepicker, there is an option to select the
container

**Comment by mibcadet** [comment]
Thank you for fast response!
