### ISSUE TITLE
What does this mean? Dropdown is now created as a child of its parent?

### ISSUE THREAD

**Issue by boris-petrov1214** [Dogfalo/materialize#1106]
What does "Dropdown is now created as a child of its parent" mean?
What should i change ?
Dropdown now works weird...

**Comment by jamesgiroux** [comment]
I second this.  Dropdowns now only show 2 items and no scrolling available.

**Comment by jamesgiroux** [comment]
Also, dropdown items are no longer wrapping.

**Comment by olivier67** [comment]
+1. It would help to have clearer documentation on dropdowns. I have to override default css on z-index and overflow to make it work properly.

**Comment by fujifish** [comment]
+1 same here. overriding z-index and overflow to make it work.

**Comment by Dogfalo** [comment]
In the most recent release, Dropdowns are created as a sibling to its button
