### ISSUE TITLE
Allow sidenav to scroll with page on desktop

### ISSUE THREAD

**Issue by RaymondBakkerMoonlightMultimedia** [Dogfalo/materialize#1108]
I'd really like to see this feature be implemented as having two seperate scrollbars is really counterintuitive when browsing on desktops.

**Comment by acburst** [comment]
What does this mean? Do you want it so that both the sidenav and the page scrolls at the same time? Because that sounds a lot more counterintuitive.

**Comment by RaymondBakkerMoonlightMultimedia** [comment]
Something like this.. http://leafo.net/sticky-kit/

And why would it be more counterintuitive? Desktop browsing with two seperate scroll bars is a huge hassle for many users..

**Comment by kabaka** [comment]
Based on the design specification, I believe the current behavior is the correct behavior.

http://www.google.com/design/spec/patterns/navigation-drawer.html

See "Scrolling" on this page.

**Comment by RaymondBakkerMoonlightMultimedia** [comment]
@kabaka Yes, it is thought out great, and works great, on mobile devices. In my opinion less so when utilizing it on platforms where it gets in the way of a great user experience as it is pretty counterintuitive on desktops.

The question arises, should we blindly follow the specification at the cost of user experience? In the specification all I see is screenshots from the mobile platform, not desktop.

The specification website seems to incorporate material design as well though here the navigation is filled up to about the height of 1080 pixels, which is probably the majority of desktop PCs (1980 x 1080), so it isn't a real issue if your navigation doesn't exceed that height, but my navigation exceeds it..

**Comment by acburst** [comment]
I think its counterintuitive because the user may not always want to scroll both with one scroll. In the case of a side nav, these elements are usually separate enough that you should scroll individually. When you want to read more of the main content it scrolls, and if you want to see more options, the side nav scrolls.

If the two things are more interconnected I could see your point but in this case I don't.

**Comment by Dogfalo** [comment]
I think that if people want this particular type of scrolling, it will be up to them. We will be leaving the current behavior as is.
