### ISSUE TITLE
side-nav invisible

### ISSUE THREAD

**Issue by louishugens** [Dogfalo/materialize#1110]
Hello Guys,

I use the side-nav to show on small screen but when i click on the toggle icon the there is a kind of transparent pan on the page and the side-nav link are there but invisible. Please help. Thans.

LH.

**Comment by Dogfalo** [comment]
Please create a codepen using the link from CONTRIBUTING.md

**Comment by Dogfalo** [comment]
I'll reopen this when you recreate this.

**Comment by louishugens** [comment]
It's ok,

there was an overflow in the nav, that's why it was hidden.

Best Regards
Hugens LOUIS
(+509)-37007622


2015-04-08 15:28 GMT-04:00 Alvin Wang <notifications@github.com>:
