### ISSUE TITLE
$scope.formName.$setPristine

### ISSUE THREAD

**Issue by pradeepb6** [Dogfalo/materialize#1111]
Is there any way to reset the form after its get submitted? Some classes like "valid" from input tag and "active" from labels should be removed so that form looks to original state after form is submitted. as of now i am removing classes manually using jquery.

**Comment by Dogfalo** [comment]
Just use form reset

**Comment by pradeepb6** [comment]
I used reset but dint workout for me.  could you please check here: https://github.com/pradeepb6/firstExample/tree/master/app and let me know if i am doing wrong. file to be checked index.html and app.js.

**Comment by Dogfalo** [comment]
Just use this http://www.w3schools.com/jsref/met_form_reset.asp
