### ISSUE TITLE
Add z-depth-0 to remove shadow from elements

### ISSUE THREAD

**Issue by LuisHerranz** [Dogfalo/materialize#1115]
Some elements come with default shadow, like the navbar or the buttons. I would like to have a z-depth-0 so we can remove the shadow on those elements and make them flat if desired.

**Comment by LuisHerranz** [comment]
Codepen with the code:
http://codepen.io/anon/pen/KwLoXr

**Comment by Dogfalo** [comment]
Added in c7305d328b73f361f5ed9d2c2e0f86d

**Comment by LuisHerranz** [comment]
Thanks!! :+1:

**Comment by 0bserver07** [comment]
Awesome.
It would be great to update the `Rails` gem with these updates.
Also the rgba is missing a zero at the end, it has to be 4 zeros

**Comment by smartclash** [comment]
I am just repeating what @0bserver07 said.

>It would be great to update the `Rails` gem with these updates.
>Also the rgba is missing a zero at the end, it has to be 4 zeros

I have mentioned you @Dogfalo  just to make sure you've already read his comment :)

**Comment by vivekgautamj** [comment]
Thanks a lott..It worked ..!!!!!!

**Comment by tomscholz** [comment]
Wow... @vivekgautamj That was, well. Fast ;)
