### ISSUE TITLE
icons not showing correctly

### ISSUE THREAD

**Issue by carlosperate** [Dogfalo/materialize#1118]
Looking at the http://materializecss.com/icons.html, the wifi and signal strength icons are not being displayed correctly: 
![icons](https://cloud.githubusercontent.com/assets/4189262/7031884/b33393b0-dd66-11e4-95e8-b26eff7c18b4.png)

I'm seeing the same in firefox and chrome under windows 8.

**Comment by tmd-uk** [comment]
+1 including IE 11.0.9

**Comment by acburst** [comment]
Updated icons 6b626ec06d5e58e3a8e84b61c6ddc4f282d663f2
