### ISSUE TITLE
NPM does not contain source files

### ISSUE THREAD

**Issue by vincentmorneau** [Dogfalo/materialize#1121]
It says that "NPM contains source files as well as the compiled CSS and JavaScript files."

When running `npm install materialize-css` (0.96.1), this is all I've got:

![image](https://cloud.githubusercontent.com/assets/5391291/7038813/4145de2e-dd85-11e4-9bac-68baf17fac78.png)

JS is minified, CSS is not, but there is no source files. 

Could you add the same content as Bower?

Thanks.

**Comment by heyalexej** [comment]
Came here to say the same. 
`^0.96.1` installs without errors (even in debug mode) but isn't complete.
```
$ tree -a node_modules/materialize-css/
node_modules/materialize-css/
├── bin
│   ├── materialize.css
│   └── materialize.js
├── CHANGELOG.md
├── font
│   ├── material-design-icons
│   │   ├── LICENSE.txt
│   │   ├── Material-Design-Icons.eot
│   │   ├── Material-Design-Icons.svg
│   │   ├── Material-Design-Icons.ttf
│   │   ├── Material-Design-Icons.woff
│   │   └── Material-Design-Icons.woff2
│   └── roboto
│       ├── Roboto-Bold.ttf
│       ├── Roboto-Bold.woff
│       ├── Roboto-Bold.woff2
│       ├── Roboto-Light.ttf
│       ├── Roboto-Light.woff
│       ├── Roboto-Light.woff2
│       ├── Roboto-Medium.ttf
│       ├── Roboto-Medium.woff
│       ├── Roboto-Medium.woff2
│       ├── Roboto-Regular.ttf
│       ├── Roboto-Regular.woff
│       ├── Roboto-Regular.woff2
│       ├── Roboto-Thin.ttf
│       ├── Roboto-Thin.woff
│       └── Roboto-Thin.woff2
├── LICENSE
├── package.json
└── README.md

4 directories, 27 files
```
`^0.95.3` crashes like in #964.

```
$ npm --version
2.7.5

$ node --version
v0.12.2
```

**Comment by adrien-louis-r** [comment]
:+1:

**Comment by vincentmorneau** [comment]
An update to the NPM repo would be nice. Does it have to wait until next version?

@adrien-louis-r Any way to fix it temporarily you think?

**Comment by adrien-louis-r** [comment]
@vincentmorneau For now i just use the previous available npm version...
"materialize-css": "~0.95.3".

**Comment by vincentmorneau** [comment]
Bummer...

**Comment by jonjaques** [comment]
A workaround would be to `npm install --save Dogfalo/materialize#v0.96.1`

**Comment by jonjaques** [comment]
@vincentmorneau npm is awesome because you can easily fork repos and then install them from the github repository.

So overcoming a bug in third party code is as simple as Fork, ninja-edit, then install like so:

```
npm install --save jonjaques/materialize#patch-npm-files
```

Then submit a PR! That way when it gets merged you can just change the reference to the published version. That way everyone benefits.

**Comment by nchase** [comment]
looks like this was fixed in 753f7bc (as reported in #1260) :smile_cat:

**Comment by vincentmorneau** [comment]
Good! Can't wait for the next version to be published.

**Comment by digitalkaoz** [comment]
@Dogfalo when will a new release published on npm?

**Comment by Dogfalo** [comment]
See #1583
