### ISSUE TITLE
Select element should fire the onchange event when a new value is chosen

### ISSUE THREAD

**Issue by MelHarbour** [Dogfalo/materialize#1124]
The HTML select element, once modified by the Materialize JS no longer fires its onchange event, as the value of the select is being modified programmatically. To mimic normal browser behaviour, the event should still be fired, but this will have to be done in the javascript, with some sort of call like:

    theSelectElement.onchange();

**Comment by Dogfalo** [comment]
It triggers the change event

**Comment by MelHarbour** [comment]
Strange - when I try and add an event listener for exactly that event, it doesn't get fired. Something like:

    document.querySelector('#mySelectElement').addEventListener('change', function(e) {
        alert("Hello, World");
    });

It works if I don't turn the select into a materialized select, but as soon as I do that, the change event no longer fires.

**Comment by MelHarbour** [comment]
And indeed, your code suggests that the change event should fire. Must be a problem at my end, I guess.

**Comment by Dogfalo** [comment]
It is working in a Meteor app that I am developing

**Comment by MelHarbour** [comment]
Something like this:

http://jsfiddle.net/x8qkwcLc/

Doesn't seem to fire the event.

**Comment by Dogfalo** [comment]
http://jsfiddle.net/x8qkwcLc/1/

**Comment by MelHarbour** [comment]
Nice, thanks!
