### ISSUE TITLE
Feature request: Fullscreen parallax 

### ISSUE THREAD

**Issue by MarhyCZ** [Dogfalo/materialize#1128]
Hi, 
it would be very cool, if you could also make parallax for a fullscreen elements (e.g. background)
Have a nice day :)

**Comment by Dogfalo** [comment]
Parallax already exists and you can change the size of the container.

**Comment by MarhyCZ** [comment]
Yeah :) But if I try to use it with fullscreen height, the image has a very big zoom. Maybe unnecessary. Is there an option to zoom it out, even with reducing a parallax effect?

**Comment by acburst** [comment]
At the moment it really depends on the dimensions and resolution of your image. For a fullscreen image it has to be a very large image for it to not look distorted
