### ISSUE TITLE
Button wave is not fully clear! - Check the image

### ISSUE THREAD

**Issue by ConsoleTVs** [Dogfalo/materialize#1130]
![](http://puu.sh/h6Fcr/1376efcc12.png)

The right corner have a sight line that is not affected by the wave

Chrome, Windows 7

**Comment by acburst** [comment]
This is because we have percent widths and when you resize your browser to a number that doesn't divide well, it will be off by a pixel. 

I dont really know of a good way to stop this from happening if anyone has suggestions.
