### ISSUE TITLE
Links in nav-wrapper disappear with the window diminishing

### ISSUE THREAD

**Issue by chaosink** [Dogfalo/materialize#1132]

**Comment by Dogfalo** [comment]
This is probably as expected. But since you didn't post any code, I have no idea

**Comment by chaosink** [comment]
It seems that when the window dimishes, the logo becomes centered and the links are collapsed into a dropdown list. But I can't see the links any more.

**Comment by Dogfalo** [comment]
Please see CONTRIBUTING.md and create a codepen.
