### ISSUE TITLE
Datepicker modal stuck on left in IE and js errors

### ISSUE THREAD

**Issue by Nimsrules** [Dogfalo/materialize#1136]
I was trying to incorporate the datepicker in one of my designs when I noticed that its modal stuck to left in IE. I checked on your site too where the problem does persist. I've tested in IE9 and IE11. It also gives certain js errors. Kindly check the attachment taken in IE9.
![capture](https://cloud.githubusercontent.com/assets/2740558/7067650/979dd63a-deea-11e4-86ca-fc36690e7762.PNG)

**Comment by carlosperate** [comment]
Materialize only supports IE10+, but it is definitely a problem for 10 and 11.
I thought the issue was resolved (https://github.com/Dogfalo/materialize/issues/948). I guess it must have crawled back somehow.

**Comment by Dogfalo** [comment]
I think the first time I must have forgotten to commit it. But the fix is commited now here: 8588662edf7f137446c57c569047acff90a3327c
