### ISSUE TITLE
Google Maps don't work inside Collapsibles

### ISSUE THREAD

**Issue by rachaelkelly** [Dogfalo/materialize#1137]
When embedding a Google map inside of a Collapsible it displays the entire world instead of the specified region:

![image](https://cloud.githubusercontent.com/assets/10882207/7074788/1c6ab572-def5-11e4-9f27-37a9b06e1588.png)

Outside the collapsible it works perfectly, and if you make a Collapsible active that one will work but the others will not.

**Comment by Dogfalo** [comment]
Please make a code pen for this issue.

**Comment by Dogfalo** [comment]
This is something that you will probably have to tweak to make it work yourself as we do not know how Maps embeds work.
