### ISSUE TITLE
dropdown constained by dimensions of parent 

### ISSUE THREAD

**Issue by abigtoe** [Dogfalo/materialize#1138]
I'm trying to add a dropdown in a card, and noticed that the dropdown size is constrained by the size of it's parent.  
 
![screen shot 2015-04-09 at 4 03 57 pm](https://cloud.githubusercontent.com/assets/4334565/7075845/0ca61d88-ded3-11e4-9859-fce9e8936c6b.png)

This is what happens if the button is on its own
![screen shot 2015-04-09 at 4 04 02 pm](https://cloud.githubusercontent.com/assets/4334565/7075678/e7b674a6-ded1-11e4-8b1a-8b69368e54eb.png)

And when the dropdown is clicked within a card, we only see the 1st option, no scroll
![screen shot 2015-04-09 at 4 04 05 pm](https://cloud.githubusercontent.com/assets/4334565/7075679/e7bb4364-ded1-11e4-801d-b88302fc3032.png)

See:
http://codepen.io/abigtoe/pen/MYMbdV

This is what should happen: 
![screen shot 2015-04-09 at 4 04 21 pm](https://cloud.githubusercontent.com/assets/4334565/7075680/e7bc687a-ded1-11e4-9282-471f9634be43.png)

Found on this site:
http://daemonite.github.io/material/ui-dropdown.html

Not sure if you can fork their code for the dropdown menu, but if you can implement something like this, it'll be yet another reason why your framework is the best out there

**Comment by Dogfalo** [comment]
Well the is an option to solve your first problem. And the second issue is just because cards has overflow hidden

**Comment by abigtoe** [comment]
wow, that was fast! 

I'll try that out. Out of curiosity, why is  overflow:hidden the default option?

**Comment by Dogfalo** [comment]
For card reveals

**Comment by abigtoe** [comment]
Indeed it does. Much appreciated!
