### ISSUE TITLE
Materialize Icons Name

### ISSUE THREAD

**Issue by giovannicoco** [Dogfalo/materialize#1139]
I think the name of the icons is jumping to the left. Take a look:
Eg: mdi-action-credit-card is not right. the right one is "mdi-action-class"
![captura de tela 2015-04-09 as 18 06 26](https://cloud.githubusercontent.com/assets/6585496/7077031/04e7fd3a-dee4-11e4-9098-55067c2547c1.png)

**Comment by Dogfalo** [comment]
Update the font files as well.
