### ISSUE TITLE
Tooltip for touch devices

### ISSUE THREAD

**Issue by kestutis-stalmokas** [Dogfalo/materialize#1141]
Do you have any plans to make tooltips usable on touch devices?
If you are not planning on doing this, would you accept such PR?

**Comment by Dogfalo** [comment]
How would you expect the Tooltip behavior to be on mobile?

**Comment by kestutis-stalmokas** [comment]
It would be nice to have an option (e.x. `data-trigger`) to define how the tooltip will be triggered: click | hover | focus | manual.

In this case click option would trigger tooltip on touch devices when user taps on the element.

What are your thoughts?

**Comment by tmd-uk** [comment]
This is how it looks on mobile device https://vimeo.com/120788406 when the user taps on the element.

**Comment by kestutis-stalmokas** [comment]
Found the bug in my own code, it does work on mobile just the way I expected.
Sorry for the fuss.

**Comment by PhilippSpo** [comment]
I also have the issue, that the tooptip dos not work on mobile. Looking at the code I wonder how a mouseenter event should be triggered by touching on a mobile device?

**Comment by PhilippSpo** [comment]
Wow apparently mouse events get called on mobile. However if you use Meteor's fastclick package they get skipped somehow. So I added the `needsclick` to my tooltip trigger and it is working fine now.

**Comment by gregblass** [comment]
@PhilippSpo I think I'm having fastclick issues too. When I run the app normally in a browser, it works fine, but fullscreen modes on Android/Chrome and iOS/Safari both fail - probably because its falling back to fastclick there? .needsclick didn't seem to fix it for me...

**Comment by blogui91** [comment]
It worked just adding .needsclick, however i am not able to close the tooltip :S  how did you achieve this @PhilippSpo
