### ISSUE TITLE
MaterializeCSS + unCSS - forms not work

### ISSUE THREAD

**Issue by thunderball1** [Dogfalo/materialize#1143]
I tried use unCSS which is really great, but I have no luck using "ignore" option in unCSS for forms. After unCSS remove not used CSS, form inputs stay static - no animation of forms input. How are animations used on forms elements? I cannot achieve it so far. 

Thanks a lot.

**Comment by Dogfalo** [comment]
Forms rely on active classes which are applied on focus. This is probably why unCSS thinks they are unused styles

**Comment by thunderball1** [comment]
I added it to ignore list for unCSS, but it doesn't work. :/

**Comment by Dogfalo** [comment]
This seems like it is more a problem with using unCSS correctly. Try reading over their documentation again. I have not personally used it so I dont know.
