### ISSUE TITLE
How can I make SideNav like an Avatar Collections

### ISSUE THREAD

**Issue by cos800** [Dogfalo/materialize#1144]
I want make the SideNav like an Avatar Collections

make this...
![snip20150411_1](https://cloud.githubusercontent.com/assets/635184/7093579/0ae47d9e-dfed-11e4-9aa8-20f0b01035c4.png)

like this...
![snip20150411_2](https://cloud.githubusercontent.com/assets/635184/7093585/17793540-dfed-11e4-9693-a0a7c6b404c9.png)

**Comment by carlosperate** [comment]
What have you tried to do so far?

**Comment by tmd-uk** [comment]
@cos800 does [this](http://codepen.io/tmd-uk/full/GgVWGG) help?

**Comment by cos800** [comment]
@tmd-uk  thanks
