### ISSUE TITLE
[Enhancement] Card slider

### ISSUE THREAD

**Issue by ianvieira** [Dogfalo/materialize#1146]
Would be great have a card slider built-in, this way you can have many cards in a row and just swap it on mobile. It would be useful for desktop and tablet too, to display lots of content in the same row.

**Comment by TemaSM** [comment]
+1

**Comment by Fonsos** [comment]
+1

**Comment by Lynxiayel** [comment]
+1

**Comment by iquabius** [comment]
+1

**Comment by rohanray** [comment]
+1

**Comment by williamhgough** [comment]
+1

**Comment by Luizgpp** [comment]
+1

**Comment by devisscher** [comment]
+1

**Comment by Luizgpp** [comment]
i'm using owl carousel to create a card slider!

**Comment by iamankits** [comment]
+1 from me too.

**Comment by trostli** [comment]
+1

**Comment by fega** [comment]
Hello, I have some questions about this.
@ianvieira there any examples in the official material design documentation?
Also, I guess that it could be implemented with a little code snippet or a little plugin, @Luizgpp can you show us your solution?

Thanks

**Comment by gideonso** [comment]
@Luizgpp 

Please provide us some example code to show how this can be done.

Thanks.

**Comment by tomscholz** [comment]
Closed due no response. If this is an error, let me know :-)
