### ISSUE TITLE
Slider height when no indicators

### ISSUE THREAD

**Issue by coldKingdom** [Dogfalo/materialize#1148]
The slider adds 40px to the height even if there are no indicators.

**Comment by HenriBeck** [comment]
Replace the Code from line 2886 - 2890 in materialize.js with this code:

if (options.indicators) {
        if (options.height != 400) {
            $this.height(options.height + 40);
            $slider.height(options.height);
        }
      } else if (!options.indicators) {
          if (options.height != 400) {
            $this.height(options.height);
            $slider.height(options.height);
            }
      }

**Comment by acburst** [comment]
Fixed in cac5a09c4ea59d4df72245b9d3cc9a86d52851a6
