### ISSUE TITLE
Close button on searchbar hides entered text

### ISSUE THREAD

**Issue by Dynodzzo** [Dogfalo/materialize#1149]
As you can see on the screeshot below, when the text is long enough to fill the input field, it goes under the close button. It would be better if the input stops before the close button.

![materialize-navbar-search](https://cloud.githubusercontent.com/assets/3044022/7106157/000bab3e-e139-11e4-8a29-6a803cfeade3.PNG)

**Comment by tmd-uk** [comment]
Use this [codepen](http://codepen.io/Dogfalo/pen/xbzPQV) to illustrate your problem.

**Comment by tmd-uk** [comment]
Can you post it in a codepen and I'll try to help.

**Comment by Dynodzzo** [comment]
Here is the codepen : http://codepen.io/anon/pen/LEwyQJ
Thanks for your help.

**Comment by tmd-uk** [comment]
@Dynodzzo I found a simple solution for you bud, [here is my solution](http://codepen.io/tmd-uk/full/KwOqVX). I hope this works for you? I used the maxlength attribute for the search field. @Dogfalo is the an alternative to this at your end?

**Comment by Dynodzzo** [comment]
Yeah i thought of that but it isn't really a solution as it limits the input. It would be nice to be able to enter a many characters as I want and limiting the input width.

**Comment by fega** [comment]
Another solution could be
```
.input-field input[type=search] {
    width: calc(100% - 8rem);
}
.my-input {
    padding-right: 56px;
}
```
