### ISSUE TITLE
Checked animation with lots of checkboxes don't show

### ISSUE THREAD

**Issue by Krazitchek** [Dogfalo/materialize#1150]
I'm not sure, but here what i note on my tests.

I have a page with 100 checkboxes unchecked, in a collection. First time i check (on) a checkbox, there is no animation to show "off" to "on" animation.

I change number of items to show 10, reload. All work fine!
I change again number of items to show 100, reload. No animation from "off" to "on".

I made this test some times (100, 10, 100, 10...) and each time i notice the "no animation" with lots of checkbox on page.

**Comment by Dogfalo** [comment]
http://jsfiddle.net/ak0on6kL/

Seems fine here.
