### ISSUE TITLE
Mobile Collapse Button Issue

### ISSUE THREAD

**Issue by qyouqme** [Dogfalo/materialize#1151]
Mobile Collapse Button has issue on Chrome browser.
See pictures below:

on chrome browser:
![qq 20150413131430](https://cloud.githubusercontent.com/assets/3434960/7110166/5305fa0a-e1df-11e4-8ac2-0044b48ead87.jpg)
![qq 20150413131449](https://cloud.githubusercontent.com/assets/3434960/7110168/57cd06aa-e1df-11e4-8654-970cab6eed2d.jpg)

on firefox browser:
![qq 20150413131513](https://cloud.githubusercontent.com/assets/3434960/7110170/661c60f2-e1df-11e4-90a3-f6c117bf5acb.jpg)
![qq 20150413131530](https://cloud.githubusercontent.com/assets/3434960/7110175/6a0788cc-e1df-11e4-99f9-f1e974a70930.jpg)

**Comment by qyouqme** [comment]
On chrome browser, when click Mobile Collapse Button there just showing the first menu item.But,on other browser show all menu items.

**Comment by Dogfalo** [comment]
What version are you using? This has probably been fixed.
