### ISSUE TITLE
Card Reveal + Materialbox

### ISSUE THREAD

**Issue by SchadLucas** [Dogfalo/materialize#1153]
#825 etc

Will it be supported one day?

Like this

    <div class="card">
        <div class="card-image waves-effect waves-block waves-light">
            <img class="materialboxed" src="$interface$">
        </div>
        <div class="card-content">
            <span class="card-title activator grey-text text-darken-4">Card Title <i class="mdi-navigation-more-vert right"></i></span>
            <p><a href="#">This is a link</a></p>
        </div>
        <div class="card-reveal">
            <span class="card-title grey-text text-darken-4">Card Title <i class="mdi-navigation-close right"></i></span>
            <p>Here is some more information about this product that is only revealed once clicked on.</p>
        </div>
    </div>

**Comment by Dogfalo** [comment]
Next time, comment on the appropriate thread instead of creating a new issue.
Added support in c259fe7615ffafc2e303e5886
