### ISSUE TITLE
Input button overlapping the select form

### ISSUE THREAD

**Issue by victordeassis** [Dogfalo/materialize#1156]
Hi guys! Thank you so much for the amazing latest improvements to the Materialize, it's awesome! I have a problem with a form that the submit button is overlapping the select options, I will upload a photo of the problem. I've tried to use z-index: 1 but I don't know if I used it correctly. Thanks for the support.
![help](https://cloud.githubusercontent.com/assets/6058804/7119722/34f3ce44-e1de-11e4-9b52-8186ff7c04aa.png)

**Comment by HenriBeck** [comment]
you have to set the z-index of the select higher than the z-index from the button

**Comment by victordeassis** [comment]
Hi Henri! Thanks for your help, I've tried to use the code below but it isn't worked. Can tell me please how do I do that?
<code>
button{
      position: relative;
      z-index: 1;
    }

     select{
      position: relative;
      z-index: 999;
    }
</code>

**Comment by victordeassis** [comment]
Ok guys, I got it! :) all I did was set a class for the button and use the CSS below. Thank you for the help and attention!

<code>.botao{ position: absolute;  z-index: auto; } </code>
