### ISSUE TITLE
Sort Table?

### ISSUE THREAD

**Issue by Xtreme89** [Dogfalo/materialize#1159]
Hi,

thanks for the wonderfull framework!

It is possible to integrate tables like bootstrap with function to sort it with a simple click?

http://wenzhixin.net.cn/p/bootstrap-table/docs/examples.html#sort-table

**Comment by linusodenring** [comment]
If you need sorting function fast, I would recommend http://tablesorter.com/docs/ . Maybe add sorting function to future releases?

**Comment by Dogfalo** [comment]
I don't feel this is an important thing for us to include. If you wan't you could make a separate extension similar to bootstrap-table

**Comment by kishorpawar** [comment]
@Dogfalo this may not be important but is really a required feature.
Other extensions/frameworks do work, but mess with UI. 

See below is the tablesorter's materialized theme.
![image](https://user-images.githubusercontent.com/4351835/32210686-11dbdcea-be35-11e7-81cc-c4c6207fccc5.png)

I agree we could customize tablesorter too, but if you provide click events on materialized tables headers it would help a lot.

I would be more than happy to fork and raised PR for the same.
