### ISSUE TITLE
Dropdown on hover does not work properly on firefox 37.0.1 OSX 10.7.5

### ISSUE THREAD

**Issue by danielglez** [Dogfalo/materialize#1163]
On the release v0.96.1, on hover dropdown the dropdown-content close automatically.

**Comment by sophocles7** [comment]
+1

On firefox, with hover and below origin, the dropdown disappears before user can navigate to it. Windows too.

**Comment by cruxiality** [comment]
+1

Same problem as described above. Only when hover is set to true.

**Comment by Alexspriet** [comment]
+1
Same issue!

**Comment by Outpox** [comment]
+1
Same issue here, the button blinks on hover

**Comment by elboman** [comment]
I created a PR for this bug: https://github.com/Dogfalo/materialize/pull/1482

**Comment by rakaaaa** [comment]
I facing the same issue again. Can someone help me.
