### ISSUE TITLE
Datepicker inside bordered table

### ISSUE THREAD

**Issue by grafa** [Dogfalo/materialize#1166]
When I put datepicker inside a `.bordered ` table it goes like 

![image](https://cloud.githubusercontent.com/assets/198654/7155637/905a785e-e360-11e4-8526-ea7f14455359.png)

**Comment by acburst** [comment]
Fixed in c236bfa8e14188418493d0c135c412317a868d51

Also fixed problems with hoverable and striped table classes

**Comment by grafa** [comment]
Well done. Many thanks!
