### ISSUE TITLE
Clicking on an icon in an accordion title doesn't active it

### ISSUE THREAD

**Issue by bobrocke** [Dogfalo/materialize#1170]
If you click anywhere within an accordion's section title, it opens/closes. Except if you click the icon. That's bad as many users will see the icon as the affordance and click that instead of the text, or open space.

**Comment by Dogfalo** [comment]
Works on v0.96.1 on the website

**Comment by bobrocke** [comment]
Thanks! I had missed the update from 0.96 to 0.96.1.
