### ISSUE TITLE
Text color doesn't work with darken/lighten/accent.

### ISSUE THREAD

**Issue by fleeting** [Dogfalo/materialize#1171]
When using something like `teal-text lighten-4` the color is just teal and doesn't follow the lighten. Is this by design?

**Comment by Dogfalo** [comment]
See the documentation, it should be text-lighten-4

**Comment by fleeting** [comment]
Yep, totally overlooked that a dozen times easily. I figured since it was chaining the darken/lighten classes to the `.color-text` it wouldn't need to be prefixed with `text`. Thanks!

**Comment by Dogfalo** [comment]
It is there so that if you also have a blue light 5 background it won't conflict

**Comment by fleeting** [comment]
Totally makes sense.
