### ISSUE TITLE
Easier way to change highlights/colors of components like blockquotes, tabs, etc.

### ISSUE THREAD

**Issue by keyscores** [Dogfalo/materialize#1172]
Am I missing something in the documentation?
I don't see an obvious way of changing the colors of highlights with a selector. Shouldn't this be an optional selector 'color-highlight' or such?

In the example of Tabs, any change I make to the classes will break the javascript, such that I have to initialize each new class that gets created.

I know of the Sass option, but I'd rather not build Sass for every project I work on.

**Comment by Dogfalo** [comment]
I don't really know what you mean that your classes break the javascript or that you have to initialize each class

**Comment by keyscores** [comment]
The script needs the tabs selector. If I change colors I would need to extend each one of these. It would be nice to have an easy way to change highlights, is all I mean. I'm really loving materialize btw :)

**Comment by Dogfalo** [comment]
You can just override the class.
