### ISSUE TITLE
right sideNav

### ISSUE THREAD

**Issue by elabsir** [Dogfalo/materialize#1173]
i put "right" class to sideNav but not work. i need sideNav on right side of screen. i try with this:

class="side-nav  fixed right" 

![css2](https://cloud.githubusercontent.com/assets/251942/7175509/72a6fc54-e42a-11e4-9969-005c136d9658.jpg)

**Comment by elabsir** [comment]
i see this issue: 
https://github.com/Dogfalo/materialize/issues/356

and this commit: 
https://github.com/Dogfalo/materialize/commit/3ba35de70f3291b67681b03ecb50e22d38cb36db

**Comment by Dogfalo** [comment]
See the documentation on how to put it on the right

**Comment by elabsir** [comment]
but i can't found anything about this in documentation: 

http://materializecss.com/side-nav.html

which part of documentation talk about right side sideNav?

**Comment by Dogfalo** [comment]
```
 $('.button-collapse').sideNav({
      menuWidth: 300, // Default is 240
      edge: 'right', // Choose the horizontal origin
      closeOnClick: true // Closes side-nav on <a> clicks, useful for Angular/Meteor
    }
  );
      ```

**Comment by elabsir** [comment]
but i need fixed right sideNav [looks like sideNav on http://materializecss.com/ site]. i need sideNav always show on large device. your solution show sideNav when user click on button collsapse.

![css2](https://cloud.githubusercontent.com/assets/251942/7176924/048c7704-e438-11e4-9703-7c12da673fce.jpg)

**Comment by Dogfalo** [comment]
Just combine it with the section on "Fixed HTML Structure"

**Comment by elabsir** [comment]
your solution not works. after combine these two section of document, sideNav goes to right side of page but buggy. collapse button shows always and if you click on it, sideNav disappeared. 

![1](https://cloud.githubusercontent.com/assets/251942/7208358/839b236a-e555-11e4-90b6-8f816e971d6a.jpg)


![2](https://cloud.githubusercontent.com/assets/251942/7208443/28c1314a-e556-11e4-9ec1-d33570c9f3a8.jpg)

also if script code didn't loaded, sideNav appear on left side of page. please check this pen: 

http://codepen.io/elabsir/pen/bdbwZO

**Comment by smithaitufe** [comment]
Was this issue ever resolved? It's still not closed. What is the current status?
