### ISSUE TITLE
Fixed action btn hover fix

### ISSUE THREAD

**Issue by Justkant** [Dogfalo/materialize#1175]
Hi,

I notice a little problem with the hover on the fixed-action-btn due to a default margin on the ul inside the btn. By simply adding "margin: 0;" into ".fixed-action-btn ul" you can fix the problem.

Thx for this framework.

**Comment by Dogfalo** [comment]
Can you screenshot what problem you are seeing?

**Comment by Justkant** [comment]
![margin-fab](https://cloud.githubusercontent.com/assets/3009753/7250055/439d4410-e81f-11e4-91b3-386af7467671.png)
As you can see, there is a margin on the tag 'ul' and :hover ignores the margin. This causes problems when you move the mouse from the first button toward ul buttons. Sorry my bad english.

**Comment by Dogfalo** [comment]
Fixed in 7145ddc79533ef896bc4f16e85f0859d8e401fc4
