### ISSUE TITLE
Misspelling in materialbox.js (?)

### ISSUE THREAD

**Issue by sirhodes** [Dogfalo/materialize#1177]
The class added to the images when materialbox is initialized is "intialized".

Shouldn't this be "initialized"?

[Reference](https://github.com/sirhodes/materialize/commit/9449881aa00e7aae5348f5590beaaffcaaf89b5c)

**Comment by sirhodes** [comment]
I already put in a pull request with the fix, can remove if that is the way that it is meant to be.

**Comment by Dogfalo** [comment]
Merged #1176
