### ISSUE TITLE
Popout section overlapping select list

### ISSUE THREAD

**Issue by spencer4of6** [Dogfalo/materialize#1179]
There is an issue when using the materialize select input inside of a 'collapsible popout' element:
<br />
![issue01](https://cloud.githubusercontent.com/assets/8053224/7191437/b2b17106-e44a-11e4-88be-fe602241e61d.png)
<br />
Changing the z-indices doesn't help; in fact, if the z-index of the popout elements are less than zero they are unusable. Right now, my solution is to just not use the popout feature, but it'd be nice to have a real solution to this issue:
<br /> 
![issue02](https://cloud.githubusercontent.com/assets/8053224/7191436/b2ae00e8-e44a-11e4-8a9b-0cc19bb20403.png)

**Comment by Dogfalo** [comment]
Can you provide the code for this?

**Comment by Dogfalo** [comment]
Fixed in 0af4142
