### ISSUE TITLE
Dropdown Content with icons: alignment problem

### ISSUE THREAD

**Issue by larikitty** [Dogfalo/materialize#1180]
I have 3 dropdowns and the last one (the one with icons) is not width-constrained or misaligned. You all can check at this [code pen](http://codepen.io/larissa/pen/ByXBgz).

Activation javascript:
```javascript
$(".dropdown-button").dropdown({ hover: false, belowOrigin: true, constrain_width: false, alignment: 'right' });
```

**Comment by acburst** [comment]
Fixed in 0c2377ba9f7303583726a9bb813c7ad577d647fe
