### ISSUE TITLE
Select vs button

### ISSUE THREAD

**Issue by grafa** [Dogfalo/materialize#1181]
Pictures says it all.

Closed (everything OK)
![image](https://cloud.githubusercontent.com/assets/198654/7202420/645f0874-e512-11e4-8722-e9b6b6b66bb9.png)

Opened (wrong z-index...probably)
![image](https://cloud.githubusercontent.com/assets/198654/7202435/83468aaa-e512-11e4-8006-2da54b15719a.png)

Thanks is advance!

**Comment by benjick** [comment]
Having the same problem

**Comment by robin0van0der0v** [comment]
I think this can be fixed with a simple z-index somewhere.

**Comment by benjick** [comment]
```CSS
.select-dropdown {
    z-index: 9999;
}
```

solves it

**Comment by acburst** [comment]
Can you show your code to reproduce this?

**Comment by Dogfalo** [comment]
Fixed in 0af4142

**Comment by grafa** [comment]
Many thanks!
