### ISSUE TITLE
"Select" items doesn't show completely in collapsible-body

### ISSUE THREAD

**Issue by messias-physics** [Dogfalo/materialize#1182]
![screenshot from 2015-04-17 10 02 41](https://cloud.githubusercontent.com/assets/6979335/7202459/eccec070-e4e8-11e4-8a93-b281665b8940.png)

**Comment by HenriBeck** [comment]
@messias-physics 

Just add this to your css file:

.collapsible-body {
overflow: visible;
}

**Comment by Dogfalo** [comment]
Fixed in 0af41425b49f20f67b51c2ba64b42abca0c4c45b
