### ISSUE TITLE
Waves doesn't seem to work

### ISSUE THREAD

**Issue by davepuchyr** [Dogfalo/materialize#1183]
I don't see the wave effect when I click buttons in my web app or on http://gwt-material.appspot.com/.  I tested with Chrome 41, Safari 7.1.3, and Internet Explorer 11.  Other effects do work, eg the animation for onmouseover on a button.  Relevant code is:

&lt;m:MaterialButton text="Button" waves="light" color="blue" /&gt;

Am I missing something?

**Comment by benjick** [comment]
```
<button class="btn blue" data-position="bottom" data-delay="50"><i class="CW3BUMB-g-a mdi-file-file-download right"></i><div class="gwt-Label CW3BUMB-g-b">Download</div></button>
```

I don't see the class `waves-effect`

**Comment by Dogfalo** [comment]
Waves has been tested on many devices and many browsers, this is a problem with your code
