### ISSUE TITLE
Its not a Issue ... Its a WISHLIST for 1.0 ...

### ISSUE THREAD

**Issue by ibrainventures** [Dogfalo/materialize#1184]
Hello Dogfalo - Team,

you made a wonderful job with your materialize css library ... 

For the future there are always some wishes to make something good to something much, much better ..
So it is time for some Wishes for the next Release of your css Lib :-)

Actually there are 

- Timepicker

- Datepicker / Datepicker Range (From -> To Date)

- Chips  
https://material.angularjs.org/#/demo/material.components.chips

- Modals with custom size (width , heigth)

- Subheader (changes content on scrolling)
https://material.angularjs.org/#/demo/material.components.subheader

- Bottomsheet
https://material.angularjs.org/#/demo/material.components.bottomSheet

- Autocomplete
https://material.angularjs.org/#/demo/material.components.autocomplete

These are mine "little" wishes .. Maybe some other persons has also some other ideas, wishes for the next Release ?

Best regards.

J.

**Comment by larikitty** [comment]
Icon Button is a nice add to this library
[https://material.angularjs.org/#/demo/material.components.button](https://material.angularjs.org/#/demo/material.components.button)

**Comment by Dogfalo** [comment]
Most of these already exist as an issue somewhere, instead you should comment on the correlating thread.

**Comment by JimishF** [comment]
Please add an auto-complete buddies.
