### ISSUE TITLE
How to contribute

### ISSUE THREAD

**Issue by achintverma** [Dogfalo/materialize#1185]
Hello, I was planning to build a CSS Framework for material design and I found Materialize. I would love to contribute to this project by adding new components and fixing issues posted by others. Please let me know how can I do this. Here's my linkedin profile: https://www.linkedin.com/in/achintverma.

**Comment by Dogfalo** [comment]
Hey @achintverma, great to hear you want to help! There is a file CONTRIBUTING.md which relates to this.
