### ISSUE TITLE
sideNav problem, does not open

### ISSUE THREAD

**Issue by gnnpls** [Dogfalo/materialize#1186]
Hi guys and congrats for the great work.
I have a problem with the sidenav. I use materialze css with phonegap for android
When content is at top I can open sidenav. But when I scroll down sidenav does not open. Only the screen darkens. This problem appears only in the device not in the browser.

Thanks in advance

**Comment by tankerkiller125** [comment]
If I had to take a guess I would think that this is an issue in the way Phonegap re-writes the code and compiles it.

**Comment by gnnpls** [comment]
The problem is caused by shadow property. I removed it and it is working fine. But there should be some kind of way to make it worth together.
Has anyone had a bug similir to this?

**Comment by Dogfalo** [comment]
What shadow property are you referring to?

**Comment by gnnpls** [comment]
I have tried with all types of box shadow, including rgba ,rgb or hex color combination.If the navbar has box shadow any kind of box shadow, the sidenav opens only at first click. At all other clicks it is just getting darker.
Weird.

**Comment by Dogfalo** [comment]
Not sure what is causing that, but I would double check your code. People have used Materialze before in Phonegap and this issue has not been reported before. In any case, it's good you've fixed your issue.

**Comment by adenta** [comment]
What do you mean when you say 'all types of box-shadow'?

**Comment by gnnpls** [comment]
I am still facing the proble. I have not found a solution. I just don't use the box shadow property.

**Comment by adenta** [comment]
So add, 

*{
Box-shadow:none;

}

To my project?

**Comment by gnnpls** [comment]
This is what I did, because shadow-box was not required for my project.

**Comment by ThunderPaul** [comment]
I have the same problem with sideNav and Phonegap.

Inizializzandola I get this error: Uncaught TypeError: $ (...). Hammer is not a function.

I tried other features such as modals and dropdown and all work.

**Comment by adenta** [comment]
Why are you using hammer? Fastclick seems to be a much more stable solution.

**Comment by ThunderPaul** [comment]
I am a newbie to Phonegap, I'm using hammer because as far as I know is asked to materialize.

How do you advise me to proceed then?

thanks

**Comment by adenta** [comment]
Could you please reword your question? I would love to help!

**Comment by ThunderPaul** [comment]
Thank you for your help.

For now solved scaricado materialize with all files present in separate js https://github.com/Dogfalo/materialize

and loading them separately require js:
<code>
require.config({

	waitSeconds: 0,
    //urlArgs: "bust=" + (new Date()).getTime(),
	paths:{
		'jquery': '../libs/jquery/jquery',
		'hammer': '../libs/hammer/hammer',
		'hammerjs': '../libs/hammer/hammerjs',
		'jquery-hammer': '../libs/hammer/jquery.hammer',
		'fastclick': '../libs/fastclick/fastclick',
		//'materialize': '../libs/materialize/js/materialize',
		'backbone': '../libs/backbone/backbone',
		'underscore': '../libs/underscrore/underscore',
		'text': '../libs/text/text',
		'handlebars': '../libs/handlebars/handlebars',
		'baasbox': '../libs/baasbox/baasbox',
		'baasfunctions': 'functions',
		'router': 'router',
		'templates': '../templates',
		'global': '../libs/materialize-master/js/global',
		'jqeasing': '../libs/materialize-master/js/jquery.easing.1.3',
		'matinit': '../libs/materialize-master/js/init',
		'pushpin': '../libs/materialize-master/js/pushpin',
		'slider': '../libs/materialize-master/js/slider',
		'sidenav': '../libs/materialize-master/js/sideNav',
		'parallax': '../libs/materialize-master/js/parallax',
		'leanModal': '../libs/materialize-master/js/leanModal',
		'scrollSpy':'../libs/materialize-master/js/scrollspy',
		'velocity': '../libs/materialize-master/js/velocity.min',
		'materialform': '../libs/materialize-master/js/forms',
		
	},
	shim:{
		/*'materialize':{
			deps: ['hammerjs', 'jquery-hammer', 'jquery']
		},*/
		'backbone':{
			deps:['underscore', 'jquery']
		},
		'baasfunctions':{
			deps:['baasbox']
		},
		'matinit':{
			deps:['global', 'hammerjs', 'jquery-hammer','jquery', 'jqeasing', 'pushpin', 'slider', 'parallax', 'leanModal', 'scrollSpy', 'sidenav', 'velocity', 'materialform']
		},
	}

});
</code>
