### ISSUE TITLE
Dropdown don't work with Angular ng-include

### ISSUE THREAD

**Issue by amerimi** [Dogfalo/materialize#1187]
Hello,

Any simple dropdown stops working when it's in a separated template included using Angular directives  like ng-include, ng-view, etc...
```html
      <!-- template.html -->
      <!-- Dropdown Trigger -->
      <a class='dropdown-button btn' href='#' data-activates='dropdown1'>Drop Me!</a>

      <!-- Dropdown Structure -->
      <ul id='dropdown1' class='dropdown-content'>
       <li><a href="#!">one</a></li>
       <li><a href="#!">two</a></li>
       <li class="divider"></li>
       <li><a href="#!">three</a></li>
      </ul>
```

```html
    <!-- index.html -->
    <div ng-include src="'template.html'"></div>
```
Thanks in advance for your help

**Comment by sumitkumar1209** [comment]
use angular-materialize http://krescruz.github.io/angular-materialize/#dropdown from https://github.com/krescruz/angular-materialize

**Comment by dhawken** [comment]
Did you activate it?  I am using a dropdown in a directive that does an ng-include and it seems to be working.  I started using the jquery passthrough to do the activations, and needed to provide the options to get it to work in the directive.

**Comment by sumitkumar1209** [comment]
if you use the angular materialize version then there is no need to activate it as it is written in docs that "dropdown" attribute takes care of that.

**Comment by dhawken** [comment]
He was asking about how to use it with straight materialize.  The last time I tried Angular Materialize, there were both a small number of widgets and enough issues with them to warrant figuring out how to make things work with materialize - thought @amerimi might be in the same boat.

**Comment by amerimi** [comment]
```js
$('.dropdown-button').dropdown({
        inDuration: 300,
        outDuration: 225,
        constrain_width: false, // Does not change width of dropdown to that of the activator
        hover: true, // Activate on hover
        gutter: 0, // Spacing from edge
        belowOrigin: false // Displays dropdown below the button
    });
```

I activate it like this and that did not work. Do you do something special to activate the dropdowns?

**Comment by dhawken** [comment]
In theory, that's all it should take, but I'm thinking i had issues with that also.  I have switched everything to the jquery passthrough in the AngularUI Utils and have mine working like this:
```javascript
<a  class='dropdown-button btn--icon right-align' href='#' data-activates='dropdown1'
       ui-jq="dropdown" ui-options="dropDownConfig()"><i class="mdi-navigation-arrow-drop-down"></i>
 </a>
```
With this function in the controller to provide the config to the passthrough:

```javascript
navDropDownConfig = function() {
      return {
        'inDuration': 300,
        'outDuration': 225,
        'constrain_width': false, // Does not change width of dropdown to that of the activator
        'hover': false, // Activate on click
        'alignment': 'left', // Aligns dropdown to left or right edge (works with constrain_width)
        'gutter': 0, // Spacing from edge
        'belowOrigin': false // Displays dropdown below the button
      };
    };
```
Again, I'm not seeing much difference between mine and yours in theory, but that's working for me in an included file.

**Comment by amerimi** [comment]
Thanks a lot that helped.

**Comment by jmls** [comment]
I was wanting to use the passthrough option, but I am struggling with certain controls. For example, I can get the dropdown working, but not the tabs. Are there any plans on the angular front, or are the passthrough options the way to go (and if so, has someone been so kind as to document them ? ;) )
