### ISSUE TITLE
Whoa! 150+ Open Issues!?

### ISSUE THREAD

**Issue by bobrocke** [Dogfalo/materialize#1188]
Is this project losing momentum? There are a lot of open issues and many with little or no response. Trouble and an uncertain future?

**Comment by Dogfalo** [comment]
Well the last commit was only 2 days ago. And we read through every issue and fix whatever is important

**Comment by bobrocke** [comment]
Maybe it's just housekeeping then? Open issues that have been resolved, but not closed?
