### ISSUE TITLE
Add to documentation the next snippet code about dynamic forms character's counter

### ISSUE THREAD

**Issue by jlsalvador** [Dogfalo/materialize#1190]
Add to https://github.com/Dogfalo/materialize/blob/gh-pages/jade/page-contents/forms_content.html information about how to create a dynamic character's counter with the next snippet code, like tabs (http://materializecss.com/tabs.html):

```
$(document).ready(function() {
  $('input[length],textarea[length]').characterCounter();
});
```

**Comment by acburst** [comment]
Added in feb1c5b
