### ISSUE TITLE
ul class right in navbar not working

### ISSUE THREAD

**Issue by gnnpls** [Dogfalo/materialize#1192]
I just updated the new materialize.css verstion and ul class="right" not working in navbar. I have in navbar one element (menu icon) in left, brand logo in center and i want a search button in the right.
But the search icon displays between menu-icon and brand logo.

**Comment by Dogfalo** [comment]
Please make a code pen for this as stated in CONTRIBUTING.md

**Comment by gnnpls** [comment]
Thanks for the help. As I was putting the code in codepen i found out that a class i was using caused the problem.
