### ISSUE TITLE
Truncate on span not working (again)

### ISSUE THREAD

**Issue by Krazitchek** [Dogfalo/materialize#1195]
I'm sorry but adding display: block; on truncate class does not truncate text on span.
Maybe i'm wrong, or i miss something ??
Look at the screenshot.
And with display: block; if i want to truncate label on checkbox, the label is on another line ! (inline-block instead of block ?).

![screenshot-mozilla firefox](https://cloud.githubusercontent.com/assets/11500208/7229892/164ff496-e769-11e4-9151-46f662c427e4.png)

**Comment by Dogfalo** [comment]
This is because there is nothing to truncate as the container is big enough. Also please do no create new issues for the same issue.
