### ISSUE TITLE
select-wrapper is not showing, so the select is totally invisible and unusable

### ISSUE THREAD

**Issue by nanowang** [Dogfalo/materialize#1198]
here's a simple example: http://codepen.io/anon/pen/jPNozE

**Comment by Dogfalo** [comment]
Because you didn't include jQuery

**Comment by nanowang** [comment]
@Dogfalo 

Hi, I'm sorry for not including jQuery in the codepen, but fixing that wont fix the issue itself.

I've update the codepen project: http://codepen.io/anon/pen/jPNozE.

Thanks.

**Comment by Dogfalo** [comment]
Please see documentation on initializing it

http://codepen.io/Dogfalo/pen/jPNjyy

**Comment by nanowang** [comment]
Can't believe just missed that. So sorry for this "issue".
