### ISSUE TITLE
Convention: change font/ to fonts/ (pluralize the font/ directory)

### ISSUE THREAD

**Issue by ejelome** [Dogfalo/materialize#1199]
People coming from `bootstrap` and `foundation` have gotten used to this tree convention / structure:
```
├── img/
├── css/
├── js/
└── fonts/
```

It's a simple change to make other people coming from these css frameworks to remove the issue of tree convention / structure, rather than having another separate `fonts/` directory in case they intermix with `bootstrap` or `foundation` assets.

**Comment by aequasi** [comment]
+1

**Comment by ometra** [comment]
+1

**Comment by Dogfalo** [comment]
Fixed in a1ca0a997efb692a27fcfa85a7cc5277b24c0e57

**Comment by ejelome** [comment]
Awesome! :)
