### ISSUE TITLE
Collapse "side-nav" on click

### ISSUE THREAD

**Issue by robin0van0der0v** [Dogfalo/materialize#1200]
When you click on a link in the ```side-nav```, it doesn't automatically collapse.
I created a single page layout, which uses link like ```#home```.

Is there a way to collapse the navigation drawer, when you click on an ```a``` element in the ```side-nav```?

**Comment by Dogfalo** [comment]
See close on click option in documentation.

**Comment by robin0van0der0v** [comment]
Thanks! Didn't notice it the first time I checked the documentation.
