### ISSUE TITLE
Empty table cells are not rendered.

### ISSUE THREAD

**Issue by hfrid** [Dogfalo/materialize#1201]
If a cell (<td>) is empty, it is not rendered and values from the next cell will appear in the wrong column.

**Comment by 9benm2** [comment]
I think it's fixed by adding &nbsp; in them

**Comment by hfrid** [comment]
That works but it is sort of an ugly workaround..

**Comment by acburst** [comment]
Please give an example codepen of this

**Comment by acburst** [comment]
Due to a lack of response I'm closing this issue. You can remake this issue with a codepen
