### ISSUE TITLE
Table hover and striped, graphical issue

### ISSUE THREAD

**Issue by hfrid** [Dogfalo/materialize#1203]
All table cells seem to have rounded corners which make them look really odd when striped or hovered. Even if the issue is easier to spot when a darker background color is used for the stripe or hover, it can even been seen on the official Materialize page:

http://materializecss.com/table.html

Zoom in on the striped example and you will see what I mean.

I have uploaded an example image here (spot the white spots in the bottom of the blue bar, those appear because of the cells having rounded corners):
![](https://i.imgur.com/zfHp5FN.png)

**Comment by wongalvis** [comment]
https://github.com/Dogfalo/materialize/pull/1240https://github.com/Dogfalo/materialize/pull/1240

**Comment by acburst** [comment]
merged
