### ISSUE TITLE
Responsive table with buttons doesn't size properly

### ISSUE THREAD

**Issue by AndrewCarterUK** [Dogfalo/materialize#1206]
Tested on Chrome and Firefox.

![responsive-table-issue](https://cloud.githubusercontent.com/assets/6486835/7254069/9c9eac66-e838-11e4-9cb0-8f331bbe102b.png)

**Comment by krisDOTco** [comment]
Could you put up a demo for us to look at, please?

**Comment by AndrewCarterUK** [comment]
http://codepen.io/anon/pen/pJoayX

https://gist.github.com/anonymous/3402ad0e041f2740df6c

**Comment by AndrewCarterUK** [comment]
Make the page smaller horizontally until the re flowed mode is triggered and you should see the misalignment,

**Comment by acburst** [comment]
I havent found a way to solve this with any clever css, but an easy fix would be to make the height of your tr and td elements a fixed height that is big enough for the buttons to fit in

**Comment by AndrewCarterUK** [comment]
Is this issue actually closed?

Surely it would be possible to hook the page resize event and use javascript to adjust the cell height?

I'd do a PR but I'm not going to have access to a suitable development environment for a few weeks.
