### ISSUE TITLE
Can not make a proper valign in Card

### ISSUE THREAD

**Issue by kawa-** [Dogfalo/materialize#1210]
Hello, Materialize is really nice.

I'd like to apply valign in the card, but can't :(

Source Code: 

~~~
<!DOCTYPE html>
<html>
    <head>
	<title>Card in Image</title>
	<link type="text/css" rel="stylesheet" href="css/materialize.min.css"  media="screen,projection"/>
	<meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no"/>
	<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/0.96.1/css/materialize.min.css">
    </head>

    <body>
	<div class="container">
	    <!-- ========== Same code (except from http://materializecss.com/media-css.html) starts (only replaced img src) ========== -->
	    <h4>Circular images</h4>
	    <div class="col s12 m8 offset-m2 l6 offset-l3">
		<div class="card-panel grey lighten-5 z-depth-1">
		    <div class="row valign-wrapper">
			<div class="col s4 m2">
			    <img src="http://materializecss.com/images/yuna.jpg" alt="" class="circle responsive-img valign">
			</div>
			<div class="col s8 m10">
			    <span class="black-text">
				This is a square image. Add the "circle" class to it to make it appear circular.
			    </span>
			</div>
		    </div>
		</div>
	    </div>
	    <!-- ========== Same code ended ========== -->
	</div>
	<script type="text/javascript" src="https://code.jquery.com/jquery-2.1.1.min.js"></script>
	<script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/0.96.1/js/materialize.min.js"></script>
    </body>
</html>
~~~

Output in Chrome: 

![2015-04-22 2 51 57](https://cloud.githubusercontent.com/assets/2506824/7258915/95768ba4-e89a-11e4-8e06-5b508c5fb0e5.png)

As you see, the image and text in the card are not in the middle of the card but a little bit upper :( I just want to make like the card with responsive image ( [http://materializecss.com/media-css.html](http://materializecss.com/media-css.html) ). How can I fix it?

**Comment by Holyphoenix** [comment]
Huh, thats weird.  Your code snipped works for me on my machine when I link to the local download of the library.  But it is broken when I use the hotlink to the cdn.  My download is .96.1.  Have there been changes to the cloudflare CDN since I downloaded a couple of days ago that may have broken it?

**Comment by kawa-** [comment]
@Holyphoenix thank you for your testing some environment.

I noticed a mistake.
In the code I pasted, I inserted an invalid line below.

~~~
    <link type="text/css" rel="stylesheet" href="css/materialize.min.css"  media="screen,projection"/>
~~~

Please delete it.

**Comment by Dogfalo** [comment]
See https://github.com/Dogfalo/materialize/issues/1241

**Comment by kawa-** [comment]
Thank you!
