### ISSUE TITLE
Sticky footer not working

### ISSUE THREAD

**Issue by vacquah** [Dogfalo/materialize#1216]
I can't get the sticky footer to work in safari - works in Chrome and Firefox.  I am on safari 7.1.5.  I also cleared my cache just to make sure.

**Comment by krisDOTco** [comment]
Do you have a demo site we can look at?

**Comment by vacquah** [comment]
Can I email it to you? private dev environment.

**Comment by MaiklNW** [comment]
Morning...

Yes. My e-mail - rabbbotnik@gmail.com

**Comment by vacquah** [comment]
Done - sent ....

**Comment by Dogfalo** [comment]
It relies on flexbox, and whether or not it works relies on the browser to support it

**Comment by vacquah** [comment]
Not sure why this is closed. Does this mean the sticky footer solution you have doesn't work in Safari? I am on version 7.1.5.

**Comment by krisDOTco** [comment]
It was closed because it's browser-specific. Alvin noted that if it doesn't, it's due to the browsers' support of it.

Could I suggest looking at the legacy Safari fixes on this page?

https://css-tricks.com/using-flexbox/

**Comment by vacquah** [comment]
I wanted to confirm that this is an issue everyone else using materializecss is facing - i.e. the sticky footer solution doesn't work in safari. I think you should mention it somewhere on your sticky footer page.

**Comment by krisDOTco** [comment]
I definitely would but I'm not a developer on this project. That said, it's not a 'done' thing - did you take a look at the link I sent you previously?

**Comment by vacquah** [comment]
I did - but again, it's not mentioned anywhere in their documentation the sticky footer solution does not work on safari and you have to resort to hacks to make it work. I posted here to check if its working for everyone without any hacks .  Surprised it hasn't come up.

**Comment by vacquah** [comment]
Here is what is said on the website: 

 "Note: This may cause issues in Internet Explorer which has weak support for flex box."

No mention of safari.

**Comment by krisDOTco** [comment]
That's fine, but between you and me right now, you need a solution. You'll find one in that link, I'm sure of it. Let's worry about documentation changes later.

That said, it's somewhat sinister that caniuse.com doesn't agree:

http://caniuse.com/#feat=flexbox

**Comment by Dogfalo** [comment]
I mean it does say you need to add prefixes.

On Mon, Apr 27, 2015 at 10:55 AM, krisDOTco <notifications@github.com>
wrote:

> That's fine, but between you and me right now, you need a solution. You'll
> find one in that link, I'm sure of it. Let's worry about documentation
> changes later.
>
> That said, it's somewhat sinister that caniuse.com doesn't agree:
>
> http://caniuse.com/#feat=flexbox
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Dogfalo/materialize/issues/1216#issuecomment-96685555>
> .
>



-- 
Doggy sends his greetings from Mars.

**Comment by krisDOTco** [comment]
"Supported with prefix: -webkit-."

I am sure that will fix the problem. I've tested it locally and it works for me.

**Comment by vacquah** [comment]
Thanks guys - the webkit prefix works for me.

**Comment by vazamb** [comment]
This is still not working for me
````
body {
  -webkit-display: flex;
  -webkit-flex-direction: column;
  -webkit-min-height: 100vh;
  flex-direction: column;
  display: flex;
  min-height: 100vh;
}

main {
  -webkit-flex: 1 0 auto;
  flex: 1 0 auto;
}
````

What am I missing?

**Comment by vacquah** [comment]
This is what is working for me ( stylus code - jsut rewrite into regular css )

    body 
	display -webkit-box
	display -webkit-flex
	display -ms-flexbox
	display flex
	min-height 100vh
	-webkit-box-orient vertical
	-webkit-box-direction normal
	-webkit-flex-direction column
	    -ms-flex-direction column
	        flex-direction column

    main 
	-webkit-box-flex 1
	-webkit-flex 1 0 auto
	    -ms-flex 1 0 auto
	        flex 1 0 auto

**Comment by vazamb** [comment]
Thank you, did the trick!

**Comment by warrencanning** [comment]
Thank you! :)

**Comment by q45** [comment]
@vacquah this worked great thanks.

**Comment by CharlieIGG** [comment]
Sorry to bring up this old post but I tried the solution @vacquah proposed (along with a couple other similar solutions) and it still doesn't work for me in Safari 9. Here's my markup:

```
body{
  font-family: "Raleway" !important;
  font-weight: 200;
  display: -webkit-box;
  display: -webkit-flex;
  display: -ms-flexbox;
  display: flex;
  min-height: 100vh;
  -webkit-box-orient: vertical;
  -webkit-box-direction: normal;
  -webkit-flex-direction: column;
      -ms-flex-direction: column;
          flex-direction: column;
  background: image-url("mdbg_alt.png");
  background-size: 100vw;
  background-repeat: no-repeat;
  background-attachment: fixed;
  overflow-x: hidden;
  background-color: #fff !important;
  @media (max-width: 769px){
    background-size: auto 100vh;
    }
}
```

```
main {
   -webkit-box-flex: 1;
   -webkit-flex: 1 0 auto;
       -ms-flex: 1 0 auto;
           flex: 1 0 auto;
 }
```

Any ideas?

**Comment by EdrSantandr** [comment]
The solution didn't work as I expected but I get there by a fix in javascript
Adding this line to set up the height of the slider

var h = window.innerHeight;
$('.slider').slider({full_width: true, indicators:false, height:h});

This work without the class  fullscreen of the slider

Hope it works for you
