### ISSUE TITLE
Reduce the massive size of the library?

### ISSUE THREAD

**Issue by dmitriz** [Dogfalo/materialize#1218]
Just downloaded package includes 2MB fonts, 
which can be a performance drag for my site.

Can I use it with standard web safe fonts to avoid the additional load?

**Comment by Neotrixsx** [comment]
Yes, I have also removed extra stuff from my fonts folder. I use only in Material-design-icon.ttf in material-design-icon folder and in Roboto folder I use only Roboto-Regular.ttf, Roboto-Regular.wolff, Roboto-Regular.woff2 only. My application works fine.

**Comment by dmitriz** [comment]
They still take up 200K space and how do you know removing the rest will work in the future?

**Comment by Neotrixsx** [comment]
But I think it takes less than 2 MB and now it's working fine in my application and website.

**Comment by dmitriz** [comment]
How does this guarantee that it will work with other websites?

- Dmitri

**Comment by Neotrixsx** [comment]
In my experience, there should not be any fall back or any problem in future

**Comment by dmitriz** [comment]
Then why are the other fonts included?

- Dmitri

**Comment by Neotrixsx** [comment]
For custom font, we generally get from other blogs not creating our own custom fonts.
Generally a full bundle with different fonts we get. So user can have the option to go through different fonts and select the necessity one.

**Comment by abhigyan2311** [comment]
I think different fonts are provided for different browser supports, so
that browser can pick the desired font...

**Comment by dmitriz** [comment]
This is from `materialize.css`: 

<pre>
@font-face {
  font-family: "Roboto";
  src: url("../font/roboto/Roboto-Thin.woff2") format("woff2"), url("../font/roboto/Roboto-Thin.woff") format("woff"), url("../font/roboto/Roboto-Thin.ttf") format("truetype");
  font-weight: 200; }
</pre>

So it is *not correct* that other fonts are not used and my question remains.

**Comment by Neotrixsx** [comment]
I tested my website using the firebug plugin it not show me any error.

**Comment by Dogfalo** [comment]
They are for browser fallback as @abhigyan2311 said. If you use Inspector Tools and monitor network it only downloads one file type.

**Comment by Dogfalo** [comment]
Futhermore, if you feel this is not acceptable, simple delete the @fontface so it does not import any fonts.

**Comment by Neotrixsx** [comment]
@ Dogfalo +1

**Comment by krisDOTco** [comment]
I have a suggestion if the font files are bothering you. Roboto is available through Google Webfonts, it's all hosted on their CDN so all you need to do is import it.

http://www.google.com/fonts#UsePlace:use/Collection:Roboto

**Comment by Dogfalo** [comment]
Well that is the old Roboto not Roboto 2.0

**Comment by dmitriz** [comment]
I have disabled `Roboto` in favour of standard `sans-serif` and it actually looks better and more readable, with more space to breath between characters, whereas `Roboto` has a "crowded" appearance (to me) - harder to distinguish the characters:

http://materializecss.com/pushpin.html

No offence taken - your design **is** very impressive!

But I (and other users) would appreciate to have the freedom to use the standard fonts without breaking things. I don't mean they break now - in fact they don't as far as I could see :-). It is the fact that **this "non-breaking" is not documented** is what is a point of concern.

There is a lot of benefits to make the fonts *optional* and *replaceable*:

- Less folders to carry with the codebase, to backup, maintain, update, version ...
- Less footprint - easier and faster to down- and upload on slow connections, for anyone working on the road to quickly pull the last changes...
- Less points of failure, should they drop their support for the fonts (and Google has the reputation of someone known to drop support for many products!)...
- More performance headache for production - caching, fallbacks...


Also please consider having more folks evaluating your font's usability, forums such as 
http://ux.stackexchange.com/ 
and 
http://graphicdesign.stackexchange.com/ 
can do great!

**Comment by DaEckster** [comment]
The docs would get quite large if every little possible change you potentially could do were added to them, although maybe a sort of wiki page or something for these kinds of things would be nice in the future, to at least have a central source for this little stuff while keeping the main docs clean.

Also, Roboto is used because it is the font of choice for Material design:
http://www.google.com/design/spec/style/typography.html

**Comment by getupkid203** [comment]
If ur unaware of the different font types that different browsers support then i feel u should start researching that before raising an issue.

**Comment by getupkid203** [comment]
This is why there are a few different font types http://www.stunningcss3.com/resources/fontface-file-types-browser-support.html

**Comment by dmitriz** [comment]
http://motherfuckingwebsite.com/ 
(No offense!)

**Comment by Dogfalo** [comment]
We will remove the material icons soon, since they have been deprecated for
a few releases already.

On Sun, Jan 3, 2016 at 1:37 AM, Dmitri Zaitsev <notifications@github.com>
wrote:

> http://motherfuckingwebsite.com/
> (No offense!)
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Dogfalo/materialize/issues/1218#issuecomment-168481518>
> .
>



-- 
Doggy sends his greetings from Mars.
