### ISSUE TITLE
Parallax (in any iteration - the demo and sample templates) does not work

### ISSUE THREAD

**Issue by krisDOTco** [Dogfalo/materialize#1219]
http://materializecss.com/parallax-demo.html

Parallax is either conflicting with something or being told not to run. Any ideas, guys?

**Comment by Dogfalo** [comment]
What browser are you using?

**Comment by krisDOTco** [comment]
Google Chrome, 42.0.2311.90 (latest up to date version).

**Comment by krisDOTco** [comment]
Fixed itself, 95% sure it was a caching issue. The console was getting in a strop with me about something, so I wiped the cache and started again. Appears to work now!
