### ISSUE TITLE
Icon picker???

### ISSUE THREAD

**Issue by lukaspijak** [Dogfalo/materialize#1221]
.

**Comment by Dogfalo** [comment]
Don't really know what this means. Please see CONTRUBUTING.md and revise your issue accordingly before this is reopened.

**Comment by lukaspijak** [comment]
Sorry. I mean like this plugin for bootstrap http://victor-valencia.github.io/bootstrap-iconpicker/

**Comment by Dogfalo** [comment]
Thank you for clarifying, but I don't think this is something we will add as it is very specific
