### ISSUE TITLE
Allow Form Switch to be an input with type 'radio', not just 'checkbox'

### ISSUE THREAD

**Issue by byrnedo** [Dogfalo/materialize#1222]
When I change the type of a switch to be a radio, the animation on the switch toggle no longer works.

Would be good to have the switch allow the input to be a radio.

Example usage:

```
<div class="switch">
     <label>
         Off
         <input name="my-radio-group" type="radio">
         <span class="lever"></span>
         On
     </label>
 </div>
```

**Comment by Dogfalo** [comment]
I suppose it can be added, but I don't think that it makes sense for a switch to act as a radio button. Similar to flipping a light switch, you wouldn't expect that it turns off the other switches.

**Comment by byrnedo** [comment]
The use case I have is a form builder, when creating a radio group you can set the individual option to be 'checked' by default.

I know I could use a regular radio for this but the switches look good I think.

![screenshot from 2015-04-23 15 18 17](https://cloud.githubusercontent.com/assets/5528491/7297896/335951f8-e9cc-11e4-82a6-c481f935482b.png)
