### ISSUE TITLE
Datepicker bug when launched from modal

### ISSUE THREAD

**Issue by AndrewCarterUK** [Dogfalo/materialize#1223]
When launching the datepicker from within the modal (quite common as lots of people place forms in a modal) the datepicker is clipped by the bounding modal and in many scenarios becomes unusable.

I've attached a codepen to demonstrate, tested on Firefox and Chrome on Linux Mint. 

http://codepen.io/anon/pen/RPwJvY

Thanks :)

**Comment by acburst** [comment]
Duplicate #1032
