### ISSUE TITLE
Typo on Portuguese translation in Getting Started page

### ISSUE THREAD

**Issue by forsureitsme** [Dogfalo/materialize#1225]
In [getting started page](http://materializecss.com/getting-started.html):

`<h4>Compilando Saas</h4>`
should be
`<h4>Compilando Sass</h4>`

I was going to PR this, but couldn't find my way through the code.

**Comment by DaEckster** [comment]
Are the translations even contained in the source? I went to fix this and couldn't find translations anywhere.

**Comment by Dogfalo** [comment]
Translations are held in a 3rd party service. I can probably fix this manually when I get around to it. Either that or one of our Portuguese translators will.

**Comment by DanilsonVeloso** [comment]
How I can to contributbe with the translation for Portuguese?

**Comment by vishnu1991** [comment]
Hello @DanilsonVeloso 
You can contribute for translation at Transifex.
https://www.transifex.com/materialize/materialize/

**Comment by kmmbvnr** [comment]
The typo still not fixed yet

![screenshot from 2016-11-23 16-57-52](https://cloud.githubusercontent.com/assets/282529/20559316/0c1d103e-b19e-11e6-94cf-52688c875d9a.png)
