### ISSUE TITLE
Icons and Text in SideNav overlap (broken in 0.96.1 but worked in 0.95.3)

### ISSUE THREAD

**Issue by derwok** [Dogfalo/materialize#1226]
I'm using Materialize with Meteor - and like the combination very much. Thanks for your hard work! 

Unfortunately Materialize 0.96.1 introduced a problem with Icons and text in a SideNav... This codepen illustrates the problem when you shrink the width of the browser window, so that you can open the **sidebar nav via the hamburger icon**:
       http://codepen.io/derwok/pen/bdGzwm
Icons and text overlap (text is always one line below the icon).

With Materialize 0.96.1 it is broken:
![materialize_broken](https://cloud.githubusercontent.com/assets/4393698/7313399/33a7213e-ea59-11e4-9ab7-77c4306cda56.png)

When I pin my meteor project to 0.95.3 with:

```
meteor add materialize:materialize@=0.95.3
```

then it looks OK, again:
![materialize_ok](https://cloud.githubusercontent.com/assets/4393698/7313404/3aeee5e4-ea59-11e4-8bb0-dc46d20ef90e.png)

**Comment by fjsuarez** [comment]
Still having this problem as of release of 0.97.

**Comment by mateeyow** [comment]
I wonder why this hasn't been fixed yet. Any work-around on this?

**Comment by nigelpasco** [comment]
I did tried using a collection with image attached as secondary content in the sidenav... didn't work :( Would be good to see this fixed in an update please :P
