### ISSUE TITLE
More than one sidenavs

### ISSUE THREAD

**Issue by akyunus** [Dogfalo/materialize#1228]
When i add two or more sidenavs with closeonclick option true, only the last activated sidenavs works properly. Here is my test page http://ak.gen.tr/xtra/bm/index.html 

Right sidenav activated with user icon. Often It doesnt close when i click on page body.

**Comment by imjoeybrennan** [comment]
+1

**Comment by imjoeybrennan** [comment]
+ 1

**Comment by imjoeybrennan** [comment]
Problem is your clicking the other nav's drag-target. It happens on all screen sizes. This guy has a fix. 
#1417

Also if you don't care about dragging open the nav you can just overwrite the css for the sidenav-overlay to increase its z-index to 998.
