### ISSUE TITLE
Selects with Angular and Materialize

### ISSUE THREAD

**Issue by SpencerLynn** [Dogfalo/materialize#1231]
When setting up a select element and using Angular to bind options (ng-options) and selected item (ng-model), the selected value is not populated when an item in the select is chosen.

Here is the HTML:
```
<div class="input-field">
  <select ng-model="gameCtrl.selectedCourse" ng-options="course.name for course in gameCtrl.allCourses">
    <option value="">Choose a Course</option>
  </select>
</div>
```

My model has a field named `selectedCourse` that is initialized to null.

If I apply the `browser-default` class to the select, angular binding has no issues.

**Comment by Dogfalo** [comment]
There are a few closed issues on this already. Take a look at those. I can always reopen this if those don't help.
