### ISSUE TITLE
Autocomplete on text inputs

### ISSUE THREAD

**Issue by Djuka** [Dogfalo/materialize#1233]
I was wondering if there is a way to initalize autocomplete on text inputs using materialize dropdown so that it would only show up on changes in that text input? If not I really think this feature should be added. It's really usefull and needed. Right? Thou I needed it for my individual goal, I think this is some basic behavior in forms and a lot of UI libraries have it, so it should be a viable feature. This is something I would like to contribute to.

**Comment by acburst** [comment]
We feel that this is slightly too complex and niche to be in a general css framework. There are many plugins that do this already that you can look into

**Comment by marciosouzajunior** [comment]
Could you suggest a plugin that works well with materialize?

**Comment by avspeed** [comment]
I have not tried it, but this posts suggest uing typeahead.js https://gist.github.com/dogrocker/20c255a7919d7033f73d
