### ISSUE TITLE
Move all initialization functions into a single function

### ISSUE THREAD

**Issue by Ecksters** [Dogfalo/materialize#1236]
Since future plans are to improve compatibility with Meteor and Angular, I propose that a master initialization function be created in the materialize.js file to resolve issues with $(document).ready firing before templates have been injected into the DOM.

This would make resolving issues such as #822 much simpler, since rather than needing to call all the internal functions that would have been used or pre-add classes to your inputs and other elements, you could simply call the single function to run the initialization functions once the framework is ready.

**Comment by qwIvan** [comment]
+1

**Comment by rubyboy** [comment]
+1

**Comment by kmmbvnr** [comment]
Duplicate #915

**Comment by tomscholz** [comment]
Please close ;)
