### ISSUE TITLE
SideNav doesn't display if page is loaded in transition zone

### ISSUE THREAD

**Issue by visioninit** [Dogfalo/materialize#1237]
Tested in Firefox and Chrome

Set browser display width to 979px (no zoom)
Open http://materializecss.com/ 

![screenshot from 2015-04-24 18 11 31](https://cloud.githubusercontent.com/assets/654993/7330877/5cae5986-eaad-11e4-8384-1f565f1bda39.png)

First discovered this on a site I'm working on.

**Comment by Dogfalo** [comment]
Hmm I tested this and seems to work on Chrome for me.

**Comment by visioninit** [comment]
The width I gave may be incorrect.  Double checking in Chrome

**Comment by visioninit** [comment]
![screenshot from 2015-04-24 21 52 26](https://cloud.githubusercontent.com/assets/654993/7331616/36958840-eacc-11e4-8ccc-4f0154666b1e.png)

**Comment by visioninit** [comment]
Looks like it is 979px.  Would have to look a bit more to see why I had the other number earlier.  The way to reproduce it though is to resize the browser window just to the point where it changes from having the sidenav to not having it.  Then scroll back just to the point where the sidenav appears again and refresh the page.  

![screenshot from 2015-04-24 21 54 22](https://cloud.githubusercontent.com/assets/654993/7331624/7cc11f3c-eacc-11e4-908d-1595261ef41c.png)

**Comment by visioninit** [comment]
![screenshot from 2015-04-24 21 59 12](https://cloud.githubusercontent.com/assets/654993/7331640/2aea12c6-eacd-11e4-8f88-e1dc1ba4ea2f.png)

**Comment by Ba5ik7** [comment]
Works fine here

**Comment by Ba5ik7** [comment]
![979](https://cloud.githubusercontent.com/assets/647887/7332581/8ee2b210-eb13-11e4-873c-8d71d8a478af.png)

**Comment by visioninit** [comment]
Just to verify, you are setting the browser width, and then opening the page?  Because if you open the page first and resize the browser to that width, it would work.

**Comment by visioninit** [comment]
Attached a video here https://drive.google.com/file/d/0B0UbPobqrsXoMjNfMjJvYXdHbzA/view

**Comment by Ba5ik7** [comment]
Edge Case

**Comment by visioninit** [comment]
Here is some more debugging info recorded in video.  https://drive.google.com/file/d/0B0UbPobqrsXoTXhsVk5QWExuVXc/view?usp=sharing

What it shows:

Issue is related to $(".button-collapse").sideNav();

adding $(window).trigger('resize'); in the page load js is a workaround

**Comment by visioninit** [comment]
I am going to work on a fix for this.  Consider it assigned to me.  ETA is Wednesday / Thursday April 29th/30th.  

For a quick workaround for materializecss.com - If you add the $(window).trigger('resize'); at the end of the javascript that runs onload, users wouldn't experience the issue.

**Comment by akyunus** [comment]
its happening to me when window.innerwidth is in 978 - 992 pixels. When the my browser window width is 992px window innerWidth is 978. So some how its checking window width. I found a condition on line 1876 at materialize.js file. Its loking for window width not window.innerWidth like on line 1884. Check that.

**Comment by visioninit** [comment]
Thanks @akyunus .  

Is this what you were looking at? 

Linking to the source js file that is used in the build of materialize.js:

https://github.com/Dogfalo/materialize/blob/master/js/sideNav.js#L76-L104

I did try running the output in the console for  "menu_id.css('left', 0);" (with menu_id) replaced to match my local menu_id, and that popped out the menu.  So I think we are on the right track and just need to make sure that the range from 978-992 is handled.

**Comment by visioninit** [comment]
Will try out the innerWidth and see if that helps get things going.

**Comment by akyunus** [comment]
i tried thats works for me :)

**Comment by akyunus** [comment]
I am new on github. and im not used to work collective. no idea about where to look and how to change on source. I just work local with dist files.

**Comment by visioninit** [comment]
It looks like you are picking it up pretty quick. :+1: 

When you said it worked for you, did you mean changing the window width to look at the inner width fixed it?  Or that you entered the menu_id.css('left',0) and it worked?

For changing it in the source you would have need to look at https://github.com/Dogfalo/materialize/blob/master/CONTRIBUTING.md which shows that grunt (a build tool) reads in the different source files and compiles (concatenates, makes minimal versions, processes SASS, etc)  into the files that we include to access the framework.

**Comment by Dogfalo** [comment]
@akyunus https://github.com/Dogfalo/materialize/blob/master/CONTRIBUTING.md

**Comment by akyunus** [comment]
Im sorry there was a misunderstanding i think. 
I dont read all you wrote. I see what you discovered. I check my local project and materializecss.com. I was using fixed sidenav so I see that a fixed sideNav doesnt display on mysterious pixel width. 
As you see on sideNav.js#L76-L104 when risizing everything is fine because "if condition" comparing innerWidth. as css media rules checks witdh of html element. When first bring menu out if condition checks the window.width. I dont read all code. i just change that "if condition" to compare innerwith.
From now on you can be sure that i'll keep the rules

**Comment by visioninit** [comment]
You are alright @akyunus, thanks for explaining.  Let me be the first to welcome you to github and contributing.  

I'll test out what you tired later on after I get some other things taken care of!  Thanks, it is very helpful.

**Comment by Dogfalo** [comment]
Fixed in 27a1051.

Thanks @visioninit and @akyunus for the help!
