### ISSUE TITLE
Radio Box Issue

### ISSUE THREAD

**Issue by hassan-ahmed** [Dogfalo/materialize#1242]
Radio boxes' checked attributes aren't being updated.

Any workaround for this ?

**Comment by Dogfalo** [comment]
This is not how radio buttons work.

From W3C Documentation,

"The checked content attribute is a boolean attribute that gives the *default* checkedness of the input element."

The DOM attribute is the one that changes

http://stackoverflow.com/questions/4882000/why-clicking-on-checkbox-does-not-add-the-attribute-checked-checked

**Comment by hassan-ahmed** [comment]
Oh, thanks for the correction.
