### ISSUE TITLE
Navigation in sidebar gets pushed into footer because of ad

### ISSUE THREAD

**Issue by augbog** [Dogfalo/materialize#1243]
![image](https://cloud.githubusercontent.com/assets/2054339/7334715/99846ae2-eb4f-11e4-95fb-56c7553ee827.png)

Notice to the right, the links get pushed into the footer. If this was intentional, feel free to close. Ideally, there should be a way to stop the sidebar from bleeding into the footer.

**Comment by kmmbvnr** [comment]
Seems fixed.

Pushpin now has the `bottom` option

![pushpin materialize](https://cloud.githubusercontent.com/assets/282529/20560058/a47d3770-b1a1-11e6-8d5a-10531695032e.png)

**Comment by augbog** [comment]
Yup looks good :) Thanks! Closing.
