### ISSUE TITLE
First slider not showing up initially

### ISSUE THREAD

**Issue by vacquah** [Dogfalo/materialize#1244]
The first slide in the slider is always blank, right after the page with the slider loads.  The first page show up only after the slider has cycled through the other pages.

**Comment by Dogfalo** [comment]
Could be a result of the error in the JS console that I am seeing on your page.

**Comment by vacquah** [comment]
the one related to pagepiling?  It still occurs without it. i can remove the page piling plugin and you can check it out again. It also happened on another build i had with materializecss

**Comment by Dogfalo** [comment]
It seems it is a problem with opacity: 0 on the .caption inside the first slide. Not sure right now if this is just a problem on your site or in Materialize.

**Comment by vacquah** [comment]
I haven't set any opacity rules at all in my css for the slider

**Comment by vacquah** [comment]
By the way. it also happens on another slider here - http://dev.enio.solar   scroll down to two sections below the top

**Comment by vitesh-youreka** [comment]
My slider does not work too :( However when I run the plugin code in my console it works fine. Without that I am getting a grey screen.

**Comment by Champa720** [comment]
Not sure what I did, slider was working? Now the first slide does not show caption on-load. No errors in console and js is triggered but not completed? I do not see velocity-animating until first transition...

On load first slide does not show caption, no velocity-animating changing values:

```html
<li class="active" style="opacity: 1;">
    <div class="caption center-align" style="opacity: 0; transform: translateY(-100px);">
    </div>
</li>
```

After slide cycle has begun, I can see velocity-animating changing values, and the slide caption drops in, on all slides:

```html
<li class="active" style="opacity: 1; transform: translateX(0px) translateY(0px);">
    <div class="caption center-align" style="opacity: 1; transform: translateY(0px) translateX(0px);">
</li>
```

**Comment by simicic** [comment]
I had the same issue, I tried to use slider without images and whenever the slider loads it does not immediately show the content of the first slide. 
It works with adding an empty img tag.

**Comment by ibart** [comment]
still affected.

**Comment by dmallory42** [comment]
This is still an issue - as others have said, adding an empty <img> tag fixes it, but this is not really an ideal solution. Are there any updates on a fix?

**Comment by clstia** [comment]
I also encountered this issue. Adding the empty <img> tag fixed it.

**Comment by thebiltheory** [comment]
Did anyone found a more elegant solution to this? 
(cc @Dogfalo )

**Comment by ndunks** [comment]
I got some problem and its wasting my time to find the problem. I fix problem by replacing materialize.js from /bin/ folder! try and tell me if resolved.
