### ISSUE TITLE
tool tip for pre disabled button doesn't removed 

### ISSUE THREAD

**Issue by baraamashaal** [Dogfalo/materialize#1246]

**Comment by Dogfalo** [comment]
Please be more descriptive and make a code pen

**Comment by baraamashaal** [comment]
okay :) 
so when u have tooltiped button and when u hover it the usual thing that is the tooltip appears 
but for some reason you may need to disable the button after clicking it and
when you do that the tooltip stayed and its doesn't removed
codepen :
http://codepen.io/baraamashaal/pen/xGbPBa

**Comment by Dogfalo** [comment]
Once you disabled something it no longer receives events. Take a look at my fix here.

http://codepen.io/Dogfalo/pen/EjjVaZ

**Comment by baraamashaal** [comment]
i got it thx man :D
