### ISSUE TITLE
Materialized bug

### ISSUE THREAD

**Issue by yask123** [Dogfalo/materialize#1247]
I have made 2 columns by grid layout system. And in their I placed image-cards , images with class materialize. 
But on clicking it the image doesn't appear in full but instead get cropped inappropriately .
![screen shot 2015-04-27 at 1 16 27 am](https://cloud.githubusercontent.com/assets/1812021/7338964/66d2d1c4-ec7b-11e4-9008-6c776af87d38.png)
![screen shot 2015-04-27 at 1 16 20 am](https://cloud.githubusercontent.com/assets/1812021/7338966/6d8db6d2-ec7b-11e4-9085-5b89c18e9536.png)

**Comment by Dogfalo** [comment]
Please take a look at closed issues or existing examples on the Materialize documentation site.

**Comment by yask123** [comment]
I have looked into it , I can't understand the issue.
The Material Box works fine in a simple page but this is how it is working when I applied Material Box inside a card. Strange..

**Comment by Dogfalo** [comment]
Just remove overflow:hidden
