### ISSUE TITLE
Date Picker: year selector should appear before the month selector 

### ISSUE THREAD

**Issue by boustanihani** [Dogfalo/materialize#1248]
Consider: http://amsul.ca/pickadate.js/date/#selectors

**When `selectYears` is truthy, the year selector should appear before the month selector.**

Check: https://github.com/amsul/pickadate.js/issues/384

**Comment by Dogfalo** [comment]
What do you mean should? This is a restyle so I don't see why the order matters?

**Comment by boustanihani** [comment]
Suppose you want to allow ages >= 18 and ask the user to input their birthday:
```
var minAge = 18;
var maxAge = 80;

$('.datepicker').pickadate({
    format: 'dd.mm.yyyy',
    selectYears: maxAge - minAge,
    selectMonths: true,
    max: -365 * minAge,
});
```

It is confusing because if a user tries to select his month first he may not be able to because some month maybe disabled... By positioning the year selector to the left this usually means that the year should be selected first and after that the month chosen.

**Comment by Willibaur** [comment]
Hi all,
is there any update about this issue, I've read the API Docs about changing positions between months and years with no success, placing `selectYears: true` before `selectMonths` but it does not work,
Thanks you very much

**Comment by animeshsinghweb** [comment]
any update yet?

**Comment by animeshsinghweb** [comment]
I did a little tweak on CSS which worked for me.
```
.picker__select--month.browser-default {
    float: right;
    margin-right: 2em;
}
```
**Here is a live demo: ** http://jsbin.com/darewal/edit?css,output
---
### Note
If the page is having more than one pickadate.js it would make the whole thing to appear like this, so if you want only a specific pickadate to look like this, then you need can define another class for selectMonth and selectYear using [klass](http://amsul.ca/pickadate.js/date/#classes) while initialising pickadate, and use that class in css to change. 👍

**Comment by Dogfalo** [comment]
An option for this has been added in 1.0
