### ISSUE TITLE
card-image stretches image, possibility for inline-block card?

### ISSUE THREAD

**Issue by humbleRumble** [Dogfalo/materialize#1249]
Working on converting my site from bootstrap to materialize, just a couple of things i would like.

1). A card-inline class for card elements to make it display:inline-block and leave the image sizing alone.
2). The card reveal "title" becomes constricted in width. 
3). A class to auto-show side-nav on large screens? (yes i realize that you can show the button on large screens)
4). A class to remove shadows from buttons (or conversely remove the shadows and just tell the user to add z-depth-1 to the button if they want a shadow)
5). maybe tone down the z-index classes a bit, it would be nice to have a little in between in there.

Love the framework. Keep up the good work.

**Comment by humbleRumble** [comment]
These are the classes I cam up with, really ugly code in my opinion. I think the user should add responsive-img class to the image if they want it to be responsive, otherwise don't touch it.
<pre>.card-inline {
    display: inline-block;
}
.card-inline .card-image img {
    position: initial!important;
    top: initial!important;
    left: initial!important;
    right: initial!important;
    bottom: initial!important;
    width: initial!important;
}
.card-inline.small .card-content {
    height: initial!important;
}</pre>


And I just thought I would let you know about these methods of centering works every time, centers perfectly, and you dont need a wrapper
<pre>.hcenter {
    position: relative;
    left: 50%;
    transform: translateX(-50%);
}
.vcenter {
    position: relative;
    top: 50%;
    transform: translateY(-50%);
}
.bcenter {
    position: relative;
    top: 50%;
    left: 50%;
    transform: translateY(-50%);
    transform: translateX(-50%);
}</pre>

**Comment by humbleRumble** [comment]
This framework needs to set less default settings, once I got to three `all: inital` statements i just wrote my own. its cool to have all of those settings easy to get to, but having to reset a whole class just to style it the way that I want gets old quick.

**Comment by acburst** [comment]
Can you give an example for when card-image stretches an image?

Also there already is a way to remove shadows from elements. Just add the class ```.z-depth-0```

**Comment by humbleRumble** [comment]
card-image sets the image width to 100%, if the card is wider than the image it stretches. As far as shadows go I got the z-depth-0 part, my real issue with this is that there should be no default shadows. The user should have to set the shadows they want rather than having to unset shadows on everything. It's all good I'm not using this anyways for the reasons stated in my last comment. The framework that I ended up writing basically just divides all of the settings into the "do one thing and do that thing well" diatribe, so my html seems like its full of classes but 1). you can see by looking at the markup what each setting applied to that element is, and 2). there are no defaults for anything. Everything gets set by the user, which is a lot easier than unsetting all of the defaults to be able to customize.

**Comment by fega** [comment]
Closed due inactivity
