### ISSUE TITLE
<select> not displaying correctly on a card

### ISSUE THREAD

**Issue by harrysonguimaraes** [Dogfalo/materialize#1250]
![captura de tela 2015-04-26 as 21 38 03](https://cloud.githubusercontent.com/assets/5912680/7340136/ab23c474-ec5c-11e4-9b90-d11f3aa4be05.png)

I have a form inside a card and my `<select>` element is getting overlayed at the end of the card.
I have an 4th option not being displayed. I've tested on v0.95 and it is working correctly. The problem came in the version 0.96. Any suggestion to get it working?

**Comment by Dogfalo** [comment]
Remove overflow:hidden from the card, this has been fixed for the next release also
