### ISSUE TITLE
Fullscreen youtube video in modal disappears

### ISSUE THREAD

**Issue by wislem** [Dogfalo/materialize#1253]
Having a youtube video inside a modal and going full screen shows website with modal overlay. Video is gone!

Happens in Chrome but not in Firefox.

[Codepen](https://gist.github.com/anonymous/c1fe90f1e0b1e67b25ac)

**Comment by acroix** [comment]
Same problem here, can you please tell me if you find a trick ?

Thanks

**Comment by jsduffy** [comment]
Same issue here.... any fix?

**Comment by davidrichey** [comment]
+1 any solutions to this?

**Comment by jrioromero** [comment]
Same issue here, even if I include the iframe directly into the modal wrapper, removing the modal-content and the modal-footer.

**Comment by rickshawhobo** [comment]
+1 has there been a solution to this

**Comment by Austin-Stephens** [comment]
+1, but looks like it's probably related to this Chromium [bug](https://bugs.chromium.org/p/chromium/issues/detail?id=460709&q=youtube%20fullscreen&colspec=ID%20Pri%20M%20Week%20ReleaseBlock%20Cr%20Status%20Owner%20Summary%20OS%20Modified)

**Comment by GorgonsMaze** [comment]
+1 I've been having this same issue, I've had to take out the fullscreen option in my videos to work around this.

**Comment by cerve** [comment]
+1 same issue in Chrome and Safari

**Comment by lipusal** [comment]
+1 same issue here with Vimeo in Chrome

**Comment by kevinchipotw** [comment]
+1

**Comment by AntonBudagov** [comment]
.modal{
   will-change: inherit
}

**Comment by cubanpete** [comment]
Freaking awesome, thanks Anton!

**Comment by kmmbvnr** [comment]
The http://codepen.io/anon/pen/KpwXwr works fine for me now in Chrome and Firefox.

Probably Youtube made some changes already.
