### ISSUE TITLE
Body scrollable while side-menu is shown

### ISSUE THREAD

**Issue by codinome** [Dogfalo/materialize#1254]
Consider a page with content bigger than the screen. And on top of that, a side-menu that too has more content than the screen. Both are scrollable. 

The default behaviour of current browsers is to scroll the parent element when the user is scrolling a child element and it reached its end. This results in some usability problems in this particular case.

Adding a overflow:hidden to the body while the side-menu is shown solves the issue nicely and it's widely compatible. Adding event hooks to the menu may open more options to developers, though.

**Comment by Dogfalo** [comment]
Fixed in 11220fd
