### ISSUE TITLE
Add styled scrollbars with overflow options.

### ISSUE THREAD

**Issue by Isprago** [Dogfalo/materialize#1255]
I tested the materialize views changing the browser (Mozilla and Chrome). I advised that the scroll bars (x and y) haven't style, they use default browser style. I would be a great idea to add new clases like:
.overflow-scrollbars (appear at big screen but not at small devices and other options)
.overflow-scrollbars.x (same but only x axis)
.overflow-scrollbars.y (y axis)

And other clases to colour, size, position (out the div or in the div) display or not top and bottom arrows, (Like Google Play app uses with its nav-bar).

That could be applicable to nav-bar, text-area, etc...

![scrollbar](https://cloud.githubusercontent.com/assets/9127964/7351576/54218256-ed06-11e4-8376-14b92a1371e5.PNG)

**Comment by getupkid203** [comment]
Chrome support the use of styled scrollbars but other browsers don't. Styled scrollbars would also go against accessibilty rules. For example ive seen some people set a scrollbar width to something like 5px wide...how would a person with arthritis or poor eye site be able to access the scrollbar easily

**Comment by kevinwarren** [comment]
I don't see why a styled scrollbar would go against accessibility rules as long as it's clearly visible & large enough like the default ones at approx 17px. I personally hardly ever click on scrollbars to scroll as my mousewheel is even easier. For me it's a visual indication more than anything. Of course they still have to be clearly visible for accessibility reasons even if mousewheels are the default method of scrolling.

This is probably one of the best 3rd party solutions out there http://manos.malihu.gr/jquery-custom-content-scroller/
Yes some of the scrollbars are very thin. However, I'm sure that if desired a selection of accessibility friendly styles could be designed & implemented into Materialize?

**Comment by kmmbvnr** [comment]
Duplicate #201
