### ISSUE TITLE
Slider shows gray bcg when accessed again without page reload

### ISSUE THREAD

**Issue by gnnpls** [Dogfalo/materialize#1259]
Hi.
When I display a div with slider everything works great for the first time. I hide the div and show other div and come back again and the bcg is gray.
Is there any de-initialiazation parameter for the slider>

**Comment by acburst** [comment]
I cant recreate this. Please submit a codepen illustrating the issue

**Comment by Dogfalo** [comment]
Closed due to lack of response or examples of the problem.
