### ISSUE TITLE
"files" field in package.json?

### ISSUE THREAD

**Issue by nchase** [Dogfalo/materialize#1260]
Hi there, love the repo. This is really awesome work that you guys have done.

Commit 23625390 introduced the `"files"` field to the repo's `package.json` which limits the published package to _only_ the files listed there.

That field makes the repo difficult to use in projects that consume dependencies via npm.

Currently we cannot use anything in the repo other than what is listed in the `"files"` field – e.g. if we want any of the uncompiled `.scss` files, or we want to use any of the individual javascript modules, we are out of luck.

**Comment by Dogfalo** [comment]
Originally this was to fix a problem with the CDN, but it seems it didn't fix it anyways. So it has been reverted in 753f7bc
