### ISSUE TITLE
JS installation in Rails 4

### ISSUE THREAD

**Issue by kockok** [Dogfalo/materialize#1261]
I successfully installed materializecss in rails with the min.js file and it works great.
![screen shot 2015-04-28 at 9 01 21 am](https://cloud.githubusercontent.com/assets/232541/7362812/d6ca71c2-eda1-11e4-8f5b-7c9dc2e27428.png)
However, if I separately load the js files, the javascript parts fail to functioning.
![screen shot 2015-04-28 at 12 31 17 pm](https://cloud.githubusercontent.com/assets/232541/7362862/a64d35ec-eda2-11e4-9fb6-56d44d6694aa.png)

Errors include:

```
ReferenceError: Can't find variable: Picker
(anonymous function)picker.date.self-5924b278beda2df8570f137f72b37e2d0f516acbc11a0994d1abb74380f078ef.js:18
global codepicker.date.self-5924b278beda2df8570f137f72b37e2d0f516acbc11a0994d1abb74380f078ef.js:20
localhost:170
```
```
[Error] TypeError: undefined is not a function (evaluating 'Vel(newToast, { "top" : "0px", opacity: 1 }, {duration: 300,
      easing: 'easeOutCubic',
      queue: false})')
  toast (toasts.self-188603d7c1c8e1177b838234026094fb90a0fe57c94bf0ffa1082dd33619a6cc.js, line 22)
  onclick (localhost, line 167)
```

Any advice?

**Comment by Dogfalo** [comment]
This is because there is a concat order. Take a look at our Gruntfile.js.
