### ISSUE TITLE
Remove css in certain div

### ISSUE THREAD

**Issue by cskiwi** [Dogfalo/materialize#1262]
Hi, I want to use a star rating found here: http://lea.verou.me/2011/08/accessible-star-rating-widget-with-pure-css/

but the materialize css messes up the css provided there, is there a possibility to remove css in a certian div?

**Comment by kbhatt2006** [comment]
Try this method
http://code.stephenmorley.org/html-and-css/star-rating-widget/

**Comment by cskiwi** [comment]
Nope still messes things up

**Comment by Dogfalo** [comment]
you would have to override the styles or set them to initial for the ones you do not want.
