### ISSUE TITLE
Bug img responsive in nav mobile

### ISSUE THREAD

**Issue by leninalbertolp** [Dogfalo/materialize#1263]
I just wanted to comment that I am submitting a bug in Firefox and IE with the responsive images in nav, I leave you some screenshots. In chrome it works perfect

![](http://i.imgur.com/C5P5xFr.png)

![](http://i.imgur.com/QUfir3C.png)

**Comment by Dogfalo** [comment]
Try removing the responsive img class

**Comment by leninalbertolp** [comment]
if I remove the logo responsive class breaks into chorme, and forces me to use width and height in the picture, but I think I'll have to do. Thank you very much, greetings from Venezuela, Go ahead, this luxury materialize.

**Comment by Dogfalo** [comment]
Just set height : 100%
