### ISSUE TITLE
Datepicker: Showing on the page without be called

### ISSUE THREAD

**Issue by brunoocasali** [Dogfalo/materialize#1264]
I'm using Firefox 37.0.2 on a Ubuntu 14.04 LTS.
Suppose I access any app done using materialize css, and it has a datepicker field.
Now I clicked in this field, and I chose the properly date and I closed using button or clicking out of modal. Nice! :+1:

But if I not click in any other field and the "focus" stay on datepicker field, and I change the tab of my browser, and come back to the form with date field, the modal shows again!!

**Comment by Dogfalo** [comment]
This is a pickadate.js issue. Open an issue there if you feel this is a problem
