### ISSUE TITLE
Add Code formatting in an addon

### ISSUE THREAD

**Issue by Dogfalo** [Dogfalo/materialize#1265]
Would it be useful to people for us to add this as an optional addon? 

![](http://puu.sh/hu7xa/d3b4a2670f.png)

**Comment by carlosperate** [comment]
I personally believe that if people need code highlighting they are probably already using their own preferred library for it. I would rather have a materialize framework focused on doing its thing as well as possible, than a framework that tries to do too much.

**Comment by vincentmorneau** [comment]
I agree with @carlosperate 

People that need code formatting are developers and should be comfortable enough to import their own library.

**Comment by DaEckster** [comment]
Agreed with above, specifically because Material design doesn't really need to do anything special for code formatting, I feel like that's the point of this framework, Material design implemented everywhere for you, and that's not really an issue with code formatting.

**Comment by lukaspijak** [comment]
Why not

**Comment by Dogfalo** [comment]
Yes I would tend to agree with you all, just wanted to see what some of the community thought.
