### ISSUE TITLE
dropdown in dropdown

### ISSUE THREAD

**Issue by LuisGerardoRC** [Dogfalo/materialize#1267]
is there any way to make a dropdown inside a dropdown or some way to make a menu with submenus, I tried unsuccessfully

**Comment by Dogfalo** [comment]
Not as of now.

**Comment by firelife12** [comment]
Any news on this?

**Comment by starbuckit** [comment]
the only way at the moment:

`.dropdown-content {
    width: auto;
    height: 400px;
}`

adjust your height based on sub menu

**Comment by nativeimaging** [comment]
This is one thing that I hoped wasn't an issue with Materialize. I have integrated a Multi-Level menu i found on tympanus.net that solves this issue perfectly. I would hope to see something like this in Materialize since i'm considering migrating my themes over to materialize.

**Comment by starbuckit** [comment]
@nativeimaging  can u provide a repositorie so i can download? ty in adv

**Comment by binarybaba** [comment]
bump.

**Comment by wupadach** [comment]
here is temp solution for "dropdown in dropdown"  [jsfiddle](https://jsfiddle.net/wupadach/54bwrzpe/4/)

**Comment by abdelouahabb** [comment]
@wupadach is there any trick using `hover : false` :(

**Comment by zlown3t** [comment]
Any news on this?

**Comment by starchild** [comment]
I'm gobsmacked that such a vital thing such as this is still unresolved.

**Comment by aliv** [comment]
i hope we have this feature soon. also @wupadach workaround is good -i didn't test it completely- but don't work with hover:false as @abdelouahabb said in comments.

**Comment by starchild** [comment]
See my work around for 1.0: https://github.com/Dogfalo/materialize/issues/6136

**Comment by starchild** [comment]
How is this closed when there is no solution in core yet?

**Comment by pixinvent** [comment]
Right no option for gutter in v1.0, please do not close it
