### ISSUE TITLE
Can't bind any event on a .modal-close

### ISSUE THREAD

**Issue by gjuchault** [Dogfalo/materialize#1270]
Hi,

When I'm trying to bind a click event on the buttons on the modal-footer, they are unbind once they are executed once.

This come from `leanModal.js` (line 110) :

``` js
$modal.find('.modal-close').off();
```

Is there any way to avoid this behavior ?

**Comment by Dogfalo** [comment]
What are you doing in the click event? maybe you should just use the complete callback

**Comment by gjuchault** [comment]
Well I'm listen to the click event to check whenever the user agreed on the modal confirmation.
If I have two buttons, one is cancelling, the other one is submitting, for example, I listen to the click event only on the submit button.

**Comment by ciencia** [comment]
@gjuchault Don't use modal-close, and instead, from your click event, call the closeModal when you're done:
```
 $(this).closest('.your-modal-dialog-class').closeModal();
```

**Comment by gjuchault** [comment]
Hem, that is not to close the modal, only to listen on the footer buttons
