### ISSUE TITLE
sorry for use it by free

### ISSUE THREAD

**Issue by jzhbiao** [Dogfalo/materialize#1271]
i will use it by free ,so sorry, when i rich i will donate it. its that ok? i hope you give me a allow for free use, i will hardly be other than grateful.please!

**Comment by Dogfalo** [comment]
Materialize is free to use! Don't worry about donating :smile:

**Comment by jzhbiao** [comment]
@Dogfalo 谢谢，

**Comment by jzhbiao** [comment]
jzhbiao@gmail.com is mine, hope we have chance to be friend

**Comment by jzhbiao** [comment]
谢谢哈 我这里是中国 希望可以成为朋友哈
