### ISSUE TITLE
Tabs - callback or trigger on active tab click

### ISSUE THREAD

**Issue by f1ana** [Dogfalo/materialize#1272]
One nice feature for tabs would be the ability to run a function when the tab change process has been completed.  A valid use case would include set up that needs to happen once the new tab content is visible (e.g.  ajax calls, resize of 3rd party UI tools that cannot determine size in display:none)
I'm not sure which would be a better implementation: providing a callback on tab init or using a trigger.

**Comment by Dogfalo** [comment]
Callback on tab doesn't really make sense to me. I think you should just implement it on a trigger.

**Comment by f1ana** [comment]
If I implement the fix, is there a best practice for what the trigger should be named or bound to?

**Comment by acburst** [comment]
Callback has been added called onShow
