### ISSUE TITLE
Form validation - replace pseudo class check for compatibility

### ISSUE THREAD

**Issue by f1ana** [Dogfalo/materialize#1273]
In the validate_field function, there is a check for a valid pseudo-class.  On modern browsers and versions of jQuery, it's no problem.  With IE9 (I know..) and lower, this doesn't work and jQuery 1.9 (I know... again...) has an issue with pseudo class selectors.
Since the fix is low impact, I believe it is worthwhile to gain a little compatibility, notably form validation now works in IE9.
object.is(':valid') should be replaced with !object.hasClass('invalid')

**Comment by Dogfalo** [comment]
IE9 is not supported.
