### ISSUE TITLE
Navbar dropdown width too small

### ISSUE THREAD

**Issue by migzisreallywewwhat** [Dogfalo/materialize#1274]
![image](https://cloud.githubusercontent.com/assets/6831138/7406894/2b6d66ac-ef3d-11e4-8d4b-b405b2293848.png)
As you can see, the dropdown is beautiful but the width is too small. Can you fix this please. My kindest regards

**Comment by qyouqme** [comment]
$('.dropdown-button').dropdown({
      inDuration: 300,
      outDuration: 225,
      constrain_width: false, // Does not change width of dropdown to that of the activator
      hover: true, // Activate on hover
      gutter: 0, // Spacing from edge
      belowOrigin: false // Displays dropdown below the button
    }
  );

I think the third setting(constrain_width) is what you need look into.

**Comment by migzisreallywewwhat** [comment]
oh thank you man, it was so foolish of me. Im so sorry
