### ISSUE TITLE
Select Dropdown exceeds screen height

### ISSUE THREAD

**Issue by hueyy** [Dogfalo/materialize#1276]
When the materialised `<select>` is near/at the bottom of the screen, its dropdown can exceed the screen. This is especially so for smaller screen sizes (more likely to happen):
![dropdown](http://i.imgur.com/ZjaDqGim.png)

Also seen on [materializecss.com](materializecss.com)

![screenshot1](http://i.imgur.com/wJKXr6lm.png)
![screenshot2](http://i.imgur.com/4fVcWI3m.png)
I suggest reversing placing the `<select>` above the option in such cases, as is done by Google:

![contacts1](http://i.imgur.com/HEirl3Km.png)
![contacts2](http://i.imgur.com/kWYWemVm.png)

**Comment by olivier67** [comment]
+1

**Comment by btecu** [comment]
Same problem on a computer (not phone).

**Comment by csapir** [comment]
+1 on computer. dropdown extends below screen.

**Comment by akyunus** [comment]
+1 how to limit the height of dropdown?

**Comment by getupkid203** [comment]
U can set a fixed height on the dropdown itself and set overflow-y to hidden.

**Comment by ciencia** [comment]
Seems to be a dupe of Issue #780

**Comment by bbshopadmin** [comment]
+1

**Comment by meichenblatt** [comment]
+1

**Comment by w0rldart** [comment]
+1

**Comment by viniciusparedes** [comment]
+1
Any solution?

**Comment by acburst** [comment]
This has been added in 88f6ddd93a183b298d0bfaa56f02624c5da55bab.

It is available on master and will be live in the next release.

**Comment by khlJunior** [comment]
Ok, now it goest to top when the height is bigger than the window size, but if i have a lot of options the select will just grow to top and hide the options.

There's a way to add a scroll inside the select?

**Comment by acburst** [comment]
I can look into adding a max-height

**Comment by khlJunior** [comment]
I didnt saw the max height, and in my case the max-height will not solve my proble. So, in my case my fix saves me because of my code. I will take a look on the max-height. Thanks! :) Sorry.

**Comment by fehmathais** [comment]
+1, I'm looking for news

**Comment by DanielRuf** [comment]
This is still relevant for the latest v1-dev as it seems.

**Comment by caglarorhan** [comment]
+1
