### ISSUE TITLE
Form reset button affects all forms on page

### ISSUE THREAD

**Issue by raptor008** [Dogfalo/materialize#1278]
Resetting a single form will affect all forms on the page by removing the "active" class from labels. I believe it should only affect the form of which you are hitting the reset button.

http://codepen.io/anon/pen/MwwoXb

1. Enter text into first field of first form.
2. Enter text into first field of second form.
3. Hit the second reset button.
4. Notice that the active class for the first form's label is removed.

**Comment by f1ana** [comment]
I have a fix for this in my fork- will create pull request shortly

**Comment by raptor008** [comment]
Good deal, thanks.

**Comment by acburst** [comment]
Fixed in c5de306
