### ISSUE TITLE
Indeterminate progress::Mozilla issue

### ISSUE THREAD

**Issue by wilsoncastiblanco** [Dogfalo/materialize#1279]
Hi, I'm using Indeterminate progress and I realised that the progress is not showing in Mozilla 37.0.2 ,I changed display attribute block to inline-block and It worked, could you fix that or what should I do? thank you so much.

**Comment by Dogfalo** [comment]
Does it work on our website?

**Comment by acburst** [comment]
Im not seeing this on my Mozilla 37.0.2. Do you have any other information about what could be causing this?
