### ISSUE TITLE
Select Javascript error

### ISSUE THREAD

**Issue by migzisreallywewwhat** [Dogfalo/materialize#1281]
The Error
`materialize.min.js:9` Uncaught TypeError: Cannot read property 'hash' of undefined

My Markup
`<div class="input-field col s12 m5 ">`
`   <select name="country" id="country">`
								`      <option value="Wew">Wew</option>`
								`      <option value="Qwe">Qwe</option>`
								`      <option value="Qqw">Qqw</option>`
								`      <option value="Wwq">Wwq</option>`
							`   </select>`
							`   <label for="country">Country</label>`
						`</div>`

My init.js
`
$(document).ready(function(){
	$('select').material_select();
	alert('select initialized!');
});
`

Problem : The Select is not initialized therefore the select is not showing itself :(

**Comment by Dogfalo** [comment]
http://codepen.io/Dogfalo/pen/zGGPZN

**Comment by migzisreallywewwhat** [comment]
but why is it giving me the error ? i still dont know :( Sorry please help

**Comment by Dogfalo** [comment]
I don't know, it is probably another error on your page.
