### ISSUE TITLE
Tabs customizing the indicator color and height

### ISSUE THREAD

**Issue by migzisreallywewwhat** [Dogfalo/materialize#1282]
Any ideas how can we customize the thing ? Thanks

**Comment by migzisreallywewwhat** [comment]
Also, how can we make the tab to act like a link? Thanks

**Comment by mouse170** [comment]
@migzisreallywewwhat Did you solved it? Can you give me an example?

**Comment by KSMorozov** [comment]
@mouse170 
```
.tabs .indicator {
  background-color: <color-of-choice>;
}
```
