### ISSUE TITLE
rendering a form in modal

### ISSUE THREAD

**Issue by benjh33** [Dogfalo/materialize#1284]
Hi,

Great framework, thanks.

When I render a form in a modal, I get this strange flap at the bottom. I can manually adjust the height of the modal (which isn't perfect), but I figured there's a better way. I've spent quite a bit of time clicking around in the css and I can't figure it out. 

![materialize_screenshot](https://cloud.githubusercontent.com/assets/3699481/7437391/9e8cf19a-f01c-11e4-935f-de984591b823.png)

**Comment by Dogfalo** [comment]
Please take a look at our CONTRIBUTING.md and create a codepen illustrating your issue. Or we can't help
