### ISSUE TITLE
High Resolution Viewport Invokes Non-responsive Layout

### ISSUE THREAD

**Issue by egladman** [Dogfalo/materialize#1286]
### The side navbar partially covers up the menu icon that collapses the navbar.

![2015-05-02-13 24 20](https://cloud.githubusercontent.com/assets/8713153/7442058/def56bdc-f0cf-11e4-8978-77982c3def48.png)

### When the side navbar is collapsed, there is white space on the left.

![2015-05-02-13 24 55](https://cloud.githubusercontent.com/assets/8713153/7442081/91543da8-f0d0-11e4-9c1e-658026b06fab.png)

**Comment by acburst** [comment]
Fixed in 70cfedca9ceeb23f702e64805e490111b5d264e3
