### ISSUE TITLE
Too much margin on mobile

### ISSUE THREAD

**Issue by Scarwolf** [Dogfalo/materialize#1287]
I am not comfortable with this, as it reduces the usable space on mobile dramatically.
See
![Image](http://i.imgur.com/JZcJkwX.png)

**Comment by f1ana** [comment]
why not just use container-fluid?

**Comment by Dogfalo** [comment]
We removed fixed padding which the container had in e2770df. See if it fits better now.

![](http://puu.sh/hDF0j/000c246dc2.png)
