### ISSUE TITLE
Problem with navbar

### ISSUE THREAD

**Issue by Pablotis** [Dogfalo/materialize#1291]
Hello, I have included a navbar on my page (Still in progress) but it doesn't open the menu on mobile phones or small screens. Here the link to my page (It's a private server so maybe it isn't available all the time): http://estoesunaprueba.ddns.net/
Thanks for help!

**Comment by Dogfalo** [comment]
Seems to work for me.

**Comment by Dogfalo** [comment]
Due to lack of response, this is being closed.
