### ISSUE TITLE
Problem with dropdows

### ISSUE THREAD

**Issue by vorant94** [Dogfalo/materialize#1292]
Hello. I've added this materialize to my rails app, and made navbar with it with dropdown menus. At first it works normal: I click on navbar, dropdown appears, and then links, which are in this dropdown work. But when I link it and try to open dropdown again it doesn't appear until I refresh the page. Please help me.

Here it is my app for example http://qualitet.herokuapp.com/

**Comment by Dogfalo** [comment]
I don't even see a dropdown. Why don't you create a isolated incident in a codepen so we can determine that this is a problem in Materialize?

**Comment by Dogfalo** [comment]
Due to a lack of response and an unclear problem, we've closed this issue for now. If you clarify with the necessary information we will reopen it.

**Comment by Thor99** [comment]
i have this problem too!!

**Comment by Thor99** [comment]
Is this a general materialize problem? I cant solve and my friend cant too

**Comment by Thor99** [comment]
http://www.alunosdesucesso.com/
Check the dropdowns!

**Comment by Thor99** [comment]
if you click in the dropdown more than one time, it doesn't appear until i refresh the page

**Comment by Dogfalo** [comment]
well it looks like you could be using meteor or something similar. In which case you need to init the component in a rendered callback

**Comment by Thor99** [comment]
Sorry, but i didn't understand

**Comment by Thor99** [comment]
I have seen this problems in others sites with materialize dropdowns
