### ISSUE TITLE
Fix badges position

### ISSUE THREAD

**Issue by Isprago** [Dogfalo/materialize#1298]
Change CSS: position:absolute to CSS: float:left.
It works if you want to add 2 or more badges.

Actually, if you add 2 badges, they overlaps.

Also, let change the text "new" in order to translate the badges.

And finally, fix collections height when they have a long title and a few badges on small screen.

**Comment by jpggvilaca** [comment]
I fixed it but i haven't done a pr. 
spans: position: relative  - display: inline-block  - float: right

**Comment by ricardodovalle** [comment]
I've getting the same error and created a jsfiddle to test.
https://jsfiddle.net/6kqL1y7u/

**Comment by 0xbaadf00d** [comment]
I think .badge class don't have to define any position (relative or not) , classes .left and .rigth already exists and defining position can lead to bug problem to add tag everywhere in html page without embbed it in a position:relative div.

**Comment by Merovex** [comment]
I'm running into a related issue where the badge is always on page far right, regardless of where I want it. Ricardo's fiddle above shows this isn't local to my situation.

**Comment by developeranirudhprabhu** [comment]
may be need to provide nesting of badges. That would be the ideal fix?

**Comment by developeranirudhprabhu** [comment]
@Isprago Can you create a fiddle and share these changes?

**Comment by Native-Coder** [comment]
Is anyone having issue putting badges on the nav bar? When i do it [this](http://i67.tinypic.com/f9mau0.png) happens. I've also had problems with my search bar not taking up the entire nav bar, but I worked around that by setting a static height on the element.

**Comment by acburst** [comment]
These issues should be fixed.

@Native-Coder http://materializecss.com/badges.html#navbar

**Comment by Native-Coder** [comment]
I have the latest version. Still having both issues. V.98
