### ISSUE TITLE
Documentation misspelling

### ISSUE THREAD

**Issue by kulik** [Dogfalo/materialize#1299]
Badges -> Dropdown ->http://materializecss.com/badges.html#collections In code semple exist redundat </li> instead </a>
http://screencloud.net/v/fTgj

**Comment by Dogfalo** [comment]
I don't know what you're talking about

**Comment by kulik** [comment]
1) please look on screenshot http://screencloud.net/v/fTgj   4th line here closing tag </li> without opening it.
2) This is lint issue also. because it is not correct to use <a> directly in <ul>.

**Comment by Dogfalo** [comment]
Already fixed by #1232
