### ISSUE TITLE
character counter doesn't appear a second time

### ISSUE THREAD

**Issue by tiagoovieira** [Dogfalo/materialize#1300]
I'm using the character counter in textarea in a modal view with a form. After submit the first time, if I open the same form modal view, the character counter doesn't appear. Any ideas?

**Comment by Dogfalo** [comment]
It might just be because it needs to be initialized if the element is created dynamically in your js.

**Comment by tiagoovieira** [comment]
yes

```
//on document ready
$(function() {
  $('.materialize-textarea').attr('length', '400').characterCounter();
});
```

solved the problem :)
