### ISSUE TITLE
Please don't recommend `maximum-scale=1.0` and `user-scalable=no`

### ISSUE THREAD

**Issue by dmitriz** [Dogfalo/materialize#1302]
The Getting Started page
http://materializecss.com/getting-started.html
recommends to block the user from zooming by these declarations:

      <meta name="viewport" content="..., maximum-scale=1.0, user-scalable=no"/>

**Please don't!**

I have bad eyes and find it really frustrating when sites silently block my attempts to zoom, in order to read their site more comfortably for my eyesight. You as designer may think your site looks perfect but the user will suffer and leave your site for the ones who care.

This is really a bad advise, please read here if this is still not convincing:

http://stackoverflow.com/a/30044183/1614973
http://blog.javierusobiaga.com/stop-using-the-viewport-tag-until-you-know-ho
http://www.lukew.com/ff/entry.asp?1945
http://ux.stackexchange.com/questions/37511/should-users-be-able-to-zoom-in-a-responsive-webdesign

**Comment by Dogfalo** [comment]
Fixed in 2a5297e

**Comment by franckl** [comment]
Those settings (maximum-scale=1.0, user-scalable=no) are still there on the parallax demo
view-source:http://materializecss.com/templates/parallax-template/preview.html
