### ISSUE TITLE
will it support with angularjs?

### ISSUE THREAD

**Issue by ohohco** [Dogfalo/materialize#1304]
no jquery ,only angularjs.will it be?

**Comment by b1rdex** [comment]
no

**Comment by DennisRoam** [comment]
We run it on Angular out of the box with no problems.

**Comment by Dogfalo** [comment]
It works with Angular, but maybe using Angular Material will be easier.

**Comment by DennisRoam** [comment]
The issue with angular-material though is it relies on ng-animate which is a resource killer on complex apps and touch apps. The touch delay is at least 1.5 seconds to switch views. Switching to materialize its 100ms or less

At least for us..
