### ISSUE TITLE
Responsive tables are broken

### ISSUE THREAD

**Issue by AndrewCarterUK** [Dogfalo/materialize#1306]
I created an issue for this but it was prematurely closed so I've been left with no option but to create a new one (previous issue: https://github.com/Dogfalo/materialize/issues/1206).

http://codepen.io/anon/pen/pJoayX

Essentially when you force a responsive table to re-flow on a small screen - the alignment is completely off because it assumes that the height of the table header is the same as the height of a table cell in that column - which is almost *never the case*.

It might be that there is no fix for this using CSS, but there are other options (Javascript).

-----------------------------------------------

Mini rant:

Would it be possible for somebody to explain to me why the previous GitHub issue was closed? As long as this behaviour is an 'issue' (which it is) the thread should remain open for future discussion.

If there is no fix for this that you wish to implement - you do not just close the issue and ignore it!

The feature should be flagged for removal in the next major version and a warning should be immediately placed on the documentation advising against its use and explaining the bug. This bug very nearly crept onto a live system of ours before it got noticed.

I've really enjoyed working with the materialize framework. I think it looks very good, is easy to use and works nicely. I honestly appreciate the hard work that has been invested in this project.

Unfortunately the handling of GitHub issues (not just mine) and certain aspects of behaviour (try using a select menu or datepicker in a modal) haven't given me the confidence that this project is production ready. As such I will be migrating current projects to use alternative design frameworks.

I understand that the authors of this project owe me nothing - but for every user who writes about their experience there are hundreds more who just drop it and move on, which is why I have included this.

**Comment by johngeorgewright** [comment]
On another note... the footer's a bit buggered too:

http://codepen.io/anon/pen/zGqVvX

**Comment by dtracers** [comment]
technically it is not even version 1 [its still in the 0.9 range as of this comment]

which typically means that it is not production ready.

**Comment by NeXTs** [comment]
Fixed http://codepen.io/NeXTs/pen/pjJZwW :+1: 

Take a look at [ZURB's responsive tables](http://zurb.com/playground/projects/responsive-tables/index.html), they don't handle multiline rows at 'responsive mode' too
