### ISSUE TITLE
Limiting Textarea Size Class

### ISSUE THREAD

**Issue by Isprago** [Dogfalo/materialize#1312]
Now I'm using a textarea. As stated in the documentation, the textarea resizes it the text exceeds.
I need to save at the database a long text (over 200 lines) so the textarea is too resized.

I fixed it with max-height.

So I had a idea. A new class for textarea called "height-limited" that will use a style="max-height:XX" as max height and will draw an up or down arrow reporting that there is text hidden out of the limits when the textarea is selected. Something like:
![textarea](https://cloud.githubusercontent.com/assets/9127964/7511610/7bfe6f6c-f4a6-11e4-82af-4b4a2bc3cee3.PNG)

The arrow can be only informative, it doesn't need to be a button move up/down

It's just and idea. IDK if it's correctly in MaterialDesign, but I thing it's usefull when you don't want to get a soaring website and you want to keep infrmation.

P.D: At least, let use the mouse wheel to go up/down with js if someone limit the height like me.

**Comment by fega** [comment]
Hello, that's not specified in the material-design guidelines. :cry:
