### ISSUE TITLE
IE9 

### ISSUE THREAD

**Issue by cskiwi** [Dogfalo/materialize#1313]
When upgrading from v0.95.3 to v0.96.1 on IE9 I got some errors:

`SCRIPT5007: Unable to get value of the property 'SetReturnValue': object is null or undefined 
localhost, line 1 character 1`
And
`SCRIPT5007: Unable to get value of the property 'contains': object is null or undefined 
materialize.js, line 1604 character 20`

Just letting this know. because time limit I need to have a working version. So can't debug anything
Hopefully I can upgrade soon.

grt Glenn

**Comment by Dogfalo** [comment]
We don't support IE9 so I can't help here.
