### ISSUE TITLE
Waves don't disappear when swiped on element and then touched. (Windows 8.1, Chrome, TouchScreen no Mouse)

### ISSUE THREAD

**Issue by DennisRoam** [Dogfalo/materialize#1314]
We use the Materialize scripts on large buttons on HD kiosks. Most times it's not noticeable but we've noticed that the waves weren't disappearing and couldn't figure out why until today. 

If you start a swipe on a element that has the wave effect, and then touch it with another input the clear only removes one wave element. This then causes a compound effect as even after released all new waves don't get cleared out and the button stacks the wave elements. 

It's a Waves issue I believe, but I notice they are on V7 so maybe once updating we'll get the fix?

**Comment by SamDeacon** [comment]
im fighting with infinte waves as well, do you know how to trigger the clear? it works fine on the materialize website but on my site it keeps pushing more and more color transition (not good when I have white writing on .waves-light!)

**Comment by m00k1e** [comment]
Hello!

 

New message, please read <http://marienka.sk/comply.php?pd>

 

hello@mookiecreative.com

**Comment by kmmbvnr** [comment]
@DennisRoam did you resolved it?

**Comment by tomscholz** [comment]
These issues are duplicates:
https://github.com/Dogfalo/materialize/issues/1314
https://github.com/Dogfalo/materialize/issues/3642
https://github.com/Dogfalo/materialize/issues/686

For future discussion, please use this issue instead.
https://github.com/Dogfalo/materialize/issues/4344
