### ISSUE TITLE
Stack icon with text

### ISSUE THREAD

**Issue by dcworldwide** [Dogfalo/materialize#1321]
Is it possible to stack icons and text? E.g. i want to overlay a # on top of a heart icon.

regards

**Comment by jpggvilaca** [comment]
I suggest you make your customized image/icon with that and then add that to html. You would have to do a lot of changes , it's just not worth it.

**Comment by acburst** [comment]
I agree, There are too many things you can do yourself with icons and I think this is simple enough to be achieved with custom css.
