### ISSUE TITLE
sidenav like Google apps

### ISSUE THREAD

**Issue by diniremix** [Dogfalo/materialize#1322]
some example of a sidenav with a logo and icons, as some Google applications such as Gmail.
as described in the guide about Material Design
[layout -structure -sidenav](http://goo.gl/lisVNW)
![gmail app](http://i.imgur.com/YhQtJ6g.png)

**Comment by carloscarcamo** [comment]
:+1:

**Comment by serkandurusoy** [comment]
+1

**Comment by derixithy** [comment]
+1

**Comment by ano95** [comment]
+1

**Comment by karbowiak** [comment]
+1

**Comment by gabrielle-ong** [comment]
Wondering if this issue has been solved, seems that we now have this feature. This is my first time attempting open source projects so sorry if Im making newbie mistakes!
<img width="301" alt="screen shot 2016-07-30 at 1 58 27 am" src="https://cloud.githubusercontent.com/assets/17236572/17258459/88b8295e-55f9-11e6-888c-5153038bd675.png">

**Comment by GorgonsMaze** [comment]
@gabrielle-ong Yes it looks like it's available in the v.97.7 release. You can either download it from github, or from the http://materializecss.com/getting-started.html

![screen shot 2016-07-29 at 2 13 35 pm](https://cloud.githubusercontent.com/assets/12011826/17258813/ad123b36-5596-11e6-8157-18edbd6e969a.png)

**Comment by tomscholz** [comment]
Since this feature has been added, please close.
