### ISSUE TITLE
Packaged Dark Theme following Material Design guidelines

### ISSUE THREAD

**Issue by DaEckster** [Dogfalo/materialize#1323]
Material Design specifically goes out of its way to specify what a [dark theme](http://www.google.com/design/spec/style/color.html#color-themes)(see bottom), including [typography specifications](http://www.google.com/design/spec/style/color.html#color-ui-color-application), should look like in the documentation. It seems as if a dark theme implementation should be created, since it requires more than just changing the secondary and primary colors.

**Comment by acburst** [comment]
I'll look into the pull request soon, I just added this into our new templates issue

**Comment by kinsi55** [comment]
Hmm, did this ever get anywhere?
