### ISSUE TITLE
Font look very bad on desktop. Why?

### ISSUE THREAD

**Issue by alekseysolo** [Dogfalo/materialize#1329]
On desktop (look at menu icon, Navbar Link, Get Started button and etc.)
![1900-06](https://cloud.githubusercontent.com/assets/301790/7541677/ccfbb7ca-f5bf-11e4-8fe9-519025433369.png)
On mobile devices, it's OK. 
I can correct by myself, but I do not understand what is the reason. 
Somebody knows?

**Comment by carlosperate** [comment]
What version of chrome are you using?

**Comment by alekseysolo** [comment]
Firefox 37.0.2, Chrome 42.0.2311.135 m
Fonts are equally bad on different devices: pc, notebook...

**Comment by Dogfalo** [comment]
Please include a screenshot

**Comment by cresharper** [comment]
What devices are you looking at this on? Sounds like a device/display issue rather than a problem with Materialize.

**Comment by cresharper** [comment]
Really old/poorly calibrated monitors can distort text like that.

**Comment by alekseysolo** [comment]
https://cloud.githubusercontent.com/assets/301790/7541677/ccfbb7ca-f5bf-11e4-8fe9-519025433369.png

2015-05-08 20:52 GMT+03:00 Alvin Wang <notifications@github.com>:

> Please include a screenshot

**Comment by Dogfalo** [comment]
Looks like you could have font smoothing turned off?

**Comment by alekseysolo** [comment]
Ok. Thanks.

**Comment by alekseysolo** [comment]
The problem is solved by using the latest version of the Roboto font from https://github.com/choffmeister/roboto-fontface-bower/releases/tag/v0.3.0
