### ISSUE TITLE
Automatically hide datepicker once date is selected

### ISSUE THREAD

**Issue by shubham-agrawal** [Dogfalo/materialize#1331]
Not working even after changing default pickerjs setting

**Comment by shubham-agrawal** [comment]
Nevermind I figured out a solution

```
click #confirm': function(event) {
    event.preventDefault();
    event.stopPropagation();
    var picker = $input.data('pickadate');
    picker.open();
    picker.on('set', function() {
      picker.close();
    })

  }
```

**Comment by allsyed** [comment]
You solution doesn't works in latest release, 0.99, Here is my solution.

`<input`id="id_startdt" type="date" class="datepicker" > `

Then

`$('#id_startdt').change(function(e){
            // using timeout so it doesn't seem sudden to user
            setTimeout(function(){
                $('#id_startdt_root').find('[data-close="true"]').click()
            }, 500)
        })`
