### ISSUE TITLE
Button over select

### ISSUE THREAD

**Issue by Isprago94** [Dogfalo/materialize#1337]
When you put a button down a select, the button overlays the select list.
![mat](https://cloud.githubusercontent.com/assets/6731956/7562401/8802e7f8-f7d4-11e4-85e3-5b3e2a9aaf5d.PNG)

I changed the z-index but it should be added to the materialize package.

**Comment by lauterry** [comment]
Hi

On Android 4.4.4, on Chrome Browser, The button overlays the select list even if I change the z-index

**Comment by Dogfalo** [comment]
Fixed already, but not released.
