### ISSUE TITLE
Very small & tiny issue :)

### ISSUE THREAD

**Issue by boustanihani** [Dogfalo/materialize#1338]
Acoording to http://materializecss.com/grid.html#grid-responsive 

- Mobile Devices are <= 600px **(.s)**
- Tablet Devices are <= 992px **(.m)**
- Desktop Devices >= 992px **(.l)**

There is only one problem, what if the screen width is 992px, would this be considered as a tablet or a desktop???

Solution: Define tablets as ```< 992px``` or desktops as ```> 992px``` **removing the "or equals" in one of them**.

**Comment by Amonstyle** [comment]
hi boustanihabni,
I think dont have a device with width is 992px :p

**Comment by boustanihani** [comment]
maybe you will resize your window to this accidently :wink:
