### ISSUE TITLE
 Navbar dropdown menulist fixed with parent width

### ISSUE THREAD

**Issue by skolade** [Dogfalo/materialize#1340]
Navbar dropdown Width is not responsive, in the sense that submenu content are wrap within it parent width, and if sub-item are longer than the parent, the menu does not strecht. is there a solution to this?

**Comment by Dogfalo** [comment]
See the constrain width option

**Comment by skolade** [comment]
@Dogfalo thanks. Where is this documentation located.

**Comment by Dogfalo** [comment]
In the dropdown documentation
