### ISSUE TITLE
Question: Disable Hover inside SideNav

### ISSUE THREAD

**Issue by boustanihani** [Dogfalo/materialize#1341]
How could we disable the hover effect of an element inside a sideNav ??
A good example is the top LOGO inside the sideNav on the site...

**Comment by Dogfalo** [comment]
you can write a custom media query for whatever element you have.

**Comment by paulomcnally** [comment]
```
ul.side-nav.fixed li.logo a:hover, ul.side-nav.fixed li.logo a.active {
   background-color: #ffffff;
}

```
