### ISSUE TITLE
change language datepicker

### ISSUE THREAD

**Issue by INGCRENGIFO** [Dogfalo/materialize#1343]
Hey guys, you can change the language of the months of the datepicker? I would like to have them in es_es.

**Comment by Isprago94** [comment]
Busca en materialize.js > "The date picker defaults." y reemplaza con las siguientes lineas.

```javascript 
// The title label to use for the month nav buttons
        labelMonthNext: 'Mes siguiente',
        labelMonthPrev: 'Mes anterior',

// The title label to use for the dropdown selectors
        labelMonthSelect: 'Selecciona un mes',
        labelYearSelect: 'Selecciona un año',

// Months and weekdays
		monthsFull: [ 'Enero', 'Febrero', 'Marzo', 'Abril', 'Mayo', 'Junio', 'Julio', 'Agosto', 'Septiembre', 'Octubre', 'Noviembre', 'Diciembre' ],
        monthsShort: [ 'Ene', 'Feb', 'Mar', 'Abr', 'May', 'Jun', 'Jul', 'Ago', 'Sep', 'Oct', 'Nov', 'Dic' ],
        weekdaysFull: [ 'Domingo', 'Lunes', 'Martes', 'Miércoles', 'Jueves', 'Viernes', 'Sábado' ],
        weekdaysShort: [ 'Dom', 'Lun', 'Mar', 'Mie', 'Jue', 'Vie', 'Sab' ],

// Materialize modified
        weekdaysLetter: [ 'D', 'L', 'M', 'X', 'J', 'V', 'S' ],

// Today and clear
        today: 'Hoy',
        clear: 'Limpiar',
        close: 'Cerrar',
```

Si ademas quieres que el calendario empiece en lunes y no en domingo, cuando inicialices el calendario, incluye la opción firstDay.
```javascript
	 $('.datepicker').pickadate({
		firstDay: true
	});
```

**Comment by INGCRENGIFO** [comment]
Hola @Isprago94 Muchas gracias por responder, Gracias a tu ayuda pude solucionarlo. Quedo muy agradecido.

**Comment by mPaleo** [comment]
This need to be in docs, or reference to http://amsul.ca/pickadate.js/date/#translations
We have two arrays with weekdays, so it can be taken from there, i think there's no need from weekdaysLetter https://github.com/Dogfalo/materialize/blob/6da429c5972c90e386e34f14bed3f17c8c40fa95/dist/js/materialize.js#L5905

**Comment by fabyeah** [comment]
:+1: please put this in the docs / on the website.

**Comment by terrill021** [comment]
Cuando se traducen a español no se puede utilizar:
var fecha = new Date('fecha_en_español');

donde fecha_en_español es un String con el formato ej: 1 Diciembre, 2016.
¿Alguien tiene alguna solución?

**Comment by MarceKalEl** [comment]
Tengo un problemilla... saben como hago que el picker se vea mas pequeño?? o en su defecto, que se vea mas abajo??  
![image](https://user-images.githubusercontent.com/22898121/34077094-51b086b2-e2d0-11e7-9560-5914ee3d510b.png)

**Comment by juank2808** [comment]
Hola yo tengo una pregunta, como hago para que el formato de fecha se este **'yyyy-mm-dd**' se como cambiarlo en el modal, pero lo que necesito es que me cambie al formato ya dicho, alguien sabria hacerlo? y que funcione claro.
Un saldudo de antemano

**Comment by juank2808** [comment]
Hello, I have a question, how do I change the format of the date to '**yyyy-mm-dd**'? How do I change it in the modal, but what I need is that I change to the format already said, someone would know how to do it? and that works clear.
regards

**Comment by TaniaTG** [comment]
@juank2808  
$("#your_elements_id").datepicker({ 
dateFormat: 'yyyy-mm-dd'
 });
o  format:'yyyy-mm-dd'

**Comment by nicolegrafica** [comment]
Pongo esto en mi <scrip>$(document).ready(function(){
    $('.datepicker').datepicker({
			monthsFull: ['Enero',
                         'Febrero', 
                         'Marzo', 
                         'Abril',
                         'Mayo',
                         'Junio', 
                         'Julio',
                         'Agosto',
                         'Septiembre',
                         'Octubre', 
                         'Noviembre', 
                         'Diciembre'],
        
			monthsShort: ['Ene', 
                          'Feb',
                          'Mar', 
                          'Abr', 
                          'May', 
                          'Jun', 
                          'Jul', 
                          'Ago',
                          'Sep', 
                          'Oct', 
                          'Nov', 
                          'Dic'],
			weekdaysFull: ['Domingo', 'Lunes', 'Martes', 'Miércoles', 'Jueves', 'Viernes', 'Sábado'],
			weekdaysShort: ['Dom', 'Lun', 'Mar', 'Mié', 'Jue', 'Vie', 'Sáb'],
		    selectMonths: true,
		    selectYears: 100, // Puedes cambiarlo para mostrar más o menos años
		    today: 'Hoy',
		    clear: 'Limpiar',
		    close: 'Ok',
		    labelMonthNext: 'Siguiente mes',
			labelMonthPrev: 'Mes anterior',
			labelMonthSelect: 'Selecciona un mes',
			labelYearSelect: 'Selecciona un año',
		  });
});
          </scrip> 

Pero no lo toma tomo el idioma por defoult del materialice csss que tengo que hacer para que lo tome?

**Comment by lherreranetlink** [comment]
@nicolegrafica pudiste resolver el error? Yo estoy batallando actualmente con el mismo problema.
