### ISSUE TITLE
Error with dynamic select menu using meteorJS

### ISSUE THREAD

**Issue by meichenblatt** [Dogfalo/materialize#1344]
When I try to put a loop in a drop down select menu it doesn't display. When materialize is disabled it works fine. Only when materialize is enabled does it display: "undefined".

<select id="location">
        {{#each regions}}
              <option value="{{_id}}">{{Name}}</option>
        {{/each}}
</select>

Thank you!!

**Comment by meichenblatt** [comment]
select id="location"
     {{#each regions}}
           option value="{{_id}}" {{Name}} /option
      {{/each}}
/select

**Comment by meichenblatt** [comment]
github deleted the parts with the angle brackets.....

**Comment by delvedor** [comment]
Same problem here!
This NOT work:
```javascript
<div class="input-field col s12">
    <select id="roomSelect">
        <option value="" disabled selected>Choose room</option>
        {{ #each rooms }}
        <option value="{{ _id }}">{{ name }}</option>
        {{ /each }}
    </select>
</div>
```
This works:
```javascript
<div class="input-field col s12">
    <select class="browser-default" id="roomSelect">
        <option value="" disabled selected>Choose room</option>
        {{ #each rooms }}
        <option value="{{ _id }}">{{ name }}</option>
        {{ /each }}
    </select>
</div>
```

**Comment by tomscholz** [comment]
Closed due inactivity, feel free to reopen it if it is still necessary
