### ISSUE TITLE
Sidebar dropdown leaking text under it

### ISSUE THREAD

**Issue by drtweety** [Dogfalo/materialize#1346]
I have a navbar with a dropdown below which there is a normal link to a page. Here is how it looks like:

![screenshot_2015-05-12-19-00-05](https://cloud.githubusercontent.com/assets/5836402/7591966/7f0d142e-f8d9-11e4-86cc-615a9fd88840.jpeg)

And when I open a dropdown below which there is a link to another dropdown, it works fine:

![screenshot_2015-05-12-18-59-50](https://cloud.githubusercontent.com/assets/5836402/7591982/967fa4aa-f8d9-11e4-81e1-e6a72c5ea3f4.jpeg)

However, If I open one with a non-dropdown link below, this is what happens:
![screenshot_2015-05-12-18-59-46](https://cloud.githubusercontent.com/assets/5836402/7591996/ac95d250-f8d9-11e4-874a-2d389b75d943.jpeg)

**Comment by Isprago94** [comment]
Try changing the z-index of dropdown-content class with a higher value:
```css
.dropdown-content {
     z-index:2;
}
```

**Comment by Dogfalo** [comment]
This is something we've fixed, but is not released
