### ISSUE TITLE
Please add support for a module system

### ISSUE THREAD

**Issue by Bretto** [Dogfalo/materialize#1348]
First off great job and congratulation.
It would be great if you could integrate properly with a module loader system, we are using JSPM and when I tried your project I got some unexpected behaviours.

jspm install npm:materialize-css 
errors on: 
http://localhost:3000/jspm_packages/npm/materialize-css@0.96.1.js 404 (Not Found)

and when using jspm install bower:materialize
the wave effect doesn't work

the setup is simple:

```
<script src="jspm_packages/system.js"></script>
<script src="config.js"></script>
<script>
        System.import("src/bootstrap").catch(function (ex) {
        console.error('Internal Error ', ex.stack || ex);
    });
</script>
```

```
import $ from 'jquery';
import materialize from 'materialize';
import angular from 'angular';
import AppModule from './app/AppModule';

angular.element(document).ready(function () {
    angular.bootstrap(document, ['AppModule']);
});
```

I think you guys need to integrate with a good module loader as relying on globals is a way of the past and prone to errors... Let me know if you need any more info.

**Comment by KingRial** [comment]
I am trying to load the library using SystemJS ( https://github.com/systemjs/systemjs ) and the problem seems to be fired by how "VelocityJS.org" is inserted inside material.js.

That library tries to declare itself twice when a module loader is present.

If you remove the heading, where the library try to declare itself to the module loader, you solve the problem.

This is just a workaround!

**Comment by kmmbvnr** [comment]
JSPM support was rejected - https://github.com/Dogfalo/materialize/issues/1208

**Comment by tomscholz** [comment]
Please close ;)

**Comment by fega** [comment]
Already approved in the feature request board for UMD and JSPM support rejected on #1208 as @kmmbvnr points

But if someone wants to create the JSPM is welcome :smiley:
