### ISSUE TITLE
Multi select control

### ISSUE THREAD

**Issue by cliren** [Dogfalo/materialize#1350]
Is there a plan for future to add multi select control or can anyone suggest an alternative?

**Comment by Isprago94** [comment]
Actually I use checkbox instead of the multiselect. They ar being organised in rows and each one in a div class "col s6 m4 l3"

**Comment by hatpick** [comment]
You can't have 1000 items as checkboxes there, a multi select box+search seems necessary.

**Comment by Dogfalo** [comment]
Duplicate #1002
