### ISSUE TITLE
Datepicker validate method not being triggered on firefox

### ISSUE THREAD

**Issue by JAFisher** [Dogfalo/materialize#1352]
Not sure why but I cannot get the same results between firefox and chrome for a datepicker.

using: osx 
latest firefox

firefox:
![screen shot 2015-05-13 at 20 26 52](https://cloud.githubusercontent.com/assets/1113016/7619617/e6fc7920-f9b1-11e4-8f26-3f2c8369f597.png)

chrome:
![screen shot 2015-05-13 at 20 31 02](https://cloud.githubusercontent.com/assets/1113016/7619620/eb3f90c6-f9b1-11e4-867a-37c2be15bbdc.png)

```
<div class="input-field col s12 m12">
    <label for="birthdate">Birthdate</label>
    <input type="date" class="datepicker validate">
</div>

<script>
  $('.datepicker').pickadate({
    selectMonths: true, // Creates a dropdown to control month
  });
</script>
```

**Comment by JAFisher** [comment]
Looks like it angular datefmt interfering :/ bah! sorry

**Comment by ManuelRiveraC** [comment]
I have the same problem. How can you solve it?

**Comment by Birssan** [comment]
In Chrome type `date` for input is changed to `text` when used with datepicker, bug ? With validate class, the input field is always invalid in chrome... In firefox, well the type of input is `date`, but validation might not be triggered, and label doesn't move up, it stays under the value...

**Comment by kkarski82** [comment]
In Firefox you can either change the input type to text or add an on.('change') trigger to it. With input type text the label behaves properly. If you want to keep it as date type you'll have to add the trigger and toggle 'active' class on the label.
