### ISSUE TITLE
Templates for parallax is not working

### ISSUE THREAD

**Issue by beingsagir** [Dogfalo/materialize#1354]
The demo for parallax is not working on chrome but firefox !

**Comment by Dogfalo** [comment]
It is working, it just may not be as apparent when using the scroll wheel because we do not control the scroll

**Comment by beingsagir** [comment]
But is not it odd when it behaves differently in different browsers ? Like, in Firefox it is super flexible and at the same time in chrome, looks like it is having fever :sob: !

[Direct Link of the subject](http://materializecss.com/templates/parallax-template/preview.html)
