### ISSUE TITLE
One image slider bug

### ISSUE THREAD

**Issue by gnnpls** [Dogfalo/materialize#1357]
Hi.
I am using your framework with phonegap for a hybrid app.
So far, most of the framework fits fine. But when I have a slider which have only one image as I swipe left or right the image is totally lost and only the bcg of the slider appears (grey). Below is a codepen example (unfortunately no images)

http://codepen.io/anon/pen/YXqdwY

**Comment by fega** [comment]
Closed due inactivity, you can reopen it if you are still having the same problem.
