### ISSUE TITLE
fixed header blinks

### ISSUE THREAD

**Issue by hriships** [Dogfalo/materialize#1359]
Hi, 
I have implemented fixed header in the app. Weird thing happening is when I scroll down a little and click the forms fields, header get blink on click event. Check the behaviour as per attached image.

![header_blink](https://cloud.githubusercontent.com/assets/3402693/7648001/104929fa-fafb-11e4-8974-da7d6184463c.gif)

**Comment by xavib** [comment]
Looks like the recurring issue with webkit and fixed elements. 

Have you tried to add -webkit-transform: translateZ(0) to the header?

**Comment by hriships** [comment]
<div class="navbar-fixed">
        <nav style="background: #900;-webkit-transform: translateZ(0);">
            <div class="nav-wrapper">
            </div>

**Comment by hriships** [comment]
```
<div class="navbar-fixed">
      <nav style="background: #900;-webkit-transform: translateZ(0);">
          <div class="nav-wrapper">....
          </div>
      </nav>
</div>
```

This way issue got fixed.
Thanks a lot @xavib

**Comment by xavib** [comment]
You are welcome @hriships. You can also add it in your CSS for all position:fixed elements

^__^

**Comment by hriships** [comment]
yes but if we add this property directly to fixed style element e.g.  .navbar-fixed (which is position:fixed) it will not work, the element is no more fixed. I have added it to child elements of position:fixed element.
Is it right way?

**Comment by hriships** [comment]
While it fixe the blink error but as you can see there is notification section on top which is position:fixed element. Now this element is not appearing.
Any help?

**Comment by xavib** [comment]
Weird. Have you checked z-index?

Anyway, this thread looks like webkit issues rather than a specific materialize issue.

**Comment by Dogfalo** [comment]
Thanks @xavib for following up on this, and yes this is webkit issue that can happen sometimes.
