### ISSUE TITLE
Button animation not working inside of card

### ISSUE THREAD

**Issue by AlexArchive** [Dogfalo/materialize#136]
I have a button inside of a `card-footer`: 

![img](http://i.imgur.com/y75vVUw.png)

``` html
<div class="card blue">
    <div class="card-content">
        <h1>{{ theme.name }}</h1>
    </div>
    <div class="card-footer">
        <p>Built by {{ theme.author }}</p>
        <a class="waves-effect waves-light btn"><i class="mdi-file-cloud"></i>View Theme</a>
    </div>
</div>
```

When I press the button, the wave effect is not invoked. 

If I take the `a` and place it _outside_ the `card-footer`, the wave effect is invoked as expected.

How can I maintain the wave effect inside of a `card-footer`? Thank you.

**Comment by bpetetot** [comment]
@ByteBlast Hi, you can trigger the wave effect by adding this into your controller :
```javascript
Waves.displayEffect();
```

**Comment by ankitparasher** [comment]
The effect is not working inside angular template. I too have similar problem.
If I use a template it doesn't work but without template it does

**Comment by Dogfalo** [comment]
Waves effect will now work on angular templates

**Comment by ByteBlast** [comment]
Good stuff lads.

**Comment by ankitparasher** [comment]
You guys are awesome :D

**Comment by Queatz** [comment]
Waves don't seem to be working on Angular 2.0 templates.

**Comment by razvanioan** [comment]
I have the same issue, and it seems that it's only if I load ALL the JS (which for now are only jQuery & materialize) asynchronous !

I have built my own asyncLoad() handler where I can define which scripts, in which order and custom callbacks, which is working as expected for years until now, see bellow the console log for the event order.

```javascript
loading jQuery
loaded jQuery
I am jQuery function(a, b)
callback for jQuery
loading materialize
loaded materialize
callback for materialize
```

I have even included a timeout between jQuery & materialize scripts (two seconds) and same result.

Funny thing is that the rest of the code used until now is working fine (tooltips, slider)

**Comment by AmareshKulkarni** [comment]
@razvanioan - The async behavior seems to be true with Aurelia as well. I had the same issue with animations and it started working once I explicitly called Waves.displayEffect();. 

Thank you.

**Comment by Ben4code** [comment]
Usually it that happend when you make multiple imports of the materialize cdn on your html file.
