### ISSUE TITLE
Cards with videos

### ISSUE THREAD

**Issue by Scarwolf** [Dogfalo/materialize#1362]
There is one big problem when using cards with videos, at least if you are using a card-title. You can no longer control the youtube video as it gets overlapped by the title.

So, you can not use the youtube controls in the following red-marked area:
![](http://i.imgur.com/kr1IkEO.png)

For me, the title is nessesary as it's a design for Wordpress.

Does anyone know a workaround?, maybe is there an option to hide the title as soon as a user starts the video?

**Comment by ajcarranquinha** [comment]
You have tryied to override ?
 .card .card-content .card-title {
        line-height: 48px; }

**Comment by ajcarranquinha** [comment]
try to override this
.card .card-image .card-title {
        position: absolute;
        bottom: 0;
        left: 0;
        padding: 20px; }

**Comment by Dogfalo** [comment]
nope, you're gonna just have to modify some of the css to make it work with the video controls
