### ISSUE TITLE
Components inside a modal

### ISSUE THREAD

**Issue by grafa** [Dogfalo/materialize#1364]
Hi guys,

I'm facing kinda strange issue. I use Slick (http://kenwheeler.github.io/slick/) and when I put some slides inside my modal window, Slick does not init itself properly. To by more specific, since closed modal is `display: none` it can't calculate it's dimensions.

I've made a quick research and I've found this https://github.com/kenwheeler/slick/issues/619
Similar issue on Bootstrap. Second comment from the bottom says it all.

So you think guys it would be possible to switch from `display` CSS property to some positioning?

P.S. I'm sorry but I think this could be quite easily done with a change inside Materialize instead of trying to figure out some dimension calculating hacks inside Slick. If not...yea, I'm sorry guys.

**Comment by mval1002** [comment]
This is just an idea, but did you try something like this in the Modal 'ready' property?

$('.your-element').slick('reInit');

**Comment by grafa** [comment]
My workaround is I initialize the Slick when the modal is opened.

**Comment by leffe322** [comment]
@grafa can you show the code solution?
