### ISSUE TITLE
Absence of documentation of dropdown functionalities

### ISSUE THREAD

**Issue by anuragagarwal561994** [Dogfalo/materialize#1367]
The code for dropdown contains 2 events open and close to let the user open and close a dropdown when the events are fired. But the documentation of this functionality is not present on the site.

http://codepen.io/Dogfalo/pen/xbzPQV an example to show the working of the triggers.

**Comment by kmmbvnr** [comment]
Seems fixed http://materializecss.com/dropdown.html

![dropdown materialize](https://cloud.githubusercontent.com/assets/282529/20561771/68829a9a-b1aa-11e6-9f74-08edf2c105cf.png)
