### ISSUE TITLE
Dropdown open/close is not toggled

### ISSUE THREAD

**Issue by anuragagarwal561994** [Dogfalo/materialize#1368]
On clicking the origin when the dropdown menu is already opened, it is not closed. Instead it opens again.
The following codepen shows a dropdown menu which is clicked 5 times to show that it is not toggled and instead opened again and again.
http://codepen.io/anon/pen/pJboXm

**Comment by rizkiandrianto** [comment]
hey @anuragagarwal561994 did you found the way how to fix this?

**Comment by anuragagarwal561994** [comment]
ya I have submitted a pull request but it got no response.
pull request #1370

**Comment by codeversed** [comment]
I tested out this patch and it does indeed fix the issue.  Hope to see this code merged soon... thanks @anuragagarwal561994!

**Comment by Muhammad-Adam** [comment]
+1

**Comment by bschnelle** [comment]
Was this fixed?  I'm still experiencing the issue in the latest version.

**Comment by anuragagarwal561994** [comment]
they closed my pull request, it wan't fixed

**Comment by bschnelle** [comment]
@acburst would you mind commenting on why this was closed?  If this is intended behavior or there is a work around would you let us know?  Thanks.

**Comment by acburst** [comment]
Are you on master? this is fixed on master. There are many commits that have changed dropdown so I didn't link any specific commit. Yes this is still an issue on the latest release but it will be fixed when we push the next release.
