### ISSUE TITLE
how to replace the "brand-logo" text with a logo .svg?

### ISSUE THREAD

**Issue by ghost** [Dogfalo/materialize#1369]

**Comment by RickCogley** [comment]
I just mimicked the main materialize site into the parallax demo: 

~~~html
  <nav class="white" role="navigation">
    <div class="nav-wrapper container">
      <a id="logo-container" href="#" class="brand-logo"><object id="front-page-logo" class="responsive-img" width="170px" type="image/svg+xml" data="img/mylogo.svg">Your browser does not support SVG.</object></a>

      <ul class="right hide-on-med-and-down">
        <li><a href="#">Navbar Link</a></li>
      </ul>

      <ul id="nav-mobile" class="side-nav">
        <li><a href="#">Navbar Link</a></li>
      </ul>
      <a href="#" data-activates="nav-mobile" class="button-collapse"><i class="mdi-navigation-menu"></i></a>
    </div>
  </nav>
~~~

I want to know:

* if I can make it responsive
* if I can make the logo just fit within the nav-wrapper, without needing the width="170px" statement

**Comment by DarwinDLRD** [comment]
I too have this doubt.
Fit logo "svg" without using "width"

**Comment by DarwinDLRD** [comment]
I too have this doubt.
Fit logo "svg" without using "width"


*Sorry ... I closed the discussion by mistake*

**Comment by truenorth** [comment]
@RickCogley Not sure if this helps, but here's an example with a SVG in `.brand-logo` sgasser.github.io/ember-cli-materialize

**Comment by RickCogley** [comment]
@truenorth thanks! A cursory look at the source of that page shows that the trick is to just use the svg file as an img. I'll give it whirl.

**Comment by truenorth** [comment]
@RickCogley you could also add the SVG inline to your HTML, and it should work too

**Comment by RickCogley** [comment]
thanks @truenorth :-)

**Comment by DarwinDLRD** [comment]
@truenorth link offline  sgasser.github.io/ember-cli-materialize :(

**Comment by truenorth** [comment]
@DarwinDLRD I maintain the ember wrapper materialize now :) mike.works/ember-cli-materialize/
