### ISSUE TITLE
Browser support

### ISSUE THREAD

**Issue by pavlospolianidis** [Dogfalo/materialize#137]
What browsers are you currently supporting?

**Comment by genirahul** [comment]
6 months since last update, any update on cross browser support issue?

**Comment by Dogfalo** [comment]
Readme states what browsers are supported

On Tue, May 26, 2015 at 8:17 PM, Rahul Ranjan <notifications@github.com>
wrote:

> 6 months since last update, any update on cross browser support issue?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Dogfalo/materialize/issues/137#issuecomment-105741708>
> .
>



-- 
Doggy sends his greetings from Mars.

**Comment by genirahul** [comment]
Thank you for quick reply. One doubt, there is no mention of Opera browser in read me. So you guys don't support opera browser or haven't tested in opera browser yet?
