### ISSUE TITLE
break tabs into more than 1 line

### ISSUE THREAD

**Issue by kartono1102** [Dogfalo/materialize#1373]
hi, i want to ask how to set tabs into 2 lines if i'm open it on mobile. i have 7 <li> on 1 tabs
the tabs:
http://codepen.io/anon/pen/Nqrqmg
it is fine when open it on laptop, but when it goes mobile, it is stack each other.
i want to break it into 2 lines, how to do that?

**Comment by acburst** [comment]
This is part of the material design principle to never stack tabs, There shouldn't be an overwhelming number of tabs on the mobile experience.
