### ISSUE TITLE
Strange grid behavior on small devices

### ISSUE THREAD

**Issue by geoextra** [Dogfalo/materialize#1377]
Hello everybody,
I have a problem in a personal project and really don't know if it's a bug or just my stupidity, so I'm sorry if I waste your time ;-)

I have a grid with six columns, which are in one line on large and medium devices and in two on small devices, so the classes are `.col.s4.m2.l2`. But if the second column is larger than the third a for me strange wrap was created:

[Codepen](http://codepen.io/anon/pen/waWoRo)
![Screenshot](https://cloud.githubusercontent.com/assets/8628685/7670435/82cc3256-fca4-11e4-8c89-a197fb327813.png)

Can someone look at this issue or tell me how to do it the right way? :smile: 

Thanks in advance
geoextra

**Comment by Dogfalo** [comment]
columns should not exceed 12 in a row.

**Comment by geoextra** [comment]
Sorry for my lack of understanding, but can you tell me where the difference between `.col.s4.m2.l2` and `.col.s12.m6.l3` (from the examples) is? I thing my structure is working without the checkboxes, so I see the problem there...

**Comment by acburst** [comment]
This will happen when you put many columns into a single row with many different heights. To make things work perfectly and divide into the different number of columns, the height needs to stay constant. You can look into a library that will do this for dynamic heights: masonry.desandro.com
