### ISSUE TITLE
tooltop.js problem when another tooltip is initialize

### ISSUE THREAD

**Issue by itsmechlark** [Dogfalo/materialize#1386]
This happen when another tooltip is setup after the previous tooltip is setup.

Problem at [tooltip.js#L16](https://github.com/Dogfalo/materialize/blob/ce5e0ba9f0ac2e32e0f2d9f8859928af32c6b0dd/js/tooltip.js#L16)

The previous container of the tooltip is remove after the second tooltip is setup.

``` html
<a id="tp1" class="btn tooltipped col s4 offset-s4 l2 offset-l1" data-position="bottom" data-delay="50" data-tooltip="I'm TP1!">TP1</a>
<a id="tp2" class="btn tooltipped col s4 offset-s4 l2 offset-l1" data-position="bottom" data-delay="50" data-tooltip="Goodbye TP1!">TP2</a>
<script>
$(document).on("click", "#tp1", function(){
    if (!$("#tp2").is(".ok")){
        $("#tp2").addClass("ok").tooltip();
    };
});
$("#tp1").tooltip();
</script>
```

Check this https://jsfiddle.net/8wxa2pym/

**Comment by itsmechlark** [comment]
PING

**Comment by toben** [comment]
I had the same issue. You have to remove the line :

**Comment by Fed03** [comment]
Very serious bug, @Dogfalo

**Comment by webbiesdk** [comment]
@toben, you cant just remove that line, then we risk having a lot of .material-tooltip divs floating around, that are never used. 

My pull-request should however fix this problem in a good way.

**Comment by carlosperate** [comment]
Has this issue been resolved since the merge of https://github.com/Dogfalo/materialize/pull/1547 ?

**Comment by webbiesdk** [comment]
I think it has, now the API is such that previous tooltips are only ever removed if you call tooltip like: `.tooltip("remove");`. 

So yeah, IMO it has been fixed.

**Comment by itsmechlark** [comment]
#1547, I think doing this every tooltip initialisation is not right it should be like [bootstrap/tooltip.js](https://github.com/twbs/bootstrap/blob/master/js/tooltip.js). We all know that `tooltip.js` is `materializecss` is just the same but differ on how it animate and looks. 

All js library should be structured well, just a suggestion.

**Comment by merlano17** [comment]
There is simple solution for this for the time being till they fix it
I use this 

```
setInterval(clearTooltip, 6000);
function clearTooltip() {
    $('.material-tooltip').hide();
  }

So every 6 seconds it will hide all the tooltips which are not closed correctly and stuck on the screen

**Comment by webbiesdk** [comment]
@merlano17 
The solution you are writing there might be a solution to the problem over at #2901, but it doesn't fix the issue described here. Which was that one tooltip disappeared when initializing another tooltip. 

The issue here has been fixed IMO, so I don't know why it hasn't been closed yet.

**Comment by fega** [comment]
I tested the fiddle example with the latest version and it worked, please reopen if you are still having the problem
