### ISSUE TITLE
Allow toasts to be closable

### ISSUE THREAD

**Issue by jcapogna** [Dogfalo/materialize#1389]
I want to leave a toast up long enough for the user to see it, but I also want them to able to close it and go on with their business. It would be nice if toasts were closable, at least an option. 

I was able to (crudely) implement this myself with the following code, which adds a close icon with an onclick handler that removes the toast from the DOM. 

```
generateDismissableToast: function(message, displayLength, className, completeCallback) {
        var htmlMessage = '<span>' + message + '</span><a onclick="this.parentElement.parentElement.parentElement.removeChild(this.parentElement.parentElement)"><i class="right mdi-navigation-close"></i></a>';
        Materialize.toast(htmlMessage, displayLength, className, completeCallback);
    }
```

**Comment by acburst** [comment]
Toasts are currently dismissible by swiping them away. This works both with touch screens and on desktops

**Comment by jcapogna** [comment]
That was not intuitive to me or anyone that I showed toasts to. Is it within material UI guidelines to swipe to dismiss on desktops?

**Comment by jacek213** [comment]
I wonder how many people thought about swiping them away on desktop... :)

**Comment by pumpknhd** [comment]
In case anyone is still looking for a solution, this will dismiss it a bit more elegantly:

<a onclick='M.Toast.getInstance(this.parentElement).dismiss();'>close or icon</a>
