### ISSUE TITLE
Find a way to override datepicker input style

### ISSUE THREAD

**Issue by Dogfalo** [Dogfalo/materialize#139]

**Comment by CoDEmanX** [comment]
As in UI or the formatting of the picked date? (ISO / US / DE / whatever notation)

**Comment by albertpak** [comment]
:+1: would be great to add functionality like in jQuery UI - specify format, altField, and altFormat

**Comment by divinespear** [comment]
How about [moment.js](http://momentjs.com)?
It has good options (include i18n), and some bootstrap-based date(time)picker plugins using this well.

**Comment by kytenz** [comment]
Tried it and I can confirm all options work as @albertpak said. We should add the documentation to http://materializecss.com :)

**Comment by rodofatos** [comment]
How about the elements with classes picker__date-display and picker_weekday-display elements ? Can we set for those 2 elements in order to change colors for date background and weekday header at the top of the window ?

Thanks

**Comment by tomscholz** [comment]
Closed due inactivity. Feel free to reopen it, if it's still necessary.
