### ISSUE TITLE
Textarea resizing is broken when setting custom fonts

### ISSUE THREAD

**Issue by francislavoie** [Dogfalo/materialize#1391]
I'm using the Courier font-family in one of my textareas and a specific font-size. The `div.hiddendiv` element doesn't inherit the font CSS from the textarea when calculating the height so it ends up being incorrect. Applying the font CSS to `div.hiddendiv` fixes this.

**Comment by francislavoie** [comment]
Also if `wrap="off"` is set on the textarea, then extra lines are added to the end result of the textarea height. `overflow-x:hidden;` should be set on the hidden div in this case for better calculation.

**Comment by francislavoie** [comment]
As a quick fix without modifying the lib, I just threw this into my script:

    $('.materialize-textarea').on('keyup keydown', function() {
      $('.hiddendiv').first().css("font-family", $(this).css("font-family"))
        .css("font-size", $(this).css("font-size"))
        .css("overflow-wrap", ($(this).attr("wrap") === "off") ? "normal" : "break-word")
        .css("white-space", ($(this).attr("wrap") === "off") ? "pre" : "pre-wrap");
    }).keyup();

**Comment by acburst** [comment]
Fixed in 89eca5ca853f1e7b1690fdc9567a5185dc7856ca
