### ISSUE TITLE
Improve "select" 

### ISSUE THREAD

**Issue by Rebolon** [Dogfalo/materialize#1393]
I've played with select input and i'm not satisfied (or i'm mis-using it) : 
When i build my select box i set a name and id, but as materialize_select build an input text field, how my JS code can identify this new field ?

It would be cool that this new input can be customized with name and id. We could add data-name and data-id inside the select node, and materialize_select could use it to create the new text field (instead of using the uid generator).

**Comment by carlosperate** [comment]
Well, why do you need to edit the "materialize created" select? you can edit the original select and recreate the materialize one. If the framework allows editing of the "materialize created" select (an styled `ul` list) then it just opens it up for a lot more bugs and corner cases.

**Comment by Rebolon** [comment]
Maybe i mis-use the component, but with meteor, i need to spy the events on the select box and it's not clear how to do that.

**Comment by carlosperate** [comment]
It should work fine in meteor, there are a few open and closed issues regarding this topic. Have a look at https://github.com/Dogfalo/materialize/issues/1062 and if that is not helpful you'll be able to find other discussions using the issue tracker search option.

**Comment by TyrionGraphiste** [comment]
Hi, the id is specified as data-id to the new input and not erased anymore.

**Comment by tomscholz** [comment]
Closed due inactivity, feel free to reopen it if it is still necessary
