### ISSUE TITLE
Icon Prefix with Select design issue

### ISSUE THREAD

**Issue by lordplagus02** [Dogfalo/materialize#1394]
I found that if you use an icon prefix with a select, it extends the "input line" below the icon, and once you've selected a value it overlaps the icon. 
![selectissue1](https://cloud.githubusercontent.com/assets/11164562/7749167/6a4ffad0-ffcb-11e4-94de-8046220eccbc.PNG)
![selectissue2](https://cloud.githubusercontent.com/assets/11164562/7749168/6a56057e-ffcb-11e4-83f3-70e16e9cce91.PNG)

**Comment by carlosperate** [comment]
This is a duplicate of https://github.com/Dogfalo/materialize/issues/853
