### ISSUE TITLE
Range slider not working with labels properly (Chrome)

### ISSUE THREAD

**Issue by lordplagus02** [Dogfalo/materialize#1395]
Please see the screenshot, the range slider isn't displaying correctly when you want to label it (and add an icon prefix)
![rangeissue1](https://cloud.githubusercontent.com/assets/11164562/7749363/3dd524c4-ffcd-11e4-87d7-b6ab77ce1432.PNG)

**Comment by yetanotherse** [comment]
+1

**Comment by fega** [comment]
Already solved http://codepen.io/fega/pen/VpRVVO?editors=1000
