### ISSUE TITLE
Typo on Helpers.html

### ISSUE THREAD

**Issue by Pizzaface** [Dogfalo/materialize#1398]
# Truncation
To truncate long lines of text in an ellipsis, add the class truncate to the tag which contains the text. See an **exaple** below of a header being truncated inside a card.

[Screenshot](https://cloud.githubusercontent.com/assets/10016234/7761683/d6b0f924-fff6-11e4-82d0-9e55f250fe5f.PNG)

**Comment by truenorth** [comment]
Looks like this has already been fixed https://github.com/Dogfalo/materialize/blob/master/jade/page-contents/helpers_content.html#L113
