### ISSUE TITLE
Input labels overlay problem

### ISSUE THREAD

**Issue by turalsprofile** [Dogfalo/materialize#1399]
Here is what I get after hiding and showing div using jquery

![screen shot 2015-05-22 at 12 40 24](https://cloud.githubusercontent.com/assets/724507/7766172/00b15f14-0080-11e5-95c6-18879e68458f.png)

How can I programmatically refresh the form?

**Comment by Isprago** [comment]
add class "active"

**Comment by turalsprofile** [comment]
is there anyway to refresh form and add active class to all filled inputs' labels

**Comment by turalsprofile** [comment]
Becase as far as I know, initially when you have values and open page, materialize does it automatically

**Comment by RakanNimer** [comment]
Can you provide a codepen ?

**Comment by Dogfalo** [comment]
Call `Materialize.updateTextFields()`

**Comment by hriships** [comment]
its not working in my case
