### ISSUE TITLE
<select> value with js

### ISSUE THREAD

**Issue by Sajgoniarz** [Dogfalo/materialize#1400]
I'm struggling with it quite a while, and I can't find any solution to retrieve dropdown / select value. Closest  as I get was when I closed select inside container with id, and onClick event on it. Then I tried to retrieve value of dynamically created ul list with css path, but your lib is adding active class to previously selected element, what means I've got previous value. When you click dropdown/select item value of select is not changing, or even html in any dom element, it's only visual change, which can be caught after next selection.

**Comment by Sajgoniarz** [comment]
#1401 FIXED w8 for merge

**Comment by Dogfalo** [comment]
Just use  .val() on the original select

**Comment by Dogfalo** [comment]
Don't see why this is necessary

**Comment by Sajgoniarz** [comment]
It would be nice to see it in documentation.

**Comment by Dogfalo** [comment]
It's the same as on any select

**Comment by jdcauley** [comment]
Thats not true on a select you set a change handler, we don't have that.
