### ISSUE TITLE
Linebreak in Tooltip

### ISSUE THREAD

**Issue by KdogM** [Dogfalo/materialize#1402]
Hey there,

first of all: Materialize is really great! 

I'm using a tooltip, but using a <br/> Tag does not generate a newline, but is displayed inside the tooltip.

Is there a possibility to create a newline?

Yours KdogM

**Comment by Dogfalo** [comment]
Yea, this is a general css question though. Just use `white-space: normal`.

**Comment by KdogM** [comment]
Oh, great. Thank You for Your reply! Maybe that's worth of an example on the homepage.

Yours
KdogM

**Comment by KdogM** [comment]
You mean the white-space attribute. I used:
<code>
.material-tooltip {
    white-space: pre;
}
</code>
 in css/style.css
which worked like a charm!

**Comment by St3ph-fr** [comment]
Hi

On my side I used the tag data-html="true" by this way I can add a line break by adding the <br> html tag.

<div class="tooltipped" data-position="bottom" data-delay="50" data-tooltip="Some text"></div>
become 
<div class="tooltipped" data-html="true" data-position="bottom" data-delay="50" data-tooltip="Some text<br>Second line"></div>

Stéphane
