### ISSUE TITLE
Update docs to explain that modal opened programatically takes the settings from its arguments and not the modal init

### ISSUE THREAD

**Issue by carlosperate** [Dogfalo/materialize#1406]
If the modal settings are edited in the`$('.modal-trigger').leanModal()` init call and the the modal is triggered programatically, it does not follow the personalised settings.

CodePen: http://codepen.io/anon/pen/rVMQEb

Edit: Modified titled to indicate issue with documentation and not code.

**Comment by Dogfalo** [comment]
This is as expected. Just pass in the same options or instead trigger a
click on the modal trigger

**Comment by carlosperate** [comment]
Oh, had no idea the settings could be passed to the `openModal` function. If I change the title would you mind leaving the issue open to edit the documentation?

**Comment by tomscholz** [comment]
LeanModal is no longer used
