### ISSUE TITLE
right sideNav on large screen appears on left on page load

### ISSUE THREAD

**Issue by iSuslov** [Dogfalo/materialize#1407]
When page is loaded right sideNav sticks to the left. After first window resize it goes back to the right. Error is on line №3643

```
if ($(window).width() > 992) {
     menu_id.css('left', 0);
}
```

should be

```
if ($(window).width() > 992) {
     if (options.edge == 'left') {
          menu_id.css('left', 0);
     } else{
          menu_id.css('right', 0);
    }
}
```

**Comment by iSuslov** [comment]
Also if having 2 panels, on the right and one the left, another bug happens. 
Line № 3627
```
$('body').append( $('<div class="drag-target"></div>'));
``` 

should be replaced with

```
var dragTarget = $('<div class="drag-target"></div>');
$('body').append(dragTarget);
```

and then, all `$('.drag-target')` should be replaced with `dragTarget`

And finally, when clicking outside sideNav, it behaves badly since you can click to dragTarget of another sideNav if it lays 'higher'.
Workaround is: near the line 3880 insert `$('body').append(dragTarget)`, so your active drag target will be always on top.

```
$this.click(function () {
                    if (menuOut == true) {
                        menuOut = false;
                        panning = false;
                        removeMenu();
                    }
                    else {
                        if (options.edge === 'left') {
```

replace with 

```
$this.click(function () {
                    if (menuOut == true) {
                        menuOut = false;
                        panning = false;
                        removeMenu();
                    }
                    else {
                        $("body").append(dragTarget)
                        if (options.edge === 'left') {
```

**Comment by fega** [comment]
I'm unable to reproduce it, also closed due inactivity

If you are still having the issue, please reopen and send us a codepen or fiddle example

Thanks.
