### ISSUE TITLE
Remove mention of flexbox from Footer demo

### ISSUE THREAD

**Issue by dandv** [Dogfalo/materialize#1409]
Since [v0.93.1 dropped support for flexbox](https://github.com/Dogfalo/materialize/blob/master/CHANGELOG.md), it should be removed from the [footer demo page](https://github.com/Dogfalo/materialize/blob/master/jade/page-contents/footer_content.html#L10).

This is unfortunate. I'd much rather see flexbox reinstated - #771.

**Comment by xorinzor** [comment]
This is only for the sticky footer, for which flexbox is actually still used.

**Comment by Dogfalo** [comment]
Flexbox is used in the footer-copyright
