### ISSUE TITLE
Taking font-size into account when resizing textarea solution

### ISSUE THREAD

**Issue by nakhbari** [Dogfalo/materialize#1411]
I was using the textarea with a specified font-size and it's height calculation is off. I added the following to textareaAutoResize($textarea)

"hiddenDiv.css('font-size', $textarea.css('font-size'));"

Works like a charm now!

**Comment by acburst** [comment]
This is not in the current release but I have already fixed this issue on master 89eca5ca853f1e7b1690fdc9567a5185dc7856ca
