### ISSUE TITLE
No sass on bower component

### ISSUE THREAD

**Issue by abcsds** [Dogfalo/materialize#1412]
Hi guys,
I was about to make a for for a materialize-sass bower component, but figured I should ask first, since it's just a couple lines of code, and bower components are usually for development. Is there any specific reason for the sass files not to be included in the bower component? 
If you wish, you could make me a branch to fork, and i'll PR back with a development bower component.

Cheers!

**Comment by gnicol-bzh** [comment]
Hello.
I was about to ask the same question. 

What about replacing in `bower.json` (**not tested**):
```json
"bin/materialize.css",
```
by
```json
"sass/materialize.scss",
```
And somewhere in the `main.scss` of an app, we could add
```scss
$material-variable-i-want-to-override: "new value";
// bower:scss
// endbower
```
So when dependencies job is done (wiredep, ...), we'll have: 
```scss
$material-variable-i-want-to-override: "new value";
// bower:scss
@import "materialize/sass/materialize.scss";
// endbower
```
...and Materialize compiled in our final `main.css`.

May be neccessary to manually override font paths:
```scss
$roboto-font-path: "../bower_components/materialize/font/roboto/";
$icons-font-path: "../bower_components/materialize/font/material-design-icons/";
$material-variable-i-want-to-override: "new value";
// bower:scss
// endbower
```

**Comment by acburst** [comment]
Fixed in latest release
