### ISSUE TITLE
Fixed action button needs a long press to reveal inner buttons on Windows phone

### ISSUE THREAD

**Issue by arcoirislabs** [Dogfalo/materialize#1413]
When running on Windows phone, a single click never reveals the inner buttons. It needs a long press.

**Comment by filippomartini** [comment]
I've got the same issue... A on click dropdown would be better since the long press open the Windows dropdown too

**Comment by fega** [comment]
Hello @arcoirislabs and @filippomartini 
I'm closing this due of inactivity, please reopen it if you are still having problems

Also, due that not all of us have a windows phone, if someone can check or fix, it will be very appreciated.
