### ISSUE TITLE
two sideNav`s buggy on close

### ISSUE THREAD

**Issue by iSuslov** [Dogfalo/materialize#1417]
If having 2 panels, on the right and one the left, you can not close sideNav by clicking outside, since you are clicking on another sideNav`s drag-target. 
Line № 3627
```
$('body').append( $('<div class="drag-target"></div>'));
``` 

should be replaced with

```
var dragTarget = $('<div class="drag-target"></div>');
$('body').append(dragTarget);
```

and then, all `$('.drag-target')` should be replaced with `dragTarget`

And finally, when clicking outside sideNav, it behaves badly since you can click to dragTarget of another sideNav if it lays 'higher'.
Workaround is: near the line 3880 insert `$('body').append(dragTarget)`, so your active drag target will be always on top.

```
$this.click(function () {
                    if (menuOut == true) {
                        menuOut = false;
                        panning = false;
                        removeMenu();
                    }
                    else {
                        if (options.edge === 'left') {
```

replace with 

```
$this.click(function () {
                    if (menuOut == true) {
                        menuOut = false;
                        panning = false;
                        removeMenu();
                    }
                    else {
                        $("body").append(dragTarget)
                        if (options.edge === 'left') {
```

**Comment by imjoeybrennan** [comment]
+1

**Comment by iSuslov** [comment]
Guys! I told you exactly what causes this bug. I even did a pull request, are you thinking it's good to just ignore it or you going to fix it another way? Please make something

**Comment by erredeco** [comment]
this solution seems to mess the tabs component... can someone check?
