### ISSUE TITLE
fixed sidenav with closeOnClick enabled

### ISSUE THREAD

**Issue by rgoomar** [Dogfalo/materialize#1426]
So, currently, if you have a fixed sideNav and you want `closeOnClick` "enabled" for your mobile side, you have to add in a work around to make sure that if a user clicks and is on a full desktop version, it doesn't hide the side nav when it should be fixed.

TLDR; You can't have `closeOnClick` enabled with a fixed side nav

A workaround I created for this is:

``` javascript
  // Side Navigation fix
  $('.side-nav li a').on('click', function(e) {
    windowsize = $(window).width();
    if (windowsize < 992) {
      $('.button-collapse').sideNav('hide');
    }
  });
```

This is probably something to look into since it is useful to have the sidenav close on click on mobile, but stay fixed on desktop screens.

**Comment by JulianKingman** [comment]
Thanks for the fix, this is kind of annoying.

**Comment by rgoomar** [comment]
@Dogfalo any update on this?

**Comment by lijoantony** [comment]
@rgoomar Thanks for the work around. However, it didn't fully work for me.
Side menu is getting hidden, but #sidenav-overlay remains.
I had to do something like this,

```javascript
var windowsize = $(window).width();
if (windowsize < 992) {
     $('.button-collapse').sideNav('hide');
     setTimeout(function(){
         $('.button-collapse').sideNav('hide');
     }, 500);
}
```
Second hide is to hide #sidenav-overlay.
Even `setTimeout(..., 0);` didn't help there.

**Comment by ronniebermejo** [comment]
#### angularized fix
```
(function () {
  'use strict';

  angular
    .module('buggy')
    .directive('sideNavBar', sideNavBar);

  sideNavBar.$inject = [];
  function sideNavBar() {
    return {
      restrict: 'C',
      require: '?ngModel',
      link: function (scope, elem, attrs, ctrl) {
        $(".button-collapse").sideNav();


        var SIDEBAR_BREAK_POINT = 992;
        var windowsize = $(window).width();
        if (windowsize < SIDEBAR_BREAK_POINT) {
          $('.button-collapse').sideNav('hide');
          setTimeout(function(){
            $('.button-collapse').sideNav('hide');
          }, 500);
        }
      }
    }
  };
})();
```

**Comment by jacek213** [comment]
this is a major issue, can we expect a fix?

**Comment by MuyBien** [comment]
+1

**Comment by Almaju** [comment]
+1

**Comment by belgacea** [comment]
+1

**Comment by asonj** [comment]
This allows you to keep the full screen nav open while still being able to click to close on mobile devices.

 ```
 if (window.matchMedia("(min-width: 992px)").matches) {
  /* the viewport is at least 992 pixels wide */
   $('.button-collapse').sideNav({
        closeOnClick: false, // Closes side-nav on <a> clicks, useful for Angular/Meteor
        }
    );
  } else {
    /* the viewport is less than 992 pixels wide */
     $('.button-collapse').sideNav({
          closeOnClick: false, // Closes side-nav on <a> clicks, useful for Angular/Meteor
          }
    );
  }

```

**Comment by tomscholz** [comment]
Fixed via https://github.com/Dogfalo/materialize/pull/4299

**Comment by netopapa** [comment]
It works!
Valeu, parceiro

**Comment by davis016** [comment]
sorry guys, i tried to hide the navbar afeter click un the links, but doesnt work, Where, i have to put this code.

if (window.matchMedia("(min-width: 992px)").matches) {
 /* the viewport is at least 992 pixels wide */
  $('.button-collapse').sideNav({
       closeOnClick: false, // Closes side-nav on <a> clicks, useful for Angular/Meteor
       }
   );
 } else {
   /* the viewport is less than 992 pixels wide */
    $('.button-collapse').sideNav({
         closeOnClick: true, // Closes side-nav on <a> clicks, useful for Angular/Meteor
         }
   );
 }

i am working with react and materialize.

thanks in advance.
