### ISSUE TITLE
"hiddendiv common" shows up

### ISSUE THREAD

**Issue by wrexlabifle** [Dogfalo/materialize#1427]
a "hiddendiv common" shows up on my page without me calling it in any way, but the most frightening is that it contained a link to faceporn ! what is that ??? have you been hacked ?

**Comment by Dogfalo** [comment]
It's your ad block

**Comment by carlosperate** [comment]
> It's your ad block 

Disagree with that, I've noticed this in two of my Materialize projects (not in any other project with other frameworks).

Probably coming from here: https://github.com/Dogfalo/materialize/blob/master/js/forms.js#L98 

Which is interesting, as one of the two projects I have it does not contain a single textarea.

**Comment by Dogfalo** [comment]
You can read more here https://github.com/chrisaljoudi/uBlock/issues/161

**Comment by carlosperate** [comment]
I wasn't refering to the faceporn link (I do not have adblock nor ublock), just the injection of `<div class="hiddendiv common"></div>` into the DOM by Materialize.

**Comment by ibart** [comment]
That link is create for textareas but it is apparently not used at all.

**Comment by Thanood** [comment]
@ibart It is used for auto resizing:
https://github.com/Dogfalo/materialize/blob/master/js/forms.js#L111

**Comment by abnerwebprorgammer** [comment]
If you preffer to remove this function you can decompress materialize.min.js or look for this piece of code
e.length || (e = a('<div class="hiddendiv common"></div>'), a("body").append(e)); and comment it.

**Comment by DanielRuf** [comment]
Right, still the sae but not using any textarea input or form.

**Comment by onyxisland** [comment]
hi i am using materialize-textarea for its auto resize feature, but whatever i type into my textarea shows up in the "hiddendiv common" div at the bottom for all to see..
