### ISSUE TITLE
Checkbox touch area 

### ISSUE THREAD

**Issue by nante** [Dogfalo/materialize#1429]
While trying to implement checkboxes I've encountered an error where the touch area would be moved down from the checkbox's label. 
Here's a screencast: 
http://screencast.com/t/16J8OoP6zpf

This happened when the container had position: fixed attribute.

What fixed the issue was setting the container's height to 100vh. 

//Edit 
Apparently it only fixed the issue on desktop emulated phone. 
While testing it on an actual device, the error still occurs.

**Comment by Dogfalo** [comment]
Its just a problem with the tap highlight on phones which is usually off and we can't fix this. Just turn off the tap highlight and use an active pseudo state instead
