### ISSUE TITLE
Fixed Nav bar position not show in position

### ISSUE THREAD

**Issue by Neotrixsx** [Dogfalo/materialize#1432]
Hi,
I uses Fixed Nav bar In my Application. position  of that nav bar not show in position its not looking good.
HTML Code:-

     <div class="navbar-fixed">
        <nav>
           <div class="nav-wrapper headercol z-depth-1 centr">
            <a href="#!">Test App</a>
          </div>
        </nav>
      </div>

Please Help Me.
![screenshot_2015-05-27-08-17-02](https://cloud.githubusercontent.com/assets/7522102/7827821/4a493b16-0449-11e5-8d6c-f1f3860a1c4e.png)

**Comment by patrickgordon** [comment]
```
<div class="navbar-fixed"> 
  <nav>
    <div class="nav-wrapper">
      <a href="#" class="brand-logo">Test App</a>
    </div>
  </nav>
</div>
```

Follow the examples:
http://materializecss.com/navbar.html

**Comment by acburst** [comment]
It looks like your body has the default margin on it. Try adding this to your css:

```
body {
  margin: 0;
}
```
