### ISSUE TITLE
raise-effect !feature request

### ISSUE THREAD

**Issue by dbauszus** [Dogfalo/materialize#1435]
I like the effect of raising buttons. But this effect should not be exclusive to buttons but rather be applied to any object like the wave-effect for example.

For now I solve this by a bit of jQuery script:

$('.card').hover(
	function() {
		$(this).toggleClass('z-depth-2');},
	function() {
		$(this).toggleClass('z-depth-2');}
	);

That solution however is not ideal as it may cause some flickering of the card element.

**Comment by Dogfalo** [comment]
You should just transition between the box shadows which you can see in the css file.
