### ISSUE TITLE
active tabs not set (red underline - onready) when used in collapsable body 

### ISSUE THREAD

**Issue by rand99** [Dogfalo/materialize#1438]
https://jsfiddle.net/za8ky8f3/2/

beautiful project by the way.

**Comment by cherimarie** [comment]
I'm having the same problem- when section first expands, no underline is visible. If I click a tab or resize the window, underline appears and works as expected.

**Comment by acburst** [comment]
Collapsible now has callbacks for onOpen and onClose. You can initialize tabs within these callbacks
