### ISSUE TITLE
Karma Configuration for materialize.js

### ISSUE THREAD

**Issue by rkusuma** [Dogfalo/materialize#1439]
I got this error when running karma test in phantomjs. I already add bind-polyfill.js for phantomjs but it still not working. Any solution?

```
ERROR [karma]: TypeError: 'undefined' is not a function (evaluating 'document.querySelectorAll.bind(document)')
at http://localhost:9876/base/bower_components/materialize/bin/materialize.js?a8dba06400b1ea0562876ad690d94e2ff9a9236e:4
```

**Comment by truenorth** [comment]
@rkusuma you might want to check out #1375

**Comment by rkusuma** [comment]
Thanks @truenorth for the info..  but my project using Karma as test runner.

**Comment by anthonymjones** [comment]
I'm not sure of a real solution here, but a bandaid would be to use Chrome as the browser instead of PhantomJS.

**Comment by fega** [comment]
Closed due inactivity, feel free to reopen it if it is still necessary.

**Comment by IAMtheIAM** [comment]
I also wonder how to use Karma to test code using Materializecss. I get
```
 TypeError: undefined is not a constructor (evaluating 'Materialize.updateTextFields()
```
Not sure if I'm supposed to spy, mock, or stub materialize, and how to do that? Any tips are appreciated.
