### ISSUE TITLE
Form field error message is not displayed

### ISSUE THREAD

**Issue by Flaburgan** [Dogfalo/materialize#1441]
Materialize does indicate when a field is not valid by turning the border-bottom to red, but the error message (is not a valid email, etc) is not displayed to the user.

**Comment by dhawken** [comment]
You need to manage that yourself.  How are you specifying the message?

**Comment by Flaburgan** [comment]
@dhawken I'm talking about the native HTML5 messages, like with `<input type="email" />` for example.

**Comment by Flaburgan** [comment]
The [Google specification](http://www.google.com/design/spec/components/text-fields.html#text-fields-single-line-text-field) displays the error message like this:
![](http://material-design.storage.googleapis.com/publish/material_v_3/material_ext_publish/0Bx4BSt6jniD7NjBXVDd4eUhWbDA/components_textfields_single4.png)

**Comment by Flaburgan** [comment]
I personally use [parsley.js](http://parsleyjs.org/) to deal with custom error messages.

**Comment by dhawken** [comment]
AFAIK, the default HTML5 messages should still appear when you submit the form, but there isn't anything to make messages like what the google spec says to show occur.

**Comment by Flaburgan** [comment]
>AFAIK, the default HTML5 messages should still appear when you submit the form

Oh, you're right. And it keeps the default browser style.

**Comment by acburst** [comment]
This feature for text inputs is implemented in master but not yet released

**Comment by Flaburgan** [comment]
For reference: https://github.com/Dogfalo/materialize/issues/361

**Comment by lepatlamass** [comment]
Materialised is total nonsense of some can't use it don't know why you guys
are just commenting on it if no one can answer me or if I can't run it.
Crappy!!!!!!
