### ISSUE TITLE
Date picker not showing correctly

### ISSUE THREAD

**Issue by Pablotis** [Dogfalo/materialize#1443]
I have done as @Dogfalo told me in #1442 but it still show incorrectly:
![image](https://cloud.githubusercontent.com/assets/10696506/7869369/8fd530f6-0582-11e5-986d-0c9cd863a24c.png)
I have uploaded it to Pen: http://codepen.io/Pablotis/pen/vOgLOL
You can see the full page here: http://estoesunaprueba.ddns.net/index.php
You will need to login using user "test" with password "test" and go to Mi Cuenta

A lot of Thanks!!!

**Comment by Dogfalo** [comment]
You didnt add the javascript. If you need more assistance please post on stack  overflow as this is not a bug
