### ISSUE TITLE
waves effect in Rails 4.

### ISSUE THREAD

**Issue by kockok** [Dogfalo/materialize#1445]
The screen recording: https://vid.me/e/nFJk

The problem is that when I first load the page, waves effect runs perfectly.
However, when I click the root link, such effect loses its functionality.
I suspect this is related to  turubolinks in rails 4.

Please help.

**Comment by stefanosc** [comment]
There is an easy way to find out, turn off turbolinks and see if it works  
Also check this out: https://github.com/mkhairi/materialize-sass/issues/18

**Comment by Dogfalo** [comment]
or just call `Waves.displayEffect` inside http://stackoverflow.com/questions/18770517/rails-4-how-to-use-document-ready-with-turbo-links

**Comment by kockok** [comment]
`Waves.displayEffect` solves the problem.
