### ISSUE TITLE
Fix : Fixed button ul overlapping the reveal card reveal trigger causing fixed button's inner ul to reveal

### ISSUE THREAD

**Issue by arcoirislabs** [Dogfalo/materialize#1446]
.fixed-action-btn ul {
    left: 0;
    right: 0;
    text-align: center;
    position: absolute;
    bottom: 64px; 
    display: none; /* add this line in materialize.css*/
  }
add a click listener to the fixed button to add the display: block css

**Comment by acburst** [comment]
Can you add a codepen showing this in action?

**Comment by arcoirislabs** [comment]
Yes we will present the fix in codepen

**Comment by Dogfalo** [comment]
The behavior of the FAB was changed in d2deb3bb8353a4be201da835e39d533fce896dc1
