### ISSUE TITLE
Select gets cut off at edge of card

### ISSUE THREAD

**Issue by thomasvanlankveld** [Dogfalo/materialize#1447]
Material select boxes at the right of your cards get cut off, ones an the bottom become unusable.

![screen shot 2015-05-29 at 12 14 23](https://cloud.githubusercontent.com/assets/5240626/7880686/49a2dc76-05fc-11e5-8c7f-c5608e77e896.png)

Browser default select boxes still work, but I don't want the last field to suddenly not be a material field when all the others are.

**Comment by acburst** [comment]
This has been fixed in master if you want to try pulling the latest files and testing that. It is not currently in release but we will try to release as soon as possible.

**Comment by Nicks182** [comment]
v0.97 was released 10 days ago, but I get the same issue. Was the fix added to that version?

**Comment by Nicks182** [comment]
So to get this to work in the meantime I just override the .card style and change the overflow:hidden to overflow: visible.
