### ISSUE TITLE
New material design icons from Google

### ISSUE THREAD

**Issue by Krazitchek** [Dogfalo/materialize#1449]
Just for information and update if possible.

Material Design Icons 2.0

    New material icon library launched
    Icon font
    Expanded documentation
    Android Vector Drawables
    More than 80 new icons
    PNGs significantly more optimized for size (~25% size reduction)
    iOS assets now organized into imagesets

**Comment by UriahsDev** [comment]
Next time at least include a direct link so we dont have to google. Thanks.

**Comment by Krazitchek** [comment]
https://github.com/google/material-design-icons/releases

**Comment by MusikDK** [comment]
Also seems the fonts are wrong. Trying to insert the mdi-action-home but get a "lock" instead.

**Comment by javatlacati** [comment]
@MusikDK  it happends because the google font has changed hex-values.
Those have to be changed at `ghpages-materialize.css` file

**Comment by MusikDK** [comment]
Makes sense. I'll just wait until theres an Icon 2.0 implementation (or I'll skip the icons from the framework and make a DIY)

**Comment by acburst** [comment]
Gonna look into removing including the actual icon font and just using Google's cdn.

http://google.github.io/material-design-icons/#icon-font-for-the-web

**Comment by Lardjo** [comment]
@acburst Good idea, but it is better to give the user a choice. Try and implement using CDN and put into the project.

**Comment by acburst** [comment]
Added in 804f2356a1a86db458b8baa51d60573c968e4250,
We are planning on a new release today as well!
