### ISSUE TITLE
Animation in forms not working

### ISSUE THREAD

**Issue by eldragon87** [Dogfalo/materialize#145]
The animation with the forms do not work correctly. The sample text is not cleared to enter new or no animation as shown on the page. Not if for lack of a call of a function in JQuery, if any, would be necessary to include the information in the web.

![form](https://cloud.githubusercontent.com/assets/8073946/5207708/9109e566-7572-11e4-8faa-7f628a326d85.jpg)

**Comment by denisg-g** [comment]
I have the same problem and i found that it was because turbolinks is disabled i have to make another app to realize it

**Comment by Szymon-dziewonski** [comment]
same here when form is inside slickjs slider div

**Comment by LazzyGuy** [comment]
I am facing the same problem mentioned I have tried every solution.
