### ISSUE TITLE
Navbar component page fixes.

### ISSUE THREAD

**Issue by brianmontanaweb** [Dogfalo/materialize#1451]
I'm going to fix a few of the navbar classes so the design is presented as intended.

"Active Items"  has logo class center, should be right.
"Navbar Dropdown Menu" logo does not include a class for padding.
"Icon Links" logo does not include a class for padding.

Just making sure this is cool to make pull requests for before I start.

**Comment by kmmbvnr** [comment]
What do you mean by `not include a class for padding`?

The links on navbar on the [demo](http://materializecss.com/navbar.html) page looks fine
