### ISSUE TITLE
Question: Howto make a "Select" Invalid

### ISSUE THREAD

**Issue by boustanihani** [Dogfalo/materialize#1454]
Could you please explain how one should (dynamically) mark a "Select" as invalid (so that a red border is shown underneath) ?

A hint about invalidating other components (like the datepicker) would be highly appreciated :smiley:

**Comment by acburst** [comment]
We are leaving any complex validation that is not provided by html up to the user. In addition, i'm not sure  how validating a select would even be useful. 

In any case, this is out of the scope of our project.

**Comment by boustanihani** [comment]
Well, when we call ```$('select').material_select();``` then the following code:

```html
<select>
    <option value="" disabled selected>Choose your option</option>
    <option value="1">Option 1</option>
    <option value="2">Option 2</option>
    <option value="3">Option 3</option>
</select>
<label>Materialize Select</label>
```
 becomes like this:
```html
<div class="select-wrapper">
    <i class="mdi-navigation-arrow-drop-down active"></i>
    <input class="select-dropdown" readonly="true" data-activates="select-options-8a6ba0ba-61d0-ccb1-b245-9fa560768eb7" value="Choose your option" type="text">
    <ul style="width: 330px; position: absolute; top: 0px; left: 0px; opacity: 1; display: none;" id="select-options-8a6ba0ba-61d0-ccb1-b245-9fa560768eb7" class="dropdown-content select-dropdown">
        <li class="disabled active"><span>Choose your option</span>
        </li>
        <li class=""><span>Option 1</span>
        </li>
        <li class=""><span>Option 2</span>
        </li>
        <li class=""><span>Option 3</span>
        </li>
    </ul>
    <select class="initialized">
        <option value="" disabled="" selected="">Choose your option</option>
        <option value="1">Option 1</option>
        <option value="2">Option 2</option>
        <option value="3">Option 3</option>
    </select>
</div>
<label>Materialize Select</label>
```
So I thought we could then add **"invalid"** to ```<input class="select-dropdown" ...>``` so it gets a red border underneath in case we need the user to select an option and he forgot to...

**Comment by boustanihani** [comment]
@acburst Take a look at the following image, the upper select is missing the red line when invalid, since you also use input fields in your initialized widget, why not be able to make the invalid style look the same?

![screenshot - 03 06 2015 - 12 03 26](https://cloud.githubusercontent.com/assets/4227548/7957612/141ccd28-09e9-11e5-9073-c34bb1059f54.png)

**Comment by Jhonatangiraldo** [comment]
Hello! My select dont is showed, when i use directives like *ngFor, or *ngIf. Can you help me ?

**Comment by degs098** [comment]
@Jhonatangiraldo you should use angular-materialize https://krescruz.github.io/angular-materialize/ maybe that will save your life in that case hahaha
