### ISSUE TITLE
Materialize.css breaks when used with jQuery in noConflict mode

### ISSUE THREAD

**Issue by jmversteeg** [Dogfalo/materialize#1456]
As the title suggests, Materialize.css will break when used with jQuery in noConflict mode due to a direct reference to the global variable `$`. This is the case in environments such as WordPress.

Please see my fixing pull request here: https://github.com/Dogfalo/materialize/pull/1374

**Comment by idmontie** [comment]
:+1: Your fix is exactly what I had to change in my local to get it to work. Awesome to see you already have issued the pull request.

**Comment by acburst** [comment]
Sorry this took so long. Added in 67c93cf
