### ISSUE TITLE
Scrollable Tabs with Materialize. Anydody know how?

### ISSUE THREAD

**Issue by ecuanaso** [Dogfalo/materialize#1458]
Has anybody found a way to do this similar to

http://material-design.storage.googleapis.com/publish/material_v_4/material_ext_publish/0B6Okdz75tqQsY1JuWnJGSHpiQkE/components-tabs-typesoftabs_scrollable_tabs_01_xhdpi_003.webm

![](http://material-design.storage.googleapis.com/publish/material_v_4/material_ext_publish/0B6Okdz75tqQsOUdyb0FjQTJTdlk/components_tabs_usage_mobile3.png)

**Comment by acburst** [comment]
Duplicate issue #487
