### ISSUE TITLE
collapsible lag on mobile

### ISSUE THREAD

**Issue by man2** [Dogfalo/materialize#1459]
is there way to make it smoother on mobile?
(I'm using meteor)

**Comment by MusikDK** [comment]
My experience a year ago (haven't really used Materialize yet) is that HammerJS is seriously bad for performance although its a really cool plugin. Try to deactivate it if you use it and see if it helps.

**Comment by acburst** [comment]
We haven't found a way to make it consistently smoother on all devices. That is very hard to achieve. As devices get better, animations will become smoother. Sorry for the inconvenience
