### ISSUE TITLE
News Ticker

### ISSUE THREAD

**Issue by Cheapskate01** [Dogfalo/materialize#1460]
So i just found that bootstrap had a news ticker, which works well. I was wondering if oyu could make the equivalent of this: https://github.com/gagi270683/jQuery-bootstrap
It would look great!

**Comment by Dogfalo** [comment]
I don't think this is important to include in the core part of materialize. What you linked was not part of bootstrap either.

**Comment by Cheapskate01** [comment]
Its okay, just a suggestion. Also, i ddidn't mean it to sound like i said
it was part of bootstrap, I meant it was built for bootstrap.
