### ISSUE TITLE
Programmatically open, close, and toggle Dropdown Menu

### ISSUE THREAD

**Issue by dacheezypuffs** [Dogfalo/materialize#1462]
Hey, is there any possible way to use javascript to open/close/toggle a dropdown menu? I'm trying to make a contextual menu when you right click, It works well until you try opening it. Thanks in advance.

**Comment by rizkiandrianto** [comment]
waiting on this... :+1:

**Comment by chris35469** [comment]
I'm using this as a work around. Not sure pretty but it works for me. 
$(document).click(function(){
    // ID of your menu button here
    $("#menu-button").click();
  })

**Comment by mattidupre** [comment]
Stumbled on this issue myself. :+1:

**Comment by Alber70g** [comment]
Yes I need this for integration with Angular2-meteor :+1:

**Comment by kmmbvnr** [comment]
Looks already implemented - http://materializecss.com/dropdown.html

![dropdown materialize](https://cloud.githubusercontent.com/assets/282529/20563958/0151ab3a-b1b5-11e6-9c91-1bd29bffd9f0.png)
