### ISSUE TITLE
How to know if the side nav is on the screen

### ISSUE THREAD

**Issue by KhaledElAnsari** [Dogfalo/materialize#1463]
Hello

I've been using this awesome framework for my latest project and I was wondering if there's a way to know if the side-nav is called and is on the screen?

**Comment by jeonghwan-kim** [comment]
@KhaledElAnsari 
You can check side-nav visibility by `#sidenav-overlay` selector. If side-nav is on screen, '$(`#sidenav-overlay`)' has array. But it is hidden, has a empty array.

```javascript
if ($('#sidenav-overlay').length > 0) {
  // side-nav is shown
} else {
  // side-nav is hidden
}
```

**Comment by KhaledElAnsari** [comment]
@jeonghwan-kim I'm already doing something like that

```javascript
$('body').on('touchend',function(e){
	if( $('#slide-out').css('right') != '-230px' ) {
		console.log('side-nav visible');
	}
	else {
		console.log('side-nav hidden');
	}
)};
```
But it's not the ideal solution! I need something faster and guaranteed

**Comment by acburst** [comment]
@jeonghwan-kim's solution seems better and more robust then checking a static number. There is no official way to tell if the side nav is open.

**Comment by brennangw** [comment]
This works for me (note it checks if it can be completely closed or open though this can be adjusted). I like that it checks if it completely closed or open though b/c it seems that o.w. you get strange shadowing errors.

```
 if ($('#slide-out').css('transform').split(',')[4] === " -250") {
            console.log("closed");
        } else if ($('#slide-out').css('transform').split(',')[4] === " 0") {
            console.log("open");
        } 
```
