### ISSUE TITLE
modal.leanModal({dismissible:false}) does not work: tested

### ISSUE THREAD

**Issue by rkstar** [Dogfalo/materialize#1464]
issue #1239 is valid.

tested and demonstrated here: http://codepen.io/anon/pen/oXBKeg
using example copied from: http://materializecss.com/modals.html

OSX Yosemite / Chrome
Version 43.0.2357.81 (64-bit)

OSX Yosemite / Firefox
Version 38.0.1

**Comment by Dogfalo** [comment]
the open function allows you to pass in different options. The leanModal call is for setting up a trigger and is not meant to be called on the modal itself.

**Comment by rkstar** [comment]
Please update the documentation to reflect this.

**Comment by neopostmodern** [comment]
Ran into this too, please update documentation. 

It's very unintuitive, I'd even call for a design change, such that calling `openModal` *without* any arguments would default to the arguments it's been initialized with.

**Comment by zorobabel** [comment]
Hey dude, your leanModal() and openModal() does not work...time to migrate to Material Design Lite

**Comment by bsrdjan** [comment]
Is it possible to set "ready" and "complete" callback functions of the modal, without opening the modal ?

**Comment by suryasarafe** [comment]
![mdoals](https://cloud.githubusercontent.com/assets/12762391/11388195/f11a9272-9365-11e5-8259-9b9adeaa1bcc.PNG)

its added to documenttaion.

**Comment by erBhushanPawar** [comment]
The problem is with including jquery. if you have 2 jquery included while setting no conflict to $ use jQuery 2.1X.x and it will work for you !


<script src="https://code.jquery.com/jquery-2.1.4.min.js"></script>
<link type="text/css" rel="stylesheet" href="./css/materialize.min.css"  media="screen,projection"/>
        <script type="text/javascript" src="./js/velocity.min.js"></script>
        <script type="text/javascript" src="js/materialize.min.js"></script>
        

Hope this will help you

**Comment by vmkazakoff** [comment]
Thanks @erBhushanPawar! My mistake is including materializecss.js before jquery and I have a lot of problems - not working modals, toasts etc... You save my day!

**Comment by conrald07** [comment]
hey guys. I've got a serious problem with modals. it doesnt' respond. I've initialised and done the coding - a copy and paste from the website- but it still doesnt work. Please could some one just post the code to include in my js file. i think that is where my prob is.

**Comment by erBhushanPawar** [comment]
`$('#modalConfirmOrder').openModal({
			    dismissible: false, // Modal can't be dismissed by clicking outside of the modal
				opacity: .5, // Opacity of modal background
				in_duration: 300, // Transition in duration
			    out_duration: 200, // Transition out duration
			    ready: function() {  }, // Callback for Modal open
			    complete: function() { /*alert('Closed');*/ } // Callback for Modal close
			});`

also make sure that you have addressed previous solution too

**Comment by conrald07** [comment]
thanks a lot @erBhushanPawar. But just one more question. i"ld like to call this function onclick(an image for example). this code runs from when my tab loads.

**Comment by conrald07** [comment]
Oh. I got it!!!. Thanks again.

**Comment by fedpettinella** [comment]
@Dogfalo Could you please add it back to the documentation? Why was it taken out again? It's important to know that `openModal()` can take options.

**Comment by dbr0** [comment]
There is no more `openModal()`. It's been changed to `.modal('open')`.
Does anyone knows how to open modal and add a callback now?

**Comment by erBhushanPawar** [comment]
@dbr0 Dude, I think they have adapted bootstrap method this time. I hope this document will help you http://www.w3schools.com/bootstrap/bootstrap_ref_js_modal.asp

**Comment by dbr0** [comment]
@erBhushanPawar Using `.modal('show')' from link you have given gives `Error: Method show does not exist on jQuery.modal`.

**Comment by bspatil0001** [comment]
Not working on clicking of browser back button.
