### ISSUE TITLE
Modal header class

### ISSUE THREAD

**Issue by koustuvsinha** [Dogfalo/materialize#1465]
It would be nice if materialize css could support a modal header class in its markup as it does in the footer : 

```html
<!-- Modal Structure -->
  <div id="modal1" class="modal">
    <!-- should have a header div -->
    <div class="modal-header">
    ...
    </div>
   <!-- end of header -->
    <div class="modal-content">
      <h4>Modal Header</h4>
      <p>A bunch of text</p>
    </div>
    <div class="modal-footer">
      <a href="#!" class=" modal-action modal-close waves-effect waves-green btn-flat">Agree</a>
    </div>
  </div>
```

If it already exists then please mention here! Thanks

**Comment by jeonghwan-kim** [comment]
Good suggestion!
However in [the document](http://www.google.com/design/spec/components/dialogs.html#dialogs-content), the header is large fonts. I think header is in `.modal-content`.

**Comment by koustuvsinha** [comment]
then it should have its separate div element

**Comment by acburst** [comment]
This seems like its more of a personal preference and not a major issue. If you want to separate out the sections further you may do so in custom css. We will keep the modal structure how it is currently.
