### ISSUE TITLE
[SOLVED] Issue using materialize select and meteor's each {{each}}  

### ISSUE THREAD

**Issue by nacholozano** [Dogfalo/materialize#1469]
I have a materialize select. 
The select content must be updated when a session var value changes.
The content would change through a helper.  

I have tried initializing the select before and after the meteor's {{each}} but it doesnt work fine.

**Comment by ricardodovalle** [comment]
@nacholozano You need to use a obverse or/and call `$('select').material_select();` again when the value or collection change in the client code.
This function will initialize or update the select.

**Comment by nacholozano** [comment]
@ricardodovalle thanks, I will try that. At the moment I have solved it using this helper after the {{#each}}

iniSelect: function(){
        var procesorPower = Session.get('procesorPower');

        Meteor.setTimeout(function(){
            $('select').material_select()
        }, 20);

    }

**Comment by s7dhansh** [comment]
Redrawing the list every 20 seconds is not a good idea.
You should use a trigger whenever the options are changed (in the helper function that returns the session/options).
Additionally, call material_select on that trigger event in your startup function.

eg:

```
iniSelect: function() {
 $("#SelectId").trigger("optionsChanged");
 return Session.get("selectOptions");
}
Meteor.startup //or Template.onRendered ->
 $("select").on("optionsChanged", function() {
    $(this).material_select();
 });
```

**Comment by brandiqa** [comment]
The solution that worked for me is by calling the 'material_select' function after the options data has been loaded.

`
Template.[name].rendered = function() {
	this.autorun(function() {
		var optionsCursor = OptionsList.find().count();
		if(optionsCursor > 0){
			 $('select').material_select();
		}
	});
};

`

**Comment by ramintagizade** [comment]
It actually closes the opened select window when adding new data .
