### ISSUE TITLE
Dropdown is blinking in Firefox 38+

### ISSUE THREAD

**Issue by zorobabel** [Dogfalo/materialize#1471]
This is not happening in Chrome.

The error in action:

https://drive.google.com/open?id=0Bw0PGSiSoSieUEFzMHZWMUx5aVE&authuser=0

**Comment by Kithio** [comment]
I'm running 28.0.5 and I can say that it doesn't occur for me. You running latest version?

**Comment by zorobabel** [comment]
Of course, did you see the vid?

**Comment by williwambu** [comment]
I have the same problem on firefox 38.0 when hover is set to true.

**Comment by danieljaniga** [comment]
same problem here

**Comment by reesebiz** [comment]
I'm experiencing the same issue in Firefox 40.0.3

**Comment by williwambu** [comment]
I think it was fixed in the latest release.

**Comment by sasharili** [comment]
I'm also experiencing this issue in FF 40.0.3

**Comment by zorobabel** [comment]
It's no fixed bro

**Comment by Kithio** [comment]
I think the problem is it activates the animation on MouseDown and Up, Not 100% sure about it to be completely honest since I haven't had time to look through the code, but by simple testing that's what it looks like

**Comment by acburst** [comment]
Fixed in 88f6ddd

**Comment by zorobabel** [comment]
@acburst Great, thanks!
