### ISSUE TITLE
Materialize Select Problem

### ISSUE THREAD

**Issue by dhelazt** [Dogfalo/materialize#1473]
Hi...
I don't know if this a bug or not, i create a form with with a select and a text area. 2 button for reset and submit, the problem is when i click the select, the button is floated in front of select options.
![abc](https://cloud.githubusercontent.com/assets/12581988/7952941/070e2486-09f0-11e5-98bd-eb3d590fba6a.png)

**Comment by dowrow** [comment]
Looks like a bug. The dropdown menu should have higher z-index IMO.

**Comment by uok** [comment]
there is https://github.com/Dogfalo/materialize/issues/1337 which says it's fixed but not released - I have the same problem but I don't know when next release happens

**Comment by dhelazt** [comment]
i think it release with many bug fixed or new feature, hope so...

**Comment by Hansage** [comment]
i put this in extra.css.
dropdown-content {
    z-index: 3;
    } 
and works

**Comment by Clearmist** [comment]
This was still an issue in version 0.96.1, but appears to have been fixed with 0.97.1.
