### ISSUE TITLE
Side nav lag when adding two buttons for it

### ISSUE THREAD

**Issue by KhaledElAnsari** [Dogfalo/materialize#1475]
Hello

I've added to collapse buttons for the same side-nav, it works will on one page but the other one needs to be tapped twice to call the side-nav! anybody faced this problem?

**Comment by acburst** [comment]
Please attach codepen

**Comment by chrisxue815** [comment]
I had the same problem even there's only one button. I fixed it by removing the click delay using FastClick (https://github.com/ftlabs/fastclick)

**Comment by KhaledElAnsari** [comment]
@acburst I copied the main elements of the side-nav in my project, it works almost fine in the fiddle I might try @chrisxue815 way maybe it will help

here's the fiddle: http://jsfiddle.net/f6k6xruc/

**Comment by KhaledElAnsari** [comment]
@chrisxue815 it didn't work bro :\

**Comment by acburst** [comment]
Hmm the fiddle seems to work for me?
What browser are you on?

**Comment by tomscholz** [comment]
Closed due inactivity. Feel free to reopen it, if it's still necessary.
