### ISSUE TITLE
Side-nav freezes when using two side-navs

### ISSUE THREAD

**Issue by narayanaditya95** [Dogfalo/materialize#1477]
The left side-nav freezes when it opens. The only way to close the left side-nav is to resort to double-clicks outside the side-nav instead of single clicks.

Codepen [here](http://codepen.io/anon/pen/ZGeawa)

EDIT: The problem occurs only in small and medium screens.

**Comment by imjoeybrennan** [comment]
Problem is your clicking the other nav's drag-target. It happens on all screen sizes. This guy has a fix. 
https://github.com/Dogfalo/materialize/issues/1417

Also if you don't care about dragging open the nav you can just overwrite the css for the sidenav-overlay to increase its z-index to 998.

**Comment by Dogfalo** [comment]
Fixed in 946543f
