### ISSUE TITLE
include materialize.js file in meteor package pls

### ISSUE THREAD

**Issue by rkstar** [Dogfalo/materialize#1479]
i had to download the `materialize.min.js` file and add it to `/client/compatibility` in order to get my meteor app to work with things like `$().sideNav()`

can you include the js file in the atmosphere package please?

**Comment by acburst** [comment]
We have made meteor apps before and the javascript plugins work. I'm sorry if it caused you trouble

**Comment by jonS90** [comment]
You guys are awesome for having a meteor package, but I seem to have this exact same issue. `$().sideNav` is undefined in Meteor. 

 >  Meteor 1.1.0.2
 >  materialize:materialize  0.97.0

**Comment by Dogfalo** [comment]
I tested it again and it is defined. You probably have some error in your package.
