### ISSUE TITLE
Close side-nav on button click

### ISSUE THREAD

**Issue by Shehab-Eltawel** [Dogfalo/materialize#1480]
Hi,
I've tried to get the side-nav close when click on button , but nothing works.   
Any clear workflow on how get such technique done with materialize side-nav ?

Thanks

**Comment by iMshyam** [comment]
[This] may help you .

[This]:http://materializecss.com/side-nav.html#method

**Comment by kasperrt** [comment]
@iMshyam that only closes the most recent sideNav, and its irrelevant what you put in the jQuery declaration (meaning you can write $("helloIAmKasperRT").sideNav("hide") and still close the most recent one).

**Comment by iSuslov** [comment]
See https://github.com/Dogfalo/materialize/issues/1417

**Comment by Shehab-Eltawel** [comment]
@kasperrt +1

**Comment by iSuslov** [comment]
https://github.com/Dogfalo/materialize/issues/1417 see

**Comment by Tux1** [comment]
I have two buttons. The first one initializes the sidebar and a second inside the sidebar closing the sidebar with (sideNav('hide')) but it doesn't work. Are you sure that is working well ?
