### ISSUE TITLE
Datepicker showing invalid state when selecting a date

### ISSUE THREAD

**Issue by netm** [Dogfalo/materialize#1481]
I am using Materalize with Meteor. Wow, it's wonderful, amazing work putting it together :)

When I select a date with a datepicker it seems to automagically add a invalid class to the input and I can't figure out for the life of me why.

```
        <div class="input-field col s6">
          <input name="start" id="start" type="date" placeholder="" class="datepicker validate" />
          <label for="start">Choose a start date...</label>
        </div>
```

Any help much appreciated.

**Comment by acburst** [comment]
I dont think validation is supported in HTML5 for date. Try removing the validate class from the input and it should be fine.

**Comment by fega** [comment]
closed due inactivity

**Comment by multiwebinc** [comment]
I was able to get validation to work for datepickers.

```
var validator = $( "#yourform" ).validate();
$('.datepicker').pickadate({
      onSet: function(context) {
        var calendar = this.$node;
        var valid = validator.element("#"+calendar.attr("id"));
        if (valid) {
          calendar.removeClass("invalid").addClass("valid");
        }
      }
    });
```

[See it on JSFiddle](http://jsfiddle.net/453ykekx/1/)
