### ISSUE TITLE
Create composer package, please

### ISSUE THREAD

**Issue by hulyman** [Dogfalo/materialize#1483]

**Comment by yang-wei** [comment]
Why would you need a composer package for a front end tool? There are `npm` and `bower` supported already.

http://materializecss.com/getting-started.html

**Comment by valorin** [comment]
Composer support is useful if you can't install Node on your server/workstation, but do have access to PHP. It is also a lot nicer to work with than NPM, and is completely automatic when you use tags for releases. You just create a basic `composer.json` file, add the project to http://packagist.org/ and forget about it :-)

**Comment by Triloworld** [comment]
Yes +1 for it. More audience will come and adopt it.
Node is only one option now. 
"npm and bower " <- Need node, I don't use it so no more option :(

**Comment by JesusRodriguezAcosta** [comment]
To use materialize with composer, just add a custom repository in composer.json. Anyway, I guess it's a good idea to add a native support.

    "repositories": [
        {
            "type": "package",
            "package": {
                "name": "dogfalo/materialize",
                "version": "0.97.1",
                "dist": {
                    "url": "http://materializecss.com/bin/materialize-src-v0.97.1.zip",
                    "type": "zip"
                }
            }
        }
    ],
    "require": {
        "dogfalo/materialize": "0.97.1"
    },
