### ISSUE TITLE
Search bar input field ie11

### ISSUE THREAD

**Issue by Veriwind** [Dogfalo/materialize#1486]
using Materialize `v0.96.1`
In IE11 the search bar from your example ( http://codepen.io/anon/pen/ZGKQWv ) is not appearing correctly. 

I don't know what the underlying problem is but I have found that the height isn't being correctly displayed. It is currently 100% and IE is taking the font-size (1.2 rem) instead of the 4.4 rem it should be. 

This in materialize.css:5078 at `nav .input-field input`

**Comment by tomscholz** [comment]
Seems to be a duplicate of:
https://github.com/Dogfalo/materialize/issues/3681 & https://github.com/Dogfalo/materialize/issues/1486
Please use https://github.com/Dogfalo/materialize/issues/1544 for future discussion
