### ISSUE TITLE
Dropdown and Buttons overlap

### ISSUE THREAD

**Issue by evankrob** [Dogfalo/materialize#1487]
Base Materialize form code with long drop down creates an overlapping button issue.

![screenshot 2015-06-06 23 36 38](https://cloud.githubusercontent.com/assets/959456/8022528/7c068fc8-0ca5-11e5-8317-5fabfdbd856d.png)

**Comment by Neotrixsx** [comment]
I suggest use "z-index" Css property in dropdown.

**Comment by acburst** [comment]
On master this is fixed. Change the z-index for now locally if you don't want to use the unreleased latest versions.
