### ISSUE TITLE
Question: New Release ?

### ISSUE THREAD

**Issue by boustanihani** [Dogfalo/materialize#1489]
Hey guys, don't you think its time for a new release? Maybe call it 0.97 :bowtie:

**Comment by dcworldwide** [comment]
:+1

**Comment by ricardodovalle** [comment]
:+1:

**Comment by dcworldwide** [comment]
Are you all meteor users? If so I think it is due to the package js design and they want autopublish only rebuild a package if the release number changes

**Comment by peiphb02** [comment]
would also like to use some bug fixes which are not released yet. Would be great if you could provide us a new release! :)

**Comment by boustanihani** [comment]
Yeah getting the bug-fixes would be great :+1:

**Comment by dcworldwide** [comment]
For meteor, if someone submits a pr for package js updating the semver with a minor release number it will trigger a meteor package release.

**Comment by boustanihani** [comment]
Here is a pull: https://github.com/Dogfalo/materialize/pull/1521

**Comment by boustanihani** [comment]
@dcworldwide Are you sure this should be done by hand ?

There seems to be a grunt task for upgrading the version number, check:
https://github.com/Dogfalo/materialize/blob/v0.96.1/Gruntfile.js#L415

**Comment by dcworldwide** [comment]
From my understanding of how meteor autopublish works. I do agree that ideally dogfalo should bump version via grunt.

**Comment by acburst** [comment]
We are working on releasing a new version today
