### ISSUE TITLE
Running grunt doesn't create the same JS/CSS version

### ISSUE THREAD

**Issue by Vadorequest** [Dogfalo/materialize#1491]
I'm wondering why when I run grunt it doesn't regenerate the exact same JS/CSS files. There actually are a lot of changes.

See the commit in my fork: https://github.com/Ayolan/materialize/commit/3968232826cd85438ff21831daf404a9b2b84586

Thanks for any insight :)

**Comment by Dogfalo** [comment]
Maybe you pulled changes from master by accident.

**Comment by Vadorequest** [comment]
I probably did that. :)
