### ISSUE TITLE
IE SVG Classlist

### ISSUE THREAD

**Issue by Schenn** [Dogfalo/materialize#1492]
In the method getWavesEffectElement, you say if an element isn't an SVG Element and has a class do something, otherwise if its classList has a class of 'waves-effect' do something else.  The way this IF is structured, an SVGElement is passed into the Else If. However, in IE, SVG Elements don't support the classList attribute, so line 1604 throws a 'Unable to get property 'contains' of undefined or null reference' error in the latest IE.

**Comment by benjaminwols** [comment]
+1

**Comment by fabyeah** [comment]
+1

The getWavesEffectElement code hasn't changed in v0.97.7, so I guess the bug is still present.

Usually this problem occurs with svg icons inside buttons/links. I use this workaround:

```
svg.icon {
	pointer-events: none;
}
```

You might need to adapt this to your html structure.

**Comment by fabyeah** [comment]
Unfortunately my workaround causes links with svg icons to not be clickable in Safari/IE/iOS, unless they're specifically set to display: block or inline-block. :(

I guess we need a PR. Unless someone has another solution?

**Comment by DetlefPeters** [comment]
+1

**Comment by tomscholz** [comment]
The bug was fixed over at the waves repo [here](https://github.com/fians/Waves/commit/1280fd29f7c215aafbbf7c00de2fb5c4303d8eb3). As soon v0.8.0 is getting released, we will merge the changes into materialize

**Comment by Dogfalo** [comment]
Fixed in 741d47a092ba4f09ce841c7fa98def1ce0dcfd2c
