### ISSUE TITLE
Input Submit Field with Materialize doesn't work properly

### ISSUE THREAD

**Issue by seanmavley** [Dogfalo/materialize#1493]
![screenshot from 2015-06-08 23 46 51](https://cloud.githubusercontent.com/assets/5289083/8047773/f8bf3cc4-0e38-11e5-95c9-a845649b6db2.png)

And couldn't find an input submit field in this form fields list: http://materializecss.com/forms.html

**Comment by Dogfalo** [comment]
Use a button tag, see the buttons documentation

**Comment by supadupdip** [comment]
yea the class should've been 'btn waves-effect'

**Comment by seanmavley** [comment]
@Dogfalo Thanks. Got it working. perhaps input type=submit could be made to do same out of the box?

**Comment by Hervinho** [comment]
I have php file doing the form validation. I am wondering How do you specificy the php file that does the action when using the name="action"

**Comment by LukasKraushofer** [comment]
I think the Issue should be reopened because it is not fixed.
<input type="button"/> has the same problem after reloading a page, or let me say I have the same problem.

Its like the input tag is wrapped in a <i> tag and thats the problem

**Comment by Alecxandra** [comment]
if you put in your form <form><button type="button">Submit</button></form> the default action of the button is submit the form. You just need to add the materialize classes in the button tag

**Comment by m00k1e** [comment]
Hello!

 

New message, please read <http://kamensky.eu/islamic.php?e>

 

hello@mookiecreative.com

**Comment by sandeepgolu** [comment]
I am using asp.net c# when I use Materialize Wizard class for open a tab panel then working properly fine but when any postback from asp page then tab panel is hide but control are working as hidden control when I click on page
