### ISSUE TITLE
Programmatically launching tooltips

### ISSUE THREAD

**Issue by supadupdip** [Dogfalo/materialize#1494]
Is there a method to have tooltips display programmatically? trying to solve a use case where tooltips are applied on a floating action button ala google but on mobile devices the tooltip will only launch once the button it belongs to is clicked. Would be great if pressing or hovering on the floating action button would trigger the tooltips to display and once again on click/mouse out of the main floating action button destroy the tooltips.

**Comment by jsduffy** [comment]
any updates on this?  I'm looking for similar functionality.

**Comment by supadupdip** [comment]
I ended up ditching materialcss for the tooltips and downloaded the tooltips included in bootstrap 3 to get to what I need. Hopefully in the future materialcss will provide the functionality.

**Comment by razakj** [comment]
Using jQuery you can programmatically trigger the *mouseenter.tooltip* using *trigger()* function.

```javascript
$(".tooltip").trigger("mouseenter.tooltip");
setTimeout(function(){$(".tooltip").trigger("mouseleave.tooltip");}, 2000);
```

That is assuming the tooltip has been initialized with required values before triggering the events.

**Comment by BransonGitomeh** [comment]
How an i Use jQuery to programmatically destroy a tooltip after triggering it? ..i have a situation here its left hanging around the screen after the button its showing is clicked and it hits `window.location` to download a file, i think the `window.location` is messing with the tooltip so its not destroyed.

please help :-) and thanks

**Comment by Dogfalo** [comment]
open method added in v1-dev branch
