### ISSUE TITLE
Icons

### ISSUE THREAD

**Issue by ajm339** [Dogfalo/materialize#1499]
The class labels for icons is not matching appropriately according to your guide (http://materializecss.com/icons.html).

For example, using class "mdi-navigation-apps" shows the icon for "mdi-navigation-fullscreen-exit".

**Comment by ajm339** [comment]
It appears to be an issue with the Sass install.  Not sure if it is a problem with your version or the gem from https://github.com/mkhairi/materialize-sass.  Posting on both.

**Comment by mindnuts** [comment]
:+1: 

Same issue is being faced by us. Is there an easy fix for this? All we did was to run the sass compiler and the icons do not match with icon list on the materializecss website. The icons are 2 or 4 positions off.

**Comment by ajm339** [comment]
Another example where it is off:

My navigation bar specifies the mobile "hamburger" menu icon:
```
<a href="#" data-activates="mobile" class="button-collapse"><i class="mdi-navigation-menu light-green-text text-darken-2"></i></a>
```

But I get this icon on Mobile:

![screen shot 2015-06-10 at 10 35 06 am](https://cloud.githubusercontent.com/assets/4138881/8085118/761d47f0-0f5c-11e5-9724-02eea205b88a.png)

**Comment by Dogfalo** [comment]
You just have an old icon file and a newer Css file

**Comment by ajm339** [comment]
I am using your latest download from the website.  I originally used the gem to get this going.  I have downloaded the fonts from your website and replaced the ones in my app and the issue persists.  What do you suggest I do to fix this issue?

**Comment by Dogfalo** [comment]
You might not be replacing the font properly since the gem will make it look for it in a different place

**Comment by carlosperate** [comment]
I had exactly the same problem when I updated the css without the icons. Like Dogfalo has said, ensure you have both from the same source (either both from the release or both from the repository). Make sure you do a hard refresh on your browser afterwards.

**Comment by ajm339** [comment]
Ok makes sense.  Yea weird using the Rails Gem, they should have saved the CSS and JS in the vendor/assets folder but they are not there...so I reverted to using the CDN and the icons are not an issue.  Thanks for the support!
