### ISSUE TITLE
Black outline on buttons with icons on firefox after clicking.

### ISSUE THREAD

**Issue by michaelbudnik** [Dogfalo/materialize#1502]
Using latest version of firefox (38.0.x)
Screen below:
![metarialize](https://cloud.githubusercontent.com/assets/10867000/8087324/10ea3628-0f92-11e5-919e-d5dabad30cbc.png)

Also the font is edgy but it was raised already.

**Comment by semlette** [comment]
Firefox has bad font rendering i believe.

**Comment by kmmbvnr** [comment]
Seems fixed. Here is screenshots taken under Win10 on https://www.browserstack.com

FF 35

![dashboard-ff35](https://cloud.githubusercontent.com/assets/282529/20586034/6e640608-b22a-11e6-99a0-2f9ae695af90.png)


FF 49

![dashboard-ff49](https://cloud.githubusercontent.com/assets/282529/20586036/710d452c-b22a-11e6-8203-fe0a9b2626f6.png)
