### ISSUE TITLE
Textarea not resizing with dynamic content

### ISSUE THREAD

**Issue by klugjo** [Dogfalo/materialize#1503]
When filling up the textarea dynamically, the textarea is not resized automatically.

Even when the textarea gains focus, it is not resized.

It would be great if the textarea was resized on focus and not only on keyup keydown.

**Comment by klugjo** [comment]
Code pen

http://codepen.io/anon/pen/doRXge

**Comment by dbauszus** [comment]
quick workaround for now:

function resizeTextArea(textarea){
	var hiddenDiv = $('.hiddendiv').first();
	if (hiddenDiv.length) {
		  hiddenDiv.css('width', textarea.width());
		  textarea.css('height', hiddenDiv.height());
	}
};

**Comment by acburst** [comment]
Have you tried this on the latest master version? I just tried putting the codepen code in a test page and it works. I've made many changes to the textarea resizing that havent been released yet.

**Comment by klugjo** [comment]
I have just tried again with the latest master and I am still having the issue. Can't seem to get it working.

What do you get exactly ? Is the textarea resizing on focus or directly when filling up the control ?

**Comment by dbauszus** [comment]
Adding focus to the autoresize function makes the text areas resize when focus is put on the element. I use the workaround to resize the text area after dynamically populating the textarea by setting its value with jQuery.

**Comment by klugjo** [comment]
Hi @dbauszus yes your workaround would definitely work, guess I will use that in the meantime.

Cheers,

**Comment by acburst** [comment]
I've just put your codepen code into a testpage on the latest version and it is working for me.

**Comment by redstrike** [comment]
I'm using v0.97 installed from Bower, and this bug is still around.
Did you fix it in master? Is there any quick patch for this?

**Comment by klugjo** [comment]
Hi @redstrike,

This what I do: call this function on page load or document ready.

```javascript
function resizeTextAreasOnFocus() {

        function resizeTextArea($textarea){

            var hiddenDiv = $('.hiddendiv').first();
            if (!hiddenDiv.length) {
                hiddenDiv = $('<div class="hiddendiv common"></div>');
                $('body').append(hiddenDiv);
            }

            var fontFamily = $textarea.css('font-family');
            var fontSize = $textarea.css('font-size');

            if (fontSize) { hiddenDiv.css('font-size', fontSize); }
            if (fontFamily) { hiddenDiv.css('font-family', fontFamily); }

            if ($textarea.attr('wrap') === "off") {
                hiddenDiv.css('overflow-wrap', "normal")
                    .css('white-space', "pre");
            }

            hiddenDiv.text($textarea.val() + '\n');
            var content = hiddenDiv.html().replace(/\n/g, '<br>');
            hiddenDiv.html(content);


            // When textarea is hidden, width goes crazy.
            // Approximate with half of window size

            if ($textarea.is(':visible')) {
                hiddenDiv.css('width', $textarea.width());
            }
            else {
                hiddenDiv.css('width', $(window).width()/2);
            }

            $textarea.css('height', hiddenDiv.height());
        }

        $('body').on('focus', '.materialize-textarea', function () {
            resizeTextArea($(this));
        })
    }
```

**Comment by jsduffy** [comment]
I'm using this from the CDN and still have this issue.  Thanks for the workarounds, but I hope that this gets resolved in the master.

**Comment by redstrike** [comment]
@klugjo Thank you very much! It works perfectly.

It seems that this bug has not been fixed in master.
https://github.com/Dogfalo/materialize/compare/v0.97.0...master

**Comment by klugjo** [comment]
@acburst Others are having the same issue ? Can you reopen this or do you need a new issue ?

Thanks !

**Comment by Dogfalo** [comment]
We'll take another look today

**Comment by acburst** [comment]
Finally fixed. There is no workaround to this because .val() does not trigger any events. So I added a custom event called "autoresize" which you have to manually trigger after any .val() changes.

```
$('#textarea1').val('New Text');
$('#textarea1').trigger('autoresize');
```

**Comment by redstrike** [comment]
@acburst How about the case of preloaded content which is returned from the server-side? Ex: I want to edit a record, the server will grab the data in db and render it in textarea, so I will make changes to that textarea by focusing on it. The textarea should expand itself because the content is filled and overflow, the user needs to see the whole of content to edit it easily. I think:

```js
$('#textarea1').trigger('autoresize');
```

is too redundant for this kind of behaviour / UX. Or do we need some init code for textarea like select?

```js
$('textarea').material_textarea();
```

**Comment by jsduffy** [comment]
This could be my own mistake, but I'm trying to use

$('.materialize-textarea').trigger('autoresize');

to fix a bunch of textareas and still not getting anything.

**Comment by flieks** [comment]
i updated to 0.97.0
i added this 
```
 $('body').on('focus', '.materialize-textarea', function () {
           $(this).trigger('autoresize');
        })
```
which is triggered when focusing but it's not resizing the textarea

**Comment by timgilbert** [comment]
Following up on the above two comments, I'm also not seeing the `'autoresize'` event have any effect in 0.97.

**Comment by PrinceJohn** [comment]
Doesn't work for me either in 0.97. My workaround is this:

function resizeTextarea( textarea ) {
	var hiddenDiv = $('.hiddendiv').first();

	if (hiddenDiv.length) {
		hiddenDiv.text( textarea.val() + '\n');
		var content = hiddenDiv.html().replace(/\n/g, '<br>');
		hiddenDiv.html(content);

		hiddenDiv.css('width', textarea.width());
		textarea.css('height', hiddenDiv.height());
	}
}

Which is pretty similar to @dbauszus workaround, except that I add text to the hiddendiv so that it has a height.

**Comment by thelinuxlich** [comment]
Autoresize event is not working for me on 0.97 too

**Comment by pranavjindal999** [comment]
Same here, Autoresize not working  for me on page load when data is passed from server.

**Comment by mikeholford** [comment]
This was happening to me too. Just check it is not a turbolinks problem you are having. If so try adding this https://github.com/kossnocorp/jquery.turbolinks

**Comment by kasperdam** [comment]
Found this trying to solve a similar issue.
Using jQuery I got what I wanted (my textarea expanding if multiple lines of text excist).

$(document).ready(function () {
$('textarea').each(function () {
            $(this).keydown();
        });
});

I want the same behaviour for all my textareas, but this could work with a textarea id aswell - I assume.
This works in Chrome and IE11 - havent check other browsers.

**Comment by ajmalhassan** [comment]
When I pasted some text into the Textarea using my mouse it didn't resize but for ctrl+v it resized so what I did is this: 

 `$('#l-textarea, #w-textarea, #c-textarea').on('mouseleave',function(){
  $('#l-textarea').trigger('autoresize');
  $('#w-textarea').trigger('autoresize');
  $('#c-textarea').trigger('autoresize');
});`

after I host the site I'll post the url here

if there is a better way, please do tell me.

**Comment by SlawomirLaba** [comment]
not working for me in 0.98

**Comment by ne0guille** [comment]
same here

**Comment by tomscholz** [comment]
@ne0guille Just writing "same here" doesn't help and to quote @SlawomirLaba "I have no idea whats the problem then", well I guess if is works in codepen, but not in your app, then it's a problem with your app

**Comment by SlawomirLaba** [comment]
after watching the problem closely, the attribute height for textarea element is not overwritten on change, maybe Im missing initialization of some kind

I copy pasted the exact code from the materialize web page

manual resizing works

I dont do anything dynamically yet, only input from keyboard so manually calling resize is not an issue

**Comment by ne0guille** [comment]
i've found out that if a refresh the page where i got the text area, the resizing works correctly, but if i navigate from another page to the textarea, its stop working and the height attributre is missing as well

**Comment by DanielRuf** [comment]
see https://github.com/Dogfalo/materialize/issues/4613#issuecomment-298391853

**Comment by newoutlaw98** [comment]
This is still an issue in v0.100.1. 
The text area does not autoresize after coming back from a java servlet call the populates the control.

**Comment by Rblock919** [comment]
I'm having an issue where my home page has all my materialize settings, looks nice, etc etc. But when I forward to a new .jsp with a java servlet, the materialize settings are all lost. Even if I forward back to the exact same page all of the settings are lost. 

I'm relatively new to programming and extremely new to materialize. I tried looking up solution in materialize documentation and googling everyone. This thread contains the closest information to my problem I've found yet.

I know that the URL changes to appname/servletname so possibly this has something to do with it? Also if I have a web.xml forward an empty url (appname/ ) to the index.jsp page then the settings also don't apply.  I can only get materialize settings to work if I type in the proper url into my browser. Ex.) appname/html/index.jsp

**Comment by DanielRuf** [comment]
Please create a new issue for this. Is materialize.js loaded?

**Comment by oabdalla** [comment]
I am still having the same issue while using the latest version of Materialize textarea. It can only resize to display all text if I hit the down key.

**Comment by iMerica** [comment]
Issue persists for me

**Comment by mrbianchi** [comment]
Thanks @Dogfalo , final answer (v1.0 beta)

**Comment by taras-yorku** [comment]
I had an issue with resizing and input field initialization when I want to display a form in a modal. I solved it by calling the following code every time the modal was displayed:

```
M.updateTextFields();
  $('.materialize-textarea').each(function (index) {
          
          M.textareaAutoResize(this);
       });
```

**Comment by globularcluster33** [comment]
tdak you're a genius! thank you so much!

**Comment by ghost** [comment]
Issue still persists for me. Can't seem to fix it.

**Comment by uy-rrodriguez** [comment]
Dear all,

In my case the resize seems to work fine, but it seems the function is not taking into account the padding. The style for my textarea is:

```
textarea.materialize-textarea {
    line-height: normal;
    overflow-y: hidden;
    padding: .8rem 0 .8rem 0;
    resize: none;
    min-height: 3rem;
    -webkit-box-sizing: border-box;
    box-sizing: border-box;
}
```

If I remove the padding, the size calculated for multi-line texts fits perfectly. If I leave the padding, then only half of the last line is visible.
