### ISSUE TITLE
Dropdown <li> doesn't update class='active' when changing selected option

### ISSUE THREAD

**Issue by smark91** [Dogfalo/materialize#1505]
In a Dropdown used like select, when changing selected option, it doesn't update the ``<li>`` class='active' matching the new option until reopening again the dropdown.

**Comment by dbauszus** [comment]
Just hit the same problem.

**Comment by smark91** [comment]
Find a workaround for now:

``$(document).on("change", "<JQuery_selector_here>", function(){``
``    $(this).material_select();``
``    var editselect = $(this).prev().prev().attr('value')``
``    var editselect = $(this).children("option:contains('"+ editselect +"')").val();``
``    $(this).attr("select-value", editselect);``
``});``

this will add a attribute on the `<select>` tag after select new `<option>`.
The `<select>` must have an `id`. Be sure to write on the JQuery_selector_here place

**Comment by dbauszus** [comment]
Hey, thanks for that. Although I am still somewhat struggling to get this working. Do you mean to put the JQuery selector for the <select> DOM on the first line? I have tried this but the result is that the value doesn't change at all now.

**Comment by dbauszus** [comment]
What I am trying to do is to get the value of the <UL> dom. But this value never changes when I change the dropdown select.

**Comment by dbauszus** [comment]
I couldn't get your example to work. Perhaps I have modified the DOM structure too much. I got confused about the double .prev() which you use. However I got an alternative workaround. The id in the first line being the id of the select element.

    $('select[id="TIPOselect"]').change(function () {
    	selectValue = $(':selected', this).text();
    	wrapper = $(this).parent();
    	wrapper.find('li').removeClass('active');
    	wrapper.find('li:contains("' + selectValue + '")').addClass('active');
    });

**Comment by smark91** [comment]
HTML
```HTML
<select id="select1">
	<option value="option1">One</option>
	<option value="option2">Two</option>
	<option value="option3">Three</option>
</select>
```
JS
```javascript
$(document).on("change", "[id^=select]", function(){        /*This select <select> object*/
    $(this).material_select();                              /*This reload "this" object */
    var editselect = $(this).prev().prev().attr('value')           
    var editselect = $(this).children("option:contains('"+ editselect +"')").val();
    $(this).attr("select-value", editselect);
});
```
DOM (after load but before any select change)
```HTML
<input type="text" class="select-dropdown" readonly="true" data-activates="select-options-e549a744-b64c-4aac-500f-94fd48bcd1c5" value="option1">
<ul id="select-options-e549a744-b64c-4aac-500f-94fd48bcd1c5" class="dropdown-content select-dropdown" style="width: 250px; position: absolute; top: 0px; left: 0px; opacity: 1; display: none;">
  <li class="active"><span>One</span></li>
  <li class=""><span>Two</span></li>
  <li class=""><span>Three</span></li>
</ul>
<select id="select1" class="initialized">
  <option value="option1">One</option>
  <option value="option2">Two</option>
  <option value="option3">Three</option>
</select>
```
DOM (after load and after select "option2")
```HTML
<input type="text" class="select-dropdown" readonly="true" data-activates="select-options-e549a744-b64c-4aac-500f-94fd48bcd1c5" value="option2">
<ul id="select-options-e549a744-b64c-4aac-500f-94fd48bcd1c5" class="dropdown-content select-dropdown" style="width: 250px; position: absolute; top: 0px; left: 0px; opacity: 1; display: none;">
  <li class=""><span>One</span></li>
  <li class="active"><span>Two</span></li>
  <li class=""><span>Three</span></li>
</ul>
<select id="select1" class="initialized">
  <option value="option1">One</option>
  <option value="option2">Two</option>
  <option value="option3">Three</option>
</select>
```
EXPLANATION
`$(this).material_select();` do the trick for make change apply to the DOM but the framework doesn't update by his own the <option> tag adding a "selected" attribute.
The only modification I can see is:
* `<input>` value
* `<li>` class="active"
but both doesn't have the option value but his label

So if you need to take the value of the selected option you have to take from one of those.
I choose to take the `<input>` way so;
`var editselect = $(this).prev().prev().attr('value')` mean:
Take "this" (`<select>`) than take his previous (`<ul>`, remember that prev take only same level tag so `<li>` is skipped) than take his previous (`<input>`) and take his content of the attribute "value".

Than with  `var editselect = $(this).children("option:contains('"+ editselect +"')").val();`
I take this value and translate with this line the label to his value, than with
`$(this).attr("select-value", editselect);` write finally the value in the form of attribute that I have call "select-value".

If you use my method remember that "select-value" become available only after a modification of the select.

For fix this I have add this code on select first loading on the DOM (so on `$(document).ready` or after an ajax call):
```javascript
var select_object = $('#select1')
  var editselect = select_object.prev().prev().attr('value')
  var editselect = select_object.children("option:contains('"+ editselect +"')").val();
  select_object.attr("select-value", editselect);
```

NOTE:
If the select is "disabled" the code for pick <input> attr "value" need ONLY ONE .prev

Sorry for possible typo mistake (I have change lot of ID and label for the example.

**Comment by dbauszus** [comment]
Hej, thanks for the great explanation. That's all working now.

**Comment by Dogfalo** [comment]
Just use  .val on the original select element

**Comment by smark91** [comment]
Oh man that's so easy....
So waste time!
select.val() works like a charm...

**Comment by smark91** [comment]
We can close.
Isn't a framework bug.
https://learn.jquery.com/using-jquery-core/faq/how-do-i-get-the-text-value-of-a-selected-option/
