### ISSUE TITLE
Materialize Select is flickering again in Firefox

### ISSUE THREAD

**Issue by 0lmar** [Dogfalo/materialize#1509]
When clicking on a "Materialize Select" in Firefox (v. 38.0.5) the select is flickering before opened. Works nicely in Chrome.

**Comment by Dogfalo** [comment]
See https://github.com/Dogfalo/materialize/pull/1482

**Comment by ramijarrar** [comment]
Still experiencing this on version 0.97.0

**Comment by carlosperate** [comment]
Can confirm this is still an issue in Firefox. If can be seen in the http://materializecss.com/forms.html#select page as well.

**Comment by Dogfalo** [comment]
Duplicate of #147
