### ISSUE TITLE
Element select not working

### ISSUE THREAD

**Issue by kamitori** [Dogfalo/materialize#151]
i can't see select on page components. Please update element select. Thanks for sharing

**Comment by mayank33** [comment]
Checked everything still not working

**Comment by carlosperate** [comment]
There doesn't seem to be any known issues with a simple select not working right now. Please create a new issue with a codepen (http://codepen.io/Dogfalo/pen/xbzPQV) example. Make sure you have initialised the javascript code indicated in http://materializecss.com/forms.html#select .

**Comment by vikohone** [comment]
**Select works with these files:**
`<script src="//code.jquery.com/jquery-2.1.2.min.js"></script>`
`<script src="//cdnjs.cloudflare.com/ajax/libs/materialize/0.97.4/js/materialize.min.js"></script>`

The select didn't work for me with these files:
`<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.0.0-alpha1/jquery.min.js"></script>`
`<script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/0.97.5/js/materialize.min.js"></script>`

So, I copy-pasted my whole page to codepen and everything magically worked.

I found out that codepen used different versions of the JS-files that what I had included.

You can see it from the Pen Settings:

![image](https://cloud.githubusercontent.com/assets/963718/12295932/0c5176b4-ba0d-11e5-8c3e-fca90892451b.png)

**Comment by bayaroch** [comment]
adsadasdasd

**Comment by TyrionGraphiste** [comment]
Yes, so don't use jQuery 3.0.0 and 2.2.0.

**Comment by RealTekOne** [comment]
with jquery 2.1.4 and this:

$(document).ready(function() {
    $('select').material_select();
});

select work fine

**Comment by schankam** [comment]
@RealTekOne Thanks, it tooks me a long time to figure out why it was not working...
