### ISSUE TITLE
How does dropdown work in Meteor?

### ISSUE THREAD

**Issue by thetechnaddict** [Dogfalo/materialize#1511]
I've tried adding a drop down to a template using the example in the materialize documentation.

              
                <a class='dropdown-button btn' href='#' data-activates="dropdown1">Drop Me!</a>

                
                <ul id='dropdown1' class='dropdown-content'>
                  <li><a href="#!">one</a></li>
                  <li><a href="#!">two</a></li>
                  <li class="divider"></li>
                  <li><a href="#!">three</a></li>
                </ul>

The drop down does not drop down.

I've tried adding initialisation code to the template' s on rendered function:

    Template.accountsAdmin.rendered = function() {
	this.$('.dropdown-button').dropdown({
		inDuration: 300,
		outDuration: 225,
		constrain_width: false, // Does not change width of dropdown to that of the activator
		hover: true, // Activate on hover
		gutter: 0, // Spacing from edge
		belowOrigin: false // Displays dropdown below the button
	});
     };

But that doesn't help.

What am I doing wrong or rather what should I be doing?

The button renders and click handlers will trigger...

**Comment by kevohagan** [comment]
I can't seem to reproduce your error. I just copy pasted your code in a materialize meteor project and it works fine. 

Any more info on this?

**Comment by thetechnaddict** [comment]
Thanks - I'll create a fresh app and try to recreate it. May take me a little time...

**Comment by thetechnaddict** [comment]
Yes, works perfectly on a new project. 

I'll start adding packages to see if any are interfering.

**Comment by thetechnaddict** [comment]
I apologise - having gone through everything it is working with apparently no changes - although the z-index is clearly - I am using it within collection-items and it is covered by the collection container.
