### ISSUE TITLE
overlay disappears after open a second modal

### ISSUE THREAD

**Issue by peiphb02** [Dogfalo/materialize#1512]
I have two modals on my page. First I open the first modal. After a button click on that modal I close the first modal and open the second modal which should not be dismissible. Unfortunately, if I close a modal and open a new modal, although the second modal is shown the shaddow-overlay disappears and I can interact with background controls!

Here a demonstration: http://codepen.io/anon/pen/doRzBb

**Comment by Dogfalo** [comment]
This is fixed but not realeasd

**Comment by peiphb02** [comment]
Alright, thx for the info! I wait with bated breath for your next release ;)
