### ISSUE TITLE
Closing dropdown in iOS

### ISSUE THREAD

**Issue by pimmey** [Dogfalo/materialize#1514]
Tapping anywhere doesn't close the dropdown, you either need to tap one of the options or another dropdown.

Tested on an iPhone 6+ with iOS 8.3

Also mentioned in [this comment](https://github.com/Dogfalo/materialize/issues/762#issuecomment-76196975) around the middle of the text.

**Comment by jadsonlourenco** [comment]
+1 - Same here, iPhone 6+ with IOS 9 (beta 1).

**Comment by acburst** [comment]
fixed in 2456c2e
