### ISSUE TITLE
Date piker 

### ISSUE THREAD

**Issue by baaboum** [Dogfalo/materialize#1516]
Hello, i see a bug, the date piker is not center in internet explorer 10.  

Thanks for your framework

**Comment by carlosperate** [comment]
Are you sure you are running the latest version? This bug might have been fixed already https://github.com/Dogfalo/materialize/issues/1136

**Comment by Dogfalo** [comment]
Yes it is fixed, I have tested it

**Comment by baaboum** [comment]
Ok thanks i'll look :)
