### ISSUE TITLE
modal doesn't fire callback or close when button is pressed

### ISSUE THREAD

**Issue by Thermatix** [Dogfalo/materialize#1517]
I have a modal with one button on it. When the button is clicked on, indeed anywhere within the modal in fact, the screen flashes but the modal doesn't close or the callback isn't fired and underneath the:
```html
<div id="lean-overlay" class="" style="display: block; opacity: 0.5;"></div>
```
I get this appended underneath:
```html
<div id="lean-overlay"></div>
```
everytime the screen flashes, also when clicked on, the button turns and stays green.

Clicking on the background however closes the modal but doesn't fire the callback and whilst the first `"lean-overlay"` div is removed, the others stay there.

Can having:

```javascript
$('a).unbind().on('click', function (event) {};
```
Watchers interfere with materialize?

**Comment by Dogfalo** [comment]
Yes unbinding all the click handlers on the close button will prevent it from working.
