### ISSUE TITLE
How to listen event of modal dismiss?

### ISSUE THREAD

**Issue by gordonpro** [Dogfalo/materialize#1520]
like the bootstrap modal event of `hidden.bs.modal`

**Comment by gabrielbiasi** [comment]
<blockquote>$('.modal-trigger').leanModal({
      dismissible: true, // Modal can be dismissed by clicking outside of the modal
      opacity: .5, // Opacity of modal background
      in_duration: 300, // Transition in duration
      out_duration: 200, // Transition out duration
      ready: function() { alert('Ready'); }, // Callback for Modal open
      <b>complete: function() { alert('Closed'); } // Callback for Modal close</b>
    }
  );</blockquote>
  
Reference: http://materializecss.com/modals.html

**Comment by zeeshanjan82** [comment]
In my case the complete function is getting called before the modal is shown to the user.

**Comment by freddy-daniel** [comment]
We are using old leanModal() for initialize. it's hard change all code for new materializecss

**Comment by rdFixFellows** [comment]
How can I perform calling an event on callback of a specific modal .

**Comment by mustii82** [comment]
`                var onModalClose = function() {
                    alert("Modal closed!");
                    //resetStepper();
                };

              var modal = document.querySelector('.modal');
                M.Modal.init(modal,{
                    onCloseEnd: onModalClose // Callback für Modal schließen.
                }
`

This will work with the Latest Version the other snippets are outdated.
