### ISSUE TITLE
z-index problem with select elements and buttons with .waves-effect

### ISSUE THREAD

**Issue by thomaslarsson** [Dogfalo/materialize#1522]
![skjermbilde 2015-06-14 kl 03 50 31](https://cloud.githubusercontent.com/assets/1395646/8146697/8abba014-1248-11e5-8fbb-e6f16ee90d50.png)

As illustrated in the image, the select options are overlapped by the submit button. 

The class .select-dropdown already applies z-index: 1, but so does .waves-effect. The issue can be fixed by raising the z-index to 2 for .select-dropdown.

**Comment by Dogfalo** [comment]
Fixed
