### ISSUE TITLE
TABS: if the location.hash matches one of the links default 'active' class not removed from the list

### ISSUE THREAD

**Issue by MisaGu** [Dogfalo/materialize#1525]
If you have hash on URL then one of the tabs will be mark as 'active', but the default 'active' class (Preselecting a tab) isn't removed.

The issue is change next code in the materialize.js file: 
<b>Line:   |  From:  |  To:</b>
<b>1071</b> &nbsp; |  <i>}&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;|  } else $links.removeClass('active');</i>

Or add this code:
<b>Line:   |  From:  |  To:</b>
<b>1066</b>&nbsp;  |  <i>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;| if($active.length)</i>
<b>1067</b>&nbsp;  |  <i>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;| $links.removeClass('active');</i>

**Comment by gonimar** [comment]
:+1:

**Comment by fega** [comment]
Closed due inactivity
If you are still having the issue, please reopen this issue,
also, you're welcome to create a pull request.

Thanks
