### ISSUE TITLE
SideNav close bugs

### ISSUE THREAD

**Issue by kasperrt** [Dogfalo/materialize#1526]
Found some bugs while creating two sideNavs
- [x] When creating two sideNavs, two divs with the class "drag-target" is created, making it so if you click outside one of the sideNavs, depending on what sides they are placed on, won't close.
- [ ] If two sideNavs are open at the same time, and the user clicks outside of both of them, the sidenavs close, but the faded overlay stays
- [ ] No way to specify what sideNav to close on button click. ($("#settings").sideNav("hide") does not close the sideNav created on #settings, instead closes the most recent sideNav)

Would be great with a fix for any of these

**Comment by kasperrt** [comment]
Found a dirty fix for the drag-target, which are adding $(".drag-target")[1].remove() if you have two sideNavs

**Comment by iSuslov** [comment]
Ahh, I know I know, look at this bug https://github.com/Dogfalo/materialize/issues/1417
I even did a pull request, but they "don't think we should call jQuery append twice". I don't want to explain then how jquery works and how this append method is implemented so I gave up. But you can apply my pull request to fix at least two issues in your list (may be all).

**Comment by tomscholz** [comment]
@iSuslov You're PR was merged back in 2015 https://github.com/Dogfalo/materialize/pull/1418
