### ISSUE TITLE
"select" control inside "modal" makes the scroll

### ISSUE THREAD

**Issue by acheshkov** [Dogfalo/materialize#1527]
The "select" control inside modal window at open state makes the scroll and not all values of select are visible. I exprect no scroll and all values of dropdowned list are visible. 

![menu_101](https://cloud.githubusercontent.com/assets/231433/8153309/49c93622-1345-11e5-9edd-36de82198f9a.png)

**Comment by jsduffy** [comment]
this is duplicated in #1713

**Comment by carlosperate** [comment]
This issue has been discussed already in https://github.com/Dogfalo/materialize/issues/1385

**Comment by TyrionGraphiste** [comment]
I think this issue now fixed. Could you please verify ?

**Comment by JoostvdB94** [comment]
This issue still is present in the current version.

**Comment by SPodjasek** [comment]
Commit above is still not a perfect solution, but suits my problem. It limits any dropdown height if placed inside `.modal` to height of `.modal-content`.
As you can see below there're two possible issues left:

- [ ] when you switch from one select to another they will still get 'full-height'
- [ ] when select is placed at bottom of modal and it will not fit upwards, it will be rendered as usual with default `max-height`

![Screencast](https://lh6.googleusercontent.com/ZgWEy4Img3NTAUHfOU-E2dfxU51Gp8PmodpjXwoB9GWXeqqkgUfHcZB37zBCj3CYWlKsrXk0)

**Comment by justinjoyn** [comment]
+1, Tried making the position:fixed for select-dropdown, the options now render above modal, but I can't place the dropdown under the select input.

**Comment by yoieh** [comment]
This is still an issue. I have the same problem but in my case the dropdown drops up and cuts of in a footer modal. I cant even select the items thats listed over the top of the modal.

![untitled](https://cloud.githubusercontent.com/assets/5743837/23650041/02c3ff8c-0321-11e7-954c-0b47b5947d39.png)


```CSS
.modal {
  overflow-y: visible;
}
```

OR

```CSS
.collection {
  overflow: visible;
}
```

Shows the whole select but then i will lose `overflow: scroll` of the `.modal-fixed-footer`.

**Comment by imaia** [comment]
I'm also affected by this issue. : /

**Comment by arredgroup** [comment]
If I use `.modal { overflow:visible; }` in case of content overflow the modal not scroll

**Comment by Dogfalo** [comment]
Fixed in v1-dev

**Comment by VicJohn** [comment]
@Dogfalo can you tell me where I have to apply the fix. Because I don't want to upgrade the api. I am using  version v0.98.1

**Comment by adhenrique** [comment]
This issue still is present in the current version.

**Comment by benNek** [comment]
Yup. this bug is still present in v0.100.2

**Comment by carusology** [comment]
@adhenrique when you say current version, do you mean in the v1 branch @Dogfalo referenced, or in one of the v0.X releases? The former means this should issue be reopened.

**Comment by adhenrique** [comment]
@carusology yeah. I refer to v1-dev, which the dogfalo commented and also master branch.

**Comment by Dogfalo** [comment]
If you are on the latest build, use the container option added in 0c703faa0fd60c96d5232ba7e33d36309b943698

**Comment by adhenrique** [comment]
@Dogfalo hmm. Like this?
`$('select').select({
    dropdownOptions: {
        container: '.modal-content',
    }
});`

**Comment by Dogfalo** [comment]
instead of the selector in the container, you should pass in the element directly

**Comment by adhenrique** [comment]
@Dogfalo I did not understand. Can u provide a simple code pls? I reviewed the docs from v1.0, but there is not instructions about this...

**Comment by Dogfalo** [comment]
This is what we do for the Select inside the Datepicker
```JavaScript
M.Select.init(yearSelect, {classes: 'select-year', dropdownOptions: {container: document.body, constrainWidth: false}});
```

**Comment by adhenrique** [comment]
Thanks @Dogfalo. 
I did some testing, and it looks like the dropdown does not get the options sent by Select.init. Look:

![image](https://user-images.githubusercontent.com/11527271/36223430-87d3d348-11ab-11e8-9aca-8ab2203c6304.png)

And forcing the option directly into the Select plugin (in _setupDropdown), Dropdown gets the option, but the problem seems to persist. Look:

![image](https://user-images.githubusercontent.com/11527271/36223661-3e866d3a-11ac-11e8-8148-aac92fdc848e.png)


Did I make a mistake?

**Comment by Dogfalo** [comment]
You are probably not using the latest build from the v1-dev branch

**Comment by adhenrique** [comment]
Weird... ;S
I downloaded from the tree/v1-dev.

That's its?

**Comment by Dogfalo** [comment]
You are not on the latest, because the container option is not shown in your screenshot. Please redownload it from github

**Comment by adhenrique** [comment]
So...
I removed all files from assets, re-downloaded, tested them and the problem persists.
The `container option` only shown when this is setted (like i do in second screenshot).

**Comment by Dogfalo** [comment]
if you are using the precompiled files from dist/ those only update on version bumps, you need to compile from the source to test out this change or wait till the next version

**Comment by VicJohn** [comment]
Found a solution for my above problem.
Replace the following lines of code in materialize.js file

`activates.css(
{
   position: 'absolute',
   top: origin.position().top + verticalOffset + scrollYOffset,
   left: leftPosition + scrollXOffset
});`

`if (activates.css("position") == "fixed" && activates.parent().hasClass("select-wrapper")) {
                    activates.css({
                        position: 'absolute',
                        top: origin.offset().top + verticalOffset + scrollYOffset,
                        left: origin.offset().left
                    });
                }
                else {
                    activates.css({
                        position: 'absolute',
                        top: origin.position().top + verticalOffset + scrollYOffset,
                        left: leftPosition + scrollXOffset
                    });
                }`
In materialize.css
`.dropdown-content
{
     //position: absolute;
     position: fixed !important;
}`

**Comment by geonanorch** [comment]
@VicJohn thank you, the fix did not work for me in modals though: the CSS 'top' property for an absolutely-positioned element applies relative to the nearest fixed-positioned ancestor (so the modal window), but `offset()` returns values relative to the document.

Here a derived fix for v0.100.2 which should work in all cases:
```javascript
        if (activates.css("position") == "fixed") {
          var fixedOffset = activates.parents().filter(function() {
            return $(this).css('position') === 'fixed';
          }).get().reduce((acc, ancestor) => {
            acc.top += $(ancestor).offset().top;
            acc.left += $(ancestor).offset().left;
            return acc;
          }, {
            top: 0,
            left: 0
          });
          activates.css({
            top: origin.offset().top - fixedOffset.top + verticalOffset + scrollYOffset,
            left: origin.offset().left - fixedOffset.left + scrollXOffset
          });
        } else {
          activates.css({
            position: 'absolute',
            top: origin.position().top + verticalOffset + scrollYOffset,
            left: leftPosition + scrollXOffset
          });
        }        
```

**Comment by VicJohn** [comment]
Was that issue still open even after applying the above CSS changes?

**Comment by geonanorch** [comment]
Yes. I did not forget to add the CSS rule, and because of `important !` the `activates.css(...)` call cannot change `position` anymore (which is good, we want `fixed`).
Note that I only tested with my own code and with materialize v0.100.2, your mileage may vary.

**Comment by VicJohn** [comment]
@geonanorch did you apply the below CSS change?

.dropdown-content { 
//position: absolute; 
position: fixed !important; 
}

**Comment by VicJohn** [comment]
@geonanorch , yes exactly

**Comment by geonanorch** [comment]
I just realized (the hard way) that while my suggested patch works when there is a fixed-positioned ancestor, it completely breaks in the case when there is not.
See previous [comment](https://github.com/Dogfalo/materialize/issues/1527#issuecomment-371492174) for an updated patch.

**Comment by yassinevic** [comment]
@geonanorch
This solution worked perfectly for me. tnx man you just saved a human life.

**Comment by Lennuj420** [comment]
@geonanorch thanks for the reply. i got it working now :smiley:

**Comment by simkessy** [comment]
Not working on my end. Is the update suppose to take care of it or do I need to override the `dropdown-content` class? 

![image](https://user-images.githubusercontent.com/5871660/45783574-0216fd00-bc1b-11e8-9849-3309ffe87e3b.png)

**Comment by geonanorch** [comment]
@simkessy the patch above is meant for v0.100.2, which is no longer receiving updates (I assume that v1 has this issue fixed, never checked). And yes, you need to modify the code in `dropdown.js`.

**Comment by immortaly007** [comment]
Maybe a bit late, but since I found this issue through Google, others might as well. 

For me, the patch above for some reason didn't work. I also didn't really like having to modify the source code.

A really simple "good enough for me" workaround is to make sure that the dropdown-content gets a scrollbar itself by limiting its height:
```css
.dropdown-content { height: 350px; }
```

And to also make sure that the modal itself is high enough by adding a `min-height`:
```html
<div id="my-modal" class="modal">
  <div class="modal-content row" style="min-height: 600px;">
     <!-- Your content and select go here -->
  </div>
</div>
```
