### ISSUE TITLE
.woff2 material icons font incorrect

### ISSUE THREAD

**Issue by jakewhiteley** [Dogfalo/materialize#1530]
If my browser uses the .woff2 file for material-design-icons, then all of the icons are incorrect and the character codes are displaying the wrong icons.

*eg. the keyboard-right icon is shown as a folder*

If I rename the .woff2 file and use the standard .woff (using chrome/firefox), then the icons display as normal.

**Comment by Dogfalo** [comment]
Please see some of the closed issues about this
