### ISSUE TITLE
Programmatically set value in select dropdown.

### ISSUE THREAD

**Issue by dbauszus** [Dogfalo/materialize#1535]
I have a simple application in which I allow the user to set a value in a select dropdown and store this value in a database. If the item is read from the database I want to populate the input controls with existing values. Is it possible to programmatically set the value in a select dropdown? How?

Cheers,
Dennis

**Comment by acburst** [comment]
What framework are you using for the backend? You can use jQuery if you are familiar with that

**Comment by dbauszus** [comment]
I am using jQuery to set the select dropdown value. This is all working now. The problem was with the active element but I have a workaround for that.

**Comment by carlosperate** [comment]
@dbauszus if you think this is no longer a problem, you can close this issue yourself.
