### ISSUE TITLE
Enable html in tooltip content

### ISSUE THREAD

**Issue by Dahkon** [Dogfalo/materialize#1537]
Hi,

I would really appreciate if you could add html content on tooltip, at least for <br>.
I use tooltips for forms online help and a one line tooltip is not enough.

My easy fix is to replace .text with .html on line 1195 and 1222 of materalize.js but that would be better to implement this optionnaly with something like :

data-enable-html="true"

Thanks,

**Comment by Bound3R** [comment]
would be great!, recently I needed to add a line break or an icon but got to resign and used plaintext :(

**Comment by Rvanlaak** [comment]
:+1:

**Comment by albertpak** [comment]
:+1:

**Comment by blinchi** [comment]
![](https://assets-cdn.github.com/images/icons/emoji/unicode/1f44d.png)

We need this!

**Comment by rikato** [comment]
Jup waiting for this aswell

**Comment by TyrionGraphiste** [comment]
Hi, as said in [#2064](https://github.com/Dogfalo/materialize/issues/2064)

You just have to change the line 59 into the tooltip.js file :

    newTooltip.children('span').text(origin.attr('data-tooltip'));

As :

    newTooltip.children('span').html(origin.attr('data-tooltip'));

**Comment by dcworldwide** [comment]
Really need this. I have two issues, 1) i need html in tooltips and 2) if you have a lot of text in the tooltip, you need to be able to control its width.

**Comment by NeXTs** [comment]
:+1:

**Comment by wdupuy** [comment]
As I don't want to modify the materialize JS file, I use this code
```
$(document).ready(function() {
	$('.tooltipped').each(function(index, element) {
		var span = $('#' + $(element).attr('data-tooltip-id') + '>span:first-child');
		span.before($(element).attr('data-tooltip'));
		span.remove();
	});
});
```

**Comment by akelmj** [comment]
set data-tooltip using jquery not woking:

javascript:
    $('.tooltipped').tooltip({delay: 50,tooltip:"I am tooltip"});

html:
  <a class="btn tooltipped" data-position="bottom" data-delay="50"   >Hover me!</a>

**Comment by tomscholz** [comment]
PR: https://github.com/Dogfalo/materialize/pull/2079
