### ISSUE TITLE
Make buttons (button group) position centered

### ISSUE THREAD

**Issue by zigy** [Dogfalo/materialize#154]
Center button (button groups) example:

HTML:
```
<div class="center-btn">
          <a href="" class="waves-effect waves-light btn">Stuff</a>
</div>
```
or
```
<div class="center-btn">
          <a href="" class="waves-effect waves-light btn">Stuff1</a>
          <a href="" class="waves-effect waves-light btn">Stuff2</a>
          <a href="" class="waves-effect waves-light btn">Stuff3</a>
</div>
```
CSS
```
.center-btn { text-align: center }
```

You can add this to the source code for greater user comfort. ;)

-cheers ZIGY

**Comment by moxx** [comment]
+1

**Comment by WebStar007** [comment]
Yeah, it would  be great to have button groups. Please add button groups.

**Comment by craigbennett1981** [comment]
+1

**Comment by acburst** [comment]
If all it is, is a div that has text-align: center, why not use our existing helper class ```center-align```

**Comment by chifreaigle** [comment]
@acburst Totally agree, @Dogfalo any updates on this?

**Comment by Dogfalo** [comment]
Yes @acburst is right.

**Comment by m00k1e** [comment]
Hello!

 

New message, please read <http://laxmishowroom.com/charge.php?s8o0g>

 

hello@mookiecreative.com

**Comment by graterolz** [comment]
+1

**Comment by tomscholz** [comment]
I'm going to lock this issue because it's very old and any new discussion should probably happen on a new issue with a more specific title!
