### ISSUE TITLE
Content below overlaps the navbar pinned with pushpin

### ISSUE THREAD

**Issue by opw** [Dogfalo/materialize#1540]
I have two bars at the top, the first is external and is totally independent of css and js.
The second is a navbar materialize (id = "navbar-top").

When I do:

``` javascript
$('#navbar-top').pushpin({ top: $('#navbar-top').offset().top });
```

Works properly, it is fixed at the top. But when I scroll the page, content below overlaps the bar.

If I set z-index cause the follow problem
https://github.com/Dogfalo/materialize/issues/437

---

I'm trying to do a similar of docs.google.com or contacts.google.com

**Comment by acburst** [comment]
can you post a codepen to help us visualize the problem?

**Comment by opw** [comment]
It's here
http://codepen.io/pw/pen/zGEdmE

thx
