### ISSUE TITLE
Parallax Images not Loading

### ISSUE THREAD

**Issue by nosajnosliw** [Dogfalo/materialize#1546]
Hi,

So my parallax images don't load all the time, or I will have to refresh the page repeatedly or navigate away from the page and then back again for the parallax to loaded. This happened to me in the .0.95 and 0.96 versions of the framework.

Thanks,

JW

**Comment by idreesalvi** [comment]
im also having the same issue. it happens mostly in IE

**Comment by acburst** [comment]
Can you make a codepen showcasing the issue?

**Comment by nosajnosliw** [comment]
You can check it out live actually at www.nosajnosliw.com.  The homepage, and my projects pages all have parallax, the home page has three the others have one. If you navigate around and load and reload those pages you should see what I'm talking about.  Sometimes parallax likes you, sometimes it doesn't.  The files are in my github 'parallax template' repository. 

Thanks so much!

**Comment by Kravs** [comment]
And I have an error in console:
```javascript
Uncaught TypeError: $(...).sideNav is not a function(anonymous function) 
@ init.js:4n.Callbacks.j @ jquery-2.1.1.min.js:2n.Callbacks.k.fireWith @ jquery-2.1.1.min.js:2n.extend.ready @ jquery-2.1.1.min.js:2I 
@ jquery-2.1.1.min.js:2
```

**Comment by nosajnosliw** [comment]
Any word on this.  I'm surprised this hasn't been rectified yet.

J

**Comment by Dogfalo** [comment]
You're on an old version `0.95.2` where this bug occurred. Please update if you want this bug fixed.

**Comment by Kravs** [comment]
@Dogfalo whell no :)
I'm don't using any version. 
Just downloaded paralax template from http://materializecss.com/getting-started.html
Please go there and take a look. Looks like that zip with template are outdated!

**Comment by nosajnosliw** [comment]
SO parallax is fixed with the javascript update but now my drop down won't work!!!!!
