### ISSUE TITLE
[Feature Request] Material Color picker plugin

### ISSUE THREAD

**Issue by koustuvsinha** [Dogfalo/materialize#1548]
It would be awesome if you could implement a Material design color picker like this :
 
![dribbble_colorpicker](https://cloud.githubusercontent.com/assets/5122822/8251628/ce61d462-169b-11e5-87f1-0664efa12bfd.png)

If it is already available, or supported by some other lib pls comment

**Comment by Dogfalo** [comment]
I am not sure if there are other libs that do this, but it seems like it is something that you could implement fairly quickly. However, this is a bit out of the scope of materialize as a color picker is not a oft needed use case.

**Comment by yanickrochon** [comment]
HTML5 does have an `<input type="color">` element. Where the proposed widget above is complicated, something like [this](https://github.com/evoluteur/colorpicker) would be nice; A simple element displaying it's color value, compatible with the current form layout (i.e. label, placeholder, input, etc.). Then, click handlers could be intercepted to display users' custom dialogs such as the one proposed above.

**Comment by yanickrochon** [comment]
Or something like [this](http://www.dematte.at/tinyColorPicker/index.html?type=mobile#demo).
