### ISSUE TITLE
npm install materialize-css without sass?

### ISSUE THREAD

**Issue by raffw7912** [Dogfalo/materialize#1552]
Don't know if it's a feature or bug, but according to your documentation:

> You can also get the latest release using NPM. this release contains source files as well as the compiled CSS and JavaScript files."

so I would expect to run npm install materialize-css and find css, js, fonts AND SASS (I assume that source files would be less/sass), but all I'm geting is bin (1 js and 1 css file) and font folders.

Bug or feature?

**Comment by miletbaker** [comment]
+1

It looks like this is fixed in 0.97 but it still hasn't been pushed to NPM

**Comment by tehnorm** [comment]
Looks like the package.json file in 0.97 is all sorts of borked... The directories hash is incorrectly specified - It seems like author might have meant to use files instead.

https://github.com/Dogfalo/materialize/blob/ffdaff79411223ab4c7f3f92a071fcf3c2d72ed4/package.json#L13

https://docs.npmjs.com/files/package.json#directories-lib

**Comment by badisa** [comment]
+1

Tried rolling back to an older version but a problem with node-sass prevented me. 

A fix to this would be appreciated

**Comment by Prashank25** [comment]
+1

its still not fixed?!?!?!?

**Comment by acburst** [comment]
Fixed in latest release
