### ISSUE TITLE
Tabbing between form elements causes label-field overlap

### ISSUE THREAD

**Issue by robojamison** [Dogfalo/materialize#1553]
**Scenario:** Filling out a form, tabbing both forward and backward through the fields.

**Outcome:** (expected) When tabbing into a field, the field label shrinks away. When tabbing out of a field, label expands again. (actual) When tabbing into a field, the field label shrinks away but the font size of the input is tiny. When tabbing out of a field, the label expands but the baseline of the field does not (due to the font size), thereby causing the label to overlap the baseline of the field. 

**Documentation:** [Screenshots](http://imgur.com/a/fSJiz) / [CodePen](http://codepen.io/robojamison/pen/Nqawoe)

**Comment by acburst** [comment]
Its because you have the class materialize-textarea on the inputs. That is what ties in the auto resizing textarea feature so adding it to your inputs causes odd effects.

**Comment by robojamison** [comment]
Thanks, I didn't realize I had the textarea class on input elements. I'm using a framework that automatically decides the best HTML tag based on my database type...looks like it got it wrong this time.

Thanks!
