### ISSUE TITLE
Modal with Fixed Footer positioning breaks in IE

### ISSUE THREAD

**Issue by tony-jones** [Dogfalo/materialize#1554]
@Eraknelo pointed out on Gitter that....fixed positioning of modal footer is broken on IE.
Just tested it out and it is indeed breaking,

![screen shot 2015-06-19 at 6 25 00 pm](https://cloud.githubusercontent.com/assets/6729106/8264176/1fb5b95e-16b1-11e5-832b-a812b0ca022b.png)

Here is the code snippet.
```
.modal.modal-fixed-footer .modal-footer {
  border-top: 1px solid rgba(0, 0, 0, 0.1);
  position: fixed; 
  bottom: 0;
}
```

My suggestion is to either use  'position: expression(fixed);' or  'position: relative;'  on the parent element and position: absolute; on the classname.

**Comment by carlosperate** [comment]
Are you using the version from master? Should be already fixed: https://github.com/Dogfalo/materialize/commit/2ca0980f8eb60c0482b8185f0ecceaf3b77e6140

**Comment by Eraknelo** [comment]
I was pointing out it didn't work on the example site. Not currently actually using it.
Maybe the sample site isn't using the latest version?

**Comment by tony-jones** [comment]
@Eraknelo ok. thanks @carlosperate for the update closing for now.
