### ISSUE TITLE
Search Bar inside navbar causes everything else to disappear

### ISSUE THREAD

**Issue by rrphotosoft** [Dogfalo/materialize#1557]
Hi,
I want to implement a simple search bar inside the nav bar.
I want it to appear after the company logo and before the list of links on the right side.
Unfortunately if i add the search bar, the links on the right vanish.
How do I achieve the intended behavior?

Code I'm using:

    <div class="row">
      <div class="navbar-fixed">
        <nav class="blue-grey darken-4">
          <div class="nav-wrapper">
            <a href="#!" class="brand-logo">LOGO</a>
             <form>
              <div class="input-field">
                <input id="search" type="search" required>
                <label for="search"><i class="mdi-action-search"></i></label>
                <i class="mdi-navigation-close"></i>
              </div>
            </form>
            <ul class="right hide-on-med-and-down">
              <li><a href="#">WP Plugin</a></li>
              <li><a href="#">Sign Up</a></li>
            </ul>
          </div>
        </nav>
      </div>
    </div>

**Comment by acburst** [comment]
Just add a margin-left property onto your input-field div

**Comment by rrphotosoft** [comment]
Hi,
I would request you to reopen this issue.
It still does not work.
The search bar runs over the links on the right side.
The margin-left only ensures that it does not overrun the company logo.
On click its height increases beyond the confines of the navbar.
Do you have any working sample code for this?
Regards,
RR.

**Comment by skaxwng** [comment]
Hey rrphotosoft,

	  <div class="navbar-fixed">
	    <nav class="blue-grey darken-4">
	      <div class="nav-wrapper">
	        <a href="#!" class="brand-logo">LOGO</a>
	        <ul class="right" style="position:absolute; right:0;">
						<li><label for="search"><i class="material-icons">search</i></label></li>
	          <li><a href="#">WP Plugin</a></li>
	          <li><a href="#">Sign Up</a></li>
	        </ul>
	         <form>
	          <div class="input-field">
	            <input id="search" type="search" required>
	            <i class="mdi-navigation-close"></i>
	          </div>
	        </form>
	      </div>
	    </nav>
	  </div>

The above could solve your problem. I tinkered your code a lil bit. It's not perfect but it works.
