### ISSUE TITLE
Class hoverable conflicts with table class="hoverable"

### ISSUE THREAD

**Issue by philipraets** [Dogfalo/materialize#1559]
With the new class hoverable, the tables with class="hoverable" get dropshadows around the entire table:
normal:
![normal](https://cloud.githubusercontent.com/assets/708011/8279119/e206fbcc-18d1-11e5-897e-ff35ee50c209.png)

hoverable:
![hoverable](https://cloud.githubusercontent.com/assets/708011/8279121/e420c032-18d1-11e5-9c96-f2af1718b5b8.png)

**Comment by mistakevin** [comment]
+1 Maybe there should be "hoverable" and "floating" classes to separate the features.

**Comment by kabaka** [comment]
It looks like this was fixed in https://github.com/Dogfalo/materialize/commit/7866e719b60b7f95645b8eed9b26e8331c54d006 but this issue was never closed. Just change the `hoverable` class to `highlight`.

I've tested and it seems to be good. :+1:
