### ISSUE TITLE
Unable to compile SASS using SCOUT 

### ISSUE THREAD

**Issue by shantikumarsingh** [Dogfalo/materialize#1560]
I tried not using npm, instead I am using SCOUT compiler for SASS compiling, throws below error

Change detected at 17:05:12 to: materialize.scss
error materialize.scss (Line 10 of _color.scss: Invalid CSS after "...: ( "lighten-5"": expected ")", was ":#fdeaeb,"light...")
create materialize.css

**Comment by abremner** [comment]
Also having this issue... Anyone have a fix?

**Comment by Dogfalo** [comment]
@abremner is right.
