### ISSUE TITLE
Switching tabs then switching back on a page w/ datepicker re-shows datepicker

### ISSUE THREAD

**Issue by robojamison** [Dogfalo/materialize#1563]
On Chrome 43, when browsing a page with a datepicker on it, switching to another tab (without the datepicker active) then switching back causes the datepicker to re-display, dimming the user's screen and potentially causing confusion.

**Codepen:** http://codepen.io/robojamison/pen/waPBrZ

**Comment by Dogfalo** [comment]
Please checked closed issues
