### ISSUE TITLE
slider Plugin Options Height not work

### ISSUE THREAD

**Issue by tomsean** [Dogfalo/materialize#1567]
when set height <400,some show error.

**Comment by ibrainventures** [comment]
+1 .. 
if i take out the height default params from  the un-minified .js file:

    ```javascript
init : function(options) {
      var defaults = {
        indicators: true,
  //       height: 400,
        transition: 500,
        interval: 6000
      };
```
i have the control over the height by mediaqueries .. but with that default param it is not woring

**Comment by fega** [comment]
closed due inactivity. if you are still having problems, please reopen this issue

Also if you provide us a codepen or fiddle showing the problem,it would be very appreciated.
