### ISSUE TITLE
wrong icons displayed on windows

### ISSUE THREAD

**Issue by erredeco** [Dogfalo/materialize#1568]
I set up a little "development" enviroment using grunt, grunt:sass, grunt:connect, grunt:assemble etc
my problem is about the icon font;
on MAC everything works fine, on Windows everything is messed up... the icons are scrambled;
it seems that the unicode characters corresponding to the icons are understood wrong.
I don't understand what goes wrong; do you have some suggestions?

**Comment by carlosperate** [comment]
There has been a change in the icons in the latest version, are you sure you are using 0.97.0 in both development environments?
http://materializecss.com/icons.html

**Comment by erredeco** [comment]
I am using the previous version (and the same version in both the enviroments) but the problem is about the different behavior between Windows and Mac... the icons are shown, but they are not the right ones

**Comment by carlosperate** [comment]
If you are using a version prior 0.97 make sure the css/javascript files are from the same master commit as the fonts, as there was also changes on those, so if you updated the one without the other you would experience that behaviour.

**Comment by erredeco** [comment]
@carlosperate please close: you were right: the fonts were different.
Just a question: with the new method of adding the icons:

 <i class="material-icons">stay_primary_landscape</i>

you will end with a lot of "nonsense" text inside your page ("stay_primary_landscape") that will be indexed by search engines. Am I right? Isn't this harmful? 
And it will be also read by assistive technologies, unless you add:

 <i class="material-icons" aria-hidden="true">stay_primary_landscape</i>

**Comment by carlosperate** [comment]
I'm not a maintainer, but if you feel your issue has been solved you can close it from you account.

About the indexing, I must admit that I don't know if this will have any effect, but I do agree with the fact that it doesn't seem very friendly for web assistive technologies. I haven't tried it myself, so I haven't really looked at the final form of the DOM, maybe the `<i>` content gets replaced, but I personally don't know.

**Comment by Dogfalo** [comment]
@erredeco This is the official google icon font they have made. I am sure most search engines now can pick apart what is content and what is not.
