### ISSUE TITLE
Is there any way to initialize functions with one line?

### ISSUE THREAD

**Issue by LouisWayne** [Dogfalo/materialize#157]
Trying to use Materialize with Angular templates - is there any way to initialize all functions with one line?

something like this: 

$( document ).ready(function() {
    materialize.init();
});

**Comment by prateek0103** [comment]
I am using latest Materialize.css and Materialize.js
Which function is needed to called for initializing animation on form input elements?

**Comment by dhawken** [comment]
Hey Louis, I am using the jquery passthrough in Angular UI instead of having explicit code to init all the components.  Works quite well and avoids clutter IMO.
