### ISSUE TITLE
Material Select remaining caret icon on destroy

### ISSUE THREAD

**Issue by avcreation** [Dogfalo/materialize#1570]
When using the $('select').material_select('destroy') command, the select correctly disapear, but letting the caret icon in parent DOM element.

Here is a fiddle for example : 

https://jsfiddle.net/4nbq2ymv/

Thx,

**Comment by philipraets** [comment]
In addition:
Updating adds extra caret icons to the select

http://codepen.io/anon/pen/XbzMva

**Comment by carlosperate** [comment]
Can confirm I am experiencing the same issue.

**Comment by ricardodovalle** [comment]
:+1:  I am getting the same issue:
http://pastebin.com/zyS0yjTx

**Comment by Cerealkillerway** [comment]
having the same issue

**Comment by acburst** [comment]
Fixed in cbcf4c8

**Comment by rkusuma** [comment]
@acburst is it not yet fixed in latest release 0.97.0.

**Comment by uok** [comment]
if you click on https://github.com/Dogfalo/materialize/commit/cbcf4c8f6c229f42dba1dd3ccde1788d7f96ff80 you can see at the top left "master" which means that it is commited, but not released. if you see a number there in the future, e.g. 0.97.1, it's released

**Comment by meichenblatt** [comment]
When will it be released?

**Comment by OminStyle** [comment]
I'm experiencing the same problem and waiting for the release.

**Comment by SomilKumar** [comment]
I too experienced the same issue , waiting for the release ...

**Comment by OminStyle** [comment]
You can add $select.parent().find('input, i, .caret').remove(); on re-initialization to fix this issue until the next release.

**Comment by serkandurusoy** [comment]
I just tried a fresh checkout of the master and the problem still seems to be there. No change of the extra caret behaviour.

I'm using meteor, if that matters.

**Comment by lasseborly** [comment]
Has been fixed in v0.97.1 @serkandurusoy.
