### ISSUE TITLE
google web font in documentation, but not in code

### ISSUE THREAD

**Issue by dheerajbhaskar** [Dogfalo/materialize#1571]
I was looking at the documentation it didn't as described in code.

Then I looked at the repository and saw that only yesterday the google-font branch was merged to master. Are these changes in 0.97.0 ? If not when would this be released?

I wish you had updated the documentation after the package was updated in atmospherejs. 

I'm just sitting here with new documentation and old code, neither of them being useful at this moment.
Please help.

**Comment by muhajirframe** [comment]
I thinks it's pretty clear here http://materializecss.com/icons.html .

**Comment by gnicol-bzh** [comment]
As far as I'm concerned, I'm looking for the "old" Materialize CSS Icon list (with "old names"), for we can't update the framework so close to the deadline of our project ;). I look into bower_components but  there is no documentation there...
Using 0.96.1.

**Comment by Dogfalo** [comment]
You can go to github and see every release documentation

**Comment by reinaldo122** [comment]
I have the same issue, when you use an icon it doesn't render the icon, just displays the name of the icon, I just had to include Material Design Icons from Google Fonts after materialize.css as a workaround.
`<link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">`

**Comment by dheerajbhaskar** [comment]
I'm using  the following document for old names:
 https://github.com/Dogfalo/materialize/blob/19029513c79fc6edd470e478b56c016ee18b9ce9/sass/components/_icons-material-design.scss

I'm using this to search for icons to use:
http://www.google.com/design/icons/
