### ISSUE TITLE
.btn and .btn-large should be auto height

### ISSUE THREAD

**Issue by Dmitrev** [Dogfalo/materialize#1574]
Whenever i make the text of a button larger, i want it to fit automatically without changing the height manually everytime. This however not possible at the moment, please see this example:

[Example of the issue](http://codepen.io/anon/pen/qdVNgN)

[Possible solution](http://codepen.io/anon/pen/jPardX)

Do you guys agree with me?

**Comment by lwiklander** [comment]
Yes, I ran into this issue just now as well.
Line-height also needs to be adjusted together with padding, in order to handle new lines in a graceful way regardless of text size.

**Comment by acburst** [comment]
These btn classes are using standard dimensions. If you want to make buttons that fall outside these I would recommend adding your own custom classes on top to override our height.
