### ISSUE TITLE
Add a root css class for apply form style

### ISSUE THREAD

**Issue by patou** [Dogfalo/materialize#1575]
We want to use materializecss in other website, but the form style (input, select, textarea) replace the website style.
Can you add a root css class for apply form style : 
```css
.form-component input { ...}
.form-component select { ...}
.form-component select { ...}
```

```html
<form class="form-component">
   Materialize form
   <input>
   <textarea>
</form>
<form>
   Non materialize form
   <input>
   <textarea>
</form>
```

**Comment by acburst** [comment]
You can add it in the sass but as a framework we aim to keep our styles not specific as possible to help users customize and override our base styles.
