### ISSUE TITLE
Search bar's close icon appearing out of the bar

### ISSUE THREAD

**Issue by marcoscssno** [Dogfalo/materialize#1577]
![screenclip](https://cloud.githubusercontent.com/assets/8012585/8314320/251b1702-19bf-11e5-9485-ac311193036e.png)

Here's a [jsfiddle](http://jsfiddle.net/78125vs0/).

**Comment by acburst** [comment]
Fixed in 43d43c2, Also in your fiddle you have the red-text class on the icon, which will break things because it won't be hidden on the start. I suggest removing that.
