### ISSUE TITLE
issue about transition in input field

### ISSUE THREAD

**Issue by dropper33** [Dogfalo/materialize#1578]
If someone have problem, as me, because there is no transition in input label, there is a missing part of css from the file you download from materializecss.com

how to solve:

search input[type=text]:focus:not([readonly]) + label,.... in css file and add

font-size: 0.8rem;
    -webkit-transform: translateY(-140%);
    -moz-transform: translateY(-140%);
    -ms-transform: translateY(-140%);
    -o-transform: translateY(-140%);
    transform: translateY(-140%); 

hope to help you.
Bye, Sam

**Comment by acburst** [comment]
The transitions and transform styles are under .input-field. Check again to see if you aren't missing that wrapping class
