### ISSUE TITLE
Now that Google Icons are part of Materilize remove old icons CSS classes

### ISSUE THREAD

**Issue by MrRafalSzymanski** [Dogfalo/materialize#1581]
As stated in the title - you advise to use Google Icons so it's quite obvious the old solution should be removed from the CSS (rules for classes that start with "mdi-"). This will make the css file much much smaller.

**Comment by carlosperate** [comment]
It will also break any project implementing the framework that only updated for bug fixes.

**Comment by MrRafalSzymanski** [comment]
Than maybe the css part that describes icon should be seperated and included as additional resource?
This way the basic css would be smaller and including the font css would allow projects to work without issues.

**Comment by acburst** [comment]
We are keeping the styles in for at least a couple more releases to give backwards compatibility. You are always free to remove the icon classes from the compiled css yourself but we think its important to not make too many jarring changes for our users
