### ISSUE TITLE
0.9.7 not published on npm

### ISSUE THREAD

**Issue by vincentmorneau** [Dogfalo/materialize#1583]
Can you please keep Bower and NPM synchronized? Thanks.

**Comment by raffw7912** [comment]
+1 for that! I had to download everything manually from GitHub! :+1:

**Comment by aequasi** [comment]
+1

**Comment by supadupdip** [comment]
+1

**Comment by ehud117** [comment]
+:+1:

**Comment by Dogfalo** [comment]
Been having an error trying to publish to npm, it seems to think there is already a version that exists

`"You cannot publish over the previously published version 0.97.0." : materialize-css`

**Comment by supadupdip** [comment]
Saw that when i ran the npm info materialize-css command

{ name: 'materialize-css',
  description: 'Builds Materialize distribution packages',
  'dist-tags': { latest: '0.96.1' },
  versions: [ '0.95.3', '0.96.1' ],
  maintainers: 'materialize <materializeframework@gmail.com>',
  time: 
   { modified: '2015-06-22T01:34:19.494Z',
     created: '2015-02-27T17:45:42.343Z',
     '0.95.3': '2015-02-27T17:45:42.343Z',
     '0.96.1': '2015-04-07T04:18:11.404Z',
     '0.97.0': '2015-06-22T01:29:26.639Z' },.......

**Comment by Dogfalo** [comment]
Reading from https://github.com/npm/npm-registry-couchapp/issues/148, it seems npm will have to updated when the next version is released.

**Comment by smithb1994** [comment]
I'm confused... so npm is not allowing new versions? When will this be fixed? As of right now materialize is still on 0.96.1 on npm. 
When can we expect to see 0.97.0?

**Comment by carlosperate** [comment]
I thin 0.97.0 will be skipped from npm and the next version should be publishable there.

**Comment by plestik** [comment]
So... you're just not going to release this version on npm? NPM users will have to wait until 0.97.1 is published? How long will that be?
