### ISSUE TITLE
Host versionized documentation

### ISSUE THREAD

**Issue by jcapogna** [Dogfalo/materialize#1586]
We're still using 0.96.1 until we find time to upgrade, regression test our applications, and fix whatever breaks. 

It would be awesome if the documentation was versionized so that I could go to materializecss.com/0.96.1 and see the documentation for the version I'm using. This feels like a necessity to me and anybody else using Materialize in a professional environment, especially if there are going to be breaking changes between versions.

**Comment by Dogfalo** [comment]
You can use git to download all the previous versions of documentation

**Comment by jcapogna** [comment]
I know. I am hosting the old documention internally for my team. 

From the chatroom, there are at least a few people using Materialize in professional projects where upgrading to a new version with breaking changes is not something quickly done. Being able to point developers and designers at the right version of the documentation would be very helpful to me. 

I don't know how you're hosting the site (is it github pages?), but it seems like it would be easy to copy the documentation from each release into a versionized directory.

**Comment by tomscholz** [comment]
@acburst @Dogfalo What about moving the documentation into a seperate repo or in a folder called `/docs` ?

**Comment by tomscholz** [comment]
I started a little project [here](https://github.com/tomscholz/materialize-archive)

**Comment by DanielRuf** [comment]
@tomscholz could be get really big. Why not tagged branches? Just my two cents / personal opinion ;-)

**Comment by tomscholz** [comment]
Actually not my code, but you are right. When we use tagged branches we can't use github hosting
Original source: https://github.com/materialize/archive
