### ISSUE TITLE
<abbr> & <acronym> default CSS

### ISSUE THREAD

**Issue by valerio-bozzolan** [Dogfalo/materialize#1588]
Simple enhancement:

Add a ```cursor:help``` to abbr and acronym tags :)

**Comment by Dogfalo** [comment]
I think we'll leave this up to the developers themselves to do if they want it

**Comment by valerio-bozzolan** [comment]
I thought that everyone want to notify the user about the presence of these very-very-very-specific tags. In any case..
Thanks for this great framework.
