### ISSUE TITLE
Transform a floating action button into a toolbar

### ISSUE THREAD

**Issue by hanfeisun** [Dogfalo/materialize#1592]
Below is a demo from Material Design Spec

http://material-design.storage.googleapis.com/publish/material_v_4/material_ext_publish/0B8v7jImPsDi-ajMzVHp3VzJ4UkU/components-buttons-fab-transition_toolbar_02.webm

I found the effect of transforming a FAB into a toolbar attractive and useful.. Is it possible for MaterializeCSS to add this feature?

**Comment by sam-g-steel** [comment]
I think I'm going to look into it! It should be pretty easy!

**Comment by emd2009** [comment]
Please keep us updated!

**Comment by sam-g-steel** [comment]
Sure, I might have some thing tonight!

**Comment by sam-g-steel** [comment]
Wow! so this is harder than I thought!!! I've been working on this in codepin and think I will share the link in a few hours. Still trying to tweak a few things!

**Comment by emd2009** [comment]
Looking forward to it!

**Comment by sam-g-steel** [comment]
I've been really sick the last week, tried several ideas and this is what I have so far. Still very much WIP
http://codepen.io/sam-g-steel/pen/MwQVwv

**Comment by emd2009** [comment]
great start!

**Comment by emd2009** [comment]
any update on this?

**Comment by acburst** [comment]
Added in 5dab6f021e22456d55753f6d9b6aabbafd6d6383
