### ISSUE TITLE
[JS] Input file don't work when loading with ajax

### ISSUE THREAD

**Issue by reidark** [Dogfalo/materialize#1594]
Hello guys.
In my application, I have a form that loads with ajax, and in this form has some input file.
I've tested, when i put this input file in a normal page, it works fine, but, when it load with ajax, it don't work as expect.

Have a fix for this?

**Comment by carlosperate** [comment]
Fixed in https://github.com/Dogfalo/materialize/pull/1733 https://github.com/Dogfalo/materialize/commit/7bec3393da3888ebdb83abf45680182d049ded6e.
