### ISSUE TITLE
there was too many compatible in webkit 534.30

### ISSUE THREAD

**Issue by joebnb** [Dogfalo/materialize#1600]
at first this css framework is beautiful,i like it so much.
but it incompatible android 4.1 browser...there are a lot of device runing in android 4.0 between 4.4...i think the lower version also has the compatible problem,
![p50625-205727](https://cloud.githubusercontent.com/assets/1646883/8376674/5a30c318-1c3c-11e5-9e7e-d3641d9490c0.jpg)
in this picture it contains a modal with fixed footer，oast and a card fix in bottom have problem
in android 5.0 it was ok
![s50625-203402](https://cloud.githubusercontent.com/assets/1646883/8376732/bdcbec0e-1c3c-11e5-8ead-9b5a51726fd3.jpg)
can we fix this？

**Comment by carlosperate** [comment]
Are you using the latest version of the framework? the modal with fix footer has been updated in 0.97

**Comment by joebnb** [comment]
15days ago version….toast has problem also


来自 魅族 MX4 Pro

-------- 原始邮件 --------
发件人：Carlos <notifications@github.com>
时间：周四 7月2日 00:15
收件人：Dogfalo/materialize <materialize@noreply.github.com>
抄送：Never <joebnb@qq.com>
主题：Re: [materialize] there was too many compatible in webkit 534.30 (#1600)

**Comment by carlosperate** [comment]
v0.97.0 has been release 11 days ago, try that one.

**Comment by carlosperate** [comment]
Since it has been over a month I assume you have resolved your issue with v0.97.0. If this is still a problem you can reopen it.

**Comment by MoonlightMultimedia** [comment]
This issue still exists in v0.97.0, tested on Android 4.1 native browser.
