### ISSUE TITLE
update documentation on site

### ISSUE THREAD

**Issue by MurWade** [Dogfalo/materialize#1601]
Go here on http://materializecss.com/dropdown.html

Under Options

It says **constrainwidth** If true, constrainWidth to the size of the dropdown activator. Default: true

But the actual json option is `constrain_width`.

**Comment by wiitohzjeh** [comment]
I guess the problem is not the documentation isn't updated, maybe who write it. If you take a look, and go down to the "initialization" code example, you will see the code is right.

**Comment by carlosperate** [comment]
`constrainwidth` is the data attribute that can be added into the HTMl.
`constrain_width` is the name of the javascript options property.
You can see in [js/dropdown.js#L32-33](https://github.com/Dogfalo/materialize/blob/70cfedca9ceeb23f702e64805e490111b5d264e3/js/dropdown.js#L32-33) how they relate.

Perhaps `constrain_width` could have been named `constrainWidth` in the javascript to follow the same convection as the others, but the documentation seems correct as it is.
