### ISSUE TITLE
New vs. old icons

### ISSUE THREAD

**Issue by corbindavenport** [Dogfalo/materialize#1606]
I just noticed that the latest version of the Materialize framework recommends using Google's CSS icons instead of the ones Materialize has used for a while. Even though Google seems to have more icons, and of course they are official, but they seem to have a lot of problems with Materialize.

For example, take a look at the old (first two) vs. new icons (third) on sideNav:

![capture](https://cloud.githubusercontent.com/assets/3879063/8390346/5a0f8b28-1c5d-11e5-8351-5bed27132ca7.PNG)

The latest version of the framework still seems to have the old icons, is it possible to add the list of old icons (and syntax) back to the website as an alternative to Google's icons? I could make a commit with the changes if needed.

**Comment by carlosperate** [comment]
They are trying to phase out the use of the old icons gradually. So, not
having them in the documentation is a step towards that direction.

**Comment by Dogfalo** [comment]
The new icons should work the same way, try adding `left` to the icon class

On Sat, Jun 27, 2015 at 4:37 AM, Carlos <notifications@github.com> wrote:

> They are trying to phase out the use of the old icons gradually. So, not
> having them in the documentation is a step towards that direction.
>
> On Sat, 27 Jun 2015 04:47 Corbin Davenport <notifications@github.com>
> wrote:
>
> > I just noticed that the latest version of the Materialize framework
> > recommends using Google's CSS icons instead of the ones Materialize has
> > used for a while. Even though Google seems to have more icons, and of
> > course they are official, but they seem to have a lot of problems with
> > Materialize.
> >
> > For example, take a look at the old (first two) vs. new icons (third) on
> > sideNav:
> >
> > [image: capture]
> > <
> https://cloud.githubusercontent.com/assets/3879063/8390346/5a0f8b28-1c5d-11e5-8351-5bed27132ca7.PNG
> >
> >
> > The latest version of the framework still seems to have the old icons, is
> > it possible to add the list of old icons (and syntax) back to the website
> > as an alternative to Google's icons? I could make a commit with the
> changes
> > if needed.
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <https://github.com/Dogfalo/materialize/issues/1606>.
>
> >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Dogfalo/materialize/issues/1606#issuecomment-116017123>
> .
>



-- 
Doggy sends his greetings from Mars.

**Comment by TomFreudenberg** [comment]
Excuse me, just for clarification: So are the "old" Icons (delivered via embedded Material-Design-Icons fonts) are deprecated by now? Will they be removed in newer releases?

Thanks for short feedback
Tom

**Comment by TomFreudenberg** [comment]
Hi, I came along with an additional question which was coming up during discussion at meteor package integration of materializecss

https://github.com/poetic/meteor-materialize-sass/issues/5

Instead of implementing the usage of offline Material-Icons font like described at:

https://google.github.io/material-design-icons/

wouldn't it be the correct way to directly implement those fonts to materializecss itself like the Roboto fonts as well?

If you reply with your suggestion I can create a PR for the project if you like.

Cheers
Tom

**Comment by TomFreudenberg** [comment]
I moved my original comment from here to a new issue

**Comment by Dogfalo** [comment]
The old icons are now removed from the repo and you should import the ones from google if you wish to use material icons.
