### ISSUE TITLE
Wave-circle doesn't work well in Safari.

### ISSUE THREAD

**Issue by hanfeisun** [Dogfalo/materialize#1607]
I found  `wave-circle` doesn't work in Safari, though it works well in the newest version of Chrome. 

In Safari (8.0.5) , I added `wave-circle` class into a button, but the wave still expands to a square, instead of a circle.    This could be reproduced in the `Circle` Section of the official document.  http://materializecss.com/waves.html#!

Here is a [Stackoverflow question](http://stackoverflow.com/questions/29431250/materialise-wave-affect-doesnt-work-properly-in-safari) about this issue. However, the solution mentioned in the answer doesn't have any effect in my Safari browser.

**Comment by fega** [comment]
@hanfeisun would you kindly to check if this is still a problem?

**Comment by hanfeisun** [comment]
I checked it in latest Safari (10.1). And the issue doesn't exist now, at least for http://materializecss.com/waves.html#!.  Maybe this issue could be closed.
