### ISSUE TITLE
icon perm_identity was wrong

### ISSUE THREAD

**Issue by zetay** [Dogfalo/materialize#1608]

**Comment by Dogfalo** [comment]
Please direct any issues you encounter with the icon font here: https://github.com/google/material-design-icons

**Comment by zetay** [comment]
Sorry, Google material design icons was correct, but mdi-navigation-menu was wrong. "menu"'s codepoint in https://github.com/google/material-design-icons/blob/master/iconfont/codepoints is e5d2, but in materialize is e8af, which is "question_answer" in Google material design icons.
