### ISSUE TITLE
Checkbox don't work in MVC-EJS template

### ISSUE THREAD

**Issue by eeeduuu** [Dogfalo/materialize#1609]
Hello,
I'm using the MVC framework with EJS templates.
If I use input checkbox in the HTML page work perfectly but if I use input checkbox inside EJS template that loads code HTML dynamically not work . Draw checkbox properly but is not marked.
I have looked if there was a way to initialize the object via JS after code load but I have not found in the documentation.
The IDs and FORs are properly assigned.
Any ideas?
Thank You
Eddy

**Comment by fega** [comment]
yeah, check http://materializecss.com/forms.html
