### ISSUE TITLE
Simple uri bug in parallax template

### ISSUE THREAD

**Issue by Kravs** [Dogfalo/materialize#1610]
In the parallax template there is an issue with linking script, please change this

```
<script src="../../dist/js/materialize.js"></script>
```

to this:

```
<script src="js/materialize.js"></script>
```

**Comment by Dogfalo** [comment]
you're probably looking at `preview.html` instead of `index.html`

**Comment by Kravs** [comment]
in parallax-template.zip there is only one html file - index.html
And when i changed the path as described above everithing start working :)

**Comment by Kravs** [comment]
@Dogfalo , I want to mension that in sources it looks corect, because near templeate folder you reallu have "dist".
BUT when you download templates from web-site as a dir it seems that dist and template are merged in following structure:
![image](https://cloud.githubusercontent.com/assets/1693842/8393158/b9dcac62-1d0b-11e5-87de-928ccd60ab91.png)

and there is no dist folder.

Now i think it is not bug in code, but rather zip is not up to date

**Comment by DominikTV** [comment]
+1

**Comment by tomscholz** [comment]
The Zip is up to date and working. Please close!

**Comment by tomscholz** [comment]
The Zip is up to date and working. Please close!
