### ISSUE TITLE
using custom js files 

### ISSUE THREAD

**Issue by baraamashaal** [Dogfalo/materialize#1611]
i want to use custom js files not the hole materialize.js file 
my question what is the main dependencies :)

another question
i made some change to the js , scss  files okay !
and i want to upgrade to the new version and if i do every thing will be lost

is there a right way to customize the files without losing any thing in upgrading ?!
sorry for bad english

**Comment by Dogfalo** [comment]
The easiest way to build your own materialize is to clone this repo, and run grunt monitor and edit the JS files. The grunt script will produce a new materialize.js file for you
