### ISSUE TITLE
Character Count works with invalid html attribute

### ISSUE THREAD

**Issue by janpieterz** [Dogfalo/materialize#1612]
The character counter works with an invalid html attribute (length) instead of using maxlength or a data-attribute.

I couldn't find the length anywhere in the specs (http://www.w3.org/TR/html5/forms.html#the-input-element). I'm using React which eliminates all attributes that are not in the specs.

In case you guys would like to get this solved, I'm more than willing to transform it towards whichever option (maxlength or data-) has your preference.

**Comment by acburst** [comment]
We aren't using max length because that restricts the characters to that number. Currently its possible to go over that and just be shown a number greater than the character count.

**Comment by janpieterz** [comment]
Yup, figured that out after trying both solutions. See the pull request for a data-max-length version.
