### ISSUE TITLE
problem adding dynamic select lists

### ISSUE THREAD

**Issue by jots** [Dogfalo/materialize#1618]
I am cloning a table row that contains select lists.  after I append it, the select list is disabled.
if I add: $('select').material_select();  after appending it, it creates a duplicate select list which works, but leaves the select list that doesn't work.

uncomment out the $('select').material_select(); in:
http://jsbin.com/hutuzagaqu/edit?html,js,output

to see what I mean.

**Comment by rexopl** [comment]
Hello, yeah there are some problems with selects. I even do material_select('destroy') and then create new one material_select() but it seems that after destroy some code left: "<span class="caret">▼</span>". 
After few destroy, create i have many carets above my select.

**Comment by smark91** [comment]
same here.
Dropdown not dynamically create on a page. when material_select() a ▼ appears for every time the function is call.

**Comment by Stroncickiy** [comment]
i have same problem

**Comment by kai23** [comment]
+1

**Comment by smark91** [comment]
find a fix.
already pull request.

https://github.com/Dogfalo/materialize/pull/1656

**Comment by carlosperate** [comment]
If this issue is only regarding the left over caret, it has already been fixed. You can get the latest built version from the bin folder.
Original issue: https://github.com/Dogfalo/materialize/issues/1570
Commit: https://github.com/Dogfalo/materialize/commit/cbcf4c8f6c229f42dba1dd3ccde1788d7f96ff80

**Comment by acburst** [comment]
The caret bug has been fixed already. I think the problem lies with you cloning the select after you've initialized it with our plugin. Initializing it with our plugin is what creates the structure so if you clone an already initialized select it will duplicate the structure. Try instead of cloning it, creating it from scratch or some different way of cloning .

**Comment by rexopl** [comment]
The problem still occurs on master version.

**Comment by sheki** [comment]
I think this exists and is a big issue for react.
