### ISSUE TITLE
New Material Icons - Self Hosting

### ISSUE THREAD

**Issue by TomFreudenberg** [Dogfalo/materialize#1619]
Hi, I came along with an additional question which was coming up during discussion at meteor package integration of materializecss

https://github.com/poetic/meteor-materialize-sass/issues/5

Wouldn't it be the correct/better way to directly implement the Material-Icons fonts to materializecss itself like the Roboto fonts as well, as described at:

https://google.github.io/material-design-icons/

instead of using Google fonts ressources

If you reply with your suggestion I can create a PR for the project if you like.

Cheers
Tom

**Comment by TomFreudenberg** [comment]
I create an PR to meteor materialized packages but I would prefer to include something like that directly to the materializecss project.

Maybe you like that as well: https://github.com/poetic/meteor-materialize-sass/pull/6

**Comment by acburst** [comment]
We don't see the need to include the package for everyone. If an individual wants to self host the icons, they can easily follow the directions on the google site and do it themselves.

**Comment by TomFreudenberg** [comment]
Hi Alan @acburst 

thanks for feedback. Isn't this the same as with Roboto font and currently still included Material-Design-Icons fonts? So in what case do you make a difference to deliver those fonts but not the new Material-Icons font.

Thanks for a short clarification

Tom
