### ISSUE TITLE
Dynamically adding 'active' class to selector

### ISSUE THREAD

**Issue by SimonKomlos** [Dogfalo/materialize#1620]
I'm using localstorage to remember users responses on my selector, and I'd like the `active` selector to be added to an `li` dynamically. 

I've gone with this route, but it doesn't seem to be working for me... Am I missing something or do I need to be doing something else? I'd really appreciate the advice.

        function loadResponses() {
        
                $(".selectFeed .dropdown-content li:nth-child("+activeIndex+")").addClass('active');
                $('select').material_select();
              
        }

Using the above code doesn't seem to work. `activeIndex` is the value that is being stored in the localstorage... Any ideas? Thanks.

**Comment by acburst** [comment]
can you post a URL or a codepen?

**Comment by SimonKomlos** [comment]
@acburst I've decided to go with a different approach. I suppose I'll close this thread.. Thanks anyway.
