### ISSUE TITLE
Range Slider (Forms) doesn't update the current value during slide

### ISSUE THREAD

**Issue by yatharthk** [Dogfalo/materialize#1621]
The range slider doesn't update the current value of range bar during slide. The value in [.thumb] is updated only when the (mouseup/touchend) event is triggered.

The current value in [.thumb] must be updated as the user slides through the bar. This would help to select accurate value easily. In fact, it's a very basic feature that must be provided to user.

The current issue can be seen on codepen at http://codepen.io/anon/pen/QbaqVK

The solved issue can be seen on codepen at http://codepen.io/anon/pen/GJyJGK

**Comment by acburst** [comment]
Thanks for contributing to the pull request!
Merged in 13c600a3eea362bf89c1a3866fabc6d6cc2cc98a
