### ISSUE TITLE
Dropdown on collection limit

### ISSUE THREAD

**Issue by the-new-sky** [Dogfalo/materialize#1627]
Hi guys, I have a little problem with dropdown, i think it's a bug, let see : 
http://www.noelshack.com/2015-27-1435588735-dropdown-problem1.png
http://www.noelshack.com/2015-27-1435588742-dropdown-problem2.png

the problem occur when a dropdown button are IN a collection, how to solve it ???

**Comment by the-new-sky** [comment]
Nobody ???

**Comment by gauravmuk** [comment]
@the-new-sky can you post a working demo of the problem you are having?

**Comment by the-new-sky** [comment]
See at : https://gist.github.com/the-new-sky/b455c4b1c1b401d10e27

**Comment by philrennie** [comment]
Had this today.
I set overflow:visible on .collection to solve it in my instance.

**Comment by serkandurusoy** [comment]
Having the same problem.

**Comment by the-new-sky** [comment]
Sorry, i didn't say that : @philrennie solve the problem !
I close this issue.

**Comment by serkandurusoy** [comment]
Well, that's a workaround, not a solution.

**Comment by the-new-sky** [comment]
It's true, if we add this CSS property in materialize.css, the "bug" was solve ?
We can potentialy create a pull request, it's easy.
Sorry for the bad english, i'm french.

**Comment by serkandurusoy** [comment]
No problem, I'm not native either :)

I don't think adding this CSS snippet solves the actual problem because I'm sure they have made it `overflow: hidden` for a reason in the first place.

So it is best if we knew *why* it is like that and what else can be done to provide a general solution.

**Comment by fega** [comment]
@the-new-sky Are you still having the problem? can you share us a codepen or fiddle snippet?

Also, do you tried placing the dropdown markup out of the collection? 

feel free to reopen it if it is needed
