### ISSUE TITLE
Having trouble trying to reproduce this tab effect

### ISSUE THREAD

**Issue by rafaelfragosom** [Dogfalo/materialize#1636]
I've started using materialize 2 days ago and I really liked this showcase's [website](http://www.straphq.com/). They are using the tabs to create a menu in the header, so far so good, I managed to get the same result but the scrolling effect. 

When you scroll the page, the tabs updates itself without clicks, and that's what I want.

Can anyone help me?

**Comment by acburst** [comment]
It seems to be a scrollspy effect. You can try adapting our scrollspy (materializecss.com/scrollspy.html) to achieve this or look at some scrollspy plugin online.

**Comment by rafaelfragosom** [comment]
Thanks!
