### ISSUE TITLE
Installing materialize using jspm

### ISSUE THREAD

**Issue by zeeshanjan82** [Dogfalo/materialize#1637]
When I try to install the materialize framework using jspm install github:dogfalo/materialize  I get error : error getting package config for github:dogfalo/materialize also the same error comes when I try installing it using :
jspm install github:dogfalo/materialize -o "{ main: 'js/bin/materialize.js', shim: { 'js/bin/materialize.js': ['jquery'] }, format: 'global', dependencies: { 'jquery': '*' }, registry: 'jspm'}"

How do I install materialize using jspm as well as install its dependencies?

**Comment by zeeshanjan82** [comment]
I even get the same error when doing simply jspm install github:dogfalo/materialize. I have attached the screenshot.
![jspm](https://cloud.githubusercontent.com/assets/8342604/8446264/858663a6-1fc5-11e5-8751-c79b19dcb65c.png)

**Comment by nrvru** [comment]
I get the same error, but with 0.96.1 is all ok.

**Comment by nrvru** [comment]
In 0.97.0 was missing a comma in package.json. This is fixed in master, but from jspm docs "Commit-based installs are not supported for the GitHub registry currently", so you can't install the version from master. Need to wait for the new version or use old 0.96.1.

**Comment by flieks** [comment]
i have same problem. Ok i'll wait

**Comment by zeeshanjan82** [comment]
The issue is fixed , I have checked int on 0.97.0
