### ISSUE TITLE
material_select() options ?

### ISSUE THREAD

**Issue by razy69** [Dogfalo/materialize#1638]
Hi, is there any options like dropdown for material_select ? 

``` js
$('select').material_select({
    maxHeight: 200px,
    belowOrigin: true
}); 
```

**Comment by Johann-S** [comment]
+1 for this two features

**Comment by TyrionGraphiste** [comment]
Hi, I included this in my PR.

**Comment by fega** [comment]
Closed due inactivity, feel free to reopen it if it is still necessary.
