### ISSUE TITLE
ScrollFire Firefox bug

### ISSUE THREAD

**Issue by pimmey** [Dogfalo/materialize#1640]
ScrollFire fires way sooner on Firefox than in other browsers. For instance, check out the demo page http://materializecss.com/scrollfire.html, scroll slower than usual to notice the bug.

Tested on Firefox 38.0.5 Linux and Mac versions.

**Comment by davetgreen** [comment]
Experiencing the same issue using latest FF Dev Edition build on OSX.

**Comment by kestutis-stalmokas** [comment]
This is actually Chrome's problem, see http://stackoverflow.com/a/20060513/606321

ScrollFire uses document.body.scrollTop, I switched that to window.pageYOffset and it works OK with latest FF and Chrome. Can anyone try this in IE?

**Comment by Dogfalo** [comment]
I tested it in IE and it worked well. Thanks for the fix.
717bd17
