### ISSUE TITLE
No more padding in the container?

### ISSUE THREAD

**Issue by steelcowboy** [Dogfalo/materialize#1641]
I noticed that the text on my site was lining up at the edge of the container div. Upon comparing it to version 0.96, it appears that `padding: 0 1.5rem` seems to be missing from the newer version. Also, the flow text has a lot less line spacing. Was this intentional? If so, why?

EDIT: Line spacing does not seem to work at all when I try setting the line-height property. Here is what my site looks like: https://steelcowboy.me/

Here is how I want the text to look -- and how it did on 0.96: http://imgur.com/AU6352m

**Comment by Dogfalo** [comment]
The fixed padding was removed, there was an issue about this raised earlier, the fixed padding was taking up a lot of precious space on smaller screens. I dont know why the line spacing would have changed. I don't believe any change was made to general text line spacing
