### ISSUE TITLE
SASS version on npm

### ISSUE THREAD

**Issue by zeeshanjan82** [Dogfalo/materialize#1642]
I am not able to find any sass version of the materialize library on npm all I find is this project on npm but it does not include the javascript files. How can someone who would like to work on sass version of materialize use this library , I can download the sass version but I would like have it on npm so it is easy to download.

**Comment by KonanMentor** [comment]
+1

**Comment by mike-north** [comment]
+1 - Angular/React/Ember communities would love this, I'm sure

**Comment by tisto** [comment]
+1

**Comment by acburst** [comment]
Fixed in latest release

**Comment by zeeshanjan82** [comment]
Does the npm package https://www.npmjs.com/package/materialize-sass  include the SASS version now?

**Comment by zeeshanjan82** [comment]
What has been fixed in latest release?

**Comment by Dogfalo** [comment]
The sass files are now included in the npm release

**Comment by zeeshanjan82** [comment]
Thanks @Dogfalo and @acburst for the update.
