### ISSUE TITLE
Long texts in dropdown inside sidenav overflowing into next button

### ISSUE THREAD

**Issue by dinoilic** [Dogfalo/materialize#1646]
As you can see in the picture, text `Structures` shouldn't be overlapping `Computer Architecture` and also `Object Oriented Programming` shouldn't be broken into two lines.

![2015-07-01--1435758714_303x352_scrot](https://cloud.githubusercontent.com/assets/4788533/8456013/e89c4e68-2008-11e5-9890-574f1405e023.png)

``` HTML
<ul id="slide-out" class="side-nav fix fixed">
    <li><a class="dropdown-button" href="#!" data-activates="dropdown3">3. semestar<i class="mdi-navigation-arrow-drop-down right"></i></a></li>
    <ul id='dropdown3' class='dropdown-content condensed light'>
        <li><a href="#!">Engineering Math</a></li>
        <li><a href="#!">Algorithms and Data Structures</a></li>
        <li><a href="#!">Computer Architecture</a></li>
        <li><a href="#!">Signals</a></li>
        <li><a href="#!">Introduction to Object Oriented Programming</a></li>
    </ul>
</ul>
```

Thanks for the help and have a nice day!

**Comment by uok** [comment]
I have the same problem!
quick fix (but not solution): add `overflow:hidden` to links inside sidenav, e.g. `#dropdown a`

**Comment by voveson** [comment]
Bump.

I'm seeing the same issue -- it seems that links inside the dropdown cannot be very long at all without causing this overlap.  Any solution yet?

**Comment by fega** [comment]
This issue is not happening anymore, but the nav is having weird behaviors when you use long text, 
a suitable solution:
```
.side-nav li>a {
    ...
    overflow: hidden;
    white-space: nowrap;
    text-overflow: ellipsis;
}
```

**Comment by tomscholz** [comment]
Closed due inactivity. Feel free to reopen it, if it's still necessary.
