### ISSUE TITLE
sideNave('hide'), does not remove the gray fade over the body content

### ISSUE THREAD

**Issue by keyscores** [Dogfalo/materialize#1648]
When I trigger the hide $('.button-collapse').sideNav('hide'); 
The menu does dissapear/hide, however the body html is still darkened by the grey overlay.

FYI I'm using Meteor,

**Comment by carlosperate** [comment]
Can you replicate the issue in the codepen listed in https://github.com/Dogfalo/materialize/blob/master/CONTRIBUTING.md ?

**Comment by janpieterz** [comment]
@keyscores does it dissapear when you click multiple times? I've had to work out some stuff because my React app was initializing the menu too often. Please check if your menu code only runs once (for example by commenting it and running it from your dev console), to see if it persists.

**Comment by keyscores** [comment]
I can make the grey go away if I click/tap the html body.

**Comment by janpieterz** [comment]
Yeah, then you probably have the problem I described. You can fix this by just calling the sidenav function once, and not more than once. Not sure how to do this in Meteor.

Another solution would be to track the state of it so the nav doesn't overlay more than once. In case you go down this road please use a pull-request so all of us can enjoy the improved version ;)

**Comment by Dogfalo** [comment]
This has been tested and I could not recreate your issue, please check your own code as @janpieterz has suggested might be the problem

**Comment by janpieterz** [comment]
@Dogfalo it's quite easy to replicate, just run $(".button-collapse").sideNav(); again on the materializecss website. 

As soon as you initiate the plugin twice, the event handler gets attached twice and therefore creates two overlays.
