### ISSUE TITLE
Calendar widget

### ISSUE THREAD

**Issue by vsodre** [Dogfalo/materialize#1652]
is it possible to use datepicker's calendar as a standalone widget?

**Comment by Dogfalo** [comment]
you can grab the code from the js files if you want to use it alone.

**Comment by vsodre** [comment]
I didn't found the files whose create the standalone calendar, so then I wrote one only for this. It's an angular directive, but I can translate for a jquery module. Will that be useful for you guys?

**Comment by Dogfalo** [comment]
Glad you found a work around for your problem, thanks for the offer, but we're fine with our current datepicker.
