### ISSUE TITLE
Don't change native elements

### ISSUE THREAD

**Issue by ghost** [Dogfalo/materialize#1659]
Don't change native elements. How does it bootstraps.. It really bad... If i want add something custom new, then me need write css rules for clearing? Good example:

```
 <footer class="footer">
```

**Comment by siriniok** [comment]
Materialize styles the "naked" HTML tags

Maybe, it don't looks like issue, but styling HTML tags by selectors like input[type="checkbox"] and select results in a lot of conflicts with other stylesheets. For example, when I use materialize with ember cli, it conflicts with stylesheets of QUnit (snapshot attached). As you can see, tests page is absolutely unusable.

![32f18ea6-4d36-11e5-9ac2-43ec4d6b846d](https://cloud.githubusercontent.com/assets/6921765/9591619/4b4ab6be-5045-11e5-9675-9a5f716db435.png)

Original issue: https://github.com/mike-north/ember-cli-materialize/issues/227

**Comment by acburst** [comment]
Fixed in e575765

**Comment by bargar** [comment]
@acburst thanks for the attention to this issue!

It seems that you have addressed the specific example of the `footer` tag but I was subscribed to this issue especially for the checkbox and select case as described by @siriniok. Would you recommend that a new issue be opened for that case?
