### ISSUE TITLE
Right-align

### ISSUE THREAD

**Issue by ttv20** [Dogfalo/materialize#1660]
[Sorry for my bad english]
in right-align a lot of thing Berserk
the span-badge stay in the left
the responsive-table header stay left
the form label stay in the worng side ( [ checkbok label  V ] need to be reverse for example)
If I would remember more problem - I write

**Comment by ttv20** [comment]
and the new icon method work but add tab space before the icon (right-align)

**Comment by acburst** [comment]
Can you post code examples? That would be helpful for us to pinpoint the problem

**Comment by ttv20** [comment]
http://ttv20.tk/materialize.html

**Comment by Dogfalo** [comment]
Right align just applies the text-align right property, youll still have to know when to apply it

**Comment by ttv20** [comment]
i try to apply it every tag - its not help...

**Comment by Dogfalo** [comment]
See here for more information https://css-tricks.com/almanac/properties/t/text-align/

**Comment by ttv20** [comment]
its not help for in form label

**Comment by ttv20** [comment]
I took the css file and I replaced all the "left" with "right" and all the "right" with "left"
now, all working great! - http://ttv20.tk/materialize.html
maybe you can publish RTL version?
