### ISSUE TITLE
Date picker format not working

### ISSUE THREAD

**Issue by steventen** [Dogfalo/materialize#1661]
Hi,

I'm trying to change the format for datepicker, like below:

```javascript
  $(document).ready(function() {
    $('.datepicker').pickadate({
       format: 'mm/dd/yyyy',
       selectMonths: true, // Creates a dropdown to control month
      });
  });
```

However, it's still display this format on the input: `1 July, 2015`

Can you tell me how can I modify the format? Thanks

**Comment by carlosperate** [comment]
Seems to be working to me: http://codepen.io/anon/pen/oXEypq

**Comment by oofurkan** [comment]
try this code. have a fun
$(document).ready()
    {
        $('select').material_select();
        $('.datepicker').pickadate({
            selectMonths: true,
            selectYears: 200, 
            format: 'dd/mm/yyyy'
        });
    }
