### ISSUE TITLE
Adjustments to the navbar height breaks the grid layout

### ISSUE THREAD

**Issue by meichenblatt** [Dogfalo/materialize#1663]
I adjusted the height of the navbar to 120px. Now if I switch to a mobile the grid layout doesn't flow downward rather it squishes together. As soon as I take out that piece of css the grid flows nicely on the mobile.

**Comment by carlosperate** [comment]
Could you provide an example in http://codepen.io/Dogfalo/pen/xbzPQV ?

**Comment by meichenblatt** [comment]
Thanks for the response.

Here you go:
http://codepen.io/anon/pen/KpQeaw

**Comment by meichenblatt** [comment]
When in mobile view the green box should go under the blue one.

**Comment by carlosperate** [comment]
If I remove the nav CSS from the codepen the boxes react the same way, are you sure the issue is with the nav height?

**Comment by meichenblatt** [comment]
On codepen with or without an adjustment to the nav the blocks don't float down.  Also on codepen the height isn't adjusting to the set amount in the css. On my site it is.

Maybe my expectations of the grid system are off. They are suppose to float down correct?

**Comment by carlosperate** [comment]
You need to add the different grid sizes per screen size, there is more info here: http://materializecss.com/grid.html#grid-responsive

**Comment by meichenblatt** [comment]
Ok thank you
