### ISSUE TITLE
IMPORTANT - New Icons Problems

### ISSUE THREAD

**Issue by ConsoleTVs** [Dogfalo/materialize#1665]
Hello!, that's quite remarcable, try both of this things:

1st problem:
The icons navbar is not working, AT ALL!
http://materializecss.com/navbar.html#icons

2nd The submit button's icon makes it look all ugly!

**Comment by carlosperate** [comment]
Could you be more specific? It works fine for me, make sure you do a hard refresh on your browser.

**Comment by ConsoleTVs** [comment]
http://puu.sh/iLOuV/93f7e3e149.jpg

web: http://erik.cat

**Comment by jhuenges** [comment]
Have you added this ```<link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">``` to import the icon font?

**Comment by ConsoleTVs** [comment]
I thought it was imported as it used, i'll try it out now!

Edit: Working
