### ISSUE TITLE
Dropdown hover doesn't work in JS version 0.97

### ISSUE THREAD

**Issue by nosajnosliw** [Dogfalo/materialize#1667]
Dropdown appears on hover but when yuou move the cursor to select an item it disappears. disabling hover in the code also disables constrain width and below origin too.

try it at www.nosajnosliw.com

Thanks,

**Comment by nosajnosliw** [comment]
I've changed my javascript version back to the old one as I"d rather haev prospective employer have access to my content than have the parallax function. 

Thanks,

JW

**Comment by Dogfalo** [comment]
Hover is working, please make a codepen that shows otherwise and I will reopen this issue.

**Comment by nosajnosliw** [comment]
The issue was live on my website but I found a workaround for it myself.
Thanks.
