### ISSUE TITLE
[BUG] Collection secondary content icon alignment issues

### ISSUE THREAD

**Issue by truenorth** [Dogfalo/materialize#1668]
Instructions to reproduce

1. Go to [the secondary content example on the materializecss.com collections page](http://materializecss.com/collections.html)
2. Open your dev tools and change one of the icons from `send` to `remove circle outline`
![screen shot 2015-07-03 at 12 33 15 pm](https://cloud.githubusercontent.com/assets/558005/8504104/b85563d4-217f-11e5-8d92-0518019949d8.png)

![screen shot 2015-07-03 at 12 31 20 pm](https://cloud.githubusercontent.com/assets/558005/8504089/7989c53c-217f-11e5-8348-ae1d9f9ccecb.png)

You will see that the icon is no longer right-aligned.

**Comment by acburst** [comment]
http://www.google.com/design/icons/#ic_remove_circle_outline

The correct ligature is remove_circle_outline, It should work with valid ligatures
