### ISSUE TITLE
search bar broken - close button

### ISSUE THREAD

**Issue by TobyEalden** [Dogfalo/materialize#1669]
See the search bar at http://materializecss.com/navbar.html

The close button appears on the line below, obscuring the first word on next line of text.

Reproduced on Chrome 43.0.2357.130 and Firefox 33.0

**Comment by TobyEalden** [comment]
Appears to be the material-icons causing the problem. If you replace:

```
<i class="material-icons">close</i>
```

with

```
<i class="mdi-navigation-close close"></i>
```

it works as expected.

**Comment by acburst** [comment]
It is working on master, We haven't updated the docs yet
