### ISSUE TITLE
Dropdown breaks when user clicks navbar button rather than dropdown item

### ISSUE THREAD

**Issue by sophocles7** [Dogfalo/materialize#1670]
With the constrain_width: false & belowOrigin: true, the dropdown menu breaks when the user clicks the navbar button rather than the dropdown.

When the user click there, the dropdown is suddenly shifted up (in the belowOrigin: false position), and the constrain_width kicks in, creating scrollbars in the dropdown if the items are long.

Before clicking, the menu will look like this:
![hover dropdown](https://cloud.githubusercontent.com/assets/11181071/8504975/adff682a-21a8-11e5-9fc9-9babf631124d.JPG)

After a user clicks the navbar item, this occurs:
![hover dropdown broken](https://cloud.githubusercontent.com/assets/11181071/8504984/d7d3ea7c-21a8-11e5-8653-7bac1c4a71eb.JPG)

(The Something item is active so it's white, the About Item is hovered in the first pic, and clicked in the second.)

Happens in all browsers I've tested.

**Comment by Dogfalo** [comment]
Check your HTML structure, you likely have duplicate id or data-activates. We have a test page which tests this exact scenario and all is working.

**Comment by sophocles7** [comment]
No duplicate ids or data-activates.

Here's a codpen:
http://codepen.io/sophocles7/pen/oXQQqb

Hover over the About, it appears as it should. Click the About, and constrain_width:false and belowOrigin:true are ignored.

**Comment by sophocles7** [comment]
After playing with this a bit more, I see that the problem is only in the jQuery initialization. If using inline data attributes, it works as expected. But it is broken for jQuery.
