### ISSUE TITLE
Collapsibles not working correctly

### ISSUE THREAD

**Issue by nesbtesh** [Dogfalo/materialize#1672]
Collapsibles open and close right away on the new update.

**Comment by carlosperate** [comment]
I haven't experienced this issue, could you provide an example in a codepen? http://codepen.io/Dogfalo/pen/xbzPQV

Also, make sure you are not accidentally initialising the collapsible more than once, as you'd get that open and close effect if you do.

**Comment by Dogfalo** [comment]
Please make a codepen

**Comment by nesbtesh** [comment]
I found the mistake, I am having an error declaring materialize.js in wordpress. So I have to double paste the script, for testing purposes and the collapsible where initializing twice.
