### ISSUE TITLE
Card size classes don't work correctly on cards without images

### ISSUE THREAD

**Issue by rosemariesadler** [Dogfalo/materialize#1673]
This is the code taken directly from the docs for a card with the simple addition of the small class:

```
      <div class="card blue darken-1 small">
        <div class="card-content white-text">
          <span class="card-title">Card Title</span>
          <p>I am a very simple card. I am good at containing small bits of information.
          I am convenient because I require little markup to use effectively.</p>
        </div>
        <div class="card-action">
          <a href="resume/projects">Projects</a>
        </div>
      </div>
```

If the width of the card is narrow, you can see that the text at the bottom gets cut off, as well as adding a block of white space that is the size of what the image would be if there was one. 

![image](https://cloud.githubusercontent.com/assets/11645238/8509882/5aaa3390-227e-11e5-8a72-9055fa50905e.png)

Additionally, with image cards that have text that overflows into the space that the card-action div occupies, it is not cut off. This is because the height of the card-action div isn't taken into account when giving the card-content and card-image heights.

![image](https://cloud.githubusercontent.com/assets/11645238/8509885/dfb40f2a-227e-11e5-9b0c-6defe4098a94.png)

**Comment by PCMRStudio** [comment]
Yeah, really annoying

**Comment by andhofmt** [comment]
I can confirm this issue.

Additionally, the card-content class is having issues wrapping text for non-image cards. Some of the letters may get truncated on various screen sizes.

Message me if any of you can close in on what's causing it and lets try to get this fixed.

**Comment by rosemariesadler** [comment]
I've been really busy with other projects lately, so I haven't had time to work on this, but I'll bet that using flexbox would solve the problems.

**Comment by rikato** [comment]
This happens because the heights of card-content and are static
fix:.
```
==SASS==
.card.small
    height: auto
    .card-content 
        height: auto
    .card-action
        position: relative
==CSS==
.card.small {
  height: auto;
}
.card.small .card-content {
  height: auto;
}
.card.small .card-action {
  position: relative;
}

```

**Comment by jartaud** [comment]
@rikato Thanks!

**Comment by fega** [comment]
solved.
