### ISSUE TITLE
Can't load Material Icons font

### ISSUE THREAD

**Issue by ericwangqing** [Dogfalo/materialize#1674]
When using with Meteor, I have to load the .material-icons rule with additional css link, otherwise these material-icons classes weren't recognized and none icons shown.  

The icon <i class="material-icons">search</i> will not be rendered as icon 
without adding <link href='http://fonts.googleapis.com/icon?family=Material+Icons' rel='stylesheet' type='text/css'/> in the head.

**Comment by Dogfalo** [comment]
We do not currently bundle it together as it gives the developer more choice on whether  or not to include it

**Comment by jonwhittlestone** [comment]
How about the icons without .material-icons rule? The icons from the font `font/material-design-icons/Material-Design-Icons.woff2`

These aren't being pulled in to my page (not showing in Network tab of Chrome Dev Tools) yet Roboto is. Both fonts are being referenced from my compiled sass

**Comment by raibutera** [comment]
+1 @jonwhittlestone
