### ISSUE TITLE
Icons not loading on windows phone

### ISSUE THREAD

**Issue by dhwanilvyas** [Dogfalo/materialize#1675]
On any windows phone icons don't load.

**Comment by AsafShochet** [comment]
maybe connected to #1679

**Comment by kmmbvnr** [comment]
Probably this was inspired by switching to external google font. See https://github.com/Dogfalo/materialize/issues/1665#issuecomment-118338549

Checked on Nokia Lumia 8.1

![dashboard](https://cloud.githubusercontent.com/assets/282529/20586692/a4dd4248-b230-11e6-8906-f0e3fdab64b8.png)

**Comment by tomscholz** [comment]
If you're still facing this issue have a look [here](https://github.com/google/material-design-icons/issues/179).
