### ISSUE TITLE
nav .brand-logo (Line 5268)

### ISSUE THREAD

**Issue by derekclair** [Dogfalo/materialize#1677]
nav .brand-logo {
    position: absolute;
    color: #fff;
    display: inline-block;
    font-size: 2.1rem;
    padding: 0;
    white-space: nowrap; }

conflicts on smaller viewports with Line 5282, which I think is missing the center, should be nav .brand-logo.center 

    @media only screen and (max-width : 992px) {
      nav .brand-logo {
        left: 50%;
        -webkit-transform: translateX(-50%);
        -moz-transform: translateX(-50%);
        -ms-transform: translateX(-50%);
        -o-transform: translateX(-50%);
        transform: translateX(-50%); } }

**Comment by jagregory** [comment]
+1 seeing the same thing. `.brand-logo.right` only works when width > 992px.

**Comment by acburst** [comment]
Fixed in fe0909f
