### ISSUE TITLE
[enhancement] Add public method to control collapsible 

### ISSUE THREAD

**Issue by carlosperate** [Dogfalo/materialize#1678]
It has been briefly discussed in a closed issue (https://github.com/Dogfalo/materialize/issues/486), so I'm opening a new one for visibility.
It'd be great to have a public method to set a collapsible open or close (not just to toggle it).

**Comment by kmmbvnr** [comment]
Duplicate #545

**Comment by acburst** [comment]
Added open and close methods to collapsible in b6d3188
