### ISSUE TITLE
Checkbox disappears on pinch to zoom.

### ISSUE THREAD

**Issue by orrgottl** [Dogfalo/materialize#1679]
It appears that on retina display (iPad Air) the checkbox check mark disappears on pinch to zoom.
this behavior reproduces on the materialize website (http://materializecss.com/forms.html)

Thank you

**Comment by AsafShochet** [comment]
happens to us also on high retina tablets, when do you plan fixing this?

**Comment by thaliemuk** [comment]
+1

**Comment by eladpf** [comment]
+1

**Comment by tomeraz** [comment]
+1

**Comment by kmmbvnr** [comment]
Reproduced on browserstack (just double click to zoom)

No issue with filled-in checkboxes. 

![dashboard](https://cloud.githubusercontent.com/assets/282529/20586792/be20b086-b231-11e6-8ab9-a89e76c8c768.png)
