### ISSUE TITLE
Dropdown - click stopPropagation

### ISSUE THREAD

**Issue by otroboe** [Dogfalo/materialize#1683]
Hey !

Do you think it would be useful to add an option to stop event click propagation when opening the dropdown ?

``` javascript
$('.dropdown-button').dropdown({
    stopPropagation: true // default: false
});
```

In my case, I use the collection component and a dropdown menu in each row. But I want a custom behavior when click on a collection-item. But this custom bind is triggered when click on the dropdown-button :)

For now I check the clicked target DOM element, but it's not very clean !

Thanks :)

**Comment by rotoxl** [comment]
+1

**Comment by vinikento** [comment]
+1

**Comment by fega** [comment]
implemented

**Comment by BrendanBehr** [comment]
It looks like this was undone with 3c76a65589ef536c0068c20e7644056b57de9a4f.  Before submitting a pull request, I just want to check to see if this was intended or an accidental removal.  I currently have a workaround implemented but I would like this feature and I have a potential fix for this.
