### ISSUE TITLE
Icon alignment changes on small screens

### ISSUE THREAD

**Issue by cchandurkar** [Dogfalo/materialize#1684]
I'm working on Emberjs App and installed `ember-cli-materialize`. It was working all fine until you pushed Google API fonts for icons. They works fine on screens above small but on small they gets stick to the top of the container.  I'm not using any explicit margin or padding. I'm importing `http://fonts.googleapis.com/icon?family=Material+Icons` in app.scss and using icons the usual way `<i class="material-icons">search</i>`

Check it out on this [CodePen](http://codepen.io/cchandurkar/pen/rVdGvM)

Preview:
![screenshot from 2015-07-06 20 47 40](https://cloud.githubusercontent.com/assets/2879791/8536590/7c1f81ac-2421-11e5-976e-9b6ec3674e72.png)

**Comment by cchandurkar** [comment]
I went to inspect element and found out that there is one css property getting generated
```css
nav ul{
  margin: 0;
}
```
If I remove this margin property icon comes back to center.

**Comment by jlsalvador** [comment]
@cchandurkar If you do that you broke the icons outside the navbar.

The problem it's about the navbar:

```
nav i.material-icons {
  line-height: 56px;
}
```
