### ISSUE TITLE
Materialize Select Just Will Not Work

### ISSUE THREAD

**Issue by spencerthayer** [Dogfalo/materialize#1689]
http://codepen.io/spencerthayer/pen/domezG

As you can see I'm linking to the Materialize CSS and JS CDN and using the default code for a `<select>` but nothing is showing up.

It would seem `<select>`'s are broken.

**Comment by Johann-S** [comment]
Yes because ``<select>``s are hidden by materialize you have to enable it with : 
``$('select').materialize_select();``

**Comment by spencerthayer** [comment]
doh!
