### ISSUE TITLE
A few bugs with version v0.97.0

### ISSUE THREAD

**Issue by gempain** [Dogfalo/materialize#1690]
Hi, 

Probably the most amazing css/js framework I have seen so far, so I thought you would appreciate some feedback about several issues I have found.
## Setup

Materialize v0.97.0
Safari 8.0.6
## Issues
1. When a date picker is applied to an input field inside a `<div class="input-field"></div>`, the placeholder should move up (respectively down) when the picker opens (respectively closes).
   ![placeholder_overlapping](http://s28.postimg.org/6ypgj8x9l/Capture_d_cran_2015_07_07_15_06_35.png)
2. IMHO, even though it is not part of the [range slider components](http://www.google.com/design/spec/components/sliders.html#sliders-discrete-slider) of Google Material Design, Materialize should  provide a double range slider.
   
   ![double_range_slider_component](http://s24.postimg.org/yknhrv03l/Capture_d_cran_2015_07_07_15_15_33.png)
3. Input error is misplaced when input has no value, most likely because of the placeholder . It only displays correctly when the placeholder slides up.
   #### Default
   
   ![wrong](http://s1.postimg.org/5njjsjg9r/Capture_d_cran_2015_07_07_15_30_33.png)
   #### Workaround
   
   ```
   placeholder=""
   ```
   #### Result
   
   ![right](http://s13.postimg.org/bxlag2bjr/Capture_d_cran_2015_07_07_15_25_19.png)
4. Long error messages will span over several lines and break the design.
   #### Default
   
   ![wrong](http://s1.postimg.org/4mnwh5onz/Capture_d_cran_2015_07_07_15_58_36.png)
   #### Workaround
   
   provided by @marci2020
   
   ```
   label[data-error]:after {
     white-space: nowrap;
   }
   ```
   #### Result
   
   ![right](http://s30.postimg.org/69cqns1z5/Capture_d_cran_2015_07_07_15_59_49.png)
5. IMHO, when several inputs are stacked, inputs below are too close to the error message.
   #### Default:
   
   ![wrong](http://s23.postimg.org/ma6iunlzf/Capture_d_cran_2015_07_07_16_16_38.png)
   #### Workaround
   
   provided by @marci2020
   
   Adding "col" class to every element with "input-field" class and putting it into an element with class "row" (like done on [Materialize form examples](http://materializecss.com/forms.html)).
   
   ```
   <div class="row">
   <div class="input-field col s12">
       <input disabled value="I am not editable" id="disabled" type="text" class="validate">
       <label for="disabled">Disabled</label>
   </div>
   </div>
   ```
   #### Result
   
   ![right](http://s14.postimg.org/q41q441gx/Capture_d_cran_2015_07_07_16_17_14.png)`
6. Error messages (from `data-error`) are not displayed on inputs with the `datepicker` class.
   
   ![datepicker_error](http://s16.postimg.org/lcuogl9n9/Capture_d_cran_2015_07_07_16_24_12.png)
7. Close a date picker, switch browser tab, come back to the previous tab and the picker reopens. Bug has been reported on Safari (8.0.6) and Chrome (43.0.2357.134).

Looking forward to reading you.

Cheers, and keep the amazing work !

**Comment by najubhai** [comment]
Oh my God I thought I was doing something wrong with the error label spanning over multiple lines. Thanks for not just reporting the bugs but also providing solutions to them!

**Comment by Clemzd** [comment]
Here is a hack to fix the third issue.
`$('input:not([placeholder])').attr('placeholder','');`

**Comment by gempain** [comment]
That will work nicely and it is probably a cleaner way to do it ! However, I try not to use JS when an HTML solution exists :)

Yep, can't wait for those issues to be fixed, especially that of the errors not displayed on date picker input fields.

**Comment by Clemzd** [comment]
@gempain Native HTML solution is always the best! Except when the HTML code is already written =)

**Comment by gempain** [comment]
@Clemzd what do you mean :) ?
> Except when the HTML code is already written =)

**Comment by Clemzd** [comment]
@gempain  I was saying that instead of this hack is better than alternate the HTML code. I think that placeholder="" is not a good practise.

And oh my bad, this solution does not work anyway
This one works instead.
`.input-field label {
	font-size: 0.8rem;
	-webkit-transform: translateY(-140%);
	-moz-transform: translateY(-140%);
	-ms-transform: translateY(-140%);
	-o-transform: translateY(-140%);
	transform: translateY(-140%);
}`

**Comment by gempain** [comment]
@Clemzd I agree with you, using `placeholder=""` is not the cleanest solution, but memory wise more efficient than using JS :) But anyways, the last solution you provided is better, as it is the exact fix that they should use ! Thanks for providing it ! I'll edit my original post to include it.

**Comment by Clemzd** [comment]
Yes, you're 100% correct. I don't really need this effect that's why the fix is enough for me for now. I am using this framework at work for a project so I don't have lot of time to spend on fixing bugs.
I am waiting for better solutions to come! =)

**Comment by gempain** [comment]
Same thing here :) I don't have much time to work on fixing these bugs ^^ I hope they'll find a solution soon :)

**Comment by marci2020** [comment]
For me width 100% does not fix the issue with the error messages mentioned in point 4.
What worked for me is white-space: nowrap.

**Comment by derixithy** [comment]
This fixes the input error for somewhat, the only problem is it still displays an effect when giving the input focus.

```
.input-field input.invalid + label {
  width:100%
}
.input-field input.invalid:not(:focus) + label:after {
  font-size: 0.8rem;
  position: absolute;
  top: 40px;
}
```

**Comment by gempain** [comment]
@marcl2020 have you tried adding `!important` to the fix ? Not sure why it isn't working for you :/ Thanks for providing a fix :) I will try it at work today and update my initial post in case it works for me as well :)

@derixithy I'll git it a try if I get some time at work today :) I might just try to find the right fix :)

Anyone has an idea on the date picker errors not showing ? That's the strangest one to me :/

**Comment by marci2020** [comment]
@gempain no haven't tried adding it, going to check later if it works.

**Comment by gempain** [comment]
@marci2020 Your solution works for me ! I also noticed a bug cause by my solution: it breaks the width of input[type=search]. The corresponding label has a padding, therefore its outer width is 100% + padding, which exceeds the width of the div, creating an x scroll... So I'll change my solution to yours in my original post. Thanks for providing it !

**Comment by marci2020** [comment]
@gempain point 5 can be solved like this:

<div class="row">
    <div class="input-field col s12">
                <input placeholder="Placeholder" id="first_name" type="text" class="validate">
                <label for="first_name" class="active">First Name</label>
    </div>
</div>

**Comment by gempain** [comment]
@marci2020 That works gracefully ! I'll update the list. However, I am not a fan of such solutions as I believe that it adds unnecessary tags to the page, that becomes unreadable, although I agree that your solution follows the philosophy of the Materialize framework :)

**Comment by marci2020** [comment]
Error mentioned in point 7 also happens with Chrome

**Comment by gempain** [comment]
@marci2020 what is your Chrome version ? (so I can update correctly).

**Comment by marci2020** [comment]
@gempain it's 43.0.2357.134

**Comment by gempain** [comment]
@marci2020 Thanks, updated :)

**Comment by marci2020** [comment]
For point 6 check:
https://jsfiddle.net/1eek79qz/4/

The error message will get into place once a value is selected.

**Comment by gempain** [comment]
Not on Safari apparently :/

![screeshot](http://s30.postimg.org/vyql3hdhd/Capture_d_cran_2015_07_21_11_05_02.png)

**Comment by iktakahiro** [comment]
My-Workaround:

```sass
.input-field label[data-error].active:after
  font-size: 0.8rem
  -webkit-transform: none
  -moz-transform: none
  -ms-transform: none
  -o-transform: none
  transform: none

.input-field label[data-error]:after
  font-size: 0.8rem
  white-space: nowrap
  -webkit-transform: translateY(-120%)
  -moz-transform: translateY(-120%)
  -ms-transform: translateY(-120%)
  -o-transform: translateY(-120%)
  transform: translateY(-120%)

form
  .row
    .col.s12
      margin-bottom: 15px
```

It seems that this issue is difficult.

**Comment by MaxVerro** [comment]
IMO, all these work around solutions are fine and do actually work. Although I would suggest a different approach. I use this framework within different .NET MVC application. Having a required Attribute is a common thing. Therefore, when returning a view, as mentioned before, if the input has no focus the data-error is misplaced. So here is what I suggest, we could use an extra markup to serve as the container for the validation error message. Basically, adding a span below the input to serve has a container for the message and will most likely be more compatible with other web framework (ie MVC uses unobstructive JavaScript which normally display the error in a span below the field. The span will automatically fill 100% of the width and should use display:block.

People who download the source could easily modify the class name applied to the span to match their need (ie: Again, for a MVC user, the class name could the changed for the one used with unobstuctive JavaScript there matching maybe custom selectors of stuff like that.

Pseudo element are great in general. Although, I am not a great fan of the approach used to display validation errors.

**Comment by enmanuelr** [comment]
Some of these CSS workarounds work great, but generally apply to inputs. When using textareas, because they dynamically grow, I'm still getting an overall between the error message and the text area content.

**Comment by vlado** [comment]
For #3 you can use `$('input.invalid:not([placeholder])').attr('placeholder', '');`. It will probably require `Materialise.updateTextFields();` also.

**Comment by ben-sykes** [comment]
6 and 7 are still issues. Has there been any response from the creators?

**Comment by ctytgat** [comment]
Is there any workaround/fix for issue6? (data-error with datepicker).
Still an issue with version 0.98.0 ...

**Comment by reynaldi2802** [comment]
issu number 6 just been fix recently by @Dogfalo

**Comment by wittsparks** [comment]
I'm still seeing issue #3 - I'm using 0.99.0 from CDN:
 https://cdnjs.cloudflare.com/ajax/libs/materialize/0.99.0/css/materialize.min.css

I take it not all of these issues have been corrected?

**Comment by Dogfalo** [comment]
In v1-dev, we've overhauled the label system so that is the error messages do no move inadvertently with the primary label.

**Comment by ctytgat** [comment]
@Dogfalo Do you know in which release this overhaul will be included?

**Comment by tomscholz** [comment]
1.0.0

**Comment by jtlthe2** [comment]
I put the following workaround in my CSS to wrap the text when I specified and when it needed to in my Angular 2 app.

```
label[data-error], label[data-success] {
    width: 100%;
    white-space: pre-wrap;
}

```
It allowed me to fill my data-error property with the following

```
[attr.data-error]="'Line 1 of the message.\nLine 2 of the message. I am going to make this really really really really really really really really really really really really really really really really really really really really really really really long, so it wraps.\nLine 3 of the message.\n'"

```

which then displayed the error how I wanted (image attached).

![screen shot 2018-01-22 at 5 57 22 pm](https://user-images.githubusercontent.com/11728238/35249121-d2d2f0fa-ff9e-11e7-923f-4a89c5566c72.png)
