### ISSUE TITLE
Fixed Action Button

### ISSUE THREAD

**Issue by csabagb** [Dogfalo/materialize#1692]
Hello,

I have a question about your Fixed Action Button. I wanted to see if I can have submenu or sub < ul > list within the main < ul > resulting something like on the linked picture. 

http://postimg.org/image/61d44d0vj/

I tried to implement submenus within the FAB but it did not work out. I used another js to get the results, but I wanted to see if there is a built-in function. See pictures for clarification. Also, is there any way we can eliminate in CSS all the non FAB related tags?

**Comment by Dogfalo** [comment]
There isn't any supported way to nest FAB's like this. This kind of behavior deviates quite a bit from the FAB in Google Material Design so we've chosen to keep it simple.
