### ISSUE TITLE
Materialize is randomly adding caret icons on top of my drop downs 

### ISSUE THREAD

**Issue by meichenblatt** [Dogfalo/materialize#1697]
This is extremely odd for some reason materialize is adding a bunch of caret icon on top of all my drop downs. It was not there before and there is nothing in my code that adds it. 

![capture](https://cloud.githubusercontent.com/assets/12259246/8577629/ce98d576-255e-11e5-8819-0e02fbd1db5e.PNG)

 Here is my code:

# <div class="row">
              <div class="row">
                    <div class="col s12 m6">
                        <select id="location">
                            <option value="" selected>Select Location</option>
                            {{#each regions}}
                                <option value="{{Name}}">{{Name}}</option>
                            {{/each}}
                        </select>
                    </div>
                </div>

**Comment by carlosperate** [comment]
Already fixed: https://github.com/Dogfalo/materialize/issues/1570
