### ISSUE TITLE
Changing Shadow Color

### ISSUE THREAD

**Issue by andhofmt** [Dogfalo/materialize#1698]
Materialize team, 

Could you point me in the right direction of changing the default shadow color if possible?
It seems as if it should be in the variables under SASS, but is not. 

Many websites with non traditional color schemes could benefit from changing shadow color / opacity.

Thanks a ton,

Andrew

**Comment by tomscholz** [comment]
https://github.com/Dogfalo/materialize/blob/e5757653366f75ee18881f0bf240d4f97e626eab/sass/components/_global.scss#L57 and please close

**Comment by tomscholz** [comment]
You can edit the properties of shadows [here](https://github.com/Dogfalo/materialize/blob/e5757653366f75ee18881f0bf240d4f97e626eab/sass/components/_global.scss#L57)
