### ISSUE TITLE
select not working in popup dialog

### ISSUE THREAD

**Issue by jmls** [Dogfalo/materialize#1701]
I have this following html

```html
 <div class="row">
              <div class="input-field col s12">
                <select>
                  <option value="" disabled selected>Choose your option</option>
                  <option value="1">Option 1</option>
                  <option value="2">Option 2</option>
                  <option value="3">Option 3</option>
                </select>
                <label>Materialize Select</label>
</div>
```
however, when I view a dialog containing this code, the select does not show or work

![screenshot from 2015-07-09 12 21 02](https://cloud.githubusercontent.com/assets/929523/8594028/1eff83a8-2635-11e5-9202-8bbfed4d673c.png)

**Comment by carlosperate** [comment]
Could you create a full example (with the modal) in a codepen? http://codepen.io/Dogfalo/pen/xbzPQV
Make sure you are initialising the javascript for the select as indicated in the documentation.

**Comment by jmls** [comment]
thanks - it was the initialising that I was missing

on another note - is it possible to call a function when the value changes - I need to be able to hide / show some values on a form depending on the value of the selected item

**Comment by carlosperate** [comment]
If you are dynamically changing the select element you will need to destroy the materialize select first and then reinitialise it.

**Comment by jmls** [comment]
no, i'm not changing the contents of the select, I want to hide some other form elements if the value changes. For example, select "car" and I want to show the excise duty, select "bus" and I want to show "number of seats"

**Comment by carlosperate** [comment]
Have you tried to add a listener to onchange? it should work as usual.

**Comment by jmls** [comment]
ah - the problem was that I am using angular and needed ng-change, not onchange. 

thanks
