### ISSUE TITLE
Tooltip close delay option

### ISSUE THREAD

**Issue by rvanlaak** [Dogfalo/materialize#1702]
We would like to use the tooltips for interaction, because a dialog is too much for the interactions we have.

Unfortunately the tooltip does not stay open on `mouseleave`. We currently use the following jQuery plugin to archieve that: https://github.com/do-m-en/jquery-ui-mouse-over-tooltip

The following improvements would be nice:
- [x] allow html
- [ ] option to set the close delay
- [ ] do not hide the tooltip on hover

**Comment by toandocoffee** [comment]
Hi,

How about this function?

Thank you

**Comment by tomscholz** [comment]
Related #2864

**Comment by Dogfalo** [comment]
in v1-dev tooltips can be opened and closed programmatically
