### ISSUE TITLE
Textarea valid color not working!

### ISSUE THREAD

**Issue by SandeepVattapparambil** [Dogfalo/materialize#1703]
color on hover and active are fine but when valid and moved away, it turns black (normal)
:focus.valid is not working, instead .valid is enough in most cases

**Comment by acburst** [comment]
are you adding the ```validate``` class on the textarea?

**Comment by carlosperate** [comment]
As it has been three weeks without a response I am closing this issue.
@SandeepVattapparambil if you are still experiencing this problem, please reply again with a codepen as indicated in the [contributing](https://github.com/Dogfalo/materialize/blob/master/CONTRIBUTING.md) file, and it'll be reopened.

**Comment by vincentcox** [comment]
still having this issue
