### ISSUE TITLE
arrow_drop_down icon not showing up

### ISSUE THREAD

**Issue by vincentcox** [Dogfalo/materialize#1705]
Problem:
<img width="1440" alt="2015-07-09_21-33-05" src="https://cloud.githubusercontent.com/assets/9286611/8604986/4fc4c7b2-2682-11e5-8df7-f3071aee21fc.png">

Any idea how to debug this?

**Comment by carlosperate** [comment]
There has been changes to the icons in 0.97.0, check out the documentation for more info.

**Comment by vincentcox** [comment]
Thanks for the fast response. But I find it strange that the default code snippets on the website are not updated.

**Comment by carlosperate** [comment]
If you find any errors in the documentation code snippets I'm sure the Materialize team would appreciate a pull request with a fix, just make sure it has not been done already on this repository master branch.

**Comment by vincentcox** [comment]
Thanks!
It can be fixed with this line of code: 
<link href="http://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">

So in the getting started guide this line of code needs to be here:

<img width="1111" alt="2015-07-09_21-45-17" src="https://cloud.githubusercontent.com/assets/9286611/8605197/da9c6c5e-2683-11e5-80f3-426e533cc76c.png">

I don't know how to properly do a pull request to be honest.

**Comment by Dogfalo** [comment]
Fixed in 925c447

**Comment by cryptoboy** [comment]
I'm getting this error as well.

**Comment by alyzidan** [comment]
i also having this error ! anyone got a solution yet ?

**Comment by Dogfalo** [comment]
Try adding:
`<link href="https://fonts.googleapis.com/icon?family=Material+Icons"
      rel="stylesheet">`
