### ISSUE TITLE
select with angular

### ISSUE THREAD

**Issue by jmls** [Dogfalo/materialize#1706]
trying to create a select with angular and ng-repeat

this is the html

```html
<select activate-select ng-model="controller.item" >
                        <div  ng-repeat="item in controller.items">
                        <option>{{ item.name}}</option>    
                        </div>
</select>
```

and the relevant controller code is
```javascript
controller.items = [{name: "foo", value:"foo"},{name:"foo2", value:"foo2"}]
controller.item = controller.items[0];

.directive('activateSelect', function() {
        return {
            restricname: 'A',
            replace: false,
            link: function(scope, element, attr) {
                element.material_select();
            }
    }});    
```
however, this does not render a select box : all I get is

{{ item.name }} as the default value, and "{{ item.name }}" is also the only item in the select

i've tried with ng-repeat on the <select> as well , same problem (although the layout is different)

is there anything I'm doing wrong here ?

**Comment by Dogfalo** [comment]
Please search closed issues as this is a common issue people have run into

**Comment by jmls** [comment]
sorry, that really didn't help. I have already searched through (especially #706) and whilst I see people having problems, I couldn't find a solution. My controller already has the data (so there's no delay, the data is present).

If I use ng-repeat, I have the problems outlined above.

If I use ng-options, then the select *does* populate, but the controller item is set to the array index + 1 (so if the list is a,b,c and I choose a, I get b in the controller item

please could you point me to the actual issue where the solution is . Thanks

**Comment by anorudes** [comment]
+1. same problem
