### ISSUE TITLE
Set Selected from Jquery to <select> 

### ISSUE THREAD

**Issue by sergiomeza** [Dogfalo/materialize#1707]
When i tried to set selected dinamically from jquery an option inside my select, it doesn't work, but when i debug without materialize it work well, do you guys know why?
my code:

<div class="input-field col s6" id="severityUp">
                            <select name="severity">
                                <option value="" disabled selected>Severity</option>
                                <option value="1">1</option>
                                <option value="2">2</option>
                                <option value="3">3</option>
                                <option value="4">4</option>
                            </select>
                        </div>

and the Jquery to set selected
$('div#severityUp select').val(1); or
$('div#severityUp select').val("1");

or changing the id to the select
$('#severityUp').val("1");

Thanks

**Comment by carlosperate** [comment]
If you change the select dynamically you have to destroy it as described in the documentation: http://materializecss.com/forms.html#select

**Comment by navee7** [comment]
Hi,
   Same problem for me. Since I'm new to coding, I don't know how to destroy and create.. Can you show me an example. When I select this dropdown, the value is not changing.
My code :

<select  name="dtime" onchange="javascript:valueselect(this)">
<option value="" disabled selected>Select</option>
<option value="1">1</option>
<option value="2">2</option>
<option value="3">3</option>
</select>

Thanks in advance

**Comment by carlosperate** [comment]
@navee7 The select documentation (http://materializecss.com/forms.html#select) describes how to create and destroy the selects. If you are still having issues it'd be quite helpful if you submitted you code in a codepen as indicated in the [contributing](https://github.com/Dogfalo/materialize/blob/master/CONTRIBUTING.md) file.

**Comment by Sspeed5cm** [comment]
Hi, guys. 
I have this issue too.
I want to use jquery to set the select value. It seems like the materialize select plugin did't provide a method  to set the select value. so, I did it by myself, but it's not convenient. see the `setCityHandler` method, and here is my code:
http://jsfiddle.net/re79x7on/

**Comment by Sspeed5cm** [comment]
@carlosperate Thanks！rerun the initialize method will work. But it seems like just work for single select, and the multiple select is not working.The checkboxs do not checked.

**Comment by rosnaib11** [comment]
This is the best way I used for dynamically set selected.

$('#role_status option[value='+data.select_val+']').attr('selected', true);
