### ISSUE TITLE
Icon Prefix with Placeholders

### ISSUE THREAD

**Issue by shawn-mcginty** [Dogfalo/materialize#1708]
Using placeholder attribute with an icon prefix causes the icon to be stuck in the focused style

![screen shot 2015-07-09 at 4 34 49 pm](https://cloud.githubusercontent.com/assets/11359437/8607446/73ce8190-2658-11e5-89a2-9f563130b7d2.png)

**Comment by acburst** [comment]
Thanks for the fix
