### ISSUE TITLE
Range slider shows old value while moving, only updates when you stop

### ISSUE THREAD

**Issue by logomaster256** [Dogfalo/materialize#1710]
When you hold the slider and move it around, it won't change it's value until you stop.

Simple *partial* fix from #1275: add 
``` thumb.find('.value').html($(this).children('input[type=range]').val()); ```
 to `mousemove touchmove` listener. (only fixes value not updating while moving, does not fix value not updating when you just click and release without moving)

Example from http://materializecss.com/forms.html#range: 
![before](https://cloud.githubusercontent.com/assets/3049847/8608227/219612a8-2699-11e5-8b95-0b550ec421a4.gif)

After the fix: 
![out](https://cloud.githubusercontent.com/assets/3049847/8608294/b792196e-2699-11e5-8c04-c17485a2e799.gif)
(notice how the value still doesn't update when you just click and release without moving it)

**Comment by logomaster256** [comment]
Okay, so the first problem (value not updating while moving) has been fixed in the repo (looks like bower and the site aren't completely up to date). As for the second one (value not updating when you just click somewhere and don't move it), I have found a fix but since it's so small, I hardly think it warrants a PR and I'm not sure what consequences it could have because the event will be called twice. Anyway... you can see the fix at https://github.com/logomaster256/materialize/commit/2913c73726cbfe2f0e3fa96327d7645396b3f28d

Solution from http://stackoverflow.com/questions/18544890/onchange-event-on-input-type-range-is-not-triggering-in-firefox-while-dragging

Gif showing that it's working:
![out](https://cloud.githubusercontent.com/assets/3049847/8638007/b106164a-28ab-11e5-95c6-a1b5fd3f08ee.gif)

Thanks for the lovely framework and have a nice day! :]

**Comment by Dogfalo** [comment]
Thanks for finding the fix, added it in 78a48bb

**Comment by logomaster256** [comment]
Also you might want to close related issues like 
* #801 
* #1498
* and possibly #109, not sure
