### ISSUE TITLE
Icons doesn't work in android 4.2 built-in browser.

### ISSUE THREAD

**Issue by hanfeisun** [Dogfalo/materialize#1711]
I'm using Android 4.2. And I found the icon of materialize  can't display at all in the built-in browser of Android 4.2. It would be great if the compatibility to android browser could be supported..

**Comment by Dogfalo** [comment]
If can confirm it doesn't work, you can open an issue https://github.com/google/material-design-icons

**Comment by hanfeisun** [comment]
@Dogfalo I think It is not the issue of "material-design-icons".

In previous versions, materialize used "CSS classes" to draw icons, font-awesome also uses this way and it works perfect in android browser.

However, materiallize use "icon-font" to replace "CSS font class" later. Maybe it is more convenient, but icon-font is not supported in Android built-in browser. (at least not supported in android 4.2).  

It seems that google doesn't use "icon-font" themselves. They just use "png" for icons. As can be seen in the link below..

https://plus.google.com/+anilsabharwal/stories/e39549b6-120c-3653-b456-2457c19f8e56

**Comment by Dogfalo** [comment]
The icon font is made by google, http://google.github.io/material-design-icons/#icon-font-for-the-web
