### ISSUE TITLE
icon font on BlackBerry 10 browser

### ISSUE THREAD

**Issue by alfredobonino** [Dogfalo/materialize#1712]
On BlackBerry 10 the example layout, don't View icons.
Probably because it not support iconfonts.
The browser of BlackBerry 10 is based on webkit

**Comment by acburst** [comment]
Are you talking about the old icon font or the new ones we just switched over to in 0.97.0?

**Comment by alfredobonino** [comment]
The new icon font, i tried the example and on blackberry 10.

**Comment by carlosperate** [comment]
Could you check if you are able to see the icons shown on http://google.github.io/material-design-icons/#sizing ?
If shows a few examples implementing the google icons at different sizes, and you should see a face icon on the left of each line of code.

**Comment by Dogfalo** [comment]
This should be fixed now in 0b876f8. Let me know if it is not @alfredobonino and I will reopen this.
