### ISSUE TITLE
Slow Scroll with collection inside modal

### ISSUE THREAD

**Issue by mikejones3** [Dogfalo/materialize#1720]
I have a decent sized collection inside a modal pop up and it is very slow scrolling through the collection when it is viewed inside of a modal.

**Comment by acburst** [comment]
Can you post a codepen?

**Comment by mikejones3** [comment]
Can I email you the code privately?

**Comment by acburst** [comment]
yes

**Comment by mikejones3** [comment]
What is your email?

**Comment by cabri89** [comment]
Hello,

I have the same problem but just on Google chrome for mobile phone.

You have a solution ? 

Regards.

**Comment by tomscholz** [comment]
I can't seem to reproduce it. I close this issue for now. If anyone posts a codepen, that is able reproduce the issue, we can reopen it.

**Comment by cabri89** [comment]
The problem is solve ^^ For why, I don't now ^^
