### ISSUE TITLE
Fullscreen SideNav Dropdown HTML Structure work error

### ISSUE THREAD

**Issue by tomsean** [Dogfalo/materialize#1721]

**Comment by Dogfalo** [comment]
please provide more information

**Comment by JimishF** [comment]
Is this same like following issue ? 
There are screen shots that explains the problem.
https://github.com/Dogfalo/materialize/issues/1735

**Comment by tomsean** [comment]
@JimishF @Dogfalo 
Fullscreen SideNav Dropdown HTML Structure work error
![small_screem](https://cloud.githubusercontent.com/assets/5907239/8716683/13733dea-2bc6-11e5-8d20-2b67b6d70cf5.png)
![large_screem](https://cloud.githubusercontent.com/assets/5907239/8716690/21bb928a-2bc6-11e5-8086-261a4f280630.png)


 <nav  role="navigation">
        <div class="nav-wrapper">
            <a href="#" class="brand-logo">test</a>
            <ul id="nav-mobile" class="side-nav">
                <li><a href="#" id="toggle-search"><i class="large mdi-action-search"></i></a></li>
                <li><a href="#">about</a></li>
                <li class="no-padding">
                    <ul class="collapsible collapsible-accordion">
                        <li>
                            <a class="collapsible-header active">test<i class="mdi-navigation-arrow-drop-down"></i></a>
                            <div class="collapsible-body">
                                <ul>
                                    <li><a href="#!">test2</a></li>
                                    <li><a href="#!">test2</a></li>
                                </ul>
                            </div>
                        </li>
                    </ul>
                </li>
            </ul>
            <a href="#" data-activates="nav-mobile" class="button-collapse show-on-large" >
                <i class="mdi-navigation-menu"></i>
            </a>
        </div>
    </nav>
