### ISSUE TITLE
Programmatically open and close Collapsible

### ISSUE THREAD

**Issue by Bluejay47** [Dogfalo/materialize#1724]
I need to be able to programmatically open and close a Collapsible area. Any suggestions? The component doesn't seem to have this ability and I looked at the code in collapsible.js and its not apparent to me how to add this functionality.

Thanks for any suggestions.

**Comment by carlosperate** [comment]
There is already an issue open for this: https://github.com/Dogfalo/materialize/issues/1678

In the meantime you could add an `id` to the header element you can trigger a  `document.getElementById('header_id').click()`

**Comment by carlosperate** [comment]
Closing this as a duplicate of https://github.com/Dogfalo/materialize/issues/1678.

**Comment by drorhilman** [comment]
`document.getElementById('header_id').click()`
 doesn't work for me. - collapsible stays close
