### ISSUE TITLE
How to trigger events (modal or toast) when dismissing collection item?

### ISSUE THREAD

**Issue by jrioromero** [Dogfalo/materialize#1725]
Is there any way to do this currently?

Thanks in advance!

**Comment by csapir** [comment]
When a collection item is dismissed, it's removed from the DOM using jQuery `.remove()`. So you can handle that `remove` event by programmatically triggering a modal/toast. jQuery UI has this built in (a `remove` event is fired when something is removed):

```
$("#myCollectionItem").on("remove", function () {
    $('#myModal').openModal();
});
```

If you don't want to use jQuery UI, you can just wrap jQuery's `remove()` function, apply a `remove` trigger and handle it as I did above.

**Comment by kmmbvnr** [comment]
Duplicate #803

**Comment by tomscholz** [comment]
@kmmbvnr You are right. This is a duplicate
