### ISSUE TITLE
Overlapping text in Card small

### ISSUE THREAD

**Issue by modfiles** [Dogfalo/materialize#1726]
Any way of fixing this issue wherein text is overlapping beyond horizontal line?
![card](https://cloud.githubusercontent.com/assets/11314888/8647327/938bf808-2989-11e5-8827-885db2a26d1a.jpg)

**Comment by modfiles** [comment]
heres another one same usage as above and same result
![card](https://cloud.githubusercontent.com/assets/11314888/8647483/e788ff2c-298a-11e5-8880-9af9549d8e41.jpg)

**Comment by seanmavley** [comment]
Can you show an example in say, CodePen? However from what I'm seeing, you have set a fixed height value, and the card isn't allowed to hide overflowing content. A code snippet could help make clearer what you want to achieve exactly

**Comment by modfiles** [comment]
can i assume that materializecss.com documentation also use a fix height? first image example came from materializecss.com (http://materializecss.com/cards.html) small card code sample
i'll post my own example later though im using mobile

**Comment by modfiles** [comment]
Here's an example. Basically, I just copy the source from http://materializecss.com/cards.html 
The issue appears in small screen device starting from 361px width
http://codepen.io/anon/pen/MwXpLq
![untitled](https://cloud.githubusercontent.com/assets/11314888/8668779/3dba354e-2a41-11e5-9aed-5987f9be6451.jpg)

**Comment by Dogfalo** [comment]
So what is your desired behavior? the small class adds a fixed height to the card so it will not expand to fit the content.
