### ISSUE TITLE
Material Box not opening correctly

### ISSUE THREAD

**Issue by XorProgramming** [Dogfalo/materialize#1730]
When you click on a material box image in the bottom right when the image is larger that the screen, it does not zoom in.  Well, it briefly zooms in and then back out, which affects the scrolling.  This shows up especially on a mobile device and even with the responsive-img class.

Example: http://codepen.io/anon/pen/YXvxXb/?editors=101

![image](https://cloud.githubusercontent.com/assets/11356722/8674151/ec591738-2a09-11e5-9bac-a4c7efdc66f6.png)

**Comment by Dogfalo** [comment]
To fix this, we would have to disable the dismiss on scroll until after the materialbox is done animating. Which is more useful than supporting a "reverse-lightbox" where the image starts out bigger than the page and shrinks.

**Comment by XorProgramming** [comment]
I certainly understand that a "reverse-lightbox" really is not worth losing a feature over.  However, the issue of the material box not zooming in also shows up in a much more standard scenario.  Check out this codepen: http://codepen.io/anon/pen/RPJqoJ.  This issue does not show up there (probably due to viewport issues), so just copy this code out of codepen into its own file.  If you open the page on a mobile device (or use Chrome's emulator), scroll to the bottom, and click on the image, you will see it does not work correctly.   Instead it just scrolls to the top.  I just wanted to add this, since this is a common case and it is affecting a website I am creating.  Thanks
