### ISSUE TITLE
Datepicker Appear Buggy

### ISSUE THREAD

**Issue by rizkiandrianto** [Dogfalo/materialize#1734]
I think it's a little bit buggy when I open datepicker, there's a blue border, but when I click on another area it will be disappear.

![1](https://cloud.githubusercontent.com/assets/2457820/8690978/4efe07ea-2ae6-11e5-98ce-71e8bd75ba7d.PNG)

**Comment by Dogfalo** [comment]
Please recreate this issue in a codepen so we can confirm the issue

**Comment by rizkiandrianto** [comment]
Here I wrote on jsfiddle, but a little bit messy.

http://jsfiddle.net/rizkiandrianto/n910uLjs/1/

**Comment by Dogfalo** [comment]
Your date picker has lots of custom  styling which may be causing this. Even so, I did not see the big you described

**Comment by brandonparsons** [comment]
I am also getting this issue. Using `ember-cli-materialize` though, not simple to re-recate.

**Comment by rizkiandrianto** [comment]
But I also got this issue even when I disable the custom style for calendar (look at the picture) @Dogfalo

**Comment by vanhtuan0409** [comment]
I also have this same issue when put the datepicker with container option

**Comment by kimyu92** [comment]
same here

**Comment by tsega** [comment]
I have the exact same problem, I've been trying to figure it our the whole day. What framework are you using, I'm on Rails and I'm using the Materialize-Sass gem. How about you guys?

**Comment by kimyu92** [comment]
@Dogfalo It is a little bit annoying when the calendar repop up back when i switch back and forth workspaces even though i have closed them before I switch. I would rather argue it as a bug rather than a feature. Hope to solve it asap. Thanks!

**Comment by tsega** [comment]
@kimyu92 after seeing the documentation page for the underlying [datepicker javascript library; pickadate](http://amsul.ca/pickadate.js/api/), it looks like the issue is with the library not with the materialize-css styling. You can see the issue with the blue line and the auto-popup happening right there on the documentation page. I will see the issues there and possibly link the solutions here.

**Comment by JimishF** [comment]
this issue is because of outline of some container div so i solved it by giving "outline:none" to parent.

**Comment by tsega** [comment]
@JimishF thank you so much for the fix, it works :+1:
