### ISSUE TITLE
Mobile Collapse nav work flow problem

### ISSUE THREAD

**Issue by JimishF** [Dogfalo/materialize#1735]
step 1 : re size your screen to small;
step 2 : click on mobile collapse button to open side nav bar;
step 3 : full screen your window;

Issue : Side bar is not hiding.
Please fix asap.

>>Normal (Full screen)
![image](https://cloud.githubusercontent.com/assets/8057628/8698452/05396862-2b1c-11e5-8c3d-9783240b1d60.png)

>> Small screen
![image](https://cloud.githubusercontent.com/assets/8057628/8696940/831ecc30-2b0e-11e5-830e-02f0d649074c.png)

>>clicked on button
![image](https://cloud.githubusercontent.com/assets/8057628/8696961/b24fbfdc-2b0e-11e5-80cc-e83907826c03.png)

>> now full screen, but sidebar is still showing.
![image](https://cloud.githubusercontent.com/assets/8057628/8696975/d6b26cb2-2b0e-11e5-8293-a59d729a85b4.png)

**Comment by CaptainBaxter** [comment]
I believe that this here is the intended behavior. It doesn't make much sense that it should close when you have already told it to be open? You could however write your own media query when going from mobile to desktop that would close the sidenav for you `$('.button-collapse').sideNav('hide');`.

**Comment by JimishF** [comment]
You are not getting what am i saying, child elements of nav-wrapper will only transform in to side nav when the size of window become small, but for full screen, they must be in nav bar.
Now you can see here that after following step 3, they are at both side.(In nav as well as side menu). so It is highly recommended to hide the side bar.

![image](https://cloud.githubusercontent.com/assets/8057628/8696975/d6b26cb2-2b0e-11e5-8293-a59d729a85b4.png)

**Comment by carlosperate** [comment]
Can you still dismiss the sidebar by clicking away from it? If so, I don't see an issue either.

**Comment by acburst** [comment]
This is an edge case that doesn't seem important. You can add your own styles to fix this if you find it a huge problem.

**Comment by JimishF** [comment]
okay Thank you I've fixed this already !
