### ISSUE TITLE
Forgot to complete

### ISSUE THREAD

**Issue by Diogomartf** [Dogfalo/materialize#1740]
![materialize](https://cloud.githubusercontent.com/assets/5664434/8712082/ced192f2-2b4f-11e5-9a0d-04538e8656b9.PNG)

You forgot to close the icon in the snippet bellow Icon Prefixes (http://materializecss.com/forms.html).
 I put in yellow on the pic above.

I don't know if this is the right place to put this kind of issue.

**Comment by carlosperate** [comment]
If you'd like, you can submit a pull request with a fix: https://github.com/Dogfalo/materialize/blob/master/jade/page-contents/forms_content.html#L253
