### ISSUE TITLE
Add minimal materialize dist with no dependencies

### ISSUE THREAD

**Issue by tlvenn** [Dogfalo/materialize#1741]
Somewhat related to https://github.com/Dogfalo/materialize/issues/1348 , It would be nice if the build system could produce a materialize.js with no inlined dependencies.

Right now I am using jspm to manage my dependencies and I happen to use Velocity and Hammer in my project. Since those 2 libs are inlined into materialize.js, we end up with those libs twice..

**Comment by neverfox** [comment]
+1

**Comment by tomscholz** [comment]
I guess you could edit the [Gruntfile.js](https://github.com/Dogfalo/materialize/blob/master/Gruntfile.js) and remove all hammerjs entries.
