### ISSUE TITLE
Bug in indicator when hides a tab

### ISSUE THREAD

**Issue by inventti-leonardo** [Dogfalo/materialize#1744]
Example
http://codepen.io/anon/pen/mJjdRj

I fixed this issue changing one line in tabs.js to <code>$links = $this.find('li.tab:visible a');</code>
![tabs js](https://cloud.githubusercontent.com/assets/1918010/8721809/9849520c-2b94-11e5-99de-f56fbee8781d.png)

**Comment by acburst** [comment]
Why are you hiding a tab? Why can't you just remove it? I don't think this is a problem that needs to be addressed at our level. If you have found a fix then you should be fine.

**Comment by inventti-leonardo** [comment]
Your framework is a charm. I think the framework can handle this kind of situation. Other mature frameworks that i have been used handle this. Please reconsider this functionally to next release :)

Thanks!
