### ISSUE TITLE
Background tearing during scroll

### ISSUE THREAD

**Issue by LCallaghan84** [Dogfalo/materialize#1745]
Using version 0,97.0 and I noticed a weird issue, when using a background image for the page. if you scroll, you will see a background image at the bottom of the page load/flicker 
this did not happen in the previous version.

**Comment by Dogfalo** [comment]
Please make a code pen

**Comment by LCallaghan84** [comment]
Here is the actual page. 

http://countdown.teamfreewill.net/wp-content/app-episode-list.php

**Comment by acburst** [comment]
what browser are you seeing this issue on? I cant seem to recreate it on chrome

**Comment by LCallaghan84** [comment]
It's on only on chrome on mobile device. If you scroll down fast, you will
see the bottom of the page loads the background image within a few seconds.

**Comment by Dogfalo** [comment]
I have not been able to reproduce this either. It is probably due to mobile image loading speeds. Background-image is just a CSS property and any issue with it is not an issue with materialize.

**Comment by LCallaghan84** [comment]
the issue has been resolved after chrome and webview app update.
