### ISSUE TITLE
Tooltips background color bug on google chrome

### ISSUE THREAD

**Issue by ahlechandre** [Dogfalo/materialize#1747]
#### google chrome 46.0.2457.0 canary
![chrome](https://cloud.githubusercontent.com/assets/7119058/8739846/8f03157e-2c17-11e5-87f5-5eacd27521c5.jpg)

#### mozilla firefox 39.0
![firefox](https://cloud.githubusercontent.com/assets/7119058/8739848/95185adc-2c17-11e5-96e0-e3b8afc0f851.jpg)

Hi, what might be happening?

**Comment by Dogfalo** [comment]
Idk, its a nightly-build browser.
