### ISSUE TITLE
Range slider not working in meteor

### ISSUE THREAD

**Issue by ntoka** [Dogfalo/materialize#1748]
Hi, 

I am using 0.97.0 version of materialize on my Meteor project (via official plugin) and I cannot get the range slider to work. While using the slider example code from the website I do not the the value popup. In addition to that - everytime i click the slider - a new <span class="thumb active"> is being created. And because it remains active - a new and different span is created everytime i touch or click the slider.

Is this a materialize bug or maybe a conflict with other plugins?

PS. Slider is located in a modal (if that makes any difference)

![mat](https://cloud.githubusercontent.com/assets/5622744/8743474/e53947b4-2c77-11e5-829f-d589a03dd56a.JPG)

**Comment by Chun-Yang** [comment]
@ntoka Did you solve it?

**Comment by Dahkon** [comment]
I got this issue too without using Meteor.
Version 0.97 was edited and not totally finished I think, about Range.

On materialize.js line 2634 need to be changed to : 
`$(this).after(thumb);`

And you deleted this on line 2694 (so need to add again) :  `thumb.find('.value').html($(this).children('input[type=range]').val());`

**Comment by mitar** [comment]
Pull request #1994 fixes the issue. No other change is needed from what I see.

**Comment by Chun-Yang** [comment]
I did another PR https://github.com/Dogfalo/materialize/pull/2353

**Comment by mitar** [comment]
#2353 was merged, so this could be closed now?
