### ISSUE TITLE
Just curious, is the team picture Photoshopped? :)

### ISSUE THREAD

**Issue by dandv** [Dogfalo/materialize#1749]
Let me state first that I love Materialize and have created a [Slant entry recommending it](http://www.slant.co/topics/150/viewpoints/19/~what-are-the-best-css-frameworks~materialize).

I'm just curious, was the team picture Photoshopped?

![team pic](http://materializecss.com/images/materialize_team.jpeg)

[Error-Level Analysis](http://www.errorlevelanalysis.com/):

![ELA](http://fotoforensics.com/analysis.php?id=2b3d3ad71a67166b434d6d513dc5d770b9d15b49.103934&fmt=ela)

**Comment by acburst** [comment]
Nope haha. thanks for the Slant entry!
