### ISSUE TITLE
drag out sidenav

### ISSUE THREAD

**Issue by ThunderPaul** [Dogfalo/materialize#1751]
Hello,
I noticed that in mobile applications, that to close the sidenav through the swip you must point the element .dragtarget.

You can close the sidenav conducting a swip puntanto directly element sidenav?

Thanks,
Paolo

**Comment by Dogfalo** [comment]
the drag target allows the element to be dragged even when it is not on the screen. Directly binding hammer handlers on the element also prevents normal interaction on the links
