### ISSUE TITLE
hoverable added shadow intentionally?

### ISSUE THREAD

**Issue by Digital-Thor** [Dogfalo/materialize#1753]
The `hoverable` class used to shade children of the class, but I just upgraded to `materialize:materialize@0.97.0` and was surprised to see that my `hoverable` tables now also have a [shadow around the entire table](http://materializecss.com/table.html#hoverable).  I was able to disable the shadow using: 

    .hoverable:hover {
      transition: none;
      box-shadow: none;
    }  

but am wondering if you added this shadow intentionally or if it might have slipped in by mistake?  

My vote is to keep `hoverable` the way it was since one of the great things about Materialize is its minimal elegance.  The new default shadow seems a bit much.  Also, if we need a shadow, you already provide a nice selection of `z-index` shadow classes.

**Comment by acburst** [comment]
fixed on master. Look for duplicate closed issues
