### ISSUE TITLE
Icons not shown

### ISSUE THREAD

**Issue by PhillippOhlandt** [Dogfalo/materialize#1754]
Hey,

I loaded materialize with npm. Copied the font folder into my public folder as described on the getting started guide. 

Instead of showing the icons, it shows only the icon name in caps. JS seems loaded correctly because the ripple effect works fine.

![materialize-icons-error](https://cloud.githubusercontent.com/assets/3123549/8761783/2b304812-2d63-11e5-8ecc-2ceaf1f2e67d.PNG)

**Comment by carlosperate** [comment]
If you do a simple search you'll find the same thing asked before: https://github.com/Dogfalo/materialize/issues?utf8=%E2%9C%93&q=is%3Aissue+icons+shown

Check the icons documentation page in the materialize website.

**Comment by PhillippOhlandt** [comment]
Ah works now. Thought he loads the font by it's own when it's present in the font folder.
