### ISSUE TITLE
Select 'destroy' keeps adding dropdown "caret" icon to DOM

### ISSUE THREAD

**Issue by aon108** [Dogfalo/materialize#1756]
When destroying select to re-init. 

<span class="caret">▼</span>

gets added to DOM and cannot be removed.

**Comment by Dogfalo** [comment]
Fixed for next release

**Comment by OminStyle** [comment]
Add $select.parent().find('input, i, .caret').remove(); on re-init for the time being. I'm waiting for the next release as well.
