### ISSUE TITLE
Pass button clicked on leanModal completed event

### ISSUE THREAD

**Issue by rcschettino** [Dogfalo/materialize#1757]
I'm using leanModal as confirm modal, but the event completed doesn't receive the '.modal-close' button as parameter. 
I need to identify when user click in 'Yes' or 'No' in my confirm modal and pass this button to completed event.

**Comment by fega** [comment]
Closed due inactivity, feel free to reopen it if it is still necessary.

**Comment by tomscholz** [comment]
leanModal has deprecated. Have a look at the [docs](materializecss.com/modals.html) :)
