### ISSUE TITLE
Tooltips got transparent corners

### ISSUE THREAD

**Issue by temkretz** [Dogfalo/materialize#1758]
I have a page with a lot of cards and every card got multiple tooltips.
Some of these tooltip have got transparent corners as you can see in the screenshot.

What can I do ?

[buggedtooltip](https://cloud.githubusercontent.com/assets/2982363/8766448/8744cdbe-2e38-11e5-8e9c-4ab0bbc189c9.png)

**Comment by carlosperate** [comment]
Please submit a codepen with an example.

**Comment by temkretz** [comment]
Sorry for the late response. It happens, if I set a max-width for the tooltip and if it's height is bigger then its width. Related to the scale_factor. I just raised the scale_factor and now the problem is gone!

PS: Every call of ".tooltip()" deletes all tooltips on the site a re-initiates them => performance killer for my infinite-scroll so I had to rewrite that too.
