### ISSUE TITLE
Parallax Template on Firefox Defaults To Mobile

### ISSUE THREAD

**Issue by TheCaucasianAsian** [Dogfalo/materialize#1759]
First of all, materializecss is awesome!  Thank you for taking the time to put this together!

I have run into a weird issue though and have a potentially stupid question.  I've downloaded the parallax template and currently running locally with a python SimpleHTTPServer and for some reason, when running in firefox it defaults to mobile and I can't get it to switch to desktop (See image below).  (Also there aren't any errors in the firefox console.) Tried it in Chrome and everything was fine.  What's weird though is that when I open your online parallax demo in firefox, everything looks perfect.  Regardless, I will just switch over to chrome for development and will be deploying the site to see if the behavior changes.  Not sure if you'll have time to look into this, but thank you in advance for your time and assistance!

Machine/Environment specs:
<ul>
<li>Machine: Macbook pro, 15 inch 16gb, running Yosemite 10.10.4</li>
<li>Firefox Version: 39</li>
<li>Chrome Version: 43.0.2357.134</li>
<li>Editor: Sublime</li>
<li>CMD Used to Host Locally: python -m SimpleHTTPServer</li>
</ul>

<h3>What I see when I run locally on firefox: </h3>
<img width="1395" alt="screen shot 2015-07-19 at 12 38 07 pm" src="https://cloud.githubusercontent.com/assets/3781589/8767482/317d9dae-2e13-11e5-9d79-162217b82fbb.png">

<h3>What I see when I click your demo on the site in firefox (also what I see when I run locally in chrome):</h3>
<img width="1396" alt="screen shot 2015-07-19 at 12 51 09 pm" src="https://cloud.githubusercontent.com/assets/3781589/8767530/df70f554-2e14-11e5-8f7c-293a0eb44b39.png">

**Comment by Dogfalo** [comment]
maybe you just have zoomed in on your localhost on Firefox. Either way, this is likely not a Materialize issue, let me know if you any updates.

**Comment by TheCaucasianAsian** [comment]
Update is: I'm retarded.  Thank you for the quick fix and sorry for the confirmed stupid question  :)
