### ISSUE TITLE
@charset in _global necessary? Prevents scoped SASS

### ISSUE THREAD

**Issue by toastercup** [Dogfalo/materialize#1761]
Hello, friends!

I am trying to scope/wrap up Materialize in a SASS class, as it conflicts with our own styling, and also fiddles with the HTML/Body tags.

The issue, however, is with the `@charset` declaration in `components/_global.scss`. SASS requires that `@charset` declarations be at the beginning of a SASS file, and cannot be wrapped in a class. I can work around the declaration in `materialize.scss` by not using this file and just including all the components I need myself, but not so with `_global`.

So this brings me to my question - is the `@charset` declaration in `_global.scss` necessary, since SASS defaults to UTF-8 anyways? Is it something I could submit a PR to remove? I see the commit that brought in this change that relates to Github Pages: https://github.com/Dogfalo/materialize/commit/0a827d0373c146e920cc107fa6dc412feac19d2c#diff-6e878a45e039655a0e04cc191d6b4db7R1

**Comment by Dogfalo** [comment]
You are right, it isn't really necessary to have it in there.
Removed in 60131b3
