### ISSUE TITLE
Input Autofocus

### ISSUE THREAD

**Issue by gfazioli** [Dogfalo/materialize#1762]
Hi there, may be an issue on input with autofocus. The `autofocus` attribute or:
```js
$( '#inputField' ).focus();
```
seems works, as you can see in below image
![image](https://cloud.githubusercontent.com/assets/432181/8773234/fd539f0e-2ed2-11e5-9d98-21dd2b706419.png)

but when I start typing I see that
![image](https://cloud.githubusercontent.com/assets/432181/8773248/118cbe88-2ed3-11e5-9eea-d2fca56ce766.png)

any idea?

**Comment by JimishF** [comment]
Add class "active" to the Label.

**Comment by Dogfalo** [comment]
Autofocus does work, 

see https://jsfiddle.net/6stuh1nh/4/

**Comment by trostli** [comment]
In safari that JSFiddle does not show Autofocus working

**Comment by JimishF** [comment]
Yeah I got problem with auto-focus attribute in IE. But 
```javascript
$( '#inputField' ).focus();
```
seems to be work fine.

**Comment by kmuenze** [comment]
I cannot get this to work $('#last_name').focus(); 

on this page: http://materializecss.com/forms.html

Did this regress?

**Comment by kmuenze** [comment]
added a settimeout as described below and it worked.

https://github.com/Dogfalo/materialize/issues/822#issuecomment-77524620

**Comment by altus34** [comment]
In Firefox 46.0.1 the JSFiddle does not show Autofocus working
