### ISSUE TITLE
Select : class active doesn't match with the selected li

### ISSUE THREAD

**Issue by TyrionGraphiste** [Dogfalo/materialize#1764]
Hi !

I recently discover an issue with the Select plugin.
"active" dynamic class doesn't match with the selected li element, as a matter of fact, the DOM is updated once time after we opened again the dropdown menu.

You can try yourself at the demo page : http://materializecss.com/forms.html#select and looking which li has the active class.

Can you fix this please ?

Moreover, your plugin doesn't include select with multiple options : http://www.w3schools.com/tags/tryit.asp?filename=tryhtml_select_multiple

Can you implement it ?

Anyway thanks for everything.

**Comment by carlosperate** [comment]
I am not sure I understand the first part of the question. If you are refering at chaing the select dynamically you'll have to reinitialise the materialize select or destroy it and create it again as indicated in the "Updating/Destroying Select" section from http://materializecss.com/forms.html#select .

About the second part there is already a request for mutiple selections in the select: https://github.com/Dogfalo/materialize/issues/1002

**Comment by TyrionGraphiste** [comment]
I'll try to explain a little better than previously.
When you select an option, an "active" class is dynamically added. But the class isn't applied on the correct item after you selected it. There is a "lag".

For the multiple select I finally created a a plugin for materialize, is there a render screen :
![multiple_select](https://cloud.githubusercontent.com/assets/10064887/8972631/1994b424-365c-11e5-981d-abbd96cc7b1c.PNG)

**Comment by Dogfalo** [comment]
You should be getting the selected value like this: http://www.w3schools.com/jsref/prop_select_value.asp

**Comment by TyrionGraphiste** [comment]
Hi Dogfalo,

I have no problems regarding the recovery of the option selected, the only one I encounter concerns the position of the active class on the selected item.

What you have linked is a way to set the select with a new option, not really get it.
For getting the selected option we can do like this :

var select = $("#select"),
      selectedOpt = select.find("option:selected");

So we can do like this for getting the option, it's right, but in this case what is the point to placing an active class ? Especially if it is not on the right.

**Comment by tejovanthn** [comment]
I added the following code near `select.siblings` in the `toggleEntryFromArray` function to update the select fields too.
```
      var child = select.children('option').eq(entryIndex);
      if(child.attr("selected")){
          child.removeAttr("selected");
      }
      else{
          child.attr("selected","selected");
      }
```

**Comment by TyrionGraphiste** [comment]
You should create your own PR and submit it.
