### ISSUE TITLE
pickadate version

### ISSUE THREAD

**Issue by bsrdjan** [Dogfalo/materialize#1767]
The datepicker version used is more than a year old: https://github.com/Dogfalo/materialize/blob/master/js/date_picker/picker.js

Are there plans to upgrade to current version 3.5.6 and add timepicker functionality ?

**Comment by Dogfalo** [comment]
This is a lower priority for us, upgrading the version takes some time as we made a lot of modifications to it. Maybe when the major version is updated we will upgrade.
