### ISSUE TITLE
checkbox + label, position issue

### ISSUE THREAD

**Issue by ibart** [Dogfalo/materialize#1768]
a div with checkbox + labels looks like this to me; relative position makes it appear like the screenshot. 
![schermata del 2015-07-21 08 40 13](https://cloud.githubusercontent.com/assets/12794205/8794453/365671ee-2f84-11e5-8cfc-2b8b96f125da.png)

**Comment by Dogfalo** [comment]
Please provide a codepen

**Comment by ibart** [comment]
here it is: http://migio.com/materializeproblem.txt

**Comment by Dogfalo** [comment]
Please see https://github.com/Dogfalo/materialize/blob/master/CONTRIBUTING.md

**Comment by ibart** [comment]
Sorry!
http://codepen.io/anon/pen/qdMNmR
Is it correct?

**Comment by Dogfalo** [comment]
Just add a z-index to your overlay and that should resolve the problem
