### ISSUE TITLE
text box Label click problem.

### ISSUE THREAD

**Issue by JimishF** [Dogfalo/materialize#1769]
Hey I've faced a minor issue where i click on the floating label of a text box, it's not focusing on the text box, for that i have to click outside the Label area. Please give solution for this.

![image](https://cloud.githubusercontent.com/assets/8057628/8794421/346a8916-2fa1-11e5-8515-a0ac4b6fabff.png)
>> clicking on label (not focusing to text box )

**Comment by JimishF** [comment]
I got the solution, It was related to ID conflicts

**Comment by Dogfalo** [comment]
Please make a code pen

**Comment by JimishF** [comment]
i think its not necessary, It happens while i have not gave ID to that text field, but materialize is smart enough to move label by clicking on text field, but when i click on label, It is unable to find out field of given ID, so it was not floating.
Another conflict was If i gave same ID to two different Labels, than focusing one will trigger another also.

**Comment by simoazzo** [comment]
I have the same problem but the ids are different.

Any idea how to solve it?

**Comment by kmmbvnr** [comment]
@simoazzo check that the label `for` attribute matched to the input `id`

![forms materialize](https://cloud.githubusercontent.com/assets/282529/20556008/35e8816e-b18f-11e6-98ab-e0baa2503273.png)

**Comment by simoazzo** [comment]
Cheers. Working Now. Thank you @kmmbvnr
