### ISSUE TITLE
Uncaught SyntaxError

### ISSUE THREAD

**Issue by junland** [Dogfalo/materialize#1776]
Our project is building a app store, we have successfully build are page but we got this error when running it locally through Brackets.

>Uncaught SyntaxError: Unexpected token (materialize.min.js:910)

Only changes to the source files were the color of the navbar. Other than that we haven't changed anything.

Were also running the lastest version. (0.97)

**Comment by andersevenrud** [comment]
+1

**Comment by andersevenrud** [comment]
This is how to fix it in the minimized version:
```

diff --git a/js/materialize.min.js b/js/materialize.min.js
index a41e330..8ad6fc9 100644
--- a/js/materialize.min.js
+++ b/js/materialize.min.js
@@ -907,7 +907,7 @@ jQuery.easing.jswing = jQuery.easing.swing, jQuery.extend(jQuery.easing, {
                         if (v.Hooks.registered[c]) {
                             var i = c,
                                 j = v.Hooks.getRoot(c);
-                            e = e || v.(a, j), d = v.Hooks.injectValue(i, d, e), c = j
+                            e = e || v(a, j), d = v.Hooks.injectValue(i, d, e), c = j
                         }
                         if (v.Normalizations.registered[c] && (d = v.Normalizations.registered[c]("inject", a, d), c = v.Normalizations.registered[c]("name", a)), h = v.Names.prefixCheck(c)[0], 8 >= n) try {
                             a.style[h] = d
@@ -4711,4 +4711,4 @@ Vel = $ ? $.Velocity : Velocity,
         }, a(document).ready(function () {
             a("input, textarea").characterCounter()
         })
-    }(jQuery);
\ No newline at end of file
+    }(jQuery);

```

**Comment by andersevenrud** [comment]
I don't know if that is correct however. Maybe it expects a `.apply(a, j)` or something

**Comment by junland** [comment]
I think it maybe on our end.

![diff](https://cloud.githubusercontent.com/assets/9792545/8835282/16c9b7c2-307f-11e5-968e-1ad15f744842.PNG)

The left is latest from this repo and the right is from our repo. So its a small change....

**Comment by andersevenrud** [comment]
Aha. There you have it then. Would be weird if it was a silent update... since you downloaded a build and all.

**Comment by carlosperate** [comment]
It sounds like you have found your issue, so I'll close this, otherwise let me know and I'll reopen it.
