### ISSUE TITLE
SIDE NAV DISAPPER IN MOST BROWSER

### ISSUE THREAD

**Issue by zionnite** [Dogfalo/materialize#1777]
thanks materizie teams....
i must say to you,  you guys have done a very wonderful job....materize framework its a very promising  framework and i believe its future...
i hosted a site and the site display normal on a computer but wen i view it from my phone device , to be precise i used UC Browser to view , it display as espected but when i view the hosted site from an OPERA Browser on my phone device i notice the side NAVIGATION DISAPPEAR .....this is the hosted site url (www.apostle-john.joons-me.com)  pls what am i to do....???? 
thanks for all ur suggestion and pointing me to the right direction

**Comment by RogerAntonio** [comment]
I noticed the same on my local website, fixed it by commenting out "left: -105%;" in the css files for all the .side-nav.fixed

**Comment by zionnite** [comment]
thanks for the quick response, but i try doing it the way you said but it
did not work....
please more of your help is needed and i appreciation your time,
thanks

**Comment by carlosperate** [comment]
It looks like you are using an old version of materialize (as I can still scroll the page when the side menu is out). Could you update it and try again? Does this only happen in mobile opera?

**Comment by RogerAntonio** [comment]
> It looks like you are using an old version of materialize (as I can still scroll the page when the side menu is out). Could you update it and try again? Does this only happen in mobile opera?

I'm using the most recent version, and I don't think the issue is not being able to scroll.
I am using Chrome and as I resize the browser window horizontally, the side-nav.fixed disappears (in my case because it has "left: -105%;" somewhere in a query.
So I commented that line out and now it's working as I want it to work, which is that it never disappears :)

**Comment by RogerAntonio** [comment]
Zionnite, You have 1 side-nav that is placed "left: -205px" by in-line styling, if you remove that in-line styling, your side-nav should be visible again.
Your navigation next to "Home" are disappearing because it has the class "hide-on-med-and-down".

**Comment by zionnite** [comment]
ok thanks... i will do that now ( u gave me strength....) thanks Antonio
and yes the navigation close to home are really disappering thanks again
for the heads up

**Comment by zionnite** [comment]
i have been fighting this code since morning and i have not seen any
change....
pls getting frustrated..... i still need your assistant in completing this
work

**Comment by Dogfalo** [comment]
Just remove `hide-on-med-and-down`
