### ISSUE TITLE
Icons in a nav dropdown not showing correctly

### ISSUE THREAD

**Issue by dietergeerts** [Dogfalo/materialize#1781]
This is because they are styled like icons will only be in the navbar itself and not in the dropdown that's on the navbar. `:not(dropdown-content)` should be added

**Comment by carlosperate** [comment]
Could you provide a codepen to illustrate the issue you are reporting? (there is a template codepen link in the [contributing](https://github.com/Dogfalo/materialize/blob/master/CONTRIBUTING.md) file). I'm not 100% sure what icons you are referring to, icons in the nav bar? icons in a drop down added to the navbar?

**Comment by dietergeerts** [comment]
Hi, I am talking about the icons in the dropdown that's added to a navbar. While making the codepen, I saw it is fixed in the latest version (0.97.0), but npm only has 0.96.1, so if the new version could be put on npm, that would be great!

**Comment by carlosperate** [comment]
There was an issue publishing 0.97.0 to npm, but the next version will be there.
