### ISSUE TITLE
Whether the embedded MarkDown

### ISSUE THREAD

**Issue by guoyoujin** [Dogfalo/materialize#1786]
I want to use the MarkDown, can you embed MarkDown, or going to embed MarkDown

**Comment by carlosperate** [comment]
I'm not quite sure I understand the question. Are you requesting markdown to html conversion functionality? That does not really fall within the goals of this framework, I'm sure there are really good libraries available to achieve this.

**Comment by guoyoujin** [comment]
ok ,think you
