### ISSUE TITLE
Tabs with different widths

### ISSUE THREAD

**Issue by cskiwi** [Dogfalo/materialize#1788]
hi,

Is there a posibility to have the tabs be the width of the text (with optional padding)?

as you can see here:
http://codepen.io/anon/pen/bdmeOO

All the tabs always have the same width, even when setting the col to differnt sizes

**Comment by ilovezy** [comment]
yeah, i think add a string cut in js should be good, or maybe have a overflow: hidden,
to protect the text in tabs too long

**Comment by carlosperate** [comment]
Yeah, I also thing I would rather have the text cut out somehow (overflow hidden is the easiest fix, js cutting the string and adding an elipsis would be the most readable), than to have unmatched tab widths.

**Comment by Zaanmedia** [comment]
+1

**Comment by vladbalan** [comment]
:+1:

**Comment by arfordweb** [comment]
You guys are saying you'd rather have tabs forced to be the same width with ellipses at the end of longer names than have variable widths on the tabs?  That viewpoint seems strange to me.

It's easy to create a good-looking set of tabs in HTML/CSS with variable widths.  The only problem seems to be the indicator.  It assumes tabs are the same width.  It doesn't seem to be overly difficult to match the position and width of each tab while making no assumptions about how wide each is.

Are the issues you have with variable widths from an implementation viewpoint?  Or do you have UX concerns?

**Comment by krabbypattified** [comment]
I'm with you arfordweb. I like the way this works:
http://codepen.io/krabbypattified/pen/oYzrmB

**Comment by acburst** [comment]
There is now support for fixed width and variable width tabs.
