### ISSUE TITLE
Collapsible and select

### ISSUE THREAD

**Issue by toben** [Dogfalo/materialize#1790]
Hello,

I have a problem using select into collapsible.
![sans titre](https://cloud.githubusercontent.com/assets/511578/8871907/233e45ec-31f9-11e5-80b4-79e549b7b7de.png)

You can see that the "z-index" is not well defined (maybe ?).

**Comment by carlosperate** [comment]
This issue is already being discussed in https://github.com/Dogfalo/materialize/issues/1385 and https://github.com/Dogfalo/materialize/issues/1527

**Comment by acburst** [comment]
Please post a codepen. I just copy and posted an example collapsible and inserted an example select and it worked straight away.

**Comment by justinjoyn** [comment]
+1, Tried making the position:fixed for select-dropdown, the options now render above modal, but I can't place the dropdown under the select input.

**Comment by fega** [comment]
Please provide a way to reproduce it. like a [codepen](https://codepen.io/fega/pen/BWeZaG)
Closed due inactivity, feel free to reopen it if it is still necessary.
