### ISSUE TITLE
Change colors for blockquote, forms etc...

### ISSUE THREAD

**Issue by PhillippOhlandt** [Dogfalo/materialize#1797]
Hey,

the blockquote element is by default red and the forms are teal by default. I didn't find a way to override it with classes. Is that planned for the future?

Phillipp

**Comment by carlosperate** [comment]
That's a good question, I guess for now you could do something like: http://codepen.io/anon/pen/eNPVNe

**Comment by PhillippOhlandt** [comment]
Yeah that could be a hotfix. Have my two colors in a config file so i can change the colors on the whole page by editing my config file. So it would be cool for the future to controll even blockquotes, forms and so on via classes.

**Comment by Dogfalo** [comment]
You won't be able to override it with any prepackaged classes, but you can use Sass to change all the variables to your liking
