### ISSUE TITLE
the container seems to be to tight on mobile?

### ISSUE THREAD

**Issue by ilovezy** [Dogfalo/materialize#1800]
here is my problem, I think this materialize css is great, but I got this problem 
In materilize.css, the container defined like this
.container {
    padding: 0 1.5rem;
    margin: 0 auto;
    max-width: 1280px;
    width: 90%;
}
@media only screen and (min-width: 601px) {
    .container {
        width: 85%;
    }
}
@media only screen and (min-width: 993px) {
    .container {
        width: 70%;
    }
}

why the container's width become much smaller when the screen is smaller
I think on mobile the container should be larger right? I have to fix this every time by myself
@media only screen and (min-width: 601px) {
    .container {
        width: 90%;
    }
}
@media only screen and (min-width: 993px) {
    .container {
        width: 90%;
    }
}

but when I check the http://materializecss.com/
It seems the container's width is not only 70%
![qq 20150726104125](https://cloud.githubusercontent.com/assets/8774988/8892281/d5382c7e-3382-11e5-898a-1cb0325257f5.jpg)

Can you make a container-fluid class like bootstrap?

**Comment by carlosperate** [comment]
In the code that you posted (which can also be seen at [bin/materialize.css#L5018-5029](https://github.com/Dogfalo/materialize/blob/1b92fb29a6deeb0e6d8ca211c93a78a260f40355/bin/materialize.css#L5018-5029), and its defined in [sass/components/_grid.scss#L1-15](https://github.com/Dogfalo/materialize/blob/master/sass/components/_grid.scss#L1-15)):

```
.container {
  margin: 0 auto;
  max-width: 1280px;
  width: 90%; }

@media only screen and (min-width : 601px) {
  .container {
    width: 85%; } }

@media only screen and (min-width : 993px) {
  .container {
    width: 70%; } }
```

The width percentage increases inversely to the width, notice the __min-width__ keywork. So it goes 90% from 0px-600px, 85% from 601px-992px and 70% on 993px and higher.

**Comment by ilovezy** [comment]
OUCH!! 
my bad, yeah it is my careless,

**Comment by ilovezy** [comment]
but I still think 90% it not wide enough on mobile, there are too muck blank on left and right side,
this is my test
![qq 20150726111346](https://cloud.githubusercontent.com/assets/8774988/8892359/469e8de6-3387-11e5-8909-25522121bd3c.jpg)

this is your page
![qq 20150726111529](https://cloud.githubusercontent.com/assets/8774988/8892363/8c811b26-3387-11e5-901e-f6dcdb45fd47.jpg)

it seems that on your page the width is much larger than 90%?

**Comment by carlosperate** [comment]
Just tested a random page in the materialize website and the container is working as expected with a 90% width, which looks very similar to the screenshot you have submitted.

It looks to me as if you have two nested containers in your implementation, giving you a total working width of 80%. Otherwise please submit a codepen (there is a template in the [contributing](https://github.com/Dogfalo/materialize/blob/master/CONTRIBUTING.md) file) to illustrate your issue.

**Comment by ilovezy** [comment]
yeah, the materialize website container width is 90%,
but I got two screen shoot here
![qq 20150726121951](https://cloud.githubusercontent.com/assets/8774988/8892569/e121b196-3390-11e5-8aa0-490f835816db.png)

![qq 20150726122106](https://cloud.githubusercontent.com/assets/8774988/8892570/e4b6b82e-3390-11e5-8a38-4d73d63d0755.jpg)

you see, if I change the container width to 100%, it look perfect, I really can't find where is the problem ,
it makes me crazy

**Comment by carlosperate** [comment]
if you are using `row` and `col`, each `col` has a left and right padding of 0.75 rem

**Comment by acburst** [comment]
Please make a codepen to help us find the problem

**Comment by ilovezy** [comment]
http://jsfiddle.net/icehota/qwrosdkn/2/
I use jsfiddle, it look good on jsfiddle
![qq 20150727190425](https://cloud.githubusercontent.com/assets/8774988/8904479/4533e9f4-3492-11e5-9e06-085234284c66.png)


and I put a sample on my page 
see here please
http://www.icehota.com/cc-materialize/materialize/
![qq 20150727190456](https://cloud.githubusercontent.com/assets/8774988/8904483/4975f2fa-3492-11e5-8ad2-e74415d4950d.jpg)

same code, different showup, 

I am  really confused

**Comment by carlosperate** [comment]
I don't think you are using the latest version of Materialize. If I use the debugger inspector to replace the css file you are loading from your server to the latest one the padding works as expected. Please upload 0.97.0 to your website and try again.

**Comment by ilovezy** [comment]
thank god it finally finished!
thanks so much, I download the lastest and it looks perfect,
thanks!
by the way can you make the h1, h2,h3, these header tags font-size change a little smaller on min screens, It looks really too big, it's my suggest, not that necessary

**Comment by ilovezy** [comment]
and I use the npm install materilize before, you should updata the scource on npm

**Comment by meichenblatt** [comment]
I am trying to override the default width. I need more space I am tried this but it didn't work. 

@media only screen and (min-width: 993px) {
    .container {
        width: 80%;
    }
}

**Comment by carlosperate** [comment]
Glad it's working, I'm closing this issue then.
About npm, there was an issue publishing 0.97.0, but the next version should be publishable there.
