### ISSUE TITLE
Image resizing problem when use "card hoverable" class and "row" class in the same time

### ISSUE THREAD

**Issue by gosick** [Dogfalo/materialize#1807]
Hi, everyone . I found a problem when I use class "card hoverable" in class "row". This will result in image resizing like sample below:
![Alt Text](http://i.imgur.com/S2yLvhj.png)

When I clicked the left side image, it looked like this
![Alt Text](http://i.imgur.com/E4SWXX6.png)

But when I clicked the right side image, I got this one
![Alt Text](http://i.imgur.com/qDcREKT.png)

Here is my sample code
![Alt Text](http://i.imgur.com/dHH09oJ.png)

If anyone has some idea about this problem, please teach me how to solve this.
Thanks!

**Comment by acburst** [comment]
Can you convert your code into an easy to view codepen to help us identify the problem?

**Comment by gosick** [comment]
Oh, sorry.
Here is the demo
http://codepen.io/gosick/pen/QbJbZM

**Comment by Dogfalo** [comment]
Remove overflow:hidden to fix this.

On Mon, Jul 27, 2015 at 9:33 PM, Jimmy Huang <notifications@github.com>
wrote:

> Oh, sorry.
> Here is the demo
> http://codepen.io/gosick/pen/QbJbZM
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Dogfalo/materialize/issues/1807#issuecomment-125437370>
> .
>



-- 
Doggy sends his greetings from Mars.

**Comment by gosick** [comment]
I see. It's the style "overflow:hidden" in card resulting in the image resizing abnormally.
I try it, and it works very well.
Thanks for helps!!
