### ISSUE TITLE
form element

### ISSUE THREAD

**Issue by PadreValetudo** [Dogfalo/materialize#181]
Hi!
I have a problem. Demo input and text area on your site work well, but when I try to put them on my site it  does not work. Checkbox, radio, range and datepicker work good, exept input and textarea. When I click on the field, label does not push up. I haven't any problems with js - console is clear.

P.S. Sorry for my english)

**Comment by joseAlbano** [comment]
For dynamic forms rendering, i find it unacceptable having to reload the script, easiest solution i have found is on forms.js (original source code) :

// Handle HTML5 autofocus
    $('input[autofocus]').siblings('label, i').addClass('active');

Just use it without "autofocus", just to inputs and problem solved

**Comment by sheki** [comment]
I agree with joseAlbano. The form renders pretty poorly. Is there a cleaner solution coming up ?

**Comment by TaherHo** [comment]
Thanks @orlax . That helped ;-)
