### ISSUE TITLE
Opening and closing a modal several times does not work

### ISSUE THREAD

**Issue by mmontone** [Dogfalo/materialize#1810]
Opening and closing a modal several times does not work

```
<div id="my-modal" class="modal">
  <h1>Hello</h1>
</div>

<script type="text/javascript">
  $("#my-modal").openModal();
  $("#my-modal").closeModal();
  $("#my-modal").openModal();
</script>
```

Shows and empty overlay with no modal

**Comment by fega** [comment]
Yeah, that's a weird behavior, but it also looks as a very strange and extreme uncommon edge case. 

this could be a work as a quick workaround,

But ¿this issue is giving you any problem in normal conditions?

Closed due inactivity, feel free to reopen it if it is still necessary.
