### ISSUE TITLE
Primary/Secundary color palette

### ISSUE THREAD

**Issue by dietergeerts** [Dogfalo/materialize#1811]
Hi,

I like how we can use colors, though I'm missing a way to use the primary/secundary color like that. So I would like to say: `color-primary lighten-2` for example. If this is not yet possible, cause I may be overlooking it, then can this be a new feature?

**Comment by Lazar95** [comment]
In case I'm not overlooking it too, I'm really surprised this hasn't been given more attention. I thought it's pretty common to do it this way, so we can change the theme more easily in the future. What's the point of `$primary-color` if I can't use `.primary` class in my HTML?

**Comment by tomscholz** [comment]
You can use scss variables [here](https://github.com/Dogfalo/materialize/blob/master/sass/components/_variables.scss#L33)
