### ISSUE TITLE
Grid problem

### ISSUE THREAD

**Issue by T00rk** [Dogfalo/materialize#1812]
I'm using grid to render a list of users.

    <% _.each(user, function(a, ax){ %>
    <div class="col s6 m6 l4">
        <div class="card">
            <a href="/u/<%= a.id %>">
                <div class="card-image">
                    <img src="<%= window.location.protocol + "//" + window.location.host + "/pictures/" + a.picture %>" class="social" />
                </div>
            </a>
            <div class="card-content">
                <div class="center-align">
                    <a class="block" href="/u/<%= a.id %>"><%= a.name.replace(' ', '<br/>') %></a>
                    <% if(typeof(a.canDelete) !== 'undefined' && a.canDelete === true) { %>
                        <a class="btn-edit-administrator dropdown-button hidden" href="javascript:void(0)" data-activates='dropdown-administrator-edit-<%= ax %>'><i class="material-icons right">more_vert</i></a>
                        <ul id='dropdown-administrator-edit-<%= ax %>' class='dropdown-content dropdown-menu settings'>
                            <li><a href="javascript:void(0);" class="block btn-remove-administrator delete" data-id="<%= a.id %>"><span class="mdi-content-remove-circle"></span> Supprimer</a></li>
                        </ul>
                    <% } %>
                </div>
            </div>
        </div>
    </div>
    <% }); %>

**Problem** [http://hpics.li/4a4d7d2](http://hpics.li/4a4d7d2)

**Comment by Dogfalo** [comment]
Add fixed height to images to fix this
