### ISSUE TITLE
Modal doesn't respect open config on close

### ISSUE THREAD

**Issue by davismj** [Dogfalo/materialize#1819]
```
$('#modal').openModal({complete:function(){console.log('something')}});
$('#modal').closeModal(); // console empty
```

**Comment by carlosperate** [comment]
The options are respected if the modal is closed non-programatically (if you dismiss it using the modal button, or click away).
If the `closeModal` function is used then new defaults are given and options have to be set using the function argument.

http://codepen.io/anon/pen/BNGYOz

**Comment by davismj** [comment]
I'm not sure why anyone would open the modal programatically with a set of options just to discard them, especially with respect to the complete callback. It just isn't a use case.

**Comment by boustanihani** [comment]
I am having the same issue, I need to close the modal programatically and wait until the animation completes then finally remove all unneeded nodes from the dom...

I think @davismj is right and as a solution I suggest providing the ability to override options (if needed) but when no further options are passed to ```closeModal```, then the ones passed to ```openModal``` should be respected.

**Comment by jvv** [comment]
I agree with @boustanihani and @davismj, just ran into this issue myself and created a small fiddle to see if the callback was ignored when running the closeModal function http://jsfiddle.net/xarzLd9z/ - does not really make sense that if I close the modal without any options the openModal (okay, leanmodal) function's options are not respected.

**Comment by nurhadijogja** [comment]
same issue, but i use this quick fix to fix my issue:
```
closeModal({
    complete: function(){
        // remove modal instance
    }
});
```

**Comment by fega** [comment]
closeModal and closeModal are deprecated

Closed due inactivity, feel free to reopen it if it is still necessary.
