### ISSUE TITLE
Trouble on font icons with meteor mobile on android

### ISSUE THREAD

**Issue by elbowz** [Dogfalo/materialize#1820]
I can see the icons, but something is wrong and something have not a good formatting.

![screenshot_2015-07-29-10-22-04](https://cloud.githubusercontent.com/assets/1451484/8953115/9d5f4844-35dc-11e5-9658-5fc7fd3cfb8a.png)

All works like a charm on Chrome mobile:
![screenshot_2015-07-29-10-30-26](https://cloud.githubusercontent.com/assets/1451484/8953180/f76f3fce-35dc-11e5-9a1a-adb6942cb94f.png)

**Comment by carlosperate** [comment]
I assume you are running Android 4.3 or older? I'm afraid that support for android below 4.4 is rather limited at the moment.

**Comment by elbowz** [comment]
Strange, I have Android 4.4.4

**Comment by elbowz** [comment]
Installing https://github.com/poetic/meteor-materialize-sass go better...but not all icons are fixed
