### ISSUE TITLE
Collapsible header text not doesn't  wrap correctly

### ISSUE THREAD

**Issue by FelipeRosa** [Dogfalo/materialize#1827]
I know this is a duplicate of #1169, but a long text in any collapsible-header doesn't wrap correctly. I'm using the meteor package.

**Comment by lsunsi** [comment]
+1

**Comment by carlosperate** [comment]
As stated in the issue you have linked, this has already been fixed, just not yet released. If can't wait until the next version is released, you could use the files from https://github.com/Dogfalo/materialize/tree/master/bin.
