### ISSUE TITLE
#leanmodal hash bang (#! aka shebang) modal-close problematic

### ISSUE THREAD

**Issue by CNSKnight** [Dogfalo/materialize#1828]
I am using `<base href="http://mysite/">` in an HTML5 `<header/>`. 
Given the exampled:

```
<a href="#!" class=" modal-action modal-close btn-flat">
      <i class="material-icons">close</i>
</a>
```

Is anyone else experiencing a page location change on _modal-action modal-close_ element click?

Beyond this, if it's just an action hook and not a link to some ajax resource, why not simply use this, which works fine w/out the overhead of an `<a/>'s` default action:

```
<button class=" modal-action modal-close waves-effect waves-orange btn-flat" type="button">
       <i class="material-icons">close</i>
 </button>
```

**Comment by danielhickman** [comment]
You can remove the `href` attribute or make it a `<span>`. 
The shebang (`href="#!"`) is only there to validate the `<a>` tag completely which is not needed.

**Comment by philipraets** [comment]
@danielhickman: the button element is the most correct element in this case, that's what its made for.

**Comment by danielhickman** [comment]
@philipraets But materialize doesn't use the button tag at all. There's issues clearing the default styles for it cross-browser.

**Comment by fega** [comment]
@CNSKnight What browser were you using? 

Could you check if this is still an issue with the latest version?

Closed due inactivity, feel free to reopen it if it is still necessary.
