### ISSUE TITLE
How to add custom validation to Materialize

### ISSUE THREAD

**Issue by VK432** [Dogfalo/materialize#1829]
@Dogfalo 

I was looking through the materialize library, and was wondering whether it would be possible to add custom validation, for different types other than the built in, text, number etc..
Any help or idea from anyone would be great :)
Haven't been able to work this out myself work this out myself :(

**Comment by philipraets** [comment]
check #595 
that one has a possible solution

**Comment by brockklein** [comment]
(leaving this here for posterity's sake)

It would depend on what stack you're using. I just finished adding some pretty nice validations using Angular 2 built in form controls. Using its conditional class application I simply apply `valid` or `invalid` to the field accordingly. 

E.g.

```html
<input 
        type="text" 
        id="name" 
        formControlName="name" 
        [class.invalid]="!complexForm.controls['name'].valid && complexForm.controls['firstName'].touched" 
        [class.valid]="complexForm.controls['name'].valid && complexForm.controls['firstName'].touched"
      >
```

Of course how you write the validations and how you apply the classes will be different depending on how you're structuring your app the basic principle of "write your own validations then add/remove the `valid` and `invalid` classes to invoke Materialize's design" should work well.

**Comment by Native-Coder** [comment]
It _would_ be nice to add some custom rules similar to jQuery's validate plugin. I'd like to validate that 2 password fields match. Using the validate plugin it would be as simple as

`$('#password_1').validate({
    rules:{
         equalTo: '#password_2'
    }
});


$('#password_2').validate({
    rules:{
        equalTo: '#password1'
    }
})`
