### ISSUE TITLE
bad materialboxed image size when in a card

### ISSUE THREAD

**Issue by kuroidoruido** [Dogfalo/materialize#1835]
I wanted to use something like that:
```html
<div class="row">
	<div class="col s6 m6 l6">
		<div class="card">
			<div class="card-content">
				<img class="materialboxed" width="300" src="http://images2.fanpop.com/images/photos/5700000/Random-random-5719763-1280-800.jpg" />
			</div>
		</div>
	</div>
</div>
```
It doesn't work. When I click on the image, the image box is "inside" the card and I see only the part of the image that is inside the limit of the card like here:
![screenshot_2015-07-31_02 55 47](https://cloud.githubusercontent.com/assets/2668904/8998575/b0bb25ee-372f-11e5-97d5-1fc07a12892f.png)
![screenshot_2015-07-31_02 55 50](https://cloud.githubusercontent.com/assets/2668904/8998574/b0bb5834-372f-11e5-9dec-260e6577ed20.png)

**Comment by Dogfalo** [comment]
Please search closed issues
