### ISSUE TITLE
Dropdown icon break inside navbar IE10+

### ISSUE THREAD

**Issue by victoreassis** [Dogfalo/materialize#1836]
The arrow_drop_down icon break the navbar on IE10+ without `display:inline-block`. the solution was add `nav ul li a.dropdown-button {display: inline-block;}` to my local css.
Keeps working fine on Chrome and Firefox.

_Note: I'm using the 0.97.0 version from the CDN_

**Comment by jais-p** [comment]
Thanks for the fix!
That was indeed an ennoying bug.
