### ISSUE TITLE
how I call textareaAutoResize function?

### ISSUE THREAD

**Issue by inyerade** [Dogfalo/materialize#1837]
I include materialize.js I have the effects all ok but when I create and fill a textarea with javascript but the height is no good. I only see first 3 lines of 7 line text.

I create textarea like this:

```
var html_1 = '<textarea class="materialize-textarea" name="c" id="textarea1">'+diag.text+'</textarea>';
$('#pane2').append(html_1);
```

I try with 

```
$('#textarea1').trigger('autoresize');
```

and

```
textareaAutoResize( $(#textarea1));
```

and nothing happen

any idea? 

I think the problem is I don't know call a function inside of  (function( $ ){ ... }( jQuery )

**Comment by Dogfalo** [comment]
Use a document.ready or you may be on an old version
