### ISSUE TITLE
Background image flicker when changing radio button

### ISSUE THREAD

**Issue by bschnelle** [Dogfalo/materialize#1839]
[CodePen](http://codepen.io/anon/pen/XboKpo)

When using a background-image on the body tag along with radio buttons a screen flicker occurs below the radio buttons when changing selections.

Edit: The issue above occurs in Chrome, but a different issue occurs in Safari where the font weight flickers instead.

**Comment by jrsilverman** [comment]
Experiencing the same thing, though I can't reproduce in your CodePen.  Were you able to find a solution to this problem?

**Comment by bschnelle** [comment]
We ended up dropping the background image.

**Comment by DanielRuf** [comment]
I can not reproduce this with the latest stable Chrome on Windows 10.
