### ISSUE TITLE
Question about material ui lite

### ISSUE THREAD

**Issue by djalmaaraujo** [Dogfalo/materialize#1840]
Since google launched the new ui kit, do you have plans to continue this project? Google material lite is pretty simple yet with too many components missing.

thanks.

**Comment by ahlechandre** [comment]
i'll migrate when **mdl** get more components

**Comment by Dogfalo** [comment]
Yes we do :smile: .

**Comment by djalmaaraujo** [comment]
@Dogfalo Thanks for letting me know.
