### ISSUE TITLE
Collapisble without data-collapsible ignores JS options

### ISSUE THREAD

**Issue by marco-kretz** [Dogfalo/materialize#1842]
When you try to initialize a '.collapsible' which has no data-collapsible attribute and pass "accordion: false" to collapsible() it gets a accordion instead. I already found the problem:

https://github.com/Dogfalo/materialize/blob/master/dist/js/materialize.js#L388

if (options.accordion || collapsible_type === "accordion" || collapsible_type === undefined)

**Comment by fega** [comment]
Closing due inactivity.
If you're still having this problem feel free to open a pull request or reopen this issue
