### ISSUE TITLE
Tabs not working correcly in collapsible structure

### ISSUE THREAD

**Issue by KaSaras** [Dogfalo/materialize#1844]
Cant get active tab botom border in collapsible structure.
Please check second collapsible tab:

http://jsfiddle.net/kasaras/tdz6uraL/1/

**Comment by ahlechandre** [comment]
you are using the same ids to these tabs. will work like a charm if you change the ids. for example

first tab
```html
  <div class="row">
    <div class="col s12">
      <ul class="tabs">
        <li class="tab"><a href="#test1">Test 1</a></li>
        <li class="tab"><a class="active" href="#test2">Test 2</a></li>
      </ul>
    </div>
    <div id="test1" class="col s12">Test 1</div>
    <div id="test2" class="col s12">Test 2</div>
  </div>
```
second tab
```html  
  <div class="row">
    <div class="col s12">
      <ul class="tabs">
        <li class="tab"><a href="#test3">Test 1</a></li>
        <li class="tab"><a class="active" href="#test4">Test 2</a></li>
      </ul>
    </div>
    <div id="test3" class="col s12">Test 1</div>
    <div id="test4" class="col s12">Test 2</div>
  </div>
```

**Comment by carlosperate** [comment]
As @ahlechandre has indicated, you need to give them unique identifiers: http://codepen.io/anon/pen/XbGqgQ

**Comment by constantin-v** [comment]
Hi,
I got a simple Tabs component in a simple Collapsible component and I got the same issue.
I look previous answers but I got unique identifiers.

[](https://jsfiddle.net/6axccg75/ )
--> first tab is marqued active but he hasn't bottom border

[](https://jsfiddle.net/70qms28o/)
--> forcing with select_tab : both tab got the bottom border

Any ideas ?
