### ISSUE TITLE
How to dismiss tooltip via javascript (not itself)

### ISSUE THREAD

**Issue by mibcadet** [Dogfalo/materialize#1846]
Hello, I got problem with meteor iron:router and materializecss. When I use .tooltipped it works almost perfect. When I click on tooltipped button / link the tooltip stays as it appeared untill I refresh browser.
So I would like to just manually call javascript method wich will allow me to close it after that click event. 

I just look for something like 'closeOnClick' in side-nav.

**Comment by Dogfalo** [comment]
$(elem).trigger('mouseleave'); should work
