### ISSUE TITLE
showStaggeredList causes lightbox's image to disappear

### ISSUE THREAD

**Issue by leonardo015** [Dogfalo/materialize#1847]
Codepen: http://codepen.io/leonardo015/pen/PqXRoZ

As you can see in the Pen: the lightbox's image gets hidden when it is inside a li that had Materialize.showStaggeredList() on it.

The issue seems to be the CSS  transform: translateX(0px); that the li gets after the animation.

**Comment by fega** [comment]
Solved in the current version
