### ISSUE TITLE
Getting Search + Buttons in navigation bar

### ISSUE THREAD

**Issue by KrisSiegel** [Dogfalo/materialize#1848]
I'm trying to find a way to make the navigation bar entirely a search box except for 1-2 buttons on the very right. Right now I can get the icon buttons to show up on the same row but the search box is really tiny (I want to fill all space except for the space occupied by the right button(s)).

Is there a built-in way to do this in materialize that I'm missing or do I need to do some CSS overriding? Which the latter is fine but I wanted to ask to see if I'm missing anything obvious.

Here is some code I'm playing with:
```html
<nav>
    <div class="nav-wrapper">
        <ul class="right">
            <li><a href="#"><i class="mdi mdi-close"></i></a></li>
        </ul>
        <form class="left">
            <div class="input-field">
                <input id="search" type="search" />
                <label for="search"><i class="mdi mdi-magnify"></i></label>
            </div>
        </form>
        
    </div>
</nav>
```

**Comment by ahlechandre** [comment]
maybe

```html
<nav>
  <div class="nav-wrapper">
    <div class="row">
      <div class="col s10">
        <form>
          <div class="input-field">
            <input id="search" type="search" />
            <label for="search"><i class="material-icons">search</i></label>
          </div>
        </form>
      </div>
      <div class="col s2">
        <ul class="right">
          <li><a href="#"><i class="material-icons">close</i></a></li>
          <li><a href="#"><i class="material-icons">link</i></a></li>
        </ul>
      </div>
    </div>
  </div>
</nav>

```

**Comment by KrisSiegel** [comment]
Oh. Not sure why I didn't think of using the grid. Ugh, thanks. I'll try that tonight.

**Comment by KrisSiegel** [comment]
There is a slight bit of padding but otherwise this is good. I can go from here; thanks!

**Comment by ahlechandre** [comment]
yeah this is also my trouble

**Comment by KOLEGA007** [comment]
This solution is not working on
Google Chrome	52.0.2743.82 
![image](https://cloud.githubusercontent.com/assets/2377891/17278145/aeca8bac-5755-11e6-8f88-b97b5fb85f5e.png)

**Comment by VicFrolov** [comment]
Yep, I can confirm this solution breaks on chrome

**Comment by ferbispojesus** [comment]
Solution ->

input[type="search"] {
  height: 64px !important; /* or height of nav */
}

**Comment by chahat** [comment]
Thanks for the code snippet, I used this and also added close icon to my search-form but close icon never shows up.. Any work arounds?

**Comment by Inamacio** [comment]
I had this same problem of stylizing the search bar in the navalize of materialize, I got the code snippet from friend @ahlechandre ahlechandre and I modified it to stay as I wanted, follow the code.
HTML
`
<div class="navbar-fixed">
  <nav class="blue accent-2" >
    <div class="nav-wrapper">
      <div class="row">
        <div class="col s2">
          <ul class="left">
          <li><a href="#">Logo</a></li>
          </ul>
        </div>
        <div class="col s7">
          <form class="search-input">
            <div class="input-field">
            <input id="search" type="search" />
            <label for="search"><i class="material-icons">search</i></label>
            </div>
          </form>
        </div>
        <div class="col s3">
          <ul class="right">
            <li><a href="#">Produtos</a></li>
            <li><a href="#">Sobre</a></li>
            <li><a href="#">Contato</a></li>
          </ul>
        </div>
      </div>
    </div>
  </nav>
</div>
`
CSS 
`input[id="search"] {
height: 45px !important; 
  margin-top: 10px;
   border-radius: 5px;
}
.search-input{
      background-color: #82b1ff ;
  height: 45px !important; 
  margin-top: 10px;
  border-radius: 5px;
}
nav .input-field label {
    top: -8px;
    left: 0;
}`

**Comment by Inamacio** [comment]
I had this same problem of stylizing the search bar in the navalize of materialize, I got the code snippet from friend @ahlechandre ahlechandre and I modified it to stay as I wanted, follow the [code.](https://codepen.io/Inamacio/pen/KvRwyx)
