### ISSUE TITLE
Material Icons Don't Work on Samsung Galaxy SIII 

### ISSUE THREAD

**Issue by kamuran21** [Dogfalo/materialize#1849]
Material Icons don't work on galaxy sIII, NoteII, Note III.

On samsung S4, and Iphone It works well but It does not work on these.

screen : 
http://imageshack.com/a/img909/740/fc12Qo.png

**Comment by carlosperate** [comment]
I'm assuming your galaxy sIII, NoteII, Note III and running an android version below 4.4, in which case this would be a duplicate of: https://github.com/Dogfalo/materialize/issues/1802
