### ISSUE TITLE
Dismissable for dynamically created element

### ISSUE THREAD

**Issue by dvbondoy** [Dogfalo/materialize#1850]
Hello! How can i implement dismissable collection to dynamically created elements..I've tested and created the collection but swiping seems not working. Any advice? thanks

**Comment by csapir** [comment]
To my knowledge, there's no official way to do this yet. 

What I would do is copy and wrap the `$(document).ready` handler that sets up all of the `.dismissable` collections (line 3399 in materialize.js) in a function that I can call whenever I want.

**Comment by dvbondoy** [comment]
Big Thanks to you @csapir .tried your advice and it worked out great..

For others that need this here's what i did..

1. i copied the code from materialize.js
2. put it inside a function. mine is dismissable()
3. bind it in an event.. 

```javascript
$("#list").on("mouseenter", ".dismissable", function(){
//call in function
dismissable();
});

```

And finally for callback..here's my post for that
https://github.com/Dogfalo/materialize/issues/803

thanks again @csapir ..you're awesome

**Comment by csapir** [comment]
@dvbondoy you're welcome, cheers!
