### ISSUE TITLE
Modal toast sent to background screen

### ISSUE THREAD

**Issue by bsrdjan** [Dogfalo/materialize#1852]
When toast created in currently open modal screen, it is not displayed in the modal but on background screen. How to send the toast to open modal screen ?

**Comment by Frekimoto** [comment]
I had the same problem. I've added the following code to my main css:

.toast, #toast-container {
	z-index: 11001;
}

I think there was an another solution in a commit, but I didn't find it.

**Comment by Dogfalo** [comment]
Fixed in bdf0aafef9ae8e7362f575b4e37e8b0f4a363569

**Comment by wuarmin** [comment]
A z-index of 10000 is not enough. We need at least 10001 in my case. Do you observe the same?
