### ISSUE TITLE
Multiple modal overlays can be applied via hitting enter multiple times with the modal trigger selected

### ISSUE THREAD

**Issue by agweber** [Dogfalo/materialize#1854]
Two ways to replicate;
 - Click on modal trigger, then press enter.
 - Tab until modal trigger highlighted (which is difficult to tell with materialize), then press enter.

There's no way for the user to remove the multiple screen-darkening overlays without refreshing the page.

**Comment by carlosperate** [comment]
This pull request should be able to fix this issue as well: https://github.com/Dogfalo/materialize/pull/1691

**Comment by agweber** [comment]
Ah, it appears issue #1647 is exactly the same as this one. I did a search but did not find any when I created this issue. This can likely be flagged as a duplicate (not sure how the moderation works on github, maybe I should just close this?)

**Comment by carlosperate** [comment]
I'll close it, as https://github.com/Dogfalo/materialize/issues/1647 would cover this as well.
