### ISSUE TITLE
Dynamically make ranges

### ISSUE THREAD

**Issue by cskiwi** [Dogfalo/materialize#1859]
Hi,

I've been using the [angular-materialize](https://github.com/krescruz/angular-materialize) for a while now, and it works great when using angular and materialize.

but now we bumped in to a small "problem" with the range sliders: because there is no direct function tp create the thumb, we can't create a directive for it to make it popup.

So my issue is more asking for moving the initialization of the range slider to a function instead of just putting the code in the `$(document).ready(function())`

Thanks in advance

**Comment by Dogfalo** [comment]
With our material noUISlider we added recently, you can make a range slider with a defined range.
