### ISSUE TITLE
material-icons star_rate   Bug 

### ISSUE THREAD

**Issue by foxtail000** [Dogfalo/materialize#1860]
this icon always on the left.

**Comment by Dogfalo** [comment]
What do you mean?

**Comment by foxtail000** [comment]
![image](https://cloud.githubusercontent.com/assets/10229164/9153185/f7f451f0-3e79-11e5-935b-a342d6930da6.png)

**Comment by donwojtallo** [comment]
Same here on latest Chrome, Firefox and Edge.

**Comment by donwojtallo** [comment]
It looks like there is no "star_rate" icon (I'm not 100% sure). Instead of that, a "star" icon appears with hidden "_rate".
For temporary fix, use "star", it's the same icon.

**Comment by austinpray** [comment]
This is still an issue here as well. It might not have anything to do with Materialize because I had the same issue with the material icons + bootstrap.

**Comment by Dogfalo** [comment]
The icon set is maintained by Google, so it would be better to open an issue there. But a fix is just to set the size explicitly, like so:
```
    font-size: 45px;
    width: 45px;
    height: 45px;
```
