### ISSUE TITLE
date picker not support closeOnSelect action? 

### ISSUE THREAD

**Issue by liniu** [Dogfalo/materialize#1862]
date picker not support closeOnSelect action?  and how to hidden date-display panel?

**Comment by andrebetiolo** [comment]
It shows an error, but it works:

$(".datepicker").on('change blur' ,function(){
	var label = $("label[for='"+this.id+"']")[0];
	if(label){
		label.className = "active";
	}
	this.close();
});

**Comment by liniu** [comment]
Thank you, and I recommend adding this action.
