### ISSUE TITLE
Table unresponsive behaviour

### ISSUE THREAD

**Issue by zionnite** [Dogfalo/materialize#1868]
Please People my table is not responsive on mobile browser , even when i re-size my browser it would not still re-size....
please what must i do???

http://http://joons-me.com/apostle-john/itinerary#my_container

**Comment by carlosperate** [comment]
Currently the website is not loading, it would be easier to help you if you provide a codepen with an example of your issue.

**Comment by Dogfalo** [comment]
Closed for lack of response. And I looked at your site and it looks like it is working.
