### ISSUE TITLE
Select sizing breaks grid flow

### ISSUE THREAD

**Issue by davismj** [Dogfalo/materialize#1869]
In Chrome for Mac, flowing rows of more than 12 columns, so that they wrap fluidly, breaks when one of those items is a select. Here is a screenshot of the issue:

![screen shot 2015-08-07 at 10 24 44](https://cloud.githubusercontent.com/assets/3845823/9126956/d17aa308-3cee-11e5-8f84-0dd742f15912.png)

Changing the height of selects just a small amount resolves the issue. Reducing the height on the select style resolves the issue:

**materialize@0.97.0.css:6706 (context added)**

```
.select-wrapper input.select-dropdown {
    position: relative;
    cursor: pointer;
    background-color: transparent;
    border: none;
    border-bottom: 1px solid #9e9e9e;
    outline: none;
    height: 2.9rem;
    line-height: 3rem;
    width: 100%;
    font-size: 1rem;
    margin: 0 0 15px 0;
    padding: 0;
    display: block;
}
```

**Comment by fega** [comment]
Closed due inactivity, feel free to reopen it if it is still necessary.
