### ISSUE TITLE
your home page icons looks not very good

### ISSUE THREAD

**Issue by ilovezy** [Dogfalo/materialize#1871]
hei, I'd like to try some icons, but something wrong is happed on your webpage
look

![qq 20150808003843](https://cloud.githubusercontent.com/assets/8774988/9140704/b4755664-3d65-11e5-993e-a771a3231ab7.png)

**Comment by rikato** [comment]
Not for me mhm did you reload your page :$

**Comment by ilovezy** [comment]
all right, still not working,
by the way can you add a tool which is called  
back to top
It's simple and usefulI think you should consider it

**Comment by Dogfalo** [comment]
What browser are you using?

**Comment by Dogfalo** [comment]
Due to lack of feedback/information, I'll be closing this issue. If you can give us more information we can reopen it.
