### ISSUE TITLE
Wrong icons path

### ISSUE THREAD

**Issue by oliviernguyenquoc** [Dogfalo/materialize#1874]
There is plenty of errors in documentation and in implementation :1234: 
http://materializecss.link/icons.html

Like "mdi-navigation-arrow-back" should be a back arrow instead of the menu icon or "mdi-navigation-menu" should be a menu icon and not a calendar icon.

**Comment by Dogfalo** [comment]
Not really sure what site you are looking at, but the correct documentation is here, http://materializecss.com/icons.html
