### ISSUE TITLE
Left and Right side menu at same time

### ISSUE THREAD

**Issue by ddingman** [Dogfalo/materialize#1875]
Using materialize with meteor. 

One of the side menus does not close on click over ~50% of the window. This was mentioned in #457 but never discussed further.

Example project that breaks here:
https://github.com/ddingman/testMaterializeSlideOuts

Click on the Open left menu text, then click on "click here 4". This will replicate the bug.

**Comment by jberiksen** [comment]
iSuslov have the solution in the issue #1417

**Comment by ddingman** [comment]
Apologies for my confusion of naivety ahead of time.

I see the fix (1417) and the merge into master (1418). But out of the box, fully updated to the latest version, the meteor package still has the bug, as demonstrated in the example project:
https://github.com/ddingman/testMaterializeSlideOuts

What am I missing in the project I posted in order to have 1418 come through into my project?

**Comment by carlosperate** [comment]
That's because a new version since the fix has not yet been released. You'll have to wait until the next materialize version is out, or you could include the javascript and css files manually from https://github.com/Dogfalo/materialize/tree/master/bin.

**Comment by ddingman** [comment]
Got it, thank you!
