### ISSUE TITLE
Card reveal activator doesn't work

### ISSUE THREAD

**Issue by eguneys** [Dogfalo/materialize#1881]
```
<div class='card'>
  <div class='card-content'>
    Content
  </div>

  <div class='card-action'>
    <a class=btn activator'>
      Register
    </a>
  </div>

  <div class='card-reveal'>
    <a class='btn'>
      Register
    </a>
  </div>
</div>
```

When I click `Register text` it doesn't reveal, it I click the button area besides the `Register text` it reveals.

**Comment by eguneys** [comment]
Also I want to be able to close the reveal with js how can I do that?

**Comment by ahlechandre** [comment]
first, in your above code you have a syntax error  

```html
 <a class=btn activator'>
      Register
    </a>
```

and i'm not sure, but i think you need to add class ```.card-title``` to your reveal close trigger works

look http://codepen.io/ahlechandre/pen/OVqBgB

**Comment by eguneys** [comment]
Ah I figured what the cause is.

I am using React and instead of `Register` as text, I have a React component that wraps it. So it's like this:
```
<a class='btn activator'>
  <FormattedMessage message='register'/>
</a>
```

This produces the following dom:

<div class='btn activator'>
  <span> Register </span>
</div>

So if I wrap the text with `span` it doesn't activate the reveal, if I click somewhere other than the text it works. See:

http://codepen.io/eguneys/pen/vOPQLb

**Comment by ahlechandre** [comment]
basically, this occurs because in [card.js](https://github.com/Dogfalo/materialize/blob/master/js/cards.js) materialize have
```javascript 
if ($(e.target).is($('.card-reveal .card-title')) || 
    $(e.target).is($('.card-reveal .card-title i'))) 
{
   // hide reveal
}
else if ($(e.target).is($('.card .activator')) || 
         $(e.target).is($('.card .activator i')) ) 
{
  // display reveal
}
```

so, when you click on ```span``` inside ```.activator``` the ```event.target``` will be ```<span> Register </span>``` and don't match the any condition

but you could make a workaround adding other ```.activator``` class to ```span``` tag

**Comment by eguneys** [comment]
Or, materialize should fix the bug and everthing works inside `.activator` no matter what.

**Comment by ahlechandre** [comment]
yep, i agree
