### ISSUE TITLE
Modal does nothing

### ISSUE THREAD

**Issue by nh1402** [Dogfalo/materialize#1882]
Have tried linking to a modal with a material icon button, modal button shown on website, but upon pressing the button nothing happens. Testing on a Nexus 5 Android M Developer Preview version 2.

**Comment by eguneys** [comment]
You have to include Material javascript files and export jquery and Materialize as globals.

**Comment by nh1402** [comment]
If I understand you correctly, I have already done that.

**Comment by carlosperate** [comment]
Could you provide a codepen with the issue as indicated in the [contributing](https://github.com/Dogfalo/materialize/blob/master/CONTRIBUTING.md) file? It would be quite helpful.

**Comment by nh1402** [comment]
Turns out I didn't initialise it in document onready. Must have modified the javascript since I last used it.
