### ISSUE TITLE
¿Fix?- Eliminate render-blocking JavaScript and CSS in above-the-fold content

### ISSUE THREAD

**Issue by ghost** [Dogfalo/materialize#1883]
Not really much to say, you know how to solve this problem?

![sin titulo](https://cloud.githubusercontent.com/assets/8794949/9180216/bc64d7e8-3f66-11e5-86ac-5d428efaa9d3.png)

https://developers.google.com/speed/docs/insights/OptimizeCSSDelivery

**Comment by tomscholz** [comment]
This has nothing todo with materialize itself. Please close.
