### ISSUE TITLE
Waves effect and data-disable-with

### ISSUE THREAD

**Issue by cars10** [Dogfalo/materialize#1884]
Hi guys, there is an issue with the following setup:

```
<a class="btn waves-effect" data-disable-with="test" data-remote="true" rel="nofollow" data-method="post" href="http://mylink">Check now</a>
```

If i click the link, then the waves appear and the data-disable-with content shows up. but even after the event finished correctly, the waves do not dissapear. the button is now darker then it was before. if i click again, it gets even darker - up to beeing black in the end.

this only happens if you keep the mouse on the link for the whole time, it gets "fixed" if you just leave the button and rehover over it.

Is there a workaround for this? i could remove the waves manually if that is possible.

**Comment by carlosperate** [comment]
Could you provide a codepen illustrating your issue? The code given works as expected: http://codepen.io/anon/pen/jPJXxp

**Comment by cars10** [comment]
Sure! 
Your fiddle does not work because there is no actual request going on.
But I quickly set up a rails app that illustrates the problem, see the code here if you are interested:
https://github.com/cars10/materialize-1884

i also deployed it, see
http://materialize.cars10k.com/


thinking about it now i am wondering if this is even a bug. Using the data-disable-with makes the button to change its content immediatly, and that also means the ripple effect.

**Comment by hubsmoke** [comment]
Just FYI, this behavior was happening for me when I accidentally included the materialize js file twice on the same page
