### ISSUE TITLE
Font-colors not respected in the darken patterns?

### ISSUE THREAD

**Issue by cdutson** [Dogfalo/materialize#1885]
Hi there! I'm giving materialize, and I can't tell if this is pilot error or if I'm misunderstanding something.

I'm trying to apply a background color to a panel. I do that by using the following:
```
<header class="col s12 deep-purple darken-4">This div is 12-columns wide</header>
```
That works great, except I notice that the `color` is still black. Looking at http://materializecss.com/color.html, the color pallete has white text on all of the darken elements. Looking at inspector, it seems they've all been manually tooled to be white.

So am I right in thinking that you have to set the text to white through some other process (extending the class, setting the color on a parent, etc), or am I missing something obvious?

**Comment by carlosperate** [comment]
Something like what is shown in the "Text Color" section from the link you posted would work: http://codepen.io/anon/pen/qdvwWG
