### ISSUE TITLE
Icons are not showing bellow KitKat (Android)

### ISSUE THREAD

**Issue by freebumba27** [Dogfalo/materialize#1888]
Hello
I had just implemented the materialize in html pages and calling those pages using phone-gap as an application. It's working android 4.4 + but no icons are showing bellow 4.4 version.

Any reason for that or any solution?

![img-20150811-wa0000](https://cloud.githubusercontent.com/assets/12707934/9190874/6331b03a-4018-11e5-9e58-6591d18f9614.jpg)
![screenshot_2015-08-11-10-58-26](https://cloud.githubusercontent.com/assets/12707934/9190875/6339ad1c-4018-11e5-8db8-6bf8547ceaf5.png)

**Comment by freebumba27** [comment]
Got the solution It's simple need to add this CSS 

.material-icons {
    font-family: 'Material Icons';
    text-rendering: optimizeLegibility;
    font-feature-settings: "liga" 1;
    font-style: normal;
    text-transform: none;
    line-height: 1;
    font-size: 24px;
    display: inline-block;
    overflow: hidden;
    -webkit-font-smoothing: antialiased;
    -moz-osx-font-smoothing: grayscale;
}

**Comment by carlosperate** [comment]
I'll relate this issue here for future reference: https://github.com/Dogfalo/materialize/issues/1802
