### ISSUE TITLE
Use REM-based Sizing

### ISSUE THREAD

**Issue by paranoid-android** [Dogfalo/materialize#1891]
Hello,

I like what I've seen with Materialize. However, there is one item stopping me from using it: the units.

From what I can tell, Materialize uses pixels for sizing. However, the trend is to use REMs. This makes it easier for typography and components. This is really valuable across different device types and sizes. I've seen this trend happening with:

Bootstrap 4
Zurb Foundation 5

Using REM-based sizing in Materialize would be valuable towards future-proofing apps made with Materialize.

**Comment by Dogfalo** [comment]
We use it in some places, but we aren't gonna be changing our units.
