### ISSUE TITLE
RTL Support

### ISSUE THREAD

**Issue by prp-e** [Dogfalo/materialize#1892]
please add rtl Support and add some Property for set a part of row in center

**Comment by prlweb** [comment]
please add support to RTL languages that wide range of developers in Persian and arabic spoken countries be able to use your product.

**Comment by idoivri** [comment]
+1!

**Comment by baraamashaal** [comment]
+1

**Comment by MahdiMajidzadeh** [comment]
+1

**Comment by drweb88** [comment]
+1

**Comment by siyanew** [comment]
+1

**Comment by sajjad-ser** [comment]
you can get rtl version from https://github.com/sajjad-ser/materialize

**Comment by drweb88** [comment]
@sajjad-ser  very thank's bro.

**Comment by MahdiMajidzadeh** [comment]
I make rtl version too, but not my version and not @sajjad-ser 's version, neither fully support of rtl

**Comment by MOstafaMRady** [comment]
+1

**Comment by moslemir** [comment]
+1

**Comment by sepehr1014** [comment]
+1

**Comment by MatanYed** [comment]
+1

**Comment by davidbgeek** [comment]
+1 :+1:

**Comment by alzintani** [comment]
+1

**Comment by aviadbd** [comment]
+1...

**Comment by mrash14** [comment]
+1

**Comment by sajjad-shirazy** [comment]
+1

**Comment by rSafari** [comment]
+1

**Comment by yyy2015c01** [comment]
+1

**Comment by mamos98** [comment]
Someone should start adding RTL support to Materialize by forking it and making the changes. They might not be familiar with RTL standards. I might start forking this repo and try adding RTL support to it soon! Will let you all know.

**Comment by mamos98** [comment]
@MehdiMajidzadeh Thanks for your work but two questions!
1. Is it Sass Based RTL or you've made the changes in the CSS files?
2. Can it be used for both RTL and LTR or its just for RTL?


_I'm actually looking for something that gives you the power to change direction just by a Sass Variable_ like Zurb Foundation

**Comment by KiarashS** [comment]
+1

**Comment by omidh28** [comment]
A year has been passed and still no clean way to add RTL support, +1

**Comment by n1arash** [comment]
+1

**Comment by ahb360** [comment]
+1

**Comment by obscurede** [comment]
+1

**Comment by MahdiMajidzadeh** [comment]
any good news?

**Comment by elsiete** [comment]
+1

**Comment by tomscholz** [comment]
The dissussion has moved [here](https://github.com/Dogfalo/materialize/pull/4391)

**Comment by ateweb** [comment]
lock at > [https://github.com/atechninfo/materialize-rtl](https://github.com/atechninfo/materialize-rtl)

**Comment by MahdiMajidzadeh** [comment]
I made my own and it's seem good
https://github.com/MahdiMajidzadeh/materialize-rtl

**Comment by MR-Mostafa** [comment]
+1

**Comment by elsiete** [comment]
We wrote a simple scss file for the ease of use, take a look at https://github.com/Jooyeshgar/materializecss-RTL

**Comment by Shadow-Talent** [comment]
+1

**Comment by Shadow-Talent** [comment]
+1 : (
