### ISSUE TITLE
Collections > Dismissable not working after ajax request

### ISSUE THREAD

**Issue by jpoupee** [Dogfalo/materialize#1893]
Hello,

Collections > Dismissable is not working after ajax requests. Is it possible to add the part of the code  into $(document).ready(function() { ...code... }) into a simple function ?

Example : 
$(document).ready(function() { Materialize.initDismissable(); });

 Materialize.initDismissable= function() {

...code...

  };

File involved : materialize > js > transitions.js

Thanks a lot.

**Comment by fega** [comment]
Please provide a way to reproduce it. could be a codepen or fiddle
Closed due inactivity, but feel free to reopen it if it is still necessary.

**Comment by nicolasbonnici** [comment]
Got the same workaround, simply take a look at node_modules/materialize-css/js/transitions.js:80 and turn the code into a jQuery plugin.

As a dirty hack you can simply do this:

Into a document ready function:

  $(document).ajaxStop(function() {

    // Touch Event
    var swipeLeft = false;
    var swipeRight = false;


    // Dismissible Collections
    $('.dismissable').each(function() {
      $(this).hammer({
        prevent_default: false
      }).bind('pan', function(e) {
        if (e.gesture.pointerType === "touch") {
          var $this = $(this);
          var direction = e.gesture.direction;
          var x = e.gesture.deltaX;
          var velocityX = e.gesture.velocityX;

          $this.velocity({ translateX: x
          }, {duration: 50, queue: false, easing: 'easeOutQuad'});

          // Swipe Left
          if (direction === 4 && (x > ($this.innerWidth() / 2) || velocityX < -0.75)) {
            swipeLeft = true;
          }

          // Swipe Right
          if (direction === 2 && (x < (-1 * $this.innerWidth() / 2) || velocityX > 0.75)) {
            swipeRight = true;
          }
        }
      }).bind('panend', function(e) {
        // Reset if collection is moved back into original position
        if (Math.abs(e.gesture.deltaX) < ($(this).innerWidth() / 2)) {
          swipeRight = false;
          swipeLeft = false;
        }

        if (e.gesture.pointerType === "touch") {
          var $this = $(this);
          if (swipeLeft || swipeRight) {
            var fullWidth;
            if (swipeLeft) { fullWidth = $this.innerWidth(); }
            else { fullWidth = -1 * $this.innerWidth(); }

            $this.velocity({ translateX: fullWidth,
            }, {duration: 100, queue: false, easing: 'easeOutQuad', complete:
              function() {
                $this.css('border', 'none');
                $this.velocity({ height: 0, padding: 0,
                }, {duration: 200, queue: false, easing: 'easeOutQuad', complete:
                  function() { $this.remove(); }
                });
              }
            });
          }
          else {
            $this.velocity({ translateX: 0,
            }, {duration: 100, queue: false, easing: 'easeOutQuad'});
          }
          swipeLeft = false;
          swipeRight = false;
        }
      });

    });
  });
