### ISSUE TITLE
[Bug] SideNav does not check if it has already been created

### ISSUE THREAD

**Issue by Aghassi** [Dogfalo/materialize#1894]
Due to the limits of my current situation, I am doing a lot of front end routing with Angular. This means that (as far as I have figured out) I can only initiate the SideNav when someone first accesses the web page. This means if someone access the page through a `#/` the SideNav won't be initiated (because angular routing is only called when the website is hit directly). So to get around this, I could initiate the SideNav creation at ever route I take, which is linked to a controller. This issue here is that this will create:
1. a memory leak 
2. multiple overlays.

For each route I take it will create a new sideNav without killing the prior one, and leave it there. The more routes I take, the more that are created, and as a result the more `sidenav-overlays` that are created. Since the sidenav only removes one overlay at a time, this causes the extras to pile up and make the page unusable. 

I'd like to propose two fixes:
1. calling `.sideNav()` will kill any existing sideNav processes if any already exist
2. closing a sidenav should go through and remove all the sidenav-overlays. Not just the first one.

**Comment by Aghassi** [comment]
```
setTimeout(function () {
            $('.button-collapse').remove();
            $('<a></a>', {
                'href': "/",
                'data-activates': 'slide-out',
                'class': 'button-collapse'
            }).insertBefore('.side-nav.fixed');
            $('<i></i>', {
                'class': 'mdi-navigation-menu'
            }).appendTo('.button-collapse');
            activateSideNav('.button-collapse');
    }, 100);
```

I made a temporary fix for now. Until this is fixed, blow away the old dom node, and create a new one and add the sideNav to it ( `activateSideNav()` does that for me).

**Comment by einlaiq** [comment]
I can't understand where exactly i should put your code

Aghassi, can You help me?

**Comment by Aghassi** [comment]
@einlaiq I out this code in a function I call every time I load a page. I'm not sure how you structured your project, but for me I have an Angular controller for each page that I load that calls some setup functions.

**Comment by einlaiq** [comment]
**Aghassi**, thanks for response!

Well, I'm using Yii and I have some more "problems":
— my `init.js`:
```javascript
(function($){
  $(function(){
    $('.button-collapse').sideNav();
  });
})(jQuery);
```

— what I need:
page with 2 `side-nav` but not on every page in my case, there are different layouts and views.

Your code works for me only once, because of beforeAction.

`activateSideNav('.button-collapse');` not working for me, instead: `$('.button-collapse').sideNav();`
`'data-activates': 'slide-out'` not working for me, instead `'data-activates': 'nav-mobile'`

**Comment by Aghassi** [comment]
@einlaiq I don't know much about Yii, I have never used it. In the case you are describing, with one page needing it, and another page not, is there a way to just check what the current path is? So if your page is the one you need it on, you can just call the activation method?

Also, please bear in mind my code is specific to my project, and that you would have to adapt it to yours. So for me, I called my nav `slide-out`, but you named yours `nav-mobile` which is why it didn't work.

**Comment by fega** [comment]
@Aghassi Did you solve the problem? 
Closed due inactivity, feel free to reopen it if it is still necessary.
