### ISSUE TITLE
Forms not working if there is an error (Rails)

### ISSUE THREAD

**Issue by SpencerCDixon** [Dogfalo/materialize#1896]
![screen shot 2015-08-11 at 2 34 07 pm](https://cloud.githubusercontent.com/assets/7471018/9206477/115bc142-4036-11e5-8b51-c586fcd552a0.png)
![screen shot 2015-08-11 at 2 33 52 pm](https://cloud.githubusercontent.com/assets/7471018/9206479/17cb9e30-4036-11e5-8681-f91957ec2cd7.png)

If you look at the name field it's not popping up like it's suppose to.  This only happens when a user submits a form and theres an error

**Comment by chrisdurheim** [comment]
I've had the same - assuming you have an @project variable available to your form from your controller, try adding a class definition of 'active' for each of your labels for fields in the form; to maintain the dynamic behavior when there's no name variable provided, I used the following:

    <%= f.label :name, class: (@project.name ? 'active' : '') %>

**Comment by mkhairi** [comment]
https://github.com/mkhairi/materialize-sass/issues/46

**Comment by tomscholz** [comment]
whoops
