### ISSUE TITLE
Materialize Dropdown not working with UI-Router Resolved values...

### ISSUE THREAD

**Issue by lt3be** [Dogfalo/materialize#1897]
I have a dropdown whose ng-options are based on a value resolved via ui-router.

App.js that is applicable:

```
.state('root.transition.discharge.assessment', {
            url: '/assessment',
            views: {
                'content@root.transition': {
                    templateUrl: 'discharge/assessment/view-assessment.html',
                    controller: 'AssessmentController'
                }
            },
            resolve: {
                docs: function(AssessmentService) {
                    return AssessmentService.getDocuments();
                },
                services: function(AssessmentService) {
                    return AssessmentService.getServices();
                }
            }
        })
```

The variable "services" is resolved properly as a list of available services.  That list should then populate my select via ng-options:

```
<select id="discharge-view-assessment-select-a-service" class="browser-default" ng-model="assessmentModel.selectedService" ng-options="service as service.displayName for service in assessmentModel.services" ng-change="assessmentModel.savePatientCareService()" ng-if="assessmentModel.services">
    <option value="" disabled selected>Select a Service</option>
</select>
```

NOTE:  the ng-if is there because I tried to use the solution outlined [here](http://stackoverflow.com/questions/29402495/values-not-showing-up-in-select-button).  However, that solution looks like it is for situations where the ng-options should be coming via a promise.  And this solution does not relate to values coming into the controller via a ui-router resolve.

**Comment by erkez** [comment]
UI-Router `resolve` also works with promises. I don't know what your methods return, but if you are using $resource, returning `AssessmentService.getServices().$promise` would be the correct way.

Well, that is not the scope of this library. You might be facing that issue, because of that `ng-if`. From the documentation (http://materializecss.com/dropdown.html):

    Initialization for dropdowns is only necessary if you create them dynamically. 

Your best bet is to have a directive which takes care of that for you.

**Comment by kmmbvnr** [comment]
Have you try https://github.com/krescruz/angular-materialize ?
