### ISSUE TITLE
Image is not showing Round using class="circle"

### ISSUE THREAD

**Issue by freebumba27** [Dogfalo/materialize#1898]
I am trying to add a image using this class - class="circle"
but In the lower version of Android (bellow KitKat) image are not showing round
any reason for that?

![image](https://cloud.githubusercontent.com/assets/12707934/9218701/375eb662-40f2-11e5-94b9-ac5585fdd832.jpg)

**Comment by DarwinDLRD** [comment]
Place your code here, please

**Comment by freebumba27** [comment]
I took a image with this class only nothing else

**Comment by Dogfalo** [comment]
http://stackoverflow.com/questions/8705249/css-border-radius-not-trimming-image-on-webkit

On Wed, Aug 12, 2015 at 8:54 PM, Bumba <notifications@github.com> wrote:

> I took a image with this class only nothing else
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Dogfalo/materialize/issues/1898#issuecomment-130521949>
> .
>



-- 
Doggy sends his greetings from Mars.

**Comment by freebumba27** [comment]
Not solving the problem

**Comment by freebumba27** [comment]
My code looks like this - 

``` 
<ul id="schoolListGrid" class="list"><li id="1" onclick="loginPage('http://www.polussoftware.com/podium_mobile/images/rainbow.jpg','http://www.d-nuke.com','55')" <a="" href="#"><img style="border-radius: 50%;" src="http://www.polussoftware.com/podium_mobile/images/rainbow.jpg" alt="" class="circle responsive-img circular_schools"><p>Rainbows Montessori</p></li><li id="2" onclick="loginPage('http://www.polussoftware.com/podium_mobile/images/christ_nagar.jpg','http://www.d-nuke.com','55')" <a="" href="#"><img style="border-radius: 50%;" src="http://www.polussoftware.com/podium_mobile/images/christ_nagar.jpg" alt="" class="circle responsive-img circular_schools"><p>Christ Nagar School</p></li><li id="3" onclick="loginPage('http://www.polussoftware.com/podium_mobile/images/christ_nagar_002.jpg','http://qa.podiumglobal.com','0')" <a="" href="#"><img style="border-radius: 50%;" src="http://www.polussoftware.com/podium_mobile/images/christ_nagar_002.jpg" alt="" class="circle responsive-img circular_schools"><p>QA Test</p></li></ul>
```

**Comment by fega** [comment]
Closed due inactivity, feel free to reopen it if it is still necessary.
