### ISSUE TITLE
Feature - Responsive Horizontal scrolling for tab navigation

### ISSUE THREAD

**Issue by jakewhiteley** [Dogfalo/materialize#1899]
The tabs js component is currently not responsive. [http://materializecss.com/tabs.html]

The behaviour should mimic that as described in the spec/image below, and can be seen on a mobile google.com search.

**Current Functionality**
When the screen width is smaller than the minimum width required by the tabs, they squash together and the text overlaps.

**Proposed**
The navbar should retain the minimum width required to display all tabs with padding in a consistent fashion. Overflow should be hidden off screen, and a user should be able to swipe the tabs left/right to scroll through the available tabs.

A scroll indicator (chevron?) should appear on focus, or by default, which indicates to a user that they can scroll. Alternatively - like the image below - the last link can be partially obscured to indicate to a user that the content is obscured.

As indicated in the Material spec, this tab style menu can be used for standard page based navigation as well as toggling tabs on the current page.

https://www.google.co.uk/design/spec/components/tabs.html#tabs-usage
![image](https://cloud.githubusercontent.com/assets/3481634/9220205/9678eeb6-40d8-11e5-8154-d69d22b4ffc6.png)

**Comment by acburst** [comment]
Added in 7e0c265808cb8d6d27cba6555fa081ef94ff86b3
