### ISSUE TITLE
Feature - Dismissible Collections should dispatch event when dismissed

### ISSUE THREAD

**Issue by jakewhiteley** [Dogfalo/materialize#1900]
Dismissible Collections which can be swiped, should trigger an event when the dismiss is completed.

This allows developers to create persistence using this interaction.

The hammer.js `panend` is not suitable for this currently, as it doesn't initially indicate whether the swipe was completed or not.

The index of the collection item should be passed as an argument, but any other information can just be found using event.target.

**Comment by jarodium** [comment]
+1

**Comment by kmmbvnr** [comment]
Duplicate #803
