### ISSUE TITLE
DatePicker not configurable

### ISSUE THREAD

**Issue by kishorpawar** [Dogfalo/materialize#1901]
I tried configuring options available at pickadate.js, but they did not work as said in the document.

I tried directly importing pickadate.js, options did work, but the css then overriden.

Can you please update pickadate.js code, in materialized.master.js?

**Comment by carlosperate** [comment]
The options are working fine as described in the documentation: http://codepen.io/anon/pen/ZGZbNx
Could you provide a codepen illustrating your issue as indicated in the [contributing](https://github.com/Dogfalo/materialize/blob/master/CONTRIBUTING.md) file?

**Comment by kishorpawar** [comment]
I was trying closeOnSelect : true

**Comment by carlosperate** [comment]
That functionality was removed to match Google's date picker implementation: https://github.com/Dogfalo/materialize/issues/870

**Comment by kishorpawar** [comment]
okay, Thanks, Can I override onSet()?

**Comment by carlosperate** [comment]
onSet seems to be working: http://codepen.io/anon/pen/ZGZbNx

**Comment by kishorpawar** [comment]
yeah, I tried in codepen you sent earlier that is working, but the same is
not working in my code.
anyways thanks for the help
you guys really rock.

**Comment by jeromemiranda** [comment]
I have tried a simple hack

onSet: function(data){
     console.log('onSet works', data)
     $('.picker__close').click();
}

onset, I've triggered the close button.
