### ISSUE TITLE
A guide of how to make it work with sass

### ISSUE THREAD

**Issue by SuperDJ** [Dogfalo/materialize#1902]
On the site there is only a very basic guide of how to make sass work http://materializecss.com/getting-started.html. But for the more inexperienced users it might be usefull to have a step by step guide on what to do. Forexample there is only a header saying to compile sass but there is no how to. the same goes for npm and bower.

**Comment by carlosperate** [comment]
If you need to learn how to use sass or npm there are far better resources online to achieve this, that is outside of the scope of the project.
