### ISSUE TITLE
Tabs Issues

### ISSUE THREAD

**Issue by Bana0615** [Dogfalo/materialize#1909]
- I cannot figure out how to change the bottom pink line for an active tab.
- Also there is no responsive feature for tabs becasue when my site gets smaller the tabs do switch from m3 to s6 even though i have it set as a class.

**Comment by AEgan** [comment]
The indication bar uses a class of `.indicator`, applying a `background-color` to that class in your css should change the color for you.

**Comment by Bana0615** [comment]
thank you! for the help with that part of the issue

**Comment by tomscholz** [comment]
You can use scss variables [here](https://github.com/Dogfalo/materialize/blob/master/sass/components/_variables.scss#L33) to customize the colors of materialize
