### ISSUE TITLE
How to get row highlighting on hoverable tables

### ISSUE THREAD

**Issue by brandonSc** [Dogfalo/materialize#1914]
Looking at the example of a hoverable table on here: http://materializecss.com/table.html

When I use the `class="hoverable"` on my table, I only get the drop-shadow around the border of the whole table, and not the grey highlighting on each of the individual rows as the mouse hovers over them. 

Is this a bug, or am I supposed to do something else to get the row highlighting?

**Comment by brandonSc** [comment]
Actually .. I've narrowed the problem down a little further. The rows do not highlight when I populate the table with javascript, but if I already have the data hard-coded in html, then I get the highlighting. 

If this is not a bug, then please let me know how I can work around this issue.

**Comment by uok** [comment]
I don't like the drop shadow around the table so I used simple row highlighting
`tr:hover { background: #f5f5f5; }`

**Comment by schr3j** [comment]
This actually is a bug. The hoverable class is used twice.
Once for the card hover effect which generates the shadow around the table in this case
and second for row highlighting in tables. If you apply this class now, it will apply both effects on tables which is not intended i guess.

**Comment by schr3j** [comment]
This is actually already fixed: 7866e719b60b7f95645b8eed9b26e8331c54d006
Hoverable table rows will be available using the "highlight" class on the the table after the next update.
I guess you could close this issue as there are so many of them and they can't keep up anyways :wink:

**Comment by brandonSc** [comment]
I'm still concerned with the fact that I don't get the row highlighting on rows I add with javascript. For example, I have a table that I have roughly set up in html, and then I populate that table with more data that I get from a `$.get` request. But I'll raise that in a separate issue if it's not fixed by the update :)

**Comment by MikeGraf** [comment]
@brandonSc  Did you ever put in an issue for the rows not being highlighted when added with javascript? 

Thanks,
Mike
