### ISSUE TITLE
ReferenceError: Materialize is not defined when calling Materialize.toast

### ISSUE THREAD

**Issue by salmansqadeer** [Dogfalo/materialize#1915]
Hey guys,

My app is throwing errors in my console, and while the behavior is operating as expected (I am seeing the correct notification appear), the errors are worrysome and I'm wondering if I am doing anything wrong. 

My code:

`
Materialize.toast('Sent Followup Email to Contact', 3000);
`

The error I am seeing:
`
I20150815-00:31:43.130(-4)? Exception while invoking method 'followUpOnTask' ReferenceError: Materialize is not defined
I20150815-00:31:43.130(-4)?   at [object Object].Meteor.methods.followUpOnTask (app/source/tasks-methods.js:146:1)
I20150815-00:31:43.131(-4)?   at maybeAuditArgumentChecks (/Users/salman.suhail/Dropbox/_CODE/meteor/simple-todos/.meteor/local/build/programs/server/packages/ddp.js:2445:12)
I20150815-00:31:43.131(-4)?   at /Users/salman.suhail/Dropbox/_CODE/meteor/simple-todos/.meteor/local/build/programs/server/packages/ddp.js:1476:20
I20150815-00:31:43.132(-4)?   at [object Object]._.extend.withValue (/Users/salman.suhail/Dropbox/_CODE/meteor/simple-todos/.meteor/local/build/programs/server/packages/meteor.js:989:17)
I20150815-00:31:43.132(-4)?   at /Users/salman.suhail/Dropbox/_CODE/meteor/simple-todos/.meteor/local/build/programs/server/packages/ddp.js:1475:41
I20150815-00:31:43.132(-4)?   at [object Object]._.extend.withValue (/Users/salman.suhail/Dropbox/_CODE/meteor/simple-todos/.meteor/local/build/programs/server/packages/meteor.js:989:17)
I20150815-00:31:43.132(-4)?   at [object Object]._.extend.protocol_handlers.method (/Users/salman.suhail/Dropbox/_CODE/meteor/simple-todos/.meteor/local/build/programs/server/packages/ddp.js:1474:51)
I20150815-00:31:43.132(-4)?   at /Users/salman.suhail/Dropbox/_CODE/meteor/simple-todos/.meteor/local/build/programs/server/packages/ddp.js:1374:43
I20150815-00:31:43.133(-4)? 
`

**Comment by Dogfalo** [comment]
sounds like you are on an old build

On Fri, Aug 14, 2015 at 9:33 PM, Salman Suhail <notifications@github.com>
wrote:

> Hey guys,
>
> My app is throwing errors in my console, and while the behavior is
> operating as expected (I am seeing the correct notification appear), the
> errors are worrysome and I'm wondering if I am doing anything wrong.
>
> My code:
>
>
> Materialize.toast('Sent Followup Email to Contact', 3000);
>
> The error I am seeing:
>
> I20150815-00:31:43.130(-4)? Exception while invoking method
> 'followUpOnTask' ReferenceError: Materialize is not defined
> I20150815-00:31:43.130(-4)? at [object
> Object].Meteor.methods.followUpOnTask (app/source/tasks-methods.js:146:1)
> I20150815-00:31:43.131(-4)? at maybeAuditArgumentChecks
> (/Users/salman.suhail/Dropbox/_CODE/meteor/simple-todos/.meteor/local/build/programs/server/packages/ddp.js:2445:12)
> I20150815-00:31:43.131(-4)? at
> /Users/salman.suhail/Dropbox/_CODE/meteor/simple-todos/.meteor/local/build/programs/server/packages/ddp.js:1476:20
> I20150815-00:31:43.132(-4)? at [object Object]._.extend.withValue
> (/Users/salman.suhail/Dropbox/_CODE/meteor/simple-todos/.meteor/local/build/programs/server/packages/meteor.js:989:17)
> I20150815-00:31:43.132(-4)? at
> /Users/salman.suhail/Dropbox/_CODE/meteor/simple-todos/.meteor/local/build/programs/server/packages/ddp.js:1475:41
> I20150815-00:31:43.132(-4)? at [object Object]._.extend.withValue
> (/Users/salman.suhail/Dropbox/_CODE/meteor/simple-todos/.meteor/local/build/programs/server/packages/meteor.js:989:17)
> I20150815-00:31:43.132(-4)? at [object
> Object]._.extend.protocol_handlers.method
> (/Users/salman.suhail/Dropbox/_CODE/meteor/simple-todos/.meteor/local/build/programs/server/packages/ddp.js:1474:51)
> I20150815-00:31:43.132(-4)? at
> /Users/salman.suhail/Dropbox/_CODE/meteor/simple-todos/.meteor/local/build/programs/server/packages/ddp.js:1374:43
> I20150815-00:31:43.133(-4)?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Dogfalo/materialize/issues/1915>.
>



-- 
Doggy sends his greetings from Mars.

**Comment by salmansqadeer** [comment]
No that doesn't seem to be the case, as I am on v0.97.0, which according to github is the latest version available? (Apologies if I am missing something obvious)
