### ISSUE TITLE
resizable side nav + enable interaction on elements in background

### ISSUE THREAD

**Issue by gg4u** [Dogfalo/materialize#1917]
hello guys, nice job!
i looked for this question in your issues, but haven't found:
is it possible to apply a side navigation, disabling the gray layer which is posited between the sidenav and elements in background?
I would like to keep interactivity open/close, but enabling interactivtity with elements in background.
I wonder if a combination of css classes would do the trick.

I would find also extremely useful a dictionary of css classes, so that they can be re-used and I think the community would benefit from it (this is a suggestion).
Thank you!

**Comment by carlosperate** [comment]
You could do the following to hide the overlay:

```
#sidenav-overlay {
  display:none;
}
```

But any click outside the side bar would cause it to close.

**Comment by gg4u** [comment]
Hi and thanks @carlosperate, I also need to enable interaction outside the side bar, without closing it.
How could I do? Should I replicate the component in js and compile a new one? Could you give some guidelines? In jquery ui is possible to have similar behavior with .resize, Id like to use only one framework.

**Comment by Dogfalo** [comment]
@gg4u, right now our showcase site has an example of the sidenav in this state.
