### ISSUE TITLE
Refresh form listeners for new content loaded with ajax

### ISSUE THREAD

**Issue by krzysztof-miemiec** [Dogfalo/materialize#1918]
I use ajax to load page content that contains forms. Unfortunately, Materialize sets file-field listener only when it loads. It would be nice to have function that would again call this part from '/forms.js' file:

```
$('.file-field').each(function() {...});
```

**Comment by epiblue** [comment]
I'm having the same problem, did you manage to find any solution?

**Comment by rs411** [comment]
I copied that function and called it manually. Ugly workaround, but worked...

**Comment by Gskartwii** [comment]
@rs411 Do you mean [forms.js](https://github.com/Dogfalo/materialize/blob/e0bce58c75bf0766ab692cfb9f3025a8c776ac09/js/forms.js)?

**Comment by rs411** [comment]
Yes, but I guess it has been changed since I can't find it right now. Here is the function I mentioned:
```javascript
    // File Input Path
    $('.file-field').each(function() {
      var path_input = $(this).find('input.file-path');
      $(this).find('input[type="file"]').change(function () {
        path_input.val($(this)[0].files[0].name);
        path_input.trigger('change');
      });
    });
```

**Comment by Gskartwii** [comment]
I had to run the whole script myself because, it would not only break file inputs, but text inputs, too.

**Comment by fega** [comment]
It seems to be something like ` Materialize.updateTextFields();`

Closed, feel free to reopen it if it is still necessary.
