### ISSUE TITLE
Custom color of input underline

### ISSUE THREAD

**Issue by zigy** [Dogfalo/materialize#192]
Please can you add custom color of input underline animation to css?
Default is blue... i need orange :yum:

**Comment by Dogfalo** [comment]
Documentation and Sass variables added.

**Comment by RohanAsmat** [comment]
Is there a way to do it programatically ?

**Comment by gauravbankoti** [comment]
Bro its not working

**Comment by greg-mckeon** [comment]
Not sure why, but this works for me:
.input-field textarea[class=materialize-textarea]:focus {
    border-bottom: 1px solid #2196f3;
    box-shadow: 0 1px 0 0 #2196f3;
}

**Comment by shinux** [comment]
i customized the border color  by (lang=pug):

    input[type=text]
      &:focus:not([readonly])
        border-bottom: 1px solid ＃0C8CF6
        box-shadow: 0 1px 0 0 ＃0C8CF6

**Comment by piq9117** [comment]
Theres a guide how to target the input elements. How about the `textarea`? How do I change it?

**Comment by vTrip** [comment]
Is there any update on this ?

**Comment by gauravbankoti** [comment]
you can change underline color by changing CSS of on focus event.

**Comment by vTrip** [comment]
I have done this, except the existing border applied from the mdl is present with the border style I apply

**Comment by mateusbfroemming** [comment]
in: theme/variables.css add this code:

$text-input-md-highlight-color-invalid: transparent;
$text-input-md-highlight-color-valid: transparent;
$text-input-md-show-invalid-highlight: transparent;
$text-input-md-highlight-color: transparent;
$text-input-md-show-valid-highlight: transparent;

but select a color!

**Comment by ray-den** [comment]
try this. its work for me fine:
 
.input-field input:focus + label {
   color: red !important;
 }

 .row .input-field input:focus {
   border-bottom: 1px solid red !important;
   box-shadow: 0 1px 0 0 red !important
 }
