### ISSUE TITLE
Fileinput with wrong css

### ISSUE THREAD

**Issue by MusikDK** [Dogfalo/materialize#1922]
The button are displayed beneath the line when using the CDN version of Materialize (CSS+JS).
I've added no custom css, but still on both occasions it positions itself wrong: 
http://www.cphrecmedia.dk/musikdk/admin/Backend-template.html

**Comment by carlosperate** [comment]
The documentation hasn't been updated yet on the website (it is on master), but the file input should be implemented as:

```HTML
  <form action="#">
    <div class="file-field input-field">
      <div class="btn">
        <span>File</span>
        <input type="file">
      </div>
      <div class="file-path-wrapper">
        <input class="file-path validate" type="text">
      </div>
    </div>
  </form>
```

**Comment by MusikDK** [comment]
@carlosperate Thanks!
