### ISSUE TITLE
The character counter span is displayed twice.

### ISSUE THREAD

**Issue by harrinsonmb** [Dogfalo/materialize#1923]
There is an error with the funcionality **characterCounter()**, the label is displayed twice.

Here is an example of what I'm talking about:
https://jsfiddle.net/g90b8qn7/

**Comment by carlosperate** [comment]
As described in http://materializecss.com/forms.html#character-counter , you only need to add the javascript initialisation if adding the input dynamically. So, it will work correctly if you remove the manual `$('input#input_text, textarea#textarea1').characterCounter();`.

**Comment by harrinsonmb** [comment]
¡oh, you're right!
I'm sorry :9

**Comment by alexwasik** [comment]
I don't have the js initialized but span is showing 3x. Below is the only reference to the character counter. I DO have a validation in my model, but this shouldn't cause the js to show 3x.
 ```= f.text_field :text, length: 120```
