### ISSUE TITLE
Feature Query

### ISSUE THREAD

**Issue by Saumik** [Dogfalo/materialize#1925]
I know Materialize.css has a swipe left to dismiss the open sidemenu option but is an implementation available for opening the menu on swiping right as found in most android phones. I have a meteorjs implementation for a android app and would want to know, is such a feature offered out of the box. If not, resources/samples or compatible library would be deeply appreciated.

**Comment by carlosperate** [comment]
Swipe to open is a supported feature: http://materializecss.com/mobile.html
