### ISSUE TITLE
[proposal] Reactive DOM components with no manual init?

### ISSUE THREAD

**Issue by Jabher** [Dogfalo/materialize#1928]
Hi, I see you have elements that are loaded manually, and a special trigger on document load.

> ...elements only need initialization if they are added dynamically.

I think it can be improved dramatically as far as css frameworks are supposed to be used by as wide group of people as possible and requirement of "you need to execute js code to load something after page load..." can bring the complexity to a lot of people.

I've made an extremely tiny (3.5k + 2.5k overhead for ie9-10) library named [corner.js](https://github.com/Jabher/cornerjs) about a year ago and only now I realize that looks like it super-fits any frontend framework, including materialize.

It's utilizing single MutationObserver (with fallback to Mutation Events for ie 9-10), is showing good performance and is really simple.

for now syntax is 

``` javascript
directive('collapsible', {
    load: function (node, arguments) { /*element attached to DOM or target class/attribute added to element callback*/ },
    unload: function (node, arguments) { /*element removed from DOM or target class/attribute removed from element callback*/ },
    alter: function (node, arguments) { /*target attribute value has been changed*/ }
})
```

It can really simplify the usage of materialize for many people as far they will just think about `$(element).html(html)` instead of `$(element).html(html); initAllTheComponents()` every time. I experienced the pain of DOM change with forgetting you have a widget to init/destroy a lot of times.

If you would like to I would help you to integrate it in Materialize in a simple way.

**Comment by fega** [comment]
What if you creates a very tiny subversion or example of how implement it in materialize? I guess that it could be added to the wiki.
Closed due inactivity, feel free to reopen it if it is still necessary.
