### ISSUE TITLE
Font icons are not lining up with text

### ISSUE THREAD

**Issue by SuperDJ** [Dogfalo/materialize#1929]
I have a couple of font icons that are not lining up with the text. 
A few examples: 
![naamloos](https://cloud.githubusercontent.com/assets/6484766/9326347/4d65dd86-4599-11e5-98f5-32dc52394a39.png)
and:
![knipsel](https://cloud.githubusercontent.com/assets/6484766/9326346/4d62c65a-4599-11e5-8151-d1fdac79ce69.PNG)

I don't add extra styling to the buttons except for the classes that come from materialize.css.

**Comment by uok** [comment]
if you use icons on buttons, make sure to add the `left` class to the `<i>` element
see http://materializecss.com/buttons.html

**Comment by SuperDJ** [comment]
This is partially fixing the problem
