### ISSUE TITLE
Request: Move Toast notifications to top

### ISSUE THREAD

**Issue by ffxsam** [Dogfalo/materialize#1932]
On the iPhone, the very bottom part of the Safari window is reserved to tap in order to call up the bottom row of buttons. Toast swipes do not work in this zone.

**Comment by tomscholz** [comment]
There is [this](https://www.eventbrite.com/engineering/mobile-safari-why/) great article which explains, what the issue is here.

**Comment by Dogfalo** [comment]
We wont be changing this as this is how notifications are specified by Material Design, however, you can simply push up the `#toast-container` slightly from the bottom if you are affected by this issue on iOS
