### ISSUE TITLE
Validation is not working on select

### ISSUE THREAD

**Issue by Alihaiderkhokher** [Dogfalo/materialize#1933]
I am using jquery validation its working fine on textboxes but not working on select. 
here is screenshot. 
![image](https://cloud.githubusercontent.com/assets/13864111/9349529/e0c312c0-4660-11e5-9eb1-2dcfb04e365d.png)

**Comment by carlosperate** [comment]
Complex validation not provided by the HTML has been left out of the scope of this project: https://github.com/Dogfalo/materialize/issues/1454

**Comment by boustanihani** [comment]
Why not simply provide **Custom Error & Success Messages** using the ```data-error``` and ```data-success``` label attributes for selects too... ?? Is this really complex?

**Comment by Dogfalo** [comment]
Because there is no html5 validation for selects.

**Comment by jvadillo** [comment]
I have the same problem, ¿Did you find any solution?

**Comment by lucasbarrossantos** [comment]
Tenho o mesmo problema, uma solução foi adicionar:

    $("select[required]").css({position: 'absolute', display: 'inline', height: 0, padding: 0, width: 0});

**Comment by tomscholz** [comment]
I don't speak Spanish. Sorry.

**Comment by lucasbarrossantos** [comment]
I have the same problem, one solution was to add:
$(document).ready(function() {
$('select').material_select();
$("select[required]").css({position: 'absolute', display: 'inline', height: 0, padding: 0, width: 0});
});

**Comment by findsarfaraz** [comment]
$("select[required]").css({position: 'absolute', display: 'inline', height: 0, padding: 0, width: 0});
});
This seems to work find...but is there any chances of added in future versions. I am using 1.0.0.
Also I thought it would be able to use this as out of box feature.
