### ISSUE TITLE
Tabs overlap others and coming out of the container in mobile device

### ISSUE THREAD

**Issue by rjsaci** [Dogfalo/materialize#1935]
Tabs overlap others and coming out of the container in mobile device.
![as](https://cloud.githubusercontent.com/assets/12507228/9357184/1f8a577e-46a3-11e5-9248-1467215f3af7.png)

**Comment by lukeclewlow** [comment]
Any fix for this?

**Comment by Pete-Tyldesley** [comment]
Also looking for a fix for this!

**Comment by 91Abdullah** [comment]
Badly looking for fix!

**Comment by acburst** [comment]
Gonna look into tabs for the next release. Probably add some form of overflow for this problem or maybe implement horizontal scrolling for tabs.

**Comment by acburst** [comment]
Fixed in 7e0c265808cb8d6d27cba6555fa081ef94ff86b3
