### ISSUE TITLE
<i> tag gets added around submit button

### ISSUE THREAD

**Issue by Thermatix** [Dogfalo/materialize#1938]
I have an input that should look like this:

``` html
<input type="submit" value="Login" class=" waves-button-input waves-effect waves-light btn waves-input-wrapper waves-input-wrapper" data-reactid=".0.0.1.2.0">
```

instead it comes out like this:

``` html
<i class="waves-effect waves-light btn waves-input-wrapper waves-input-wrapper" style="">
    <input type="submit" value="Login" class="waves-button-input" data-reactid=".0.0.1.2.0">
</i>
```

I have to use Jquery to make it look like the sample at the top.

I'm sure it's a bug with materialize because if I remove all the materialize js files the problem goes away, specifically if I remove `materialize.js` it goes away (of course nothing else works though).

EDIT: I'm using v0.96.1, I will update to the latest version first.

EDIT: just updated to v0.97 and no change.

EDIT: I noticed something weird, when I removed my fix, and then click on the form submit button, this oddity goes away for subsequent re-renders of the page.

**Comment by Willibaur** [comment]
You have duplicated the call of `waves-input-wrapper` class
