### ISSUE TITLE
How to dynamically create modal?

### ISSUE THREAD

**Issue by tdhz77** [Dogfalo/materialize#1940]
I'm using meteor and have a render function 
    Template.uploads.onRendered(function() {
    $('.modal-trigger').leanModal();
});

How do I pass the .modal-trigger id of the dynamic content? eg) Is there a src attribute in leanModal? or do how do I dynamically change line 2 based off context?

**Comment by Dogfalo** [comment]
the .modal-trigger needs to be replaced with something more specific if you want to init only one. Our modal documentation is pretty extensive, please take a look there.
