### ISSUE TITLE
Possible customization options?

### ISSUE THREAD

**Issue by zocheyado** [Dogfalo/materialize#1941]
So I have been using materialize for a while and I love it but I like bootstraps grid system much more. Bootstrap has an option to chose which parts of the framework you would like to compile. So for some projects I just need materalize - cards, some projects I need the whole thing etc. Is this possible without going through the css and removing all the portions I do not want?

**Comment by acburst** [comment]
If you download the sass version, then our components are separated into individual scss files

**Comment by SuperDJ** [comment]
In the materialize.scss there is a list of all components. You can comment them out
