### ISSUE TITLE
Why tabs content is visible always

### ISSUE THREAD

**Issue by AsMoh** [Dogfalo/materialize#1942]
Hi,

I was trying to test how can I create tabs using materialize, and I was testing this code

     <div class="row">
    <div class="col s12">
      <ul class="tabs">
        <li class="tab col s3"><a href="#test1">Test 1 </a></li>
        <li class="tab col s3"><a class="active" href="#test2">Test 2</a></li>
        <li class="tab col s3"><a href="#test3">Test 3</a></li>
        <li class="tab col s3"><a href="#test4">Test 4</a></li>
      </ul>
    </div>

    <div id="test1" class="col s12">Test 1</div>
    <div id="test2" class="col s12">Test 2</div>
    <div id="test3" class="col s12">Test 3</div>
    <div id="test4" class="col s12">Test 4</div>
    </div>

The problem is that the content of all divs is always visible as shown in the following figure
![errormaterialize](https://cloud.githubusercontent.com/assets/10277729/9375792/22cfe99e-4716-11e5-9311-674ef2f32ccb.jpg)

I did intialize the tabs   with this line         $('ul.tabs').tabs();

Can you help me to know why am I getting this weird output? Thank you in advance.

**Comment by carlosperate** [comment]
It seems to be working fine (I only did a copy and paste): http://codepen.io/anon/pen/JdQbXP
Could you provide more information about your setup or a codepen illustrating the issue?

**Comment by AsMoh** [comment]
When I include it in my project, I got this output.
Here is the link for my project...
https://drive.google.com/file/d/0B2NyxfyoVjxcV2ZISUt6bWxQc0U/view?usp=sharing


I am also using jquery-ui at the same project..

Thank you in advance..

**Comment by AsMoh** [comment]
Please, help me to figure out why the tabs are not working in my project. I spent the whole day trying to solve the problem.

**Comment by Dogfalo** [comment]
It's probably a jQuery ui conflict.

**Comment by AsMoh** [comment]
Do you have any idea how to solve this conflict?

**Comment by macsupport** [comment]
It is not a materialize issue but  is a conflict with jqueryui tabs. If you add jqueryui to the codepen by @carlosperate, you can see your issue. If you need jqueryui, just build it without tabs included.

**Comment by AsMoh** [comment]
Sorry I did not get you .. How to build the jqueryui without tabs?

**Comment by AsMoh** [comment]
Thank you so much...

**Comment by vincentcox** [comment]
THANK YOU SO MUCH!
It was indeed a jqueryui issue. Was looking for this the last half hour...
