### ISSUE TITLE
Swipe tabs

### ISSUE THREAD

**Issue by rotoxl** [Dogfalo/materialize#1943]
It would be helplful to reduce the native-hybrid gap if tabs were swipable (to get to next/prev tab page)

![Sample](http://4.bp.blogspot.com/-hq8Ypacwllc/VMDofifOVYI/AAAAAAAAAv8/-fFxUk5qOIo/s1600/bloggif_54c0e8476d484.gif)

**Comment by bkuri** [comment]
+1 this would be really nice to have.

**Comment by Zaanmedia** [comment]
+1

**Comment by MoeBadr** [comment]
+1

**Comment by seanfrasure** [comment]
+1

**Comment by baraamashaal** [comment]
+1

**Comment by Cedriking** [comment]
I've shown a demo of an app I'm working on to some friends, and they all thought they could swipe to the next page because this is a core feature of the Android apps. +1

**Comment by listepo** [comment]
+1

**Comment by jaiswalabhinav17** [comment]
Do we have any third party tool or any jQuery plugin that we can club and use with material design for swiping within the tabs  ? ?

**Comment by MoeBadr** [comment]
@jaiswalabhinav17  checkout http://hammerjs.github.io/

**Comment by T-bond** [comment]
So, wasn't this added to the v0.97.6 or just the changelog misses it? I would like this future too.
+1

**Comment by rubenlpz** [comment]
There isn't sliding tabs yet?

**Comment by proudUzbek** [comment]
Any news?

**Comment by matthenning** [comment]
Any news yet if I may ask?

**Comment by rotoxl** [comment]
Uoh! Can't wait to test it 😍
