### ISSUE TITLE
Materialize and Meteor: not seeing any materialize functions on `$.fn`

### ISSUE THREAD

**Issue by AlexFrazer** [Dogfalo/materialize#1946]
Here's the code that gave me issues.

```
Template['Layout'].onRendered(function () {
  $('.dropdown-user-menu').dropdown({});
});
```

It says that `$().dropdown` is not defined. I checked `$.fn` and `dropdown` is indeed not defined. It doesn't seem to show up in the `Materialize` object either.

Some versioning information:

```
$ meteor list | grep materialize
materialize:materialize             0.97.0  Materialize (official): A modern ...
useraccounts:materialize            1.12.2  Accounts Templates styled for Mat...
```

early warning: I might not be using it right.

**Comment by dgrijuela** [comment]
Hi Alex,

Maybe you are not getting the element correctly.

Try this and see if returns undefined or the element you want:
```
Template['Layout'].onRendered(function () {
  console.log($('.dropdown-user-menu'));
});
```

**Comment by AlexFrazer** [comment]
I have confirmed that it is selecting an element. The autocomplete on a jQuery object does not contain `dropdown`, either. Here is some console output to show.

![alt-text](https://i.imgur.com/h18Hktg.png)

**Comment by Blahah** [comment]
The selection is actually returning an array of elements (because you used a class selector), so you want to take the first result:

```js
Template['Layout'].onRendered(function () {
  $('.dropdown-user-menu')[0].dropdown({});
});
```

**Comment by AlexFrazer** [comment]
Same result.

**Comment by dgrijuela** [comment]
I guess you're using the official package. Try removing it and installing [this one](https://atmospherejs.com/poetic/materialize-scss).

**Comment by Dogfalo** [comment]
I believe this is fixed, @AlexFrazer can you confirm?
