### ISSUE TITLE
'constrain_width' option in dropdown.js doesn't follow the naming convention

### ISSUE THREAD

**Issue by bashmach** [Dogfalo/materialize#1948]
Hey!

Just wondering why constrain_width option does not follow camelCase naming convention like other options there ([js/dropdown.js](https://github.com/Dogfalo/materialize/blob/master/js/dropdown.js#L10)).

I use this plugin via [ember-cli-materialize](https://github.com/mike-north/ember-cli-materialize) and found this [difference](https://github.com/mike-north/ember-cli-materialize/blob/master/addon/components/md-btn-dropdown.js#L28), but unable to fix it there because of `requireCamelCaseOrUpperCaseIdentifiers` [jscs rule](http://jscs.info/rule/requireCamelCaseOrUpperCaseIdentifiers.html).

Furthermore, I found reference about 'camelCase' variant in [documentation](https://github.com/Dogfalo/materialize/blob/master/dropdown.html#L154).

**Comment by carlosperate** [comment]
It looks like https://github.com/Dogfalo/materialize/commit/3201bee3772fdaec89ef4421594466472f162674 was one of the first options added, and the other camel case options were included afterwards. Either way, updating this would be a breaking change, which is worse than maintaining an inconsistency, so the documentation should be updated to replace constrainWidth with a better description of the option.

**Comment by bashmach** [comment]
Ok, I understand
Is there any chance to let me provide now a support for both variants and remove inconsistence option in the future (major?) release?

**Comment by acburst** [comment]
Fixed in 66d37f0
