### ISSUE TITLE
color helpers for hover states

### ISSUE THREAD

**Issue by krisalexander** [Dogfalo/materialize#1951]
I'm not sure if it is possible, I haven't worked it out. But on several occasions already since using materialize, i've naturally went to go set a hover state color using color helpers, but there aren't any.

**Comment by carlosperate** [comment]
Could you specify what you mean by "hover state color"? Are you refering to the [shadows](http://materializecss.com/shadow.html), [hoverable table](http://materializecss.com/table.html), or something else?

**Comment by Dogfalo** [comment]
There are too many variations of this to handle, background-color, box-shadow for :hover :active styles. Its best to just make your own small utility class that has the exact color/opacity you want
