### ISSUE TITLE
Sticky Footer in Safari 8 is not working

### ISSUE THREAD

**Issue by harshveers** [Dogfalo/materialize#1952]
Stickey footer in Safari 8(Version 8.0.2 (10600.2.5)) is not sticking to bottom of viewport when content is little on page.
Page structure:

    <body>
    <main>
        ...
    </main>
    <footer class="page-footer">
        <div class="footer-copyright">
            <div class="container">
               © 2015 Copyright Test
               <a class="grey-text text-lighten-4 right" href="#!">Some Link</a>
            </div>
        </div>
       </footer>
    </body>

CSS:

    body {
    	display: flex;
    	min-height: 100vh;
    	flex-direction: column;
    }
    
    main {
    	flex: 1 0 auto;
    }

Looks like min-height: 100vh is somehow causing the problem, if I remove it, it works fine in Safari but breaks in other browsers.

**Comment by concept-core** [comment]
does this help you  ?
http://ryanfait.com/sticky-footer/

**Comment by RicPlan** [comment]
Hi,

I solved it with this:

body {  
    display: -webkit-flex;
    display: flex;
    min-height: 100vh;    
    -webkit-flex-direction: column;
    flex-direction: column;
  }

  main {
    -webkit-flex: 1 0 auto;
    flex: 1 0 auto;
  }

Cheers
