### ISSUE TITLE
File input button not correctly working with multiple files

### ISSUE THREAD

**Issue by SuperDJ** [Dogfalo/materialize#1953]
When I make a input file that allows multiple files. The text field will only show the last file added. I would like to see that all files are shown. Or at least files for the length of the input. So if there are so many files added that it would go outside the text field it would result in dots.

              <div class="row">
                      <div class="file-field input-field">
		           <input type="text" class="file-path">
		             <div class="btn">
			             <span>File</span>
		                     <input type="file" name="files[]" multiple>
		         </div>
	         </div>
         </div>

**Comment by carlosperate** [comment]
This has been fixed after the v.0.97.0 release: https://github.com/Dogfalo/materialize/pull/1654
If you need the fix before the next version is released you can use the version from https://github.com/Dogfalo/materialize/tree/master/bin
