### ISSUE TITLE
Circular reveal transition/animation

### ISSUE THREAD

**Issue by mammuth** [Dogfalo/materialize#1955]
Card with reveals (http://materializecss.com/cards.html#reveal) should use the more material-like circular reveal transition like in this example in Googles MD guidelines: 
https://material-design.storage.googleapis.com/publish/material_v_4/material_ext_publish/0B3T7oTWa3HiFZ3BiM1dnR0ZPU1k/animation_meanigfultrans_visualcont.webm
or here: 
https://material-design.storage.googleapis.com/publish/material_v_4/material_ext_publish/0B08MbvYZK1iNT2dLWHE1NG8tV00/animation-meaningfultransitions-consistentchoreography-do1_large_xhdpi.webm

**Comment by Dogfalo** [comment]
The card reveal we do is exactly how it is done on https://www.android.com/wear/ under the "Choose your watch" section. I do not see a problem with it.

**Comment by mammuth** [comment]
Well we probably both know how inconsistent Google is in following its own design guidelines across their products.

Of course there is no problem with the current transition; it just can be improved drastically.
