### ISSUE TITLE
Multiple modal hide those below

### ISSUE THREAD

**Issue by damianopetrungaro** [Dogfalo/materialize#1956]
When i open multiple modal via leanModal()
it show the modal clicked, then if i want to show another modal while the first is open
if the first modal is wrote before the second one, this will not be shawn...
There's a fix for close all the modals, then open the clicked one?

**Comment by carlosperate** [comment]
Multiple modals can coexist "on top" of each other, there is an issue about opening the same modal several times, but there is a pull request that should be able to solve that.
Unless I not understood your problem correctly, what you are describing should be working. Could you provide a codepen illustrating the issue, as it is described in the [contributing](https://github.com/Dogfalo/materialize/blob/master/CONTRIBUTING.md) file?
