### ISSUE TITLE
Error: Failed to decode downloaded font

### ISSUE THREAD

**Issue by krisalexander** [Dogfalo/materialize#1957]
When I run the page in production mode (combined, and minified), I get a repeating console warning that looks like this:

Failed to decode downloaded font: http://localhost:9000/font/roboto/Roboto-Light.woff
localhost/:1 Failed to decode downloaded font: http://localhost:9000/font/roboto/Roboto-Light.ttf
localhost/:1 Failed to decode downloaded font: http://localhost:9000/font/roboto/Roboto-Regular.woff2
localhost/:1 Failed to decode downloaded font: http://localhost:9000/font/roboto/Roboto-Regular.woff
localhost/:1 Failed to decode downloaded font: http://localhost:9000/font/roboto/Roboto-Regular.ttf
localhost/:1 Failed to decode downloaded font: http://localhost:9000/font/roboto/Roboto-Thin.woff2
localhost/:1 Failed to decode downloaded font: http://localhost:9000/font/roboto/Roboto-Thin.woff
localhost/:1 Failed to decode downloaded font: http://localhost:9000/font/roboto/Roboto-Thin.ttf
localhost/:1 Failed to decode downloaded font: http://localhost:9000/font/roboto/Roboto-Light.woff2
localhost/:1 Failed to decode downloaded font: http://localhost:9000/font/roboto/Roboto-Light.woff
localhost/:1 Failed to decode downloaded font: http://localhost:9000/font/roboto/Roboto-Light.ttf
localhost/:1 Failed to decode downloaded font: http://localhost:9000/font/roboto/Roboto-Regular.woff2
localhost/:1 Failed to decode downloaded font: http://localhost:9000/font/roboto/Roboto-Regular.woff
localhost/:1 Failed to decode downloaded font: http://localhost:9000/font/roboto/Roboto-Regular.ttf
localhost/:1 Failed to decode downloaded font: http://localhost:9000/font/roboto/Roboto-Thin.woff2
localhost/:1 Failed to decode downloaded font: http://localhost:9000/font/roboto/Roboto-Thin.woff
localhost/:1 Failed to decode downloaded font: http://localhost:9000/font/roboto/Roboto-Thin.ttf
localhost/:1 Failed to decode downloaded font: http://localhost:9000/font/roboto/Roboto-Light.woff2
localhost/:1 Failed to decode downloaded font: http://localhost:9000/font/roboto/Roboto-Light.woff
localhost/:1 Failed to decode downloaded font: http://localhost:9000/font/roboto/Roboto-Light.ttf
localhost/:1 Failed to decode downloaded font: http://localhost:9000/font/roboto/Roboto-Regular.woff2
localhost/:1 Failed to decode downloaded font: http://localhost:9000/font/roboto/Roboto-Regular.woff
localhost/:1 Failed to decode downloaded font: http://localhost:9000/font/roboto/Roboto-Regular.ttf
localhost/:1 Failed to decode downloaded font: http://localhost:9000/font/roboto/Roboto-Thin.woff2
localhost/:1 Failed to decode downloaded font: http://localhost:9000/font/roboto/Roboto-Thin.woff
localhost/:1 Failed to decode downloaded font: http://localhost:9000/font/roboto/Roboto-Thin.ttf
localhost/:1 Failed to decode downloaded font: http://localhost:9000/font/roboto/Roboto-Light.woff2
localhost/:1 Failed to decode downloaded font: http://localhost:9000/font/roboto/Roboto-Light.woff
localhost/:1 Failed to decode downloaded font: http://localhost:9000/font/roboto/Roboto-Light.ttf
localhost/:1 Failed to decode downloaded font: http://localhost:9000/font/roboto/Roboto-Regular.woff2
localhost/:1 Failed to decode downloaded font: http://localhost:9000/font/roboto/Roboto-Regular.woff
localhost/:1 Failed to decode downloaded font: http://localhost:9000/font/roboto/Roboto-Regular.ttf

**Comment by carlosperate** [comment]
Are you sure the fonts are accessible from http://localhost:9000/font/roboto/ ?

**Comment by siriniok** [comment]
I have the same problem. I'm use Rails and Ember CLI. I'm able to open all fonts in chrome resource panel, so they are accessible.

**Comment by siriniok** [comment]
I just add next mime types to my Rails config/mime-types.rb and the problem went away.
Mime::Type.register 'application/x-font-woff', :woff
Mime::Type.register 'application/font-woff2', :woff2
Mime::Type.register 'application/x-font-ttf', :ttf

**Comment by siriniok** [comment]
I think this issue should be closed because it is absolutely not related to materialize.

**Comment by carlosperate** [comment]
Closing this as we haven't heard back from @krisalexander and @siriniok's issue has been resolved.

@krisalexander you can comment again here to reopen the issue if necessary.
