### ISSUE TITLE
Replacing normalize by sanitize

### ISSUE THREAD

**Issue by danielzilli** [Dogfalo/materialize#1961]
Since Materialize only support IE10+ and other modern browsers,  you can move away from normalize and use a more updated methodology to makes browsers render elements consistently and allows you to style with today’s best practices out-of-the-box. For that, replacing normalize by sanitize https://10up.github.io/sanitize.css/ seems to be a right move.

**Comment by Dogfalo** [comment]
This could cause some problems in the framework and isn't really worth the time to swap out normalize
