### ISSUE TITLE
Floating button hover bug

### ISSUE THREAD

**Issue by Flaburgan** [Dogfalo/materialize#1962]
You can reproduce this behavior with the floating button at the bottom right of the [doc pages](http://materializecss.com/buttons.html).

The buttons contained inside the floating button are showing even if we hover **above** the button and not on it. The elements are there, they are just not displayed (hidden using `opacity`). That means that the area above the floating btn is not clickable (because when you point there, the floating buttons appear, making you unable to click on the content **under** it).

**Comment by carlosperate** [comment]
This is the current behaviour that Google uses: https://github.com/Dogfalo/materialize/issues/729
