### ISSUE TITLE
Navbar "mobile collapse button" not responsive

### ISSUE THREAD

**Issue by desiby** [Dogfalo/materialize#1963]
The mobile collapse button in http://materializecss.com/navbar.html is not behaving as expected. Whenever I resize my window or in mobile view the sidenav doesn't show up in my app. I used the example, and initialized the javascript. Works fine in the browser but the "hamburger" button doesn't work upon resizing the window. PLEASE HELP! REALLY LIKE THIS FRAMEWORK

**Comment by carlosperate** [comment]
Please provide a codepen illustrating your issue as indicated in the [contributing](https://github.com/Dogfalo/materialize/blob/master/CONTRIBUTING.md) file.

**Comment by desiby** [comment]
Never mind I fixed the  problem (had to include the script in my html page before the end of the </body> instead of having it sit there in the application.js file (I'm using Ruby on Rails)
thanks and my bad
