### ISSUE TITLE
Question: Howto make a "Select" Invalid

### ISSUE THREAD

**Issue by boustanihani** [Dogfalo/materialize#1965]
Could you please reopen issue https://github.com/Dogfalo/materialize/issues/1454 for further discussion, or maybe leave some comment on my last 2 posts?

**Comment by Dogfalo** [comment]
There is nothing about valid styling for selects stated in Material Design, if you want to add something that is up to you, but we will not be adding it for now

**Comment by boustanihani** [comment]
You seem to offer **Custom Error & Success Messages** for text inputs using the ```data-error``` and ```data-success``` label attributes... Could this also apply to selects??
