### ISSUE TITLE
Forms issue on Mac OS X Safari

### ISSUE THREAD

**Issue by DarkmatterVale** [Dogfalo/materialize#1967]
I am having an issue with displaying a form on safari. For some reason, when you select the fields within the form, the name of the field which is usually contained within the field, does not move. This causes the text that the user inputs to be written under the name of the text, like in the below image.

![screen shot 2015-08-27 at 10 01 39 am](https://cloud.githubusercontent.com/assets/6094957/9522404/aa41c80c-4ca2-11e5-9246-060641ef3636.png)

When a field is selected but no text is entered, the form looks like the following:

![screen shot 2015-08-27 at 9 43 09 am](https://cloud.githubusercontent.com/assets/6094957/9522297/14692802-4ca2-11e5-97aa-af931b5691e1.png)

I know that this is not like what the form is supposed to look like. When I test the form code in Codepen, however, it seems to work fine. The link to the codepin is below.

http://codepen.io/anon/pen/JYPEVW

Does anyone know why this is happening?

**Comment by Dogfalo** [comment]
Check your id's and make sure they match in the HTML

**Comment by DarkmatterVale** [comment]
I just double checked and all of them match in the HTML.

**Comment by DarkmatterVale** [comment]
I figured out the problem. I did not load jQuery before materialize.js, causing the webpage to break.

Thanks for the help!
