### ISSUE TITLE
Slider images not responsive 

### ISSUE THREAD

**Issue by clinton2111** [Dogfalo/materialize#1970]
The slider works perfectly for desktop views but the only problem im facing is that,when viewing my site on a mobile device the images in the slider don't re size to the size of the screen. Any workaround?

**Comment by Guhogu** [comment]
I have the same problem, is there a way for the slider to preserve aspect ratio on mobile?

**Comment by rockstarwebdesign** [comment]
Is this still on review? : s

**Comment by fega** [comment]
I cannot reproduce it
It is still an issue?  What was the browser?

Closed due inactivity, feel free to reopen it if it is still necessary.
