### ISSUE TITLE
Picker function is not defined 

### ISSUE THREAD

**Issue by Saajan** [Dogfalo/materialize#1976]
I have a grunt task which will concat all the js files in materializecss folder. As there are 2 files in the date_picker folder , picker.date.js which is dependent on picker.js . Whenever concatenation of the js takes place picker.date.js is added at the top and picker.js next. So this throws the error.

**Comment by Dogfalo** [comment]
Take a look at https://github.com/Dogfalo/materialize/blob/master/Gruntfile.js to see how to concat the js files

**Comment by Saajan** [comment]
Thanks .. that was helpful
