### ISSUE TITLE
file-path-wrapper does not working

### ISSUE THREAD

**Issue by NetanelBasal** [Dogfalo/materialize#1977]
I copied your example from the file upload section:

```html
   <div class="file-field input-field">
         <div class="btn orange">
            <span>File</span>
             <input type="file">
           </div>
                <div class="file-path-wrapper">
                     <input class="file-path validate valid" type="text">
                 </div>
    </div>
```
But when i am choosing file the name does not appear in the file-path-wrapper input and the line is not green like in your demo. when i am missing?

**Comment by Dogfalo** [comment]
Worked for me, I removed the valid class which you should not be adding directly http://codepen.io/Dogfalo/pen/BoaNKN

**Comment by NetanelBasal** [comment]
What trigger the valid class to be added? javascript?

**Comment by phamlehieu** [comment]
I'm using meteor with materialize 0.97.0 and got the same issue with the file-path-wrapper.

**Comment by rijk** [comment]
Here's the code responsible for setting the path: https://github.com/Dogfalo/materialize/blob/master/js/forms.js#L161-L172. My guess is the event handler is not triggered in Meteor.

**Comment by rijk** [comment]
This is the code I added to do it manually (Coffeescript, sorry):

```
Template.File.events
	'change input[type="file"]': ( e, t ) ->
		pathEl = t.$( e.target ).closest( '.file-field' ).find( 'input.file-path' )
		pathEl.val _.pluck( e.target.files, 'name' ).join ', '
```
