### ISSUE TITLE
Dropdown exceeded outside a wrapper card

### ISSUE THREAD

**Issue by ido567** [Dogfalo/materialize#1978]
I'm using this code to locate a dropdown on the bottom right side of a card:
```html
<div class="row right">
    <!-- Dropdown Trigger -->
    <a class='dropdown-button' href='#' data-alignment="left" data-hover="true" data-activates='item-actions-1'>
        <i class="material-icons right">more_vert</i>
    </a>

    <!-- Dropdown Structure -->
    <ul id='item-actions-1' class='dropdown-content'>
    <li><a href="#!">one</a></li>
        <li><a href="#!">two</a></li>
        <li><a href="#!">three</a></li>
    </ul>
</div>
```

My problem is that the dropdown is located outside of the card, so it's not visible
There is a way to force the dropdown to be opened upside-left?

This is my full code:
http://codepen.io/anon/pen/rONNoN

**Comment by dloewen** [comment]
Looks like the place to change it is around line 506 of materialize.js. Instead of setting the 'left' CSS, it could work if it was 'right' and the calculation changed to reflect that.

```
  // Position dropdown
  activates.css({
    position: 'absolute',
    top: origin.position().top + offset,
    left: origin.position().left + width_difference + gutter_spacing
  });
```

**Comment by ido567** [comment]
I don't want to change things on an external library, because I won't be able to update the library in the future.
If there is no way to implement it, I think it's good suggestion for the next version.

**Comment by acburst** [comment]
Added alignment option in 74775453f6a755bc421172eeb89987660c9b1575
