### ISSUE TITLE
Lean Overlay Z-Index

### ISSUE THREAD

**Issue by klombomb** [Dogfalo/materialize#1982]
Wen the Modal is clicked (anywhere inside the modal) the a new lean overlay is created with a Z-index of 1004. This causes the modal to stop working and makes it act as if underneath the lean overlay.

**Comment by klombomb** [comment]
I have but it isn't working as expected.
http://codepen.io/KingK/pen/avbmPV

**Comment by carlosperate** [comment]
If you are not injecting the modal dynamically there is no need to initialise it twice: http://codepen.io/anon/pen/LpYyEB

**Comment by ManuelRiveraC** [comment]
Sorry but I don't understand How to initialise a modal if there is no trigger?

**Comment by klombomb** [comment]
The modal has its own API. You can simply call.
```javascript
$('#my_modal').openModal();
```
You can find the full docs here, the JS code is located at the bottom of the page:http://materializecss.com/modals.html

**Comment by tdotholla** [comment]
Even when i call it with 
`$('#my_modal').openModal();`
I still get a high z-index on the element's inline style of 1002 
and imported stylesheet specifying a z-index on '.lean-modal' of -999

**Comment by narkissbv** [comment]
`$('#my_modal').openModa();` is deprecated, and now (version 0.100.2) opened like so: `$('#my_modal').modal('open');` and closed similarly: `$('#my_modal').modal('close');`.

**Comment by shahishasank** [comment]
I was using div of modal structure inside nav tag which causes this issue
