### ISSUE TITLE
Fixed Action Button Reveal Direction

### ISSUE THREAD

**Issue by reesebiz** [Dogfalo/materialize#1983]
For the Fixed Action Button is it possible to change the direction the list items reveal? Currently it only reveals in the UP direction. I'm looking for a way to reveal the items downwards. 

It would look something like this:
![](http://puu.sh/jVeKM/6ad354afc6.png)

**Comment by acburst** [comment]
Maybe we can also add horizontal directions if that's desired

**Comment by Dogfalo** [comment]
Added in 3151c17d8825d6eabe8c0c9763abdcbf8199b51f
