### ISSUE TITLE
Materialbox in modal

### ISSUE THREAD

**Issue by valerio-bozzolan** [Dogfalo/materialize#1986]
I have to report that a materialbox-ed image doesn't work properly in a modal.

**Comment by carlosperate** [comment]
Could you provide a codepen illustrating the issue as indicated in the [contributing](https://github.com/Dogfalo/materialize/blob/master/CONTRIBUTING.md) file?

**Comment by tdhz77** [comment]
Same result for me.

**Comment by brunogoossens** [comment]
same here

**Comment by MyTheValentinus** [comment]
Same issue

**Comment by acburst** [comment]
This has been fixed
