### ISSUE TITLE
HTML in Tooltip

### ISSUE THREAD

**Issue by dhruv4** [Dogfalo/materialize#1987]
Hey! Firstly, this is a super awesome framework :)

Is it possible to have HTML markup in a tooltip? That is, I'm trying to put a table in the tooltip, so I put in "<table><tr><td>etc</td></tr></table>" in the "data-tooltip" field, but it's not working.

**Comment by override-chaos** [comment]
Currently it is not possible without hacking at the js. There is another issues regards HTML in tooltips.

https://github.com/Dogfalo/materialize/issues/1537

**Comment by dhruv4** [comment]
Shoot didn't see that. Alright, thanks!
