### ISSUE TITLE
Does materialize work with angular?

### ISSUE THREAD

**Issue by dcoferraz** [Dogfalo/materialize#1991]
I have a project that uses angular and I want to use materialize on it. Is that possible?

**Comment by Toujimon** [comment]
Yep, though not all features have been implemented yet.
https://github.com/krescruz/angular-materialize

**Comment by dcoferraz** [comment]
It wasn't quite working for me, but did you ever give it a try @Toujimon ?

**Comment by Toujimon** [comment]
I'm currently working on a project with this and it's working just fine. My major complains are about the datepicker (it works really funny and I just used the one referenced in the angular ui selection).
Can you be more specific about your problem using it?

**Comment by dcoferraz** [comment]
Well, in an ongoing project, I tried to use the select option as set on https://github.com/krescruz/angular-materialize.

That did not work at all, because I had to set the select functionality by hand on my JS like this:

```
$('select').material_select();
```

So we ended up throwing away jquery and all materialize.js and used angular material. =/

**Comment by Toujimon** [comment]
I understand. I must admit that for dropdowns, I prefer to use the "browser-default" class option instead.

**Comment by Dogfalo** [comment]
Thanks @Toujimon for the responses.

**Comment by ferchoman09** [comment]
The materialize DatePicker didn't work for me with AngularJS.
