### ISSUE TITLE
empty stripe at the bottom of cards with only an image element

### ISSUE THREAD

**Issue by Lynxiayel** [Dogfalo/materialize#1992]
As shown in the following pic, there's a small stripe at the bottom of the card. I assume when the image is used as the only element of a card, it should fill the card and the bottom stripes should not exist.
![4](https://cloud.githubusercontent.com/assets/1536638/9615659/9bfb267a-50c7-11e5-9d48-956fc1d781cf.png)

```
<div class="card teal darken-2 z-depth-3">
      <div class="card-image" >
                <a href="http://localhost:1313/album/montreal/">
                      <img src="/album/montreal/1.JPG">
                </a>
                <span class="card-title white-text">
                        Montreal
                </span>
      </div>
</div>
```

**Comment by acburst** [comment]
Fixed in aa1b00640ddefdf4c74c190c004fa406cf6ac82f
