### ISSUE TITLE
Bug in the "btn-floating" with browser Internet Explorer in OS Windows 8 and Windows 7

### ISSUE THREAD

**Issue by saralhernandez** [Dogfalo/materialize#1993]
Hi everyone,
The "btn-floating" is showing in the part bottom right to the page and it isn't activating the events with cursor, It is happening with browser Internet Explorer version 11, in OS Windows 8 and Windows 7, Someone can help me?
Thank you all!

**Comment by Dogfalo** [comment]
See the fixed action button section
