### ISSUE TITLE
JS Callback can use as funciton

### ISSUE THREAD

**Issue by shrimp2t** [Dogfalo/materialize#1998]
Now i see the example for callback function like

``` javascript
var options = [
    {selector: '.class', offset: 200, callback: 'globalFunction()' },
  ];
  Materialize.scrollFire(options);
```

Can you change callback function like this

``` javascript
var options = [
    {
    selector: '.class', offset: 200, callback: function( selector  ){
      // do something here
   } },

  ];
  Materialize.scrollFire(options);
```

Also can we use "offset" as number or function callback better like this

``` javascript
var options = [
    {
    selector: '.class', 
    offset: function( selector ){
        var offset_number =  200;
       return offset_number
     }, 
    callback: function( selector  ){
      // do something here
   },

{
    selector: '.class', 
    offset: 200 
    callback: function( selector  ){
      // do something here
   },

 },

  ];
  Materialize.scrollFire(options);
```

Sorry for my bad English :D

(edited only to fix the code formatting)

**Comment by carlosperate** [comment]
For the moment the scrollFire callback function [does not take any arguments](https://github.com/Dogfalo/materialize/blob/master/js/scrollFire.js#L33).

> can we use "offset" as number or function callback better like this

```javascript
    offset: function( selector ){
        var offset_number =  200;
       return offset_number
     }, 
```

I am not quite sure what you are trying to achieve with this, or why should an implementation would be useful.

**Comment by kkarkos** [comment]
Agree with the callback request. At the moment the callback can only access the global scope. But for OOP it would be more useful to be able tp call a "local" function (or to define a function as above example inline). At the moment "this" is the window object.

**Comment by kielni** [comment]
I have a pull request to allow callback to be a function here: https://github.com/Dogfalo/materialize/pull/2351

**Comment by kevgathuku** [comment]
+1 @kielni 
I think that's a useful addition

**Comment by fega** [comment]
added
