### ISSUE TITLE
How to I make a hybrid app using google materialize?

### ISSUE THREAD

**Issue by NikiShah** [Dogfalo/materialize#2000]
I have designed my pages using google materialize. They are html pages.How do I make an apk file as well as an ios app from the same. Please provide steps.I have installed npm from the documentation given in materialcss.com . But bower is not being installed.

**Comment by Dogfalo** [comment]
Take a look at Cordova or phonegap. There are plenty of guides available on the internet

**Comment by NikiShah** [comment]
thank you.  That worked

**Comment by NikiShah** [comment]
Thank you. That worked
