### ISSUE TITLE
materialbox doesn't work Ubuntu 14.04 firefox 40.

### ISSUE THREAD

**Issue by tdhz77** [Dogfalo/materialize#2001]
Using meteor package:           

```
<img class="materialboxed" width="600px" data-caption="{{metadata.description}}" src="{{this.url store="thumbs"}}"/>
```

Works under Chrome, Microsoft Edge.
10 different magnify glasses appear when you click on image.

**Comment by kmmbvnr** [comment]
It's ok with latest materialize on  FF35 and 49.
