### ISSUE TITLE
Website Materializecss.com is ahead of npm latest release

### ISSUE THREAD

**Issue by James-Firth** [Dogfalo/materialize#2002]
I started using Materialize via npm recently and noticed the website is ahead of the latest npm release (0.96.1).

This means that the website is not helpful when looking for icons as the naming scheme changed.

The workaround is to look at the commit release and find the icons.html page. However, some of the base names changed so ctrl+f searching for the general name doesn't work.

I think there should be a way to view multiple version of the website for different release numbers (helps support older code) or barring that, only have the website using the latest release (and not beyond).

Thoughts? Thanks!

**Comment by austinpray** [comment]
For the lazy: https://rawgit.com/Dogfalo/materialize/b3698e6282997eecd4cd9abf8720d4e605a762ee/index.html

These are the docs for 0.96.1

**Comment by carlosperate** [comment]
Thanks @austinpray, I was about to suggest the same.
There was an issue with npm publishing 0.97.0, so until the next release it will be unsynchronised. After that all versions should be in sync.
I wouldn't edit the website to display the documentation for older versions, but perhaps we could include a rawgit link into the changelog for reference.

**Comment by James-Firth** [comment]
Ah, I hadn't heard of rawgit before, that's pretty much all I needed.

@carlosperate Oh that makes sense now, I wasn't aware of that, thanks for the info!
