### ISSUE TITLE
Issue using materialize css with form_for

### ISSUE THREAD

**Issue by kumar91gopi** [Dogfalo/materialize#2003]
i am using materialize-sass with for developing rails 4 app. i am having many issues styling form_for with materialise
![button](https://cloud.githubusercontent.com/assets/10248907/9674836/cce50ea6-52f0-11e5-951b-b59107e0232a.JPG)
 the button looks fine initially but in case of error this appears.
![radio](https://cloud.githubusercontent.com/assets/10248907/9674837/cce92aa4-52f0-11e5-8c90-8a56dd6d5282.JPG)

two set of radio buttons are generated the materialize buttons are not clickable

**Comment by Dogfalo** [comment]
That is because that gem you are using is adding additional elements. Make sure it matches as we wrote it in our docs. Nothing we can do about 3rd party gems
