### ISSUE TITLE
attribute 'data-error' is not working with textarea

### ISSUE THREAD

**Issue by joonas-yoon** [Dogfalo/materialize#2006]
also 'data-success' is not working either. whenever focused or actived

is there no using about this?

**Comment by angelxmoreno** [comment]
this feature is very incomplete. does it work if you change it to an input field? I am under the impression that it only works for input fields.

**Comment by joonas-yoon** [comment]
Thank you for reply

**Comment by angelxmoreno** [comment]
:thumbsup:
