### ISSUE TITLE
Can I put Collection into Collapsible?

### ISSUE THREAD

**Issue by Rompei** [Dogfalo/materialize#2008]
I'm using this library for my projects and appreciate it so match.

I've tried to put Collection into Collapsible, then it was worked, but there was a blank between collapsible-header and collapsible-body like this.
http://codepen.io/Rompei/pen/qOEzOg

So is my code wrong or is it impossible?

**Comment by Zaanmedia** [comment]
Are you sure there is no margin or padding between those elements? I'm on mobile so i can't check it out for you!

**Comment by Rompei** [comment]
@Zaanmedia 
Thank you for your response.
Yes, I did't write CSS on the demo, only HTML.

**Comment by Blahah** [comment]
You just need to remove the top margin on the collection: http://codepen.io/anon/pen/dYozaz

**Comment by carlosperate** [comment]
I'd suggest to edit the css for collections descendant of collapsibles, but yeah @Blahah's suggestion will work: http://codepen.io/anon/pen/zvGaoN

**Comment by Rompei** [comment]
@Blahah 
Thank you, it worked. 
@carlosperate 
Why don't you add this code to the project? Because I think it is pretty useful to make a foldable list.

**Comment by Rompei** [comment]
My final solution is here.
http://codepen.io/Rompei/pen/qOEzOg

**Comment by acburst** [comment]
Added in f51af6b
