### ISSUE TITLE
Fix sized cards not showing text correctly.

### ISSUE THREAD

**Issue by Lynxiayel** [Dogfalo/materialize#2009]
When the card is set as a predefined size (small/medium/large), the text in the card is somehow chopped off and only get partially showing.

An example of medium card goes below (or [here on codepen](http://codepen.io/anon/pen/XmbWOQ)). Similar issue happens to both small and large cards.

![1](https://cloud.githubusercontent.com/assets/1536638/9707174/dc93c562-54cc-11e5-95bc-9c10ee33c271.png)

code goes here
```
<html>
<head>
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/0.97.0/css/materialize.min.css">
  <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/0.97.0/js/materialize.min.js">
  </script>
</head>

<body>
  <div class="row">
    <div class="col m4 s12">
      <div class="card blue-grey darken-3 medium">
        <div class="card-content grey-text text-lighten-2">
          <span class="card-title white-text">
                        <a href="#">
                            test
                        </a>
                    </span>
          <p>line 1 is showing.
            <br> line 2 is showing.
            <br> line 3 is showing.
            <br> line 4 is partially showing.
            <br> line 5 is not showing.
            <br>
          </p>
        </div>
        <div class="card-action">
          <a href="#">Read more ...</a>
        </div>
      </div>
    </div>
  </div>
</body>
</html>
```

**Comment by Dogfalo** [comment]
Because the cards you are using should look like this ![](http://puu.sh/k2rg2/c39d434eb4.png). You are missing an image

**Comment by Lynxiayel** [comment]
Thanks, so does that mean the predefined sizes only apply to image cards?

**Comment by Dogfalo** [comment]
Yep, that is right
On Sun, Sep 6, 2015 at 7:26 PM, Lynxiayel <notifications@github.com> wrote:

> Thanks, so does that mean the predefined sizes only apply to image cards?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Dogfalo/materialize/issues/2009#issuecomment-138160511>
> .
>



-- 
Doggy sends his greetings from Mars.
