### ISSUE TITLE
Style default scrollbar

### ISSUE THREAD

**Issue by zigy** [Dogfalo/materialize#201]
It would be a great thing if you're in your CSS framework changed the default scrollbar style. On my site I use webkit version:

CSS
```
::-webkit-scrollbar {
    width: 12px;
}
 
::-webkit-scrollbar-track {
    -webkit-box-shadow: inset 0 0 6px rgba(0,0,0,0.3); 
}
 
::-webkit-scrollbar-thumb {
    -webkit-box-shadow: inset 0 0 6px rgba(0,0,0,0.5); 
}
```
Next thing is cursor selection color:

CSS
```
::-moz-selection { background: #ffa726; color: #fff; }
::selection { background: #ffa726; color: #fff; }
```
You can try it too, it looks really nice.

**Comment by acburst** [comment]
We are not looking to add this into our core framework. It is easy enough to customize yourself.
