### ISSUE TITLE
Radio Buttons

### ISSUE THREAD

**Issue by INGCRENGIFO** [Dogfalo/materialize#2013]
Hola, tengo un problema al usar los radio button, cuando cargo datos me daña el DOM, tengo el siguiente codigo.
<div class="col s3">
              <p>
                <input type="radio" name="recorrido" id="ida" ng-model="solViaticos.Desplazamientos[tabs[selectedTab].id].Recorrido" value="I">
                <label for="ida">Ida</label>
              </p>
            </div>
            <div class="col s3">
              <p>
                <input type="radio" name="recorrido" id="idayreg" ng-model="solViaticos.Desplazamientos[tabs[selectedTab].id].Recorrido" value="R">
                <label for="idayreg">Ida y Regreso</label>
              </p>
            </div>

Luego al cargarle un valor al Radio Button este me daña la interfaz como la imagen que adjunto.
![radiobutton](https://cloud.githubusercontent.com/assets/12200313/9735444/88fe0982-5600-11e5-8e3f-4dc208a7bfc0.png)

**Comment by INGCRENGIFO** [comment]
The "Agregar Novedad" button opens a modal, if I open the modal and I close everything is fixed, or if I zoom into the page also is arranged, this only happens in Chrome, Firefox no problem.

I am grateful to collaborate.

**Comment by carlosperate** [comment]
Could you please provide a codepen illustrating a full example of your issue? it'd be quite hard to help you otherwise.

**Comment by INGCRENGIFO** [comment]
Hi carlosperate, Thanks for your support.

The code is in this link:
http://codepen.io/anon/pen/avvoYy?editors=101

In line 179 the variable "Recorrido" is the one that fails, and the html is on line 86

**Comment by carlosperate** [comment]
A minimalistic example showing only the issue would be a lot more helpful, I am not sure what I am supposed to be looking for in your codepen.

**Comment by Dogfalo** [comment]
The radio buttons work for me, what is the problem?

**Comment by INGCRENGIFO** [comment]
loading data fails me but I decided to remove the "RadioButton" to avoid me headaches
