### ISSUE TITLE
Input Problems

### ISSUE THREAD

**Issue by cabrinhaFx** [Dogfalo/materialize#2014]
![materializeinput](https://cloud.githubusercontent.com/assets/13951053/9738322/2f6b62c0-564b-11e5-865f-a08bf0f3cdf8.jpg)
I´m Filling the Input over a Java-Script and therefore the Animation don`t get`s triggered:
 Label and Input are overlapping, Label isn`t animated going to the top

Also there is no color-changing during the animation, the label color don`t change.

**Comment by Dogfalo** [comment]
See closed issues please.
