### ISSUE TITLE
Bug? - Collection cannot handle events if the data come from JSON

### ISSUE THREAD

**Issue by RataDP** [Dogfalo/materialize#2015]
I was trying to handle the click event in collection, but jQuery/JS didn't do anything in my project. When I clicked in the element, nothing appeared but an alert had to show in the browser.

 I tryed in codepen and jsFiddle and it worked well but I was trying in this sites with local data. When I tryed retriving a JSON from a website, the error appeared another time. So I conclude the problem is this. Following this I will paste a CodePen with the two scenarios.

http://codepen.io/RataDP/pen/pjJLrd

Is there a problem with Materialize or with the jQuery? And are there approaches to solve this problem?

**Comment by chr8993** [comment]
It seems that since the content is loaded through Ajax you will have to bind the event listener to the document or a parent instead of the actual element like so:
```js
$(document).on('click', '.event-click', function(e) {
    //your code here
});
```
Updated codepen: http://codepen.io/anon/pen/gapzQz

**Comment by acburst** [comment]
did this solve the issue? Closing for now assuming this fixes it
