### ISSUE TITLE
Move popups up the dom

### ISSUE THREAD

**Issue by MeMyselfI** [Dogfalo/materialize#2016]
Hi.

If you have a constraint area like in a card or inside a  div with scrollbars popups like dropdowns or datepickers are cut off because they are inserted deeply inside the DOM instead of the body.
In the datepicker you can use the option component:document.body but there isn't such an option with the dropdown for example.

So please rewrite all popup to be added to the body so they will be displayed above everything else.

Cheers.

**Comment by MeMyselfI** [comment]
A quick and dirty (breaks .activator for example) workaround is to move the popup once it is shown:

In the placeDropdown function I added at the end

.animate( {opacity: 1}, {queue: false, duration: options.inDuration, easing: 'easeOutSine', done: function () {
         var offset = $(this).offset (), prev = $(this).prev (), prevID = prev.attr ('id') || 'gen-'+Math.round (Math.random ()*100000);
          prev.attr ('id', prevID);
          $(this).attr ('data-prev-id', prevID);
          $(this).appendTo (document.body).offset (offset);
          }});

and overwrote the hideDropdown function with

      activates.fadeOut (options.outDuration, function () {
       $(this).appendTo ($('#'+$(this).attr ('data-prev-id')).parent ());
       });
      activates.removeClass('active');

**Comment by MeMyselfI** [comment]
Is this already changed?

**Comment by MeMyselfI** [comment]
Push.

**Comment by tomscholz** [comment]
You can send a pull request, but I will close this issue for now. If you decide to open a pr, we can maybe reopen this issue
