### ISSUE TITLE
validate and pickadate does not work

### ISSUE THREAD

**Issue by MeMyselfI** [Dogfalo/materialize#2017]
I am not sure why but .is(':valid') is always false. Tried to use type="text" and set the format of the picker to yyyy/mm/dd without success.

**Comment by MeMyselfI** [comment]
Here's a quick and dirty fix: 

window.validate_field = (function () {
    var original = window.validate_field;
    return function (el) {
     if (el.hasClass ('datepicker')) {
        if (el.val () === '')
           el.removeClass ('valid').addClass ('invalid');
           else el.removeClass ('invalid').addClass ('valid');
        } else original (el);
     };
    }) ();

**Comment by Birssan** [comment]
Same issue here, is there any valid/clean fix :( ?

**Comment by fega** [comment]
Could you check if this is still an issue with the last version?

Closed due inactivity, feel free to reopen it if it is still necessary.

**Comment by quentinHydrobat** [comment]
Well error still here

Input stays red even when done

**Comment by fega** [comment]
@tomscholz this  should be reopenned?
