### ISSUE TITLE
MaterializeCSS on Cordova: layout is broken

### ISSUE THREAD

**Issue by MulletPr00f** [Dogfalo/materialize#2018]
I'm coding a test app on Cordova. If I access it through Chrome (it's just a html file) or through the device emulator (Ripple), the layout is perfectly fine. But when I open the app on the device, the icon layout is all over the place, just as the circle size / margin. Could someone point me in to the correct path? What am I missing here?

Chrome:
![chrome](https://cloud.githubusercontent.com/assets/5559691/9775821/c891b444-5728-11e5-97fd-ca83012db264.png)

Emulator:
![ripple](https://cloud.githubusercontent.com/assets/5559691/9775777/542bc3e2-5728-11e5-9699-bea442942816.png)

Device:
![device](https://cloud.githubusercontent.com/assets/5559691/9775857/15474f10-5729-11e5-8a3f-8d02bc655cd1.jpg)

Thanks!

**Comment by dcoferraz** [comment]
That's a awesome question because with this great CSS framework the use with Cordova apps will be used with it.

:+1:

**Comment by carlosperate** [comment]
Is your test device running 4.3 or lower?

**Comment by MulletPr00f** [comment]
@dcoferraz Thanks for the support :)

@carlosperate IDK why I didn't mention this earlier, but my device is actually running Android 5.0.

**Comment by carlosperate** [comment]
Seems to be a similar issue to https://github.com/Dogfalo/materialize/issues/905
Could you open that test page with the android browser just to confirm the same issue?

Also it would be really helpful if you could provide a minimum example (something with just the circular icon displaying this issue) that we could use during testing.

**Comment by MulletPr00f** [comment]
@carlosperate I couldn't find that test page you mentioned, but I wrote a simple example, including that floating button. The collection I pulled from MaterializeCSS samples, "Avatar Content". The code is here:
http://codepen.io/anon/pen/eppgQK?editors=100

On my device, using cordova, this is what I get. Mind that not only the icons are in the wrong place but the text is also smaller than it should be, giving the < li > a look that is like its bigger than it should be.
![sc-cordova](https://cloud.githubusercontent.com/assets/5559691/9796193/38e6fb94-57cb-11e5-9e18-9cd53c75756b.jpg)

On the same device, checking that codepen through the default browser, the mdi-navigation-menu icon of the menu renders properly, but all the other icons (material-icons) don't. This also happens on Dolphin browser.
![sc-default](https://cloud.githubusercontent.com/assets/5559691/9796198/3d7a7582-57cb-11e5-90d3-29bc259acd84.jpg)
![sc-dolphin](https://cloud.githubusercontent.com/assets/5559691/9796204/422bda8a-57cb-11e5-8541-76d77828cb59.jpg)

But on Chrome, all is rendered properly.
![sc-chrome](https://cloud.githubusercontent.com/assets/5559691/9796211/5103333c-57cb-11e5-82e0-2faade4ad966.jpg)

**Comment by MulletPr00f** [comment]
OK, I managed to fix this issue by adding the Crosswalk Webview plugin on my Cordova app. Unfortunately I couldn't figure out what the problem really was, but if I were to point fingers, would be to a poorly handle of EM sizes on the default Android Webview, and/or the meta viewport set.

**Comment by dcoferraz** [comment]
@MulletPr00f, on my developments with Cordova apps I have noticed the same issue. Android's (or Cordova's) Webview has a poor support for ```em```.
I had to workaround the problem with using explicit pixel sizes.

**Comment by dcoferraz** [comment]
@MulletPr00f, I had the same issue using ```em``` on Cordova apps. Unfortunately I had to workaround the problem using an explicit pixel size.

Thanks for the answer about Crosswalk Webview! :) :+1:

**Comment by MulletPr00f** [comment]
I'd like to thank @dcoferraz and @carlosperate for the support. I'm gonna close this issue since I won't be chasing the cause of this problem anymore.

**Comment by Denly** [comment]
I have this issue too in Cordova. Webview is huge, 23 MB. Hope this issue can be opened again and fix it! Thank you!  @MulletPr00f 

![screen shot 2017-06-25 at 2 02 17 am](https://user-images.githubusercontent.com/7588279/27514001-98e60eb8-594a-11e7-9dfb-93a95ca1e5a0.png)
![screen shot 2017-06-25 at 2 02 12 am](https://user-images.githubusercontent.com/7588279/27514002-98e6cbbe-594a-11e7-8e91-51fb92aaf103.png)

**Comment by DanielRuf** [comment]
@Denly which version of Materialize do you use? Is it fixed when you move to px measures?

**Comment by QuackBtz** [comment]
Recently I've been dealing with this, a workaround is to set TextZoom to 100 for your webclient.

**Comment by evirens** [comment]
I found this is caused by the text size setting in android, but I don't consider changing this a fix, since I'd like to be able to keep my settings
