### ISSUE TITLE
responsive-img not responsive in small screen, IE11 and FF40.0.3

### ISSUE THREAD

**Issue by pedroserapio** [Dogfalo/materialize#2019]
Hello!

My first round with Materialize, why responsive-img class works with Large and Middle screens but stop working with small screens. Only Opera and Chrome works correctly. Something I'm missing?

Best regards.

**Comment by MulletPr00f** [comment]
Hi @pedroserapio, could you provide a codepen?

**Comment by pedroserapio** [comment]
Hello @MulletPr00f , thank you for the reply.
Have a look, please.

http://codepen.io/Serapio/full/WQQXvr/

I hope you can see that if the image is placed outside of a card, stop being responsive when the screen is small.

My best regards.

**Comment by Dogfalo** [comment]
Because you didn't define the small grid size and only m and l were defined
