### ISSUE TITLE
Add dropdown in navigation

### ISSUE THREAD

**Issue by vacquah** [Dogfalo/materialize#202]
Is there a way to design a navbar which includes an element with a dropdown?

**Comment by fteem** [comment]
@iamraju did you solve your question?

**Comment by DWboutin** [comment]
The dropdown don't work for me. I use it with Meteor JS. This is my onRedered function:
```
Template.header.onRendered(function(){
	$(".button-collapse").sideNav();
	$(".dropdown-button").dropdown();
});
```
The `.sideNav()` works well, but the `.dropdown` didn't work at all.

This is my LI tag 
```
<li>
  <a href="#!" class="dropdown-button" data-activates="account-dropdown">My account <i class="material-icons right">&#xE313;</i></a>
  <ul id="account-dropdown" class="dropdown-content">
    <li><a href="#!">one</a></li>
    <li><a href="#!">two</a></li>
    <li class="divider"></li>
    <li><a href="#!">three</a></li>
  </ul>
</li>
```

Nothing changes when i click on my link. I tried anything, any changes to make it work. Please help.

**Comment by iamraju** [comment]
@fteem Nope, I had to switch to something else to solve it.

**Comment by ranska** [comment]
@DWboutin same for me i do everthing that is writing here but it didn't work for me.
it work on side bar but not on top menu
version:
gem materialize-sass (0.97.0)

**Comment by nigelpasco** [comment]
@DWboutin @ranska On meteor it seems ok. I have tested on a fresh simple meteor build with materialize@=0.97.0

@DWboutin I think you need to take the account-dropdown section out of the <li>. It should be separated from the button.

@ranska... any details? See below for a working meteor example.

```
<head>
  <title>test2</title>
  <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet"> <!-- adds material icons -->
</head>

<body>

  {{> hello}}
</body>

<template name="hello">

  <!-- Dropdown Structure -->
<ul id="dropdown1" class="dropdown-content">
  <li><a href="#!">one</a></li>
  <li><a href="#!">two</a></li>
  <li class="divider"></li>
  <li><a href="#!">three</a></li>
</ul>
<nav>
  <div class="nav-wrapper">
    <a href="#!" class="brand-logo">Logo</a>
    <ul class="right hide-on-med-and-down">
      <li><a href="sass.html">Sass</a></li>
      <li><a href="badges.html">Components</a></li>
      <!-- Dropdown Trigger -->
      <li><a class="dropdown-button" href="#!" data-activates="dropdown1">Dropdown<i class="material-icons right">arrow_drop_down</i></a></li>
    </ul>
  </div>
</nav>

</template>
```
```
if (Meteor.isClient) {

  Template.hello.onRendered(function(){
      $(".dropdown-button").dropdown();
  });

}
```

**Comment by jalasem** [comment]
I used the dropdown in my navigation bar, but two out of four is showing and here is my code in html for my navbar:

<nav class="white blue-text">
                <div class="navbar-wrapper container">
                  
                  <a href="#" data-activates="mobile-menu" class="button-collapse indigo-text"><i class="material-icons">menu</i></a>
                  <a href="#" class="brand-logo left"><img src="images/logo.png" class="top-logo"></a>

                  <ul class="hide-on-med-and-down right">
                    <li class="waves-effect waves-light"><a href="index.html">Home</a></li>
                    <li class="waves-effect waves-light"><a href="about.html">About Us</a></li>
                    <li class="waves-effect waves-light active"><a class="dropdown-button" href="#!" data-activates="dropdown1" href="javascript:void(0)">Gallery</a></li>
                    <ul id='dropdown1' class='dropdown-content'>
          					  <li><a href="#!">Videos</a></li>
          					  <li><a href="publication.html">Publication</a></li>
          					  <li><a href="#!">Interviews</a></li>
          					  <li><a href="#!">Pictures</a></li>
          					</ul>
                    <li class="waves-effect waves-light"><a href="javascript:void(0)">News</a></li>
                    <li class="waves-effect waves-light"><a href="events.html">Events</a></li>
                    <li class="waves-effect waves-light"><a href="partners.html">Partners</a></li>
                    <li class="waves-effect waves-light"><a href="javascript:void(0)">Contact Us</a></li>
                  </ul>
                  <ul class="side-nav" id="mobile-menu">
                    <li class="waves-effect waves-light"><a href="index.html">Home</a></li>
                    <li class="waves-effect waves-light"><a href="about.html">About Us</a></li>
                    <li class="waves-effect waves-light active"><a href="javascript:void(0)">Gallery</a></li>
                    <li class="waves-effect waves-light"><a href="javascript:void(0)">News</a></li>
                    <li class="waves-effect waves-light"><a href="events.html">Events</a></li>
                    <li class="waves-effect waves-light"><a href="partners.html">Partners</a></li>
                    <li class="waves-effect waves-light"><a href="javascript:void(0)">Contact Us</a></li>
                  </ul>
                </div>
            </nav>

here is all my css modifications:

.slider{
	margin-top: 0.1rem;
}
.top-logo {
    width: 15rem;
    margin-top: -4rem;
}
nav ul a {
    font-size: 1.1rem;
    color: #2196F3;
}
#donate{
	height: 400px;
	padding: 0 0rem;
    margin-top: -1.65rem;
    padding-top: 5rem;
}
nav, nav .nav-wrapper i, nav a.button-collapse, nav a.button-collapse i {
    min-height: 105px;
    line-height: 105px;
}
.container {
    width: 95%;
}
p,h1,h2,h3,h4,h5{
	color: #2196F3;
}
h5{
	margin: 0.5rem auto;
}
.card{
	padding-left: 0.5rem;
	padding-right: 0.5rem;
}
.card p, .card ul li, ul li{
	font-size: 1.1rem;
}
.slider .slides li .caption {
    color: #fff;
    position: absolute;
    top: 15%;
    left: 10%;
    width: 70%;
    opacity: 0;
}
.caption h1,.caption h2, .caption h3, .caption h4, .caption h5, .caption p{
	color: white;
}
.input-field {
    position: relative;
    margin-top: 0rem;
}

and lastly my js:

        $(document).ready(function(){
      $('.slider').slider({full_width: true, height:350});
    });
    $('.dropdown-button').dropdown({
      inDuration: 300,
      outDuration: 225,
      hover: true,
      belowOrigin: true
  );

I have uploaded a demo at http://www.jalasem.com
thank you

**Comment by santhosh77h** [comment]
while implementing dropdown for mobile app using phonegap. dropdown-content is not closing on selecting any one dropdown content.i have used the same codes from materializecss dropdown codes. and i have initilized dropdown in my javascript file as

 $('.dropdown-button').dropdown();
