### ISSUE TITLE
datepiker correct format in firefox

### ISSUE THREAD

**Issue by INGCRENGIFO** [Dogfalo/materialize#2020]
Hello, it has passed them by loading a db date from the picker does not take them the right format? if I select the date from the picker it looks good but if by the db have problems between firefox and chrome. Has anyone been able to solve?

**Comment by carlosperate** [comment]
Could you provide a codepen illustrating the issue as indicated in the [contributing](https://github.com/Dogfalo/materialize/blob/master/CONTRIBUTING.md) file?

**Comment by INGCRENGIFO** [comment]
Okay, I'm arranging the code to paste into codepen.

**Comment by INGCRENGIFO** [comment]
Hello @carlosperate , this is the code:
http://codepen.io/anon/pen/vNLrgJ?editors=101
so it is in chrome
![chrome](https://cloud.githubusercontent.com/assets/12200313/9878983/0a594cfa-5b8b-11e5-8873-03a66965f936.png)
so it is in Firefox
![firefox](https://cloud.githubusercontent.com/assets/12200313/9878982/0a139606-5b8b-11e5-86a5-7122a5cb34ed.png)

**Comment by INGCRENGIFO** [comment]
But someone has any idea ?? I still have the error: S

**Comment by tomscholz** [comment]
I can not reproduce your problem and your codepen doesn't use the latest version of materialize
