### ISSUE TITLE
Retain the url fragment when tabs are clicked

### ISSUE THREAD

**Issue by kalenjordan** [Dogfalo/materialize#2029]
It seems like it would be ideal for the url fragment to be retained upon clicking on tab links.  This allows for easy deeplinking into tabs.  

I saw that the reason it's not retained is because of the `e.preventDefault()` call that's made.  It's probably a good thing that it prevents a little bit of jerkiness when clicking b/c it avoids the jump action which probably isn't necessary.  But I think that losing the url fragment is a bad trade-off in this case.

Any thoughts?

**Comment by fega** [comment]
closed due inactivity
