### ISSUE TITLE
Feature Request: Hardware Accelerated SideNav

### ISSUE THREAD

**Issue by boustanihani** [Dogfalo/materialize#2030]
I know this has been requested in https://github.com/Dogfalo/materialize/issues/1739, I just want to ask for forcing hardware acceleration on the "SideNav" because it is very sluggish on mobile... This would really be a great start and enhance user experience a lot.

**Comment by Dogfalo** [comment]
Added in df0c80fbd6c7f42e5d597464ce6962fbb8e3dfea

**Comment by boustanihani** [comment]
cool :+1:
