### ISSUE TITLE
Textarea resize is too large

### ISSUE THREAD

**Issue by simkessy** [Dogfalo/materialize#2032]
My textarea expands way too much on text input as oppose to in the demo where it skips 1 line, I'm getting this: 

http://i.imgur.com/fXE4f9Y.png

**Comment by acburst** [comment]
Can you please submit a codepen example

**Comment by simkessy** [comment]
Nevermind, I wrapper the form css around `.materialize-form` so it wouldn't conflict with other non-materialize rules. Turns out I needed to take `.hiddendiv` out from that because the rules weren't being applied
