### ISSUE TITLE
Extras folder is not included in the zips

### ISSUE THREAD

**Issue by acburst** [Dogfalo/materialize#2033]

**Comment by tomscholz** [comment]
Extras are still not a part of the zips!

**Comment by fega** [comment]
OK!!! sorry! :open_mouth:

**Comment by tomscholz** [comment]
@acburst Why do they even have to be a part of "the zips"? I mean people can easily download them or obtain them via a git cdn like rawgit

**Comment by tomscholz** [comment]
https://github.com/Dogfalo/materialize/pull/4799
