### ISSUE TITLE
Disabling hover on FAB

### ISSUE THREAD

**Issue by zkellerdevelops** [Dogfalo/materialize#2040]
I'm trying to make a FAB with multiple options only pop up on a click event, and then close on another click event using `openFAB();` and `closeFAB();`. 

How can i disable the hover action?

I've tried commenting out lines 7-16 on buttons.js to no avail.
Can you point me in the right direction?

**Comment by msolters** [comment]
Hey @zkellerdevelops, I have implemented a very similar setup to what I think you're asking for and I'd gladly put together a quick PR if you can confirm it's what you're after.

If you register an account (does not have to be real email) against [this demo here](http://tilesjs.meteor.com/register), it ought to present you with a FAB menu that is triggered *only* on click.  Let me know if that's the behaviour you had in mind.

**Comment by zkellerdevelops** [comment]
Yep! That's it.
Turns out we are likely going to ditch this button due to client feedback, but I'd love a PR inc ase we decide to add this back in, or if I use it for another project.

**Comment by msolters** [comment]
@zkellerdevelops I've implemented the override you're after.  My PR introduces a CSS class called `.click-to-toggle`, and adding it into a `.fixed-action-btn` menu will:

*  *Prevent* hover behaviour
*  Toggle opening or closing the menu (w/ animation) whenever the `.large-btn` is clicked.  Works for vertical and horizontal FAB menus.

Example:
```html
<div class="fixed-action-btn click-to-toggle">
  <a class="btn-floating btn-large red">
    <i class="large mdi-navigation-menu"></i>
  </a>
  <ul>
    <li><a class="btn-floating red"><i class="material-icons">insert_chart</i></a></li>
    <li><a class="btn-floating yellow darken-1"><i class="material-icons">format_quote</i></a></li>
    <li><a class="btn-floating green"><i class="material-icons">publish</i></a></li>
    <li><a class="btn-floating blue"><i class="material-icons">attach_file</i></a></li>
  </ul>
</div>
```

**Comment by zkellerdevelops** [comment]
Thanks guys. Really appreciate it.
