### ISSUE TITLE
This package destroys basic Meteor components

### ISSUE THREAD

**Issue by methodbox** [Dogfalo/materialize#2043]
As soon as I installed this, even Spacebars wasn't recognized. Templates weren't recognized.

I don't know how this Atmosphere package was compiled, but it wasn't done correctly. I packaged a small JS library for my own use and it didn't hose my entire application.

This readout is from the web console in Chrome:
```
Uncaught TypeError: Cannot set property 'guid' of undefined
global-imports.js:6 Uncaught TypeError: Cannot read property 'Materialize' of undefined
template.about.js:2 Uncaught ReferenceError: Template is not defined
template.contact.js:2 Uncaught ReferenceError: Template is not defined
template.home.js:2 Uncaught ReferenceError: Template is not defined
template.master-layout.js:2 Uncaught ReferenceError: Template is not defined
template.nav.js:2 Uncaught ReferenceError: Template is not defined
meteor.js:888 Exception in callback of async function: ReferenceError: Deps is not defined
    at Layout.beginRendering (http://localhost:3000/packages/iron_layout.js?4e65c46acdaf0ce6a8b1a479d7b9d0b5c0902062:288:3)
    at Controller.beginRendering (http://localhost:3000/packages/iron_controller.js?5a7eedaafda7001b9d5cb52322a419bbb758968c:290:23)
    at RouteController._runRoute (http://localhost:3000/packages/iron_router.js?7b16fe70bccff9182aca02afb2ccd7708ac57c64:470:8)
    at Function.Route.dispatch (http://localhost:3000/packages/iron_router.js?7b16fe70bccff9182aca02afb2ccd7708ac57c64:854:18)
    at route (http://localhost:3000/packages/iron_router.js?7b16fe70bccff9182aca02afb2ccd7708ac57c64:711:11)
    at boundNext (http://localhost:3000/packages/iron_middleware-stack.js?56e0c02a758f48c0a704ca978a8fb6d7bd9ebbab:424:31)
    at http://localhost:3000/packages/meteor.js?43b7958c1598803e94014f27f5f622b0bddc0aaf:983:22
    at boundNext (http://localhost:3000/packages/iron_middleware-stack.js?56e0c02a758f48c0a704ca978a8fb6d7bd9ebbab:371:14)
    at http://localhost:3000/packages/meteor.js?43b7958c1598803e94014f27f5f622b0bddc0aaf:983:22
    at dispatch (http://localhost:3000/packages/iron_middleware-stack.js?56e0c02a758f48c0a704ca978a8fb6d7bd9ebbab:448:3)
iron_layout.js:95 Uncaught ReferenceError: Spacebars is not defined
```

**Comment by iamkevingreen** [comment]
Having the same problem

**Comment by lsunsi** [comment]
When Spacebars isn't recognized, something must be terribly wrong.
Some issue here, btw.

**Comment by methodbox** [comment]
Note that ```$meteor remove materialize:materialize``` will remove the package successfully, apparently with no detrimental effects (none that I've found so far).

**Comment by methodbox** [comment]
I've found this package, but it doesn't appear to have an Atmosphere package yet.
https://github.com/npvn/meteor-material-design

Their Material examples are superb.

I may try to package this up for Atmosphere later. I've also left a note on the owner's Github issues that there's no Atmosphere instructions the package is not found at Atmospherejs.com.

**Comment by msolters** [comment]
This is the same issue as https://github.com/Dogfalo/materialize/issues/2037.

You can still use all the features of this package, just specify to use the last version, 0.97.0.  Quoting from that thread:

> ...edit your .meteor/packages file and change materialize:materialize to materialize:materialize@=0.97.0 for the time being. Then a meteor update will ensure your version stays at 0.97.0 until the latest one gets fixed.

**Comment by heshaohu** [comment]
meteor remove materialize:materialize
meteor add materialize:materialize@=0.97.0

**Comment by heshaohu** [comment]
meteor remove materialize:materialize
meteor add materialize:materialize@=0.97.0
And now all is ok.

**Comment by Hamatek** [comment]
yep go for with the previous version has @heshaohu  mentioned:
meteor add materialize:materialize@=0.97.0

**Comment by dcworldwide** [comment]
Same issue. Rolling back to 0.97.0

**Comment by claytonmarinho** [comment]
Worked with me when back to 0.97.0

**Comment by alexchopin** [comment]
Same issue.

**Comment by tdhz77** [comment]
+1

**Comment by methodbox** [comment]
Just for the record, are you all on the latest version of Meteor @.4?

**Comment by JCRamires** [comment]
Using latest Meteor version, Materialize 0.97.1 breaks everything, 0.97.0 works fine

**Comment by grsabreu** [comment]
I made a fix for that, guys
Waiting approve for merging

**Comment by carlosperate** [comment]
Thanks for the report and looking into the issue. For now I'll be closing this one to consolidate this specific issue into https://github.com/Dogfalo/materialize/issues/2037.

**Comment by lnmunhoz** [comment]
@heshaohu +1

**Comment by joaobarcia** [comment]
+1

**Comment by TimoRuetten** [comment]
+1 why its not fixed yet ?

**Comment by thekavish** [comment]
Rolled back to 0.97.0 , thanks @Hamatek and @heshaohu
