### ISSUE TITLE
Should I remove meteor bootstrap package? 

### ISSUE THREAD

**Issue by zevsuld** [Dogfalo/materialize#2046]
Hi!
I used bootstrap package for my app, now switching to materialize package. Should I remove bootstrap package? It seems like materialize package have some classes as same name as bootstrap.

**Comment by carlosperate** [comment]
Not really recommended: https://github.com/Dogfalo/materialize/issues/1803

**Comment by zevsuld** [comment]
@carlosperate thank you. 
I will remove bootstrap package.
