### ISSUE TITLE
Tooltipped broken with 0.97.1 (meteor)

### ISSUE THREAD

**Issue by tdhz77** [Dogfalo/materialize#2050]
Tooltipped not firing.

```javascript
Template.uploads.onRendered(function() {
    $('.tooltipped').tooltip({delay: 0});
});
````
uploads.html
```javascript
    <a class="btn tooltipped" data-position="right" data-delay="50" data-tooltip="I am tooltip">Hover me!  </a>
```

removed jquery,  
 entered"
```javascript
    '$('.tooltipped').tooltip({delay: 0});' 
```
into console which fired up 

```javascript
    <a class="btn tooltipped"...> 
```

as expected.. 

Any help here?

**Comment by tdhz77** [comment]
meteor removed materialize:materialize
added CDN and everything works.

**Comment by acburst** [comment]
There are some major problems with meteor as of the latest release. Rollback to our previous version. I'm closing this issue and consolidating all meteor discussion in this issue: #2043
