### ISSUE TITLE
Multiples dropdown links

### ISSUE THREAD

**Issue by viniciusmichelutti** [Dogfalo/materialize#2051]
Guys, I have many cards in my page, and every card has a button to the same dropdown, since I have only one dropdown content, the dropdown appears only on the last card of the page.

``` html
<div class="card">
    <div class="card-content">
        <a href="#" class="right dropdown-button" data-activates="task-menu"><i class="material-icons">more_vert</i></a>
        <p>CARD 1</p>
    </div>
</div>
<div class="card">
    <div class="card-content">
        <a href="#" class="right dropdown-button" data-activates="task-menu"><i class="material-icons">more_vert</i></a>
        <p>CARD 2</p>
    </div>
</div>

<!-- DROPDOWN CONTENT -->
<ul id="task-menu" class="dropdown-content">
    <li><a href="#!">Assign to me</a></li>
    <li><a href="#!">Details</a></li>
    <li><a href="#!">Remove</a></li>
 </ul>
```

How can I make the same dropdown works in multiple cards?

**Comment by acburst** [comment]
This is currently not supported. We can look into a fix but this probably won't be a priority for now. You can just add multiple dropdown menus which is ugly but will work for now.

**Comment by TyrionGraphiste** [comment]
I pushed a quick solution at this address : (3467b76)[https://github.com/TyrionGraphiste/materialize/commit/3467b76d0eaa18f4993f030c0c3efa139b76da75]

Sorry for the wrong PR, idk yet how to open another PR if we already got one opened.

**Comment by viniciusmichelutti** [comment]
Nice @TyrionGraphiste, I'll make this change locally for now, thanks in advance!

**Comment by viniciusmichelutti** [comment]
@TyrionGraphiste it works! Thanks for the fix! @acburst can we take the Tyrion pull request and merge?

**Comment by romant** [comment]
any news on whether this will be accepted ?

**Comment by Xstream007** [comment]
Hey... Sorry for reopening this. But I don't understand where to put that code. Sorry I'm new to materialize but I'm facing the same problem with card-panels. Where is dropdown.js file? Where to put the code? @viniciusmichelutti you say the solution is fixed. Help me.
