### ISSUE TITLE
Bug Sidebar (with tag <a>)

### ISSUE THREAD

**Issue by Master-Antonio** [Dogfalo/materialize#2053]
Hello guys, 
there is one problem also important in last build.
Class="button-collapse" don't work with tag <a> .
I had to force in this way.
<li data-activates="slide-out" class="button-collapse"><i class="mdi-navigation-menu"></i></li>

Work.
But the result is this .
https://i.gyazo.com/506e7b639c4e84ce49b6cb3c72834158.png

Don't have CSS RULES .
Color is black and does not adapt with the menu items ( width , position , height ext ext )
https://i.gyazo.com/776c5796525ac510e8ae7aed4025bc20.png

**Comment by acburst** [comment]
Can you post your code as well?

**Comment by Master-Antonio** [comment]
<nav>
		<div class="nav-wrapper">
		<a href="" class="brand-logo center">
		<img src="images/logo.png">
	   </a>
	 
		
		<a href="#" data-activates="mobile-demo" class="button-collapse"><i class="material-icons">menu</i></a>
		<ul class="side-nav" id="mobile-demo">
		<li><a href="#">Chi siamo</a></li>
		<li><a href="#">Categorie</a></li>
		<li><a href="#">Varie</a></li>
		<li><a href="#">Varie</a></li>
		</ul>
		<script>$(".button-collapse").sideNav();</script>
		
	  
			
			<ul class="left hide-on-med-and-down">
			</ul>
			
	  
			
			<ul class="right hide-on-med-and-down">
			
			
			<li data-activates="slide-out" class="button-collapse"><i class="mdi-navigation-menu"></i></li>
			 <ul id="slide-out" class="side-nav">
			<li><a href="#!">Categoria</a></li>
			<li><a href="#!">Categoria</a></li>
			<li><a href="#!">Categoria</a></li>
			<li><a href="#!">Categoria</a></li>
			<li><a href="#!">Categoria</a></li>
			<li><a href="#!">Categoria</a></li>
			<li><a href="#!">Categoria</a></li>
			<li><a href="#!">Categoria</a></li>
			<li><a href="#!">Categoria</a></li>
			<li><a href="#!">Categoria</a></li>
			<li><a href="#!">Categoria</a></li>
			<li><a href="#!">Categoria</a></li>
			<li><a href="#!">Categoria</a></li>
			<li><a href="#!">Categoria</a></li>
			<li><a href="#!">Categoria</a></li>
			<li><a href="#!">Categoria</a></li>
			<li><a href="#!">Categoria</a></li>
			<li><a href="#!">Categoria</a></li>
			<li><a href="#!">Categoria</a></li>
			<li><a href="#!">Categoria</a></li>
			<li><a href="#!">Categoria</a></li>
			<li><a href="#!">Categoria</a></li>
			<li><a href="#!">Categoria</a></li>
			<li><a href="#!">Categoria</a></li>
			<li><a href="#!">Categoria</a></li>
			<li><a href="#!">Categoria</a></li>
			</ul>
			<script>$('.button-collapse').sideNav({
			menuWidth: 240, // Predefinito 240
			edge: 'right', // Cambi la posizione d'origine
			}
			);</script>

**Comment by Master-Antonio** [comment]
http://pastebin.com/Z4Qzi5kY
ext ext ext.

**Comment by Master-Antonio** [comment]
@acburst  So?

**Comment by fega** [comment]
@Master-Antonio 
Could you check if this is still an issue with the latest version?

Closed due inactivity, feel free to reopen it if it is still necessary.
