### ISSUE TITLE
Select Materialize doesnt work using ng-repeat angular. 

### ISSUE THREAD

**Issue by bylinggha** [Dogfalo/materialize#2062]
its my source:
![1](https://cloud.githubusercontent.com/assets/10545136/9988590/06ce134a-607c-11e5-8e68-a7e10894d55d.png)

its my result:
![1](https://cloud.githubusercontent.com/assets/10545136/9988623/579f2552-607c-11e5-9c71-6a83e0fef3fc.png)

After inspect Element: 
![1](https://cloud.githubusercontent.com/assets/10545136/9988658/a984fc20-607c-11e5-8244-8af613c8cca6.png)

if i look the select option is work but why UL not repeat like select.

Thanks.

**Comment by bylinggha** [comment]
up

**Comment by tiagoovieira** [comment]
@bylinggha, Materializecss when initializes the material_select the value of `noTelp` is empty, you have to `$('select').material_select();` after `$scope.noTelp` is updated with the new values
