### ISSUE TITLE
0.97.1 Roboto font weight (Chrome) problem.

### ISSUE THREAD

**Issue by lukaspijak** [Dogfalo/materialize#2063]
In sass/components/_roboto.scss atribute local() causes problem with load font (weight: 200, 300, 400) (Chrome 45) .

**Comment by carlosperate** [comment]
Could you be more specific?

**Comment by lukaspijak** [comment]
Just not working font-weight 200, 300 and 400 at Chrome 45 for Windows 10.

**Comment by lukaspijak** [comment]
Solution is remove local atribute from definition.

**Comment by DanielRuf** [comment]
Do you have all the weights /variants of Roboto locally installed?
