### ISSUE TITLE
Feature Request: allow HTML in tooltips

### ISSUE THREAD

**Issue by k4kfh** [Dogfalo/materialize#2064]
I'd like to see the ability to use normal HTML in a tooltip, particularly because it would mean you would be able to use buttons. I could make a UI where I could hover over something and an "EDIT" or "CLOSE" button would appear. I think this would be useful, anyone else?

**Comment by TyrionGraphiste** [comment]
You just have to change the line 59 into the tooltip.js file to :

    newTooltip.children('span').html(origin.attr('data-tooltip'));

**Comment by carlosperate** [comment]
Duplicate of https://github.com/Dogfalo/materialize/issues/1537.

**Comment by drusepth** [comment]
Curious: why is this not the default behavior?

**Comment by k4kfh** [comment]
I'm not really sure, that's what I was wondering. Seems easier to have a
way to *disable *it than to enable it.
