### ISSUE TITLE
Feature Request: Vertical Button Group

### ISSUE THREAD

**Issue by rbizarra** [Dogfalo/materialize#2065]
I'm thinking that it might be nice to have an easy way to create a vertical button group, just like we have in other frameworks.

**Comment by TyrionGraphiste** [comment]
I don't see what you mean by "vertical button group". Could you add a codeopen or jsfiddle to your opening issue please ?

**Comment by badaro42** [comment]
A collection of buttons alligned vertically, like these in this image: https://i.imgur.com/rRe7Ps5.png
