### ISSUE TITLE
Datepicker Focuses when Changing Browser Tabs (Chrome 45)

### ISSUE THREAD

**Issue by seanmhanson** [Dogfalo/materialize#2067]
The Datepicker reappears after being triggered and dismissed when navigating away from, and back to an active tab. This can be replicated with the docs (http://materializecss.com/forms.html#date-picker):

1. Click the input to trigger the datepicker
2. Click away to dismiss the datepicker
3. Change tabs to another website
4. Change back to the docs. The datepicker is now opened erroneously.

**Comment by seanmhanson** [comment]
It looks like this stems from pickadate.js, and that adding the following as an argument will fix this. Why not make this a default behavior and fix this when used in materialize?

`onClose: function() {
        $(document.activeElement).blur();
    }`

example in context:
````
$('.datepicker').pickadate({
    selectMonths: false,
    selectYears: false,
    onClose: function() {
        $(document.activeElement).blur();
    }
});
````

**Comment by serkandurusoy** [comment]
This had actually been reported over at #1316 and the `onClose` workaround has been suggested.

**Comment by Dogfalo** [comment]
Losing keyboard focus is not a good solution to the problem
