### ISSUE TITLE
Doesn't work as expected.

### ISSUE THREAD

**Issue by trusktr** [Dogfalo/materialize#2068]
I have this markup (in React):

```html
                        <a className="btn-floating btn-medium waves-effect waves-light red">
                            <i className="material-icons">add</i>
                        </a>
```

which results in the red button at the top left:

![screenshot from 2015-09-21 14-01-56](https://cloud.githubusercontent.com/assets/297678/10004960/554424f0-6069-11e5-8990-0e91918873d5.png)

The words aren't converted to a plus symbol, it just says "ADD". Also, the CSS styles seems to mess up the text below it (although the styles aren't materialize-related).

I have 

```html
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/0.97.1/css/materialize.min.css">
    <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/0.97.1/js/materialize.min.js"></script>
```

in the header to load Materialize. Why won't it convert to a plus sign? It also messes up the layout of the text in the white area (there are no materialize-related classes being used there).

**Comment by msolters** [comment]
For the icons, [the Materialize docs](http://materializecss.com/icons.html) state (although personally I too, would expect these to be included out of the box) that you must add the following to your `<head>` to actually get the Materialize icon assets:

```
  <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
```

**Comment by JulianKingman** [comment]
Thanks @msolters, that was both unexpected and very helpful.
