### ISSUE TITLE
Add avatar, icon and checkbox area inside collections

### ISSUE THREAD

**Issue by alearcy** [Dogfalo/materialize#207]
Hi! is it possible to add elements (avatar, left icons or checkbox) inside collections list? Like this:
![listgroup](https://cloud.githubusercontent.com/assets/5402295/5350252/5ebfb084-7f42-11e4-9f36-3e868ebc33dd.png)

thanks ;-)

**Comment by acburst** [comment]
Fixed in 4f80fb3dc4142490ed88bfff57d0f2bbb1c57eb3
