### ISSUE TITLE
Fix "Uncaught TypeError: Cannot read property '0' of undefined" with input[type=range] and at least Chrome

### ISSUE THREAD

**Issue by MeMyselfI** [Dogfalo/materialize#2072]
You will get this error with the current Chrome (Desktop, Windows) using the range slider.

Problem is that an input event does not have a pageX:
  
  $(document).on('input mousedown touchstart', range_type, function(e) {
  ...
   if(e.pageX === undefined || e.pageX === null){//mobile
         left = e.originalEvent.touches[0].pageX - $(this).offset().left;
      }

**Comment by qm3ster** [comment]
+1
Desktop Chrome, can confirm
What would be a better detector of desktop vs mobile?
(And shouldn't that kind of thing be handled at the beginning of the file and used from a variable hereafter?)

**Comment by MeMyselfI** [comment]
It's not a question of detecting desktop vs. mobile. There is no coordinate in an input event so a simple

if (e.type == 'input') return;

before the detection of coordinates will do.

**Comment by qm3ster** [comment]
Okay, then how come it actually works on desktop?
How come both mutually exclusive options get triggered?

**Comment by MeMyselfI** [comment]
There's another onmousemove event handler which does the update.

**Comment by qm3ster** [comment]
Maybe I am just a potato, but in the 'input mousedown touchstart' handler, if you put a breakpoint in the "else", that gets hit as well.

**Comment by davedawkins** [comment]
Also getting this issue.

**Comment by acburst** [comment]
Fixed in 53246af
