### ISSUE TITLE
Change z-index of input[type=range] thumb

### ISSUE THREAD

**Issue by MeMyselfI** [Dogfalo/materialize#2074]
The thumb of the input does not have a z-index, meaning that if a label follows (which is the default order in for the form fields here) the thumb will be underneath. Adding a z-index:1 should prevent this.

**Comment by fega** [comment]
Please provide a way to reproduce it. like a codepen or  a fiddle snippet
Closed due inactivity, feel free to reopen it if it is still necessary.
