### ISSUE TITLE
Enter the date manual

### ISSUE THREAD

**Issue by cskiwi** [Dogfalo/materialize#2076]
hi,

I'm wondering if there is an option to input the date manual so not the datepicker.
But if the user wants it would still be available.

Mostly because I'm using it for defining a time period, which can be 5 year, so then you would have to click 60 times on the month thingy, so it would be easier if you could just lower the year number manually

**Comment by carlosperate** [comment]
Datepicker is based on http://amsul.ca/pickadate.js/, so you can have a look there and see if there is any option.

**Comment by tomscholz** [comment]
Solution: http://amsul.ca/pickadate.js/date/#html5-attributes
