### ISSUE TITLE
Checkbox and Radios do not follow Material spec

### ISSUE THREAD

**Issue by wopian** [Dogfalo/materialize#208]
Materialize is still using the old checkbox design:
![](http://i.imgur.com/6MtMejE.png)
Material Spec:
![](http://i.imgur.com/yDgfm7z.png)

Radios are also missing the spacing between the outline and the selected circle filler.
![](http://i.imgur.com/kqzLyBa.png)
Material Spec:
![](http://i.imgur.com/VjQsH1f.png)

**Comment by coliff** [comment]
Just chiming in to mention that Google's Polymer project have now updated their paper-checkbox to match the Material Design. Hope to see these changes in Materialize.
https://blog.polymer-project.org/releases/2015/01/28/release-0.5.4/
https://www.polymer-project.org/components/paper-checkbox/demo.html

**Comment by Dogfalo** [comment]
Added checkbox style in c75eec50e75146e0e3fc8937ca633aafc23eff31
