### ISSUE TITLE
V 0.97.1 -> Cards on ipad big bug

### ISSUE THREAD

**Issue by ibrainventures** [Dogfalo/materialize#2080]
Card size small,
Card size medium,
Card size large 

Crashed ... Title , text .. Are completly trashed ...

http://materializecss.com/cards.html

**Comment by Zexorz** [comment]
Any screen?

**Comment by ibrainventures** [comment]
![materializecardscrasg](https://cloud.githubusercontent.com/assets/8803626/10076756/5869fd46-62dd-11e5-8fcb-ae3b83723784.jpg)

**Comment by ibrainventures** [comment]
sure

**Comment by ibrainventures** [comment]
![materializecardscras3](https://cloud.githubusercontent.com/assets/8803626/10076957/618285e6-62de-11e5-983c-491d8b202c20.jpg)

**Comment by acburst** [comment]
This is not an iPad specific problem, just a screen size related problem. 

I've adjusted the height values to better adapt to multiple sizes in b6d5f86
