### ISSUE TITLE
V 0.97.1 -> iOs Safari -> Swipe right on Slider ->  resizes / microsizes the complete screen layout 

### ISSUE THREAD

**Issue by ibrainventures** [Dogfalo/materialize#2084]
if i swipe right on the materialize slider (and my finger is near the right bezel edge) the complete screensize is stepwise  minimized .. and the screen looks terrible ...

screen:

![img_1864](https://cloud.githubusercontent.com/assets/8803626/10098907/30d2a280-6385-11e5-9eb2-c4d87ee0c565.PNG)

the left swipe is okay, it looks like it should look:

![img_1871](https://cloud.githubusercontent.com/assets/8803626/10098918/48577a5c-6385-11e5-816f-4edfcc0f0b09.PNG)

**Comment by fega** [comment]
Could you check if this is still an issue with the last version?
Closed due inactivity, feel free to reopen it if it is still necessary.
