### ISSUE TITLE
Dropdown just refusing to show up?

### ISSUE THREAD

**Issue by k4kfh** [Dogfalo/materialize#2090]
I'm trying to use MaterializeCSS in a JS/HTML app that I'm writing and I've run into a snag. No matter what I do, the dropdown select box just won't work. If I use the browser-default class, it shows up. Without that though, nothing shows. Nothing at all, it's like the HTML elements don't even exist.

I'm using Materialize 0.97.1 straight off the site as of tonight.

Here is my HTML for this area of the page, you should be able to ignore everything but the <select> tag. I also tried copy/paste from the documentation and it doesn't work that way either.

``` javascript
    <div class="input-field col s6">
    <select>
    <option>EMD FT</option>
    <option>EMD F7-A</option>
    <option>EMD GP15-1</option>
    </select>
    </div>
```

**Comment by zevsuld** [comment]
@k4kfh hi there! 
did you find a way to fix it? I have same problem here.
My case browser-default does not even display dropdown select box. I'm using Materialize 0.97.0.

**Comment by k4kfh** [comment]
@zevsuld, I haven't messed with the drop down since posting this issue because I invented a new way to structure my UI, however I found that compiling Materialize from SASS fixed an issue I was having with the Chips feature. I'm not sure if this would fix the drop down issue, and I can't test right now, but it's worth a shot.

**Comment by zevsuld** [comment]
@k4kfh thank you. I found an answer on stackoverflow, It works perfectly.
If there someone who have this issue please read this. 
https://stackoverflow.com/questions/28258106/materialize-css-select-doesnt-seem-to-render

**Comment by slmatthiesen** [comment]
Thanks!!!

**Comment by allebd** [comment]
This below solved it for me

$(document).ready(function(){
    $('select').not('.disabled').formSelect();
});
