### ISSUE TITLE
using material box for card images

### ISSUE THREAD

**Issue by alisabzevari** [Dogfalo/materialize#2091]
I am trying to use material box for card images. My target is to click on card image and view it fullscreen.
```html
<div class="card large hoverable">
    <div class="card-image">
      <img materialize="" class="materialboxed" width="650" src.bind="movie.poster">
    </div>
    <div class="card-content">
      <span class="card-title activator grey-text text-darken-4">${movie.title + " - " + movie.imdbRating}<i class="material-icons right">more_vert</i></span>
      <p>${movie.genre.join(', ')}</p>
    </div>
    <div class="card-reveal">
      <span class="card-title grey-text text-darken-4">${movie.title}<i class="material-icons right">close</i></span>
      <p>${movie.director}</p>
      <p>${movie.genre.join(', ')}</p>
      <p>${movie.actors.join(', ')}</p>
      <p>${movie.plot}</p>
    </div>
  </div>
```
The problem is that it could not make the image container bigger. So the image will be zoomed but because the container is small it couldn't show all of the image.

**Comment by emileae** [comment]
I'm getting the same issue and I'm reluctant to modify materialbox.js

**Comment by acburst** [comment]
override the overflow: hidden on the outer card class. Please try to search in previous / closed issues. This is a very common issue.

**Comment by acburst** [comment]
Fixed in 37c9d7941d6fa0b1a35e055b70d34e6afe634e4c

If you don't want to remove overflow: hidden yourself, materialbox will now look for ancestors with overflow hidden and remove that attribute and then reset them to their original overflow when you exit out of the materialbox.

**Comment by emileae** [comment]
Wow, thanks for the super fast response, your latest commit has fixed my issue.

**Comment by alisabzevari** [comment]
Works like a charm. Thanks!

**Comment by z4ki** [comment]
is there an example how to remove hidden  overlow
