### ISSUE TITLE
Materialize modal trigger

### ISSUE THREAD

**Issue by JPaulPunzalan** [Dogfalo/materialize#2092]
Is it really required to use html tags (button, a) to trigger modal using javascript?

I'm planning to open the modal using only one line of javascript just like opening a bootstrap modal but my app only shows me the dark overlay. It doesn't show the modal at all.

The javascript that I'm using is the one in the website:

$('#modal1').openModal();

Any help would be appreciated haha I'm stuck since I prefer using modals to lessen the user's clicks! Thanks!

**Comment by TheRinseM** [comment]
$(document).on('load',function() { $("#modal1").openModal();}); ?

**Comment by acburst** [comment]
Can you post a codepen?

**Comment by JPaulPunzalan** [comment]
$(document).on('load',function() { 
   $("#modal1").openModal();
});

This code only reloads my web page. I'm a .net developer and I'm trying to open the modal from codebehind since I passed the 'id' data there through an **ASP LINKBUTTON**. In bootstrap, it works using only this code

$("#modal1").modal("show");

But now I started using Matrialize CSS and that logic of using the one-liner script

$("#modal1").openModal();

doesn't seem to apply/function **when you're not using HTML tags (button and a) as modal triggers.**. :(

**Comment by JPaulPunzalan** [comment]
Nevermind, guys! It is just that I forgot to put a code that would close the modal!

Hence, $("#modal1").closeModal();

 So sorry!!! Thanks for the help too though!!!

**Comment by rupakrockthecse100** [comment]
Hi 
what is the final solution to the issue?

**Comment by rupakrockthecse100** [comment]
This is javascript code :
function openLoginVerificationModal() {
                 $('#modalLoginOTPVerify').modal('open');
                
        }

Now code in code behind is :
ScriptManager.RegisterStartupScript(this, this.GetType(), "Pop", "openLoginVerificationModal();", true);

But it is not working.
For javascript alert, bootstrap modal it is working.
