### ISSUE TITLE
Button text gets cut off when icon is wrapped in a div

### ISSUE THREAD

**Issue by exload** [Dogfalo/materialize#2094]
If you have `<a class="waves-effect waves-light btn"><div><i class="material-icons left">cloud</i></div>button</a>` you will see the button does not expand to fit its content as it should. The selectors properly apply styles to the i, however, something else must be happening that I am not noticing causing the text to get cut off.

Here is a working demo. 

https://jsbin.com/hetucowono/edit?html,output

**Comment by acburst** [comment]
Why do you have a random div wrapping the icon? remove that and it works fine.
```
<a class="waves-effect waves-light btn"><i class="material-icons left">cloud</i>working</a>
<a class="waves-effect waves-light btn"><i class="material-icons left">cloud</i>not working</a>
```

**Comment by exload** [comment]
I realize that but I am basically trying to create a web component library wrapper around this library. Part of the requirements for creating a web component is to have a root node. The root node is that div.

**Comment by acburst** [comment]
Well if you style that root node differently it can work. Does it have to be a div? If you replace it with a span it will work. Basically that node has to have `display: inline`

**Comment by exload** [comment]
Awesome, that worked perfectly. Thanks!
