### ISSUE TITLE
Adding the Pushpin feature - It changes the width of any other elements bellow the tabs 

### ISSUE THREAD

**Issue by raymundosaraiva** [Dogfalo/materialize#2095]
![screen shot 2015-09-28 at 12 43 46 am](https://cloud.githubusercontent.com/assets/13022429/10127561/16e56bb8-657a-11e5-9147-d3b2826f2d61.png)
![screen shot 2015-09-28 at 12 43 57 am](https://cloud.githubusercontent.com/assets/13022429/10127562/17159054-657a-11e5-9792-69ce14f0e361.png)

As you can see the size of the list below is affected.

From now this solved my problem:
    function updateElements(objects, scrolled) {
              objects.each(function () {
                // Add position fixed (because its between top and bottom)
                if (options.top <= scrolled && options.bottom >= scrolled && !$(this).hasClass('pinned')) {
                  removePinClasses($(this));
                  $(this).css('top', options.offset);
                  $(this).css('width', '100%'); // RIGHT HERE
                 $(this).addClass('pinned');
            }

You guys should check on that.

**Comment by jstoup111** [comment]
Not sure if you meant to close this. I'm using meteor and it get packaged up. Unfortunately it makes it rather difficult to monkey patch so that it works appropriately. Any work on this?
