### ISSUE TITLE
Input field error wraps if longer than associated label

### ISSUE THREAD

**Issue by theberengersniper** [Dogfalo/materialize#2100]
If the user defines an error message against an input field, the message will wrap because it's constrained by the width of the label element.

In my case the solution is to set a width of 100% on the label, thereby allowing the label and its error message to fill the available container width.

**Comment by acburst** [comment]
Can you post a codepen?

**Comment by theberengersniper** [comment]
Hi there, the issue is present in this fiddle: https://jsfiddle.net/fraserm/sr8abjjg/

**Comment by Dogfalo** [comment]
This has been fixed and is in v0.97.5

**Comment by fahimk** [comment]
@Dogfalo seeing this same issue in 0.97.6
