### ISSUE TITLE
Error text scales with the field label

### ISSUE THREAD

**Issue by theberengersniper** [Dogfalo/materialize#2101]
In a scenario where I'm validating a text field (that isn't allowed to be empty), as soon as I hit the submit button the validation runs, fails and subsequently displays the error message (as defined through the data-error attribute). The problem is, because the field is also empty, taking focus out the field by clicking submit causes the field label to animate back into its normal empty position, which also causes the associated error message to scale and move.
![field error problem](https://cloud.githubusercontent.com/assets/912384/10169781/99c3f134-66ca-11e5-91ea-726bf081915b.png)

**Comment by dcoferraz** [comment]
@theberengersniper , could you show a codepen example of the issue?

We can help you better that way!

**Comment by theberengersniper** [comment]
Hi there, here's a fiddle with the issue present: https://jsfiddle.net/fraserm/sr8abjjg/

**Comment by dcoferraz** [comment]
hey @theberengersniper

I saw that the issue is that there is no width for the element. It's out-of-the-box giving this error.

I made a quick fix for you here: https://jsfiddle.net/u9not0dg/

It's not a solution! The team should see this if there isn't something that could be fixed! :)

**Comment by luanfonceca** [comment]
I just got the same problem right now.

There is a "problem" in your fix @dcoferraz, if we have a text bigger than 150px?
I think it should have the same width as the input has.

**Comment by Bound3R** [comment]
I can fix using this line in sass
```sass
// [Fix] Text inputs custom error message
input[type=text],
input[type=password],
input[type=email],
input[type=url],
input[type=time],
input[type=date],
input[type=datetime-local],
input[type=tel],
input[type=number],
input[type=search],
textarea.materialize-textarea {
  &.valid + label:after,
  &.invalid + label:after,
  &:focus.valid + label:after,
  &:focus.invalid + label:after {
    white-space: pre;
  }
}```

**Comment by luanfonceca** [comment]
Its work for me @Bound3R!

**Comment by dcoferraz** [comment]
Indeed it was not a solution @luanfonceca, as I mentioned, but it's great seeing that @Bound3R came to a more mature solution!
Maybe this could be suggested for the team to upload in the project?
Thanks!

**Comment by theberengersniper** [comment]
These suggestions resolve the issue with the label wrapping, but not the problem described in this issue, which is (as you can see from the image above) that the error text scales with the field label when focus is removed from the field when there's no text in it.

**Comment by Bound3R** [comment]
@theberengersniper I understand, but I guess you're the one doing the validation.
is a slightly more complex error because the message does not have a specification for such cases ( empty error message ), however, you can try this solution although it is a little forced. 


SASS
```sass
// [Fix] Text inputs custom error message
input[type=text],
input[type=password],
input[type=email],
input[type=url],
input[type=time],
input[type=date],
input[type=datetime-local],
input[type=tel],
input[type=number],
input[type=search],
textarea.materialize-textarea {
  &.valid + label:after,
  &.invalid + label:after,
  &:focus.valid + label:after,
  &:focus.invalid + label:after {
    white-space: pre;
  }
  &.empty {
    &:not(:focus).valid + label:after,
    &:not(:focus).invalid + label:after {
      top: 2.8rem;
      
    } 
  }
}
```
jQuery
```javascript
$(document).ready(function(){
  $( '.input-field input' ).each(function(){
    ( $( this ).val()  == '' ) ? $( this ).addClass('empty') : $(this).removeClass('empty');
  });
  $( '.input-field input' ).on('focus blur ', function(){
    ( $( this ).val()  == '' ) ? $( this ).addClass('empty') : $(this).removeClass('empty');
  });
});
```

Live Demo
http://codepen.io/Bound3R/pen/YyNMre

> PD: I regret that the animation is bad, but I hope to help with this quick fix  :sweat_smile:

**Comment by Bound3R** [comment]
@theberengersniper, @luanfonceca, @dcoferraz someone tried the fix?

**Comment by WhyEee** [comment]
I tried @Bound3R's fix, but I wanted to get rid of the "glitchy" animation that's still left.
My own workaround is to add a blank placeholder to the input when adding the error message.

**Comment by Bound3R** [comment]
@WhyEee  understood, I'm dusting the snippet and see a more robust solution for out animation :+1:
