### ISSUE TITLE
Card reveal not closing on close.

### ISSUE THREAD

**Issue by tinker20** [Dogfalo/materialize#2103]
<div id="reveal" class="col-xs-12 col-sm-6 col-lg-9 row"> 

    <div class="col-sm-4 col-md-3 card card-division" ng-repeat="item in items">
          <div class="card-image waves-effect waves-block waves-light">
            <img class="activator responsive-img" ng-src="{{item.photo}}" >
          </div>
          <div class="card-content">
            <span class="card-title activator grey-text text-darken-4">{{item.name}}<i class="material-icons right">more_vert</i>
            </span>
            <p><b>{{item.price}}</b></p>
            <p><a class="btn btn-sm btn-primary btn-raised right-align" ng-click="addToCart(item)"><i class="material-icons">add</i></a></p>
          </div>
          <div class="card-reveal">
            <span class="card-title grey-text text-darken-4">{item.name}}<i class="material-icons right">close</i></span>
            <p>{{item.description}}</p>
          </div>
              </div>
        </div>

I have the following code for the card-reveal. The reveal part doesn't closes when the <b>close</b> is clicked. Instead it stays on the same position till the page is refreshed. How to fix this?

Thanks in advance.

**Comment by acburst** [comment]
Your code is not complete. Try replicating your problem in a codepen. 

I tried recreating your code here:
```
<div class="row">
  <div class="card col s6">
    <div class="card-content ">
      <span class="card-title activator grey-text text-darken-4">{{item.name}}<i class="material-icons right">more_vert</i>
      </span>
      <p><b>{{item.price}}</b></p>
      <p><a class="btn btn-sm btn-primary btn-raised right-align" ng-click="addToCart(item)"><i class="material-icons">add</i></a></p>
    </div>
    <div class="card-reveal">
      <span class="card-title grey-text text-darken-4">{item.name}}<i class="material-icons right">close</i></span>
      <p>{{item.description}}</p>
    </div>
  </div>
</div>
```

And it works for me.
