### ISSUE TITLE
Modal "shown" & "hidden" events?

### ISSUE THREAD

**Issue by FinnLawrence** [Dogfalo/materialize#2106]
Hey team, love the framework!

Was wondering if there was a plan for Modals to fire events like the Bootstrap ones do http://getbootstrap.com/javascript/#modals-events

Would be invaluable for a few projects that I'm working on!

Cheers & thanks for all your hard work :)

**Comment by Dogfalo** [comment]
There are callback functions already on the documentation

**Comment by FinnLawrence** [comment]
Perfect! Didn't see that down in the options, thanks!
