### ISSUE TITLE
Uncaught TypeError: Cannot set property 'guid' of undefined

### ISSUE THREAD

**Issue by calvinfu1128** [Dogfalo/materialize#2107]
Hi,

My project is upgraded to Meteor v1.2 and I receive Uncaught TypeError: Cannot set property 'guid' of undefined, which breaks my project.

The problem solved if I remove Materialize from my project.

Appreciated for help.

Cheers,

Calvin

**Comment by 3210jr** [comment]
I also found that because of the new changes in Meteor 1.2, it becomes necessary for the authors of packages to make certain changes to their projects. I hope the materialize team can get to this soon.

To keep developing, you could remove the package and download the source files which you will then simply include into your project. You will face some minor glitches here and there but nothing too difficult.

Oh, btw, I am a big fan of materialize, good job guys!

**Comment by rernst76** [comment]
I ran into this issue as well and got around it by using an older version of the Materialize package:
`meteor add materialize:materialize@= 0.97.0`

**Comment by nitya** [comment]
/sub

I saw the exact same behavior. Upgrading to Materialize 0.97.1 breaks existing projects. I'd like to hear more about @3210jr  observation that this could be related to changes in Meteor 1.2? 

I'm sticking with 0.97.0 for now but look forward to hearing how/when to make the upgrade to 0.97.1 correctly.

**Comment by awhitford** [comment]
+1

Adding Materialize 0.97.1 (latest) broke my project:  ```meteor add materialize:materialize```

```
Uncaught TypeError: Cannot set property 'guid' of undefined [materialize_materialize.js:38]
Uncaught TypeError: Cannot read property 'Materialize' of undefined [global-imports.js:12]
```

But then rolling back to 0.97.0 is OK...  Thanks for the tip.

_(But now I am afraid to update...)_

**Comment by awhitford** [comment]
BTW...  Recreating this is trivial:
1. Create a new project:  ```meteor create myproj```
2. Start it, it runs fine:  ```cd myproj``` and then ```meteor```
3. Add materialize:  ```meteor add materialize:materialize``` and then ```meteor``` and now the app is broken.

**Comment by awhitford** [comment]
This looks like a **duplicate** of issue #2037.

**Comment by agoutgex** [comment]
I confirm, same issue for me.
rernst76's suggestion made my app work again :
`meteor add materialize:materialize@=0.97.0`
Metrialize looks gorgeous guys, I can't wait to work on it!

**Comment by fabyeah** [comment]
This seems to be fixed now. Can somebody confirm?

**Comment by nitya** [comment]
I noticed that upgrading to the latest version (0.97.2) -- causes the issue to go away. The good thing is that upgrading also gives you access to the newer features (e.g., chips, breadcrumbs). The downside is that the 0.97.2 version seems to break the mdi- (material design icons) classes (e.g., mdi-navigation-menu doesn't work) -- but overall we decided it was worth moving up.
