### ISSUE TITLE
Icons with underscore are not displayed well on small screen in webapp

### ISSUE THREAD

**Issue by ga2** [Dogfalo/materialize#2109]
Hello,
first of all, thank you Materialize Team for this wonderful tool

I have an issue that regards the icons: I am building a website using the web view widget on Android.
The website is made of webpages inside the app (is not online - for the moment)
The problem is while I can see all the icons well on a galaxy tab 4 and on chrome for windows, icons with underscore are not show or wrong in smaller screens (Asus Zenfone 5, android 4.4)

For example if I use 
[i class="material-icons left"]keyboard_tab[/i]example (i am using this type of bracket instead angular to show the code)
it is OK in the two devices, instead on Asus I see "keyboard" icon and "tab" icon

"perm_identity" is not shown at all (always on smaller screen)

So I suppose there are some problems with underscores

thank you

![senza titolo-1](https://cloud.githubusercontent.com/assets/6691230/10222407/11590f92-6854-11e5-96b6-51ccba7e4496.png)

**Comment by thedesignable** [comment]
@ga2 provide a screenshot or something to understand what you exactly you are referring to. It won't be possible to suggest anything unless there is something to analyse.

**Comment by ga2** [comment]
ok @thedesignable I uploaded a screenshot, thank you for the suggestion

**Comment by thedesignable** [comment]
@ga2 Have you tried adding viewport under head in your index file?
also try the valign-wrapper class for UL and valign for LI's. That could do the trick

**Comment by ga2** [comment]
@thedesignable Of course I've tried but I didn't solve anything because the problem is based on underscores that makes the icons wrong NOT a problem of layout itself
Just look again at the difference between the icons near "logout" in zenfone and in galaxy; the code is the same for both, the problem is the naming of the icons that involve the use of underscore
In fact the icon "keyboard_tab" is read by smaller devices as "keyboard" and "tab"
the icon "perm_contact_calendar" is read, I suppose as "perm" and because doesn't exists an icon called "perm" it is not shown

**Comment by thedesignable** [comment]
@ga2 have you add the material-icons stylesheet to you project? 
Try using - instead of underscores and see if that works for you. 
update this if it works.

**Comment by ga2** [comment]
@thedesignable Is this the stylesheet are you talking about "fonts.googleapis.com/icon?family=Material+Icons"? If it is, yes I've included it
and using - insted _ hasn't helped me

The important thing is now I have reported this issues... until a fix, I will use other icons without _ ....

**Comment by essuraj** [comment]
the included icons work by this cheatsheet https://s3.amazonaws.com/kantan-dresssed-demos/demos/ives/blue_preview/007_icons@fa-lightbulb-o%252F004_mdi_icons.html

**Comment by tomscholz** [comment]
Can't seem to reproduce it. Please provide a codepen to illustrate your issue.
