### ISSUE TITLE
ScrollBar Hideen

### ISSUE THREAD

**Issue by ghost** [Dogfalo/materialize#2114]
![sem titulo](https://cloud.githubusercontent.com/assets/13270780/10261620/e2d4f1a8-6976-11e5-92ee-f6655d4d17fa.png)
Bottom of scrollbar is hide on Chrome

**Comment by carusogabriel** [comment]
Fixed this removing the following lines on _sideNav.scss:
8: height: calc(100% + 60px);
10: padding-bottom: 60px;
