### ISSUE TITLE
Add destroy method to accordion

### ISSUE THREAD

**Issue by MeMyselfI** [Dogfalo/materialize#2115]
Please add a destroy method to accordion.

**Comment by acburst** [comment]
Could you flesh out your issue a bit more? What exactly do you want in a destroy method and what problems does it solve? It's really hard to justify changing something for a one line description.

**Comment by MeMyselfI** [comment]
Sure. I use materiaize for a web application. Therefore I need to create and destroy widgets dynamically. If those widgets register listeners there will be most likely memory leaks when those listeners still points to dom elements.

**Comment by Mythli** [comment]
the same is true for almost all other components. using it with frameworks like react or ember is a pitty.

**Comment by MeMyselfI** [comment]
Any update to this major issue?

**Comment by Mythli** [comment]
Push

**Comment by tomscholz** [comment]
https://github.com/Dogfalo/materialize/issues/4522
