### ISSUE TITLE
Are there issues with modal-triggers being inside relatively positioned elements?

### ISSUE THREAD

**Issue by Itagiba** [Dogfalo/materialize#2116]
I have started to use materialize instead of bootstrap but have been running into a few issues. The Modal for example, if I place the trigger inside other elements i.e. cards containing ngRepeat, it no longer triggers the modal. So for example if I do the following:

```
div class="card-image waves-effect waves-block waves-light" ng-repeat="work in myWork">
                   <!--MODAL BUTTON-->
                  <a class="waves-effect waves-light btn modal-trigger" href="#modal1">Modal</a>
                  <img class="activator" src="images/sample-1.jpg">
                </div>
                <div class="card-content">
                ....etc.
```

Then the Modal is no longer visible. I also find it difficult to debbug in order to see what is happening, has anyone has had a chance to ply with this properly?

**Comment by acburst** [comment]
Sorry im a little confused on what you are trying to do. Do you want to repeat cards and have modal triggers in each to trigger 1 modal or each of them trigger their own modal?

**Comment by Itagiba** [comment]
Sorry, my code is split in several parts so I cannot use a codepen. Basically  I have dynamic data pulled from firebase like so:

``````
             <div id="postItems" ng-repeat="work in myWork">
             <!--//THIS SHOUD TRIGGER A MODAL TO EDIT THE CASE STUDY-->
               <a class="waves-effect waves-light btn modal-trigger" href="#modal1">Modal</a>
               <div class="col s12 m6"  >
              <div class="card small">
                <div class="card-image waves-effect waves-block waves-light">
                  <img class="activator" src="images/sample-1.jpg">
                </div>
                <div class="card-content">
                  <span class="card-title activator grey-text text-darken-4">{{work.Title}}<i class="material-icons right">more_vert</i></span>
                  <p><a href="#">Read More</a></p>
                  <p>Client: {{work.Client}} &nbsp; Launch: {{work.Launch | date:'mediumDate'}}</p>
                </div>
                <div class="card-reveal">
                  <span class="card-title grey-text text-darken-4">{{work.Title}}<i class="material-icons right">close</i></span>
                  <div>{{work.Summary}}</div>
                </div>
            </div>
        </div>

So it should be one Modal template for all but with a floating button on each to enable you to edit it. For some reason, as soon as I place the button inside the ng-repeat, the Modal stops working. I hope that this is clear.

**Comment by Itagiba** [comment]
I am still stuck with the issue, it looks like it will be easier to go back to good ol' reliable bootstrap. For some reason if you place the modal trigger inside an ng-repeat it will not work. I have added boostrap to my existing materialized web app but it is messy to use both. there are some issues with the positioning of the modal window (bottom:0 and top:0 also need to be added). Anyway, if anyone manages to get it working with angularjs (repeat), let me know.

**Comment by svangordon** [comment]
It's not the positioning, it's the ng-repeat. The easiest way to do this is to trigger the modal from an ng-click even using jQuery.  So your a tag will look like this :

`<a href="" ng-click="modalTrigger()" class="modal-trigger title">Check out our foo</a>`

and then the ng-click looks like this :

`$scope.modalTrigger = function () {
    $('#modalName').openModal()
}`

You can see a fuller example at [CodePly](http://blog.codeply.com/2015/04/09/5-material-design-examples-using-materializecss/) (the last example). There are a couple of other ways that you can solve this, like making a [custom directive](http://stackoverflow.com/questions/32925642/materialize-button-inside-ng-repeat-not-triggering-modal), and Angular Materialize's [custom modal directive](http://krescruz.github.io/angular-materialize/#modals) may solve the problem.  But quite frankly, I think that solution I've outlined above is the simplest.

**Comment by SunandoSamaddar** [comment]
@svangordon Thanks man. Smooth it was after applying the changes you've pointed out.

**Comment by anirban2015** [comment]
use openModel() instead of model()
