### ISSUE TITLE
Auto-resize not working in accordion and tabs

### ISSUE THREAD

**Issue by patrick-riemer** [Dogfalo/materialize#2119]
When the text area is implemented in a accordion or tab, the auto-resize is not working, even after clicking into the field. Only pressing a key inside the field seems to force the auto-resize.

**Comment by kybd92** [comment]
Hi Patrick,

Did you find a solution to this problem? I am having trouble with this.

Thanks

**Comment by patrick-riemer** [comment]
This bug was in an old version. I am not sure if it persists in the latest version. You can try to trigger the autoresize manually (I think that is what I've done to that time) via JS.

**Comment by kybd92** [comment]
Triggering the autoresize manually worked! Thanks
