### ISSUE TITLE
tabs for external links?

### ISSUE THREAD

**Issue by kumar91gopi** [Dogfalo/materialize#2121]
I'm working with the Materializecss front-end framework and I'm trying to use tabs for moving along external links but it seems like it doesn't work. The examples are for content with a ID inside the same page we're on. How can I solve this? Thank you.

**Comment by msolters** [comment]
Can you give more detail?  An example use case?

If you mean "Can I use a tab link to redirect the user to an entirely new web page," then that is trivially easy.

If you mean, "Can I use a tab to load a different web page inside the tab content container," then that is also fairly easy but will require some AJAX in your application code.

If you mean, "Can I use a tab to control tab content on a different web page," then that is also possible but it won't be as easy.

But I do not yet understand what you're attempting to do.

**Comment by kumar91gopi** [comment]
I want a tab link to redirect a user to entirely new web page.
I tried adding the url path in the href of the tabs but it didn't worked out.

**Comment by msolters** [comment]
Gotcha, so it's *probably* an `event.preventDefault()` type situation in the tab-click handler.  The only real semantic way we could get around this is to introduce a CSS class that could be added to individual tabs that would essentially block the click event handler so that the default `href` behaviour would take over.

**Comment by msolters** [comment]
I found a better work-around for the above PR:

If you just add `target="_self"` or `target="_blank"` to the `<a>` tag inside the tab, Materialize will know that it's a hyperlink to an external resource, and it will honour the requested behaviour.  All other tabs will continue to behave as expected.

With this solution, the internal tab content for an external link will be blank.  I hope that's OK.  It's hard to think of a use case where you would want both -- I think this is the most logical way to preserve both the Materialize tab behaviour as well as still be able to easily access the underlying default HTML5 behaviour.

**Comment by kumar91gopi** [comment]
<a class="teal-text active" target="_blank" href="https://xyz.com">Profile</a>
i already tried this but this too isn't working. i dont how to fix this.

**Comment by msolters** [comment]
*It's not a feature of Materialize yet*.  It's new code I just added in [this pull request](https://github.com/Dogfalo/materialize/pull/2124).  So at this point in time, adding `target` won't have any effect unless you pull that commit and then rebuild from source to try it out.

**Comment by alexenderjohanson** [comment]
Any ETA on when will this be released?

**Comment by Messi10AP** [comment]
When will this feature be released? @msolters

**Comment by msolters** [comment]
IDK, it is not my decision.  Someone from Materialize would have to (1) accept my PR and then (2) release a new version of Materialize. :\

If you want it right now, just merge my changes (https://github.com/Dogfalo/materialize/issues/2124) to your own codebase.

**Comment by AdiFahmi** [comment]
@msolters I'm new to JS, does your change is override-able?
I mean, can i make something like custom.js to override mateialize.js like in CSS?

So i still able to update to the lastest materialize.js version without have to modify it.

**Comment by msolters** [comment]
It's more complicated with Javascript.  It's possible, of course, to redefine objects after they've already been defined, but it's not at all recommended.  You must be very careful the order in which you modify your prototype structures -- and now you're sending more redundant code to the client that is never used.

In addition, this project uses a build procedure that essentially takes the parts that authors modify and then reduces them down to a handful of "minimized" master files that include everything.  Therefore, you have no choice but to merge in the [actual changes you like](https://github.com/Dogfalo/materialize/pull/2124/files) and then rebuild your own JS files.

**Comment by msolters** [comment]
It's not very hard though!  See the readme: https://github.com/Dogfalo/materialize/blob/master/CONTRIBUTING.md

**Comment by AdiFahmi** [comment]
@msolters yup, i know. But the problem is when the new version of materialize out, the change i made will gone. :cry:

**Comment by metalbote** [comment]
+1

**Comment by phu** [comment]
Since I need tabs for entirely non-JS hrefs, I worked around this by copying the `.tabs` styles from around line 7962 in materialize.css to another file and renaming that version of the class. Not a great solution, but at least now the JS doesn't railroad my links.

**Comment by shunjid** [comment]
> I found a better work-around for the above PR:
> 
> If you just add `target="_self"` or `target="_blank"` to the `<a>` tag inside the tab, Materialize will know that it's a hyperlink to an external resource, and it will honour the requested behaviour. All other tabs will continue to behave as expected.
> 
> With this solution, the internal tab content for an external link will be blank. I hope that's OK. It's hard to think of a use case where you would want both -- I think this is the most logical way to preserve both the Materialize tab behaviour as well as still be able to easily access the underlying default HTML5 behaviour.

Saved life even after 4 years
