### ISSUE TITLE
bower's bug

### ISSUE THREAD

**Issue by damiankaplewski** [Dogfalo/materialize#2123]
Hi. I had a problem with downloading all files from repo. When I wrote "bower install materialize" not installed .html files. I think there are important files. "npm install materialize-css" correct the error, but it's "npm" :P

**Comment by thedesignable** [comment]
Addition to @damiankaplewski 's description I am attaching the screenshot of file structure. http://screenshot.sh/m3eb2tmQwnhTS
![structure](https://cloud.githubusercontent.com/assets/10688315/10286100/b0f38962-6ba9-11e5-8af3-c5d1cc29f4ad.jpg)
The Bower package seems to be incomplete. This is required to be fixed.

**Comment by dali99** [comment]
I'm having a similar issue where the JS folder isnt downloaded.
