### ISSUE TITLE
Input does not check if value has been changed

### ISSUE THREAD

**Issue by kennyjwilli** [Dogfalo/materialize#2131]
If you change the value of an input programmatically, the input's label will not react to that change. The label should float up if the value of an input changes from blank to a non-blank value.

Demo: http://codepen.io/anon/pen/qOmyBJ?editors=101

**Comment by msolters** [comment]
What if you tried:

```js
function foo() {
  var input = $("#last_name");
  document.getElementById('last_name').value = 'foo bar';
  input.change(); // should theoretically update input state
}
```

The only way to really make this convenient might be like a `Matetialize` method for setting an input's value, and then running `.change()` on the input. Something along the lines of

```js
Materialize.prototype.setInputValue($input, value) {
  $input.val( value );
  $input.change();
}
```

**Comment by kennyjwilli** [comment]
That works. A convenience method would be okay but really not a great solution. I think a better solution would be to set up a dom property listener and automatically call `.change()` when the input's value is changed.

**Comment by msolters** [comment]
I agree, I do not like it either.

I'd love to see how a dom property listener as you described could be implemented.  AFAIK you can't set an event on dynamic property changing -- the thinking being that if you programmatically change an input's value, you might as well also take care of the associated logic maybe?  Either way it's inconvenient.

But short of adding a timeInterval and diff'ing the value I see no way of implementing a value listener.

**Comment by kennyjwilli** [comment]
Use a [MutationObserver](https://developer.mozilla.org/en-US/docs/Web/API/MutationObserver)?

**Comment by msolters** [comment]
OK!  Let me check this out, it looks very cool.

**Comment by msolters** [comment]
Unfortunately it seems `MutationObservers` will only react the same as other event solutions which are unsatisfactory -- it will catch the user typing, but setting the value using vanilla `.value` assignment or jQuery `.val()` do not produce any observer event.

**Comment by kennyjwilli** [comment]
Too bad. I suppose the convenience function is the best we can do for now..
