### ISSUE TITLE
Select dropdown label cut off (response to 633)

### ISSUE THREAD

**Issue by tzfrs** [Dogfalo/materialize#2133]
There is already a closed issue for this #633

You said, that it's the expected behaviour, but isn't it possible to have the same behaviour like

http://gregfranko.com/jquery.selectBoxIt.js/ ?

If the label is too long, the text is cut off, too (as in materializecss) but an elipsis is added and the drop down arrow is still visible. With materialize the text overlaps the arrow. 

Or if you think that the elipsis is ugly, what about this solution?

http://stackoverflow.com/a/24964722/2823419

**Comment by fega** [comment]
Please provide a way to reproduce it and see what do you want to achieve
Closed due inactivity, feel free to reopen it if it is still necessary

**Comment by tzfrs** [comment]
You are kidding me right? Answering after 1 1/2 years and just closing it because of inactivity. Inactivity by whom? By me or by you? Feels like EA. Back to Bootstrap then.

**Comment by DanielRuf** [comment]
The codepen info was added in February 2015.

https://github.com/Dogfalo/materialize/commit/cfb7fc3adc3526978177da7d1fe685b6bf4fcaea

We are cleaning up and you can still reopen / request to reopen.

So far a solution like you suggest makes sense.

**Comment by DanielRuf** [comment]
Also the suggested solution is still open https://github.com/Dogfalo/materialize/issues/4343
