### ISSUE TITLE
SideNav Problem on iOS 9.0.2 with Safari

### ISSUE THREAD

**Issue by proxymus** [Dogfalo/materialize#2134]
I've tried the SideNav Example on a test site. It is working on desktop browser but on mobile IOS devices (iPhone 4S, iPhone 5 and iPad 2 with IOS 9.0.2) the scaling is wrong (the text is too big). It is working with Chrome on that devices, but not with Safari.
I was able to find out that version 0.96.0 and 0.96.1 are working. It stopped working beginning with version 0.97.0.
```
<!DOCTYPE html>
<html>

<head>
<!--Import Google Icon Font-->
<link href="http://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
<!--Import materialize.css-->
<link rel="stylesheet" href="css/materialize.min.css" media="screen,projection"/>
<!--Let browser know website is optimized for mobile-->
<meta name="viewport" content="width=device-width, initial-scale=1.0"/>
<!--Import jQuery before materialize.js-->
<script type="text/javascript" src="https://code.jquery.com/jquery-2.1.1.min.js"></script>

<!-- Compiled and minified JavaScript -->
<script src="js/materialize.js"></script>
</head>
<body>
<nav>
  <ul class="right hide-on-med-and-down">
    <li><a href="#!">First Sidebar Link</a></li>
    <li><a href="#!">Second Sidebar Link</a></li>
  </ul>
  <ul id="slide-out" class="side-nav">
    <li><a href="#!">First Sidebar Link</a></li>
    <li><a href="#!">Second Sidebar Link</a></li>
  </ul>
  <a href="#" data-activates="slide-out" class="button-collapse"><i class="mdi-navigation-menu"></i></a>
</nav>
<script>
// Initialize collapse button
$(".button-collapse").sideNav();
// Initialize collapsible (uncomment the line below if you use the dropdown variation)
$('.collapsible').collapsible();
</script>
</body>
</html>
```

http://www.directupload.net/file/d/4133/sbz4yttx_png.htm

Any help is appreciated.

**Comment by proxymus** [comment]
Same issue as issue #2120

**Comment by proxymus** [comment]
It works when I add
```
maximum-scale=1"
```
to the ```<meta name="viewport"...>``` area.
```
<meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1" />
```

**Comment by TomFreudenberg** [comment]
Thanks, I can confirm that this works on my app as well as removing the overflow hidden state.

**Comment by clthck** [comment]
Thanks @proxymus. your solution worked like a charm for me.

**Comment by Jurjen-V** [comment]
The solution is not working for me. Using iphone 7plus safarie (IOS 13.3.1).
I made a [stackoverflow](https://stackoverflow.com/questions/60651175/materialize-collapsible-accordion-not-working-ios-13) question about it. Help is welcome.
