### ISSUE TITLE
Slider with 1 image still responds to touch on mobile

### ISSUE THREAD

**Issue by clselin** [Dogfalo/materialize#2136]
Hi 

I've created a slider. This is dynamically populated with content, so it may have 1 slide, or it may have many slides. 

In instances when there is only 1 slide, on desktop this is fine, but on mobile the Hammer touch events are still active and the user can swipe to the side - but all they can swipe to is empty grey. 

Is it possible to disable hammer in some simple way, or is there a feature to disable this I'm not seeing?

**Comment by fega** [comment]
Could you check if this is still an issue with the last version?

Closed due inactivity, feel free to reopen it if it is still necessary.
