### ISSUE TITLE
Modal with text input positioning on iPad

### ISSUE THREAD

**Issue by theberengersniper** [Dogfalo/materialize#2138]
If a modal containing a text field is displayed on an iPad, the modal is scrolled way off screen by the appearance of the iPad's keyboard. The user must then manually scroll the page to find the modal again.

It would be great if there was a way to detect a touch-based device and position the modal differently. This is kind of a clanger for me at the moment.

**Comment by whatda** [comment]
Same problem with Android here. So far I've only found tips for web-apps, but not for browser use.

**Comment by fega** [comment]
Please provide a way to visualize it. like a gif or picture
Closed due inactivity, feel free to reopen it if it is still necessary.
