### ISSUE TITLE
Closing modal by clicking overlay doesn't run Complete callback

### ISSUE THREAD

**Issue by Ecksters** [Dogfalo/materialize#2142]
In the documentation I don't see any way to configure a modal programmatically, it requires me to make an invisible open-modal button and then programmatically click that.

Looking at the sourcecode it appears you can use the same arguments as used for the leanModal button setup, but it's not in the docs anywhere.

**Comment by Ecksters** [comment]
Also, it appears that when you programatically close a modal with dismissible set to false, it doesn't close the overlay.

**Comment by msolters** [comment]
If you happen to be using this with Meteor, you should take a look at [MaterializeModal](http://materializemodal.meteor.com/).  It resolves quite a few of these problems.  Of course this won't be of use if you're using the vanilla JS out-of-the-box :(

**Comment by djom20** [comment]
I have the same problem, I try to invoke functions or code within the callback function complete, in the property leanModal, but the alert does not work like documentation. I have found in codepen a code where the above evidence. http://codepen.io/anon/pen/oXBKeg

**Comment by Dogfalo** [comment]
Fixed in 1d70a66a6fa484f9e44231c528a723106ad81371
