### ISSUE TITLE
Support for <input required>

### ISSUE THREAD

**Issue by MeMyselfI** [Dogfalo/materialize#2143]
Adding support for the required attribute should be quite easy to implement:

  window.validate_field = function(object) {
       ...
      var required = !!object.attr ('required');
      if (object.val().length === 0 && (object[0].validity.badInput === false && !required)) {
         ...

**Comment by garrypolley** [comment]
Are there plans to support his feature? It seems like a fairly common case.  I see https://github.com/Dogfalo/materialize/pull/3912 which may or may not fix it.

**Comment by Dogfalo** [comment]
Added in #4883
