### ISSUE TITLE
A suggestion for the CSS in container class

### ISSUE THREAD

**Issue by laichak** [Dogfalo/materialize#2145]
/\* 
Add min-width for smoother re-sizing of container width at break-points when user is re-sizing the desktop browser window.
*/

@media only screen and (min-width : 601px) {
    .container {
        width: 85%;
        min-width: 560px;
    }
}

@media only screen and (min-width : 993px) {
    .container {
        width: 70%;
        min-width: 955px;
    }
}

**Comment by fega** [comment]
But it will create an oversized container from 955px; to 601px

Closed due inactivity, feel free to reopen it if it is still necessary.
