### ISSUE TITLE
Wave/Ripple effect does not work when there is a spinner active. (Chrome)

### ISSUE THREAD

**Issue by WilbertE** [Dogfalo/materialize#2149]
I think I found a problem with the ripple effect.
1. There is a newer version of the wave effect (v0.7.2) https://github.com/fians/Waves/releases
2. When there is a spinner active, the wave effect occasionally doesn't work in Chrome.
   It might be a bug in Chrome. Sometimes it work, a lot of time the transitions is not played and the wave instantly shows.

I can't find out why it happens but I've created a JSFiddle: http://jsfiddle.net/b477sa4w/1/

**Comment by fega** [comment]
it looks like your fiddle is not importing the libraries
