### ISSUE TITLE
Responsive grid are too small

### ISSUE THREAD

**Issue by the-new-sky** [Dogfalo/materialize#2150]
Hello guys,
I have a Sony Xperia Z3 Compact and my materialize's website was printed as a tablet but it's a phone...
400px is for very small phone, my phone is also a compact version and it's recognized as a tablet.
Is there a way to adjust the dimensions of the grids ???

Sorry for the bad english I'm French :/

**Comment by acburst** [comment]
The label is arbitrary. You can design your "tablet" version to be similar to a phone version. 
But you can always download the Sass version and edit the variables.scss file:

Look for these values and they will change the media queries for the entire framework.
```
// Media Query Ranges
$small-screen-up: 601px !default;
$medium-screen-up: 993px !default;
$large-screen-up: 1201px !default;
$small-screen: 600px !default;
$medium-screen: 992px !default;
$large-screen: 1200px !default;
```
