### ISSUE TITLE
Materialbox image not shown on Chrome mobile if data-caption is used

### ISSUE THREAD

**Issue by N1bbler** [Dogfalo/materialize#2153]
1. On Chrome mobile, go to: http://materializecss.com/media.html
2. first image works fine
3. 2nd image with data-caption doesn't work; image is shown for 1 second, then disappears

**Comment by acburst** [comment]
What OS? It works fine on my nexus 5

**Comment by N1bbler** [comment]
Thanks and sorry I forgot to add that crucial bit of info. I am seeing this on IOS + Chrome. With testing further I see that it is not only the elements with data-captions, the ones without are flakey as well.
