### ISSUE TITLE
Docs - Wrong example for toast

### ISSUE THREAD

**Issue by SteveEdson** [Dogfalo/materialize#2154]
>Custom HTML
You can pass in an HTML String as the first argument as well. Take a look at the example below, where we pass in text as well as a flat button. If you call an external function instead of in-line JavaScript, you will not need to escape quotation marks.

>TOAST WITH ACTION
```js
  var $toastContent = $('I am toast content');
  Materialize.toast($toastContent, 5000);
```

The above example does not show the correct code to match the description.

Thanks.

**Comment by acburst** [comment]
Fixed in 4fb1621
