### ISSUE TITLE
Feature: Animation of underline in input

### ISSUE THREAD

**Issue by cungen** [Dogfalo/materialize#2157]
I recommend adding animation of the underline in input. The current behavior is just show when the input is focus. How about show the underline in the bottom center with width animation from 0 to 100%, just like polymer do or other material design's input do.

**Comment by fongfan999** [comment]
I wanted to recommend this feature too :)

**Comment by Loilo** [comment]
I agree. Even if it's only a small visual tweak it was actually the first and kind of most impressive thing I saw in Material Design.

**Comment by fega** [comment]
In response of #2753,

**Comment by fega** [comment]
I guess that someone could share an snippet about it
