### ISSUE TITLE
Can provide multi-page controls like jquery mobile？

### ISSUE THREAD

**Issue by liniu** [Dogfalo/materialize#2160]
Can provide multi-page controls like jquery mobile？

**Comment by acburst** [comment]
Can you be more specific? maybe some actual source examples or reasoning behind why you want something.

**Comment by liniu** [comment]
In many cases, one page is not enough to use, need to pop up a dialog  to fill in the information( like shipping detail)  , but pop-up operation is not so friendly, a  better way is to slide switch to another page, and slide left to back, but  multiple pages are in one request。

My English is limited, can you understand my description？ the following example：

http://demos.jquerymobile.com/1.4.5/pages-multi-page/
