### ISSUE TITLE
[slider enhancement request] add prev/next to external slider JS API

### ISSUE THREAD

**Issue by guykatz** [Dogfalo/materialize#2161]
Hi;
currently there is a stop/start functionality only on the slider JS Object. when using indicators the indicators, clicks can act as a trigger for next and prev style functionality but with no indicators, using a paused slider, I would still want to be able to programatically go to the next/prev slide.
 I think we need a prev/next function in the API.
thanks.

**Comment by acburst** [comment]
Added in 5ff3ba4
