### ISSUE TITLE
multiple sliders per page JS API mixes up sliders

### ISSUE THREAD

**Issue by guykatz** [Dogfalo/materialize#2162]
Hi;
please see: http://codepen.io/anon/pen/BowVRr
2 sliders in same page, 'pause' is called on the first but executed on the second instead.
thanks.

**Comment by JimishF** [comment]
+1

**Comment by guykatz** [comment]
I'm not a JS expert but it looks like the $interval is declared on the global scope (without 'var'). this seems to impact the ability of having multiple sliders on the same page and being able to stop and start the, via JS.
so instead of:
        // auto scroll
        $interval = setInterval(
do something like:
        // auto scroll
        var $interval = setInterval(

and this might help... or at least its a good start :)

**Comment by acburst** [comment]
Yes, this is a pretty embarrassing bug haha. Thanks for catching this.

Fixed in 542bcc4
