### ISSUE TITLE
Tabs in Navbar

### ISSUE THREAD

**Issue by LCallaghan84** [Dogfalo/materialize#2169]
Using tabs as a navigation in the header does not work?
anyway you can make the tabs work in the nav section, and have them control he tab content in the main section?

**Comment by acburst** [comment]
Do you have any specific examples or codepens of it not working? We try and keep open issues that have more substance with specific examples.

**Comment by LCallaghan84** [comment]
well I have tried it before on a template but it just did not work, maybe i am not doing it correctly

**Comment by acburst** [comment]
Please post a code example of it not working. It's hard for us to guess what's going wrong if we don't have anything to go on

**Comment by LCallaghan84** [comment]
hmm.. for some reason, the tabs now work in the navbar. thanks for offering to help

http://codepen.io/anon/pen/JYOyBx

**Comment by LCallaghan84** [comment]
However i cant put the tabs on the right side of the logo. only below it.

**Comment by tmd-uk** [comment]
Hey guys, just a quick one for you. I have been playing around with your idea of the tabs in the navbar and this is what I have so far, I am still going through it and perfecting it as I go. But here it is, like I said I am still working on it to perfect it. http://codepen.io/tmd-uk/full/megEqR/

**Comment by LCallaghan84** [comment]
very nice design, that is exactly what i was thinking of trying to make.

**Comment by tmd-uk** [comment]
I just need to either remove the logo or tab nav on Mobile, the tab nav seems to overlap the logo. So I have a few options to try and see what it looks like. If you guys like it when I have finished it and perfected it by all means fork it and use it for your projects.

**Comment by LCallaghan84** [comment]
Mind if a make a suggestion for Mobile?, how about hide the tabs in mobile, and use the side nav with links to control the tab content

**Comment by tmd-uk** [comment]
I did have that in mind, I'm away from the laptop until tomorrow so I'll add it then. Thank you for that.

**Comment by LCallaghan84** [comment]
That's the only solution I can think of, I am glad to see you managed to make the tabs to be in the same row as the logo.

**Comment by tmd-uk** [comment]
Thanks @LCallaghan84 It didn't take that long (2 mins) to figure it out. I will still be perfecting it though, I am just waiting on the scrollable navs to be added by @Dogfalo if they are available. That way users can scroll the tabs like what's available with http://getmdl.io

**Comment by acburst** [comment]
What exactly do you mean by scrollable navs? Our tabs now can scroll horizontally if the container has a fixed width.

**Comment by tmd-uk** [comment]
What I mean is look at the mobile version of getmdl.io's nav. It scrolls when interacted with, a few users have been asking and have been confused why there is no docs or evidence of scrollable tabs. Which is why I reference getmdl.io.

**Comment by NitroBAY** [comment]
The link is dead

**Comment by tmd-uk** [comment]
@NitroBAY I'll create a better one later on.

**Comment by rockymontana** [comment]
Waay laters on @tmd-uk ;)

**Comment by tomscholz** [comment]
http://materializecss.com/navbar.html#navbar-tabs Please close
