### ISSUE TITLE
Breaking iron:router routing

### ISSUE THREAD

**Issue by MehdiSolati** [Dogfalo/materialize#2171]
When I use the (most recent) iron:router and (most recent) materialize:materialize packages for my app, I'm getting this message on my localhost:3000

"Couldn't find a template named 'index' or 'index'. Are you sure you defined it?"

Materialize is the only CSS package that causes this, since I've removed it and tried Bootstrap to see if it works (and it does). Don't worry though, I would never use Bootstrap, I just placed all the CSS and JS files into my app and imported some stuff in my <head>

**Comment by Dogfalo** [comment]
This is fixed now, it was a problem with the packaging. You can clone the master branch here to use the latest version. See this on how to do that: https://forums.meteor.com/t/how-to-install-meteor-package-direct-from-github/1693
