### ISSUE TITLE
onShow for sideNav

### ISSUE THREAD

**Issue by MuyBien** [Dogfalo/materialize#2181]
Hi!
Wondering if there is a way to launch a function on show for the sideNav.
If no, are you planning to add it?

Thanks!

**Comment by guykatz** [comment]
note that you can probably attach an on animation/transition end do catch it. pseudo code :
elems.addClass(anim/transitionClass).on(anim/transitionEndEventName, function() {//do something}

**Comment by MuyBien** [comment]
Hi,
yeah I was planning to do that but I can't figured out the name of the animEndEventName.
Do you know where I can found it?

Thanks!

**Comment by mccraveiro** [comment]
You could use a [MutationObserver](https://developer.mozilla.org/en/docs/Web/API/MutationObserver) however it is not supported on IE <11

**Comment by MuyBien** [comment]
Pretty interesting the MutationObserver! I didn't know about it.
I put a MutationObserver on attribute of the slideOut like this 
```
  var observer = new MutationObserver(function(mutations) {
    mutations.forEach(function(mutation) {
      var target = $(mutation.target);
      //Do something
    });    
  });
  var target = document.querySelector('#slide-out');
  observer.observe(target, {attributes: true});
```
It's working well meaning that the changes are observed but the slideOut effect is adding the class "velocity-animating" and changing the left css attribute. So what I did it's to check for the presence of the class "velocity-animating" meaning that the animation is on going and waiting for this class to disappear. Like that:
```
if(target.attr("class").indexOf("velocity-animating")<0){
   Materialize.showStaggeredList('#slide-out');
}
```
My problem now, is that at the end of the animation the left position is updated two times to 0 and the class "velocity-animating" is no longer present. So my callback is fired twice...

I am stuck here... :( 
Any help please...

**Comment by MuyBien** [comment]
Finally, the simplest way is to add onComplete velocity option to sideNav.js directly. Then I can call the sideNav plugin with onShow and onHide...
I don't think it's code in a good way, so I can't make a Pull Request...

**Comment by tomscholz** [comment]
There are currently no callbacks for the sidenav
