### ISSUE TITLE
In Firefox, range HTML5 element still shows the outline

### ISSUE THREAD

**Issue by mitar** [Dogfalo/materialize#2182]
![screen shot 2015-10-20 at 3 32 50 am](https://cloud.githubusercontent.com/assets/585279/10604738/6b8988f8-76db-11e5-9712-d3352a88a8c3.png)

Firefox 41.0.2.

Example is from [guide](http://materializecss.com/forms.html).

**Comment by Dogfalo** [comment]
Fixed by @soniabrami in #2756
