### ISSUE TITLE
In Firefox, range HTML5 thumb does not close always

### ISSUE THREAD

**Issue by mitar** [Dogfalo/materialize#2183]
It does not close always on mouseout.

![screen shot 2015-10-20 at 3 32 50 am](https://cloud.githubusercontent.com/assets/585279/10604738/6b8988f8-76db-11e5-9712-d3352a88a8c3.png)

Firefox 41.0.2.

Example is from [guide](http://materializecss.com/forms.html).

**Comment by Dahkon** [comment]
Same problem here.

**Comment by sakulstra** [comment]
same problem here^

**Comment by jeromemiranda** [comment]
same problem here.
![screenshot from 2016-01-29 08 26 23](https://cloud.githubusercontent.com/assets/10937400/12663446/4e4962ae-c663-11e5-8e1b-3855f178fb37.png)

**Comment by MonsterKiller** [comment]
This issue still exists, even on their documentation as mentioned by OP.

**Comment by fega** [comment]
@mitar It looks okay in the latest version in either Materialize and firefox
