### ISSUE TITLE
Not all icons are listed

### ISSUE THREAD

**Issue by mitar** [Dogfalo/materialize#2185]
For example, [cards page](http://materializecss.com/cards.html) uses `<i class="material-icons right">more_vert</i>` icon, which is not listed [among icons available](http://materializecss.com/icons.html).

It seems this is a much better list (you have to adapt names a bit): https://s3.amazonaws.com/kantan-dresssed-demos/demos/ives/blue_preview/007_icons@fa-lightbulb-o%252F004_mdi_icons.html

**Comment by SuperDJ** [comment]
Maybe you can find some more here: http://www.google.com/design/icons/

**Comment by mitar** [comment]
But naming is unclear from there.

**Comment by SuperDJ** [comment]
If you want to use: `<i class="material-icons right">more_vert</i>` add `<link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">` in your `head` if you haven't already done so. Then each icon which has a space requires the use of `_`.  If there is something else unclear please let us know

**Comment by mitar** [comment]
Ah, http://www.google.com/design/icons/ dynamically renders the page. This is why searching for "more very" didn't find anything. It does not render the whole page at once. What a bad approach for a reference material.

**Comment by obouchari** [comment]
You can use https://materialdesignicons.com/ instead.

**Comment by mitar** [comment]
Great site. But materialdesignicons.com seems to include icons which do not exist in what Materialize provide? Even if I list just Google icons there are missing icons. At least under the names there. Like `car_wash` is on the list, but it is not available.

**Comment by obouchari** [comment]
MaterializeCss also seems to have duplication in the documentation you need to include the link to MDI from google fonts, but there is already a list of font files included in the framework! sass/components/_icons-material-design.scss

**Comment by timtribers** [comment]
@mitar on Chrome you can use the dev panel to search the dynamic page source at https://www.google.com/design/icons/ - just press ctrl-f (or mac equiv) and search for your keyword.  If you find an element with that name, you can right-click the source and use 'scroll into view' to show it.  But expect you knew that already.

**Comment by tomscholz** [comment]
Please close
