### ISSUE TITLE
Avoid Toast on Error

### ISSUE THREAD

**Issue by ramkumarvss** [Dogfalo/materialize#2186]
When any Error happened due to the API, Toast is prompting in the screen. How to avoid it.

![image](https://cloud.githubusercontent.com/assets/11497110/10626398/377c097c-77cc-11e5-98f6-bfcec42b8721.png)

Error:

![image](https://cloud.githubusercontent.com/assets/11497110/10626406/51d5eb94-77cc-11e5-91af-be0967023e8d.png)

Please any one try to resolve this issue.

**Comment by fega** [comment]
Closed due inactivity, if you want to reopen this, please provide an example to be able to reproduce it.

Thanks
