### ISSUE TITLE
Not possible to use "required" validation with radio buttons in Chrome

### ISSUE THREAD

**Issue by mitar** [Dogfalo/materialize#2187]
For such ratio button(s):

``` html
          <div class="row">
              <div class="input-field col s12 center-align">
                <input type="radio" name="category" value="category1" id="point-category-category1" required />
                <label for="point-category-category1">Category 1</label>
              </div>
          </div>
```

I am getting in the Chrome the following error:

```
An invalid form control with name='category' is not focusable.
```

The reason is probably because Materialize hides the radio buttons away from the page and replace it with custom rendering.

**Comment by acburst** [comment]
Can you post more code or a demo? I'm not sure where exactly youre getting the error.

**Comment by mitar** [comment]
Here it is:

http://jsfiddle.net/pzxj2sy5/1/

Open in Chrome and click on "submit" button. You will get in the web console:

> An invalid form control with name='category' is not focusable.

**Comment by OminStyle** [comment]
I'm having the same issue.

**Comment by OminStyle** [comment]
My workaround for now is adding the follow after the contact has been rendered.
```
$('input').css('visibility', 'visible');
```

**Comment by mitar** [comment]
But isn't the real radio inputs pushed outside of the visible page? And only labels are then left in their place? So focus to required radio button then would not really work correctly?

**Comment by OminStyle** [comment]
```
So focus to required radio button then would not really work correctly?
```
You're right but at the very least, people won't be able to submit the form without completing it. I'm not satisfied with the solution either :(

**Comment by seanodotcom** [comment]
+1 Having this problem too.
How do you display a message to the user when _required_ radio inputs are not filled?

**Comment by Voxran** [comment]
Sorry for the up, but I still have the same issue in 0.97.6... No error message on radio in Chrome or Blink-browsers :/

**Comment by GorgonsMaze** [comment]
+1 on this. Chrome doesn't work. Firefox displays the required message, but its no where near the radio buttons.

**Comment by EdgarMP** [comment]
I still have this problem. Any suggestions?

**Comment by LGracia** [comment]
Hi guys.
I have the same issue, my solution is this(I hope it's not too late):
- Add 'name' attribute for everyone elements within 'div' with class 'input-field' .
- Add class 'validate' to the first radio-button within the 'div' with class 'input-field', it's not necessary for all elements.
- Use the javascript file.

https://jsbin.com/jeyaset/edit?html,js,output

**Comment by avinashdvv** [comment]
how to solve same issue in input box with collapsible

**Comment by LGracia** [comment]
checkout this, let me know if this is the function that you want
https://jsbin.com/sojozoj/edit?html,js,output

**Comment by Native-Coder** [comment]
Same problem here guys. Required radio buttons don't show the required message. The page just scrolls up to them.

**Comment by LGracia** [comment]
Hi, try with this
https://gist.github.com/LGracia/f6243383b12d1636395b0ba52ee3c016

**Comment by Dogfalo** [comment]
Fixed in 57423d86

**Comment by shehjart** [comment]
Hi guys, any idea how to solve the same problem for <select> also. I am running into exactly the same error message.

**Comment by richardalain83** [comment]
@shehjart  if you use bootstrap accordion  or jquery ui accordion and the input is in a closed pane of the accordion, you might  get this error.
