### ISSUE TITLE
Feature Request : expandable

### ISSUE THREAD

**Issue by Mr-Zer0** [Dogfalo/materialize#2189]
I would like to request new feature called expandable. Just like a feature from mdl http://www.getmdl.io/components/index.html#textfields-section

**Comment by acburst** [comment]
Are you talking about an expanding text field? Because our textareas auto resize

**Comment by Mr-Zer0** [comment]
I mean ..
Text field will expend when search icon is clicked.

**Comment by winters-song** [comment]
@acburst Textfield's border-bottom has an animation when being focused.

**Comment by Mr-Zer0** [comment]
http://www.getmdl.io/components/index.html#textfields-section

Please "Expandable Textfield" in this page.

**Comment by alanjames1987** [comment]
+1

**Comment by fega** [comment]
Moved to feature request board
