### ISSUE TITLE
Form validation

### ISSUE THREAD

**Issue by ramunasm** [Dogfalo/materialize#219]
It would be great to have something like: http://foundation.zurb.com/docs/components/abide.html
integrated.
Are there any nice solutions for validation besides writing custom scripts?

**Comment by dhawken** [comment]
What are the classes to use for manually applied validation?

**Comment by AngeloG** [comment]
Any recommendations on validation libraries like Foundation Abide that work well with Materialize?

**Comment by J-tt** [comment]
@tomscholz 

Any reason this is still open? It seems like the debate here is closed.
