### ISSUE TITLE
grid docs need more info

### ISSUE THREAD

**Issue by guykatz** [Dogfalo/materialize#2193]
Hi;
it is not clear from the docs when to create a new row. for example, the following from the docs:
```<div class="row">
      <div class="col s12 grid-example">This div is 12-columns wide</div>
    <div class="col s6 offset-s6 grid-example">6-columns (offset-by-6)</div>
  </div>```
would essentially create a 2 row layout. so why aren't they in 2 different row tag? I mean, when should I split this into 2 rows instead? what should my criteria be?:

thanks

**Comment by SuperDJ** [comment]
I think this is more a personal thing and it depends on what is needed. Looking at the docs of some other well know responsive frameworks: [Zurb Foundation grid](http://foundation.zurb.com/docs/components/grid.html) and [Bootstrap grid](http://getbootstrap.com/css/#grid). There is no specific explanation on a grid.

**Comment by Dogfalo** [comment]
Yes I think our grid docs are already more descriptive than most
