### ISSUE TITLE
Tabs don't respond to coloring text?

### ISSUE THREAD

**Issue by Jollarvia** [Dogfalo/materialize#2194]
If you include a className of teal-text or anything else included in the project on a .tab, the color remains the default red. Likely we can change it in a stylesheet, but it's better to just use the classes provided if we prefer. Wave works. I'm not sure if background colors change but I couldn't find any way to get the text to respond to classes.

**Comment by acburst** [comment]
If you have a tags within those li.tab's then you need to put the teal-text class on that.
