### ISSUE TITLE
Is there a way to make a navbar dropdown on mobile seems like materialize page side-nav?

### ISSUE THREAD

**Issue by victordeassis** [Dogfalo/materialize#2196]

**Comment by mccraveiro** [comment]
@victordeassis Can you provide more details on what you are trying to achieve?
If I've understood you correctly, you are trying to open the side-bar when a dropdown is clicked. 
Then I would suggest you to create a fake dropdown button and attach a side-nav show event to it. Also, on the side-bar items you would do the same. However this time you would update the dropdown value and close the side-nav.

**Comment by victordeassis** [comment]
Hi @mccraveiro thank you for the help, I wanna make a navbar just like the materialize homepage when my page is on a smartphone, just like the image, can you help me please?

![screenshot](https://cloud.githubusercontent.com/assets/6058804/10764761/cd33a10c-7cb6-11e5-825e-68fb18482417.png)

**Comment by mccraveiro** [comment]
@raisiqueira Have you seen http://materializecss.com/side-nav.html?
