### ISSUE TITLE
Tabs have bug with hash

### ISSUE THREAD

**Issue by Splintex** [Dogfalo/materialize#2197]
Tabs works pretty good without hash, but with hash it has some problem. I uncommented this string for using hash

``` javascript
// Change url to current tab
window.location.hash = $active.attr('href');
```

and page starts jumping when I click the tab. 
Example http://codepen.io/Splinter/full/RWQMBj/

**Comment by Splintex** [comment]
The problem was with attribute id. I rewrote with data-id attribute and it works good.

**Comment by screengroove** [comment]
data-id attr working great for me..Thanks Splintex

**Comment by tomscholz** [comment]
Is this an issue?
