### ISSUE TITLE
data-error and data-success not working?

### ISSUE THREAD

**Issue by masterpowers** [Dogfalo/materialize#2201]
```
<input id="email" type="email" class="validate text email required" name="email">
<label for="email" data-error="wrong" data-success="right">Email Address</label>

```

Dont know if it is a bug or not?

Anyone Can Help me out with this?

**Comment by Dogfalo** [comment]
It is working: http://codepen.io/Dogfalo/pen/xZzjWW

**Comment by knipknap** [comment]
Your code snippet is not working in Chrome 51. No errors are showing up.

**Comment by knipknap** [comment]
I also tried FF47, still no luck.

**Comment by LukaVerhoeven** [comment]
I had the same problem.
1. Check if it is in a container with a class input-field
2. The input has to be the 1st Element and the label has to the 2nd element in this container

2nd fixed it for me

**Comment by SWAT10101** [comment]
I had the same problem. 
It work only  with <span class="helper-text" data-error="wrong" data-success="right"></span>
