### ISSUE TITLE
Dropdowns do not close when origin is clicked

### ISSUE THREAD

**Issue by jonathanmaloy** [Dogfalo/materialize#2202]
Dropdowns do not close when origin is clicked and belowOrigin is true.
<a href="http://codepen.io/anon/pen/OyvmOM" target="_blank">http://codepen.io/anon/pen/OyvmOM</a>

**Comment by jonathanmaloy** [comment]
So I went and fixed the issue then relized it was already fixed on the source file. I assume it will be apart of the next release?

**Comment by Dogfalo** [comment]
yes it will!
