### ISSUE TITLE
Tabs with sliders

### ISSUE THREAD

**Issue by SirusDoma** [Dogfalo/materialize#2203]
Hello, I am new in Materialize CSS, and it's awesome!

However, In Android, when i have a lot of tabs that cannot be displayed all of them at once,the tabs wrapped into something that can be scrolled / swapped horizontally, with left and right navigation, and It seems Materialize CSS didn't have this behavior...

It's look like similar like Browser Tab, notice there are Left and Right Navigation Button:
![moztabs](https://cloud.githubusercontent.com/assets/9136829/10721428/17e83924-7bd6-11e5-95a5-37c30b86eb5c.png)

More Likely (Without Navigation Button, but I prefer with Navigation Button):

![demotab](https://cloud.githubusercontent.com/assets/9136829/10721442/30e44d3c-7bd6-11e5-91cb-c35b00be92cc.png)

I hope this available in future version of Materialize CSS!
Thanks in advance

**Comment by bylinggha** [comment]
Good Idea :D

**Comment by acburst** [comment]
I've added this here 7e0c265808cb8d6d27cba6555fa081ef94ff86b3. This allows for scrolling thru the tabs with touch or mouse but has no arrows yet. This is not in the latest release yet, but will be in the next.
