### ISSUE TITLE
Materialboxed is buggy when put in a row

### ISSUE THREAD

**Issue by EliasJorgensen** [Dogfalo/materialize#2205]
I have a materialbox in my project, and i want to display 3 in a row.
If i do:
```
<img class="materialboxed responsive-img" src="/img/image.jpg">
```
It works without any problems, but if i do:
```
<div class="row">
	<img class="materialboxed responsive-img col s12 m4" src="/img/order1.jpg">
</div>
```
the image will only pop up about 50% of the time. When it doesn't pop up, it will just kinda jitter real quick and that's it.

**Comment by Dogfalo** [comment]
Perhaps take a look at how it is done here: http://materializecss.com/showcase.html
