### ISSUE TITLE
dropdown mobile tap detection

### ISSUE THREAD

**Issue by philipraets** [Dogfalo/materialize#2212]
I'm using forms within dropdowns, and it's working great, except since the touchstart events are added to dropdowns. From the moment I touch the dropdown, it closes.

Example use of forms in dropdowns:
dropdown-button:
![image1](https://cloud.githubusercontent.com/assets/708011/11333315/1a84eb2a-91cd-11e5-9922-cc6239329d1f.PNG)

dropdown with form:
![image2](https://cloud.githubusercontent.com/assets/708011/11333316/1f6db108-91cd-11e5-8c5f-a63f9a6db046.PNG)

Now I take the dropdown javascript file and remove the touchstart events and load this file with my application, but maybe there is a better solution?

Philip

**Comment by philipraets** [comment]
updated with better description and screenshots

**Comment by fega** [comment]
Could you check if this is still an issue with the last version? and
Please provide a way to reproduce it. like a [codepen](https://codepen.io/fega/pen/BWeZaG)

**Comment by Dogfalo** [comment]
I believe this was fixed in v0.98.0. Please reopen this if this is not the case.
