### ISSUE TITLE
Q: gaps

### ISSUE THREAD

**Issue by grafa** [Dogfalo/materialize#2213]
Hey guys,

when I compare MaterializeCSS vs Material Design Lite by Google the biggest difference I see is the gaps. Everywhere. Grid, components like forms, big buttons, tables, ...

I'm not sure if Google or you are "right", but is there a way, how to tell to your framework no to be so space greedy? I mean, is there any base-variable like multiplier, that I can lower and shrink everything a bit together, so I will get the MDL look?

Reason:
I build up a huge project for my client on your framework, but the client constantly complains about the space. He says it's nice but megalomaniacal. And now I see, he is right.

Thanks for your time and the answer!

**Comment by acburst** [comment]
There are default margins on the grid system's rows. You can change these values in the _variables.scss file: 

```
$element-top-margin: $gutter-width/3 !default;
$element-bottom-margin: ($gutter-width*2)/3 !default;
```

But you are always free to add your own css and customize our base styles to reduce some of the spacing.

**Comment by grafa** [comment]
Just tried your suggestion on different project.

The thing is that I can minimalize spaces between boxes but i.e. not inside table cells th and th. The same issue is with material select. Sure I can override them in my CSS file, but who wants to do that for every type of element?

I've checked all variables in project and all relevant I can see it variable $gutter-width. Sadly this "global spacing variable" is not used in tables and most of another elements. It's pitty because if it would we could adjust spacing globally it would keep the ratio between element spacing.

What do you think?

Thank you.
