### ISSUE TITLE
Vertical align tabs

### ISSUE THREAD

**Issue by Kail0** [Dogfalo/materialize#2215]
Hello,

I'm kind of sorry, I'm asking, but Is there a "simple" way to make tabs vertical, instad of horizontal? 

Ive tried multiple solution, but it just mess with my site..

Thank you and have a nice day

**Comment by acburst** [comment]
Currently we don't plan on supporting vertical tabs. But if people have personal solutions that work feel free to post them.

**Comment by Kail0** [comment]
Ohh, thank you for reply. I'm currently working on solution to that. I might commit result, when it's finnished.
