### ISSUE TITLE
Style bug when nouislider is not connect

### ISSUE THREAD

**Issue by spantons** [Dogfalo/materialize#2216]
Hi before all, thanks for all the contribution with materialize.

I am trying to use a form -> range -> noUiSlider (3rd party), but I need that the two selectors must not be connected between them. This is my code:

var slider = document.getElementById('test5');
  noUiSlider.create(slider, {
   start: [20, 80],
   step: 1,
   range: {
     'min': 0,
     'max': 100
   },
   format: wNumb({
     decimals: 0
   })
  });

**Comment by mccraveiro** [comment]
@spantons can you provide a codepen explaining the issue?

**Comment by spantons** [comment]
Hi @mccraveiro, http://codepen.io/spantons/pen/rOvjwo

**Comment by mccraveiro** [comment]
You can quick fix with 
```
.noUi-origin {
  top: 6px !important;
}
```
However, I can confirm this bug
