### ISSUE TITLE
Font Awesome

### ISSUE THREAD

**Issue by PolGuixe** [Dogfalo/materialize#2220]
Is anybody experiencing issues when using [Font Awesome](https://fortawesome.github.io/Font-Awesome/)? Specially inside nav bar or side bar links.

**Comment by vasya10** [comment]
We used font-awesome a few months ago, and found that we had to tweak the styles a bit to get it working correctly (position, line-height etc). After materializecss fully switched to supporting Google Material Design Icons, we did the same, and they appear to work fine without any issues.

**Comment by PolGuixe** [comment]
@vasya10 cool. Can you share the fix? :)

**Comment by vasya10** [comment]
@PolGuixe it was a few months ago, and dont have the code with me.. I remember we had to override the line-height property to adjust the display. You may want to just to play with Chrome dev tools to get what you want. We are fully using Google MDI now.

**Comment by willseward** [comment]
I just did this:

```css
.fa {
    display: inherit !important;
 }
```
