### ISSUE TITLE
Grid with unequal height items

### ISSUE THREAD

**Issue by phamlehieu** [Dogfalo/materialize#2223]
I'm trying to use grid system in materialize to display some items have dynamic height base on their's content, and I got this issue. There's a big blank space on the left side when right column is longer than left column. Anybody has solution for this case ?
Example code:
```html
<div class="row">
    <div class="col s12 grid-example">
        <span class="flow-text">This div is 12-columns wide on all screen sizes</span></div>
    <div class="col s6 grid-example"><span class="flow-text">6-columns (one-half)</span><br><span class="flow-text">6-columns (one-half)</span>
    </div>
    <div class="col s6 grid-example"><span class="flow-text">6-columns (one-half)</span></div>
    <div class="col s6 grid-example"><span class="flow-text">6-columns (one-half)</span><br><span class="flow-text">6-columns (one-half)</span>
    </div>
    <div class="col s6 grid-example"><span class="flow-text">6-columns (one-half)</span><br><span class="flow-text">6-columns (one-half)</span>
    </div>
</div>
```
Example screenshot:
![screen shot 2015-10-29 at 10 48 19 pm](https://cloud.githubusercontent.com/assets/6805429/10823758/b54ffeb6-7e8f-11e5-971f-a6a5ae130ca8.png)

**Comment by acburst** [comment]
This is not possible with a basic grid. You can use http://masonry.desandro.com/ to achieve this effect

**Comment by andreatrygit** [comment]
I see that materialize offer flowtext, which should autoscale for that
