### ISSUE TITLE
Meteor materialize package: icons are missing

### ISSUE THREAD

**Issue by ajinkyapisal** [Dogfalo/materialize#2224]
I created new Meteor 1.2.1 project and I added official materialize package. I am not seeing material icons in my webpage. 

Steps:
```meteor create sample-project
meteor add materialize:materialize@=0.97.0```

Add below line to the sample-project.html file
```
<a class="waves-effect waves-light btn"><i class="material-icons left">cloud</i>button</a>
```

**Comment by rijk** [comment]
Have you added the `<link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">` line to the header? See http://materializecss.com/icons.html

**Comment by ajinkyapisal** [comment]
@rijk Yes. I did that. Now it is working for. I was under the assumption that these things are handled in the materialize css meteor package.

**Comment by rijk** [comment]
I had the same problem today ;)
