### ISSUE TITLE
Move files under "font" folder to "fonts"

### ISSUE THREAD

**Issue by SirusDoma** [Dogfalo/materialize#2227]
I think it's necessary to move "font" folder to "fonts".
Since the most font icon files located under "fonts" folder, it would create 2 similar folder ("font" and "fonts") when using them along with Materialize.

**Comment by pascalwhoop** [comment]
+1 had to create an extra gulp task for it.

**Comment by Dogfalo** [comment]
fixed in a1ca0a997efb692a27fcfa85a7cc5277b24c0e57
