### ISSUE TITLE
Search bar misaligned in webkit

### ISSUE THREAD

**Issue by kfarwell** [Dogfalo/materialize#2229]
gecko
![2015-10-31-111341_1280x800_scrot](https://cloud.githubusercontent.com/assets/4172356/10864327/eb4e2f10-7fc0-11e5-9e04-a859ad8e0b65.png)

webkit and IE11
![2015-10-31-111330_1280x800_scrot](https://cloud.githubusercontent.com/assets/4172356/10864330/f940369a-7fc0-11e5-885b-a0cf8224ae82.png)

http://codepen.io/anon/pen/MaXqjL

```
<nav class="pink" role="navigation">
  <div class="nav-wrapper container">
    <a id="logo-container" href="/" class="brand-logo black-text">
      <img src="/img/logo.png" alt="title" />
      <span>title</span>
    </a>
    <ul class="right"><li>
      <form action="/search" method="post">
        <div class="input-field">
          <input id="search" name="search" type="search" placeholder="Search tags..." required>
          <label for="search"><i class="material-icons black-text">search</i></label>
        </div>
      </form>
    </li></ul>
  </div>
</nav>
```

**Comment by acburst** [comment]
hmm can't seem to recreate it. But try removing the UL and adding the right `class` directly onto the form.

```
<nav class="pink" role="navigation">
  <div class="nav-wrapper container">
    <a id="logo-container" href="/" class="brand-logo black-text">
      <img src="/img/logo.png" alt="title" />
      <span>title</span>
    </a>
    <form action="/search" method="post" class="right">
      <div class="input-field">
        <input id="search" name="search" type="search" placeholder="Search tags..." required>
        <label for="search"><i class="material-icons black-text">search</i></label>
      </div>
    </form>
  </div>
</nav>
```

**Comment by kfarwell** [comment]
@acburst No change in rendering.

> hmm can't seem to recreate it.

The [codepen](http://codepen.io/anon/pen/MaXqjL) has the issue in surf and Midori for me.

**Comment by keeferrourke** [comment]
+1 Can confirm that this is an issue in *some* webkit browsers such as [surf](http://surf.suckless.org/). 
[Epiphany 3.18.5](https://wiki.gnome.org/Apps/Web) under Gnome 3.18.4 is fine however.

**Comment by fega** [comment]
@kfarwell @keeferrourke 
Could you check if this is still an issue with the latest version?

**Comment by keeferrourke** [comment]
@fega I've made another code pen using the latest version of Materialize (v0.98.1) to demonstrate that this is still an issue. The second and third navbars use the (ineffective) suggestion from @acburst. I use [MDI icons](https://materialdesignicons.com/) in this example because (for whatever reason) the Materialize icons also don't render, and instead only display as text.

See http://codepen.io/anon/pen/pPvqQM?editors=1000

The rendering is still not what one would expect in the latest Chrome/Chromium, and the issue definitely persists.

**Comment by fega** [comment]
@keeferrouke thanks to take the time to test all of this stuff. 

The icons issue could be a problem with the material icon project and the ligature support of the web browsers, but should be great to provide a fallback for compatibility 

We will have in mind this issue, thanks again.

**Comment by keeferrourke** [comment]
Has this been solved? At this point... what is the correct markup to put a search-bar in the nav-bar?
