### ISSUE TITLE
Shadow / Z-Depth not working if background color was set

### ISSUE THREAD

**Issue by SirusDoma** [Dogfalo/materialize#2230]
Hello, It's seems that z-depth not working if the element background / background color is set.

Let's say I have 2 div columns element, I uses `z-depth-1` class to one of them, it works as expected, however, if the other one (the one without z-depth) background / background color is set (I use `grey lighten-2` in this case), the z-depth is not working

I hope this gonna be fixed in future version

**Comment by acburst** [comment]
Can you post a codepen of this?

**Comment by SirusDoma** [comment]
Here the JSFiddle:
http://jsfiddle.net/SirusDoma/1s09qn7p/

The strange behavior as follows:
1. The navbar doesn't show the box shadow on `Test Content` part, and the shadow is still visible in `Test Aside` areas (I know that by default, the navbar has z-depth, removing it from the class change nothing)
2. Notice `Test Aside` shadow doesn't appear on `Test Content` areas

**Comment by acburst** [comment]
1. The shadow is still there on `Test Content` its just the contrast of the grey color making it look lighter and less noticeable. This will always happen if you have two different color containers with the same shadow over it.

2. This is a z-index issue. If you want the `Test Aside` to go over `Test Content` try adding a z-index to `Test Aside`

**Comment by SirusDoma** [comment]
When I changed the `Test Content` to pink, it's seems I can see the shadow of `nav` there, my bad.
However, set the z-index to `Test Aside` content seems didn't work well.

I set `z-index` of `Test Content` to 1 and `Test Aside` to 1000, and I can't see the shadow there...
