### ISSUE TITLE
New type of Image card

### ISSUE THREAD

**Issue by LCallaghan84** [Dogfalo/materialize#2235]
Any chance of a new type of card, just a image card, no content but just an image with a title
![image-card-sample](https://cloud.githubusercontent.com/assets/868753/10881007/387c51d8-8168-11e5-84c7-014048bb025c.jpg)

**Comment by acburst** [comment]
You can already do this without the bar. Just remove the `card-content` and the `card-action`. But that you can add yourself with a line of css.

```
     <div class="row">
        <div class="col s12 m7">
          <div class="card">
            <div class="card-image">
              <img src="images/sample-1.jpg">
              <span class="card-title">Card Title</span>
            </div>
          </div>
        </div>
      </div>
```
