### ISSUE TITLE
Youtube video embeds have letterboxing

### ISSUE THREAD

**Issue by jsduffy** [Dogfalo/materialize#2237]
It seems like youtube videos in the responsive video container (sometimes?) have weird letterboxing.  I don't see this all the time, and it's not major, but it is unsightly.  In fact, I see it now with the two embeds on the materialize site, and it doesn't seem to be related to having/not having controls as far as I can tell.  I'm seeing this with multiple browsers.  See screenshot below for details (notice how the top video has black bars on the top and bottom, and the bottom video doesn't):

![screen shot 2015-11-02 at 3 16 55 pm](https://cloud.githubusercontent.com/assets/7926758/10893133/2dc7f97e-8175-11e5-859a-dbda7d721969.png)

**Comment by acburst** [comment]
Fixed in 714bb5a
