### ISSUE TITLE
Dropdown button for various directions and scroll bars

### ISSUE THREAD

**Issue by SirusDoma** [Dogfalo/materialize#2239]
Currently, Materialize only has Dropdown button, so I guess it's good idea to add something like Dropup, Dropleft and Dropright (Similar to Dropdown, unless the Contents would appear at respective direction). Those components would really helpful in certain situations.

Consider in such situation that you need Dropdown at the bottom of page, if it was "dropdown" it will enlarge the site height, leave the white gaps to unused spaces (http://jsfiddle.net/SirusDoma/sc4kndL1/), it will be great if Materialize could detect what kind of direction of the Drop button that fit with the current position of the element, otherwise it will be good enough if these Drop buttons available to use.

Also it's good idea to warp the Dropdown contents into something that could be scrolled vertically / swapped vertically when it's has very long contents

Like, when you have 20 Items of Dropdown and display them at once will really inefficient

**Comment by pedrofs** [comment]
Would be great to have such options for dropdown!

+1

**Comment by zhaoyao91** [comment]
+1

our design place the app bar on the bottom, so the current dropdown effect is  bad.

**Comment by fega** [comment]
Closed due inactivity, feel free to reopen it if it is still necessary.
