### ISSUE TITLE
select options going off screen

### ISSUE THREAD

**Issue by scriptwell** [Dogfalo/materialize#2241]
The height of the select dropdown is not constrained to the screen size and made scrollable, it just goes off screen. Also the dropdown does not go up if its position is close to the bottom of the screen.

![image](https://cloud.githubusercontent.com/assets/8147877/10925252/a1ffaf1e-82e0-11e5-95a3-0ef95d4d3f84.png)

The dropdown should open upward, or be constrained by the bottom edge of the screen and scroll.

![image](https://cloud.githubusercontent.com/assets/8147877/10925271/bd040314-82e0-11e5-900d-20f6300df604.png)

I would expect the dropdown height to stop below 2014 and be scrollable to show 2015+ options.

**Comment by acburst** [comment]
This is fixed on master. please look for similar closed issues like this #2034. We are trying to get a release out this weekend.

**Comment by ElpySites** [comment]
I have the same problem, but only when there is no space at the bottom of the screen, so select opens to top, then it goes off screen. If it opens as usually - down, it works ok.

**Comment by masterpowers** [comment]
got the same issue when i got so many options loaded dynamically
<blockquote class="imgur-embed-pub" lang="en" data-id="SZz83GL"><a href="//imgur.com/SZz83GL">View post on imgur.com</a></blockquote><script async src="//s.imgur.com/min/embed.js" charset="utf-8"></script>

**Comment by khlJunior** [comment]
The select has no height declared, just max-height. So if you set a height, select will automatically let you scroll inside to show the other options when the options are bigger than the height declared.
The max-height is 650 by default if i'm not wrong. 

Materialize does not change the height of the select based on screen size, i've solved this issue just setting the max-height to a fixed size.

**Comment by acburst** [comment]
Fixed in b18d753. Now I check if flowing upwards also goes offscreen. If that is true then I just crop the height of the dropdown to fit to the bottom of the screen.
