### ISSUE TITLE
Why don't select options in dropdown wrap to next line

### ISSUE THREAD

**Issue by fabyeah** [Dogfalo/materialize#2245]
In a select dropdown, there will be a horizontal scrollbar for options that are too long. Especially on mobile, this can happen a lot.

This is because of this CSS:

```
.dropdown-content {
    ...
    white-space: nowrap;
    ...
}
```

When I remove that CSS rule, the text wraps and everything seems to be fine. Or is it? Is there a specific reason for the nowrap rule? Is it related to this #1646 ?

**Comment by fega** [comment]
It appears to be solved in the current version.

Thanks
