### ISSUE TITLE
SideNav and Modals Transition is not smooth in mobile device

### ISSUE THREAD

**Issue by SirusDoma** [Dogfalo/materialize#2250]
I make some test to create an app based on Materialize with Cordova, I use android platform with minimum requirement KitKat, however the animation/transition of SideNav and modals are stutter.

I though it was because Cordova, but I tested with built-in browser and Google Chrome, it's still lags so much.

I hope Materialize would faster and reliable on mobile device in future version!

**Comment by acburst** [comment]
Yes, we do plan on optimizing many of our components. Many were written quickly in the early stages of the project, but it takes time to go back over all of them and improve them. I know at least for side-nav that we transition the left or right property which is not good performance wise. Eventually we will switch to using transform translate.

If anyone wants to take a crack at making the switch to animating with transform: translate it would be highly appreciated.

**Comment by ElpySites** [comment]
I modified it, so it works with translateX instead of left and with some custom css, but i didn't modify it for edge: right yet. Transition is smooth on mobile now.

**Comment by CalvinNoronha** [comment]
Yes I agree, trying to build an app for Cordova is quite laggy at this time.

Chrome works fine enough, I hope you guys optimize it asap cause this is quite a helper :)

**Comment by ElpySites** [comment]
I made it for both sides and fixed css as well, just have to make a pull request.

**Comment by acburst** [comment]
Looking forward to it @ElpySites

**Comment by kacpersaw** [comment]
@ElpySites Can't wait for this PR :)))

**Comment by Frondor** [comment]
still waiting...

**Comment by CalvinNoronha** [comment]
Still waiting for a pull ...

**Comment by inventti-leonardo** [comment]
Maybe this project can use Animate.css, seems fast...

https://daneden.github.io/animate.css/

**Comment by Y0lk** [comment]
Not sure it's really necessary. Most of the animations in material are fairly simple, it's just that a lot of them are done in js, and not necessarily optimized. The side nav needs JS because we need to be able to drag it.

**Comment by MarkoCen** [comment]
Hope the PR could be accepted soon... this issue prevents me to use Materialize my production project, since the prototyping was pretty laggy on mobile browser, specially on Android devices...

**Comment by Y0lk** [comment]
Same here, that's why I use a custom fork of Materialize now. Materialize needs more admins =/

**Comment by Dogfalo** [comment]
There were some problems with the PR due to some complexity around drag events, I created and pushed a fix here: df0c80fbd6c7f42e5d597464ce6962fbb8e3dfea

Sorry for the delay everyone.

**Comment by NitroBAY** [comment]
still incredbly slow on a very modern anddroid on chrome like 1FPS/second both for navbar and modal (transition to open it and dragging)

**Comment by brunogoossens** [comment]
The sidenav is also slow on my cordova project.

**Comment by freddy-daniel** [comment]
Me too I'm using [materializecss ](http://materializecss.com/mobile.html).Navigation drawer is not perfect in my cordova app.

**Comment by brunogoossens** [comment]
Is it possible to use JS only for dragging the sidenav and use CSS animations when clicking the sidenav open button?

**Comment by judasane** [comment]
Now with materialize V1 it still remains **too** slow

**Comment by Amine-Smahi** [comment]
Too slow and laggy
