### ISSUE TITLE
Use Autoprefixer instead of _prefixer.scss

### ISSUE THREAD

**Issue by obouchari** [Dogfalo/materialize#2251]
I think it would be better to use Autoprefixer instead of the _prefixer.scss file since it will add some unnecessary/outdated prefixes.

**Comment by acburst** [comment]
I'm not familiar with any auto prefixers. Do you have any suggestions?

**Comment by obouchari** [comment]
grunt-autoprefixer (https://www.npmjs.com/package/grunt-autoprefixer), I can work on it and submit a pull request :)

**Comment by ccheney** [comment]
@obouchari please use [grunt-postcss](https://github.com/nDmitry/grunt-postcss) since [grunt-autoprefixer](https://github.com/ndmitry/grunt-autoprefixer) was deprecated about 5 months ago

**Comment by obouchari** [comment]
Thanks for the info, I will Update.

**Comment by clthck** [comment]
why should I use autoprefixer instead of mixin prefixers? what's the pros?

**Comment by obouchari** [comment]
Autoprefixer is up to date with latest browser support (using caniuse.com). also you can specify the browsers versions you want to support.

**Comment by Dogfalo** [comment]
We use autoprefixer now for easier prefixes :)
