### ISSUE TITLE
Materialize still not updated on Atmosphere (Meteor)

### ISSUE THREAD

**Issue by ntoka** [Dogfalo/materialize#2256]
Hello,

because it seems you do not follow closed tasks I created a new one.

It seems that you fixed the issue crashed meteor apps after updating to 0.97.1. And though you say you did it - on Atmosphere service Materialize package is still broken. This means that me and many other Meteor users cannot install latest version of Materialize meteor package. Please update that package to the latest version that supports Meteor.

Thanks

**Comment by acburst** [comment]
its fixed on master and it will be fixed when we release 0.97.2
