### ISSUE TITLE
Non-responsive card sizes in grid

### ISSUE THREAD

**Issue by NickDelBen** [Dogfalo/materialize#2257]
When i create responsive cards inside the grid layout, the grid rows have a static height, and do not allow for the cards of different heights to be snug up against one another in the column.

See here for an example (expand view window to see responsiveness in action)
https://jsfiddle.net/cnbkLq4s/

The behaviour i am seeking can be seen in the rightmost column, but for some reason this behaviour does not apply to the first columns.

Essentially I would like to preserve the 'width scaling' that comes with the materialize grid package (that is resize and max elements on line based on page width) but not preserve the restions on a row. 

To just have responsiveness on the width but not static rows

**Comment by NickDelBen** [comment]
Essentially I would like to preserve the 'width scaling' that comes with the materialize grid package (that is resize and max elements on line based on page width) but not preserve the restions on a row. 

To just have responsiveness on the width but not static rows

**Comment by acburst** [comment]
There are libraries for this. Check out http://masonry.desandro.com/
