### ISSUE TITLE
Who can provide Pushpin HTML Structure

### ISSUE THREAD

**Issue by penghuajun** [Dogfalo/materialize#2261]
The plugin is not used.

**Comment by acburst** [comment]
Could you try to describe your problem better? It would be helpful for everyone if you put a little more content in your issue.

**Comment by penghuajun** [comment]
Thanks for your heads up。
How to use the Pushpin plug-in?
I like this, but to no avail.
<div class="container">
<div class="tabs-wrapper">
<div class="row">
<div class="col l4 offset-l8">
<h2>这是浮动部分</h2>
<p>浮动的任意结构</p>

</div>
</div>
</div>
<script type="text/javascript">$('.tabs-wrapper .row').pushpin({ top: $('.tabs-wrapper').offset().top });</script>
</div>

**Comment by penghuajun** [comment]
<pre>
<div class="container">
<div class="tabs-wrapper">
<div class="row">
<div class="col l4 offset-l8">
<h2>这是浮动部分</h2>
<p>浮动的任意结构</p>

</div>
</div>
</div>
<script type="text/javascript">$('.tabs-wrapper .row').pushpin({ top: $('.tabs-wrapper').offset().top });</script>
</div></pre>

**Comment by alijaffar** [comment]
:-1: 
This should be closed as it's not contributive... it takes up time which can be spent on real issues, not requests! Guys, please just close and ignore requests like this ^

**Comment by sfarzy** [comment]
@penghuajun If you're looking for a complete demo of pushpin, It's source is available over [here](https://github.com/Dogfalo/materialize/blob/de2be388be189bc8b92f021c4188d94b400e3a4c/test/html/pushpin.html).

Else, please close this issue.
