### ISSUE TITLE
Using text input within modal causes wrong label positioning

### ISSUE THREAD

**Issue by Messier82** [Dogfalo/materialize#2263]
When I try to put input field inside modal, label positioning is wrong. It isn't just moving up, as it is in normal, it's just become smaller, but stays in the same place.

./views/navbar.html
```HTML
<div id="register" class="modal" ng-controller="RegisterController">
    <register-form></register-form>
</div>

<script>
    $('.modal-trigger').leanModal();
</script>
```

./views/register.html
```HTML
<div class="modal-content" style="color: black;">
    <h4>Register</h4>
    <div class="row input-field col s12">
        <label for="anothername">Another name:</label>
        <input id="anothername" type="text" class="validate" placeholder="" />
    </div>
</div>
<div class="modal-footer">
    <a href="#!" class=" modal-action modal-close waves-effect waves-green btn-flat">Agree</a>
</div>
```
(I'm using AngularJS)

![materialize bug](https://cloud.githubusercontent.com/assets/5177291/11022600/6e5a3baa-866b-11e5-8d37-1409eb34831a.jpg)

Also label font-size isn't setting back, after deselecting input

Outside a modal input fields works well

**Comment by acburst** [comment]
You have to place the label right after your input. Not before

**Comment by phbernard** [comment]
I encountered a similar issue. Since Google offers this page as a solution, here we go: the text fields must be refreshed when the modal is displayed. For example:

    $('.modal').modal({
      ready: function() {
        Materialize.updateTextFields();
      }
    });
