### ISSUE TITLE
bower ENOTFOUND     Package Materialize not found

### ISSUE THREAD

**Issue by iammary** [Dogfalo/materialize#2264]
I am getting this error when installing materialize using bower

bower ENOTFOUND     Package Materialize not found

**Comment by Dogfalo** [comment]
Try it with lower case materialize

On Sun, Nov 8, 2015 at 5:56 PM, Mary Jesany Anub <notifications@github.com>
wrote:

> I am getting this error when installing materialize using bower
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Dogfalo/materialize/issues/2264>.
>



-- 
Doggy sends his greetings from Mars.

**Comment by iammary** [comment]
Yeah my bad. This error is generated when I tried installing https://github.com/krescruz/angular-materialize.
