### ISSUE TITLE
materializecss.com get cross-origin  error

### ISSUE THREAD

**Issue by elabsir** [Dogfalo/materialize#2266]
![cors](https://cloud.githubusercontent.com/assets/251942/11031691/877d2a68-86eb-11e5-8841-a707e2f7c980.jpg)

materializecss.com get cross-origin  error when load fonts from gstatic.com

**Comment by elabsir** [comment]
if we use https instead http, everything ok.
https://fonts.gstatic.com/s/materialicons/v8/2fcrYFNaTjcS6g4U3t-Y5ZjZjT5FdEJ140U2DJYC3mY.woff2

**Comment by acburst** [comment]
Not sure where you are seeing this.
