### ISSUE TITLE
form.js material_select() and filter bug

### ISSUE THREAD

**Issue by demimurych** [Dogfalo/materialize#2267]
Sry for my english.
In material_select you use keydown event
$newSelect.on('keydown', onKeyDown);
This only works for the English layout.
Because keydown event provides keycode only for physical keys.

For example
If I'm in the Russian keyboard layout and press the russian key - "a (keycode 1072)" in the keydown event you get a code 70 (English key F)

So
We need to use keypress event (NOT keydown or keyup)  for the correct operation of the filter in different keyboard layouts.

**Comment by fega** [comment]
Please provide a way to reproduce it.
Closed due inactivity, feel free to reopen it if it is still necessary.
