### ISSUE TITLE
Meteor Project font direction

### ISSUE THREAD

**Issue by sicum** [Dogfalo/materialize#2268]
the font is directioned 
packages/materialize_materialize/dist/font/material-design-icons
but the font file is
packages/materialize_materialize/font/material-design-icons
this error resolve in css
add 
this 
@font-face {
  font-family: "Material-Design-Icons";
  src: url("packages/materialize_materialize/dist/font/material-design-icons/Material-Design-Icons.eot?") format("embedded-opentype"), url("packages/materialize_materialize/dist/font/material-design-icons/Material-Design-Icons.woff2") format("woff2"), url("packages/materialize_materialize/dist/font/material-design-icons/Material-Design-Icons.woff") format("woff"), url("packages/materialize_materialize/dist/font/material-design-icons/Material-Design-Icons.ttf") format("truetype"), url("packages/materialize_materialize/dist/font/material-design-icons/Material-Design-Icons.svg") format("svg");
  font-weight: normal;
  font-style: normal;
}

**Comment by Mistaken3lf** [comment]
Does this affect icons and the mobile menu because they are not showing up correctly for me? My hamburger menu is a square and some icons don't load properly.

**Comment by Wooobee** [comment]
where did you put this? Sadly not working for me.

**Comment by sicum** [comment]
stylesheet principal in my project direct 
but
