### ISSUE TITLE
Add Icon-Buttons

### ISSUE THREAD

**Issue by ottigerb** [Dogfalo/materialize#227]
Icon-Button would be very nice!

I have found this - maybe as a starting-point:
http://codepen.io/ragingwind/pen/vnHEw

**Comment by lukaspijak** [comment]
+1

**Comment by RaSeR** [comment]
+1

**Comment by larikitty** [comment]
+ 1
[https://material.angularjs.org/#/demo/material.components.button](https://material.angularjs.org/#/demo/material.components.button)

**Comment by Riuujin** [comment]
+1

**Comment by burflip** [comment]
+1

**Comment by bali182** [comment]
+10

**Comment by maimouzaki** [comment]
+1

**Comment by fega** [comment]
+1

**Comment by yanickrochon** [comment]
Wait, is this still valid? I mean this

```
<a class="btn btn-floating btn-flat"><i class="material-icons">close</i></a>
```

essentially does what this issue is referring to, no?

**Comment by lonniev** [comment]
This looks a little better to me in my layout:

`<a class="btn-flat right waves-circle"><i class="material-icons">close</i></a>`

**Comment by tomscholz** [comment]
Please close this issue.
Try this https://codepen.io/tomscholz/pen/XMrBJe
