### ISSUE TITLE
Cards broken in 0.97.2

### ISSUE THREAD

**Issue by LCallaghan84** [Dogfalo/materialize#2275]
I don't what is wrong or how to fix this but the cards are broken in version 0.97.2

Here is the working version (using 0.97.1)
http://countdown.teamfreewill.net/wp-content/app-episode-list.php

and here is the broken one (0.97.2)
http://countdown.teamfreewill.net/wp-content/ep-schedule.php

**Comment by Mistaken3lf** [comment]
They were messed up for me as well. Had to tweak how the rows were setup for them to show up properly.

**Comment by LCallaghan84** [comment]
how did you fix it?

**Comment by acburst** [comment]
This is because we removed the default overflow: hidden on cards. You can fix this manually right now by adding overflow: hidden onto your cards.

I also fixed this in 19965b3
