### ISSUE TITLE
Materialize menu and Wordpress

### ISSUE THREAD

**Issue by coffeeneed** [Dogfalo/materialize#2276]
I'm trying to populate the menu with a Wordpress walker where there's a possibility that multiple menu items has a dropdown menu. Anything got this working or is it a Materialize "bottleneck"?

Thanks.

**Comment by Vaalyn** [comment]
I've build a few WordPress themes that use Materialize and had to make a piece of code to get dropdowns working on the navigation. I still think it's a bit ugly but it works for me.
Maybe this will help you: http://pastebin.com/6A1VVkgD

**Comment by coffeeneed** [comment]
@Vaalyn Hi and thanks for your reply and solution. I will check this out.

By the way: have you (or anyone else reading this post) managed to "componentify" Materialize by choosing to use the dropdown functionality only? Tried to include only the dropdown.js, but it didn't trigger.

**Comment by avagva** [comment]
The dropdown for my nav bar not work :(
I use the follow code in the header:



<div class="navbar-fixed"> 
<nav role="navigation">
<div class="nav-wrapper container">
<a href="#!" class="brand-logo"><?php _e('Logo', 'newborn'); ?></a>
<a href="#" data-activates="mobile-demo" class="button-collapse"><i class="mdi-navigation-menu"></i></a>
<?php 
// Header Menu navigation menu.
$main_menu = str_replace('<a href="#!">', '<a class="dropdown-button" href="#!" data-activates="dropdownxxx" data-beloworigin="true">', 
str_replace(
'<ul class="sub-menu">',
'<ul id="dropdownxxx" class="dropdown-content vc-red-light">', 
wp_nav_menu( array(
'echo' => false,
'menu_class' => 'right hide-on-med-and-down menu',
'theme_location' => 'header_menu',
'container' => '',
) )
)
);

for ($i=0; $i <= substr_count($main_menu, 'id="dropdownxxx"'); $i++) { 
$main_menu = preg_replace('/xxx/', $i, $main_menu, 2);
}

echo $main_menu;

// Header Menu navigation menu mobile.
$mobile_menu = str_replace('<a href="#!">', '<a class="dropdown-button" href="#!" data-activates="dropdownxxx" data-beloworigin="true">', 
str_replace(
'<ul class="sub-menu">',
'<ul id="dropdownxxx" class="dropdown-content vc-red-light">', 
wp_nav_menu( array(
'echo' => false,
'menu_class' => 'side-nav',
'menu_id' => 'mobile-demo',
'theme_location' => 'header_menu',
'container' => '',
) )
)
);

for ($i=0; $i <= substr_count($mobile_menu, 'id="dropdownxxx"'); $i++) { 
$mobile_menu = preg_replace('/xxx/', $i.'m', $mobile_menu, 2);
}

echo $mobile_menu;

?>

</div>
</nav>
</div>


Demo: http://grosca1a.bget.ru
Please help me to fix that error :(

**Comment by Vaalyn** [comment]
The hover seems to be working for me, however the mobile view does not.
I think that this is due to the link of the dropdown button.
I've only built it to work with a drop down button that doesn't link to another page and just triggers the dropdown to show.
Don't realy know how to get it working with a button that links to something I didn't need that yet.

**Comment by avagva** [comment]
I see the css code, need to change the display:none and position: absolute for hover. 
Give me you url, I want to see your menu.
You have a skype ? Maybe we can to fix the dropdown menu faster togheter.

**Comment by Vaalyn** [comment]
Here is a site I've recently built that has 2 dropdowns: http://www.weitmar-genclerbirligi.de
Hope that will help you but I don't have the time atm to help you on skype, sorry.

**Comment by avagva** [comment]
You can to sent your menu code with js and php arrays on my e-mail grosca@bk.ru and  when I finis my nav bar I will send you my code. =)

**Comment by jessor** [comment]
Use a custom walker. This is very basic, but better than preg_replacing and works with single hierarchy drop downs.

In your theme:
````
<?php wp_nav_menu( array(
    'theme_location' => 'top-bar',
    'walker' => new Materialize_Walker_Desktop_Nav_Menu(),
    'menu_class' => 'left hide-on-med-and-down'
) ); ?>
```

In your functions.php or somewhere else:
```
<?php

if( ! class_exists( 'Materialize_Walker_Desktop_Nav_Menu' ) ) :

    class Materialize_Walker_Desktop_Nav_Menu extends Walker_Nav_Menu {

        private $curItem;
     
        /**
         * Starts the list before the elements are added.
         *
         * Adds classes to the unordered list sub-menus.
         *
         * @param string $output Passed by reference. Used to append additional content.
         * @param int    $depth  Depth of menu item. Used for padding.
         * @param array  $args   An array of arguments. @see wp_nav_menu()
         */
        function start_lvl( &$output, $depth = 0, $args = array() ) {

            // Depth-dependent classes.
            $indent = ( $depth > 0  ? str_repeat( "\t", $depth ) : '' ); // code indent
            $display_depth = ( $depth + 1); // because it counts the first submenu as 0
            $classes = array(
                'sub-menu',
                ( $display_depth % 2  ? 'menu-odd' : 'menu-even' ),
                ( $display_depth >=2 ? 'sub-sub-menu' : '' ),
                'menu-depth-' . $display_depth
            );
            $class_names = implode( ' ', $classes );

            // Build HTML for output.
            $output .= "\n" . $indent . '<ul id="' . $this->curItem->post_name . '" class="' . $class_names . ' dropdown-content">' . "\n";
        }
     
        /**
         * Start the element output.
         *
         * Adds main/sub-classes to the list items and links.
         *
         * @param string $output Passed by reference. Used to append additional content.
         * @param object $item   Menu item data object.
         * @param int    $depth  Depth of menu item. Used for padding.
         * @param array  $args   An array of arguments. @see wp_nav_menu()
         * @param int    $id     Current item ID.
         */
        function start_el( &$output, $item, $depth = 0, $args = array(), $id = 0 ) {
            global $wp_query;
            $this->curItem = $item;
            $indent = ( $depth > 0 ? str_repeat( "\t", $depth ) : '' ); // code indent
     
            // Depth-dependent classes.
            $depth_classes = array(
                ( $depth == 0 ? 'main-menu-item' : 'sub-menu-item' ),
                ( $depth >=2 ? 'sub-sub-menu-item' : '' ),
                ( $depth % 2 ? 'menu-item-odd' : 'menu-item-even' ),
                'menu-item-depth-' . $depth
            );

            $depth_class_names = esc_attr( implode( ' ', $depth_classes ) );
     
            // Passed classes.
            $classes = empty( $item->classes ) ? array() : (array) $item->classes;
            $class_names = esc_attr( implode( ' ', apply_filters( 'nav_menu_css_class', array_filter( $classes ), $item ) ) );
     
            // Build HTML.
            $output .= $indent . '<li id="nav-menu-item-'. $item->ID . '" class="' . $depth_class_names . ' ' . $class_names . '">';
     
            // Link attributes.
            $attributes  = ! empty( $item->attr_title ) ? ' title="'  . esc_attr( $item->attr_title ) .'"' : '';
            $attributes .= ! empty( $item->target )     ? ' target="' . esc_attr( $item->target     ) .'"' : '';
            $attributes .= ! empty( $item->xfn )        ? ' rel="'    . esc_attr( $item->xfn        ) .'"' : '';
            $attributes .= ! empty( $item->url )        ? ' href="'   . esc_attr( $item->url        ) .'"' : '';
            $attributes .= ' class="menu-link ' . ( $depth > 0 ? 'sub-menu-link' : 'main-menu-link' ) . '"';

            if( in_array( 'menu-item-has-children', $item->classes ) ) 
                $attributes .= ' data-activates="' . $item->post_name . '"';

            // Build HTML output and pass through the proper filter.
            $item_output = sprintf( '%1$s<a%2$s>%3$s%4$s%5$s</a>%6$s',
                $args->before,
                $attributes,
                $args->link_before,
                apply_filters( 'the_title', $item->title, $item->ID ),
                $args->link_after,
                $args->after
            );
            $output .= apply_filters( 'walker_nav_menu_start_el', $item_output, $item, $depth, $args );
        }
    }

endif;
?>
```

**Comment by rabisnaqvi** [comment]
Anyone here got it working? I am still looking for the answer....

**Comment by tomscholz** [comment]
@rabisnaqvi I recently saw a tutorial over at [34sp.com](https://www.34sp.com/blog/wordpress-materialized-creating-material-design-theme-pt-1-theme-setup/) that explains how to achieve this.
