### ISSUE TITLE
Add few options to SideNav

### ISSUE THREAD

**Issue by SirusDoma** [Dogfalo/materialize#2277]
On current SideNav, when it's expanded, the whole page is dimmed but the SideNav it's self, and disappear when click / touch anywhere (this behavior can be disabled through `closeOnClick` props)

However, I think it will be useful for everyone if Materialize supports few types / options that would make SideNav work differently. You will probably put this issue on lowest priority because this may considered as essential features while the framework itself isn't fully completed yet as the version is not yet 1.0

But I think this will come handy in most situation for everyone that building kind of web apps, and here the following options i would like to suggest: 

1. Option to turn on / off the dimmed effect, when dim effect is turned off, the SideNav usually still remain when clicking anywhere, but of course, it will be preferable if the options is could be customized by the user (this may called "Docked SideNav" (?))
2. Customization of the sides of SideNav (whether it show on left side or right side or even able to add 2 sidenav that could appear on left and right side)
3. Option to turn on / off swipable option on mobile or device with touch support
4. Icons SideNav. A SideNav that consist with icons only, in android apps, this may come as sticky SideNav and expandable/collapsible to show/hide the menu text.
5. Lastly, the header SideNav, in Android Apps, the SideNav (or drawer) have the header, it come with simple App name and short brief description of the app and also the icon / logo of the app. Providing default SideNav header may useful for beginner also may help the others when creating a simple SideNav

That's all my ideas about the SideNav

**Comment by Dogfalo** [comment]
1. This already exists as our fixed SideNav.
2. Side Nav alreaddy supports right side positioning.
3. Since this is not a highly requested feature and doesnt not bring any significant gain we will not add this for now.

I'll create a separate issue for 4

5. Already exists as an issue https://github.com/Dogfalo/materialize/issues/1322
