### ISSUE TITLE
Icons are displayed as text

### ISSUE THREAD

**Issue by bali182** [Dogfalo/materialize#2279]
Hi guys,

This is what's happening, i have been trying to figure out why for hours, no luck:
![untitled](https://cloud.githubusercontent.com/assets/3879181/11100323/dfae65dc-88b0-11e5-98e4-965f8369e168.png)

This is my `index.html`, that you are seeing in the picture, the only thing I did different, is that I added a local copy of the `icon.css`, that you guys reference from a cdn, and changed it, so that it points to the `Material-Design-Icons.woff2` shipped with materialize:

```html
<!DOCTYPE html>
<html>
<head>
	<title>Test</title>
	<!-- components js -->
	<script type="text/javascript" src="../components/jquery/js/jquery.js"></script>
	<script type="text/javascript" src="../components/Materialize/js/materialize.js"></script>
	<!-- components css -->
	<link type="text/css" rel="stylesheet" href="../components/Materialize/css/materialize.css" />
	<!-- other css -->
	<link type="text/css" rel="stylesheet" href="../css/icon.css" />
</head>
<body>
	<a class="waves-effect waves-light btn"><i class="material-icons left">cloud</i>button</a>
</body>
</html>
```
Chrome shows, that material both `Material-Design-Icons.woff2` and `Roboto regular` are loaded.

This is the project structure:

```
+---components
|   +---jquery
|   |   \---js
|   |           jquery.js
|   |           
|   \---Materialize
|       +---css
|       |       materialize.css
|       |       
|       +---font
|       |   +---material-design-icons
|       |   |       Material-Design-Icons.woff2
|       |   |       
|       |   \---roboto
|       |           Roboto-Bold.woff2
|       |           Roboto-Light.woff2
|       |           Roboto-Medium.woff2
|       |           Roboto-Regular.woff2
|       |           Roboto-Thin.woff2
|       |           
|       \---js
|               materialize.js
|               
+---css
|       icon.css
+---html
|       index.html    <-- this is the index.html
``` 

Could anybody help, why this is happening? 
Thanks, Balazs

**Comment by SirusDoma** [comment]
I also encounter this with the lastest version.
I workarounds against this by changing `<i>` element with class based (e.g: '<i class="mdi-file-cloud"></i>') until they fix this...

or.. there is might something wrong with our setup(??)

**Comment by bali182** [comment]
This works perfectly! I was also sniffing around in the css looking for the font awesome style icon classes, but didn't found, that you have to put the category name there too, just tried `mdi-cloud`. Thanks! Also, while we are having this setup, it looks like here is a complete list of the icon classes: http://fezvrasta.github.io/bootstrap-material-design/bootstrap-elements.html (bottom of the page)

**Comment by SirusDoma** [comment]
@bali182 FYI, here is the official icons that provided by google:
https://www.google.com/design/icons/

try add `category` and replace space with `-` (e.g: to use `arrow drop down` icon under `navigation`, you should put it as`mdi-navigation-arrow-drop-down`)
