### ISSUE TITLE
Meteor materialize package: icons are missing (again)

### ISSUE THREAD

**Issue by M4v3R** [Dogfalo/materialize#2286]
I know about the issue #2224, however it doesn't help, icons are still missing. I'm using a fresh Meteor 1.2.1 project. First of all I see that `<link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">` line is already included in the HTML. The problem seems to be that the above CSS defines "Material Icons" font, while Materialize CSS expects the name "Material-Design-Icons".

However what's even more weird is that `package.js` file in materialize repository actually adds icon files as assets to the project, but when I inspect the generated CSS, it gives an incorrect path:

```
@font-face {
  font-family: "Material-Design-Icons";
  src: url("packages/materialize_materialize/dist/font/material-design-icons/Material-Design-Icons.eot?") format("embedded-opentype") -- SNIP --
  font-weight: normal;
  font-style: normal;
}
```

Note that the CSS expects the font to be found at `packages/materialize_materialize/dist/font/material-design-icons/Material-Design-Icons.eot`, but the real path is `packages/materialize_materialize/font/material-design-icons/Material-Design-Icons.eot` (note the missing `dist/`). Any ideas why `dist/` gets added to the path?

**Comment by acburst** [comment]
have you looked at #2272? Let me know if this works for you

**Comment by micaelpdias** [comment]
@acburst where can I find package.js after using meteor add?
I look in /root/.meteor/packages/materialize and the package.js is empty

**Comment by Wooobee** [comment]
exactly same problem for me: Update the package now I get the error:
`Failed to decode downloaded font: http://localhost:3000/packages/materialize_materialize/dist/font/material-design-icons/Material-Design-Icons.woff`
`(index):1 OTS parsing error: invalid version tag`

But I can find the files in under:
`http://localhost:3000/packages/materialize_materialize/font/material-design-icons/Material-Design-Icons.woff`

Best Manuel

**Comment by keyscores** [comment]
+1 still having issues with fonts in 0.97.5

**Comment by cesarve77** [comment]
1+

**Comment by Dogfalo** [comment]
All the old font files are removed. The correct way to use the icons is through the Google Font link.
