### ISSUE TITLE
Multiple Select init doesn't take count of <option selected>

### ISSUE THREAD

**Issue by rodofatos** [Dogfalo/materialize#2287]
Hi there, 
just tried with latest version(v0.97.2) to populate a <select> with <option selected> value and then call the js init on the select element. Everything is fine aside the fact that the values in the list are not checked. 
Is this an issue or i am doing something wrong, can someone advise ?

**Comment by TyrionGraphiste** [comment]
Just read : https://github.com/Dogfalo/materialize/issues/2274

**Comment by acburst** [comment]
Duplicate #2274
