### ISSUE TITLE
Question: original material color names

### ISSUE THREAD

**Issue by raveclassic** [Dogfalo/materialize#2288]
Hi all, thanks for this great project!

I have a simple question: why did you implement your own color palette instead of using [the spec](https://www.google.com/design/spec/style/color.html#color-color-palette)?
Right now I'm trying to adopt a project on [material-ui for react](http://material-ui.com/) to materialize because of their inline-styles and your color naming is a bit confusing.

What is the mapping between your palette (base color, light, dark) to google's one? (that table with numbers)

UPD: Is there any possibility to switch to google's spec to be more consistent with material design?

Thanks!

**Comment by acburst** [comment]
Are you looking at the same _color.scss file as I am? We copied the hex values exactly.

**Comment by raveclassic** [comment]
@acburst Hex values are correct, I meant only the naming: `amber-100`, `amber-200`...

**Comment by djensen47** [comment]
Agreed, I think it's both convenient and odd that the names are like .red.lighten-5. It would nice to also have .red500 and .redA200 and so forth. When I'm referencing colors from the spec and then go to materialize I have to convert red200 to lighten-2 or is is lighten-3?

**Comment by yanickrochon** [comment]
The project could support both naming conventions. I personally don't mind the `green-lighten-2`, etc.

For example

```
green-lighten-3 === green-200 === #A5D6A7

green accent-4 === green-a700 === #00C853

blue-grey lighten-1 === blue-gray-400 === #78909C
```

etc.

**Comment by Dogfalo** [comment]
Since the color classes are already very large when it comes to css output, we are not going to be supporting alternate naming conventions

**Comment by djensen47** [comment]
This is a little confusing. The Materialize naming convention _is_ an alternate naming convention. 

So will you be changing to use he standard MD spec or leaving it with the current alternate convention?

**Comment by tomscholz** [comment]
I agree with @djensen47 here. The naming convention is confusing. Even though it would be a breaking change, I think switching to a schema like `green-200` would make much more sense, since, as @djensen47 already pointed out, it is not always clear which materialize color is representing which color in the specs.
