### ISSUE TITLE
Materialize install not working via JSPM

### ISSUE THREAD

**Issue by asemahle** [Dogfalo/materialize#2290]
Currently, installing Materialize via JSPM as `jspm install github:Dogfalo/materialize` results in an empty file structure being added to the project. The empty file structure looks like this:

```
-materialize@0.97.2
|-font
| |-material-design-icons
| |-roboto
|-js
| |-bin
| |-date_picker
|-sass
| |-components
| | |-date_picker
```

I'm unsure whether this is a problem with Materialize or with JSPM. This behaviour occurs with versions 0.97.0, 0.97.1, and 0.97.2. Using JSPM to install version 0.96.1 works as expected.

Possibly related threads:
- Dogfalo/Materialize#1208 (so jspm isn't officially supported...)
- Dogfalo/Materialize#1637 (... though people have made it work in the past)

**Comment by Nivl** [comment]
Doing the following will give you all the files:

    jspm install github:dogfalo/materialize@master -o "{registry:'npm'}"

**Comment by KamilLelonek** [comment]
This gives me

```bash
GET http://127.0.0.1:56396/jQuery.js 404 (Not Found)
```

**Comment by clintharris** [comment]
@Nivl Thanks for the tip on using `master`--this fixed my problem.

@KamilLelonek I had the same problem; was able to fix it by adding a shim per #1637:
```
jspm install github:dogfalo/materialize@master -o "{ main: 'bin/materialize.js', shim: { 'bin/materialize.js': ['jquery'] }, format: 'global', dependencies: { 'jquery': '*' }, registry: 'npm'}"
```
The only issue I have now is figuring out to make these overrides persist in jspm's package.json or my systemjs config file. Otherwise, cloning my project and running `jspm install` won't include the overrides...

**Comment by clintharris** [comment]
Another issue related installing Materialize via JSPM (and loading it with jspm's default module loader, systemjs): **the wave effects don't work automatically**.

In a nutshell, the workaround is to manually call `Waves.displayEffects()` (note: newer versions of Waves usings `Waves.init()` instead):
```
import materialize from 'dogfalo/materialize';
materialize.Waves.displayEffect();
```
As you can see above, Materialize includes [Waves](http://fian.my.id/Waves) (a 3rd-party library which creates the ripple-like animations when you click on buttons, etc.)--you don't need to install it separately. It does contain a call to `Waves.displayEffect()` (as part of listening for the `DOMContentLoaded` event), but it doesn't seem to work.

**Comment by KamilLelonek** [comment]
@clintharris still no success.

```javascript
import 'dogfalo/materialize';
```

![image](https://cloud.githubusercontent.com/assets/3199333/11877700/3e3038a4-a4f1-11e5-9faa-8a922fa38068.png)

**Comment by fega** [comment]
@KamilLelonek Did you solve your problem?

Closed due inactivity, feel free to reopen it if it is still necessary.
