### ISSUE TITLE
Access to modal-trigger

### ISSUE THREAD

**Issue by mishantrop** [Dogfalo/materialize#2292]
How to access to modal-trigger within ready function?

```
$('.modal-trigger').leanModal({
      ready: function() { alert('Ready'); }
});
```

**Comment by acburst** [comment]
Could you explain this more? I'm not sure what you mean.

**Comment by gojigeje** [comment]
Maybe he want to pop up a modal when the DOM are ready? :confused:

**Comment by mishantrop** [comment]
I am sorry for this poor description (and my English) of what i want. 
For example, there is modal-trigger:
```
<a href="#modal" class="modal-trigger" data-id="42">Delete record #42</a>
```
So, I want have access to this modal-trigger in ready-callback of modal. 
```
$('.modal-trigger').leanModal({
    ready: function() {
        console.log('Are you sure want to delete record #' + $(modal).attr('data-id') + '?');
    }
});
```

**Comment by maziey93** [comment]
I need something exactly like this through some access to the modal that can exactly be triggered, in  the likes of: 
'''

	$('.modal-trigger').leanModal({
      ready: function() { $(this).addClass('animated bounceOutLeft'); }, // Callback for Modal open
      complete: function() { $(this).addClass('animated bounceOutLeft'); } // Callback for Modal close
	})
'''

**Comment by mishantrop** [comment]
@maziey93, I know how to get access to modal, but I need get access to modal-trigger.

**Comment by fega** [comment]
Closed due inactivity, feel free to reopen it if it is still necessary.
