### ISSUE TITLE
Reduce npm tarball size (23MB)

### ISSUE THREAD

**Issue by ratson** [Dogfalo/materialize#2293]
The file size of https://registry.npmjs.org/materialize-css/-/materialize-css-0.97.2.tgz is pretty big due to the images and other static assets for the website, which are not necessary for package user.

It would be great if this could be improved, even though internet speed is fast these days.

**Comment by Dogfalo** [comment]
I added the images folder to the npmignore. But I will leave the rest of the documentation in because others have requested it to be in there.
