### ISSUE TITLE
Uncaught TypeError: c.className.indexOf is not a function

### ISSUE THREAD

**Issue by MHerszak** [Dogfalo/materialize#2297]
Hi,

I am using your package with meteor and I am getting the following error: *Uncaught TypeError: c.className.indexOf is not a function* when I click on a button. Debugging is a bitch with minified files. Any idea what that could be?

![screen shot 2015-11-14 at 17 54 45](https://cloud.githubusercontent.com/assets/4604432/11166605/2c0eb3a6-8af9-11e5-9a31-5d32c015391b.png)

**Comment by acburst** [comment]
Can you post your html?

**Comment by MHerszak** [comment]
It's all React components. No HTML.

**Comment by acburst** [comment]
Have you tried using the unminified files? You can download the latest master files.

**Comment by MHerszak** [comment]
I will try that and close this issue for now.
