### ISSUE TITLE
[Enhancement] Why the need for your own javascript initalize file?

### ISSUE THREAD

**Issue by KeithBohler** [Dogfalo/materialize#2299]
A bit of an unfortunate for MaterializeCSS, is that it requires a init javascript file for the toggles and other javascript related features to operate. I love Materialize, but the problem is that it requires the extra work that I'm not entirely familiar with. Where as Bootstrap, allows all these toggles and things to immediately work by implementing the scripts in the HTML file. Just a suggestion and piece of my mind, but other than that regard.. everything else is great.

**Comment by tomscholz** [comment]
You can initialize all the functions from within a script tag in a html file aswell
