### ISSUE TITLE
Progress bars

### ISSUE THREAD

**Issue by Dogfalo** [Dogfalo/materialize#23]

**Comment by davidsoderberg** [comment]
What are your toughts on this, maybe I can help?

**Comment by Dogfalo** [comment]
We are dealing with other parts of the framework right now so it would be great if you could help!

**Comment by davidsoderberg** [comment]
Sure, any toughts on this yet?

**Comment by acburst** [comment]
Take a look at this http://www.google.com/design/spec/components/progress-activity.html#progress-activity-types-of-indicators under the linear section.

If you want, you could try making the indeterminate progress bar, and maybe some form of determinate progress bar where you can have some attribute or class that sets how full the percentage is.

**Comment by davidsoderberg** [comment]
Maybe we could make it an jquery plugin?

**Comment by Dogfalo** [comment]
I don't think jQuery should be necessary here.

On Thu, Jan 8, 2015 at 12:59 PM, David Söderberg <notifications@github.com>
wrote:

> Maybe we could make it an jquery plugin?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Dogfalo/materialize/issues/23#issuecomment-69220244>.
>



-- 
Doggy sends his greetings from Mars.

**Comment by davidsoderberg** [comment]
I thinking about setting width of progess, how that will be easy to make with css. 100 classes is not a good solution. We can set it on a div like this ```style="width: 80%;``` But that is not nice if you ask me...

**Comment by acburst** [comment]
How about you just try making the indeterminate bar first and we can think about the other one after

**Comment by davidsoderberg** [comment]
Alright :smile:

**Comment by davidsoderberg** [comment]
Alright here is a first try:
CSS:
```
.progress {
	position: relative;
	height: 5px;
	display: block;
	width: 100%;
	background-color: #c7c7c7;
	margin: 1em 0;
	overflow: hidden;
}
.indeterminate {
	position: absolute;
	top: 0;
	right: 0;
	bottom: 0;
	left: 0;
	-webkit-animation: indeterminate 1s linear infinite;
}

@-webkit-keyframes indeterminate {
	0% {
		-webkit-transform: translate(-100%);
	}
	50% {
		-webkit-transform: translate(0%);
	}
	100% {
		-webkit-transform: translate(100%);
	}
}
```
And HTML:
```
<div class="progress">					
	<div class="indeterminate red"></div>
</div>
```
So what do you think?

**Comment by acburst** [comment]
It's looking pretty good. Do you wanna try experimenting with some easing?

**Comment by davidsoderberg** [comment]
Sure but I thought I could do determinate first :)

**Comment by Dogfalo** [comment]
Also fee free to join our chat room here, where it is easier to have discussion about new features. https://gitter.im/Dogfalo/materialize

**Comment by Dogfalo** [comment]
Added in 0c4e9b93ac7e14309d92e5d838957127f3845df4
