### ISSUE TITLE
Production ready?

### ISSUE THREAD

**Issue by jesperordrup** [Dogfalo/materialize#2303]
Hi there

Just tried using forms and select and it doesnt works. I'll report it - but for now just asking what is the current status on this project? 

best
jesper

**Comment by acburst** [comment]
Duplicate of #2265. There have been many issues opened about select if you wanna search them for solutions. Many people are using Materialize in a production ready way (checkout the showcase!). There are more bugs than we'd like but we are working hard on fixing them.
