### ISSUE TITLE
Mobile Collapse Button in ipad safari is not work

### ISSUE THREAD

**Issue by c941010623** [Dogfalo/materialize#2306]
in my ipad 2 ios 9.0 and use safari look Mobile Collapse Button

it's not work  and very not normal

**Comment by ItsLukeJames** [comment]
I've seen some websites using 0.95.3 javascript&css and it's working fine; try that

**Comment by ItsLukeJames** [comment]
Same problem for me, I need a fix ASAP.

**Comment by ItsLukeJames** [comment]
I've found a fix; 

On a computer, shorten your Browser to a size where the Collapse button is showing, then enter the javascript console and type;
    $(".button-collapse").sideNav();
and hit enter.
If the button is working in the browser then the issue is probably the javascript surrounded by that one line in your code.

**Comment by c941010623** [comment]
i use
<meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0, user-scalable=no">
and it's ok
and work very good

**Comment by c941010623** [comment]
i use
meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0, user-scalable=no"

and work very good

**Comment by janbaer** [comment]
I've the same problem here with the latest mobile version of Safari.

**Comment by manindragautam** [comment]
### Just Add this script in the end of body of html or xml between script tags
`(function($){
  $(function(){

     $('.button-collapse').sideNav();

  }); // end of document ready
})(jQuery); // end of jQuery name space`

**Comment by janbaer** [comment]
@manindragautam Thank you very much fpr the tip, it works now also in Safari! The strange is, that I also called the **sideNav** function, but within my Angular 2 code and it seem that this has worked with Chrome but not with Safari...

**Comment by manindragautam** [comment]
@janbaer So it's working perfectly everywhere or not

**Comment by janbaer** [comment]
@manindragautam Yes, it's working now also in Safari mobile!
