### ISSUE TITLE
IE11 hover bug with dropdown in nav

### ISSUE THREAD

**Issue by coffeeneed** [Dogfalo/materialize#2307]
![materialize_dropdown_bug](https://cloud.githubusercontent.com/assets/11244539/11177906/33281a14-8c49-11e5-8671-e5d5fffc8a11.jpg)

Have a look at the image (it's a screenshot from http://materializecss.com/navbar.html). When hovering the dropdown item (or in the lower vicinity) in Internet Explorer 11 it shows an empty div. Is this a bug and will be fixed?

I should mention that when clicking, the dropdown meny shows correctly.

Ideas?

**Comment by fega** [comment]
I doesn't have IE 11, could you check if this is still an issue with the last version?

Closed due inactivity, feel free to reopen it if it is still necessary.

**Comment by gajmp** [comment]
Its still exists. I have checked in IE 10 and 11. (below screenshot took in IE10) In both version its showing in the down. if we add inline-block then its corrected. but we need the default one
![navbar](https://user-images.githubusercontent.com/1171132/34811428-d785be38-f6c6-11e7-8e84-b12219a2f2bd.png)
