### ISSUE TITLE
v0.97.3 broke column offset

### ISSUE THREAD

**Issue by hanzki** [Dogfalo/materialize#2308]
In v0.97.2 the column offset rules were defined after column size rules which made the offset to correctly override the margin style. But in the latest release the offsets are defined in the midst of the column size rules which causes problems if the size of the offset is smaller than the size of the column.

Here's an example:
```html
<div class="row">
    <div class="col s8 offset-s2">
        <!-- column content here -->
    </div>
</div> 
```

**Comment by alijaffar** [comment]
:+1: 
I noticed offset-m1 no longer offset... I made a temporary solution w/ CSS:
removing margin-left: 0; from below should allow it to work, but hmm... needs a real fix.
`
.col.m3 {
    width: 25%;
    margin-left: none;
`

**Comment by acburst** [comment]
Hmm, this should've been a problem in 0.97.2 as well.

Anyways, fixed in d5db2a3

**Comment by lid3rs** [comment]
Sorry for a stupid question, but how can i update? bower update seems like not fixing the issue.

**Comment by beforeadream** [comment]
I'd suggest wait for the next release, or rollback to previous one. 

Correct me if I'm wrong.

**Comment by lid3rs** [comment]
Thank you. Rolled back.

**Comment by FiestaUSA** [comment]
Does anybody have the older release? I copied over my current one when I updated :(

**Comment by beforeadream** [comment]
@FiestaUSA I'd suggest you take a look at bower.io

**Comment by beforeadream** [comment]
Or you can always find older version here https://github.com/Dogfalo/materialize/releases
