### ISSUE TITLE
v0.97.3 : SELECT - last option not selectable.

### ISSUE THREAD

**Issue by cunneen** [Dogfalo/materialize#2309]
The last item in a select is not selectable.
See here for reproduction:

http://codepen.io/anon/pen/ojmwVe

**Comment by TyrionGraphiste** [comment]
It appears this is because the dropdown is higher than the window height, but it's very specific to this demo.
The click is never triggered.

**Comment by cunneen** [comment]
You're right: it's not just the last option that exhibits the problem; ANY
option that needs to be scrolled into view is not selectable. Playing with
the zoom level and panel height helps to illustrate this.

**Comment by beforeadream** [comment]
+1

**Comment by benthepoet** [comment]
+1

**Comment by felipemarin** [comment]
+1

**Comment by acburst** [comment]
merged in 8600af568a548d6ac5a0e3f5ee3a24da0093c564
