### ISSUE TITLE
Scrollable tabs example

### ISSUE THREAD

**Issue by SirusDoma** [Dogfalo/materialize#2311]
As 0.97.2 released, I noticed that finally materialize add Scrollable tabs.
However I can't find the example on documentation..

**Comment by acburst** [comment]
There is no markup difference. It's just when the width of the tabs container is small enough it will allow you to scroll horizontally through the tabs

**Comment by acburst** [comment]
But anyways, I added an example here a27f00b9e18fd29e7e164096e68b1f1e146e8c82
