### ISSUE TITLE
Broken grid

### ISSUE THREAD

**Issue by beforeadream** [Dogfalo/materialize#2313]
Seems like after updating to 0.97.3 `offset-s*` properties are broken. Could you check it?

![untitled](https://cloud.githubusercontent.com/assets/864218/11197882/1e2adf22-8cc9-11e5-8e9d-e8288b3d6b9f.gif)

Correct me, please, if I'm wrong.

Thanks a lot for a great framework! :kissing_closed_eyes:

**Comment by lid3rs** [comment]
Confirmed

**Comment by acburst** [comment]
I have committed a fix already. Sorry for the inconvenience!

Duplicate of #2308

**Comment by beforeadream** [comment]
@acburst oh, I see. Thanks a lot! :+1:
