### ISSUE TITLE
Offsetting

### ISSUE THREAD

**Issue by scalagos0123** [Dogfalo/materialize#2316]
Offset doesnt work on the new update (0.97.3)

**Comment by beforeadream** [comment]
Already reported and even fixed :+1: 

https://github.com/Dogfalo/materialize/issues/2313
https://github.com/Dogfalo/materialize/issues/2312
https://github.com/Dogfalo/materialize/issues/2308

https://github.com/Dogfalo/materialize/commit/d5db2a3290ab2848f4482aae2933756b8e357346

**Comment by acburst** [comment]
Duplicate
