### ISSUE TITLE
Styled input file button

### ISSUE THREAD

**Issue by italomaia** [Dogfalo/materialize#232]
Hello folks! These days I made my first materialize design. It looks gorgeous. When inserting a input file, tough, it looked plain ugly. I know how messy it is to style a input file button, but, is it a goal in the short term to style these kind of buttons?

**Comment by newmanw** [comment]
+1

**Comment by acburst** [comment]
Added in 763c0e5113d0753983286acfa3253b66eacdac6d!

Let me know what you guys think
