### ISSUE TITLE
Pushpin feature doc

### ISSUE THREAD

**Issue by mambax** [Dogfalo/materialize#2320]
It seems that the docs of [Pushpin](http://materializecss.com/pushpin.html) are not up to date with the demo site itself.
Neither is there a class called 'tabs-wrapper' in the DOM-Tree, nor is there a valid HTML code example in the docs.

Therefore I struggle to get the following structure running...

```
<div class="row">
    <div class="col s12 m3 l2">
        <div class="tabs-wrapper">
            <p>I am a very simple card. I am good at containing small bits of information. I am convenient because I require little markup to use effectively.</p>
            <a href="#">This is a link</a>
            <a href="#">This is a link</a>
        </div>
    </div>
    <div class="col s12 m9 l10">
        <div ui-view class="uiview container"> </div>
    </div>
</div>
```

Since the docs do not tell how to use that class and where to put it and there is also no reliable code in the HTML itself, please fix that. And keep up the good work :)

**Comment by samdeman22** [comment]
Did you get this working? If so how? I'm also seeing this as an issue, no html tied to the jquery function in the documentation to look at.

**Comment by mambax** [comment]
I did not follow further, sorry to disappoint.

**Comment by j4zz** [comment]
I’m struggling with the same issue. Please update the documentation.

**Comment by sfarzy** [comment]
This  file has an working example,  [pushpin.html](https://github.com/Dogfalo/materialize/blob/de2be388be189bc8b92f021c4188d94b400e3a4c/test/html/pushpin.html).

Here are the relevant sections.

### HTML
```html
<nav>
    <div class="nav-wrapper">
        <a href="#" class="brand-logo">Dynamic Top and Bottom at 500px</a>
        <ul id="nav-mobile" class="right hide-on-med-and-down">
            <li><a id="removePushPin" class="waves-effect waves-light btn">Remove PushPin</a></li>
            <li><a id="topTo200" class="waves-effect waves-light btn">Change Top to 200px</a></li>
            <li><a id="bottomTo200" class="waves-effect waves-light btn">Change Bottom to 200px</a></li>
        </ul>
    </div>
</nav>
```
### JS
```js
$( document ).ready(function() {
$('nav').pushpin({
  top: $('nav').offset().top,
  bottom: 500
});

$(window).on('scroll', function() {
  $('#scrollTop').text($(window).scrollTop());
});

$('#removePushPin').on('click', function() {
  $('nav').pushpin('remove');
});

$('#bottomTo200').on('click', function() {
  $('nav').pushpin({
    bottom: 200
  });
});

$('#topTo200').on('click', function() {
  $('nav').pushpin({
    top: 200
  });
});
});
```

**Comment by acburst** [comment]
Added a demo to pushpin in 6c1aaaf
