### ISSUE TITLE
Grid offset not working after update

### ISSUE THREAD

**Issue by Messier82** [Dogfalo/materialize#2325]
Have updated from 0.97.1 to 0.97.3 and grid offset stopped working. Here's the code:
```HTML
<div class="row" style="margin-top: -80px;">
      <div class="col l8 offset-l2 m10 offset-m1 s12">
          <ng-view></ng-view>
      </div>
</div>
```

Also, I have noticed, that in Chrome dev-tool col l8 class is overwriting margin rule of offset-l2 class.
![overwriting rule](https://i.gyazo.com/2e49bc0e9803a83d367706bbbeb55c0f.png)

**Comment by Messier82** [comment]
That it looks on the v0.93.1 with the same code
![not overwriting rule](https://i.gyazo.com/8586d376376a0a76ea9a074985863244.png)

**Comment by jeffijoe** [comment]
Same issue.

![Image](https://files.gitter.im/Dogfalo/materialize/Uj5g/blob)

**Comment by Messier82** [comment]
Found, that It's already fixed in https://github.com/Dogfalo/materialize/commit/d5db2a3290ab2848f4482aae2933756b8e357346

**Comment by jeffijoe** [comment]
@Messier82 do you know when this fix will come to an NPM near me?

**Comment by Messier82** [comment]
@jeffijoe no. I just downloaded https://github.com/Dogfalo/materialize/blob/master/bin/materialize.css from github and placed it in my project.
