### ISSUE TITLE
Translate docs for other languages

### ISSUE THREAD

**Issue by thebergamo** [Dogfalo/materialize#233]
Well, I'm like very much Materialize and maybe is very cool if the project can be translated for other languages like mine (pt-br) and a pack for translation the docs can be closer for other peoples starting this fantastic world of development, but some not be able to read in English.

Thanks for your attention and this project is Gorgeous!

**Comment by pwmvx1289** [comment]
I can help translating to Chinese.

**Comment by Dogfalo** [comment]
If you want to email me, I can add you to the translation team

**Comment by RaSeR** [comment]
@Dogfalo I can help with Russian

**Comment by lukaspijak** [comment]
I can help with Czech

**Comment by mazzie14** [comment]
I can help with Dutch if needed

**Comment by Dogfalo** [comment]
@RaSeR @lukaspijak email me your email address and I can add you to the team.

**Comment by lukaspijak** [comment]
Unfortunately, a lot of phrases is not allowed to translate.

**Comment by carloscarcamo** [comment]
Hey @Dogfalo I saw that there are new content to translate, would be good if you add more strings on transifex for translating.

**Comment by ilyaulyanov** [comment]
@Dogfalo Do you still need an English to Russian translator?

**Comment by Dogfalo** [comment]
Yes we do! Our Russian translation is only mostly done. If you could send me your email address, I can set you up on the translation team

**Comment by danilolutz** [comment]
@Dogfalo I want to contribute with brazilian portuguese translation!!

**Comment by Dogfalo** [comment]
Email me your email address and I can set you up as well!

**Comment by scerelli** [comment]
I van help with italiano translation!

**Comment by danilolutz** [comment]
We need a reviewer for portuguese translation!

**Comment by Dogfalo** [comment]
@scerelli I emailed you.

**Comment by 19Gerhard85** [comment]
@Dogfalo I can provide you the german translation.

**Comment by Dogfalo** [comment]
@19Gerhard85 Can you send me an email so I can get your email address? I'll send you an invite afterwards.

**Comment by Dogfalo** [comment]
I added new content to be translated since we have added new things to our documentation. Thanks for your hard work everyone!

**Comment by Dogfalo** [comment]
Translation progress:
![](http://puu.sh/gyzsy/e1d9eeac0c.png)

**Comment by m-blank** [comment]
@Dogfalo Do you need another german translator?

**Comment by lukaspijak** [comment]
Czech language finished. I'll proofread later.

**Comment by danilolutz** [comment]
100% of pt translation!

**Comment by Dogfalo** [comment]
@m-blank Send me an email and I will add you to the translation team!

**Comment by carloscarcamo** [comment]
Spanish at 100% :)

**Comment by brunopulis** [comment]
@Dogfalo Some strings on getting-started.html aren't translated to Portuguese. How can I contribute?

**Comment by danilolutz** [comment]
@brunopulis The strings that was not translated aren't picked to translation!

**Comment by Dogfalo** [comment]
@brunopulis which strings are you concerned about?

**Comment by brunopulis** [comment]
@Dogfalo The strings of **CDN**, **NPM**, **RubyGem** and there are some spelling mistakes in Portuguese that need to be corrected.

**Comment by Dogfalo** [comment]
I can add you to the translation team if you want to help correct these issues.

**Comment by brunopulis** [comment]
@Dogfalo Off course! :D I can help to correct these issues.

**Comment by danilolutz** [comment]
@Dogfalo This strings must be picked up!

![untitled](https://cloud.githubusercontent.com/assets/1561739/6917167/950b8256-d778-11e4-944e-bfd8bfdaa663.png)

**Comment by danilolutz** [comment]
@Dogfalo  And include @brunopulis to help me improve the portuguese translation! =D

**Comment by heyalexej** [comment]
German seems to be somewhat behind. Feel free to add me @Dogfalo. I'm a native German speaker with a thorough understanding of the English language. Would love to help.

**Comment by Dogfalo** [comment]
Send me an email so I can add you! @heyalexej

**Comment by heyalexej** [comment]
Done.

**Comment by brunopulis** [comment]
@Dogfalo You added me to help @danilolutz  to improve the translation into Portuguese?

**Comment by akyunus** [comment]
Is there any turkish translator?

**Comment by kovkus** [comment]
@Dogfalo can you invite me to do slovak translation ? davidkovac99@gmail.com

**Comment by carloscarcamo** [comment]
Hey @Dogfalo, there are new things on materialize website, would be good to add some strings on transifex for translation.

**Comment by mbrandau** [comment]
If still needed I can help with german.

**Comment by javatlacati** [comment]
@Dogfalo  I can help with Spanish and Italian

**Comment by poppinlp** [comment]
@Dogfalo 
I can help with Chinese and already send request on Transifex. 
Here's a material design documentation that i have translated: https://github.com/1sters/material_design_zh

**Comment by GuibertLo** [comment]
Hello ! I can help to translate in french if you need it :)

**Comment by akyunus** [comment]
@Dogfalo , I'm also ready for turkish translation.

**Comment by jgg0218** [comment]
@Dogfalo can I have an invitation to help with the Spanish there's more to translate .

**Comment by TyrionGraphiste** [comment]
Hi ! I can help for french traductions if you need :)

**Comment by keika299** [comment]
@Dogfalo  I can translate to Japanese.
Please invite me on Transifex!

**Comment by Dogfalo** [comment]
@keika299 @jgg0218 I added you to the team. @TyrionGraphiste @akyunus Please send me an email so I can have an email address to send the invite to!

**Comment by keika299** [comment]
Thank you!
My friend can translate to Japanese, too.
If I can work with her, please invite her! (Already she sent request on Transifex! Her name is Sena.)

**Comment by jgg0218** [comment]
Dont know what went wrong when i log on on transifex it appears that i m
not a member of the group. Even if I log in with the github account could
you accept the invitation I did again in transifex Thanks.

On Mon, Sep 28, 2015, 1:56 AM Alvin Wang <notifications@github.com> wrote:

> @keika299 <https://github.com/keika299> @jgg0218
> <https://github.com/jgg0218> I added you to the team. @TyrionGraphiste
> <https://github.com/TyrionGraphiste> @akyunus <https://github.com/akyunus>
> Please send me an email so I can have an email address to send the invite
> to!
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Dogfalo/materialize/issues/233#issuecomment-143646197>
> .
>
--

**Comment by SuperDJ** [comment]
I could help with Dutch translation

**Comment by puilp0502** [comment]
Can you invite me to Transifex? Seems like there are a lot of words remaining that need to be translated to Korean. (I already sent a request)

**Comment by puilp0502** [comment]
@Dogfalo I think there are some "uncollected" strings which seems to be untranslatable....

**Comment by elabsir** [comment]
@Dogfalo I can translate to Persian [Farsi]

**Comment by MetaiR** [comment]
@bessmartir please help for develope this site materializertl.ir
@Dogfalo I can translate to Presian too

**Comment by TyrionGraphiste** [comment]
@Dogfalo I send a mail there is a while, but no response until here.

**Comment by roccomuso** [comment]
@Dogfalo I can help with Italian. I'm sending you my email.

**Comment by ziemek99** [comment]
I can try translating into Polish 😊

**Comment by CesarGonzalezM** [comment]
@Dogfalo another spanish helper over here :D

**Comment by sikha** [comment]
Can you give link to transifex or add me in team ?

**Comment by PabloDinella** [comment]
Hey, I'm a lot of english text on the docs, but when I head onto https://www.transifex.com/materialize/materialize/language/pt/ it says the translation to portuguese is 100%, which is not true... How can we proceed? I want to translate the parts that are not translated yet.

**Comment by cikal** [comment]
@Dogfalo i want join too with my language Indonesian.. can you invite mee too??

**Comment by OmarEinea** [comment]
@Dogfalo I'm willing to translate the docs to Arabic, I've sent a request to join on transifex.com and waiting for your approval :)

**Comment by phongphan117** [comment]
I need to translate to Thai, please.

**Comment by vaheqelyan** [comment]
You can just use yandex translate api and easily to translate  documentation. You need to get an api key,it is absolutely free.

 translate as much as you want.

 https://tech.yandex.com/translate/

**Comment by Dargmuesli** [comment]
I sent a request to join the German-Squad :)

**Comment by Dargmuesli** [comment]
@Dogfalo @acburst I would really like to translate as some German translations are misspelled and simply wrong. It would be great if one of you could accept my request as the current translation really annoys me.

**Comment by Dogfalo** [comment]
@Dargmuesli I didn't see your request, but I sent an invite to your listed email address.

**Comment by athagoras** [comment]
@Dogfalo Can you add Thai language in your transifex project, please?

**Comment by Dargmuesli** [comment]
Ok, project "translate 380 English strings to German in three days" is finally finished!
Though, as others mentioned, not all string can be translated via transifex.

**Comment by Songbird0** [comment]
Hi there, I can help to translate in french ! :)

**Comment by Dogfalo** [comment]
@Dargmuesli Thanks for your hard work!

**Comment by MatheusFreitag** [comment]
Hello guys! 
As @PabloDinella pointed out, if you check https://www.transifex.com/materialize/materialize/language/pt/ it will say Portuguese is 100% done, but this is not true. 

With this screenshot as an example, you can see we currently have a mix of portuguese and english in every major page of the documentation. 

![screen shot 2017-04-01 at 10 27 01 pm](https://cloud.githubusercontent.com/assets/2220005/24583759/063c9330-172c-11e7-9ba8-9363c5091d86.png)

I would be glad to help with the missing translations but I don't know how to proceed. Is there any way to help?
Thanks guys!

**Comment by tomscholz** [comment]
@Dogfalo since only you have admin access to the transifex account, I would please you, to look into this

**Comment by NonameSLdev** [comment]
@Dogfalo I can translate it into Hebrew. Add me to transifex and I'll help. Also, perhaps we can close this issue?

**Comment by tomscholz** [comment]
> If you want to help us translate the documentation into other languages, please send us an email at materializeframework@gmail.com telling us which language team you want to join. We use Transifex as our localization platform and we will send you an invite there.

https://github.com/Dogfalo/materialize#translation
