### ISSUE TITLE
Q: What I should do if tabs content width not fitting parent element?

### ISSUE THREAD

**Issue by Messier82** [Dogfalo/materialize#2330]
Hello!
Here's my situation: I have tabs panel and parent element width based on column system. What should I do, if I have a lot of tab items and they do not fit inside parent element? For example: we have normal fitting on desktop, but, on mobile, they don't fit and appears vertical scrollbar for the whole site. Is it possible, to do, as it's done in, for example, Google Play? There scrolling appears only for tab section.

**Comment by acburst** [comment]
Can you post some sample code?

**Comment by Messier82** [comment]
I'm using AngularJS:
<b>menubar.html(view/template)</b>
```HTML
<div class="blue col s12">
    <div class="col l8 offset-l2 m10 offset-m1 s12">
        <ul style="color: white; background: transparent;" class="tabs">
            <div ng-repeat="item in items">
                <li class="tab waves-effect waves-light" style="width: 110px;"><a href="{{ item.url}}" class="white-text">{{ item.name}}</a></li>
            </div>
        </ul>
    </div>
</div>

<script>
    $('ul.tabs').tabs();
</script>
```

<b>MenuBarController.js</b>
```JS
var MenuBarController = mainModule.controller("MenuBarController", ["$scope", function ($scope) {
        $scope.items = [
            {
                name: "Home",
                url: "#home"
            },
            {
                name: "About Us",
                url: "#about"
            },
            {
                name: "Contacts",
                url: "#contacts"
            },{
                name: "Contact Us",
                url: "#contact"
            }
        ];
    }]);
```

Here we can see fixed width for all elements(unfortunately I didn't managed, why ng-repeat ignores percentage widths).
That's how it looks on desktop:
![desktop view](https://i.gyazo.com/9dd7fa2ffca7a43f0eef6947f136378b.png)

That's how it looks on mobile:
![mobile look](https://i.gyazo.com/00e369c640e883d17802ebb4be1419db.png)

As you can see, tabs isn't fitting inside whole viewport width, that causes scrollbar appearing for the whole site.
![scrolled mobile view](https://i.gyazo.com/ab89cfd60631eb440b4da5f91f73f1ef.png)

I want, that scrollbar be appeared only for tabs section and scrolls only tabs section, like it is in Google Play, for example.

**Comment by Messier82** [comment]
Okay, found, that in last version(from github) it is already done, but, when the scrollbar isn't needed(desktop version, for example) - scrollbar doesn't hide.
![scollbar don't dissapear](https://i.gyazo.com/b0934b9f61793f8cea9c8058c4b832c3.png)

**Comment by acburst** [comment]
Changed overflow-x to auto in 221a242.

Thanks for pointing this out!
