### ISSUE TITLE
Issues on _grid.scss

### ISSUE THREAD

**Issue by serdimoa** [Dogfalo/materialize#2331]
Hi, why in this code have margin-left:0; 
its not good. For me and i mean on other people. We want centered all)
    @media #{$large-and-up} {

      $i: 1;
      @while $i <= $num-cols {
        $perc: unquote((100 / ($num-cols / $i)) + "%");
        &.l#{$i} {
          width: $perc;
          margin-left: 0;
        }

**Comment by TyrionGraphiste** [comment]
You should have search for same issues before open this one.
