### ISSUE TITLE
Toast and Modal

### ISSUE THREAD

**Issue by khlJunior** [Dogfalo/materialize#2332]
I have a Modal, and inside the modal i have a function that call a Toast, but the Toast is behind the modal overlay. There's a way that toast will be show over everything?

**Comment by TyrionGraphiste** [comment]
Modify the toast z-index css property.

**Comment by khlJunior** [comment]
Wow, it was my fault, i was trying to add a classe with a new z-index property, i've changed directly on materialize css and now is working :) thank you. sorry about that.

**Comment by TyrionGraphiste** [comment]
If you solved your problem I think you can close your issue.
