### ISSUE TITLE
Datepicker appear automatically whenever I view the webpage

### ISSUE THREAD

**Issue by Mr-Zer0** [Dogfalo/materialize#2336]
I click datepicker field and set date. And close the datepicker. It is ok. After that I switch another window (from chrome to sublime text). When I switch back to this page (at chrome) datepicker pop-up automatically. I close it again and switch another window again and switch back again the datepicker pop-up again automatically. Thanks.

**Comment by Dogfalo** [comment]
Duplicate of #2067
