### ISSUE TITLE
Radio button not showing when Input tag placed inside Label tag

### ISSUE THREAD

**Issue by donskifarrell** [Dogfalo/materialize#2339]
I'm creating a radio button input with the following code:

```
  <label>
    <input class="with-gap center" name="lens" type="radio" value="yes" />
          Yes
  </label>
```

Which will show the label 'Yes' but does not show the radio button to click. 
Using the 'for' attribute works correctly though.

I'm unable to use the 'for' attribute as I am re-using the same form twice on one page and so the click's interfere.

**Comment by MJafarMashhadi** [comment]
Or if input tag is placed after label tag. 
That's a huge problem in right to left languages like Persian, Hebrew and Arabic.

**Comment by MJafarMashhadi** [comment]
[Related codepen](http://codepen.io/anon/pen/bEzJBB)

Note that [Django form API](https://docs.djangoproject.com/en/1.9/topics/forms/) puts `input` inside `label` tag. This bug makes life harder for Django developers who use materialize!

**Comment by Cedricdelcroix** [comment]
hey @donskifarrell ! 
I have the same problem ! 
I'm looking for solve it . 
How do you solve yours ?

**Comment by donskifarrell** [comment]
Hi,

I was using early Angular2 beta's, so my app was all componentised. I made a hacky workaround that created a guid each time the component was created, meaning that the id's on the input/label combo was unique to each component and therefore the page. Roughly:

```
<div>
  <input id="{{reused + guid}}">
  <label for="{{reused + guid}}">
</div>
```

This was a while ago so things may have moved on since then to make this easier (hopefully)

**Comment by tomscholz** [comment]
Closed due inactivity. Feel free to reopen it, if it's still necessary.

**Comment by TheCodingRecruiter** [comment]
2019, still an issue.  Can't seem to get it to work unless I put a label at the start and then another label after the closed span.  Then it doesn't register the value of the object.

**Comment by lucodyne** [comment]
Having this same issue, not finding a solution for it

**Comment by pwcreative** [comment]
@TheCodingRecruiter can you provide a simple codepen showing the problem? I'm not clear what the issue is. Original post said that he couldn't use a a for attribute because he is using a duplicate form - that in itself is an issue with the developers code and not a materialize issue I think?

**Comment by ghost** [comment]
making sure the label text ("Yes" in this case) was wrapped in span tags fixed this problem for me
