### ISSUE TITLE
collapsible accordian is not working after latest update

### ISSUE THREAD

**Issue by sbsomya** [Dogfalo/materialize#2341]
Previously was working applied the latest javascript for multiple select option but collapsible accordian is not working

**Comment by acburst** [comment]
Please show some code examples or a codepen.

**Comment by sbsomya** [comment]
Resolved it actually was adding dynamically the li elements and initializing it by the following code

$('.collapsible').collapsible({
        accordion : false // A setting that changes the collapsible behavior to expandable instead of the default accordion style
    });

After commenting this it worked (Ideally should be there according to docs)
