### ISSUE TITLE
New transition suggestion (example code too)

### ISSUE THREAD

**Issue by k4kfh** [Dogfalo/materialize#2343]
I am in the process of building a one-page Material Design site, using a combination of my own work and MaterializeCSS. I found myself searching for a way to apply the ``Materialize.showStaggeredList()` transition to things other than list elements, and I didn't find an easy way to do it, so I modified the staggered list function to fit my needs.

This code sample is the entire transition function, written in JavaScript and requiring jQuery to run.

``` javascript
transition.slideIn = function(selector, durationARG, startPosition) {

    //Make sure opacity is set to 0
    $(selector).css("opacity", 0)

    //If duration isn't specified
    if (durationARG == undefined) {
        durationARG = 800;
    }
    //If start position isn't specified, revert to default
    if (startPosition == undefined) {
        startPosition = "-500px";
    }

    var time = 0;
    $(selector).velocity(
        { translateX: "-500px"},
        { duration: 0 });

    $(selector).velocity(
        { opacity: "1", translateX: "0"},
        { duration: durationARG, delay: time, easing: [60, 10] }
    );
    time += 120;
  };
```

`selector` is a normal selector argument, like on the other transition functions.

`durationARG` sets how long the animation lasts. It has a weird name to avoid some conflicts later on in the script.

`startPosition` adjusts how far the element is offset initially. The default is 300px to the left, but you can use anything you want. This also means you can set the direction it slides in from, simply by adjusting this accordingly.

When you call this, it will automatically make sure the opacity is set to 0, and it will fade it in as it slides.

A demo can be found here: http://codepen.io/k4kfh/full/zvXwjj/

I'm very new to Git (and GitHub) so forgive me if I did anything dumb. I'll be happy to write documentation for this if people are interested, I just tossed this together in an afternoon though so I didn't bother to write anything yet. Hope this helps!

**Comment by seanfrasure** [comment]
Nice idea! Just not sure if it meets the Material Design features.

**Comment by k4kfh** [comment]
I think it sort of does. I didn't get the idea from a Material Design site/app, but it seems Google is using some similar transitions. For example, [this page on the Google Material spec](https://www.google.com/design/spec/animation/meaningful-transitions.html#meaningful-transitions-consistent-choreography) shows several elements "flying in", although in this case it is from the bottom rather than the side. My code technically supports flying in from the bottom, however this may do weird things to the dimensions of the page (when I tried having things fly in from the bottom it extended the length of the page to account for the offset during animation, which makes everything seem awkward)

**Comment by seanfrasure** [comment]
I mean it should follow the direction of the the red line. Other than that it's fine!
