### ISSUE TITLE
Center Input

### ISSUE THREAD

**Issue by Keltah** [Dogfalo/materialize#2347]
Hey, with the new version of MaterializeCSS, my forms are not centered.
Exemple of one input :
```<div class="row">
<div class="col s12">
<div class="input-field col s10 offset-s1 center">
     <i class="material-icons prefix">account_circle</i>
     <input id="id" required="" class="validate" type="text">
     <label for="id">Lien</label>
</div></div></div>```
With the v0.97.2, it's okay. Am I a wrong ?

**Comment by tmd-uk** [comment]
Have you tried adding the center to either the col s12 or the row and see if that works?

**Comment by Keltah** [comment]
I have just tried it. Even by putting the center on both it does not work...

**Comment by tmd-uk** [comment]
Can you get put the code in a Codepen and I'll have a look it for you.

**Comment by Keltah** [comment]
Here we go : http://codepen.io/anon/pen/RWOQLO
I think I did not forget anything... I copied the html for the form. I have the same problem on another page. The form are not centered on the Codepen too !

**Comment by lcdss** [comment]
Seems a priority problem with offset and col:
```css
.row .col.s10 {
    width: 83.33333%;
    margin-left: 0;
}
.row .col.offset-s1 {
    margin-left: 8.33333%;
}
```

if u add !important to .row .col.offset-*, it will work.

**Comment by Keltah** [comment]
So, why it's okay with the v0.97.2 and not with v0.97.3.
Bug, or just a modification ?

**Comment by lcdss** [comment]
It's a bug and will be ok in the next release: [#2328](https://github.com/Dogfalo/materialize/issues/2328)

**Comment by acburst** [comment]
duplicate #2328
