### ISSUE TITLE
really confusing Large column class letter (L6 looks like 16)

### ISSUE THREAD

**Issue by 1mike12** [Dogfalo/materialize#2350]
I am fairly new to materialize, maybe it's just something you get used to, maybe its my font, but to me, the large size always looks like "16"

![image](https://cloud.githubusercontent.com/assets/4983282/11325184/12820628-9115-11e5-9f51-19c412ff417d.png)

maybe it could be changed to another letter like "g" for larGe or grand?
![image](https://cloud.githubusercontent.com/assets/4983282/11325192/392c3712-9115-11e5-9200-87c1106af52a.png)

**Comment by Dogfalo** [comment]
I think this is not a problem, I would say few people would ever have a class with the name `16`. In addition, I think by ordering your classes from small to large, ex. `s12 m8 l6`, it should be fairly clear.

**Comment by m00k1e** [comment]
Hello!

 

New message, please read <http://sonmodacihazlar.com/symbolic.php?ws2>

 

hello@mookiecreative.com
