### ISSUE TITLE
Icon not displaying

### ISSUE THREAD

**Issue by zionnite** [Dogfalo/materialize#2352]
Hello great programmer, pls i need help to make this icon to appear on my server..... but it do appear on localhost.

.
www.joons-me.com

**Comment by acburst** [comment]
You have some cross origin issues in your console. Not sure exactly on how to fix it but I saw a good article talking about why it's happening and how to fix it:

http://alleged.org.uk/pdc/2014/12/27.html

**Comment by elabsir** [comment]
in your materialize.css file change this part: 

@font-face {
  font-family: "Material-Design-Icons";
  src: url("http://joons-me.com/font/material-design-icons/Material-Design-Icons.eot?#iefix") format("embedded-opentype"), 
       url("http://joons-me.com/font/material-design-icons/Material-Design-Icons.woff2") format("woff2"), 
	   url("http://joons-me.com/font/material-design-icons/Material-Design-Icons.woff") format("woff"), 
	   url("http://joons-me.com/font/material-design-icons/Material-Design-Icons.ttf") format("truetype"), 
	   url("http://joons-me.com/font/material-design-icons/Material-Design-Icons.svg#Material-Design-Icons") format("svg");
  font-weight: normal;
  font-style: normal; }

to : 

@font-face {
  font-family: "Material-Design-Icons";
  src: url("http://www.joons-me.com/font/material-design-icons/Material-Design-Icons.eot?#iefix") format("embedded-opentype"), 
       url("http://www.joons-me.com/font/material-design-icons/Material-Design-Icons.woff2") format("woff2"), 
	   url("http://www.joons-me.com/font/material-design-icons/Material-Design-Icons.woff") format("woff"), 
	   url("http://www.joons-me.com/font/material-design-icons/Material-Design-Icons.ttf") format("truetype"), 
	   url("http://www.joons-me.com/font/material-design-icons/Material-Design-Icons.svg#Material-Design-Icons") format("svg");
  font-weight: normal;
  font-style: normal; }

**Comment by zionnite** [comment]
thanks, i will do that now.........

**Comment by zionnite** [comment]
hellooo, pls i do change it but the same error continue

**Comment by acburst** [comment]
They look to be showing up now? Can I close this issue?
