### ISSUE TITLE
Can open single modal multiple times with keyboard input

### ISSUE THREAD

**Issue by barisbalic** [Dogfalo/materialize#2354]
It's possible to select an element that opens a modal and spam the enter key, opening the same modal many times.  You can only close/remove the topmost modal, leaving behind one or more overlays, which makes the page unusable.

**Comment by ericvrp** [comment]
Yes, this is a showstopper for me to. It's for instance clearly visible on http://materializecss.com/modals.html when pressing the MODAL button follow by a coupe of times pressing the Enter key. For me the problem exists Google Chrome but not with Safari.

**Comment by DikshaDeo** [comment]
There are compatibility issues with Chrome. Try with latest version. Patch will be helpful.

**Comment by ericvrp** [comment]
Chrome reports this: (OSX)
"Version 47.0.2526.73 (64-bit)
Google Chrome is up to date."

**Comment by m00k1e** [comment]
Hello!

 

New message, please read <http://hj99.net/rebel.php?jkqy>

 

hello@mookiecreative.com

**Comment by fega** [comment]
I cannot reproduce it in the latest version.

Closed due inactivity, feel free to reopen it if it is still necessary.
