### ISSUE TITLE
modals and tabs

### ISSUE THREAD

**Issue by metadespliegues** [Dogfalo/materialize#2357]
Hello!

I'm tryin to put three tabs inside a bottom sheet modal, using this code: http://pastebin.com/m55D1PVJ

The issue happens when you try to change the tab inside the modal, i load the page, the modal opens and when i change the thab (to any tab) a gray low-opacity background appears over the page (with higher z-index than the modal) and i cant interact with the modal, i've to reload the page because even closing the modal (with ESC) doesnt remove the gray background

Materialize version: v0.97.3
Thanks!

**Comment by acburst** [comment]
Initializing leanModal() is for the modal trigger only. So your code is almost correct.

So just remove the ```$("#verHotel").leanModal();``` line and it should work as intended.
