### ISSUE TITLE
sideNav is not a function with Meteor

### ISSUE THREAD

**Issue by Mcfloy** [Dogfalo/materialize#2362]
I'm trying to integrate a sideNav on my meteor project, but meteor is saying *"this.$(...).sideNav is not a function"*

My sidenav is in a template named "header", and in a javascript file i have
*Template.header.onRendered(function () {
	this.$('.button-collapse').sideNav();
});*

Why Meteor keep saying sideNav is not a function ? (Same problem if i put the jquery line in the html file, and jquery is installed by default)

**Comment by Mistaken3lf** [comment]
I don't think you need "this" in the front. I have a side nav in my meteor project and it works fine.

**Comment by Mcfloy** [comment]
Still having the *"$(...).sideNav is not a function"*
I installed materialize with bower, and included the files in my mainTemplate, am i right ?
