### ISSUE TITLE
Autofocus issue on Firefox

### ISSUE THREAD

**Issue by ev5unleash** [Dogfalo/materialize#2363]
Using the autofocus tag for text fields on Firefox does render properly. The placeholder text overlays with the actual text. 

![textfieldissue](https://cloud.githubusercontent.com/assets/3869356/11339102/d5775dda-91c5-11e5-933f-f485bca1b4ce.PNG)

Textbox code
<input id="username" type="text" class="validate" autofocus onKeyPress="{if (event.keyCode==13) login()}">

**Comment by gfazioli** [comment]
I have the same issue on Firefox. It works on chrome

**Comment by r-pluss** [comment]
Still having this issue with latest Firefox release (43.0.4).
No problems in Chrome.

**Comment by Dogfalo** [comment]
@StewartSG will try and take a look

**Comment by fega** [comment]
duplicate of #1762
