### ISSUE TITLE
Tablet problem Grid

### ISSUE THREAD

**Issue by abdesigner** [Dogfalo/materialize#2364]
I see one problem (maybe is just mine) in landscape orientation (tablet - iPad - other small devise) if I use M for set the size on tablet or iPad that devise use the L class because the screen resolution is bigger then 900 for solve that i made this new Class, what you think ? 

ON GRID.scss

@media #{$medium-and-up-landscape} {

```
  $i: 1;
  @while $i <= $num-cols {
    $perc: unquote((100 / ($num-cols / $i)) + "%");
    &.land-m#{$i} {
      width: $perc;
      margin-left: 0;
    }
    $i: $i + 1;
  }
  $i: 1;
  @while $i <= $num-cols {
    $perc: unquote((100 / ($num-cols / $i)) + "%");
    &.offset-land-m#{$i} {
      margin-left: $perc;
    }
    $i: $i + 1;
  }

}

@media #{$large-and-up-landscape} {

  $i: 1;
  @while $i <= $num-cols {
    $perc: unquote((100 / ($num-cols / $i)) + "%");
    &.land-l#{$i} {
      width: $perc;
      margin-left: 0;
    }
    $i: $i + 1;
  }
  $i: 1;
  @while $i <= $num-cols {
    $perc: unquote((100 / ($num-cols / $i)) + "%");
    &.offset-land-l#{$i} {
      margin-left: $perc;
    }
    $i: $i + 1;
  }
}
```

ON VARIABLES.scss

// Media Query Ranges
$small-screen-up: 601px !default;
$medium-screen-up: 1025px !default;
$large-screen-up: 1201px !default;
$small-screen: 600px !default;
$medium-screen: 1024px !default;
$large-screen: 1200px !default;

$small-screen-up-landscape: 1025px !default;
$medium-screen-up-landscape: 1281px !default;

$landscape: " and (orientation : landscape)";
$portrait: " and (orientation : portrait)";

$medium-and-up: "only screen and (min-width : #{$small-screen-up})" !default;
$large-and-up: "only screen and (min-width : #{$medium-screen-up})" !default;

$medium-and-up-landscape: "only screen and (min-width : #{$small-screen-up-landscape}) #{$landscape}" !default;
$large-and-up-landscape: "only screen and (min-width : #{$medium-screen-up-landscape}) #{$landscape}" !default;

$small-and-down: "only screen and (max-width : #{$small-screen})" !default;
$medium-and-down: "only screen and (max-width : #{$medium-screen})" !default;

$medium-only: "only screen and (min-width : #{$small-screen-up}) and (max-width : #{$medium-screen})" !default;

**Comment by JulioSimon** [comment]
@abdesigner just wanted to say that your solution is perfect, it does the job on landscape tablets getting "L" grid instead of "M" or "M" instead of "S".

Thank you!

**Comment by abdesigner** [comment]
I'm glad to be helpful, perhaps in the future it will be introduced somthing similar in framework
