### ISSUE TITLE
Question: Can materialize generate close icon for modal by default ?

### ISSUE THREAD

**Issue by sasikanthnimmagadda** [Dogfalo/materialize#2367]
Hi, 

Is there a default way of adding a close icon on top right corner of modal ?

I have seen this in documentation 
"To add a close button, just add the class .modal-close to your button."
In the footer, i have buttons with this class. 
I also need a close icon on top right corner of modal. Is there a default/easy way to do this ?
Anything during modal initialization ?

Thanks,
Sasi

**Comment by dennis1804** [comment]
add to materialize.js line 692:
```
if(options.closeIcon) { 
      $modal.append('<button class="modal-close btn-flat" style="position:absolute;top:0;right:0;">X</button>');
 }
```

And you can call function: 
```
$('modal-trigger').leanModal({
      closeIcon: true
});
```

**Comment by valerio-bozzolan** [comment]
Please reopen this feature :) Good patch, should be closed when published/accepted/denied in the repository.
