### ISSUE TITLE
Hovering icon has overlap graphics issues on FireFox

### ISSUE THREAD

**Issue by avezrizvi** [Dogfalo/materialize#2368]
We have a hovering icon question mark button on our website. There are no problems on Chrome, but on Firefox, an overlapping of graphics occurs on the button. See screenshots below: 

Original:
![image](https://cloud.githubusercontent.com/assets/11009123/11370015/b5a8c864-92d2-11e5-8f0d-ca9367d4644d.png)

As you scroll or move mouse over:
![image](https://cloud.githubusercontent.com/assets/11009123/11369968/76e689ae-92d2-11e5-8a5d-f7cdc8b4bc85.png)
![image](https://cloud.githubusercontent.com/assets/11009123/11370029/cd07a34a-92d2-11e5-895d-1658462662dd.png)

**Comment by Dogfalo** [comment]
Please create a codepen for this.

**Comment by Dogfalo** [comment]
Closed due to lack of information/reproducibility

**Comment by avezrizvi** [comment]
Did you actually try this on Firefox? We have a number of people who can reproduce this bug.

**Comment by Dogfalo** [comment]
Yes I did, I don't know what icon you are using and you didn't make a codepen either.
