### ISSUE TITLE
Color schemes for forms

### ISSUE THREAD

**Issue by webbird** [Dogfalo/materialize#2369]
I've created a form using blue-grey colors, but there seems no way to set the color for active element. Please look at the bottom border in the password field below.

![2015-11-24 16_22_05](https://cloud.githubusercontent.com/assets/147354/11371217/b393a0f4-92c7-11e5-8232-fc621f8f09a5.png)

Would be great to have color schemes for the whole form.

**Comment by anthropos9** [comment]
I think the answer to your question his here: http://materializecss.com/forms.html (About 1/8 of the page down, just before the TextArea heading.

**Comment by KSMorozov** [comment]
@webbird I had problem with it aswel tho there is a documentation on that matter as @anthropos9 mentioned, i ended up writing wall of css text for styling each input type. Better styling of forms would be neat inb4 ssas 🙉

**Comment by webbird** [comment]
Thank you for your hints.

I know I _could_ do this by myself, but I think it would be great to just have the predefined color schemes at hand. :D Like: <form class="<colorscheme>"...> and that's it.

**Comment by anthropos9** [comment]
@webbird I agree it would be nice to be able to set it without creating overrides. I did it recently and I was a little surprised that I had to manually set it or compile the SASS myself.

**Comment by Dogfalo** [comment]
Convenience color classes can add a lot of bloat. While some may want it, others will hate that it drive up the library size

**Comment by anthropos9** [comment]
Something like how MDL does it where you pick the pre-compiled color scheme you desire (```material.{primary}-{accent}.min.css```) could serve as a best of both worlds solution. I understand that would mean somebody has to either manually compile every solution or set up a script that will compile them for you. Just a thought.

**Comment by anthropos9** [comment]
Another idea might be a form color scheme addon, not required but helpful for those that want it and are willing to put up with the bloat.

**Comment by acburst** [comment]
Using our color variables in sass is the easiest way for now. We can look into some form of dynamic download for our package later.

**Comment by webbird** [comment]
+1 for the addon. I am not using SASS (and am not going to), but I am willing to help create default color schemes for forms. Maybe we can build a small team and make a new repo for that? There's no need to have it all in the "core" as @Dogfalo feared. Just an addition for those who like to have a nice start.

**Comment by Fyb3roptik** [comment]
How do I use the sass built in stuff? All I have is the min css included. I am using Sass on my backend though and would like to use this. YOU DONT PUT ANY DOCU ANYWHERE FOR DOING THIS! All I see is people say it is easier to use sass, BUT NOTHING ABOUT HOW!!!!

**Comment by fega** [comment]
fixed http://materializecss.com/forms.html
