### ISSUE TITLE
Textarea won't autoresize on initial page load on mobile

### ISSUE THREAD

**Issue by thomasvanlankveld** [Dogfalo/materialize#2371]
In a Meteor project:

``` handlebars
<div class="input-field col m8 s12">
  <textarea id="event-story" class="materialize-textarea">{{story}}</textarea>
  <label class="active" for="event-story">Story</label>
</div>
```

Just stays three lines long even though the text is much larger. It does resize as soon as I start typing.

I tried to envoke an autoresize manually (in `Template.myTemplate.onRendered()`), but nothing happens:

``` javascript
$story.trigger('autoresize');
```

Or even something ridiculous like:

``` javascript
$story.val($story.val());
$story.trigger('autoresize');
```

Manual `trigger('autoresize')` from the chrome console doesn't do anything either.

**Comment by sun2rise** [comment]
+1

**Comment by dishcandanty** [comment]
+1

**Comment by fega** [comment]
Please provide a way to reproduce it. like a [codepen](https://codepen.io/fega/pen/BWeZaG) or  a snippet
Closed due inactivity, feel free to reopen it if it is still necessary.
