### ISSUE TITLE
jQuery Confirm ESC Key affect materialize modal

### ISSUE THREAD

**Issue by khlJunior** [Dogfalo/materialize#2373]
I'm showing a modal with materialize, everything works so well, but when i show a alert with jquery-confirm jquery plugin, when i press the esc key the confirm dissapear and modal too.

I thinked to filter the esc key and define if jconfirm was active or modal, if i filter the esc key returning false jconfirm stop working (i want that) but materialize doest not.

What im doing wrong ?

**Comment by TyrionGraphiste** [comment]
It's very specific to your application. I don't think Materialize will adapt for your own usage.

**Comment by khlJunior** [comment]
Thank you Tyrion. 
Modals have a option to disable the click outside and dismiss, if this option cover the ESC key will be great. After i posted this i looked into the code, i think that i have a solution, i will try, but the dismissable option covering the esc key too is a good option in the modals.

Sry for english. I'm from Brazil. :)

**Comment by khlJunior** [comment]
UPDATE: There's a way to disable the ESC key for Modals ?

**Comment by JamesMilnerUK** [comment]
Supposedly you can do $("#mymodal").openModal({dismissable: false }) however I can't seem to get this to work.

**Comment by fega** [comment]
Closed due inactivity, feel free to reopen it if it is still necessary.
