### ISSUE TITLE
Navbar Links ul watch bad in mobile

### ISSUE THREAD

**Issue by Jolete** [Dogfalo/materialize#2376]
Hi,

I have added icons in my navbar. But in mobile those watch with margin:0. because the current code is:

// Navbar Links
  ul {
    margin: 0;

I resoved it this way:

nav ul  {
    // disable margin: 0 in materializecss
    @media #{$small-and-down} {

```
}
@media #{$medium-only} {
    margin: 0;
}
@media #{$large-and-up} {
    margin: 0;
}
```

}

**Comment by fega** [comment]
Please provide a way to reproduce it.
Closed due inactivity, feel free to reopen it if it is still necessary.
