### ISSUE TITLE
dropdown menu preventdefault

### ISSUE THREAD

**Issue by lid3rs** [Dogfalo/materialize#2377]
Is there a way, how i can not to disable a link of parent element of submenu.

-parent (href not working, but i need this to be a link which goes to another page)
--link
--link

$(".dropdown-button").dropdown({
        belowOrigin: true,
        alignment: 'left',
        constrain_width: false,
        hover: true
//maybe something like: linkable: true
    });

**Comment by fega** [comment]
Closed due inactivity, feel free to reopen it if it is still necessary.
