### ISSUE TITLE
How should I style with media queries using bower?

### ISSUE THREAD

**Issue by italomaia** [Dogfalo/materialize#238]
In this link http://materializecss.com/sass.html

There is a example on how to apply rules using materialize media queries. What's my understanding: I should @import some scss file from materialize sass and then use that snippet. Looking into materialize code, I've found $small-and-down in _global, also, a lot of other statements. 
Would it be the case where the variable definitions are moved into another file so that importing then for usage is harmless? Example:

@import "path/path/components/global"
@media #{$small-and-down} {
      // my styles for small screens and down
}

The "need" I wish to fulfill and motivated this issue is that I wish to have a piece of text aligned right in the navbar when the screen is small

**Comment by Dogfalo** [comment]
You don't need to import anything. This isn't related to bower also, it is just how Sass works.
