### ISSUE TITLE
Question: Is Materialize compatible with Bootstrap 3 ?

### ISSUE THREAD

**Issue by sasikanthnimmagadda** [Dogfalo/materialize#2382]
Hi, 

I am using bootstrap 3 in existing project.
Wanted to add materialize css in this project. 

1. Is materialize compatible with Bootstrap. ?
2. Are there any known issues, i need to be aware of ?

Thanks,
Sasi

**Comment by TyrionGraphiste** [comment]
Hi, there is no interest to load two frameworks for the same project because this includes files for each frameworks, moreover, some components may conflict with some others so this is not advisable.

**Comment by ItsLukeJames** [comment]
I switched from Bootstrap to Materialize yesterday, I've had no problems. Just need to review the code and change the classes and stuff to how Mat- likes it

**Comment by acburst** [comment]
We do not support any compatibility between multiple frontend frameworks.

**Comment by endra89** [comment]
@acburst can i integrated with bootstrap table: ( http://bootstrap-table.wenzhixin.net.cn/ )
i know it need bootstrap framework, any sugest table plugin like wenzhixin table?
