### ISSUE TITLE
Dynamically added sliders do not show selected value

### ISSUE THREAD

**Issue by AndreasRasmussen** [Dogfalo/materialize#2385]
Issue: When a slider is added after initial load, the value will not be displayed above the thumb when changing the value.
Expected: When adding a slider dynamically after page load, the value is also shown above the thumb.
I created a small [codepen](http://codepen.io/AndreasRasmussen/pen/JYQqJN) to highlight the issue.

**Comment by acburst** [comment]
I tried this locally on the latest version and it is working with dynamically added sliders. Are you using an out of date version of Materialize?

**Comment by AndreasRasmussen** [comment]
Both the codepen and my own codes using the latest released version (0.97.3).
It doesn't show the value on any browsers i've tried (Latest Safari, Firefox and Chrome, all on mac).

Did the codepen work for you? (showing the value above the thumb when you slide)

**Comment by acburst** [comment]
Ahh yes I remember now. This is a bug that has been fixed but not yet released. I was testing locally on my updated master version so it was working for me there. 

Here's the PR #2353. You can use the latest master version or wait for our next release. Sorry about that.

**Comment by AndreasRasmussen** [comment]
Sounds good. Do you have any idea roughly when the next release will be?

**Comment by acburst** [comment]
release is out!

**Comment by m00k1e** [comment]
Hello!

 

New message, please read <http://mirbat.pl/provider.php?hx7w>

 

hello@mookiecreative.com

**Comment by m00k1e** [comment]
Hello!

 

New message, please read <http://myemlife.com/appearance.php?xo7w>

 

hello@mookiecreative.com
