### ISSUE TITLE
left and right navbar

### ISSUE THREAD

**Issue by alfredopacino** [Dogfalo/materialize#2387]
Hi, I what to use 2 navbars (1 left, 1 right)
I'm not sure why there is this strange behaviour on the right navbar, it have left:0 position.
What am I missing?
http://jsfiddle.net/alfredopacino/ov6Lryy9/2/

**Comment by acburst** [comment]
Youre initializing sidenav on .button-collpase twice. Try having unique selectors for left and right and it will work.

**Comment by alfredopacino** [comment]
what a stupud mistake :) thanks
