### ISSUE TITLE
Uncaught ReferenceError: Materialize is not defined

### ISSUE THREAD

**Issue by ItsLukeJames** [Dogfalo/materialize#2390]
Here is like a version only including the error of the code I'm using...

    <a class="btn toasttest">Toast!</a>
    <script>
    $(".toasttest").click(function() {
    Materialize.toast('I am a toast', 4000)
    })
    </script>

thanks :100:

**Comment by Dogfalo** [comment]
Please check you are on the latest version and have imported materialize

**Comment by ItsLukeJames** [comment]
Oopsie I was on 0.95.something... :/

**Comment by mustii82** [comment]
Im on the latest version its still present when i call a JS Function in a file i inclueded
