### ISSUE TITLE
Update from 0.9x.x to 0.93.7

### ISSUE THREAD

**Issue by carusogabriel** [Dogfalo/materialize#2391]
Hello again guys,

Quick question: how can I update MaterializeCSS from any 0.9x.x to 0.93.7 seeing that I've made a lot of changes in some .scss and .js files?

Thanks again

**Comment by TyrionGraphiste** [comment]
Hi there,

The best solution would be to use an IDE to merge the JavaScript files.
For the CSS files, I advise you to place your modified CSS in late materialize CSS file (0.93.7), but if you've really put everywhere, once again you should use the IDE to merge all the difference between each file.

In this case, there is no simple way to update your version to the newest.

**Comment by carusogabriel** [comment]
Hello,

Good one, I use Netbeans IDE and it has a good tool to merge files and see the differences!

Thanks for the help!
