### ISSUE TITLE
Navbar flickering

### ISSUE THREAD

**Issue by nishantjain91** [Dogfalo/materialize#2392]
I am having the same issue as defined in issue #754 only on chrome. In all other browsers it's working fine. I am using 0.97.3 version on meteor

**Comment by tejgop** [comment]
What version of chrome are you using?

**Comment by Dogfalo** [comment]
Did you try the solution in #754?

**Comment by nishantjain91** [comment]
No clear solution is provided in #754. I I set transform attribute, then my mobile navbar. I am on chrome version  46.0.2490.86

**Comment by Dogfalo** [comment]
Did you apply custom transform styles or are you just using our navbar out of the box?

**Comment by nishantjain91** [comment]
No, I am just using navbar out of box . I haven't applied any custom transform and the problem only occurs on mac version of chrome not in windows
