### ISSUE TITLE
Update Material icons

### ISSUE THREAD

**Issue by ghost** [Dogfalo/materialize#2396]
There's a couple of new icons in [Material icons](http://www.google.com/design/icons/) collections!

**Comment by seanfrasure** [comment]
+1

**Comment by MetaiR** [comment]
they are inside the materialize.css file (without need to include any more css file)
you can see a list of them here -> http://groupfarsi.ir/icons
you can use theme like example blow
i class="mdi-navigation-arrow-forward">/i>

**Comment by carusogabriel** [comment]
Chek out the updates on the [Google Material Design Icons](https://www.google.com/design/icons/) and pay attention that there are some with the `new` badge!

**Comment by MetaiR** [comment]
If you use icons like docs in -> http://materializecss.com/icons.html you have the new one because in this way you incloud the google icons.
If you mean is useing new icons with just materialize.css file, i have to say the creators have to import it(i think ur meaning this like a suggestion)

**Comment by tomscholz** [comment]
As
