### ISSUE TITLE
font-paths are wrong on sass variables

### ISSUE THREAD

**Issue by ghost** [Dogfalo/materialize#2397]
It seems that the

```
$roboto-font-path: "../font/roboto/" !default;
$icons-font-path: "../font/material-design-icons/" !default;
```

are pointing to one level down rather than the correct path, causing error of importing when using sass.

**Comment by lorem--ipsum** [comment]
Any update on this ?

**Comment by tomscholz** [comment]
Works fine for me

**Comment by tomscholz** [comment]
Everything should work. See [here](https://github.com/Dogfalo/materialize/blob/master/sass/components/_variables.scss#L140)
