### ISSUE TITLE
Question: MaterialBox

### ISSUE THREAD

**Issue by Cedriking** [Dogfalo/materialize#2398]
Hello, this is just a question, not an issue :smile: 

Does MaterialBox can have an array of images? To have a kind of slider inside of the lightbox?

Thank you for your help.

**Comment by rodriguez-loic** [comment]
No I don't think so.

According to the [media documentation](http://materializecss.com/media.html#slider), you can add a "lightbox" on each image of the slider, or make a fullscreen slider. But not directly use slider in the "lightbox".

Also, maybe there is some tricks to do it easily.

**Comment by Cedriking** [comment]
Thank you @rodriguez-loic :+1:

**Comment by rodriguez-loic** [comment]
De rien :)
