### ISSUE TITLE
Dropdown wrong displayed with optgroups and options together

### ISSUE THREAD

**Issue by kirillkhaitbaev** [Dogfalo/materialize#2399]
Code:
`<select>`
`    <option value="1">1</option>`
`    <option value="2">2</option>`
`    <optgroup label="Optgroup1">`
`        <option value="11">11</option>`
`        <option value="12">12</option>`
`    </optgroup>`
`</select>`

Options with values 1 and 2 not displayed and accordingly selected values 11 and 12 is wrong

**Comment by acburst** [comment]
Fixed in afcce0e. Thanks for pointing this out!
