### ISSUE TITLE
slide out SideNav width is fixed to 240px;

### ISSUE THREAD

**Issue by ancientdemon** [Dogfalo/materialize#2401]
The width of the slideNav is fixed to 240px; in '.side-nav' class in materialize.css. We can override in custom css and have different width or auto with. However, this won't work because the javascripts seem to assume that width is always 240 and it sets style="left:-250px" in order to hide it and if width was more than 250px, then part of the sideNav is still visible in hidden state as well.

Screenshots from chrome dev tool are attached

![image](https://cloud.githubusercontent.com/assets/15957098/11482348/4bc05e6a-9770-11e5-812c-29e1530c023d.png)

![image](https://cloud.githubusercontent.com/assets/15957098/11482383/7dffae76-9770-11e5-85d9-4e755f97a94b.png)

**Comment by gitdistill** [comment]
I just noticed this as well.
Same happens when using a fixed nav that is always open on larger screens. It's right on page load, but if you start to resize the browser window the inline style with default value overwrites, which breaks the layout if your compensating the main content with padding.

**Comment by ancientdemon** [comment]
thanks gitdistill for adding to this. Since you mentioned 'fixed' style, I thought of updating this thread with another defect(?). Although this may warrant a separate issue by itself.

Consider the following html

![image](https://cloud.githubusercontent.com/assets/15957098/11509371/bdf13336-982b-11e5-88eb-93bd8fae3916.png)

Here I have specified 'fixed' style which keeps the sideNav fixed for larger screens and it hides the sideNav for smaller screens. This works as expected. However, issues is that I want the sideNav to close upon clicking a menu option and hence I am also doing this in code.

![image](https://cloud.githubusercontent.com/assets/15957098/11509770/134a9550-982e-11e5-80a2-dac7ed9d12b7.png)

My expectation is that closeOnClick: true is only applicale to the small screen. I don't want the menu to close upon click in larger screens (since I have used "fixed" style). Therefore the logic in materialize-css javaScripts should be fixed to use closeOnClick: true will not affect the "fixed" behaviour.

**Comment by ancientdemon** [comment]
btw, I found a solution for the original issue that I posted. When we programatically initialize the sideNave we can change the width. However, this width is in pixels, and we cannot use any other unit (em, vw etc) and we cannot have 'auto' width as well. Still, this solves my problem.

![image](https://cloud.githubusercontent.com/assets/15957098/11509995/62360536-982f-11e5-8f16-02ee7903fe22.png)

**Comment by gitdistill** [comment]
Oops should have mentioned the menuwidth property, as thats what I was using! As my issue was that on initialization it used this value, but on browser resize, inline styles get manipulated but with the default value. I should probably open a separate issue. Or maybe you could test and see if this happens to you as well.

**Comment by ancientdemon** [comment]
I added the second issue mentioned here as a separate issue
#2520
