### ISSUE TITLE
Dropdown : Open / Close Control Programatically

### ISSUE THREAD

**Issue by kevzlou7979** [Dogfalo/materialize#2403]
Hi guys,

Like FAB and Modal Components we need also a method called openDropdown and closeDropdown to be able to control the component programatically.

Best Regards,
Kevin

**Comment by kevzlou7979** [comment]
Any news?

**Comment by acburst** [comment]
Added in 51f3b11

Just do:
```
$('dropdown-button').dropdown('close');
$('dropdown-button').dropdown('open');
```
