### ISSUE TITLE
Change js reference in parallax-template.zip

### ISSUE THREAD

**Issue by juscilan** [Dogfalo/materialize#2404]
I suggest changing the reference in the file (link on the site) : 
http://materializecss.com/templates/parallax-template.zip

File:
materialize/templates/parallax-template/index.html

source:
script src="../../dist/js/materialize.js"></script

destination:
script src="js/materialize.js"></script

at,
@juscilan

**Comment by acburst** [comment]
Fixed in 2e582a7
