### ISSUE TITLE
material_select not work for multiple options selected

### ISSUE THREAD

**Issue by JuniorNunes7** [Dogfalo/materialize#2405]
When i load the select with $('select').material_select() the loaded material_select not detect options selected in html and no check this options.

**Comment by damienwebdev** [comment]
This is already addressed in #2274. Please read the associated issue there.

**Comment by TyrionGraphiste** [comment]
You can use the materialize.js file in the bin folder currently, this version is now updated instead waiting for the next release.

**Comment by JuniorNunes7** [comment]
Thanks !!

Em ter, 1 de dez de 2015 às 15:10, TyrionGraphiste <notifications@github.com>
escreveu:
