### ISSUE TITLE
Interference between svg and materialize.css

### ISSUE THREAD

**Issue by Overdrivr** [Dogfalo/materialize#2410]
I am working on a project using d3js to manipulate DOM and specifically `<svg>`s. Now, I just added materialize.css to my page, and immediately had a display issue inside an svg element.

Just for context, I have a base `<svg>` tag, containing a single `<g>`. This `<g>` is used to support zoom + pan by applying transforms on it.

Then this `<g>` contains itself a single `<svg>` element (to provide a transformation reference for child elements). In this last `<svg>`, I have a multitude of draggable items.

Now my problem is that if I pan the page to the right, and drag an item to the left, it gets clipped inside the root `<svg>`, somewhere in the middle.

See
![image](https://cloud.githubusercontent.com/assets/1294805/11532190/828b1d2a-9902-11e5-99a9-e723db19a7f0.png)

Here is a jsfiddle to reproduce the issue:
http://jsfiddle.net/Overdrivr/50rdynth/

If you remove the dependency to materialize.css, problem goes away.
If you remove `overflow: visible` (without materialize dependency) in the second svg element, problem appears.

Thank you for your help, I really hope to get it solved to enjoy materialize on my website.

**Comment by Dogfalo** [comment]
Opening up the jsfiddle, I don't see any console errors. What are the steps to reproduce it here?

**Comment by Overdrivr** [comment]
There is no error with the console (the one on my screenshot is just missing favicon).
Just drag the items around in the jsfiddle and you will see the issue.

**Comment by zukethenuke** [comment]
Did you have any luck getting D3 and Materialize to work together?  I added materialize to an app I'm building and it messed up all the D3 visualizations that I already had working.  If I remove the Materialize the visuals work the way they are supposed to.  Any suggestions?

**Comment by fega** [comment]
@Overdrivr @Overdrivr This is still an issue? 

Closed due inactivity, feel free to reopen it if it is still necessary.
