### ISSUE TITLE
Password input is not showing correctly when autocompleted

### ISSUE THREAD

**Issue by rodofatos** [Dogfalo/materialize#2412]
Hello, 

Password inputs display incorrectly when you have auto-complete on in browser(e.g. Login form with saved password). Attached is a file showing the current behavior.

![passwordinput](https://cloud.githubusercontent.com/assets/12541574/11560471/6a4f7022-99c9-11e5-9b11-f8c628ba8e2e.jpg)

**Comment by lcdss** [comment]
This happens to when you load data automatically from the server into the form.

**Comment by rodofatos** [comment]
@lcdss still the control should render itself as active, or is this something that i should do by myself ?

**Comment by lcdss** [comment]
Labels should change their state to active if not empty and input only if it is in focus.

**Comment by rodofatos** [comment]
I know this, but should I do something with it or it should be triggered by the materialize ?

**Comment by lcdss** [comment]
These events should be triggered by the materializecss, so you don't needs do anything. Personally i'm not recommend using materializecss in production cause it is very unstable, for now.

**Comment by kmmbvnr** [comment]
The issue is discussed in #194

**Comment by tomscholz** [comment]
Closed due inactivity and missing feedback. Feel free to reopen it, if it's still necessary.
