### ISSUE TITLE
Stepper Component

### ISSUE THREAD

**Issue by kevzlou7979** [Dogfalo/materialize#2414]
Hi you can check my custom stepper component we built on GWT-Material.
http://gwtmaterialdesign.github.io/gwt-material-demo/snapshot/#steppers

<b>Resource Files</b>
You can fork and add to Materializecss about the component.
http://codepen.io/kevzlou7979/pen/QyWbyr

<b>Demo</b>
![stepper](https://cloud.githubusercontent.com/assets/3138071/11576149/9ec2470e-9a4f-11e5-8e1d-c88a5612de68.gif)

**Comment by acburst** [comment]
It looks nice! Currently we are focused on bug fixing and stability so anyone can make a PR of this but it may take a while for us to get to it ourselves.

**Comment by kevzlou7979** [comment]
Yes you can check our updates on gwt-material about the horizontal stepper
and error feature

**Comment by imjoeybrennan** [comment]
+1 for steppers!

**Comment by smkamranqadri** [comment]
+1

**Comment by tirth-patel** [comment]
+1 @kevzlou7979

**Comment by marcorivm** [comment]
+1

**Comment by MXfive** [comment]
+1

**Comment by Isaiasdd** [comment]
+1

**Comment by sommmen** [comment]
+1

**Comment by thechch** [comment]
+1

**Comment by Kinark** [comment]
Well, it's not perfect yet, but I made a small plugin =)

https://github.com/Kinark/Materialize-stepper

I hope you like it!

**Comment by JeffMatson** [comment]
+1

**Comment by constantin-v** [comment]
+1

**Comment by tomscholz** [comment]
Have a look at [this](https://github.com/Kinark/Materialize-stepper)
