### ISSUE TITLE
Webpackized

### ISSUE THREAD

**Issue by aguegu** [Dogfalo/materialize#2416]
Is there any one using materialize with webpack? And use npm to install the package, not bower anymore? 

I have check the source code a little bit. Regarding the js files, it feel more like a collection of js files, but not well organised. etc, jQuery is required in many different ways.
I think libs like hammerjs, velocity should be required as deps or peerDeps in package.json, not hard coded in.

**Comment by aguegu** [comment]
I have look into the source, the webpackized way I prefer is 

```js

  var $ = window.jQuery = require('jquery');
  // require('materialize-css/bin/materialize.js');

  require('jquery-easing');

  require("materialize-css/js/animation.js");
  require("velocity-animate");

  require("materialize-css/js/jquery.hammer.js");
  require("imports?$=jquery!materialize-css/js/global.js");
  require("materialize-css/js/collapsible.js");
  require("materialize-css/js/dropdown.js");
  require("materialize-css/js/leanModal.js");
  require("materialize-css/js/materialbox.js");
  require("materialize-css/js/parallax.js");
  require("materialize-css/js/tabs.js");
  require("materialize-css/js/tooltip.js");
  require("materialize-css/js/waves.js");
  require("materialize-css/js/toasts.js");

  require("materialize-css/js/sideNav.js");
  require("materialize-css/js/scrollspy.js");
  require("materialize-css/js/forms.js");
  require("materialize-css/js/slider.js");
  require("materialize-css/js/cards.js");
  require("materialize-css/js/chips.js");
  require("materialize-css/js/pushpin.js");
  require("materialize-css/js/buttons.js");
  require("materialize-css/js/transitions.js");
  require("materialize-css/js/scrollFire.js");

  require('imports?define=>false!pickadate/lib/picker.js');
  require('imports?define=>false!pickadate/lib/picker.date.js');

  require("materialize-css/js/character_counter.js");
```

also install the deps seperately with npm, kinda like peer deps: 

```json
"dependencies": {
    "hammerjs": "^2.0.4",
    "jquery": "^2.1.4",
    "jquery-easing": "0.0.1",
    "materialize-css": "^0.97.3",
    "pickadate": "^3.5.6"
}
```

**Comment by 9Dave9** [comment]
yes I am using npm with webpack and trying to require materialize.. unfortunately still get the velocity missing error.

I still get this error

The error occurs when trying to trigger a model - 

`Uncaught TypeError: g.velocity is not a function`

Jquery version 2.1.4
Materialize v0.97.5

Webpack config - 

```ruby
module.exports = {
  entry: filesToCompile,
  context: __dirname + '/javascripts',
  plugins: plugins,
  output: {
    filename: outputFile,
    path: Path.resolve("../public/assets")
  },
  module: {
    loaders: [
      {
        test: /\.js$/,
        exclude: [/node_modules/],
        loader: 'babel-loader'
      },
      { test: /util\/js\//, loader: 'imports?jQuery=jquery' },
      {
        test: /\.scss$/,
        loader: ExtractTextPlugin.extract(
          'style-loader',
          'css!sass?outputStyle=expanded' +
          '&includePaths[]=' + Path.resolve(__dirname, './node_modules') +
          '&includePaths[]=' + Path.resolve(__dirname, './styles')
        )
      }
    ]
  },
  devtool: "source-map"
};
```

and my js main require...

```javascript
$ = window.jQuery =  require('jquery');
var skel = require('./vendor/skel.min.js');
var util = require('./vendor/util.js');
var materialize = require('./vendor/materialize.min.js');
```

All is fine when using the cdn, the problem I have with this when actually trying to require these files myself.

Any suggestions would be awesome.

**Comment by aguegu** [comment]
check out my folk: 

https://github.com/aguegu/vue-materializecss

it may help. :)

**Comment by 9Dave9** [comment]
@aguegu,  nice! - will give this a run the moment I get home.. will let you know how it goes, thanks.

**Comment by szymonmichalak** [comment]
@aguegu thanks for that! It works well if I refresh the specific page, however it looks like it doesn't start when there is a transition in SPA (React + react-router) to a page that contains materialcss JS element (e.g. tabs). Any ideas?

**Comment by aguegu** [comment]
@szymonmichalak Because the materialcssJS rely heavily on jquery and jquery plugins. most of the plugins are initialized only when the DOM is ready, like in 

```
$(function() {

});
```

When it comes to SPA, they need to be re-initialized again and again.

That is basically what I did in my folk, if you check the html templates. 

And that is why I have stop implement materialcssJS and trying MDL now. MDL is not so fancy yet, but its consistency is much better.

**Comment by szymonmichalak** [comment]
@aguegu I thought so and I already tried it... and I feel the same way you feel...

Thanks for mentioning MDL, I have no idea how I haven't heard about it yet! That's a beautiful discovery, thanks a lot! :smile:

**Comment by aguegu** [comment]
@szymonmichalak you are welcome. 

I also recommend [vuejs](http://vuejs.org). Check it out and tell me how you feel about it. I am not that into React or Angular by the way.

**Comment by fega** [comment]
Closed due inactivity, feel free to reopen it if it is still necessary.
