### ISSUE TITLE
Waves go outside of radius on mobile devices

### ISSUE THREAD

**Issue by helium96** [Dogfalo/materialize#2417]

**Comment by acburst** [comment]
Please be more descriptive and try and include a code example.

**Comment by samdeman22** [comment]
I can confirm that this also happens on windows 10, firefox. That is, assuming that the OP means the situation where you can see the wave move outside of its bounds if a circle button is used. I found that this happens occasionally when clicking normally, but more often when holding down on the button for some reason.

**Comment by DanielRuf** [comment]
Probably related https://github.com/Dogfalo/materialize/issues/4344

**Comment by tomscholz** [comment]
Closed due inactivity and missing feedback. Feel free to reopen it, if it's still necessary.
