### ISSUE TITLE
icon support

### ISSUE THREAD

**Issue by zionnite** [Dogfalo/materialize#2423]
wow, here i am again...
pls, i hav try to  solve this issue using many tactics i even submitted one not long a go, but the issue still remain unsolve rather an admin close it for me...

the issue are icons are not displaying on chrome,opera,mozila, even on mobile device...

pls take a look at  what am talking about ... www.joons-me.com.

i have other site to host for client, this is one major issue am always afriad of materilize master... pls guys give me help..

thanks in advance

**Comment by MetaiR** [comment]
ommmm its displaying for me very well (i tried it by chromume{chrome} and firefox 42)
i saw your html code in inspect element tool and i understood that u use icons class which in materialize.css file, i have a question here, why you dont you use icons from google icon?( like the document in here http://materializecss.com/icons.html )
maybe its solve ur problem (i hope)

**Comment by zionnite** [comment]
okay... thanks for your time...
but how did u think i should position the 2 .JS file

**Comment by MetaiR** [comment]
before the /body tag (its usually in the end of the codes and before /html tag)

**Comment by zionnite** [comment]
sir, its before the the </body> tag

**Comment by MetaiR** [comment]
have to exactly before
what im seeing about your codes is this -> 
[your-codes.txt](https://github.com/Dogfalo/materialize/files/52900/your-codes.txt)
and the right code i think is this -> 
[right-codes.txt](https://github.com/Dogfalo/materialize/files/52901/right-codes.txt)

in the first one(your codes{codes that i see in inspect on ur site) you put 2 JS file right after footer and hove some other code after 2 Js code (u didnt put them right before the /body tag)

**Comment by zionnite** [comment]
i just update it to your code but its still showing the issue

**Comment by MetaiR** [comment]
in the first place i see still a div element after 2Js file :( (its this div class="hiddendiv common">/div>)
in the secend place ; congratulation , the icons is correct for me. clear all of your cookie browser maybe its correct

**Comment by MetaiR** [comment]
i see that your side menu wont work it because jquery doesnt define sooner
by the way i have to say this side menu make u in trouble actually because its add a div tag at the end of your tags (after materialize.Js file)

**Comment by Dogfalo** [comment]
You have a lot of JS errors on your website, which could cause some problems. I also just submitted an icon fix here: 0b876f8

**Comment by zionnite** [comment]
Big thanks to u people for your great help....

its working now on desktop and laptop.... the issue was that when i used
the link like this the icon we not display joons-me.com but when i do it
like tgis the icon we display www.joons-me.com...

BUT ONE THING IS THAT ICONS ARE NOT DISPLAYING ON OPERA MINI...

Am looking forward for your help..(of a true materialize-master rock).

Thanks Again for helping

**Comment by AdiFahmi** [comment]
@zionnite glyphicons, font-awesome, google material icons, etc. None of them working on opera mini. It also happen in another css framework like bootstrap.

**Comment by zionnite** [comment]
ok thanks for the info. and in sight into opera mini...

Pls is there anyway to go around this???
