### ISSUE TITLE
It's hiding when I click on scroll of select?

### ISSUE THREAD

**Issue by inventti-leonardo** [Dogfalo/materialize#2426]
:(

http://codepen.io/anon/pen/PZoBVv

**Comment by MetaiR** [comment]
wrong link
please correct it

**Comment by TyrionGraphiste** [comment]
This is a normal behavior. If you want to select multiple options you can use the multiple select.

**Comment by inventti-leonardo** [comment]
I mean when you click on scroll to roll items up or down, hide all content. :(

**Comment by MetaiR** [comment]
ommmm TyrionGraphiste right
"its a normal behavior"
you can manualy add this that dont show the scroll bar for just make beautifuler (its not help you in main mater)
add to select
style="overflow:hidden !important;"

**Comment by seanlynchsl** [comment]
$('select').material_select();
            
        //fixes bug where Select would close when scrubber was dragged in Chrome
        var onMouseDown = function(e) {
            // preventing the default still allows the scroll, but blocks the blur.
            // We're inside the scrollbar if the clientX is >= the clientWidth.
            if (e.clientX >= e.target.clientWidth || e.clientY >= e.target.clientHeight) {
                e.preventDefault();
            }
        };

        $('select').siblings('input.select-dropdown').on('mousedown', onMouseDown);

**Comment by MetaiR** [comment]
ommm seanlynchsl your answer's place is not here

**Comment by inventti-leonardo** [comment]
It's working
