### ISSUE TITLE
Materialbox on card image with v0.97.3

### ISSUE THREAD

**Issue by dirkpennings** [Dogfalo/materialize#2432]
Hi, this issue was fixed before, but with the latest version I'm getting it again.. 
Further details see original thread: https://github.com/Dogfalo/materialize/issues/2091

**Comment by acburst** [comment]
Can you post an example of this not working? Please give more information. I just tried it on my local version and it works.

**Comment by dirkpennings** [comment]
I'll post an example this weekend (sorry for the late reply)
