### ISSUE TITLE
Modal cause page content to jump..

### ISSUE THREAD

**Issue by ritchiedalto** [Dogfalo/materialize#2433]
I'm assuming everyone else is experiencing this?

When a modal is engaged the javascript puts ``overflow: hidden`` on ``<body>``. I assume this is done to prevent scrolling with the mouse wheel, but the problem is that when overflow is hidden, the scroll-bar vanishes and the page content jumps a bit to the right, by as much width as the scroll-bar previously occupied.

I gotta say, it's jarring and looks unprofessional. I'd rather let the background scroll behind the modal if the user should engage the mouse wheel. If it's on a touch device, the modal will close when they touch outside the modal content box anyways, so scrolling wont happen.

Thank you.

**Comment by ProfNandaa** [comment]
@ritchiedalto - I see what you mean, someone can quickly checkout [the modal examples in the docs](http://materializecss.com/modals.html). What do you suggest?

Will some _easing_ help, so that it's snappy?

**Comment by Dogfalo** [comment]
Fixed by 1023d8b2aa6ad350364e525f2e154a3b1c57cc06
