### ISSUE TITLE
bower update

### ISSUE THREAD

**Issue by carusogabriel** [Dogfalo/materialize#2434]
Hi community

Quickly one:
- When a commit is made, if I go to bower and update the `Materialize` folder, will I get the changes? If not, does anybody know what do I have to do?

Thanks :smiley:

**Comment by Dogfalo** [comment]
If you want daily updates, you should clone the git repo and use that is the lib package instead. then using `git pull` will sync you to the latest updates. Bower will get updated every release and not in between. Hope this helps.

**Comment by carusogabriel** [comment]
I got it, I'll change to a `git repo` instead of `Bower`. 

Thanks
