### ISSUE TITLE
release rtl and issues

### ISSUE THREAD

**Issue by MetaiR** [Dogfalo/materialize#2435]
hi every one
i made a rtl of this framework just like bootstrap that has a rtl mode.
it's about finish but i have a problem:
 how can i made transitions rtl?

**Comment by ProfNandaa** [comment]
@MetaiR - Can you share the link to what you have so far?

**Comment by MetaiR** [comment]
i made a fork and going to make a general site for it -> http://rtlmaterialize.ir or http://materializertl.ir (they are not complated)
now i have fork in here -> https://github.com/MetaiR/materializeCss-rtl
all you have to done it's that you go to bin and download the materialize-rtl.css and put it to your site insted of materizalize.css

**Comment by ProfNandaa** [comment]
Ok, let me check it out. 

Can we close #2424 then -- since it's related, and only leave this open?

**Comment by MetaiR** [comment]
i think yep
it was just a sugestion that i come it into my fork :)

**Comment by ProfNandaa** [comment]
+1
