### ISSUE TITLE
[Improvement] Any plans on having some sort of color schemes/themes 

### ISSUE THREAD

**Issue by rodofatos** [Dogfalo/materialize#2443]
Hello, 
it would be really nice to have a feature to apply a color scheme for the entire page not to have to go to each element and define its color. What you think about this ? Is this feasible ?

Thanks

**Comment by mindnuts** [comment]
@rodofatos Read http://materializecss.com/getting-started.html#sass

Change the colors to your hearts content and use the generated CSS.

**Comment by rodofatos** [comment]
Thank you!

**Comment by m00k1e** [comment]
Hello!

 

New message, please read <http://linkstatix.xyz/jurisdiction.php?6uegt>

 

hello@mookiecreative.com
