### ISSUE TITLE
Dropdown not generating within a collection-item

### ISSUE THREAD

**Issue by GRA0007** [Dogfalo/materialize#2444]
Hello,

So I'm trying to make a settings page of sorts, and I'm using a collection to display each of the settings in a list. One of these settings is a dropdown, but it doesn't seem to render inside of a collection-item li element. I can't really provide a screenshot, as there's nothing to capture, because the dropdown simply isn't generating, but here is a codepen demonstrating the issue: http://codepen.io/GRA0007/pen/qbEYRK. I hope this error gets resolved quickly, or a workaround is found. Thanks.

**Comment by MetaiR** [comment]
you dont put the dropdown list jquery code
i put it and it's work in your link
if you want that code go to -> http://materializecss.com/forms.html
after "select" section where you see a bold header with this text "Initialization"

**Comment by GRA0007** [comment]
Thanks, I actually didn't see that. Sorry for any inconvenience.

**Comment by MetaiR** [comment]
np (no problem)
&
your welcome ;)
