### ISSUE TITLE
offset rule is overwritten by col and column size

### ISSUE THREAD

**Issue by aovchinn** [Dogfalo/materialize#2447]
![screenshot from 2015-12-09 00 02 00](https://cloud.githubusercontent.com/assets/3647829/11668434/3f53229a-9e08-11e5-9f3c-b923fe444b42.png)

So as you can see the offset rule is not working.
Try it yourself.

```html
<!DOCTYPE html>
<html lang="en">
<head>
    <link rel="stylesheet" href="./bower_components/Materialize/dist/css/materialize.min.css">

    <script defer type="text/javascript"
            src="./bower_components/jquery/dist/jquery.min.js"></script>
    <script defer type="text/javascript"
            src="./bower_components/Materialize/dist/js/materialize.min.js"></script>

    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<div class="row">
    <div class="col s4">some s4 witout offset</div>
    <div class="col s4 offset-s1">with offset</div>
</div>

</body>
</html>
```

**Comment by MetaiR** [comment]
in the first place you should put the Js files right before closer body tag. (i think after you do this it'll work)
in the secend place why you dont use push and pull?
---more information---
if you want to know diffrence between pull & push and offset (if you dont know) 
the pull and push just use right : "bla bla" or left : "bla bla (i think it was left)
but
the offset use margin-left : "bla bla"
the cool thing between these it's if your element near the side of page and use pull or push (your value more than the width {i hope u get it}) , your element go out of the window !!!
but in the other hand if you use offset it's go to next line

**Comment by acburst** [comment]
Duplicate #2328
