### ISSUE TITLE
Initialize characterCounter on <input> from JavaScript

### ISSUE THREAD

**Issue by BTVincent** [Dogfalo/materialize#2449]
I need this functionality for an app : 
```js
$("#myInput").characterCounter(140);
```
instead of
```html
<input id="myInput" type="text" length="140" />
```

**Comment by ProfNandaa** [comment]
@BTVincent -- how about this?
```javascript
$("#myInput").attr("length", 140);
```

**Comment by BTVincent** [comment]
Feels like duct tape but it does the job, thanks ;)

**Comment by ProfNandaa** [comment]
Good, thanks :)

**Comment by m00k1e** [comment]
Hello!

 

New message, please read <http://miss.vn/now.php?m>

 

hello@mookiecreative.com
