### ISSUE TITLE
Weird positioning of <select> content

### ISSUE THREAD

**Issue by MusikDK** [Dogfalo/materialize#2453]
http://www.cphrecmedia.dk/musikdk/CMS/shop/createnew.html

The Select numbers are floating right and on smaller screens outside the input-field. How come its not just aligned left?

**Comment by ProfNandaa** [comment]
@MusikDK - I wish you did a screen-shot of what you mean exactly...on both screens.

**Comment by TyrionGraphiste** [comment]
Only because the content of your select's option contains spaces.
It doesn't belongs to Materialize, only from you.

**Comment by MusikDK** [comment]
Ahh doh. Didnt think of this as I thoughts CODAs tidy HTML feature wouldn't insert empty spaces.
Thanks for the help and sorry for the inconvenience.
