### ISSUE TITLE
Collapsible inside Dropdown

### ISSUE THREAD

**Issue by ghost** [Dogfalo/materialize#2455]
Hello there

I've tried a lot chance some .scss and .js files to put a collapsible inside a dropdown, but I can't  :weary:

Does anybody has a solution for this?

Thanks for now

**Comment by TyrionGraphiste** [comment]
It's sounds like you want to do something, but I'm sure there is another way to do it because dropdown closes on click.

**Comment by MetaiR** [comment]
by this code the dropdown not close on click

$('select').material_select();

    //fixes bug where Select would close when scrubber was dragged in Chrome
    var onMouseDown = function(e) {
        // preventing the default still allows the scroll, but blocks the blur.
        // We're inside the scrollbar if the clientX is >= the clientWidth.
        if (e.clientX >= e.target.clientWidth || e.clientY >= e.target.clientHeight) {
            e.preventDefault();
        }
    };

    $('select').siblings('input.select-dropdown').on('mousedown', onMouseDown);
