### ISSUE TITLE
Question: how to create new materialize icons and include in button list

### ISSUE THREAD

**Issue by gg4u** [Dogfalo/materialize#2456]
Hello!
I'd like to add a new icon to the icon set, so you can include it with the syntax:

```
<i class="material-icons">custom_label</i>
```

could you please provide a short guideline how to do that?
where icons should be created and indexed?
and d'you have any styling guide you followed to make icons visually consistent?

**Comment by Nohinn** [comment]
The icons are part of a font file (ttf, woff, ...) it is not as easy as to put a new icon image in a folder and use it.

Here you have a tutorial on how to create custom webfonts with ligatures (so you can use "custom_label" as the text of the html element and it will be translated to the matching icon)
http://webdesign.tutsplus.com/articles/your-logo-as-a-web-font-ligature--webdesign-11375

**Comment by tomscholz** [comment]
The icons aren't actually a part of materialize. They were made by google. Check their repo out [here](https://github.com/google/material-design-icons). If you have any issues or icon request, you can post them there.
