### ISSUE TITLE
Datepicker contained!

### ISSUE THREAD

**Issue by seemsindie** [Dogfalo/materialize#2457]
Hello guys,

I have a small panel that i made for login/registration but when i attach date picker to one input i get this:

![image](https://cloud.githubusercontent.com/assets/1268576/11745543/34810d06-a019-11e5-8f8f-d93f6c7a20a9.png)

I guess it's because it's inside a panel and form, and i manipulate those width, height...
But shouldn't datepicker be a global control, so it dims a whole page, not like this...

Can someone help me with this?

Thanks, Ivan

**Comment by ev5unleash** [comment]
Seems like you have the dateSelector inside of div. It would be hard to troubleshoot unless you make a codepen.

**Comment by seemsindie** [comment]
@ev5unleash There you go http://codepen.io/seemsindie/pen/eJpOrj?editors=101 it's just a quick demo, but it shows the bug.

**Comment by Dogfalo** [comment]
There is a container option in pickadate.js which fixes this

**Comment by seemsindie** [comment]
Thanks @Dogfalo
