### ISSUE TITLE
Multiple Selection .val() issue

### ISSUE THREAD

**Issue by ev5unleash** [Dogfalo/materialize#2458]
Hi there,

When using the new Multiple Selection element, I have an issue retrieving the values. The jQuery .val() selector works fine until you deselect an entry. It just won't register that the entry has been unselected. For instance, when I select all of the entries in the multiple selection element, I get the values 1,2,3 from .val(). When I deselect the value 2, it will still show up under .val(). 

Pen link: http://codepen.io/ev5unleash/pen/EPVYLG

Any help would be appreciated. 

Thanks,

**Comment by TyrionGraphiste** [comment]
For now you can just select active <li> from the ul.

**Comment by ev5unleash** [comment]
The only problem is that you can't select the ul elements as it's ID is generated with a generated GUID.

**Comment by TyrionGraphiste** [comment]
$("select_id").siblings("ul.dropdown-content").find("li.active");

**Comment by ev5unleash** [comment]
Unfortunately, that will not give me the actual value. It's only possible to parse out the option text in a dirty way with that route.

**Comment by TyrionGraphiste** [comment]
It should be fixed if @acburst accepts the PR above.

**Comment by acburst** [comment]
Merged

**Comment by seemsindie** [comment]
When is this going be available for update?

**Comment by acburst** [comment]
We will try and get a release done before the holiday season starts
