### ISSUE TITLE
Update the Min/Max of the Datepicker

### ISSUE THREAD

**Issue by nathankoop** [Dogfalo/materialize#2460]
Is there the ability to change the Min/Max value of a datepicker dynamically.

Basically I have two datepickers, one is StartDate, when that's set, the EndDate needs to have it's min value updated (and vice-versa).

I cannot see a way to accomplish this in the documentation nor in the code.

Is it possible?

**Comment by barisbalic** [comment]
This is possible in the library that materializecss uses, but not from materializecss itself.  I also wanted this functionality but it looks like the options are not passed through.

**Comment by Dogfalo** [comment]
The options are passed through. Are they not working?

**Comment by barisbalic** [comment]
That is interesting, because today I tried passing `closeOnSelect: true` which has not worked.  When I checked the docu here http://materializecss.com/forms.html, it says explicitly "At this time, not all pickadate.js options are working with our implementation", so I thought that was the reason.

**Comment by Native-Coder** [comment]
I can confirm this over a year later. I have 2 date pickers so that my users can set a date range. And I can't set the minimum or maximum values of said date pickers.

**Comment by Dogfalo** [comment]
This is possible in v1-dev, you can change the options property directly. This will work in this scenario, but is not advisable to use for all options.
