### ISSUE TITLE
Button Issue

### ISSUE THREAD

**Issue by 205112067** [Dogfalo/materialize#2462]
There is no such type of button available in materializecss like btn-success, btn-cancel, btn-info which is available in bootstrap.
To achive these we need to modify css each time.
or is there any alternate way to achive these...?

**Comment by MetaiR** [comment]
you can just give the class to button that you want
just need color of background and color of text

**Comment by irontiga** [comment]
```
<a class="btn green">Success</a>
<a class="btn orange">Warn</a>
<a class="btn red">Danger</a>
<a class="btn blue">Info</a>
```
More info here http://materializecss.com/color.html

**Comment by Sajonara** [comment]
@205112067 Are you using sass? If so, you can easily extend the classes. Like so:

``` css
.btn-success {
@extend .blue, .white-text
}
```

Then you could use it in your html like so:

``` html
<a href="#" class="btn btn-success">#</a>
```

This would then create a blue button with white text, similar to the one that Bootstrap offers.
