### ISSUE TITLE
Checkbox don't work in ASP.NET

### ISSUE THREAD

**Issue by warakornkid** [Dogfalo/materialize#2463]
Hello
I develop website by ASP.NET and have problem about checkbook.
1. When I use ASP.NET Checkbox. like 
<asp:CheckBox ID="chkPersist" runat="server" /> 
It can't change status.
2. When I use HTML input type="checkbox" and add runat="server" like 
<input id="chkPersist" type="checkbox" runat="server" />. 
It can't change status.

How to fix it
Thank
Warakon

**Comment by Nohinn** [comment]
Hello, I'm not sure about your issue... Do you mean that it is not working using WebForms?

In that case, the ID you use for a control in WebForms is prefixed with the parent's ID.
To avoid that you should use ClientIDMode="Static".

WebForms example:
```
     <p>
        <asp:CheckBox ID="testCheckbox" ClientIDMode="Static" runat="server" />
        <asp:Label AssociatedControlID="testCheckbox" ClientIDMode="Static" runat="server" />
    </p>
```

**Comment by warakornkid** [comment]
Hello

Thank you very much. It’s work like I want.

 

Warakorn Kidkumnuan
