### ISSUE TITLE
sentence not put in one line in toast in my language

### ISSUE THREAD

**Issue by MetaiR** [Dogfalo/materialize#2464]
hi every one
my language is persian and when i use it in toast its locks like the picture:
http://rtlmaterialize.ir/Screenshot.png
what's the problem?

**Comment by TyrionGraphiste** [comment]
What is your HTML code ?
Can you make a screen of your browser code with the toast content (different from your HTML code) ?

**Comment by MetaiR** [comment]
<!DOCTYPE html>
  <html>
    <head>
		<meta http-equiv="Content-Type" content="text/html; charset=utf-8">
		<title>مستندات متریالیز ار تی ال</title>

      
      <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
      
      <link type="text/css" rel="stylesheet" href="materialize/css/materialize-rtl.css"  media="screen,projection"/>
      <link type="text/css" rel="stylesheet" href="materialize/css/main.css"  media="screen,projection"/>

      
      <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    </head>

    <body>
  <a class="btn" onclick="Materialize.toast('سلام دنیا', 10000)">Toast!</a>

      
      <script type="text/javascript" src="materialize/js/jquery-2.1.4.min.js"></script>
      <script>

      
</script>
      <script src="materialize/js/materialize.min.js"></script>
    </body>
  </html>

**Comment by TyrionGraphiste** [comment]
For toast, text is the first param and duration the second.

Otherwise, try to delete word-break: break-word; CSS rule in .toast { ... }

**Comment by MetaiR** [comment]
when you type persian in display it's shown as second param actually it's wrote as first one
but thank you so much by deleting or change the value to normal it's working well.
I have another question why we use word-break in toast?

**Comment by TyrionGraphiste** [comment]
Idk, maybe they want to keep the toast content on several lines instead just one.
For my case, once time I have to delete this rule because just like you, I wanted to keep the content on one single line.

**Comment by MetaiR** [comment]
any way
thank you so much

**Comment by m00k1e** [comment]
Hello!

 

New message, please read <http://piava.cl/convinced.php?69h>

 

hello@mookiecreative.com

**Comment by m00k1e** [comment]
Hello!

 

New message, please read <http://www.andreaovallealcaldesa.com/ease.php?5vu>

 

hello@mookiecreative.com
