### ISSUE TITLE
Materialize input inner

### ISSUE THREAD

**Issue by lexetam** [Dogfalo/materialize#2467]
![input spinner](http://bootsnipp.com/img/screenshots/13f5656272628b1b72b600876aa9a9b6c6fee6a0.jpeg)
 How i can crate a input spinner like image

**Comment by Sajonara** [comment]
@lexetam I think right now, you cannot. At least the documentation on Materialize's form helpers does not mention such a possibility (cf. http://materializecss.com/forms.html).

**Comment by Dogfalo** [comment]
You can use a regular input with type[number]:
http://puu.sh/lTkNf/7957fdc057.png
