### ISSUE TITLE
Dropdown contained!

### ISSUE THREAD

**Issue by seemsindie** [Dogfalo/materialize#2468]
Hello,

I have a similar problem i had with datepicker, but datepicker has an option containter.
![image](https://cloud.githubusercontent.com/assets/1268576/11766320/4372194e-a182-11e5-94d9-684864083ebc.png)

I tried setting the z-index on select-wrapper but nothing...
The dropdown is contained in that form, but it should be above it, any solution?

Thanks, Ivan.

**Comment by acburst** [comment]
Does the card have overflow hidden?

**Comment by seemsindie** [comment]
@acburst Thanks man, i really didn't notice that.
