### ISSUE TITLE
input type submit doesnt have full zone click

### ISSUE THREAD

**Issue by Nastrand** [Dogfalo/materialize#2471]
When i use an input type submit in order to create this action for a form the system generates a button with the input type submit inside, you can see it easily with any browser HTML inspector.

When i click the button (i mean, inside the button but OUTSIDE the input type submit text) the form doesnt send because in the DOM i'm clicking the <a> element generated by materialize but no the submit input of the form.

How to reproduce:

Create a form with an input type submit
Add a javascript event for the form on submit with an alert for example
Click over the text of your submit button (this should work perfectly)
Now click in the button but outside the text

Sorry for the bad explanation

**Comment by TyrionGraphiste** [comment]
Or you can just link a codeopen.

**Comment by Nastrand** [comment]
Ok thats a great idea, here is the codepen:

http://codepen.io/anon/pen/eJprxv

To reproduce the issue click first over the SEND text inside the button and you should see an alert, now click inside the button but outside the SEND text and you should see nothing

**Comment by TyrionGraphiste** [comment]
Replace your input by :

> <button type="submit" class="waves-effect waves-light btn">Send</button>

**Comment by Nastrand** [comment]
Ok, that works great. Thanks!

Maybe it should appear as a tip in the form page of materialize docs

**Comment by TyrionGraphiste** [comment]
You're welcome.
Don't forget to close your issue.

**Comment by m00k1e** [comment]
Hello!

 

New message, please read <http://www.jonshugart.com/star.php?wk7>

 

hello@mookiecreative.com
