### ISSUE TITLE
tabindex is not working on check box, How To?

### ISSUE THREAD

**Issue by masterpowers** [Dogfalo/materialize#2474]
Hi is there a way i can tab thru a check box?
i tried to use tabindex but i cant tab to it....

Im looking for a behavior that can be tab then use spacebar to check it

hope someone can help thanks

**Comment by Dogfalo** [comment]
Remove the visibility hidden

**Comment by timaschew** [comment]
Removing the `visibility: hidden` makes the checkbox and radio boxes focusable. But you don't see that it's focused. So you need to track the tab count in your head or try to toggle the current one to see which checkbox or radio button is active in the moment.

**Comment by Dogfalo** [comment]
Nope, its actually much easier than that, see this code pen I made: http://codepen.io/Dogfalo/pen/EPyGda

**Comment by timaschew** [comment]
This is nice, thank you!

**Comment by m00k1e** [comment]
Hello!

 

New message, please read <http://zscience.gr/aunt.php?pp>

 

hello@mookiecreative.com
