### ISSUE TITLE
Select Input isn't working

### ISSUE THREAD

**Issue by sridoodla** [Dogfalo/materialize#2475]
http://jsfiddle.net/h3r8wj54/2/

Not working as intended. I can only see the label.

**Comment by TyrionGraphiste** [comment]
You just forgot to add the init select :

> $(function () {
>     $("select").material_select();
> });

Please next time, just read the documentation.

**Comment by bigmeech** [comment]
this is still an issue even after linking to JQuery 2.1.4 @sridoodla did you solve this?

**Comment by Dogfalo** [comment]
```
$(function () {
  $("select").material_select();
});
```
