### ISSUE TITLE
SideNav collapsible header sizing/spacing

### ISSUE THREAD

**Issue by njoniec** [Dogfalo/materialize#2477]
The spacing between items as well as the size of the 'collapsible header' element do not correspond with the height of the other items in the sidenav list.

http://codepen.io/njoniec/pen/eJpxxK

Here is a screenshot of the issue in Chrome:
![Chrome screenshot](http://new.tinygrab.com/e47af387c4c903b346d4fec8033786bfdfc29ad7c2.png)

Here is a screenshot of the issue in the CodePen linked above: 
![CodePen screenshot](http://new.tinygrab.com/e47af387c4a70a6f7dbdc122a332f5a387c53aed3a.png)

**Comment by acburst** [comment]
Fixed in 1a4a958. 

I also added a variable for sidenav item height in variables.scss
