### ISSUE TITLE
Alternative to bootstrap .affix?

### ISSUE THREAD

**Issue by k4kfh** [Dogfalo/materialize#2486]
I am trying to do a navbar on a Materialize-based site. I know there is the option to do a permanently fixed navbar, but I want one that clings to the top of the screen only once you scroll past it.

As I understand it, bootstrap's ``.affix`` class does exactly this, so is there a possibility of adding such a feature to MaterializeCSS?

An example of what I am trying to do can be seen [here](https://teksyndicate.com). Notice how the navbar changes to fixed positioning only once you scroll down past it.

**Comment by acburst** [comment]
Our version of affix is called [Pushpin](http://materializecss.com/pushpin.html).
