### ISSUE TITLE
Plagiarism of your work

### ISSUE THREAD

**Issue by lukaspijak** [Dogfalo/materialize#2491]
Hello,

in this framework (http://mdbootstrap.com/material-design-for-bootstrap/) author use your work as premium content. It's not fair to you.

**Comment by BrySi** [comment]
Hey,
The correct link is http://mdbootstrap.com/material-design-for-bootstrap/
(you forgotten the "." before the "com".)
And I agree, that's a mix between Materialize and Bootstrap.. And it's 49$
:O

2015-12-16 13:37 GMT+01:00 Lukáš Piják <notifications@github.com>:

> Hello,
>
> in this framework (http://mdbootstrapcom/material-design-for-bootstrap/)
> author use your work as premium content It's not fair to you
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Dogfalo/materialize/issues/2491>.
>



-- 
         BRYAN SIMON

**Comment by Blahah** [comment]
It's perfectly fine for someone to take MIT licensed code and charge money for it, as long as they include the license.

**Comment by lukaspijak** [comment]
No licence included, all headers deleted and no reference to materialize...

**Comment by Frondor** [comment]
That's exactly what I said when I saw the project for first time: https://www.facebook.com/groups/AngularJS2/permalink/717202361713182/

**Comment by danielhickman** [comment]
It looks a bit different. Look at the tooltips, for example.

**Comment by SuperDJ** [comment]
It might look a bit different but that might be due to the fact that bootstrap is underneath it. The majority of components do look like they work the same (same code markup).

**Comment by maciekpaprocki** [comment]
Yep, this guy is stilling full on. Even class names are based on your framework. The worst he actually destroyed it while doing that :(

**Comment by chifreaigle** [comment]
He should mention materialize at least : /

**Comment by maciekpaprocki** [comment]
And include license. That's actually required by MIT from what I am aware. http://mdbootstrap.com/wp-content/themes/mdbootstrap/css/mdb.min.css?ver=4.4.1

**Comment by tomscholz** [comment]
Closed due inactivity. Feel free to reopen it, if it's still necessary.
