### ISSUE TITLE
collapsible not working since upgrade from 0.97.1 to 0.97.3

### ISSUE THREAD

**Issue by yzargari** [Dogfalo/materialize#2496]
I'm using collapsibles of type accordion all over my application and it appears to have stopped working since my recent upgrade. Anyone else having the same issue?

I did a diff between the two js files and found that several lines were added/changed in the collapsible function - so I can only assume a bug.

I did notice, however, that if I run the collapsible initialization function the second time, it miraculously starts working....

Edit: I just noticed that on some pages it does work and on some it doesn't.
Edit2: I also found that this may affect expandable-type collapsibles

Thanks,
Joseph

**Comment by fbrau** [comment]
My collapsibles aren't working neither.

I've tried with the samples at the docs and they arent' either.

The initial rendering is fine but when I click on a item it unfolds and instanlty closes.
There are no error messages (error console is clean).

A for the two times initialization trick... it doesnt work for me...

COLLAPSIBLES ARE UNUSABLE

**Comment by acburst** [comment]
Fixed in 6be48ea.

Initializing multiple times won't break collapsibles anymore.

**Comment by fbrau** [comment]
thanks for the rapid fix

**Comment by m00k1e** [comment]
Hello!

 

New message, please read <http://www.client-interaction.com/interrupt.php?7>

 

hello@mookiecreative.com
