### ISSUE TITLE
Label floats above input field

### ISSUE THREAD

**Issue by smileytechguy** [Dogfalo/materialize#2499]
On a input field, when I click it causes the label to float above.  On fields with a palceholder the label is already too high

**Comment by acburst** [comment]
I'm not sure what your problem is? That is the feature of our labels. That they act as placeholders that float above. Do you have a code example of your problem?

**Comment by smileytechguy** [comment]
i mean the label floats into whitespace and can no longer be seen

**Comment by acburst** [comment]
Please post an example codepen of your problem otherwise we have no idea how to help you.

**Comment by BackSpaceTech** [comment]
In the docs:
 "If you are having trouble with the labels overlapping prefilled content, Try adding class="active" to the label"
This will fix your problem.

**Comment by smileytechguy** [comment]
I resolved this by lowering translateY(-140%) to 80-90%.
