### ISSUE TITLE
Urgent bugs on the CSS order

### ISSUE THREAD

**Issue by gfazioli** [Dogfalo/materialize#2502]
Hi guys, I found a bugs on CSS 0.97.3

This new version has a wrong order of some CSS definition. For example, in `dist/materialize.css` you can see that

![image](https://cloud.githubusercontent.com/assets/432181/11901277/ff4ec172-a5aa-11e5-98b4-897043428e05.png)

As you can see from image above, the `offset-l3` is define before (row 5336) the `.l6` (row 5661). So, the `margin` can't override and it doesn't work,

**Comment by TyrionGraphiste** [comment]
This is already fixed, just link the latest generated CSS version.

**Comment by gfazioli** [comment]
@TyrionGraphiste in current master branch the dist/css seems the same. Do you mean in the next release?

**Comment by TyrionGraphiste** [comment]
https://github.com/Dogfalo/materialize/blob/master/bin/materialize.css

**Comment by gfazioli** [comment]
@TyrionGraphiste ok, works! thx
