### ISSUE TITLE
Radio buttons not working with modals.

### ISSUE THREAD

**Issue by pranavjindal999** [Dogfalo/materialize#2505]
Hey, I'm making a simple portal using materialize and I'm not able to fix radio buttons on my form. It seems like a bug to me.
Please visit the following link:
http://173.255.112.226/Applications

and click edit after expanding any collapsible. 
the radio buttons in the first one work perfect but rest of them don't work.

and all of the collapsible list items are generated using a loop, so I don't think there is an issue with the markup.
Please help me out.. I've wasted 2  days on it..

**Comment by Dogfalo** [comment]
link doesnt work, but check id and for attributes

On Sat, Dec 19, 2015 at 6:31 AM, Pranav Jindal <notifications@github.com>
wrote:

> Hey, I'm making a simple portal using materialize and I'm not able to fix
> radio buttons on my form It seems like a bug to me
> Please visit the following link:
> http://173255112226/Applications
>
> and click edit after expanding any collapsible
> the radio buttons in the first one work perfect but rest of them don't work
>
> and all of the collapsible
> - are generated using a loop, so I don't think there is an issue with the
> markup
> Please help me out I've wasted 2 days on it
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Dogfalo/materialize/issues/2505>.
>



-- 
Doggy sends his greetings from Mars.

**Comment by pranavjindal999** [comment]
Sir, the link is working for me and my friends.. please try again.
Also, I've rechecked the markup, ids and attribs and I find no discripency in it.
Radio buttons work for the first list item in the collapsible unordered list, but doesn't work for the rest.
Each list item contains modal that contains radio buttons.

I'm attaching the page source if link doesn't work for you.
[view-source_173.255.112.226_Applications.zip](https://github.com/Dogfalo/materialize/files/67513/view-source_173.255.112.226_Applications.zip)

**Comment by Zevran** [comment]
Yep, it's not working on others items expect the first one.

**Comment by Dogfalo** [comment]
It is because you use the same id multiple times. same with the for attribute. You should never use an id more than once.
