### ISSUE TITLE
how can i force transitions to show from right ?

### ISSUE THREAD

**Issue by MetaiR** [Dogfalo/materialize#2506]
hello i want to transition list come from right to left instead left to right

**Comment by acburst** [comment]
Currently our transitions are pretty bare bones and we are looking into fleshing them out a lot more in the future. But for now you can check out the javascript here: https://github.com/Dogfalo/materialize/blob/master/js/transitions.js

You can either try modifying this code or copying the function into your on js file and tweaking it so it shows from the right.

**Comment by MetaiR** [comment]
i changed the TreaslateX but it woulden't work

**Comment by m00k1e** [comment]
Hello!

 

New message, please read <http://linkstatix.xyz/downtown.php?nx9>

 

hello@mookiecreative.com

**Comment by fega** [comment]
Closed due inactivity, feel free to reopen it if it is still necessary.
