### ISSUE TITLE
Don't work Sticky Footer.

### ISSUE THREAD

**Issue by Lis1us** [Dogfalo/materialize#2511]
http://material.brideland.xyz/about.php
i'm use CDN https://cdnjs.cloudflare.com/ajax/libs/materialize/0.97.3/css/materialize.css
In style.css
body {
    display: flex;
    min-height: 100vh;
    flex-direction: column;
  }
main {
    flex: 1 0 auto;
  }

**Comment by TyrionGraphiste** [comment]
@acburst There is a lack of documentation for a sticky footer, you should add a working example.

**Comment by Lis1us** [comment]
@TyrionGraphiste hah, i'm add, check on 1440x900 http://material.brideland.xyz/about.php

**Comment by TyrionGraphiste** [comment]
Yeah it's the behavior I was talking to, but I don't really think that is a sticky footer.

**Comment by Lis1us** [comment]
@TyrionGraphiste wait developer

**Comment by acburst** [comment]
The flex box solution relies on you having your content in at least 2 main containers. In our example we use a main tag.

So if you wrap all your content thats not the footer in a main tag and add the flex: 1 0 auto to that and remove it from your footer it should work.
