### ISSUE TITLE
Possible to add a tooltip dynamically?

### ISSUE THREAD

**Issue by patricklindsay** [Dogfalo/materialize#2513]
More of a question than an issue.. Is it possible to do this?

**Comment by Dogfalo** [comment]
Yes, just call the init function shown in the documentation on the element you just added.

**Comment by edlisten** [comment]
@Dogfalo The tooltip init function does not seem to be working to update the tooltip when added dynamically: https://jsfiddle.net/edlisten/grafo4su/1/
