### ISSUE TITLE
waves-effect doesn't always clear properly

### ISSUE THREAD

**Issue by Kazakuri** [Dogfalo/materialize#2515]
Not really breaking or common, but you can get the wave effect to stack permanently by dragging the button or clicking side to side fairly quickly.

Side to Side:
http://codepen.io/anon/pen/pgbyGE
![http://i.imgur.com/K1IpMkX.gif](http://i.imgur.com/K1IpMkX.gif)

Dragging:
http://materializecss.com/
![http://i.imgur.com/rwHTf9p.gif](http://i.imgur.com/rwHTf9p.gif)

**Comment by yoni7790** [comment]
+1

**Comment by fega** [comment]
duplicate #2667
