### ISSUE TITLE
[Feature] Reverse Text Color Based on Background Color Automatically

### ISSUE THREAD

**Issue by Zevran** [Dogfalo/materialize#2517]
Hi,

I noticed that whenever I set a background color, the text color doesn't adapt. It would be great to add this feature.

https://css-tricks.com/reverse-text-color-mix-blend-mode/

I will submit a pull request soon but if in the mean time someone has already implemented this it would be great to contribute :) !

Thanks

**Comment by Y0lk** [comment]
It certainly is a cool feature but it's not really well supported yet and definitely out of the range of browsers Materialize supports =/ 

http://caniuse.com/#search=mix-blend-mode

**Comment by Zevran** [comment]
Yeah true, maybe there is a way to handle it in another way for the (bad) browsers ?

**Comment by fega** [comment]
Moved to feature request board.
