### ISSUE TITLE
input text field issue

### ISSUE THREAD

**Issue by alfredopacino** [Dogfalo/materialize#2518]
Hi
sometimes I click on the input type=text, the label became "active" but the input field isn't active (I can't directly type on it)
In other words the border-bottom stays grey

(i'm on chrome 47.0.2526.106 m / win7)

![elim](https://cloud.githubusercontent.com/assets/6325475/11935161/adf400b8-a806-11e5-9891-2c7c156f57c2.png)

**Comment by ProfNandaa** [comment]
@alfredopacino -- Hi Alfred, when you say "sometimes" do you mean this works okay sometimes and doesn't work some other time?

**Comment by alfredopacino** [comment]
yes..not sure why

**Comment by Dogfalo** [comment]
Please create a codepen to help us fix this issue

**Comment by alfredopacino** [comment]
https://jsfiddle.net/alfredopacino/yc7u4zm7/

nop, I can't replace the issue..  this jsfiddle works fine  :/

**Comment by alfredopacino** [comment]
here to you, please ignore those js error, those aren't the problem (on my local site I haven't any, they are just json sources)
http://nabbaitalia.it/files/materialbug/register.php
Try to refresh the page and click repeatedly on those text field you will see this situation
![a](https://cloud.githubusercontent.com/assets/6325475/11946441/17e575fc-a85b-11e5-9fde-f3a9022ccd49.png)

**Comment by Dogfalo** [comment]
Looks like a 3rd party issue with material-tags. I think you should open an issue there. Because I cannot replicate this with our forms.

**Comment by alfredopacino** [comment]
ok..sadly the authro doesn't look so present on its repository :/
just to be sure: do you noticed the "bug" too?

**Comment by JeanPaulBeard** [comment]
This is my solution for bug
`.input-field label {
    pointer-events: all;
}`
