### ISSUE TITLE
Not Responsive On Mobile

### ISSUE THREAD

**Issue by TheCaucasianAsian** [Dogfalo/materialize#2521]
Hi,

I have a feeling I have another stupid question for you.  My site, although responsive via manual resizing in the Desktop's browser, isn't doing the same on all mobile devices.  (The dev site: http://mycafezen.com/)

I'm using a barebones rails application, hosted in heroku.  Still waiting for pictures from the folks though so still using the default.  Anyway, thanks for your help!

**Comment by Dogfalo** [comment]
Add a meta tag with the viewport

**Comment by TheCaucasianAsian** [comment]
Thank you for looking into this, I did have a viewport tag though.

After playing around, it came down to an over-estimation of display sizes.  All the mobile devices I was using to test it fell under the "m" not "s" class.  Once I changed all my m6's to m12's, everything behaved as desired.
