### ISSUE TITLE
[Bug] SideNav doesn't handle properly buttons

### ISSUE THREAD

**Issue by Zevran** [Dogfalo/materialize#2523]
Hi,

Just like previous release where the navbar behavior for buttons were wrong, it's the same for the sidenav !

![screen shot 2015-12-22 at 11 56 16](https://cloud.githubusercontent.com/assets/498465/11953774/1593653c-a8a3-11e5-925e-f7c65882bab9.png)

I will make a pull request soon :)

**Comment by Zevran** [comment]
Submitted [pull request](https://github.com/Dogfalo/materialize/pull/2528)

**Comment by acburst** [comment]
Merged
