### ISSUE TITLE
[Feaure] Add full width button option

### ISSUE THREAD

**Issue by Zevran** [Dogfalo/materialize#2524]
Hi,

It would be great to add a class that could allow buttons to take full width of parent div.

What do your think ?

Thanks :)

**Comment by Zevran** [comment]
Submitted [pull request](https://github.com/Dogfalo/materialize/issues/2524)

**Comment by acburst** [comment]
I think this is simple enough and generic enough to the point where the developer can make this themselves.

**Comment by Zevran** [comment]
Yeah indeed ^^
