### ISSUE TITLE
[Bug] Form custom error/success messages

### ISSUE THREAD

**Issue by Zevran** [Dogfalo/materialize#2525]
Hi,

Custom error or success messages replace spaces in string with line return ! Is it a correct behavior ?

![screen shot 2015-12-22 at 12 24 30](https://cloud.githubusercontent.com/assets/498465/11954240/34a884ee-a8a7-11e5-8128-49e7e340c767.png)

Thanks

**Comment by Zevran** [comment]
Submitted [pull request](https://github.com/Dogfalo/materialize/pull/2526) .

**Comment by remzr7** [comment]
+1

**Comment by Dogfalo** [comment]
Fixed.
