### ISSUE TITLE
Icons Broken After Upgrade

### ISSUE THREAD

**Issue by douggard** [Dogfalo/materialize#2530]
I upgraded to 97.4 to fix the materialboxed problems. This ended up breaking the icons. Particularly the mdi-social-person. You can see the problem at the bottom of this page: http://materializecss.link/icons.html

The code previously used was: 

    <i class="mdi-social-person"></i>

The fix was including the Google icon font replacing the icon code with something like this:

    <i class="material-icons">person</i>

Not sure if this is something you want to support.

**Comment by Dogfalo** [comment]
The Google icon font had been the official way we include fonts for several
releases now

**Comment by IPWright83** [comment]
I've noticed this too - having re-downloaded them from Google they're fixed, but we're currently including materialize in our project using Bower. This means that whenever we produce a build, we're going to have broken icons :-1:

**Comment by Dogfalo** [comment]
The old icons have been removed now.
