### ISSUE TITLE
_reverse is not a function

### ISSUE THREAD

**Issue by epiblue** [Dogfalo/materialize#2531]
Hello,

I'm trying to implement materialize framework to the new template I'm building, but I get this error...

It's conflicting with prototype.js  I think...

Any ideas how to fix it? I've been strugling with no luck for sometime now.

In this code: 
`
  var openFABMenu = function (btn) {
    $this = btn;
    if ($this.hasClass('active') === false) {

```
  // Get direction option
  var horizontal = $this.hasClass('horizontal');
  var offsetY, offsetX;

  if (horizontal === true) {
    offsetX = 40;
  } else {
    offsetY = 40;
  }

  $this.addClass('active');
  $this.find('ul .btn-floating').velocity(
    { scaleY: ".4", scaleX: ".4", translateY: offsetY + 'px', translateX: offsetX + 'px'},
    { duration: 0 });

  var time = 0;
  $this.find('ul .btn-floating')._reverse().each( function () {
    $(this).velocity(
      { opacity: "1", scaleX: "1", scaleY: "1", translateY: "0", translateX: '0'},
      { duration: 80, delay: time });
    time += 40;
  });
}
```

};`

Thanks,

**Comment by epiblue** [comment]
Any help here? Please

**Comment by patrickcfantato** [comment]
You solved the problem? I'm with the same problem here

**Comment by fega** [comment]
@epiblue @johnschult  Did you solve the issue? 

if not, could someone share a code pen to see what's happening?

thanks

Closed due inactivity, feel free to reopen it if it is still necessary.
