### ISSUE TITLE
Triggering Swtich On/Of

### ISSUE THREAD

**Issue by muralidharbg** [Dogfalo/materialize#2534]
Hi,

If I try turning the switch on and then off and then back on again using jquery simply by adding 'checked' attribute value, removing checked attribute and then adding it back again the switch does not turn on. 

Example: 
$("#switch1").attr('checked', 'checked');
$("#switch1").removeAttr('checked');
$("#switch1").attr('checked', 'checked');

Is there a fix for this?

**Comment by Dogfalo** [comment]
Use prop() instead of attr(), http://api.jquery.com/prop/

**Comment by qiaosangning** [comment]
![test2](https://user-images.githubusercontent.com/10937892/29444027-ce18b1e6-840e-11e7-8208-dd028fececc4.gif)  Can I change the swich statue using jquery through prop or attr or others? It seems I can do nothing to change the status.

**Comment by Dogfalo** [comment]
you need to modify the prop of the input not the div

**Comment by qiaosangning** [comment]
![test3](https://user-images.githubusercontent.com/10937892/29444349-7e13b490-8411-11e7-9eb5-0d3106ff50b5.gif)

I tried to modify the input element which id is "test2", still the switch do not change the status. Is there anything that I did wrong?

**Comment by Dogfalo** [comment]
https://codepen.io/Dogfalo/pen/gxvpBO It is working for me

**Comment by qiaosangning** [comment]
Oh...... I find the reason, it's the id "test2" which i add on the element "input", affects the "prop" attribute. "$($(".switch input")[0]).prop("checked",true)" works. Thank you. 
<img width="659" alt="screen shot 2017-08-18 at 13 23 26" src="https://user-images.githubusercontent.com/10937892/29445375-f6fe192a-8418-11e7-9c52-1c375a80142b.png">
