### ISSUE TITLE
Calling `$('#modal').closeModal()` without any options should use the options passed to `$('#modal').openModal()`

### ISSUE THREAD

**Issue by debanshuk** [Dogfalo/materialize#2537]
As per https://github.com/Dogfalo/materialize/blob/8c71b4ca5e190c7f09d79febb7d2c756bc32bbde/js/leanModal.js#L98, calling `$('#modal').closeModal()` without any options, uses only the default options (`defaults`). But it should use the options originally passed to `$('#modal').openModal()` in such a case. isn't it?

**Comment by gaiazov** [comment]
I ran into this issue today. Looks like the `options` passed in during `openModal` are not available in `closeModal`. 

One way to handle it is to store the `options` in the modal data and then read it inside `closeModal`.

**Comment by fega** [comment]
leanModal is now deprecated
