### ISSUE TITLE
Documentation for valid and invalid classes for form validation

### ISSUE THREAD

**Issue by remzr7** [Dogfalo/materialize#2540]
The form validation documentation only talks about the validate class and doesn't deal with custom logic for validation. The JS simply adds and removes valid/invalid classes. Shouldn't this be in the documentation?

**Comment by alfredopacino** [comment]
I noticed this too, any help?

**Comment by Dogfalo** [comment]
Added in 9fc38f0aa96d658631538bcd037cabed15be073b
