### ISSUE TITLE
Search input type breaks if you use a placeholder 

### ISSUE THREAD

**Issue by jdinard** [Dogfalo/materialize#2541]
For example:

`
            <form>
              <div className="input-field">
               <input id="search" placeholder="Search by email" type="search" required />
                <label ><i className="material-icons">search</i></label>
                <i className="material-icons" onClick={this.clearSearch}>close</i>
              </div>
            </form>
`

Will cause the search icon to get stuck in its animated position, even after the search bar no longer has focus.

However
`
            <form>
              <div className="input-field">
               <input id="search" type="search" required />
                <label ><i className="material-icons">search</i></label>
                <i className="material-icons" onClick={this.clearSearch}>close</i>
              </div>
            </form>
`

Does not cause the same issue

**Comment by fega** [comment]
Could you check if this is still an issue with the last version?
Closed due inactivity, feel free to reopen it if it is still necessary.
