### ISSUE TITLE
What external JavaScript libraries are used?

### ISSUE THREAD

**Issue by SuperDJ** [Dogfalo/materialize#2543]
It might be usefull to developers to know what external JavaScript libraries are used.

In the source code forexample I can see [Hammer.js](http://hammerjs.github.io/) but this is not mentioned in the documentation.
In the issues and pr's I have seen multple questions about [require.js](http://requirejs.org/) but can't find it in the source code.

So why I think it would be usefull to know what external libraries are used:
- Developers might not need to include a library because it is already in Materialize;
- Documentation on how to use libraries already in Materialize;
- A link to the documentation of each library to help out developers as Materialize might be the starting point for searching the documentation

**Comment by tomscholz** [comment]
Materialize uses the following, but most of them are contained inside the repo

    "hammerjs": "^2.0.4",
    "jquery": "^2.1.4",
    "jquery-hammerjs": "^2.0.0",
    "jquery.easing": "^1.3.2",
    "node-archiver": "^0.3.0",
    "velocity-animate": "^1.2.3"

**Comment by tomscholz** [comment]
Related: https://github.com/Dogfalo/materialize/issues/3707
