### ISSUE TITLE
Two Date pickers are not working togethar

### ISSUE THREAD

**Issue by tanuj225** [Dogfalo/materialize#2544]
Hello all 
This is my first issue request in github so i am looking for solution of my problem
I use datepicker in to and from field to get two dates and show refined data but when i use two datepicker together it stop working.

Anyone else also faces the same issue ?

**Comment by lebart** [comment]
Multiple datepicker on the same page are working fine for me. I suggest that you show us some code to be able to give you an answer. I would probably guess that your two datepickers fields have the same id or something like that. Maybe a bad plugin initialization. 
Another suggestion would be to post this on stackoverflow maybe?

**Comment by Dogfalo** [comment]
@tanuj225 If you have more information on reproducing this, please post here and I will reopen this. But it seems to be working.
