### ISSUE TITLE
Wrong grid behavior with Masonry

### ISSUE THREAD

**Issue by mizurnix** [Dogfalo/materialize#2545]
Hello,

I have a Masonry grid with s6 m4 l3 columns. I have noticed a problem on Chrome/IE:

Somewhere below 1200px viewport width, masonry causes three column layout. This is before reaching 992px and it looks like this: ![ugly](https://cloud.githubusercontent.com/assets/10742145/12005719/eaa56bee-abcd-11e5-831d-b52e079f702d.png)

Here is [codepen](http://codepen.io/anon/pen/OMRvrM). It does not happen always, but if you play a little with browser window width, it will.

PS - Could not reproduce on firefox.

**Comment by fega** [comment]
Would you kindly check this is still a problem with the last versions of both projects?

Closed due inactivity, feel free to reopen it if it is still necessary.
