### ISSUE TITLE
Photo uploader needed

### ISSUE THREAD

**Issue by muroshi** [Dogfalo/materialize#2546]
It would be great if we would have a photouploader in forms like dropzone.js (http://www.dropzonejs.com) or jquery file upload (https://blueimp.github.io/jQuery-File-Upload/). From the look more like the first one.

**Comment by muroshi** [comment]
Dropbox.js seems templatable and  comes with an MIT licence. Any takers?

**Comment by Dogfalo** [comment]
See #362. I understand this functionality would be nice. But as is, dropzone is already very nicely styled and it has 63kb of js which is a lot of weight to add.
