### ISSUE TITLE
Suggestion for .tabs class

### ISSUE THREAD

**Issue by ibart** [Dogfalo/materialize#2547]
I suggest you to add 2 lines:

  max-width: 100%;
  overflow-x: hidden;

After the last update, i got scrollable tabs everywhere.

**Comment by typekpb** [comment]
+1 

same issue on chrome (ver: 45.0.2454.85), however firefox (ver: 38.4.0) doesn't have the problem

see: https://jsfiddle.net/9ma5muf4/2/

however suggested solution works OK for both.

**Comment by tomscholz** [comment]
Closing in favor for https://github.com/Dogfalo/materialize/issues/4400
