### ISSUE TITLE
Select Element not rendering code properly in 0.97.5 too.

### ISSUE THREAD

**Issue by hemuk** [Dogfalo/materialize#2548]
Hi,

   Select is still not sending the form value in the request. It seems its not rendering the html code properly. I tried the posted fixes? Please help. Thanks.

**Comment by TyrionGraphiste** [comment]
This issue should be fixed if they accept the PR.

**Comment by hemuk** [comment]
Hey Tyrion, 
   An workarounds please?

**Comment by TyrionGraphiste** [comment]
For now you can get the form.js code on my fork.

**Comment by hemuk** [comment]
Thanks Tyrion. It works.

**Comment by TyrionGraphiste** [comment]
You're welcome. If you encounter an error or any issue please report it.
