### ISSUE TITLE
scss: wrong/ambiguous breakpoints in media queries

### ISSUE THREAD

**Issue by vanilla-thunder** [Dogfalo/materialize#2549]
Hello,
i just noticed, that _variables.scss uses wrong breakpoints for media-queries.
 the screen size ranges are defined as:
`$small-screen-up: 601px !default;`
`$small-screen: 600px !default;`
`$medium-screen: 992px !default;`
`$medium-screen-up: 993px !default;`
`$large-screen: 1200px !default;`
`$large-screen-up: 1201px !default;`

but variables for media queries are using wrong breakpoints:
`$small-and-down: "only screen and (max-width : #{$small-screen})" !default;`
`$medium-and-down: "only screen and (max-width : #{$medium-screen})" !default;`
`$medium-only: "only screen and (min-width : #{$small-screen-up}) and (max-width : #{$medium-screen})" !default;`
`$medium-and-up: "only screen and (min-width : #{$small-screen-up})" !default;`
`$large-and-up: "only screen and (min-width : #{$medium-screen-up})" !default;`

the "large and up" media query implies being applied to >=large screens, which means >= 1201px, but it actually uses mediaum breapoint, which makes the "large" media query available for medium screens. Thats a bit confusing and ambiguous. And there is no media query for screens >=1200px.

There is no real use for media queries for exact screen width of 992 or 600px.
3 or 4 breakpoints should be enough and it would simplify the development:
width < small 600 (as default one)
width >= small 600
width >= medium 992
width >= large 1200

**Comment by m00k1e** [comment]
Hello!

 

New message, please read <http://admin.rinhoo.com/being.php?bbzwx>

 

hello@mookiecreative.com

**Comment by awexfwex** [comment]
Got bitten by this as well. Makes no sense as it is.

**Comment by scandorama** [comment]
There's a 393px difference between a small and a large screen in Materialize - makes NO sense at all. A response would be appreciated and a preferred way (Sass?) to manage the breakpoints even if you're limited to only 3 screen sizes.

**Comment by DetlefPeters** [comment]
I agree with vanilla-thunder.

The MD spec has a breakpoint system with 5 sizes, see [https://material.google.com/layout/responsive-ui.html#responsive-ui-breakpoints](url)
thus, medium size should be [992px. 1408px], large should be [1409px, 1888px] and xlarge [1889px, inf.[

Please adjust the `$medium-and-up` and `$large-and-up` variables, too, as they should refer to `$medium-screen-up` and `$large-screen-up`, resp. At the moment, a `col m6` is defined for small screen sizes...

**Comment by charpeni** [comment]
@acburst Any thoughts on this ?

> We'll think about this for the future, but for now the best way would be to write your own breakpoints in Sass. #1026

Breakpoint variables are really confusing and it seems outdated.

**Comment by acburst** [comment]
Added xl in 104da64
