### ISSUE TITLE
Select Multiple won't deselect

### ISSUE THREAD

**Issue by anthropos9** [Dogfalo/materialize#2554]
I have several select items that are using the multiple option. On render they correctly show which items have been selected. If I select a new item it gets added to the list correctly. My issue is that if i deselect an item that was selected at render and submit, that deselection doesn't get saved. In firebug I can see that there's no change in the selected property on the actual select item. Not sure If I'm doing it wrong or if there is an error in the code.  Here's the code for one of my selects:

```
<div class="input-field col s12 l6">
    <select name="groups[1][]" id="frm_groups_1" multiple>
        <option value="" disabled >Choose groups</option>
        <option value="39" >Cancer Research Protocols</option>
        <option value="38" >Document Editor</option>
        <option value="37" >Jobs Admin</option>
        <option value="36" selected>Per Diem Agency</option>
        <option value="35" >EPFM</option>
        <option value="34" >TFM</option>
        <option value="33" >Blog Author</option>
        <option value="32" >Provider Editor</option>
        <option value="31" >Marketing Coordinator</option>
        <option value="30" >CareConnect</option>
        <option value="29" >Foundation Events Manager</option>
        <option value="28" >Medical Staff</option>
        <option value="27" >Class Admin</option>
        <option value="26" >Page Editor</option>
        <option value="25" selected>Administrators</option>
        <option value="9" selected>Super Administrators</option>
    </select>
</div>
```

And from the jQuery file I have:

```
    $('select').material_select();
```

**Comment by anthropos9** [comment]
FYI I am using 0.97.5

**Comment by TyrionGraphiste** [comment]
Hi, this issue should be fixed in the next release if they accept the PR : https://github.com/Dogfalo/materialize/pull/2514

For now you can take the component code direct on my repository.

**Comment by nicolasFauren** [comment]
Hi, 

We have the same issue with deselecting an option. I'll try @TyrionGraphiste code.

**Comment by nicolasFauren** [comment]
@TyrionGraphiste 's code seems to work fine for the multiple select so far. Thank you

**Comment by TyrionGraphiste** [comment]
@nicolasFauren Thanks for replied
@acburst Do you want to merge the PR ?

**Comment by lebart** [comment]
Hi, 

Same issue here. 
Any updates about the merge of the PR or any other solution?

**Comment by TyrionGraphiste** [comment]
Hi, I'm currently working on an other version. If you want to test it before a probable PR please refer to https://github.com/Dogfalo/materialize/issues/2522#issuecomment-170671609

**Comment by lebart** [comment]
@TyrionGraphiste Thank you

**Comment by TyrionGraphiste** [comment]
I added the CSS in my last past, you have to add after materialize.css

**Comment by fega** [comment]
Closed due inactivity, feel free to reopen it if it is still necessary.
