### ISSUE TITLE
add edit icon to the existing list

### ISSUE THREAD

**Issue by SantanMaddi** [Dogfalo/materialize#2555]
[Something like this](https://cdn3.iconfinder.com/data/icons/google-material-design-icons/48/ic_mode_edit_48px-128.png)

**Comment by TyrionGraphiste** [comment]
Hi,

What list are you talking ?

**Comment by SantanMaddi** [comment]
Most basic icon is edit for most applications, which must be included in the icons.html page. I have create a PR adding the mode_edit icon. Hope this clarifies!

**Comment by AdiFahmi** [comment]
Why?
Materialize CSS is using Google Material Icons, and the complete and updated list of the icons is in here : https://design.google.com/icons/

**Comment by SantanMaddi** [comment]
It can be argued either ways, there need not be a list at all as in [here](http://materializecss.com/icons.html) and could easily redirect the user to the link @AdiFahmi mentioned. However, the idea behind maintaining a list is to give the feel that most common icons are right at hand to the user to avoid further navigation. And edit icon falls under most commonly used icons.

**Comment by AdiFahmi** [comment]
Agreed

But IMO, [Icons page](http://materializecss.com/icons.html) should be just *preview* of some icons, and the link to Google Mateial Icons page should more *eye-catching*.
