### ISSUE TITLE
Problem with select within a "Modal Bottom Sheet Style"

### ISSUE THREAD

**Issue by lcpereira** [Dogfalo/materialize#2557]
Hello,

I'm trying to use the select within "Bottom Sheet Modal Style", however, is not displaying correctly. I know that the select is opened as select position, being at the top, the list is open on the bottom, I could manually say that in this case specific, be opened to low?

Thanks

![select](https://cloud.githubusercontent.com/assets/10385917/12045398/5ccfee7a-ae89-11e5-96a4-2b948466e396.png)

**Comment by TyrionGraphiste** [comment]
For now there is now way to achieve this, I think this is hard to detect when the select becomes not visible.

**Comment by KarimGeiger** [comment]
I think I have a similar problem. I'm trying to use the date picker in a bottom sheet style modal, which also gets cut off. Interestingly, Firefox renders everything perfectly, while on Chrome and mobile (iOS/Android) the rendering fails. See this fiddle to reproduce:

https://jsfiddle.net/2m2cqqdu/1/

Would be really thankful for any advice on how to get this working.

![screen shot 2016-03-22 at 02 46 20](https://cloud.githubusercontent.com/assets/2329930/13939786/4dd4fd94-efd8-11e5-8f5b-740565dc962e.png)

**Comment by Thanood** [comment]
For datepicker it's really easy because you can simply set the container to "body" (or anything in between):
```javascript
$('#datepicker').pickadate({ container: 'body' });
```

Modified fiddle:
https://jsfiddle.net/asbz02y7/

**Comment by KarimGeiger** [comment]
That's awesome. Thanks a lot, @Thanood :)

**Comment by NitroBAY** [comment]
The bug is still here, if I find a solution for select I will share it. If anyone have a tip, please tell it because it's an huge problem for me...

**Comment by NitroBAY** [comment]
Hello. As I had the same problem, The solution for me was to add "overflow-y: visible" to the modal. 
By default it is set by Materialize to auto. According to [W3C](http://www.w3schools.com/cssref/css3_pr_overflow-y.asp) :
> Should cause a scrolling mechanism to be provided for overflowing boxes
But I have been testing bottom sheets modal with elements causing childs of modal to be greater than modal itself even directly on Materialize's website with overflow-y: visible and the "scrolling system" are still working. So I could consider add my fix as a pull request but I need feedback on it to be sure it'll not break anything. 
Hope this bit could help

**Comment by NitroBAY** [comment]
Hello. As I had the same problem, The solution for me was to add "overflow-y: visible" to the modal. 
By default it is set by Materialize to auto. According to [W3C](http://www.w3schools.com/cssref/css3_pr_overflow-y.asp), overflow-y: auto :
> Should cause a scrolling mechanism to be provided for overflowing boxes

So changing auto to visible will make modal unscrollable.

**Comment by NitroBAY** [comment]
Second solution use brower's native select by adding browser-default to select as described [here](http://materializecss.com/forms.html#select). I didn't already figure out which css rules makes browser's native select visible even with overflow-y: auto (which is what set by default to bottom sheet modal)

**Comment by fega** [comment]
@tomscholz this is a duplicate Issue, I guess, Did you know if it is true?

**Comment by stap123** [comment]
I have experienced this issue today. I can confirm that setting overflow-y:visible on the modal seems to have fixed the issue.

**Comment by acburst** [comment]
Container option added in 42aa7476.

You can specify `document.body` as the container of the dropdown to pull the dropdown out of the modal.

**Comment by zzarmandoq** [comment]
I specified the modal in container option and it worked for me, the dropdown never got higher or out of the modal.
