### ISSUE TITLE
Start date and end date option in datePicker

### ISSUE THREAD

**Issue by sanjeevverma** [Dogfalo/materialize#2558]
In DatePicker, do you provide start date and end date option. if yes, then how to implement that and if No then when you will provide that option.

**Comment by Dogfalo** [comment]
see pickadate.js which has the options documentation

**Comment by maxmumford** [comment]
`<input id="startDate" materialize="pickadate" [materializeParams]="[{selectMonths: true, selectYears: 15, min: 1}]" type="text" />`

documentation:

http://amsul.ca/pickadate.js/api/#method-set-min
