### ISSUE TITLE
Dropdown Width

### ISSUE THREAD

**Issue by ConsoleTVs** [Dogfalo/materialize#256]
The dropdown feature should try to adjust it's width with the largest text inside:

Current Release:
http://i.gyazo.com/5a651b4140790f6870a6dc26a3996609.png

What it should look like:
http://i.gyazo.com/f9918f592fff2cd421223f16d3d7dc5c.png

**Comment by clusteratlas** [comment]
2017: constrainWidth is now passed as an object option/property upon jquery initialization of the dropdown. Check http://materializecss.com/dropdown.html !

sample (with hover, lol):

```
$(".dropdown-button").dropdown({ hover: true, constrainWidth: false });
```

**Comment by adhavalboy** [comment]
Still not working in march 2018

**Comment by supperpiecheese** [comment]
If you go into materializecss.js and go to line 2199 you can change the default to true.

![image](https://user-images.githubusercontent.com/16927633/40683613-0eb6b5ee-635d-11e8-8dcd-f27f9427c4a3.png)
