### ISSUE TITLE
No group label for checkboxes or radio buttons

### ISSUE THREAD

**Issue by acierpinski** [Dogfalo/materialize#2561]
If you want to group decisions by radiobuttons or checkboxes you cannot set a group label.

**Comment by TyrionGraphiste** [comment]
Yes you can : https://jsfiddle.net/TyrionGraphiste/8res4xmr/

**Comment by Dogfalo** [comment]
There is also an example of this on the documentation

**Comment by arajay** [comment]
>  set a group label

These are labels for the individual radio controls, but there is no documentation for how to label the radio group. I've been playing around and can't get the group label to be positioned in a manner consistent with other form labels.
