### ISSUE TITLE
How to use thin Roboto Font

### ISSUE THREAD

**Issue by mahesh0431** [Dogfalo/materialize#2562]
I am new to meteor and CSS stuff. I am using materialize package in my meteor project but by default the font is appearing as little bit bold
![image](https://cloud.githubusercontent.com/assets/6804552/12054236/99b545c4-af47-11e5-89a1-1129eeb3d5a3.png)

But i want my font to appear a thin like in this official materialize page

![image](https://cloud.githubusercontent.com/assets/6804552/12054244/bae8250e-af47-11e5-9768-9ea95f1fb731.png)

**Comment by TyrionGraphiste** [comment]
In your CSS you have to specify the weight of the font to use :

html {
    font-family: "Roboto", sans serif;
    **font-weight: 300;**
}

**Comment by mahesh0431** [comment]
@TyrionGraphiste , really appriciate your help, thank you so much!!! and i feel like the meteor part is not documented properly, or am i missing something ?

**Comment by mahesh0431** [comment]
@TyrionGraphiste  my bad documentation is there only.. anyways thanks again!!
