### ISSUE TITLE
unable to change tabs width (to less than 100%)

### ISSUE THREAD

**Issue by typekpb** [Dogfalo/materialize#2564]
tried to make tabs occupy only `50%` of the `width` via:

```
ul.tabs {
  float: left;
  width: 50%;
}
```

didn't work as javascript initiating the tabs seems to set `width` to `100%` anyway. 

So having:

```
<ul class="tabs">
```

results in:

```
<ul class="tabs" style="width: 100%;">
```

Example: https://jsfiddle.net/9ma5muf4/

Even setting style inline doesn't work here, as having:

```
  <ul class="tabs" style="width=50%;">
```

produces the same output anyway, see: https://jsfiddle.net/9ma5muf4/1/

**Comment by typekpb** [comment]
well, OK, solution suggested in #2547 provides desired output.

Works if using:

	ul.tabs {
	  float: left;
	  max-width: 50%;
	  overflow-x: hidden;
	}

See: https://jsfiddle.net/yd67644r/

It surely is a workaround for me. Feel free to close this one or reuse to document more general fix, if that is required.

**Comment by fega** [comment]
thanks @typekpb
