### ISSUE TITLE
Icons do not appear in meteor installation

### ISSUE THREAD

**Issue by Nikolay-Pomytkin** [Dogfalo/materialize#2567]
**Meteor:** v 1.2.1
**Atmosphere package:** materialize:materialize@0.97.5
**Issue:** Icons do not show.
```
 <i class="label"></i>
```
 results in *LABEL*

**Comment by Dogfalo** [comment]
Did you add
`<link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">`

**Comment by Nikolay-Pomytkin** [comment]
That seems to have fixed the issue, but wouldn't it make more sense for all the icons to load in with the installation of the atmosphere package, rather than manually have to load them in? That could be an added feature in the future.
