### ISSUE TITLE
FAB Responsive Behavior

### ISSUE THREAD

**Issue by markibanez** [Dogfalo/materialize#2568]
Hi,

I was wondering if you have a solution for fabs going off screen on narrower widths. I've included a couple of screenshots. The first one is one a wider screen and the second on shows fabs exceeding the screen on the narrower screen. 

![image](https://cloud.githubusercontent.com/assets/7534847/12062339/e64820d0-afd5-11e5-802d-fd562ce0f49d.png)

![image](https://cloud.githubusercontent.com/assets/7534847/12062348/04058310-afd6-11e5-9bc5-dbb086de7740.png)

**Comment by Dogfalo** [comment]
Try making it vertical if you have a lot of buttons
