### ISSUE TITLE
grid push/pull not working properly in 0.97.3 - 0.97.5 

### ISSUE THREAD

**Issue by nicolefinnie** [Dogfalo/materialize#2569]
Our site needs to support Arabic languages so we use the grid pull/push feature to change our layout by language. 

For example: <div ng-class="properties.rightToLeft ? 'col m11 s10 pull-s2':'col m11 s10'">  however, it works fine in 0.97.2 but not in later versions, I hit a similar problem with offset ( #2328 ) which has been fixed in 0.97.4. Can't find any duplicate issue, but I saw some grid pull/push has been added to 0.97.3, and it might be related. 

Thanks
Nicole

// our HTML code

<div class="row">
            <div ng-class="properties.rightToLeft ? 'col m1 s2 push-s10 right':'col m1 s2 left'">
                <svg version="1.1" xmlns="http://www.w3.org/2000/svg" 

                </svg>
            </div>

```
        <div ng-class="properties.rightToLeft ? 'col m11 s10 pull-s2':'col m11 s10'">
            <input ng-class="properties.rightToLeft ? 'right-align':'left-align'" type="text" id="username" name="username" class="validate" ng-model="credentials.username" placeholder="{{properties.username}}" lowercase required>
            <div ng-messages="userForm.username.$error" role="alert">
            <p class="help-block error-text" ng-message="required">Username is required.</p>
            </div>
        </div>
      </div>
```

**Comment by nicolefinnie** [comment]
Forgot to attach the screenshots of our site, the two fields in the middle should be right-aligned with 'col m1 s2 push-s10 right' (the icon) and 'col m11 s10 pull-s2' (the input field) 

The first screenshot shows the issue in 0.97.3 or 0.97.5
![materializegridpushproblem](https://cloud.githubusercontent.com/assets/15970573/12064816/d3031772-afcc-11e5-8a1e-7711e302ed5b.png)

The second screenshot shows no issue in 0.97.2

![materializegridpush0972](https://cloud.githubusercontent.com/assets/15970573/12064860/8d6b14e8-afcd-11e5-888e-9fa7fdf44be9.png)

**Comment by m00k1e** [comment]
Hello!

 

New message, please read <http://scannerlab.com/typical.php?y82c>

 

hello@mookiecreative.com

**Comment by tomscholz** [comment]
Can you post a codepen that uses the latest version? Anyhow, I will close this issue for now
