### ISSUE TITLE
Icons with two word names not working

### ISSUE THREAD

**Issue by babakness** [Dogfalo/materialize#2571]
It seems icons that have two or more words in their names don't work. For example:

```html
<i class="material-icons">camera</i>
```
works however

```html
<i class="material-icons">navigate back</i>
```

does not work. All icons with two words or more don't work, it seems the space is being parsed, indeed

```html
<i class="material-icons">camera camera</i>
```

shows two cameras. Is there a documented way of utilizing icons with two names or more?

Thanks.

**Comment by gnarlycharlie4** [comment]
This is what you're looking for. I ran into this but figured it out through [Google's material icon font docs](https://design.google.com/icons/)

`<i class="material-icons">navigate_back</i>`
