### ISSUE TITLE
Dropdown menu binding

### ISSUE THREAD

**Issue by JPaulPunzalan** [Dogfalo/materialize#2578]
<b>Is it possible NOW to bind the select class with data coming from a database table?</b> I see that this framework has released several versions over the past months.

I tried using Materialize last August or September and I concluded at that time that Materialize cannot bind data from database tables. The output that I got during that experimentation was an invisible dropdown menu. It doesn't show.

I'm just wondering if it is possible now to bind data from database tables to the materialize dropdown?

**Comment by fega** [comment]
Closed due inactivity, feel free to reopen it if it is still necessary.
