### ISSUE TITLE
Datepicker. Argument 1 of Node.contains is not an object. Firefox

### ISSUE THREAD

**Issue by Mirdrack** [Dogfalo/materialize#2583]
Hello:

I'm developing an application where I use a datepicker installed with bower, everything runs perfect until I  try use the buttons on the bottom
All of them throws me this error: 
![Image of Bug](http://img.prntscr.com/img?url=http://i.imgur.com/GxohyFV.png)

After a little bit of research I found the problem on **pickdate.js**, the problem comes up on **Firefox** when tries to querying for active element with `$.contains`.
This bug already was fixed but it seems like materialize takes an older version.
You can check this bug here:
The issue: 
https://github.com/amsul/pickadate.js/issues/325
The bug fix: 
https://github.com/amsul/pickadate.js/commit/bfa2e1eaa9b61b1d1e004698098c463e4a175023

I just edit **materialize.js** like the fix and now everything is fine.

I do not attach a CodePen example because I thing it is not necessary, hope my info be useful and let me know if need more information about it, I will be happy to help.

Thanks for all.

**Comment by fega** [comment]
Could you check if this is still an issue with the last version?
Closed due inactivity, feel free to reopen it if it is still necessary.

**Comment by crespyl** [comment]
I'm seeing this issue again, and it happens in both Firefox and Chrome.
The same fix still works; changing [line 698](https://github.com/Dogfalo/materialize/blob/master/js/date_picker/picker.js#L698) from
```
activeElement = activeElement && ( activeElement.type || activeElement.href )
```
to
```
activeElement = ( activeElement.type || activeElement.href ) && activeElement
```

ensures that the correct value gets assigned.

**Comment by Mirdrack** [comment]
Should we create a pull request with the updated version of pickdate.js?

**Comment by Dogfalo** [comment]
create a pr with the fix, not the updated version of pickadate
