### ISSUE TITLE
Side nav issue

### ISSUE THREAD

**Issue by nicolasFauren** [Dogfalo/materialize#2589]
Hi everybody

since the last [release](https://github.com/Dogfalo/materialize/releases/tag/v0.97.5), there is a problem on our side navs panels: it seems the user needs at least 2 click outside the navigation panel to get the focus on the main page behind. The side nav panel is supposed to dismiss every time the user click outside (similar to the popup behavior). Does anyone have the same issue?

**Comment by Dogfalo** [comment]
The Sidenav component hasn't been changed in 7 months. Maybe you changed
something in your code?

On Sun, Jan 3, 2016 at 9:03 PM, nicolasFauren <notifications@github.com>
wrote:

> Hi everybody
>
> since the last release
> <https://githubcom/Dogfalo/materialize/releases/tag/v0975>, there is a
> problem on our side navs panels: it seems the user needs at least 2 click
> outside the navigation panel to get the focus on the main page behind The
> side nav panel is supposed to dismiss every time the user click outside
> (similar to the popup behavior) Does anyone have the same issue?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Dogfalo/materialize/issues/2589>.
>



-- 
Doggy sends his greetings from Mars.

**Comment by khachikyan** [comment]
Having the same issue as well.

**Comment by nicolasFauren** [comment]
@Dogfalo we didn't change anything in our code, we made the upgrade on an isolated branch, maybe the problem comes from another component

**Comment by acburst** [comment]
Can you post a code example?

**Comment by nicolasFauren** [comment]
For sure, here is the html : 
```
<div id="slide-out" class="side-nav row col s12">
    <!-- SIDE BAR -->
    <form class="col s11 offset-s1" name="form" ng-submit="ctrl.getList()">

        <h4>Recherche</h4>

        <div class="row">
            <select id="etat_select" class="browser-default"
                    ng-options="etats.code as etats.valeur for etats in ctrl.etats"
                    ng-model="ctrl.form.etat" select-init>
            </select>
        </div>

        <div class="row">
            <div class="input-field col s4">
                <input id="annee" name="annee" type="text" class="validate"
                       ng-model="ctrl.form.annee" ng-pattern="/^[0-9]*$/"
                       ng-maxlength="4" ng-minlength="4" floating-label="Habilit&eacute; en"
                       ng-model-options="{ allowInvalid: true}">

                <div class="field-hint" ng-messages="form.annee.$error"
                     ng-show="form.annee.$dirty">
                    <div ng-message="pattern">Le champs doit &ecirc;tre num&eacute;rique</div>
                    <div ng-message="maxlength,minlength">Une ann&eacute;e doit &ecirc;tre sur 4 caract&egrave;res</div>

                </div>
            </div>
        </div>

        <div class="row">
            <div class="input-field col s12">
                <angucomplete-alt id="intitule"
                                  pause="400"
                                  selected-object="ctrl.suggestIntitule"
                                  search-fields="ctrl.form.intitule"
                                  title-field="intitule"
                                  label="Intitul&eacute;"></angucomplete-alt>
            </div>
        </div>

        <div class="row">
            <div class="input-field col s12">
                <angucomplete-alt id="jure"
                                  pause="400"
                                  selected-object="ctrl.suggestJure"
                                  search-fields="ctrl.form.jure"
                                  title-field="jury"
                                  label="Jur&eacute;"></angucomplete-alt>
            </div>
        </div>

        <div class="row">
            <button class="btn waves-effect waves-light col offset-s6" type="submit"
                    ng-show="ctrl.form.annee || ctrl.form.etat "
                    ng-disabled="form.$invalid">Rechercher
                <i class="material-icons right">send</i>
            </button>
            <button class="btn waves-effect waves-light col offset-s6" type="submit"
                    ng-show="!ctrl.form.annee && !ctrl.form.etat"
                    ng-disabled="form.$invalid">Tous
                <i class="material-icons right">send</i>
            </button>
        </div>

    </form>
</div>
````

And we initiate the side bar like this in our controller : 
```
    initSideNav() {

        $('.button-collapse-recherche').sideNav({
                menuWidth: 350,
                edge: 'left',
                closeOnClick: true
            }
        );
        $('.button-collapse-recherche').sideNav('show');

    }
```
We don't face the problem at first display of the page, when we navigate through the application, and then come back on a page with a side nav, then the issue appears.

**Comment by surabhilabs** [comment]
I see the same issue in a specific case. also this dom element seems to be leaking as well

<div class="drag-target" style="touch-action: pan-y; -webkit-user-drag: none; -webkit-tap-highlight-color: rgba(0, 0, 0, 0); left: 0px;"></div>

**Comment by fega** [comment]
@nicolasFauren @startupgurukul, It looks as a problem with event handlers.
Closed due inactivity, feel free to reopen it if it is still necessary.
Please provide a way to reproduce it. like a [codepen](https://codepen.io/fega/pen/BWeZaG)
