### ISSUE TITLE
Help with Modal

### ISSUE THREAD

**Issue by joelmuskwe** [Dogfalo/materialize#2590]
How can i destory the instance of the modal completely and not just close the modal.I want a scenario where each time the modal is opened it will be a new instance.
$('#modal1').closeModal();

**Comment by gaiazov** [comment]
I ran into this issue today. Looks like the `options` passed in during `openModal` are not available in `closeModal`. Looks like one way to handle it is to store the `options` in the modal data and then read it inside `closeModal`.

**Comment by fega** [comment]
maybe remove it with jquery could works?

Closed due inactivity, feel free to reopen it if it is still necessary.
