### ISSUE TITLE
extending lighten class not working (ignored) in sass

### ISSUE THREAD

**Issue by Ahmed-90** [Dogfalo/materialize#2593]
Hi

am using the sass version.. this:
```sass
.info-name {
   @extend .grey, .lighten-1;
}
```

dont work it just apply the color `.grey` and no `.lighten` but this:
```sass
.info-name {
   @extend .grey, .darken-1;
} 
```

works fine .. also if i use the color classes in the HTML doc (like `class="grey lighten-1"`)  it works but not with sass `@extend`

here is the issue inthe inspect/debug: 

![debug](https://cloud.githubusercontent.com/assets/6548599/12096772/600906c6-b320-11e5-9a55-b0c965d5df76.png)

Thanks

**Comment by acburst** [comment]
Ahh thanks for pointing this out. This is due to how we ordered the sass classes. 

Fixed in a596b33. Let me know if this fixes it!

**Comment by Ahmed-90** [comment]
Yep works now :+1:  

Thanks

**Comment by jordanpe1** [comment]
How did you solve the problem?
