### ISSUE TITLE
Grid columns with size 0 display

### ISSUE THREAD

**Issue by aviemet** [Dogfalo/materialize#2594]
For responsive design, it's helpful to be able to set a column as width 0, usually on a small screen so that it just disappears. Currently, a `co`l with class `s0` still takes up space and throws the flow off. Here's the workaround I'm using:

    .col{
    	@media #{$small-and-down} {
    		&.s0{
    			display: none;
    		}
    	}
    	@media #{$medium-only} {
    		&.m0{
    			display: none;
    		}
    	}
    	@media #{$large-and-up} {
    		&.l0{
    			display: none;
    		}
    	}
    }

**Comment by Ahmed-90** [comment]
hide on X is already there @ http://materializecss.com/helpers.html#hiding and a list of classes (under sass in docs)
```
 /* These classes can be added to HTML Elements
   * to affect visibility on certain displays.
   */
  .hide-on-small-only
  .hide-on-small-and-down
  .hide-on-med-and-down
  .hide-on-med-and-up
  .hide-on-med-only
  .hide-on-large-only
  .show-on-large
  .show-on-medium
  .show-on-small
  .show-on-medium-and-up
  .show-on-medium-and-down
```

**Comment by aviemet** [comment]
I'm aware of `hide-on-x` classes, I just thought it could be useful to be able to keep the grid system syntax.
