### ISSUE TITLE
Icons not included in Meteor package

### ISSUE THREAD

**Issue by afang** [Dogfalo/materialize#2595]
`<i class="material-icons prefix">account_circle</i>` not being loaded.

![](http://content.screencast.com/users/Gyazo/folders/Jing/media/aed70e7e-aa2e-4257-a8fc-66cc05c388ab/00000004.png)

I need to include `<link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">` manually.

**Comment by Dogfalo** [comment]
This is described in the icon documentation
