### ISSUE TITLE
having a duplicate dropdown menù button does not work

### ISSUE THREAD

**Issue by badpenguin** [Dogfalo/materialize#2596]
I tried to bind a dropdown in both desktop and mobile menù, see below, but the button will not work for desktop, only mobile will work. I had to duplicate ul#dropdown1 as ul#dropdown2 having extra markup in the code.

Is it the correct behavior? Or its a bug with "data-activates" of .dropdown-button script?

Example:

```
  <nav>
    <div class="nav-wrapper">
      <a href="#!" class="brand-logo">Logo</a>
      <a href="#" data-activates="mobile-demo" class="button-collapse"><i class="material-icons">menu</i></a>
      <ul class="right hide-on-med-and-down">
        <li><a href="sass.html">Sass</a></li>
        <li><a href="badges.html">Components</a></li>
        <li><a href="collapsible.html">Javascript</a></li>
        <li><a href="mobile.html">Mobile</a></li>
        <li><a class="dropdown-button" href="#!" data-activates="dropdown1">Dropdown<i class="material-icons right">arrow_drop_down</i></a></li>
      </ul>
      <ul class="side-nav" id="mobile-demo">
        <li><a href="sass.html">Sass</a></li>
        <li><a href="badges.html">Components</a></li>
        <li><a href="collapsible.html">Javascript</a></li>
        <li><a href="mobile.html">Mobile</a></li>
        <li><a class="dropdown-button" href="#!" data-activates="dropdown1">Dropdown<i class="material-icons right">arrow_drop_down</i></a></li>
      </ul>
    </div>
  </nav>

<ul id="dropdown1" class="dropdown-content">
  <li><a href="#!">one</a></li>
  <li><a href="#!">two</a></li>
  <li class="divider"></li>
  <li><a href="#!">three</a></li>
</ul>
```

**Comment by CesarGonzalezM** [comment]
It's not exactly a bug. The dropdown-content element position itself relatively from the trigger, so it first move to the desktop menu trigger and next to the mobile one.

It is working ok, but not visible due to the sidenav is not showing and bad positioned. Maybe the solution is attach the dropdown to the clicked item before showing.

**Comment by seanriordan08** [comment]
I'm having the same problem (Ruby2.2.2, Rails 4, gem 'materialize-sass'). I can get the dropdowns working on mobile or desktop, but not both (responsive). At this point, I'm happy to settle for collapsible on mobile!

**Comment by rekiemfaxaf** [comment]
Hi, i'm having the same problem with rails 4.2.2, ruby 2.1, and gem materialize-sass, i can get to work the side navbar for mobile versions

**Comment by Mavril14** [comment]
You maybe add the class "navbar-fixed" before your "mobile-demo".
If you make this, that make a bug in your dropdown.

**Comment by badpenguin** [comment]
Materialize looks like abandonedware. I switched to UiKit since long ago.

**Comment by tomscholz** [comment]
Closed due inactivity. Feel free to reopen it, if it's still necessary.
