### ISSUE TITLE
Right side-nav issue

### ISSUE THREAD

**Issue by armineslami** [Dogfalo/materialize#2599]
Hi
There is an issue with fixed side-nav when it's edge is set to 'right' which is when the page is loaded the side-nav is on the left :

![screen shot 1394-10-15 at 20 14 19](https://cloud.githubusercontent.com/assets/4068423/12121138/01aba902-b3e9-11e5-86a9-8813677c6a28.png)

but when the browser is resized just a little bit, it moves to the right :

![screen shot 1394-10-15 at 20 14 39](https://cloud.githubusercontent.com/assets/4068423/12121141/059ee56a-b3e9-11e5-9b08-0c414a79e9a4.png)

I've tested it on safari, chrome and microsoft edge and the only version that it seems to work fine is 0-95-3.

**Comment by Thanood** [comment]
I think this issue can be resolved by adding class="right-aligned" to the side-nav div.
But this is not documented and may therefore change in the future, I think.

Is there an "official" way to create a right-aligned fixed side-nav?
