### ISSUE TITLE
Datepicker label over date input

### ISSUE THREAD

**Issue by italomaia** [Dogfalo/materialize#260]
I have a input with type "date" and class "datepicker". When filled, the label gets over the input value. See the printscreen below. 

![date](https://cloud.githubusercontent.com/assets/14670/5446864/a1844fa4-84a3-11e4-9e92-a535c0c5fdb6.png)

The field is just like in the example:

```
<div class="input-field">
    <label for="emission">Data de Emissão</label>
    <input type="date" value="" required="required" name="emission" id="emission" class="datepicker">
</div>
```

**Comment by idovgan519** [comment]
This should be added to the documentation as that is not an immediately obvious answer.
