### ISSUE TITLE
Dropdown content referenced multiple times

### ISSUE THREAD

**Issue by jcutrono** [Dogfalo/materialize#2607]
The logic for placing the dropdown-content runs on initialization. If you have a dropdown referenced in a repeater, the dropdown-content will only be attached to the last element. If the placeDropdown method were to place the contents when it was called, would solve the problem.

dropdown.js - line 49
origin.after(activates);

place that call inside the placeDropdown function 6 lines down.
![placedropdown](https://cloud.githubusercontent.com/assets/2238260/12147731/68abf6d2-b468-11e5-8d75-a9da0adeb157.png)

**Comment by fega** [comment]
Closed due inactivity, feel free to reopen it if it is still necessary.
