### ISSUE TITLE
how make Character Counter count 2 character in newlines

### ISSUE THREAD

**Issue by darckyn** [Dogfalo/materialize#2609]
Hello.

Please Help.

How I make the Character Counter count 2 characters in newlines?
The string It is stored in a database, and i need this function.

Thx.

**Comment by Dogfalo** [comment]
This is something you need to write yourself if you want a new line to count twice. You can take a look at our code or look online to see how to do this.

**Comment by darckyn** [comment]
thanks for answering.

I made a small change in the code and is now counting correctly.

Please, in the future consider adding this feature.
It will help many programmers who need to insert a textarea in the database.

And thanks for the amazing css. :)
