### ISSUE TITLE
Materialize cdnjs Install does not trigger animations

### ISSUE THREAD

**Issue by yoavgurevich** [Dogfalo/materialize#2610]
I am trying to add Materialize in simple cdnjs format to my webpage, and the card component I'm attempting to use does not collapse/expand at all even though there are no console errors from the dependency loads...

Here is my HTML on codepen. I have yet to use any JS on top of this code:

https://codepen.io/anon/pen/BjWOQB

Thanks in advance...

**Comment by acburst** [comment]
You are not using codepen correctly. In your html section you should only put markup that would go inside the body tags. If you want to add script dependencies click on settings and you can add external css links and javascript links.

Here's a quick example of your pen with the correct way to add dependencies.
https://codepen.io/anon/pen/YwVPgb

**Comment by yoavgurevich** [comment]
+1 thank you, but for the life of me I won't understand why these did not work as self-resolving tags...
