### ISSUE TITLE
On mobile phone screen, div with class 'drag-target' close right part of 'slide-nav' menu

### ISSUE THREAD

**Issue by asbelov** [Dogfalo/materialize#2614]
Hello,

On screens with small resolution (mobile phone screens), when showing menu 'slide-nav', you set width of div with class 'drag-target' to 50% 
f.e. in js file: dragTarget.css({width: '50%', right: '', left: 0});

In this case, div with class 'drag-target' close right part of menu 'slide-nav' and I can't use elements, located on a right part of 'slide-nav' menu.
Please, correct this, it is very important for me.

Thank you for you work

**Comment by fega** [comment]
Close in favor of #2715
