### ISSUE TITLE
IE11 Navbar dropdown 

### ISSUE THREAD

**Issue by Stakexx** [Dogfalo/materialize#2618]
Found an issue with the Navbar dropdown in IE11. With the current <b>nav ul a {</b> styling it displaces the items in the menu, see below. (Highlighted the menu items to show where the icons end up ect)

![image](https://cloud.githubusercontent.com/assets/16610664/12199390/b182ae48-b60f-11e5-8e4e-0cd8c43d51d6.png)

If you change display in nav ul a from <b>'display: block;'</b> to <b>'display: inline-flex;'</b> this resolves the issue.

Just thought I would let you guys know, haven't tested whether or not this affects anything else or if there is perhaps a better way to do it.

Cheers
Stakex

**Comment by acburst** [comment]
Fixed in a9c0279.

I actually used inline-block in this case.

**Comment by proxymus** [comment]
But isn't working with IE11 on the materializecss.com site.
![grafik](https://cloud.githubusercontent.com/assets/1539498/22592183/c67f4156-ea18-11e6-8405-d859d85b8cfe.png)
