### ISSUE TITLE
Icon not displaying on opera-mini

### ISSUE THREAD

**Issue by zionnite** [Dogfalo/materialize#2619]
Happy new year great and wonderful personality,
please am having issue with the materilize icon... its not displaying on opera-mini brower but it do display on other brower....

thanks again and happy new year

**Comment by arcv** [comment]
Opera Mini doesn't support font icons but support SVG. You may follow this guide to support Opera Mini; https://dev.opera.com/articles/making-sites-work-opera-mini/

**Comment by Dogfalo** [comment]
@zionnite You can find more info on the icons here: https://github.com/google/material-design-icons. Thanks @arcv for providing a helpful resource..
