### ISSUE TITLE
Question: how to color tabs

### ISSUE THREAD

**Issue by gg4u** [Dogfalo/materialize#2620]
Hello, I have not found in documentation how to change color palette of tabs.
Eg. https://developers.google.com/knowledge-graph/reference/rest/v1/

tabs are blue white.
instead I am having red white.

I tried with combination `class="tab blue white-text"` but did not work.

**Comment by acburst** [comment]
If you are familiar with sass we have variables to customize these colors. But besides that the color classes should work for coloring everything except the underline indicator. Make sure you are adding the white-text to the a tag which has the actual text and not the outer tab class.

**Comment by Dogfalo** [comment]
We can add some documentation on how to style tabs to help others.

**Comment by samehraban** [comment]
Isn't it a pitfall that tab indicator is always red? and there is no simple way to colorize all the tabs text together?

**Comment by chifreaigle** [comment]
As i said, the documentation needs a rework.

**Comment by LunarGem** [comment]
I have a list of all of the ways I changed colors before I learned Sass (I waded through a lot of code). I could see if I could write a guide for this?
