### ISSUE TITLE
Text is flickering during the transition of the checkbox

### ISSUE THREAD

**Issue by ramunasm** [Dogfalo/materialize#263]
When I have multiple checkboxes and tick the top most the ones that are below it flicker during the animation period.

It looks like the font-weight changes during the transition period. I'm seeing this problem on Safari and Chrome, though Chrome shows less of a change or so it looks.

A couple of screenshots. One is form in normal state, the other was made during the transition of the checkbox:

![after](https://cloud.githubusercontent.com/assets/1158178/5449900/fc62e086-8505-11e4-945e-15d71a4de2c0.png)
![during](https://cloud.githubusercontent.com/assets/1158178/5449899/fc5cfe6e-8505-11e4-8cfa-1ed26366d633.png)

**Comment by Dogfalo** [comment]
If someone can confirm this issue I can reopen this.
