### ISSUE TITLE
Cannot click navbar dropdown items on IOS safari

### ISSUE THREAD

**Issue by zhaoyao91** [Dogfalo/materialize#2630]
Even I copy the code from the demo page into a simplest meteor app, I cannot click dropdown items on safari on my ipad.

```
<head>
  <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
  <meta name="viewport"
        content="width=device-width, initial-scale=1, minimum-scale=1, maximum-scale=1, user-scalable=no">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <title>test</title>
  <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
</head>

<body>
<!-- Dropdown Structure -->
<ul id="dropdown1" class="dropdown-content">
  <li><a href="#!" class="one">one</a></li>
  <li><a href="#!" class="one">two</a></li>
  <li class="divider"></li>
  <li><a href="#!" class="one">three</a></li>
</ul>
<nav>
  <div class="nav-wrapper">
    <a href="#!" class="brand-logo">Logo</a>
    <ul class="right">
      <li><a href="sass.html">Sass</a></li>
      <li><a href="badges.html">Components</a></li>
      <!-- Dropdown Trigger -->
      <li><a class="dropdown-button" href="#!" data-activates="dropdown1">Dropdown<i class="material-icons right">arrow_drop_down</i></a>
      </li>
    </ul>
  </div>
</nav>

<script>
  $(".dropdown-button").dropdown();
  $('.one').on('click', function () {alert('one')});
</script>
</body>
```

**Comment by zhaoyao91** [comment]
even worse, the normal dropdown items cannot be clicked either

    <head>
      <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
      <meta name="viewport"
            content="width=device-width, initial-scale=1, minimum-scale=1, maximum-scale=1, user-scalable=no">
      <meta http-equiv="X-UA-Compatible" content="IE=edge">
      <title>test</title>
      <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
    </head>
    
    <body>
    
    <ul id="dropdown1" class="dropdown-content">
      <li><a href="#!" class="one">one</a></li>
      <li><a href="#!" class="one">two</a></li>
      <li class="divider"></li>
      <li><a href="#!" class="one">three</a></li>
    </ul>
    <nav>
      <div class="nav-wrapper">
        <a href="#!" class="brand-logo">Logo</a>
        <ul class="right">
          <li><a href="sass.html">Sass</a></li>
          <li><a href="badges.html">Components</a></li>
          
          <li><a class="dropdown-button" href="#!" data-activates="dropdown1">Dropdown<i class="material-icons right">arrow_drop_down</i></a>
          </li>
        </ul>
      </div>
    </nav>
    
    
    <a class='dropdown-button btn' href='#' data-activates='dropdown2'>Drop Me!</a>
    
    <ul id='dropdown2' class='dropdown-content'>
      <li><a href="#!" class="two">one</a></li>
      <li><a href="#!" class="two">two</a></li>
      <li class="divider"></li>
      <li class="two"><a href="#!" >three</a></li>
    </ul>
    
    <script>
      $(".dropdown-button").dropdown();
      $('.one').on('click', function () {alert('one')});
      $('.two').on('click', function () {alert('two')});
    </script>
    </body>

**Comment by zhaoyao91** [comment]
I have created a PR to fix this. please review it.

**Comment by khachikyan** [comment]
I had the same issue; created an issue a while ago #2612

**Comment by zhaoyao91** [comment]
@khachikyan you can try my [PR](https://github.com/Dogfalo/materialize/pull/2632) to temporarily fix this.
just include this file to override.

**Comment by fega** [comment]
Closed due inactivity, feel free to reopen it if it is still necessary.
