### ISSUE TITLE
Ghost transformation of Select elements into ul li is very messy and causing major problems.

### ISSUE THREAD

**Issue by 9Dave9** [Dogfalo/materialize#2631]
Essentially the id's for the `option` elements become useless - as the li elements Materialize creates -  only take in the inner most HTML i.e text for the corresponding element it is trying to clone into an 

`<li><span>innermost text in my option element</span></li>`

For for example if my select options contain `<a href="some_id">category</a>`.. the anchor tag is stripped out! How do you make those options actual links without messing around with javascript?!

Any class and id on my option elements for my select is also stripped out so I have no way of finding out which option was selected in the original in case I want to trigger a link or content stripped out by materialize in my select options. At the very least the id and options should also be copied over to make manipulation with js so much easier.

Example.

``` html
   <select   id="catgeories_selection">
     <option id="option_id_1" value="1"><a href='#category1'>category 1</a></option>
     <option id="option_id_2" value="2"><a href='#category1'>category 2</a></option>
    ... etc etc etc
  </select>

Should be converted by materialize(if you insist on not just styling the actual select) to:
   <ul  id="catgeories_selection">
      <span id="option_id_1"><a href='#category1'>category 1</a></span>
      <span id="option_id_2"><a href='#category1'>category 1</a></span>
     ... etc etc etc
```
and finally you will still need a value for the input element you are using to display the option selected... and using the inner most html text of each option is fine.. But you really shouldn't remove any html or content for that matter from the options when creating your styled `<li>`.

**Comment by acburst** [comment]
This is really bad practice to be using a select as a dropdown navigation. You shouldn't have anchor tags within options. Why don't you just use our regular dropdowns to achieve this?

**Comment by 9Dave9** [comment]
What I am actually doing is replacing the Materialize tab headings with a select for mobile users. 
And since the 'value' of each original object is ignored when building the Materialize 'ul'. That information is being lost - so my next attempt at working around this was to add in an anchor tag. BUT  - I see now it's not just anchor tags - Materialize strips out any HTML tags inside the option tags if I am not mistaken.

Also I am know using the Materialize js function
'$('ul.tabs').tabs('select_tab', 'tab_id')' - which seems to do that  job. 

 `<option>` tags have values for a reason though - usually, standard practice is to add the numeric id of a certain object in the `value` field and the actual human readable `name` of said object in the option field i.e 

'<option value="referable_db_id">Human readable part</option>'
This is now impossible because the value is stripped - maybe add it to the `<li>` elements materialize creates as an `id`? 

I was trying to add the anchor tags because the 'value' was not being added to the <li>  tags.
All I really needed was have a `class` or `id` ` to reference so I could hide or display the correct tab.


This is a great lib btw - thanks a bunch(forgot to mention this above.)

**Comment by acburst** [comment]
If you are already using javascript why dont you just check the value of the select and select the tab that way? The html materialize constructs is just for visual effect which is why we stripped it down to the bare necessities. 

And thanks for saying, we appreciate that :) 
And also the styling for dropdown and select are pretty similar, no?

**Comment by TyrionGraphiste** [comment]
Hi, I fixed your issue in the version I'm currently working on. The values will not disappear but will write into each <li> element under the *data-value=value* form. Hope it should be good for you too.

When u're saying that Materialize strips out any HTML tags inside the option tags, this is a normal behavior because an option element cannot have any child elements, so yes it's not advisable to insert HTML into an option.

**Comment by 9Dave9** [comment]
I see.. Yeh I wasn't aware of the no child elements in an option tag being poor practice. Thanks for the heads up.

Ah that's awesome - Thank you!
