### ISSUE TITLE
hide tab container befor load complete

### ISSUE THREAD

**Issue by MetaiR** [Dogfalo/materialize#2633]
the content of tabs(which has not class="active") are shown when the page in load and will be hidden when load complete.
how can i do something that the content of my tabs are not shown before the load too?

**Comment by adriandj** [comment]
Eso es normal en mi opinion, ya que cargas el script de materialize al final, quizá si lo colocas en el head funcione correctamente, pero yo en especial, el contenido de mi tab principal es la que se carga al inicio, las demás son cargadas por ajax al hacer click en una Tab. Saludos
