### ISSUE TITLE
Button lighten on hover when default color is changed

### ISSUE THREAD

**Issue by brandonSc** [Dogfalo/materialize#2637]
If the default color is changed on a button, then the color no longer "lightens" on mouse hover. 

For example with this button, 

```
<a class="waves-effect waves-light btn-large">Button</a>
```

the color ligthens on hover. But after changing the color to red

```
<a class="waves-effect waves-light btn-large red">Button</a>
```

the button stays the same color on hover. 

It isn't obvious to me how to get that effect back for different button colors. Is it possible to have the buttons always "lighten" regardless of the background color?

**Comment by heneryville** [comment]
+1 
Perhaps the best way to do this is to add the hover effects inside the color classes themselves (Such as .red:hover ).

**Comment by fega** [comment]
@brandonSc did you resolve the problem?

Closed due inactivity, feel free to reopen it if it is still necessary.

**Comment by merkuriy** [comment]
This is an actual problem

**Comment by Boboss74** [comment]
I worked a little on it few months ago.
I got no more time now, maybe it could be helpful
