### ISSUE TITLE
datepicker not working with jQuery v2.2.0

### ISSUE THREAD

**Issue by clthck** [Dogfalo/materialize#2638]
When clicked on pickadated input element, datepicker is not triggered. I tried to find out what was causing this bug for a day and a half. Finally it turned out that I was using jQuery v2.2.0 and it's not compatible with jQuery v2.2.0. When I tried with jQuery v2.1.x, it worked fine.

This means jQuery v2.2.x or higher won't be available for me to use with materialize datepicker.
Can you fix this bug quick?

FYI, here's a codepen link:
http://codepen.io/clthck/pen/mVwRqM

**Comment by TyrionGraphiste** [comment]
Use the jQuery proposed with the framework.
The framework can't be responsible of all client modifications.

**Comment by clthck** [comment]
Ok, btw this is not a related thing with this issue, but I'm wondering why prefixers are commented out in the latest release.

**Comment by MiPnamic** [comment]
@TyrionGraphiste just a little note, installing Materialize with Bower there are no explicit version dependency so, on a clean install, it won't work out-of-the-box and you (as I've done) should manually downgrade jQuery to the version 2.1.3 for get it working

**Comment by TyrionGraphiste** [comment]
@MiPnamic Ok, thought a jQuery version was specified for each Materialize version, so just don't use jQuery 2.2, I didn't read the modifications list but surely there are changes that are incompatible with Materialize.

**Comment by clthck** [comment]
Yeah, I had to downgrade to 2.1.x. thanks guys.
