### ISSUE TITLE
<a> and <button> buttons are different

### ISSUE THREAD

**Issue by zhaoyao91** [Dogfalo/materialize#2640]
we can define button  by `<a>` or `<button>`, but some style is different.

due to [_form.scss](https://github.com/Dogfalo/materialize/blob/master/sass/components/_form.scss), line 5, `<button>` will be add a background color, which will show on `<button class="btn-flat">`, but that will not show on `<a class="btn-flat">`.

can you fix this or offer some guideline? thanks

**Comment by fega** [comment]
It looks solved in the current version
https://jsfiddle.net/Fega/m2v7yav1/
