### ISSUE TITLE
I need some mixins fo sass

### ISSUE THREAD

**Issue by rubenmedios** [Dogfalo/materialize#2641]
I search in google and can´t find sass mixins except this (http://materializecss.com/sass.html#mixins) and i need for the grid, buttons, etc...

Someone here have these mixins please? I need work a website with materialize and i like sass for web semantics for classes. Thanks in advance :)

**Comment by rubenmedios** [comment]
I search in google and can´t find sass mixins except this (http://materializecss.com/sass.html#mixins) and i need for the grid, buttons, etc...

Someone here have these mixins please? I need work a website with materialize and i like sass for web semantics for classes. Thanks in advance :)

**Comment by Dogfalo** [comment]
https://github.com/Dogfalo/materialize/blob/master/sass/components/_prefixer.scss

**Comment by rubenmedios** [comment]
Thank you very much @Dogfalo you are great!

**Comment by thebiltheory** [comment]
Hi @Dogfalo, 
in my materialize bower repo _prefixer.scss is all commented out. Any reason for that? What is the right way to import it/ uncomment it? 

Thanks in advance man! Outstanding Job on the framework!
