### ISSUE TITLE
Materialize for Meteor

### ISSUE THREAD

**Issue by atulmy** [Dogfalo/materialize#2643]
https://atmospherejs.com/materialize/materialize

The planettraining:material-design-icons-font package utilizes local icon pack instead of fetching from Google servers. Since the internet might be slow on mobile phones, its better to load local icon fonts.

I can see the font files here: /project/.meteor/local/build/programs/web.browser/packages/materialize_materialize/dist/font

How can I utilize these already present font files instead of using Google font CSS link?

**Comment by Dogfalo** [comment]
Whether it is google's servers or your own server it will still be from the internet. Mobile phones don't come with a local version of the icons.

**Comment by atulmy** [comment]
Can you check this: https://atmospherejs.com/planettraining/material-design-icons ? I installed this package and the CSS pointed to the local font file instead of google server and worked without active internet. I've also checked both Roboto and Material Icons font files are present in the materialize/materialize package but yet we reference it from google servers. Sorry to bother you though.

**Comment by Dogfalo** [comment]
The icon font we have bundled is not the same. If you want to use the one google provides offline, just download it.
