### ISSUE TITLE
SideNav won't close if the wrong half of a navbar-fixed is clicked v0.97.5

### ISSUE THREAD

**Issue by dharders** [Dogfalo/materialize#2645]
Great framework. Irritating issue:

In short, I have a Fixed Navbar with a SideNav inside (as specified in latest docs), see Plunkr here: https://plnkr.co/edit/PkEO7aVQvObHUbycVZIO?p=preview

When the sideNav is open, if I click on the wrong half of the navbar/header, the sideNav will NOT close. Clicking anywhere else will close the sideNav (including clicking the other half of the navbar/header). Try the demo above yourself!

If I remove the class "navbar-fixed" from the parent div, then all functions correctly...but I'm left without a fixed navbar....

**Comment by dharders** [comment]
There is an unofficial workaround here: http://codepen.io/anon/pen/XbZYPg

Essentially, they remove sideNav out of the nav element and modify the z-index. See issue #1664

It would be great to do this the official way if you could take a look. Otherwise, if you like the authors workaround of moving the sideNav/ul out of the nav element, maybe update the official docs?

**Comment by fega** [comment]
It looks solved in the current version
