### ISSUE TITLE
Timining: Materialize.toast VS Alert

### ISSUE THREAD

**Issue by gg4u** [Dogfalo/materialize#2646]
Hello,

How to trigger Materialize.toast immediately?

I have a chain of promises doing some work, user might wait some time and want to tell it.

I did a test on the first bit of execution, inserting alert('message') and Materialize.toast($toastContent, 3000);

I found that alert() is fired immediately, while Materialize.toat() will be only displayed after all the promises have been executed. 
I cannot figure out why and how to fix it.

I would prefer not to use modals, for I want to keep HTML structure separate from controllers and interaction wrapped in my library.

here my code:

```
function alertUser(message, time) {
  Materialize.toast(message, time);
};
```

```
function () {
return fetchMap(getUrl)
  .then(function(data){
   
    alertUser('Computing over  '+ data['nodes'].length +'  points', 3000);
    alert('Computing over  '+ data['nodes'].length +'  points'); // alert fires here: OK!
    $('body').('background','red') // test : CSS jquery fires here: OK!
    return data
  })
 .then() ...
 .then() ...
 .done() ... // Materialize display toast message here... USER gotta wait, NOT OK!
}
```

**Comment by MetaiR** [comment]
it's because of this matter that material.js must be load for using toasts
for you just one solution in my mind right now
"use page loaders" to load all of your page and then show the pages

**Comment by Dogfalo** [comment]
Alert will stop execution of code while ours does not. There is also around a 250ms time where the Toast animates in, this is why alert seems to fire first.
