### ISSUE TITLE
Scrollspy Compatibility

### ISSUE THREAD

**Issue by filipeskeeled** [Dogfalo/materialize#2647]
Your scrollspy plugin only supports jQuery 2.1.x as far as I've tried. jQuery 1.x is a no go, same with 2.2.x.
I would assume it was something specific to jQuery 2.1.x.

Technically, the bug resides in the linking, that jQuery does not recognize how you through the linking at it - a[href=#step] - in any other version that not 2.1.x so maybe something they changed only there, and then reverted the change on 2.2.x.

**Comment by pdonorio** [comment]
+1

I see there is a commit for this fix, would this be available in the next release?
Thank you a lot

**Comment by Dogfalo** [comment]
Yes it will be.
