### ISSUE TITLE
can't pre select multiple options 

### ISSUE THREAD

**Issue by venturion** [Dogfalo/materialize#2652]
#### i can't pre select multiple options in a multiple select

example:
```html
 <div class="input-field col s12">
    <select multiple>
      <option value="1" selected>Option 1</option>
      <option value="2" selected>Option 2</option>
      <option value="3" selected>Option 3</option>
    </select>
    <label>Materialize Select</label>
  </div>
```

**Comment by dgadelha** [comment]
This issue still affects me.

**Comment by fega** [comment]
@dgadelha 
Please provide a way to reproduce it to see what's happening. like a [codepen](https://codepen.io/fega/pen/BWeZaG)

**Comment by dgadelha** [comment]
My bad, didn't notice that when dynamically adding items you must call `$("select").material_select("update");`

**Comment by bspatil0001** [comment]
$("select").material_select("update"); not making any difference. When i initialise pre-selected data, It is showing undefined and no options are selected. If any one has found solution share it. Thank you.
