### ISSUE TITLE
SVG on your site is not showing

### ISSUE THREAD

**Issue by tmd-uk** [Dogfalo/materialize#2653]
@acburst @Dogfalo There is an issue with your site, the SVG image is not showing and is issuing 2 errors in chrome dev tools. Not sure if you have noticed this at all?

![untitled-1](https://cloud.githubusercontent.com/assets/7654330/12308647/4f17986c-ba3e-11e5-9231-271aec015630.jpg)

**Comment by chifreaigle** [comment]
How to reproduce ?
