### ISSUE TITLE
distinction between modal close events in "complete" callback

### ISSUE THREAD

**Issue by pierrekraemer** [Dogfalo/materialize#2656]
Is it possible, in the "complete" callback of a modal, to make the distinction between different events that could lead to the event ?
If the modal is dismissible, is there a way to know if the callback is called because the modal has been dismissed or because a modal-close button was triggered ?
If there are multiple modal-close buttons, is there a way to know which button was triggered ? For example, in the doc, some example modals have an "Agree" and a "Disagree" button. Is there a way to pass something into the "complete" callback to make the distinction between the different cases ?

**Comment by lisatassone** [comment]
It would be better with the addition of an onApprove function that can be applied to the action button leaving the closing functionality separate.

**Comment by odelbos** [comment]
Yes, it's possible, I found it reading the source code of `model.js`.
You have to register a listener to your 'Agree' and 'Disagree' buttons or href waiting for the event : 'click.close'.

```javascript
$('#agree').on('click.close', function (e) {
  console.log('click agree');
  // Do stuff ...
});

$('#disagree').on('click.close', function (e) {
  console.log('click disagree');
  // Do stuff ...
});
```

```html
<div class="modal-footer">
  <a id="#agree" href="#!" class="modal-action modal-close waves-effect waves-green btn-flat">Agree</a>
  <a id="#disagree" href="#!" class="modal-action modal-close waves-effect waves-green btn-flat">Disagree</a>
</div>
```
