### ISSUE TITLE
Cannot destroy sideNav

### ISSUE THREAD

**Issue by zhaoyao91** [Dogfalo/materialize#2657]
you can init a sideNav, but you cannot destroy it. if you init several times, there will be a lot of `drag-target` on the body...

**Comment by Thanood** [comment]
This also seems to affect f.i. DropDown. That or I just couldn't find the destroy handler. :smile: 
When dealing with dynamically added elements, this could become an issue.

**Comment by makeros** [comment]
Hi.
I think that this should solve the problem https://github.com/Dogfalo/materialize/pull/2847
Just trying to make it usable for my webapp.

**Comment by tomscholz** [comment]
Merged https://github.com/Dogfalo/materialize/pull/3419
