### ISSUE TITLE
Bug: use collapsible in sidenav

### ISSUE THREAD

**Issue by MetaiR** [Dogfalo/materialize#2663]
hi,
when we are useing collapsible in sidenav (like your example in you general site for make dropdown in sidenav) the padding and margin of dropdown li is not like other ones

**Comment by mister009** [comment]
I think I might have the same issue. 

Do you refer to this? 
![bug](https://cloud.githubusercontent.com/assets/3356942/12370036/bf985a5a-bbc8-11e5-8551-0f5bef3bbd4d.png)

**Comment by MetaiR** [comment]
no my problem is about height
i will put a picture of it
![2](https://cloud.githubusercontent.com/assets/7807264/12373648/532fd960-bc95-11e5-9200-b3453e7b98d1.png)
![untitled](https://cloud.githubusercontent.com/assets/7807264/12373649/5331a98e-bc95-11e5-92ff-9509f174ad8a.png)

**Comment by fega** [comment]
Closed due inactivity, feel free to reopen it if it is still necessary.
