### ISSUE TITLE
HTML5 range indicator not disappearing

### ISSUE THREAD

**Issue by SHAD0WF4X** [Dogfalo/materialize#2671]
The green indicator boble is not disappearing.

User agent string: Mozilla/5.0 (Windows NT 10.0; WOW64; rv:43.0) Gecko/20100101 Firefox/43.0

I used this example http://materializecss.com/forms.html#range

Chrome seems to be working fine.

**Comment by jeromemiranda** [comment]
How come this issue was closed but not yet fixed. I'm also having the same issue using firefox.

![screenshot from 2016-01-29 08 26 23](https://cloud.githubusercontent.com/assets/10937400/12663351/7bf68a98-c662-11e5-8d4e-c1d3504cd463.png)

**Comment by SHAD0WF4X** [comment]
This is already an issue
