### ISSUE TITLE
range scroll ball error

### ISSUE THREAD

**Issue by venturion** [Dogfalo/materialize#2675]
## when you set step attribute in the range, thumb balloon doesn't follow the range ball

example:

``` html
<input type="range" name="points" min="0" max="100" class="active" step="40">
```

![range-error](https://cloud.githubusercontent.com/assets/3776794/12404104/f25d4fe6-be1f-11e5-9dcd-082de7268077.png)

**Comment by DanielRuf** [comment]
Can not reproduce it with the latest release.

**Comment by etatus** [comment]
Something similar occurs when you set a range from negative to positive values.

`      <input type="range" id="test5" min="-10" max="10" />`

**Comment by DanielRuf** [comment]
Please test the master branch, also see https://github.com/Dogfalo/materialize/pull/4466

**Comment by fega** [comment]
Closed due inactivity, feel free to reopen it if it is still necessary.
