### ISSUE TITLE
List of needed jQuery modules?

### ISSUE THREAD

**Issue by Ahmed-90** [Dogfalo/materialize#2679]
So i would like to optimize my scripts... am using vue.js for my front end so i don't really need jQuery.. i have it only for materialize..

is there a list of needed [modules](https://github.com/jquery/jquery#modules) somewhere ? so i can build a custom/smaller jquery file? 

Thanks

**Comment by PDXIII** [comment]
Hi! I am not a core member, but usually you can inspect the dependencies in the [bower.json](https://github.com/Dogfalo/materialize/blob/master/bower.json).

**Comment by Ahmed-90** [comment]
Hi,.. thanks but the only thing about jquery is this:
```json
 "dependencies": {
    "jquery": ">=2.1.1"
  },
```

**Comment by PDXIII** [comment]
Maybe jQuery is the only dependency

**Comment by Thanood** [comment]
I think at least the npm-version (or "source" version) depends on hammerjs and Velocity, but not quite sure.

**Comment by Ahmed-90** [comment]
my point is.. i don't need the whole jQuery lib.. jQuery supports custom builds(for smaller .js file and optimized code) which is exactly what i want to know.. which jQuery modules are used by Materialize ? so i can build my own little jQuery file

**Comment by PDXIII** [comment]
I see! You would like to know what features depend on jQuery! 

When I understand it right, they use jQuery for selecting DOM elements. So, if you use any JavaScript feature from Materialize you'll need jQuery. 

For me it seems like, you’ll need to rewrite the features you'll like to use, if you like to drop jQuery.

**Comment by Ahmed-90** [comment]
@PDXIII 
actually its the other way around xD  
do you know that you can tear down jQuery itself ? so instead of rewriting materializecss scripts i just rebuild jQuery with the needed modules

**Comment by PDXIII** [comment]
@Ahmed-90
Aww! Like they use just jQuery.addClass and .removeClass you'll go to jQuery.com and just compile these two plugins into a custom library.

**Comment by Ahmed-90** [comment]
@PDXIII yeah kind of check this https://github.com/jquery/jquery#modules

**Comment by PDXIII** [comment]
Thank you very much! You showed something to me I wasn't aware of. 

Sorry, I couldn't help you with your problem!

**Comment by PDXIII** [comment]
Maybe, a real dirty method I would try, when I am bored from waiting on any response:

1. Open the materialize.js in Atom or Sublime Text. 
2. Select '$.('
3. Expand selection to multiple selection with **cmd + d** till you don't find any more '$('
4. Try to expand selection after the module, like '$("CSSselector").jQueryModule'
5. Then copy & paste into a new file.
6. Take a look, maybe you’love find what you were looking for.

It's dirty, and maybe you want to wash yourself after you've done that, but you could give it a try!

**Comment by Ahmed-90** [comment]
@PDXIII hehehe am not that desperate :smile: 
am sure the devs have something on this and if thy don't then its a suggestion not everyone uses jQuery these days :older_man:

**Comment by coffenbacher** [comment]
A good answer to this would be great. jQuery is pretty heavy if it's not being used for anything more than selectors. We don't use it for anything else so it's a little unfortunate that Materialize has a dependency on it. Minimizing that negative impact is important for us.

**Comment by chifreaigle** [comment]
@Dogfalo Got anything on this ?

**Comment by Dogfalo** [comment]
We are going to try to migrate away from jQuery slowly with each release. To see what modules are used, try using a regex search like this `\$\('(.[^']*)\'\).(.[^(]*)` to find the module names
