### ISSUE TITLE
carousel not working correctly in tabs

### ISSUE THREAD

**Issue by Funtrax** [Dogfalo/materialize#2680]
When a carousel is in a tab the carousel not work correctly until u click on the carousel-div than it fixes by itself. If the tab is marked as active and u reload the page everyting is fine ... do someone have an idea how to fix this?

**Comment by acburst** [comment]
Added in 1a7182b

I've added an onShow callback for tabs. Here is an example of how you can fix your problem:
```
$('ul.tabs').tabs({
  onShow: function(tab) {
    $('.carousel').carousel();
  }
});
```

**Comment by KForKevin** [comment]
It is not working now. If a carousel is included in tabs, it would automatically swiped back to the first tab when trying to go to the second tab.
