### ISSUE TITLE
select don't have blur event?

### ISSUE THREAD

**Issue by venturion** [Dogfalo/materialize#2682]
The select input don't have blur event?

**Comment by TyrionGraphiste** [comment]
Yes it has.

**Comment by venturion** [comment]
i can't trigger it using jquery

**Comment by chifreaigle** [comment]
We need a better documentation on Materialize js things, a reworked one with more details .

**Comment by Birssan** [comment]
Same problem here.
If you don't use the `browser_default` class, the blur event isn't triggered.
