### ISSUE TITLE
Waves effect on disabled buttons

### ISSUE THREAD

**Issue by fjsuarez** [Dogfalo/materialize#2683]
Here is a code pen replicating the issue.
http://codepen.io/fjsuarez/pen/mVpEge

You can see that by adding the `disabled` class to an `<a>` element, the button still responds to clicks and generates waves.

I'm aware of issue #947, but I'm not sure if it's the same issue since there is no code example in that issue.

My current workaround is adding attribute `disabled` and having a CSS rule for elements with such attribute `pointer-events: none;`

**Comment by chifreaigle** [comment]
+1 , disabled btns mustn't have waves

**Comment by wemyss** [comment]
this is fixed in the latest commit no?
https://github.com/Dogfalo/materialize/commit/f2ac62e246099e4d96e3aef1f81830db62976b41

**Comment by chifreaigle** [comment]
@wemyss Yes it's fixed, Time to close this issue @fjsuarez  :D
