### ISSUE TITLE
Long list of dropdown options become non-selectable. 

### ISSUE THREAD

**Issue by Beck89** [Dogfalo/materialize#2685]
If the amount of options in a dropdown are enough to make the list scrollable then the options near the bottom are not selectable. When you click the option the dropdown goes away but the value does not update. 

Here is a demo video of the issue. Notice how I am unable to select Washington

Video: http://beck.lt/16q47

**Comment by chifreaigle** [comment]
+1

**Comment by dbnoble** [comment]
@Beck89 have you tried setting a max-height on the container so that it doesn't go all the way to the bottom of the page before starting to scroll? I haven't experienced this.

Still should be fixed anyway of course.

**Comment by Beck89** [comment]
@dbnoble I don't think that would make a difference. 

The issue arises when the option list height is restricted by the bottom frame of your browser. I attached a my demo files if you're interested in checking it out. 

Demo: http://beck.lt/Nkp0

**Comment by acburst** [comment]
This was fixed in some select commits.
