### ISSUE TITLE
Label effect with active css class doesn't work when I use ng-transclude in input element.

### ISSUE THREAD

**Issue by fabioviana** [Dogfalo/materialize#2686]
In my project I have a directive that use ng-transclude element with replace and this case the final html structure is:

< div class="input-field" >
< ng-transclude > < input ... > < / ng-transclude >
< label ... > ... < / label >
< / div >

The js selector to apply the class "active" is fixed:
$(this).siblings('label, i')...

Can I create a fork to apply a plugin, like this:
Materialize.findLabel = function (element, selector) {
   return $(element).siblings(selector);
};

... use:
Materialize.findLabel(this, 'label, i').addClass('active');
...
Materialize.findLabel(this, 'label, i').removeClass('active');

---- in my project I going to customize the function "findLabel" to:
Materialize.findLabel = function (element, selector) {
   return $(element).parent().find(selector);
};

In my project this fix solve all situations.

**Comment by fabioviana** [comment]
HTML structure:
< div class="input-field" >
< ng-transclude > < input ... > < / ng-transclude >
< label ... > ... < / label >
< / div >

**Comment by fabioviana** [comment]
The css to apply color is wrong too, for example:

input[type=text]:focus:not([readonly]) + label, 
... {
  color: #26a69a;
}

I don't know how solve this...

**Comment by redbmk** [comment]
I'm not extremely familiar with angular, but according to [the docs](https://docs.angularjs.org/api/ng/directive/ngTransclude) it looks like you might be able to do `<input ng-transclude />` instead of `<ng-transclude><input /></ng-transclude>`. I think that would solve the problem if it works for whatever `ng-transclude` does.

**Comment by fabioviana** [comment]
I know with to use ng-transclude, the problem with ng-transclude is that it creates an element that the Materializecss doesn't work. Materializecss needs that the input is siblings of label, but ng-transclude doesn't do this. If Materializecss wants to work together with ng-transclude it will change the js selector and css class, maybe as I explained previously.

**Comment by redbmk** [comment]
Maybe the javascript could put "active" and "hover" classes on the `div` with "input-field", but that seems less efficient. Is there a way to get the final html structure to look more like the following?

```
<div class="input-field">
  <ng-transclude>
    <input ...>
    <label ...> ... </label>
  </ng-transclude>
</div>
```

Do you have some sample code you can show on something like plnkr or jsfiddle?

**Comment by fega** [comment]
Closed due inactivity, feel free to reopen it if it is still necessary.
in that case, please provide a way to reproduce it. like a [codepen](https://codepen.io/fega/pen/BWeZaG)
