### ISSUE TITLE
Input type time won't animate the label correctly.

### ISSUE THREAD

**Issue by muroshi** [Dogfalo/materialize#2687]
As written above.

**Comment by dani14-96** [comment]
Same for types "date", "datetime-local", "time" and "week".
![captura de pantalla 2016-09-01 a las 17 48 48](https://cloud.githubusercontent.com/assets/10668217/18174084/7c153524-706c-11e6-822b-338278c6088a.png)

**Comment by maxmumford** [comment]
As a temporary workaround add the "active" class to the label and it'll at least not block the user's view of the input.

**Comment by dani14-96** [comment]
I experimented a bit and added the following code to style.css as a workaround:

`.input-time label{
    font-size: 0.8rem;
    -webkit-transform: translateY(-140%);
     transform: translateY(-140%);
}`

which is the same css code that for `.input-field label.active{}`

So basically the same that adding "active" class

**Comment by serhathalil** [comment]
hi dani, 

i add style.css which codes, but not working.

.input-time label{ font-size: 0.8rem; -webkit-transform: translateY(-140%); transform: translateY(-140%); }
