### ISSUE TITLE
datepicker is not working with jquery v2.2.0

### ISSUE THREAD

**Issue by kamrankr** [Dogfalo/materialize#2688]

**Comment by samrm111** [comment]
+1

**Comment by niwasmala** [comment]
+1

This is annoying when you don't know what could be wrong, just doing bower update and voila, datepicker not working anymore. Currently I'm using jquery v2.1.4 so datepicker still works.

**Comment by throrin19** [comment]
+1, I test with the official pickadate library and it works fine but i have not the materialize theme :(

**Comment by vhaarr** [comment]
+1

Good thing I had the wits to check the issue tracker on github or I would have gone crazy trying to find the problem.

Would be nice if materializecss updated to at least pickadate.js 3.5.5 regardless, so that we get the "closeOnSelect" option.

**Comment by Dogfalo** [comment]
Fixed by #2889
