### ISSUE TITLE
Webpack/React Install

### ISSUE THREAD

**Issue by gazzer82** [Dogfalo/materialize#2690]
So, I have been trying for several hours to get this to work properly with webpack for a react project. If I include the JS either via requiring directly to the materialize.js file or by importing the framework I get the following error during compile. Anyone got any ideas how to fix this. 

It all seems to load fine and the JavaScript functions and CSS stuff all works properly, but I would really like to make this error go away. 

```
WARNING in ./~/jquery/dist/jquery.js
There is another module with an equal name when case is ignored.
This can lead to unexpected behavior when compiling on a filesystem with other case-semantic.
Rename module if multiple modules are expected or use equal casing if one module is expected.

WARNING in ./~/jQuery/dist/jquery.js
There is another module with an equal name when case is ignored.
This can lead to unexpected behavior when compiling on a filesystem with other case-semantic.
Rename module if multiple modules are expected or use equal casing if one module is expecked.
```

Thanks

Gareth

**Comment by gazzer82** [comment]
Ok, so this is fixed by change the following at the top of the materialise.js file:

```
jQuery = $ = require('jquery');
```

**Comment by neo01124** [comment]
similar thing here https://github.com/Dogfalo/materialize/issues/2681

but awaiting devs' reply

**Comment by gazzer82** [comment]
Ah yes, well i've submitted a pull request, but seeing the length of the queue, i think it might take a while . . .

**Comment by pistou** [comment]
I solved this error **without having to edit materialize-css bin file**.
In your `webpack.config.js`, simply add the following rule:

```
module.exports = {
    // ...
    resolve: {
        alias: {
            jQuery: "path/to/jquery/dist/jquery"
        }
    }
    // ...
};
```

**Comment by neo01124** [comment]
above solution works for me, thanks @pistou

**Comment by antoinejaussoin** [comment]
@pistou 's solution works like a charm. Merci beaucoup !
