### ISSUE TITLE
data-error input same lenght than label

### ISSUE THREAD

**Issue by nalmada** [Dogfalo/materialize#2691]
Hi,

I see that data-error message can only be the same lenght as the label, before it go to newline : ![capture](https://cloud.githubusercontent.com/assets/10788696/12511314/b91e777a-c110-11e5-985c-53f775e22fb8.PNG)
Can you change this please?

Code example : 

```html
<div class="row">
    <form class="col s12">
      <div class="row">
        <div class="input-field col s12">
          <input id="email" type="email" class="validate">
          <label for="email" data-error="this input is def. wrong bro" data-success="right">Email </label>
        </div>
      </div>
    </form>
  </div>
```

Thanks (it's a TP)

**Comment by Dogfalo** [comment]
This is fixed already.

**Comment by Dogfalo** [comment]
For next release
