### ISSUE TITLE
$(...).carousel is not a function

### ISSUE THREAD

**Issue by khlJunior** [Dogfalo/materialize#2692]
Hey Guys. I have a website, everything is working fine, i have jquery and materialize js working.

When i call the method $('.carousel').carousel(); like in the example, the carousel does not work.
In console.log i have this error Uncaught TypeError: $(...).carousel is not a function.

I removed all another jquery plugins, everything and didn't worked.
 Any idea ?

Materialize version is 0.97.5. I 've updated the materialize and nothing.

**Comment by Dogfalo** [comment]
Maybe you forgot the period before carousel?

**Comment by khlJunior** [comment]
Sorry Dogfalo, i'm from Brazil, my english is very bad.
I can't understand what u said. 

(I've made a copy of this file and tried using another plugin for carousel, worked but i loved materialize's carousel. I want to use materialize's solution. :+1: )

**Comment by Dogfalo** [comment]
Make sure you add jQuery first before materialize

**Comment by khlJunior** [comment]
I'm sure about this, in order  i load Jquery, Materialize and after in a document ready function i call the carousel. I tried moving the carousel call to the end of the page but same issue.

I can start Navbar,materialbox for images, only carousel is now working.

**Comment by SouzaMarcos** [comment]
Do you use the materialize.min.js with all functions?
Copy and paste the import in head of html document.

**Comment by Dogfalo** [comment]
I can confirm that the carousel function does exist as I can call it in the Materialize documentation page. This seems like it is a JS issue on your end.

**Comment by kartboy16** [comment]
Figured it out.  Make sure you are on version 0.97.5.  I took a look inside 0.97.3 and the carousel was nowhere to be found.  

When I tried to run update, it wouldn't let me update either so I had to remove and add materialize again.  

Hope this helps!

**Comment by baoxiehao** [comment]
I got the same problem with phoenix.

<html>
  ...
  <body>

    <div class="container">
      <main role="main">
        <%= render @view_module, @view_template, assigns %>
      </main>
    </div>

    
    <script type="text/javascript" src="https://code.jquery.com/jquery-2.1.1.min.js"></script>
    <script src="<%= static_path(@conn, "/js/app.js") %>"></script>
    <script type="text/javascript">
      $(document).ready(function(){
        console.log("carousel...")
        $('.carousel').carousel();
      });
    </script>
    </script>
  </body>
</html>

output:

gallery:52 Uncaught TypeError: $(...).carousel is not a function(anonymous function) @ gallery:52j @ jquery-2.1.1.min.js:2fireWith @ jquery-2.1.1.min.js:2ready @ jquery-2.1.1.min.js:2I @ jquery-2.1.1.min.js:2
(program):5 Uncaught TypeError: Cannot read property 'removeAttribute' of null(anonymous function) @ (program):5(anonymous function) @ (program):20

**Comment by Rim-777** [comment]
I've got the same issue in a Rails project.  I use gem 'materialize-sass'  
I would be very happy if somebody help me to figure out how can I solve it.

**Comment by Dogfalo** [comment]
@Rim-777 you most likely are including jquery after materialize where it should be the other way around

**Comment by Rim-777** [comment]
this is my assets/application.js:
`

- //= require jquery
- //= require materialize-sprockets
- //= require jquery_ujs
- //= require jquery-ui
- //= require jquery.ui.autocomplete.scroll.min.js
- //= require tag-it
- //= require jquery.remotipart
- //= require jquery.canvasCrop.js
- //= require jquery-fileupload/basic
- //= require jquery.magnific-popup.min.js
- //= require cocoon
- //= require twitter/typeahead.min
- //= require cloudinary
- //= require sortablejs
- //= require_tree .

`

**Comment by ItsYanko** [comment]
> Make sure you add jQuery first before materialize
> On Jan 22, 2016 8:48 AM, "Junior Machado" [notifications@github.com](mailto:notifications@github.com) wrote:
> 
> > Sorry Dogfalo, i'm from Brazil, my english is very bad.
> > I can't understand what u said.
> > (I've made a copy of this file and tried using another plugin for
> > carousel, worked but i loved materialize's carousel. I want to use
> > materialize's solution. [image: 👍] )
> > —
> > Reply to this email directly or view it on GitHub
> > [#2692 (comment)](https://github.com/Dogfalo/materialize/issues/2692#issuecomment-173974100)
> > .

this did the trick for me. thanks
