### ISSUE TITLE
How to Make Btm SHeet Full Height and Side Nav Modal Full Width?

### ISSUE THREAD

**Issue by masterpowers** [Dogfalo/materialize#2698]
My Balls is Twisted Looking for something to alter the behavior of modal
but it always get me the behaviour i dont want...
Hope someone can Share me a Way how to Enable this 2 Things i wanted

Coz i wanted to Have a Side Nav Full Width or Btm Sheet Full Height Like Facebook

THanks For Help

**Comment by Dogfalo** [comment]
You can change max-height on bottom sheet and the menuWidth option on sidenav

**Comment by zenkkor** [comment]
Hey @Dogfalo 

I tried setting 

```
 max-height: 100% !important;
 top: 25px !important;
```

And it works perf size-wise, but now that beautiful slide up effect is gone. Any way clue of I can keep that nice effect of sliding up and have it full height?

Thanks!

**Comment by Dogfalo** [comment]
Not currently, we would have to change the javascript to support it for that to work

**Comment by zenkkor** [comment]
Ok cool, i'll hack something together myself. 👨‍💻 

Thanks for the answer,
Rok
