### ISSUE TITLE
Vertical align (with valign-wrapper and valign) is not working

### ISSUE THREAD

**Issue by mjbshaw** [Dogfalo/materialize#2700]
Vertical alignment does not seem to be working. See the following screenshot of the demo page:

![Vertical align does not work](https://cloud.githubusercontent.com/assets/1204698/12531997/41c5e0d4-c1bd-11e5-9648-0ac508f4b021.png)

Screenshot is from Safari Version 9.0.2 (11601.3.9). I've also tried Chrome and Firefox and I get the same results in both of them.

**Comment by guptamo** [comment]
I'm having the same issue with the following code
```html
<div class="valign-wrapper col s12 m6">
                        <h2 class="black-text valign">Experienced Chiropractor and Registered Massage Therapists in Blackburn Hamlet</h2>
                    </div>
```

**Comment by boyriot** [comment]
anyone know how to fix?

**Comment by brgrz** [comment]
Vertical align with valign-wrapper works fine for me.

The thing that's not working is container within valign-wrapper - the container width gets distorted in some way.

**Comment by brgrz** [comment]
When I have container within valign-wrapper aligned element, the container width is not as it should be (e.g. 70%, 80 or 90%) but a bit less like 10-20px less.

**Comment by ktamiola** [comment]
I can reproduce this problem too!

**Comment by JosePaniagua** [comment]
esta es mi solucion de ejemplo para un login espero les sirva

**Comment by JosePaniagua** [comment]
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
	xmlns:h="http://java.sun.com/jsf/html"
	xmlns:p="http://primefaces.org/ui">
<h:head>
	<title>Login</title>
	<meta name="viewport"
		content="width=device-width, initial-scale=1, maximum-scale=1.0" />
	<link href="https://fonts.googleapis.com/icon?family=Material+Icons"
		rel="stylesheet" />
	
	<h:outputStylesheet name="css/materialize.css" />
</h:head>
<h:body styleClass="white">

	<div class="valign-wrapper" id="login-page">
		<div class="container">
			<div class="center-align">
				<div class="row">
					<div class="col s0 m4 l4" />
					<div class="col s12 m4 l4">
						<div class="card">
							<div class="card-content">
								<img class="responsive-img"
									src="http://idsoft.com.ar/javax.faces.resource/div.png.xhtml?ln=img"
									style="max-width: 64px;" />
								<div class="left-align">
									<h:form id="form-login">
										<p:growl autoUpdate="true" />
										<div class="row">
											<div class="col s12 input-field">
												<h:inputText id="username" value="#{login.username}"
													required="true" requiredMessage="User required" />
												<h:outputLabel for="username" value="User" />
											</div>
											<div class="col s12 input-field">
												<h:inputSecret id="password" required="true"
													value="#{login.password}"
													requiredMessage="Password required!" />
												<h:outputLabel for="password" value="Password" />
											</div>
											<div class="col s12 input-field">
												<h:commandLink value="Go!" styleClass="btn btn-large"
													actionListener="#{login.access()}" />
											</div>
										</div>
									</h:form>
								</div>
							</div>
						</div>
					</div>
					<div class="col s0 m4 l4" />
				</div>
			</div>
		</div>
	</div>
	<h:outputScript name="js/jquery.js" />
	<h:outputScript name="js/materialize.js" />
	<script>
            $(document).on("ready",function(){
                $('#login-page').css({'height': window.innerHeight + 'px'});
            });
        </script>
</h:body>
</html>

**Comment by andikahmadr7** [comment]
u might put `valign-wrapper` within `row` class instead put them in `row` 's parent class

**Comment by hgsadhrakiya** [comment]
Here is the solution:
Give this CSS to the div which you have to centralize..
```
.class-name {
        margin: 0px;
	padding:0px;
	float: left;
	width:100%;
	position:absolute;
	top: 50%;
	transform: translateY(-50%) translateX(-50%);
	left:50%;
}
```

**Comment by Dogfalo** [comment]
The screenshot you posted looks vertically centered. valign is also meant to work in localized places so if you place a large number elements inside it, you may break your layout.

**Comment by sarfaraz72** [comment]
As the valign-wrapper uses flex. So, the minimum solution is to make it a block in mobile.

@media screen and (max-width:768px){
  .valign-wrapper {
    display: inline-block;}
}
