### ISSUE TITLE
Wrong positioning with position relative

### ISSUE THREAD

**Issue by fragsalat** [Dogfalo/materialize#2702]
Hi.

I wanted to use the dropdown like in the docu. But the positioning is wrong.
The html structure is the following.

```
<div class="row">
        <div class="col s12 m6 l4">
            <div class="card">
                <div class="card-image">
                </div>
                <div class="card-action">
                    <div class="buttons">
                        <span class="dropdown-button icon-ellipsis-v" data-activates="menu-7"></span>
                        <ul class="dropdown-content" id="menu-7">
                           ...
                        </ul>
                    </div>
                </div>
            </div>
        </div>    
    </div>
</div>
```

The dropdown should be placed beside dropdown-button but it is miles away.
1. It's placing the content everytime beside the button so the overflow hidden of the .card makes it impossible to see the content.
2. The position relative of the .card is killing the absolute position calculation of the dropdown.

Any suggestions???
Regards

**Comment by fega** [comment]
Please provide a way to reproduce it. like a [codepen](https://codepen.io/fega/pen/BWeZaG)

Closed due inactivity, feel free to reopen it if it is still necessary.
