### ISSUE TITLE
rerender select

### ISSUE THREAD

**Issue by sebyx07** [Dogfalo/materialize#2705]
i just want to add a css class to select when it updates, but i have to call rerender every time. is there a better method?

``` js
_reRender: function(){
    this.$().material_select('destroy');
    this.$().material_select();
 }
```

**Comment by TyrionGraphiste** [comment]
For the moment there is no other way.

**Comment by sebyx07** [comment]
i also have problem with inputs type text. the placeholder is over the input value. i have a SPA with ember. what should i trigger on the input to render correctly?

**Comment by TyrionGraphiste** [comment]
You should add the active class to your input if he gets a value pre-filled.
