### ISSUE TITLE
material_select('destroy') doesn't work on a child of a cloned element.

### ISSUE THREAD

**Issue by spencer4of6** [Dogfalo/materialize#2711]
When trying to destroy a select that is a child of a cloned element, the generated elements don't go away.

[Here's a link](https://jsfiddle.net/spencer4of6/3yun3kxq/14/) to an example.

And here's the code in case the link doesn't work:

``` html
<div class='wrapper-div'>
  <select>
    <option value=1>Option 1</option>
    <option value=2>Option 2</option>
  </select>
</div>

<button class='btn' id='copy'>
  Copy this
</button>
```

``` js

$(function() {
  $('select').material_select();

  $('#copy').click(function() {
    var $newSelect = $('.wrapper-div').clone();
    $('body').append($newSelect);
    $newSelect.find('select').material_select('destroy');
  });
});
```

It looks like this after `material_select('destroy')` is run on the second element:

![capture](https://cloud.githubusercontent.com/assets/8053224/12623592/1fc0f4be-c4e8-11e5-9a3e-bc7234b11e84.PNG)

**Comment by lvandyk** [comment]
Also had the same issue trying to dynamically add selects with a "+" button and letting jquery using a select tag as a template (which actually got material_selected() on body ready). What I had to do is move the template into a very long javascript string variable.

**Comment by fega** [comment]
You have two problems, 1 when you call `$('select').material_select();`  materialize destroys the select and creates an input instead, so you cannot simply clone the result.

Also `newSelect.find('select').material_select('destroy');` simply didn't found the select.
