### ISSUE TITLE
Long content is hidden in card reveal

### ISSUE THREAD

**Issue by bui** [Dogfalo/materialize#2716]
**Fiddle**: https://jsfiddle.net/3rhf4h3a/

I want to use a `.card-action` element with my `.card-reveal` card so that the actions appear even after the reveal. The code in the above fiddle works OK, but as you can see the last of the content & scrollbar is hidden underneath the `.card-action`.

Could this be fixed at all?

**Comment by robertofabrizi** [comment]
Well if you add <p>empty p</p> after your true final one, it does what you want.
I guess as a workaround you can use say jquery to add an extra "empty" p, or something like that.

**Comment by bui** [comment]
Sure, but that doesn't do anything about the scrollbar. Fiddling around with the `.card-reveal`'s height and margin sort of fixes it, but it's very dirty and inconsistent.

**Comment by acburst** [comment]
Added in 5b75e62. We now support both options with card-reveal. The docs won't be updated on our website until we release but you can git pull and see the docs locally.

But basically, if you place the card-reveal directly after the card-actions div your card-actions will always be visible. If you place them anywhere else, the card-reveal will cover your card-actions.

**Comment by bui** [comment]
Thanks! The end of the scrollbar is still hidden though, are you aware @acburst?
https://jsfiddle.net/pwrbgtej/
