### ISSUE TITLE
Select doesn't work well with Datatables, starting from version 0.96

### ISSUE THREAD

**Issue by robertofabrizi** [Dogfalo/materialize#2717]
As the title says, you can see from this fiddle http://jsfiddle.net/ebRXw/1323/ that when I select how many rows to show, the select doesn't close itself after i click a choise, but re-opens itself right away.
This doesn't happen with an older version of materializecss, for example 0.95.2: http://jsfiddle.net/ebRXw/1324/

**Comment by robertofabrizi** [comment]
Dear friends, has anyone managed to find a workaround for this issue?
Thank you,
Roberto

**Comment by robertofabrizi** [comment]
Is there any news on this subject?
Cheers,
Roberto

**Comment by robertofabrizi** [comment]
Anyone else having this issue?
Cheers,
Roberto

**Comment by smoreno91** [comment]
I have the same issue. Did you found any solution?

**Comment by larnacoeur** [comment]
Same here. Is there any solution to this ?

**Comment by nikhilmathew** [comment]
I got the same problem as well, i have other select on the same page but they are working perfectly fine, only the select belonging to the Data Tables is showing this bug. 
Is there a solution?

**Comment by larnacoeur** [comment]
I made it work in very dirty way.. I'm currently detaching whole UL from DOM and attaching it again after 200ms. Something like this:
```javascript
$("select")
        .change(function() {
            var t = this;
            var content = $(this).siblings('ul').detach();
            setTimeout(function () {
                $(t).parent().append(content);
                $("select").material_select();
            }, 200);
        });
```
maybe it'll help you :)

**Comment by chicocode** [comment]
I made a hack too, maybe less intrusive. 
```
$('.datables-container')
    .on('click', '.select-dropdown li', e => e.preventDefault()})
```

**Comment by Dogfalo** [comment]
Please test this with the v1-dev branch.

**Comment by Dogfalo** [comment]
I checked this on v1-dev and it is working
