### ISSUE TITLE
Bug search bar decaled

### ISSUE THREAD

**Issue by NitroBAY** [Dogfalo/materialize#2722]
When I un-zoom once in chrome the first time the search bar is moved, the second time I do all is good, the third time it's moved etc.
Normal :
![image](https://cloud.githubusercontent.com/assets/9869317/12691001/5511ba16-c6e8-11e5-98e6-102428da6118.png)
Buggy : 
![image](https://cloud.githubusercontent.com/assets/9869317/12691007/5ccc0c70-c6e8-11e5-8127-8fc9085e56aa.png)

**Comment by Dogfalo** [comment]
Zooming in causes all sorts of odd things that we can't control.

**Comment by NitroBAY** [comment]
You're not half as exigeant as what material design required

**Comment by Dogfalo** [comment]
If you use any site zoomed in or out there will be alignment issues.
