### ISSUE TITLE
My Icon Break on Some Device How to Fix this?

### ISSUE THREAD

**Issue by masterpowers** [Dogfalo/materialize#2726]
I have no problem in firefox, ie and google chrome in a desktop user...
but ive got instances that my icons break in apple ipad , other mobile devices such as lenovo model...
this is my custom.css

```

@font-face {
  font-family: 'Material Icons';
  font-style: normal;
  font-weight: 400;
  src: local('Material Icons'), local('MaterialIcons-Regular'), url(https://fonts.gstatic.com/s/materialicons/v11/2fcrYFNaTjcS6g4U3t-Y5ZjZjT5FdEJ140U2DJYC3mY.woff2) format('woff2');
}

.material-icons {
  font-family: 'Material Icons';
  font-weight: normal;
  font-style: normal;
  font-size: 24px;
  line-height: 1;
  letter-spacing: normal;
  text-transform: none;
  display: inline-block;
  white-space: nowrap;
  word-wrap: normal;
  direction: ltr;
  -webkit-font-feature-settings: 'liga';
  -webkit-font-smoothing: antialiased;
}
```
this is my materializedcss version:
```
Materialize v0.97.5
```

Majority of the Apple Made Devices Break the Icos except Iphone 6 plus :(
Anyone Experience this help

**Comment by Dogfalo** [comment]
You can try searching some closed issues, but the font is provided by Google and you should post on their repository
