### ISSUE TITLE
problem when open a modal while some modal is already opening

### ISSUE THREAD

**Issue by zhaoyao91** [Dogfalo/materialize#2727]
while some modal is opening, open a new modal will not clear previous overlay.

**Comment by fega** [comment]
Do you have a modal that opens a modal?
If this is still a problem, please provide a way to reproduce it.
Closed due inactivity but feel free to reopen it if it is still necessary.

**Comment by tomscholz** [comment]
Seems like a Duplicate of https://github.com/Dogfalo/materialize/issues/4044
