### ISSUE TITLE
Dropdown icon IE11

### ISSUE THREAD

**Issue by stevenspinoza** [Dogfalo/materialize#2735]
Hi,
I put a picture, a thousand words, but I'm trying to use the same example but even in your site the icon is offset. Thanks
![dropdown](https://cloud.githubusercontent.com/assets/5944011/12738154/555e644c-c92c-11e5-93d0-99ef714d057d.jpg)

**Comment by chi-bd** [comment]
See #2833

**Comment by fega** [comment]
It was
