### ISSUE TITLE
bower.json - main contains non entrypoint files

### ISSUE THREAD

**Issue by gfduszynski** [Dogfalo/materialize#2738]
Specification states that main section is only to include entry point files.
https://github.com/bower/spec/blob/master/json.md

Current list makes it harder to work with build scripts, 
plus pattern 'sass/*' breaks gulp plugins like for ex. https://github.com/ck86/main-bower-files

**Comment by Dogfalo** [comment]
`sass/*` has been removed in a1ca0a997efb692a27fcfa85a7cc5277b24c0e57
