### ISSUE TITLE
Navbar move all elements 

### ISSUE THREAD

**Issue by NitroBAY** [Dogfalo/materialize#2740]
Hello, when one open the navbar ALL elements of the body are moved (navbar etc.) and come back to their position when close it... I'm sure these great devs will know how to fix that :dancer:

**Comment by Dogfalo** [comment]
I appreciate the bug report but not your snarky attitude. We read every
issue and we will work on a fix for this.

**Comment by NitroBAY** [comment]
'Bug fixed by 1023d8b2
