### ISSUE TITLE
The wave doesn't fit the floating btn

### ISSUE THREAD

**Issue by NitroBAY** [Dogfalo/materialize#2743]
![image](https://cloud.githubusercontent.com/assets/9869317/12797487/7b94ae98-cac4-11e5-8488-09f5c59ce5b3.png)
You see, wave doesn't fit all the button which make a really non-proper render for those as exigeants as me

**Comment by Dogfalo** [comment]
Are you zoomed in on the browser?

**Comment by NitroBAY** [comment]
In this case I wasn't but it appears that zoom can fix the problem sometimes

**Comment by NitroBAY** [comment]
I close as it's a bit annoying for maniac but I think Materialize team has higher priority as they have more than one hundred issue and 270 PR (and it's growing)
