### ISSUE TITLE
truncated text and icons would sometimes overlap

### ISSUE THREAD

**Issue by justinchuby** [Dogfalo/materialize#2748]
Please hover your mouse on the first item at
[https://www.cmucoursefind.xyz/buggy?q=51262#sec](https://www.cmucoursefind.xyz/buggy?q=51262#sec)
<img width="358" alt="2016-02-04 9 24 13" src="https://cloud.githubusercontent.com/assets/11205048/12817655/18c54d06-cb21-11e5-923b-319ef35b36b8.png">
(looks like that)

```
<div class="col s12 m8 l8 truncate">
    <i class="material-icons hide-on-small-only">class</i>
    <span>
      51262 &nbsp;A&nbsp;&nbsp;Communication Design Fundamentals: Design for Interactions for Communications
    </span>
</div>
```

**Comment by Dogfalo** [comment]
It seems fine on my end
