### ISSUE TITLE
lots of duplicate properties in css

### ISSUE THREAD

**Issue by syberknight** [Dogfalo/materialize#2749]
i don't know how relevant or important any of these are, but thought i'd let you know in case you didn't. btw: this is a screenshot of Dreamweaver for Mac (latest version) telling me about it.

<img width="550" alt="screen shot 2016-02-04 at 5 08 53 pm" src="https://cloud.githubusercontent.com/assets/3630609/12832817/1a472f32-cb62-11e5-8fb5-1e211cb3c548.png">

**Comment by fega** [comment]
Could you check if this is still an issue with the last version?

Closed due inactivity, feel free to reopen it if it is still necessary.

**Comment by DanielRuf** [comment]
https://github.com/Dogfalo/materialize/pull/4498/files

**Comment by tomscholz** [comment]
Thanks for letting us know. We will look into it
