### ISSUE TITLE
Form labels don't work properly inside div.parallax-container

### ISSUE THREAD

**Issue by JDougherty** [Dogfalo/materialize#2750]
The `parallax-container` class has `line-height: 0` attribute, and this causes labels to be positioned incorrectly, both when the associated field has and does not have focus/content. 

Explicitly setting `line-height: 22.5px` on the parent `div.input-field` will fix this issue.

**Comment by acburst** [comment]
This is not part of materialize rather just our template. parallax-container inherently does not have any line-height set
