### ISSUE TITLE
Slider (range) with discreete points

### ISSUE THREAD

**Issue by mitar** [Dogfalo/materialize#2751]
It would be great to be able to have discrete points on the slider/range, the way it is described here: https://www.google.com/design/spec/components/sliders.html#sliders-discrete-slider

**Comment by acburst** [comment]
You can achieve this using step in the HTML5 range, and there is also a step option in the noUiSlider

**Comment by mitar** [comment]
But visually those steps are not drawn. At least I have not managed to get them to be visible. You are saying that visually ticks should appear if step option is enabled?
