### ISSUE TITLE
Datepicker issue

### ISSUE THREAD

**Issue by avirati** [Dogfalo/materialize#2752]
Use Case : 

> 1. Select a date.
> 2. Close the date picker
> 3. Focus out of the browser (_Alt + Tab_ or _Cmd + Tab_)
> 4. Focus in to the Browser again (_Alt + Tab_ or _Cmd + Tab_)
> 5. The date picker modal shows up again

Things I have tried : 

> 1. Blurring the date picker input element.
> 2. `document.body.focus()`

However, if I click somewhere else in the screen, and try to reproduce the behaviour, it doesn't.

I am pretty sure that its a bug, but if its not, I would like to know how to stop this behaviour.

**Comment by Dogfalo** [comment]
See https://github.com/amsul/pickadate.js/issues/160
