### ISSUE TITLE
Missing the cool input and textarea underline effect

### ISSUE THREAD

**Issue by onigetoc** [Dogfalo/materialize#2753]
I love Materialize.

I find it miss the cool input and textarea underline effect
like this one here.
[Border bottom effect](http://fezvrasta.github.io/bootstrap-material-design/#input)

**Comment by fega** [comment]
it doesn't fit with the material design specs

https://material.io/guidelines/components/text-fields.html#text-fields-required-fields

**Comment by onigetoc** [comment]
Every other material design frameworksdo it.

**Comment by fega** [comment]
Well, that's true.
https://getmdl.io/components/#textfields-section
curiously the source of confusion is two google project's

Added to the feature request dashboard

**Comment by onigetoc** [comment]
Here only underline with no effects
https://material.angularjs.org/latest/demo/input

**Comment by acburst** [comment]
While we try and follow the material design guidelines as closely as possible, in the end they are still just guidelines. Even Google strays away from it when it makes sense. Sometimes the choices we make for this framework are just personal preferences that may not be perfectly in line with the guidelines. Also, I like the simple fade in better than this animation personally.

**Comment by Nohinn** [comment]
Made a first attempt for this (would have to check if it works on all cases).
Added an span element after the label of the input with a css class named border-expand. So this can be an optional feature for those who would like to make use of it.

And added this CSS:
`
.input-field > label + .border-expand {
	display: block;
	width: 100%;
	position: absolute;
	top: 0;
	pointer-events: none;
	min-height: 3rem;
}

.input-field > label + .border-expand:after {
	content: "";
	position: absolute;
	width: 10px;
	background-color: #26a69a;
	left: 45%;
	height: 2px;
	top: calc(100% - 1px);
	transition-duration: .3s;
	transition-timing-function: cubic-bezier(.4,0,.2,1);
	visibility: hidden;
}

.input-field > label:not(.label-icon).active + .border-expand:after {
	left: 0;
	width: 100%;
	visibility: visible;
}
`
