### ISSUE TITLE
Proper way to extend buttons sizes

### ISSUE THREAD

**Issue by diegoaguilar** [Dogfalo/materialize#2755]
So, I need large buttons, I got `<a class="btn-floating btn-large">Example</a>` but that is not enough for me, I really need larger and custom sized elements. Are there any other classes for it? And, what should be proper way to extend the button classes to achieve custom sizes?

**Comment by soniabrami** [comment]
Hi Diegoaguilar, 
You could modify the $button-height, $button-large-height and play with any button font size or padding variable as well if necessary.

available variables can be found in:
https://github.com/Dogfalo/materialize/blob/master/sass/components/_variables.scss
