### ISSUE TITLE
how to add the ribbon

### ISSUE THREAD

**Issue by rc1107** [Dogfalo/materialize#2759]
![qqqqqqq](https://cloud.githubusercontent.com/assets/15191551/12874912/312c8ef0-ce04-11e5-8793-731f9edd6858.PNG)

![gallery1](https://cloud.githubusercontent.com/assets/15191551/12874990/39196d70-ce06-11e5-91d6-7d110477c007.jpg)

is there any way to create ribbon ,which is marked in image with blue circle.
becouse when i uses <img>> tag it come one after one in out put.

@Dogfalo 
here is my code:

```<div class="col s12 m3">
	<div class="card hoverable hoverable">
               <img src="img/new.png">
             <div class="card-image" style="left: 0px; top: 0px">
			<img src="img/gallery1.jpg">
		</div>
		<div class="card-content center-align grey-text text-darken-1">
			<h5>$56</h5>
			<span><strong>Easy Polo Black Edition.</strong></span>
		</div>
			<div class="center-align card-action">
			<a class="waves-effect waves-light btn orange darken-4" style="font-size: 12px">
        <i class="material-icons right">shopping_cart</i>Add to cart</a></div>
			</div>
	</div>```

**Comment by SuperDJ** [comment]
I think this belongs on [SO](http://stackoverflow.com/) as this isn't an issue of the framework
