### ISSUE TITLE
Help with search dropdown

### ISSUE THREAD

**Issue by t2013anurag** [Dogfalo/materialize#2760]
![df](https://cloud.githubusercontent.com/assets/9719394/12875914/8a9063f2-ce1a-11e5-8160-b73f323ef30e.png)

I have an auto complete api which fetches data from the mongodb. I am having trouble making a view similar to the search as in the screenshot. I have tried mostly all the possible ways.
I tried following the link but it didn't workout.
https://github.com/Dogfalo/materialize/issues/607

**Comment by acburst** [comment]
This is something I wrote custom for our documentation. It is not part of our framework. 

You can look up tutorials or browse stackoverflow but this isn't the place to be asking
