### ISSUE TITLE
[Feature Request] Sliding Tabs

### ISSUE THREAD

**Issue by hetunandu** [Dogfalo/materialize#2762]
Hey guys! Really love Materialize. I have started using it in every project and recommend it to everyone. 

One thing I always feel that got problematic was tabs. A user always has to click to go to the next section. Also while testing I find a lot of users trying to slide to go to the next tab cause they have that habit in android material designed apps. 

Getting that kind of sliding on web is difficult but I just thought it would be an amazing feature. After that there is no competition for you (atleast for me)

**Comment by Dogfalo** [comment]
That's great to hear @hetunandu! Thanks for spreading the word. We agree that this would be a useful feature. There is a issue open for it here: #1943
