### ISSUE TITLE
checkbox visibility being set to hidden is unnecessary and unhelpful.

### ISSUE THREAD

**Issue by vsajip** [Dogfalo/materialize#2767]
Since checkboxes have their `position` set to `absolute` and `left` set to `-9999px`, setting the `visibility` to `hidden` is unnecessary. Morever, it is unhelpful, as because it is set, you can't tab onto checkboxes. Removing this from the CSS seems to have no visual effect, but you can then tab on to checkboxes and toggle their state with space bar, for instance.

**Comment by vsajip** [comment]
Since checkboxes have their `position` set to `absolute` and `left` set to `-9999px`, setting the `visibility` to `hidden` is unnecessary. Morever, it is unhelpful, as because it is set, you can't tab onto checkboxes. Removing this from the CSS seems to have no visual effect, but you can then tab on to checkboxes and toggle their state with space bar, for instance.

**Comment by rthomson83** [comment]
Submit a PR?

**Comment by vsajip** [comment]
It's literally a one-line change (removal of `visibility: hidden`). Wouldn't it be quicker and simpler for a committer to just delete the line, presuming they agree with the proposal? Is there a project policy about wanting a PR for every single change? I understand the value of PRs in general, of course, but I normally don't require that bug reporters for my projects submit a PR if their proposed change is easily grokkable and reviewable without one.

**Comment by Dogfalo** [comment]
Already added in 4042c89b37fa856e91012aa59f4af54ad5d66d66
