### ISSUE TITLE
Adding Snackbar

### ISSUE THREAD

**Issue by AkshayChordiya** [Dogfalo/materialize#2769]
The library is pretty great. It seems few components from Material Design Guidelines, one of which is SnackBar
I hope Snack Bar is added soon, it's one of the most important component. 
Thank you.

**Comment by SuperDJ** [comment]
[This](http://materializecss.com/dialogs.html)?

**Comment by AkshayChordiya** [comment]
@SuperDJ Nope it is `Toast`. What I am looking for is something like this "Toast with Undo button".
You can find more details about `SnackBar` over here https://www.google.com/design/spec/components/snackbars-toasts.html

**Comment by Dogfalo** [comment]
You can simply use a toast with a callback

**Comment by AkshayChordiya** [comment]
@Dogfalo Thank you so much.
