### ISSUE TITLE
Change font directory

### ISSUE THREAD

**Issue by tiaguinhor** [Dogfalo/materialize#2774]
You can change the default path sources of material to follow the pattern of other libraries such as font-awesome for example?

The current path of the variable is ../font/, change to ../fonts/

Leaving this default path, it becomes easier for the gulp work together with other libraries.

_variables.scss (https://github.com/Dogfalo/materialize/blob/master/sass/components/_variables.scss)
/* 9. Fonts
   ========================================================================== */

$roboto-font-path: "../font/roboto/" !default;
$icons-font-path: "../font/material-design-icons/" !default;

**Comment by Dogfalo** [comment]
Fixed in a1ca0a997efb692a27fcfa85a7cc5277b24c0e57
