### ISSUE TITLE
Search bar not working the http://materializecss.com/

### ISSUE THREAD

**Issue by solo14000** [Dogfalo/materialize#2778]
Hello,

I cannot get search bar working under Chrome 48.

Thanks

**Comment by acburst** [comment]
Are you talking about the search bar on our documentation? Because it is working for me. Do you have any other information? Maybe console errors or something.

**Comment by solo14000** [comment]
Yes i m talking about the documentation search bar on your web site. I
notice a js error few months ago but it seems tat error has disapeared. Not
sure it was related to the search bar. I will have a look on it as soon as
possible and come back to you.

**Comment by solo14000** [comment]
did you made any fixes recently? Seems to work now for me.

**Comment by acburst** [comment]
Nope, may have been some random error.
