### ISSUE TITLE
Preformatted HTML5 input fields

### ISSUE THREAD

**Issue by acierpinski** [Dogfalo/materialize#2780]
The following field types should have an active label always:
<input type="date" />
<input type="datetime" />
<input type="datetime-local" />
<input type="time" />
<input type="week" />
<input type="month" />
<input type="color" />

**Comment by acburst** [comment]
Please give more information and flesh out your issue.

**Comment by acierpinski** [comment]
Sorry, some text was filtered.
The following input types should always have an active label:

input type=date, datetime, color, month, week, time, datetime-local

Empty input fields have an rendered content, e. g. --:--:-- for time input fields. 
Labels will be rendered at the placeholder position and will overlay the rendered content. The is not correct.

**Comment by mlecoq** [comment]
+1 for input type month ! 

Thanks !
