### ISSUE TITLE
Forms in Nav Dropdowns

### ISSUE THREAD

**Issue by Tbutnyakov** [Dogfalo/materialize#2781]
Hey! 
Can you make support of forms in dropdowns menu of navigation bar?
I think you already know about that forms work incorrect.
But it is a very popular pattern - build login/register form inside dropdowns in nav panel. 

Do you have some sort of temporary solution to this problem ?

P.S. Thank you for awesome package!

**Comment by snktre59** [comment]
Interesting topic, anyone ?

**Comment by fega** [comment]
@Tbutnyakov @snktre59 Could do you provide an clear example? thanks

**Comment by fega** [comment]
Closed due inactivity, feel free to reopen it if it is still necessary.
