### ISSUE TITLE
update to pickadate.js new version because of datepicker trouble

### ISSUE THREAD

**Issue by solo14000** [Dogfalo/materialize#2782]
Hello,

I'm facing trouble with datepicker using hiddenPrefix, hiddenSuffix, container and containerHidden options. It seems that pickdate.js has solved several bugs related to that options. Did you plan to update the pickadate.js version in Materializecss??

Thanks

**Comment by tomscholz** [comment]
Have a look at my comment [here](https://github.com/Dogfalo/materialize/issues/3061#issuecomment-291892596)
