### ISSUE TITLE
Use opacity instead of adjusting color for text

### ISSUE THREAD

**Issue by ishitatsuyuki** [Dogfalo/materialize#2784]
According to Material Design guidelines, it's preferred to use opacity instead of changing the color. [1]

I think something like "red-text text-secondary" should look good.

[1] https://www.google.com/design/spec/style/color.html#color-text-background-colors

**Comment by lars-derichter** [comment]
+1

**Comment by HIRANO-Satoshi** [comment]
+1

I think so, too. We need the standard way to specify text opacities.

**Comment by HIRANO-Satoshi** [comment]
Polymer's paper-style has color.html and there are definitions of opacities.

```
<style is="custom-style">

  :root {

     .....

    /* opacity for dark text on a light background */
    --dark-divider-opacity: 0.12;
    --dark-disabled-opacity: 0.38; /* or hint text or icon */
    --dark-secondary-opacity: 0.54;
    --dark-primary-opacity: 0.87;

    /* opacity for light text on a dark background */
    --light-divider-opacity: 0.12;
    --light-disabled-opacity: 0.3; /* or hint text or icon */
    --light-secondary-opacity: 0.7;
    --light-primary-opacity: 1.0;
}
```

The *dark-primary-opacity* is defined as 0.87, but not used anywhere in Polymer surprisingly.

Also, it seems for me that texts in Polymer's [default-theme](https://github.com/PolymerElements/paper-styles/blob/master/default-theme.html) and [typography demo](https://github.com/PolymerElements/paper-styles/blob/master/typography.html) do not have opacity.

**Comment by Dogfalo** [comment]
We change the alpha of the color which is equivalent of changing the opacity. Except that it will not interfere with other non-text objects.
