### ISSUE TITLE
z-index: -1 on labels for fields with .validate causes the labels not to be visible

### ISSUE THREAD

**Issue by vsajip** [Dogfalo/materialize#2785]
The `z-index: -1` in the following rule in `_input-fields.scss`:
```
  // Full width label when using validate for error messages
  &.validate + label {
    width: 100%;
    z-index: -1;
  }
```
causes the label to be hidden behind the field when the field has class `validate`. Removing the `z-index` line causes the label to be visible. What's the reason for specifying `z-index: -1`?

(N.B. This is not from a released version, but from the latest source.)

**Comment by acburst** [comment]
Please post a code example.

**Comment by vsajip** [comment]
[This pen](http://codepen.io/vsajip/pen/RrveOy) illustrates the problem. There are two fields in the HTML, `username` and `email`. The former has the `validate` class set, the latter does not. The CSS is a copy/paste of the entire materialize.css from the repo. You should see (I'm using Chromium 48.0 on Linux) that the username label is not visible, but the email label is. If you change the class from `validate` to e.g. `zvalidate`, the label for username appears. Also, if you leave the class at `validate` but locate and change the `z-index: -1;` in the label rules covering `.validate` to e.g. `zz-index: -1;`, the label for username also appears.

Note that due to the large size of the CSS, CodePen can be a bit slow to render the example.

**Comment by Dogfalo** [comment]
For future reference, it is easier to fork [this pen] (http://codepen.io/Dogfalo/pen/xbzPQV). I think the problem is that you did not use the `input-field` class

**Comment by vsajip** [comment]
Thanks, but there is an `input-field` class in the div which encloses the input field - as per the examples in the documentation.

```
  <div class="row">
    <div id="id_username_container" class="input-field col s12 required">
      <i class="mdi-action-account-box prefix"></i>
      <input type="text" name="username" id="id_username" length="8" class="validate">
      <label for="id_username">Username</label>
    </div>
  </div>
  <div class="row">
    <div id="id_email_container" class="input-field col s12 required">
      <i class="mdi-communication-email prefix"></i>
      <input type="email" name="email" id="id_email">
      <label for="id_email">Email Address</label>
    </div>
  </div>
```
The reason things don't work when you type in the bottom field is that there is no JS referenced in the pen, which means that the label isn't moved out of the way when you type. I didn't bother to include the JS, since it's not needed to show the visibility problem. In the real form which I stripped this example from, everything works fine if I comment out the `z-index: -1;`, including labels moving up and out of the way on focus, etc.

BTW that pen you mentioned appears to be referencing 0.97.5 of the CSS/JS, which don't exhibit the problem. I found this problem in the latest source.

Great work, by the way! Kudos :-)

**Comment by Dogfalo** [comment]
Oh sorry, I didn't see the class in the html when I was looking at it. 

I removed z-index and added a pointer-events: none; instead on the label in 8b57819330fb0151315ef58fdaff299cd6b0be2
