### ISSUE TITLE
UL default style

### ISSUE THREAD

**Issue by Mat-thieu** [Dogfalo/materialize#2786]
An unsorted list (without any framework classes) hides the bullet points, It'd be nice to have a class that returns it to default state or have it so class-less ULs show the bullet points by default.

**Comment by acburst** [comment]
Added in 51dead92e41ce995d3eb2a9775383c7b30aff2b8

Use the class ```.browser-default```

**Comment by Mottie** [comment]
This is still messed up!

If I add `.browser-default` to a `UL`, I would expect the padding and list items to have their default appearance - **[see demo](https://jsfiddle.net/Mottie/bej4qtjn/)**

This css is needed to make the `browser-default` class actually behave as expected:

```css
ul.browser-default {
  padding-left: 40px;
}
ul.browser-default li {
  list-style-type: inherit;
}
```

Please consider changing the definition in the [`_global.scss` file](https://github.com/Dogfalo/materialize/blob/master/sass/components/_global.scss) as follows:

```sass
ul {
  &:not(.browser-default) {
    padding: 0;
    list-style-type: none;

    li {
      list-style-type: none;
    }
  }
}
```
