### ISSUE TITLE
Button inside carousel is not working

### ISSUE THREAD

**Issue by ShivaliPatel** [Dogfalo/materialize#2787]
I am using carousel and have put a button on it. But the click functionality is not working in emulator.

**Comment by f1ana** [comment]
Do you have an example or fiddle for reference?

**Comment by ShivaliPatel** [comment]
Here is the code.

HTML code:

```
<div class="carousel carousel-slider" custom-Carousel >
        <div class="carousel-item">
            <div class="carousel-content">
                <p>Get started</p>
            </div>
        </div>
        <div class="carousel-item">
            <div class="carousel-content">
                <button onclick="login()">Login</button>
            </div>
        </div>
</div>
```

javascript initialization :

```
jQuery(".carousel.carousel-slider").carousel({full_width: true});
```

Css code:

```
.tourScreen .carousel {
  height: 100%!important;
}
.tourScreen .carousel .carousel-item:nth-child(1) {
  background: url("../img/guide%20(1).jpg") center center;
}
.tourScreen .carousel .carousel-item:nth-child(2) {
  background: url("../img/guide%20(2).jpg") center center;
}
```

Click event on button is working fine in browser, but not in emulator.

**Comment by cunneen** [comment]
Carousel adds its own click event listener:

[https://github.com/Dogfalo/materialize/blob/master/js/carousel.js#L97](https://github.com/Dogfalo/materialize/blob/6ce0fdce0fc8229d84bc03f13f404a12601b600c/js/carousel.js#L97)

It'd be good to be able to provide our own event hooks to carousel.

**Comment by acburst** [comment]
This should be fixed on the newest release.
