### ISSUE TITLE
Multiple modals z-index issue

### ISSUE THREAD

**Issue by kevzlou7979** [Dogfalo/materialize#2788]
Hi guys, 

Modal components start at an z-index of 1000 and lower their z-index value whenever another is opened/closed. So essentially, after a lot of open/close operations, a modal would no longer be shown in front of other elements like a sidenav / navbar components.

**Comment by acburst** [comment]
Hmm, can you post an example that causes the bug where it lowers the z-index? I've tested locally and it seems to be going up correctly.

**Comment by fega** [comment]
Closed due inactivity, feel free to reopen it if it is still necessary.
