### ISSUE TITLE
Multilevel dropdowns

### ISSUE THREAD

**Issue by lastnoob** [Dogfalo/materialize#2789]
I would like to achieve something like [this](http://www.cssscript.com/demo/create-a-multi-level-drop-down-menu-with-pure-css/), but with the materialize dropdown component. I would like it to have multiple levels.  
However, I'm stuck at [this](http://codepen.io/simii/pen/rxPjXd), a scroll bar appears in the dropdown menu when hovering, it seems like the dropdown content is an actual "mini browser window", instead of just showing up next to it.

Anyone can help me fix this issue? Multilevel dropdowns are quite essential in my opinion.

**Comment by acburst** [comment]
Our dropdowns have overflow to allow scrolling. If you want, you can override this on the UL elements with ```overflow: visible;```

Then you just have to style the nested UL to your needs and it should work.
