### ISSUE TITLE
Uneven height columns get messed up when reducing width of screen

### ISSUE THREAD

**Issue by luismgz** [Dogfalo/materialize#279]
You can see it here: http://bit.do/mybug
There are two rows.
The second row has four columns of equal width (when in large mode), but different length of content inside. When reducing the width of the browser, they get messed up in weird ways.

**Comment by maurop123** [comment]
This StackOverflow question helped me with this issue: http://stackoverflow.com/questions/23087190/masonry-overlapping-issue
