### ISSUE TITLE
Form select label and caret misaligned in a sidenav

### ISSUE THREAD

**Issue by solo14000** [Dogfalo/materialize#2793]
Hello,

I'm trying to build a search form in a side nav using a select dropdown.
The label and the caret are misaligned.

Here is a simple example: [http://jsfiddle.net/craj431z/](http://jsfiddle.net/craj431z/1/)
Could you confirm and fix it or give me a workaround?

Thanks in advance

**Comment by TyrionGraphiste** [comment]
You have to wrap your .input-field inside a : `<div class="row">`
