### ISSUE TITLE
Make inactive labels non-selectable

### ISSUE THREAD

**Issue by vsajip** [Dogfalo/materialize#2794]
Suggested enhancement: adding the rule

```
      label:not(.active) {
        -webkit-user-select: none;
        -moz-user-select: none;
        -ms-user-select: none;
        user-select: none;
      }
```

would be an improvement over the current situation, where if you carelessly drag while clicking on an input field to focus on it, part of its label gets selected, and it doesn't move up out of the way. This is most likely not the user's intention: if the user really needs/wants to select/copy the label, this can always be done when the label has been made active.

**Comment by fega** [comment]
Closed due inactivity

Also, it rarely happens (never in my case, I'm testing right now), but it's only my opinion

**Comment by vsajip** [comment]
What do you mean by 'inactivity'? Were you expecting a PR for this? It is quite easy to reproduce. Here's a couple of animated GIFs showing the effect - from the materializecss.com "Components | Forms" page.
![scap1](https://cloud.githubusercontent.com/assets/130553/24694095/80f81cf8-19d8-11e7-9a47-fffd88b9265f.gif)
![scap2](https://cloud.githubusercontent.com/assets/130553/24694098/8808a350-19d8-11e7-96f0-649d32984f45.gif)

**Comment by fega** [comment]
Hello @vsajip 
We are happy that a lot of people are contributing to this project, but as you can see there are a lot of open issues and some of them like this have more than a year open and sadly didn't receive the appropriate attention. that means "inactivity". So we are trying hard to improving this situation taking decisions about the issues in the more effective way as possible.

About the issue, yeah I already reproduce it easily but only when I intentionally wanted that this happens, I didn't be a usability problem, also I was thinking if someone wanted to copy paste the labels, it could be frustrating with your proposed enhancement.

I will be glad to reopen this issue for further discussion.

**Comment by acburst** [comment]
I agree with @fega. I think the label should always be selectable and if it is only selectable in a specific state, that is confusing to the user. I understand that sometimes the user may select it when they tried to focus, but text highlight is very noticeable and understandable so I don't think its too much of a concern.

**Comment by vsajip** [comment]
I came across this when not trying to select the label - just by a careless movement of the mouse while clicking on the field. (Hence it is proposed as an enhancement rather than a bug.) IMO It spoils the effect of the label jumping up to sit over the field when you focus on the field.

**Comment by acburst** [comment]
Then it would never be selectable right? I think we just disagree here, and it seems like you could easily use some custom css to achieve this on your own project.

**Comment by vsajip** [comment]
Sure, I've already applied the above CSS in my own project.
