### ISSUE TITLE
Modal displays incorrectly in side nav

### ISSUE THREAD

**Issue by solo14000** [Dogfalo/materialize#2799]
Hello,

I'm working on a sive nav. I need to display a modal on button click (search form submit for instance).
Badly, the modal is displayed in the side nav instead in the main window. 
Have a look here on that trouble : [http://jsfiddle.net/n6x0b4hx/2/](http://jsfiddle.net/n6x0b4hx/2/)

A workaround could be to move the modal div struture outside the nav tag but it is no really possible using my framework. So could you fix it? 

Thanks a lot

**Comment by supachailllpay** [comment]
What about move your Modal Structure out of nav?. It can put in any place (put it outside still make sense for me).

```html
<nav>
  <ul class="right hide-on-med-and-down">
    <li><a href="#!">First Sidebar Link</a></li>
  </ul>
  <ul id="slide-out" class="side-nav">
    <li>  <!-- Modal Trigger -->
      <a class="waves-effect waves-light btn modal-trigger" href="#modal1">Modal</a>
    </li>
  </ul>
  <a href="#" data-activates="slide-out" class="button-collapse"><i class="mdi-navigation-menu"></i></a>
</nav>

<!-- Modal Structure -->
<div id="modal1" class="modal">
  <div class="modal-content">
    <h4>Modal Header</h4>
    <p>A bunch of text</p>
  </div>
  <div class="modal-footer">
    <a href="#!" class=" modal-action modal-close waves-effect waves-green btn-flat">Agree</a>
  </div>
</div>
```

**Comment by solo14000** [comment]
In fact, I did move the structure using a jQuery call because in my case it is not very simple to split modal structure and trigger in 2 different divs using my php framework
