### ISSUE TITLE
hide-on-small class not working correctly

### ISSUE THREAD

**Issue by themakshter** [Dogfalo/materialize#2800]
I am not sure if it is just me being stupid or not, but I am trying to hide the table of contents on the small screen. However, when I try to do that using the `hide-on-small-only` class, it doesn't seem to work.

This [codepen](https://codepen.io/anon/pen/adXdqr) can be used to show that. If you use chrome inspector and toggle device mode, using small screens like the Nexus 6P or iPhones, the table of contents does not disappear. hide-on-med-and-down seems to work correctly, but not this.

**Comment by acburst** [comment]
On mobile you need meta tags to stop the window from resizing. Codepen won't do it so using the chrome inspector probably won't work but if you just reduce the window size it should work. If you actually try it on a phone it should work too.

Look into meta tags like:  ```<meta name="viewport" content="width=device-width, initial-scale=1">```

**Comment by Fabiyo-90** [comment]
it's still not working on Materialize v0.98.0

**Comment by tomscholz** [comment]
@Fabiyo-90 See https://github.com/Dogfalo/materialize/issues/2800#issuecomment-186967181. It is working.
