### ISSUE TITLE
Carousel does not work on all touch based browsers

### ISSUE THREAD

**Issue by Defaoite** [Dogfalo/materialize#2806]
I have found that the carousel item href links don't seem to work on Safari on iOS and Chrome on Android (surprisingly they do work on Chrome for iOS)

Looking at your Javascript, it seems your dragged variable may be causing a problem on these mobile web browser but I am not certain. I would much appriciate any information on how to solve this problem

**Comment by Defaoite** [comment]
Anyone with a solution to this problem?

**Comment by acburst** [comment]
Finally fixed in b731cf0. Sorry about the slow response
