### ISSUE TITLE
Feature request: events for dropdown

### ISSUE THREAD

**Issue by mishantrop** [Dogfalo/materialize#2807]
Hello.
Is it possible to make events for dropdown like in Bootstrap? It would be awesome and very usefull. 
[http://getbootstrap.com/javascript/#dropdowns](http://getbootstrap.com/javascript/#dropdowns)

**Comment by Ragsboss** [comment]
+1

**Comment by mattiabasone** [comment]
+1

**Comment by fega** [comment]
Moved to feature request board

**Comment by tomscholz** [comment]
This feature already exsists: http://materializecss.com/dropdown.html#initialization

`  $('.dropdown-button').dropdown('open');`
`  $('.dropdown-button').dropdown('close');`

**Comment by acburst** [comment]
I believe @mishantrop means events or callbacks. Those are just programmatic ways of opening and closing the dropdown.

**Comment by tomscholz** [comment]
@acburst Bootstrap doesn't provide any callbacks for dropdowns. But I think the solution [here](https://stackoverflow.com/a/12479858) can be easily applied to materialize as well

**Comment by acburst** [comment]
They use events and have their users write custom event handlers. We've been using callbacks instead in Materialize so I think we should stick to that convention

**Comment by tomscholz** [comment]
@acburst You are right, found it [here](https://getbootstrap.com/javascript/#dropdowns-events)
