### ISSUE TITLE
Feature request: Label and select in a single line

### ISSUE THREAD

**Issue by Ragsboss** [Dogfalo/materialize#2810]
I'm trying to get the label for a select control (drop-down) in the same line as the drop-down. http://materializecss.com/forms.html#select always has the label in its own line and drop down in the next line. But I want them in one line because two lines is wasting a lot of real-estate on the right and vertical scrollbar is coming way too often. 

This feature request is to support this built-in. I'd also appreciate any suggestions on how to achieve this.. Right now I'm using row and cols - one col with <p> and second col with select (without label). Plus I'm using custom styling on first column to make it align vertically with select..

**Comment by fega** [comment]
Hello, I'm not sure if I can understand your request, can you provide a sample image?

**Comment by tomscholz** [comment]
Can you post a codepen to help us visualize the problem? Anyhow, I will close this issue for now :) Feel free to reopen it anytime :)
