### ISSUE TITLE
Pass data to a materialize modal

### ISSUE THREAD

**Issue by bruno-farias** [Dogfalo/materialize#2811]
How can i pass a variable to a modal? I trying to create a delete confirmation.

this is what i got until now:

`
$('.delete-phone-type').leanModal({
    ready: function(e) {
        $('.title').text('Confirms the exclusion of the id: ' + $(this).data('pk'));
    }
});`

<hr>

in bootstrap I do this way and works...
`$('.product-delete-modal').on('show.bs.modal', function (e) {
        $('[name="id"]').val($(e.relatedTarget).data('id'));
    });`

**Comment by kurtaking** [comment]
Were you ever able to figure out how to get this to work? I am trying to do the same thing.

**Comment by Paco-Cervantes** [comment]
had the same problem, I wrote a jquery function, perhaps you can use, here an example in [jsFiddle](https://jsfiddle.net/Paco_Cervantes/Lfn3L5pr/17/), and  the repository in [github](https://github.com/Paco-Cervantes/Materialize-Messages)

**Comment by fega** [comment]
Closed due inactivity, feel free to reopen it if it is still necessary.
