### ISSUE TITLE
Side Nav dragging out is unreliable on mobile

### ISSUE THREAD

**Issue by TitusJonas** [Dogfalo/materialize#2819]
Steps to reproduce:
1. Go to the Materializecss website
2. Touchslide in from the left and drag out the sidenav
3. Move the Sidenav back in
4. Repeat 2. and 3. fast -> sometimes the sidenav won't react and doesn't show up.

Tested and reproduced on: 
Nexus 5 with Android 6
Galaxy Note 2 with Android 4.4

**Comment by fega** [comment]
Closed due inactivity, feel free to reopen it if it is still necessary.

**Comment by tomscholz** [comment]
Duplicate of https://github.com/Dogfalo/materialize/issues/3872
