### ISSUE TITLE
Scrollspy not working in JQuery 2.2.0

### ISSUE THREAD

**Issue by remi-gelinas** [Dogfalo/materialize#2826]
Using JQuery 2.2.0, I receive an unrecognized expression error  on `<a href="#home"></a>` when setting up Scrollspy. I am using Materialize 0.97.5 via CDN. Is this because Scrollspy's selectors are not updated? If not, how do I fix it?

**Comment by Dogfalo** [comment]
Take a look at the recent changes on scroll spy, that might help.

**Comment by remi-gelinas** [comment]
So scroll spy was updated to select hrefs properly, but the current CDN-hosted version does not contain the fixes.

**Comment by nclopezo** [comment]
Hi,
I am having the same issue Materialize 0.97.5. In my case I use the unminified file for development and django compressor in production. I guess these are the changes you are mentioning:
https://github.com/Dogfalo/materialize/commit/aa1a26abf2d868c26d7f353fa248f1597e94c223
Just in case another person sees this conversation and wants to find them quickly.

**Comment by MacGyer** [comment]
Hi,

when will there be a new release published containing at least this fix:
https://github.com/Dogfalo/materialize/blob/master/js/scrollspy.js#L179

in 0.97.5 release ```dist/js/materialize.js``` the scrollSpy href selector bug fix is not included
https://github.com/Dogfalo/materialize/blob/master/dist/js/materialize.js#L2478

Thanks for getting back.

**Comment by Dogfalo** [comment]
Not sure of the release date, but the best thing to do for now is to not use jQuery 2.2.x
