### ISSUE TITLE
Responsive-table it's bad when has some blank fields

### ISSUE THREAD

**Issue by ferchoman09** [Dogfalo/materialize#2828]
I have a table with class="responsive-table"
When I have blank fields, the table looks bad.

![capture](https://cloud.githubusercontent.com/assets/4257523/13227507/f0050d82-d964-11e5-8d65-3b7d90c6d150.PNG)

**Comment by f1ana** [comment]
While clearly not a permanent fix, what about adding &nbsp; to the empty columns?

**Comment by ferchoman09** [comment]
Good idea ! Works fine.
Hopefully the fix will come soon.

**Comment by Dogfalo** [comment]
I have a fix that involves adding a before element with a non breaking space '\00a0'

**Comment by Dogfalo** [comment]
Fixed in 7114660

**Comment by ferchoman09** [comment]
Thanks,
When can I download the fix?
