### ISSUE TITLE
focus on input fields

### ISSUE THREAD

**Issue by kmuenze** [Dogfalo/materialize#2829]
I cannot get this to work $('#last_name').focus(); from the console on this page: http://materializecss.com/forms.html

I see #1762 is closed but it does not appear to be working.

Did this regress?

**Comment by kmuenze** [comment]
added a settimeout delay as described here and it worked:
https://github.com/Dogfalo/materialize/issues/822#issuecomment-77524620

**Comment by ferchoman09** [comment]
I am trying focus on input text with settimeout like the comments. But didn't works.
