### ISSUE TITLE
listen to opening/closing event on sideNav

### ISSUE THREAD

**Issue by dstN** [Dogfalo/materialize#2830]
hello, 

how can i check if my mobile is "opened" or "closed"? i want to switch the hamburger icon to a close icon if the nav is opened... and i couldn't find out how.

**Comment by Thanood** [comment]
Afaik there are no actual events. But ```show``` is triggering a ```click``` on the sidenav button ([see here](https://github.com/Dogfalo/materialize/blob/master/js/sideNav.js#L309)) and ```hide``` is triggering a click in ```$('#sidenav-overlay')``` ([see here](https://github.com/Dogfalo/materialize/blob/master/js/sideNav.js#L312)).

You could probably attach to these events.

**Comment by dstN** [comment]
why am i finding 16 results for "hide" in the unminified-js and only 9 in the minified-js..  that makes no sense at all.

**Comment by baraamashaal** [comment]
maybe comments :joy: :joy:

**Comment by dstN** [comment]
@Thanood i tried this with this code: 

`show : function() {
      this.trigger('click');
      $(".button-collapse").addClass("menuopen");
      $("#nav-mobile").addClass("open");    
    },
    hide : function() {
      $('#sidenav-overlay').trigger('click');
      $(".button-collapse").removeClass("menuopen");
      $("#nav-mobile").removeClass("open");
    }`

but this doesn't work. no class is added.

**Comment by dstN** [comment]
ok i think now it's working. only one thing which doesn't work:

if i use the hammer.js-extension where the user is able to drag the navi in and out the addClass-Stuff works, but i can't find the trigger where the navi gets dragged out. this is my only error i get.. the classes stay on the button and the nav if i drag the navi out.

**Comment by dstN** [comment]
ok found everything:

i added my removeClass-Stuff in the "removeMenu();"-Function.
and everwhere it says menuOut = true, i added my addClass-Stuff and vice versa on menuOut = false.

**Comment by stueynet** [comment]
@Thanood can you tell me a bit more about how you hook into that ? I am having the same issue with my hamburger changing. One problem is that you can click anywhere to close the sideNav so my burger has no idea that it was closed. Is there a way to listen to the menuOut status? Thanks in advance for the help.

**Comment by Thanood** [comment]
Sorry, I didn't actually try that yet. :smile: 
I can try it tomorrow but now I have to get some sleep.

@stueynet I thought of something like ```$('#sidenav-overlay').on('click')```

**Comment by dstN** [comment]
i used this manually fixed sidenav.js (written for my needs):

http://pastebin.com/aDcF5EDH

**Comment by lance13c** [comment]
These events are exactly what I'm looking for. I'd like to submit a feature request for opening/closing (show/hide) events for the sidenav.

**Comment by DonHartman** [comment]
@lance13c I created a pull request that adds these events back in July, but it doesn't look like they've had a chance to look at it yet, but I've been keeping it up to date with master. So here's to hoping they get to it soon.
