### ISSUE TITLE
Materialboxed image does not show outside table

### ISSUE THREAD

**Issue by OnBlur** [Dogfalo/materialize#2832]
On mobile when selecting the materialboxed image inside a table, the image shows only inside the table, because of that it cuts the image. See images.

![table](https://cloud.githubusercontent.com/assets/15030701/13267430/842553dc-da7d-11e5-97e4-0d76eb44df0e.png)
![materialboxed](https://cloud.githubusercontent.com/assets/15030701/13267294/d88f22a0-da7c-11e5-9052-1ad513898e0e.png)

**Comment by fega** [comment]
Could you check if this is still an issue with the last version?
Closed due inactivity, feel free to reopen it if it is still necessary.
