### ISSUE TITLE
TypeError: Cannot read property 'hash' of undefined

### ISSUE THREAD

**Issue by Vaalyn** [Dogfalo/materialize#2834]
When using Materialize in combination with the standard Wordpress + WooCommerce Plugin the materialize.js throws a TypeError on line 1213 on the single product page of a WooCommerce product.

This part throws the error: `$content = $($active[0].hash);`

It seems like WooCommerce's product tabs area is responsible for this error.

This is the standard product tabs area html: http://pastebin.com/ywDQWup1

I could fix the problem by replacing:
`$content = $($active[0].hash);`

With this:

```
if ($active[0] !== undefined) {
    $content = $($active[0].hash);
}
```

and on Line 1252 I replaced this part:
`$content.hide();`

With this:
```
if ($content !== undefined) {
    $content.hide();
}
```

**Comment by acburst** [comment]
Merged thanks!

**Comment by engelsarx** [comment]
Thanks! it´s working!
