### ISSUE TITLE
Collections disregard Material design spec

### ISSUE THREAD

**Issue by 13k** [Dogfalo/materialize#2837]
At current state, collections are mostly unusable for almost every case a list would be used.
- It isn't supposed to have borders

The [List spec](https://www.google.com/design/spec/components/lists.html) doesn't even mention the word "border".
- It isn't supposed to have full-bleed dividers for every item by default

The [Dividers spec](https://www.google.com/design/spec/components/dividers.html#dividers-usage) clearly states you shouldn't overuse full-bleed dividers:

![2016-02-24 at 11 56 am](https://cloud.githubusercontent.com/assets/4762/13289170/c6fa2b22-daed-11e5-9474-69d7e18a3d7b.png)

Collections should not decide anything about dividers, it should be up to the client to create and use them inside lists (pretty much like creating a `.divider` element inside a collection).

**Comment by djensen47** [comment]
First, Materialize is a great library, kudos to the team who built it.

However, I agree with @13k "collections" doesn't follow the material design spec. In fact, it really should be called Lists, no?

**Comment by tomscholz** [comment]
See https://github.com/Dogfalo/materialize/pull/4727

**Comment by 13k** [comment]
nice! I suppose we can close this one then?

**Comment by tomscholz** [comment]
I would keep it open until we have discussed, if want to merge or declined the PR.

**Comment by chuckdries** [comment]
Quick Q: Is this refactor going to bring the sidebar's list stuff in line with the rest of materialize? I've been really frustrated lately juggling between collections and sidebar lists that contain the same content but have totally different capabilities. Collections feel so limited, I can't even get links to work with secondary content, whereas the sidebar list just works.

**Comment by 13k** [comment]
I'm cleaning up my open issues and this one seems like it's stale/fixed. Feel free to reopen if this is a mistake.
