### ISSUE TITLE
support for a module loader i.e. UMD?

### ISSUE THREAD

**Issue by tnguyen14** [Dogfalo/materialize#284]
It would be great if the syntax support a module loader, for e.g. using UMD (https://github.com/umdjs/umd). Personally, I'd like to be able to include materialize.js or a component as a CommonJS module and let browserify do the bundling.

**Comment by slaivyn** [comment]
:+1: I would like to import it using browserify

**Comment by lee-40square** [comment]
+1 Materialize is published to NPM, but it's not CommonJS compliant so it can't really be used in that fashion.

I can't easily use it in my build process. Actually, even in Bower I can't easily use it in my build process. This is even more important for projects using AngularJS.

**Comment by piuccio** [comment]
Or JSPM :smile:

**Comment by carloscarcamo** [comment]
I'm using materialize with Browserify, but since materialize is not just a js file, you still need to include manually the css file in order get materialize working, for using materialize.js with browserify take a look a this issue #923

**Comment by rogue780** [comment]
Making this browserifiable would make my life infinitely better. +1

**Comment by KenGorab** [comment]
For the browserify users out there, you can use (browserify-shim)[https://github.com/thlorenz/browserify-shim] to "inject" dependencies into modules that aren't explicitly `require`d in within the module. It's not an idea solution, but such a strategy is often used with non-CommonJS/AMD modules I've found.

**Comment by fega** [comment]
Moved to https://github.com/Dogfalo/materialize/projects/3

**Comment by fega** [comment]
#2085 related

**Comment by tomscholz** [comment]
Closed due inactivity. Feel free to reopen it, if it's still necessary.
