### ISSUE TITLE
Form error messages break to 2 lines

### ISSUE THREAD

**Issue by moshest** [Dogfalo/materialize#2842]
![fireshot capture 12 - - file____home_ms_git_ventures_fluxteam_template_signup html](https://cloud.githubusercontent.com/assets/534911/13354476/f1b4d51c-dca3-11e5-86b2-37cabd86d518.png)

It's breaks to 2 lines because the `::after` content is bigger then the `label` width.

You can solve it by adding "nowrap" rule:
```
... label::after {
  white-space: nowrap;
}
```

**Comment by Kail0** [comment]
But this can lead to ugly behaviour on mobiles...

**Comment by moshest** [comment]
Good point. We can disable it on small screens via `@media`.

**Comment by Dogfalo** [comment]
Already fixed
