### ISSUE TITLE
Collapsible doesn't expand

### ISSUE THREAD

**Issue by LucciSMo** [Dogfalo/materialize#2844]
I am trying to use collapsible ,but when I click into item expandable the collapsable-body shows but it  hides automatically at .05 seconds

Im using  Materialize v0.97.5 on Header from min.js and min.css

**Comment by Dogfalo** [comment]
Check over your html structure.maybe you have an included div which is
nearing the event handlers

**Comment by LucciSMo** [comment]
I found my error , I was adding the min.js and min.css two times on the document. 

Thanks.

**Comment by dkent600** [comment]
I am encountering the same problem, and I am not including anything twice.
