### ISSUE TITLE
Dropdown not working on Chrome (48.0.2564.104) on iOS (9.2.1)

### ISSUE THREAD

**Issue by ianwensink** [Dogfalo/materialize#2850]
The selectbox is not opening on an iPhone iOS 9 using a Chrome Browser. Chrome seems to focus, but there isn't happening anything. Working perfectly in Safari and Chrome on Android.

**Comment by fega** [comment]
What version are you using? it looks fixed in the current version?
Thanks
Closed due inactivity, feel free to reopen it if it is still necessary.
