### ISSUE TITLE
Add JS helper classes to make creating interactive data driven lists and multi-lists easy

### ISSUE THREAD

**Issue by sam-g-steel** [Dogfalo/materialize#2851]
<img width="1021" alt="screen shot 2016-02-28 at 3 48 05 pm" src="https://cloud.githubusercontent.com/assets/10963749/13382149/d4c95cbc-de32-11e5-9451-f88db5450811.png">

<img width="1026" alt="screen shot 2016-02-28 at 3 48 48 pm" src="https://cloud.githubusercontent.com/assets/10963749/13382219/b9c8969c-de34-11e5-8d97-9f53e148673e.png">

see fork...
-- https://github.com/sam-g-steel/materialize/tree/JS-list-classes
-- https://rawgit.com/sam-g-steel/materialize/JS-list-classes/advancedcollections.html

I am currently working on more examples but here is one...
http://codepen.io/sam-g-steel/pen/JXPMoY/?editors=0010

**Comment by sam-g-steel** [comment]
The links above show the helper classes that I've been working on.

Here is a quick example of how to use this class.

<div id="lst1">

var data = [
   {text: "Mobile Bay", value: 1 }, 
   {text: "Pensacola",  value: 2 },
   {text: "FT Walton",  value: 3 },
   {text: "Gulf Port",  value: 4 }
];

var MyList = new DataList("text", "value", data).setName("City").bindToData();

$("#lst1").replaceWith(MyList.renderToHTML());

**Comment by fega** [comment]
@sam-g-steel Hello, I believe that this is out of the materializeCSS scope, but could be great as a plugin.

**Comment by sam-g-steel** [comment]
@fega OK, thanks... I've been away from materializeCSS for a bit... I've been doing slot of Feb with react.
