### ISSUE TITLE
Tooltips are not working on switch 

### ISSUE THREAD

**Issue by vaishali-ghayal** [Dogfalo/materialize#2852]
TypeError: Materialize.guid is not a function
var tooltipId = Materialize.guid();

**Comment by acburst** [comment]
Please post a more comprehensive example

**Comment by vaishali-ghayal** [comment]
I have upgraded materialize to 0.97.5 version.With this whenever I am trying to use tooltips or select element  it's throwing error TypeError: Materialize.guid is not a function.

**Comment by acburst** [comment]
Can you post the code that is causing the error I mean
