### ISSUE TITLE
Cant call modal  from inside php

### ISSUE THREAD

**Issue by tceydeliler** [Dogfalo/materialize#2853]
Hi,
Altough I can open moel inside html, I cant call same modal from php

`if (isset($_POST["btn_submit"])) {
		$result= authenticateAdmin($_POST["username"],$_POST["password"]);
		      
  			if ($result > 1000) {  
			header("Location: admin.php");
			}
			elseif($result == 0) {
			$err_msg=$error2;
			echo "<script type='text/javascript'>$('#modalLockAccount').openModal();</script>";
			}`

or

`if (isset($_POST["btn_submit"])) {
		$result= authenticateAdmin($_POST["username"],$_POST["password"]);
		      
  			if ($result > 1000) {  
			header("Location: admin.php");
			}
			elseif($result == 0) {
			$err_msg=$error2;
			echo "<script >$('#modalLockAccount').openModal();</script>";
			}`
Is th,s a bug  or do I add somethng to my code?

**Comment by MetaiR** [comment]
can you use ajax?

**Comment by tceydeliler** [comment]
I solved it.
When I make DOM readyi it works.
Thank you.
