### ISSUE TITLE
map not loading in modal

### ISSUE THREAD

**Issue by nasr18** [Dogfalo/materialize#2854]
i want to add map to get location from the user using modal. but map not loading. please tell me solution fast please.

**Comment by sam-g-steel** [comment]
Have any details, like what map library you're using?
Any links to a website that exhibits this behavior?

**Comment by nasr18** [comment]
using google map api "http://maps.googleapis.com/maps/api/js?libraries=places" and using div #map-canvas to bind map view.

**Comment by maxflex** [comment]
My guess is that you have to fire a `map.resize()` event every time you open a modal

**Comment by nasr18** [comment]
can you give some sample coding?

**Comment by Dogfalo** [comment]
The map is maybe not able to calculate the height when the modal is display: none. Just call map.resize() after the modal is shown.

**Comment by nasr18** [comment]
no success dude. i did whatever i have to do. but no success.  :(

**Comment by Dogfalo** [comment]
You just need to do what is described here.
http://stackoverflow.com/questions/10197128/google-maps-api-v3-not-rendering-competely-on-tabbed-page-using-twitters-bootst

On Sun, Mar 13, 2016 at 10:30 PM, Mohamed Nasrullah <
notifications@github.com> wrote:

> no success dude. i did whatever i have to do. but no success. :(
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Dogfalo/materialize/issues/2854#issuecomment-196150730>
> .
>



-- 
Doggy sends his greetings from Mars.

**Comment by nasr18** [comment]
Dude i found the issue that when is map loading in modal. Actually if the page contains map and if we open a modal with map div in it means, the map in modal is not displaying untill we resize the window. If we resize the window means map is displaying in modal. How to fix this???
