### ISSUE TITLE
wave problem on linux browsers

### ISSUE THREAD

**Issue by MetaiR** [Dogfalo/materialize#2858]
hi
we have a bad response for wave effects on linux browsers
(i tested on elementryOs and firefox 44)

**Comment by Dogfalo** [comment]
Please be more descriptive of what the problem is.

**Comment by MetaiR** [comment]
the animation is not happend correctly. every time has new problem in animation's effect

**Comment by MetaiR** [comment]
the animation is not happend correctly. every time has new problem in animation's effect

**Comment by fega** [comment]
Please provide a way to reproduce/visualize it. like a [codepen](https://codepen.io/fega/pen/BWeZaG) or  at least a gif

Closed due inactivity, feel free to reopen it if it is still necessary.
