### ISSUE TITLE
Website fix

### ISSUE THREAD

**Issue by rppgoud** [Dogfalo/materialize#2859]
Hi materlize team,

This issue, i found in all the pages, so you can restrict the side menu upto some extend, with out over lapping it on the footer, it will look akward, so if you fix, it might look pretty. 

![materlizefault](https://cloud.githubusercontent.com/assets/13496134/13425993/a56e34b6-dfd0-11e5-91c0-bb76a94c905b.png)

**Comment by acburst** [comment]
Fixed in e8b16c6
