### ISSUE TITLE
Font other than Roboto

### ISSUE THREAD

**Issue by aviemet** [Dogfalo/materialize#2863]
It would be nice to have Roboto be a little less coupled from the main build. I would like to have a few variables which would allow me to set the fonts I want to use, one for sans, one for serif and one for mono-space.

If Roboto is going to be a default, would it be unreasonable to reference it remotely using an import statement from Google's webfonts? This would alleviate the need to have a separate `_roboto.scss` file and a variable for `$roboto-font-path`. With the three variables I mentioned above, we would then be able to import and assign our font choices without needing to decouple Roboto from the source files.

Though I understand that using a remote import in a framework may not be ideal. Perhaps there's a good middle ground.

**Comment by cjaoude** [comment]
i just noticed this too; just trying this framework.

the font shouldn't even be a local dependency. it should be imported in straight from Google Fonts

and ya, make it a var

**Comment by gagalago** [comment]
yes make it a var :)

**Comment by tomscholz** [comment]
https://github.com/Dogfalo/materialize/pull/4393

**Comment by gagalago** [comment]
Yes, it's one thing. The other is the ability to not compile roboto inside materialise if roboto is not used. Because fonts are heavy, if a font is not used, it's not a good option to have the declaration of `@font-face`.

**Comment by tomscholz** [comment]
@gagalago If you don't want roboto compiled, you can easily remove it from the materialize.scss and compile it yourself

**Comment by uok** [comment]
Modern browsers only load fonts if they are used. So you can just set fonts in your own override.css
