### ISSUE TITLE
Feature request: Detach or disable pushpin if pinned is bigger viewport

### ISSUE THREAD

**Issue by mblarsen** [Dogfalo/materialize#2866]
The ability to detach or disable the pushpin in case the pinned element is too big for the viewport.

Problem: Content in pinned content goes outside viewport making it unreachable. 

Preferably a solution that watches viewport and resize event. If not just an option to unpin.

**Comment by acupajoe** [comment]
@mblarsen #3179

**Comment by acburst** [comment]
Merged
