### ISSUE TITLE
Overwriting variables and colours

### ISSUE THREAD

**Issue by stueynet** [Dogfalo/materialize#2867]
I am importing materialize into my main app.scss file as follows:

```
@import "bower_components/Materialize/sass/materialize";
@import "variables";
@import "colors";
```

Also tried:

```
@import "variables";
@import "colors";
@import "bower_components/Materialize/sass/materialize";
```

I am trying to overwrite colors by having my own local colors file as I used to do with bootstrap. However it does not seem to effect anything. I can always just copy the entire folder to my project but I would prefer to leave it within bower and simply overwrite in my application.

If I declare variables in my local variables file, it works just fine. However I cannot seem to update the colours. For example in my colors file:

```
$teal: (
        "base":       #009688,
);
```

This has no effect. The library still builds with the colors defined within the bower_components color.scss file.

Any thoughts on why this would not be working?

**Comment by overbyte** [comment]
i ended up creating my own materialize.scss with the imports and adding my colors & variables after the materialize variables import so they got overridden before the rest of the sass was implemented

**Comment by stueynet** [comment]
Thanks @overbyte. I guess thats what I was trying to avoid but I will go ahead with that for now. Cheers!

**Comment by Dogfalo** [comment]
How are you defining your variables? As long as you don't have default on
then it should work.

**Comment by stueynet** [comment]
So the variables overwrite is working fine. But the colors do not have any effect. Example:

```
$teal: (
        "base": #274d96,
);
```

Doesn't change the teal color.

**Comment by web-4-u** [comment]
I've got the same problem here. I'm using bower and gulp. 

Gulp code
`gulp.task('sass', function () {
	return gulp.src('./src/scss/app.scss')
		.pipe(sourcemaps.init())
		.pipe(sass({
			includePaths: "./bower_components/materialize/sass"
		}).on('error', sass.logError))
		.pipe(sourcemaps.write())
		.pipe(gulp.dest('./assets/css'));
});`

Scss code
`@import 'settings';
@import 'materialize';`

Settings code
`$blue: (
	"base":       #007FC0,
	"lighten-5":  #E3F2FD,
	"lighten-4":  #BBDEFB,
	"lighten-3":  #90CAF9,
	"lighten-2":  #64B5F6,
	"lighten-1":  #42A5F5,
	"darken-1":   #1E88E5,
	"darken-2":   #1976D2,
	"darken-3":   #1565C0,
	"darken-4":   #0D47A1,
	"accent-1":    #82B1FF,
	"accent-2":    #448AFF,
	"accent-3":    #2979FF,
	"accent-4":    #2962FF
);`

The only way I managed to make it work was to add "!default" after $blue variable declaration in Materialize Bower component file. Which makes no sens at all (modify original file).

Why color declaration don't have !default in sass original file ?

Thanks

**Comment by ezkay** [comment]
This is needed so bad to get implemated properly.. Would avoid of recoloring all buttons etc with the color-class.

**Comment by tomscholz** [comment]
Closed due inactivity. Feel free to reopen it, if it's still necessary.
