### ISSUE TITLE
Tabs Inside Modal. Bottom bar appears on both tabs

### ISSUE THREAD

**Issue by sandeshdesigns** [Dogfalo/materialize#2871]
Hi , 
I am trying to code tabs inside the popup modal. Tab selection appears on both. I have pasted the code and screenshot
  `<div id="modal1" class="modal">
        <div class="modal-content">
            <div class="row">
                <div class="col s12">
                    <ul class="tabs">
                        <li class="tab col s6"><a href="#test1">Test 1</a></li>
                        <li class="tab col s6"><a href="#test2">Test 2</a></li>
                    </ul>
                </div>
                <div id="test1" class="col s12">Test 1</div>
                <div id="test2" class="col s12">Test 2</div>
            </div>
        </div>
    </div>`

And my jq code is 

'$('ul.tabs').tabs('select_tab', 'test1');
        $('.modal-trigger').leanModal();'
please find the image below for the issue where both the tabs are selected when the modal is loaded
![image](https://cloud.githubusercontent.com/assets/17606782/13482847/8c5226fe-e115-11e5-967e-b4a54bb00ae7.png)

**Comment by acburst** [comment]
Try
```
$('.modal-trigger').leanModal({ready: function() {
  $('ul.tabs').tabs('select_tab', 'test1');
}});
```
