### ISSUE TITLE
Hide classes and reflow on orientation change

### ISSUE THREAD

**Issue by burnaDLX** [Dogfalo/materialize#2873]
First, I love materialize, it's a really great framework. But I have a problem with the hide-classes.

```
.hide-on-small-only
.hide-on-small-and-down
.hide-on-med-and-down
.hide-on-med-and-up
.hide-on-med-only
.hide-on-large-only
.show-on-large
.show-on-medium
.show-on-small
.show-on-medium-and-up
.show-on-medium-and-down
```

I know these classes use `display:none !important` and therefore the browser doesn't calculate the size off the hidden elements while painting the site. But if I change the orientation e.g from portrait to landscape on a phone and the class is no longer valid, displaying the former hidden element totally messes up my layout. Wouldn't it be better to use something like this:

```
@media only screen and (max-width : 600px){
    .hide-on-small-only, .hide-on-small-and-down {
        height: 0 !important
        visibility: hidden !important
        overflow:hidden !important;
    } 
}
```

So losing the validity of a class doesn't have this kind of negative side effects or am I missing something?

**Comment by acburst** [comment]
The point of using display none is so that things can reorder. It should be used in conjunction with our grid system. So for example something like:

```
<div class="col m4 hide-on-small-and-down"></div>

<div class="col m8 s12"></div>
```

Would not just have some invisible div taking up space. If you are having problems with this do you mind sharing some code?

**Comment by burnaDLX** [comment]
Sure I can share some code... 

**How it does not work**

```
<div class="section">
    <div class="row container">
        <div class="col s12 m10 push-m1 l8 push-l2">
          <!-- headline goes here -->
        </div>
    </div>

    <!-- hidden on mobile -->
    <div class="hide-on-small-only">
        <div class=row>
            <div class="col s12 m10 push-m1 l6 push-l3">
                <!-- markup hidden on mobile goes here -->
            </div>
        </div>
        <div class=row>
            <div class="col s12 m10 push-m1 l6 push-l3">
                <!-- markup hidden on mobile goes here -->
            </div>
        </div>
        <div class=row>
            <div class="col s12 m10 push-m1 l6 push-l3">
                <!-- markup hidden on mobile goes here -->
            </div>
        </div>
    </div>

</div>


<!--this markup slips to the top and over the
former hidden container on orientation change -->
<div class="section cream-bg center-align about-us-section">
    <div class="row container">
        <div class="col s12 m10 push-m1 l8 push-l2">
            <!-- headline goes here -->
        </div>
    </div>
    <div class="row ">
        <div class="col s12 m10 push-m1 l6 push-l3">
            <!-- some other markup goes here -->
        </div>
    </div>
</div>
```


Portrait
![image](https://cloud.githubusercontent.com/assets/12218103/13525798/d78e9848-e203-11e5-9eee-58e63f907de3.png)

Landcape
![image](https://cloud.githubusercontent.com/assets/12218103/13525811/f4858bd2-e203-11e5-97ae-56a12991640c.png)



but if I modified the class
```
/*css*/
@media only screen and (max-width : 600px){
    .hide-on-small-only, .hide-on-small-and-down {
        height: 0 !important
        visibility: hidden !important
        overflow:hidden !important;
    } 
}
```

it works 

Landcape
![image](https://cloud.githubusercontent.com/assets/12218103/13525894/75f888b8-e204-11e5-987c-356bc392bb53.png)

Even if it's not the better way, maybe this helps someone, who is struggling with the same problem.
