### ISSUE TITLE
different colors for different toasts

### ISSUE THREAD

**Issue by nasr18** [Dogfalo/materialize#2876]
I would like to show the toast like "Saved Successfully", "Please check your entry" and so on. for each information i wanna popup toast with different colors. For successfull message, toast color wanna be green, for error it should be red and so on.

**Comment by Kail0** [comment]
It's in the documentation - [dialogs](http://materializecss.com/dialogs.html)

> **Styling Toasts**
`Materialize.toast('I am a toast!', 3000, 'blue') // 'blue' is the class I'm applying to the toast for color`

**Comment by nasr18** [comment]
thanks dude. i got it. but i also need 'rounded' class along with color class. how to do????

**Comment by sam-g-steel** [comment]
``` javascript
Materialize.toast('I am a toast!', 3000, 'blue rounded') 
```

Like @Kail0 mentioned... It's in the documentation - [dialogs ](http://materializecss.com/dialogs.html)

**Comment by ragnarok22** [comment]
isn't in this direction [dialogs](http://materializecss.com/dialogs.html).

**Comment by santafebound** [comment]
Yeah a little blurb on color should be included in the documentation. It's not there currently.

**Comment by NitroBAY** [comment]
I didn't understand, until I come across here, that we can customize the color of toasts.

**Comment by freddy-daniel** [comment]
I agree you can change colors.but how to set my custom color by  HEX code like #3a4a61

**Comment by Dogfalo** [comment]
in your css file, you can define a class and then set this class in JS

**Comment by freddy-daniel** [comment]
I already got it thanks man.

**Comment by EzequielValencia** [comment]
ddd

**Comment by Gnanam12** [comment]
can i use colours directly in my javascript helper class?

**Comment by Dogfalo** [comment]
No that will not work

**Comment by shunjid** [comment]
In **Updated Version**, It's something like:

```
M.toast({
html: 'Data updated Successfully',
classes: 'green darken-1 rounded'
});
```

**Comment by shunjid** [comment]
In Updated Version, It's something like:

```javascript
M.toast({
html: 'Data updated Successfully',
classes: 'green darken-1 rounded'
});
```

**Comment by Jalkhov** [comment]
> 
> 
> In Updated Version, It's something like:
> 
> ```js
> M.toast({
> html: 'Data updated Successfully',
> classes: 'green darken-1 rounded'
> });
> ```

Perfect

**Comment by Owolabi-Oluwatosin** [comment]
How can I add border: 2px blue solid; to the toast? I want the background-color to be white while the border color to be red or green depending on the type of message

**Comment by Natali-story** [comment]
Just in case if someone still face issues with customize toasts on Materialize .
Just add on the HTML page <style>
<style>     
#toast-container {
  top: auto !important;
  right: auto !important;
  bottom: 40%;
  left:40%;  
  }
.toast {
    background-color: #26a69a !important;
}
</style>
