### ISSUE TITLE
#sidenav-overlay showes up above .side-nav

### ISSUE THREAD

**Issue by ezkay** [Dogfalo/materialize#2879]
Hi,

the `#sidenav-overlay showes` up above the slide out `.side-nav` (see screenshot).

I'm wondering how to fix this? Is it the right way to just set the following css?

```
#sidenav-overlay {
    left: 240px;
}
```

![bildschirmfoto 2016-03-05 um 16 09 08](https://cloud.githubusercontent.com/assets/10404121/13548284/ab06b370-e2ec-11e5-918a-7611d70ec4e6.png)

**Comment by diegogurgel** [comment]
Hi @ezkay  same occurs here so i just called open and close programatticaly: 
`$('.button-collapse').sideNav('show');`
`$('.button-collapse').sideNav('hide');`

**Comment by Uzzije** [comment]
@ezkay overide side-overlay z index in your own css file
#sidenav-overlay {
    z-index: 1;
}
make sure that your css file comes after materialize own css file

**Comment by vpezeshkian** [comment]
That's not the best approach, modifying css is not encouraged, especially when you have other widgets on the screen such as FAB buttons.

Anyway the issue persisted even though the z-index on layover is 998 and the menu 999

**Comment by 441N143G** [comment]
z-index: 996 works perfectly

**Comment by PeteOliveira** [comment]
Thanks for both suggestions!  The following worked for me.

#sidenav-overlay {
    z-index: 996;
}

**Comment by xylude** [comment]
I had the same problem, and after digging around I realized that if you put the .side-nav inside of the .navbar-fixed component the z-index for .navbar-fixed will override the one set on .side-nav. I fixed this without messing about with the css by moving the .side-nav component out of the .navbar-fixed one.

The lesson learned here is even if you aren't using the .navbar-fixed class, it might be some other parent causing your z-index to be wrong on the .side-nav.

Hope this helps!

**Comment by DBPreston** [comment]
@xylude's fix worked for me - far better than overriding the z-index in CSS (which didn't work in 0.98.0 anyway). This should maybe referred to in docs.

**Comment by tomscholz** [comment]
I would never recommend to change the z-index. When using the fixed navbar you have to move the mobile sidenav outside the nav sector. Anyway. This is a duplicate to https://github.com/Dogfalo/materialize/issues/3844. Please Close or create a PR that fixes this issue. Thanks :)

**Comment by tomscholz** [comment]
These issues are all duplicates:
https://github.com/Dogfalo/materialize/issues/1664
https://github.com/Dogfalo/materialize/issues/3918
https://github.com/Dogfalo/materialize/issues/4046
https://github.com/Dogfalo/materialize/issues/4231
https://github.com/Dogfalo/materialize/issues/437
https://github.com/Dogfalo/materialize/issues/4318
https://github.com/Dogfalo/materialize/issues/3982
https://github.com/Dogfalo/materialize/issues/2879
https://github.com/Dogfalo/materialize/issues/4187

For the future discussion, please use this issue instead.
https://github.com/Dogfalo/materialize/issues/3844

**Comment by cedric858** [comment]
@xylude's fix worked for me too, thx a lot! So shouldn't they update their materializer's documentation and mention this case of figure  when people use the navbar or sidenav component?

**Comment by tomscholz** [comment]
Woops, sorry. Wrong issue
