### ISSUE TITLE
Tabs don't work with variable tab size

### ISSUE THREAD

**Issue by WilbertE** [Dogfalo/materialize#2886]
The tabs indictator doesn't work with variable tab sizes.
The size of the indicator is always the size of the frist column and isnt updated.

`<li class='tab col s5'>tab1</li>
<li class='tab col s6'>tab2</li>
<li class='tab col s1'>tab3</li>`

**Comment by WilbertE** [comment]
Fixed it and made a pull request. (first time ever so I hope I did it the right way).
https://github.com/Dogfalo/materialize/pull/2887

**Comment by acburst** [comment]
Variable width tabs added in 8be878359048e84c6494a3682d10a966766536b2
