### ISSUE TITLE
Jquery unobtrusive validation does not work with some inputs.

### ISSUE THREAD

**Issue by Sectar** [Dogfalo/materialize#2890]
Some forms are processing incorrect with jquery unobtrusive validation.

For example:
I am developing web app (ASP.Net MVC 5, Jquery 2.2.1, Jquery Validation 1.14.0, Jquery Unobtrusive Validation 3.2.3) and i have next model class:

`public class PersonalInfo
    {
        [Required(AllowEmptyStrings = false, ErrorMessage = "Field can not be empty")]
        [StringLength(40, ErrorMessage = "First name is too long. Please enter a shorter first name.")]
        public string FirstName { get; set; }.
    }`

How we can see there is 2 validation attribures. What will rendererd in html:

`<div class="row margin-0">
                <div class="input-field col s12">
                    <i class="mdi-social-person-outline prefix"></i>
                    <input data-val="true" data-val-length="First name is too long. Please enter a shorter first name." data-val-length-max="40" data-val-required="Field can not be empty" id="first-name" name="FirstName" type="text" value="Fred" class="input-validation-error">
                    <label class="center-align" for="first-name">First name</label>
                    <span class="field-validation-error" data-valmsg-for="FirstName" data-valmsg-replace="true"><span for="first-name" class="">Field can not be empty</span></span>
                </div>
            </div>`

And after that magic starts =)  If I am typing into input nothing happens ultil text length less than 40 symbols. After that unobtrusive validation works well. But before that validation does not react on required attribute.

**Comment by fega** [comment]
Please provide a way to reproduce it and see it in action. like a codepen or  a fiddle snippet
Closed due inactivity, feel free to reopen it if it is still necessary.
