### ISSUE TITLE
Question: why do tabs need ids? (vs passing in elements)

### ISSUE THREAD

**Issue by pajtai** [Dogfalo/materialize#2892]
The [docs](http://materializecss.com/tabs.html) for tabs says that to programmatically trigger a tab change, you need to pass in an id:

``` javascript
$('ul.tabs').tabs('select_tab', 'tab_id');
```

Why can't you pass in a css selector or dom element or jQuery object? Seems like it would be very convenient and easy to implement?

Would a PR to change [select_tab](https://github.com/Dogfalo/materialize/blob/master/js/tabs.js#L117) from:

``` javascript
    select_tab : function( id ) {
      this.find('a[href="#' + id + '"]').trigger('click');
    }
```

to 

``` javascript
    select_tab : function( selected ) {
      $($(selected), this).trigger('click');
    }
```

be useful?

Just running into a situation where I have a handle on the elements, but don't want to create ids.

Think the above change could handle passing in an id, selector, dom element, or jQuery object.

**Comment by tomscholz** [comment]
@DanielRuf Your opinion on this?

**Comment by DanielRuf** [comment]
This is not backwards compatible.

> You can programmatically trigger a tab change with our select_tab method. You have to input the id of the tab you want to switch to. In the case of our demo it would be either test1, test2, test3, or test4.
