### ISSUE TITLE
RequireJs Issue: Error: Mismatched anonymous define() module

### ISSUE THREAD

**Issue by oceanwap** [Dogfalo/materialize#2893]
You are using anonymous define in distribution and bin files. It's causing error while using with requirejs.

**Comment by bery** [comment]
I am facing the same issue - did you manage to find a solution to that?

**Comment by oceanwap** [comment]
I stopped using JS file provided in this distribution.

**Comment by bery** [comment]
Oh, ok. And could you share more information on how did you build/create the file?

**Comment by fega** [comment]
Closed due inactivity, feel free to reopen it if it is still necessary.
