### ISSUE TITLE
Collapsible preselected section causes unnecessary CSS reflows

### ISSUE THREAD

**Issue by isaachinman** [Dogfalo/materialize#2895]
Been using the framework for a while and just noticed this rather glaring oversight. Collapsible.active is opened by JavaScript, so the "preselected" section actually opens after doc ready, and causes unnecessary CSS reflows.

[Here's a JsFiddle to exemplify what I mean.](https://jsfiddle.net/nrLkwxu6/)

I think there should be a CSS declaration in place here to prevent reflows. Seems like a simple/logical refinement.

For the moment in my own projects, I've added an additional CSS declaration:

```
.collapsible-body.active {
  display: block
}
```

Then just add an "active" class to any .collapsible-body you want to be open on pageload. This prevents CSS reflows.

**Comment by fega** [comment]
I didn't get what is the problem that is showed I see all as expected :sweat: 


Closed due inactivity, feel free to reopen it if it is still necessary.
Thanks
