### ISSUE TITLE
Uncaught ReferenceError: Vel is not defined

### ISSUE THREAD

**Issue by aldofunes** [Dogfalo/materialize#2897]
I am having this problem. When I call `Materialize.toast('I am a toast!', 3000, 'rounded')` I get the following exception:
````
Uncaught ReferenceError: Vel is not defined(…)
  Materialize.toast @ toasts.js:26
  (anonymous function) @ VM66596:2
  InjectedScript._evaluateOn @ VM66436:875
  InjectedScript._evaluateAndWrap @ VM66436:808
  InjectedScript.evaluate @ VM66436:664
````
I am sure Velocity is loaded and all.

I am using the latest src files including the js files.

**Comment by Kail0** [comment]
Are you trying to do it in Wordpress?

**Comment by aldofunes** [comment]
I am using Meteor. In another project I am using the Atmosphere package and all works well. In both I have jQuery 1.11.4

**Comment by aldofunes** [comment]
I gave up and simply went back to using the atmosphere package. It works well.

**Comment by Kail0** [comment]
Sorry for late answer... You have definitely deprecated version of jQuery.
You need at least version [version 2.x](https://jquery.com/download/#jquery-2-x)
