### ISSUE TITLE
Tooltip freezes after an ajax update in form

### ISSUE THREAD

**Issue by darckyn** [Dogfalo/materialize#2901]
Hello.

I'm just reporting a strange behavior of the tooltip.

When I run an Ajax update on the button that is active with a tooltip, and let the mouse pointer stopped on that same button, the tooltip of that button freezes the screen and for working any tooltip of other buttons.

Running javascript to remove the tooltip, nothing happens, but if I run javascript to update the tooltip, it returns to normal but the old tooltip prevails frozen on the screen.

These are the javascript I'm using:

$('.tooltipped').tooltip({delay: 50});
and
$('.tooltipped').tooltip('remove');

My solution was not to use a tooltip in buttons with Ajax actions that update an entire form.

btw thx for materialized :)

**Comment by merlano17** [comment]
That's one of the bug which happens all the time, when a tooltip is re-initialized this happens

This bug is similar to https://github.com/Dogfalo/materialize/issues/2818

**Comment by merlano17** [comment]
Till the admins fix that issue 

This simple function you can use to remove all those frozen tooltips
```
setInterval(clearTooltip, 6000);
function clearTooltip() {
    $('.material-tooltip').hide();
  }

Every 6 seconds it will run the function and makes sure that there is no frozen tooltips on the screen

**Comment by darckyn** [comment]
Thanks for stopgap solution, but I will continue to not use tooltips until this error is eliminated

Let's hope that the creators find a solution to stop this error.

**Comment by KonstantinKolodnitsky** [comment]
This happens to me when I disable button programmatically on click event.

    disableButton: function (button) {
        button.setAttribute('disabled', true);
    },

**Comment by darckyn** [comment]
Hello @KonstantinKolodnitsky .

You can fix this by disabling the tooltip with the button at the same time.
Here is a examble code:

`$(document).ready(function() {
    $('#button_click').click(function(event){
        $(this).attr('disabled', true);
        $(this).tooltip('remove');
    });
});`

[https://jsfiddle.net/xyLtztbb/1/](url)

**Comment by KonstantinKolodnitsky** [comment]
Hi @darckyn 
That's not a solution.

I don't want to remove the tooltip. In my case the button shows/hides the form, so a user may click on it many times.

**Comment by Dogfalo** [comment]
https://github.com/Dogfalo/materialize/issues/1702

**Comment by fernando4530** [comment]
Hello team;
This solution that Dogfalo mentioned is an alternative JQUERY solution.
So, will there be a native solution for this?

Thank you

**Comment by Dogfalo** [comment]
The native solution in 1.0 is to destroy the tooltip using the plugin method before removing the origin of the tooltip from the dom
