### ISSUE TITLE
Last Tab adds a Scroll

### ISSUE THREAD

**Issue by Utkarshbhimte** [Dogfalo/materialize#2902]
When clicked the last tab in mid to small screen, a Horizontal Scroll is created within the ul. Please look into it

![screenshot 2](https://cloud.githubusercontent.com/assets/13379773/13720713/b9f1e0aa-e835-11e5-98b7-760420cf628f.png)
![screenshot 3](https://cloud.githubusercontent.com/assets/13379773/13720714/b9f20e90-e835-11e5-8df9-7ded75dbc26b.png)
![screenshot 1](https://cloud.githubusercontent.com/assets/13379773/13720712/b9f1a96e-e835-11e5-9265-e092eadd51d3.png)

**Comment by NeilCresswell** [comment]
See same issue on larger screens too.
Tested on Chrome 49.0.2623.87 m (64-bit) with latest Materialize as of yesterday.

Dirty quick fix was to add this to my CSS:
ul.tabs {overflow: hidden; }

**Comment by Thanood** [comment]
That seems to be a calculating problem as mentioned in #2635 and #2584.

**Comment by acburst** [comment]
Fixed in 4f18709
