### ISSUE TITLE
[URGENT] search navbar in IE 11 bug

### ISSUE THREAD

**Issue by NitroBAY** [Dogfalo/materialize#2903]
In IE 11 the navbar search is totaly buggy (with all zoom). The input field is only in very top of the bar... http://imgur.com/BGo6LdL please note that the bug is present when I use the official website and also when I try the code on my side... I'm waiting the bug to be fix before launching my project in prod.

**Comment by NitroBAY** [comment]
Up

**Comment by NitroBAY** [comment]
I also have this bug in chrome on android ...

**Comment by NitroBAY** [comment]
Still not solved

**Comment by AlvaroLQueiroz** [comment]
I have the same problem in linux chrome v50. I fixed using:

nav .nav-wrapper form, nav .nav-wrapper form .input-field{
   height: 100%;
}

**Comment by acburst** [comment]
Merged c129dc1
