### ISSUE TITLE
Tabs created dynamically

### ISSUE THREAD

**Issue by fredericoregateiro** [Dogfalo/materialize#2904]
Hello,

I've been working with Materialize and it's a great library.

I have had some difficulties with tabs created dynamically.

I've created a codepen with the problems
http://codepen.io/regateiro/pen/WwGwLO

**Comment by itsmesiddhant** [comment]
I think the problem is with a line in your getHtml() function . You have applied a class="active" in your anchor element that is causing the error.

    '<li class="tab col s3"><a class="active" href="#test2">Test 2</a></li>' 
   just make a small change
 '<li class="tab col s3"><a href="#test2">Test 2</a></li>'

**Comment by fredericoregateiro** [comment]
Good point, i've just missed that active class.
But the highlighted tab problem still persist, on both cases.

Thanks

**Comment by fega** [comment]
@fredericoregateiro did you solve your problem?

**Comment by fega** [comment]
Closed due inactivity, feel free to reopen it if it is still necessary.
