### ISSUE TITLE
Open FAB button to the right side

### ISSUE THREAD

**Issue by pmargreff** [Dogfalo/materialize#2905]
Can I do a FAB (action) button open options to the right side instead the left side?

**Comment by Dogfalo** [comment]
The design spec if for the button to be on the right, so right now it only supports opening up and to the left. but you can easily modify the code if you want it to do something else.

**Comment by pmargreff** [comment]
@Dogfalo Thanks, could you help pointing out witch are the property i need change to overwrite this behavior ?
