### ISSUE TITLE
How to Disable Accordion Collapse if already Expanded

### ISSUE THREAD

**Issue by syberknight** [Dogfalo/materialize#2908]
is it possible?

so, when a user clicks on a "collapsible-header", and that expands whatever is in it, i'd like to then disable that expanded "collapsible-header" from closing if a user clicks on it again. it should only close when the user clicks on a different "collapsible-header" option.
does that make sense?

**Comment by Dogfalo** [comment]
Currently there is no way to do that without modifying some of the code.

**Comment by syberknight** [comment]
ok. thanks for the quick reply!

**Comment by jacobq** [comment]
BTW, if you're looking for some simple code you can use to do this, see https://github.com/Dogfalo/materialize/issues/2987
