### ISSUE TITLE
'Fixed Right Sidenav' is Not Placed on Right, But on Left side

### ISSUE THREAD

**Issue by subins2000** [Dogfalo/materialize#2910]
This is similar to #1488 

I have two sidebars, one on left and other on right :

```html
<a clas="open_left" data-activates="nav-left"></a>
<div class="side-nav fixed" id="nav-left"></div>
<a clas="open_right" data-activates="nav-right"></a>
<div class="side-nav fixed" id="nav-right"></div>
```
```js
$(".open_left").sideNav({
  edge: 'left'
});
$(".open_right").sideNav({
  edge: 'right'
});
```
The problem is that both side navs are placed on left. This bug does not happen when the right side nav is **not fixed**.

[Demo](http://codepen.io/subins2000/pen/KzgBWR)

**Comment by Thanood** [comment]
It works if you remove the collapse button and add ```right-aligned``` class to the side-nav. Not to say this is a good solution but it works. :smile: 

On the other hand: with fixed side-navs, the collapse button doesn't make much sense anyway (it "unfixes" but does not fix the side-nav again).

**Comment by subins2000** [comment]
@Thanood That is a fix. But when I updated the sideNav from to this https://github.com/Dogfalo/materialize/blob/master/js/sideNav.js the bug was fixed without adding the `right-aligned` class.
