### ISSUE TITLE
The web font has some problem.

### ISSUE THREAD

**Issue by Lovin0730** [Dogfalo/materialize#2912]
Hello, there are some mistakes in the web fonts in the package which has a 'woff' suffix .In microsoft edge, the font can't show correctly. I download a new one from https://fonts.googleapis.com/icon?family=Material+Icons and it works well. So I think you should check the font documents in the package.

**Comment by Dogfalo** [comment]
We're removing the font files in the next release, so please use the one in the link you have. These instructions are reiterated on the icons page.
