### ISSUE TITLE
Button on Accordion Header

### ISSUE THREAD

**Issue by RhanCandia** [Dogfalo/materialize#2914]
I tried to add a button on the header pulled to the right.

I want to trigger a different function and not expand the accordion when I click on that button. But the accordion expands.

How do I cancel the accordion expand when I click on the button inside the header?

**Comment by Thanood** [comment]
You could stop propagation on the button event:
http://codepen.io/anon/pen/Mybmyj

**Comment by RhanCandia** [comment]
@Thanood , thanks! That solved it!
