### ISSUE TITLE
Sidenav bug

### ISSUE THREAD

**Issue by Modhappy** [Dogfalo/materialize#2917]
I found a bug in the materialize css with the sidenav,
While viewing it on a mobile device, the background color overlaps because its an RGBA transparent color value. If you add this line to your css it fixes it:
 **@media only screen and (max-width: 991px) {nav ul a:hover {background-color:transparent;}}**
The background color for :active and :hover are the same transparent color value so they overlap and become darker when you view it on a mobile device

**Comment by fega** [comment]
Can you test if this still a problem?, also can you provide a way to reproduce it? thanks

Closed due inactivity, feel free to reopen it if it is still necessary.
