### ISSUE TITLE
select do not work

### ISSUE THREAD

**Issue by willbeefine** [Dogfalo/materialize#2921]
Something went wrong with select element of materializecss. They didn't render.
Here is my code: http://codepen.io/8bee/pen/VaPzZe

Another issue like mine has been submit before but I can't find my own problem by the solution in this post: https://github.com/Dogfalo/materialize/issues/151

**Comment by jdebray** [comment]
you need, in the setting put the jquery library before the materialize library

**Comment by rogeercruz** [comment]
Hello,

Please add the "setting" to the documentation in the website.
Thanks
