### ISSUE TITLE
Material boxed inside Absolutely positioned Div

### ISSUE THREAD

**Issue by xTMNTxRaphaelx** [Dogfalo/materialize#2922]
Hi,

I am trying to put some images inside absolutely positioned div. but the problem is on clicking it only show a portion of the image like this
http://prnt.sc/age93h

 Any solution you can offer? Really appreciate it.

**Comment by pheliperocha** [comment]
Could you put your code here? And be sure that the div aren't with overflow hidden, and if the image has the size of the div content

**Comment by xTMNTxRaphaelx** [comment]
Hello, sorry for late reply. Parent div is with overflow hidden and positioned absolute.

**Comment by MyTheValentinus** [comment]
Same issue.

**Comment by fega** [comment]
Please provide a way to reproduce it. like a [codepen](https://codepen.io/fega/pen/BWeZaG)

Closed due inactivity, feel free to reopen it if it is still necessary.
