### ISSUE TITLE
Multi Select not working in Firefox

### ISSUE THREAD

**Issue by sajjad008** [Dogfalo/materialize#2926]
I have downloaded **Materialize alpha release v0.97.5**. The multi select is working (i.e. correctly shows the check mark against the selected options) on Chrome and IE, but not on **Mozilla Firefox**. Please fix this issue on Firefox as well.

**Comment by paulina-pacheco** [comment]
I cloned the repo and opened the forms.html, the multiselect works fine on Mozilla Firefox 44.0.2 for Ubuntu

**Comment by sajjad008** [comment]
Hi,
Please note that I was using **Firefox** on **Windows 10**.
The multi-select works fine when I have to render a multi-select without pre-populating the selected options. The problem I was facing was if there are more than one options which were to be selected by default, then all the selected options are not shown as selected. I had to use the following js code in order to make it work on all browsers:
```
	$('select').material_select();
	//Fix for Materialize multi-select Bug
	$('select').each(function() {
		var select = $(this);
		var select_dropdown = $(select).siblings('.select-dropdown');
		var selectUL = $(select).siblings('ul#'+$(select_dropdown).attr('data-activates'));
		$('li', selectUL).each(function(index) {
			var isSelected = $('option:nth-child('+(index+1)+')', select).attr('selected') == 'selected';
			if(isSelected) {
				$(this).addClass('active');
			}
		});
	});
```

**Comment by fega** [comment]
Please provide a way to reproduce it. like a [codepen](https://codepen.io/fega/pen/BWeZaG)

Closed due inactivity, feel free to reopen it if it is still necessary.
