### ISSUE TITLE
table with height defined and vertical scroll

### ISSUE THREAD

**Issue by ferchoman09** [Dogfalo/materialize#2927]
I need a table with defined height or maxHeight and vertical scroll. But, the materializecssTable seems to be ignoring the height css property. 
Has anyone done it before?
Can any one help me?

**Comment by atussec** [comment]
give it a custom class which have a hight and a width

**Comment by joyanta** [comment]
hi this does not seem to work

**Comment by ferchoman09** [comment]
I could not do it either

**Comment by cpett** [comment]
Anyone have luck with this?

**Comment by fega** [comment]
Could you bring me a little codepen or fiddle?

**Comment by cpett** [comment]
I was able to get this working with some help from SO. Can't find the post anymore... here's a [codepen](https://codepen.io/cpett/pen/gmJygO)
