### ISSUE TITLE
checkbox with enclosing label not working

### ISSUE THREAD

**Issue by Vaalyn** [Dogfalo/materialize#2929]
I'm encountering a problem with checkboxes that are enclosed by a label instead of having the label after the input element. The checkbox will not be displayed.

This is an example of the issue: [codepen](http://codepen.io/anon/pen/MyJMoO)

I'm mainly encountering this problem while working on WordPress sites with plugins that output such enclosed checkboxes (for example woocommerce germanized).

Is it possible to get materialize working with enclosed checkboxes?

**Comment by paulina-pacheco** [comment]
I think the problem is that materialize uses the element+element selector like this

**Comment by Vaalyn** [comment]
I just took a look at the part of the css that you mentioned.
Unfortunately I think that there is no css only way to implement the style/behavior of the materialize checkbox with the enclosing label.

Would a javascript function that "unwraps" checkboxes from enclosing labels be a useful addition to materialize or would that be something that is better to be implemented outside of materializes scope?

**Comment by acburst** [comment]
Currently our checkboxes only work with the label in the exact structure we provide. (After the input)
