### ISSUE TITLE
Grid flow not as expected when using push and pull - 0.97.5

### ISSUE THREAD

**Issue by kevintelford** [Dogfalo/materialize#2930]
I have a grid row that has a set of columns that flows between two display rows.  As an example, columns w/text 1, 2 and 3 on the first row and 4, 5, and 6 on the second
```html
<div class="row">
  <div class="col l4 red">1</div>
  <div class="col l4 yellow">2</div>
  <div class="col l4 green">3</div>
  <div class="col l4 cyan">4</div>
  <div class="col l4 blue">5</div>
  <div class="col l4 purple">6</div>
</div>
```
<img width="1003" alt="screen shot 2016-03-19 at 2 49 31 pm" src="https://cloud.githubusercontent.com/assets/632089/13900670/05e637de-ede2-11e5-8771-18cba8b48fc1.png">

By using push and pull I can reorder [1,2,3] and [4,5,6].  However, I'd expect that by using push and pull I could switch 3 and 4, however that is not the case
```html
<div class="row">
  <div class="col l4 red">1</div>
  <div class="col l4 yellow">2</div>
  <div class="col l4 push-l4 green">3</div>
  <div class="col l4 pull-l4 cyan">4</div>
  <div class="col l4 blue">5</div>
  <div class="col l4 purple">6</div>
</div>
```
<img width="1084" alt="screen shot 2016-03-19 at 2 50 14 pm" src="https://cloud.githubusercontent.com/assets/632089/13900675/4a4ccaf0-ede2-11e5-91e5-a03e5cfce667.png">

I may have an incorrect expectation/understanding, but I figured I'd make an issue incase this is not behaving as expected.

**Comment by acburst** [comment]
That is not how push and pull work. If you are using more than 12 columns worth in a row, the rows are determined by order in the HTML structure. Push and pull are only used for rearranging in the same row

**Comment by kevintelford** [comment]
Sorry for the delayed response.  So what I was actually after was switching columns between rows, which, it sounds like isn't what push and pull are for.

For example, I want my large responsive design to look like this
<img width="1025" alt="screen shot 2016-04-10 at 9 57 56 am" src="https://cloud.githubusercontent.com/assets/632089/14410697/f1abe908-ff02-11e5-9e82-b6b5809d6219.png">
And then when on a small device, to look like
<img width="544" alt="screen shot 2016-04-10 at 9 58 11 am" src="https://cloud.githubusercontent.com/assets/632089/14410701/f93ae926-ff02-11e5-869f-941cd3a6755e.png">

I had hoped to achieve this through push and pull, however it looks like I didn't fully understand how they function.  I suspect I should just create two shadow divs and then use .hide-on-large-only and .show-on-large to display the correct one for the appropriate media size.

Thanks for the feedback and good job w/the library.

Best,
Kevin
