### ISSUE TITLE
Date picker not showing

### ISSUE THREAD

**Issue by PNixx** [Dogfalo/materialize#2938]
After clicking on the field nothing happens. Do not add the class to the field: picker - opened. It does not work in the 0.97.5 release and the latest version of the master.
![2016-03-22 10 36 01](https://cloud.githubusercontent.com/assets/1117351/13944863/4af14d54-f022-11e5-8012-23cce9d936fc.png)

**Comment by Thanood** [comment]
I experienced that, too. Couldn't nail it down to what causes this.
This is possibly a workaround:

```javascript
$('.datepicker').on('focusin', function () {
  $('.datepicker').pickadate('open');
});
```

**Comment by anddah** [comment]
Try using jQuery 2.1.4 instead of 2.2.* (it's still a bug but that fixed it for me)

**Comment by PNixx** [comment]
@anddah I tried use jQuery v2.2.2, but it not working for me.

**Comment by anddah** [comment]
@PNixx and i said that you shouldn't use 2.2.2 :) use 2.1.4 instead

**Comment by PNixx** [comment]
@anddah ooh, thanks man! Maybe need to be corrected bower dependencies?

**Comment by marcelino-m** [comment]
Thanksssss!!!

**Comment by Dogfalo** [comment]
This bug has been fixed, but is not released yet.

**Comment by Kravs** [comment]
@Dogfalo When this fix will be released ?
