### ISSUE TITLE
Select scroll to active option

### ISSUE THREAD

**Issue by PNixx** [Dogfalo/materialize#2940]
Scroll the list to the selected item after the opening doesn't work.

**Comment by acburst** [comment]
Please post more information / code examples to help flesh out your problem.

**Comment by PNixx** [comment]
Yes, you can see on screenshot:
1. ![2016-03-22 18 48 14](https://cloud.githubusercontent.com/assets/1117351/13957783/2b904efc-f067-11e5-91d7-34b2176bd6ab.png)
2. ![2016-03-22 18 48 22](https://cloud.githubusercontent.com/assets/1117351/13957784/2b91050e-f067-11e5-830a-0ae9d9b59213.png)
3. ![2016-03-22 18 48 45](https://cloud.githubusercontent.com/assets/1117351/13957785/2b931358-f067-11e5-9482-6e4185573ab1.png)

In the third step, I wheel, scroll to the correct position. I test on Mac, Firefox 45.0.1

**Comment by mike-fastpay** [comment]
I also experienced this issue. I have to write a VERY elaborate hack to get it to scroll. Took me 4 days to correct. One thing I can add is that for some reason this only happens when I have more than one select menu on the page. And sometimes it will work the first time the menu is opened and then after a option is selected it will not scroll the second time the menu is opened.

Here's now I implemented a hack in case anyone else needs this.

`
/**
                 * Type jump ahead method. This method allows the user
                 * to hit a keyboard key to jump to a selection
                 */
                initTypeAhead = function(){
                    // Grab all the LIs in the Debtor select menu
                    if(!document.querySelector('#'+$scope.selectMenuId)){// id of your select menu
                        $log.warn($scope.selectMenuId,'Not Found');
                        return;
                    }
                    target = document.querySelector('#'+$scope.selectMenuId).querySelectorAll('li');
                    $log.warn('initTypeAhead on ',$scope.selectMenuId);
                    //Instantiate a new observer
                    observer = new MutationObserver(function(mutations) {
                     
                      mutations.forEach(function(mutation) {
                        if($(mutation.target).hasClass('selected') && selectedTarget !== mutation.target){
                            $log.warn('mutation.target', mutation.target);
                            // store the current selection to avoid selecting the same item twice in a row
                            selectedTarget = mutation.target;

                            // Grab the UL
                            targetParent = mutation.target.parentElement;

                            // for JQuery to scroll to the li we need to construct the selector passing the UL id and the index of the li
                            var scrollTarget = '#' + targetParent.id + ' li:nth-child(' + listArr.indexOf(mutation.target) + ')';

                            //$log.warn('scrollTarget ',scrollTarget);
                            //$log.warn('scrollTarget height',$(scrollTarget).height());

                            // Animate the list
                            if($(scrollTarget).position()){
                                $('#' + targetParent.id).animate({
                                    scrollTop: $(scrollTarget).height() * listArr.indexOf(mutation.target)
                                }, 500);
                            }
                        }
                      });
                    });

                    // Initialize an Observer for every li in the ul
                    // This needs to happen because keypress events
                    // are disabled when select menu is open.
                    _.forEach(target, function(value, key) {
                        //$log.warn('add observer to',value, 'key',key);
                        observer.observe(value, { attributes: true, childList: true, characterData: true, subtree:true, characterDataOldValue:true });
                        listArr[key] = value;
                    });
                };

// Here I have a promise that is resolved when the options are loaded.
// I set $scope.menuReady to true.
// Each time the user selects and option on ng-change I set it to false again and the promise resets the value to true.
                $scope.$watch('menuReady', function(newVal, oldVal){
                    $log.warn('watch menuReady', newVal);
                    if(!!newVal){
                        $log.warn('Call TypeAhead');
                        $timeout(initTypeAhead, 1000);
                    }
                });
`


I eneded up placing this all in an attribute directive so now on every select menu that is broken by materlizecss I just add init-type-ahead-dir on the containing div and I pass the ID of the div.

**Comment by mike-fastpay** [comment]
To be clear. My code above works because at the very least materlize is still working to add "selected' class on the correct element when I hit a letter on the keyboard. It's just not always jumping to that element.

**Comment by fega** [comment]
Closed due inactivity, feel free to reopen it if it is still necessary. in this case please add a way to reproduce it, thanks
