### ISSUE TITLE
Vertical gap between columns in 4-col structure.

### ISSUE THREAD

**Issue by PauloFrancaLacerda** [Dogfalo/materialize#2941]
I was playing with the templates provided, and came across the idea of trying a 4-2-1 layout: 4 columns (for large devices), 2 cols (for medium devices) and 1 col for small ones.
So, I did this to the original "Starter" template:

- 1) Copied the 3rd col and pasted as the 4th col.
- 2) Changed the column classes, like this:   "col s12 m4" ==> "col s12 m6 l3"
- 3) Worked as expected. (figure 1)
- 4) Then, I added more text to the 2nd column. Allright again. (figure 2)
- 5) Restored the original text in the 2nd col (undid step 4).
- 6) Finally, I could see the vertical gap after adding some text to the first column. (figure 3)

http://imgur.com/a/9EcI8/all

I think it's not (visually) correct. It looks like there's a margin/padding bug, or something.
Did I do anything wrong?
Thanks in advance.

**Comment by acburst** [comment]
You did nothing wrong. If you want to put more than 12 cols worth inside a single row and want it to fit nicely you can achieve this with [masonry](http://masonry.desandro.com/). It is not something easily solved with just structure and layout

**Comment by PauloFrancaLacerda** [comment]
In time...
Just realized the problem is bigger: In the figure 3, we can see not only the gap as mentioned, but also a misplace issue (the 3rd and 4th columns are in the wrong/inverted side). Notice both 3rd and 4th columns were in the correct sides (figures 1 and 2), before the extra text has been added to the 1st col.

**Comment by PauloFrancaLacerda** [comment]
@acburst, thank you for masonry. It looks very good. :)
