### ISSUE TITLE
Error in material_select() if an object is passed

### ISSUE THREAD

**Issue by MythicAngel** [Dogfalo/materialize#2945]
When we use `$('select').material_select()` (for select tags), if we provide a javascript object inside material_select() function then an error occurs when any of the options are clicked.

So, this cause an error: `$('select').material_select({})`
But this is ok: `$('select').material_select()`

Please check demo for reproduce it: [https://jsfiddle.net/seouljsfiddle/1d0pppqr/](https://jsfiddle.net/seouljsfiddle/1d0pppqr/) (Don't forget to open console when you click on an item)

**Comment by Thanood** [comment]
The argument of material_select() is expected to be a function:
https://github.com/Dogfalo/materialize/blob/master/js/forms.js#L389

At this line, your object is essentially being called, causing an error.

**Comment by TyrionGraphiste** [comment]
You should follow the documentation, because currently you can't pass an object as Thanood said.
