### ISSUE TITLE
cannot call toast after load element

### ISSUE THREAD

**Issue by tceydeliler** [Dogfalo/materialize#2950]
Hi,
I try to set an alert with toast.
Altough security_orange.png or  security_red.png  load no test shown.
Have an Idea?

`$(document).ready(function()
	{
		setInterval(function()
			{
				$("#status").html("").load('status.php');
				var attr = $("#front-page-logo").attr("src");
				if (attr.indexOf("security_orange.png") > -1) 
					{
	    				Materialize.toast('orange desin', 4000);
	    			}
	  		 	else if(attr.indexOf("security_red.png") > -1) 
	   			{
	    				Materialize.toast('red desin', 4000);
	    			}
    		}, 10000);
	});
`
and <a> tag is in status.php:
`		echo '<a href="admin.php" id="logo-container" class=" brand-logo tooltipped" data-position="bottom" data-delay="50" data-tooltip="Ana Sayfa"><img class="imgOrange" id="front-page-logo" src="../img/security_orange.png" /></a>';`

**Comment by philipraets** [comment]
jQuery load is asynchronously which means it will fetch "status.php" and doesn't wait until this is finished for executing the rest of the code. 

It does has a callback function, that gets executed after load gets the "status.php" page. So if you put your checks for color in the callback it should work.

I would change your code to this:

`$(document).ready(function() { 
	setInterval(function() { 
		$("#status").html("").load('status.php', function(){
			var logo = $("#front-page-logo").attr("src"); 
			if (logo.indexOf("orange") > -1) { 
				Materialize.toast('orange desin', 4000); 
			} else if(logo.indexOf("red") > -1) { 
				Materialize.toast('red desin', 4000); 
			}
		});
	}, 10000);
});`

**Comment by tceydeliler** [comment]
Cool :)
It works perfect :)
