### ISSUE TITLE
Could we get a release up in hurrr?

### ISSUE THREAD

**Issue by danny-andrews** [Dogfalo/materialize#2951]
Looks like the latest release was 3 months ago, and a lot's [changed](https://github.com/Dogfalo/materialize/compare/14f272a58e3524623e330c7...master) since then. Could we git a new release out?

**Comment by NitroBAY** [comment]
we're at  v0.97.5, why do you add to v0.96.0, and yeah I agree that you need to have a new release soon as possible

**Comment by remzr7** [comment]
+1

**Comment by Dogfalo** [comment]
New release 0.97.6 is out
