### ISSUE TITLE
"Roboto Thin" font-weight is 100 not 200

### ISSUE THREAD

**Issue by moleculezz** [Dogfalo/materialize#2952]
Hello,

As you can see here, there is only `100`, `300`, `400`.. etc. There is no `200`. So the font-weight set in this project `200` does not exist. https://www.google.com/fonts#UsePlace:use/Collection:Roboto:400,100,300,500,700,900

**Comment by Dogfalo** [comment]
I changed it now to match what is specified on google fonts. c0d5a9f9b228841ac4db9a1532df11a2a4adbefd
