### ISSUE TITLE
Empty responsive table glitching out when resizing

### ISSUE THREAD

**Issue by vincentcox** [Dogfalo/materialize#2954]
**This only occurs when the table is empty. **
Normal (looking good):
<img width="754" alt="screen shot 2016-03-24 at 10 46 18" src="https://cloud.githubusercontent.com/assets/9286611/14013637/dad26eda-f1ad-11e5-981c-817ddb5285bf.png">
Resized a bit (glitching out):
<img width="768" alt="screen shot 2016-03-24 at 10 46 28" src="https://cloud.githubusercontent.com/assets/9286611/14013640/dd4ddad2-f1ad-11e5-9db8-a8714eb10720.png">

code:
```
<table id="selected_rules" class="striped responsive-table">
                      <thead>
                        <tr>
                          <th>id</th>
                          <th>Parameter</th>
                          <th>Type</th>
                          <th>Path</th>
                          <th>occurance</th>
                        </tr>
                      </thead>
                      <tbody id="body_table_rules">
                      </tbody>
                    </table>
```

**Comment by Dogfalo** [comment]
What styles are you applying? Please make a codepen. See CONTRIBUTING.md

On Thu, Mar 24, 2016 at 2:49 AM, Vincent Cox <notifications@github.com>
wrote:

> **This only occurs when the table is empty. **
> Normal (looking good):
> [image: screen shot 2016-03-24 at 10 46 18]
> <https://cloud.githubusercontent.com/assets/9286611/14013637/dad26eda-f1ad-11e5-981c-817ddb5285bf.png>
> Resized a bit (glitching out):
> [image: screen shot 2016-03-24 at 10 46 28]
> <https://cloud.githubusercontent.com/assets/9286611/14013640/dd4ddad2-f1ad-11e5-9db8-a8714eb10720.png>
>
> code:
>
> <table id="selected_rules" class="striped responsive-table">
>                       <thead>
>                         <tr>
>                           <th>id</th>
>                           <th>Parameter</th>
>                           <th>Type</th>
>                           <th>Path</th>
>                           <th>occurance</th>
>                         </tr>
>                       </thead>
>                       <tbody id="body_table_rules">
>                       </tbody>
>                     </table>
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/Dogfalo/materialize/issues/2954>
>



-- 
Doggy sends his greetings from Mars.

**Comment by vincentcox** [comment]
Thanks for your reply! Here is the codepen as requested:
http://codepen.io/anon/pen/LNLERa

**Comment by acburst** [comment]
You could use our grid system and wrap your card div in a ```<div class="row"></div>```

**Comment by vincentcox** [comment]
@acburst Thanks! That fixed the problem!
