### ISSUE TITLE
New Badge in SideNav

### ISSUE THREAD

**Issue by geniustanley** [Dogfalo/materialize#2955]
I need new badge in SideNav but it doesn't work
![screenshot from 2016-03-24 22 46 28](https://cloud.githubusercontent.com/assets/11531622/14020484/4c726806-f212-11e5-9714-71a550314c2d.png)

So I change it by adding some code
`
    span.new.badge {
      line-height: 20px;
      margin-top: 22px;
    }
`
![screenshot from 2016-03-24 22 45 47](https://cloud.githubusercontent.com/assets/11531622/14020489/544fa0ac-f212-11e5-8ec2-87598a90ea88.png)

This is my [CodePen](http://codepen.io/geniustanley/pen/BKRvLL)

**Comment by an0nh4x0r** [comment]
thanks :)

**Comment by acburst** [comment]
Fixed
