### ISSUE TITLE
material-icons prefix bug

### ISSUE THREAD

**Issue by Lis1us** [Dogfalo/materialize#2956]
Why when I use icon-prefix turns out that's it?
<img src="https://habrastorage.org/files/0a2/e22/f39/0a2e22f39cc24ca48c573f95d6847e86.png"/>
P.S. no icon-prefix all right

**Comment by Dogfalo** [comment]
Hmm I'm not sure what you mean :confused:

**Comment by Lis1us** [comment]
@Dogfalo http://brideland.xyz/contact.php check this

**Comment by Dogfalo** [comment]
I don't know what I'm supposed to be looking at. It seems like your icons are working fine. If you have any questions on how it works, please read the Icon documentation carefully
