### ISSUE TITLE
Switches

### ISSUE THREAD

**Issue by Dogfalo** [Dogfalo/materialize#296]

**Comment by davidsoderberg** [comment]
Can I help on this one?

**Comment by acburst** [comment]
Sure. Take a look here http://www.google.com/design/spec/components/switches.html#switches-switch

**Comment by davidsoderberg** [comment]
Only the ligth theme?

**Comment by acburst** [comment]
For now. Also are you familiar with Hammer.js? Its what we use for touch

**Comment by davidsoderberg** [comment]
No I do not think we need hammer.js for touch. It just need a regular click event?

**Comment by acburst** [comment]
Well you don't have to worry about that now. But eventually we want to be able to drag it

**Comment by davidsoderberg** [comment]
okey :smile:

**Comment by Dogfalo** [comment]
One problem you may run into when creating the switches is that you will have to override our existing checkbox style. So when you create the switch css, make sure it works when materialize.css is included.

**Comment by davidsoderberg** [comment]
I already had that in mind thanks any way.

**Comment by Dogfalo** [comment]
Great! Looking forward to it

**Comment by davidsoderberg** [comment]
Please check gitter.

**Comment by Dogfalo** [comment]
Added in 1b7f17f011169de0f118a82ea710c6841a4b8949
