### ISSUE TITLE
How to open inner collapsible from outer one

### ISSUE THREAD

**Issue by tceydeliler** [Dogfalo/materialize#2960]
Hi,
I try to use collapsible for help page.
That's why  I have some collapsible located 3 times inner.
I want to use first section of most outer  collapsible as index page to open inner collapsibles.
But I can open only the collapsible which members section. Cant open inner collapsible by clicking

Have you any idea or hint?

Regards,

**Comment by fega** [comment]
I didn't test it by myself but I suspect that the collapsible is not well designed to achieve this effect, maybe you should edit the code to get it.
