### ISSUE TITLE
tabs doesn't work with ui-sref

### ISSUE THREAD

**Issue by pmargreff** [Dogfalo/materialize#2962]
I'm using ui-router (angular.js) to do routes. When I try to use tabs for navigation two things happen, the first, animation on tab with ui-sref doesn't work. The second, when the tab content load all animations only work when I press F5. 

Someone already solve this problem??

Here is new tabs code (doesn't work well):

```

<div class="col s4 right">
  <ul class="tabs">
    <li class="tab col s1"><a ui-sref="home.map" href="">Map</a></li>
    <li class="tab col s1"><a>Updates</a></li>
    <li class="tab col s1"><a class="active" ui-sref="home.inventory">itens</a></li>
    <li class="tab col s1"><a>OPTIONS</a></li>
   </ul>
</div>
```

And here is the old one (work fine but without tabs animations) 

```

<ul class="right hide-on-med-and-down">
  <a ui-sref="home.map" class="my-gray-text waves-effect waves-light material-icons">room</a>
  <a class="my-gray-text waves-effect waves-light material-icons">inbox</a>
  <a ui-sref="home.inventory" class="my-gray-text waves-effect waves-light material-icons">work</a>
  <a data-beloworigin="true" data-activates='dropdown1' class="turquoise-darken-text waves-effect waves-light material-icons dropdown-button">account_circle</a>
</ul>
```

**Comment by fega** [comment]
Please provide a way to reproduce it. like a codepen or  a fiddle snippet
Closed due inactivity, feel free to reopen it if it is still necessary.
