### ISSUE TITLE
An div that is not affected by the materialize css and js

### ISSUE THREAD

**Issue by LGRI** [Dogfalo/materialize#2963]
I need to use the original html, css and js code in part of a page design, but all of the element has been affected by materialize. if there is a "unmaterialize" tag or attribute for this case would be wonderful.

**Comment by bkovacev** [comment]
I think you basically solved your own problem - write its' own css - so subclass it and use jquery select/find to use it and attach needed js.

**Comment by chrisco23** [comment]
found this because I have the same issue as the OP.  I'm trying to use jquery-maskmoney.  No idea how to "unmaterialize" nor "uncss" everything.  Any ideas?  Or perhaps material design has its own ideas about currency input?  But I've found nothing on that topic either.
