### ISSUE TITLE
Edit the "smoothness" of the ScrollSpy

### ISSUE THREAD

**Issue by Kamel38** [Dogfalo/materialize#2964]
Hello !

I'm using **MaterializeCss** for my next project, and when I use the scrollspy, I notice that it moves to quickly. Is it possible to _edit the speed_ ? I don't know Javascript, that's why I'm asking. If there's any code line that I have to change in the js file, could you tell me ?

Thanks :)

**Comment by Dogfalo** [comment]
Change the duration here:
https://github.com/Dogfalo/materialize/blob/master/js/scrollspy.js#L185

**Comment by Kamel38** [comment]
Thank you ! :)
