### ISSUE TITLE
Checkbox tabindex not working

### ISSUE THREAD

**Issue by artur99** [Dogfalo/materialize#2967]
If a user would like to browse the form using the tab key, they won't be able to reach the checkboxes... Also tried with adding tabindex="x" to them, and still the same... On Chrome it seemt that after removing the  `visibility: hidden;` from `[type=checkbox]:checked, [type=checkbox]:not(:checked)`, and keeping the other proprieties `position: absolute; left: -9999px`, it worked...

So, I think it would be a good idea to remove the `visibility: hidden`, as long as the checkbox would still be not visible

Thanks!

**Comment by acburst** [comment]
Checkout this issue 2777

Have you tried the latest commit on master? We will try and release a new version soon
