### ISSUE TITLE
Grid and valign-wrapper

### ISSUE THREAD

**Issue by philipraets** [Dogfalo/materialize#2968]
Hi,

I'm using the grid system, but when i combine this with the valign-wrapper, it doesn't respect the columns anymore.
It is because of display:flex on valign-wrapper.

See the following codepen:
http://codepen.io/anon/pen/XdaXWe

The first row has 2 columns with s12 m6 l6 classes.
The second row has the same 2 columns but wrapped with valign, but it seems to ignore s12.

On med and large screens:
![valign-wrapper1](https://cloud.githubusercontent.com/assets/708011/14106936/feedf64e-f5b4-11e5-8997-1f6c83f90e69.jpg)

on small screens:
![valign-wrapper2](https://cloud.githubusercontent.com/assets/708011/14106937/0130ad84-f5b5-11e5-8257-1bd0dc3a3512.jpg)

**Comment by Dogfalo** [comment]
This is working as intended. valign is not meant to be used on the same element as row or col for the exact reason you mentioned.

**Comment by darckyn** [comment]
Hi.

I just use some come to bypass this

Here is my code:

@media #{$small-and-down} {
    .valign-wrapper{
        display: inherit;
    }
}
