### ISSUE TITLE
forms problem....

### ISSUE THREAD

**Issue by Dergercol** [Dogfalo/materialize#2969]
![screenshot_2016-03-29-22-31-28](https://cloud.githubusercontent.com/assets/17719426/14117429/13821498-f5fe-11e5-86a2-b83c2eb04be3.png)

**Comment by Dergercol** [comment]
How can i fix it?

**Comment by Dergercol** [comment]
<h4>Регистрация</h4>
        <p>Пожалуйста... Введите ваши данные</p><br>
        <div class="row">
          <form class="col s12">
            <div class="row">
              <div class="input-field col s6">
                <i class="material-icons prefix">account_circle</i>
                <input id="icon_prefix" type="text" class="validate" style="display:n0ne;" >
                <label for="icon_prefix">Ник</label>
              </div>
              <div class="input-field col s6">
                <i class="material-icons prefix">email</i>
                <input id="icon_telephone" type="email" class="validate">
                <label for="icon_telephone">email</label>
              </div>
            </div>
          </form>
        </div>

**Comment by Dergercol** [comment]
<code>
   <h4>Регистрация</h4>
        <p>Пожалуйста... Введите ваши данные</p><br>
        <div class="row">
          <form class="col s12">
            <div class="row">
              <div class="input-field col s6">
                <i class="material-icons prefix">account_circle</i>
                <input id="icon_prefix" type="text" class="validate" style="display:n0ne;" >
                <label for="icon_prefix">Ник</label>
              </div>
              <div class="input-field col s6">
                <i class="material-icons prefix">email</i>
                <input id="icon_telephone" type="email" class="validate">
                <label for="icon_telephone">email</label>
              </div>
            </div>
          </form>
        </div>
</code>

**Comment by Dergercol** [comment]
<pre>
 <h4>Регистрация</h4>
        <p>Пожалуйста... Введите ваши данные</p><br>
        <div class="row">
          <form class="col s12">
            <div class="row">
              <div class="input-field col s6">
                <i class="material-icons prefix">account_circle</i>
                <input id="icon_prefix" type="text" class="validate" style="display:n0ne;" >
                <label for="icon_prefix">Ник</label>
              </div>
              <div class="input-field col s6">
                <i class="material-icons prefix">email</i>
                <input id="icon_telephone" type="email" class="validate">
                <label for="icon_telephone">email</label>
              </div>
            </div>
          </form>
        </div>
</pre>

**Comment by Dergercol** [comment]
<pre><code>
<h4>Регистрация</h4>
        <p>Пожалуйста... Введите ваши данные</p><br>
        <div class="row">
          <form class="col s12">
            <div class="row">
              <div class="input-field col s6">
                <i class="material-icons prefix">account_circle</i>
                <input id="icon_prefix" type="text" class="validate" style="display:n0ne;" >
                <label for="icon_prefix">Ник</label>
              </div>
              <div class="input-field col s6">
                <i class="material-icons prefix">email</i>
                <input id="icon_telephone" type="email" class="validate">
                <label for="icon_telephone">email</label>
              </div>
            </div>
          </form>
        </div>
</pre></code>

**Comment by Dergercol** [comment]
My code, and i have latest version

**Comment by artur99** [comment]
Is that Chrome on Android?

**Comment by Dogfalo** [comment]
You most likely have not included jQuery or materialize.js properly.
