### ISSUE TITLE
Css search bug

### ISSUE THREAD

**Issue by Josepdal** [Dogfalo/materialize#2971]
https://i.gyazo.com/c8bfe30a9424cd779ed2c61dfe934d33.png

**Comment by acburst** [comment]
can you post some code and flesh this out more. These types of issues are very unhelpful because I have no way of diagnosing the problem to fix it.

**Comment by Josepdal** [comment]
@acburst you can watch code here: http://materializecss.com/navbar.html

is wrong in your guide too

**Comment by Thanood** [comment]
@Josepdal Which browser is it that you use?

**Comment by Josepdal** [comment]
@Thanood Chrome, in os x and windows does not working fine

**Comment by NitroBAY** [comment]
Hello Josepdal, sorry for your problem, I had the same on IE (#2903). I sent a pull request, I don't know if Materialize's team will accept it but as I already patch my website you could test if my pull request fix your problem here : https://pharmaciesousprefecture.fr/ :D

**Comment by AlvaroLQueiroz** [comment]
I have the same problem in linux chrome v50. I fixed using:

`nav .nav-wrapper form, nav .nav-wrapper form .input-field{
height: 100%;
}`

**Comment by acburst** [comment]
Merged c129dc1

**Comment by DatoBula** [comment]
@AlvaroLQueiroz thanks, I had same problem and your solution worked for me.
