### ISSUE TITLE
Add a Materialize.init() function

### ISSUE THREAD

**Issue by mladenilic** [Dogfalo/materialize#2972]
[Turbolinks](https://github.com/turbolinks/turbolinks) is ruby gem massively used by Ruby on Rails applications. It intercepts each get request, fetches the content and swaps is without doing the full page reload.

Since document ready is not triggered after the content is dynamically swapped, materialize js is not initialized.

Since turbolinks offer custom events, problem could be easily solved if there is a nice and simple way to dynamically initialize js modules. Something like `Materialize.init()`. It can then be internally called on document ready, but would further allow developers to manually initialize them whenever needed.

I'm sure that turbolinks are just one example and that there are many more cases where this issue arises.

**Comment by fega** [comment]
Added to the feature request board

**Comment by artm** [comment]
Is there any ETA on this? 

And correct me if I'm wrong, this is just about exposing [this function][1] with a name? 

[1]: https://github.com/Dogfalo/materialize/blob/v1-dev/js/init.js#L2

**Comment by DanielRuf** [comment]
@artm The file that you linked to is just for the docs. There is no automatic initialization in v1 anymore.
You should only reinit the components that you actually use.

**Comment by artm** [comment]
So, say, if I want to make the close button on chips work after turbolinks:load I have to copy and paste [this fragment][1] into appropriate place in my code (and the same for every component)?

[1]: https://github.com/Dogfalo/materialize/blob/v1-dev/js/chips.js#L474-L480

**Comment by artm** [comment]
hmm, looks like I don't need that, sorry for the noise

**Comment by DanielRuf** [comment]
The event listener should also fire for dynamically added elements.
