### ISSUE TITLE
<select> and <ul> list width is being forced

### ISSUE THREAD

**Issue by kenopen** [Dogfalo/materialize#2976]
Using current CDN of Materialize.

Materialize is currently forcing the width  of select and ul dropdowns when dropdown is active. is there a way to overwrite this?

My original code:
`<ul id="export-dropdown" class="dropdown-content" style="width:170;">`

When I inspect the element, I see the following code:
`<ul id="export-dropdown" class="dropdown-content active" style="width: 58px; position: absolute; top: 0px; left: 350px; opacity: 1; display: block;">`

Screenshot:
![image](https://cloud.githubusercontent.com/assets/5868732/14175357/c643f518-f74a-11e5-9b5b-f452041839f2.png)

Screenshot, if I remove top and width style properties:
![image](https://cloud.githubusercontent.com/assets/5868732/14175432/3b4c86fe-f74b-11e5-8243-34fa6513cc14.png)

**Comment by philipraets** [comment]
Yes there is, by using data-constrainwidth="false" on the dropdown-button.

**Comment by kenopen** [comment]
Thanks. Solved my issue.

**Comment by bmla** [comment]
Is it not possible to get this https://codepen.io/bmla/pen/WXomyw to behave the same as this https://codepen.io/bmla/pen/wPoOXa? I.e. is there a constrainwidth=false on a select?
