### ISSUE TITLE
Validation field is too narrow

### ISSUE THREAD

**Issue by JZiebikiewicz** [Dogfalo/materialize#2986]
When I add validation text longer than label, it looks like this:
![2016-04-02_231446](https://cloud.githubusercontent.com/assets/16606706/14229036/d86c71ea-f928-11e5-85b0-e881ee7a874c.png)

To fix: add `width: 100%;` to `.input-field label` and will work perfect:
![2016-04-02_231505](https://cloud.githubusercontent.com/assets/16606706/14229037/d86f61de-f928-11e5-9244-5c1f1706bb50.png)

**Comment by Dogfalo** [comment]
This has already been fixed
