### ISSUE TITLE
Collapsible component

### ISSUE THREAD

**Issue by LCallaghan84** [Dogfalo/materialize#2987]
When the collapsible component is using the accordion option, it should not collapse, one section should always be open and can not be collapsed. This should be set to default. If the component is set to expandable, then it can collapse.

**Comment by jacobq** [comment]
Where is the "accordion" option? I am trying to implement this behavior as well but did not see it described on the project website / docs.

**Comment by LCallaghan84** [comment]
Look in the JavaScript section of the site, modular is called collapsible.

**Comment by jacobq** [comment]
@LCallaghan84, sorry, please allow me to clarify. I found the information about collapsibles and now I see where it mentions accordions, but I don't see any place where it talks about how to prevent all of the items from being closed at the same time (i.e. accordion wherein the active item cannot be collapsed). I posted some code above that "works" but, of course, would prefer to use built-in options for this if there are any.

**Comment by Thanood** [comment]
Why should I not be able to close collapsibles?
Think of Google Inbox, I can open only one conversation at a time (accordion) but I can also close it.

**Comment by LCallaghan84** [comment]
Oh okay I get it now. That is what I wanted to do also. This option needs
to be added because jQuery Ui has that option and so do other accordion
scripts

**Comment by jacobq** [comment]
@Thanood There are applications for both behaviors. In my case, it is for an electron-based (desktop) app where user is selecting a connection type (network, serial, etc.) and setting parameters for each, and the collapsible functions as a "radio button" for the type. If all panels were collapsed there would be nothing else to see.
