### ISSUE TITLE
Sidenav opens in the new version

### ISSUE THREAD

**Issue by ConsoleTVs** [Dogfalo/materialize#2988]
sidebar opens if you press on the left side of the page after reloading it, lets say, you realod the page, put your curson in the left of the screen (at the end of the left side, when you can't go further) and press once there. The sidebar will pop and leave in a sec, you'll need to reload the page for it not to happen again!

**Comment by fega** [comment]
Closed due inactivity, feel free to reopen it if it is still necessary.
