### ISSUE TITLE
Missing font files on cdnjs (v0.97.6)

### ISSUE THREAD

**Issue by uok** [Dogfalo/materialize#2989]
Using the [getting started](http://materializecss.com/getting-started.html) template with cdnjs links causes multiple 404 errors for font files. 
the path should be `/font` and not `/fonts`
e.g. cdnjs.cloudflare.com/ajax/libs/materialize/0.97.6/font**s**/roboto/Roboto-Regular.woff2

**Comment by aquatix** [comment]
Same here (hate to do a +1 comment, but it bites me :) )

**Comment by lebart** [comment]
In the changelog of April the 1st they mentioned the changement in font path. I think they just missed the cdn.

**Comment by aquatix** [comment]
Indeed, but it's still a bug in the hosted version :) Lets hope they can fix it soon, I like to be up-to-date, especially with this nice project.

**Comment by lebart** [comment]
I totally agree with you. But lately the issues fixing and pull merging aren't ... let says regular ;)
That's sad because the community is growing fast and the project is really nice!

**Comment by Dogfalo** [comment]
This issue has been resolved as they are now hosted at the right path on CDNJS :smile:
