### ISSUE TITLE
Side nav links do not work when wrapped in a parallax-container

### ISSUE THREAD

**Issue by pickleshb** [Dogfalo/materialize#2990]
When a nav element is containing a side nav is contained within a parallax-container the nav will slide in but clicking any link inside the side nav will do nothing, this can be fixed by putting the side nav outside the parallax-container but it's not ideal

**Comment by acburst** [comment]
Can you explain your situation more? maybe with code examples? I'm not sure why you want to put a sidenav within a parallax container.

**Comment by pickleshb** [comment]
[Here](//gist.github.com/pickleshb/e08203b8d38cf18bd13d13ad726f3129) is a gist of what doesn't work and here is a picture of why it's in a parallax-container
<img width="305" alt="screen shot 2016-04-03 at 21 31 22" src="https://cloud.githubusercontent.com/assets/5897290/14234783/837c1a44-f9e3-11e5-8fe7-dd056626f44b.png">

When the side nav comes in it looks like by default it renders behind another element, and changing the z-index of the nav doesn't change this or make it clickable

**Comment by fega** [comment]
Please provide a way to reproduce it. like a [codepen](https://codepen.io/fega/pen/BWeZaG), it's a lot better tan a gist
