### ISSUE TITLE
Toast location

### ISSUE THREAD

**Issue by artur99** [Dogfalo/materialize#2991]
It would be really nice to be able to set up the toast location when calling the function, like:
`Materialize.toast('text', 3000, 'left');`
And have a `left: 8%` instead of `right: 8%`

Thank you! :D

**Comment by Dogfalo** [comment]
You can apply classes in the function which you can then position then with

**Comment by artur99** [comment]
But the classes are applied to `.toast`, and the `left: 8%` is set to `#toast-container` that is it's parent, and the browser did not integrate yet a way for CSS to use parent-selectors...

**Comment by Dogfalo** [comment]
Then I think you should just change the css of the toast container. Since you want an app to consistent there's not much reason to have some toasts left and some toasts right in JS

**Comment by artur99** [comment]
Ok, thank you!
