### ISSUE TITLE
problem with select element after using .load (ajax)

### ISSUE THREAD

**Issue by MetaiR** [Dogfalo/materialize#2992]
hello all,
i saw a problem with select's
it's happening when we using .load() method on ajax
when using .load the select element comes as a normal text
how can i solve it?

**Comment by Dogfalo** [comment]
You must initialize it if adding it through ajax

On Sun, Apr 3, 2016 at 1:32 PM, Seyed Ali Roshan <notifications@github.com>
wrote:

> hello all,
> i saw a problem with select's
> it's happening when we using .load() method on ajax
> when using .load the select element comes as a normal text
> how can i solve it?
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/Dogfalo/materialize/issues/2992>
>



-- 
Doggy sends his greetings from Mars.

**Comment by MetaiR** [comment]
@Dogfalo 
can you explain it more?
if give me an example too that's be so so grate

**Comment by Dogfalo** [comment]
This is explained in the initialization section in the select docs
