### ISSUE TITLE
Consider using Paul Lewis's "FLIP" technique to achieve 60 FPS on all devices

### ISSUE THREAD

**Issue by oneezy** [Dogfalo/materialize#2993]
Make all animations 60 FPS on every device w/ Paul Lewis's technique.

**Link to video:** https://www.youtube.com/watch?v=RCFQu0hK6bU
**Link to article:** https://aerotwist.com/blog/flip-your-animations/
**Link to Github demo:** https://github.com/googlechrome/flipjs

**Comment by darckyn** [comment]
Please make it happen in the materializecss.

Performance is very important

:)

**Comment by Dogfalo** [comment]
We already try to animate on transforms as much as possible.

**Comment by fega** [comment]
@Dogfalo but FLIP technique is not just use transforms....
