### ISSUE TITLE
Materialize Interaction Elements Color Change?

### ISSUE THREAD

**Issue by niiapa** [Dogfalo/materialize#2995]
Hi, I'm relatively new to Materialize, but I've been using it for about a week now so I thought I was finally getting the hang of it. Prior to the update from 2 days ago, my page body was blue-grey and by default my buttons and action/interaction elements were pink. But now that I've updated the files, they've all defaulted to the teal color. 

Is this that's wrong with my version of materialize or was it always supposed to be like this? And to fix it, does that mean I have to go back and manually add color classes to my page? 

Thanks for the help in advance.

**Comment by acburst** [comment]
Did you make changes to the variables file? When you updated you may have overwritten that file causing the color changes. Try taking a look if that file has changed.
