### ISSUE TITLE
Don't trigger wave effect when element is being dragged.

### ISSUE THREAD

**Issue by cheryllaird** [Dogfalo/materialize#2996]
At the moment when an element with the waves class is clicked, it triggers the wave effect.
If I was to drag the element, it also triggers the wave effect.

Is it possible that on drag it does not trigger the wave effect?

http://codepen.io/cheryllaird/pen/zqPGdm

**Comment by Dogfalo** [comment]
This is how it is supposed to work, as shown on android.if you drag the
notifications they ripple upon touch. You can modify the js to get a
different behavior however

**Comment by Dogfalo** [comment]
Take a look at this line and the one around it to make your changes: https://github.com/Dogfalo/materialize/blob/master/js/waves.js#L229

**Comment by fabyeah** [comment]
https://medium.com/@owencm/designing-great-uis-for-progressive-web-apps-dd38c1d20f7

**Recommendation 3: Touching an element while scrolling shouldn’t trigger touch feedback**

> The issue was fixed by aborting the ripple animation if the user’s touch location moved more than 6 pixels in any direction within the first few hundred milliseconds.
