### ISSUE TITLE
rtl support for Arabic, Hebrew and Farsi languages

### ISSUE THREAD

**Issue by srabeat** [Dogfalo/materialize#3002]
Is Materialize going to support rtl languages? I would love to contribute if it's on your roadmap.

**Comment by Dogfalo** [comment]
We currently have no plans for it. There is a third party fork which hacks in RTL support. Search the issues to find it.

**Comment by MetaiR** [comment]
@srabeat
https://github.com/MetaiR/materializeCss-rtl
checked with samples
