### ISSUE TITLE
Sidenav does not work

### ISSUE THREAD

**Issue by JackBank** [Dogfalo/materialize#3003]
When I click the hamburger it doesn't slide out.. i really dont know what to do..

`<!DOCTYPE html>
<html>
    <head>
        
        <link href="http://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
        
        <link type="text/css" rel="stylesheet" href="css/materialize.min.css"  media="screen,projection"/>

        
        <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    </head>

    <body>
        <nav>
            <div class="nav-wrapper">
                <a href="#!" class="brand-logo">Logo</a>
                <a href="#" data-activates="mobile-demo" class="button-collapse"><i class="material-icons">menu</i></a>
                <ul class="right hide-on-med-and-down">
                    <li><a href="sass.html">Sass</a></li>
                    <li><a href="badges.html">Components</a></li>
                    <li><a href="collapsible.html">Javascript</a></li>
                    <li><a href="mobile.html">Mobile</a></li>
                </ul>
                <ul class="side-nav" id="mobile-demo">
                    <li><a href="sass.html">Sass</a></li>
                    <li><a href="badges.html">Components</a></li>
                    <li><a href="collapsible.html">Javascript</a></li>
                    <li><a href="mobile.html">Mobile</a></li>
                </ul>
            </div>
        </nav>
        
        <script>
            $( document ).ready(function(){
                $(".button-collapse").sideNav({edge: 'left'});
            });
        </script>
        <script type="text/javascript" src="https://code.jquery.com/jquery-2.1.1.min.js"></script>
        <script type="text/javascript" src="js/materialize.min.js"></script>
    </body>
</html>`

**Comment by uok** [comment]
I put your HTML into a [materialize codepen](http://codepen.io/Dogfalo/pen/xbzPQV) (v0.97.5) and it seems to work
make sure to check if you load all libraries correctly and watch for errors in the javascript console

**Comment by JackBank** [comment]
Even if I put it in that codepen it doesn't work for me.. I try to click on it but it doesn't slide out

**Comment by JackBank** [comment]
I don't get any errors when i use my code in netbeans..

**Comment by JackBank** [comment]
codepen does work now but the code still doesn't work when I put it in my documents

**Comment by Dogfalo** [comment]
Well your script is above jQuery dependency so it will not work.
