### ISSUE TITLE
Angular select don't work

### ISSUE THREAD

**Issue by pmargreff** [Dogfalo/materialize#3005]
Hi, i'm try to use materialize with angular. But, all times i try to use ng-repeat to construct a select, it not work. Someone could help me with that issue?

**Comment by pmargreff** [comment]
I solve the problem written a jQuery funcition to build the select on hand, and after I call $('select').material_select(); to render it ([how is indicate in this question](https://github.com/Dogfalo/materialize/issues/2062)).

**Comment by Dogfalo** [comment]
The need for this is described in the documentation
