### ISSUE TITLE
Buttons in Navbar in IE10 / IE11 placed incorrectly

### ISSUE THREAD

**Issue by vp2177** [Dogfalo/materialize#3008]
Screenshot (IE11 vs Chrome):
![materialize-navbar-ie11](https://cloud.githubusercontent.com/assets/451903/14335582/50f7cdca-fc54-11e5-986b-5c3d67925712.png)

**Comment by pmargreff** [comment]
I guess it isn't only in IE, after last (0.97.6 - 2016 April 1st) update my `navbar` icon is invisible too. For me it's broked on Chrome and Firefox. 

**Before** update:

![print2](https://cloud.githubusercontent.com/assets/9089847/14372192/ad9e1db6-fd14-11e5-8716-ee267b68ee22.jpeg)


**After** update:

![print1](https://cloud.githubusercontent.com/assets/9089847/14372173/8868ca78-fd14-11e5-9a0b-9f3570a42bf9.jpeg)

**Comment by vp2177** [comment]
My issue is due to the `nav ul { margin: 0 }` rule.
If I remove that, it is fine.

Affected browsers:
* Chrome 49
* IE 11

Not affected:
* Chrome 51 (canary)
* Firefox 45

**Comment by fega** [comment]
@vp2177 
Could you check if this is still an issue with the latest version?

Closed due inactivity, feel free to reopen it if it is still necessary.
