### ISSUE TITLE
Date Picker

### ISSUE THREAD

**Issue by MarcoCucchi** [Dogfalo/materialize#3009]
Hi guys, we have an issue on Data picker, see below:

- open a Date picher.
- press Close
- open a new browser tab
- come back to Date picker page. BUG: although I close the dp, it comes out again. (you can see it in the attached screen)

![date_picker](https://cloud.githubusercontent.com/assets/13817916/14349388/0e63c67a-fcc3-11e5-918a-065d6d1f5c10.gif)

**Comment by ElieSaber22** [comment]
try to remove the focus from it.

**Comment by Thanood** [comment]
see https://github.com/Dogfalo/materialize/issues/2067 for a workaround
see also https://github.com/amsul/pickadate.js/issues/160

**Comment by MarcoCucchi** [comment]
Thank you  @ElieSaber22 @Thanood
