### ISSUE TITLE
material_select parameters

### ISSUE THREAD

**Issue by ElieSaber22** [Dogfalo/materialize#3010]
Please if could somebody write what are the parameters that can be used in the material_select:
Like:  $("#ddlCodes").material_select("destroy");

Is there something like:  1-  $("#ddlCodes").material_select("selectAll");
                                       2-  $("#ddlCodes").material_select("deselectAll");
                                       3-  $("#ddlCodes").material_select("refresh");
                                       4- $("#ddlCodes").material_select("update"); ...

Please it will help a lot especially in Multi Check Boxes Select;
Thanks.

**Comment by Thanood** [comment]
Apparently, there is only "destroy".
To be perfectly sure, look here: https://github.com/Dogfalo/materialize/blob/master/js/forms.js#L279
Search for "callback" in the scope of the select plugin.

**Comment by ElieSaber22** [comment]
Thanks for your fast and good answer.
