### ISSUE TITLE
Uncaught ReferenceError: Hammer is not defined

### ISSUE THREAD

**Issue by locomain** [Dogfalo/materialize#3011]
Uncaught ReferenceError: Hammer is not defined.
exception is thrown when including the library in Electron.

**Comment by dreszczyk** [comment]
+1

**Comment by locomain** [comment]
i fixed this by downloading and adding hammer.js like this   <script src="content/scripts/libs/hammer.js" onload="window.Hammer = module.exports;"></script>

**Comment by yuen1318** [comment]
@locomain  where can i download hammer.js?
