### ISSUE TITLE
Dropdown width issue

### ISSUE THREAD

**Issue by Isprago94** [Dogfalo/materialize#3014]
If you set activation on hover as false, the width of the dropwdown list is the same than the dropwdown although you set constrain_width as false.

**Comment by neFAST** [comment]
Did you found a workaround?

**Comment by hacker115** [comment]
I have the same isue but all the options are ignored if you disable the hover option.
So if I have the following code in my JS its all ignored.
`               inDuration: 300,
                outDuration: 225,
                constrain_width: false, // Does not change width of dropdown to that of the activator
                hover: false, // Activate on hover
                gutter: 0, // Spacing from edge
                belowOrigin: true, // Displays dropdown below the button
                alignment: 'right' // Displays dropdown with edge aligned to the left of button`
Anyone with a solution for this problem?

**Comment by fega** [comment]
@Isprago94 I'm unable to reproduce it in the latest version: https://codepen.io/fega/pen/GmKKpR

Closed, feel free to reopen it if it is still necessary.
