### ISSUE TITLE
php sass compiling error

### ISSUE THREAD

**Issue by niC00L** [Dogfalo/materialize#3017]
Hi, I'm using Nette framework and php sass compiler. I have this problem

> parse error: failed at `$materialize-red: (` /scss/materialize/components/_color.scss on line 10

And here is what NetBeans tells about this 
![errorsass](https://cloud.githubusercontent.com/assets/12592426/14403468/7bd310ae-fe57-11e5-9594-e4305e22f20f.png)

How can I solve this?
Thanks

**Comment by fega** [comment]
Closed due inactivity, feel free to reopen it if it is still necessary.

**Comment by DanielRuf** [comment]
Try to configure your IDE for SASS
