### ISSUE TITLE
Icon prefix with input fields with s12 in small screens goes out of the view port

### ISSUE THREAD

**Issue by Parthchokshi** [Dogfalo/materialize#3018]
I was making a form with s12 in small screens and m10 in medium and large screens. I noticed that if we keep the icon prefix and also col s12 in small screens, it goes out of the view port and generates horizontal scrolling. You can notice that in materializecss.com mobile website where the example of how to do the icon prefix is given. Same issues seems there. 

![cc934e1f-2c57-4424-93b9-b796370424ee](https://cloud.githubusercontent.com/assets/6808993/14405993/1f415400-fe6a-11e5-95cd-c55fafd5c4ba.jpg)

**Comment by acburst** [comment]
Good catch! Thanks for pointing this out

Fixed in 9d8cd80.

**Comment by Parthchokshi** [comment]
Oh, so it is not merged yet, isn't it?
