### ISSUE TITLE
Select options not selectable after scrolling

### ISSUE THREAD

**Issue by arrebarritra** [Dogfalo/materialize#3019]
Issue: 
If you add enough items on a select for a scrollbar to appear; then you scroll down and click on an option it is not selected.

Selecting option without scrolling:
1. Selecting
![screenshot 18](https://cloud.githubusercontent.com/assets/16391017/14406605/cd6c796e-feac-11e5-9019-995eece5486b.png)
2. Selected
![screenshot 20](https://cloud.githubusercontent.com/assets/16391017/14406610/deb1a938-feac-11e5-8543-bdffe055d1fc.png)

Selecting options after scrolling:
1. Selecting
![screenshot 19](https://cloud.githubusercontent.com/assets/16391017/14406611/ea28470e-feac-11e5-9534-2e9b9419d39e.png)
2. Item is not selected
![screenshot 20](https://cloud.githubusercontent.com/assets/16391017/14406613/0061e926-fead-11e5-8882-dcbda9cd1ce0.png)

**Comment by swunderlich** [comment]
Same issue with `class="browser default"`.

**Comment by swunderlich** [comment]
@arrebarritra Check if you are generating the options dynamically and if it's called only once. It solved my problem. ;)

**Comment by arrebarritra** [comment]
@swunderlich no it is only called once. I don't think this is a problem with my code because I have tested adding more select options on the selects on the materialize website and they too don't work properly. Can you specify exactly what solved your problem?

**Comment by arrebarritra** [comment]
And by the way scrolling does work on the browser default as evident by this codepen http://codepen.io/anon/pen/GZYYeW

**Comment by swunderlich** [comment]
Sure. I am using materialize with angular2. I wanted to use the styled select fields. (`$('select').material_select();`). But as this call runs after angular having it "things" done, it seems to break bindings. I wasn't eager to dig in deeper. So I rolled back to the browser default. This wasn't working as well until I recognized that my `*ngFor` iterator was called all the time. My **angular2** code now looks like this:
```
<select class="browser-default" [(ngModel)]="someModel.someAttr">
     <optgroup label="Some description">
            <option *ngFor="#option of availableOptions" [value]="option.value">
                    {{option.description}}
            </option>
     </optgroup>
</select>`
```

Hope this helps.

**Comment by swunderlich** [comment]
http://codepen.io/anon/pen/WwaYNy works for me though!?

**Comment by arrebarritra** [comment]
I'll get back to you soon, I'll test some things

**Comment by arrebarritra** [comment]
Well it might be something that ruins the select easily, scrolling and selecting is not working on materializes website and neither on mine. I made another bit of code testing it and it's working. So it's a  mystery why this is happening

**Comment by arrebarritra** [comment]
After a little research I have found that putting two <select> beside or near (I still haven't looked in to exactly when it happens) each other will cause this problem

**Comment by arrebarritra** [comment]
And finally it was just an error with Materialize 0.97.3. Upgraded to .6 and it works
