### ISSUE TITLE
mdi-navigation-menu has vanished

### ISSUE THREAD

**Issue by Queatz** [Dogfalo/materialize#3022]
As described in http://materializecss.com/side-nav.html

`mdi-navigation-menu` has vanished in `0.97.6`.  It was in `0.97.5`.

**Comment by Dogfalo** [comment]
Sorry, the documentation was incorrect. I just fixed it now, take a look at the changes here to see how to fix it. This is a result of the old icon font being deprecated and finally removed with this latest version. 489279f23aaa0c7a901eb6ffa30b34c76591d67a
