### ISSUE TITLE
parallax-container height not changing

### ISSUE THREAD

**Issue by pricetula** [Dogfalo/materialize#3023]
Following the instructions set on materialize documentation. The height of the parallax container doesn't seem to change despite adding a custom css file with : -

<link type="text/css" rel="stylesheet" href="css/materialize.min.css"  media="screen,projection"/>

<link type="text/css" rel="stylesheet" href="css/custom.css"  media="screen,projection"/>

//Content of custom.css file
.parallax-container{
  height:"100px";
}

**Comment by Marcusg62** [comment]
I have same issue, what was the fix?

**Comment by pricetula** [comment]
@Marcusg62 my problem was silly height:"100px"; css should not have quotes on the value should have been height: 100px;
