### ISSUE TITLE
as the two select be renamed

### ISSUE THREAD

**Issue by yoclens** [Dogfalo/materialize#3026]
hello I have two select it on the same page and one keeps me and the other will not be that there are problems to use two select on the same page with the option materialize and change the texe tipe and I saved correctly
$('select').material_select(); as the two select be renamed

**Comment by TyrionGraphiste** [comment]
Hi,

If you could provide a JSfiddle it'll be useful. You can have more than one select in your page ofc, it works on the documentation, take a look.
