### ISSUE TITLE
Active tab not working in modal

### ISSUE THREAD

**Issue by artur99** [Dogfalo/materialize#3027]
The `indicator` for the active tab in a modal is not working.
Example code: https://jsfiddle.net/pyef686w/

It will show up the active tab's contents, but the indicator, the pink bar won't show up until the first click in the popup...

(It starts working if I reinitialize the tabs(`$('ul.tabs').tabs();`) with the modal opent, but using this, the DOM will get 2 `.indicator` elements...

Thank you!

**Comment by artur99** [comment]
Temporary solved with: `$($("ul.tabs a")[0]).trigger( "click" );`, but I think there should be a better way of doing this..

**Comment by Ketcap** [comment]
had a same issue find a way to do it .. Solution is 
call tab function after opened modal.
So if you are using openModal() function to open it call tabs after that or if you are using leanModal use 
selector.modal({
ready:function(){
 selector.tabs()
}
})

worked for me let me know if it works

**Comment by kit1989** [comment]
Ketcap, work for me! Thanks!
