### ISSUE TITLE
Icons no longer working on chrome/RHEL 6.5

### ISSUE THREAD

**Issue by austinbarrington** [Dogfalo/materialize#3028]
Hello,

All of the materialize icons are not working just for linux based systems.

![image](https://cloud.githubusercontent.com/assets/5592627/14454901/9995b616-0094-11e6-892c-e394255fe1a8.png)

**Comment by Dogfalo** [comment]
I believe you just haven't included the web font hosted by Google

**Comment by austinbarrington** [comment]
I apologise, it seems to be where I am running two VPN's google must be blocking my connection to the fonts from where ever I am exiting.
