### ISSUE TITLE
Select don't work in Modal

### ISSUE THREAD

**Issue by tthil** [Dogfalo/materialize#3029]
Using Select in Modal don't work. the onChange event never trigger.

<Select className='col s4' multi simpleValue value={this.state.classValue} placeholder='Select trip class' options={this.state.classOptions} onChange={this.handleSelectChange.bind(this, 'classValue')} />

//Thomas

**Comment by quentinHydrobat** [comment]
Hey =)

Your <select> html is added dynamically or already in ?

**Comment by Helwieahmad** [comment]
i have question. how to design navbar with more submenu and arrange to horizontal?

**Comment by quentinHydrobat** [comment]
@Helwieahmad Go to https://gitter.im/Dogfalo/materialize or create your own ticket ...

**Comment by TyrionGraphiste** [comment]
Hi, did you solve your issue ?
