### ISSUE TITLE
Problem with tabs created dynamically

### ISSUE THREAD

**Issue by IamHenryValdez** [Dogfalo/materialize#3030]
Hi everyone, 
I have a problem with the creation of tabs dynamically,
When i append to the DOM an new tabs, I call $("ul.tabs").tabs() and use the select_tab method after, what happen is that it does display the new tab, but doesn't hide the current one. It display the new tab at the bottom of the old.

**Comment by quentinHydrobat** [comment]
That's weird, code snippet or screenshot are welcome =)

**Comment by IamHenryValdez** [comment]
Here is my add_tab function
![capture1](https://cloud.githubusercontent.com/assets/8546853/14461315/fc501576-008f-11e6-87e3-36e81b8e2253.PNG)

Here is the base html code where the tabs are displayed
![capture2](https://cloud.githubusercontent.com/assets/8546853/14461328/0e1dca28-0090-11e6-9661-3155b561f34d.PNG)

Here is the DOM when the new tab is attached
![capture4](https://cloud.githubusercontent.com/assets/8546853/14461343/21aeac38-0090-11e6-9ee7-7a25df9bbc46.PNG)

**Comment by quentinHydrobat** [comment]
You have to destroy your tabs then rebuild it (entirely) then trigger it again with `$('ul.tabs').tabs();` then select tabs ... sad but it's the same with ```<select>``` when you want to add or select another `<option>`

**Comment by IamHenryValdez** [comment]
For real ? Is it the only solution because it seems... like not the more optimized solutions. anyway. Looks like I'll have to clone the elements..

**Comment by quentinHydrobat** [comment]
Materialize isn't the solution if you use a lot of dynamic informations (look at http://materializecss.com/showcase.html) sooooo, do as you want.

**Comment by IamHenryValdez** [comment]
Ohh. I found the solution. It was very dumb. The href attribute in the <a> tags in the ul.tabs wasn't the same has the one of the tab...........
