### ISSUE TITLE
Parallax Image scaling for large images.

### ISSUE THREAD

**Issue by rubendinho** [Dogfalo/materialize#3036]
I am using a large image (2000 x 1333) with Parallax, but the parallax effect is only showing a small piece of it.

Is there a way to control the scaling of the the Parallax image effect using CSS?

Thanks,

**Comment by acburst** [comment]
Can you post a code example? Our parallax tries to maintain the image in its natural resolution. You can tweak the width of the parallax img and the height of the parallax container but then you have to make sure that its dimensions will always fit in the container.

**Comment by ciobamike** [comment]
Same issue, I simply fixed it with : 

`.parallax img { width: 100%; }`

**Comment by rubendinho** [comment]
worked like a charm - thanks!


On April 29, 2016 at 7:54:54 AM, ciobamike (notifications@github.com) wrote:

Same issue, I simply fixed it with :

.parallax img { width: 100%; }

**Comment by Cypher1** [comment]
Thanks @ciobamike

**Comment by GGolov** [comment]
With high-res photos I found this solution (plain CSS):

```
@media only screen and (max-width : 992px) {
  .parallax img {
    max-height: 100%;
  }
}

@media only screen and (min-width: 993px) {
  .parallax img {
    max-height: 150%; /* or higher percentages. It's up to your taste */
  }
}

**Comment by fega** [comment]
@GGolov @ciobamike Thanks!

**Comment by Naterra** [comment]
Did you try to add class="responsive-img" to the img tag?

**Comment by puremilkorwhite** [comment]
`<picture>
	<source media="(min-width: 1680px)" srcset="images/spotlight1-1680.jpg">
	<source media="(min-width: 1280px)" srcset="images/spotlight1-1280.jpg">
	<source media="(min-width: 980px)" srcset="images/spotlight1-980.jpg">
	<source media="(min-width: 736px)" srcset="images/spotlight1-736.jpg">
	<source media="(min-width: 480px)" srcset="images/spotlight1-480.jpg">
	<source media="(min-width: 1px)" srcset="images/spotlight1.jpg">
	
	<img src="images/spotlight1.jpg" alt="Fout bij laden" style="width:100%;">
</picture>`

While you are at it, imagine you could minimize the used bandwith.
