### ISSUE TITLE
sideNav with edge=right broken

### ISSUE THREAD

**Issue by yzargari** [Dogfalo/materialize#3037]
Hello,

I just upgraded from 0.97.3 to 0.97.6 and the first thing I noticed is that my mobile sidenav, which is on the right side of the screen is no longer playing nice.
I partially shows up when hidden and misplaced when showing.

I noticed the css includes `right: auto` under .side-nav.right-aligned
If I remove that, it works fine again.

A bug, I guess?

**Comment by yzargari** [comment]
I think I realized what happen. I converted the css file to RTL (using rtlcss) and that changed the values from your original (it actually has `left: auto` on it).

I should not be coding at 4:30am...

**Comment by fega** [comment]
Please provide a way to reproduce it. like a [codepen](https://codepen.io/fega/pen/BWeZaG) or  a snippet

Closed due inactivity, feel free to reopen it if it is still necessary.
