### ISSUE TITLE
materialize functions don't work on imported pages

### ISSUE THREAD

**Issue by kenopen** [Dogfalo/materialize#3038]
Hi there,

I have a main jsp page with a navigation and menu bar with dropdowns, all works correctly. Based on options selected by the user a particular jsp page is imported using:

`<c:import url="pageName.jsp"/>`

This imported jsp also has dropdown menus on a nav bar, but don't work. From what I can tell the "data-activates" is not being picked up.

Sample list item code:

Menu bar item:
`<li id="idMenuDynamicGroup_sort"><a class="dropdown-button" href="#!" data-constrainwidth="false" data-activates="sort-dropdown"><i class="material-icons color-menu-font">sort_by_alpha</i></a></li>`

Linked menu:
`<ul id="sort-dropdown" class="dropdown-content" style="width:170;">
	
	<c:forEach var="map" varStatus="s_map" items="${on_List.orderMap}">
		<c:set var="imgName" value="${map.value > 0 ? 'arrow_upward':'arrow_downward'}" />
		<li><a href="javascript: void(0);" onclick="sortByLink(this,'list&action=setOrder&orderRef=${map.value}',${on_List.isSubsetList});">
		<i class="material-icons right" style="font-size:12px;">${imgName}</i>&nbsp;${map.key}</a></li>
	</c:forEach>
</ul>`

All materialize and jquery CDNs are imported at the top of the main page, and the `<script>$(document).ready(onLoadForm());</script>`

Is run at the bottom of the main page.

This menu works perfectly on the main page, but does not display on the imported page

Any advice?

**Comment by kenopen** [comment]
Solution found.

**Comment by tcitworld** [comment]
Well that's helpful.
