### ISSUE TITLE
[Feature Request] Extended Feature Set for SideNav

### ISSUE THREAD

**Issue by junland** [Dogfalo/materialize#3039]
Think the side bar / navigation drawer needs a little more attention, here are some things that I found in the material documentation (https://www.google.com/design/spec/patterns/navigation-drawer.html#navigation-drawer-content) that might be worth adding to the project.
- Full height navigation drawer / sidenav
- Navigation drawer clipped under the app bar
- Floating navigation drawer
- Mini navigation (Where only icons show)
- Sidenav header (See below)
  ![Navbar Content](https://material-design.storage.googleapis.com/publish/material_v_4/material_ext_publish/0Bzhp5Z4wHba3Q0tDQ3Z1OHg5VHc/patterns_navdrawer_elevation1.png)

**Comment by milost** [comment]
+1

**Comment by tomscholz** [comment]
Added in https://github.com/Dogfalo/materialize/commit/eeb1162faec168f21dc940a3d946018736c6dd68
Please close this issue
