### ISSUE TITLE
Unnecessary CSS class generated for shades

### ISSUE THREAD

**Issue by wemyss** [Dogfalo/materialize#3043]
**The issue**
In the generated css we have classes such as `.shades.black` and `.black` (as seen in below screenshots), isn't the `.shades` prefix unnecessary as there is no lighter or darker versions of each shade?

In the generated css files the following css classes are generated:
<img width="467" alt="screen shot 2016-04-15 at 3 39 23 pm" src="https://cloud.githubusercontent.com/assets/8426915/14552550/e1654ebc-0322-11e6-963f-2d896f90f3ba.png">
and
![screen shot 2016-04-15 at 4 10 27 pm](https://cloud.githubusercontent.com/assets/8426915/14552807/a16f95a4-0324-11e6-8eae-0e641bfabf40.png)

**What's causing the problem**
The following loop in _color.scss generates the css with the "shades" class name:
![screen shot 2016-04-15 at 4 02 50 pm](https://cloud.githubusercontent.com/assets/8426915/14552674/b9820466-0323-11e6-9afd-50c791a1b949.png)

And then right below is a loop for creating classes for each shade
![screen shot 2016-04-15 at 4 02 58 pm](https://cloud.githubusercontent.com/assets/8426915/14552679/be94463a-0323-11e6-92c0-d958f67095f4.png)

**Fix?**
Add an if condition in the colors loop to exclude shades as they have their own dedicated loop.

**Comment by acburst** [comment]
thanks for pointing this out!
