### ISSUE TITLE
Tiles / Grid list component? (question / feature request)

### ISSUE THREAD

**Issue by jacobq** [Dogfalo/materialize#3046]
It looks like there are no built-in components for making [tiles / grid lists](https://www.google.com/design/spec/components/grid-lists.html). Is that right or am I just not seeing them? If they're intentionally not included I'm curious to know where I can learn more about that design decision. 

(I am not a professional designer but am responsible for the design of an app that I'm making so am trying to learn. In my case, I want to present multiple choices where each choice has an icon or photo, a name, and possibly a description. Should I be using cards instead?)

**Comment by acburst** [comment]
You can use our grid system. Just make sure each item has the same height and it will naturally grid

**Comment by jacobq** [comment]
@acburst, ah thank you for the advice. Is there a particular component I should be using for each item or doesn't it matter (so long as they are set to display: inline-block;`)?

**Comment by Ephenodrom** [comment]
I needed a grid-list for one of my projects, so I build the grid-list on my on. Most complicated part was the sorting and resorting on page resizing. Feel free to use :).

https://github.com/Ephenodrom/Materialize-Grid-List
