### ISSUE TITLE
Input Type Label

### ISSUE THREAD

**Issue by farazappy** [Dogfalo/materialize#3049]
Hello,
I'm trying to change the **value** of _text_ field by clicking a _button_. I have the following code ->

_Text Field_
`<label for="mytext">My Label</label><input type="text" id="mytext">`
_Button_
`<button onclick="myFunction()">`
_Script_
`<script>
function myFunction() {
document.getElementById("mytext").value = "New Text";
}
</script>`

Usually when I click on the text field, the label slides up but when I try to change the value of the text field using the button, it over writes the label.

Any possible Fix?

Thanks.

**Something Like This Happens**
![image](https://cloud.githubusercontent.com/assets/16976631/14580060/f17ac388-03de-11e6-9121-107d446914ff.png)

**Something Like This Should Happen** _This Was Done By Clicking And Typing_
![image](https://cloud.githubusercontent.com/assets/16976631/14580062/0fe712cc-03df-11e6-8fac-d198fab9ca88.png)

**Comment by acburst** [comment]
Setting the value with javascript doesn't trigger any of our functions. You can try adding the active class to the label when you set the value of the text field.

**Comment by farazappy** [comment]
@acburst Thanks! That did worked for me!
