### ISSUE TITLE
Dynamic populating of select not working for materialize css

### ISSUE THREAD

**Issue by RohitLol** [Dogfalo/materialize#3050]
[wel.zip](https://github.com/Dogfalo/materialize/files/222365/wel.zip)

I have attached my php file which represents the issue that I'm facing when using materialize css and  dynamically populating select dropdown using javascript.
The select dropdown doesn't get populated by data appended through javascript. 
please help.

**Comment by matrix818181** [comment]
2 issues... in your code.

1. s1.value == 'Arsenal' --> s1.value == 1
2. Put "$('select').material_select();" after your for loop. You need to refresh the list after you're done.

In your example, I don't understand why you do basic javascript instead of using jQuery.

**Comment by Dogfalo** [comment]
Yep, @matrix818181 is right, you have to call the material_select() function if it is added dynamically. This is also mentioned in the documentation.

**Comment by apudiu** [comment]
But I'm experiencing a different & very odd problem.  I've 5 select's on a bottom sheet modal, The first one let me pick first 5, 2nd one let me pick 3 & rest of them allow only 1 item.

What is going on? no errors on console... Please help

**Comment by ramintagizade** [comment]
But what to do with the behavior of select closing window every time it updates .

**Comment by bhuiyanmobasshir94** [comment]
This really helped me @Dogfalo. Thank you so much
