### ISSUE TITLE
Italics in a collapsible header are squished

### ISSUE THREAD

**Issue by Cypher1** [Dogfalo/materialize#3052]
Italics in the header of a collapsible are restricted to 2rem (which is pretty small).
Why do we do this?

Can we not do it? Thanks

(Of course it is easy to have a work around but it doesn't make good sense to me.)

**Comment by acburst** [comment]
I'm not sure what you mean. Are you saying the letter spacing is squished? because we don't change letter spacing in collapsible header. Can you post some code examples?

**Comment by Cypher1** [comment]
Don't have the code with me but in the interests of responding now:

When using italics in a span that is in a collapsible header the width is restricted to 2rem which is far too small for any more than a single icon (which is what I think it was intended for). Cheers

**Comment by Cypher1** [comment]
Found it: in /components/_collapsible.sass


.collapsible {
  border-top: 1px solid $collapsible-border-color;
  border-right: 1px solid $collapsible-border-color;
  border-left: 1px solid $collapsible-border-color;
  margin: $element-top-margin 0 $element-bottom-margin 0;
  @extend .z-depth-1;
}

.collapsible-header {
  display: block;
  cursor: pointer;
  min-height: $collapsible-height;
  line-height: $collapsible-height;
  padding: 0 1rem;
  background-color: $collapsible-header-color;
  border-bottom: 1px solid $collapsible-border-color;

  i {
    width: 2rem; // right here
    font-size: 1.6rem;
    line-height: $collapsible-height;
    display: block;
    float: left;
    text-align: center;
    margin-right: 1rem;
  }
}
