### ISSUE TITLE
how to properly structure your html for pushpin?

### ISSUE THREAD

**Issue by masterpowers** [Dogfalo/materialize#3054]
I wanna use push pin on the right side like the one in the materializecss.com website

```
<div class="row">

<div class="col l8 m8 s12">
</div>

<div class="col l4 m4 s12" id="columniwannapush">
</div>

</div
```

```
<script>
  $(document).ready(function(){
    $('#columniwannapush').pushpin({ top: $('#columniwannapush').offset().top });
  });
</script>
        
```
I wanna Push pined the second column 

when i do it like that

the content on the first column is covered by the pinned item...

How can i do the same pin like in the official site of materializecss.com

**Comment by acburst** [comment]
Your structure is close

try: 
```
<div class="row">

<div class="col l8 m8 s12">
</div>

<div class="col l4 m4 s12">
  <div id="columniwannapush">

  </div>
</div>

</div
```

Because you don't want to take the column out of the flow. So add a nested div inside and call pushpin on that instead
