### ISSUE TITLE
Installation of materialize fails - npm install materialize-css

### ISSUE THREAD

**Issue by pricetula** [Dogfalo/materialize#3056]
Installation of Materialize through NPM always fails, I dont know why

npm ERR! node v4.2.2
npm ERR! npm  v2.14.7

npm ERR! shasum check failed for /tmp/npm-25465-e174659c/registry.npmjs.org/materialize-css/-/materialize-css-0.97.6.tgz
npm ERR! Expected: b4a7f7875005d5c43b2b22eaa7bdb74b050450fe
npm ERR! Actual:   934fb0b396bc5d260484e64970d576261def106e
npm ERR! From:     https://registry.npmjs.org/materialize-css/-/materialize-css-0.97.6.tgz
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

**Comment by Dogfalo** [comment]
I have node: v5.3.0 and npm: v3.3.12 and it is working for me.

**Comment by pricetula** [comment]
Thank you for the tip
I ran npm cache clean
Deleted the module manually then re-installed successfully
