### ISSUE TITLE
Meteor package v0.97.6

### ISSUE THREAD

**Issue by samybob1** [Dogfalo/materialize#3057]
The latest release (version 0.97.6) has been published on npm but not on Atmosphere! :cry: 

![npm](https://cloud.githubusercontent.com/assets/2417752/14611031/940a1074-0590-11e6-8f40-eafac7386e98.png)

![atmosphere](https://cloud.githubusercontent.com/assets/2417752/14610959/48043da8-0590-11e6-8407-740a9286651f.png)

**Comment by Dogfalo** [comment]
Seems autopublish for Meteor is dead / not working anymore. Will look into this more.

**Comment by keyscores** [comment]
+1 duplicated with https://github.com/Dogfalo/materialize/issues/3210

**Comment by Dogfalo** [comment]
We have pushed this version manually
