### ISSUE TITLE
CharacterCounter() executing twice angularjs

### ISSUE THREAD

**Issue by johhansantana** [Dogfalo/materialize#3058]
I'm using angularjs for a project, I've notice that this function `CharacterCounter()` already gets executed when refreshing the current page, but when I browser states in my app, when I go back to that input it doesn't have the CharacterCounter.

I tried executing manually the function when entering that state and it works, but when I refresh the page with the input (with my manual `CharacterCounter()` initialization function) it gets executed twice, resulting in a weird character counter render.

Is there a way to make `CharacterCounter()` not get executed when you first visit the app and only execute if I initialize it?

Or is there another solution for this?

Thanks!

**Comment by acburst** [comment]
Hmm, the characterCounter function should have checks so that calling it twice on the same element won't mess things up. You could check for the character counter element before you do your manual call
