### ISSUE TITLE
Radio filling color

### ISSUE THREAD

**Issue by Isprago94** [Dogfalo/materialize#3060]
Does it exist a way to change the color of que radio and the other components from the forms? I've tried adding: blue-text (to the input), blue (to the imput), blue (to the father <p>) etc...

**Comment by acburst** [comment]
You can change the radio color in our variables file. look for `$radio-fill-color`

**Comment by cytsunny** [comment]
So it is only possible to change the color by using SASS? Is there a way to change it if I use CSS directly?

**Comment by Dogfalo** [comment]
I advise using the chrome inspector to get the specific CSS selectors for this

**Comment by DanielRuf** [comment]
@cytsunny take a look at https://github.com/Dogfalo/materialize/blob/master/sass/components/forms/_radio-buttons.scss#L70-L73, this is normal CSS in general (with a color variable).

**Comment by cytsunny** [comment]
It is possible to change the color of a specific CSS selector or simply install SCSS compiler to change the code, but I would expect something like adding a class to change the color, just like what bootstrap do to button color, or what you do to background color and text color.

I would say this is a feature request. Not a must have, but will be really handy if you have this feature added.

**Comment by smileytechguy** [comment]
You can use custom CSS.  Here is the code needed to do override anywhere where the default teal is used (collapsed for longness), just replace `<?= COLOR_HEX ?>` with the hex color you want to use.

<details>
<summary>CSS</summary>
.collection .collection-item.active {
    background-color: <?= COLOR_HEX ?>;
}

.collection a.collection-item {
    color: <?= COLOR_HEX ?>;
}

.secondary-content {
    color: <?= COLOR_HEX ?>;
}

.progress .determinate {
    background-color: <?= COLOR_HEX ?>;
}

.progress .indeterminate {
    background-color: <?= COLOR_HEX ?>;
}

span.badge.new {
    background-color: <?= COLOR_HEX ?>;
}

.btn, .btn-large {
    background-color: <?= COLOR_HEX ?>;
}

.btn-floating {
    background-color: <?= COLOR_HEX ?>;
}

.btn-floating:hover {
    background-color: <?= COLOR_HEX ?>;
}

.fixed-action-btn .fab-backdrop {
    background-color: <?= COLOR_HEX ?>;
}

.dropdown-content li>a, .dropdown-content li>span {
    color: <?= COLOR_HEX ?>;
}

.chips.focus {
    border-bottom: 1px solid <?= COLOR_HEX ?>;
    box-shadow: 0 1px 0 0 <?= COLOR_HEX ?>;
}

.chips .chip.selected {
    background-color: <?= COLOR_HEX ?>;
}

input:not([type]):focus:not([readonly]), input[type=text]:focus:not([readonly]), input[type=password]:focus:not([readonly]), input[type=email]:focus:not([readonly]), input[type=url]:focus:not([readonly]), input[type=time]:focus:not([readonly]), input[type=date]:focus:not([readonly]), input[type=datetime]:focus:not([readonly]), input[type=datetime-local]:focus:not([readonly]), input[type=tel]:focus:not([readonly]), input[type=number]:focus:not([readonly]), input[type=search]:focus:not([readonly]), textarea.materialize-textarea:focus:not([readonly]) {
    border-bottom: 1px solid <?= COLOR_HEX ?>;
    box-shadow: 0 1px 0 0 <?= COLOR_HEX ?>;
}

input:not([type]):focus:not([readonly])+label, input[type=text]:focus:not([readonly])+label, input[type=password]:focus:not([readonly])+label, input[type=email]:focus:not([readonly])+label, input[type=url]:focus:not([readonly])+label, input[type=time]:focus:not([readonly])+label, input[type=date]:focus:not([readonly])+label, input[type=datetime]:focus:not([readonly])+label, input[type=datetime-local]:focus:not([readonly])+label, input[type=tel]:focus:not([readonly])+label, input[type=number]:focus:not([readonly])+label, input[type=search]:focus:not([readonly])+label, textarea.materialize-textarea:focus:not([readonly])+label {
    color: <?= COLOR_HEX ?>;
}

.input-field .prefix.active {
    color: <?= COLOR_HEX ?>;
}

[type="radio"]:checked+label:after, [type="radio"].with-gap:checked+label:before, [type="radio"].with-gap:checked+label:after {
    border: 2px solid <?= COLOR_HEX ?>;
}

[type="radio"]:checked+label:after, [type="radio"].with-gap:checked+label:after {
    background-color: <?= COLOR_HEX ?>;
}

[type="checkbox"]:checked+label:before {
    border-right: 2px solid <?= COLOR_HEX ?>;
    border-bottom: 2px solid <?= COLOR_HEX ?>;
}


/* Indeterminate checkbox */

[type="checkbox"]:indeterminate+label:before {
    border-right: 2px solid <?= COLOR_HEX ?>;
}

[type="checkbox"].filled-in:checked+label:after {
    border: 2px solid <?= COLOR_HEX ?>;
    background-color: <?= COLOR_HEX ?>;
}

[type="checkbox"].filled-in.tabbed:checked:focus+label:after {
    background-color: <?= COLOR_HEX ?>;
    border-color: <?= COLOR_HEX ?>;
}

input[type=range]+.thumb {
    background-color: <?= COLOR_HEX ?>;
}

input[type=range]+.thumb .value {
    color: <?= COLOR_HEX ?>;
}

input[type=range]::-webkit-slider-thumb {
    background-color: <?= COLOR_HEX ?>;
}

input[type=range]::-moz-range-thumb {
    background: <?= COLOR_HEX ?>;
}

input[type=range]::-ms-thumb {
    background: <?= COLOR_HEX ?>;
}

.side-nav li>a.btn-floating:hover {
    background-color: <?= COLOR_HEX ?>;
}

.spinner-layer {
    border-color: <?= COLOR_HEX ?>;
}

.picker__date-display {
    background-color: <?= COLOR_HEX ?>;
}

.picker__day.picker__day--today {
    color: <?= COLOR_HEX ?>;
}

.picker__day--selected, .picker__day--selected:hover, .picker--focused .picker__day--selected {
    background-color: <?= COLOR_HEX ?>;
}

.picker__close, .picker__today {
    color: <?= COLOR_HEX ?>;
}
</details>

**Comment by DanielRuf** [comment]
Exactly.

Just use
```css
[type="radio"]:checked + label:after,
[type="radio"].with-gap:checked + label:after {
  background-color: #yourhexcolor;
}
```

**Comment by tomscholz** [comment]
See https://github.com/Dogfalo/materialize/pull/3904
