### ISSUE TITLE
Multiple dates select

### ISSUE THREAD

**Issue by lebart** [Dogfalo/materialize#3061]
Hi, 

Is there a way to use the datepicker for selecting multiple dates at once? The classic output would be a comma separated values of dates. 

I tried pickadate.js `allowMultiple` option without success. 

If it's not possible yet could we tag this issue with futur enhancement ?

**Comment by fega** [comment]
Personally, I dislike, it could be confusing for the user

**Comment by lebart** [comment]
@fega Can you tell me more about "confusing"? I use it all the time for booking purposes when ranges are not an option, or for events creation when you need an event to be at different dates. 

If it's an option and it defaults to false, we can avoid any confusion and let the programer decides when to use it for instance when the end user knows that it's available?

**Comment by fega** [comment]
Well I'm trying to imagine how it could work in my mind :laughing: , can you show me an example of your implementation? I'm really interested in this kind of usability improvements

**Comment by lebart** [comment]
Haha we both don't understand each other mind ;) But thanks for trying ! 

I'll post some code if it could help. But basically here is a typical situation: 

- Basic app for activities management. 
- An activity will have a title, a start (datetime), an end (datetime), and a bunch of other fields
- Client says: "we need to make an activity and it will occur three times, monday x, thuesday y and monday z in two weeks". We didn't want to repeat the process of filling a new activity form for each date because it's the same infos except for the dates. Here dates didn't follow a pattern like every x week... 

In the form we put an text field connected to the date picker and this particular datepicker is set to allow multiple pick. So the datepicker won't close when a date is selected and the user can select some other dates. The selected dates appeared with a different color on the datepicker so the user sees which dates are chosen. 

The text field is filled with dates separated by a comma. 

In the backend we can now parse the textfield and do what we need to do: created more activities in the db with different dates or put dates in a separated model .... 
 
[Here is an exemple of the multiple date picker in action](http://jsbin.com/jijatuqani/edit?html,js,output) Just be sure to uncomment the allowMultiple line in the options.

Hope this helps!

**Comment by fega** [comment]
hahaha, I was imagining something totally different,

I guess that should be nice to be implemented, but I don't know if it fits better in a plugin, due the fact that is not an extremely common issue.

**Comment by lebart** [comment]
@fega you making me curious, what were you thinking about? 

I agreed to the fact that it's not a common use case, but I also think that it could be a nice enhancement! 

The fact that the date picker is part of the framework is interesting and avoid having to chose another lib and then try to adjust all its classes and styles to match the framework and theme.

**Comment by tomscholz** [comment]
Materialize uses a modified version of [amsul/pickadate.js](https://github.com/amsul/pickadate.js/) The problem is that pickadate currently does not have support for multiple dates. [Reference](https://github.com/amsul/pickadate.js/issues/83)

**Comment by fega** [comment]
Yeah that's true, and for that reason, it was added to the feature request board, the lead contributors will decide if this should be added or not

My thought is that, as you can see, we have a huge bottleneck in the pull request, we are working to move all the things, but I believe that it will take a while to keep the things flowing as expected again.

I'm not discouraging you from making a pull request I'm pointing that it will take some time to review and merge this kind of pull request, You could add quickly in a plugin in benefit the community sooner.

**Comment by lebart** [comment]
@tomscholz As you mentioned that Materialize uses a modified version cannot it be simpler to add this? 

Actually I know that pickadate currently didn't support it, but the link mentioned above on jsbin shows  that the version 4.0 of pickadate can do it. Maybe we can grab the code for that and use it in the "modified version" ?

**Comment by tomscholz** [comment]
The jsbin didn't work for me at all  :)

**Comment by lebart** [comment]
@fega I agree with you, maybe there are more important things to do. As soon as I got time I'll try something and share it if possible.

@tomscholz strange this is working for me

<img width="1969" alt="capture d ecran 2017-04-05 a 11 04 26" src="https://cloud.githubusercontent.com/assets/2455364/24712066/ce972a6e-19ef-11e7-9d83-53db3483c90f.png">

**Comment by tomscholz** [comment]
The problem with pickadate.js is that it is currently looking for Project Maintainers and the last commit to [version4](https://github.com/amsul/pickadate.js/tree/4.0.0) was back in 2014

**Comment by lebart** [comment]
@tomscholz sadly yes, maybe the decision should not to add new options to the date picker but do we need to maintain our own picker or should it be externalized. 

Maybe we should wait the answer of the lead contributors to the request and see if we get a clear vision for the future of the picker, than we can decide to make a move or not on the multiple date selection. 

BTW thanks for the discussion, I'm sure we'll come with great ideas.

**Comment by Dogfalo** [comment]
Picker maintenance is something we are looking into. But this feature is not something we plan to support in the near future.
