### ISSUE TITLE
Datepicker activates when changing between browser tab or window

### ISSUE THREAD

**Issue by Aeseir** [Dogfalo/materialize#3062]
Essentially when you land on a page where datepicker is active, if you change tabs or browser window and then go back to the original tab or window where the date picker is active it will automatically pop up without being interacted with by user.

Tested on Chrome 49.0.2623.112 and Edge 25.10586.0.0 browsers.

Steps to replicate:

1. Go to http://materializecss.com/forms.html#date-picker
2. Open up New Tab/Browser Window
3. Go back to tab containing the materializecss page
4. Datepicker should pop up

In some cases a step needs to be added in between 1 and 2 to also trigger the problem:
1 a) click on the Birthdate input field (you can select date or not up to you)

**Comment by Thanood** [comment]
Please have a look here: https://github.com/Dogfalo/materialize/issues/2067#issuecomment-142107599

@Dogfalo Maybe this  and the existing workaround should be mentioned in the docs.

**Comment by Aeseir** [comment]
@Thanood thank dude, missed that one. Definitely should be mentioned in docs.

**Comment by alexssandrog** [comment]
Hello, I did not find this workaround in docs, can you help me?
