### ISSUE TITLE
nav > ul > ul

### ISSUE THREAD

**Issue by valerio-bozzolan** [Dogfalo/materialize#3063]
# notabug?

https://jsfiddle.net/ak6wuftn/

MaterializeCSS already provides something to correctly style nested uls?

(#2276 ← That is a bad bug title!)

**Comment by acburst** [comment]
I'm not sure what problem you are trying to describe here. Can you explain more?

**Comment by valerio-bozzolan** [comment]
@acburst Both manually or using a CMS (see #2276) a lot of people use nested `ul`s. I mean menu trees in the navbar.

I don't know if this is more exaustive: https://jsfiddle.net/ak6wuftn/4/
![desktop](https://cloud.githubusercontent.com/assets/6052909/14812486/b0c7501a-0b9d-11e6-8b23-a5356331f0ee.png)

## What I see now as default
1. An `ul > ul > li` (even if it's always shown) it can't be seen because of white text on white background (e.g. "ghosts")
2. An `ul > ul` is always shown


## What I expect as default
1. `ul > ul > li` without white text on white background: not "ghosts". As you can see in the [previous](https://jsfiddle.net/ak6wuftn/) JSFiddle, people actually has to set e.g. `black-text`.
2. As default some sort of `ul > ul:hover` animation (I mean [this](http://line25.com/wp-content/uploads/2012/css-menu/demo/index.html)) in order to don't show suddently the complete menu tree.

**Comment by tomscholz** [comment]
Duplicate: https://github.com/Dogfalo/materialize/issues/859
