### ISSUE TITLE
Alternate optgroup and option

### ISSUE THREAD

**Issue by matrix818181** [Dogfalo/materialize#3064]
I'm trying to do something like this:
- Option A
- Option B
- Optgroup 1
  - Option 1A
  - Option 1B
- Option C
- Optgroup 2
  - Option 2A
  - Option 2B
- Option D
- Option E

But I get something like this :
- Option A
- Option B
- Optgroup 1
  - Option 1A
  - Option 1B
  - Option C
- Optgroup 2
  - Option 2A
  - Option 2B
  - Option D
  - Option E

**Comment by acburst** [comment]
Can you post your code? or a codepen

**Comment by matrix818181** [comment]
I double checked and it's was an issue from 0.97.5

I was not able to recreate with 0.97.6

Thx.
