### ISSUE TITLE
Tabs indicator negative right value

### ISSUE THREAD

**Issue by atulmy** [Dogfalo/materialize#3065]
`$indicator.css({"right": $tabs_width - (($index + 1) * $tab_width)});`

Can this be:
```
var right = $tabs_width - (($index + 1) * $tab_width
$indicator.css({"right": (right < 0) ? 0 : right)});
```
![tab-1](https://cloud.githubusercontent.com/assets/685786/14701217/cdf770a0-07c1-11e6-82d4-3558f98c0cca.png)
![tab-2](https://cloud.githubusercontent.com/assets/685786/14701215/cd81c8a0-07c1-11e6-88c5-08a18df8cf85.png)

**Comment by acburst** [comment]
Can you post your code? The right position should only be negative if your tabs have overflow so your solution would break overflowing tabs.

**Comment by atulmy** [comment]
@acburst you can check the code here: http://crowdproduct.com/engage

**Comment by acburst** [comment]
How do you recreate the bug? I'm on the latest chrome mac and I dont see the problem

**Comment by atulmy** [comment]
@acburst yes I am also unable to see the issue (which is a good thing). Maybe it had to do something with other leaky CSS which might have been changed. If incase I am able to reproduct, will open with the specific code again. Thanks for the help dude.

**Comment by diosat91** [comment]
I know that this issue was closed but I have been having the exact same issue. The only changes I have made to tabs are the colours, nothing to do with overflow.

**Comment by atulmy** [comment]
@diosat91 check if your `<ul class="tabs">` does not have any negative margin or more than 100% of width.

**Comment by diosat91** [comment]
Nope, neither. I tried out different numbers of tabs and found there to be negative right when there were 2, 6, 7 and 10 tabs (only tried 10), 0 when there were 1, 3, 5, 9 tabs and positive when there were 4 or 8. It appears to be a very slight rounding issue. It's only ever out by a few pixels which is barely noticeable except the scroller that appears like @atulmy's example above.

**Comment by mnannola** [comment]
@atulmy I able to reproduce this issue in Chrome 56.0.2924.87 on Mac.  I made a codepen showing the issue using the exact same markup as the materialize.css tabs example.

Steps to reproduce:
1.  Go to http://codepen.io/mnannola/pen/qrWoVL
2.  Resize your browser to 1152px x 590px
3.  Click on the last tab ("Test 4")
4.  Observe a overflow-y scrollbar going across all four tabs, and a 'right' property value of "-0.6875px;" on the indicator inline style tag.

![screen shot 2017-02-22 at 12 22 26 pm](https://cloud.githubusercontent.com/assets/2358757/23225991/a5320c46-f8f9-11e6-8511-771210943d99.png)

**Comment by mnannola** [comment]
@acburst should this issue be reopened?  Let me know if you would like me to provide any more info.

Digging into it a little more.  I think the issue lies in the calcRightPos function: https://github.com/Dogfalo/materialize/blob/master/js/tabs.js#L34

the `el.position().left` value is fractional, but el.outerWidth() function is not.

**Comment by atulmy** [comment]
@mnannola, strange. Doesn't show up the horizontal scroll anymore since I last encountered. Must be because of some leaky CSS or browser resize calculation, but anyway **the calculation should be fixed to avoid negative values**. 

I've used the tabs extensively, almost on all the pages on http://app.crowdproduct.com and it seems to work properly. 

Screenshot of your codepen on my macOS Sierra @ 10.12.3 (16D32) with Chrome @ 56.0.2924.87 (64-bit) with viewport of 1152px x 590px

![fireshot capture 63 - a pen by michael nannola - http___codepen io_mnannola_pen_qrwovl](https://cloud.githubusercontent.com/assets/685786/23228591/235610d6-f963-11e6-9391-197e1be62cb8.png)

**Comment by mnannola** [comment]
@atulmy thanks for looking at it.  That screenshot shows you have your codepen set to a different view than my screenshot, which probably affects this.  If you go to the 'Change View' button and select to have the main window on the bottom instead of the side, do you see the scrollbar?

**Comment by atulmy** [comment]
@mnannola, yes I did try changing the views (all 3 possibilities). No scroll though.

**Comment by mnannola** [comment]
@atulmy interesting!  I am on OS X El Capitan 10.11.5.  Not sure what else could be the culprit.  I also tried on Safari and received the same scrollbar when the viewport was the same size.
