### ISSUE TITLE
Huge compiled CSS when extending grid

### ISSUE THREAD

**Issue by kagneta** [Dogfalo/materialize#3066]
I noticed that when I extend the grid classes to make my markup more semantic the CSS file got super large (over 600kb). 

By moving the .col def outside of the .row definition, the file compiled to significantly less size (100kb). 

Hoping to get your thoughts on this

**Comment by acburst** [comment]
How exactly are you extending the grid? We use Sass loops to make all our grid classes so maybe you added something that is getting duplicated into all those classes.

**Comment by kagneta** [comment]
Im just using a sass @extend.  for example (not my actual code): 

.appBody {
   @extend .row 
}

questionText {
   @extend .col;
   @extend .l5;
   @extend .m12;
}

I have a few instances of this.  I assumed something was wrong with my code when my css was comming out at 500+kb so i did some reasearch and it lead me to believe my problem was extending nexted selectors.  So while the sass the generates the grid was originally like this:

row {
  margin-left: auto;
  margin-right: auto;
  margin-bottom: 20px;
  // Clear floating children
  &:after {
    content: "";
    display: table;
    clear: both;
  }

}

**Comment by fega** [comment]
@kagneta Did you solve your problem?

Closed due inactivity, feel free to reopen it if it is still necessary.
