### ISSUE TITLE
indeterminate-checkbox

### ISSUE THREAD

**Issue by MetaiR** [Dogfalo/materialize#3068]
hi all,
i saw the samples but i couldn't find any thing about which class has to be given to indeterminate checkbox to make an indeterminate-checkbox

**Comment by Dogfalo** [comment]
indeterminate is a html property that you set in javascript

**Comment by MetaiR** [comment]
can you show me the samples about that?

**Comment by acburst** [comment]
https://developer.mozilla.org/en-US/docs/Web/CSS/:indeterminate

**Comment by ermarkar** [comment]
how can i set materializecss checkbox state to indeterminate?? any working sample please?
