### ISSUE TITLE
ScrollFire not working

### ISSUE THREAD

**Issue by DarwinDLRD** [Dogfalo/materialize#3069]
¿Why? My code is...

`var options = [
    {selector: '#myelement', offset: 200, callback: '$(this).addClass("animated")' },
];
Materialize.scrollFire(options);`

and

`<span class="wow" id="myelement1">Hello, World!</span>`

The text is always visible :(

demo: https://jsfiddle.net/xouxscvu/

**Comment by acburst** [comment]
Currently $(this) won't refer to anything because our callback is just called, not through any jQuery events. I am going to work on extending our callback to return with a parameter which is the current selected element.

**Comment by acburst** [comment]
Added in e3b8c7f8828803b068990dfe1195620a64f6e2ed.

Here's how you would achieve what you want:

```
var options = [ {selector: '#myelement', offset: 200, callback: function(el) {
  $(el).addClass("animated")';
} }, ]; Materialize.scrollFire(options);
```
