### ISSUE TITLE
Grid tiers similar to angular-material/bootstrap

### ISSUE THREAD

**Issue by rajeev1982** [Dogfalo/materialize#3070]
Hi There,
I am starting to use materializecss and wrote a few pages so far using it. Just figured out that materializecss has only small, medium and large tier as compared to extra-small, small, medium, large and extra large in bootstrap and angular meterial. Having more tiers gives more control on how the pages will look on diff screen sizes. Would it be possible to extend grids to make it more granular to make it similar to angular-material. Here is the grids comparison.

**Materializecss:**
small                <= 600px   (Mobile devices)
medium           <= 992px   (Tablet Devices)
large                > 992px (Desktop Devices)

**Bootstrap:**
// Extra small devices (portrait phones, less than 34em)
// No media query since this is the default in Bootstrap

// Small devices (landscape phones, 34em and up)
@media (min-width: 34em) { ... }

// Medium devices (tablets, 48em and up)
@media (min-width: 48em) { ... }

// Large devices (desktops, 62em and up)
@media (min-width: 62em) { ... }

// Extra large devices (large desktops, 75em and up)
@media (min-width: 75em) { ... }

**Angular material:**
layout                  Sets default layout direction unless overridden by another breakpoint.
layout-xs              width < 600px
layout-gt-xs          width >= 600px
layout-sm             600px <= width < 960px
layout-gt-sm         width >= 960px
layout-md            960px <= width < 1280px
layout-gt-md        width >= 1280px
layout-lg              1280px <= width < 1920px
layout-gt-lg          width >= 1920px
layout-xl               width >= 1920px

**Comment by jaankoppe** [comment]
Hi.

I needed some extra media queries also, so I modified the sass files to add an "xs" media query.
It looks like it's mobile-first, so I had to modify the "s" to "xs" and then made a copy of the "m" where I changed it to "s".

What I did:

**_variables.scss**

Find the section 11.Global - Media Query Ranges and add these lines

`$extra-small-screen-up: 481px !default; 
$extra-small-screen: 480px !default; // <-- xs max width

$small-and-up: "only screen and (min-width : #{$extra-small-screen-up})" !default;
$extra-small-and-down: "only screen and (max-width : #{$extra-small-screen})" !default;`

**_grid.scss**

under the .col {...} :

_1. change s to xs:_

`@while $i <= $num-cols {
      $perc: unquote((100 / ($num-cols / $i)) + "%");
      &.xs#{$i} { // <-- s to xs
        width: $perc;
        margin-left: auto;
        left: auto;
        right: auto;
      }
      $i: $i + 1;
    }

    $i: 1;
    @while $i <= $num-cols {
      $perc: unquote((100 / ($num-cols / $i)) + "%");
      &.offset-xs#{$i} { // <-- s to xs
        margin-left: $perc;
      }
      &.pull-xs#{$i} { // <-- s to xs
        right: $perc;
      }
      &.push-xs#{$i} { // <-- s to xs
        left: $perc;
      }
      $i: $i + 1;
    }`

_2. Make copy of m and change m to s and medium to small:_

`@media #{$small-and-up} { // <-- medium to small

      $i: 1;
      @while $i <= $num-cols {
        $perc: unquote((100 / ($num-cols / $i)) + "%");
        &.s#{$i} { // <-- m to s
          width: $perc;
          margin-left: auto;
          left: auto;
          right: auto;
        }
        $i: $i + 1
      }

      $i: 1;
      @while $i <= $num-cols {
        $perc: unquote((100 / ($num-cols / $i)) + "%");
        &.offset-s#{$i} { <-- m to s
          margin-left: $perc;
        }
        &.pull-s#{$i} { <-- m to s
          right: $perc;
        }
        &.push-s#{$i} { <-- m to s
          left: $perc;
        }
        $i: $i + 1;
      }
    }`

After that compile it to css and you can use class="col xs*"

**Comment by acburst** [comment]
Added xl in 104da64
