### ISSUE TITLE
card issue

### ISSUE THREAD

**Issue by sun2rise** [Dogfalo/materialize#3071]
Hi,
can someone help me understand why this card doesn't work? the reveal is not going to reveal anyting..

http://jsfiddle.net/sunrising/nufxnj1e/

**Comment by alexandresoliveira** [comment]
You did not load jquery in external resources

https://ajax.googleapis.com/ajax/libs/jquery/2.2.2/jquery.min.js
https://cdnjs.cloudflare.com/ajax/libs/materialize/0.97.6/js/materialize.min.js
https://cdnjs.cloudflare.com/ajax/libs/materialize/0.97.6/css/materialize.min.css

Remember, the order of imports is important!

**Comment by sun2rise** [comment]
UH! Thanks,
In meteor the import order is a little messy, al least until version 1.2 (which i am still using).
maybe this detail should deserve a better highlight or a standard solution. or maybe i was the one missing it ;)

thanks again

**Comment by sun2rise** [comment]
@alexandresoliveira i'm sorry but i checked on my meteor project.. jquery is already bundled inside meteor so it loads first then materialize.. still the problem shows :(

**Comment by sun2rise** [comment]
i am working with meteor so jquery is always loaded before materializecss.. but if i test it on ipad or emulate ipad with chrome developer tools the reveal won't show up..

**Comment by sun2rise** [comment]
Problem found:
Cards and Modals do not work with pdfjs package
https://atmospherejs.com/pascoual/pdfjs
