### ISSUE TITLE
Misalignment in label when class=validate is used

### ISSUE THREAD

**Issue by liko28s** [Dogfalo/materialize#3072]
Hi Guys, i have an input with validation as follows:
`<div class="input-field col s12 m6 l3">
	<input type="text" name="first_name" id="frm-registerForm-first_name" required="" class="validate">
	<label for="frm-registerForm-first_name" data-error="Must be a valid Name" class="">First Name</label>
</div>`

And looks like
![image](https://cloud.githubusercontent.com/assets/9079747/14754585/f24b6fd4-08a1-11e6-8f29-3762a23b361a.png)

As you can see, there are a padding or misalignment in the label element when `class="validate"` is present

When i remove thee validation class is render as follows
![image](https://cloud.githubusercontent.com/assets/9079747/14754588/f9f072e8-08a1-11e6-9ee6-b26b393a2feb.png)

I think this is the right way to be displayed, can you please tell me what's wrong?

I'm using Materialize 0.97.6
PD: For a very weird reason the [codepen example](http://codepen.io/Dogfalo/pen/xbzPQV) is working fine.

**Comment by Dogfalo** [comment]
If the codepen is working then you likely have something in your own CSS file that might be affecting it.
