### ISSUE TITLE
Sass version no longer compiles

### ISSUE THREAD

**Issue by xaben** [Dogfalo/materialize#3074]
After latest upgrade of node-sass that broke some BC as explained here: https://medium.com/@xzyfer/why-node-sass-broke-your-code-and-semver-1b3e409c57b9#.nnml2bdw2

the sass version no longer compiles :(

It just dies with:

```
Segmentation fault (core dumped)
```

**Comment by Dogfalo** [comment]
Which node-sass version are you talking about?

**Comment by carlos-algms** [comment]
```shell
node node_modules/node-sass/bin/node-sass -v
node-sass       3.5.3   (Wrapper)       [JavaScript]
libsass         3.3.5   (Sass Compiler) [C/C++]
```

The last version that compiles is `0.97.3`, any newer version throw the segmentation fault error.

**Comment by xaben** [comment]
yes the last working version of node-sass is 3.4.2, all versions >= 3.5.0 do not work

**Comment by creatio** [comment]
Has tere been any progress on this issue?
