### ISSUE TITLE
Cannot incorporate Google Maps Api effectively with materialize inputs

### ISSUE THREAD

**Issue by Aeseir** [Dogfalo/materialize#3076]
Not sure if anyone has attempted this yet but i tried to corporate Maps Api Autocomplete Address  https://developers.google.com/maps/documentation/javascript/examples/places-autocomplete-addressform into my site and it just doesn't do anything.

Removing materialize css and js and it works fine, but with it nothing happens.

**Comment by derekrliang** [comment]
It seems to work for me.

Try my CodePen below, enter a valid Google Maps API Key.

[https://codepen.io/derekrliang/pen/GZBezL](https://codepen.io/derekrliang/pen/GZBezL)

**Comment by Dogfalo** [comment]
Thanks @derekrliang for the codepen demo.
