### ISSUE TITLE
<input> tags rendering with hard to click <i> around it

### ISSUE THREAD

**Issue by actuallymentor** [Dogfalo/materialize#3077]
When implementing a form (not using materialize form markup) the rendering makes the button hard to click. Specifically a wrapping <i> makes the button nonresponsive to clicking outside the actual text.

Source html:

`<input id="one" class="answer col l10 offset-l1 m12 s12 waves-effect waves-light btn" type="submit" value="I Understand and Agree"></input>`

Rendered html in chrome:

`<i class="answer col l10 offset-l1 m12 s12 waves-effect waves-light btn waves-input-wrapper" style=""><input id="one" class="waves-button-input" type="submit" value="I Understand and Agree"></i>`

Clicking the <i> gives a wave effect but does not trigger the form.

**Comment by derekrliang** [comment]
See the issue here, along with a button submit:
https://codepen.io/derekrliang/pen/GZBbyw

Any particular reason you want to use a input instead of a button for form submit?

**Comment by Dogfalo** [comment]
Your markup with the `i` tag wrapping seems very strange, place the waves effect on the button directly instead as @derekrliang does in his example
