### ISSUE TITLE
Displaying a different side-nav class when going to a different page.

### ISSUE THREAD

**Issue by claide** [Dogfalo/materialize#3079]
Is there a way I can change the display or the class of the side-nav when moving to another web page? For example a default side-nav when in home page and a fixed side-nav in other page. Or is there a forum for materializecss?

**Comment by derekrliang** [comment]
Not sure about any forums, but there is an official chat room:
https://gitter.im/Dogfalo/materialize

**Comment by claide** [comment]
Thanks for the link +1:

**Comment by fega** [comment]
Closed due inactivity, feel free to reopen it if it is still necessary.
