### ISSUE TITLE
Tabs problems in Bottom Sheet

### ISSUE THREAD

**Issue by Serkis** [Dogfalo/materialize#3081]
Please demo http://ders34.com/mm/index.html

"Bottom Sheet" when it first opened, "indicator" does not appear.

**Comment by acburst** [comment]
This is because the tabs are initialized in a hidden object. To get the indicator to show reinitialize the tabs like: `$('ul.tabs').tabs();` when you activate the modal

**Comment by Serkis** [comment]
Thank you so much.
