### ISSUE TITLE
Download Link on "Getting Started" is broken

### ISSUE THREAD

**Issue by ZykezIX** [Dogfalo/materialize#3088]
Thought I'd give you a quick heads up, the download link on:

http://www.um.es/docencia/barzana/materializecss/getting-started.html

Is broken. It currently points to: http://materializecss.com/bin/materialize-v0.97.5.zip

Updating the link to http://materializecss.com/bin/materialize-v0.97.6.zip allows it to succeed normally. 

(Also, the information in getting started should point to the x.6 version as well)

**Comment by acburst** [comment]
To be honest, I'm not sure who is hosting that link but we are not affiliated. Be sure to always use our site to get the most up to date documentation.

**Comment by ZykezIX** [comment]
Thanks for the update, but I will point out that the link I posted was the link found on this page:
http://materializecss.com/getting-started.html

Thanks,

**Comment by acburst** [comment]
Where exactly did you find that link?

**Comment by ZykezIX** [comment]
As I mentioned previously, it was found here:

http://materializecss.com/getting-started.html

Specifically, it was the associated link to this button:

![capture](https://cloud.githubusercontent.com/assets/9407482/14958586/76042140-1059-11e6-8f39-1b019a278281.PNG)

**Comment by Thanood** [comment]
JFI: for me, the link leads to the "normal" Materialize hosting:
http://materializecss.com/bin/materialize-v0.97.6.zip

**Comment by ZykezIX** [comment]
Right - it leads there now, I can confirm that. 

At the time I opened this, it did not. Nothing to worry about I suppose, just doing my due diligence. Let me know if I can get you any more information.

Thanks,
