### ISSUE TITLE
How can i Submit the Value of the Form Slider Component?

### ISSUE THREAD

**Issue by masterpowers** [Dogfalo/materialize#3089]
Hi im Using Laravel in my Project , and i tried to follow the simplest example in the site demo
yes i did get the same result... 
i also included it in my Form
```
{!! Form::open(['route' => 'guest::product@index', 'method' => 'GET', 'class' => 'col s12']) !!} 
        <div id="test5" name="priceRange[]"></div>

    {!! Form::submit('Filter', ['class' => 'btn waves-effect waves-light col s12']) !!}

    {!! Form::close() !!}

</div>
@endsection

@section('customjs')
<script>
var slider = document.getElementById('test5');
  noUiSlider.create(slider, {
   start: [20, 80],
   connect: true,
   step: 1,
   range: {
     'min': 0,
     'max': 100
   },
   format: wNumb({
     decimals: 0
   })
  })
</script>
@endsection
```
when i dd the request 
i get an empty array...

How can I add this to the request?
Any Solution to this?

**Comment by Dogfalo** [comment]
You can read the values of the slider by using their api call `.get()`. See documentation here: https://refreshless.com/nouislider/slider-read-write/
