### ISSUE TITLE
Checkbox is in disabled but still clickable

### ISSUE THREAD

**Issue by MaxineCaulfield** [Dogfalo/materialize#3092]
I use [systemjs](https://github.com/systemjs/systemjs) to load the materialize module and also used [artTemplate](https://github.com/aui/artTemplate) at the same time,but when the template output to the page , the modality of checkboxes shows that it was in disabled status.But after I clicked it changed to checked status.

disabled status :
![checkbox disabled](http://i3.piimg.com/a9a976f18ebb4f3e.png)
after click it :
![checkbox click](http://i3.piimg.com/57d11ba79a74d8bb.png)

The code which I use has been written below , I think it needs to be simular with updateTextFields() to reinitialize checkboxes.

messagePush.html
```html
<!-- atrTemplate area -->
<div id="addTpl" style="display: none;">
    {{each data as value}}
    <div class="userBox col l2 m3 s6">
        <div class="userImage">
            <div class="singleUser">
                {{#value.issended | issended:'' }}  <!-- function here -->
                <label for="{{value.id}}"></label>
            </div>
            <img src="{{value.imagurl}}">
        </div>
        <div class="userInfo">
            <span class="userName">{{value.name}}</span>
            <span class="userPhone">{{value.mobile}}</span>
        </div>
    </div>
    {{/each}}
</div>
<!-- output -->
<div id="target" style="overflow: hidden"></div>

<script>
System.import("../messagePush").then(function(load){
    load();
});
</script>
```

---

messagePush.js
```javascript
require("materialize");
var artTpl = require("arttemplate");

//atrTemplate helper snippet
$.ajax({
    url: url,
    dataType: 'json',
    type: 'post',
    data: { //some data here }
    success: function(data){
        var Tpl = artTpl('addTpl');
        artTpl.helper('issended',function(value){
            if(value == 1){
                return '<input type="checkbox" class="filled-in" disabled="disabled" id="'+ id +'">'
            }else{
                return '<input type="checkbox" class="filled-in" id="'+ id +'">'
            }
        });
        $('#target').html(Tpl);
    }
});
```

**Comment by Dogfalo** [comment]
Checkboxes don't require JavaScript, disabled is an HTML feature. The problem is not with Materialize in this case. It may be something to do with the ArtTemplate. I have checked that adding the disabled attribute does disable mouse click events. 

http://codepen.io/Dogfalo/pen/MyzyPB
