### ISSUE TITLE
Mixed content over SSL

### ISSUE THREAD

**Issue by MicheleRiva** [Dogfalo/materialize#3093]
Hi,
my website is working over SSL connection, but I get an issue with the icon font.
Here you are what I get with my chrome console:

`materialize.min.js:6 Mixed Content: The page at 'https://micheleriva.it/' was loaded over HTTPS, but requested an insecure font 'http://fonts.gstatic.com/s/materialicons/v14/2fcrYFNaTjcS6g4U3t-Y5UEw0lE80llgEseQY3FEmqw.woff2'. 

This request has been blocked; the content must be served over HTTPS.

(anonymous function) @ materialize.min.js:6
(anonymous function) @ materialize.min.js:7
(anonymous function) @ materialize.min.js:6
(anonymous function) @ materialize.min.js:6`

I've looked for this file in materialize.min.js but I can't find this URL anywhere. Any idea?
Thanks!

**Comment by kaytrance** [comment]
remove the `http:` part leaving only `//fonts.gstatic.com/s/materialicons/v14/2fcrYFNaTjcS6g4U3t-Y5UEw0lE80llgEseQY3FEmqw.woff2. This way the browser will try to use appropriate connection based on what connection your site have.

**Comment by Dogfalo** [comment]
This is loaded by the google font cdn. Follow @kaytrance 's advice.
