### ISSUE TITLE
I hope there is a way to mark a push pin to stop going over your footer...

### ISSUE THREAD

**Issue by masterpowers** [Dogfalo/materialize#3094]
Pushpin works like a charm but , on the contrary, there should be a way...
to automatically decide to keep the pushpin pinned....
with regards to your footer...
Since a page with low content will have a problem of pushpin going overboard your footer....

**Comment by acburst** [comment]
There is a bottom property that you can set that defines where the pushpinned element stops. With some javascript you can calculate where your footer is from the top and use that as your bottom and it will stop before your footer.
