### ISSUE TITLE
timepicker css problem

### ISSUE THREAD

**Issue by nasr18** [Dogfalo/materialize#3095]
I'm using timepicker in my web application. In that while selecting minutes, it allowing me to select only +5 minutes, like 05, 10, 15, 20 and so on instead of 01, 02, 03, etc. So i managed to edit js file and successfully got what i want. Now I'm getting minutes like 01, 02, 03, etc. But only major problem is its css. See this.............
![screenshot from 2016-04-28 18 29 37](https://cloud.githubusercontent.com/assets/7514936/14886601/365455fc-0d6f-11e6-85a7-62ae01da7964.png)

see the time. its 04:43. but look below, it is pointing towards 45 and not showing the `selected` class.

Looking for help. @douggr

**Comment by Dogfalo** [comment]
Not sure how this relates to Materialize?

**Comment by nasr18** [comment]
I forgot from where i got this timepicker. But anyway i found the code and fixed it. now its working fine.
