### ISSUE TITLE
fixed-action-btn problem

### ISSUE THREAD

**Issue by makkaba** [Dogfalo/materialize#3097]
LINK IS HERE

https://codepen.io/makkaba/pen/qZJjwP

other inputs are blocked by fixed-action-btn

please check it out, thanks.

**Comment by acburst** [comment]
These inline styles `top: 45px; left: 24px;` are causing the problem. The fixed-action-btn is position: fixed and it has the initial properties `right: 23px; bottom: 23px`. By adding top and left you are defining a huge area. If you reset the right and bottom properties it will work.

```
<div class="fixed-action-btn" style="top: 45px; left: 24px; right: auto; bottom: auto;">
```
