### ISSUE TITLE
Open Collapsible programatically 

### ISSUE THREAD

**Issue by flieks** [Dogfalo/materialize#3098]
Hi,

How to do this? I can't find it in the issues.
I'm trying this but it's not working:

```
 var col = $('.collapsible').collapsible({
                    accordion: false
});
if (this.filteractive) {
      var test = $('.collapsible-header');
      col[0].accordionOpen(test);
}
```
`accordionOpen() doesn't exist` but it's there in the [source](https://github.com/Dogfalo/materialize/blob/master/js/collapsible.js#L28)

Thanks

**Comment by Clemzd** [comment]
Simply programmaticaly click on the row you want in the accordion.
For example :`$('#rowTwo').click();`

**Comment by flieks** [comment]
ha, i forgot i can do that :)
thanks Clemzd
