### ISSUE TITLE
How to disable 'a' button?

### ISSUE THREAD

**Issue by Clemzd** [Dogfalo/materialize#3099]
I try to disable a button in materialize without delete the click event. But as you can see on this [jsfiddle](http://jsfiddle.net/abm8wjga/2/), I only get the visual effect. The click event is still launching.

I tried the following:

`$('#btnOne').prop('disabled', true).addClass('disabled');`
Is it a bug? Or am I doing something wrong?

EDIT : it seems there isn't the problem with the tag button

2 possibles workarounds see here : http://stackoverflow.com/questions/36919718/how-to-disable-button-with-materialize

**Comment by Dogfalo** [comment]
This is an HTML question and not a Materialize issue. `a` tags cannot be disabled by properties. instead add `pointer-events: none`.

**Comment by yevgnenll** [comment]
@Dogfalo thx
