### ISSUE TITLE
pushpin functionality

### ISSUE THREAD

**Issue by spirit-infernal** [Dogfalo/materialize#3101]
Using pushpin jquery script causing overwrite all properties for pinable block. This problem was present 8 months ago [http://www.gitterforum.com/discussion/dogfalo-materialize?page=828](url) and stands still.
i.e. if trying to pushpin block with class="right" and then pushpin him - he will float to left, ignore position and width properties, which can be given for a parent block/blocks.

Live example: [http://jsbin.com/kibicaniju](url)

also, requesting to add a extended explanation for functionality for whole framework, or at least for this function. For example, which dimension I must use for specifly, how much pinned block must have margin from top or bottom? 

Screenshots, if use additional division for pushpin. Containing elements still loose their properties, but not loosing alignment

before scroll
![screenshot_1](https://cloud.githubusercontent.com/assets/13832173/14917843/072d18ea-0e32-11e6-8301-5f27a7337d34.jpg)

after scroll

![screenshot_2](https://cloud.githubusercontent.com/assets/13832173/14917845/0d425ae2-0e32-11e6-9ca0-b3722aa38db1.jpg)

and there is no idea, how to specify on which block pushpin must unpin. Is there another situation, when neccesary to use third-party framework for correct work this?

**Comment by acburst** [comment]
Our pushpin plugin changes the positioning to fixed. Usually if things aren't styled strictly enough, this change in positioning will cause your element to look different.

**Comment by spirit-infernal** [comment]
okay, thanks

**Comment by spirit-infernal** [comment]
As I see, problem still not solved. Pushpin function acts same after few updates of Materialize. So problem stands still - even block has pinned class - he removes from DOM stream and has it's own place, all correct, according to current html and css specs. But what I tried to say before and repeat now - is that probably you can include into script part of Materialize little fix, or even overwrite all function, for queueing block width (as I remember materialize jquery part acts after DOM loads, so all elements exactly will have their properties like width and height, so my suggestion is possible to do) and replacing it for pinned block, when he have .pinned class.
Please, see at codepen [here ](http://codepen.io/spirit-infernal/full/ozVYYB/) at right lime block and you can understand what I mean. I used script from source code of your documentation, slightly edited for demo and work. 
and look [here](http://codepen.io/spirit-infernal/full/EgrNRg/), where I commented addition for fixing this issue. Probably you have better realization for migitating this problem in future. 
Best regards, Spirit.

**Comment by kmmbvnr** [comment]
>> include into script part of Materialize little fix, or even overwrite all function, for queueing block width

That's exactly how `datatables.fixedHeader` works. It reads and clones width() for fixed element.

There is `autoWidth: false` option exists to disable this behaviour.

https://datatables.net/extensions/fixedheader/

**Comment by spirit-infernal** [comment]
strange, but without fix - it won't work. And with CSS only reach this effect impossible.

**Comment by kmmbvnr** [comment]
@spirit-infernal I refer to the different library that implements the fixed element functionality in the same way as you suggest.

I also think, it's a good idea to add the same into MaterializeCSS

**Comment by spirit-infernal** [comment]
ahh, sorry, didn't checked sources of site on your link)
So yes, I think it's easy to fix. Strange, that they aren't done this already

**Comment by Edd-G** [comment]
This issue not solved.
https://github.com/Dogfalo/materialize/issues/4169
Why close this if problem persists?

See problem in action whit pushpin plugin:
https://jsfiddle.net/EddG/ve06586j/12/
How to resolve problem with pinned block?
If has class "pinned" break width.
