### ISSUE TITLE
Material Design Icons

### ISSUE THREAD

**Issue by n1k1c4** [Dogfalo/materialize#3103]
Arrrgh… T_T

I spent on the search for solutions 3 hours of your life!

Your font icons are not working.

I had to keep the font of the icons locally, and I finished writing styles and took the font from your repository. But nothing worked. Until I took the original font files from the Google repository.

**Comment by Dogfalo** [comment]
The font documentation says this at the top of the page.

On Friday, April 29, 2016, Nikita <notifications@github.com> wrote:

> Arrrgh… T_T
>
> I spent on the search for solutions 3 hours of your life!
>
> Your font icons are not working.
>
> I had to keep the font of the icons locally, and I finished writing styles
> and took the font from your repository. But nothing worked. Until I took
> the original font files from the Google repository.
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/Dogfalo/materialize/issues/3103>
>


-- 
Doggy sends his greetings from Mars.
