### ISSUE TITLE
Footer won't go down

### ISSUE THREAD

**Issue by AngelMunoz** [Dogfalo/materialize#3105]
Hello, I've been trying to figure out why my footer won't go down

https://codepen.io/tunaxor/pen/wGYLLO

is there any particular reason?
I'm using the header, main, footer structure as suggested in the footer's page on the materialize website

however this only happens to me on chrome and internet explorer
not on edge (I don't have firefox installed)
![laugh](https://cloud.githubusercontent.com/assets/8684875/14933965/f7ca428e-0e5d-11e6-8e5c-25295351923d.JPG)

**Comment by acburst** [comment]
You didn't add the CSS from here: http://materializecss.com/footer.html#sticky-footer
