### ISSUE TITLE
Overflow-x appearing even though there is room for the full tab content.

### ISSUE THREAD

**Issue by robertofabrizi** [Dogfalo/materialize#3107]
As the title says, I'd like to know why the overflow-x bar is appearing, even if there is perfectly enough space for all the content. The bar only floats for like 2 pixels...

https://dl.dropboxusercontent.com/u/66751019/Cattura.JPG

How can this be prevented? I need the overflow-x for when it's actually needed (mobile devices for example), so I cant override it with css.

Thank you,
Roberto

**Comment by acburst** [comment]
Can you post your code? I would like to take a look

**Comment by robertofabrizi** [comment]
Here is the fiddle with printscreen:

http://jsfiddle.net/ak0on6kL/178/

https://dl.dropboxusercontent.com/u/66751019/Cattura.PNG

Some caveats:

- It only appears at some resolutions. On my laptop's low res it doesn't happen at the moment, on the pc that I used for the printscreen, which is full hd, i managed to trigger it
- It disappears if I open for example the js console of Chrome
- It doesn't happen every single time, try to enlarge the output as much as possible and then hit run, that is what I did to make it appear on that fiddle.

Thank you for taking a look at this!!

Best regards,
Roberto

**Comment by robertofabrizi** [comment]
@acburst Dear Alan, did you manage to check my example? Cheers!!

**Comment by acburst** [comment]
Have you tried using the latest version of master? I believe I fixed something similar to this but it is not in the current release yet.

**Comment by fega** [comment]
Closed due inactivity, feel free to reopen it if it is still necessary.
