### ISSUE TITLE
JS characterCounter() function uses incorrect attribute

### ISSUE THREAD

**Issue by Nukeface** [Dogfalo/materialize#3108]
`characterCounter()` function searches `<input>` elements for `length` attribute. However, though it technically 'could' be added to these elements, the [HTML5 docs](https://www.w3.org/TR/html-markup/input.text.html#input.text) state the usage of `maxlength` attribute instead. Could be solved in either or both manners of: set function to default search for `maxlength` or add option to pass function attribute name to search for (e.g. `data-length`)

**Comment by Dogfalo** [comment]
This is done to leave the choice for the developer to enforce a hard limit during typing or to allow typing of the limit while warning the user.
