### ISSUE TITLE
pagination misalignment

### ISSUE THREAD

**Issue by runofthemill** [Dogfalo/materialize#3109]
on OSX 10.11.4, Chrome 50.0.2661.86

The class `waves-effect` adds `vertical-align: middle` to the list element, but `active` and `disabled` don't have an explicit `vertical-align` value. 

Active item appears to be top aligned:
![screen shot 2016-04-30 at 11 01 13 pm](https://cloud.githubusercontent.com/assets/8418440/14940408/85401042-0f28-11e6-8379-09b9b83ee97b.png)

Disabled item appears to be a pixel or two higher than non-disabled:
![screen shot 2016-04-30 at 11 01 00 pm](https://cloud.githubusercontent.com/assets/8418440/14940410/9f90a36c-0f28-11e6-894a-ca2d33150224.png)

Giving list elements `vertical-align: middle` or `vertical-align: -webkit-baseline-middle` seems to fix:
![screen shot 2016-04-30 at 11 03 11 pm](https://cloud.githubusercontent.com/assets/8418440/14940415/f443292a-0f28-11e6-87e3-d55260072600.png)

Cheers! :)

**Comment by acburst** [comment]
This has been fixed on master and will be public in the next release. In the meantime you can try our latest version and see if that helps
