### ISSUE TITLE
How to make responsive image on slider?

### ISSUE THREAD

**Issue by donnygunawan93** [Dogfalo/materialize#3110]
http://materializecss.com/media.html#slider

thats image not responsive

**Comment by Dogfalo** [comment]
I don't see why it is not responsive to you. What would the image look like if it were responsive?

**Comment by donnygunawan93** [comment]
http://materializecss.com/media.html#slider height of image not responsive

how to make slider like this http://materializecss.com/media.html#carousel, 2nd example is responsive

**Comment by gdoron** [comment]
@Dogfalo @donnygunawan93 I'm not sure what's not responsive in the slider example.
But the carousel is indeed **not** responsive for images.
Easily fixed by instead of having `<img>` inside of the `.carousel-item`, adding `.carousel-item` background-image.

Is this what you meant @donnygunawan93 ?

**Comment by mckenzieja** [comment]
I have the same issue except when the view port changes, the indicators are not maintaining their position but rather being "pushed" out below into white space.

**Comment by fega** [comment]
@mccraveiro Can you send us a codepen to reproduce the issue? please

**Comment by fega** [comment]
Closed due inactivity, feel free to reopen it if it is still necessary.

**Comment by vinothinin** [comment]
I faced that same problem. height is not responsive. What i have to do to set responsive height in materialize css??

**Comment by leonadito** [comment]
I would also like to find out

**Comment by leonadito** [comment]
I inserted `<a class="carousel-item responsive-img col s12 m7 l4" href="#one!">`
works, but you have to refresh the page. how to solve this without refreshing

**Comment by YosiLeibman** [comment]
hi... someone alredy get the answer?

**Comment by harri00413** [comment]
As there is still no workable solution here I have to assume it is not possible with the Materialize slider.
