### ISSUE TITLE
Bad navbar search rendering on chrome

### ISSUE THREAD

**Issue by rhuanbarreto** [Dogfalo/materialize#3117]
On Chrome 50 the navbar search is not rendering correctly.

http://materializecss.com/navbar.html#search-docs

On firefox it's ok.

**Comment by acburst** [comment]
This issue was fixed and merged c129dc1.

It will be public in the next release or you could download our latest version

**Comment by ev1stensberg** [comment]
Is the CDN also updated to latest, or where could I find that?

**Comment by ev1stensberg** [comment]
Examples on your website is broken & working with this from CDN causes the exact same thing.

**Comment by lordplagus02** [comment]
+1 this, something has suddenly caused my navbars to render strangely on chrome.

**Comment by Dogfalo** [comment]
Website reflects the current version not the latest (mater-branch) version. You can download the latest build off github in `bin/` if you want.

**Comment by ev1stensberg** [comment]
Tried to fix this in #3125 ( using div instead )

**Comment by acburst** [comment]
As I said the changes will be public when we release next. To get the latest version you will have to download the files yourself from github
