### ISSUE TITLE
jsdelivr

### ISSUE THREAD

**Issue by pikilon** [Dogfalo/materialize#3119]
As told on twitter I created a new Issue to address this request.

jsdelivr is a huge free CDN and you can find there from jquery, react, angular, bootstrap... to almost anything.

The best thing is grouping js/css libraries in one call, like this
https://cdn.jsdelivr.net/g/jquery@2.2.3,requirejs@2.1.22,require-css@0.1.8,react@15.0.1,hammerjs@2.0.8

(jquery, requirejs, react and hammerjs...)

I can't include materializecss because is not there (almos everything but materializecss)

Thanks

**Comment by Dogfalo** [comment]
It has been added already. May have to manually backfill some older versions though
https://github.com/jsdelivr/jsdelivr/tree/master/files/materialize
