### ISSUE TITLE
Issue when jquery ui is included with materialize

### ISSUE THREAD

**Issue by merlano17** [Dogfalo/materialize#3120]
The tool-tips doesn't show up.

Please have a look into it asap

**Comment by acburst** [comment]
Please put more effort into describing your issue. Have you tried recreating this issue with a codepen or a  jsfiddle where you can add these external libraries?

**Comment by Dogfalo** [comment]
Probably a naming conflict, you can change the name of the function to avoid this.

**Comment by merlano17** [comment]
@acburst Am working on a project in Yii2, with materialize and recently i added jquery ui asset for sortable functionality. It works fine in development environment, if i run the project in production environment then the tooltips are not at all generated in the view files (even if i call the function from console it doesn't initialize the tooltips)

Difference between dev and prod environment is that, in prod environment the assets are compressed into one js and css file using http://www.yiiframework.com/doc-2.0/guide-structure-assets.html 

So i don't think i can replicate using codepen or a jsfiddle

**Comment by Dogfalo** [comment]
Try resolving the naming conflict as I said. We also don't provide support nor do we expect Materialize to work perfectly in conjunction with other UI libraries
