### ISSUE TITLE
Datepicker closeOnSelect Workaround Breaks Date Formatting

### ISSUE THREAD

**Issue by bliles** [Dogfalo/materialize#3122]
There is a workaround posted in #870 for how to deal with the lack of built in support for close on select. However, this workaround breaks the built in date formatting. In fact it appears that adding an onSet function at all even if it does nothing, breaks the date formatting.

It would seem that it is a common enough desire for the ability to have the picker close after select that this should be natively supported as a configurable option.

**Comment by ben-sykes** [comment]
Could you explain your issue a bit more? 

There a few options that I believe you can pass in (found on http://amsul.ca/pickadate.js/date/ that this control is built from) that may solve your problem, but I could use a bit more information about your issue.

As always, if you could create a fiddle or something so I could work with your problem first hand, that would also be helpful.

**Comment by hustcer** [comment]
close on select seems not work
