### ISSUE TITLE
disabled property on buttons

### ISSUE THREAD

**Issue by INGCRENGIFO** [Dogfalo/materialize#3126]
Hi developers, yesterday upgrade to the latest version of MaterializeCSS. But now I see that the property does not work in those disabled buttons, not if the update change something and not know, attached images of before and after.
![1](https://cloud.githubusercontent.com/assets/12200313/14997108/a55354b8-1142-11e6-8858-b7b643d987ba.png)
![2](https://cloud.githubusercontent.com/assets/12200313/14997109/a56e2284-1142-11e6-8178-3a0910c9f317.png)

**Comment by merlano17** [comment]
I also faced the same, if we click the disabled button, it does the click action (which it should not do)

For the time being am using jquery disabled property

**Comment by INGCRENGIFO** [comment]
@merlano17 how do you do it?

**Comment by meteormanaged** [comment]
@INGCRENGIFO you can use some simple jquery in the meantime to stop this from happening.

something like this in doc ready:

    $('a.disabled').click(() => event.preventDefault()));

**Comment by merlano17** [comment]
@INGCRENGIFO 
$(element).prop('disabled','disabled');

And to enable it use $(element).prop('disabled',false);

**Comment by wemyss** [comment]
<img width="630" alt="screen shot 2016-05-13 at 9 17 14 pm" src="https://cloud.githubusercontent.com/assets/8426915/15246456/5c9140d0-1950-11e6-8766-b26db17c21b6.png">
Not sure if this has to do with the issue, but here in the sass source files you can see that pointer-events still occur on the buttons themselves (only the children get disabled with the `*` selector). This causes the issue of a button being disabled yet the link or onclick event still activating onclick

As for the disabled styles I'm not sure as to why that doesnt work..

**Comment by acburst** [comment]
Not sure if chrome recently changed anything but technically speaking, by standards the disabled property should only be used on input buttons. But because it used to work, i've added it as a supported attribute in c34a92f

**Comment by INGCRENGIFO** [comment]
@acburst Hello, how you could apply the change that you went? materialize remains in the version 0.97.6

**Comment by acburst** [comment]
You can either download the latest code from github or wait until we release next

**Comment by INGCRENGIFO** [comment]
let me see if I understand, if I download what is on the main page of git, that's the version you modified your ?? which has the bug fixed?
![git](https://cloud.githubusercontent.com/assets/12200313/15359307/507c6b40-1cce-11e6-8877-a9607838cebb.png)

**Comment by INGCRENGIFO** [comment]
@acburst and knew how to download and update, everything was solved. Thank you so much!
