### ISSUE TITLE
Materialize.js effects don't work using RequireJS

### ISSUE THREAD

**Issue by Urahara** [Dogfalo/materialize#3128]
Hi!

When i add script manually in `head` or end of `body` all the effects works, but when i use requirejs to load effects don't work (waves for example). Is there any way I can call the function to start the script manually? I tried using headjs but the result is the same.

Snippet of manually add scripts:
https://jsfiddle.net/fn4btn52/show/

My code to load .js using require:

```
;(function( undefined ) {
  'use strict';
  
  
requirejs.config({
  paths: {
    'jquery': 'jquery.min',
    'materialize': 'materialize.min'
  },
  shim: {
    'materialize': {
      deps: ['jquery']
    }
  }
});  
  
  require(['jquery', 'materialize'], function() {
    console.log('loaded');
  });
})();
```

HTML:
```
<!DOCTYPE html>
<html>
<head>
      <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/0.97.6/css/materialize.css" media="screen" type="text/css">
      <script data-main="js/boot" src="https://cdnjs.cloudflare.com/ajax/libs/require.js/2.2.0/require.min.js"></script>
      
</head>
<body>
    <a class="waves-effect waves-light btn">Botão</a>
</body>
</html>
```

**Comment by tiago580** [comment]
Vc ta usando algum framework pra templates?

**Comment by Urahara** [comment]
@tiago580 Sim, estou usando Handlebars, acabei deixando o .js do materialize no final da página.

**Comment by tiago580** [comment]
Consegui utilizando a versão do @ccloli [https://github.com/ccloli/materialize/tree/AMD-fix/dist/js](url). Nem precisou adicionar outras dependências com o o Hammer.js

**Comment by Urahara** [comment]
@tiago580  Obrigado vou testar depois, eu atualmente estou o headjs pra carregar os javascripts.
