### ISSUE TITLE
LESS version

### ISSUE THREAD

**Issue by volnei** [Dogfalo/materialize#313]
Would be great if you had a LESS version

**Comment by AWMooreCO** [comment]
I concur. This would be awesome if there was LESS support

**Comment by globeFrEak** [comment]
:+1:

**Comment by volnei** [comment]
Hey guys!!! =)

Please, this is very relevant... take look at this.
https://www.npmjs.com/package/grunt-refactor

**Comment by ygor27** [comment]
+1, Less is really easer to use maintain and compile.

**Comment by marciomunhoz** [comment]
+1  My team is eager to start using Materialize, but we are waiting for LESS version.

**Comment by faelvasco** [comment]
we need the LESS version, would be great.

**Comment by clouzada81** [comment]
+1... I think it would be really important. LESS is easer to work

**Comment by eliveltonmendes** [comment]
+1 I LESS version would be great. Much easier.

**Comment by JohnJr** [comment]
Support for Less would be awesome!!

**Comment by vsalvalagio** [comment]
+1 LESS

**Comment by BatistaGabriel** [comment]
LESS

**Comment by Pandahisham** [comment]
LESS please

**Comment by hebbet** [comment]
+1

**Comment by svenvandescheur** [comment]
+1

**Comment by Dragsbaek** [comment]
+1

**Comment by roaringbits** [comment]
+1

**Comment by samehkamaleldin** [comment]
+1

**Comment by mc388** [comment]
+1

**Comment by NicolasPio** [comment]
+1

**Comment by roaringbits** [comment]
Might give this a go myself.

**Comment by CurosMJ** [comment]
+1 This would let people who use LESS to import Materialize directly into their code.

**Comment by Teranode** [comment]
please allow less :(  - 99% of my css is less compiled

**Comment by Oguzhanpiskin** [comment]
LESS would be less instead of S(ass)

**Comment by pezioz** [comment]
+1 It would be awesome :)

**Comment by ricardodovalle** [comment]
:+1:

**Comment by superbug** [comment]
+1

**Comment by gnicol-bzh** [comment]
As long as it doesn't replace SASS!
But it would mean more work to keep up to date both LESS and SASS to do the same job.

**Comment by blomdahldaniel** [comment]
+1

**Comment by stivaugoin** [comment]
+1

**Comment by Torrin** [comment]
+1

**Comment by himynameisdave** [comment]
:+1:

**Comment by Sinark** [comment]
+1

**Comment by gpincheiraa** [comment]
LESS please!

**Comment by loenk2x** [comment]
LESS !

**Comment by insideaem** [comment]
+1 LESS

**Comment by lcdss** [comment]
:-1:  for LESS.

**Comment by Nikofoxxx** [comment]
+1

**Comment by beforeadream** [comment]
Who can list compelling reasons why migrate on less?

**Comment by blomdahldaniel** [comment]
Don't you think that there is a big enough crowd that prefer LESS? A lot of
people with Twitter Bootstrap background knows LESS better and I do think
that there is a whole lot of people with that background. With that said,
SASS is getting more and more dominant and even Bootstrap is letting go of
LESS in their Bootstrap 4 so, as of now, i cannot see any reason except
convenience for all the people that prefer LESS, but I don't know in what
approach you have towards your users.


2015-11-17 13:48 GMT+01:00 Valery Lyatevich <notifications@github.com>:

**Comment by Maelstrome26** [comment]
+1

**Comment by mistriel** [comment]
+1 Less

**Comment by bymarcojacinto** [comment]
+1 for Less

**Comment by Levitas** [comment]
+1 still wanted ;)

**Comment by delsanic** [comment]
+1 for Less

**Comment by cayvowcorir** [comment]
+1

**Comment by caesay** [comment]
+1

**Comment by barbiebrega** [comment]
+1

**Comment by eric-burel** [comment]
This would allow Materialize to work with Sails.js (which use Less) by default and would be awesome for fast development

**Comment by Yugzz** [comment]
+1

**Comment by marcingolenia** [comment]
+1

**Comment by niittymaa** [comment]
++ !

**Comment by dpineda64** [comment]
+1

**Comment by markotom** [comment]
+1

**Comment by iaderlorduy** [comment]
+1

**Comment by machiaveli88** [comment]
+1

**Comment by ralphbert** [comment]
+1

**Comment by cderche** [comment]
+1

**Comment by stevecawdery** [comment]
+2 1 for ego

**Comment by kmmbvnr** [comment]
There are so many people left `+1` comment here, that more than enough to develop a fork of MarerializeCSS with LESS, instead of asking core devs :smile:

**Comment by yanickrochon** [comment]
I agree with @kmmbvnr that there are a "big enough crowd that prefer LESS" to do something about it, then someone ought to do something, right? 

Also, that are arguably more reasons to keep SASS only than to have a LESS version, or even both of them. The popularity of something does not necessarily indicate any form of superiority. Because IDE vs SCSI, VHS vs Betamax, Blue-ray vs HD DVD, to name but a few, were popular, and yet not necessarily the best technological choices.

The module is published with a pre-built CSS file that can easily be merged with other CSS files, generated or not. I don't see a good reason to fiddle with the SASS anyway; extend the styles with your own custom selectors and styles!

**Comment by Dogfalo** [comment]
This isn't something that we think would be a good use of our time, so we won't be maintaining a LESS version. If someone does make their own however, post it here to help people out 👍

**Comment by himynameisdave** [comment]
![single tear](http://static.deathandtaxesmag.com/uploads/2012/09/superhero.gif)

totally understandable though, this lib wasn't built on Less.

**Comment by NyushaDEV** [comment]
+1 Less!
