### ISSUE TITLE
Conflict between Data picker and Google Drive File Picker

### ISSUE THREAD

**Issue by phbernard** [Dogfalo/materialize#3130]
The [Date picker](http://materializecss.com/forms.html#date-picker) conflicts with [Google Drive File Picker](https://developers.google.com/picker/docs/).

When triggering Google's Picker:
- The authorization popup (to grant access to the web site) works as expected.
- The overlay is applied to the page as expected.
- The picker dialog itself is nearly invisible:

![image](https://cloud.githubusercontent.com/assets/423852/15072948/cd9d0b0c-1396-11e6-8d96-d4ab36a28cd1.png)

This is because the `picker` class is declared in both environments.

To reproduce the issue:
- [Follow the Hello World example](https://developers.google.com/picker/docs/#hiworld). Note: it requires an API key. Not a big deal, but you need your own Google account, etc.
- Access the sample page through a local web server, authenticate and authorize the sample app. The picker appears as expected.
- In the sample page, insert the following line just after `head` opening: `<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/0.97.6/css/materialize.min.css" type="text/css">
  `
- Access the page again: this time, the picker doesn't appear.

**Comment by obmelvin** [comment]
I have just run into this issue myself. Did you find a semi elegant way around it?

**Comment by phbernard** [comment]
I excluded the date picker from my personal Materialize build. For example, in a Gulp file, add `.pipe(stripLine(/\/date_picker\//))` (from package gulp-strip-line) to the Materialize SASS build task to exclude the related lines in `materialize.scss`.

So this is just a workaround: you still can't make Google Drive and the date picker work together.

**Comment by obmelvin** [comment]
That's unfortunate to hear, but consistent with my efforts. I tried modifying the CSS file to change class names, but apparently didn't change enough because they were still conflicting.

Thank you for your reply though!
