### ISSUE TITLE
Datepicker doesn't appear fullscreen when inside card-reveal

### ISSUE THREAD

**Issue by muktisuperior** [Dogfalo/materialize#3131]
I'd tried to put datepicker inside `.card-reveal` but when i clicked it, it shows only inside card-reveal and not appear in full screen.

you can look in:
http://codepen.io/muktisuperior/pen/vGbYmG

Thanks.

**Comment by d62remi** [comment]
Used container option with pickadate 
http://amsul.ca/pickadate.js/date/#container

;-)

**Comment by muktisuperior** [comment]
Waa thank you it's work
