### ISSUE TITLE
Integration with other icon libraries?

### ISSUE THREAD

**Issue by jacobq** [Dogfalo/materialize#3132]
I would like to use the community-added material design icons (from [here](https://materialdesignicons.com/)). Could you help me understand the process of doing this? Instead of linking-in Google's CSS can I just drop in one from that project? What parts of your library might I need to adjust? (Sorry if these are dumb questions -- I do not know much about icons yet). Do I need to support using the icons via <i> element with icon name (vs. using a class name or some other method)?

**Comment by Dogfalo** [comment]
You shouldn't need to adjust anything. we haven't added anything that limits functionality with other icon fonts!

**Comment by jacobq** [comment]
OK...It seems like in your examples (like [this one](http://materializecss.com/icons.html)) you use code like `<i class="material-icons">name</i>` but if I use the other I think I need to do something like `<i class="mdi mdi-name"></i>`. Are you saying that Materialize itself does not contain any code depending on this format? (i.e. the examples just show one possible choice of icon integration)

**Comment by Dogfalo** [comment]
yes, in documentation we use MDI because this is a material design framework
