### ISSUE TITLE
Mobile Nav bar broken on 0.97.6

### ISSUE THREAD

**Issue by jnguyen7410** [Dogfalo/materialize#3137]
Expected: Nav bar should pull out and hamburger icon should be shown on mobile
Actual: In 0.97.6, the nav bar is completely broken and the hamburger icon doesn't show

Was testing out mobile input on website when I realized I couldn't use it at all. Was testing this on live version of site. In 0.97.5, this was working fine. Switching to 0.97.6 broke this.

Website not working [here](http://nguyeningcode.com/test/test.html).
Website working [here](http://nguyeningcode.com/).

With layout change, this doesn't completely break my site, but on live version, it will. I tested with the live version as well.

**Comment by jnguyen7410** [comment]
![ezgif com-resize](https://cloud.githubusercontent.com/assets/855279/15109431/32e8cdfc-1590-11e6-9f06-1057f143285d.gif)

**Comment by fega** [comment]
Please provide a way to reproduce it. like a [codepen](https://codepen.io/fega/pen/BWeZaG) or  a snippet, your website is not working

Closed due inactivity, feel free to reopen it if it is still necessary.
