### ISSUE TITLE
Center-align doesn't work on H element

### ISSUE THREAD

**Issue by Marinc** [Dogfalo/materialize#3138]
Hello ! 
I've got this problem with H element and parallax effect 
i want the element to be in the center of the parallax (align and valign), but the center-align class doesn't work. 

`<div class="parallax-container valign-wrapper center-align">
      <div class="parallax"><img src="images/parallax1.jpg"></div>
      <h2 class="center-align valign white-text center-align">TEXT HERE</h2>
    </div>`

Thank you !

**Comment by chi-bd** [comment]
Try this.
```css
h2.center-align{
    margin: 0 auto;
}
```
