### ISSUE TITLE
Cannot find module './picker.js'

### ISSUE THREAD

**Issue by denzBrade** [Dogfalo/materialize#3139]
Discovered this issue then researched it. The OP can be found here by numerous other people:
https://github.com/Dogfalo/materialize/issues/1422

This is a **big issue** for those of us trying to either require or import the NPM version.
Please could this be addressed.

To clarify when running the project the picker.js file is missing from the '/materialize-css/bin' folder.

**Comment by criticalmaas** [comment]
I was able to bypass this by simply copying picker.js into the bin directory using npm postinstall command. **_It's a temporary solution only._**

```"postinstall": "cp node_modules/materialize-css/js/date_picker/picker.js www/lib"```

**Comment by denz-brade-2015** [comment]
@criticalmaas nice one & thanks for the trick, could prove useful in the interim. 
Still I hope they can address this issue its an extremely popular issue which would deter people from using this nice framework.

**Comment by actuallymentor** [comment]
Still an issue. I applied a temporary fix that still allows for require('materialize-css') in a browserify/gulp setting.

```  "postinstall": "cp node_modules/materialize-css/js/date_picker/picker.js node_modules/materialize-css/bin" ```

**Comment by aeksco** [comment]
Also seeing this issue with Browserify.

**Comment by nmors** [comment]
i'm getting this issue with browserify

**Comment by fernandogmar** [comment]
I am still getting this issue, 2017!! :sweat_smile: 

Thanks!

**Comment by fernandogmar** [comment]
Ok, I am using jspm to install it so this is what I finally did:

```
jspm install materialize-css=npm:materialize-css -o '{format: "amd", "main": "bin/materialize.js", shim: { "bin/materialize": ["jquery"] }}'
```

just in case someone got the same problem ;)

**Comment by Jujunol** [comment]
Being such a big issue I'm surprised that this isn't patched yet.

**Comment by denzBrade** [comment]
Seeing all these recent messages :( 
Sorry guys the point of my post was for the issue to be rectified asap, 
hope you all have a temporary work around in the meantime.

**Comment by NitroBAY** [comment]
@Dogfalo why don't you fix that ?

**Comment by christopher-s** [comment]
This is a pretty severe little bug. Can we get it in the next release right away?

**Comment by madsem** [comment]
ridiculous that since and related issue are open since 2015. Jeez

**Comment by Flubbex** [comment]
Having this bug too right now, looking for a workaround. Disappointing too because I had some great browser-only testing experiences with materialize and I was kinda looking forward to implementing it :/ 

Oh.. this issue is a year old..

**Comment by tomscholz** [comment]
I published a npm package with the latest changes under the name `materialize-css-temp`. Would you mind to test, if this fixes your problem?

**Comment by tomscholz** [comment]
Related https://github.com/Dogfalo/materialize/pull/4158

**Comment by Dogfalo** [comment]
Not sure if the problem will be solved for everyone, but just released a new version that should fix this issue. Give it a try and let me know if the issue persists. 

My deepest apologies for letting this issue go unfettered for so long.

**Comment by Dogfalo** [comment]
Closing this until I receive news otherwise
