### ISSUE TITLE
Dropdown doesn't work in  angular routes

### ISSUE THREAD

**Issue by sexobert** [Dogfalo/materialize#3143]
Dropdown  button  does'nt  work  in  anugular  routes. 
Like  you make a single page ap with  angular  client routing,  and  try to add  a  dropdown  button  in  one  of  your  routes pages. You'll  notices  that,  the  button  will  appear, but nothing after  click.

**Comment by 07carvalho** [comment]
I'm with the same issue. did you know how fix it?

**Comment by sexobert** [comment]
Sorry, I couldn’t, I was at there beginning of my project, so I choose Angular Material v1(with is no more supported too).

**Comment by 07carvalho** [comment]
I get a stackoverflow tip to always initialize the dropdown in every page. not cool, but worked

$('.dropdown-button').dropdown({
    alignment: 'left', 
    inDuration: 200,
    outDuration: 150,
    constrain_width: true,
    hover: false, 
    gutter: 1
});

**Comment by sexobert** [comment]
Copy that, thanks for sharing.

Axel-Christian Guéi

On Nov 20, 2016, at 11:17 AM, Felipe Carvalho <notifications@github.com<mailto:notifications@github.com>> wrote:


I get a stackoverflow tip to always initialize the dropdown in every page. not cool, but worked

$('.dropdown-button').dropdown({
alignment: 'left',
inDuration: 200,
outDuration: 150,
constrain_width: true,
hover: false,
gutter: 1
});

-
