### ISSUE TITLE
Feature request: slider could have a method that returns the current index of the image being shown.

### ISSUE THREAD

**Issue by keyscores** [Dogfalo/materialize#3145]
Is there any undocumented way to get the current index of the slider image?

Sometimes it's necessary to know what index the slider is at, so that other functions or views on the page can be triggered. 

Thanks in advance

**Comment by acburst** [comment]
Currently there is no javascript way to get the current index. But in the meantime you can get the active slide. The li tag will have an active class when it is the current slide

**Comment by keyscores** [comment]
I don't recall how it's done today. But could you somehow set the id attribute to the index on init ?  Another attribute?

**Comment by acburst** [comment]
What is wrong with using the active class?

**Comment by keyscores** [comment]
Because I actually  need to get an ID which is not present there currently. I'm not using it for images, I'm using the slider to show document text. And I have an array of object to do this, and no way to know what index it is at.

**Comment by acburst** [comment]
You can get the index from the active class with jQuery though. 

https://api.jquery.com/index/

**Comment by fega** [comment]
Moved to the feature request board, feel free to ask if you need further information.

**Comment by tomscholz** [comment]
@fega I think this issue has been resolved (https://github.com/Dogfalo/materialize/issues/3145#issuecomment-219609122)
