### ISSUE TITLE
Input search is not working

### ISSUE THREAD

**Issue by andre-mendes** [Dogfalo/materialize#3157]
the search field is not working

http://materializecss.com/
in the sidebar :)

**Comment by iNilo** [comment]
Need more info on this, what browser are you using ? do you have any script blockers running ?

Seems to be fine on latest stable FF & Chrome

**Comment by stevanusp** [comment]
i have a same problem here. and i'm using FF

**Comment by fega** [comment]
Please provide a way to reproduce it. like a [codepen](https://codepen.io/fega/pen/BWeZaG)
