### ISSUE TITLE
scrollFire: Provide element that triggerd callback as paramter

### ISSUE THREAD

**Issue by AnderssonPeter** [Dogfalo/materialize#3158]
It would be nice if the element that triggerd the callback would be passed into the callback function.

Then we could write something like 
```
var options = [{
    selector: '.slideIn', offset: 200, callback: function (element) {
        $(element).slideIn();
    }
}];
Materialize.scrollFire(options);
```

**Comment by acburst** [comment]
This has been added in e3b8c7f8828803b068990dfe1195620a64f6e2ed. It will be public in the next release. You can also download the latest and use it there
