### ISSUE TITLE
Materializecss select problem

### ISSUE THREAD

**Issue by Serkis** [Dogfalo/materialize#3166]
I am using **Smoothstate.js** on [this web page](http://ders34.com/tpl_cat_ozelders.html). 
"Materializecss Select" does not work. Make the transition to other pages when I came back again.

**Comment by acburst** [comment]
Please explain your problem more. I can't see the problem on that page

**Comment by Serkis** [comment]
Thank you. Please watch the video
https://drive.google.com/file/d/0B2gIpmEHCnhoWUg4Q2daSlVJdVU/view?usp=sharing

**Comment by acburst** [comment]
I have no idea what your code is doing. Do you have any code examples? But it seems like you just need to reinitialize your selects at some point.

**Comment by Serkis** [comment]
[The method of there](https://github.com/miguel-perez/smoothState.js#faq). But I could not.

**Comment by Serkis** [comment]
I solved the problem. Thank you very much.
