### ISSUE TITLE
Using icons for navbar links - Wrong height in <li> tag.

### ISSUE THREAD

**Issue by guillecro** [Dogfalo/materialize#3169]
So I have this navbar.

```
<nav>
    <div class="container">
        <div class="nav-wrapper">
            <a href="{{ site.baseurl }}/" class="brand-logo">
                <img src="/img/small-logo.png" class="responsive-img" alt="">
            </a>
            <ul id="nav-mobile" class="right hide-on-med-and-down">
                <li><a href="sass.html"><i class="material-icons">home</i></a></li>
                <li><a href="badges.html">Docs</a></li>
                <li><a href="badges.html">Blog</a></li>
                <li><a href="badges.html">About</a></li>
                <li><a class="waves-effect waves-light btn">Probar</a></li>
            </ul>
        </div>
    </div>
</nav>
```

Home button will be a Home icon, `<i class="material-icons">home</i>`
Problem is that somehow the `<li>` of the home link breaks the navbar, by adding more height to the `<ul>`. If you remove the `<i>` then the height is fixed. It happens with all the icons packs: fontawesome, material-design-icons, etc.

Here is a screenshot.

![screenshot from 2016-05-16 18-37-26](https://cloud.githubusercontent.com/assets/8771166/15305095/6d41df90-1b97-11e6-8608-935e4e220ce7.png)

**Comment by acburst** [comment]
Fixed in 607951e
