### ISSUE TITLE
Blinking cursor on ipad for dropdowns. How to fix?

### ISSUE THREAD

**Issue by vitaly-ndaw** [Dogfalo/materialize#3171]
Hi

There is a bug on ipad 
Blinking cursor on ipad for dropdowns. How to fix?

thanks

**Comment by jensbroecher** [comment]
I have the same problem on iPhone. I tried a lot of hacks but nothing worked for me. On Android and Web it's fine.

**Comment by PushkaCom** [comment]
I am having this issue - sometimes the dropdown comes up fine, and sometimes when clicking the select-box the cursor-bar will be active next to the selection/option text and not open the menu.

2017-03 version 
IOS version - 10.2.1

![img_0001](https://cloud.githubusercontent.com/assets/985223/24179727/f9879fec-0f04-11e7-9686-60da6bcf1875.PNG)

**Comment by tomscholz** [comment]
These issues are all duplicates:
https://github.com/Dogfalo/materialize/issues/4413
https://github.com/Dogfalo/materialize/issues/4315
https://github.com/Dogfalo/materialize/issues/4306
https://github.com/Dogfalo/materialize/issues/3715
https://github.com/Dogfalo/materialize/issues/3171
https://github.com/Dogfalo/materialize/issues/630

For the future discussion, please use this issue instead.
https://github.com/Dogfalo/materialize/issues/3790
