### ISSUE TITLE
Problem/Question with collapsible

### ISSUE THREAD

**Issue by breferrari** [Dogfalo/materialize#3173]
Is there a way to disable the collapsible animation so it appears opened and static when the page loads?
I'm using it with Angular on a menu, and everytime the menu view gets reloaded (when I change a page, for example), the menu gets reloaded and the collapsible/accordion animation occurs.

**Comment by acupajoe** [comment]
@breferrari : As per the documentation on the website: Adding the active class to the div(s) you want to have pre-opened will disable the animation. 

`<div class="collapsible-header active"><i class="mdi-maps-place"></i>Second</div>`

**Comment by camilawaz** [comment]
I try to add the class active using jQuery and have no success. 
@acupajoe you know if its possible to do that? 

The idea is: after click on a button, all of my collapsible tabs receive the class active and shows open to the user. 

Thank you.
