### ISSUE TITLE
Dropdown is not opened in a modal window

### ISSUE THREAD

**Issue by nitoloz** [Dogfalo/materialize#3175]
Hi guys!

I am using Materialize with Angular and have created a service  that wraps the work with modal widows, so they wont be always hanging in the DOM.(I actually use code from here: https://gist.github.com/viniciusmelquiades/3654a3520ecda1d198f4)
So when the modal is closed and modal controller is not used anymore I call 
`
modal.closeModal();  
modal.remove();
`
But when I wait 5 sec(mentioned in timeout) and open modal window for the second time all the elements in modal window work fine, but the dropdown initialization fails and `<ul>` element is not added to the DOM.

Do you know what it may be? I am very serious about clearing the DOM, so I would be happy to hear some advice to improve my solution. 

Thanks!
Andrey

**Comment by acupajoe** [comment]
@nitoloz are you reinitializing the dropdown after you've added the content to the modal?
