### ISSUE TITLE
Firefox Mobile URL Bar Causing SideNav Height Issues on Scroll

### ISSUE THREAD

**Issue by btply** [Dogfalo/materialize#3176]
In Firefox mobile, when a SideNav is opened on a page that has not been scrolled, the URL bar takes up a portion of the top of the page. 

![Unscrolled](https://cloud.githubusercontent.com/assets/2947232/15361321/d9545402-1d08-11e6-84c0-2f077fab63e9.png)

When the Nav is then scrolled, the URL bar disappearing with the scroll causes a gap at the bottom of the page equal to the size of the URL bar.

![Scrolled](https://cloud.githubusercontent.com/assets/2947232/15361320/d9333c90-1d08-11e6-96f8-2ee70dec7532.png)

This makes for a bad user experience.

**Comment by fega** [comment]
This is still a problem? can you check it please?
Closed due inactivity, feel free to reopen it if it is still necessary.
