### ISSUE TITLE
Selection windows shown under card

### ISSUE THREAD

**Issue by tceydeliler** [Dogfalo/materialize#3177]
Why happen this?
![screenshot-area-2016-05-18-171021](https://cloud.githubusercontent.com/assets/10337838/15362549/38eae88a-1d1e-11e6-8a5a-5c53969e8fcb.png)

**Comment by acburst** [comment]
Do you have a code example?

**Comment by tceydeliler** [comment]
`<!DOCTYPE html>
<html>
	<head>
		<meta charset="UTF-8">
		<meta name="viewport" content="width=device-width, initial-scale=1.0">
		<link type="text/css" rel="stylesheet" href="css/prism.css"  media="screen,projection"/>
		<link type="text/css" rel="stylesheet" href="css/font-awesome.min.css"  media="screen,projection"/>
		<link type="text/css" rel="stylesheet" href="css/materialize.min.css"  media="screen,projection"/>
		<link type="text/css" rel="stylesheet" href="font/material-design-icons/mdi.css"  media="screen,projection"/>
		
		<style type="text/css">
		.row {
    		font-size:0px;
   		margin-bottom: 0px
		}
		.row .col {
		    float:none !important;
		    display:inline-block;
		    font-size:12px;;
		    vertical-align:middle;
		}
		.row .col.s2 {
		    padding-top: 20px;
		    padding-bottom: 5px;
		}		    
		</style>
		
	</head>
	<body>
		<div class="container">
		
			
			<div class="card col m10">	
				<div class="card-content grey lighten-4">
					<div class="row">
						<div class="col s1">
							<i class="material-icons large prefix red-text">thumb_down</i>
						</div>
						<div class="col s11">
							<div>
								<span class="card-title">Adres Bloklama</span>							
							</div>
							<div>
								<p><h6>Bloklanacak adresi girerek butona basınız</h6></p>			
							</div>							
						</div>
					</div>
				</div>
				<div class="card-action">
					<div class="row">
						<form class="col s12">
							<div class="row">
		        				<div class="input-field col s5">
		          				<i class="material-icons large prefix red-text">public</i>
		          				<input id="icon_prefix" type="text" class="validate">
		          				<label for="icon_prefix">Bloklanacak Adres</label>
		        				</div>
		        				<div class="input-field col s5">
		        					
									<select multiple>
										<option value="" disabled selected>Seçiniz</option>
										<option value="1">Sosyal Medya</option>
										<option value="2">Bahis</option>
										<option value="3">Web Mail</option>
										<option value="4">Yetişkin</option>
										<option value="5">Streaming Media</option>
										<option value="6">Malware</option>
										<option value="1">Sosyal Medya</option>
										<option value="2">Bahis</option>
										<option value="3">Web Mail</option>
										<option value="4">Yetişkin</option>
										<option value="5">Streaming Media</option>
										<option value="6">Malware</option>
									</select>
									<label>Kategori</label>
		        				</div>
		        				<div class="col s2 valign-wrapper center-align">			
									<button class="btn red waves-effect waves-light valign center" type="submit" name="action">Ekle
										<i class="material-icons left">clear</i>
									</button>
		        				</div>
		        			</div>	
						</form>
					</div>	
				</div>	
			</div>

			
			<div class="card col m10">
				<div class="card-content grey lighten-4">
					<div class="row">
						<div class="col s1">
							<i class="material-icons large prefix green-text">thumb_up</i>
						</div>
						<div class="col s11">
							<div>
								<span class="card-title">Adres İzin</span>							
							</div>
							<div>
								<p><h6>Bloklanmış adresi adresi girerek butona basınız</h6></p>
							</div>							
						</div>
					</div>
				</div>
				<div class="card-action">
					<div class="row">
						<form class="col s12">
							<div class="row">						
		        				<div class="input-field col s5">
		          				<i class="material-icons large prefix green-text">public</i>
		          				<input id="icon_prefix" type="text" class="validate" required pattern=" [a-z][A-Z][0-9][\.]">
		          				<label for="icon_prefix">Açılacak Adres</label>
		        				</div>        				
		        				<div class="input-field col s5"></div>	        				
		        				<div class="col s2 valign-wrapper center-align">			
									<button class="btn green waves-effect waves-light valign center" type="submit" name="action">Çıkar
										<i class="material-icons left">check</i>
									</button>
		        				</div>      				
		        			</div>	
						</form>
					</div>		
				</div>
			</div>
			
						
			<div class="card col m10">
				<div class="card-content grey lighten-4">
					<div class="row">
						<div class="col s1">
							<i class="material-icons large prefix red-text">import_contacts</i>
						</div>
						<div class="col s11">
							<div>
								<span class="card-title">Kategori Bazlı Bloklama</span>							
							</div>
							<div>
								<p><h6>Bloklamak istediğiniz kategorileri seçerek girerek butona basınız</h6></p>							
							</div>							
						</div>
					</div>
				</div>
				<div class="card-action">
					<div class="row">
						<form class="col s12">
							<div class="row">						
		        				<div class="input-field col s5">
		        					
									<select multiple>
										<option value="" disabled selected>Seçiniz</option>
										<option value="1">Sosyal Medya</option>
										<option value="2">Bahis</option>
										<option value="3">Web Mail</option>
										<option value="4">Yetişkin</option>
										<option value="5">Streaming Media</option>
										<option value="6">Malware</option>
										<option value="1">Sosyal Medya</option>
										<option value="2">Bahis</option>
										<option value="3">Web Mail</option>
										<option value="4">Yetişkin</option>
										<option value="5">Streaming Media</option>
										<option value="6">Malware</option>
									</select>
									<label>Kategori</label>
		        				</div>
		        				<div class="input-field col s5"></div>
		        				<div class="col s2 valign-wrapper center-align">			
									<button class="btn red waves-effect waves-light valign center" type="submit" name="action">Ekle
										<i class="material-icons left">clear</i>
									</button>
		        				</div>
		        			</div>	
						</form>
					</div>		
				</div>
			</div>
			
						
			<div class="card col m10">
				<div class="card-content grey lighten-4">
					<div class="row">
						<div class="col s1">
							<i class="material-icons large prefix red-text">import_contacts</i>
						</div>
						<div class="col s11">
							<div>
								<span class="card-title">Test</span>							
							</div>
							<div>
								<p><h6>Test test test test test test</h6></p>							
							</div>							
						</div>
					</div>
				</div>
				<div class="card-action">
					<div class="row">
						<form class="col s12">
							<div class="row">						
		        				<div class="input-field col s5">
		        					
									<select multiple>
										<option value="" disabled selected>Seçiniz</option>
										<option value="1">Sosyal Medya</option>
										<option value="2">Bahis</option>
										<option value="3">Web Mail</option>
										<option value="4">Yetişkin</option>
										<option value="5">Streaming Media</option>
										<option value="6">Malware</option>
										<option value="1">Sosyal Medya</option>
										<option value="2">Bahis</option>
										<option value="3">Web Mail</option>
										<option value="4">Yetişkin</option>
										<option value="5">Streaming Media</option>
										<option value="6">Malware</option>
									</select>
									<label>Kategori</label>
		        				</div>
		        				<div class="input-field col s5"></div>
		        				<div class="col s2 valign-wrapper center-align">			
									<button class="btn red waves-effect waves-light valign center" type="submit" name="action">Ekle
										<i class="material-icons left">clear</i>
									</button>
		        				</div>
		        			</div>	
						</form>
					</div>		
				</div>
			</div>
			
		</div>		
	
		<script type="text/javascript" src="js/jquery-2.1.1.min.js"></script>
      <script type="text/javascript" src="js/materialize.min.js"></script>
      <script type="text/javascript" src="js/init.js"></script>
      <script type="text/javascript" src="js/prism.js"></script>
      
	</body>	
</html>`

**Comment by acburst** [comment]
This was caused by the card-action z-index. Ive changed the css around a bit so this should fix it 20c94d8. If you want to download our latest.

But in the meantime try overriding the `.card-action` z-index:

```
.card-action {
  z-index: auto;
}
