### ISSUE TITLE
Missing function to unbind listeners when removing `<select>` elements

### ISSUE THREAD

**Issue by jacobq** [Dogfalo/materialize#3180]
`$.fn.material_select` is needed to obtain proper behavior of `<select>` elements once they have been added to the DOM, but there does not appear to be an inverse function for this (i.e. one that takes care of unbinding the event handlers to avoid memory leaks / zombies, etc.). In modern front-end JS applications it it common to create and delete elements like `<select>` controls, so could you please add this function or explain what to do to address this?

https://github.com/Dogfalo/materialize/blob/master/js/forms.js#L363

**Comment by acupajoe** [comment]
@jacobq You should be able to destroy using `$.fn.material_select('destroy')`  as seen here in forms.js

```
// If destroying the select, remove the selelct-id and reset it to it's uninitialized state.
if(callback === 'destroy') {
    $select.data('select-id', null).removeClass('initialized');
    return;
}
```

**Comment by jacobq** [comment]
Aha, thanks for pointing that out! I guess I was looking for a second function when I should have been looking inside the same function.
