### ISSUE TITLE
Is it posible to disable particular select element?

### ISSUE THREAD

**Issue by epiblue** [Dogfalo/materialize#3181]
Hello,

I've implemented the MaterializeCss in our Magento template, and some of the dropdowns (`select` elements) are causing malfunctions. Is it posible to disable particular `select` elements?

In case anybody know's how to fix it, Magento has the shipping price calculator and when the country is chosen, the Province dropdown is not beeing updated, if you can suggest a better way to fix it without disabling the Material styling, it would be great help.

Thank you and waiting for your reply, 

Best wishes,
Arthur

**Comment by acupajoe** [comment]
@epiblue You don't have to bind to all selects on the page, the documentation gives the example: `$('select').material_select();` which is for all `select` DOM elements. If you want to limit it to a specific set, add a class to the selector i.e. `$('select.materialize').material_select();`

**Comment by epiblue** [comment]
@acupajoe 

Thanks for your reply, Yeah I saw this, but the thing is that, there are quite a few select elements all over the site, and the `$('select').material_select();` is perfect to affect all. 

It would be nice to have something to ignore a particular select option, you know what I mean? 

For example: `$('select.ignore').material_select_ignore(); `

I hope I'm explaning myself,

Best wishes and thanks for the reply,

**Comment by acupajoe** [comment]
Try `$('select').not('.ignore').material_select()`?

**Comment by fega** [comment]
Closed due inactivity, feel free to reopen it if it is still necessary.
