### ISSUE TITLE
Need a RESET css file for all your css adjustments in native elements like <nav> tag

### ISSUE THREAD

**Issue by systemaker** [Dogfalo/materialize#3182]
hello,
Can we get a reset css file to normalize native elements like nav tag  without all your customized attributes ?

**Comment by systemaker** [comment]
zzzZZZZzzz

**Comment by fega** [comment]
you could build it from the scss removing the unwanted features.

**Comment by systemaker** [comment]
Did it a long time ago but the css file that you provided should be in a version filtered for easy css customs of materialize components

**Comment by fega** [comment]
something like this?

http://jqueryui.com/download/

**Comment by tomscholz** [comment]
@systemaker Check [this](https://bitbucket.org/seanmavley/matcustom) out.

**Comment by fega** [comment]
@tomscholz  It seems to be a little outdated, it would be great to place it in a subdomain of materializecss.com
