### ISSUE TITLE
Dropdown in slider cause conflicts

### ISSUE THREAD

**Issue by hamidre13** [Dogfalo/materialize#3183]
If you have dropdown in slider it will cause conflicts. Here is the demo:
[Code pen](http://codepen.io/hamidre13/pen/NNZXbb)
The reason is :
[https://github.com/Dogfalo/materialize/blob/master/js/slider.js#L20](https://github.com/Dogfalo/materialize/blob/master/js/slider.js#L20)
changing that to : $slider.children() should solve the problem although it dropdown still does not work. I will look into that and open another issue.

**Comment by acburst** [comment]
Thanks for pointing this out!

Fixed in 9bd32b0
