### ISSUE TITLE
wave-circle make icon not fit in navbar

### ISSUE THREAD

**Issue by ardianta** [Dogfalo/materialize#3185]
I create menu item in navbar, it just contain icon and give it `wave-circle` class

``` html
<ul class='right'>
    <li>
        <a class="waves-effect wave-circle" href="/p/arsip-petani-kode.html">
              <i class='material-icons'>archive</i>
        </a>
    </li>
</ul>
```

The output:
![](http://imgur.com/1otsYpll.png)

**Comment by acburst** [comment]
You need to give the anchor tag some css. Try giving it a set width and height.
