### ISSUE TITLE
Images inside buttons

### ISSUE THREAD

**Issue by LCallaghan84** [Dogfalo/materialize#3189]
Is there any chance you can make a new button, one that you can use images 
and the images have the wave effect

for example: http://codepen.io/Lcallaghan84/pen/pyMvew

I used transparent images inside button, but the wave effect does not show.
is there I can make it work?

**Comment by acburst** [comment]
You have double added the waves-effect for some reason. Remove the waves classes from your img and leave them on the wrapping anchor and they work

**Comment by LCallaghan84** [comment]
alright, thanks. it works. still would be nice to see a new button component that you can use images as well.

**Comment by acburst** [comment]
What would it do exactly? I don't see any problem with what you've done

**Comment by LCallaghan84** [comment]
I used transparent images inside buttons, but images that do not have transparent backgrounds, the wave effect wont work. so adding a new button that supports images of all types with wave effect but would be nice :+1:
