### ISSUE TITLE
Sample Code for Indeterminate style checkbox is not there on website.

### ISSUE THREAD

**Issue by tirth-patel** [Dogfalo/materialize#3192]
![ ](http://i.imgur.com/goLosv7.png)

**Comment by acburst** [comment]
Fixed in 6191605

**Comment by ermarkar** [comment]
`<p>
      <label>
        <input id="indeterminate-checkbox" type="checkbox" />
        <span>Indeterminate Style</span>
      </label>
    </p>`

this is not working. Your library is good but can you please improve the documentation.
