### ISSUE TITLE
How to start wave effect?

### ISSUE THREAD

**Issue by softshape** [Dogfalo/materialize#3193]
How to start wave effect on the waves-enabled button with JavaScript? I've tried to emulate mouse click, but mouseup(), mousedown() and click() won't work.

**Comment by acburst** [comment]
We use http://fian.my.id/Waves/ and currently in our version of waves there is no option for this. There is a newer version we can update to that does have an option to trigger a wave programmatically. We'd be open to some help with updating waves and making sure it doesn't cause any backwards compatibility problems

**Comment by softshape** [comment]
They have some bugs still, I've just submitted one - https://github.com/fians/Waves/issues/156 - probably it's a good idea to update but better wait for bugfixes.

**Comment by mateosss** [comment]
Is there any update on this?

**Comment by softshape** [comment]
They still use waves.js 2 years old. I've finally dropped waves.js from my package and replace it with this code, shorter and stable -

```
$(function(){
  $(document).on('click', '.waves-effect', function(e){
 
    var ink, d, x, y;

    if ($(this).find(".ink").length === 0) 
    {
      $(this).prepend("<span class='ink'></span>");
    }
         
    ink = $(this).find(".ink");
    ink.removeClass("animate");
     
    if (!ink.height() && !ink.width())
    {
      d = Math.max($(this).outerWidth(), $(this).outerHeight());
      ink.css({height: d, width: d});
    }
     
    x = e.pageX - $(this).offset().left - ink.width()/2;
    y = e.pageY - $(this).offset().top - ink.height()/2;
     
    ink.css({top: y+'px', left: x+'px'}).addClass("animate");
  });
});
```

**Comment by softshape** [comment]
here's CSS part -

```
.ink {
  display: block;
  position: absolute;
  background:rgba(55, 55, 55, 0.1);
  border-radius: 100%;
  -webkit-transform:scale(0);
     -moz-transform:scale(0);
       -o-transform:scale(0);
          transform:scale(0);
}

.animate {
	-webkit-animation:ripple 0.65s linear;
   -moz-animation:ripple 0.65s linear;
    -ms-animation:ripple 0.65s linear;
     -o-animation:ripple 0.65s linear;
        animation:ripple 0.65s linear;
}

@-webkit-keyframes ripple {
    100% {opacity: 0; -webkit-transform: scale(2.5);}
}
@-moz-keyframes ripple {
    100% {opacity: 0; -moz-transform: scale(2.5);}
}
@-o-keyframes ripple {
    100% {opacity: 0; -o-transform: scale(2.5);}
}
@keyframes ripple {
    100% {opacity: 0; transform: scale(2.5);}
}
```

**Comment by tomscholz** [comment]
@acburst What do you think? Is it time to drop waves.js? @softshape I guess you could create a PR that implements it and we will look into it :)

**Comment by tomscholz** [comment]
Closed due inactivity and missing feedback. Feel free to reopen it, if it's still necessary.
