### ISSUE TITLE
select not working properly with angularjs.

### ISSUE THREAD

**Issue by nasr18** [Dogfalo/materialize#3194]
`select` not working properly with angularjs. See the below image.

![materialize select](https://cloud.githubusercontent.com/assets/7514936/15466772/c826b834-20f8-11e6-9790-a93903c0694e.png)

Hepl me as soon as you can

**Comment by kMeillet** [comment]
Try to use this select directive : https://github.com/krescruz/angular-materialize

**Comment by nasr18** [comment]
ok @kMeillet  will look at it.
