### ISSUE TITLE
Invalid bower.json

### ISSUE THREAD

**Issue by gluons** [Dogfalo/materialize#3195]
**Bower Warning**
```
bower materialize#*       invalid-meta The "name" is recommended to be lowercase, can contain digits, dots, dashes
bower materialize#*       invalid-meta The "main" field cannot contain font, image, audio, or video files
bower materialize#*       invalid-meta The "main" field has to contain only 1 file per filetype; found multiple .ttf files
bower materialize#*       invalid-meta The "main" field has to contain only 1 file per filetype; found multiple .woff files
bower materialize#*       invalid-meta The "main" field has to contain only 1 file per filetype; found multiple .woff2 files
```

**Comment by kevgathuku** [comment]
I agree. From the [spec](https://github.com/bower/spec/blob/master/json.md)
 - `name` field: Lowercase, a-z, can contain digits, 0-9, can contain dash or dot but not start/end with them.
 - Image and font files may be used or referenced within the JS or Sass files, but are not main files as they are not entry-points.

**Comment by gluons** [comment]
So Sad  :disappointed_relieved:

<img width="808" alt="Bower Warning" src="https://cloud.githubusercontent.com/assets/4688092/15707349/8006975a-2822-11e6-8ceb-2104f27ec942.png">
