### ISSUE TITLE
Problem with Searh Bar in NavBar

### ISSUE THREAD

**Issue by imraphox** [Dogfalo/materialize#3198]
![screen shot 2016-05-23 at 3 31 49 pm](https://cloud.githubusercontent.com/assets/1952434/15480361/8cea174a-20fb-11e6-8f5e-9e1ca73838cb.png)

on focus not work properly.

**Comment by kaytrance** [comment]
See #3117

**Comment by acburst** [comment]
Duplicate of #3161
