### ISSUE TITLE
Why material select clones the select element class list?

### ISSUE THREAD

**Issue by ahlechandre** [Dogfalo/materialize#3199]
Considering a select element:

``` html
<select class="my-select">
   <!-- options -->
</select>
```

After initialized by `material_select` method the select class list is cloned in parent node:

``` html
<div class="select-wrapper my-select">
   <!-- (...) -->
   <select class="my-select">
      <!-- options -->
   </select>
</div>
```

Now the query selector `.my-select` I will get `div.my-select` instead of `select.my-select` and it is does not seem the right thing.

For example, considering a scenario that has a handler for registration and upgrade new components and each component is represented by its class. This behavior breaks the normal flow of application.  

Every time the handler check for upgrade it will double the components infinitely. 

e.g.

``` html
<select class="my-select">...</select>
```

``` js
// Registration.
handler.registerComponent({
  name: 'MySelect',
  cssClass: 'my-select'
});

// Handler will query for the css class and upgrade all elements.
// First time, will upgrade ok because ".my-select" means the select element. 
handler.upgradeComponent('MySelect');
```

Now the select element seems like this and handler knows that component is upgraded.

``` html
<div class="select-wrapper my-select">
   <!-- (...) -->
   <select class="my-select" data-upgraded="MySelect">
      <!-- options -->
   </select>
</div>
```

After, It will fail if need to check for upgrade:

``` js
// Now the handler will find "div.select-wrapper.my-select" instead of select element. 
handler.upgradeComponent('MySelect');
```

``` html
<div class="select-wrapper my-select">
   <!-- (...) -->
   <div class="select-wrapper my-select" data-upgraded="MySelect">
     <!-- (...) -->
     <select class="my-select" data-upgraded="MySelect">
         <!-- options -->
      </select>
   </div>
</div>
```

**Comment by acburst** [comment]
Can you upgrade with Id? It doesn't clone Ids

**Comment by ahlechandre** [comment]
@acburst It's a conceptual issue. A component behavior must be assigned to a `class` that can represents more than one element and not a specific `id`.

Maybe the right thing is the Framework not clone/depends/use css classes defined by users to keep independence of application builded with it. 

Why clones the class list in this case? to trigger the `onchange` event? 

I suggest that Materialize team to review this issue.

**Comment by fega** [comment]
@acburst What we could do with this issue?, I cannot define it as a enhancement, bug.

**Comment by fega** [comment]
Closed due inactivity, feel free to reopen it if it is still necessary.

**Comment by ruinunes** [comment]
I found myself needing to _replace_ the parent `'select-wrapper'`, with a newly cloned select element and after that run `.materialize_select()`.

```coffeescript
$existingSelects.on 'contentChanged', ->
      $select = $ this
      $select.parent('.select-wrapper').replaceWith $select
      $select.material_select()
```
