### ISSUE TITLE
Select dropdown appearing behind other elements

### ISSUE THREAD

**Issue by dmallory42** [Dogfalo/materialize#3200]
Similarly to #1385, I'm having an issue where a dropdown will be hidden if it goes outside of the area of its parent (please see screenshot).

![screen shot 2016-05-24 at 13 13 44](https://cloud.githubusercontent.com/assets/11770181/15503362/6b68a9e0-21b1-11e6-97ef-b3044a1395fa.png)

The other thread suggested using `overflow: visible` on the parent to the Select Dropdown, this will work, however this is not a viable option for me as I need the overflow to be set to 'auto' in order to render other elements of the page correctly. Are there any alternative ways to get around this issue, or any plans to otherwise resolve it? Thanks.

**Comment by weinde** [comment]
I have the same problem... any way to resolve this?

**Comment by fega** [comment]
Please provide a way to reproduce it. like a [codepen](https://codepen.io/fega/pen/BWeZaG)

Closed due inactivity, feel free to reopen it if it is still necessary.
