### ISSUE TITLE
Support for Jquery 3.0

### ISSUE THREAD

**Issue by raul782** [Dogfalo/materialize#3201]
As Jquery approaches its final release, I'm wondering where we stand in order to support this dependency.

So far, I've found one item not working with the jquery 3.0rc1, I'll keep testing and updating this issue with other breaking changes, unless this is being dealt somewhere else.
- Select Input not displaying options correctly.

**Comment by kmmbvnr** [comment]
jQuery Migrate could help to find a possible issues

http://blog.jquery.com/2016/05/19/jquery-migrate-1-4-1-released-and-the-path-to-jquery-3-0/

**Comment by acburst** [comment]
Moving to jQuery 3.0 is going to take a large effort. It will take a long time to fully test everything and we would be open to incremental pull requests that would make our plugins work well with jQuery 3

**Comment by erkiha** [comment]
I have also found that select input does not work with jquery 3.0. Also tried with jquery 3.0 migration plugin, this did not help.

Everything else I needed worked ok in jquery 3.0. So only one issue for me.

**Comment by dmethvin** [comment]
I might be able to help here. Do you have some idea of where the problems are? Will the tests give me some idea?

**Comment by sommmen** [comment]
How is JQ3 support going?
is there a branch i could look at for more jq3 support?

**Comment by Dogfalo** [comment]
I wasn't able to recreate the problem with the select input in jQuery 3.1.1. Can you give more information about what is not working? @erkiha @raul782

**Comment by fega** [comment]
Closed due inactivity, feel free to reopen it if it is still necessary.

**Comment by tomscholz** [comment]
I will reopen this issue until we have merged or declined [this PR](https://github.com/Dogfalo/materialize/pull/4587)

**Comment by ministrycrm** [comment]
![](https://files.slack.com/files-pri/T0DGRBBFS-F5ELFH9UH/screen_shot_2017-05-18_at_12.38.57_pm.png)

**Comment by ministrycrm** [comment]
![image](https://cloud.githubusercontent.com/assets/449786/26216113/8b350430-3bc8-11e7-9ac8-d2e4d37aaa00.png)

**Comment by tomscholz** [comment]
Merged in https://github.com/Dogfalo/materialize/commit/e2d9710672e120f72134704e4fb33f0bf5538af7
