### ISSUE TITLE
how to move overflow-y in modal to  keep right  browser page ?

### ISSUE THREAD

**Issue by tonspu55** [Dogfalo/materialize#3204]
![issue](https://cloud.githubusercontent.com/assets/16715282/15567960/a041d86e-2353-11e6-99c8-aa5c81886aa6.png)

**Comment by Xuzrus** [comment]
Adding _left:auto_ to the modal will remove the constraint on the left side and thus allow it to align to the right.
```
.modal {
    left: auto;
}
```
