### ISSUE TITLE
FAB buttons to work in position:relative

### ISSUE THREAD

**Issue by keyscores** [Dogfalo/materialize#3207]
See reproduciton here: 
http://jsfiddle.net/L0jg6bn6/

FAB buttons are great. But sometimes they need to be positioned 'relative' in a div. The trouble is that the 'child' buttons get misplaced, and they appear in a 'fixed' position elsewhere on the screen. 

Are there docs to address this or is it a bug?

**Comment by acburst** [comment]
Try setting the width of the container to the width of your button

**Comment by keyscores** [comment]
Thanks it does work. It is quite hard to get the child buttons to align perfectly. 
But that seems to only solve vertical child buttons. How would we do it with horizontal buttons? Which BTW doesn't seem to be working in the jsfiddle: http://jsfiddle.net/L0jg6bn6/

**Comment by keyscores** [comment]
@acburst Any updates regarding this issue? Would be nice for FAB to work in static and relative mode.

**Comment by fega** [comment]
@keyscores I'm not sure what do you want yo achieve with your jsfiddle, but it seems to be working in the latest version

Closed due inactivity, feel free to reopen it if it is still necessary.
