### ISSUE TITLE
Mobile version of nav not working a all in latest release (chrome)

### ISSUE THREAD

**Issue by Saul-Simhon** [Dogfalo/materialize#3209]
go to: http://materializecss.com/navbar.html

shrink window. the nav items at the top disappear in all the examples,  but no mobile version of it is available. Occurs on my local static html too (with one top nav). worked in prior version of materialize

**Comment by Dogfalo** [comment]
Not a bug  they have show on medium and down class which goes them on smaller screens

**Comment by Saul-Simhon** [comment]
yes, your right. I see it works on your page. 

On my page, when I changed <i class="mdi-navigation-menu"></i> to <i class="material-icons">menu</i>, the menu appears. Not sure why <i class="mdi-navigation-menu"></i> used to work, now it does not.

**Comment by Dogfalo** [comment]
The icons have changed in one of the more recent versions.
