### ISSUE TITLE
Make v0.97.6 available on Atmospherejs/Meteor

### ISSUE THREAD

**Issue by sazp96** [Dogfalo/materialize#3210]
Hey guys, two things:

1. I :heart: materialize
2. Could you make the latest version available for Meteor? Thanks!

![image](https://cloud.githubusercontent.com/assets/9439311/15619583/c90812f0-241a-11e6-936c-3245fa96ad99.png)

**Comment by keyscores** [comment]
+1

**Comment by Dogfalo** [comment]
The autopublisher we were using no longer works, but we have pushed this version manually
