### ISSUE TITLE
Select in Angular-Materialize don't show me, appear in display:none

### ISSUE THREAD

**Issue by gomezv9** [Dogfalo/materialize#3211]
Hi 

I have a problem with the Angular-Materialize Select in my project.

The problem is that the select show me in "display:none", I think that it haven´t been execute very good in the javascript or I don´t know.

This is my Select:

```
<div input-field>

            <select ng-model="selected_state" ng-change="getArrayCities(selected_state)" material-select>
                 <option value="" disabled selected>Choose a state</option>
                <option ng-repeat="st in usa track by $index" value="{{st}}" >{{st.name}}</option>
            </select>


</div>
```

But if I put the class:"browser-default", it show without the Angular-Materialize effect but it work perfect, like this:

```
<div input-field>

            <select ng-model="selected_state" class="browser-default" ng-change="getArrayCities(selected_state)">
                 <option value="" disabled selected>Choose a state</option>
                <option ng-repeat="st in usa track by $index" value="{{st}}" >{{st.name}}</option>
            </select>

</div>
```

I don't know why this happend.

Any help ?

**Comment by TyrionGraphiste** [comment]
Did you init the select with :
`$(function () {
    $('select').material_select();
});`
