### ISSUE TITLE
Horizontal FAB class is using vertical alignment for child buttons

### ISSUE THREAD

**Issue by keyscores** [Dogfalo/materialize#3213]
Since 0.97.6 it seems the 'horizontal' tag is not working for FAB buttons. I've copied the Materialize example from buttons.html into the jsfiddle: http://jsfiddle.net/fovka3og/

Here is the reproduction with 0.97.5 resources. It works as expected:
http://jsfiddle.net/0x6te116/

**Comment by acburst** [comment]
Your js fiddle is using a 0.97.0 css file. I've tested with a current version and it works.

**Comment by keyscores** [comment]
@acburst, I'm using the Meteor package, perhaps that needs to be updated?
