### ISSUE TITLE
Search bar shifted on Google Chrome

### ISSUE THREAD

**Issue by aymericpasco** [Dogfalo/materialize#3215]
Hi,

The search bar is shifted on Google Chrome browser from me.

Problem only with GC, works fine with others.

Ayme

**Comment by MrPark97** [comment]
You can add 
#search {
	height: inherit;
}
in any custom style after init materialize.css

**Comment by aymericpasco** [comment]
Hi, thx for your answer,

Doesn't work with "#search" but work directly with : 
```
.input-field input[type=search] {
    height: inherit;
}
```
