### ISSUE TITLE
cannot make the date picker a required field

### ISSUE THREAD

**Issue by rantool** [Dogfalo/materialize#3216]
how to change date picker to a required field?
I have tried this but does not work
                           <div class="input-field col s6">  
                            <label name="buildDate" class="">Build Date</label>
                            <input id="buildDate" type="text" class="datepicker picker__input" required>  
                        </div>

**Comment by rantool** [comment]
<div class="input-field col s6">   
                            <label name="buildDate" class="">Build Date</label>
                            <input id="buildDate" type="text" class="datepicker picker__input" required>                                       
                        </div>

**Comment by anantoghosh** [comment]
From the datepicker documentation

> By default, typing into the input is disabled by giving it a readOnly attribute. Doing so ensures that virtual keyboards don’t pop open on touch devices. It is also a confirmation that values passed to the server will be of a consistent format. 

> Because each input is readOnly by default, HTML5 attributes, such as required and pattern, do not get enforced.

You can manually check for the values instead
checkout the example https://jsfiddle.net/9e33kq0q/1/

**Comment by jpt007** [comment]
@anantoghosh - Thanks for the manual check example. Do you know of a way to show the "data-error" defined in the label when it's invalid?

**Comment by anantoghosh** [comment]
Add some css classes
https://jsfiddle.net/anantoghosh/cgzLmx0t/1/

**Comment by jpt007** [comment]
Thanks @anantoghosh !
