### ISSUE TITLE
Time select appears in two lines 

### ISSUE THREAD

**Issue by faethonm** [Dogfalo/materialize#3217]
Hello, im having an issue with time select using materialize in rails. My time_select input field is
https://www.dropbox.com/s/9mw6c72z06vbqar/Screenshot%202016-05-31%2001.24.06.png?dl=0
and the code is here 
 https://gist.github.com/faethonm/90af410bb87598d7210320fbc2a48fb6

**Comment by Dogfalo** [comment]
Use the grid system to lay out your form. having class `col s6` will fix it.

**Comment by mbd-s** [comment]
I've got the same issue, and I'm already making use of the grid system: 
```
<div class="input-field col l3">
      <i class="material-icons prefix">query_builder</i>
      <%= f.time_select :start_time, ignore_date: true, minute_step: 15 %>
      <%= f.label :start_time %>
    </div>
```
