### ISSUE TITLE
Can not clear margins inside the ".container" class

### ISSUE THREAD

**Issue by nazarposhta** [Dogfalo/materialize#3218]
I'm using the container class in my project and on the mobile phones (sometimes) I need to clear margins        inside the ".container" but it's not possible, because that box have 70% width on the mobile. 
https://monosnap.com/file/1bobOsMG1PvhHe6hMqpHz27x6IKGHg

As you see class ".row" does not manage this problem. I steel have some margin on the right and left side.

**Comment by Nohinn** [comment]
To remove those margins you need to:
1) Set width to 100% for the .container element so it overwrites the different media css rules:
`@media only screen and (min-width: 993px)
.container {
    width: 70%;
}

@media only screen and (min-width: 601px)
.container {
    width: 85%;
}
`

2) Set margin to 0. `.container { margin: 0; }`
3) In case you need it, set max-width to 100% `.container { max-width: 100%; }`

Just be careful with the media css rules, those are the ones you should try to replace with your own rules.

**Comment by acburst** [comment]
Try overriding with your own css rules
