### ISSUE TITLE
Can't truncate breadcrumb text

### ISSUE THREAD

**Issue by RhanCandia** [Dogfalo/materialize#3220]
Adding truncate class to the breadcrumb breaks it. I tried manually truncating the texts through css but no luck. Any help would be appreciated.

**Comment by Nohinn** [comment]
When applying the truncate class, the element css display value is block.
I have prepared a codepen that you can check for truncating breadcrumb text.
http://codepen.io/Nohinn/pen/ezpbWa

The spans inside the a breadcrumb elements are used so you can define a max-width only for the text, so you don't have any problems with the separators.

The important steps are:
1) Apply to the truncate element the display: inline-block;
2) Apply to the truncate element the vertical-align: top. So all the breadcrumbs are vertical aligned.

**Comment by RhanCandia** [comment]
Thank you. That works. It was having `vertical-align: top` that I missed.
