### ISSUE TITLE
How can I use jquery maskMoney or any other currency input solution

### ISSUE THREAD

**Issue by chrisco23** [Dogfalo/materialize#3222]
I've spent countless hours with no solution here.

I take it there is no way to break out of materialize to use a regular jquery plugin, like jquery-maskMoney?

And I can find no alternative for a decent currency input suitable for the "material design" way of doing things.

Granted, I'm a developer and not really a designer but can anybody suggest anything?  This is completely a showstopper I don't need right now.

**Comment by fega** [comment]
Please in the future provide a way to reproduce the problem that you're facing. like a codepen or  a fiddle snippet

Closed due inactivity, feel free to reopen it if it is still necessary.
