### ISSUE TITLE
row inside an container and negative margin

### ISSUE THREAD

**Issue by eric-burel** [Dogfalo/materialize#3225]
Hi, 

I have some trouble with negative margins, here is the simplest code to reproduce :
```html
<div class="container" style="background-color:#ff0000>
    <div class="row>
        Hello
    </div>
</div>`
```
The hello seems to be "floating" in the left, half outside the red block
That's due to `.container .row` rule (`_grid.scss` file) setting negative right and left margins : `margin-left:-0.75rem`.

Maybe that's normal, but I can't understand why...
The issue might be related to #3218, however it happened on a large screen.

**Comment by acburst** [comment]
Our grid system is made so that every .row should have a .col nested immediately inside. So you will have weird behavior if you have single .row's or .col's
