### ISSUE TITLE
Update to use latest Waves.js because there is a fix for memory leak with removeEventListener

### ISSUE THREAD

**Issue by kunukn** [Dogfalo/materialize#3226]
The waves.js old version has memory leak and has been fixed 
https://github.com/fians/Waves/commit/8a79d8b0c03ad775cc2ed43e0c7d357a5049d235

I could not see any usage of removeEventListener on current code in materializecss in waves.js.

In Chrome browser I have tested by adding a material design button.
In browser console I use this script.

```
var listenerCount = 0;
(function() {
    var ael = Node.prototype.addEventListener;
    Node.prototype.addEventListener = function() {
         listenerCount++;
         ael.apply(this, arguments);
    }
    var rel = Node.prototype.removeEventListener;
    Node.prototype.removeEventListener = function() {
         listenerCount--;
         rel.apply(this, arguments);
    }
})();
```

Then click the material design button a few times. You will see the number of event listeners increases.
In the browser console type `listenerCount`and enter to see the number of event listeners.

**Comment by acupajoe** [comment]
#3193 Related comments

**Comment by fega** [comment]
Duplicate
