### ISSUE TITLE
SideNav is not working right in 97.6

### ISSUE THREAD

**Issue by Raullg98** [Dogfalo/materialize#3227]
My web page in 97.5 
http://codepen.io/raullg/pen/jrPwGz
http://prntscr.com/bbz1fw
<img src="http://image.prntscr.com/image/4e8f8416770c4562af52ee23b6885ce8.png">

My web page in 97.6
http://codepen.io/raullg/pen/pbJwpK
<img src="http://image.prntscr.com/image/6dba102f1dc546709ba308e6bbb08fc8.png">

**Comment by acburst** [comment]
Sidenav is working fine. We have stopped supporting the old icon which is being used in your example. Checkout the icons docs for more information on how to switch over to the official icon font.
