### ISSUE TITLE
Tooltips not present when ".tooltipped" class is added dynamically

### ISSUE THREAD

**Issue by Clean0nion** [Dogfalo/materialize#3228]
Using AngularJS, I'm dynamically adding /  removing the ".tooltipped" class to and from elements using ngClass. None of them have tooltips.

**Comment by apexJCL** [comment]
It may sound dumb, but, Did you initialized the tooltips on js?

**Comment by Clean0nion** [comment]
Ah. No.
xD
Thank you very much!
