### ISSUE TITLE
Ripple effect incomplete on click at corner of big button

### ISSUE THREAD

**Issue by Maximetinu** [Dogfalo/materialize#3232]
Gif of what's happening:
https://i.imgflip.com/15f45k.gif

I am so disgusting with this.
Try harder guys. Try harder.

**Comment by Lifka** [comment]
OMG

**Comment by fega** [comment]
I Know that this is duplicate, but I cannot found the other issue

**Comment by Maximetinu** [comment]
What do you mean?
