### ISSUE TITLE
Huge line-height in collapsible-header that has more than one line

### ISSUE THREAD

**Issue by Jeffrey04** [Dogfalo/materialize#3233]
is it possible to not have `line-height: 3rem`?

**Comment by Nohinn** [comment]
You can do it with CSS or after initializing the collapsible using jQuery to modify the line-height for that header.

a)
`.collapsible-header {
    line-height: normal;
}`

b)
`$(".collapsible-header").css("line-height", "normal");`

If you only want to apply that for an specific header then add an extra class using jQuery to the header and apply the before code to that css class.

**Comment by Jeffrey04** [comment]
ok, got that fixed with 

```
    .collapsible-header {
        line-height: 1.5rem;
        padding: 1rem;
    }
```

hopefully this doesn't break other element's style
