### ISSUE TITLE
materialboxed inside of Tabs, weird interaction with the overlay

### ISSUE THREAD

**Issue by ryancj** [Dogfalo/materialize#3234]
Hi. Been working on my personal site and I'm trying to put images inside my Tab sections.
Getting some weird interactions:
- Only the tabs section gets covered by the overlay
- When the image expands, it hides beneath images (also 'materialboxed') that are outside the tab section

I just want the images within my tab section to behave like it should. The overlay to cover the full screen with a caption where it sits on top of everything else. What should I do? 

Thanks!

[Screenshots of whats happening](http://imgur.com/a/G4NGc)

**Comment by acburst** [comment]
Can you post some code samples?

**Comment by fega** [comment]
Closed due inactivity, feel free to reopen it if it is still necessary.
