### ISSUE TITLE
PSD Template

### ISSUE THREAD

**Issue by free6k** [Dogfalo/materialize#3236]
Hello all! I want use this framework for next our project. I have next question: Does somebody have psd template(photoshop, ai, indesign or more) for this framework or another fast constructor for designers??

Thanks all for you answers!

**Comment by Dogfalo** [comment]
Try using the official component PSD from Google: [here](https://material.google.com/resources/sticker-sheets-icons.html#)

**Comment by free6k** [comment]
Thanks for your answer! Will be cool if somebody would create online editor )

**Comment by Kail0** [comment]
Why would you want online editor if you just need vector components and working graphic program eg. Photoshop, illustrator? (:

If you want to design in MD, I definitely suggest you to look in their (guidlines)[https://material.google.com/] 
You can find all other principles and PSD templates, as @Dogfalo wrote before
