### ISSUE TITLE
Datepicker parent overflow:hidden

### ISSUE THREAD

**Issue by dehrax** [Dogfalo/materialize#3238]
When the datepicker has a parent with overflow:hidden, the overlay does not seem to override it. 
![image](https://cloud.githubusercontent.com/assets/1438972/15962050/bef9d296-2f08-11e6-97dc-e02836e00d64.png)

Could a similar approach be used here as in materialbox?

https://github.com/Dogfalo/materialize/blob/b03030ed5c5ea2018424e2b6a73084f65e8ec63d/js/materialbox.js#L59

**Comment by fega** [comment]
Could you check if this is still an issue with the last version? also,
please provide a way to reproduce it. like a codepen or  a fiddle snippet

Closed due inactivity, feel free to reopen it if it is still necessary.

**Comment by tomscholz** [comment]
You can set the parent of the datepicker. Have a look [here](https://github.com/Dogfalo/materialize/issues/1032)
