### ISSUE TITLE
disable close on select for datepicker component

### ISSUE THREAD

**Issue by wayou** [Dogfalo/materialize#324]
really love this framework!

here's a suggestion:

the more reasonable way for the data picker is to click the `OK` button to close just like [this](http://ui.lumapps.com/directives/date-picker) does.

and the android 5 also behaviors that way. there's a `OK` and `cancel` button to close the modal.
![webwxgetmsgimg](https://cloud.githubusercontent.com/assets/3783096/5537955/a00c7726-8ae5-11e4-97b6-1d85f534dcca.jpg)

**Comment by Dogfalo** [comment]
Fixed in db0629d30a9d3e5ac06a019955a8e10062f91833
