### ISSUE TITLE
Footer not visible on mobile

### ISSUE THREAD

**Issue by debsush** [Dogfalo/materialize#3243]
Hi,

My app footer is currently working fine in desktop/laptop etc. but is not visible on mobile.

AppName: http://gocharting.com

Please let me know where am I going wrong

Regards,
SD

**Comment by acburst** [comment]
You are wrapping everything in an iframe. This is causing it to have a max-height. Not sure why you are using an iframe but it won't work well responsively.

**Comment by debsush** [comment]
Thank you for noting that.   I have made the change and now you can access the app without any iframe.

Two issues:
1. Footer not visible in mobile
2. navbar does not cover 100% of the width
3. The Logo name "GoCharting" not appearing in navbar

Kindly help me on this.

Thank you
SD

**Comment by debsush** [comment]
@acburst @Dogfalo 
Please help with my queries in case you have had a chance to review my app now.  I am struggling to get the nitty-gritties ironed out before my release.

Appreciate you work on this awesome framework.
Regards
SD
