### ISSUE TITLE
incorrect email validation

### ISSUE THREAD

**Issue by paritosh-gupta** [Dogfalo/materialize#3248]
The inbuilt email validation seems to have incorrect logic. It does not require a tld to be entered
For example:-
abc@gmail is detected as valid when it should be abc@gmail.com
Can be replicated on:-
http://materializecss.com/forms.html
tested on 0.97.6

**Comment by acburst** [comment]
This is the built in HTML5 email input validation type. We did not implement this and it is out of our control. Learn more here: [http://www.w3schools.com/html/html_form_input_types.asp](http://www.w3schools.com/html/html_form_input_types.asp)
