### ISSUE TITLE
Select max-height overflow

### ISSUE THREAD

**Issue by liukidar** [Dogfalo/materialize#3252]
In a page with two or more selects with a lot of options which will cause the resizing of the <ul> with the max-height property to avoid the viewport overflow, if you open the first select and then click directly on the second, this would not be resized and it will cause the overflow.
![screenshot 4](https://cloud.githubusercontent.com/assets/19915578/16021130/4d897642-31b1-11e6-9411-0ad251c7ba3c.png)
In the screenshot I have previously clicked on the first select.
I've look through materialize.js and I think the main problem is here:
`if ($('ul.select-dropdown').not(options[0]).is(':visible')) 
{
$('input.select-dropdown').trigger('close');
}`
Deleting or changing into this:
`if ($('ul.select-dropdown').not(options[0]).hasClass('active'))
 {
$('input.select-dropdown').trigger('close');
}`
solves the problem, althought I haven't any idea of what these lines do (so I don't know if the correction leads to other issues; this line is called for each dropdown on the page if I directly click on a new select).
Other solutions I've found:
`function hideDropdown() {
                // Check for simultaneous focus and click events.
                isFocused = false;
                activates.fadeOut(options.outDuration);
                activates.removeClass('active');
                origin.removeClass('active');
                setTimeout(function () {
                                activates.css('max-height', '');
                }, options.outDuration);
            }`
When clicking on a new select the activates in the functions would be overidden and will be the new one's max-height to be changed and not the old one (which cause the overflow). So I removed this SetTimeout and place instead a 
`activates.css('max-height', '');`
before
`if (offsetTop + activates.innerHeight() > windowHeight) {
                    // If going upwards still goes offscreen, just crop height of dropdown.
                    if (offsetTop + originHeight - activates.innerHeight() < 0) {
                        var adjustedHeight = windowHeight - offsetTop - verticalOffset;
                        activates.css('max-height', adjustedHeight);
                    } else {
                        // Flow upwards.
                        if (!verticalOffset) {
                            verticalOffset += originHeight;
                        }
                        verticalOffset -= activates.innerHeight();
                    }
                }`
I hope this could help. For any other details I'm here

**Comment by fega** [comment]
Closed due inactivity
Personally, I cannot get what are you trying to solve, Could you add a snippet or a way to reproduce it?

**Comment by liukidar** [comment]
In the last build everything seems fine. That issue was with the 0.97.x.

2017-04-05 5:57 GMT+02:00 Fabian Gutierrez <notifications@github.com>:
