### ISSUE TITLE
Card Reveal Ripple Animation

### ISSUE THREAD

**Issue by igeligel** [Dogfalo/materialize#3257]
If you try to move the image in a card which has the class activator the ripple effect will stack and will not delete old overlays.

Example of it:
[https://streamable.com/p7b4](https://streamable.com/p7b4)

Used Software:
- Materialize 0.97.6
- Chrome Version 51.0.2704.84 m
- Windows 10

I do not know how to fix it, just wanted to report it. Sorry :(

**Comment by GRIM2D** [comment]
Try to make your image `not selectable`

Refer to this: http://stackoverflow.com/questions/826782/css-rule-to-disable-text-selection-highlighting

**Comment by fega** [comment]
Duplicate #2667
