### ISSUE TITLE
Changing Modal Hover Color

### ISSUE THREAD

**Issue by fupuchu** [Dogfalo/materialize#3258]
Hello,

I've ran into an issue where I wanted to change the hover color for modal-trigger.

Currently I have this on my custom css file

> body > main > div > p:nth-child(1) > a:hover{
>	background-color: black;
>}
>body > main > div > p:nth-child(6) > a:hover{
>	background-color: black;
>}

Is there a way to unify this across the whole site?

**Comment by Nohinn** [comment]
You could add a custom CSS class to both buttons and then in your css declare only once the css rule:
`.myCustomButtonClass:hover {
background-color: black;
}`
