### ISSUE TITLE
How do you get the full file path?

### ISSUE THREAD

**Issue by Nxt3** [Dogfalo/materialize#3262]
When uploading a file using the `file-field` class. Unfortunatly, once a file is uploaded, we don't get the complete path. How can we get the full path?

Example:

I upload a file called `pepe.png`, and the path I get back is 'pepe.png'. I need the full path (i.e. `/Users/user/Downloads/pepe.png`). I'm trying to use this with mailgun via a nodejs app--but using this class isn't helping as much as I had hoped.

**Comment by Nohinn** [comment]
This 'issue' is not related to MaterializeCSS.

You cannot get the full path from a file input due to security concerns.

**Comment by Nxt3** [comment]
Then how are you supposed to upload a file with just that path?

**Comment by Nohinn** [comment]
On server side you will get the bytes and the filename 'pepe.png' to be able to save it to a path on the server.
You should check documentation, regarding file uploads, of the server side technology you use (PHP, ASP.NET, ...)
