### ISSUE TITLE
NOT FULLY OFFLINE ~

### ISSUE THREAD

**Issue by MerIgos** [Dogfalo/materialize#3268]
Maybe I'm just the one but, I thought that this docs are 100% offline and I figured it out when I transfer the files to my other computer. Can you download the online files, create a folder copy then paste it there and put it offline.? Anyway the docs, are so helpful for me. Thanks anyway ^_^

**Comment by acburst** [comment]
If you download our whole repo just open the index.html file locally and that's our docs
