### ISSUE TITLE
Unable to programmatically set focus on form input

### ISSUE THREAD

**Issue by Jesse-Breuer** [Dogfalo/materialize#3270]
Hello I need to set a text input field to get focus when I click on an element which contains it.
$('.editable').on("click", function(){
   $(this).find('input[type=text]').trigger('focus');
}

I would expect the input to get focus but it does not.
Looking at the materialze js, I can only find this::

    // Add active when element has focus
    $(document).on('focus', input_selector, function () {
      $(this).siblings('label, i').addClass('active');
    });

which doesnt look like it should interfere

**Comment by Nohinn** [comment]
Could you post your HTML?
Do you have, by any chance, any event handler for the focus/click where you do a preventDefault()?

Here you have a sample, a form with 'editable' css class that triggers the focus event on an input within. As you can see, I cannot reproduce the issue:
https://jsfiddle.net/La8qx3k9/

**Comment by Jesse-Breuer** [comment]
Here is an example.
https://jsfiddle.net/mdcums8t/2/
It is an "edit in place" application in which I can click on a table cell, and the text is replaced with a form field in which to edit it. Then it goes back to being regular text on blur.

What is happening now is that clicking in the cell opens the input and hides the text as expected. Then if I click outside of the input without first clicking into the input to give it focus, nothing happens. But If I click inside the input (giving it focus) and then outside in the rest of the table cell. It works as expected. Thus I am trying to automatically apply focus when making the input visible.

**Comment by Jesse-Breuer** [comment]
Thank you for your time in responding earlier NohInn, My issue was actually not related to Material, but to the need to set a timeout between showing a hidden element and giving it focus.
