### ISSUE TITLE
Initialization options are not applied in dropdown

### ISSUE THREAD

**Issue by josendf** [Dogfalo/materialize#3271]
The initialization options are not applied in dropdown:

[dropdown.js#L40](https://github.com/Dogfalo/materialize/blob/master/js/dropdown.js#L40)

`var options = $.extend({}, defaults, options);`

The intention is to merge the `options` variable from the outer scope, but the `options` variable from the inner scope is used, which is `undefined`.

Either the inner variable or the outer variable should be renamed, for example:

`var _options = $.extend({}, defaults, options);`

**Comment by suneelv** [comment]
Same issue for me too... the function parameter was changed from option to options and this results in always taking default options

**Comment by joaobarcia** [comment]
Same issue here

**Comment by joaobarcia** [comment]
Reverting to 0.97.6 to fix

**Comment by btopro** [comment]
#3482 same issue. Dropping var from it ensures the right one is used

**Comment by btopro** [comment]
this is fixed in master it appears

**Comment by btopro** [comment]
this is fixed in the latest 0.97.8 and should be closed
