### ISSUE TITLE
Materialize.updateTextFields is not defined on React + NWjs

### ISSUE THREAD

**Issue by GRiMe2D** [Dogfalo/materialize#3272]
I am currently creating standalone app using React.js and NWjs with this framework. 
Calling `Materialize.updateTextFields` from `componentDidMount` will fail as `$(document).ready()` is not called yet. 

Temporary solution is copy the code, and paste at global scope. 

Can you 'move-up' from `$(document).ready()`?

**Comment by fega** [comment]
As far as I understand it could be called whenever you want

I have almost no experience with React itself, but could you try with a little delay? I know that it should work without it, but give it a try

**Comment by fega** [comment]
Closed due inactivity, feel free to reopen it if it is still necessary.
