### ISSUE TITLE
Using placeholder in input disables the animation

### ISSUE THREAD

**Issue by wolfram77** [Dogfalo/materialize#3274]
I like the animation with input elements, and want to have it even if i have placeholder set for it.

``` html
<div class="row">
<div class="input-field col s12">
    <i class="material-icons prefix">account_circle</i>
    <label for="user-id">Username</label>
    <input id="user-id" placeholder="kailas77" type="text">
</div>
<div class="input-field col s12">
    <i class="material-icons prefix">heart</i>
    <label for="user-tags">Things you always wanted to do</label>
    <textarea id="user-tags" placeholder="organic-farming, swimming, camping" class="materialize-textarea"></textarea>
</div>
</div>
```

Using placeholder made it static, so i tried the following:

``` html
<div class="row">
<div class="input-field col s12">
    <i class="material-icons prefix">account_circle</i>
    <label for="user-id">Username</label>
    <input id="user-id" oplaceholder="kailas77" type="text">
</div>
<div class="input-field col s12">
    <i class="material-icons prefix">heart</i>
    <label for="user-tags">Things you always wanted to do</label>
    <textarea id="user-tags" oplaceholder="organic-farming, swimming, camping" class="materialize-textarea"></textarea>
</div>
</div>
```

``` js
var onInputFocus = function() {
    var e = $(this);
    e.attr('placeholder', e.attr('oplaceholder'));
};

var onInputBlur = function() {
    var e = $(this);
    e.attr('placeholder', null);
    if(!e.val()) $('label[for="'+e.attr('id')+'"]').removeClass('active');
};

var runInput = function() {
    $('input').focus(onInputFocus);
    $('input').blur(onInputBlur);
    $('textarea').focus(onInputFocus);
    $('textarea').blur(onInputBlur);
};
```

It would be great if you could make this a default feature of materialize.<br>
Thanks.

**Comment by wolfram77** [comment]
To apply the same to textarea as well, has to do the following:

```js
var runInput = function() {
	$('input').focus(onInputFocus);
	$('input').blur(onInputBlur);
	$('textarea').focus(onInputFocus);
	$('textarea').blur(onInputBlur);
};
```

**Comment by acburst** [comment]
I don't understand. The point of the animation is to use the label as the placeholder. If you have both then the animation no longer makes sense because they overlap? Or am I not understanding your problem correctly?

**Comment by wolfram77** [comment]
I have seen placeholder's being often used to provide extra information (examples) about a particular input, and label just gives a basic idea about. So it makes sense to display that extra information when user is ready to start typing.
ex: http://convert2mp3.net/en/index.php

I understand what you are saying. The label stays in place of placeholder, until input is focused, when it moves up to the label position with animation. I guess you did this so that the labels don't look to be associated with another input on the top (it would create confusion).

Using the same idea, we could keep the labels close to the input with hidden placeholder. The placeholder can be revealed (and the label moved up) when the input field is selected. It makes sense to display that extra information (placeholder) to be display when user is focused on that input, makes the form look neat, and also does not create confusion regarding which field associated with which input before we start typing (if placeholders are provided).

And thanks for responding, my first feature request in any repo :).
