### ISSUE TITLE
pre-filled date input does not update on Firefox

### ISSUE THREAD

**Issue by BenjaminHubert** [Dogfalo/materialize#3276]
On Chrome: 
![image](https://cloud.githubusercontent.com/assets/6542524/16170766/403933d2-355e-11e6-8d75-41b98944520a.png)

On Firefox: 
![image](https://cloud.githubusercontent.com/assets/6542524/16170748/caa7027a-355d-11e6-8f4b-cde879476e8b.png)

I tried to use Materialize.updateTextFields(); but it does not seem to help.

**Comment by younessadmi** [comment]
+1

**Comment by jmherazo** [comment]
+1

**Comment by imaia** [comment]
+1

**Comment by lddv** [comment]
@BenjaminHubert if you manually add class `active` to that field when it is populated, then you will get the behavior you want. I agree that `Materialize.updateTextFields()` should do the job, but applied the solution I mentioned in a project. It's kind of a hack but it works.

**Comment by Efot** [comment]
+1

**Comment by fega** [comment]
@BenjaminHubert @younessadmi @jmherazo @imaia @lddv @Efot Could someone check if this is still an issue?

**Comment by Dogfalo** [comment]
Closed due to lack of response
