### ISSUE TITLE
Search for tables

### ISSUE THREAD

**Issue by MrUnknownGamer** [Dogfalo/materialize#3277]
Hi,

I love materialize and think its great but one thing is missing from it that I would LOVE to see. I was wondering if you guys could add a built-in search feature for tables. Something like this http://jsfiddle.net/9hGym/293/

If you guys could do that, that would be GREAT because for the life of me, I can't get it to work with materialize.

**Comment by kirilow** [comment]
Use datatable jquery with material design.
Here is a simple q how i use datatable with Materialize.

![image](https://cloud.githubusercontent.com/assets/4599949/16175642/824947fe-35fd-11e6-9ba2-35f3e20c553d.png)

**Comment by endra89** [comment]
@kirilow can you give jsfindle or code epen example, im need it  too, thx.

**Comment by kirilow** [comment]
[https://datatables.net/examples/index](url)
[https://datatables.net/examples/styling/material.html](url)

**Comment by endra89** [comment]
@kirilow on your link : data table use MDL (material design lite) not Materialize, shuld i customize this link https://cdn.datatables.net/1.10.12/js/dataTables.material.min.js to materialize.css ?

**Comment by kirilow** [comment]
Just include all MDL file in your router and that is

**Comment by bassie1995** [comment]
Someone made dataTables use Materialize, so you don't have to add all MDL files for just this: http://codepen.io/azamatms/pen/ZGwOMM/.

I haven't tried it with newer versions, but it looks good for me.

**Comment by tomscholz** [comment]
Closing. Use this issue instead https://github.com/Dogfalo/materialize/issues/1327
