### ISSUE TITLE
100% height left sidebar

### ISSUE THREAD

**Issue by postaczech** [Dogfalo/materialize#3278]
I have left sidebar like this:

<div class="row">
        <div class="col s12 m5 l3">
            <section class="pink darken-1 left-panel">Left Sidebar</section>
        </div>
</div>

But I can't set the 100% height for this sidebar, it seems that row do problems. How can I fix this? I’m   trying to create a simple layout where there will be a sidebar on the left and the main content area on the right with the same 100% height, but the row blocked them.

**Comment by acburst** [comment]
Please post some code or some examples
