### ISSUE TITLE
Failed to decode downloaded font (Meteor with new package.js)

### ISSUE THREAD

**Issue by NitroBAY** [Dogfalo/materialize#3281]
#2217 is back since I installed 5afb6000 with the new package.js on meteor...

**Comment by NitroBAY** [comment]
By the way all the font are downloaded, is that normal ? In chromium based browser only woff2 should be downloaded, right ? 

![font](https://cloud.githubusercontent.com/assets/9869317/16196220/7c3a1414-36fd-11e6-9af0-abad81687767.PNG)

**Comment by cw4inctec** [comment]
+1  also have the decode issue with Meteor 1.4 and materialize:materialize~0.97.7 (using Chrome)
same as in issue #2217  
----
Failed to decode downloaded font: http://localhost:3000/packages/materialize_materialize/fonts/roboto/Roboto-Regular.woff2
OTS parsing error: invalid version tag
----

**Comment by keyscores** [comment]
What worked for me was adding this line to main.css

`@import url('https://fonts.googleapis.com/css?family=Roboto:100,400');
`
*Pay attention to the weights you need, like 100, 400 etc.

**Comment by Dogfalo** [comment]
Fixed by #4000
