### ISSUE TITLE
using material box for card images with multiple div

### ISSUE THREAD

**Issue by ivanlaharnar** [Dogfalo/materialize#3285]
Looks like class='materialboxed' doesnt work if you have a litle more divs on the card . here is my example: http://mink.si/materialize_test/ . If I click on image it doesnt open obove all content. 
I've seen the solutions like [here ](https://github.com/Dogfalo/materialize/issues/2091) and here []https://github.com/Dogfalo/materialize/commit/e39958fa2c133b650095163ecd3062f6f955ecfd(url) but none of this solutions doesnt workin my case.

Any suggestion?

**Comment by acburst** [comment]
Fixed card reveal bug in 7115621.

Materialbox is not compatible with waves. Remove the waves classes from your card-image and it should work with the fix above.
