### ISSUE TITLE
Align data-success to the right

### ISSUE THREAD

**Issue by fupuchu** [Dogfalo/materialize#3286]
Hi there, is it possible to shift data-error and data-success messages to the right of the label?

Currently it looks like this 
![screen shot 2016-06-21 at 12 43 21 pm](https://cloud.githubusercontent.com/assets/12230197/16218269/0eb73f6e-37ae-11e6-99e9-d2b90091cf4c.png)

Do I add a text-align: right here?

> textarea.materialize-textarea:focus.valid + label:after {
>   content: attr(data-success);
>   color: #4CAF50;
>   opacity: 1;
> }

**Comment by fega** [comment]
solved, also the position is accordingly with the material design patterns https://material.io/guidelines/patterns/errors.html
