### ISSUE TITLE
toggle switch

### ISSUE THREAD

**Issue by rajneeshojha** [Dogfalo/materialize#3289]
when toggle switch is in off status and if that toggle switch is inside a form no value received for toggle status.

suppose i want to put the toggle switch on a form ,lets say in a captcha setting section section of my form , so user can disable or enable captcha .
when switch is on and for is submited i will receive the value and update db marking enable_captcha as 1 
but if i toggle switch to off status and submit for there will not be any data for that off state and thus unable to mark enable_captcha to 0 in db.

am i doing something wrong ?

**Comment by kirilow** [comment]
toggle switch is a checkbox.
in PHP write something like this:
`if (isset($_POST['myCheckbox'])) {
  $checkBoxValue = "yes";
} else {
  $checkBoxValue = "no";
}`

**Comment by rajneeshojha** [comment]
what if i dont know the name of input? and i am looping in foreach($_POST) and saving every key in db, as the index will not be there in case of toggle being off,

**Comment by Dogfalo** [comment]
Try using `.val()` on the toggle.

**Comment by rajneeshojha** [comment]
really ? use .val() in PHP?  or you mean to say i make a submit hook and update then use.val on toggle and copy its value to another hidden input and then use that hidden input in post ? if you are saying about using second method then i must say it is not practical way

**Comment by mitar** [comment]
It seems toggle does not get updated. Value is `on` all the time, even if you turn it off. This is visible also on the demo site.

**Comment by mitar** [comment]
One should use `$('#switches input:checked')` to get its checked status.

**Comment by r-pluss** [comment]
If you are already using JQuery in your project, I find `$('#my-switch-id').prop('checked')` to be the most idiomatic way to get the value of a switch as a boolean.

**Comment by fega** [comment]
Closed due inactivity, feel free to reopen it if it is still necessary.
