### ISSUE TITLE
Materialize + Masonry: Overlapping occurring even with imagesLoaded js

### ISSUE THREAD

**Issue by kingIZZZY** [Dogfalo/materialize#3293]
http://dev.randompod.com

Trying to use Materialize with masonry as templated/exemplified here: https://github.com/Dogfalo/materialize/tree/master/templates/masonry-template.

Grid items are **overlapping**, despite running the [imagesLoaded](https://github.com/desandro/imagesloaded) javascript

View Source: http://dev.randompod.com/wp-content/themes/dev/js/app.js

**Comment by kingIZZZY** [comment]
Seems like the official preview is altogether not working either: http://materializecss.com/templates/masonry-template/preview.html

**Comment by acburst** [comment]
Hmm, I'm not sure why this is happening. The masonry is definitely working because if you resize the page the masonry kicks in. So what exactly is almComplete? If its loading content from ajax maybe its calling masonry too early before the content is in the DOM? Its hard to tell without working on the code directly.

**Comment by kingIZZZY** [comment]
Actually that's _precisely_ what almComplete is supposed to be; the callback invoked **after** content has finished loading via ajax. Thus the plugin's abbreviated prefix "alm" for [**A**jax **L**oad **M**ore Masonry Integration](https://connekthq.com/plugins/ajax-load-more/examples/masonry/)

Might [my issue thread reply at the ALM project](https://github.com/dcooney/wordpress-ajax-load-more/issues/114#issuecomment-227633013) be close enough to "working on the code directly" ?

**Comment by tomscholz** [comment]
Closed due inactivity. Feel free to reopen it, if it's still necessary.
