### ISSUE TITLE
navbar-fixed bug when using inside of container div

### ISSUE THREAD

**Issue by bluetea55z** [Dogfalo/materialize#3294]
When inside of a container div and adding the navbar-fixed wrapper div it causes the nav to overflow to the right side of the page.

**Comment by ruchern** [comment]
Same problem here on mobile. Desktop browser has no problem.

**Comment by GorgonsMaze** [comment]
+1

**Comment by antalexa** [comment]
I have the same issue and tried to resize height as suggested in the docs for navbar-fixed. I also tried pushpin but the navbar still overflows off the page

**Comment by Agentscreech** [comment]
Any resolution to this?  I cut and pasted the documentation and it did this bug on every resolution I've tried.

**Comment by Dogfalo** [comment]
You should be doing:
navbar-fixed > container > content

instead of 
container > navbar-fixed > content
