### ISSUE TITLE
Angulajs ngview content isn't rendered well

### ISSUE THREAD

**Issue by kvozon** [Dogfalo/materialize#3297]
Hello, i have a page with materialize and it works well, but when i load dynamic content with angular into ngview, the tabs isn't rendered, while they do in the main page. When i call $("ul.tabs").tabs() it fixes the problem. I found this solution in materialize documentation, but i wanted to ask, if there is another solution and if not, what other elements require a manual initialization? Thank you!

**Comment by fega** [comment]
Well, materialize doesn't provide ways to detect automatic js elements and initialize them,
Also, I guess that enforce something like that could create performance problem, so it's better that the programmers implement it by themselves.

**Comment by fega** [comment]
Posible solution #1928
