### ISSUE TITLE
Parallax not working when images src is not local?

### ISSUE THREAD

**Issue by 0alpha0** [Dogfalo/materialize#3298]
Tried using the parallax template on the website with lorempixel.com and it failed to apply the effect on the image.

**Comment by acburst** [comment]
Can you post your code? I just tried it locally and it works fine for me.

**Comment by 0alpha0** [comment]
Never mind, the image was huge so the effect didn't show clearly. An option to control the parallax speed or image offset per scroll would be immensely helpful.
