### ISSUE TITLE
dropdown in table header

### ISSUE THREAD

**Issue by italomaia** [Dogfalo/materialize#330]
Hi folks. Today I had the idea of putting a dropdow inside a table thead th in order to create a filter. Result is pretty sweet. Ok, the dropdow was not created to be put there, but hey, it works. 

So, whats my goal here: it works; it doesn't look pretty while working. What you guys thing about having it as a supported functionality for dropdown, with neat looks (table wise) and all?

**Comment by Dogfalo** [comment]
We don't want to be creating specific designs for dropdowns based on where they appear. Instead if there is a specific style you want. Add it in your own style.css.
