### ISSUE TITLE
Option For Showing Password (with Eye Material Icon)

### ISSUE THREAD

**Issue by TristanWiley** [Dogfalo/materialize#3300]
Similar to #1214 however. Feature suggestion to include a class that adds a "view password" inside of an input. Icon can be https://design.google.com/icons/#ic_remove_red_eye or another.

Basically a toggle to show password or hide password inside of the HTML input. The JS is simple, I just can't get the toggle inside the input.

**Comment by tomscholz** [comment]
Duplicate of https://github.com/Dogfalo/materialize/issues/1214
