### ISSUE TITLE
Calendar on window focus

### ISSUE THREAD

**Issue by edse83** [Dogfalo/materialize#3304]
Hi, I'm getting a strange behavior when using the calendar:

When selecting or opening the calendar input, it shows the calendar, if closed and if I minimize the window or change tabs and open the tab again (without having to click again) the calendar appears. 
http://d.pr/v/qdBY

This also happens on the demo site:
http://materializecss.com/forms.html

Any ideas on how to fix this?

**Comment by Dogfalo** [comment]
This is caused by the focus which opens the picker. 
Search through closed issues: https://github.com/Dogfalo/materialize/issues?q=is%3Aissue+picker+tab+is%3Aclosed
