### ISSUE TITLE
Scrollspy

### ISSUE THREAD

**Issue by landed1** [Dogfalo/materialize#3305]
Please tell us in the docs what is the originating library for this [https://github.com/thesmart]

I would like to know the event that I can listen for when my thing is in the viewport centre...

**Comment by acburst** [comment]
I'm confused. You just linked the originating library's author?

https://github.com/thesmart/jquery-scrollspy

**Comment by landed1** [comment]
I was trying to get to the original lib so I can inspect the code to try and see how to get the events I need.
As it looks like there is no event for centre in the screen just entering or leaving. Yes my mistake linking to the author.
