### ISSUE TITLE
How to edit tab's down color?

### ISSUE THREAD

**Issue by Heroata** [Dogfalo/materialize#3306]
![image](https://cloud.githubusercontent.com/assets/10375421/16326760/1617a944-39d2-11e6-840b-d06635b00b95.png)

In this picture I cant edit the pink lines.

**Comment by acburst** [comment]
If you are using Sass you can change the $tabs-underline-color variable in _variables.scss.

Otherwise you will have to add your own css to it. You can use the selector:
```
.tabs .indicator {
  background-color: #yourcolor;
}
```

**Comment by Heroata** [comment]
Thank you a lot!

25 Haz 2016 22:45 tarihinde "Alan Chang" <notifications@github.com> yazdı:
