### ISSUE TITLE
Slider overflow on mobile

### ISSUE THREAD

**Issue by tetpsy** [Dogfalo/materialize#3307]
I've noticed this weird effect when using touch to swipe on the default slider.

It almost overflows the page to the sides, like the content is loose, it moves around with my finger.

I would like the slider to be more rigid and not move so much on mobile, any ideas?

ps, doesn't show on chrome inspect mobile, only on actual iphone.

**Comment by humbertomn** [comment]
Hi @tetpsy , did you find a solution for this or ended up using a different plugin?

**Comment by tetpsy** [comment]
@humbertomn Hey man i actually ended up using mui.css, it might be more basic, but feels good. https://www.muicss.com/

**Comment by tetpsy** [comment]
@humbertomn maybe just use an external slider instead
