### ISSUE TITLE
[Modals] How to get rid of ugly scrollbar in modal and set it on modal's overlay instead?

### ISSUE THREAD

**Issue by wzup** [Dogfalo/materialize#3314]
Here is what default modal looks like if the content is large, it has ugly scrollbar:

> ![modals - materialize - google chrome 2016-06-26 13 13 32](https://cloud.githubusercontent.com/assets/3880497/16360714/85ad26ea-3ba2-11e6-8fc2-97a14cf8c153.png)

How may we get rid of modal scrollbar and set a scrollbar on modal's overlay instead? As an example, please check out Airbnb login or registration modals (see a screenshot below). Can we achieve the same behaviour without drastically/deeply recoding or changing modal's markup?

> ![vacation rentals homes apartments rooms for rent - airbnb - google chrome 2016-06-26 13 18 33](https://cloud.githubusercontent.com/assets/3880497/16360704/1f41b128-3ba2-11e6-8fa7-37fe30bd83b1.png)

**Comment by wzup** [comment]
Any feedback from developers??

**Comment by fega** [comment]
thanks @wzup
