### ISSUE TITLE
Display stays dark closing SideNav

### ISSUE THREAD

**Issue by Croghs** [Dogfalo/materialize#3317]
Hi, 
I used the SideNav for mobile devices, but if I close it with a click on a <a>, the sidenav closes but the display stays dark.

Just this as option activated:
`$('.button-collapse').sideNav({
      closeOnClick: true
    }
  );`

Why? And how can I fix it?

**Comment by Dogfalo** [comment]
Create a codepen with your code please. http://codepen.io/Dogfalo/pen/xbzPQV

**Comment by Croghs** [comment]
http://codepen.io/croghs/pen/wWgZyV This is just the code for the SideNav. If you need the full code just comment again please. (It's alot of code...)

**Comment by omt66** [comment]
I observed the same behavior. SideNav closes but the overlay stays on Chrome and IE. Firefox seems to be working OK.

**Comment by jegan97** [comment]
I am too facing the same issue :(

**Comment by rmallermartins** [comment]
Same issue here, even in Firefox. Seems like it's creating 2 overlays instead of one sometimes, so I have to click 2 times outside of the sideNav to exclude both of them.

**Comment by bobRafat** [comment]
I'm having the same issue here, any fix?

**Comment by jegan97** [comment]
My problem was  I included the materialize files two times..After removing one link and script , it is working fine.. :)

**Comment by fega** [comment]
Sadly the codepen was deleted.

Closed due inactivity, feel free to reopen it if it is still necessary, in that case please provide a new codepen.
