### ISSUE TITLE
Disable sideNav when click outside the sideNav

### ISSUE THREAD

**Issue by GhazanfarKhan** [Dogfalo/materialize#3320]
I donot want to close sideNav when clicking outside the sideNav. Is there any option like 
`{ dismissible: false }` in sideNavs just like modals?

**Comment by kcranky** [comment]
`$('.button-collapse').sideNav({
        closeOnClick: true
    });`

**Comment by GorgonsMaze** [comment]
+1 on this.

**Comment by GhazanfarKhan** [comment]
`$('.button-collapse').sideNav({
closeOnClick: true
});

I tried this but it closes by click overlay

**Comment by Dogfalo** [comment]
I don't think this is a large use case and doesn't promote good UX.
