### ISSUE TITLE
How i can get left align collections item?

### ISSUE THREAD

**Issue by evgenosiptsov** [Dogfalo/materialize#3322]
HI!

Is there any way for create this?
![components_cards8](https://cloud.githubusercontent.com/assets/17506504/16380387/64fa8ad6-3c7f-11e6-9b8f-9120e3a5626f.png)

**Comment by oscarmartins** [comment]
I CAN DO WHEN THESE WILLING TO PAY?

ÓSCAR MARTINS
PROGRAMADOR
Telemóvel.: +351 913859014


2016-06-27 13:54 GMT+01:00 evgenosiptsov <notifications@github.com>:

**Comment by evgenosiptsov** [comment]
Haha, thanks, I can do it myself for free) But i'm interesting complex solution via Google Materfial Design.

**Comment by oscarmartins** [comment]
Very well :) Yes it seems to me a good idea that you use Google Material
Design: P

ÓSCAR MARTINS
PROGRAMADOR
Telemóvel.: +351 913859014


2016-06-27 15:11 GMT+01:00 evgenosiptsov <notifications@github.com>:

**Comment by acburst** [comment]
Can you not just mark an image as secondary-content? We use the secondary-content class to pull items to the right of a collection

**Comment by kmmbvnr** [comment]
Thanks @acburst i didn't see that materializecss have `.secondary-content` class

@evgenosiptsov here is the code pen demonstrates collection list with images on the right - http://codepen.io/kmmbvnr/pen/xOpoBX


![a pen by mikhail podgurskiy](https://cloud.githubusercontent.com/assets/282529/16898668/9d7eab96-4c04-11e6-904b-b30fb49062cc.png)

**Comment by fega** [comment]
Closed due inactivity, feel free to reopen it if it is still necessary.
