### ISSUE TITLE
Submitting form after fixing invalid input

### ISSUE THREAD

**Issue by yaron-e** [Dogfalo/materialize#3323]
When submitting a form that has an input that is required and has a pattern check and the form attempted to be submitted with a invalid input, the form wont submit and show a error message with the required format. The bug happens after you enter a valid input, the input stays red (invalid). The only way to submit the form is to reload the page and reenter everything. 

```
<input required type="password" name="password" id="password" class="validate"  pattern="(?=^.{6,}$)((?=.*\d)|(?=.*\W+))(?![.\n])(?=.*[A-Z])(?=.*[a-z]).*$" oninvalid="Password must contain at least 1 uppercase, 1 lowercase, 1 number and be a minimum of 6 characters in length.">
<label for="password" data-error="" data-success="" class="active">Password<label>
```

**Comment by fega** [comment]
@yaron-e did you tried with `Materialize.updateTextFields();`? 
Also please provide a way to reproduce it. like a [codepen](https://codepen.io/fega/pen/BWeZaG) 

Closed due inactivity, feel free to reopen it if it is still necessary.
