### ISSUE TITLE
[Tooltips] Toolips do not work

### ISSUE THREAD

**Issue by wzup** [Dogfalo/materialize#3324]
1) Tooltips just do not work with initialization. Your documentation is miserable about them. How to control them?

This doesn't work!
```
<input id="inpId" class="tooltipped" data-validate="1" type="text" name="inpName" placeholder="---" >

$("#inpId.tooltipped").tooltip({delay: 50, position: 'left', tooltip: 'Not valid'});
```

I want manually start a tooltip. How can I do it? How to pass text and params?

**Comment by Tempus35** [comment]
This is what I am working on myself, it seems (from looking at the code) that position and text are not able to be set programmatically. There is a PR for position but not text. I am trying to see if I can add it myself.

**Comment by Tempus35** [comment]
I just made a PR where I added in this ability #3326

**Comment by acburst** [comment]
Merged

**Comment by wzup** [comment]
What is PR?

**Comment by wzup** [comment]
How do you do all this stuff? Commits, changes, merge your personal code with existing repos? I know Git but use it only on my local dev machine. And how to bring changes in GitHub repos?
