### ISSUE TITLE
Valign-wrapper on Mobile

### ISSUE THREAD

**Issue by Luizgpp** [Dogfalo/materialize#3327]
Hello, i'm using valign-wraper Helper to align itens on desktop, but when change to mobile still align that itens and responsive grid don't work.

See here http://codepen.io/anon/pen/dXvpjK

If i remove valign-wrapper the responsive works fine.
But if i don't remove - valign still forcing objects side by side. 

Its a bug?

Sorry my english.

**Comment by alexsales** [comment]
Checkout the comments in issue #2997. A possible workaround that doesn't require you to duplicate a bunch of code is to just use a media query to target small screens (<= 600px) and change the css display to inherit [https://plnkr.co/ByUOUA92GHTelskSvXcs](https://plnkr.co/ByUOUA92GHTelskSvXcs):

`
 @media only screen and (max-width: 600px) {
   .row.valign-wrapper {
     display: inherit;
   }
 } 
`
