### ISSUE TITLE
FloatingActionButton Anchored On Card?

### ISSUE THREAD

**Issue by TristanWiley** [Dogfalo/materialize#3328]
Is it possible to anchor a FloatingActionButton on the corner of the card with the current code?  

For example, see attached image. Similar to in Android development.

![Anchored example](https://cloud.githubusercontent.com/assets/2747793/16402515/ef107dee-3cba-11e6-97f6-69707c8ac625.png)

**Comment by fega** [comment]
It looks implemented in the current version.

http://materializecss.com/cards.html

**Comment by tomscholz** [comment]
This was added in version v0.98.0 :)
