### ISSUE TITLE
Two Floating Labels.

### ISSUE THREAD

**Issue by danphilip** [Dogfalo/materialize#3331]
![aaaaa](https://cloud.githubusercontent.com/assets/16207149/16413422/7d5a379a-3d4f-11e6-823a-c10d08d6d321.png)

Can I add two floating labels to a single input field so that one label is aligned to the left of the field and the other to the right.
If this was already asked, please provide a reference. Thanks in advance.

**Comment by Dogfalo** [comment]
You can achieve this through some CSS,
 
Take a look at this simple HTML example of the label.
```
<label for="password" class=""><span>Password</span><span style="
    text-align: right;
    position: absolute;
    right: 23px;
">Required</span></label>
```
