### ISSUE TITLE
Docs Carousel Example Currently Broken

### ISSUE THREAD

**Issue by komali2** [Dogfalo/materialize#3332]
On the [docs site](http://materializecss.com/media.html#one!), the carousel example shows broken image links. 

![screenshot 21](https://cloud.githubusercontent.com/assets/8533113/16434364/50225b82-3d44-11e6-8c0b-d6bd72223acc.png)

![screenshot 22](https://cloud.githubusercontent.com/assets/8533113/16434452/bf559172-3d44-11e6-9191-feaf11c0df7c.png)

Chrome version Version 51.0.2704.103 m

Windows 10 pro Insider Preview v 1511
64bit
Surface Pro 3

**Comment by acburst** [comment]
These are links to an external site called lorempixel.com
Nothing we can do about it. It probably was down for a small period of time.

**Comment by Dargmuesli** [comment]
The site is still (or again) down. Maybe switch to another image hoster?
