### ISSUE TITLE
Add function a fixed-action-btn

### ISSUE THREAD

**Issue by arg3ni5** [Dogfalo/materialize#3333]
I use this function, in order to keep active only 1 fixed-action-btn.
if I touch another, first turn off everything that this active and then active the new one

var caf=function(){var c=document.querySelectorAll(".fixed-action-btn.active");[].forEach.call(c,function(c){c.classList.remove("active")})};    

![captura de pantalla 2016-06-29 01 03 06](https://cloud.githubusercontent.com/assets/12776890/16443501/7ec635a6-3d96-11e6-9b68-d5dee083527e.png)

**Comment by acburst** [comment]
Can you post some sample code?
