### ISSUE TITLE
Option to reveal SideNav on window width larger than 992px

### ISSUE THREAD

**Issue by seanzzz** [Dogfalo/materialize#3335]
Currently a fixed sideNav shows up when the window width is larger than 992px. However, given a 300px-width sideNav, if the sideNav shows up at 992px, it only leaves 692px for rest of the window, which is fairly narrow, despite the display of the elements are following the 'large' window rules. I wonder if there is any option to modify the threshold so that a fixed sideNav only shows up when the window width is large than, for example, 1292px.

**Comment by fega** [comment]
Maybe
```
@media only screen and (max-width: 1292px){
 .side-nav.fixed {
    -webkit-transform: translateX(-105%);
    transform: translateX(-105%);
  }
}
```
Closed due inactivity, feel free to reopen it if it is still necessary.
