### ISSUE TITLE
Fixed-navbar logo gets pulled right and stuck when using slider on mobile

### ISSUE THREAD

**Issue by GorgonsMaze** [Dogfalo/materialize#3336]
Helping a fellow user @andersonsouzars from chat post their issue.

When using a fixed-navbar with a slider below on **mobile**, the center "logo" gets pulled to the right and stuck when user scroll-drags to the right with the actual slider image, not the indicator buttons. Once it's stuck it won't move back when trying to scroll the opposite way. This only happens on mobile, as a few people tried testing the problem with chrome dev tools, but it doesn't let you scroll drag the images.

Image: https://files.gitter.im/Dogfalo/materialize/MTdB/blob

Code: [here](http://codepen.io/zzzian/pen/oLvWYv)

Thanks!

**Comment by humbertomn** [comment]
+1 this is happening on iOS/safari for me.

**Comment by fega** [comment]
I'm unable to reproduce it :/ 
Could you check if this is still an issue with the last version?

Closed due inactivity, feel free to reopen it if it is still necessary.

**Comment by tomscholz** [comment]
Works with the latest version: https://codepen.io/anon/pen/gmNRZq
