### ISSUE TITLE
Parallax on Firefox Developer Edition

### ISSUE THREAD

**Issue by Luizgpp** [Dogfalo/materialize#3337]
I'm getting this message on Firefox Developer Edition 49.0a2 (2016-06-29)

> This site appears to use a scroll-linked positioning effect. This may not work well with asynchronous panning; see https://developer.mozilla.org/docs/Mozilla/Performance/ScrollLinkedEffects for further details and to join the discussion on related tools and features!

Any fix?

Thanks!

**Comment by Dogfalo** [comment]
Almost all parallax effects rely on JS with a scroll handler. I don't see this a problem that needs to be fixed.
