### ISSUE TITLE
Fonst error GET

### ISSUE THREAD

**Issue by darwindlrd** [Dogfalo/materialize#3345]
Why do I receive this error?
Download files again Materializecss but still does not work.

![captura de pantalla 12](https://cloud.githubusercontent.com/assets/20263111/16543832/37cf5fd2-40b2-11e6-9eaa-765cdb1c5fd5.png)

**Comment by Dogfalo** [comment]
Make sure you have your font files in the correct place and that you are hosting them as well on production.
