### ISSUE TITLE
Scrollspy UI rout 

### ISSUE THREAD

**Issue by oussamaABID** [Dogfalo/materialize#3346]
Hey 
i use angular and materialize 

`config(function routeConfig($stateProvider, $urlRouterProvider) {
        // config rout
        $urlRouterProvider.when('devices','/devices');
        $urlRouterProvider.when('home', '/home');
        $urlRouterProvider.otherwise( '/home' );})`
### ui main

`<div class="fixed-action-btn horizontal" style="bottom: 45px; right: 24px;">
    <a class="btn-floating btn-large red">
      <i class="large material-icons">mode_edit</i>
    </a>
    <ul>
      <li><a class="btn-floating red" ui-sref="devices"><i class="material-icons">insert_chart</i></a></li>
      <li><a class="btn-floating yellow darken-1" ui-sref="home"><i class="material-icons">format_quote</i></a></li>
    </ul>
  </div>`
### ui devices

`<h1>devices</h1>`
### ui home

`        <div class="row">

```
<div class="col hide-on-small-only m3 l2" style="position: fixed; right:10px;" >
  <ul class="section table-of-contents">
      <li ng-repeat="model in homeCtrl.networks"><a href="#{{model.name}}">{{model.name}}</a></li>
  </ul>

</div>

           <div class="col s12 m9 l10">
  <div ng-repeat="model in homeCtrl.networks" id="{{model.name}}" class="section scrollspy">
```

...`

in first loading ui scrollspy working OK
but when i go home > to devices and i back 
scrollspy  not working 
when i reload  it's working again

**Comment by fega** [comment]
Closed due inactivity, feel free to reopen it if it is still necessary.
