### ISSUE TITLE
Toggle buttons

### ISSUE THREAD

**Issue by Asido** [Dogfalo/materialize#3347]
I am wondering if there is anything built-in to create toggle or group buttons. If not, would be a great addition.

[Material design specs](https://material.google.com/components/buttons.html#buttons-toggle-buttons)

**Comment by acburst** [comment]
This is something that would definitely be cool to add. There's still a lot on my plate right now and its holiday season for me so I would be open to a Pull Request if anyone wants to take a crack at styling this with checkboxes or radio buttons. 

Otherwise I can look into this when I can.

**Comment by Dogfalo** [comment]
While this would be nice to have, not sure if it would be widely used.
