### ISSUE TITLE
Iframe in modal does not show up because of "will-change"

### ISSUE THREAD

**Issue by actuallymentor** [Dogfalo/materialize#3348]
When putting an iframe in a modal the full screen option does not work (both in iframe and other video players).

The only way to disable this is to add:

`.modal {    will-change: initial;     }`

Is there any reason that is in there in the first place?

**Comment by acburst** [comment]
Can you post some sample code?

**Comment by actuallymentor** [comment]
Any iframe in a modal popup.

**Comment by ManuelRiveraC** [comment]
That's true. I'm using a video.js player on a modal. When I'm going fullscreen video I got this issue too.
https://gmkr.io/s/57a8ba2b3537bedb053a29d4/0
Changing "will-change" only for "top" resolve the problem.

Codepen (very basic sample but I hope it helps!): 
http://s.codepen.io/ManuelRiveraC/debug/rLQzPq

**Comment by fega** [comment]
@ManuelRiveraC I cannot see the code pen

Could you check if this is still an issue with the latest version?

Closed due inactivity, feel free to reopen it if it is still necessary.
