### ISSUE TITLE
Strange issue with toasts in firefox

### ISSUE THREAD

**Issue by 0x4321** [Dogfalo/materialize#3349]
Hi,
I changed my toasts so that they are always at the bottom just like when using the mobile layout. Hower in firefox they fade in normally and then slip down again so you can't see them completely.
In Chrome it works just fine. It's not only on my webpage, it happens on the example page for toasts too when viewing it in mobile layout.
I have created two gifs to show what I mean.
Chrome:
![gif](https://cloud.githubusercontent.com/assets/17899843/16585064/479a01c4-42bf-11e6-8970-1d401a8c15ca.gif)

Firefox:
![gif](https://cloud.githubusercontent.com/assets/17899843/16585077/5c86d706-42bf-11e6-8697-56bf64e64c66.gif)

How can I resolve this?

**Comment by anantoghosh** [comment]
hmm this should be a bug, a very strange bug
Firefox on 'Medium' screen size, the toast fades in correct position first, then snaps down a little.
Here, @0x4321 added `bottom: 0, width: 100%` properties so its snaps down out of view.

I can reproduce this on
'Medium' size display
Firefox 48.0b5
Windows 10 x64

On mobile and desktop screen size, it works fine.
Interestingly, it does not happen on jsfiddle https://jsfiddle.net/anantoghosh/6Lbmrzh7/2/
but happens on http://materializecss.com/dialogs.html

@0x4321 can you try it out with different jquery versions

**Comment by anantoghosh** [comment]
![1](https://cloud.githubusercontent.com/assets/12339068/16692818/1e03a714-4550-11e6-85a6-0a49bf9b79c4.png)
It looks like toast container is collapsing.
Removing `float: left` from the `.toast` class fixes the problem. I don't know if the `float:left` is required some place else.
I think Firefox is misbehaving with the combination of display, float and position properties that have been used.

**Comment by anantoghosh** [comment]
Yup, `.toast-container` is collapsing on both 'medium' and 'desktop' screen size due to `.toast` having float property. Nothing happens visually for 'desktop'.
Another thing to note is that if I pause js execution at the collapsed state then resize firefox, it fixes itself.
This definitely has to be a Firefox bug, incorrectly calculating the size of child element.
As a workaround try
```css
.toast {
  float: none
}
```
It does not seem like the float property was necessary on `.toast` anyway.

**Comment by acburst** [comment]
I can no longer reproduce this on the latest firefox. Feel free to reopen if you can reproduce with a codepen
