### ISSUE TITLE
transplant to my own css

### ISSUE THREAD

**Issue by fanyer** [Dogfalo/materialize#3352]
I just want to transplant the datepicker component, can I import the scss and js of datepicker and then compile my own sass, it seems not smoonth. Or are there any interfaces UserGuide or Docs to extend your materilize framwork?

**Comment by Dogfalo** [comment]
If you want to just take the datepicker component, you just have to define the variables that exist in the datepicker scss file. The datepicker exists as a very separate component as it is pickadate.js
