### ISSUE TITLE
Datepicker not passing information through it.

### ISSUE THREAD

**Issue by shawnmfarnum** [Dogfalo/materialize#3356]
datepicker won't pass information through it. if I put it back to the default date className it passes. the second I put datepicker in there and start using the Materialize datepicker only those datepicker fields start not passing the data along..... Any thoughts?    

![bitmap](https://cloud.githubusercontent.com/assets/2795471/16665672/af358014-4441-11e6-8bcf-68550cd40b74.png)

**Comment by Dogfalo** [comment]
Seems like this could be fixed by using: http://amsul.ca/pickadate.js/api/#method-set
