### ISSUE TITLE
FIXED but need response: Collapsible Bug

### ISSUE THREAD

**Issue by lordsacha** [Dogfalo/materialize#3360]
When entering iframe in a part of collapsible, all collapsible after the iframe, even in different dive or collapsible will be hidden. If I enter iframe at third of collapsibel, second and first still show up. How can I put iframe in everysingle body collapsible :worried:. paragraph tags worked fine, though, just the iframe tag that breaks. http://pastebin.com/fuiAd8iu

**Comment by lordsacha** [comment]
fixed. iframe somehow needs to be formatted like <iframe src...></iframe> instead of <iframe src... />

**Comment by acburst** [comment]
I believe the correct markup for an iframe requires an ending tag.
