### ISSUE TITLE
Slider quick left-right swipe bug

### ISSUE THREAD

**Issue by larsvansche** [Dogfalo/materialize#3362]
When I use the slider and quickly swipe left and then right, the first image is still visible on the left of the slider, the second image has disappeared (which is supposed to happen), and the slider itself is empty. It happens on Chrome Mobile mode (the developers tool), on Safari on iPhone (I'm running the newest iOS as of July 11th) and on the Google Chrome App for iPhone, so it's probably not device-bound or browser-bound. 

See the image below for an example. The bug works both ways (with the first image staying on the right). 

![knipsel 11-07-2016](https://cloud.githubusercontent.com/assets/16673968/16722800/5cd187fe-4749-11e6-93f2-aa0e99be581d.JPG)

**Comment by humbertomn** [comment]
+1 I also get this

**Comment by bigggge** [comment]
+1 
![](http://7xq3d5.com1.z0.glb.clouddn.com/IMG_3412.PNG)

**Comment by fega** [comment]
@larsvansche @humbertomn Could someone check if this is an issue in the latest version? thanks

**Comment by tomscholz** [comment]
Closed due inactivity. Feel free to reopen it, if it's still necessary.
