### ISSUE TITLE
carousel vertical offset

### ISSUE THREAD

**Issue by cunneen** [Dogfalo/materialize#3363]
The carousel reserves a lot of space above it. This makes it much less useful on mobile. It can be seen on the [materialize site](http://materializecss.com/media.html) ; note the gap between the carousel and the text above it.

Here is what it looks like on an iphone.

![screen shot 2016-07-11 at 4 52 33 pm](https://cloud.githubusercontent.com/assets/1751645/16725058/1abe944e-4788-11e6-9f95-cdbec035cf9e.png)

**Comment by AbdullahDahmash** [comment]
+1

**Comment by tejovanthn** [comment]
Any update on this?

**Comment by acburst** [comment]
You can add your own css styles to carousel and carousel-item. These are just the default styles
