### ISSUE TITLE
corners of tooltips which are cut

### ISSUE THREAD

**Issue by Airmanbzh** [Dogfalo/materialize#3365]
Hello,

I've got an issue with tooltips. It seems that when you use html content and the height is bigger than the width, corners of the tooltip are cut.

Here you can find an example of code : https://fiddle.jshell.net/hcy8btaa/1/

**Comment by acburst** [comment]
I cleaned up our tooltip calculation in b9e279b.

This will be public in our next release, but if you dont wan't to wait you can download our master branch here on github.
