### ISSUE TITLE
Slider suggested method

### ISSUE THREAD

**Issue by landed1** [Dogfalo/materialize#3366]
To make the slider responsive I find that I need to set the height of the slider dynamically. Use for example the resize or orientation change and the slider wont resize properly for mobile. You can try to set this as in the height property at creation but I feel it made it glitchy for some reason.

**Comment by fega** [comment]
Maybe this is fixed in the current version.

Here I couldn't see any issues about the responsive behavior
http://materializecss.com/fullscreen-slider-demo.html
http://materializecss.com/media.html
