### ISSUE TITLE
Can MATERIALIZE work using angularJS?

### ISSUE THREAD

**Issue by falinsin** [Dogfalo/materialize#3367]
Is there an extra module JS so we can use MATERIALIZE in angularJS?

Or even a version of materialize for angularJS.

thanks in advance

**Comment by binarybaba** [comment]
It can sure work using angular. I'm building a website for my company.. Working just fine uptil now..

**Comment by Saiberbest** [comment]
For angularJS better choice is https://material.angularjs.org/.

**Comment by Dogfalo** [comment]
We do not support Angular officially, so there may be some problems. There are some 3rd party repos that try to facilitate working with Materialize in Angular. I have not tested it however. https://github.com/InfomediaLtd/angular2-materialize
