### ISSUE TITLE
Enhancement: Alert Design

### ISSUE THREAD

**Issue by ModdyLP** [Dogfalo/materialize#3370]
Hello 

can you add some alert dialog design? I would like a Alert dialog that is on the page shown and not as toast or popup. Is there a way to implement this?

Best Regards
ModdyLP

**Comment by kmmbvnr** [comment]
Do you mean modal dialog? http://materializecss.com/modals.html#!

**Comment by ModdyLP** [comment]
No I mean the same as a Modal Dialog but not as Popup. I think it would look nice if you have a a quarder like the cards and then a symbol for warning or error.

**Comment by kmmbvnr** [comment]
Should it be in library? It's pretty easy to implement it

http://codepen.io/kmmbvnr/pen/pbppLW

![a pen by mikhail podgurskiy](https://cloud.githubusercontent.com/assets/282529/16872896/ad927bb0-4ab1-11e6-9a7e-7cc0dbb457c5.png)

**Comment by ModdyLP** [comment]
Oh that look good but without the Buttons it would be better. But for now thank you very much for your help.

**Comment by Dogfalo** [comment]
What is the difference between this and a modal?
