### ISSUE TITLE
Card Reveal component turns white on img drag.

### ISSUE THREAD

**Issue by JeremieBastienMCQ** [Dogfalo/materialize#3372]
This bug is witnessable directly on [the materialize official website.](http://materializecss.com/cards.html)

Basically if you drag the image and drag it in the image. After a few times it will dissappear. See gif below for example. Also to get the image back you hover in and out over the image.

![bug](https://cloud.githubusercontent.com/assets/12067597/16850790/ae244d44-49ce-11e6-8d38-b729a74f3cbf.gif)

**Comment by tomscholz** [comment]
This is fixed in `master`
