### ISSUE TITLE
Icons Not Showing in Materialize 0.97.6 using Meteor App

### ISSUE THREAD

**Issue by Digital-Thor** [Dogfalo/materialize#3373]
I tested my Meteor app in Chrome, FireFox, IE and Safari.  All browsers don't show Materialize icons anymore.  I've forced the Materialize version back to 0.97.5 and then the icons show properly again.  When I use Materialize 0.97.6, the icons disappear and IE console reports:

> CSS3111: @font-face encountered unknown error. File: Roboto-Thin.eot
> CSS3111: @font-face encountered unknown error. File: Roboto-Medium.eot
> CSS3111: @font-face encountered unknown error. File: Roboto-Light.eot
> CSS3111: @font-face encountered unknown error. File: Roboto-Regular.eot
> CSS3111: @font-face encountered unknown error. File: Roboto-Bold.eot

Other consoles don't report errors, but it I don't think the IE errors are relevant since the same errors occur when the icons show properly in Materialize version 0.97.5.

I'm using Meteor 1.3.4.1.  The rest of the packages are:

> accounts-base@1.2.8
> accounts-password@1.1.11
> accounts-ui@1.1.9
> accounts-ui-unstyled@1.1.12
> allow-deny@1.0.5
> autoupdate@1.2.10
> babel-compiler@6.8.3
> babel-runtime@0.1.9_1
> base64@1.0.9
> binary-heap@1.0.9
> blaze@2.1.8
> blaze-html-templates@1.0.4
> blaze-tools@1.0.9
> boilerplate-generator@1.0.9
> browser-policy-common@1.0.10
> browser-policy-framing@1.0.11
> caching-compiler@1.0.5_1
> caching-html-compiler@1.0.6
> callback-hook@1.0.9
> check@1.2.3
> coffeescript@1.1.2_1
> ddp@1.2.5
> ddp-client@1.2.8_1
> ddp-common@1.2.6
> ddp-rate-limiter@1.0.5
> ddp-server@1.2.8_1
> deps@1.0.12
> diff-sequence@1.0.6
> ecmascript@0.4.6_1
> ecmascript-runtime@0.2.11_1
> ejson@1.0.12
> email@1.0.14_1
> fastclick@1.0.12
> geojson-utils@1.0.9
> hot-code-push@1.0.4
> html-tools@1.0.10
> htmljs@1.0.10
> http@1.1.7
> id-map@1.0.8
> iron:controller@1.0.12
> iron:core@1.0.11
> iron:dynamic-template@1.0.12
> iron:layout@1.0.12
> iron:location@1.0.11
> iron:middleware-stack@1.1.0
> iron:router@1.0.13
> iron:url@1.0.11
> jquery@1.11.9
> launch-screen@1.0.12
> less@2.6.3_1
> livedata@1.0.18
> localstorage@1.0.11
> logging@1.0.13_1
> materialize:materialize@0.97.5
> meteor@1.1.15_1
> meteor-base@1.0.4
> meteor-platform@1.2.6
> minifier-css@1.1.12_1
> minifier-js@1.1.12_1
> minimongo@1.0.17
> mizzao:timesync@0.4.0
> mizzao:user-status@0.6.6
> mobile-experience@1.0.4
> mobile-status-bar@1.0.12
> modules@0.6.4
> modules-runtime@0.6.4_1
> momentjs:moment@2.14.1
> mongo@1.1.9_1
> mongo-id@1.0.5
> npm-bcrypt@0.8.7
> npm-mongo@1.4.44_1
> observe-sequence@1.0.12
> okgrow:router-autoscroll@0.1.8
> ongoworks:google-spreadsheets@0.5.1
> ordered-dict@1.0.8
> ovcharik:favico@0.3.7
> perak:mqtt-collection@1.0.4
> percolate:synced-cron@1.3.2
> promise@0.7.2_1
> rafaelhdr:google-charts@0.0.2
> random@1.0.10
> rate-limit@1.0.5
> reactive-dict@1.1.8
> reactive-var@1.0.10
> reload@1.1.10
> retry@1.0.8
> risul:moment-timezone@0.5.0_5
> routepolicy@1.0.11
> service-configuration@1.0.10
> session@1.1.6
> sha@1.0.8
> spacebars@1.0.12
> spacebars-compiler@1.0.12
> srp@1.0.9
> standard-app-packages@1.0.9
> standard-minifier-css@1.0.7_1
> standard-minifier-js@1.0.7_1
> templating@1.1.12_1
> templating-tools@1.0.4
> tracker@1.0.14
> ui@1.0.11
> underscore@1.0.9
> url@1.0.10
> webapp@1.2.9_1
> webapp-hashing@1.0.9
>

**Comment by kcranky** [comment]
Have you got

<link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">

In your <head> tag?

**Comment by Digital-Thor** [comment]
Thanks.  Not sure if text pasted correctly in your response.  Or is your response missing something?

**Comment by kcranky** [comment]
I have edited it, initially nothing was showing. Should be fine now

**Comment by Digital-Thor** [comment]
Yes it's there, but I didn't realize that the mark-up syntax changed in the latest release from:

`<i class="mdi-action-star-rate"></i>` to
`<i class="material-icons">star</i>`

I've changed my mark-up and all is working now.  Thanks.
