### ISSUE TITLE
Form is not responsive

### ISSUE THREAD

**Issue by Gurdeep001** [Dogfalo/materialize#3375]
Form are not responsive while we switch larger device to small device.
here is my code,
http://codepen.io/Gurdeep001/pen/groXkE

and on this link  http://materializecss.com/forms.html  is also not responsive

@sahilbabbar

**Comment by kmmbvnr** [comment]
The materializecss grid expects that each `.col` should be inside `.row`.

Check this sample - http://codepen.io/kmmbvnr/pen/pbppyR I've added `<div class='row'>` around your form

**Comment by kirilow** [comment]
Add name Attribute in input field

**Comment by acburst** [comment]
@kmmbvnr is correct
