### ISSUE TITLE
z-depth-1 is not the right style

### ISSUE THREAD

**Issue by SirMaxime** [Dogfalo/materialize#3378]
The z-depth-1 class doesn't have the right shadows. Google's Material Design uses something more like 
`box-shadow: 0 1px 3px rgba(0,0,0,0.12), 0 1px 2px rgba(0,0,0,0.24);`
for cards. This should be the box shadow for the  z-depth-1 class

**Comment by kmmbvnr** [comment]
Here is 3d option - how is expandjs made shadows:

https://github.com/expandjs/mat-shadow/blob/master/mat-shadow.html

**Comment by Kail0** [comment]
```css
0 1px 4px 0 rgba(0,0,0,0.14)``` is on G+ site

**Comment by Dogfalo** [comment]
There is no "right shadow". you'll see that at google every material framework they make and all their apps have a different definition of z-depth-1. 

However, our shadows still looked out of date and I have updated them to look similar to Polymer's 5db6c8a
