### ISSUE TITLE
Responsive table and Dropdown

### ISSUE THREAD

**Issue by vuquangtam** [Dogfalo/materialize#3380]
When i use dropdown button in responsive-table. the posion of drop down list is not correct (it will not correct when using horizontal scroll, the offset is the same as horizontal scroll). Anybody have a solution for this issue ? Thank you :)
Adding example : https://jsfiddle.net/vuquangtam/ufa8gtzz/3/

**Comment by acburst** [comment]
Can you post a code example of this problem?

**Comment by vuquangtam** [comment]
https://jsfiddle.net/vuquangtam/ufa8gtzz/3/. when scroll the horizontal bar, the dropdown list position isnt corrent :)

**Comment by darckyn** [comment]
There is a similar error in the tabs structure too. 
:(

**Comment by vuquangtam** [comment]
the error offset of dropdown list is the same as the offset of horizontal scrollbar.

**Comment by vuquangtam** [comment]
Hope someone can fix it. Try days but no luck :(

**Comment by acburst** [comment]
Fixed in d7ab90e.

You can get it now if you download the latest release, or wait for an official release that is coming soon!

**Comment by vuquangtam** [comment]
I've just download the lastest and it still has a problem with responsive-table.

**Comment by gpressutto5** [comment]
I've just download the lastest and it still has a problem with responsive-table.
