### ISSUE TITLE
Opening/Closing materialize accordion programatically

### ISSUE THREAD

**Issue by kurtaking** [Dogfalo/materialize#3384]
I see in Materialize's documentation that there are several jQuery methods to open/close the sidebar, modal, etc, but I can't find anything about the accordions.

Is there a way to programmatically open/close the accordion when I user clicks a button?

Modal Example:
$('#modal1').openModal();
$('#modal1').closeModal();

What I need:
$('#li-id').openAccordion();
$('#li-id').closeAccordion();

**Comment by chi-bd** [comment]
Try this.
```javascript
(function ($) {
  function _accordion(flag) {
    var $this = $(this);
    if ($this.hasClass('active') == flag) return;
    
    $(this).children('.collapsible-header').trigger('click');
  }
  $.fn.openAccordion = function() {
    _accordion.call(this, true);
  }
  $.fn.closeAccordion = function() {
    _accordion.call(this, false);
  }
}( jQuery ));
```
```javascript
$('#accordion li:nth-child(1)').openAccordion();
$('#accordion li:nth-child(1)').closeAccordion();
```

**Comment by kurtaking** [comment]
Thank you! Sorry it took me a while to respond. I was out of town.
