### ISSUE TITLE
Dropdown not properly horizontally aligned

### ISSUE THREAD

**Issue by vaindil** [Dogfalo/materialize#3385]
I'm attempting to put a dropdown in my navbar, but it doesn't properly align horizontally. [Here's a fiddle.](https://jsfiddle.net/0g2eu3dy/2/) Not sure if I'm doing something wrong or if this is a bug.

**Comment by fega** [comment]
Well, I guess that this button was not designed to be used as a dropdown activator

a quick workaround could be 
```
nav ul a.btn{
    margin-left: 0;
    margin-right: 0;
}
```
