### ISSUE TITLE
navbar 's nav link disappear when windows width is too small

### ISSUE THREAD

**Issue by eromoe** [Dogfalo/materialize#3386]
I need nav show when I shrink window.

normally:
![qq 20160720114524](https://cloud.githubusercontent.com/assets/3938751/16974495/b07e0954-4e6f-11e6-9d3b-1b4c12aba725.png)

disappear when width is too small
![qq 20160720114441](https://cloud.githubusercontent.com/assets/3938751/16974487/97bc77f2-4e6f-11e6-9452-60dc24b4dad2.png)

PS: I don't want to use jquery, so I don't add materialize.js too. I just want css display correctly.

**Comment by acburst** [comment]
If you just copy and pasted code from our navbar documentation, then it probably has a `hide-on-med-and-down` class on it. Remove that and it should show all the time

**Comment by eromoe** [comment]
@acburst Thanks, it need add a description for this class.
