### ISSUE TITLE
Slider Cropping Images

### ISSUE THREAD

**Issue by jpan127** [Dogfalo/materialize#3387]
Hi, I'm sorry, I did not know where else to post.  Not sure if this is an issue or just me not understanding it.

But when I'm using the slider it keeps cropping the top and bottom of my photos maybe by 15% each.  Is there a way around this?  This is with fullscreen.

I then tried to use the non-fullscreen version hoping to customize the height, but it ended up only a third of my page.  I changed some of the slider class heights but it doesn't have any effect.

This is my first website/framework/code so I'm kind of confused.

**Comment by Dargmuesli** [comment]
What happens when you resize your browser window? Does the crop amount change? Does it suddenly crop your images horizontally instead of vertically?

**Comment by fega** [comment]
@jpan127 please provide a way to reproduce it. like a [codepen](https://codepen.io/fega/pen/BWeZaG) or  a snippet

Closed due inactivity, feel free to reopen it if it is still necessary.
