### ISSUE TITLE
Parallax should not require javascript

### ISSUE THREAD

**Issue by jymbob** [Dogfalo/materialize#3388]
Parallax scrolling can be easily achieved using pure CSS3 3D positioning and zooming. See [http://keithclark.co.uk/articles/pure-css-parallax-websites/](http://keithclark.co.uk/articles/pure-css-parallax-websites/) for a worked example

**Comment by fega** [comment]
@jymbob I agree with you. I don't know the opinion of @Dogfalo and @acburst 

But I believe that it should be maintained in the long term  for backward compatibility

**Comment by Thanood** [comment]
Frankly, nothing on that site works in my IE10.. But Materialize targets IE10.

**Comment by DanielRuf** [comment]
@fega huh, why did you close the issue?

Maybe it would work with polyfills.

Also, is parallax scrolling part of the materialdesign docs? I think it's not.
For me it feels a bit like feature creep.

Main target should be a web framework wich provides all the material design components in the official specification.

**Comment by fega** [comment]
Sorry, I shouldn't, I wanted to open a discussion:tired_face: 

@DanielRuf I agree, this is an over bloated feature, in my opinion, it could be isolated a plugin

Maybe we could create the plugin and begin to launch a deprecation warning in the console before get rid of it.

**Comment by DanielRuf** [comment]
> it could be isolated as a plugin

Definitely.

> before get rid of it.

Before what?

@tomscholz thoughts on this feature request?

**Comment by fega** [comment]
> > before get rid of it.

> Before what?

Before deleting it?
Before killing the parallax feature?
Before sending the feature to the limbo of the parallax features?
 
Hehe, sorry for my English mistakes :cry:

**Comment by DanielRuf** [comment]
> it could be isolated as a plugin

Right.

> Hehe, sorry for my English mistakes 😢

No problem, needed a moment to understand it. No worries.

**Comment by Sha-Grisha** [comment]
Parallax works very slow and lags on my laptop in energy saving mode (core i7) and on mobile (Yotaphone2). All firefox. I'm afraid, that's because js is using here...

**Comment by fega** [comment]
@Sha-Grisha I noted a better performance in JQuery 3+ , 

But if you want to get rid all the javascript, the @jymbob sugestion should work right

**Comment by tarekadam** [comment]
I just re-did my template with the pure css that was recommended by the opener of this thread, @jymbob -  It's really good.

**Comment by Dogfalo** [comment]
We're going to leave parallax as a js plugin, but thank you @jymbob for linking the resource, it will be helpful to those who are looking for a pure css parallax solution.
