### ISSUE TITLE
Sidenav scrolling bug - possible to see even on the project website

### ISSUE THREAD

**Issue by humbertomn** [Dogfalo/materialize#3389]
Tested on iPhone:

1- Open http://materializecss.com/
2- Click on the menu icon
3- Try to scroll down through the menu: You will notice the website background content is moving, when it shouldn't. If you open a sub-link (eg. "Components") and try to scroll down and up, the issues becomes even more relevant.

**Comment by fega** [comment]
It appears that the side nav is a little bit over-sized.

**Comment by blackchineykh** [comment]
Is this fixed? I have this same issue and would like to know if anyone has a solution or work around. 

Thanks
