### ISSUE TITLE
Checking checkboxes in responsive table resets scroll in mobile view

### ISSUE THREAD

**Issue by James-A1** [Dogfalo/materialize#3390]
I created a responsive table with checkboxes in the first column. When I switch to mobile view and try to check one of the boxes of, lets say the 5th record, it will reset the scroll bar of the table back to the left. Any workaround/fix for this?

**Comment by Dogfalo** [comment]
You can set the original checkboxes to visibliity hidden. We implemented a fix for this before, but this disables screen reader and keyboard tab accessibility.

Another option is to tweak the position so that they remain in the same place but are opacity: 0 and z-index: -1.
