### ISSUE TITLE
custom width for dropdown menu?

### ISSUE THREAD

**Issue by hamedmoody** [Dogfalo/materialize#3391]
Hi
i want use dropdown menu just with icon. but default width not allow me to define width with css.
how can i define with for dropdown custom width?
Thanks

**Comment by Xuzrus** [comment]
If you want a quick and dirty solution (without editing Materialize's JS), you can simply define the width with CSS and add the !important rule to prevent JS from changing it.

```
 <!-- Dropdown Structure -->
  <ul id='dropdown1' class='dropdown-content' style="width: 300px !important">
    <li><a>one</a></li>
    <li><a">two</a></li>
    <li><a>three</a></li>
  </ul>
```
Using the !important rule will prevent anything from changing the width value, so be careful.

**Comment by hamedmoody** [comment]
Ok
Thanks

**Comment by tgm-mstreicher** [comment]
`

  <ul id='dropdown1' class='dropdown-content' style="width: 300px !important">
    <li><a>one</a></li>
    <li><a">two</a></li>
    <li><a>three</a></li>
  </ul>
`
only work at navbar

**Comment by EvgenyVetrov** [comment]
ugly method

**Comment by CheechRockwizard** [comment]
I found that this has now been added to materialize
[https://github.com/Dogfalo/materialize/issues/805](https://github.com/Dogfalo/materialize/issues/805)

2017: constrainWidth is now passed as an object option/property upon jquery initialization of the dropdown. Check http://materializecss.com/dropdown.html ! sample (with hover, lol):

` $(".dropdown-button").dropdown({ hover: true, constrainWidth: false });`
--

**Comment by adhavalboy** [comment]
Do 
<li>  <a class="dropdown-button transparent" data-hover="true" data-constrainWidth="false" href='#' data-activates='dropdown1'><b>Algorithm</b><i class="material-icons right">arrow_drop_down</i></a></li>


here 
data-constrainWidth="false" will allow you  to do that
