### ISSUE TITLE
How Can i enabled and disabled a multiselect way JS/jQuery

### ISSUE THREAD

**Issue by carand315** [Dogfalo/materialize#3397]
I have a multiselect disabled  `<select multiple disabled>`
                    
![image](https://cloud.githubusercontent.com/assets/12404236/17074743/3ef3e970-5045-11e6-8ace-5daab72a1db2.png)

i want to enable the select element (when the checkbox is checked) i try:
 `$("select").prop('disabled', false)` but doesnt work.

thanks for your help.

**Comment by kmmbvnr** [comment]
I suppose that after `.prop('disabled', false)` you need to run `$('select').material_select();`

Generally, after any operation on materialized`select` tag you need to call  `$('select').material_select();` to sync dropdown with underline hidden select.

**Comment by carand315** [comment]
@kmmbvnr Thanks You, its works, re-run  `$('select').material_select();`

**Comment by Baraw** [comment]
Hello,

I'm having the same issue. It's not working anymore, nor with .material_select(); or .formSelect();
