### ISSUE TITLE
Potential Issue with Selectize.js?

### ISSUE THREAD

**Issue by ghost** [Dogfalo/materialize#3398]
I couldn't get Selectize JS to work `http://selectize.github.io/selectize.js/` with Materialize. Went over the code and cannot figure what would be wrong other than that there is a JS conflict (which is over my abilities to be able to resolve...) I thought adding "browser-default" as mentioned here: `http://materializecss.com/forms.html` might resolve issues between the two but it does not seem to. 
- First, whenever Selectize CSS is loaded it messes up all the form labels
- but it also does not ever work on the form either.
- But no reported errors in debug console. 

I have not tried any of the other similar plugins yet, does anyone know of anything that does the same but has been tested working? Or can has anyone used Materialize successfully with Selectize?

**Comment by aashay0101** [comment]
I used Materialize successfully with Selectizejs, I think the issue that you are facing can be solved by using the standalone file of selectizejs. If you cannot solve the error, then attach a screenshot.

Link: [https://github.com/selectize/selectize.js/blob/master/dist/js/standalone/selectize.js](https://github.com/selectize/selectize.js/blob/master/dist/js/standalone/selectize.js)
