### ISSUE TITLE
0.97.7 SideNav with several class="material-icons" displayed in cascade

### ISSUE THREAD

**Issue by pier7529** [Dogfalo/materialize#3400]
Hi. 
I take your example code SideNav and insert into mine. If you have multiple elements class="material-icons" in a list, they are displayed in cascade and no more vertical aligned as in 0.97.6

See screenshot or my website (view it on small screen)

<img width="264" alt="capture_sidenav" src="https://cloud.githubusercontent.com/assets/20623346/17083210/b7f8ed68-5197-11e6-8f5f-6e1117f980ec.PNG">

**Comment by Dogfalo** [comment]
Please post a [codepen ](http://codepen.io/Dogfalo/pen/xbzPQV) so we can fix the problem.

**Comment by pier7529** [comment]
As I'm not a web developer expert. Unfortunately, I was not able to manage the codepen. I got my ic_home icon in fullscreen but nothing in small screen

**Comment by Dogfalo** [comment]
Just go to the codepen, click "fork" then paste in HTML and CSS and JS

**Comment by pier7529** [comment]
It was what I've done but the renderer is not correct inot codepen

**Comment by pier7529** [comment]
codepen saved (I missed $(".button-collapse").sideNav(); )

**Comment by acburst** [comment]
You need to post the link to your codepen for us to see it

**Comment by pier7529** [comment]
Apologize : [http://codepen.io/anon/pen/wWjqoN](url)

**Comment by acburst** [comment]
Fixed in ebfa85e. 
If you want to fix it now, you can move the entire `ul#nav-mobile` out of the nav.

**Comment by darckyn** [comment]
Thx @acburst , this fix this also helped me. :)

**Comment by rohitsuratekar** [comment]
I am facing this problem again. Check this : http://codepen.io/rohitsuratekar/pen/pbGxwV. I tried putting "side-nav" inside or outside nav. Did not help.

**Comment by kmmbvnr** [comment]
@rohitsuratekar fix is not in the 0.97.7 release, but putting "side-nav" outside nav should help. See - http://codepen.io/kmmbvnr/pen/rLPqkQ

**Comment by rohitsuratekar** [comment]
@kmmbvnr : Hi, I downloaded CSS and JS files from (http://materializecss.com/getting-started.html) just yesterday and using them in my project. However it is still giving me similar results (i.e. extra space in navigation drawer). Am I missing something ?

**Comment by kmmbvnr** [comment]
@rohitsuratekar yes. As i said, the fix is not released and not in this files yet.
