### ISSUE TITLE
Datepicker inside a modal is wrong in safari

### ISSUE THREAD

**Issue by gomezv9** [Dogfalo/materialize#3401]
Hi

I'm working with a datepicker inside a modal but in chrome it looks fine but in safari it looks wrong. I attachment an screenshot with the problem.

Please, any help ?
![datepicker](https://cloud.githubusercontent.com/assets/7514182/17084762/fb940e6a-518b-11e6-9a14-bb6940b174bc.png)

**Comment by Dogfalo** [comment]
#1032
