### ISSUE TITLE
Carousel weird offset?

### ISSUE THREAD

**Issue by Kithio** [Dogfalo/materialize#3403]
My items are weirdly offset upon initialization of the object.
https://cdn.discordapp.com/attachments/131921658721206272/206862124067192833/unknown.png

That is where they should be...
https://cdn.discordapp.com/attachments/131921658721206272/206862459691204608/unknown.png

Any idea what's causing this? At first I thought it didn't like my custom size of the carousel but that didn't help (images above are from code without modified height of carousel)

Modified Height: (offset)
https://cdn.discordapp.com/attachments/131921658721206272/206862810586546177/unknown.png

Modified Height: (as it should be)
https://cdn.discordapp.com/attachments/131921658721206272/206862938110164992/unknown.png

The initial translate of the first item is
> translateX(-26px) translateY(-26px) translateX(0px) translateX(0px) translateZ(0px)

However upon moving to next item and back it's now...
> translateX(66px) translateY(3px) translateX(0px) translateX(0px) translateZ(0px)

**Comment by acburst** [comment]
Can you post some code to help debug?

**Comment by Kithio** [comment]
@acburst I literally copied the structure from the materialize website and initialized it using the javascript, no additional stuff to it and ran it. I don't see any reason why it should be offset like that.

I'm building my code using a weird ASP.Net based framework so the code wouldn't change anything as it requires a lot of things to run.

**Comment by acburst** [comment]
Well, it will be hard to debug without actually playing with something on my browser. But looking at the screen shots it looks like you have it inside a collapsible? If so this is probably causing issues if it is hidden when it is initialized. 

I will add callbacks to the collapsible plugin and then you can use these to make sure the carousel is rendered correctly on open

**Comment by acburst** [comment]
Added in 171a9ef.

You can now fix this problem by using the onOpen callback like this:

```
$('.collapsible').collapsible({
  onOpen: function(el) {
    var carousel = el.find('.carousel');
    if (carousel.length) {
      carousel.trigger('carouselNext', [0.000001]);
    }
  }
});
```
