### ISSUE TITLE
Side Nav won't reopen after swipe on mobile

### ISSUE THREAD

**Issue by christophwolff** [Dogfalo/materialize#3404]
When you open the Side-Nav via the burger menu and swipe it away and then want to reopen it, the Side Nav flickers open for some pixels and closes immediately. Issue is also on the Project Homepage. Movile Safari iOS 9.3.2 iPhone 6s

Havent tested on Android or older iOS Versions and other iOS Devices.

**Comment by fega** [comment]
Please provide a way to reproduce it. like a codepen or  a fiddle snippet and Could you check if this is still an issue with the last version?

Closed due inactivity, feel free to reopen it if it is still necessary.
