### ISSUE TITLE
select rendering two seperate selects in angularjs

### ISSUE THREAD

**Issue by nikhilrayaprolu** [Dogfalo/materialize#3405]
I am using the basic select in input form but the select is not working properly.on initialising the javascript for select  $('select').material_select(); in my angular app on dynamic load

my output shows a both default select and a materialize select.
![screenshot from 2016-07-25 11-50-05](https://cloud.githubusercontent.com/assets/15216503/17092165/4b21f7e4-525e-11e6-901f-89f6b9e3517d.png)

**Comment by TyrionGraphiste** [comment]
Look at your CSS, your default select should be not visible.
