### ISSUE TITLE
Material Box image in href

### ISSUE THREAD

**Issue by andrew-za** [Dogfalo/materialize#3407]
I require a different image to popup when clicking the <img> so trying to figure out a way todo this. 
It does seem that I am able to wrap the img tag in a <a> and specify the path in the href but when clicking it appears to popup the image but redirects away.

**Comment by fega** [comment]
Closed due inactivity, feel free to reopen it if it is still necessary.

**Comment by ITfee** [comment]
Similar issue here. I want Material Box to open the high resolution version of my thumbnail like that:

`<a class="materialboxed" href="http://mydomain.com/cover/high/pic.jpg"><img src="http://mydomain.com/cover/thumbs/pic.jpg"></a>`

But that doesn't work. Is there a workaround or is it simply not possible or a bug?

**Comment by ITfee** [comment]
@fega @andrew-za Can you please reopen?

**Comment by ITfee** [comment]
Duplictate of #2452
