### ISSUE TITLE
Modal does not work if parent div has CSS transform!

### ISSUE THREAD

**Issue by vpezeshkian** [Dogfalo/materialize#3410]
Hi guys,

The modal dos not seems to handle properly if parents (not immediate) has  `transform` in style.
As soon as I uncheck `transform: translate(10px, 10px);` in dev tools, modal appears...

here's a screenshot.

It's impossible to get rid of that transform since it plays key role in my code. 

Any suggestion? Thanks.

![screen shot 2016-07-25 at 10 27 12 am](https://cloud.githubusercontent.com/assets/6642294/17110681/125d2754-5253-11e6-8952-c1a4fcd19e05.png)

**Comment by Thanood** [comment]
Can you move the actual modal out of the parent and just keep the trigger there?
http://codepen.io/anon/pen/jAxQwK

**Comment by vpezeshkian** [comment]
Hmm yes, it's possible, and I tried it and it's working properly, but I have problem with this approach... The black area you see in the screenshot is my React component, which has a modal for settings. I have methods/styles bound to the modal which makes it not easy to do.

**Comment by vpezeshkian** [comment]
[The issue is this](http://stackoverflow.com/questions/15194313/webkit-css-transform3d-position-fixed-issue)

Anyone can suggest a workaround?

**Comment by vpezeshkian** [comment]
It's because CSS transforms introduces new coordinates for the component.

**Comment by fega** [comment]
@vpezeshkian Please provide a codepen to understand exactly what's happening

thanks. 

Closed due inactivity, feel free to reopen it if it is still necessary.
