### ISSUE TITLE
'Failed to decode downloaded font' since updating to 0.97.7

### ISSUE THREAD

**Issue by leanwebtools** [Dogfalo/materialize#3411]
Since updating to 0.97.7 (on a Meteor project) I'm seeing this error:

activities:1 Failed to decode downloaded font: http://localhost:3000/packages/materialize_materialize/fonts/roboto/Roboto-Regular.woff2
activities:1 OTS parsing error: invalid version tag
activities:1 Failed to decode downloaded font: http://localhost:3000/packages/materialize_materialize/fonts/roboto/Roboto-Regular.woff
activities:1 OTS parsing error: invalid version tag
activities:1 Failed to decode downloaded font: http://localhost:3000/packages/materialize_materialize/fonts/roboto/Roboto-Regular.ttf
activities:1 OTS parsing error: invalid version tag
activities:1 Failed to decode downloaded font: http://localhost:3000/packages/materialize_materialize/fonts/roboto/Roboto-Regular.woff2
activities:1 OTS parsing error: invalid version tag
activities:1 Failed to decode downloaded font: http://localhost:3000/packages/materialize_materialize/fonts/roboto/Roboto-Regular.woff
activities:1 OTS parsing error: invalid version tag
activities:1 Failed to decode downloaded font: http://localhost:3000/packages/materialize_materialize/fonts/roboto/Roboto-Regular.ttf
activities:1 OTS parsing error: invalid version tag

**Comment by milts** [comment]
Hmm, I also just updated and stumbled across this bug.

**Comment by leanwebtools** [comment]
Hi Milts -- see the comment by diegonc near the bottom of #3413 for a workaround the worked for me as well.

**Comment by NitroBAY** [comment]
This is kinda incredible as I opened an issue 2 months ago so way before atmosphere's package was updated and I referenced this issue to told to fix this bug before publishing, but they just let that huge problem free...

**Comment by mitar** [comment]
I solved it by setting the [$roboto-font-pat](https://github.com/peer/mind/blob/master/packages/council/base/base.scss#L19) variable. I do use [my fork](https://github.com/Dogfalo/materialize/issues/1018#issuecomment-238071594).

**Comment by RyanThomasMusser** [comment]
+1

**Comment by keyscores** [comment]
What worked for me was adding this line to main.css

`@import url('https://fonts.googleapis.com/css?family=Roboto:100,400');
`
*Pay attention to the weights you need, like 100, 400 etc.

**Comment by Dogfalo** [comment]
Fixed by #4000
