### ISSUE TITLE
[Tabs] RTL direction behavior

### ISSUE THREAD

**Issue by SynaOne** [Dogfalo/materialize#3414]
Hello guys, 

I'm using tabs from materialize and I come to an issue when I am in RTL direction.

Indeed, when you change from LTR to RTL, tabs behavior don't change.

Take this example :
TAB1 | TAB2 | DISABLED TAB | TAB4 | TAB5

In LTR, if you click on TAB1, you show TAB1 and it is focus with an underline.
In RTL, if you click on TAB1, you show TAB1 but the focus with an underline is on TAB5.

http://materializecss.com/tabs.html
Right clic on the scrollable tabs and adding "direction: 'ltr'" on "tabs tab-demo z-depth-1" reproduce that issue.

Can you fix this behavior please ?

Thanks you,

**Comment by Xuzrus** [comment]
Have confirmed this error. The right-to-left text direction changes the order of the tabs (correctly so) but the indicator is still assuming they are sorted right-to-left.

![test1](https://cloud.githubusercontent.com/assets/17909361/17235507/89e86482-550f-11e6-8df3-4295dc6555b1.JPG)

![test2](https://cloud.githubusercontent.com/assets/17909361/17235508/8a165e8c-550f-11e6-860f-eb7fd805ef3c.JPG)
