### ISSUE TITLE
textarea has wrong height after set text 

### ISSUE THREAD

**Issue by IvannaBabchanik** [Dogfalo/materialize#3415]
if text is set to via JS, textarea has wrong height. Text should has a lot of enters( \r\n)
[example](https://jsfiddle.net/v3zttvy6/3/)

**Comment by ben-sykes** [comment]
I agree that this is an issue.

At the very least, if the auto-resize must remain without option to turn it off, should there be some way of indicating that there is a lot of text in the text area? (maybe that's a better way to approach this issue?)

**Comment by acburst** [comment]
There is a note in the documentation saying if you dynamically set the text in a textarea you have to manually trigger the resize.

```
$('#textarea1').val('New Text');
$('#textarea1').trigger('autoresize');
```
