### ISSUE TITLE
Forms - select using material_select() is not working properly

### ISSUE THREAD

**Issue by kpavankumar** [Dogfalo/materialize#3416]
If the Select has more than two options with **same displayname** (even though both will have different values). On any option selection only the **first option having the selected displayname** will be selected.

Yeah I know that options should have different display names too. but I can differentiate it with data-icons attribute.

--> This is practically working based on display name of the options. not the values.
Hence it loses the basic select functionality.

**Comment by acburst** [comment]
Can you post a code example
