### ISSUE TITLE
Dropdown Width Error

### ISSUE THREAD

**Issue by mehmetalidumlu** [Dogfalo/materialize#3418]
Hi, i want dropdown menu in navbar. But dropdown not set width truly. Its width view 58 px on console always. There is a JSFiddle example and screenshot from my computer.

Note: I try constrain_width and constrainWidth but not work

[JSFiddle Example](https://jsfiddle.net/mehmetalidumlu/6xus30vm/)
[Screenshot - I](http://prntscr.com/by2a2j)
[Screenshot - II](http://prntscr.com/by2aqz)

**Comment by acburst** [comment]
Try using this fix #3417
