### ISSUE TITLE
Validation Problem with Datepicker

### ISSUE THREAD

**Issue by CrazyCake15** [Dogfalo/materialize#3420]
If you select a date, it's instand "invalid"

example: http://new.terrapixel.net/bewerbung/architekt_form
date field: Geburtstag

**Comment by MacGyer** [comment]
can't reproduce. Chrome, Win10

![birthday_valid](https://cloud.githubusercontent.com/assets/2939625/17226759/38d21524-550b-11e6-84fe-6b82f4790d59.png)

**Comment by Dogfalo** [comment]
Please provide additional information if you want this issue reopened.
