### ISSUE TITLE
Latest Angular-cli issues

### ISSUE THREAD

**Issue by Zambiorix** [Dogfalo/materialize#3421]
Hi,

I have installed the latest Angular-cli from github / master
https://github.com/angular/angular-cli
And installed following the guidelines
=>Development Hints for hacking on angular-cli

Then create an app. All runs as expected.

Want to install angular2-materalize as per your guidelines for angular-cli.

But now I have issues ..

In your guidelines is stated that I have to make changes in:
angular-cli-build.js
system-config.ts

But those files do not exist anymore .. 

If I serve the app, I get the following error:

ERROR in ./~/angular2-materialize/dist/index.js
Module not found: Error: Can't resolve 'materialize' in '/Users/ABC/Documents/Documents/Development/Projects/ManagingSoftware.Tracker/Development/Tracker.Website/website-v1/node_modules/angular2-materialize/dist'
 @ ./~/angular2-materialize/dist/index.js 2:0-22
 @ ./src/main.ts
 @ multi main

What is the correct way to install materialize when a project is created with the latest build from angular-cli?

Thanks!

Cheers

Gerd

**Comment by Dogfalo** [comment]
You should ask [the owner of that repo](https://github.com/InfomediaLtd/angular2-materialize). We did not make that 3rd party package so we do not know.
