### ISSUE TITLE
Cual es la resolucion maxima de materialize

### ISSUE THREAD

**Issue by judasniper** [Dogfalo/materialize#3422]
Tengo un problema estoy haciendo una pagina que en mi computadora se ve bien, en mi celular huawei g6 lte se ve bien.
Pero en el celular de mi compañero no se ve. él tiene un Note-4.

Se me ocurre que es por la resolucion.

en la pantalla de él no se ven los iconos.
<i class="material-icons">reorder</i>

es icono que yo uso en el menú no se ven en el Note4.

por aquello, si tengo el meta name viewport.

<meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1.0, user-scalable=no"/>

Como puedo arreglar eso. 

Gracias

**Comment by acburst** [comment]
Sorry, english only here please
