### ISSUE TITLE
Labels break when switching from 0.97.6 to 0.97.7

### ISSUE THREAD

**Issue by dparnane** [Dogfalo/materialize#3425]
Updating from 0.97.6 to 0.97.7 causes the labels on a prefixed input field jump off the form. Please see the screenshots attached below.

It seems that the change that breaks the labels might be the addition of `width: calc(100% - 3rem);` to the elements.
## 0.97.6

![screenshot 2016-07-28 16 26 02](https://cloud.githubusercontent.com/assets/227861/17214492/d715a644-54e1-11e6-9d0b-98a527fa3552.png)
## 0.97.7

![screenshot 2016-07-28 16 24 14](https://cloud.githubusercontent.com/assets/227861/17214493/d98b9faa-54e1-11e6-8e6c-a8c20e20daad.png)

**Comment by dparnane** [comment]
I'm trying to reproduce this in a Plunker, will comment here once I get it done.

**Comment by kfbow** [comment]
+1

**Comment by zjaml** [comment]
Happening to me in Chrome as well. This should be an higher priority issue.

**Comment by rz-robsn** [comment]
I'm having the same problem in Chrome 52, macOS 10.11.6.

The weird thing is the bug shows only when I add the input field dynamically through Javascript. It looks fine when it's already included in my html.

**Comment by malucky** [comment]
just ran into this issue. It appears to arise from the different browser implementation in calculating position for absolutely positioned elements when `left` is not explicitly specified. Not sure if this is a browser vendor bug or an ambiguous part of the spec. The fix on materialize's level would be to add `left: 0` to the label element

**Comment by fega** [comment]
I cannot reproduce it in 0.98.2

Closed due inactivity, feel free to reopen it if it is still necessary, in that case, please provide a way to reproduce it. like a [codepen](https://codepen.io/fega/pen/BWeZaG)
