### ISSUE TITLE
Icons do not work with Meteor 1.4

### ISSUE THREAD

**Issue by yanickrochon** [Dogfalo/materialize#3427]
After hot-fixing issue #3413, refreshing the page does not generate any relevant loading errors, however there are no icons on  page. I have copy-pasted HTML templates directly from [Materlialize](http://materializecss.com/getting-started.html)'s website, but this is what I see

![selection_047](https://cloud.githubusercontent.com/assets/78461/17234251/f0a68358-5504-11e6-916c-88fbf09893b5.png)

I am not sure why icons would not show. I have tried fiddling with the DOM tree, adding classes, and styles, copying HTML elements directly from the site... Icons do not show.

**Comment by Dogfalo** [comment]
The icons are not bundled by default, read the "Usage" section at http://materializecss.com/icons.html

**Comment by yanickrochon** [comment]
Right. Coming from Bootstrap, and non-Meteor frameworks, I missed that part, I guess. Thanks!
