### ISSUE TITLE
The `more_vert` icon is causing Google to say "This page is in Norwegian. Would you like to translate it?".

### ISSUE THREAD

**Issue by saadq** [Dogfalo/materialize#3429]
Here is what happens when I use the [`more_vert`](https://design.google.com/icons/#ic_more_vert) icon:

<img width="1280" alt="screen shot 2016-07-28 at 10 13 26 pm" src="https://cloud.githubusercontent.com/assets/5678694/17238550/78196ba0-5511-11e6-8b9e-75f428a64968.png">

If I change it to something like the [`arrow_drop_down`](https://design.google.com/icons/#ic_arrow_drop_down), the issue is resolved:

<img width="1280" alt="screen shot 2016-07-28 at 10 15 13 pm" src="https://cloud.githubusercontent.com/assets/5678694/17238566/9342cb92-5511-11e6-836c-707c92c95e9f.png">

Is there any way around this?

Here is the relevant part of the code:

```jsx
{/* Dropdown Structure when menu icon is clicked */}
<ul id='menu' className='dropdown-content'>
  <li><a href='#!'>one</a></li>
  <li><a href='#!'>two</a></li>
  <li className='divider'></li>
  <li><a href='#!'>three</a></li>
</ul>

{/* Nav starts here */}
<nav role='navigation'>
  <div className='nav-wrapper container'>
    <a id='logo-container' href='/' className='brand-logo'>
      QTimer
      <i className='material-icons left hide-on-med-and-down'>apps</i>
    </a>
    <ul className='right hide-on-med-and-down'>
      <Link to='/'><li>Timer</li></Link>
      <a className='dropdown-button' href='#!' data-activates='menu'>
        <i className='material-icons right'>arrow_drop_down</i> {/* Issue is here */}
      </a>
    </ul>
  </div>
</nav>
```

**Comment by Dogfalo** [comment]
Add `class="notranslate"`
http://stackoverflow.com/questions/9628507/how-can-i-tell-google-translate-to-not-translate-a-section-of-a-website

**Comment by saadq** [comment]
Adding `className='notranslate'` didn't seem to work. I wonder if it was a React/JSX issue since I don't seem to be having this translate issue when using the nav with just regular HTML.

Doing `html lang="en"` did the trick though, thanks.
