### ISSUE TITLE
JQ validation plugin not able to validate date picker in IE11

### ISSUE THREAD

**Issue by IvannaBabchanik** [Dogfalo/materialize#3432]
Hi All, 
I have validation issue in IE11. I use JQ validation plugin in project. I add date picker to form without any validation rules. On form submit I always get validation error.
The defect observed only on IE 11 and looks like custom configuration (format, formatSubmit, monthsFull etc.) is parsed incorrectly.
[jsfiddle](https://jsfiddle.net/hdv9rsn9/)

**Comment by fega** [comment]
I testing it, it works as expected
