### ISSUE TITLE
Turn off dragging side nav from the edge.

### ISSUE THREAD

**Issue by kuxa** [Dogfalo/materialize#3434]
Hi,

I use two side navs, both from left side. The thing is I want the second menu to be opened **only** through the link in the first menu, so it highly bothers me that it is possible to open it also by dragging from the left edge. It would be nice if it would be possible to turn off dragging when initializing side nav, for example
`$('.side-nav-2').sideNav({
      closeOnClick: true,
      openOnDrag: false
    }
  );`

This property would of course be true by default. I believe it would not be a big problem for you to implement this and it would make a lot of lives easier.

Thanks a lot!

**Comment by acburst** [comment]
Added draggable as a side-nav option in 8301f86
