### ISSUE TITLE
Autocomplete in a modal

### ISSUE THREAD

**Issue by ziracmo** [Dogfalo/materialize#3435]
Hello everyone,

I'm posting because i notice something when you want to create an autocompletion for an input text in a modal.

The autocompletion window which shows us the suggestions is display behind the input.

The way i use to get around this is to change the `.autocomplete-content` property `margin-top : -15px` to 0.

Thanks !

**Comment by fega** [comment]
Can you provide a way to reproduce it?
Thanks
Closed due inactivity, feel free to reopen it if it is still necessary.
