### ISSUE TITLE
Special Options Carousel not working with v97.7

### ISSUE THREAD

**Issue by GorgonsMaze** [Dogfalo/materialize#3436]
Me and a few other people from the gitter chat have been experiencing issues with the **special options** carousel. We're using the latest version v97.7. It seems to be hidden. 

![screen shot 2016-07-29 at 1 19 49 pm](https://cloud.githubusercontent.com/assets/12011826/17258640/de7adc92-5595-11e6-946c-5503976588d5.png)

```  
  <div class="carousel carousel-slider center" data-indicators="true">
    <div class="carousel-fixed-item center">
      <a class="btn waves-effect white grey-text darken-text-2">button</a>
    </div>
    <div class="carousel-item red white-text" href="#one!">
      <h2>First Panel</h2>
      <p class="white-text">This is your first panel</p>
    </div>
    <div class="carousel-item amber white-text" href="#two!">
      <h2>Second Panel</h2>
      <p class="white-text">This is your second panel</p>
    </div>
    <div class="carousel-item green white-text" href="#three!">
      <h2>Third Panel</h2>
      <p class="white-text">This is your third panel</p>
    </div>
    <div class="carousel-item blue white-text" href="#four!">
      <h2>Fourth Panel</h2>
      <p class="white-text">This is your fourth panel</p>
    </div>
  </div>
```

```
 $(document).ready(function(){
      $('.carousel').carousel();
    });
```

Here's a [codepen](http://codepen.io/zzzian/pen/dXjNWx?editors=1010) of the issue. In dev tools it shows it's intializing, it's just not displaying correctly.

When messing around with the css in dev tools I'm able to get it to display somewhat, but it doesn't look, or feel correct. When sliding there's a thin white lines that display in the middle of each slide, and the right side seems to show the next slide a bit. It ends up sliding like the original carousel, instead of a like on the documentation page.

For instance in dev tools I messed around with a few things, and  I got it to display like this. 

![image](https://cloud.githubusercontent.com/assets/12011826/17257744/7935137e-5591-11e6-8151-4a67e5bbb3ca.png)

By changing these things...

```
.carousel.carousel-slider {
    height: 500px;
}
.carousel .indicators .indicator-item {
    margin: 0 5px;
}
.carousel.carousel-slider .carousel-item {
    top: 100%;
}
```

**Comment by acburst** [comment]
I think this may be an error in our documentation. The special options carousel requires the full_width property to be true.

```
$('.carousel.carousel-slider').carousel({full_width: true});
```

I will fix the documentation ASAP

**Comment by acburst** [comment]
Added in 2dd646a

**Comment by Branksy** [comment]
full_width (which works for me) is written I believe incorrectly in the site docs as 'fullWidth'...

**Comment by rockyru** [comment]
The documentation is still not updated. It's still written there fullWidth.

**Comment by acburst** [comment]
The documentation is correct. Recently we switched all of our options to be consistent and use camelcase.

**Comment by rockyru** [comment]
I've tried the fullWidth but the carousel breaks. But when I used the full_width it works. Or is the version that I'm using?

**Comment by rockyru** [comment]
Ah! Correct I'm using the 98.0 version and the current version now is 98.1. My bad!
