### ISSUE TITLE
Autocomplete doesn't work

### ISSUE THREAD

**Issue by olilutz** [Dogfalo/materialize#3444]
Hey there if I use the new Form Autocomplete with the code provided on the page there's no dropdown list opening up and suggesting the words.
The class="autocomplete" should be added for jquery $(input.autocomplete)...
Autocomplete is a cool feature please make it work correctly.
For comparison I used the cdn script version 0.97.7
If it works for someone else please show me how to make it work.

**Comment by diegonc** [comment]
Here's a CodePen
http://codepen.io/diegonc/pen/qNrWRP

Note that the autocomplete plugin is registered with jQuery in a ready callback so it's not available until then.

**Comment by olilutz** [comment]
Thanks it worked :)
