### ISSUE TITLE
Delete Confirmation Modal

### ISSUE THREAD

**Issue by kurtaking** [Dogfalo/materialize#3445]
Does anyone have a method for using materialize modals to confirm deleting an entry for a user? I see the 'ready' and 'complete' modal options, but am unable to figure out how to only have the 'complete' function execute if the user clicks "delete" instead of "cancel".

**Comment by acburst** [comment]
You can not use the modal callbacks and instead apply your own click handler to your "delete" button

**Comment by jarodium** [comment]
Will be there an option for that? You can check bootboxjs for the plugin.

**Comment by Paco-Cervantes** [comment]
maybe this can help [material-Messages](https://jsfiddle.net/Paco_Cervantes/Lfn3L5pr/2/)

**Comment by jarodium** [comment]
Looks great. Should be added to the Framework

**Comment by kurtaking** [comment]
Closing after responses from acburst and Paco-Cervantes
