### ISSUE TITLE
Background page is scrolling in Modal popup

### ISSUE THREAD

**Issue by ragu-nathan** [Dogfalo/materialize#3450]
After opening the Modal page, the background scroll is working.. this is very much annoying in mobile only. It is working fine in Web page. Could you please help me to resolve this. Please refer this: https://jsfiddle.net/ragu_nathan/w9tmwv2z/2/
Thanks

**Comment by jdkealy** [comment]
👍  same issue here
works the same on the modal demo, background scrolls on mobile
http://materializecss.com/modals.html#!

**Comment by rubendinho** [comment]
any update/suggested fixes on this?  thanks

**Comment by haojia321** [comment]
Do this: Set your body width: 100%; and position: fixed; when modal is displayed. 
Only set those 2 styles when modal is showed.

I will try to make a PR for this issue. but for now you can try my above solution.

**Comment by acburst** [comment]
I can't seem to reproduce this issue on the latest version. Do you have a codepen?

**Comment by haojia321** [comment]
@acburst This is mobile specific, I tested on my iphone it is reproducible. 
just open modal from http://materializecss.com/modals.html# from iphone will see the issue. 
Im not sure about android though.

**Comment by tomscholz** [comment]
@acburst After opening a modal, try to scroll on the overlay...

**Comment by Greta** [comment]
This is still a bug.  I believe it can be resolved if you add the `overflow-y: hidden` style to the `<html>` tag as well as the `<body>` tag.

**Comment by mangakid** [comment]
+1

**Comment by acburst** [comment]
Modal was been rewritten in alpha v1.0.0, if this issue still exists please open a new issue

**Comment by vishwasvogga** [comment]
body{
  overflow-y: scroll !important;
}

This will solve the issue..
