### ISSUE TITLE
Textarea issue in Google Chrome on Parallax Container

### ISSUE THREAD

**Issue by Key7i** [Dogfalo/materialize#3455]
Adding a textarea on parallax container doesn't work in Google Chrome...

**Comment by Key7i** [comment]
It looks like parallax-container custom css in style.css is causing issue which comes with demo parallax template.

http://codepen.io/key7i/pen/BzOXgx

`.parallax-container { min-height: 380px; line-height: 0; height: auto; color: rgba(255,255,255,.9); }`

**Comment by fega** [comment]
Is working now, thanks
