### ISSUE TITLE
Can't overwrite individual modal with its own options, causes blocking overlay

### ISSUE THREAD

**Issue by lisatassone** [Dogfalo/materialize#3456]
If you initialise all modals at DOM ready with something like this:

`$('.modal-trigger').leanModal();`

and use ".modal-trigger" for your modal links:

`<a  class="modal-trigger" href="#hostname" id="UrlText">.something.com</a>
                    </div>`

If you then want to specify a particular complete function for a specific modal:

`$("#hostname").leanModal({ 
        complete: function(){
                      alert("hi");
              }
})`
Once you click on the link, the modal will come up fine. Click into the modal, another overlay appears and effectively blocks the whole UI.

Codepen: [http://codepen.io/lisatassone/pen/RRZNWA]

This behaviour makes the modal functionality inflexible. You effectively have to initiate every modal with different options individually. Can one set these functions after the fact?

**Comment by fega** [comment]
It looks solved in the current version 
http://codepen.io/fega/pen/GWLmKE
