### ISSUE TITLE
Adding chips dynamically

### ISSUE THREAD

**Issue by choallin** [Dogfalo/materialize#3458]
I have a "chips input field" where the user can create tags for some custom data.
After the user has written 3 chars I show him a few tags (as a chip) that already exists. If he clicks on one, it should show up in the input field as well. I tried to to this by just calling the material_chip function and give it all the data as the data attribute. But this doesn't work.  
Is there another way of creating chips in the input field dynamically?

**Comment by ferchoman09** [comment]
+1 I have the same problem

**Comment by robextrem** [comment]
Same here. An autocomplete feature is required. Maybe like [https://github.com/henrychavez/materialize-tags/](url) Materialize Tags

**Comment by developeranirudhprabhu** [comment]
I have suggested a solution for this here: https://github.com/Dogfalo/materialize/issues/3626. Let me know your thoughts

**Comment by developeranirudhprabhu** [comment]
@Dogfalo Please merge my PR to resolve this issue. Looking forward to contribute more

**Comment by acburst** [comment]
merged
