### ISSUE TITLE
Preselecting tab between two pages via href cause two active tab

### ISSUE THREAD

**Issue by ballanz89** [Dogfalo/materialize#3459]
I have two pages: main.html and preferences.html.
In the main page I have 5 tabs. 
The third one is the default one (class=active).
The last one is the preferences tab and the content is a button that point to preferences.html.
In the preferences.html I have a back link (href="index.html#preferences").
When I go back to index.html I have the 3rd tab active and the preferences tab too (with the indicator -the line- as well).
The third tab has not the indicator.

**Comment by acburst** [comment]
Can you post some code examples?

**Comment by ballanz89** [comment]
[demo.zip](https://github.com/Dogfalo/materialize/files/434853/demo.zip)

I attached the demo within a zip file.

**Comment by ballanz89** [comment]
Open the index.html, go to the Profile tab (last one), click on the "Mario Rossi" card and then back arrow.
You will see the middle tab active and the last one too.

**Comment by yogeshwar607** [comment]
any solution ?

**Comment by ballanz89** [comment]
@yogeshwar607 unfortunately no, they closed this issue with no solution.
