### ISSUE TITLE
Tabs "onShow" doesn't work

### ISSUE THREAD

**Issue by panrus** [Dogfalo/materialize#3461]
Or maybe I do smth wrong?

`$("ul.tabs").tabs({
  onShow: function(tab) {
   console.log(tab);
  }
});
`

After updating to v0.97.7 - everything work fine

**Comment by bturloff** [comment]
Not working for me either

**Comment by rabbitwish** [comment]
Seem like since version `0.98.0` the callback for `onShow` is not working... (._. ;;;)

**Comment by devpolish** [comment]
Any update about it?
