### ISSUE TITLE
Badges in Dropdown

### ISSUE THREAD

**Issue by lee011** [Dogfalo/materialize#3463]
When badges is used in dropdown, it may be overlapped the dropdown item's text if the item's text is long.

For example, the below screenshot shows that the badge "13" for the item "Very Long Long Long Text" is overlapped the item's text.

![image](https://cloud.githubusercontent.com/assets/11925743/17426809/1239fbe4-5b0e-11e6-9cf5-472b53823912.png)

Here is the code of the example: https://jsfiddle.net/hf8uwp96/4/

**Comment by lee011** [comment]
Temporary solution: Set the padding of the `<a>` tag to an appropiate value, say 70px, to avoid overlapping.

![image](https://cloud.githubusercontent.com/assets/11925743/17454418/20ae5698-5bc7-11e6-9e43-430021290310.png)

Code of above example with temporary solution applied: https://jsfiddle.net/hf8uwp96/5/

**Comment by acburst** [comment]
Fixed in 3b7572d
