### ISSUE TITLE
Lean overlay in Modal Opening Twice. with One Modal Opened

### ISSUE THREAD

**Issue by jansen07** [Dogfalo/materialize#3464]
opening modal with 
function openUpdateEducModal(educID){
            $('#modalEditEducationalBG').openModal();
.....
.
.
.....
...
}

10% of the time it creates 2 lean-overlay ..
so when i click close or outside. it will only (obviously) close one lean Modal... help

materialize-lean-overlay-13
materialize-lean-overlay-14

**Comment by fega** [comment]
Closed due inactivity
