### ISSUE TITLE
Width of drag-target when side-nav is open

### ISSUE THREAD

**Issue by vtboren56** [Dogfalo/materialize#3465]
When we open the side-nav. then the small screen it covers half of the screen and will not be allowed to touch the links. I think it should be equal to the width of the screen width minus the width of the side-nav.
![2016-08-05_16-22-19](https://cloud.githubusercontent.com/assets/3805129/17435232/dd1a2040-5b28-11e6-93ac-2ff1cd88844c.png)

**Comment by voidale** [comment]
+1 had the same issue, I fixed it with changing materialize.js line 2248 
from `dragTarget.css({width: '50%', right: 0, left: ''});`
to `dragTarget.css({width: '20%', right: 0, left: ''});`
