### ISSUE TITLE
`data-stoppropagation` doesn't work on buttons under dropdown in collapsible

### ISSUE THREAD

**Issue by vpezeshkian** [Dogfalo/materialize#3467]
On collapsible header we can now put `data-stoppropagation='true'` in order to prevent open/close of the collapsible body, cool.

But it fails when you click on any button inside dropdown which the launcher is on collapsible header. See screenshots:

-- layout is collapsible header that has more option button (sc1)
-- more option open a drop down without closing the collapsible  (cool thanks to data-stoppropagation) (sc1)
-- but when I click any of the buttons inside drop down it closes the collapsible (sc2)

<img width="134" alt="sc1" src="https://cloud.githubusercontent.com/assets/6642294/17450362/9a8b27f6-5b14-11e6-9ba2-b9344d1d26e9.png">

![sc2](https://cloud.githubusercontent.com/assets/6642294/17450365/9db8a3f4-5b14-11e6-9ad3-23e4b581f5a3.png)

Any way to prevent this to happen?

**Comment by jndoy** [comment]
I'm having this issue too

**Comment by acburst** [comment]
Can you post some example code?

**Comment by vpezeshkian** [comment]
```javascript
<li key={i} className='collapsibleLayout white'>
<div className='collapsible-header'>
<a className='dropdown-button btn-floating waves-effect waves-teal transparent z-depth-0'
             data-activates={`layoutOptions${i}`}
             data-constrainwidth='false'
             data-alignment='left'
             data-stoppropagation='true'
             style={Styles.layoutOptionsIcon}>
            <i className='material-icons small grey-text text-darken-4' style={{position: 'relative', left: '3px', bottom: '2px'}}>more_vert</i>
          </a>
<ul id={`layoutOptions${i}`} className='dropdown-content'>
            <li>
              <a className='grey-text text-darken-4' onClick={::this.activateLayout}>
                Active
                <i className='material-icons right' style={isActive ? {visibility: 'visible'} : {visibility: 'hidden'}}>done</i>
              </a>
            </li>
</ul>
</div>
</li>

When I click on "Active"  which is under dropdown it closes the collapsible... no need to mention that each `<li>` goes under `<ul ref='layoutCollapsible' className='collapsible' `... This is a React application.

**Comment by vpezeshkian** [comment]
Any suggestions???

**Comment by vpezeshkian** [comment]
Questions just piles up on each other with no answers

**Comment by fega** [comment]
@vpezeshkian 
Could you check if this is still an issue with the latest version? also,
please provide a way to reproduce it. like a [codepen](https://codepen.io/fega/pen/BWeZaG)

**Comment by Dogfalo** [comment]
This option has been removed in v1-dev
