### ISSUE TITLE
Failed to @import file

### ISSUE THREAD

**Issue by 1073113** [Dogfalo/materialize#3469]
Hi, I realized latest version supports Sass. However I failed to import components to modified the variables. 
According to fourseven:scss documentation, I did 
`@import "{materialize:materialize}/sass/components/_variables.scss";`
 Kindly advise how to modified default materializeCss template.

**Comment by iqbalaqaba** [comment]
@1073113 have you tried to edit the materializecss template from its .css files ? Thank you.
