### ISSUE TITLE
Responsive tables and rowspan - problem on small screen

### ISSUE THREAD

**Issue by dbr0** [Dogfalo/materialize#3472]
```
<table style="width:100%">
  <tr>
    <th>First Name:</th>
    <td>Bill Gates</td>
  </tr>
  <tr>
    <th rowspan="2">Telephone:</th>
    <td>555 77 854</td>
  </tr>
  <tr>
    <td>555 77 855</td>
  </tr>
</table>
```

When collapsed and title row switches to title colum the rowspan doesn't work anymore. It ignores it completely and the second row (row in collapsed view) misses one column (row in collapsed view)

**Comment by mescuderocuu** [comment]
@dbr0 isn't this already solve?
demo:
http://codepen.io/marcoswars/pen/eBgdaz

**Comment by jridky** [comment]
No, it isn't. In your demo, you're not using responsive-table class for table element.

Is there any way, how to reach that state, in which will be table's rowspan behavior transferred to colspan behavior on small screens using responsive-table class for table?
