### ISSUE TITLE
Tooltip backdrop issue with jQuery 3

### ISSUE THREAD

**Issue by pimmey** [Dogfalo/materialize#3473]
After several hours of investigation, I've noticed that tooltips don't work properly with jQuery 3 (particularly tested with 3.1.0 - the one I got with `bower install materialize`). The behaviour is pretty weird: on mouse out the backdrop disappears, but the tooltip content remains and on mouse in again the backdrop fills only a part of the tooltip. 

Attaching screenshots to make it slightly clearer:

<img width="114" alt="screen shot 2016-08-07 at 20 37 03" src="https://cloud.githubusercontent.com/assets/5588929/17464079/c9685c58-5cde-11e6-9927-308bb5959403.png">
<img width="124" alt="screen shot 2016-08-07 at 20 37 13" src="https://cloud.githubusercontent.com/assets/5588929/17464080/c9979932-5cde-11e6-8be2-67775c0cbad2.png">
<img width="126" alt="screen shot 2016-08-07 at 20 37 20" src="https://cloud.githubusercontent.com/assets/5588929/17464081/c99fd41c-5cde-11e6-9598-3e89d6c92b77.png">

**Comment by kmmbvnr** [comment]
MaterializeCSS have no support for JQuery 3 #3201

**Comment by pimmey** [comment]
I suppose bower.json should restrict that then.
```
"dependencies": {
    "jquery": ">=2.1.1 <3.0.0"
}

**Comment by Dogfalo** [comment]
Fixed in acc8f5e
