### ISSUE TITLE
materialize.css font-weight: 14px

### ISSUE THREAD

**Issue by eugeneilyin** [Dogfalo/materialize#3475]
Please check **bin/materialize.css** line(**6944**)

.side-nav .userView .name,
.side-nav .userView .email {
  font-weight: **14px;**
  line-height: 24px;
}

Is **font-weight** can be **14px**? Seems like typo (not a font-weight or not 14px)

**Comment by TyrionGraphiste** [comment]
You're right, it's : `font-size: 14px;` or `font-weight: bold;` for example.

**Comment by eugeneilyin** [comment]
What is correct variant?

**Comment by acburst** [comment]
Fixed in 0828914
