### ISSUE TITLE
Form Animaton not working in downloaded min.js

### ISSUE THREAD

**Issue by Macro-Man** [Dogfalo/materialize#3476]
When using the downloaded version of materialize.js from the main site (http://materializecss.com/getting-started.html) the animation doesn't work on form input fields where the label should animate upward out of the way of the users input when taking focus.

This animation **does** work however when using the CDN supplied from the same page (https://cdnjs.cloudflare.com/ajax/libs/materialize/0.97.7/js/materialize.min.js)

Which would imply that there is a bug with the downloadable version...

**Comment by fega** [comment]
It looks solved in the current version
Closed, feel free to reopen it if it is still having problems.
