### ISSUE TITLE
Material Select blinking on iOS

### ISSUE THREAD

**Issue by brandflownet** [Dogfalo/materialize#3479]
I am trying to create my website in Material Design, however I found one issue with Material Select. It is  working fine on Windows/OSX/Android , however for some reason when I open Material Select component on my iPad and click on it, there is a blinking cursor showing from the Background of the Dropdown.

Screen [http://laesserundpartner.ch/files/cache/select.png](url)

**Comment by ziracmo** [comment]
The screen doesn't work

**Comment by brandflownet** [comment]
Copy paste URL to browser address bar, it will work

**Comment by TyrionGraphiste** [comment]
It's a duplicate issue. There is the same on IE.

**Comment by ammichael** [comment]
Can you link it? Couldn't find.

**Comment by Dogfalo** [comment]
Duplicate of #630
