### ISSUE TITLE
Have a cdn up-to-date with master

### ISSUE THREAD

**Issue by pingec** [Dogfalo/materialize#3484]
First thanks for all the hard work that is being put into this framework, it is quite a gem.

Now to the issue: I have spent hours fixing 2 bugs in https://cdnjs.cloudflare.com/ajax/libs/materialize/0.97.7/js/materialize.js

Only to then realize they are already fixed in master. Now I have to spend even more time on learning how to compile materialize myself.

I think it would save time if there was a cdn link to a compiled materialize source from latest master commit.

**Comment by DanielRuf** [comment]
Use http://rawgit.com/

**Comment by tomscholz** [comment]
We are planning on releasing bugfixes more often. Sorry for the inconvenience.
