### ISSUE TITLE
New features with Chips

### ISSUE THREAD

**Issue by Luizgpp** [Dogfalo/materialize#3486]
Looking for this feature on Materialize. 

https://select2.github.io/examples.html#multiple

We already have Chips, multiple select and autocomplete.

Need join all together.

**Comment by olilutz** [comment]
That would be awesome.
Images in Chips and Autocomplete or Select could be in sync.

**Comment by Almaju** [comment]
What about including Select2 in the core features?

**Comment by aashay0101** [comment]
I found a simple library which meets the exacts needs for chips, autocomplete and multiple select to be combined, and it is much better than [Select2](https://select2.github.io/examples.html#multiple) ( as previosuly mentioned by @Luizgpp ) . Have a look at **selectizejs** [http://selectize.github.io/selectize.js/](url) . After working hours and hours on Select2, I shifted to Selectize, it has high customization abilities and simpler API.

**Comment by developeranirudhprabhu** [comment]
@Dogfalo Any comments on this?

**Comment by acburst** [comment]
Added a first pass at chips autocomplete integration in 83e6ba0.

Would appreciate some testing. You can check it out on the latest master version under the chips docs.

**Comment by developeranirudhprabhu** [comment]
@acburst sure we can do that

**Comment by fega** [comment]
@developeranirudhprabhu Did you do the test? thanks!

**Comment by developeranirudhprabhu** [comment]
Not yet. Been caught up with many things lately
