### ISSUE TITLE
Load selected itens on mutiple select

### ISSUE THREAD

**Issue by Luizgpp** [Dogfalo/materialize#3487]
Hello, can i load some itens checked on multiple select?

I don't see options on select.

Thanks guys!

**Comment by Luizgpp** [comment]
Sorry for this. I found the anwer here #2670. 

`$('select').val([value1, value2]).trigger('update');`

Can update documentation please?

Our can i help to add on documentantion?

Thanks!

**Comment by acburst** [comment]
You can actually add the selected attribute to the ones you want to be preselected

```
    <div class="input-field col s6">
      <select multiple>
        <option value="" disabled >Choose your option</option>
        <option value="1" selected>Option 1</option>
        <option value="2">Option 2</option>
        <option value="3" selected>Option 3</option>
      </select>
      <label>Materialize Select Multiple with selected</label>
    </div>
```
