### ISSUE TITLE
Support for Arrive.js

### ISSUE THREAD

**Issue by bertvh** [Dogfalo/materialize#3488]
I'm currently using http://fezvrasta.github.io/bootstrap-material-design/ but would like to switch to Materialize as is has more components.

The great thing about bootstrap-material-design is that it supports Arrive.js for dynamically added elements (applies the necessary js to it). Any plans to add this to Materialize?

I suppose I can code this outside the lib as well.. just a question.

**Comment by kmmbvnr** [comment]
Is it really showstopper?

It looks it's pretty easy to add `Arrive.js` initialization code in your codebase instead of usual material init scripts.

**Comment by bertvh** [comment]
Nope.. not a showstopper, just bringing up the question.

PS. I found https://www.npmjs.com/package/angular2-materialize , which is probably even better in my case.

Closing this issue. Thanks.
