### ISSUE TITLE
Issue with Tabs External link 

### ISSUE THREAD

**Issue by GaryHenshall** [Dogfalo/materialize#3494]
I am following this documentation: http://materializecss.com/tabs.html#external However the links are not working when i use any target property on the tab. 

E.g. `<li class="tab col m3 col s12"><a target="_blank" href="http://google.com/">My Information</a></li>`

This only works if i right click and select open in new tab.

**Comment by acburst** [comment]
I've tried it locally and it works for me. Do you have some sample code?

**Comment by mirshko** [comment]
I'm having this issue as well

`<div class="row container no-margin">
    <div class="col s12">
        <ul class="tabs grey lighten-5">
            <li class="tab col s3">
                <a target="_self" href="http://svalinn.local:5757/edu.html">Home</a>
            </li>
            <li class="tab col s3">
                <a target="_self" href="http://svalinn.local:5757/educators.html">Educators</a>
            </li>
            <li class="tab col s3">
                <a target="_self" href="http://svalinn.local:5757/students.html">Students</a>
            </li>
        </ul>
    </div>
</div>`

**Comment by GaryHenshall** [comment]
Just been testing this issue again. Here is my Tabbed section:

```
<div class="col s12">
     	<ul class="tabs" style="font-size: 16px;">
        	<li class="tab col m6"><a class="active" href="#MyApps">My Tools and Links</a</li>
		<li class="tab col m6"><a target="_blank" href="http://www.google.com">My Info</a></li>
	</ul>
</div> 
```

This doesnt work when i single click on it, however when i right click "Open Link In Ned Tab" it does link to Google.

**Comment by jpt007** [comment]
Having this issue as well... jsfiddle with the above example from @mirshko 

https://jsfiddle.net/jpt007/930v3zog/

**Comment by jpt007** [comment]
Anyone else having this issue?

**Comment by GaryHenshall** [comment]
I was/am still having this issue. Ended up creating my own tabs to solve the problem.

**Comment by jpt007** [comment]
Check your references and make sure you are using the latest source. For some reason I had 0.97.3. Using 0.97.7 resolved the issue. I updated the fiddle above and it's working.

**Comment by chris-fa** [comment]
0.97.7 breaks something that was working in 0.97.1, however it shows no error log.

**Comment by tomscholz** [comment]
@chris-fa Have you tried v0.98.1?

**Comment by chris-fa** [comment]
@tomscholz yes, 0.98.1 doesnt have `leanModal` breaking one of the components

**Comment by tomscholz** [comment]
@chris-fa To initialize modal use
`$('.modal').modal();`
instead of
` $('.modal').leanModal();`

**Comment by chris-fa** [comment]
@tomscholz Thanks for the help man, however in the 200k line code system with no tests that I just received a couple of months ago, doing that refactor is not a simple thing. I don't want people calling that I broke something totally unrelated by updating the library version.  I just don't understand why was the public API altered in a patch/minor version update.
