### ISSUE TITLE
Tooltip no render data-tooltip value from binding property at change 

### ISSUE THREAD

**Issue by jagcolombat** [Dogfalo/materialize#3495]
I have a component on a project angular2-cli with this element: 
`<div materialize="tooltip" data-position="bottom" [attr.data-tooltip]="connected" ></div>`
where the value of data-tooltip attribute should update at change the property component connected
This work fine in 0.97.6 but not on 0.97.7

**Comment by hem19** [comment]
I too can confirm this issue. Even though on inspecting element in chrome, I can see data-tooltip has value but it is not getting shown and only a blank black rectangle is visible.
I am binding variable like this - 
`<div materialize="tooltip" data-position="bottom" data-delay="50" [attr.data-tooltip]="versionVariable" ></div>`
I am using materializecss (0.97.7) with angular2-materialize and angular2 rc.4
When used 0.97.6 version, it is working fine.

**Comment by gnicol-bzh** [comment]
Same problem since 0.97.7 using i18next.js.

- 0.97.6 works: https://jsfiddle.net/zg9ajokp/
- 0.97.7 doesn't: https://jsfiddle.net/qvarj3x8/1/

(same code, different materialize version in "external resources")

**Comment by Deniscapp** [comment]
Same problem here :(

**Comment by savchukm** [comment]
any updates?

**Comment by fega** [comment]
@gnicol-bzh 
look: https://jsfiddle.net/Fega/z0bg24hj/1/

when the tooltip is modified it should be reinitialized with 

```
 $(document).ready(function(){
    $('.tooltipped').tooltip({delay: 50});
  });
```
Closed, feel free to reopen it if it is still necessary.
