### ISSUE TITLE
Google custom search

### ISSUE THREAD

**Issue by Touficbatache** [Dogfalo/materialize#3500]
Hey, I would like to see google custom search implemented in materializecss! Like you enter the code of your google custom search with the material search box! It would be great! Thanks

**Comment by acburst** [comment]
What exactly do you want? I'm not sure what our framework would do because it's mostly just dealing with Google's custom search api?

**Comment by Touficbatache** [comment]
I mean, I have my google search code and I want to make it look like
materialize's search box... Can I do that ?

**Comment by Touficbatache** [comment]
For example : google gave me my code, now I want to add it on my website but I want it to look like materialize's search box which is available on the website in the navbar tab...

**Comment by acburst** [comment]
It is just a custom thing I wrote for the website. I don't think it really fits in materialize as a component. But feel free to copy the CSS and HTML

**Comment by Touficbatache** [comment]
How can I make it look like Materialize's search box? What should I copy and what should I make?
