### ISSUE TITLE
Closing modal - after modal is closed new overlay is created

### ISSUE THREAD

**Issue by Voyteck0** [Dogfalo/materialize#3504]
When closing modal a new overlay is created right after closing animation is completed. This overaly has next index number at the end of id.
Interesting is that it is created after the animation is finished, so it can be destroyed only by binding to the close button destroying method delayed by setTimeout() function - workaround code below:

```
$('...').leanModal({
   complete: setTimeout(function() { $(".lean-overlay").remove(); })
});
```

As per now unfortunatelly "complete" callback also works incorrectly - so the above workaround will work only after fixing that (#3503) or the setTimout() code needs to be put somewhere else.

**Comment by jndoy** [comment]
How are we doing with this? Will there be a fix to modals anytime soon?

**Comment by fega** [comment]
leanModal is now deprecated.
