### ISSUE TITLE
$.fn.autocomplete conflicts with jQuery UI

### ISSUE THREAD

**Issue by blamoo** [Dogfalo/materialize#3506]
Materialize never had an autocomplete feature, so i've used jQuery UI to create that behavior.
This last release blocks me from using our legacy code since materialize declares $.fn.autocomplete inside a $(document).ready call and jQuery UI doesn't.
It also breaks my feature because Materialize's autocomplete doesn't allow me to perform ajax searchs...
Because of that, i had to freeze the version 0.97.6 on my bnower.json

What about renaming .autocomplete to something else?

**Comment by Dogfalo** [comment]
I think the best solution here is to rename and compile a Materialize build using `grunt monitor` for your own project.
