### ISSUE TITLE
New sideNav user elements wrong padding on fixed sidenav

### ISSUE THREAD

**Issue by tomscholz** [Dogfalo/materialize#3507]
I included the latest css and js files to use the new user sidenav elements, but there are display wrong when the class fixed is added to the sidenav. As you can see on desktop there is a slightly more padding to left and right side. On mobile everything looks like it should. 
[This is what it should look like (Codepen)](https://codepen.io/tomscholz/pen/QEYbLq)
[This is what it looks like (Live)](https://tomscholz.github.io/materialize-map/)

**Comment by deepsheth** [comment]
The elements are displaying correctly based on the CSS.
When your sidenav is fixed, the Materialize CSS for `.side-nav.fixed a` specifies `padding: 0 16px;`.
If you don't have a fixed sidenav, `.side-nav a` specifies `padding: 0 32px;` This is where the padding difference comes from, but I do agree that 32px does look better.

You can fix this by making the fixed sidenav have 32px padding.

**Comment by tomscholz** [comment]
Thanks. This did really help :) But I thought this should be implemented in the master ^^

**Comment by tomscholz** [comment]
I forgot something. The icons are also wrong adjusted.

**Comment by deepsheth** [comment]
The sidebar is inheriting properties from `nav .nav-wrapper i` which makes the icons 64px and that cuts into the list item below it, forcing it to shift right. If you move all of the HTML code for the sidebar under `</nav>`, the `.nav-wrapper` property will not be inherited and the icons will scale properly making everything adjust properly.
