### ISSUE TITLE
implementing two side navs (left and right) 

### ISSUE THREAD

**Issue by RajbirSi** [Dogfalo/materialize#3510]
hi,
is it possible to implementing two side navs in same page?
because i just tried this, its only one side nav working at a time.

**Comment by kmmbvnr** [comment]
Here is codepen that demonstrates 2 sidebars simultaneously worked fine http://codepen.io/kmmbvnr/pen/ZOwBYj

**Comment by RajbirSi** [comment]
thanks for quick reply :)
