### ISSUE TITLE
Input-field label misaligned

### ISSUE THREAD

**Issue by DoKZ** [Dogfalo/materialize#3516]
Label for an input within `input-field` is inlined after an input instead of being over an input.

Most modern browsers: 
![issue1](https://cloud.githubusercontent.com/assets/8306952/17656418/b4d05054-62db-11e6-8af4-ac58cd629bb3.png)

IE11:
![issue3](https://cloud.githubusercontent.com/assets/8306952/17656415/b4cb3d94-62db-11e6-806a-bf81d31864f4.png)

Here is the [JSBin snippet](http://jsbin.com/giroviquni/2/edit?html,output), which demonstrates this wrong behavior. It works great in all browsers, except for IE.

After some investigations, it looks like the problem is that it is somehow related to `position`, `display` and absence of `left` CSS property.

**Comment by kmmbvnr** [comment]
Currently, the `left` property is applied to the input field label, only if input field has the `.col` class

https://github.com/Dogfalo/materialize/blob/master/sass/components/forms/_input-fields.scss#L129
