### ISSUE TITLE
Slider caption not displayed for first slide

### ISSUE THREAD

**Issue by thiagupct** [Dogfalo/materialize#3517]
A situation where we have to use background colors instead of image for sliders so `img` is replaced with a `div` -> with this change, caption is not displayed for the first slide when initiated. Below was the code

**FROM THIS**

`<div class="slider">
   <ul class="slides">
      <li>
        <img src="http://website.com/test.png" alt="test image">
        <div class="caption center-align">
          <h3>This is our big Tagline!</h3>
          <h5 class="light grey-text text-lighten-3">Here's our small slogan.</h5>
        </div>
      </li>
  </div>`

**TO THIS**

`<div class="slider">
    <ul class="slides">
      <li>
        <div class="img-slide blue-color-slider"></div> 
        <div class="caption center-align">
          <h3>This is our big Tagline!</h3>
          <h5 class="light grey-text text-lighten-3">Here's our small slogan.</h5>
        </div>
      </li>
  </div>`

Found that slider.js uses `img` tag to adjust opacity to caption

`151        $active.find('img').each(function() {
 152         $active.find('.caption').velocity({opacity: 1, translateX: 0, translateY: 0}, {duration: options.transition, queue: false, easing: 'easeOutQuad'});
153        });`

**Can't we move to class based model like**

`151        $active.find('.img-slide').each(function() {
 152         $active.find('.caption').velocity({opacity: 1, translateX: 0, translateY: 0}, {duration: options.transition, queue: false, easing: 'easeOutQuad'});
153        });`

Now we were able to use background color in sliders. Was there anything other than this to update? Any suggestion is much appreciated:)

**Comment by fega** [comment]
Please provide a way to reproduce it.
Could you check if this is still an issue with the last version?
Closed due inactivity, feel free to reopen it if it is still necessary.
