### ISSUE TITLE
.collapsible-header .popout .truncate Icon Overlap

### ISSUE THREAD

**Issue by synicalsyntax** [Dogfalo/materialize#3518]
I'm currently working with popout-style Collapsible elements with Github Octicon icons  and truncated text in the header, but for some reason in mobile screens after I expand one section the other sections' text overlap onto the icon.

I've recorded the glitch in the following gif and it can be seen in this [JSFiddle](https://jsfiddle.net/b2zx8axg/2/) (please shrink the size of the output so that it is roughly the same width of a mobile screen).

![Recording](http://g.recordit.co/ZWQmsoq6gf.gif)

Any ideas on why this is happening and how I could fix it?

**Comment by fega** [comment]
It checked the snippet and it looks fine :open_mouth: 
Maybe could be a browser related bug?

Closed due inactivity, feel free to reopen it if it is still necessary.
