### ISSUE TITLE
Badges in sidenav

### ISSUE THREAD

**Issue by Chaesin** [Dogfalo/materialize#3519]
Thanks for all your hard work. I have a question that I cannot seem to find a way around. Badges in sidenav are filling the entire height of the block instead of being nicely padded like in a collection. Please refer to images below. My code is included below as well.

`<ul id="slide-out" class="side-nav fixed">`
`<li>`
`<a href="index.php">Orders <span class="new badge">4</span></a>`
`</li>`
`<li>`
`<a href="#!">Second Sidebar Link <span class="new badge" data-badge-caption="$12.00">4</span></a>`
`</li>`
`</ul>`

Is this a mistake in my coding or a feature that is not supported yet?
Thanks for all your help.

![image](https://cloud.githubusercontent.com/assets/21048881/17685214/9b056a56-6394-11e6-900c-bac73e4c6df8.png)
![image](https://cloud.githubusercontent.com/assets/21048881/17685227/bb411d9c-6394-11e6-986e-6cf457428fac.png)

**Comment by kuxa** [comment]
I have solved it like this
`<ul id="slide-out" class="side-nav fixed">`
` <li>`
`  <a href="#!">Second Sidebar Link `
`   <span>`
`    <span class="new badge" data-badge-caption="$12.00">4</span>`
`   </span>`
`  </a>`
` </li>`
`</ul>`

`.side-nav li > a > span {`
`  position: absolute;`
`  right: 10px;`
`  line-height: inherit;`
`}`

`.side-nav li > a > span .badge {`
`  line-height: initial;`
`  position: static;`
`}`

But it would definitely be cool if Materialize solved this automatically!

**Comment by acburst** [comment]
Fixed in 9db3eef.

Thanks for pointing this out
