### ISSUE TITLE
Scrollable tab? the tabs should scroll not the container

### ISSUE THREAD

**Issue by serak** [Dogfalo/materialize#3521]
thats the ugliest thing i even seen as a designer .. please check scrollable tab from angular material

**Comment by acburst** [comment]
I'm sorry but I don't even know what you are referring to. If you want to be critical of something please give me more than a sentence. Try linking to examples or making a codepen.

**Comment by serak** [comment]
I am talking about design aspect and blending with the material recommendation
forexample : 
yours : https://s4.postimg.org/ykq9ufuul/scroll.jpg

What It should Have been like 
https://s3.postimg.org/oye72afib/scroll_Nice.jpg
