### ISSUE TITLE
Cards out of view point

### ISSUE THREAD

**Issue by Sepehr13** [Dogfalo/materialize#3522]
hey there!
thanks for this great framework but there is problem with cards.
the cards are not responsive, they gets out of view point when device screen become smaller
![pic1](https://cloud.githubusercontent.com/assets/21054209/17691765/9df57a14-63ab-11e6-88d2-1440ce0a2fd0.JPG)

even worse in smaller screens

![pic2](https://cloud.githubusercontent.com/assets/21054209/17691777/b15939ec-63ab-11e6-883b-ee614152b945.JPG)
![pic3](https://cloud.githubusercontent.com/assets/21054209/17692180/bebf335a-63ad-11e6-805d-d7f371f6986f.JPG)

 i tried to play with margins paddings and overflows but non of them working

here's my code

[sepehr.txt](https://github.com/Dogfalo/materialize/files/419781/sepehr.txt)

**Comment by Sepehr13** [comment]
looks like problem was the parallax container but now the problem is cards are not in one row
![pic4](https://cloud.githubusercontent.com/assets/21054209/17692881/70a9defa-63b1-11e6-8803-b2c44450f1e4.JPG)

**Comment by Sepehr13** [comment]
looks like problem was the parallax container but what if i want to put my whole content in full screen parallax ?

**Comment by kmmbvnr** [comment]
That's hard to help without a code sample. Could you create a codepen?

**Comment by acburst** [comment]
I dont know what kind of responsiveness will be able to fix this unless you want your cards to go to unreasonably small heights. Maybe try making the font smaller on smaller screens?

**Comment by Sepehr13** [comment]
i was trying to put my whole content in parallax container i shouldn't have done that. problem fixed anyway
