### ISSUE TITLE
Carousel not properly working when sliding left first

### ISSUE THREAD

**Issue by heXXag0n** [Dogfalo/materialize#3523]
Hello MATERIALIZE developer team,
it seems that if you start scrolling left on a carousel, meaning having the item with the first index and scroll left for one time, the click event doesn't work anymore on the entire carousel until a complete reload of the page.

**Comment by acburst** [comment]
I can't seem to recreate. Please be more descriptive. Which type of carousel options, what browser, OS, etc.

**Comment by heXXag0n** [comment]
I'm sorry, it was my bad, I used some other stuff that interfered with the carousel. The issue is closed now.
