### ISSUE TITLE
Incorrect jquery version in bower.json

### ISSUE THREAD

**Issue by faalsh** [Dogfalo/materialize#3524]
The jquery version in bower.json is incorrect. Currently it is: 

```
"jquery": ">=2.1.1"
```

This will download jquery 3 which is not supported yet. 

Bower command and output is as follows: 

```
bower install materialize
```

```
bower materialize#*             cached https://github.com/Dogfalo/materialize.git#0.97.7
bower materialize#*           validate 0.97.7 against https://github.com/Dogfalo/materialize.git#*
bower jquery#>=2.1.1            cached https://github.com/jquery/jquery-dist.git#3.1.0
bower jquery#>=2.1.1          validate 3.1.0 against https://github.com/jquery/jquery-dist.git#>=2.1.1
bower materialize#^0.97.7      install materialize#0.97.7
bower jquery#>=2.1.1           install jquery#3.1.0

materialize#0.97.7 bower_components\materialize
└── jquery#3.1.0

jquery#3.1.0 bower_components\jquery
```

**Comment by kmmbvnr** [comment]
related #3473 #3201``

**Comment by faalsh** [comment]
I don't think they are related. Both reported issues are requesting support for jquery 3.
This issue is to report that when using bower to install materialize, it will download jquery 3 which is not compatible. A simple fix could be by changing bower.json to:
```
jquery: "2"
```
which will download the latest compatible jquery 2 depenency

**Comment by fega** [comment]
Jquery 3 is now supported, thanks @faalsh
