### ISSUE TITLE
Replace complicated helpers

### ISSUE THREAD

**Issue by szymsza** [Dogfalo/materialize#3531]
Hi,
great job with Materialize, I love it! But I think complicated helpers like `.hide-on-med-and-down` could be easily replacable.

I suggest followings:

```
.hide-on-small-only => .not-small
.hide-on-med-only => .not-med
.hide-on-med-and-down => .large-only
.hide-on-med-and-up => .small-only
.hide-on-large-only => .not-large
```

Plus new helper `.med-only` would be great.

I think this syntax is much easier and nicer.

Thanks!

**Comment by eboye** [comment]
While it saves space and look nicer, I think it's more intuitive as it is right now.

But `.med-only` would be nice ;)
