### ISSUE TITLE
Parallax not working (v0.97.7)

### ISSUE THREAD

**Issue by artus9033** [Dogfalo/materialize#3533]
Parallax doesn't work with materializecss v0.97.7. I included the materializecss files and jquery in my html and tried initialising the parallax both in the head and in the end of body, but none worked. This is my code (it's a django application base.html): http://pastebin.com/ah1C3dtU

**Comment by Sepehr13** [comment]
There are lots of problems in your code
Script tags doesn't need to be in head tag
Plus you don't need you use different parallax plugin just use materialize parallax.

**Comment by iqbalaqaba** [comment]
@artus9033 The paralax doc is right here : http://materializecss.com/parallax.html. 
don't forget to include the Javascript.

**Comment by iqbalaqaba** [comment]
@artus9033 could you give us a screenshot ? thanks

**Comment by iqbalaqaba** [comment]
actually i have the same problem too, but after i'm including the `init.js` and `prism.css` to my code, the carousel finally worked.. maybe you can try that option from me :smile:

**Comment by kluzny** [comment]
Try running off master branch, issue may have been fixed in #3570, which is not in the cdn or release
