### ISSUE TITLE
Wrong graphic used to explain active items for navbar in documentation page

### ISSUE THREAD

**Issue by ramanujamgond** [Dogfalo/materialize#3534]
This error is not related to your code but as I was going through your documentation page [http://materializecss.com/navbar.html]. I find that your graphical representation for active items is wrong. In your snippet code you have used wrong classes. 

I am enclosing a screen shot just go through it for details.

![active_item](https://cloud.githubusercontent.com/assets/8182687/17755311/f68e2170-64f6-11e6-99b1-8ba4ae40c785.jpg)

**Comment by iqbalaqaba** [comment]
Admin should fix this as soon as possible. I mean, yeah, docs is everything...

**Comment by acburst** [comment]
Fixed in d576c4f. 

Thanks for pointing this out!
