### ISSUE TITLE
Icon issue

### ISSUE THREAD

**Issue by iqbalaqaba** [Dogfalo/materialize#3535]
This issue began when i put the icon in the navbar and i turn on the responsive mode on Firefox.
I'm actually not sure whether it's an **issue or a bug.**

Here's my screenshot : 
![screen shot 2016-08-18 at 06 29 13](https://cloud.githubusercontent.com/assets/20835372/17756865/19e1d05c-650d-11e6-98de-e2d563169bf3.png)

And the code for the navbar is right here : http://pastebin.com/uhDc94VZ

Any Help appreciated.

**Comment by kmmbvnr** [comment]
That's should be fixed in master #3400

**Comment by iqbalaqaba** [comment]
thanks @kmmbvnr , will try it from your pen (http://codepen.io/kmmbvnr/pen/rLPqkQ)
And you mentioning about putting side-nav outside the nav tag ? Like this or not : `<ul id="nav-mobile" class="side-nav  fixed left-align">`

**Comment by kmmbvnr** [comment]
@iqbalaqaba yep, with 0.97.7 you can just move `ul` outside of `<nav></nav>`

**Comment by iqbalaqaba** [comment]
thanks @kmmbvnr ! it solved the problem and created another problem :confused: 
Now the icon is worked perfectly but i can't scroll my side-nav menu when it's on mobile devices.

**Comment by tomscholz** [comment]
@iqbalaqaba Can you post a codepen with your menu? Or can we close this issue?
