### ISSUE TITLE
Flexbox isn't working in materialize

### ISSUE THREAD

**Issue by jwentwistle** [Dogfalo/materialize#3536]
I'm applying flexbox properties to CSS classes in DIVs and they're not being applied. For instance, I have the following CSS properties:

``` 
.item-container {
  display: flex;
  flex-direction: column;
  flex-wrap: nowrap;
  align-content: stretch;
  height: inherit;
}

.item-discuss {
    flex-grow: 2;
    flex-shrink: 0;
    margin: 10px 0px 20px 0px;
    padding: 0px 10px 0px 10px;
}

.item-discuss-add {
    flex-grow: 0;
    flex-shrink: 1;
    flex-basis: 60px;
}
```

And the following code in my template: 

```
  <div class="row">
    <div class="col s12">
    <div class="item-container">

    <div class="item-discuss">
    {{#each messages}}
    <b>{{username}}</b>: {{text}}
    <br>
    {{/each}}
    </div>

    <div class="item-discuss-add grey lighten-2">
      {{>discussAddition}}
    </div>
  </div>
  </div>
</div>
```

And it aside from the flex-direction property being applied, it doesn't take up the entire space of the column.

**Comment by Dogfalo** [comment]
Columns have no inherent height, so that is why your flex styles are not working as you expect. This isn't a bug with the framework but just an aspect of CSS
