### ISSUE TITLE
Work around for nav in chrome mobile?

### ISSUE THREAD

**Issue by Daniel-Stahl** [Dogfalo/materialize#3538]
Hi there I recently put the mobile menu nav in my site and I noticed its hard to drag the menu out when i'm viewing on my phone. It looks like it wants to drag out, but when I try to drag it out, chrome takes me back a page. Is there a work around for this? I think thats a cool feature and I want to utilize it.

**Comment by acburst** [comment]
Do you mean safari mobile? I dont remember chrome doing this. Either way, I don't know of any way to override this native behavior.

**Comment by Dogfalo** [comment]
Unfortunately there isn't a way to disable it. Android users who are used to that pattern will be able to use it, but on iOS they will have to use the hamburger icon.
