### ISSUE TITLE
keyboard control for materialize-select

### ISSUE THREAD

**Issue by chen-ye** [Dogfalo/materialize#354]
Currently, tab-flow bypasses materialize select.  Keyboard functionality should instead mirror system select.  Generally the way this is done is by instead of setting the 'invisible' <select> to display:none, clipping it to 0,0,0,0 and detecting keyboard input when it is focused.

**Comment by robinbortlik** [comment]
Solved by https://github.com/Dogfalo/materialize/pull/582

**Comment by Dogfalo** [comment]
Added in 48ff6ccf348523fe9c4f8d3c82a097dd8caa0651 by @robinbortlik
