### ISSUE TITLE
Text in card of Carousel are blurry

### ISSUE THREAD

**Issue by gomezv9** [Dogfalo/materialize#3545]
Hi

I have a little problem.

Inside of my Carousel, I have some texts but this appears like blurry. I have searched if I had a mistake but I think is the property of Carousel 3D, I don`t know if someone have the same problem.

Thank

**Comment by iqbalaqaba** [comment]
Could you provide us with some of screenshot or codepen snippets ? So we can diagnose your problem clearly :blush:
