### ISSUE TITLE
Tooltip containers are orphaned when new tooltip is created on element that previously had tooltip

### ISSUE THREAD

**Issue by tomaszkrym** [Dogfalo/materialize#3546]
1. Create an element with tooltipped class
2. Call on this element .tooltip() method

There would be 2 containers for tooltip created, the first one would not be used anymore.

The solution would be to check, if the element.attr('data-tooltip-id')  is set, and either remove or reuse the old container. Of course the code calling .tooltip() method can check it, but it would be nice, if the tooltip API did this defensive check itself.

**Comment by acburst** [comment]
Fixed in 474ea82.

Thanks for pointing this out!
