### ISSUE TITLE
Carousel placed within a .collapsible-body displays only its top 100 pixels

### ISSUE THREAD

**Issue by snicky** [Dogfalo/materialize#3547]
The problem happens if you try to put a carousel within a `.collapsible-body` of a collapsible. My guess is it's due to the initial `display: none` of the `.collapsible-body`, because of which the height of `.carousel-item`s cannot be determined. 

http://codepen.io/snicky/pen/oLOobX
(carousel is placed on the third item)

**Comment by acburst** [comment]
Added in 171a9ef.

You can now fix this problem by using the onOpen callback like this:

$('.collapsible').collapsible({
  onOpen: function(el) {
    var carousel = el.find('.carousel');
    if (carousel.length) {
      carousel.trigger('carouselNext', [0.000001]);
    }
  }
});

**Comment by jahmasta** [comment]
Hello For a vanilla JS code what will be the right syntax ?
Thanks
