### ISSUE TITLE
noUiSlider vertical slider not rendering or working properly

### ISSUE THREAD

**Issue by ryanaddams** [Dogfalo/materialize#3549]
This code works fine with the current version of NoUiSlider and its default CSS. Using the Materialize-provided version and CSS, the slider is stuck in the top position and won't visibly move. Not sure if this is an old bug from NoUiSlider or if this is a new one introduced with Materialize.

```
            <div id="slider-2"></div>

<script>
            noUiSlider.create(document.getElementById('slider-2'), {
                range: {
                    'min': [-5],
                    'max': [5]
                },
                start: [0],
                step: 1,
                handles: 1,
                tooltips: false,
                orientation: 'vertical'
            });
</script>
```

**Comment by huang-da** [comment]
I'm having the same problem, does anyone have the answer? :/
