### ISSUE TITLE
Select list gets closed while clicking an option

### ISSUE THREAD

**Issue by rufuswhittle** [Dogfalo/materialize#3550]
Currently, the select works properly if items in the list get "mouse click" event. But if it gets only "mouse down" event, the list get closed without selecting.

Step to reproduce the issue: 
1. Open any select (not dropdown) by clicking on it
2. Hover the mouse pointer on any "option"
3. Just push left mouse button without releasing it

As a result of these steps whole list of options will get closed (disappear).

Some users cant click their mouse fast enough, so they cant select an option in a list. It would be nice to have this fixed.

Thanks.

**Comment by fega** [comment]
I'm unable to reproduce it with the provided instructions.
Closed due inactivity, feel free to reopen it if it is still necessary.
