### ISSUE TITLE
ScrollSpy is removing elements

### ISSUE THREAD

**Issue by larsvansche** [Dogfalo/materialize#3553]
Hello, 

I've tried to use scrollspy. It works quite allright, but sometimes it gives the element I want to scroll to a display:none state. I'll describe my order of operations: 

When I click the first button, the page scrolls to its destined element (the element with ID = about-me). 
When I click the second button, the page indeed scrolls to that element, but the FIRST element aquires the display:none in its style attribute. 
When I click the first button again, the first element reappears, the second element disappears, and the page doesn't scroll
If I click the first button again (two times in a row), the page does scroll. This time no elements are removed. 

The problem is within MaterializeCSS, because when I don't include the js file, it doesn't cause any problems. 

Please help me on this matter. This website needs to go live this week.

**Comment by larsvansche** [comment]
I would like to add that scrollspy is the ONLY javascript I'm using: 

`$(document).ready(function () {
    $('.scrollspy').scrollSpy('scrollOffset', 400);
});`

**Comment by GorgonsMaze** [comment]
Your problem sounds very specific to your code. Best thing to do is make a [codepen ](http://codepen.io/) that shows your issue, so someone can take a look.

**Comment by larsvansche** [comment]
http://codepen.io/EastSideToTheWebsite/pen/ZONWPo

Here it is. I hope someone finds the problem...

**Comment by acburst** [comment]
You have set your navigation to be tabs which is causing this odd behavior. Remove the tabs class and it shouldn't hide your content anymore

**Comment by larsvansche** [comment]
You are amazing! I use php to load in the buttons, the "tabs" class was in a place I didn't even bother to look...
