### ISSUE TITLE
input fields widening mobile webpage

### ISSUE THREAD

**Issue by larsvansche** [Dogfalo/materialize#3554]
Hello, 

I've noticed that the labels on input fields often widen a mobile webpage, it makes the webpage horizontally scrollable. For as far as I know, this only happens when the input field has a prefix icon, pushing it right far enough to make it pop out of the screen. 

I also have a quick fix for this: 
`label {
    max-width:240px;
  }`
Works for me, but perhaps a real fix can be implemented some day? 

Thanks.

**Comment by acburst** [comment]
Have you tried the latest master commit? Im pretty sure this was fixed
