### ISSUE TITLE
Any way to change Switch color?

### ISSUE THREAD

**Issue by ErraticFox** [Dogfalo/materialize#3555]
I've tried using colors in various anchors inside a switches html block. It doesn't look like there's a way to change a switches color without manually typing the active classes out in css and overriding them with `!important`. If this is the case, this should be added in as a feature.

**Comment by Nohinn** [comment]
I don't know if I understood you right. Take a look at this codepen:
http://codepen.io/Nohinn/pen/xONgLv

To change the switch color without using !important you should use those css rules.

**Comment by ErraticFox** [comment]
That's what I basically did. I was requesting a feature to change a switches color just like you would a button by simply adding a color class.

**Comment by acburst** [comment]
This is actually harder than it sounds to do, and adding these additional color classes is probably not worth it from a size / bloat standpoint. Have you tried using the sass variables?

**Comment by ErraticFox** [comment]
I don't use Sass.

**Comment by acburst** [comment]
Then I think just using plain css to override is your best option right now. The problem with making these color classes work with more specific cases is that it causes our css file to grow very large due to it needing to add css styles for each color in our large color palette.

**Comment by ErraticFox** [comment]
What's the difference of you being able to do it with a button compared to a switch?

**Comment by Dogfalo** [comment]
Other color classes are a simple `background-color` style. Doing it with a switch involves much more.

**Comment by ErraticFox** [comment]
I'm sure I'm most likely being ignorant, though I am curious. Isn't the block below just `background-color`?

```
.switch label input[type=checkbox]:checked+.lever:after {
    background-color: #FF5252 !important;
}
.switch label input[type=checkbox]:checked+.lever {
    background-color: #FF5252 !important;
}
```

**Comment by Nohinn** [comment]
Using for example red as an additional class to an element applies: 
```
.red {
    background-color: #F44336 !important;
}
``` 
to that element.

But if you want to apply this class to a switch you must consider all the switch CSS section of the framework:

- .switch label input[type=checkbox]:checked + .lever
- .switch label input[type=checkbox]:checked + .lever:after
- .switch label .lever
- .switch label .lever:after
-  input[type=checkbox]:checked:not(:disabled) ~ .lever:active::after, input[type=checkbox]:checked:not(:disabled).tabbed:focus ~ .lever::after
- input[type=checkbox]:not(:disabled) ~ .lever:active:after, input[type=checkbox]:not(:disabled).tabbed:focus ~ .lever::after
- .switch label input[type=checkbox][disabled] + .lever:after, .switch label input[type=checkbox][disabled]:checked + .lever:after

Though in your case you might not need to implement all those rules, by adding the option of changing the color of the switch just by adding a color class all those rules must be taken into account.
So imagine having to add for each color in the framework the color variation for the switch. The file would be really big compared to the current one.
