### ISSUE TITLE
A way to reinitialize scrollSpy

### ISSUE THREAD

**Issue by mitar** [Dogfalo/materialize#3557]
It would be great if there would be a way to reinitialize scrollSpy. Because if content is dynamic it can move in position vertically and then scrollSpy becomes inprecise. Simply calling scrollSpy again does not work and initializes multiple selector lines. It does not clean a previous instance of scrollSpy.

**Comment by mitar** [comment]
Hm, I am looking into the code. Does it even reinitialize when window is resized? It is doing something, but it does not seem to do anything. It just calls `jWindow.trigger('scrollSpy:winSize')` which is not listened anywhere?

**Comment by NitroBAY** [comment]
+1 mitar (thanks to mitar who's improving both the UI framework I use (materialize) and the isomorphic (back + front) framework I use (Meteor))

**Comment by NitroBAY** [comment]
If anyone of the official team @Dogfalo @acburst etc. could try to make scrollSpy reinitiable it would be very handy

**Comment by acburst** [comment]
I've been doing some local tests and I can't seem to find any issues with dynamic content? Can you make a simple codepen or something to demonstrate the issue?

**Comment by NitroBAY** [comment]
I'll show you if you want but I already check, if there's some text with scrollspy and then I init scrollspy it's working but if the HTML changes the scrollspy remains the same as before, and there's no way to refresh it, if I redo       `$('.scrollspy').scrollSpy();` it doesn't clean old scrollspy, actually it doesn't do anything.

**Comment by acburst** [comment]
Please make a codepen or something so I can see it reproduced, because I have done tests locally and I can't seem to find any errors.

**Comment by NitroBAY** [comment]
The explanation, that class scrollspy hasn't to be on the title only but on a whole div which wrap title + content, you gave to me on #3830 makes that this issue isn't an issue anymore, scrollSpy is working even with dynamic content.
This issue can be closed.

**Comment by mitar** [comment]
I made a codepen here: http://codepen.io/mitar/pen/rWNXab

Open codepen, scroll to the bottom, so that "initialization" is selected in the table of contents on the right, then start clicking "add content to structure" button **without scrolling**, structure will take over whole visible space, but "initialization" will stay selected. The selection gets fixed if you scroll, but I would like to be able to trigger re-selecting the content from the "add content to structure" button event callback, because I know that I just edited the content.

**Comment by acburst** [comment]
Refactored scrollspy to use classes in 5e8d6862. This should give you a standard way to reinit by using the destroy method. This will be available in v1.
