### ISSUE TITLE
Correct border-radius value for images in horizontal cards.

### ISSUE THREAD

**Issue by jrioromero** [Dogfalo/materialize#3558]
In the following code:

.card.horizontal .card-image img {
max-width: 100%;
width: auto;
}

The instruction
border-radius: 2px 0 0 2px;

should be included in order to override the default instruction
border-radius: 2px 2px 0 0;

that fits for default cards, but not for images in horizontal cards.

**Comment by acburst** [comment]
Ahh good catch, thanks!

Fixed in 4f0ed8b
