### ISSUE TITLE
Trigger autoresize for textarea after materialize draw page

### ISSUE THREAD

**Issue by Kravs** [Dogfalo/materialize#3562]
Hello,

My data for textarea is not filled by JS but it looks like due to some UI issues I also need to trigger autoresize to fix size of textarea. 

How to do that after materialize creates all UI? Could I bind to some event or...???

I know ugly workaround -  to wait 500ms and trigger "autoresize", but I don't want to have such dirty/unstable fix.

**Comment by acburst** [comment]
Are you using any other frameworks that is delaying the draw of things?

**Comment by Kravs** [comment]
Only jQuery and MaterializeCSS...

**Comment by fega** [comment]
@Kravs 
Please provide a way to reproduce it. like a [codepen](https://codepen.io/fega/pen/BWeZaG)
also, could you check if this is still an issue with the latest version?

Closed due inactivity, feel free to reopen it if it is still necessary.
