### ISSUE TITLE
.dropdown() with options not working on 0.97.7

### ISSUE THREAD

**Issue by sebastian-rivera** [Dogfalo/materialize#3565]
Hi, I just recently moved from version 0.97.5 to 0.97.7 and I noticed that my dropdown button in my nav bar was no longer using my drop down options such as having the drop down appear below. Has anyone had the same issue? I reverted back and it works fine.

**Comment by eboye** [comment]
Answered here: #3417

**Comment by sebastian-rivera** [comment]
I see thanks!
