### ISSUE TITLE
Smooth scrolling in a single page?

### ISSUE THREAD

**Issue by FilSalustri** [Dogfalo/materialize#3567]
I'm trying materialize for my home page at http://deseng.ryerson.ca/~fil/.

Right now, following a link in the topbar to an anchor in the current page causes a jump scroll.  

However, on the Materialize website (e.g., http://materializecss.com/side-nav.html), there's a smooth scroll when following a TOC link in the sidebar.

Basically, on my page, the TOC is in the topbar, but I don't know how to get the smooth scrolling going. Can someone help?

**Comment by iqbalaqaba** [comment]
Hello @FilSalustri ! Great page you got there..
I will tell you for a bit :smile: 
You can place this code that i got from ( https://css-tricks.com/snippets/jquery/smooth-scrolling/ ) between your <script> code :grin:     

```$('a[href*=#]:not([href=#])').click(function() {
    if (location.pathname.replace(/^\//,'') == this.pathname.replace(/^\//,'') 
        || location.hostname == this.hostname) {
        var target = $(this.hash);
        target = target.length ? target : $('[name=' + this.hash.slice(1) +']');
           if (target.length) {
             $('html,body').animate({
                 scrollTop: target.offset().top
            }, 1000);
         return false;
        }
    }
});```

**Comment by iqbalaqaba** [comment]
if you need my help, just let me know.

**Comment by FilSalustri** [comment]
Thanks @iqbalaqaba. Will give it a try ASAP.

**Comment by iqbalaqaba** [comment]
@FilSalustri your welcome :+1:

**Comment by vishnu1991** [comment]
Hello @FilSalustri  You can use Scroll Spy for smooth scrolling.
http://materializecss.com/scrollspy.html

**Comment by FilSalustri** [comment]
I had tried scrollspy without luck previously.
I have discovered my error - it was a silly noob error: I did not load jQuery before materialize.
Scrolling now works as expected. Thanks to everyone for their assistance.
