### ISSUE TITLE
DOCS: Tooltip initialization changes?

### ISSUE THREAD

**Issue by keyscores** [Dogfalo/materialize#3571]
I'm using Meteor and noticed my tooltips don't behave as expected in 0.97.7 
( It's difficult to produce a reproduction of this, unless you have a meteor environment). 

Seems like the initialization script is no longer needed to initialize? See: https://jsfiddle.net/wq938tnf/

Somehow this breaks in Meteor (possibly Angular too). Now it seems there is no way to manually init the component. Please confirm?

For example: 

        $('.tooltipped').tooltip({delay: 3000});

Should have a 3 second delay. However it loads instantly. See it load instantly here: https://jsfiddle.net/xgdqj8gx/

**Comment by acburst** [comment]
The data attributes have priority over the jQuery options. If you want to set the options by jQuery do that. Or set the data attributes. But the data attributes will override.
