### ISSUE TITLE
about modal

### ISSUE THREAD

**Issue by simpliw** [Dogfalo/materialize#3575]
i clear the value of the input in the modal before i close modal. when i reopen the modal, the input is not the initial state. It seems to get the focus. how can i deal with it to make it look like a new modal?

**Comment by simpliw** [comment]
![wechatimg71](https://cloud.githubusercontent.com/assets/7286685/18000561/4cc78584-6bb1-11e6-94a3-c14593c35aab.jpeg)

**Comment by iqbalaqaba** [comment]
@simpliw any code snippets ?

**Comment by simpliw** [comment]
@iqbalaqaba  i can only paste the main code

modal.vue
<template lang="html">
  <div>
    
  <a class="waves-effect waves-light btn modal-trigger" href="#modal1">Add</a>

  
  <div id="modal1" class="modal">
    <div class="modal-content">
      <h4>Add a todo</h4>
      <div class="input-field">
        <input type="text" id="content" class='validate' v-model="temp.content" required="true">
        <label for="content">what to do?</label>
      </div>
      <div class="input-field">
        <input type="text" id="name" class='validate' v-model="temp.name" required="true">
        <label for="name">who am i?</label>
      </div>
    </div>
    <div class="modal-footer">
      <a href="#!" class=" modal-action modal-close waves-effect waves-green btn-flat" @click='notify'>Add</a>
    </div>
  </div>
  </div>
</template>

<script>
export default {
  data() {
      return {
        temp: {
          content: '',
          name: ''
        }
      };
    },
    computed: {},
    ready() {
      $('.modal-trigger').leanModal();
    },
    attached() {},
    methods: {
      notify: function() {
        if (this.temp.content.trim() && this.temp.name.trim()) {
          this.$dispatch('child-msg', this.temp)
          this.temp.content = '';
          this.temp.name = '';
        }
      }
    },
    components: {}
};
</script>

<style lang="css">
</style>


todo.vue

<template>
<div class="todo col s12 m10">
  <div class="collection">
    <a href="#!" class="collection-item" v-for="item in items">{{item.content}}<span class="badge">{{item.name}}</span></a>
  </div>
  <modal></modal>
</div>
</template>

<script>
import {
  TodoCreate,
  TodosFetch
} from '../../db/Todo';
import Modal from './Modal.vue';
export default {
  data() {
      return {
        items: [],
        todo: {
          name: '',
          content: ''
        }
      }
    },
    components: {
      Modal
    },
    
    events: {
      'child-msg': function(obj) {
        let that = this;
        TodoCreate(obj, function(res) {
          that.reload();
        }, function(error) {
          console.info(error)
        })
      }
    }

}
</script>


<style scoped>
h1 {
  color: #42b983;
}
</style>

**Comment by acburst** [comment]
Code snippets help us debug the situation for you. While a screenshot is helpful, it is almost impossible to tell you what the problem is

**Comment by jndoy** [comment]
I have a simple javascript form reset on the click of the close button:

`<script> function resetForm(formID, msgs) {
document.getElementById(formID).reset();
document.getElementById(msgs).innerHTML ='';
}</script>`

`<div class="modal-footer"><a class="modal-action modal-close btn-flat"
onclick='resetForm("contact_form", "contact-form-messages");'>Close</a></div>`

It does the trick

**Comment by simpliw** [comment]
export default {
  data() {
      return {
        temp: {
          content: '',
          name: ''
        }
      };
    },
    computed: {},
    ready() {
      $('.modal-trigger').leanModal();
    },
    attached() {},
    methods: {
      notify: function() {
        if (this.temp.content.trim() && this.temp.name.trim()) {
          this.$dispatch('child-msg', this.temp)
          this.temp.content = '';
          this.temp.name = '';
        }
      }
    },
    components: {}
};

**Comment by simpliw** [comment]
@jndoy 
I tried it your way. the label on top is not located inside the input

**Comment by jndoy** [comment]
@simpliw I didn't include the code for the form itself in my example. I just attached a function to the close button of the modal that the form is inside. I have several modal forms on one page, so the function takes the form ID and the ID of it's corresponding error output element  as parameters.
