### ISSUE TITLE
Tooltip Initialization Options Not Working

### ISSUE THREAD

**Issue by RhanCandia** [Dogfalo/materialize#3577]
I am on 0.97.6 and all tooltip initialization options don't work except delay. I can't figure out what's wrong.

**Comment by acburst** [comment]
Can you post your code? I can't help you without any information.

**Comment by RhanCandia** [comment]
My code is very straightforward.

$('.selector').tooltip({
    delay: 800,
    tooltip: "<h1>This is a test.</h1>,
    html: true
});
