### ISSUE TITLE
Slider image background css distorts

### ISSUE THREAD

**Issue by Dargmuesli** [Dogfalo/materialize#3580]
## Description

When your website's [CSP](https://en.wikipedia.org/wiki/Content_Security_Policy) settings block base64, images in a slider are displayed distorted because css background properties like `background-size: cover;` and `background-position: center;` are not applied.
## Affected browsers

Only Firefox (Version 47.0.1), no other browsers.
## Related commits

53873ce
## Known Fix

One possible fix is - of course - to allow data-uris in your `.htaccess` file like this:

`Header set Content-Security-Policy "img-src data:;"`
**Notice the colon!**

But this is certainly not what everybody wants to do or can do, so maybe you can find a different workaround in materialize.

**Comment by fega** [comment]
Closed due inactivity, feel free to reopen it if it is still necessary.
