### ISSUE TITLE
Click wave effect doesn't work

### ISSUE THREAD

**Issue by djessedirckx** [Dogfalo/materialize#3581]
I don't know why, but the waves don't work when I click the button. I can't see what I'm doing wrong. This is the html I've written so far.

`<!DOCYTYPE HTML>
<html>
	<head>
		<title>Djesse Dirckx</title>
		<meta charset="UTF-8">
		<meta name="viewport" content="width=device-width, initial-scale=1">
		<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/0.97.7/css/materialize.min.css">
		<link rel="stylesheet" href="site.css">
	</head>
	<body>
		<div class="container">
			<div class="row">
				<div class="col s12" id="top">						
					<a class="waves-effect waves-light btn">button</a>
				</div>
			</div>
		</div>
	</body>
</html>`

**Comment by acburst** [comment]
Have you included our javascript?
