### ISSUE TITLE
Add support to disable appending images with auto complete

### ISSUE THREAD

**Issue by mushtaqak** [Dogfalo/materialize#3583]
I would like a default option that would let us disable appending images to autocomplete li.

P.S: I am working on PR that would allow us this option.

**Comment by yanickrochon** [comment]
Currently, if the associated data value is a string, it is displayed as an image URL. Just add the feature that, if it is an object, then it is some data which is *not* an image. This way, no need for extra options, and it should be 99% BC.

For example : 

```
// standard implementation
$('input.autocomplete').autocomplete({
  data: {
    "Apple": null,
    "Microsoft": null,
    "Google": 'http://placehold.it/250x250'
  }
});

// data has data... (i.e. no images)
$('input.autocomplete').autocomplete({
  data: {
    "Apple": null,
    "Microsoft": null,
    "Google": { id: 1, url: 'http://placehold.it/250x250' }
  }
});
```

**Comment by mushtaqak** [comment]
@yanickrochon Looks a good idea, let me find some time and come up with a better solution. Thanks
