### ISSUE TITLE
Checkbox inside <label>

### ISSUE THREAD

**Issue by subins2000** [Dogfalo/materialize#3585]
It would be great if checkbox can be made like this :

``` html
<label>
  <input type="checkbox" />
  <span>Check this</span>
</label>
```

The above code is similar to how switches are made :

``` html
<div class="switch">
  <label>
    <input type="checkbox" />
    <span class="lever"></span>
  </label>
</div>
```

I suggest to remove the current way of making checkboxes and use it under a `label` tag. Current approach :

```
<input type="checkbox" id="test5" />
<label for="test5">Red</label>
```
## Pros
- Less confusing (both switch and checkbox will use same approach)
- No need of `id` tag and `for` tag. The `id` tag is important and cannot be wasted as you can scroll to a section of page with it (`http://exampl.com/index.html#test5`)

There maybe more pros, but I can't think of any cons ;)

**Comment by subins2000** [comment]
@Dogfalo Your comments on this proposal ?

**Comment by Dogfalo** [comment]
I agree this is a good change. Will add this in a future version.

**Comment by avrahamcool** [comment]
any news on this?

**Comment by tomscholz** [comment]
This issue has been moved to one of our project boards :)

**Comment by mitar** [comment]
Hm, but why closing issues which are moved to approved feature requests? Strange.

**Comment by tomscholz** [comment]
Sorry, I have made a mistake here

**Comment by acburst** [comment]
Added in v1-dev de0b8765
