### ISSUE TITLE
Add support to add data attribute to autocomplete

### ISSUE THREAD

**Issue by mushtaqak** [Dogfalo/materialize#3586]
Add a data attribute to the autocomplete input field so that the value can be used when we pass data list to autocomplete plugin.

E.g.

```
$('input.autocomplete').autocomplete({
    data: {
      "Apple": 1,
      "Microsoft": 2,
      "Google": 3
    },
    data_attr : 'data-id'
  });
```

**Comment by yanickrochon** [comment]
I'd rather have a callback when a value is selected.

```
const data = {
  "Apple": 1,
  "Microsoft": 2,
  "Google": 3
}; 
$('input.autocomplete').autocomplete({
  data: data,
  select: function (target, selection) {
    var val = data[selection];
    $(input).data('id', val);
  }
});
```

**Comment by mushtaqak** [comment]
@yanickrochon Looks a good idea, let me find some time and come up with a better solution. Thanks

**Comment by fega** [comment]
Closed due inactivity, feel free to reopen it if it is still necessary.
