### ISSUE TITLE
Badges in Collapsible

### ISSUE THREAD

**Issue by Saravana-Kumar-putta** [Dogfalo/materialize#3588]
Badges are not supported in collapsible

**Comment by acburst** [comment]
Can you be more specific and put in more content into this issue. Do you want badges to work on collapsible headers?

**Comment by Saravana-Kumar-putta** [comment]
Exactly I need badges to work on collapsible headers, I tried by putting the badges in headers but it come extreme right of the browser  not in the headers of collapsible

**Comment by karinacarmona** [comment]
Ran into this too. I just set position:relative on the collapsible-headers

**Comment by Saravana-Kumar-putta** [comment]
You mean I need to put style for collapsible headers ?

**Comment by karinacarmona** [comment]
Yeah I had to add styles to it

**Comment by acburst** [comment]
Fixed in 8f2aff0
