### ISSUE TITLE
Pass trigger element to lean Modal

### ISSUE THREAD

**Issue by yanickrochon** [Dogfalo/materialize#3590]
Since it is possible to have many different elements triggering the same modal, it would be nice to have the triggering element within the onReady callback (or something).

See [related question](http://stackoverflow.com/questions/39210925/materialize-get-modal-trigger-element/39211304#39211304).

**Comment by yanickrochon** [comment]
For example :

```js
$('.modal-trigger').leanModal({
  ready: function(event) {
    // event = {
    //  "type": "onReady",
    //  "trigger": <DOMelement>,
    //  "timeStamp": Number,
    //  ...
    //}
    console.log('Modal triggered by', event.trigger);
  }
});
```

**Comment by acburst** [comment]
I'm currently in the process of rewriting our modal to move away from initializing on a trigger element. But I can change the callback functions to pass the modal element as a parameter.

**Comment by yanickrochon** [comment]
Looks nice so far. But it would still be possible to pass the trigger to the `ready` function, if you pass this [here](https://github.com/Dogfalo/materialize/blob/master/js/modal.js#L149), then you'd have the trigger as argument to passe it as second argument to the `ready` function [here](https://github.com/Dogfalo/materialize/blob/master/js/modal.js#L149).

**Comment by acburst** [comment]
Added in 3be5561

**Comment by yanickrochon** [comment]
Splendid! :+1:
