### ISSUE TITLE
Official React Port

### ISSUE THREAD

**Issue by atulmy** [Dogfalo/materialize#3593]
Will we see an official **React** port of current MaterializeCSS in near future, or like very soon? There is already a React [Material-UI](http://www.material-ui.com/) library and an [unofficial](https://react-materialize.github.io/) (I guess)  but since lot of people have been using Materialize, it'll be really exciting and useful to have an official MaterializeCSS library for React.

**Comment by acburst** [comment]
I do not have much experience with react, but I do recognize it's popularity and usefulness. This is something that could be done in the future but no official plans right now. If someone who's experienced with react would like to help us out I'd be interested
