### ISSUE TITLE
Django and label ordering problems

### ISSUE THREAD

**Issue by felippepuhle** [Dogfalo/materialize#3594]
Using the classic form rendering method in Django(`form.as_p`), the label tag comes before the input, which breaks some form fields.

Example:
`<label for=”id_receive_email”>Receive email:</label> <input id=”id_receive_email” name=”receive_email” type=”checkbox”>`

Materialize CSS works with `[type="checkbox"]+label` selector. There's a way to handle with this without change Django default behavior?

**Comment by MartinMelo97** [comment]
I have the same problem :(

**Comment by kmmbvnr** [comment]
You can use mine [django-material](https://github.com/viewflow/django-material) project that customizes form rendering to be compatible with materializecss

**Comment by fega** [comment]
Closed due inactivity, feel free to reopen it if it is still necessary.
