### ISSUE TITLE
materialboxed image cannot be centered

### ISSUE THREAD

**Issue by neokio** [Dogfalo/materialize#3598]
The following 3 column images ...

```
    <div class="container">
        <div class="section">
            <div class="row">
                <div class="col s12 m4 center">
                    <img src="/css/images/blah1.jpg" width="200px" height="200px" class="materialboxed circle" alt="blah1" data-caption="blah1">
                </div>
                <div class="col s12 m4 center">
                    <img src="/css/images/blah2.jpg" width="200px" height="200px" class="materialboxed circle" alt="blah2" data-caption="blah2">
                </div>
                <div class="col s12 m4 center">
                    <img src="/css/images/blah3.jpg" width="200px" height="200px" class="materialboxed circle" alt="blah3" data-caption="blah3">
                </div>
            </div>
        </div>
    </div>
```

... will be flush left, despite their container having the `center` class. Removing `materialboxed` centers them again (but loses the materialbox). Adding this css ...

```
    .materialboxed{ display: inline-block; }
```

... lets me use materialbox while centering the images correctly, however the enlargement animation jumps in a strange way. From looking at all the different materialboxed js issues, most of which are quite basic, this code clearly could benefit from some attention.

**Comment by acburst** [comment]
Our center class is only a text-align: center, so if you want to use it for anything other than text like block elements you will need to add inline-block.

As for the animation, I tried doing this locally and i'm not seeing any strange jumps. Could there be anything else that is causing this issue?

**Comment by Poyser1911** [comment]
it only does the weird animation for images with a small width, when u click it pushes to the left before zooming.
for larger width images its barely visible and looks almost normal.

**Comment by yurigo** [comment]
> it only does the weird animation for images with a small width, when u click it pushes to the left before zooming.
for larger width images its barely visible and looks almost normal.

I've been playing with this classes and found this issue.  Adding `display: inline-block` in `.materialboxed` does this weird animation.  I added this css to solve this.
``` css
.center .materialboxed,
.center-align .materialboxed {
    margin: 0 auto; position: relative !important;
}
```
