### ISSUE TITLE
Refactored Modal Plugin. Testing needed!

### ISSUE THREAD

**Issue by acburst** [Dogfalo/materialize#3600]
I've refactored the modal plugin in bfb74577f802234b72df10c5185b172c12c61453 which fixed a bunch of bugs and cleaned up the code. The plugin is now initialized on the actual modal element itself and NOT the trigger. I've also renamed the plugin to be just modal.

```
// Examples
$('.modal').modal();
$('.modal').modal('open');
$('.modal').modal('close');
```

I'd really appreciate if people could try out the master build and see if there any problems or bugs that this rewrite has caused.

**Comment by K1llMan** [comment]
```
        open: function() {
            a(this).trigger("openModal")
        },
        open: function() {
            a(this).trigger("closeModal")
        }
```
Open/close handlers problem. 
Overlay doesn't appear.

**Comment by Nohinn** [comment]
As @K1llMan said. There are issues with the handlers.

They're only bound if you call `.modal()` with or without arguments before calling .modal('open').
Before you could have the HTML element and just calling `.openModal(arguments)` would open the modal window, without having to initialize it in any way previously.

**Comment by Nohinn** [comment]
Another issue.

When closing a modal the opacity is changed, etc. but the display is not changed to 'none' as in previous releases. Making all the content from the modal invisible and on top of everything on your UI.

**Comment by acburst** [comment]
@K1llMan Fixed double open option in 4f6025f.

@Nohinn Fixed display none bug in d4795ca.
But can you explain the other issues a bit more? I think its fine to have to initialize the modal to be able to call open or close.

**Comment by Nohinn** [comment]
Yes @acburst it is absolutely logical, but in terms of ease of use we are moving from 1 function call to 2.

The reamining issue I reported. although you can pass arguments to the open/close function, they're not taken into account. 
A developer may need two buttons to close a modal, each one will do a different task on the complete callback function of the modal. Right now, you define all the plugin parameters when you initialize the modal. But you cannot pass a new complete callback function (for example) to the close function, because  the close function doesn't take into account arguments.

**Comment by yanickrochon** [comment]
The issue of `$(modalSelector).modal().modal('open')` could be solved by two solutions 

1. Have `.modal('open')` initialize the modal if not already so, then call the instance method
2. Add an init option to open the modal initially, just like [Bootstrap does](http://getbootstrap.com/javascript/#modals-options) with it's `show` option.

Ordinarily, jQuery plugins are based on instances that are available directly unto the element's data. For example : `$(modalSelector).modal('open');` and `$(modalSelector).data('modal').open();` should be equivalent. Again, with Bootstrap, components are contained this way, and the modal instance can be retrieved via `.data('bs.modal')`.

The widget standard API, with jQuery, is

* `init` - create the component (this should not be called twice)
* *setters* / *getters* - mutate and retrieve the component's various states and options
* `destroy` - cleanup function that reverts any DOM changes back and remove any event listeners

All these are contained within a single prototype that can be extended if necessary.

**Note:** there is an issue that the modal may be initialize twice, adding [duplicate event listeners](https://github.com/Dogfalo/materialize/blob/master/js/modal.js#L156) on the modal element. Ironically, the triggers are properly cleaned, so this may just be an oversight.
