### ISSUE TITLE
Error when using with bootstrap

### ISSUE THREAD

**Issue by nikhilgoyal94** [Dogfalo/materialize#3601]
Hi Team,

I was creating a website using Bootstrap and Materialize.

I found Materialize.js is throwing some error when I use bootstrap's carousel in the website. I looked into the issue and found these errors. Kindly consider the same.

**Error 1**
In Line 7171, the value of **el** is undefined but is trying to set some properties of that. So it may be checked for the **undefined** before setting the properties.

**Error 2**
In Line 7228, the value of **el** is undefined but is trying to set some properties of that. So it may be checked for the **undefined** before setting the properties.

Also, I saw the same issue is in many other places where **el** is not being checked before setting the values.

These issues are fixed if we check for the undefined before setting the  values.

**Comment by Dogfalo** [comment]
Using Bootstrap alongside Materialize is not advised and will almost certainly cause problems.
