### ISSUE TITLE
error installing materialize:materialize in Meteor

### ISSUE THREAD

**Issue by Rathius** [Dogfalo/materialize#3602]
I've been trying and trying to install materialize in a Meteor project I'm working on for the last month and it just will not install. I get the same error every time. I've been looking and looking for a fix but I still have yet to find one.

Here's the error I keep getting. Make sure to take not of the **multiple 404 errors**. 

 => Errors while adding packages:             

While loading package fourseven:scss@3.2.0:
error: Command failed:
/Users/xxxx/.meteor/packages/meteor-tool/.1.4.1_1.1h0re2h++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/bin/npm
rebuild --no-bin-links --update-binary
Cannot download
"https://github.com/sass/node-sass/releases/download/v3.2.0/darwin-x64-46_binding.node":
HTTP error 404 Not Found
gyp ERR! configure error 
gyp ERR! stack Error: 404 status code downloading tarball
gyp ERR! stack     at Request.<anonymous>
(/Users/xxxx/.meteor/packages/fourseven_scss/.3.2.0.1kzh141++os.osx.x86_64+web.browser+web.cordova/plugin.compileScss.os.osx.x86_64/npm/node_modules/meteor/compileScss/compileScss/node_modules/node-sass/node_modules/pangyp/lib/install.js:251:14)
gyp ERR! stack     at emitOne (events.js:82:20)
gyp ERR! stack     at Request.emit (events.js:169:7)
gyp ERR! stack     at Request.onRequestResponse
(/Users/xxxx/.meteor/packages/fourseven_scss/.3.2.0.1kzh141++os.osx.x86_64+web.browser+web.cordova/plugin.compileScss.os.osx.x86_64/npm/node_modules/meteor/compileScss/compileScss/node_modules/node-sass/node_modules/pangyp/node_modules/request/request.js:1255:10)
gyp ERR! stack     at emitOne (events.js:77:13)
gyp ERR! stack     at ClientRequest.emit (events.js:169:7)
gyp ERR! stack     at HTTPParser.parserOnIncomingClient
(_http_client.js:433:21)
gyp ERR! stack     at HTTPParser.parserOnHeadersComplete
(_http_common.js:103:23)
gyp ERR! stack     at TLSSocket.socketOnData (_http_client.js:322:20)
gyp ERR! stack     at emitOne (events.js:77:13)
gyp ERR! System Darwin 15.6.0
gyp ERR! command
"/Users/xxxx/.meteor/packages/meteor-tool/.1.4.1_1.1h0re2h++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/bin/node"
"/Users/xxxx/.meteor/packages/fourseven_scss/.3.2.0.1kzh141++os.osx.x86_64+web.browser+web.cordova/plugin.compileScss.os.osx.x86_64/npm/node_modules/meteor/compileScss/compileScss/node_modules/.temp-11iw2fa/node_modules/node-sass/node_modules/pangyp/bin/node-gyp"
"rebuild" "--libsass_ext=" "--libsass_cflags=" "--libsass_ldflags="
"--libsass_library="
gyp ERR! cwd
/Users/xxxx/.meteor/packages/fourseven_scss/.3.2.0.1kzh141++os.osx.x86_64+web.browser+web.cordova/plugin.compileScss.os.osx.x86_64/npm/node_modules/meteor/compileScss/compileScss/node_modules/.temp-11iw2fa/node_modules/node-sass
gyp ERR! node -v v4.5.0
gyp ERR! pangyp -v v2.2.1
gyp ERR! not ok 
Build failed

npm ERR! Darwin 15.6.0
npm ERR! argv
"/Users/xxxx/.meteor/packages/meteor-tool/.1.4.1_1.1h0re2h++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/bin/node"
"/Users/xxxx/.meteor/packages/meteor-tool/.1.4.1_1.1h0re2h++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/bin/npm"
"rebuild" "--no-bin-links" "--update-binary"
npm ERR! node v4.5.0
npm ERR! npm  v3.10.6
npm ERR! code ELIFECYCLE
npm ERR! node-sass@3.2.0 postinstall: `node scripts/build.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the node-sass@3.2.0 postinstall script 'node
scripts/build.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the node-sass package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node scripts/build.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs node-sass
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls node-sass
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!
/Users/xxxx/.meteor/packages/fourseven_scss/.3.2.0.1kzh141++os.osx.x86_64+web.browser+web.cordova/plugin.compileScss.os.osx.x86_64/npm/node_modules/meteor/compileScss/compileScss/node_modules/.temp-11iw2fa/npm-debug.log
Cannot download
"https://github.com/sass/node-sass/releases/download/v3.2.0/darwin-x64-46_binding.node":
HTTP error 404 Not Found
gyp ERR! configure error 
gyp ERR! stack Error: 404 status code downloading tarball
gyp ERR! stack     at Request.<anonymous>
(/Users/xxxx/.meteor/packages/fourseven_scss/.3.2.0.1kzh141++os.osx.x86_64+web.browser+web.cordova/plugin.compileScss.os.osx.x86_64/npm/node_modules/meteor/compileScss/compileScss/node_modules/node-sass/node_modules/pangyp/lib/install.js:251:14)
gyp ERR! stack     at emitOne (events.js:82:20)
gyp ERR! stack     at Request.emit (events.js:169:7)
gyp ERR! stack     at Request.onRequestResponse
(/Users/xxxx/.meteor/packages/fourseven_scss/.3.2.0.1kzh141++os.osx.x86_64+web.browser+web.cordova/plugin.compileScss.os.osx.x86_64/npm/node_modules/meteor/compileScss/compileScss/node_modules/node-sass/node_modules/pangyp/node_modules/request/request.js:1255:10)
gyp ERR! stack     at emitOne (events.js:77:13)
gyp ERR! stack     at ClientRequest.emit (events.js:169:7)
gyp ERR! stack     at HTTPParser.parserOnIncomingClient
(_http_client.js:433:21)
gyp ERR! stack     at HTTPParser.parserOnHeadersComplete
(_http_common.js:103:23)
gyp ERR! stack     at TLSSocket.socketOnData (_http_client.js:322:20)
gyp ERR! stack     at emitOne (events.js:77:13)
gyp ERR! System Darwin 15.6.0
gyp ERR! command
"/Users/xxxx/.meteor/packages/meteor-tool/.1.4.1_1.1h0re2h++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/bin/node"
"/Users/xxxx/.meteor/packages/fourseven_scss/.3.2.0.1kzh141++os.osx.x86_64+web.browser+web.cordova/plugin.compileScss.os.osx.x86_64/npm/node_modules/meteor/compileScss/compileScss/node_modules/.temp-11iw2fa/node_modules/node-sass/node_modules/pangyp/bin/node-gyp"
"rebuild" "--libsass_ext=" "--libsass_cflags=" "--libsass_ldflags="
"--libsass_library="
gyp ERR! cwd
/Users/xxxx/.meteor/packages/fourseven_scss/.3.2.0.1kzh141++os.osx.x86_64+web.browser+web.cordova/plugin.compileScss.os.osx.x86_64/npm/node_modules/meteor/compileScss/compileScss/node_modules/.temp-11iw2fa/node_modules/node-sass
gyp ERR! node -v v4.5.0
gyp ERR! pangyp -v v2.2.1
gyp ERR! not ok 
Build failed

npm ERR! Darwin 15.6.0
npm ERR! argv
"/Users/xxxx/.meteor/packages/meteor-tool/.1.4.1_1.1h0re2h++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/bin/node"
"/Users/xxxx/.meteor/packages/meteor-tool/.1.4.1_1.1h0re2h++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/bin/npm"
"rebuild" "--no-bin-links" "--update-binary"
npm ERR! node v4.5.0
npm ERR! npm  v3.10.6
npm ERR! code ELIFECYCLE
npm ERR! node-sass@3.2.0 postinstall: `node scripts/build.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the node-sass@3.2.0 postinstall script 'node
scripts/build.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the node-sass package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node scripts/build.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs node-sass
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls node-sass
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!
/Users/xxxx/.meteor/packages/fourseven_scss/.3.2.0.1kzh141++os.osx.x86_64+web.browser+web.cordova/plugin.compileScss.os.osx.x86_64/npm/node_modules/meteor/compileScss/compileScss/node_modules/.temp-11iw2fa/npm-debug.log

kindly fix this please. I really don't want to use Bootstrap or some other responsive framework.

**Comment by Rathius** [comment]
The error actually comes from fourseven:scss. I installed fourseven:scss first then tried installing Materialize and it worked.

**Comment by ruohki** [comment]
@Rathius solves the problems ty
