### ISSUE TITLE
Cannot install 

### ISSUE THREAD

**Issue by apps4av** [Dogfalo/materialize#3604]
zkhan@zkhan-ThinkPad-E520:~/app$ meteor add materialize:materialize => Errors while adding packages:             

While loading package fourseven:scss@3.2.0:
error: Command failed:
/home/zkhan/.meteor/packages/meteor-tool/.1.4.1_1.139xb76++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/dev_bundle/bin/npm
rebuild --no-bin-links --update-binary
Cannot download
"https://github.com/sass/node-sass/releases/download/v3.2.0/linux-x64-46_binding.node":
HTTP error 404 Not Found
gyp ERR! configure error 
gyp ERR! stack Error: 404 status code downloading tarball
gyp ERR! stack     at Request.<anonymous>
(/home/zkhan/.meteor/packages/fourseven_scss/.3.2.0.12lfg4f++os.linux.x86_64+web.browser+web.cordova/plugin.compileScss.os.linux.x86_64/npm/node_modules/meteor/compileScss/compileScss/node_modules/node-sass/node_modules/pangyp/lib/install.js:251:14)
gyp ERR! stack     at emitOne (events.js:82:20)
gyp ERR! stack     at Request.emit (events.js:169:7)
gyp ERR! stack     at Request.onRequestResponse
(/home/zkhan/.meteor/packages/fourseven_scss/.3.2.0.12lfg4f++os.linux.x86_64+web.browser+web.cordova/plugin.compileScss.os.linux.x86_64/npm/node_modules/meteor/compileScss/compileScss/node_modules/node-sass/node_modules/pangyp/node_modules/request/request.js:1255:10)
gyp ERR! stack     at emitOne (events.js:77:13)
gyp ERR! stack     at ClientRequest.emit (events.js:169:7)
gyp ERR! stack     at HTTPParser.parserOnIncomingClient
(_http_client.js:433:21)
gyp ERR! stack     at HTTPParser.parserOnHeadersComplete
(_http_common.js:103:23)
gyp ERR! stack     at TLSSocket.socketOnData (_http_client.js:322:20)
gyp ERR! stack     at emitOne (events.js:77:13)
gyp ERR! System Linux 4.4.0-34-generic
gyp ERR! command
"/home/zkhan/.meteor/packages/meteor-tool/.1.4.1_1.139xb76++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/dev_bundle/bin/node"
"/home/zkhan/.meteor/packages/fourseven_scss/.3.2.0.12lfg4f++os.linux.x86_64+web.browser+web.cordova/plugin.compileScss.os.linux.x86_64/npm/node_modules/meteor/compileScss/compileScss/node_modules/.temp-s2mg0r/node_modules/node-sass/node_modules/pangyp/bin/node-gyp"
"rebuild" "--libsass_ext=" "--libsass_cflags=" "--libsass_ldflags="
"--libsass_library="
gyp ERR! cwd
/home/zkhan/.meteor/packages/fourseven_scss/.3.2.0.12lfg4f++os.linux.x86_64+web.browser+web.cordova/plugin.compileScss.os.linux.x86_64/npm/node_modules/meteor/compileScss/compileScss/node_modules/.temp-s2mg0r/node_modules/node-sass
gyp ERR! node -v v4.5.0
gyp ERR! pangyp -v v2.2.1
gyp ERR! not ok 
Build failed

npm ERR! Linux 4.4.0-34-generic
npm ERR! argv
"/home/zkhan/.meteor/packages/meteor-tool/.1.4.1_1.139xb76++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/dev_bundle/bin/node"
"/home/zkhan/.meteor/packages/meteor-tool/.1.4.1_1.139xb76++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/dev_bundle/bin/npm"
"rebuild" "--no-bin-links" "--update-binary"
npm ERR! node v4.5.0
npm ERR! npm  v3.10.6
npm ERR! code ELIFECYCLE
npm ERR! node-sass@3.2.0 postinstall: `node scripts/build.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the node-sass@3.2.0 postinstall script 'node
scripts/build.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the node-sass package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node scripts/build.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs node-sass
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls node-sass
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!
/home/zkhan/.meteor/packages/fourseven_scss/.3.2.0.12lfg4f++os.linux.x86_64+web.browser+web.cordova/plugin.compileScss.os.linux.x86_64/npm/node_modules/meteor/compileScss/compileScss/node_modules/.temp-s2mg0r/npm-debug.log
Cannot download
"https://github.com/sass/node-sass/releases/download/v3.2.0/linux-x64-46_binding.node":
HTTP error 404 Not Found
gyp ERR! configure error 
gyp ERR! stack Error: 404 status code downloading tarball
gyp ERR! stack     at Request.<anonymous>
(/home/zkhan/.meteor/packages/fourseven_scss/.3.2.0.12lfg4f++os.linux.x86_64+web.browser+web.cordova/plugin.compileScss.os.linux.x86_64/npm/node_modules/meteor/compileScss/compileScss/node_modules/node-sass/node_modules/pangyp/lib/install.js:251:14)
gyp ERR! stack     at emitOne (events.js:82:20)
gyp ERR! stack     at Request.emit (events.js:169:7)
gyp ERR! stack     at Request.onRequestResponse
(/home/zkhan/.meteor/packages/fourseven_scss/.3.2.0.12lfg4f++os.linux.x86_64+web.browser+web.cordova/plugin.compileScss.os.linux.x86_64/npm/node_modules/meteor/compileScss/compileScss/node_modules/node-sass/node_modules/pangyp/node_modules/request/request.js:1255:10)
gyp ERR! stack     at emitOne (events.js:77:13)
gyp ERR! stack     at ClientRequest.emit (events.js:169:7)
gyp ERR! stack     at HTTPParser.parserOnIncomingClient
(_http_client.js:433:21)
gyp ERR! stack     at HTTPParser.parserOnHeadersComplete
(_http_common.js:103:23)
gyp ERR! stack     at TLSSocket.socketOnData (_http_client.js:322:20)
gyp ERR! stack     at emitOne (events.js:77:13)
gyp ERR! System Linux 4.4.0-34-generic
gyp ERR! command
"/home/zkhan/.meteor/packages/meteor-tool/.1.4.1_1.139xb76++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/dev_bundle/bin/node"
"/home/zkhan/.meteor/packages/fourseven_scss/.3.2.0.12lfg4f++os.linux.x86_64+web.browser+web.cordova/plugin.compileScss.os.linux.x86_64/npm/node_modules/meteor/compileScss/compileScss/node_modules/.temp-s2mg0r/node_modules/node-sass/node_modules/pangyp/bin/node-gyp"
"rebuild" "--libsass_ext=" "--libsass_cflags=" "--libsass_ldflags="
"--libsass_library="
gyp ERR! cwd
/home/zkhan/.meteor/packages/fourseven_scss/.3.2.0.12lfg4f++os.linux.x86_64+web.browser+web.cordova/plugin.compileScss.os.linux.x86_64/npm/node_modules/meteor/compileScss/compileScss/node_modules/.temp-s2mg0r/node_modules/node-sass
gyp ERR! node -v v4.5.0
gyp ERR! pangyp -v v2.2.1
gyp ERR! not ok 
Build failed

npm ERR! Linux 4.4.0-34-generic
npm ERR! argv
"/home/zkhan/.meteor/packages/meteor-tool/.1.4.1_1.139xb76++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/dev_bundle/bin/node"
"/home/zkhan/.meteor/packages/meteor-tool/.1.4.1_1.139xb76++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/dev_bundle/bin/npm"
"rebuild" "--no-bin-links" "--update-binary"
npm ERR! node v4.5.0
npm ERR! npm  v3.10.6
npm ERR! code ELIFECYCLE
npm ERR! node-sass@3.2.0 postinstall: `node scripts/build.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the node-sass@3.2.0 postinstall script 'node
scripts/build.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the node-sass package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node scripts/build.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs node-sass
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls node-sass
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!
/home/zkhan/.meteor/packages/fourseven_scss/.3.2.0.12lfg4f++os.linux.x86_64+web.browser+web.cordova/plugin.compileScss.os.linux.x86_64/npm/node_modules/meteor/compileScss/compileScss/node_modules/.temp-s2mg0r/npm-debug.log

**Comment by adriangrantdotorg** [comment]
I'm getting the same error

**Comment by adriangrantdotorg** [comment]
Actually see this, this worked for me [https://github.com/Dogfalo/materialize/issues/3602](https://github.com/Dogfalo/materialize/issues/3602)
