### ISSUE TITLE
Sidenav overlay does not hide when calling .sideNav("hide")

### ISSUE THREAD

**Issue by krmax44** [Dogfalo/materialize#3606]
When calling `$(".button-collapse").sideNav("hide")`, the `#sidenav-overlay` does not get hidden with the side-nav.

Workaround: `$("#sidenav-overlay").hide();`

**Comment by Nohinn** [comment]
http://codepen.io/Nohinn/pen/rrazqv

Am I missing something to reproduce that issue?

**Comment by krmax44** [comment]
@Nohinn weird. Have same version, but in my project it loves to bug around...
