### ISSUE TITLE
Carousel only showing top 213px

### ISSUE THREAD

**Issue by vandie** [Dogfalo/materialize#3607]
No matter what I do, I cannot seem to get the Carousel to show more than the top 213px. It just sets the style of the div to height 213px...

http://puu.sh/qZzaK/03f782609c.jpg

**Comment by acburst** [comment]
Can you post example code

**Comment by vishnu1991** [comment]
@vandie Create a codepen or post some example code so that we can solve your issue.
Thanks.

**Comment by acburst** [comment]
Fixed in bb5dd21
