### ISSUE TITLE
Wrong values are being selected in multiple select with optgroups

### ISSUE THREAD

**Issue by aregmk** [Dogfalo/materialize#3613]
Hi, I had troubles with multiple select which has optgroups.
I noticed that if I select some options in UI , I get wrong values in text input.
Here is the codepen: http://codepen.io/aregmk/pen/ZpYqpV

So I think I found a fast solution: add "optgroup" in line 3386 in function called setValueToInput.
So this line: var text = select.find('option').eq(entriesArray[i]).text();
should be changed with this: var text = select.find('optgroup, option').eq(entriesArray[i]).text();

Thanks.

**Comment by acburst** [comment]
Fixed in 7b67132
