### ISSUE TITLE
class .brand-logo.left not work

### ISSUE THREAD

**Issue by Isaiasdd** [Dogfalo/materialize#3614]
I have the code to test...

```
<nav>
    <div class="nav-wrapper">
        <a href="#" class="brand-logo left">Logo</a>
        <a href="#" class="brand-logo right">Logo</a>
    </div>
</nav>
```

see in [http://codepen.io/isaiasdd/pen/BLyvAK](url)

the line

`<a href="#" class="brand-logo left">Logo</a>`

don't have a 

```
nav .brand-logo.left{
    left: 0.5rem;
    padding: 0;
}
```

images:

![bug_cap_1](https://cloud.githubusercontent.com/assets/5838676/18275795/e652e8cc-741e-11e6-9e1f-0075b5f06c84.png)

![bug_cap_2](https://cloud.githubusercontent.com/assets/5838676/18275806/f5c50cc2-741e-11e6-90cf-c65d3a4d45eb.png)

**Comment by Dogfalo** [comment]
Added in 424d254fc23c3781364a26bd3b2c219ef8ff1be8
