### ISSUE TITLE
Issue with Grid in Firefox fullscreen

### ISSUE THREAD

**Issue by joshuaheisler** [Dogfalo/materialize#3618]
I have an issue with the CSS Grid in Firefox. When i open my webpage in fullscreen browser window with firefox it doesnt work, but in chrome there is not issue. Please see the attached files. The first one is firefox, the second one is chrome.

![firefox](https://cloud.githubusercontent.com/assets/20925843/18303641/7ab3ccce-74de-11e6-9ba2-481cf96082ea.png)
![chrome](https://cloud.githubusercontent.com/assets/20925843/18303646/7d9f41ca-74de-11e6-9cf4-adbe533a7785.png)

Is there any known solution to this or do you need more information?

**Comment by Kail0** [comment]
Link for your site would be indeed nice to provide, so as it's easier to find the issue. 
If you are running localhost, you might use [Fiddle](https://jsfiddle.net/) or [Codepen](https://codepen.io)
