### ISSUE TITLE
Change data of autocomplete input doesn't work 

### ISSUE THREAD

**Issue by cabri89** [Dogfalo/materialize#3619]
Hello,

I try to change the data of autocomplete input for a search bar but he doesnt work.

My new data is on the jsonString variable.

And I try to change data with this code :

`$('input.autocomplete').autocomplete({
            data: jsonString
         });
`

At the initialisation I initialise the data directly with the string and he work but when I change with a function he doesnt work.

You have an idea for resolve this problem ?

**Comment by mushtaqak** [comment]
@cabri89 I had faced the same issue, looks like your `jsonString` would not be correctly defined or empty ?

Can you provide the code snippet where you change the data ?

**Comment by acburst** [comment]
Fixed a bug with changing the data of an autocomplete in 14de2a0
