### ISSUE TITLE
Navbar dropdown - Not defaulting to hover:true

### ISSUE THREAD

**Issue by meteormanaged** [Dogfalo/materialize#3624]
https://github.com/Dogfalo/materialize/blob/master/navbar.html#L378

This states:
" By default, the dropdown menu is activated by hovering over the dropdown trigger. To activate the dropdown menu on click, pass { hover: false } into the above dropdown() function"

This does not appear to be the case for me.  I'm required to add `hover: true` to enable the feature.

**Comment by acburst** [comment]
Can you post some of your example code that is not working?

**Comment by eboye** [comment]
I think this is related to this issue: #3417

**Comment by meteormanaged** [comment]
I'm using a pretty standard navbar following the documentation to the letter.  Same results using exact example:

```
<!-- Dropdown Structure -->
<ul id="dropdown1" class="dropdown-content">
  <li><a href="#!">one</a></li>
  <li><a href="#!">two</a></li>
  <li class="divider"></li>
  <li><a href="#!">three</a></li>
</ul>
<nav>
  <div class="nav-wrapper">
    <a href="#!" class="brand-logo">Logo</a>
    <ul class="right hide-on-med-and-down">
      <li><a href="sass.html">Sass</a></li>
      <li><a href="badges.html">Components</a></li>
      <!-- Dropdown Trigger -->
      <li><a class="dropdown-button" href="#!" data-activates="dropdown1">Dropdown<i class="material-icons right">arrow_drop_down</i></a></li>
    </ul>
  </div>
</nav>
```

Using `$('.button-collapse').sideNav();` it does not open on hover, which seems to make the above reference statement incorrect.

Using `$('.dropdown-button').dropdown({hover: true});` gets the job done, so it appears to be defaulting to false.

Interestingly, the information on the dropdown page says the default will be false:

https://github.com/Dogfalo/materialize/blob/master/dropdown.html#L166

"If true, the dropdown will open on hover. Default: false"

Also seems to make the above reference statement incorrect, unless there's logic to determine if the dropdown is in the nav (I haven't looked yet.)

I don't think there's a code bug here.  I think there's just some mismatched documentation to sort.

**Comment by fega** [comment]
this is still an issue in the latest version  https://codepen.io/fega/pen/wdBEWj

**Comment by tomscholz** [comment]
This is just a problem with the docs. https://github.com/Dogfalo/materialize/blob/master/js/dropdown.js#L15
default hover state is false

**Comment by melineWb** [comment]
$('.dropdown-button').dropdown({hover: true}) does not work onClick on tablet devices
