### ISSUE TITLE
Close modal on other keys than ESC

### ISSUE THREAD

**Issue by JKamans** [Dogfalo/materialize#3625]
It would be nice to close the Materialize modal on other keys then ESC (for example Enter). Is it possible to add this to the options given to openModal()? Something like this:
...
openModal: function(options) {
      $('body').css('overflow', 'hidden');
      var defaults = {
        opacity: 0.5,
        in_duration: 350,
        out_duration: 250,
        ready: undefined,
        complete: undefined,
        dismissible: true,
        starting_top: '4%',
        closeKeyCode: 27 //<-- ESC on default
      },
...
       $(document).on('keyup.leanModal' + overlayID, function(e) {
          // Instead of--> if (e.keyCode === 27) {   // ESC key
          if (e.keyCode === closeKeyCode){ // <-- use this. Maybe even with an array of closeKeyCodes?
            $modal.closeModal(options);
          }
        });
...

**Comment by vishnu1991** [comment]
You can replace
**Materialize.js :** 
**Line 766**  
`if (e.keyCode === 27 )` 
with
`if (e.keyCode === 13 || e.keyCode === 9)`

or other keycodes
> Shift key = 16
> Ctrl = 17
> Esc = 27
> Alt = 18
> Spacebar = 32

Reply to this thread if you're not satisfied with the answer or if its not the expected solution.
Happy to help!
