### ISSUE TITLE
"material_chip()" Add parameter to empty tags/overwrite existing ones

### ISSUE THREAD

**Issue by FoxInFlame** [Dogfalo/materialize#3626]
Setting tags as empty would be a great feature. When dynamically loading tags, and dynamically hiding tags, the tags don't disappear.

**Comment by acburst** [comment]
Can you post some code to help explain your issue more?

**Comment by developeranirudhprabhu** [comment]
Yes it would be good to have this feature.

**Comment by developeranirudhprabhu** [comment]
I made some changes which help me achieve similar thing. I made following changes to materialize.js.

1. Ln 3794 commented the if block for double intialization
2. For all events added a "off" handler. For example
self.$document.off('click', SELS.CHIPS).on('click', SELS.CHIPS, function(e){
        $(e.target).find(SELS.INPUT).focus();
      });

This should allow us to add the data in following manner:
$('.selectedServices.chips').material_chip({'data':targetList});

Hope this helps

**Comment by matiasah7** [comment]
does it work?

**Comment by developeranirudhprabhu** [comment]
Yes. Worked for me. You can try it out.


Get Outlook for Android






On Thu, Sep 22, 2016 at 4:29 AM +0530, "Matías Abal" <notifications@github.com> wrote:





does it work?

**Comment by FoxInFlame** [comment]
I forgot to reply, it worked for me as well!

**Comment by developeranirudhprabhu** [comment]
I have not yet committed this to the branch!

**Comment by FoxInFlame** [comment]
My mistake.

**Comment by matiasah7** [comment]
I've tried but didn't work for me. Can you show how your final code looks?.

**Comment by developeranirudhprabhu** [comment]
Can you share your changes here?

**Comment by matiasah7** [comment]
Sure. I've Materialize v0.97.7

In Materialize.js:

   - Commented this lines 3793-3796: 

       `// if ($chips.data("initialized")) {

        //   // Prevent double initialization.

        //   return;

        // }`

   - Add a "off" to this lines (3817-3829) (I dont know if that's correct or i should add it to more lines):

`
  this.handleEvents = function(){
      var SELS = self.SELS;

      self.$document.off('click', SELS.CHIPS).on('click', SELS.CHIPS, function(e){
         $(e.target).find(SELS.INPUT).focus();
      });

      self.$document.off('click', SELS.CHIPS).on('click', SELS.CHIP, function(e){
        $(SELS.CHIP).removeClass('selected');
        $(this).toggleClass('selected');
      });

      self.$document.off('keydown', SELS.CHIPS).on('keydown', function(e){
        if ($(e.target).is('input, textarea')) {
          return;
        }


`
  


   - And in my controller (im using AngularJS):

`
  $(document).ready(function() {
            $('.modal-trigger').leanModal();
        });

        $('.chips-initial').material_chip({
            'data': $rootScope.emailChips
        });


`


EmailChips is a array like: [{tag: "string"},{tag:"String2"}] . I update it everytime that i change the currentFolder, and it works good. But my chips always are initialized with the first value of the variable.

Hope you can understand it, first post and bad english :D.

**Comment by FoxInFlame** [comment]
Add the off() method like you did, but for all the other on()s in that function. Lines 3883, 3888, 3892, and 3914. I don't know if that'll fix it for you, but that's what I did.

**Comment by matiasah7** [comment]
Thanks, i've done it but still load only the first time.

**Comment by developeranirudhprabhu** [comment]
off is to be added to all events

**Comment by developeranirudhprabhu** [comment]
Can you kindly tell what is your exact requirement?

**Comment by matiasah7** [comment]
Sure.

In my project, i've folders. Each folder can be shared. I use chips to share the folder.That's working well.

Now im trying to see shared users of each folder. Im trying to use chips initalized for that.  When i load the first folder (doesn't care which folder is) it shows correctly the shared people chip by chip. When i go to another folder still showing the first initialized chips. I use a variable to give the shared people, the variable is working correctly because i print it in my html under the chips and it changes everytime.

So what i need exactly is re-initialize the chips.

**Comment by developeranirudhprabhu** [comment]
Ok. I had similar kind off issue for which i made the above suggested changes. What you need to do is make all of the changes i suggested above. Then on every folder change trigger

$('.chips-initial').material_chip({
        'data': $rootScope.emailChips
    });

Also please make sure that the root scope values are updating successfully before the call. You add a breakpoint and ensure.
Hope this help.

**Comment by developeranirudhprabhu** [comment]
Also i was using ".chips" not ".chips-initial". Not sure if that makes any impact.

**Comment by matiasah7** [comment]
Now it works!!!!! 

I add the off method to all lines that you both said, comments the lines of prevent double initialization and change chips-initial for chips.

Thanks so much.

**Comment by developeranirudhprabhu** [comment]
Have added the fix. Hopefully they will merge it soon

**Comment by developeranirudhprabhu** [comment]
@acburst and @Dogfalo Please merge the fix or let me know if any more changes are needed. Will make those changes soon

**Comment by acburst** [comment]
Merged
