### ISSUE TITLE
Carousel time_constant not working

### ISSUE THREAD

**Issue by Saravana-Kumar-putta** [Dogfalo/materialize#3628]
Hi m using carousel and setting the property time_constant:2 it does not change the slide after 2 seconds and for more time i waited it doesn't change

**Comment by Nohinn** [comment]
Hello @Saravana-Kumar-putta , there is a misunderstanding on this property.
The time_constant property sets the time for the transition effect, not the time between transitions. The carousel control does not change from one element to the next one by itself, you should trigger it.
The only control doing that is the slider (currently).

**Comment by Saravana-Kumar-putta** [comment]
Thanks for the update @Nohinn , Is there any workaround for transition to be done by itself.

**Comment by Nohinn** [comment]
The only workarounds right now would be:
1) 
```
var constant = 2000;
var carouselInterval = setInterval(function() {
    $('.carousel').carousel('next');
}, constant);
```

Being the value of the constant var your custom value.
In case you want to stop the carousel, then you will have to clear the interval:
`clearInterval(carouselInterval);`

2)
Change the carousel control to the slider control.

**Comment by Saravana-Kumar-putta** [comment]
Thanks @Nohinn
