### ISSUE TITLE
autocomplete, leaving a wreckage of an empty list (IE)

### ISSUE THREAD

**Issue by yuya-tani** [Dogfalo/materialize#3631]
Hello.

Enter the characters in the form, to display the auto-complete,
In the case of the list of number of scroll bar is displayed
When you delete a form of the character from there
It will remain an empty list is displayed on the screen.
if the focus out, will remain.

![autocomplete_1](https://cloud.githubusercontent.com/assets/22019718/18377731/c236788c-76a3-11e6-9757-40cd6a7cd39d.png)
![autocomplete_2](https://cloud.githubusercontent.com/assets/22019718/18377738/ca91331e-76a3-11e6-8343-19b5a021f1c2.png)

Occurred in the IE, it did not occur in Chrome.
How can I solve this?

this code

http://codepen.io/yuya-tani/pen/yaXaGX

Enter "a" to the form.
If you select any will occur.
Internet Explorer 11

**Comment by yuya-tani** [comment]
this code

http://codepen.io/yuya-tani/pen/yaXaGX

Enter "a" to the form.
If you select any will occur.

**Comment by domicode** [comment]
how did you solve that @yuya-tani ?
