### ISSUE TITLE
Submit works only when clicking directly on the label of the button.

### ISSUE THREAD

**Issue by gudata** [Dogfalo/materialize#3633]
Submit works only when clicking directly on the label of the button. 
If I click bellow or above the label the ripple effect is shown but the form is not submitted. 

What am I doing wrong?

**Comment by vishnu1991** [comment]
Make a **codepen** or **provide some code snippet** so we can figure out whats the problem.

**Comment by gudata** [comment]
With Submit button code it works
It doesn't work with Input

```html
 <input type="submit" name="commit" value="Broken Submit" class="btn waves-effect waves-light" data-disable-with="Broken submit">
```

Clicking near the end of the button, ops the input, doesn't trigger the action. Here is the codepen

http://codepen.io/gudata/pen/wzWArb

**Comment by vishnu1991** [comment]
Looks like the class `.waves-effect` is overriding the default behaviour of the input submit tag.
You can replace 
```html
<input type="submit" name="commit" value="Broken Submit" class="btn waves-effect waves-light" data-disable-with="Broken submit">
```
with 
```html
<input type="submit" name="commit" value="Working Submit" class="btn" data-disable-with="Working submit">
```

**Comment by gudata** [comment]
It works, but without the waves effect. 

When presented, the waves effect is interrupted from the submit action, maybe it is not OK to have effect on the submit button. I haven't found what is the correct behavior for  material design.

**Comment by vishnu1991** [comment]
You can have a look at [Google Material Design Website](https://material.google.com/components/buttons.html#buttons-button-types) for material design specification on buttons.
Btw I also agree to you on
> maybe it is not OK to have effect on the submit button
as on submitting the user will directly land to other page/same page where waves effect will not be useful.
If u still want to use waves effect with submit button u can go for button tag instead of input tag.

**Comment by gudata** [comment]
On the link you point in the "Behavior" it is shown that the buttons should have effect, after all the material design for giving material feel.
I have workaround, thanks! You decide about the ticket.

**Comment by vishnu1991** [comment]
Yes actually button should have effect but in this case on using input the waves are overriding so we can use Button tag with waves effect which is working fine!

**Comment by Dogfalo** [comment]
You should use the <button> tag when using waves, see documentation:
http://materializecss.com/buttons.html
