### ISSUE TITLE
Dropdown.js - Inconsistent option property naming.

### ISSUE THREAD

**Issue by meteormanaged** [Dogfalo/materialize#3635]
Pretty simple

From https://github.com/Dogfalo/materialize/blob/master/js/dropdown.js#L11-L20

```
 var defaults = {
      inDuration: 300,
      outDuration: 225,
      constrain_width: true, // Constrains width of dropdown to the activator
      hover: false,
      gutter: 0, // Spacing from edge
      belowOrigin: false,
      alignment: 'left',
      stopPropagation: false
    };
```

All properties are `camelCase` except for `constrain_width` which is underscored.  Took a look in the code to find out why this option wasn't working for me intuitively.

The documentation DOES note this correctly but it should probably be swapped out to match all other options, and deprecated, or at least a secondary check added for convenience on the option.

**Comment by acburst** [comment]
Fixed in 66d37f0
