### ISSUE TITLE
Deinitialize material_chip?

### ISSUE THREAD

**Issue by FoxInFlame** [Dogfalo/materialize#3639]
It would be great to have an option to deinitialize, or remove the material_chip from an element.

Maybe like, `$(element).material_chip("remove")`

And that would remove all the chips and make it a normal textbox without any events.

**Comment by developeranirudhprabhu** [comment]
This is a must have feature

**Comment by developeranirudhprabhu** [comment]
Can you try adding following code at line 3785 in materialize.js

if ('destroy' === options) {
      return this.$el.empty().off();
    }
After making this change you can invoke this in following manner

$('.chips.tobeEmptied').material_chip("destroy");
 
Lemme know if it works for you.

**Comment by developeranirudhprabhu** [comment]
FYI, "remove" only removes the chips presently.

**Comment by developeranirudhprabhu** [comment]
@FoxInFlame Did you try the suggested fix?

**Comment by FoxInFlame** [comment]
The fix did make the input box empty, however, it also made it completely unclickable. I can no longer click and input text or tags.

**Comment by developeranirudhprabhu** [comment]
Can you please share some info about you are trying to do? Because the way i understood you wanted something like "destroy" method. I tested it on a div which i earlier initialized with "material_chip"

**Comment by developeranirudhprabhu** [comment]
@FoxInFlame Can you tell your exact requirement and if you were able to find a fix?

**Comment by tomscholz** [comment]
@FoxInFlame Are you still testing? ;)

**Comment by FoxInFlame** [comment]
@tomscholz Not anymore. I decided to try other methods.

**Comment by acburst** [comment]
Chips have been rewritten in v1.0.0 alpha and has the destroy method.
