### ISSUE TITLE
Gray area on mobile Parallax demo website

### ISSUE THREAD

**Issue by tofanelli** [Dogfalo/materialize#3640]
hey guys.... how's going?

does anyone know why the parallax demo gets a gray area when goes mobile? Does anyone knows how to fix it?

I already added a white class on body tag, added a white class on the container.... and nothing seems to really work =\.... 

I'm out of ideas at this time... =\

![image](https://cloud.githubusercontent.com/assets/5512922/18419352/2762e92a-782f-11e6-9fa9-63b1b921871f.png)

**Comment by vishnu1991** [comment]
Hello  @tofanelli,
The Parallax demo is working fine ( i.e. There is no grey area on mobile ) on all devices(Desktop,Tablet and even mobile).Make sure you're not missing any files.
[Download Parallax demo](http://materializecss.com/templates/parallax-template.zip)  from official site.

If you are still facing issue then pls reply to this thread.We'll be happy to help you!

**Comment by tofanelli** [comment]
Hi @vishnu1991 ....

how are you? Hope ok... 

Well.. the picture attached here was taken from the Materialize website, look into the URL. 


Cheers =)

**Comment by vishnu1991** [comment]
Hello @tofanelli , 
Yes i have checked it but its working fine there is no gray area (Checked on ios 10)!
Pls make sure you're checking the current version of materialize( v 0.97.7).
[Parallax Demo](http://materializecss.com/templates/parallax-template/preview.html)
