### ISSUE TITLE
Close sidenav on "back"

### ISSUE THREAD

**Issue by eboye** [Dogfalo/materialize#3641]
It would be cool if opening of sidenav would push history state so that when on mobile device user hits back button the sidenav closes. So it would replicate the mobile app behaviour.

I'll see if I can make this myself and make a pull request. But just wanted to ask if this is planned at all?

**Comment by acburst** [comment]
I don't think I've seen this without the use of a framework like angular or something. If you could get it working in a not too hacky way we'd love to see it in a PR

**Comment by eboye** [comment]
Sure. I'll try to make it as easy as possible and as optional parameter in sidenav function.

**Comment by eboye** [comment]
@acburst 
OK, I've made the implementation of back button that closes the sidenav:

https://github.com/eboye/materialize/commit/967c8ea778fc2f652ba1e31c097399d27aebaeef

I haven't made a pull request as I've changed the sideNav.js to comply with jslint that may not be what you want. But feel free to copy the parts of code that does this.

I haven't made the checks if the option is enabled for history pushing that may be needed for option turned off. I'll make those when I have some spare time.

**Comment by fega** [comment]
Closed due inactivity, feel free to reopen it if it is still necessary.

**Comment by eboye** [comment]
Any chance on this being merged?

**Comment by Dogfalo** [comment]
We're adding more methods to the sidenav so it will be easier to control sidenav.

**Comment by eboye** [comment]
@Dogfalo OK, great ... looking forward to it.
