### ISSUE TITLE
waves-effect stacking 

### ISSUE THREAD

**Issue by ong-leonard1** [Dogfalo/materialize#3642]
The waves-effect kept stacking whenever a button is press. If I pressed multiple times, the waves-effect will keep stacking as shown in the image. The waves would not disperse/dissolve. I did not change the css or js files. What may caused this issue?

Before clicking.
![snip20160912_1](https://cloud.githubusercontent.com/assets/6406553/18425558/162914f4-78ed-11e6-8622-2910d375ba02.png)

After clicking. 
![snip20160912_2](https://cloud.githubusercontent.com/assets/6406553/18425557/162841a0-78ed-11e6-81ad-9c306c6e8547.png)

`
                    <div class="row">
                        <div class="col s6">
                            <h5>Amazon.com Inc.</h5>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col s12">
                            <h6>Price (Last Close)</h6>
                            <a class="waves-effect waves-light light-blue darken-3 btn"><i class="material-icons right">shopping_basket</i>Add to Basket</a>
                        </div>
                    </div>`

**Comment by vishnu1991** [comment]
Hello @ong-leonard1 , 
Looks like the waves are working fine(waves are dissolving fine ) even after clicking it multiple times.
you can try this  [**codepen**](https://codepen.io/vishnu1991/pen/KgrqEB) .

If you're still facing issues reply to this thread.
We will be happy to help.

**Comment by ong-leonard1** [comment]
hi @vishnu1991,

yes, thank you so much. I don't know why, now it is working properly.

**Comment by ghstahl** [comment]
I have repoed this issue on my side as well.  
https://github.com/Dogfalo/materialize/issues/3709

**Comment by jejey** [comment]
> ghstahl commented on Oct 1, 2016 • edited
> I have repoed this issue on my side as well.
> 
> #3709 

I had the same issue because I added the html head file twice (with all links to js / css ... )

**Comment by tomscholz** [comment]
These issues are all duplicates:
https://github.com/Dogfalo/materialize/issues/1314
https://github.com/Dogfalo/materialize/issues/3642
https://github.com/Dogfalo/materialize/issues/686

For future discussion, please use this issue instead.
https://github.com/Dogfalo/materialize/issues/4344
