### ISSUE TITLE
lStack is not defined

### ISSUE THREAD

**Issue by andrey-helldar** [Dogfalo/materialize#3644]
When trying to open the window via the "$('#order-consult').openModal();", or "$('.modal-trigger').leanModal();" the console there is an error:

> http://savepic.ru/11350313.jpg

**Comment by andrey-helldar** [comment]
I'm using 0.97.7 version, downloaded from http://materializecss.com/getting-started.html (SASS)

**Comment by ishan28mkip** [comment]
+1 I am getting the same error

**Comment by andrey-helldar** [comment]
I found the cause of the error.
Combining jQuery and MaterializeCSS library files into one, I see this error.
If the file to load separately from each other, then there is no error, and everything works fine.

**Comment by ishan28mkip** [comment]
This is actually a small bug, they haven't defined lStack in the openModal function, so if JS runs in strict more it gives this error. I will open a PR to fix this.

**Comment by acburst** [comment]
I've rewritten the modal plugin here #3600. If you want to test it out from the latest master branch and see if the bug still persists

**Comment by ruta-goomba** [comment]
I am getting the same error. It seems like lStack variable in https://github.com/Dogfalo/materialize/blob/master/js/modal.js is still not initialised.
