### ISSUE TITLE
Date picker date display does not use same date for day/month/weekday/year label

### ISSUE THREAD

**Issue by 1Jajen1** [Dogfalo/materialize#3645]
The datepicker date display above the calendar does not use the same settings for actually displaying weekday/day/month/year. Weekday and day use either the selected time or the current time. Month uses the selected time or the viewset time and year always uses the viewset time. 

I'd suggest using either the selected time or the highlighted time for all options and/or giving to option to choose one of them.

**Comment by 1Jajen1** [comment]
Also in addition to this: the viewsetObject's date value is always 1 no matter what the highlighted date is.

**Comment by fega** [comment]
It look related with the fact that 
> pickadate.js is that it is currently looking for Project Maintainers and the last commit to [version4](https://github.com/amsul/pickadate.js/tree/4.0.0) was back in 2014 

#3061
