### ISSUE TITLE
materialize.css loading twice

### ISSUE THREAD

**Issue by droda59** [Dogfalo/materialize#3647]
Hi, I'm having a problem where materialize.css loads twice. 
I have the materialize sass code in my project, which I use to override variables, and compile it and include it in my style.css file. 
JSPM then seems to load the original materialize.css file, because there's a reference to it in the materialize.js file. 

What is the correct way to do this and override the variables in my sass files? 
Thanks!

**Comment by MariuszHenn** [comment]
You can use overrides in your package, to point JSPM which files shoud be included automaticly.

**Comment by droda59** [comment]
Yes it works! Thanks :)
```  packages: {
    "materialize-css": {
      "main": "bin/materialize.js",
      "map": {
        "bin/materialize.css": "dist/app/style.css"
      }
    }
  },```
