### ISSUE TITLE
select not working with angular

### ISSUE THREAD

**Issue by wayou** [Dogfalo/materialize#365]
the select form component not working with angularjs.

only works in `browser-default` mode. 

but the browser default is not that elegant with other elements on the page :(

**Comment by esalinas00** [comment]
I am having his same problem, please explain the work around.

**Comment by wayou** [comment]
can this be re-opened?

**Comment by Dogfalo** [comment]
What is the problem with the element?

**Comment by wayou** [comment]
hi @Dogfalo ,

have you checked the plunker? 

basically the data-binding of angular is broken after the materialized style applied on the `select` element.
while you can see the working one below within the plunker for a reference.

**Comment by lauterry** [comment]
+1 Please reopen this issue

**Comment by yurtaev** [comment]
+1

**Comment by Cerealkillerway** [comment]
+1

**Comment by flamingm0e** [comment]
+1

I have been fighting this for a few hours now

**Comment by Dogfalo** [comment]
https://github.com/Dogfalo/materialize/issues/706

**Comment by frknbasaran** [comment]
+1
It was lost me two hours

**Comment by charles4201** [comment]
+1 same kind of issue with select of angular-materialize, when choosing same option selected, the select doesn't close drop-down. But in class="browser-default", it works.
Please reopen this issue

**Comment by MorganChristison** [comment]
+1

**Comment by rogerwalt** [comment]
+1

**Comment by longstone** [comment]
+1

**Comment by yeager-j** [comment]
+1 I am also having this issue

**Comment by ochstobi** [comment]
+1

**Comment by tomscholz** [comment]
Just writing "+1" doesn't do anything. We should move the conversation to https://github.com/Dogfalo/materialize/issues/4529

**Comment by seifallah** [comment]
I know this is old but here is how I did a work arround
  $(document).ready(function() {
    setTimeout(function(){ $('select').material_select(); }, 1000);
    });

**Comment by arieltoledo** [comment]
Move to #2838 as its not working with angular or vue.

**Comment by rexsateesh** [comment]
**Its working for me but its temporary hack**

*.component.html
```
<div class="input-field col s12">
      <select formControlName="status" [(ngModel)]="selectedStatus" data-model="selectedStatus" class="select">
          <option [ngValue]="" disabled>Select</option>
          <option [ngValue]="1">Enable</option>
         <option [ngValue]="0">Disable</option>
     </select>
 <label>Status</label>
</div>
```

*.component.ts
```
ngAfterViewInit() {
        const self = this;
        jQuery(document).on('change', 'select', function(){
            var v = $(this).val().split(': '), model = $(this).attr('data-model');
            if(typeof v[1] != 'undefined') {
                self[model] = v[1];
            }
        });
 }
```
