### ISSUE TITLE
getWavesEffectElement iterates over parentElement - should use parentNode instead

### ISSUE THREAD

**Issue by JoschaMetze** [Dogfalo/materialize#3652]
Hi,

in waves.js function getWavesEffectElement you iterate over target.parentElement recursively. This leads ot problems in IE11 SVG-Elements where parentElement is undefined. Changing this to target.parentNode works as expected in all browsers.

Kind Regards
Joscha

**Comment by DetlefPeters** [comment]
I have experienced the same problems.
+1 please fix this issue

**Comment by DetlefPeters** [comment]
I opened a copy of this issue here: https://github.com/fians/Waves/issues/167
This seems to be the original source of waves.js

Best regards,
  Detlef

**Comment by Dogfalo** [comment]
Fixed in 741d47a092ba4f09ce841c7fa98def1ce0dcfd2c
