### ISSUE TITLE
tooltip() conflict with jQuery UI

### ISSUE THREAD

**Issue by Dmitrev** [Dogfalo/materialize#3653]
The tooltip in materialize stops working if you include jQuery UI

**To replicate**

Working Sample (without jQuery UI): 
https://jsfiddle.net/7on5358q/

Broken Tooltip, same source except with jQuery:
https://jsfiddle.net/7on5358q/1/

I tried to change the classname, but it's not a classname conflict:
https://jsfiddle.net/L1f63d9c/1/

**Comment by Nohinn** [comment]
Both jQuery UI and Materialize are UI frameworks.
The conflict is with the function call, both frameworks have a "tooltip" function.

Right now if you want to have both frameworks working at the same time:
    - Options A: materialize would need to refactor the function names. 
    - Options B: Build a custom jQuery UI bundle without adding the tooltip functionality.

**Comment by Dmitrev** [comment]
@Nohinn thanks, i guess the cleanest way would be to build a custom jquery-ui dist without the tooltip. Like this:
https://jqueryui.com/download/#!version=1.12.0&components=111111111111111111111111111111101111111111111111

I'll try this and update this topic

**Comment by Dmitrev** [comment]
See my previous comment as a workaround, i tested it.

**Comment by ArturGrigio** [comment]
Or you can use this library: https://github.com/sudiptpa/ui-sortable

Just run: 

`bower install ui-sortable --save`
