### ISSUE TITLE
IE10 Materialize waves-effect issue, after click event.target become waves-ripple, not the element i click

### ISSUE THREAD

**Issue by soonhuat** [Dogfalo/materialize#3655]
I have a "div" with waves-effect from materialize binded click event of alert "click div".

In this "div" contain "i tag" binded click event of alert "click i".

In IE11, firefox, and chrome, when i click on "i tag" will correctly fire the click event alert "click i", As expected. As I click the "div" will fire click event that alert "click div".

Only in IE10, when I click the "i tag" it fire alert "click div" which is click event from the "div". It should alert "click i".

Anyone could save me?

I have stimulate the scenario in jsBIn: http://jsbin.com/zodokezoqe/1/edit?html,css,js,output

**Comment by fega** [comment]
Do you still have this problem?
Closed due inactivity, feel free to reopen it if it is still necessary.
