### ISSUE TITLE
.btn's z-index is higher than the navbar's

### ISSUE THREAD

**Issue by timmyrs** [Dogfalo/materialize#3657]
The title pretty much says it. Please fix.

**Comment by Kail0** [comment]
The title pretty much doesn't say anything. Fixex navbar has `z-index: 998` and only one button has the same z-index, which is `.fixed-action-btn`. I didn't find any other btn with higher value.

Please, post which selectors

**Comment by timmyrs** [comment]
I don't seem to find it anymore. :|
