### ISSUE TITLE
Remove ttf and eot

### ISSUE THREAD

**Issue by ishan28mkip** [Dogfalo/materialize#3658]
Woff and woff2 have a combined 90% compatibility on http://caniuse.com/#feat=woff. Adding EOT and TTF is adding another 800Kb in the build and slowing down websites.

If removing is not a solution there should be some way for end users to easily opt out. I will also try to work out a simple solution.

**Comment by eboye** [comment]
It can be filtered out.

For example, I'm using gulp to copy fonts, so the task looks like this:

```
// ### Copy Vendor
gulp.task('copyVendor', function () {
    'use strict';
    //Materialize Fonts
    gulp.src(
        './bower_components/Materialize/dist/fonts/roboto/*.woff?',
        {
            base: './bower_components/Materialize/dist/fonts/roboto'
        }
    ).pipe(gulp.dest('./dist/fonts/roboto'));
});
```
Also I make my main.scss where I import everything from main scss of Materialize where I skipped _roboto.scss import and added mine without eot and ttf.
