### ISSUE TITLE
navbar with buttons and logo is not aligned with search

### ISSUE THREAD

**Issue by VicFrolov** [Dogfalo/materialize#3660]
I saw a closed issue regarding this from a few months back, but it seems it is now broken in google.

I tried:

```
<nav>
  <div class="nav-wrapper">
    <div class="row">
      <div class="col s10">
        <form>
          <div class="input-field">
            <input id="search" type="search" />
            <label for="search"><i class="material-icons">search</i></label>
          </div>
        </form>
      </div>
      <div class="col s2">
        <ul class="right">
          <li><a href="#"><i class="material-icons">close</i></a></li>
          <li><a href="#"><i class="material-icons">link</i></a></li>
        </ul>
      </div>
    </div>
  </div>
</nav>
```

but as you can see the search box is above the navbar

**Comment by VicFrolov** [comment]
Someone postd a suggestion using scss, how would I do this with just css/js/html?

**Comment by vishnu1991** [comment]
@VicFrolov 
Can you pls reference the  suggestion stated using "scss". so that we can help you to do it with html / js / css.
Thanks.

**Comment by VicFrolov** [comment]
Yeah, but not sure if this actually works, seems like they deleted it?

They Wrote:
`Solution ->

input[type="search"] {
height: 64px !important; /* or height of nav */
}`
