### ISSUE TITLE
Collabsible Accordion doesn’t reposition long-form contents to the top of the screen

### ISSUE THREAD

**Issue by iPhoneDevLog** [Dogfalo/materialize#3665]
When you first tap on any accordion section, it opens downward. After scrolling down several screens, you reach the next accordion section. Tapping on that section expands it upward, not downward, meaning that you have to manually scroll back up to come to the top of the new section. Ideally, the top of each opened accordion section should reposition at the top of the visible screen. This is true for card-reveal as well; obviously coders were not expecting several screens of content to be shoehorned into these fields, but only short content. Sorry about that! The Accordion feature is just a terrific one for mobile use, but not when implemented this way.

**Comment by iPhoneDevLog** [comment]
This could be resolved by allowing the designer to turn off automatic collapsing when a new section is tapped, then they will always open downward. Manually clicking/tapping on a section header again will collapse it.

**Comment by acburst** [comment]
There are 2 versions of the collapsible. The accordion enforces the rule that only one section can be open at a time. But you can set it to allow multiple sections to be open at the same time.
