### ISSUE TITLE
Grid leaving blank columns

### ISSUE THREAD

**Issue by wolfadverts** [Dogfalo/materialize#3668]
While developing we found this abnormal behaviour. We tried to find the cause and was in vain. Attached with the screenshot showing the issue.
![error](https://cloud.githubusercontent.com/assets/10608605/18608689/c7b419e8-7d0d-11e6-9c5e-86fa26e56057.png)

Any help is much appreciated. Thanks

**Comment by vishnu1991** [comment]
Hello @wolfadverts , 
This may be due to the **irregular image size or the content**  of the first card.from the the screenshot it looks like  due to the card1 is taking  extra height which makes  the below card to be  shifted to other side.

> It would be better if you make a sample codepen so that we can solve your problem.

**Comment by cvaraj** [comment]
@wolfadverts  you can fix this issue with css alone. write below code in your custom.css

.products col:nth-child(3n+1) {
    clear:left


}

**Comment by wolfadverts** [comment]
Will try this. Thanks @cvaraj @vishnu1991
