### ISSUE TITLE
getting autocomplete value after updating

### ISSUE THREAD

**Issue by mlourens** [Dogfalo/materialize#3669]
Maybe I'm just doing it wrong but I can't get the autocomplete value after selecting an option. The value of the input is set to the typed (partial) of the autocomplete instead of the full selected value. 

`
$('input.guests').on('change', function() {
    console.log($(this).val());
 });
`

after typing "**te**" and selecting the option "**test**" the value still return "**te**"

Any help is appriciated,
Maurice

**Comment by Nohinn** [comment]
The change event is firing when you click on the option because the input's blur event is fired as soon as you click on it.
You could try using a timeout in your change function, or bind a click event to the options suggested by the autocomplete control, to get the current value.
