### ISSUE TITLE
Dropdown Hover:true not working while hover menu

### ISSUE THREAD

**Issue by cvaraj** [Dogfalo/materialize#3670]
when i set hover:true in dropdown menu, while hover link its appear but i can't select the dropdown links it will disappear, any solution for this ?..

**Comment by vishnu1991** [comment]
@cvaraj 
Materialize.js
Line 463 
Replace
`  hover: false,`  with
`hover: true`
The dropdown will work and select even on hover.

**Comment by cvaraj** [comment]
thank you @vishnu1991 , its workinng . but when i use out of Materialize.js . like my footer or custom.js its not working ..

**Comment by vishnu1991** [comment]
you can change the respective minified file(`materialize.min.js`) same as the `materialize.js` file.

**Comment by cvaraj** [comment]
ok @vishnu1991 i will check .. Thank you

**Comment by LeviDooley** [comment]
The recommended solution to this bug is for us to modify your code? Lol. That seems a bit absurd. This bug should be re-opened, and actually fixed.
