### ISSUE TITLE
Carousel is not working for lower version of android phones

### ISSUE THREAD

**Issue by Swathi8** [Dogfalo/materialize#3671]
I'm using materializecss for my cordova project. 
I'm using the carousel - it works great except for lower versions of android. I'm currently checking with android v4.2. 
But error `ReferenceError: requestAnimationFrame is not defined` being thrown from the materiailize.js.

So I looked into materialize.js source code,  as `requestAnimationFrame` is undefined- tried with `webkitRequestAnimationFrame`  wherever the `requestAnimationFrame` is being used - then it started working in androind 4.2. I think this is the issue with backward compatibility.

**Comment by Swathi8** [comment]
Any work around to make it work, without editing the materiaize.js file?

**Comment by acburst** [comment]
Added a polyfill in 0e76801.

Can you try this latest commit and let me know if it works?
