### ISSUE TITLE
Grid gutter width

### ISSUE THREAD

**Issue by cvaraj** [Dogfalo/materialize#3673]
Is there any gutter width for grid, how to give space between grids, is there any solutions...

**Comment by stap123** [comment]
@cvaraj Not sure what you mean here without a little more information but the col class already provides padding to the left and right of a div with that class applied.

`.row .col {
    float: left;
    box-sizing: border-box;
    padding: 0 0.75rem;
}`

This should provide the gutter between columns within a row. If you provide more information I can clarify/correct my answer

**Comment by acburst** [comment]
The gutter width can be altered in our Sass variables file. Or you can override the padding like @stap123 showed above

**Comment by cvaraj** [comment]
thank you @stap123 and @acburst  i understood ..
