### ISSUE TITLE
dropdown plugin option beloworigin is not respected in latest mater branch

### ISSUE THREAD

**Issue by gideonso** [Dogfalo/materialize#3675]
I downloaded the latest master branch and build a drop down menu with the example code. The dropdown menu doesn't appear below the first level menu item even I set beloworigin to true. Then I switch back to a older version, everything is fine.

**Comment by Kail0** [comment]
Answered here: #3417

**Comment by gideonso** [comment]
Hi,

Thanks for your response. I already use the latest mater branch. The bug should have fixed but the problem persists. 

If I need to modify the core js in order to make the dropdown options work. I thing this is indeed a bug.

Gideon
