### ISSUE TITLE
Dropdown hover not working after 0.97.7 update

### ISSUE THREAD

**Issue by EclairOChocola** [Dogfalo/materialize#3677]
Hi, since i've update to 0.97.7, dropdown content does not activate on hover. I use it in navbar

My html:
`<ul class='right hide-on-med-and-down'>
						<li>
							<a href='#!' id='welcomeDropdown' class='dropdown-button' data-activates='dropdown'>
								<div class='chip'>
									<img src='<?php echo (isset($_SESSION['user']['']) ? (isset($_SESSION['user']['']) || isset($_SESSION['user']['']) ? $_SESSION['user'][''] : './images/'.$_SESSION['user'][''] ) : './images/loginLogo.jpg' ) ?>' alt='img'>
									<?php echo (!isset($_SESSION['']) ? 'Bienvenue ' : $_SESSION['user'][''].' '.$_SESSION['user'][''] ); ?>
								</div>
							</a>
						</li>
					</ul>`

Mys js: 
`$('#welcomeDropdown').dropdown({
	inDuration: 300,
	outDuration: 225,
	constrain_width: true, // Does not change width of dropdown to that of the activator
	hover: true, // Activate on hover
	gutter: 0, // Spacing from edge
	belowOrigin: true, // Displays dropdown below the button
	alignment: 'left' // Displays dropdown with edge aligned to the left of button
});`

**Comment by Kail0** [comment]
Answered here: #3417
