### ISSUE TITLE
Parallax does not work with jquary 3

### ISSUE THREAD

**Issue by chief-j** [Dogfalo/materialize#3678]
When reload page using f5 everything works nicely, bat if press menu button on site, i have error
## TypeError: a is undefined

r.fn.load() | jquery3.min.js:4
------------ | -------------
a.fn.parallax/</<() |  materialize.min.js:8
.each() |  jquery3.min.js:2
r.prototype.each() |  jquery3.min.js:2
a.fn.parallax/<() |  materialize.min.js:8
.each() |  jquery3.min.js:2
r.prototype.each() |  jquery3.min.js:2
a.fn.parallax() | materialize.min.js:8
<анонімно> | script.js:163
g/</j() |  jquery3.min.js:2 
g/</k<() | jquery3.min.js:2
in a line 163 in the script.js i have $('.parallax').parallax();

**Comment by kluzny** [comment]
Try running off master branch, issue may have been fixed in #3570, which is not in the cdn or release

**Comment by chief-j** [comment]
Parallax is working but not working modal
## TypeError: $(...).leanModal is not a function
```
$('.modal-trigger').leanModal();
```
