### ISSUE TITLE
Sidenav from right to left

### ISSUE THREAD

**Issue by vishnu1991** [Dogfalo/materialize#3679]
Currently sidenavigation is from left to right but it would be useful if materialize also support right to left sidenav(opening from right side).

**Comment by Isapour** [comment]
`<ul id="slide-out" class="side-nav right-aligned click-to-toggle">
	<li><div class="userView">
			<img class="background" src="images/office.jpg">
			<a href="#!user"><img class="circle" src="images/yuna.jpg"></a>
			<a href="#!name"><span class="white-text name">John Doe</span></a>
			<a href="#!email"><span class="white-text email">jdandturk@gmail.com</span></a>
		</div></li>
	<li><a href="#!"><i class="material-icons">cloud</i>First Link With Icon</a></li>
	<li><a href="#!">Second Link</a></li>
	<li><div class="divider"></div></li>
	<li><a class="subheader">Subheader</a></li>
	<li><a class="waves-effect" href="#!">Third Link With Waves</a></li>
</ul>
<div class="fixed-action-btn">
	<a class="btn btn-floating btn-large button-collapse" data-activates="slide-out" href="#">
		<i class="orange material-icons">view_headline</i>
	</a>
</div>
`
But it does not move from right to left
How do I change the direction of its movement

**Comment by Nohinn** [comment]
Hello @vishnu1991. Sidenav is supporting already that feature.
```
$(".button-collapse").sideNav({
    edge: "right"
});
```

You can see it in action in this codepen:
http://codepen.io/Nohinn/pen/ampVwV

**Comment by vishnu1991** [comment]
Thanks @Nohinn

**Comment by Isapour** [comment]
Thanks 🙏

**Comment by vishnu1991** [comment]
@Nohinn 
Looks like its not in the docs!

**Comment by Nohinn** [comment]
@vishnu1991 Here you have it: http://materializecss.com/side-nav.html#options
