### ISSUE TITLE
Slider not working at all

### ISSUE THREAD

**Issue by sabreking** [Dogfalo/materialize#368]
I initialized it in js properly and even used the exact code given on the website but the slider doesn't work

**Comment by kennethCarl** [comment]
what is .94 file and where i can download it?

**Comment by Dogfalo** [comment]
0.94 is an old release

**Comment by kennethCarl** [comment]
actually my slider doesn't work too, my current materialize source at the moment was from here http://materializecss.com/getting-started.html and when i used the source code above I only see gray background.

**Comment by BaurainO** [comment]
I have the same probleme, any issue ?

**Comment by BaurainO** [comment]
OK find why, check your console browse ( F12 / Console ) 
And there is this : Failed to load resource: the server responded with a status of 404 (Not Found)  http://localhost/materialize%200.95/css/style.css
Just remove %XXX of your URL

**Comment by kristianmandrup** [comment]
I have the same problem with the slider not working...

Trying to debug, I can see I never enter the `this.each` loop or the `$this.on('sliderStart', ` function.

```js
    init : function(options) {
      var defaults = {
        indicators: true,
        height: 400,
        transition: 500,
        interval: 6000
      };

      options = $.extend(defaults, options);

			console.log('init slider', options, this.each);

      return this.each(function() {
				console.log('for each slider');
```

This is what I log in the console and have just before I initialize the slider:

```js
          var id = this.id;
          var selector = '#' + id + '.slider';
          var options = this.options || {full_width: true};
          var sliderElem = $(selector);
          console.log('slider', selector, options, sliderElem);
          // sliderElem.slider({});
          // sliderElem.slider({});
          sliderElem.slider('start');
```

Output:

```js
slider 
selector: #my-slideshow.slider 
options: Object {} 
sliderElem: [prevObject: n.fn.init[1], context: document, selector: "#my-slideshow.slider"]`
```

Any ideas? I don't get any errors in my browser console. I'm trying to wrap the slider as a Polymer web component. Not sure if that could cause the problem. If so, then it is too "fragile"... IMO.

**Comment by kristianmandrup** [comment]
It seems to be related to this: `http://stackoverflow.com/questions/3106414/in-jquery-how-does-the-this-each-work` and perhaps due to the context being set to `document`??
