### ISSUE TITLE
Sidebar not loading

### ISSUE THREAD

**Issue by dolfvdberg** [Dogfalo/materialize#3680]
Good day

We recently updated to the latest version and the sidebar on mobile is not showing. I only shows a black overlay and not the side menu.

http://41.77.59.107:999/

**Comment by dolfvdberg** [comment]
Hi it works on .5 but then the Modals is not working. It closes but black overly stays

**Comment by fega** [comment]
Hello @dolfvdberg  did you solve your problem?
Closed due inactivity, feel free to reopen it if it is still necessary.
