### ISSUE TITLE
Callback triggers

### ISSUE THREAD

**Issue by larsvansche** [Dogfalo/materialize#3685]
It has happened several times now that I had to search the materialize.js file and add a trigger after a certain event, just to make sure I can perform code after a materializeCSS component was finished loading/running. 

My suggestion is that triggers get added after every event, so we can write callbacks ourselves. 

I'm not sure if this is the right place to post this, please inform me if it isn't.

**Comment by acburst** [comment]
We've added callback function parameters to some of our components. Can you point out specific ones where you need them?

**Comment by larsvansche** [comment]
I ran in to a lack of callbacks twice: once with tabs and once with pushpin. I added triggers in the materialize.js file that I can call with $("element").on("trigger", function() { /* do something */ });. 

Besides those two, I can't say for which components I will need callbacks in the future.

**Comment by acburst** [comment]
There is a callback parameter for tabs. Is that not sufficient? And I can look into adding some for  pushpin

**Comment by tomscholz** [comment]
Closed due inactivity. Feel free to reopen it, if it's still necessary.
