### ISSUE TITLE
Error when trying to show toast

### ISSUE THREAD

**Issue by wigvp** [Dogfalo/materialize#3686]
Hi, 
there is an error in the js shown console when I try to show a toast with `Materialize.toast("hi", 1000)`

> Velocity: First argument ([object HTMLDivElement]) was not a property map, a known action, or a registered redirect. Aborting.

What could this mean?

P.S.: The error is relatively new, but I didn't update the js file, so it's probably something in my code that causes Materialize to throw an error. I have no idea what this could be. :(

**Comment by acburst** [comment]
Can you post some sample code?

**Comment by Dogfalo** [comment]
Closed from lack of reproduciblity and response.
