### ISSUE TITLE
SideNav <li> nesting with icons

### ISSUE THREAD

**Issue by Tirke** [Dogfalo/materialize#3690]
I've discovered this issue while playing around with a SideNav. 
It is also possible to reproduce the issue in the documentation.
The issue is really easy to trigger :
1. Resize the window under 600px
2. Open the hamburger menu
3. Every subsequent menu item will be nested

[Pen replicating the issue](http://codepen.io/anon/pen/jrBjVj)

Potential fix : I've found that adding the class _waves-effect_ on anchor tags fix this issue by simply providing the rule overflow: hidden.

**Comment by sagarchoudhary96** [comment]
@Tirke i would like to work on it

**Comment by sagarchoudhary96** [comment]
@Tirke it's not getting fixed as you told . if i apply waves-effect class on components anchor tag then javascript li item comes normal but components li item still remains nested

**Comment by Tirke** [comment]
I didn't dig deeper as I only wanted to have a visually aligned effect.
Which I have with the class.
See [here](http://i.imgur.com/LJ5KAqm.png) on last version with waves-effect class on <a> tags.

**Comment by hanshenrik** [comment]
Weird error, I encountered the same.

This might have been introduced in `materialize:materialize@0.97.7`, as my menu looked fine before I did an update of my Meteor project. My previous version of Materialize was 0.97.6.

Adding the `waves-effect` class worked, but is a bit of a hacky fix I guess..

**Comment by fega** [comment]
fixed 
https://codepen.io/fega/pen/VbLjJe
