### ISSUE TITLE
SideNav new feature : options icon always visibles

### ISSUE THREAD

**Issue by Rebolon** [Dogfalo/materialize#3692]
Hi, 

To improve the design of the side-nav component it could be interesting to add an option to let the side-nav visible with inly the icons in the ul > li > a

[sample](https://files.gitter.im/Dogfalo/materialize/5VPK/side-nav.PNG)

For instance, the side-nav js component hide/show the menu.
It might add options to : 
- align the content on the right side of the menu
- don't collapse fully, but only remove text
- push the main content on the right to prevent the side-nav to be over it
- display the menu when a user touch the menu (mobile) or when the mouse is hover / click

**Comment by Kail0** [comment]
I don't think this is necessary since it's not a part (it's go against it) of [Material Design](https://material.google.com/layout/structure.html#structure-side-nav)

**Comment by TomDevs** [comment]
This doesn't actually go against material design; there is a "Mini SideNav" is the [Material Design Spec](https://material.google.com/patterns/navigation-drawer.html#navigation-drawer-behavior). I would love to see this feature added!

**Comment by Kail0** [comment]
@TomDevs Thank you for the clarification. Please, ignore my previous post.

**Comment by spatialbits** [comment]
+1

**Comment by tomscholz** [comment]
Do you mean something like this [here](https://demenzpilot.herokuapp.com/karte)? The application is a little bit broken. Don't blame me

**Comment by tomscholz** [comment]
![bildschirmfoto 2017-04-16 um 16 50 31](https://cloud.githubusercontent.com/assets/20381749/25072001/d6024e72-22c4-11e7-9ca4-5b96305e0e62.png)
![bildschirmfoto 2017-04-16 um 16 50 26](https://cloud.githubusercontent.com/assets/20381749/25072002/d65158f0-22c4-11e7-9152-3af31b8653b0.png)

**Comment by tomscholz** [comment]
Closed due inactivity and missing feedback. Feel free to reopen it, if it's still necessary.
