### ISSUE TITLE
Customizing the multi-select separator

### ISSUE THREAD

**Issue by shawndibble** [Dogfalo/materialize#3697]
I am using the multi-select for my project, however I have select options as "LastName, FirstName". As such, the comma separator makes it difficult to distinguish users. Is there a way to set the separator type when we initialize the material_select() function?

**Comment by acburst** [comment]
Can you explain a little more? I'm not sure i'm understanding what you are asking for.

**Comment by shawndibble** [comment]
So if you have a select box setup so you can select multiple options, it may show something like: Joe, Mike, David, John. And that is fine in most cases, however I am having a employee list that is lastname, firstname, so it looks like this: Davison, Joe, Barley, Mike, Langston, David, Smith, John. And that is difficult to distinguish each person. It would be nice to be able to set an option such as:

```
$('select').material_select({
     'separator': '; '
});
```
And thus get: Davison, Joe; Barley, Mike; Langston, David; Smith, John
