### ISSUE TITLE
fab icon text issue

### ISSUE THREAD

**Issue by joaosardinha** [Dogfalo/materialize#3698]
Firstly I want to say how awesome what you guys are doing is!
I'm hosting a website on firebase, this is how a fab looks when I run the index offline (expected behaviour): 
![image](https://cloud.githubusercontent.com/assets/15181917/18897381/d2796f56-8521-11e6-9502-e4f4ba090042.png)
This is how it looks on the web:
![image](https://cloud.githubusercontent.com/assets/15181917/18897403/f58bf428-8521-11e6-9a7a-1e0607ef25ea.png)

```
<div style="position: fixed; bottom: 0; left: 5%; bottom: 18% ">
	<a class="btn-floating btn-large waves-effect waves-grey white" >
		<i class="material-icons black-text" >search</i>
	</a>
</div>
```

**Comment by acburst** [comment]
This just means you aren't including the material icons correctly. Check out the icons documentation to find the stylesheet to include.
