### ISSUE TITLE
FAB to Toolbar added. Testing Needed!

### ISSUE THREAD

**Issue by acburst** [Dogfalo/materialize#3699]
I've made an initial version of a FAB that turns into a bottom toolbar. Similar to the effect shown here [fab-transition-toolbar](http://material-design.storage.googleapis.com/publish/material_v_4/material_ext_publish/0B8v7jImPsDi-ajMzVHp3VzJ4UkU/components-buttons-fab-transition_toolbar_02.webm). You can checkout the documentation for it under buttons, floating buttons on the master branch.

Here is the basic markup:

```
  <div class="fixed-action-btn horizontal click-to-toggle">
    <a class="btn-floating btn-large red">
      <i class="material-icons">menu</i>
    </a>
    <ul>
      <li><a class="btn-floating red"><i class="material-icons">insert_chart</i></a></li>
      <li><a class="btn-floating yellow darken-1"><i class="material-icons">format_quote</i></a></li>
      <li><a class="btn-floating green"><i class="material-icons">publish</i></a></li>
      <li><a class="btn-floating blue"><i class="material-icons">attach_file</i></a></li>
    </ul>
  </div>
```

You can also open and close programmatically:

```
 $('.fixed-action-btn.toolbar').openToolbar();
 $('.fixed-action-btn.toolbar').closeToolbar();
```

I would appreciate some feedback and testing on this new feature. Thanks everyone!

**Comment by quentinHydrobat** [comment]
Hey =)

Hoooo Sh\t this is awesome =D 
But i have no idea where i can use it on my project xD

As soon as i use it, i'll come back ;)

**Comment by apawsey** [comment]
Gonna try and do a test with it now...

**Comment by geminitydesigns** [comment]
Hey, I'm tyring to use this. Does it still work??

**Comment by acburst** [comment]
It is only available on the master branch and is not in our official release. You can try using it and I would appreciate any feedback you have
