### ISSUE TITLE
waves don't reach the edge

### ISSUE THREAD

**Issue by joaosardinha** [Dogfalo/materialize#3703]
![image](https://cloud.githubusercontent.com/assets/15181917/18935434/f35c3f94-85d7-11e6-9604-f124fe0c619b.png)

Okay, so this is happening when I click and hold in the edge of a view. 
Also the right side of every view doesn't seem to get affected by the waves, also noticeable on the image.

**Comment by fega** [comment]
Closed due inactivity, feel free to reopen it if it is still necessary.
