### ISSUE TITLE
Grid and HTML5 problems

### ISSUE THREAD

**Issue by ConsoleTVs** [Dogfalo/materialize#371]
First problem: Grid: http://i.gyazo.com/1a10be0a1e2b3259851bf841365b21d1.png
Code: http://hastebin.com/muduconega.xml

Second problem: HTML5: http://i.gyazo.com/e06c518befea613eeede89b5e56f40ef.png
Code: http://hastebin.com/leloviseqo.xml

**Comment by Dogfalo** [comment]
Resolved
