### ISSUE TITLE
Materialbox inside  <div class="col m4" > doesnt display picture as expected

### ISSUE THREAD

**Issue by abds5** [Dogfalo/materialize#3710]
Hi,
I want  use  the materialbox inside "div" whith col S12 m4 class  for responsive design, but when I click the image, the materialbox displays the image with the col m4 width and not with a normal width in the middle of the screen ( as the demo in Materialize web site).
can someone help to fix this issue? Thanks

what I expect: [http://i.stack.imgur.com/YRpe0.jpg)]
what I get: [http://i.stack.imgur.com/s75xV.png]
@acburst

**Comment by acburst** [comment]
I've tested this locally and its working for me. Do you have a live link? If not try recreating your problem in a [codepen](http://codepen.io/Dogfalo/pen/xbzPQV).

**Comment by abds5** [comment]
Thanks for your fast answer, I found the problem! It was a conflict with a JS  script^^
