### ISSUE TITLE
No 'chip' in 'chip.delete'

### ISSUE THREAD

**Issue by lunatolun** [Dogfalo/materialize#3711]
I have chip.add which functions normally but chip.delete doesn't 

```
$('.chips').on('chip.add', function(e, chip){
        //do stuff, chip is not undefined
});

$('.chips').on('chip.delete', function(e, chip){
    console.log(chip);
    //chip is undefined
});
```

**Comment by acburst** [comment]
I've tested this locally and it seems to be working. Have you tried this on the latest master commit?

**Comment by lunatolun** [comment]
My bad... No issue here

**Comment by brickmaker** [comment]
I've meet this question too, so how can I avoid this problem?
