### ISSUE TITLE
404 on Fonts

### ISSUE THREAD

**Issue by bryantp** [Dogfalo/materialize#3712]
Hello, 

I added in your project via bower 

`bower install materialize`

however, I am getting issues with gulp when trying to serve the files. It is unable to find the Woff files for the fonts:

```
home:1 GET http://localhost:3000/font/material-design-icons/Material-Design-Icons.woff2 404 (Not Found)
home:1 GET http://localhost:3000/font/material-design-icons/Material-Design-Icons.woff 404 (Not Found)
home:1 GET http://localhost:3000/font/material-design-icons/Material-Design-Icons.ttf 404 (Not Found)
```

I have also installed Material Design Icons via Bower, but that did not resolve the issue. Any idea why the files are not being served?

**Comment by barns** [comment]
I'm getting a similar error, but it's the Roboto font files that are 404ing for me. I believe the cause of this is that the css is looking for the font files in `yourproject/dist/fonts`, but the fonts are actually located in `yourproject/bower_components/materialize/dist/fonts`.

As a temporary fix, I've copied across the missing font files into `myproject/dist/fonts`, but this does seem like an issue the developers need to fix.

**Comment by bryantp** [comment]
That seems like a good work around, I will give it a try. However, I hate modifying my build for a third party component that isn't playing nice.

**Comment by Dogfalo** [comment]
@bryantp What version are you using? We no longer include material icons directly.
