### ISSUE TITLE
Uncaught TypeError: Cannot read property 'top' of undefined

### ISSUE THREAD

**Issue by stratoss** [Dogfalo/materialize#3713]
materialize.js:1456 Uncaught TypeError: Cannot read property 'top' of undefined

**Comment by acburst** [comment]
Can you post a codepen reproducing the error.

**Comment by stratoss** [comment]
Unfortunately not, I was too busy fixing issues to make a codepen and already fixed it with the proposed solution.

**Comment by mirandadp** [comment]
I've the same issue, to reproduce the error: goto input ('.select2-search__field') in select2, type any word, no include in lis, and then push arrow up.
 for example: go to examples page: https://select2.github.io/examples.html, and go to The basics\Single select boxes\ and turn it into this... ; open select2 Alaska, and type 'sjdlkjsdlkfjsdlkjfls' and then press keyup.

**Comment by fega** [comment]
Please provide a way to reproduce it. like a [codepen](https://codepen.io/fega/pen/BWeZaG)

Closed due inactivity, feel free to reopen it if it is still necessary.
