### ISSUE TITLE
IE11 appear into input select a cursor

### ISSUE THREAD

**Issue by gomezv9** [Dogfalo/materialize#3715]
Hi

The input select in IE11 hava a bug, this show me like a "Cursor" ( if I was going to write something ) when I open de input select.

It only appear in IE11

Any help with this bug..

Thanks

**Comment by tomscholz** [comment]
These issues are all duplicates:
https://github.com/Dogfalo/materialize/issues/4413
https://github.com/Dogfalo/materialize/issues/4315
https://github.com/Dogfalo/materialize/issues/4306
https://github.com/Dogfalo/materialize/issues/3715
https://github.com/Dogfalo/materialize/issues/3171
https://github.com/Dogfalo/materialize/issues/630

For the future discussion, please use this issue instead.
https://github.com/Dogfalo/materialize/issues/3790
