### ISSUE TITLE
Como cambiar el color de los Tab's | Materialize

### ISSUE THREAD

**Issue by Pelenchim** [Dogfalo/materialize#3717]
**# ## Atravez del siguiente codigo se puede cambiar los estilos de los tab's**

.tabs .tab a 
{
    font-weight: 700;                       /*para cambiar el grosor de la letra*/
    color: #2196f3;                         /*cambiamos el color de la letra*/
}
.tabs .tab a:hover                        /*Aca aplicamos los estilos que queremos que se ejecuten en el hover*/
{
    color: #8bccff;    
}
ul.tabs div.indicator                  /*para cambiar los estilos de la linea que indica cuando la pestaña esta activa*/
{
    background: #2196f3;                   /*cambiamos el color*/
    height: 3px;                  /* tambien cambiamos el tamaño si queremos*/
}
.tabs .tab a.active                  /*tmbien podemos de cambiar el estilo de el elemento activo*/
{
    font-weight: 700;
    color: #f0132c;
}

**Comment by acburst** [comment]
I'm sorry but issue's are english only

**Comment by Antonyselt** [comment]
Gracias, se aprecia toda la ayuda.
