### ISSUE TITLE
Scrolling in modal isn't working when using smooth page scroll scripts

### ISSUE THREAD

**Issue by JamesJGoodwin** [Dogfalo/materialize#3720]
The subject describes the situation. When i setup a smooth page scroll script and trying to open modal window - scrolling on it isn't working. I can't scroll content in modal window, but background is scrolling(which could not)

**Comment by note89** [comment]
Any solution to this ?

**Comment by tomscholz** [comment]
> We can not provide support for third party libraries. If you post an issue about a specific problem that is causing a conflict with a specific library we can look into it, but it is impossible to be perfectly compatible with everything - Acburst https://github.com/Dogfalo/materialize/issues/4365

**Comment by fega** [comment]
And maybe we can help but it's virtually impossible if you no provide a codepen
