### ISSUE TITLE
Let's add some padding to .brand-logo

### ISSUE THREAD

**Issue by ruslandzhumaev** [Dogfalo/materialize#3721]
![1](https://cloud.githubusercontent.com/assets/13280420/19051927/16fb7588-89b5-11e6-8bbd-5bfee86657f4.jpg)

**Comment by Kail0** [comment]
Just add nested `col s12` to `nav-wrapper`

**Comment by ruslandzhumaev** [comment]
[Done](https://github.com/Dogfalo/materialize/pull/3726)

**Comment by yashojha19** [comment]
add in your css
```
.brand-logo {
    padding-left: 12px !important;
}
```
