### ISSUE TITLE
Tooltips not working?

### ISSUE THREAD

**Issue by joaosardinha** [Dogfalo/materialize#3722]
I'm testing with the example from the docs and it just doesn't do anything.

``<a class="btn tooltipped" data-position="bottom" data-delay="50" data-tooltip="I am tooltip">Hover me!</a>``

![dgddg](https://cloud.githubusercontent.com/assets/15181917/19060513/cfda0f26-89e0-11e6-81d4-df3bdd5d1690.png)

All the other Materialize classes are working.

**Comment by pnishank** [comment]
I guess you need to Initialize in JS as shown in docs 
`$(document).ready(function(){
    $('.tooltipped').tooltip({delay: 50});
  });`
checkout docs [dialogs](http://materializecss.com/dialogs.html) under Tooltip section

**Comment by joaosardinha** [comment]
@pnishank The docs say that I only need to initialize it if I add them dynamically. But I had tried it and still doesn't work.

**Comment by Nohinn** [comment]
@joaosardinha are you using any other UI framework (like jQuery UI) that might be overriding the Materialize tooltip function?

**Comment by joaosardinha** [comment]
@Nohinn You're right, I was. It's working now. Sorry guys my bad

**Comment by simoazzo** [comment]
I have jquery-ui-min but it is before materlize, and still not working.

**Comment by Nohinn** [comment]
@simoazzo try adding this between your jquery-ui-min and materialize references to make sure there are no conflicts between them:
`$.widget.bridge('uitooltip', $.ui.tooltip);`

**Comment by simoazzo** [comment]
No Luck :( I have tried but nothing is showing.

**Comment by Nohinn** [comment]
@simoazzo  could you post a snippet of your code so anyone can take a look and try to solve your problem?

**Comment by simoazzo** [comment]
My markup is the same as demoed in materlize:

`  <a class="btn tooltipped" data-position="bottom" data-delay="50" data-tooltip="I am tooltip">Hover me!</a>
```
`
    <link rel="stylesheet" href="/foundation-zurb-template-master/bower_components/Materialize/dist/css/materialize.min.css">
    <link rel="stylesheet" href="/foundation-zurb-template-master/dist/assets/css/site.css">
   <script src="/foundation-zurb-template-master/bower_components/jquery/dist/jquery.min.js"></script>
    <script src="/foundation-zurb-template-master/jquery-ui-1.12.1.custom/jquery-ui.min.js"></script>
    <script src="/foundation-zurb-template-master/bower_components/Materialize/dist/js/materialize.min.js"></script>
```

I am using this in Angular 2

**Comment by sirb0rab0g1** [comment]
Hi i am new on angular JS 2 same with this problem i am putting tooltips but its not working anybody ?

**Comment by SatoAzuri13** [comment]
$(document).ready(function () {
          // the "href" attribute of the modal trigger must specify the modal ID that wants to be triggered
      
          $('#comment').tooltip({ delay: 50 });
      });

**Comment by htkcodes** [comment]
Please make sure to initialize it with the class that you're using it on.

**Comment by alan19031216** [comment]
maybe is you materialize version is different 
the new one is 
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0-rc.2/js/materialize.min.js"></script>
 <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0-rc.2/css/materialize.min.css">

**Comment by Exia01** [comment]
> @simoazzo try adding this between your jquery-ui-min and materialize references to make sure there are no conflicts between them:
> `$.widget.bridge('uitooltip', $.ui.tooltip);`

- This fixed the issue for me!! Thank you!!! I implemented a smooth scrolling with jquery UI but I had everything else with Materialize This is how I fixed my issue I am including a snippet for me people to see a visual 

`  // Smooth scrolling using jQuery easing
  $('a.js-scroll-trigger[href*="#"]:not([href="#"])').click(function() {
    if (
      location.pathname.replace(/^\//, '') ==
        this.pathname.replace(/^\//, '') &&
      location.hostname == this.hostname
    ) {
      let target = $(this.hash);
      target = target.length ? target : $('[name=' + this.hash.slice(1) + ']');
      if (target.length) {
        $('html, body').animate(
          {
            scrollTop: target.offset().top - 70
          },
          1000,
          'easeInOutExpo'
        );
        return false;
      }
    }
  });
  $.widget.bridge('uitooltip', $.ui.tooltip); //this bridges both tooltip
    /* Initializes tooltip */
    $('.tooltipped').tooltip();`


Hope this helps!
