### ISSUE TITLE
Responsive Table does not support multiple header rows

### ISSUE THREAD

**Issue by garrypolley** [Dogfalo/materialize#3727]
The columns do not stack in the rendered responsive view.  

See this code pen: http://codepen.io/garrypolley/full/kkxAGg/

This is what it looks like: 

<img width="809" alt="screen shot 2016-10-04 at 10 37 42 am" src="https://cloud.githubusercontent.com/assets/992175/19081072/9d7e98a6-8a1e-11e6-9573-1194b7b72b22.png">

I would expect the stacking to still take place when using multiple `<thead>` rows.  For now my solution is to remove the top headers via css, but that does not fix the root of the issue.  

See this for my current work around: http://codepen.io/garrypolley/pen/zKPmJP

<img width="814" alt="screen shot 2016-10-04 at 10 39 08 am" src="https://cloud.githubusercontent.com/assets/992175/19081122/ce1f6102-8a1e-11e6-92bb-7141cb6242f6.png">

I have more columns in my actual examples that span multiple.

**Comment by mescuderocuu** [comment]
I don't fully understand what you want to achieve with multiple thead, what i understand is that you want to display:
![try](https://cloud.githubusercontent.com/assets/22203496/20315741/38341542-ab1c-11e6-8067-aae7b1514064.png)

is that correct?

**Comment by garrypolley** [comment]
That's not the desired result. 

What I want is for this
<img width="1304" alt="screen shot 2016-11-15 at 11 16 03 am" src="https://cloud.githubusercontent.com/assets/992175/20315818/f3ca5412-ab24-11e6-9d94-b7576c8c1fb1.png">

To have this layout when it is made to a smaller screen.  (excuse the styles looking terrible):

<img width="858" alt="screen shot 2016-11-15 at 11 17 07 am" src="https://cloud.githubusercontent.com/assets/992175/20315964/9e1e5e9a-ab25-11e6-816b-a5c0c49cd8d9.png">


Basically the second level of headers should be represented in the row version of the column headers, but they are not represented at all. _All_ **column header** rows are translated into _one_  **column** when made into the responsive version of the table. 

My first header with `row 1 column 1` spans two columns and my second also spans two levels the `row 1 column 2`.  This is done to visually group headers together in the UI. As it stands right now the columns no longer maintain their meaning when it switches to the responsive version of the table.

**Comment by mescuderocuu** [comment]
I achieve this:
![try2](https://cloud.githubusercontent.com/assets/22203496/20320480/3551cb18-ab2f-11e6-98ea-37fd5463a2c1.png)

sorry for taking too long

**Comment by garrypolley** [comment]
That's what I was thinking, and it looks much better than my image copy/paste version.

**Comment by mescuderocuu** [comment]
Here is the link of how i did it
http://codepen.io/marcoswars/pen/MbjwoQ

**Comment by garrypolley** [comment]
That markup isn't valid markup according to the specification. 

Mozilla has some docs on it here: https://developer.mozilla.org/en-US/docs/Web/HTML/Element/thead

That's why I didn't do something like that.  Invalid markup often leads to accessibility issues for screen readers.

**Comment by mescuderocuu** [comment]
I think i understand your point, so if i do it like this
http://codepen.io/marcoswars/pen/MbjwoQ
It will be a valid markup?

**Comment by garrypolley** [comment]
That works, and is valid markup, the only downside is the unneeded elements. The consumer would need to know that they must put in "empty" elements. Which maybe the JavaScript could do that for them in the multi-tr thead case.

**Comment by mescuderocuu** [comment]
Ok ok, that was the same i was thinking

**Comment by mescuderocuu** [comment]
@garrypolley i think i manage how to do it via js:
http://codepen.io/marcoswars/pen/MbjwoQ

**Comment by fega** [comment]
@mescuderocuu thanks 

Closed due inactivity, feel free to reopen it if it is still necessary.
