### ISSUE TITLE
Page scrolls to top when modal opens

### ISSUE THREAD

**Issue by joaosardinha** [Dogfalo/materialize#3730]
This happens with every example from the docs. This also seems to happen with the Boostrap modal, but the solutions for it don't.

**Comment by stap123** [comment]
@joaosardinha They seem to working fine for me, could it just be your browser?

**Comment by joaosardinha** [comment]
@stap123 It's happening on Chrome, Edge and Firefox. Maybe this is the modal's normal behaviour?

**Comment by stap123** [comment]
@joaosardinha I can't get it to happen in Chrome, Edge, IE or Firefox so I don't think it's default behaviour. Is this happening in one of your projects or are you literally going to the materialize docs and clicking these buttons?

![image](https://cloud.githubusercontent.com/assets/10199083/19132438/5573744a-8b4b-11e6-86ec-a6d85a9b2863.png)

**Comment by joaosardinha** [comment]
It's happening on my project, the example in the docs work correctly. Here's my code:

	<div id="shareModal" class="modal bottom-sheet">
		<div class="modal-content" style="padding-bottom: 50px">
		     ...
		</div>
	</div>

`    $("#shareModal").openModal();`

I'm not using any other framework. Any thoughts?

**Comment by 1xxxx** [comment]
Hello! Receive mail, my English is poor, I did which part is wrong? Email is talking about me? If I were you ... I'm so sorry! Please forgive me, I am a beginner.Poor English + reading to perform translation, very difficult. apologize

**Comment by stap123** [comment]
What triggers the openModal() method? eg. a button click?

**Comment by joaosardinha** [comment]
Yes a button click.
This button:
```
<button class="btn waves-effect" id="sharePostButton2" >
    Share post
    <i class="material-icons right">share</i>
</button>
```

**Comment by stap123** [comment]
Is it inside a form tag? If so try adding preventDefault() to the end of the click event.

```
$('#btn').click(function (e) {
            $('#shareModal').openModal();
            e.preventDefault();
        });
```

**Comment by joaosardinha** [comment]
It isn't, I tried that anyway and no luck.

**Comment by Torcado** [comment]
Here's your solution (from the docs):
"If you prefer to use a button to open a modal specify the Modal ID in data-target rather than the href attribute."
BTW: Just adding "data-target" to a normal link (in addition to href) also prevents jumping to the top of the page.

**Comment by joaosardinha** [comment]
@Torcado It didn't solve the problem. Same still happens.

**Comment by Torcado** [comment]
Do you - by any chance - use "overflow-y: scroll" on your html tag?

**Comment by joaosardinha** [comment]
@Torcado Yes, and removing it solved it!

Although I need it to prevent the content from shifting to the right when a modal opens, is there a replacement that has the same effect?

**Comment by Torcado** [comment]
Glad I could help. That's the same issue I was struggling with yesterday … and yes: I also did use "overflow-y: scroll" to prevent some ugly shifting in my static navbar. ;)
Currently I do not have an alternative solution. Let me know if you come up with something!

**Comment by joaosardinha** [comment]
@Torcado Actually, my navbar doesn't shift, only views getting positioned by setting a distance from the page's sides (eg. right="10%"), this is my navbar:

```
<div class="z-depth-2" style="width: 100%; background-color: white; align-content: center; align-items: center;">
	<div style="width: 60%; margin: 0 auto;">	
		<ul class="tabs center-align section scrollspy" id="tabsContainer" >
			tabs here
	    </ul>
	</div>
</div>
```
Hope it helps

**Comment by kishorekumar080297** [comment]
I too had the same issue, but adding the $(document).ready function solved the issue and the page doesn't scroll now while invoking the modal
`  $(document).ready(function(){
       $('.modal').modal({
          dismissible: true, 
          opacity: .5,
          inDuration: 300, 
          outDuration: 200,
          startingTop: '4%',
          endingTop: '10%',
     );
     });`
Gist [URL]: (https://gist.github.com/kishorekumar080297/edf059eba16e12c967d55f7a4868b6a9)
Hope it helps

**Comment by robinloic** [comment]
I had the same issue. Nothing here worked for me. Blocking the modal's display to block functioned.
`.modal {
	display: block !important;
}`
Hope it helps.
