### ISSUE TITLE
 Feature Request: Rotated and Flipped Icons

### ISSUE THREAD

**Issue by darckyn** [Dogfalo/materialize#3732]
Hello to all materializecss developers.

Please consider placing a feature that allows you to rotate and(or) flip the icons of materialize.

Here is an example: https://zavoloklom.github.io/material-design-iconic-font/examples.html#rotated-flipped

Thank you very much.

**Comment by stap123** [comment]
You could solve this quite easily by adding some classes to your own css file. For example to rotate an icon by 45 degrees you could apply the below class to the material icon element.

```
.rotate-45 {
    -webkit-transform: rotate(45deg);
    -moz-transform: rotate(45deg);
    -ms-transform: rotate(45deg);
    -o-transform: rotate(45deg);
    transform: rotate(45deg);
}
```

`<i class="material-icons rotate-45">file_download</i>`

Would produce the following output:

![image](https://cloud.githubusercontent.com/assets/10199083/19123896/a1107f38-8b28-11e6-9ca4-0629d7572953.png)

**Comment by darckyn** [comment]
Thank you very much @stap123 for the help, your code save me :)

I am new to css and a rotate and flip class will be very useful.

It is precisely because I am new to css that I use materializecss in my project.
I look for a tool that has these features already implemented.
I'm really enjoying using materializecss and so I am requesting these functions.

@stap123 If you know how to do this (rotate and flip), please suggest a few lines of code for developers to add these simple functions.

thx again

**Comment by darckyn** [comment]
My request is not only to help me, but to all who use materializecss and makes it even better for everyone :)

For quick search I did, I realized that is not very complicated to do, and it's common to do on websites so I believe worth the effort.

If this function also work's well for images, would be perfect!

**Comment by stap123** [comment]
I guess adding some 'standard' rotate classes like 45, 90, 180 would be beneficial for the time invested but obviously you wouldn't want to be providing a class that allows for each individual degree of rotation I wouldn't of thought.

**Comment by stap123** [comment]
@darckyn Here you go

```
.icon-flipped {
    -o-transform: scaleX(-1);
    -moz-transform: scaleX(-1);
    -webkit-transform: scaleX(-1);
    -ms-transform: scaleX(-1);
    transform: scaleX(-1);
}
```

**Comment by darckyn** [comment]
Thank you @stap123 .

Another code that saved the day :)

Yes, the rotate class will be locked in 45, 90, 180.
If is need different rotations, then uses vertical and horizontal flip to provide more options.

**Comment by acburst** [comment]
I think classes like these are a little to easy to make yourself and they would just clutter up the framework.

**Comment by MonteShaffer** [comment]
Please see the font-awesome classes... http://fontawesome.io/examples/

They have flip/rotate in the examples.

I mixed with material icons like so.
`<i class="material-icons fa-flip-vertical">change_history</i>`
