### ISSUE TITLE
Modal not working properly when class modal-fixed-footer is taken out

### ISSUE THREAD

**Issue by johhansantana** [Dogfalo/materialize#3740]
Hello

I have a modal that works on every browser except on google chrome in a mac environment.

It does this if I take out the `modal-fixed-footer` class
![error](https://cloud.githubusercontent.com/assets/9933887/19170035/c920b756-8be4-11e6-94bb-ef54f1801dba.gif)

and this is with the class `modal-fixed-footer` in `<div id="myModal" class="modal modal-fixed-footer">`

![errorfixed](https://cloud.githubusercontent.com/assets/9933887/19170062/eb5e1cdc-8be4-11e6-96b9-bfc93cedc757.gif)

In safari it works properly with or without that class

**Comment by BleMot** [comment]
Hi, i have the same problem, any solution?

**Comment by acburst** [comment]
Can you post your code?

**Comment by graudeejs** [comment]
I have the same issue.
I found that removing ```waves-effect``` and ```waves-light``` classes form buttons in modal fixed it.

**Comment by graudeejs** [comment]
Found different modal for which above solution didn't work.

However I noticed that in @jsantana90 modal and my modals that are affected there's a common element - radio button.

If you comment out ```position: relative``` for ```:before``` and ```:after``` elements of radio button label then modal renders normally (apart from radio button obviously)

**Comment by acburst** [comment]
Hmm there was a recent fix I commited in 64d2b84 which handled a similar bug with radio buttons in modals. Could you test with our latest master version and let me know if you are still experiencing issues after this fix?

**Comment by graudeejs** [comment]
It's fixed in Chrome 53 Beta

**Comment by fega** [comment]
Closed due inactivity, feel free to reopen it if it is still necessary.

**Comment by nofearOnline** [comment]
none of the answers helped me I am trying to show a table of buttons in modal. when the modal is modal-fixed-footer scrolling does not affect the buttons only the table rows. when i remove it the modal works fine but the footer does not work.
