### ISSUE TITLE
Arrow Keys to navigate full-screen sliders

### ISSUE THREAD

**Issue by AdamHess** [Dogfalo/materialize#3741]
Most sites forget about this. When on desktop most people want to quickly hop through the slideshow using the arrow keys instead of clicking on each individual slide's next arrow. 

make the arrow keys move between slides. 

left-right are back and foward

up-down could be back and forward, or could be used to dismiss the full screen effect. 

hacker mode: 

use vim configurations for hjkl for the same effect

gamer mode: 

use wsad keys as above.

**Comment by Shivang-Bhandari** [comment]
@AdamHess Can i be of any help in resolving this issue ?

**Comment by littleread** [comment]
Is there any way to accomplish this?

**Comment by fega** [comment]
Is my personal opinion, but I never encourage the use of sliders, for this: https://yoast.com/opinion-on-sliders/

Also, if you want to make a Slide based website, you should use something more specific to your needs like reveal.js

**Comment by tomscholz** [comment]
I guess we will not look into add this into the core framework. It is easy enough to customize yourself.
https://jsbin.com/xetejiwese/edit?html,js
https://jsbin.com/xetejiwese
