### ISSUE TITLE
[Suggestion] Noto font

### ISSUE THREAD

**Issue by justinkruit** [Dogfalo/materialize#3744]
Hey,

Maybe it's a good idea to add the new Noto font to the font family, for when Roboto doesn't have the symbol? The font got released today by Google. https://www.google.com/get/noto/

**Comment by Aenoa** [comment]
Would be great ! Giving less work for those who aim for Cyrillic translations and such non-latin languages!

**Comment by Dogfalo** [comment]
We'll leave Roboto as the only included font since it is the primary material design font. If you need Noto for other languages, you'll have to add it yourself.

**Comment by smileytechguy** [comment]
@Dogfalo if you close this may as well close #3762
