### ISSUE TITLE
Form Range [no UI slider ] tooltips with longer values

### ISSUE THREAD

**Issue by Izopi4a** [Dogfalo/materialize#3748]
```
var slider = document.getElementById('priceSlider');

        noUiSlider.create(slider, {
            start: [0, 50000],
            tooltips: true,
            connect: false,
            step: 500,
            range: {
                'min': 0,
                'max': 50000
            },
            format: wNumb({
                decimals: 2,
                thousand: '.',
                postfix: ' $.',
            })
        });
```

in this case the number doesnt fit into the tooltip. Tested with chrome.

Is this a bug, or there is an css fix I have to apply for myself ?

//also does anyone knows how to add labels to this noUI slider ?

**Comment by jonasroessum** [comment]
I fixed this my manually adjusting the CSS. It was quite cumbersome to get working properly. It was clearly only meant for small number values.

**Comment by Izopi4a** [comment]
can you please post the css code?

**Comment by nimrossum** [comment]
https://gist.github.com/joglr/1618067911e482aea53ab65f6e9233da

**Comment by Izopi4a** [comment]
thanks man

**Comment by ZeCarlosCoutinho** [comment]
@joglr The code snippet not available anymore and I'm facing the exact same problem.
Do you, by any change, still have the code after 5 years? xD

**Comment by nimrossum** [comment]
> @joglr The code snippet not available anymore and I'm facing the exact same problem.
> Do you, by any change, still have the code after 5 years? xD

I changed my username since then, I've fixed the link above. Hope you can use it!
