### ISSUE TITLE
Material Icons Not Aligning Properly

### ISSUE THREAD

**Issue by ProProPro1** [Dogfalo/materialize#3751]
![dsdd](https://cloud.githubusercontent.com/assets/20212891/19209023/cfcabc54-8d02-11e6-9894-d9f829d819ba.jpg)

Material Icons Aren't Aligning Properly

CODE: `<span class="card-title"><i class="material-icons">warning</i> Welcome</span>`

**Comment by stap123** [comment]
Try adding the class "left" to the i with the material-icons class as below

`<span class="card-title"><i class="material-icons left">warning</i> Welcome</span>`

**Comment by ProProPro1** [comment]
@stap123 Doesn't Work. It Just Makes It Even Worse. 

CODE: `<span class="card-title"><i class="material-icons left">warning</i> Welcome</span>`
![err2](https://cloud.githubusercontent.com/assets/20212891/19215224/68e6c9ec-8d98-11e6-92cd-b2f5bf19ea0c.png)

**Comment by stap123** [comment]
Try the valign and valign-wrapper helper classes 

```
<div class="card">
    <span class="card-title valign-wrapper"><i class="material-icons valign">warning</i> Welcome</span>
</div>
```

![image](https://cloud.githubusercontent.com/assets/10199083/19215648/a57fc6b2-8d9b-11e6-8138-35e4c39e33b2.png)

**Comment by ProProPro1** [comment]
thanks :D It Works Very Well :D
