### ISSUE TITLE
Cannot adjust z-index for lean-overlay

### ISSUE THREAD

**Issue by egee-irl** [Dogfalo/materialize#3753]
The z-index for lean-overlay cannot be adjusted because the index itself is hard coded and dynamically added by JavaScript in the openModal: function(options) function.

There's supposed to be a CSS style that optionally allows for an override of the default value which is set at 999, but adjusting the z-index via styling has no affect, again because the z-index is set dynamically.

**Comment by Dogfalo** [comment]
You shouldn't need to change it as it will then conflict with other modals, but you can always use a `!important` if for whatever reason you have to change it.
