### ISSUE TITLE
form select with `browser-default` class looks like broken while running on Chrome browser in Android 6 device

### ISSUE THREAD

**Issue by rohanray** [Dogfalo/materialize#3756]
Hello, I am using form select with browser-default class in one of my app. I think this is broken in Android 6 Chrome

The demo for browser-default on http://materializecss.com/forms.html too doesnt work on Chrome browser on Android 6 device

**Comment by ntharani** [comment]
![2016-10-09_13-33-02](https://cloud.githubusercontent.com/assets/1318301/19223444/028c82a8-8e25-11e6-9d67-f73c23cf1a9c.png)

What is irritating is that it works on the Android Emulator. But have tried 4 physical devices now and in each case unable to select with class = "browser-default". Emulator image attached.

**Comment by Dogfalo** [comment]
Not seeing this issue on my own android device. It's also unlikely that we could break the native select interface even if we wanted to. Closing this unless more people run into this issue.
