### ISSUE TITLE
Validation of dynamic form with multiple select variations

### ISSUE THREAD

**Issue by Romanulus** [Dogfalo/materialize#3758]
Is there a 'more semantic' way of sniffing out which select box is being rendered to the screen?  

Obviously, calling 'material_select()' on your selects renders companion select boxes -- I find this difficult in sniffing out which select box is visible on the stage for validation (for instance when switching between Countries and their corresponding Province or State select boxes).

Hope this makes sense... thank you!

**Comment by jonasroessum** [comment]
Could you maybe illustrate this in a codepen? Use this template for easy materializing: http://codepen.io/pen/?template=oLakEj
It has all the materialize nescetities included.

**Comment by Romanulus** [comment]
Hi and thanks for taking the time to help; I ended up realizing it was a fairly simple fix.
Since I'm using materializecss and jquery validation I created a custom validation method for select boxes to first check if it is on the stage, then set my validation rules to ignore everything _but_ those select boxes (that could be hidden/switch dynamically).

Example:

```
  $.validator.addMethod('select_check', function(value, element, params) {
    if ($('#' + element.name + '-wrapper').css('display') != 'none') {
      // Item on stage...
      return (value != null);
    } else {
      return true;
    }
  });

$(".form").validate({
    ignore: ":hidden:not(#all, #the, #things)",
    // ...etc...
    rules: {
      email: {
        validate_email: true,
        required: true
      },
      ship_salutation: {
        select_check: true,
      },
      // etc...
    }
  });
```
    
Hopefully, if some poor soul comes Googling through here, is helped.
