### ISSUE TITLE
Navbar swipe to close

### ISSUE THREAD

**Issue by carlosperate** [Dogfalo/materialize#376]
This is more of a feature request, or improvement, I did a quick search and couldn't find a discussion about it, apologies if this is a duplicate. Would it be possible to implement the option to dismiss the Navbar by swiping to the direction where it came from? As far as I am aware the only way to do this is to click/touch outside of the Navbar.

**Comment by Dogfalo** [comment]
This was a removed feature due to an iOS bug. There is an existing issue on
it.
