### ISSUE TITLE
Tooltips stick if button opens new modal

### ISSUE THREAD

**Issue by ev5unleash** [Dogfalo/materialize#3764]
Hey Materialize Team,

Been having a small issue where a tooltipped button's tooltip will stick and not go away if the button opened a new popup modal. This happens about 50% of the time. My guess is that the onmouseout never gets called when the darkened div takes over. My workaround for now is to just delete the material-tooltip divs and re-call tooltip.

Thanks,

**Comment by jonasroessum** [comment]
In general, I also find the tooltips very glitchy. For example, if you move your mouse in and out too fast, ghosting occurs. Also, they work really poorly on mobile, where two taps are required to trigger a button.

**Comment by acburst** [comment]
can you post your code example?

**Comment by jonasroessum** [comment]
https://gfycat.com/FaithfulFrighteningGourami

http://codepen.io/jonasroessum/pen/BLOdpb?editors=1000

**Comment by vpezeshkian** [comment]
Any update on this? I also have issue with tooltips, I put it under `btn-floating`, first time it works fine but when I click on the button, the tooltip freezes and never disappear...

**Comment by Dogfalo** [comment]
Not sure what the solution would be for this, as the mouseleave wont be called if a new overlay takes over the current context. We've added a close method to tooltips in v1-dev which will allow you to close the tooltip on modal open.

**Comment by supperpiecheese** [comment]
A little workaround for anyone who is interested (@ev5unleash), if you add line 4530 in the materialize.js you can set a timer for the tool tip. The line of code I used is: `setTimeout(function(){_this27._animateOut();}, 1000);` and you can edit the `1000` to whatever time you want (in ms). I simply made it one second and it works for me! @Dogfalo, maybe consider making this an Boolean option? Cheers!

![image](https://user-images.githubusercontent.com/16927633/40735473-400e62fc-6409-11e8-916e-80a1a3d5ed57.png)
