### ISSUE TITLE
is there input addon ?

### ISSUE THREAD

**Issue by Izopi4a** [Dogfalo/materialize#3765]
I struggle to find how to make an input field and box/text next to the it.

Is there a way to do that ?

**Comment by jonasroessum** [comment]
Use labels. In the future, use gitter for getting help with using materialize. Please only submit feature requests and or issues you are experiencing.

**Comment by Izopi4a** [comment]
can you point me to this "gitter" please where i can get some help if I need ?

**Comment by jonasroessum** [comment]
There's a button at the bottom of the website that says chat. Click on that. 
http://materializecss.com
