### ISSUE TITLE
A complete and fully implemented stepper

### ISSUE THREAD

**Issue by Kinark** [Dogfalo/materialize#3770]
Hey, I missed a stepper in Materializecss framework, so I made one for myself: 

https://kinark.github.io/Materialize-stepper/

You can fork Materialize Stepper on github:

https://github.com/Kinark/Materialize-stepper

There is a horizontal version too!

Maybe you could implement it on materialize :D
It would be just copy and paste, since it was made based on the framework!

**Comment by odyright** [comment]
@Kinark great work. U might implement optional steps label too.

**Comment by Kinark** [comment]
Labels will be added in the next update, along with another new stuff :)
Thank you!

**Comment by RolandStuder** [comment]
@Kinark Are there any plans to make a pull request to integrate it into the standard materialize.css library?

**Comment by Kinark** [comment]
@RolandStuder Well, I would love. I didn't think about the possibility, but well, it would be an honor for me! I don't have such courage to create it, since materializecss is so big and I'm so small.

@odyright Well, I forgot to say, it's already implemented (among with other sutff)!

**Comment by RolandStuder** [comment]
@Kinark Well I hope the project maintainers will take note. I think a good quality stepper would be worth a lot. Thanks for your effort!

**Comment by stap123** [comment]
@Kinark Very nice! should definitely look at getting this in the framework.

**Comment by tomscholz** [comment]
This looks awesome!

**Comment by Kinark** [comment]
Thank you all :)

**Comment by fega** [comment]
it was added to

https://github.com/Dogfalo/materialize/wiki/Third-party-plugins

thanks!
