### ISSUE TITLE
Carousel with image is not working

### ISSUE THREAD

**Issue by mukatk** [Dogfalo/materialize#3773]
I'm trying to use the Materialize example but I got the following error:

```
<script type="text/javascript">
    $(document).ready(function () {
        $('.carousel.carousel-slider').carousel({full_width: true});
    });
</script>

<div class="carousel carousel-slider">
    <a class="carousel-item" href="#one!"><img src="http://lorempixel.com/800/400/food/1"></a>
    <a class="carousel-item" href="#two!"><img src="http://lorempixel.com/800/400/food/2"></a>
    <a class="carousel-item" href="#three!"><img src="http://lorempixel.com/800/400/food/3"></a>
    <a class="carousel-item" href="#four!"><img src="http://lorempixel.com/800/400/food/4"></a>
</div>

```

jQuery.Deferred exception: a.indexOf is not a function TypeError: a.indexOf is not a function

**Comment by kangfredy** [comment]
on my console is .carousel is not function?why?same as mkatk.carousel doesn't work.im using image slider but it's same as carousel.cannot work.

**Comment by nirajrajgor** [comment]
This is because it does not support the latest jQuery version.
Try using this - https://code.jquery.com/jquery-2.1.1.min.js version. As it is mentioned on their official website.
Here is the [working demo](http://codepen.io/nirajtech/pen/qagJZp)

**Comment by camnuckols** [comment]
Unfortunately, this still does not work. It works sometimes, but other times it is too slow to initialize and so the carousel ends up in a weird position and not aligned like it should, covering up other parts of the site. I just tested this now.

**Comment by fega** [comment]
@camnuckols could you check if this is still an issue?

**Comment by nirajrajgor** [comment]
@fega I have reproduced both the slider at codepen, it's working fine. U can check out the jquery, material js version used.
https://codepen.io/nirajtech/pen/rmagaL?editors=1010

**Comment by tomscholz** [comment]
Works for me :)
