### ISSUE TITLE
Modal not working properly when it has an unchecked radio button

### ISSUE THREAD

**Issue by sumitjaisingh** [Dogfalo/materialize#3774]
If you add couple of radio buttons to the modal and some content which causes the modal to have a scrollbar, then upon scrolling the modal does not scroll properly. Here is the sample code which you can use to reproduce the issue.

    <a class="waves-effect waves-light btn modal-trigger" href="#modal1">Modal</a>

    
    <div id="modal1" class="modal">
        <div class="modal-content">
            <h4>Modal Header</h4>
            <p>
                Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum viverra magna arcu, sit amet fringilla tortor aliquet sit amet. Curabitur vel est hendrerit, maximus arcu ut, tristique ipsum. Morbi dapibus ut nibh id eleifend. Etiam suscipit imperdiet enim. Aenean eget ante dolor. Aenean hendrerit purus sed gravida sagittis. Proin semper tincidunt mi sit amet malesuada. Praesent erat magna, suscipit sed viverra sit amet, tincidunt id elit. Mauris vitae purus ultricies, elementum sem at, pellentesque augue. Maecenas vel orci vel nisi sollicitudin lacinia non ut odio. Quisque lorem sapien, fermentum at arcu nec, laoreet iaculis velit. In hac habitasse platea dictumst. Integer consequat magna arcu, eget malesuada ante semper quis. Vivamus eu justo efficitur, scelerisque nisl eget, consequat nulla.
            </p>
            <p>
                Duis maximus porttitor ultrices. Pellentesque euismod velit lectus. Integer fringilla vel lacus vel sagittis. Sed vitae bibendum nisi. Sed quis dui malesuada, malesuada elit malesuada, consectetur mauris. Nullam hendrerit, diam vitae iaculis pulvinar, velit elit rhoncus nisl, vel finibus arcu nisl eget nibh. Nulla facilisi. Phasellus at elit non turpis congue lacinia. Aenean vitae erat nibh. Integer cursus nec velit id accumsan. Aliquam erat volutpat. Vivamus placerat turpis nec diam volutpat, in vestibulum felis luctus. Mauris lorem risus, vulputate a justo a, finibus pretium erat. Sed iaculis dolor eget dui pulvinar, a fringilla ligula accumsan. Quisque rhoncus eu massa vitae ultrices.
            </p>
            <p>
                Phasellus mollis feugiat dapibus. Curabitur tincidunt at leo sed porttitor. Nunc et luctus dui. Maecenas luctus arcu non varius volutpat. Phasellus imperdiet eget ex at porta. Donec sit amet elementum lorem. Fusce lectus nulla, pellentesque at justo quis, sodales dictum odio. Vivamus accumsan turpis sed maximus eleifend. Suspendisse potenti. Pellentesque ut commodo nisl. Aenean at mauris at ex volutpat efficitur.
            </p>
            <div class="input-field">
                <input name="group1" type="radio" id="test1" />
                <label for="test1">Red</label>

                <input name="group1" type="radio" id="test2" checked />
                <label for="test1">Red</label>
            </div>
            <p>
                Duis luctus neque ut commodo consectetur. In hac habitasse platea dictumst. Nunc id hendrerit felis. Morbi vitae dapibus risus, at euismod arcu. Quisque laoreet in velit quis rhoncus. Vestibulum blandit arcu nec turpis placerat, vel dignissim elit iaculis. Sed aliquam ex metus, euismod faucibus erat mollis vel. Pellentesque dapibus lacus in nisl aliquam, ac lobortis justo commodo. Integer facilisis erat auctor, maximus elit lobortis, consequat leo. Ut maximus scelerisque diam at aliquet.
            </p>
            <p>
                Suspendisse purus ante, pharetra in ipsum id, fringilla scelerisque tellus. Suspendisse potenti. Vestibulum at semper arcu. Nulla rhoncus turpis auctor ipsum aliquet efficitur. Quisque sodales leo sed sapien hendrerit egestas. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Nam nunc elit, consequat id tristique at, condimentum vitae ligula.
            </p>
        </div>
        <div class="modal-footer">
            <a href="#!" class="modal-action modal-close waves-effect waves-green btn-flat">Agree</a>
        </div>
    </div>

**Comment by iyochan32** [comment]
I'd Experienced this issues... T___T

Too bad that I can't change all modal with radio buttons in my app, so my hot fixes is just pop up the dialog box to convince user to use Firefox for better experiences...  :(

**Comment by acburst** [comment]
Hmm there were some odd z-indices on our radio button pseudo elements that I removed which fixes these issues. Hopefully they were unnecessary. 

Fixed in 64d2b84

**Comment by sumitjaisingh** [comment]
Thanks for a quick fix.
