### ISSUE TITLE
Different text color for when a tab becomes active

### ISSUE THREAD

**Issue by basplas** [Dogfalo/materialize#3777]
I want to use a different text-color for a tab when it's active. I tried it through a CSS override with the `.indicator class` (doesn't work), because I can't find an `.active class` for tabs.

Any thoughts on how I can implement this?

**Comment by neildocherty** [comment]
The active class is applied to the content of the tab. Check out this [codepen for an example](http://codepen.io/NDfool/pen/qaQGZJ)
