### ISSUE TITLE
Carousel Special Option: Events Ajax does not trigger a Toast in a second time on, from the button.

### ISSUE THREAD

**Issue by darckyn** [Dogfalo/materialize#3778]
Hello

I am using the carousel with special options to display multiple tables.

The User makes a click on a button within the carousel that activates an ajax event that does 2 things:
1. Update table.
2. Displays an Toast reporting success or failure.

Ajax event is usually activated on the first click (Performing the update on the table and displaying the Toast), but the second time on, the table is usually updated but the Toast is not displayed.

Only Toast is not displayed, ajax event is triggered and all the functions are performed correctly the second time.

I tried to reverse the order of events to see if solved (Toast first and then update the spreadsheet), but it still fails and the problem persists.

The most interesting is that this behavior occurs only within the carousel, if I do the same function outside the carousel it normally runs every time.

There appears no error message on the console browser or javascript.

I believe it can be a mistake Toast or Carousel or just me :/

Please someone help me with this problem.

OBS: Ajax update I do is only on the table.

tks. :)

**Comment by acburst** [comment]
Do you have some code examples?

**Comment by darckyn** [comment]
After the update release v0.97.8 this error has been corrected.

Thank you for all the help :)
