### ISSUE TITLE
Editable sliders

### ISSUE THREAD

**Issue by ventouris** [Dogfalo/materialize#378]
Hello everyone. Recently I found Polymer and I've started to redesign my website. However, it seems nonsense for me to do it with Polymer now and I was looking for a framework. Likely, I found MaterializeCSS.

The most important component for my website is the editable sliders like those in Polymer website. Is there any way to create the same thing with Materialize?

**Comment by acburst** [comment]
Would you mind linking the component? I'm not sure which one you are talking about.

**Comment by ventouris** [comment]
@acburst Of course

Here is the link --> https://www.polymer-project.org/components/paper-slider/demo.html

The second group with the Red Green Blue labels

**Comment by kmmbvnr** [comment]
Updated link - https://elements.polymer-project.org/elements/paper-slider?view=demo:demo/index.html&active=paper-slider
![paper slider polymer element catalog](https://cloud.githubusercontent.com/assets/282529/20552526/34590dfa-b176-11e6-97c6-094ad92bd6e4.png)

**Comment by tomscholz** [comment]
Checkout the http://materializecss.com/forms.html#range-input html5 range component
