### ISSUE TITLE
Better Documentation for select element

### ISSUE THREAD

**Issue by palerdot** [Dogfalo/materialize#3781]
Select element does not display if not initialized. This information is no where in the documentation and we have to dig through the internet to find a solution to this issue. The solution came from the following SO link - http://stackoverflow.com/questions/28258106/materialize-css-select-doesnt-seem-to-render

This should be documented in the forms page. Also, the other issue pointed out in the SO link regarding dynamic generation of select box also needs some consideration as it is a very common requirement. This issue might be a make or break issue for developers to adopt materialize.

**Comment by acburst** [comment]
The initialization part in the documentation is definitely in the docs. I guess it is a little far down. Also the update / destroy method is documented under initialization. I'm not sure what else is needed to help with dynamic generation though

**Comment by vontell** [comment]
I agree that this should be better specified; I just spent 30 minutes wondering why my copy and pasted code from the docs wasn't working, then I found this issue.

**Comment by acburst** [comment]
Added in 30ded5033a8d2712ab72bc337ee7c3d29ebf8852
