### ISSUE TITLE
Mixins doesn't work. 

### ISSUE THREAD

**Issue by thebiltheory** [Dogfalo/materialize#3783]
@Dogfalo Any idea why prefixer.scss is all commented out??
What is the right way to includes them?

**Comment by ninniuz** [comment]
@thebiltheory guess it's because they switched to [autoprefixer](https://github.com/postcss/autoprefixer)

**Comment by developeranirudhprabhu** [comment]
@acburst Can you please comment?

**Comment by Dogfalo** [comment]
We use autoprefixer now to get vendor prefixes into the builds, however, if in your project you can use them if you also use Sass, see this guide on how to use [mixins](http://sass-lang.com/guide#topic-6)
