### ISSUE TITLE
cannot set the top of my pushpin

### ISSUE THREAD

**Issue by falconmick** [Dogfalo/materialize#3784]
Hey guys. I have a pushpin which I am trying to set it's top via JQuery, but it's always 0:

```
    private resetPin() {
        let targetPinLocation = $('.pushpin-target');
        if (typeof (targetPinLocation.offset()) === 'undefined') {
            targetPinLocation = $('.card:first-child');
        }
        let offset = targetPinLocation.offset().top;

        console.log(`usign offset: ${offset}`);

        $('.toolbar-pushpin').pushpin({ top: offset });
    }
```

```
<div class="toolbar-pushpin-container col s1">
    <div class="col card white no-margin-top toolbar-pushpin">
        <div class="valign-wrapper">
            <ul class="valign center">
                <li><i class="material-icons clickable">add_circle</i></li>
            </ul>
        </div>
    </div>
</div>
```

What I am doign is calling resetPin when the page first loads and a pushpin-target is not set, therefore it will fallback to the first item in the cards. Then when I click on another card, I dynamically add the pushpin-target and I get the console log, but the top of the pushpin doesn't change.

Any ideas?

**Comment by acburst** [comment]
Hmm I did some testing locally and changing options on pushpins through click events seems to be working for me. Have you tried logging your offset variable to make sure it is not 0? and have you tried on the latest master branch?

**Comment by falconmick** [comment]
yeah it's definatly not 0. Could you share your test code? maybe i'm derping somwhere

**Comment by acburst** [comment]
If you have cloned our master repo I have a bunch of manual html testpages. You can look at the source for the pushpin one I wrote [here](https://raw.githubusercontent.com/Dogfalo/materialize/master/test/html/pushpin.html). But it would be easiest if you cloned our master repo and opened that html file in your browser. Let me know if that works for you
