### ISSUE TITLE
Scrollspy don't works if `id` contains dot or other special character

### ISSUE THREAD

**Issue by kmmbvnr** [Dogfalo/materialize#3785]
This line failed in case if `this.hash` contains dots or other special symbols.
```
		    var offset = $(this.hash).offset().top + 1;
```

jQuery requires such character to be escaped:

http://stackoverflow.com/questions/9930577/jquery-dot-in-id-selector

https://learn.jquery.com/using-jquery-core/faq/how-do-i-select-an-element-by-an-id-that-has-characters-used-in-css-notation/

**Comment by acburst** [comment]
Wow, to be honest I didn't even know id's could have all these special characters haha.

Fixed in 8623e7e
