### ISSUE TITLE
Simple button with icon have different width

### ISSUE THREAD

**Issue by horosgrisa** [Dogfalo/materialize#3786]
For Example
```html
<a class="waves-effect waves-light btn"><i class="material-icons right">cloud</i>button</a>
<a class="waves-effect waves-light btn"><i class="material-icons right">ic_file_download</i>button</a>
```

![rsz_ _ _ _2016-10-17_13-43-07](https://cloud.githubusercontent.com/assets/4980269/19434718/d755a294-946f-11e6-9943-4c359eb27059.png)

**Comment by acburst** [comment]
Not sure where you got the ligature ic_file_download. Just file_download seems to be the right size, not sure whats going on with ic_file_download.
