### ISSUE TITLE
Bug of input field and textarea label in Edge and firefox

### ISSUE THREAD

**Issue by yyh1102** [Dogfalo/materialize#3787]
![image](https://cloud.githubusercontent.com/assets/10328169/19446120/e0f01ad2-94c9-11e6-9349-50c22ee15143.png)
The label of the input field is innormal while it is normal in Chrome.
And the bug is "padding" property
![image](https://cloud.githubusercontent.com/assets/10328169/19446193/3b0961cc-94ca-11e6-8e60-705c287c2b55.png)
When i cancel "padding:0",and it goes well!
![image](https://cloud.githubusercontent.com/assets/10328169/19446160/1160d288-94ca-11e6-830e-185112ddd441.png)
![image](https://cloud.githubusercontent.com/assets/10328169/19446206/47bd9d7a-94ca-11e6-9af3-a2719c6fdb16.png)
And the bug shows in Edge and firefox~

**Comment by acburst** [comment]
Can you post the code that is causing this? Is it all input fields?

**Comment by yyh1102** [comment]
It is all input fields.I don't know which part of code causing this. I just import materialize.css v0.97.7 from bootstrap cdn and use it. I think the key point is the difference of compile for "padding:0" in Edge,Firefox and Chrome.

**Comment by geremiasseq** [comment]
I solved as follow:

input:not([type]),
input[type=text],
input[type=password],
input[type=email],
input[type=url],
input[type=time],
input[type=date],
input[type=datetime],
input[type=datetime-local],
input[type=tel],
input[type=number],
input[type=search],
textarea.materialize-textarea {
    padding: 1px;
}

**Comment by kmmbvnr** [comment]
I can't reproduce this on Edge
![screenshot from 2016-10-25 09-22-58](https://cloud.githubusercontent.com/assets/282529/19671984/afa1231a-9a94-11e6-9094-b66bb1efbdb2.png)

**Comment by fega** [comment]
it looks as a duplicate of #3822 but without a proper codepen is impossible to confirm

Closed due inactivity, feel free to reopen it if it is still necessary.
