### ISSUE TITLE
Label Positioning

### ISSUE THREAD

**Issue by dapplebeforedawn** [Dogfalo/materialize#3789]
The labels show to the far right depending on the whitespace and ordering in your markup:

![screen shot 2016-10-17 at 8 54 56 pm](https://cloud.githubusercontent.com/assets/193421/19460773/ba75f77c-94ac-11e6-8345-f982ab6d1b09.png)

This example HTML file reproduces:

``` html
<head>
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/0.97.7/css/materialize.min.css">
</head>

<body>
<div class="container">

<!-- The lable shows in a weird spot -->
<div class="input-field">
  <input id="comment" name="comment"><label for="comment">broken</label></div>


<!-- The label shows correct here.  The only difference from the block above -->
<!-- is that there's whitespace between the `<input>` and the `<label>` -->
<div class="input-field">
  <input id="comment" name="comment">
  <label for="comment">working</label></div>

<!-- This one also shows correctly.  It's identical to the first, broken,  -->
<!-- block; except the `<input>` and the `<label>` have been flip/flopped. -->

<div class="input-field">
  <label for="comment">also working</label><input id="comment" name="comment"></div>

</div>
</body>
```

I would credit this issue to user (my 😄 ) error, except the [docs](http://materializecss.com/forms.html#textarea) show the `<label>` tag coming after the `<input>`/`<textarea>` tag, so I expect this is a common point of confusion for new people.  For generated HTML the developer might not be able to specify the newlines.  I was using React when I noticed it.

I'm not sure if a doc fix or a code fix is more appropriate.  What do you think?

**Comment by acburst** [comment]
Hmm, I cant seem to reproduce the first issue. What OS and browser are you using? And have you tried on the latest master branch?

**Comment by dapplebeforedawn** [comment]
Ah sorry for the lack of detail!  I tried Chrome, Safari, and Firefox on OSX.

I'm seeing the same issue on master.  I checked it by changing the `<link>` tag above to a `<style>` tag, and copy-pasting in the [css from here](https://raw.githubusercontent.com/Dogfalo/materialize/master/dist/css/materialize.min.css)

**Comment by acburst** [comment]
The dist file is actually the release version css, not the latest css from master. To try the latest you can use [this css](https://raw.githubusercontent.com/Dogfalo/materialize/master/bin/materialize.css)

**Comment by kmmbvnr** [comment]
@dapplebeforedawn You need to use "row" and "col" classes for the fields as in the MaterializeCSS docs example - http://materializecss.com/forms.html

```html
<div class="container">
  <form>
    <div class="row">
      <div class="input-field col s12">
        <input id="comment" name="comment"><label for="comment">broken</label></div>
      </div>
    </div>
  </form>
</div>
```
