### ISSUE TITLE
Side Nav 

### ISSUE THREAD

**Issue by ksatria** [Dogfalo/materialize#3791]
When an icon (I've tried Material Icons and FontAwesome icons) included in li tag on side nav, the list broke
![sidenav problem](https://cloud.githubusercontent.com/assets/2881583/19469203/7c17074e-9544-11e6-88df-37e9fa37da06.PNG)

**Comment by kmmbvnr** [comment]
Check the https://github.com/Dogfalo/materialize/issues/3400 

If you using 0.97.7  release, just put "side-nav" outside nav
