### ISSUE TITLE
Problem with Form/Switches component for Thymeleaf Engine

### ISSUE THREAD

**Issue by yusser** [Dogfalo/materialize#3793]
I'm using MatirializeCSS in na Java project with Thymeleaf engine's and i found a problem.

After copy and paste this code:
`<div class="switch">
                                                <label>
                                                    Não
                                                    <input id="ativo" th:field="*{ativo}" type="checkbox" />
                                                    <span class="lever"></span>
                                                    Sim
                                                </label>
                                            </div>`

to do it works with Thymeleaf it's necessary add **th:field="*{ativo}"** attribute. This code is necessary to make thymeleaf work after inspect the code i note this diference: 
`<div class="switch">
                                                <label>
                                                    Não
                                                    <input name="_ativo" value="on" type="hidden"><input id="ativo" name="ativo" value="true" type="checkbox">
                                                    <span class="lever"></span>
                                                    Sim
                                                </label>
                                            </div>`

thymeleaf, automaticaly, include this code: `<input name="_ativo" value="on" type="hidden">`.  Study others template's engine i note this is a best pratice. So, to make Materialize and Thymeleaf works with this scenario i did this workaraound: 
`$('form .switch').each(function(i, o){
    let switcherField = $(o);
    let hiddenInput   = switcherField.find('input:hidden');
    let visibleInput  = switcherField.find('input:visible');
    if (hiddenInput.length > 0 && visibleInput.length > 0){
        hiddenInput.insertBefore(visibleInput);
    }
});`

**Comment by Dogfalo** [comment]
Since this is a problem when working with a specific framework we will be closing this.
