### ISSUE TITLE
Materialize Select Option Height Change Possible?

### ISSUE THREAD

**Issue by kevinfaguiar** [Dogfalo/materialize#3797]
There is a way to set the height of the options in a select dropdown? I want to make them be more tiny.
Default Height of Option:
![this to be](https://cloud.githubusercontent.com/assets/18222497/19520304/89f2630e-95ee-11e6-9538-2803b87cb8d4.png)
What I want:
![like this](https://cloud.githubusercontent.com/assets/18222497/19520323/9cc50bbc-95ee-11e6-8969-12d81eaa076c.png)

**Comment by acburst** [comment]
If you are using Sass you can change the variable $dropdown-item-height in our _variables.scss file. Otherwise you can simply write your own css overriding our styles.

**Comment by scraggelz** [comment]
I'm also running into this issue. I've tried overriding with height and line-height attributes but the select input is not changing size.

**Comment by meo1** [comment]
I have the same problem.

**Comment by meo1** [comment]
I guess I solved the problem, my solution may help you:

`select-wrapper input.select-dropdown{
    height:25px;
}
.dropdown-content li {
 min-height: 25px;
  line-height: 1rem;
}
.dropdown-content.select-dropdown li {
  margin:0;
  padding:0;
  height:25px;
}
.dropdown-content.select-dropdown li span{
  margin:0;
  padding:0;
  }`
