### ISSUE TITLE
Materialize Dropdown behind Label, Input and Select Elements

### ISSUE THREAD

**Issue by kevinfaguiar** [Dogfalo/materialize#3798]
I have a mini sidemenu, and when I hover above the icons on this mini sidemenu, a dropdown appears with pages for the user. It's working as expected, except by the fact the dropdown content seem like behind any Label, Input or Select elements, as below:
![bug1](https://cloud.githubusercontent.com/assets/18222497/19527312/50d5c71a-9606-11e6-907e-1a0210ee32d9.png)
![bug2](https://cloud.githubusercontent.com/assets/18222497/19527317/542e2cc2-9606-11e6-9f43-a09b67cad4f7.png)
There is a way to correct this or, at least, put the dropdown content of the mini sidemenu above everything?

**Comment by acburst** [comment]
Can you post some code on codepen or something? It will help us debug

**Comment by kevinfaguiar** [comment]
Seems like a stacking context issue. 
Already fixed this though setting the z-index of the .sidenav-mini (the div of all the mini sidenav). Early I was setting the dropdown-content z-index, which was not working.
