### ISSUE TITLE
Multiple checkboxes not working with Leaflet web-mapping Overlay toggle groups

### ISSUE THREAD

**Issue by Mapamatician** [Dogfalo/materialize#3802]
I am using Materialize 0.97.7 with Leaflet 1.0.1 (latest)

```
    <script src="https://cdnjs.cloudflare.com/ajax/libs/leaflet/1.0.1/leaflet-src.js"></script>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/leaflet/1.0.1/leaflet.css">
```

When I try to create an overlay with multiple checkboxes to toggle items, no checkbox(es) appears, only labels. If I switch CSS cdn to another framework, they appear. 

Leaflet code for debudding in case someone is interested:
http://leafletjs.com/reference-1.0.0.html#layergroup

```
// items to toggle
var myItems = new L.LayerGroup();
// bind popup to each item once checkbox is selected
L.marker([lat, lon]).bindPopup('Item').addTo(myItems);
// create overlays multi-checkbox selection
var overlays = {
    Items = myItems
};
// add overlays to the web-map
L.control.layers(null, overlays).addTo(map);
```

This is obviously not a Leaflet issue as it works fine with other CSS

Can anyone offer a fix? 

Thanks

**Comment by Mapamatician** [comment]
Thinking out loud here but as a quick fix, would it be possible to have a div with a class that could ignore Materialize CSS? 

Within this div one could add the map, add another CSS and keep working until there is a proper fix.

**Comment by Mapamatician** [comment]
I have attempted to edit the Leaflet source to change checkboxes to a switch with no luck, can someone provide input on this first Javascript fix?
```

Original source code: 
https://github.com/Leaflet/Leaflet/blob/63fd4edc76893ab2a2f83d54e703e0a4da73de7b/src/control/Control.Layers.js#L282

my first github attempt: 
var SwitchClass = function (obj) {
		var label = document.createElement('label'),
		    checked = this._map.hasLayer(obj.layer),
		    input,
		    span;

		if (obj.overlay) {
			input = document.createElement('input');
			input.type = 'checkbox';
			span = document.createElement('span');
			span.className = 'lever';
			input.className = 'leaflet-control-layers-selector'; 
			input.defaultChecked = checked;
			console.log(input);
			console.log(span);
		} else {
			input = this._createRadioElement('leaflet-base-layers', checked);
		}

		input.layerId = L.stamp(obj.layer);

		L.DomEvent.on(input, 'click', this._onInputClick, this);

		var name = document.createElement('span');
		name.innerHTML = ' ' + obj.name;

		// Helps from preventing layer control flicker when checkboxes are disabled
		// https://github.com/Leaflet/Leaflet/issues/2771
		var holder = document.createElement('div');

		holder.className = 'switch';
		label.appendChild(holder);
		holder.appendChild(input);
		holder.appendChild(span);
		holder.appendChild(name);
		

		var container = obj.overlay ? this._overlaysList : this._baseLayersList;
		container.appendChild(label);

		this._checkDisabledLayers();
		return label;
	};
```

**Comment by fega** [comment]
Please provide a way to reproduce it. like a [codepen](https://codepen.io/fega/pen/BWeZaG)

Closed due inactivity, feel free to reopen it if it is still necessary.

**Comment by rikyperdana** [comment]
It also happened to my project and still there's no way around :(

**Comment by shahryaramd** [comment]
Have a look at this [thread](https://stackoverflow.com/questions/40155017/materialize-css-not-showing-multiple-checkboxes-with-leaflet-web-mapping-overlay) that creates a workaround
