### ISSUE TITLE
Toast Removal

### ISSUE THREAD

**Issue by FoxInFlame** [Dogfalo/materialize#3809]
Let's say you have a Materialize.toast that shows "Loading...". The code would be: `Materialize.toast("Loading...")`

Now, since the toast doesn't have a timeout, the toast doesn't disappear. You want to make the toast disappear in another function.

I would love to see a `Materialize.toast().remove()`, to remove all toasts, or maybe another function to remove the current one.

**Comment by NitroBAY** [comment]
If that can help you a bit you can do that
```
// toast takes (message, thetime, theclass), if you set second param (time) to null toast will never dismiss automatically 
Materialize.toast($message, null, 'offline-toast');
$('.offline-toast').remove();
```

**Comment by Nexxado** [comment]
@NitroBAY thats a nice workaround, but i really want every toast to have a default timeout (unless specified) and the next toast will only show after the previous one timed out.

**Comment by NitroBAY** [comment]
I wouldn't like a default timeout, and in any way add such a feature would be compatibility breaking.

**Comment by smitthakkar96** [comment]
@NitroBAY according to materialize documentation you can pass the third parameter as className

`Materialize.toast(message, displayLength, className, completeCallback);`

So To remove the toast you can use the below method I use to dismiss Toast

```
Materialize.dismissToast = function(className){
  $("#toast-container ." + className).remove();
}
```
The above method will remove the toast from toastContainer.

**Comment by smitthakkar96** [comment]
Also checkout pull request [https://github.com/Dogfalo/materialize/issues/1317](#1317)

**Comment by NitroBAY** [comment]
@smitthakkar96 I know you can pass a className, I used className in my first example to show @FoxInFlame how you can add a className to remove one or many toast (depending if you defined one class per toast or one class per all toasts)

**Comment by NitroBAY** [comment]
@smitthakkar96 maybe you wanted to talk to talk @someoneelse

**Comment by smitthakkar96** [comment]
@NitroBAY woops didn't see that

**Comment by tomscholz** [comment]
Closed due inactivity
