### ISSUE TITLE
Second Level Collapsible

### ISSUE THREAD

**Issue by ProProPro1** [Dogfalo/materialize#3810]
When I Try To Put Another Collapsible Inside Of Another Collapsible. It Doesn't Work.

IMAGE: 
![wqd](https://cloud.githubusercontent.com/assets/20212891/19615282/5016a4ea-97fd-11e6-8b13-4955fd1ec4d2.jpg)

CODE: `<li class="no-padding"><ul class="collapsible accordion" data-collapsible="accordion">
    <li>
    <div class="collapsible-header">#1<i class="material-icons right blue-text">arrow_drop_down</i></div>
    <div class="collapsible-body">
    <a href="#">content</a>
    <a href="#">content</a>
    <a href="#">content</a>
    <a href="#">content</a><ul class="collapsible accordion" data-collapsible="accordion">
    <li>
    <div class="collapsible-header">#2<i class="material-icons right blue-text">arrow_drop_down</i></div>
    <div class="collapsible-body">
    <a href="#">content</a>
    <a href="#">content</a>
    <a href="#">content</a>
    <a href="#">content</a>
    </div>
    </li>
    </ul>
    </div>
    </li>
    <li>
    <div class="collapsible-header">#3<i class="material-icons right blue-text">arrow_drop_down</i></div>
    <div class="collapsible-body">
    <a href="#">content</a>
    <a href="#">content</a>
    <a href="#">content</a>
    <a href="#">content</a>
    </div>
    </li>
    </ul></li>`

**Comment by acburst** [comment]
Fixed in d7c8d44
