### ISSUE TITLE
input type color does not work

### ISSUE THREAD

**Issue by smariel** [Dogfalo/materialize#3811]
The HTML5 type "[color](https://www.w3.org/community/webed/wiki/HTML/Elements/input/color)" for input elements is not stylized by Materialize 0.97.7.
The label is displayed over the color picker. The color picker itself has the default browser style.
It "works" but it has no Materialize style.

http://codepen.io/anon/pen/amPgoq

Would it be possible to manage this type of input ?

**Comment by acburst** [comment]
We are not interested in making a special color picker as of this moment. We feel it is too niche of an input right now and it would be overstyling. I'm sure there are some color picker plugins out there.
