### ISSUE TITLE
input  label error when col and rows classes are not used

### ISSUE THREAD

**Issue by IAMtheIAM** [Dogfalo/materialize#3822]
On FireFox v49.0.1, the `label` gets fixed incorrectly to the right of the input field, instead of flushed with the input field at the left margin. 

Adding `left: 0` fixes this immediately, with no foreseeable consequences.

Here is the current way it looks.

![error_on_firefox_with_labels_and_input_fields](https://cloud.githubusercontent.com/assets/13709948/19747164/fa28bb00-9b8e-11e6-8a88-2da7afccecc1.png)

Here is how it looks with this PR, which is how it should look

![error_corrected_on_firefox_with_labels_and_input_fields](https://cloud.githubusercontent.com/assets/13709948/19747212/2e509d26-9b8f-11e6-9eda-18fa94e8edac.png)

PR already submitted:
https://github.com/Dogfalo/materialize/pull/3821

**Comment by acburst** [comment]
Can you post your code so I can recreate it locally?

**Comment by kmmbvnr** [comment]
I saw this was reported here several times, but I never was able to reproduce it.

Here is Firefox 49.0.2 got from https://www.mozilla.org/en-US/firefox/new/ on ubuntu 15.10

![screenshot from 2016-10-27 08-56-57](https://cloud.githubusercontent.com/assets/282529/19753012/633fb99c-9c23-11e6-80d5-10145222d578.png)

**Comment by kmmbvnr** [comment]
It looks it happens if a form doesn't use grid "row" and "col" classes. 

http://codepen.io/kmmbvnr/pen/kkmAAO

It's ok on Chrome 54

![screenshot from 2016-10-27 09-19-41](https://cloud.githubusercontent.com/assets/282529/19753460/a3ca7094-9c26-11e6-96c6-14175bff4942.png)

But broken on FF 49

![screenshot from 2016-10-27 09-19-50](https://cloud.githubusercontent.com/assets/282529/19753470/ad9dab22-9c26-11e6-9a64-1c80c6b0dd6c.png)


See also #3789

**Comment by IAMtheIAM** [comment]
@kmmbvnr Yes you are correct, this is occurring when not using .row .col tags. The reason is because I prefer to use a custom grid made with Susy 2, rather than the premade grid in materialize. In that case, I have no need for the .row .col tags since my grid handles it.

But, then we have the label positioning issue.

My code:

Sass
```
/********************/
/* Login.scss */
/********************/
@import '../../assets/styles/appwide-metastyles.scss';

/// <reference path="../../../node_modules/susy/sass/susy/language/_susy.scss" />
/// <reference path="../../../node_modules/bourbon/app/assets/stylesheets/bourbon" />
/// <reference path="../../assets/styles/shared/variables.scss" />
/// <reference path="../../assets/styles/shared/mixins.scss" />

// The Susy Span Mixin Syntax
// This creates the app layout using Susy's Math functions
// @include span( <$span> of [<$context>] [<$last>] );
// Note: Arguments within square brackets are optional arguments

@include nested(24) {
   login {
      @include clearfix;
      align-items: center;
      height: 80vh;
      display: flex;
      justify-content: center; //height: 100vh; // This forces .app-container to 100% of your viewport

      .welcome-message {
         color: #fff;
         font-weight: bold;
      }

      .login-form {
         width: span(6);
         margin: 20px;
         position: relative;
         //top: 200px;
         @include border-radius(10px);

         md-card {
            background-color: #f9f9f9;
            margin: 20px 0;
            padding: 34px;
            @include border-radius(10px);
         }

         button.login-submit {
            margin: 15px 0 10px;
            font-size: 1.5em;
         }
      }
   }
   // end login {}
}

// end susy nested {} context
```

HTML
```
<div class="card-container login-form">
    <div class="welcome-message text-align-center">
        <h5>Angular2 Webpack2 DotNET Starter</h5>
        <h3>By IAMtheIAM</h3>
    </div>

   <!--The Materialize way-->
   <div class="card">
      <div class="card-content">
         <form role="form" (submit)="login($event, username.value, password.value)">
            <div class="row">
               <div class="input-field">
                  <i class="material-icons suffix">account_circle</i>
                  <input type="text" #username class="" id="username1" value="admin">
                  <label for="username1">Username</label>

               </div>
            </div>
            <div class="row">
               <div class="input-field">
                  <i class="material-icons suffix">lock_outline</i>
                  <input type="password" #password class="" id="password1">
                  <label for="password1">Password</label>
               </div>
            </div>

            <div class="row">
               <div class="input-field">
                  <input type="checkbox" id="rememberMe1" value="" class="rememberMe" /><!--<label for="rememberMe1">Remember me</label>-->

                  <input type="checkbox" id="filled-in-box1" class="filled-in rememberMe" />
                  <label for="filled-in-box1">Remember me</label>

                  <span class="float-right"><a href="/forgotpassword">Forgot password?</a></span><br>
                  <!--<span class="float-right"><a (click)="logout()">Logout</a></span>-->

               </div>
            </div>

            <button class="btn btn-block btn-large waves-effect waves-light login-submit" type="submit" name="action">
               Login<i class="material-icons right">send</i>
            </button>
         </form>
      </div>
   </div>
</div>

```

**Comment by acburst** [comment]
Have you been able to recreate this on the latest master branch? I'm pretty sure i've added this in 28b119a8233280e927318f8b02051a6f69ff65cf

**Comment by kmmbvnr** [comment]
I've upgraded the codepen to from 0.97.7 to 0.97.8 and the issue looks fixed under FF

**Comment by tomscholz** [comment]
@kmmbvnr You say this issue is fixed?

**Comment by kmmbvnr** [comment]
@tomscholz yep, works fine in latest release http://codepen.io/kmmbvnr/pen/kkmAAO

**Comment by fega** [comment]
@kmmbvnr thanks!
