### ISSUE TITLE
Collapsible close by js code

### ISSUE THREAD

**Issue by ReiiYuki** [Dogfalo/materialize#3827]
Can I close collapsible by clicking some button (not the header) in collapsible body?

**Comment by kmmbvnr** [comment]
You can just set 'display:none' for collapsible-body.

**Comment by ReiiYuki** [comment]
Can I open it again after that?

**Comment by kmmbvnr** [comment]
Yeap, it worked for me in with dev tools. You can also use `.slideUp.' - https://github.com/Dogfalo/materialize/blob/master/js/collapsible.js#L38

A bit hacky, since materialize have no such functionality out of the box.

**Comment by ReiiYuki** [comment]
![image](https://cloud.githubusercontent.com/assets/10514215/19828156/26520a2c-9de9-11e6-8dc4-0353f1b6f130.png)

Thank It work but so sad haha

Why header still popout ?

JQuery
```
shouldComponentUpdate(nextProps){
    $('#header-form').removeClass("acitve")
    $('#li-form').removeClass("acitve")
    $('#form').css('display','none');
    return this.props.admin.product !== nextProps
  }
```


React Code
```
<li id="li-form">
            <div id="header-form" className="collapsible-header grey lighten-4 center">Add new Category</div>
            <div id="form"className="collapsible-body">
              <CategoryEditForm add={true}/>
            </div>
          </li>
```

**Comment by acburst** [comment]
Added open and close methods to collapsible in b6d3188
