### ISSUE TITLE
Clicking label does not activate text input

### ISSUE THREAD

**Issue by ReckerSwartz** [Dogfalo/materialize#3829]
I am using  ruby on rails with Materialize Gem
I am working on signup/sign-in form in Model
The problem is with password text field .when clicked on password label active class is not added but work   fine with other input fields can't see any issue in java-script .
Inputs do not activate when clicking the label. You need to click below the label to active.

Rendered Html Output

`<form class="new_user" id="new_user" action="/signup" accept-charset="UTF-8" method="post">
   <input name="utf8" type="hidden" value="&#x2713;" /><input type="hidden" name="authenticity_token" value="O+umZfkwTTGEFsUoZCCcm/rwWFHPrXbtgbN72KdOmU3yTTh3ftqqCTq6xBRHKFvI8u2f3LQgRh4lyC3U01kzVQ==" />
   <div class="row">
      <div class="col s12 center-align">
         <i class="material-icons prefix">wc</i>
         <input class="with-gap validate" type="radio" value="male" name="user[gender]" id="user_gender_male" />
         <label for="user_gender_male">Male</label>
         <input class="with-gap validate" type="radio" value="female" name="user[gender]" id="user_gender_female" />
         <label for="user_gender_female">Female</label>
      </div>
   </div>
   <div class="row">
      <div class="input-field col s12 m6">
         <i class="material-icons prefix">account_circle</i>
         <input type="text" name="user[user_name]" id="user_user_name" />
         <label for="user_user_name">Name</label>
      </div>
      <div class="input-field col s12 m6">
         <i class="material-icons prefix">date_range</i>
         <input class="datepicker" type="text" name="user[dob]" id="user_dob" />
         <label for="user_dob">Birthday</label>
      </div>
   </div>
   <div class="row">
      <div class="input-field col s12 m6">
         <i class="material-icons prefix">lock_outline</i>
         <input type="password" name="user[password]" id="user_password" />
         <label for="user_password">Password</label>
      </div>
      <div class="input-field col s12 m6">
         <i class="material-icons prefix">lock_outline</i>
         <input autocomplete="off" type="password" name="user[password_confirmation]" id="user_password_confirmation" />
         <label for="user_password_confirmation">Password confirmation</label>
      </div>
   </div>
   <div class="row">
      <div class="input-field col s12 m6">
         <i class="material-icons prefix">assignment_ind</i>
         <input class="validate" type="email" value="" name="user[email]" id="user_email" />
         <label for="user_email">Email</label>
      </div>
      <div class="input-field col s12 m6">
         <i class="material-icons prefix">phone</i>
         <input type="tel" name="user[phone_number]" id="user_phone_number" />
         <label for="user_phone_number">Phone number</label>
      </div>
   </div>
   <div class="row">
      <div class="col s12">
         <input type="submit" name="commit" value="Sign up" class="btn col s12" data-disable-with="Sign up" />
      </div>
   </div>
</form>`

Any Help Will be Welcomed.

**Comment by jessenieminen** [comment]
I've had the same problem but was able to monkeypatch that quite easily with the help of css pointer-events. 

Just adding the following piece of less code did the trick for me. If you're not using less, the actual code will of course differ for you but the basic principle stays the same.

```
/* Clicking the label does not activate the input without this */
input[type="text"] + label {
	pointer-events: none;

	* {
		pointer-events: all;
	}
}
```

Having said that, I think this should definitely be fixed directly to Materialize.

**Comment by kmmbvnr** [comment]
As stated in the [docs](http://materializecss.com/forms.html#input), you need to  wrap each text and password fields into `<div class="input-field">`, ex

```html
    <div class="input-field">
      <input type="password" name="user[password]" id="user_password" />
       <label for="user_password">Password</label>
    </div>
```

**Comment by ReckerSwartz** [comment]
@jessenieminen thanks for help I'm also able to do it by using JavaScript but not able find direct solution., by using JavaScript I'm able to to show validation message on that field .
@kmmbvnr 
My Code for only password field
`<div class=" col s12 m4">
          <div class="input-field">
                          <i class="material-icons prefix">vpn_key</i>
                          <input autocomplete="off" id="user_password2" type="password" name="user[password]" />
                          <label id="password_lbl" for="user_password">Password</label>
          </div>
        </div>`

**Comment by kmmbvnr** [comment]
You have wrong `id` in the `<label for="` attribute.

```
<input id="user_password2" ...
<label for="user_password" ...
```

Check the:

https://codepen.io/kmmbvnr/pen/dObyzM?editors=1000#0

**Comment by kmmbvnr** [comment]
Btw, you don't have to turn off autocomplete for the password. Just add

```
input:-webkit-autofill + label {
  font-size: 0.8rem;
  transform: translateY(-140%); }
```

See #194

**Comment by JeanPaulBeard** [comment]
This is my solution for bug
`.input-field label {
    pointer-events: all;
}`

**Comment by AmitJoki** [comment]
Yes @JeanPaulBeard 
```
.input-field label{
    pointer-events: all !important;
}
```

Solved all the problem. Strangely enough, it was set to `none`, and even strange enough was that I used Internet Explorer to find and rectify this 😄

**Comment by les113** [comment]
This is not a bug. pointer-events: all; is not required. 

The solution, as given by @kmmbvnr above, is to match your label for and input field id.
