### ISSUE TITLE
When there's no title in view scrollspy is disabled

### ISSUE THREAD

**Issue by NitroBAY** [Dogfalo/materialize#3830]
It's working : http://i.imgur.com/mTIIIuh.png
As soon as there's no header, no headline of the scrollspy is shown but I would like the nearest title to be emphasized http://i.imgur.com/YGqNRqI.png

**Comment by acburst** [comment]
Can you post your code.

**Comment by NitroBAY** [comment]
https://jsfiddle.net/NitroBAY/opL9axyh/ I don't know why but the table of content isn't  fixed tough

**Comment by NitroBAY** [comment]
@acburst can you make table of content fixed on the top right ?

**Comment by NitroBAY** [comment]
I updated my jsfiddle @acburst

**Comment by acburst** [comment]
You should be placing the scrollspy class on the entire container for which you want it to recognize. Placing them on the titles will end up with very small areas where the scrollspy is active.

**Comment by NitroBAY** [comment]
Thanks
