### ISSUE TITLE
Params ignored in Dropdown

### ISSUE THREAD

**Issue by bryantp** [Dogfalo/materialize#3831]
Hello,

The params for the dropdown are ignored when initialized via Jquery param. I initialized the dropdown like so: 

   ```
 $('.thing').dropdown({
      inDuration: 300,
      outDuration: 225,
      constrain_width: false,
      hover: true, 
      gutter: 0,
      belowOrigin: true, //Is ignored
      alignment: 'left' 
    }
  );
```

but the params are ignored on this [line](https://github.com/Dogfalo/materialize/blob/master/dist/js/materialize.js#L488):

```
    this.each(function(){
      var origin = $(this);
      var options = $.extend({}, defaults, options);
      var isFocused = false;
```

[Here](https://plnkr.co/edit/kETCCuy6At9GRkhqZc6H) is a plunkr demonstrating my usage.

**Comment by acburst** [comment]
Fixed in #3417
