### ISSUE TITLE
Make tables swipe able on mobile device

### ISSUE THREAD

**Issue by hustcer** [Dogfalo/materialize#3834]
Hi,
Thanks for the great work.
IMHO, instead of make table cells stack on mobile device, It's more convenient for some cases to make tables swipe able, just like [tablesaw](https://github.com/filamentgroup/tablesaw) swipe mode or [tabellajs](https://github.com/iliketomatoes/tabellajs).

**Comment by tomscholz** [comment]
Added in v0.98.0
