### ISSUE TITLE
link with disabled class can be clicked.

### ISSUE THREAD

**Issue by gidcs** [Dogfalo/materialize#3835]
Is this a known issue?
The link of chevron_left is working although it has disabled class.
http://materializecss.com/pagination.html

**Comment by theavinashofficial** [comment]
No man, I checked it and it is not working. 
Check my pen
http://codepen.io/avinashsingh/pen/RobYgQ
Just giving it a disabled class it becomes disables and color fades i.e. becomes light grey.

**Comment by gidcs** [comment]
Yes. It becomes light grey but it could be clicked.
Try again with this.
http://codepen.io/gidcs/pen/pNzxJb

**Comment by avinash97** [comment]
Ya  Man I checked it and you are correct. It is an issue.
I have corrected this here
http://codepen.io/avinashsingh/pen/VmwWXv
@Dogfalo or @acburst has to just add this line
.disabled {
pointer-events: none !important;
}
in the class and it will be resolved.

**Comment by developeranirudhprabhu** [comment]
@acburst Can your merge the commit and mark this as closed?

**Comment by NonameSLdev** [comment]
Close this issue please. @fega @tomscholz

**Comment by tomscholz** [comment]
Okay, I will close this for now. And BTW @TheAvinashSingh you totally copied my GitHub bio ;)

**Comment by TheAvinashSingh** [comment]
I liked your bio @tomscholz so I made it mine too ;-)
