### ISSUE TITLE
Sidebar links and collapsible-headers have different padding-left

### ISSUE THREAD

**Issue by kmmbvnr** [Dogfalo/materialize#3837]
It looks a bit inconsistent that `<a>` has 32px padding-left on a sidebar, but `<a class="collapsible-header">` has `16px` only.

http://codepen.io/kmmbvnr/pen/OReoZL (with 0.97.8)
![a pen by mikhail podgurskiy](https://cloud.githubusercontent.com/assets/282529/19845329/15d7a292-9f60-11e6-8ad1-2e4a164c4922.png)

**Comment by mescuderocuu** [comment]
You can add 
```
.collapsible-body ul li{
  margin-left: -16px;
}
```
to a css and it should be equal.
But it suppose that look better with the default padding-left

**Comment by kmmbvnr** [comment]
@mescuderocuu  I mean inconsistency for top level links (first, second, collapsible)

**Comment by mescuderocuu** [comment]
Oh ok ok, sorry, i misunderstand

**Comment by kmmbvnr** [comment]
May be related to #928

**Comment by donBigote** [comment]
I use this in my sass
```
.sidenav .collapsible-header
  padding: 0 32px
```
