### ISSUE TITLE
I suggest to use Vibrant.js

### ISSUE THREAD

**Issue by bkrajendra** [Dogfalo/materialize#3838]
consider my kind suggesstion to make use of http://jariz.github.io/vibrant.js/

This extract prominent colors from an image. Can useful for applying colors to image borders, chrome title bar, UserView background or many other uses

**Comment by acburst** [comment]
We are trying to minimize the amount of 3rd party libraries we rely on. But I agree this library is really helpful but I don't see why it would be necessary to include with the framework at this time.
