### ISSUE TITLE
class="bordered" on Table doesn't work.

### ISSUE THREAD

**Issue by ventouris** [Dogfalo/materialize#384]
As the title says, class="bordered" for Tables doesn't work neither on documentation, nor on code. It shows a simple table instead.

**Comment by Dogfalo** [comment]
I don't know what you mean, the documentation is showing it working.

**Comment by ventouris** [comment]
@Dogfalo http://awesomescreenshot.com/0fd44h4x78

This is a screenshot from documentation. The table is without border :(

**Comment by Dogfalo** [comment]
borders are between rows

**Comment by ventouris** [comment]
Sorry. I am used to other frameworks that bordered means everything. Not only between lines. Have you consider to add also borders on the outside of table?

**Comment by Dogfalo** [comment]
I think we will leave bordered as is for now.

On Fri, Jan 2, 2015 at 6:23 PM, Anastasios Ventouris <
notifications@github.com> wrote:

> Sorry. I am used to other frameworks that bordered means everything. Not
> only between lines. Have you consider to add also borders on the outside of
> table?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Dogfalo/materialize/issues/384#issuecomment-68572498>.
>



-- 
Doggy sends his greetings from Mars.

**Comment by simonsmiley** [comment]
I guess it would be nice to have an option to add vertical borders as well
