### ISSUE TITLE
Isolate Materializecss stylesheet 

### ISSUE THREAD

**Issue by eugeniogrigoras** [Dogfalo/materialize#3840]
Is there any method to make materialize styles not to affect other elements in the page, but only certain divs or portion of code?

**Comment by kmmbvnr** [comment]
You can build materialize css from sass with a prefix to all classes, with postcss.

There are several projects could help with this, ex:

https://www.npmjs.com/package/postcss-selector-prefix
https://www.npmjs.com/package/postcss-class-prefix
