### ISSUE TITLE
Extended Navbar with Tabs without li links

### ISSUE THREAD

**Issue by tomscholz** [Dogfalo/materialize#3846]
As you can see in the first codepen the navbar is totally broken but in the other codepen, when the navbar is filled with some links everything looks normal.
[Buggy](https://codepen.io/tomscholz/pen/GjVGKb)
[Fixed](https://codepen.io/tomscholz/pen/bwXMWy)

**Comment by acburst** [comment]
Fixed in a8f301a6e93c7c760d5052b30d1d69437d530018
