### ISSUE TITLE
Impossible to add package: no compatible binary build

### ISSUE THREAD

**Issue by Almaju** [Dogfalo/materialize#3847]
I might ask a dumb question here but I have made a few search and can't find any answer yet...

Here is what happens when I try to install Materialize via `meteor add materialize:materialize`:

```
 => Errors while adding packages:             
                                              
While checking for materialize:materialize@0.97.8:
error: No compatible binary build found for this package. Contact the package
author and ask them to publish it for your platform.
```

It works with `meteor add materialize:materialize@=0.97.7` though. Am I the only one concerned by this?

**Comment by acburst** [comment]
What OS are you using?

**Comment by Almaju** [comment]
Ubuntu 16.04

**Comment by acburst** [comment]
Hmm I went through and publish-for-arch. Can you let me know if it is working now? It may take a bit to update though, i'm not sure

**Comment by Almaju** [comment]
Works like a charm now! Thanks for your reactivity! :)

**Comment by Almaju** [comment]
I get this errors now, not sure it's related to Materialize but just to let you know:
```
materialize_materialize.js?hash=ee6cc99…:7826 
Uncaught Error: Scss compiler error: Undefined variable: "$medium-and-down".

global-imports.js?hash=942d746…:9 
Uncaught TypeError: Cannot read property 'Materialize' of undefined(anonymous function)

app.js?hash=0a915b5…:1
Uncaught ReferenceError: meteorInstall is not defined
```

**Comment by acburst** [comment]
We've had problems before with the meteor sass compiler. Try updating that package. I think it's called fourseven

**Comment by Zaidiii** [comment]
I am facing same problem whould you guys please help me
