### ISSUE TITLE
Links Not Displaying On Fixed Navbar

### ISSUE THREAD

**Issue by ProProPro1** [Dogfalo/materialize#3848]
When You Put Links Inside Of The Fixed Navbar The Text Does Not Appear.

http://codepen.io/anon/pen/dpxgBP

Here Is A Example Of The Issue On Code Pen.

![qeww](https://cloud.githubusercontent.com/assets/20212891/19903887/98be70f8-a070-11e6-9bc3-54276e3ec8a5.jpg)

**Comment by iqbalaqaba** [comment]
@ProProPro1 Hello, i saw : 
```
header,main,footer {
    padding-left:300px;
}
```
if you remove the padding-left, the link will be showed up 😃 
Please check my [codepen](http://codepen.io/iqbalaqaba/pen/EgqqeX)

**Comment by kmmbvnr** [comment]
@iqbalaqaba  `padding-left` required to leave the place for SideNav

@ProProPro1 to fix this you can use `navbar-fixed` on the <nav> class. Check the codepen - http://codepen.io/kmmbvnr/pen/XjvvyR

**Comment by iqbalaqaba** [comment]
Ah! I'm very sorry, just realized that he want to that email link to be showed up. I thougt it was the "sass" and "component" link!
Sorry @kmmbvnr

**Comment by iqbalaqaba** [comment]
Ah, got it @ProProPro1 your code for navbar is : 
```
 <header>
  <div class="navbar-fixed">
    <nav>
```
and it should be : 
```
<nav class="navbar-fixed">
      <div class="nav-wrapper">

```
just like in the @kmmbvnr code. Please tell me if i'm wrong 😆

**Comment by kmmbvnr** [comment]
Yeah, i just realized that the following code

```
  <div class="navbar-fixed">
    <nav>
```

is what is suggested in the documentation. I'm actually don't know what part should be fixed. `.navbar-fixed` sass or just the documentation page

**Comment by iqbalaqaba** [comment]
Maybe @Dogfalo could fix this problem in the docs.
