### ISSUE TITLE
Error after new update (meteor)

### ISSUE THREAD

**Issue by lunatolun** [Dogfalo/materialize#3849]
It was fine before update. No error logs in to the console. I tried both with and without fourseven:scss in packages. Is this an issue with fourseven:scss?

When I remove and add both packages, the versions seem to be correct:
```
fourseven:scss           added, version 3.10.0
materialize:materialize  added, version 0.97.8
```

Errors:
```
Error: Scss compiler error: Undefined variable: "$medium-and-down"
TypeError: Package['materialize:materialize'] is undefined
ReferenceError: meteorInstall is not defined
```

**EDIT**
I installed with NPM and imported CSS and JS. It works fine. Don't know what is causing the issue when I install from atmosphere packages
```
import 'materialize-css/bin/materialize.css'
import 'materialize-css/bin/materialize.js'
```

**EDIT 2**
using Materialize 0.97.7 fixed the issue for me

**Comment by Dogfalo** [comment]
Fixed, see #3905 for more information
