### ISSUE TITLE
multiple custom error messages

### ISSUE THREAD

**Issue by jmls** [Dogfalo/materialize#3852]
how does one go about showing multiple error messages for an input field ?

for example, an email field must
1) be required
2) be a valid email field (a@b.com)
3) have a minimum length (say 5 chars)

how can I show an appropriate message for each type of error using the `data-error` attribute ?

I am using angular, if that's of any help ...

**Comment by kmmbvnr** [comment]
The problem with multiple error messages, that it would change the overall control height, that would re-layout all control below. That's a big ugly for on the fly validation.

**Comment by Dogfalo** [comment]
You will need a javascript validation script if you want to do something like this.

**Comment by dipakchandranp** [comment]
This is how I have resolved my scenario for an input field where a user can enter an email address and verify if there is user exist in the system with the same email Id.

1. Created an input field with type email and provided invalid email message as the data-error attribute value.
```
<div class="input-field inline">
<input type="email" id="emailOrPhone" name="emailOrPhone" required="" minlength="1" class="validate valid" value="dipakchandranp15@gmail.com">
<label for="emailOrPhone" class="active">Mobile number / Email ID</label>
<span class="helper-text" data-error="Invalid email address"></span>
</div>
```

2. Whenever email address is getting verified from the server with an error message from the server, we update the data-error attribute value through javascript and set the invalid class to the input element to show this message.
```
<div class="input-field inline">
<input type="email" id="emailOrPhone" name="emailOrPhone" required="" minlength="1" class="validate invalid" value="dipakchandranp15@gmail.com">
<label for="emailOrPhone" class="active">Mobile number / Email ID</label>
<span class="helper-text" data-error=User not present in the system"></span>
</div>
```
