### ISSUE TITLE
FAB to Toolbar not working on mobile

### ISSUE THREAD

**Issue by adamwozniak** [Dogfalo/materialize#3853]
I think a comment is not necessary :) How to fix this?
![fab_toolbar](https://cloud.githubusercontent.com/assets/23217056/19934375/b2500d1e-a116-11e6-9763-123dc5af2864.jpg)

**Comment by ProProPro1** [comment]
Can you show the code?

**Comment by adamwozniak** [comment]
Copied from website. Nothing changed.

`    <div class="fixed-action-btn toolbar">
      <a class="btn-floating btn-large blue darken-4">
        <i class="large material-icons">mode_edit</i>
      </a>
      <ul>
        <li class="waves-effect waves-light"><a href="#!"><i class="material-icons">format_quote</i></a></li>
        <li class="waves-effect waves-light"><a href="#!"><i class="material-icons">publish</i></a></li>
        <li class="waves-effect waves-light"><a href="#!"><i class="material-icons">attach_file</i></a></li>
      </ul>
    </div>`

**Comment by adamwozniak** [comment]
I don't know why but when I changed view to PC and than go back to Mobile, everything works fine. 
When I try on different phone. Everything was fine from the beginning. Strange.
Sorry for trouble.
