### ISSUE TITLE
Dropdown is not scrollable on mobile

### ISSUE THREAD

**Issue by Fen747** [Dogfalo/materialize#3854]
Hi folk.

I'm using materializecss:materializecss@0.97.6.

It seems that dropdown menus are not scrollable on mobile : my dropdown menu is closed as soon as my finger start to swipe to scroll the dropdown, which has a fixed max-height. The problem appears on every mobile device I've tried.

All the needed code to reproduce the problem is here : https://jsfiddle.net/3ywogd9u/

That's very annoying, as it makes things like notification panels unusable. I'haven't figured out what caused this strange behavior in the lib.

Any idea / solution about it ?

**Comment by kmmbvnr** [comment]
Yeah, I can confirm this  - http://codepen.io/kmmbvnr/details/GNKdaP/ 

Dropdowns are no scrollable on iPhone Safari iOS 10.1 and Android Chrome 54

**Comment by tomscholz** [comment]
Yeah, I hate that bug :D

**Comment by acburst** [comment]
Fixed in 1d94110

**Comment by hiteshsahu** [comment]
I had the same issue after a day of head scratching I found out I was using the older version of the library. 

Please check CDN version from
http://materializecss.com/getting-started.html

 I am sharing code snippet on as new as 27/03/2017. Hope it helps somebody.

 
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>

    
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">

    
    
    <link rel="stylesheet"
          href="https://cdnjs.cloudflare.com/ajax/libs/materialize/0.98.1/css/materialize.min.css">
    <link rel="stylesheet" href="https://cdn.datatables.net/1.10.13/css/jquery.dataTables.min.css">
 
   
    
    <script type="text/javascript" src="https://code.jquery.com/jquery-2.1.1.min.js"></script>

    
    <script type="text/javascript"
            src="https://cdnjs.cloudflare.com/ajax/libs/materialize/0.98.1/js/materialize.min.js"></script>

**Comment by lewiss444** [comment]
Had this issue with the hover:true option. Here is my solution : 
`if ($(window).width() < 992) {
	$(".dropdown-button").dropdown({
		hover:false,
		constrainWidth:false,
		belowOrigin:true
	});
} else {
		$(".dropdown-button").dropdown({
		hover:true,
		constrainWidth:false,
		belowOrigin:true
	});
}`

**Comment by alexim39** [comment]
> Had this issue with the hover:true option. Here is my solution :
> `if ($(window).width() < 992) { $(".dropdown-button").dropdown({ hover:false, constrainWidth:false, belowOrigin:true }); } else { $(".dropdown-button").dropdown({ hover:true, constrainWidth:false, belowOrigin:true }); }`

Many thanks @lewiss444 was able to use your work-around to resolve similar challenge.
