### ISSUE TITLE
why is the npm install downloading the whole materialize-css website?

### ISSUE THREAD

**Issue by cjaoude** [Dogfalo/materialize#3855]
guys, the npm install downloads _evvveryyything_...the entire Materialize website.

Call me crazy :) but it should only download the framework sass/scss src files. Or am I missing something here...

tnx

**Comment by kmmbvnr** [comment]
I think b/c it's default npm behavior ;)

[.npmignore](https://docs.npmjs.com/files/package.json#files) can be set to avoid this. It looks like only `dist`, `sass`, `js` folders need to be included into the distribution

**Comment by cjaoude** [comment]
I know _why_, but not *why*. :) 

As a package it should just be the framework sass files. The Materialize website has no business being an npm package for app development. "capice?"  ;)

**Comment by tomscholz** [comment]
#3621 I had kinda a solution, but no one wanted to talk with  me about that :(

**Comment by kevgathuku** [comment]
@cjaoude You're right. No need to download the entire Materialize website. I was just as surprised to see the installed npm package takes up a whole `18.13MB`
@kmmbvnr Would something like this in the `package.json` work? 
```json
"files": ["dist", "sass", "js"],
```
Or would the ignored files also have to be in the `.npmignore` file?
Anyone know how you would test what would be installed by `npm` locally?

**Comment by cjaoude** [comment]
Keep it simple...or SRP.  Split the website and framework into separate repos. The website consumes the framework as a package.

**Comment by fega** [comment]
I  agree with @cjaoude 
What do you think @acburst or @Dogfalo ?

**Comment by tomscholz** [comment]
Would be fixed by https://github.com/Dogfalo/materialize/pull/4774
