### ISSUE TITLE
hide the side nav on large screens 

### ISSUE THREAD

**Issue by heshamelmasry77** [Dogfalo/materialize#3857]
hey i wanna hide the side nav on lareg screen for example more than 992px i wanna hide it i tried to write thhis code but it doesnt work like how you did it on your website:

$(window).resize(function(){
	if ($(window).width() >= 992){
		// do something here

        $(".side-nav").css('transform', 'translateX(-105%)');

	}
});

it doesnt work nice and smothly liek how you did it on your website how ic an achieve yours ?

**Comment by avinash97** [comment]
They used media queries for this
```
@media only screen and(max-width:992px){
.side-nav.fixed {
-webkit-transform:translateX(-105%);
transform:translateX(-105%);
}
.side-nav.fixed.right-aligned{
-webkit-transform:translateX(105%);
transform:translateX(105%)
}
}
```

**Comment by arpit1997** [comment]
Why don't you use class `hide-on-large-only` in sidenav section instead of this
```
$(window).resize(function(){
if ($(window).width() >= 992){
// do something here

    $(".side-nav").css('transform', 'translateX(-105%)');

}
});
```

**Comment by tomscholz** [comment]
Closed due inactivity
