### ISSUE TITLE
REMOTE CONTENT IN MODAL

### ISSUE THREAD

**Issue by umahatokula** [Dogfalo/materialize#3858]
Is it possible to open a url content in a modal. If yes, how?

**Comment by kmmbvnr** [comment]
See  https://github.com/Dogfalo/materialize/issues/586#issuecomment-255769998

**Comment by ProProPro1** [comment]
XMLHttpRequest:
`var xml = new XMLHttpRequest();
xml.open('GET','http://www.whatever.com/',true);

 xmlhttp.onreadystatechange=function() {
  if (xmlhttp.readyState==4) {
$('body').html(xmlHttp.responseText); 
  }
 }
 xmlhttp.send();
`
AJAX(With jQuery):
`$.ajax({
  url: 'http://www.whatever.com/',
  success: function(response){
$('body').html(response);
}
});`
PHP:
`<?PHP
$ch = curl_init();
curl_setopt($ch, CURLOPT_URL, 'http://www.whatever.com/');
curl_setopt($ch, CURLOPT_HEADER, 0);
curl_setopt($ch, CURLOPT_HTTPHEADER, array('REMOTE_ADDR: 127.0.0.1','HTTP_Forwarded_For: 127.0.0.1','HTTP_X_FORWARDED_FOR: 127.0.0.1','Client-Ip: 127.0.0.1','X-Client-Ip: 127.0.0.1'));
curl_setopt($ch, CURLOPT_RETURNTRANSFER, 1);

$result = curl_exec($ch);

if($result || $result != NULL){
echo $result;
}
?>`

**Comment by acburst** [comment]
Are you talking about an iframe? Because you can look into those. Either way not really the right place to be discussing it. Try stackoverflow or our gitter chat.
