### ISSUE TITLE
Material Box shows compressed / corrupt image on hover

### ISSUE THREAD

**Issue by mirshko** [Dogfalo/materialize#3860]
Not entirely sure why this is happening but when you mouse over on the image that is using `materialboxed` it becomes all corrupt looking. 

See here

![screen shot 2016-11-03 at 3 10 59 pm](https://cloud.githubusercontent.com/assets/8116716/19981321/e52aedc8-a1d7-11e6-9688-6cc49178d5c0.png)

**Comment by acburst** [comment]
Fixed in 523fabb
