### ISSUE TITLE
Set offset to zero for small screen

### ISSUE THREAD

**Issue by smitthakkar96** [Dogfalo/materialize#3861]
Is is possible to have something like this offset-l4 offset-m3 offset-s0, I don't want any offset in smaller screen sizes.

**Comment by acburst** [comment]
If you just omit `offset-s0`, and leave `offset-l4 offset-m3`, This will happen. Our column sizes work by cascading upwards not downwards. So if you only set an `offset-s2`, ALL sizes would inherit that offset.
