### ISSUE TITLE
Meteor Issue after last update (materialize:materialize and fourseven:scss)

### ISSUE THREAD

**Issue by 3210jr** [Dogfalo/materialize#3863]
Hey,

I had no errors before the last update about an hour ago. The update I made had the following changes:
    
    Changes to your project's package version selections from updating package versions:
                                              
    babel-runtime            upgraded from 0.1.12 to 0.1.13
    fourseven:scss           upgraded from 3.10.0 to 3.10.1
    materialize:materialize  upgraded from 0.97.7 to 0.97.8

the current version of meteor is `1.4.2`

after the update I get the following errors:
    
    Uncaught Error: Scss compiler error: Undefined variable: "$medium-and-down"
    Uncaught TypeError: Cannot read property 'Materialize' of undefined
    ReferenceError: meteorInstall is not defined

this was after updating to materialize version 0.97.8

even after downgrading to version 0.97.7, I still get the same error.

Any help is appreciated.
Thanks again.

**Comment by kmmbvnr** [comment]
Looks like duplicate for #3849

**Comment by 3210jr** [comment]
@kmmbvnr it feels different since the package versions are different and his solution under EDIT 2 does not work for me.

**Comment by 3210jr** [comment]
I remove all node modules, meteor reset, and restarted my laptop. 0.97.7 works fine now. still problem with 0.97.8.

**Comment by LMS90** [comment]
Same problem with 0.97.8 version.

**Comment by ckiw** [comment]
I have this problem too, downgraded with `meteor add materialize:materialize@=0.97.7`

**Comment by pk-student-trilogy** [comment]
Downgraded to 0.97.7 like @ckiw and worked for me

**Comment by sunlee-newyork** [comment]
Downgraded to 0.97.7 like @ckiw and worked for me

**Comment by liambrownweb** [comment]
Same here as @ckiw and @sunlee-newyork. App did not have any of the mentioned errors when I removed materialize:materialize entirely (though the interface lost functionality, as would be expected). Installing 0.97.7 fixed the errors and brought the app back to previous functionality.

**Comment by aisamu** [comment]
Same here, worked after downgrading to 0.97.7

**Comment by bryanlimy** [comment]
same here. worked after downgrading to 0.97.7, but getting warning 
- `Failed to decode downloaded font: http://localhost:3000/packages/materialize_materialize/fonts/roboto/Roboto-Regular.woff2`
- `OTS parsing error: invalid version tag`

**Comment by surtic86** [comment]
Any news about this Issue?

**Comment by tdotholla** [comment]
All of the above... but now i'm also getting wierd glitches in modal where css isn't changing when modal is triggered; css remains `display:none` instead of `display:block`, so the gray overlay shows up, but no modal. 
and then i can't click 'out' of the gray overlay.

**Comment by matt-moon** [comment]
Same issue with 0.97.8. When I updated Meteor to 1.4.3.2, it automatically installed Materialize 0.97.8, but console was showing Materialize errors. Downgraded to 0.97.7 and works fine. When trying to update manually to 0.97.8 Meteor claims it's at latest compatible version.

**Comment by fmarques899** [comment]
I got the same problem and solved downgrading the package to 0.97.0. Tried too to use 0.97.7 and worked well. Does the 0.97.8 will be update by now? Because some bugs in dropdowns were solved and tabs can be supported into this version, and I have interest into those features. Waiting anxiously for the update !!

Thank you very much

**Comment by Dogfalo** [comment]
Fixed, see #3905 for more information
