### ISSUE TITLE
Waves Effect Collapsible

### ISSUE THREAD

**Issue by Projoh** [Dogfalo/materialize#3864]
When adding a waves effect to a collapsible, the animations become very laggy.

`<div class="collapsible-header waves-effect waves-block waves-blue">`

and 

`<div class="collapsible-body waves-effect waves-block waves-light">`

Both would cause lagg.

**Comment by avinash97** [comment]
Can u post a pen on codepen.io and then share that here.

**Comment by acburst** [comment]
The waves effect should be reserved for simple touch targets. If you add it to everything it will not be very perfomant.
