### ISSUE TITLE
Datepicker on click not triggering

### ISSUE THREAD

**Issue by gnnpls** [Dogfalo/materialize#3867]
Hi everybody.

We have a very strange behavior with on click for datepicker.

We add a custom field on render:
onRender: function() {
                                $('<div class="sbp_custom_title">' + $('.sbp_check_buttons .button[data-id="' + d_id + '"] .up_row').text() + '</div>').prependTo($('#' + d_id + '_root .picker__date-display'));

}

Then we try to bind a click event for this class like below:

 $(document).on('click','.sbp_custom_title',function()
            {
                alert('nikos');

            });

We have tried every possible solution but the on click event is not working at all.

We think is something with the picker__ classes.

Any ideas about that?

**Comment by Dogfalo** [comment]
This isn't a materialize related problem as this pertains to custom code you added.
