### ISSUE TITLE
Modal jQuery plugin Initialization in Documentation not updated

### ISSUE THREAD

**Issue by ralpho00** [Dogfalo/materialize#3873]
In the documentation it says  `$('.modal').modal();` which does not work. I added `.modal-trigger` class to the trigger and then initialized the trigger `$('.modal-trigger').leanModal();`.

**Comment by VeeK727** [comment]
This is what was there originally until they changed it to this style. Although it doesn't work. Still using the leanModal function

**Comment by kmmbvnr** [comment]
`$('.modal').modal();` is for the latest 0.97.8

`.leanModal();` used previously till `0.97.7`

**Comment by kmmbvnr** [comment]
@ralpho00 @VeeK727  can you create a codepen that demonstrates the issue?

I'm successfully using `modal()` with latest `0.97.8` (http://demo.viewflow.io/workflow/ the plus button) and the MaterializeCSS docs also built with `modal()`

**Comment by ralpho00** [comment]
Thanks @kmmbvnr, i think i am using 0.97.7, that's why. Issue is solved 👍
