### ISSUE TITLE
Search Icon issue in SideNav

### ISSUE THREAD

**Issue by Shivang-Bhandari** [Dogfalo/materialize#3874]
@Dogfalo @acburst Please have a look

When a Searchbar is added as a List item in the Side NavBar, The Search Icon Gets Displaced in the List and overlays other list items.
PFA The Screenshots of the problem.
![mat1](https://cloud.githubusercontent.com/assets/16368588/20037789/6742126a-a44d-11e6-8c31-08ca81a41091.png)
![mat2](https://cloud.githubusercontent.com/assets/16368588/20037788/673d7246-a44d-11e6-96ae-cd74f224d230.png)

**Comment by acburst** [comment]
can you post a code example

**Comment by Shivang-Bhandari** [comment]
sure thing

**Comment by Shivang-Bhandari** [comment]
Github Repo : https://github.com/Shivang-Bhandari/P5-Neighborhood-Maps

Live App : https://shivang-bhandari.github.io/P5-Neighborhood-Maps/

@acburst let me know if anything else is needed

**Comment by Shivang-Bhandari** [comment]
@acburst any updates?

**Comment by acburst** [comment]
I restructured things so that you can now add the class `label-icon` to your search icon label and you it won't move. You'll have to switch to master though. If not you can instead not use a label and just position a search icon yourself with css.

Added in f927836.
