### ISSUE TITLE
Feature request: three-state filled-in checkboxes

### ISSUE THREAD

**Issue by hartwork** [Dogfalo/materialize#3875]
Hi there!

I am a happy user of materialize with project https://github.com/hartwork/jawanndenn. materialize worked better for me than others, good work, very nice!

I am going to need three-state checkboxes at some point, potentially the click rotating UX demoed at https://css-tricks.com/indeterminate-checkboxes/#cp_embed_gaxrbv. While I may be able to do the rotation myself, the filled-in checkbox class does not seem to visually distinguish indeterminate and unchecked, yet. How about using the gray of the unchecked state and the checked graphics of the checked state to make a distinct indeterminate state for filled-in boxes? What do you think?

Best, Sebastian

**Comment by kmmbvnr** [comment]
There is no 3-state checkbox in the material design specs, and seems no other material-design CSS library have support for it

ex:

- https://getmdl.io/components/index.html#toggles-section/checkbox
- http://www.materialdoc.com/check-box/

I found only one 3party library that provides indeterminate checkbox state for the android

- https://github.com/sevar83/indeterminate-checkbox

![image](https://cloud.githubusercontent.com/assets/282529/20099515/142ac12a-a5e3-11e6-8206-b43f61762ec2.png)

**Comment by hartwork** [comment]
The current code supports indeterminate state display (http://materializecss.com/forms.html#checkbox) for non-`filled-in`-style boxes already. I am going to try myself then, I suppose.

**Comment by ermarkar** [comment]
any update on this?
