### ISSUE TITLE
Clicking on FAB multiple times trigger the Chrome search on Android

### ISSUE THREAD

**Issue by okon3** [Dogfalo/materialize#3876]
I'm facing this issue with the FAB button on Chrome for Android:
If you click on the button to open the FAB menu and then you want to close the menu and press on the FAB again, the chrome search function gets triggered.

Here's a video:
https://www.youtube.com/watch?v=FdrBzHQkQk4

**Comment by acburst** [comment]
Hmm this seems like it is trying to select the text for the ligature of the material icons. Have you tried setting the FAB to `user-select: none;`?

**Comment by okon3** [comment]
I tried to use the `.click-to-toggle` and now it behaves correctly on mobile. I'm fine with it since I didn't like the hover on desktop.
