### ISSUE TITLE
How to make tabs out of the dropdown selections used in forms? (not using it in a form but like the looks)

### ISSUE THREAD

**Issue by lastnoob** [Dogfalo/materialize#3878]
I like the looks of the dropdown selection used in forms more than the simple dropdown, and I'd like to make tabs out of it. Any ways to achieve this with the materialize jquery function 'tabs'?

thanks

**Comment by acburst** [comment]
You can override the tabs yourself with custom css and try and recreate it. But I'm not sure this is the best place to be asking this. This is more of a specific implementation question that is best asked on stackoverflow or our gitter
