### ISSUE TITLE
Enhancement: Autocomplete fuzzy matching

### ISSUE THREAD

**Issue by skhavari** [Dogfalo/materialize#3879]
Feature Request:
Allow auto complete to fuzzy match the data so you can build an autocomplete experience similar to sublime text.  Could use something like [fuze.js](https://github.com/krisk/Fuse) for searching.

**Comment by ReilySiegel** [comment]
I have done nsomething like this for a recent project, I will submit a PR.

**Comment by ReilySiegel** [comment]
Is this what you are looking for? 
http://codepen.io/ReilySiegel/details/RoddRN/

**Comment by taorg** [comment]
I've seen your example and is awesome.
Could you submit a PR or share your code, please?
Thx

**Comment by taorg** [comment]
Ok you use fuse.js I go it, thx
