### ISSUE TITLE
Select element rendering twice

### ISSUE THREAD

**Issue by elbecita** [Dogfalo/materialize#3880]
Hello, I am using select element with filterrific and it is rendered twice:
![materializecss_select_error](https://cloud.githubusercontent.com/assets/1207220/20040868/5dd88f4e-a414-11e6-9da4-021fdbd2a67e.png)

It happens once I do the `$('select').material_select();` and I don't really know what's going on.

The haml code looks like (same for the other select):
```
.input-field
    = f.select :with_status, @filterrific.select_options[:status_for_select]
    = f.label 'Status'
```
Might be that the `material_select()` fn is doing something weird?

**Comment by developeranirudhprabhu** [comment]
@elbecita I'm not aware about haml can you share a HTML version of this through code pen may be?

**Comment by Dogfalo** [comment]
Looks like your own CSS is causing it to show the original select when it should be hidden.
