### ISSUE TITLE
[Dropdown on Mobile] Clicking on Dropdown link opens the link below it

### ISSUE THREAD

**Issue by gnicol-bzh** [Dogfalo/materialize#3883]
Clicking on Dropdown link opens the link below it (if it exists, for example if there's a Collection).

Bug seen on mobile devices (ie. Samsung S5) or when activating Device toolbar on Chrome desktop, since (at least) v0.97.6, still reproduced on v0.97.8.

No problem on Chrome desktop (when Device toobar is NOT activated).

To reproduce, use a _real mobile device_, or emulate it on a desktop navigator (such as Chrome):
- See JSFiddle : https://jsfiddle.net/gnicol_bzh/txo3ap2x/
- Enter mobile mode (F12 then CTRL+SHIFT+M)
- Click "Dropdown" then "Google" to open... MaterializeCSS instead of Google!

**Comment by tomscholz** [comment]
I can't reproduce this. Which browser are you using?

**Comment by gnicol-bzh** [comment]
Reported first on Samsung S5, reproduced on Chrome Desktop **when device mode is enabled**  _(Developer Tools > "Toggle Device Toolbar", second icon on the top left)_: 
![image](https://cloud.githubusercontent.com/assets/11173645/20091973/f116472e-a595-11e6-9c48-cd7011da1c68.png)

**Comment by NonameSLdev** [comment]
@gnicol-bzh @tomscholz Confirmed. This is indeed an odd issue.

**Comment by Dogfalo** [comment]
You can apply stopPropagation() or preventDefault() on any element yourself

**Comment by Ken-Gilb** [comment]
> You can apply stopPropagation() or preventDefault() on any element yourself

Why is this marked closed? Where is the fix? Am I to apply stopPropagation or preventDefault myself?

**Comment by CatalinRadoi** [comment]
2021 March, still not resolved.

**Comment by CatalinRadoi** [comment]
OK guys, here is the fix, pretty complex stuff lol (is Dogfalo's code for ios13 but it fixes this also)
https://pastebin.com/GKix4xbm
