### ISSUE TITLE
Autocomplete Lag - minLength?

### ISSUE THREAD

**Issue by alan-xie** [Dogfalo/materialize#3884]
Would it be possible to add a minLength argument to the autocomplete feature? I'm working with large lists of names and was using jQuery UI with Bootstrap before I switched over completely to Materialize. Unfortunately, the autocomplete function searches my full list the moment I begin typing, and this creates incredible latency before I can even type the second letter of a name. Would greatly appreciate, thanks!

**Comment by tchillingworth** [comment]
Agreed, this would be a very helpful feature to have built-in.

**Comment by acburst** [comment]
Fixed in 14de2a0

**Comment by acburst** [comment]
Added a limit in 14de2a0.
