### ISSUE TITLE
carousel and slider is not working along side with "http://www.w3schools.com/lib/w3data.js"

### ISSUE THREAD

**Issue by avinashdvv** [Dogfalo/materialize#3885]
1. slider and carousel are in a temp.html page
 when i loading them in main.html page using JQUERY or W3data.js
slider and carousel are not working

**Comment by acburst** [comment]
This is not enough information. Please read the contributing guidelines and put in more effort to explain your problem. When in doubt add a codepen to demonstrate the issue.
