### ISSUE TITLE
Can't change the trigger selector for the new modal

### ISSUE THREAD

**Issue by gudata** [Dogfalo/materialize#3889]
This works
```javascript
  $('.modal').modal({
      dismissible: true,
      opacity: .5
    });
````

and this doesn't

```javascript
  $('.js-modal-trigger').modal({
      dismissible: true,
      opacity: .5
    });

```

If I execute the  $('.modal').modal() then the $('.js-modal-trigger').modal() works also.

http://codepen.io/gudata/pen/yVNQqo

**Comment by lunixyacht** [comment]
in file modal.js i think you must call methods.ini before trigger (can't make a trigger on something not declared)  

may be the solution is :

replace LINE 942
```
    open : function() {
      	$(this).trigger('openModal');
    },
```


by this :
```
open : function() {
       methods.init.apply( this, arguments );
      	$(this).trigger('openModal');
    },
```

**Comment by lunixyacht** [comment]
With the solution i proposed you can directly call the modal like this:

$('.js-modal-trigger').modal(
      'open',
     {
      dismissible: true,
      opacity: .5
     }
);

**Comment by ben-sykes** [comment]
@lunixyacht , has there been any update regarding your proposed change?

**Comment by storm1er** [comment]
This cause some bug :( 
https://github.com/Dogfalo/materialize/issues/4909
