### ISSUE TITLE
Simple alert box

### ISSUE THREAD

**Issue by Dogfalo** [Dogfalo/materialize#389]

**Comment by theduke** [comment]
+1 for dismissable alert boxes like Bootstrap has them.

**Comment by blackfyre** [comment]
:+1:

**Comment by resilva** [comment]
:+1: would be very usefull :)

**Comment by koustuvsinha** [comment]
:+1: It would be great if this library could provide alerts as specified in Google Material design

http://www.google.co.in/design/spec/components/dialogs.html#dialogs-alerts

**Comment by joaobarcia** [comment]
+1!

**Comment by dcoferraz** [comment]
:+1:

**Comment by sleeplessman** [comment]
+1!
currently i use modals instead.

**Comment by aprendizadoonline** [comment]
+1

**Comment by tengis** [comment]
+1

**Comment by G-khanddorj** [comment]
+1

**Comment by gabila-r** [comment]
When will the alerts be available ?

**Comment by caiocsalvador** [comment]
+1

**Comment by victorcosta** [comment]
+1

**Comment by dleo** [comment]
+1

**Comment by adriandurran** [comment]
+1

**Comment by spark998** [comment]
+1

**Comment by yigitozkavci** [comment]
+1

**Comment by mishantrop** [comment]
+1

**Comment by matheuss** [comment]
+1

**Comment by SiliticX** [comment]
+1

**Comment by pablocrivella** [comment]
+1

**Comment by FilipLukac** [comment]
+1

**Comment by acburst** [comment]
Would be open to a Pull Request of something simple

**Comment by pedroo21** [comment]
+1

**Comment by tomscholz** [comment]
You can achieve the same effect by using cards (to get bootstrap like alerts) or modals for dialogs

**Comment by tomscholz** [comment]
https://codepen.io/tomscholz/pen/GWzYpG You get the idea
