### ISSUE TITLE
materialize form styling issue with safari

### ISSUE THREAD

**Issue by ariingber** [Dogfalo/materialize#3891]
My form is styled correctly with chrome but has a different look in safari as seen here ... [chrome on left safari on right]
<img width="1293" alt="screen shot 2016-11-08 at 3 40 41 pm" src="https://cloud.githubusercontent.com/assets/15352435/20116409/169e4634-a5ca-11e6-9b28-bbf97b9b3b11.png">
Is there a simple way to fix this that I don't know about?  Thanks!

**Comment by kmmbvnr** [comment]
See #3822
