### ISSUE TITLE
Unable to initial $(..) in react component 

### ISSUE THREAD

**Issue by bnlambert** [Dogfalo/materialize#3892]
I am currently using materialize with react. I keep having this error
`TypeError: $(...).sideNav is not a function
	

$(".button-collapse").sideNav({
	`
My component looks like this
'componentDidMount()
  {
	  //Initialize collapse button
        $(".button-collapse").sideNav({
		  closeOnClick: true
		});
  }
  '
It prevents the side nav from popping up. but when I refresh the page it works.

Please help

**Comment by rwaness** [comment]
+1

**Comment by bnlambert** [comment]
I was able to resolve this by loading the Materialcss files through webpack. My code looks like this

`resolve: {
	  extensions: ['', '.less', '.scss', '.css', '.js', '.json'],
	  modulesDirectories: [
      'node_modules',
      path.resolve(__dirname, './node_modules')
    ],
      alias: {
		materializecss: 'css/materialize.css',
        materialize: 'js/materialize.js',
	
        jQuery: "js/jquery.min.js"
      }
  }`

Another posibility is require the css and js files from within the react component.
