### ISSUE TITLE
fixed-action-btn not working

### ISSUE THREAD

**Issue by Archetipo95** [Dogfalo/materialize#3895]
I'm using standard code from the [site](http://materializecss.com/buttons.html). On chrome (desktop & mobile) and edge when I resize the page fixed action button is not working proprely (just a small portion on top of the button is clickable) on IE everything is working fine (o.O) .
Maybe it's my fault I'm not an expert.

![image](https://cloud.githubusercontent.com/assets/11798239/20151580/eedc6d28-a6ba-11e6-8537-af4d1b8ae171.png)

I'm testing your framework on my project on github: [LINK](https://archetipo95.github.io/Material.Design.Site/)

**Comment by Thanood** [comment]
It's the `#toast-container` with a high `z-index` that's blocking the button.
You could either place the button a bit more up or gibe it a `z-index` bigger then 10000.
