### ISSUE TITLE
Modal with text edit BUG

### ISSUE THREAD

**Issue by tozik** [Dogfalo/materialize#3897]
Hi there)
Us need a  modal, but we have trouble.
When we put in modal textedit, or any components, textedit doesn't works, you can see on the picture how
can you help please, we lost many timy for find trouble)
label from textedit doesn't up, and when i try writing text, i'm not see him.
i can see only when it is(text) allocated

................(click)="openModal()........

		
		<div id="modal1" materialize="modal" class="modal" [materializeParams]="[{dismissible: true}]" [materializeActions]="modalActions">
			<div class="modal-content">
				<div class="container">
					<div class="z-depth-1 grey lighten-4 row" style="display: inline-block; padding: 32px 48px 0px 48px; border: 1px solid #EEE;">

						<form class="col s12" method="post">
							<div class='row'>
								<div class='col s12'>
								</div>
							</div>

							<div class='row'>
								<div class='input-field col s12'>
									<input class='validate' type='email' name='email' id='email' />
									<label for='email'>Enter your email</label>
								</div>
							</div>

							<div class='row'>
								<div class='input-field col s12'>
									<input class='validate' type='password' name='password' id='password' />
									<label for='password'>Enter your password</label>
								</div>
								<label style='float: right;'>
								<a class='pink-text' href='#!'><b>Forgot Password?</b></a>
							</label>
							</div>

							<br />
							<div class='row'>
								<button type='submit' name='btn_login' class='col s12 btn btn-large waves-effect indigo'>Login</button>
							</div>
						</form>
					</div>
				</div>
			</div>
		</div>

		<side-menu></side-menu>
	</div>

`

![scr](https://cloud.githubusercontent.com/assets/18100033/20153639/c4f78866-a6d4-11e6-808e-799e974bdb16.png)

**Comment by ralpho00** [comment]
Is the password text field working?

**Comment by tozik** [comment]
> Is the password text field working?
no, he is doesn't works, i am try all that i can

**Comment by Thanood** [comment]
Try calling `Materialize.updateTextFields()` *after* the modal is opened.

**Comment by tozik** [comment]
we are find problem
needed was put description modal, outside component navbar, and call modal from navbar
thanks
