### ISSUE TITLE
Carousel is not working when local images are used instead of loremimage samples in docs

### ISSUE THREAD

**Issue by SandeepVattapparambil** [Dogfalo/materialize#3899]
Carousel doesnot support image files of any type from file system. works only with the loremimage samples as given in the docs.

**Comment by sfarzy** [comment]
@SandeepVattapparambil Could you please give some more details regarding the issue. Carousel should be able to use images from file system.

**Comment by SandeepVattapparambil** [comment]
I used a carousel inside a card. Its able to load images from loremimage as in sample docs, but when I load images from development file system, it does not work . Its says initialized when inspected but its not rendering as expected..

**Comment by seanmavley** [comment]
I hope this can be closed now as @SandeepVattapparambil issues isn't a 'issue' with Materialize

**Comment by ChristfriedBalizou** [comment]
PTAL http://codepen.io/ChristfriedBalizou-1472222311/pen/WodLWQ?editors=1010#0

**Comment by arpit9295** [comment]
Can confirm, I had the same issue except not in card. The image path seemed to be correct but was only working when using lorem images

**Comment by sfarzy** [comment]
@arpit9295 In the codepen example provided above images are not from lorem and it seems to work. Please verify the path to images are valid. 
If the problems persists, please provide a codepen example to inspect.

**Comment by Braytiner** [comment]
Is not working for me too. Only Works with lorempixels images.

![materialize-carousel](https://cloud.githubusercontent.com/assets/11064602/25249224/87b36136-25e7-11e7-829d-1eecd259f533.png)

**Comment by sfarzy** [comment]
@Braytiner It works fine for me even when using other image sources. Please take a look at this [codepen](https://codepen.io/sfarzy/pen/Pmzqbm?editors=1000). If it still doesn't work, Please provide with a non-working example to understand the issue.

**Comment by acburst** [comment]
Fixed in 538f9dee04d7b8589b179cd78e1e20ad6a164787
