### ISSUE TITLE
Pulldown Refresh Component

### ISSUE THREAD

**Issue by Dogfalo** [Dogfalo/materialize#390]

**Comment by CoDEmanX** [comment]
The official google apps running on Android 5 vary a lot when it comes to pulldown refresh...

The material design docs suggest to use a shadowed circle that is being dragged out as you pull down: http://www.google.com/design/spec/patterns/swipe-to-refresh.html

The reality is however, that some apps use a very thin horizontal line to indicate the pulldown action and refresh, others use the standard circular progress indicator, sometimes combined with a button to refresh (if there's no content shown in the target area).

**Comment by tomscholz** [comment]
If you interested in having a pull to refresh component in your personal project, have a look [here](https://lightningtgc.github.io/material-refresh/). Anyhow, I will close this issue for now :)
