### ISSUE TITLE
w3c css validation errors

### ISSUE THREAD

**Issue by alejandromartincruz** [Dogfalo/materialize#3901]
I'm trying to validate the css of my app in w3c css validator and there is a lot of errors in the materialize css. It works fine, but it is not passing the w3c validation. 

it happens with 0.97.7 and with 0.97.8, I haven't tried with other versions.

https://jigsaw.w3.org/css-validator/validator?uri=https%3A%2F%2Fcdnjs.cloudflare.com%2Fajax%2Flibs%2Fmaterialize%2F0.97.8%2Fcss%2Fmaterialize.min.css&profile=css3&usermedium=all&warning=1&vextwarning=&lang=es

https://jigsaw.w3.org/css-validator/validator?uri=https%3A%2F%2Fcdnjs.cloudflare.com%2Fajax%2Flibs%2Fmaterialize%2F0.97.7%2Fcss%2Fmaterialize.min.css&profile=css3&usermedium=all&warning=1&vextwarning=&lang=en

**Comment by kmmbvnr** [comment]
I don't see something unusual or critical.  W3c standard always was far avay from real browsers implentations.

**Comment by gnicol-bzh** [comment]
> _"the code is more what you'd call "guidelines" than actual rules"_ - Hector Barbossa

Same for W3C & CSS validation ;)

**Comment by alejandromartincruz** [comment]
ok then, I know it's not critical. As I said before, it works fine. ;)

Thanks
