### ISSUE TITLE
v0.97.8 introduces breaking changes

### ISSUE THREAD

**Issue by Levino** [Dogfalo/materialize#3902]
Somehow the modal api changes broke our production build. Fixed the version to 0.97.6 now but thought someone else might have issues. Took me a while to find. You should not publish breaking changes with a patch.

**Comment by jlebras** [comment]
I just encountered this problem with a fresh install of a project, the refactoring of the modal plugin is a breaking change. Modals in projects relying on older versions do not work anymore. 
For now we have to freeze the version of materialize-css to 0.97.7 and cannot benefit from future patch/minor versions until we update all of our projects using modals...

**Comment by kmmbvnr** [comment]
Duplicate #3865
