### ISSUE TITLE
Can't get materialize navbar with pushpin and scrollspy to work

### ISSUE THREAD

**Issue by said50** [Dogfalo/materialize#3903]
I want a navbar in scrollspy style, and make it fixed using pushpin, how do I do this? I don't get the desired result at all
[https://i.stack.imgur.com/WyrYV.png](url)
Here is my code: http://codepen.io/said50/pen/JbGXgW

It does work in terms of clicking and scrolling to it
But it doesn't stay "pushpinned" (+ I don't know how to style it like on the materialdesign site)

**Comment by acburst** [comment]
Judging by your codepen, it looks like you are initializing pushpin on the wrong div

**Comment by kmmbvnr** [comment]
Check this one - http://codepen.io/kmmbvnr/pen/XNXVaY

You just need carefully follow the documentation,

The only inconsstence issue that `navbar` expects the `class="active"` on a `<li>` elements, but `scrollspy` set `active` class in `<a>` elements.

So you have to specify manually 

```
a.active {
  background-color: #ea454b;
}
```

**Comment by acburst** [comment]
I've added a more in depth pushpin demo in 6c1aaaf

**Comment by said50** [comment]
Ok got it fixed (accidentally deleted a div). But how can I style it so that it will get fixed at the middle right on the page (just like the materialize site). Got it to work with css but it didn't work well with the containers

**Comment by NonameSLdev** [comment]
Maybe close this issue?
