### ISSUE TITLE
Chips does not allow usage of white space between text (strings) but it works when &nbsp; is used.

### ISSUE THREAD

**Issue by SandeepVattapparambil** [Dogfalo/materialize#3907]

**Comment by acburst** [comment]
Please read the contributing guidelines and put more effort into your issues. Try and explain in more words what is wrong and add a codepen to demonstrate it more clearly.

**Comment by SandeepVattapparambil** [comment]
"Chips" when used inside a valign-wrapper prevents usage of white-space

**Comment by developeranirudhprabhu** [comment]
@SandeepVattapparambil Can you share your code so that we can inspect this?
