### ISSUE TITLE
switch value 'off' submit 

### ISSUE THREAD

**Issue by rubenscd** [Dogfalo/materialize#3908]
Please, 

How I need capture the switch value 'off' (POST, GET) on submit the `<form>`

**Comment by ralpho00** [comment]
Simply put a name on your check box like this: 

` <div class="switch">`
                                    `<label>`
                                        `Off`
                                     `   <input type="checkbox" name='switch'>`
                                        `<span class="lever"></span>`
                                       ` On`
                                    `</label>`
                                `</div>`

The value would either be on or off.

**Comment by developeranirudhprabhu** [comment]
@rubenscd can you confirm if this worked? Else you can use JS in following manner

**_`var switchState = ($("input['name'='switch']").is(":checked"))? "ON" : "OFF"`_**

Let us know your response

**Comment by Dogfalo** [comment]
This question isn't specifically related to Materialize.

**Comment by hudson6666** [comment]
@rubenscd Is this what you're looking for? #961

**Comment by hudson6666** [comment]
@developeranirudhprabhu Thank you! It does work for me!!
