### ISSUE TITLE
Where can i share a link to show a github open source project for Materiazlise?

### ISSUE THREAD

**Issue by onigetoc** [Dogfalo/materialize#3910]
Where can i share a link to show a github open source project for Materiazlise?

 I did a Chrome extension template using the great Materialize CSS and i want to share it with Chrome extension developper.

Here on Github: https://github.com/onigetoc/Materialize-CSS-Chrome-Extension-template

Popup view:
![](https://raw.githubusercontent.com/onigetoc/Materialize-CSS-Chrome-Extension-template/gh-pages/img/screenshot1.png)

Extension option: 
![](https://raw.githubusercontent.com/onigetoc/Materialize-CSS-Chrome-Extension-template/gh-pages/img/screenshot2.png)

**Comment by tomscholz** [comment]
http://materializecss.com/showcase.html
