### ISSUE TITLE
Missing Font Files Error | Lack of documentation on changing path of fonts

### ISSUE THREAD

**Issue by danimvijay** [Dogfalo/materialize#3915]
### Description
File missing error shown up even after changing all font file locations in materialize.css. Am I missing something?

### Repro Steps
File locations are different from default. Say my css files are in '<site root>/rcss/', js in '<site root>/rjs/' and fonts are in '<site root>/assets/rfonts/'. But error denotes something still refers older locations of font files. Where should I change?

Changes all locations in materialize.css only. Couldn't find any other file which calls font files.

### Screenshot
![capture](https://cloud.githubusercontent.com/assets/3250760/20379946/f2616696-acc4-11e6-93e9-ceda15f0fc5f.PNG)

**Comment by kmmbvnr** [comment]
Probably you miss some location in materialize.css, or CSS file is cached

**Comment by danimvijay** [comment]
Cleared cache and all occurrences of '/font/' replaced with '/assets/rfonts/' already and I can see the change in source in browser. There were 25 occurrences of of '/font/' in 'materialize.css' which I changed. Still the problem persists as in the screenshot. Is there something to do with 'materialize.js'? This is one thing not documented well and I think how to change font file location must be included in getting started/typography.

**Comment by kmmbvnr** [comment]
There is no `/font/` in the materialize css. It uses `/fonts/` directory

![search results](https://cloud.githubusercontent.com/assets/282529/20384194/229d189c-acdd-11e6-8824-4f05b58ea228.png)

Maybe you include another one `materialize.css` with unchanged variables. You can try to save "web-page complete" from chome and search over the files for `/fonts/` text

**Comment by danimvijay** [comment]
Oh OK. It was Cloudflare CDN who caches CSS caused the issue. My bad. Replacing all 25 locations in materialize.css enables changing font directory. If there is any possibility to modify it into a single path and reusing the same, customization will be lot easier, just saying. Anyway thanks for the support @kmmbvnr.
