### ISSUE TITLE
ScrollFire optimization

### ISSUE THREAD

**Issue by yanickrochon** [Dogfalo/materialize#3916]
There are a few WTF in the scrollFire component.

1) it will run a timer indefinitely, regardless if all callbacks have been fired.
2) it will search and check the element's selector, regardless if all callbacks have been fired.
3) it will keep references to obsolete objects beyond their useful states
4) it will add duplicate window scroll listeners...

Bottom line is, this component is in dire need to be refactored. I can prepare a PR tonight.

**Comment by acburst** [comment]
Do you think you could help post some code examples to test with?

**Comment by yanickrochon** [comment]
You mean add tests cases? For now, my intention was to make it seamless with existing use cases, and didn't bother reading existing tests; I ran `grunt travis --filter=scrollFire` and it passed. Also note the timestamp of this issue and my PR; I basically wrote and pushed all that in 20 minutes, before leaving work, today :smile:

**Comment by acburst** [comment]
Yeh no rush, Just wondering if you saved any of the code you used to discover these errors. Would be nice to have

**Comment by yanickrochon** [comment]
No, actually, I was investigating another bug, and started reading the source code for scrollFire.... the bug I have has nothing to do with scrollFire, but I still investigated that avenue. I noticed that, in my code, I create a "load more" control to create an infinite scrolling list, and I was calling scrollFire many times because of that. I just wanted to prevent mem leaks and other timers being executed for no reason in the background.

**Comment by yanickrochon** [comment]
I just realized that the tests do not run against the actual source, but against the compiled JavaScript?? This is just weird.... anyhow, I did all the tests (i.e. lint, compiling, running the server with ad-hoc testing, automated spec tests, etc.) and all seem to check out, now.

**Comment by acburst** [comment]
Added in 0257ec7

**Comment by yanickrochon** [comment]
You simply replaced setInterval with a throttled version. Many of the issues are not resolved, no.
