### ISSUE TITLE
Add "Feature Discovery"

### ISSUE THREAD

**Issue by AkshayChordiya** [Dogfalo/materialize#3919]
### Description
Adding "Feature Discovery" aka Onboarding Experience mentioned in the Material Design Guidelines to materializecss framework

### References
[Feature Discovery Material Design](https://material.google.com/growth-communications/feature-discovery.html)

**Comment by tomscholz** [comment]
@AkshayChordiya The link is broken, it's https://material.google.com/growth-communications/feature-discovery.html

**Comment by AkshayChordiya** [comment]
@tomscholz Thanks I fixed the link.

**Comment by inventti-leonardo** [comment]
I developed a tap target here #4164

**Comment by acburst** [comment]
Merged in bf01e95514495684d90754a16ba8eed25f0f074b
