### ISSUE TITLE
Navbar fixed goes to right on modal open

### ISSUE THREAD

**Issue by Kinark** [Dogfalo/materialize#3921]
### Description
Navbar fixed goes to right on modal open

### Repro Steps
Just add a navbar fixed and open a modal.

But I solved it with this:

```
body {
   width: 100%;
}

header, .navbar-fixed, .navbar-fixed nav {
   width: inherit;
}
```

**Comment by fega** [comment]
maybe it was solved or I cannot understand your issue
https://codepen.io/fega/pen/vxweaJ

Could you check if this is still an issue with the last version?
Closed due inactivity, feel free to reopen it if it is still necessary.
