### ISSUE TITLE
What file to edit when contributing?

### ISSUE THREAD

**Issue by smileytechguy** [Dogfalo/materialize#3925]
Hi,
I'm looking to submit a PR which will affect the JS, CSS, and Documentation.  What files would I edit?  (CONTRIBUTING.md only says what not to)
Also, should I write the html documentation or is that reserved for you guys?
Thanks,
@smileytechguy

**Comment by acburst** [comment]
If you are familiar with Grunt, you can use grunt monitor to help compile all the files. For editing Documentation, edit "component"_content.html in jade/page-contents. For editing JS you can just edit the individual js files. For editing css you should edit the Sass files in sass/components.

**Comment by developeranirudhprabhu** [comment]
@acburst @Dogfalo I think the question has been answered. We can close this ticket
