### ISSUE TITLE
Bug with button initializing on Meteor, Iron Router Layout, Materialize side-nav

### ISSUE THREAD

**Issue by lpgeiger** [Dogfalo/materialize#3928]
### Description
There is a case when the Materialize buttons do not initialized correctly. Hover, and click will not work, until you click once.

This is a real corner case. I've isolated it to Meteor's iron router Router.layout() helper. And this issue only affects side-nav. The reason I've ticketed it in Materialize is because it only happens to side-nav. I'm wondering if any events being emitted are in conflict with initializing buttons.

### Repro Steps
Pull this repo, and run `> meteor npm install`, and then `>meteor`
https://github.com/keyscores/materialize_ironrouter_issue

When you start from the 'broken' template, the destination's buttons will not be initialized correctly. Hover, and click will not work, until you click once.

**Comment by keyscores** [comment]
Cross posted here: https://github.com/iron-meteor/iron-router/issues/1556

**Comment by keyscores** [comment]
@acburst  could it be that the templates are generating 2 <body> sections? Would this break side-nav but not other components?

**Comment by tomscholz** [comment]
Did you resolve the issue?
