### ISSUE TITLE
Not a issus but want to submit a project made with Materialize

### ISSUE THREAD

**Issue by onigetoc** [Dogfalo/materialize#3930]
I did find out that there's a lot of class similarity with Materialize and Bootstrap.

I wanted to have a good share counter button and i find bootstrap-social and SocialShare for counting sharing and create sharing button, but i was not happy with the button look.
Then i mixed 4 great scripts found on Github to do cool sharing buttons

Github project: https://github.com/onigetoc/Social-Share-Buttons-Counter
Demo: https://cdn.rawgit.com/onigetoc/Social-Share-Buttons-Counter/master/demo-bootstrap.html

**Comment by kmmbvnr** [comment]
Very nice. 

I'm thinking about to start new project `awesome-materialize` - curated list of 3d party libs and tips to work with MaterializeCSS

**Comment by onigetoc** [comment]
By the way, i also did a Chrome Extension template with Materialize. 
I was inspired by the new Chrome Extension for Chromecast from Google.
https://github.com/onigetoc/Materialize-CSS-Chrome-Extension-template

**Comment by acburst** [comment]
Github issues isn't the place for this. Feel free to send us an email
