### ISSUE TITLE
Black can't be the primary color

### ISSUE THREAD

**Issue by pawelad** [Dogfalo/materialize#3932]
### Description
When setting `black` as the primary color the SASS files won't compile. I know black isn't really a material color, but I believe this is still a bug.

### Repro Steps
When setting primary color to black:
```
$primary-color: color("black", "base") !default;
```
and trying to compile the files you get:
```
Error: argument `$color` of `rgba($color, $alpha)` must be a color

       Backtrace:
       	app/static/materializecss/sass/components/_tabs.scss:57, in function `rgba`
       	app/static/materializecss/sass/components/_tabs.scss:57
        on line 57 of app/static/materializecss/sass/components/_tabs.scss
>>       color: rgba($tabs-text-color, .7);
   -------------^
```
 When switching it back to a 'regular' color (i.e. 'red') everything works as expected.

**Comment by kmmbvnr** [comment]
You should specify it directly, without referring to material colors map.

```
$primary-color: #000000; 
```

**Comment by pawelad** [comment]
Thanks, the fix does work.

Any reason why that's required? Is that you don't specify color 'type' for black, as it only has one, and thus it can't be used with `color()` function?

**Comment by kmmbvnr** [comment]
`color` is the helper that translates material names like `red lighten-5` to hex values - https://github.com/Dogfalo/materialize/blob/master/sass/components/_color.scss#L402

So it's not a fix. That's how it suppose to work.

 If the color is not in the predefined list of colors, it can't be converted to hex in sass.

**Comment by pawelad** [comment]
Yeah, I get it now.

Thanks for the help and the explanation!
