### ISSUE TITLE
Roboto display issue

### ISSUE THREAD

**Issue by Capu-Johann** [Dogfalo/materialize#3935]
Hi, The roboto font displays weirdly on firefox since two days: (on every website that contains Roboto)
![image](http://image.prntscr.com/image/08a49ecc00284249800b638df4fe19cf.png)
Have you an idea how I can fix that?
I tried [this](http://stackoverflow.com/questions/34751547/display-issues-with-roboto-font-from-materialize-in-firefox) and searched for other solution but nothing worked unfortunately

**Comment by developeranirudhprabhu** [comment]
@acburst Do you think we can do anything about this? m not sure if font rendering is in our hands

**Comment by Dogfalo** [comment]
@Capu-Johann Did you try not useing the Woff2 version of the font?

**Comment by Capu-Johann** [comment]
@Dogfalo I assume I did.
But I haven't the problem anymore, dunno when it happened. Maybe when I updated firefox.. not sure though :/

**Comment by ssinyagin** [comment]
I see this behavior in Firefox 42

**Comment by ssinyagin** [comment]
![materialize_issue_3935](https://cloud.githubusercontent.com/assets/393007/23156674/416b320a-f818-11e6-8765-44f0a8037b24.png)

**Comment by Capu-Johann** [comment]
Note: When I had the font issue I had it on other websites that also contains roboto.
