### ISSUE TITLE
Multiple Select Limit number of selections

### ISSUE THREAD

**Issue by z1haze** [Dogfalo/materialize#3938]
Please forgive me If I am reposting, but with so many issues ,its hard to tell.. I am just trying to limit the number of selections from the multiple select. I am trying to just use jquery, to check on change, but it seems the context of this is the select itself, and not the selected option, so there seems to be no way to limit the number of options a user has checked. Please look into this. thanks.

even the event.target shows the select element. How are we supposed to get the actual option thats being changed?

**Comment by Verurteilt** [comment]
It seems to be you want to limit the number of items a user can choose with a multiple select?

If so, there might be some workarounds:

http://stackoverflow.com/questions/2046205/how-do-you-limit-options-selected-in-a-html-select-box

**Comment by z1haze** [comment]
That seems pretty hacky though and not very scalable.. so for every multiple select i have to create a variable to store the value of it??

**Comment by Verurteilt** [comment]
No need to create this script for every select you have, you can easily use this script:

`$('select').on('change', function() {
    var $sel = $(this).find(':selected');
    if ($sel.length < 4) {
        $sel.addClass('selected');
        $(this).find(':not(:selected)').removeClass('selected');
    }else
        $(this)
        .find(':selected:not(.selected)')
        .prop('selected', false);
});`

and customize it to listen to only those who have certain data attribute (data-max-select for example) and grab the max items option from a data attribute too.

**Comment by z1haze** [comment]
your solution unchecks every option

**Comment by z1haze** [comment]
i found a working solution that is modular though for anyone who is curious. it might not be perfect, but it works

```
$('select.limit').on('change', function() {
        if ($(this).val().length > $(this).data('limit')) {
            $(this).val($(this).data('value'));
            $('select').material_select();
        } else {
            $(this).data('value', $(this).val());
        }
    });
```

**Comment by Verurteilt** [comment]
Good to know 💃

**Comment by tomscholz** [comment]
Closed due inactivity. Feel free to reopen it, if it's still necessary.
