### ISSUE TITLE
Open modal from AJAX response

### ISSUE THREAD

**Issue by Verurteilt** [Dogfalo/materialize#3939]
It seems to be that the modal can only be opened from an inline html based on a selector, is there a way to open  a modal based on a response of an AJAX request?

**Comment by kmmbvnr** [comment]
Duplicate #586 

Check the https://github.com/Dogfalo/materialize/issues/586#issuecomment-255769998 for the proposed solution

**Comment by dbr0** [comment]
I'm having the same issue, not sure how does the #586 refers to this problem.

What I want to achieve is to open modal on AJAX .done() and redirect on close but after the last update (0.97.7, not 100% sure about this) it all broke.

Now I can only open modal with button.

Putting `$('.modal').modal();` or `$('.modal').modal("open");` in document ready does nothing.

Also I can't make this callback work:

`$('.modal').modal({
                complete: function() { alert('Closed'); }
            });`

`console.log('ok')` next to the code works nicely and so does opening modali via a href.

**Comment by developeranirudhprabhu** [comment]
@dbr0 Can you tell me how you were implementing it earlier and how are you doing it now and kind off functionality are you looking at?

**Comment by dbr0** [comment]
@developeranirudhprabhu It is solved as described in updates. First error with callback was my error and the second thing was to open the modal I needed to init it first. It's all working now here. However this was very unpleasant experience. Luckily for me it all broke during testing and not in production.

Not really sure how it was done before. If it's really important to you I could browse through my commits and search for the changes?

**Comment by developeranirudhprabhu** [comment]
@acburst I think we can close this ticket based on the above comment

**Comment by developeranirudhprabhu** [comment]
@Dogfalo I think we can close the ticket based on the above comments
