### ISSUE TITLE
Waves not working in Windows (touchscreen) + Chrome

### ISSUE THREAD

**Issue by Dogfalo** [Dogfalo/materialize#394]

**Comment by will-hart** [comment]
Unable to replicate in Win 7 or 8 using Chrome `39.0.2171.95`

**Comment by Dogfalo** [comment]
I believe it is only a problem when the computer also has a touch screen.

**Comment by carlosperate** [comment]
I can confirm waves does not work on Chrome nor Opera on Windows with a touch screen

**Comment by Dogfalo** [comment]
Should be fixed in bfff4395766db0154302c7dc074d72269bbcaed2. I may need some help testing this as neither of the core developers have a touchscreen windows device.

**Comment by carlosperate** [comment]
I can confirm it now works in Chome and Opera on my test environment (Windows 8.1 laptop with touch screen).

**Comment by Dogfalo** [comment]
Fixed in bfff4395766db0154302c7dc074d72269bbcaed2

**Comment by murliatdure** [comment]
Yeah this was initiated form touch device desktop, and now fixed.
Thanks alot..
