### ISSUE TITLE
I want to participate in translation

### ISSUE THREAD

**Issue by Lutece** [Dogfalo/materialize#3940]
Hello, I am working as a front-end developer in Korea.
I like Meterialize so much!
I want to know if I can participate in translation
I am currently translating JavaScript from the Mozilla Developer Network website.
I want all pages translated in Korean.
I'll wait answer.

thanks!

**Comment by kmmbvnr** [comment]
Hi, first you need to join to the materializecss translation project here - https://www.transifex.com/materialize

Probably, you will get approvement from the project maintainers in a several days after that.

![materialize overview](https://cloud.githubusercontent.com/assets/282529/20620948/7daf9f94-b326-11e6-94e8-66b2e95314e2.png)

**Comment by Lutece** [comment]
thank you!
