### ISSUE TITLE
Collapsible only accept 1 paragraph?

### ISSUE THREAD

**Issue by suntrop** [Dogfalo/materialize#3941]
### Description
The collapsible content default styles are strange. If you put in 2 <p> those are divided by a huge padding. Lists won't work at all. There are more problems with content styles in collapsible 

Is this an intended behaviour?

**Comment by kmmbvnr** [comment]
Can you please create a codepen that demonstrates the issue?

**Comment by suntrop** [comment]
There you go … http://codepen.io/suntrop/pen/qqXGQa

**Comment by tomscholz** [comment]
@suntrop Have you tried: https://codepen.io/tomscholz/pen/ZBxaPw ?

**Comment by acburst** [comment]
In times like these it is best to write some simple css to override our base style to whatever you choose.

**Comment by developeranirudhprabhu** [comment]
@suntrop This happens cause of the styles associated with p beyond the collapsible. As suggested by @acburst please customize these elements with appropriate selectors

**Comment by developeranirudhprabhu** [comment]
@acburst I think we can close this issue.

**Comment by suntrop** [comment]
I already customised it. I just wanted you to know that there are issues with it. You can't always replace a paragraph with line breaks, especially when the content comes from a CMS.

**Comment by Dogfalo** [comment]
We can place the padding on the `.collapsible-body` instead, that might be a good solution for this.

**Comment by developeranirudhprabhu** [comment]
@Dogfalo I think the issue is sorted. Please close this ticket as well

**Comment by Dogfalo** [comment]
Fixed in a0a09ca
