### ISSUE TITLE
I want to be a contributer

### ISSUE THREAD

**Issue by Shivang-Bhandari** [Dogfalo/materialize#3943]
Hello, I am currently a front end web developer from India and i have been using materialize for quite some time now. I would like to contribute to the project in any way possible.
Thank you for this amazing open sourced project

**Comment by SulphurDioxide** [comment]
Check out CONTRIBUTING.md in the main repository.

**Comment by acburst** [comment]
Feel free to send us an email at materializeframework@gmail.com.

But the best way to contribute at first is to make well written pull requests. Make sure to write out and explain what you've changed or done to help make the merge easier. If you have any questions you can always email us about anything.
