### ISSUE TITLE
Input Field Icon Alignment Issue

### ISSUE THREAD

**Issue by Shivang-Bhandari** [Dogfalo/materialize#3944]
![icon](https://cloud.githubusercontent.com/assets/16368588/20636497/1efe6d9a-b394-11e6-8c58-2bb7ebaea161.jpg)
The Icon added in the input field to cancel the input (Cross Icon) is slightly raised from the centre and is not in symmetry with the input field.
I am attaching a screenshot of the issue i am facing.
I have found the fix and will be generating a pull request for the same.

The source code can be viewed at : github.com/Shivang-Bhandari/P5-Neighborhood-maps

**Comment by acburst** [comment]
Can you make a codepen to easily reproduce this?

**Comment by Shivang-Bhandari** [comment]
@acburst sure thing

**Comment by Shivang-Bhandari** [comment]
@acburst 
Codepen Link : http://codepen.io/thegrim/pen/yVjwZj

**Comment by fega** [comment]
You  have markup errors http://codepen.io/fega/pen/wdBEJX?editors=1010
