### ISSUE TITLE
Grid elements misaligned when svg and png/jpg in columns

### ISSUE THREAD

**Issue by wemyss** [Dogfalo/materialize#3946]
### Description
So when you use the grid system with mixed image types the columns and rows move in strange ways.

<img width="1160" alt="screen shot 2016-11-26 at 2 32 05 pm" src="https://cloud.githubusercontent.com/assets/8426915/20637764/2d796752-b3e5-11e6-90d3-fe94d6068454.png">

### Repro Steps
Use the following html (from the codepen):

```html
<div class="container">
  <div class="row">
    <div class="col s6 m4">
      <img src="http://s.cdpn.io/3/kiwi.svg">
    </div>
    <div class="col s6 m4">
      <img src="http://www.personal.psu.edu/users/r/j/rjq5009/mushroom.png">
    </div>
    <div class="col s6 m4">
      <img src="http://s.cdpn.io/3/kiwi.svg">
    </div>
    <div class="col s6 m4">
      <img src="http://www.queness.com/resources/images/png/apple_ex.png">
    </div>
    <div class="col s6 m4">
      <img src="http://s.cdpn.io/3/kiwi.svg">
    </div>
    <div class="col s6 m4">
      <img src="http://s.cdpn.io/3/kiwi.svg">
    </div>
  </div>
</div>
```

### Screenshots / Codepen
[codepen of the problem](http://codepen.io/wemyss/pen/VmzvrG?editors=1100)

**Comment by acburst** [comment]
This is how it will look. What do you want it to do? If you want things to fit perfectly try looking into 3rd party grid libraries like [Masonry.js](http://masonry.desandro.com/). This is not something that can be achieved with CSS alone.

**Comment by developeranirudhprabhu** [comment]
@wemyss alternatively if you know the max height that your images can have you can specify the min height. That ways the will appear aligned. The shortcoming of that is hardcoded value of height

**Comment by developeranirudhprabhu** [comment]
@acburst Can we close this issue? I dont see there is anything more that can be discussed and added
