### ISSUE TITLE
Select: Tab key after second .material_select()

### ISSUE THREAD

**Issue by MazeT73** [Dogfalo/materialize#3948]
### Description
I'm using materialize in a meteor project with react. The data for the select component is received from the server asynchronously so I have two places where I call `$(this.selectInput).material_select();`
After the second call I'm no longer able to focus the select component with the tab key. I have to press tab twice on the component which is before the select component and I can't figure out where the focus has gone after pressing tab the first time.
It seems no visible component has received the focus, but I can't figure out which one it is. If I set tabindex="-1" to the select element the materialized select component is left out of tab order and the component before and after the select component receive the focus with a single tab key press, just as expected.

### Repro Steps
```
componentDidMount() {
  $(this.selectInput).material_select();
}

componentDidUpdate() {
  $(this.selectInput).material_select();
}

render() {
  return (
    <select id={this.props.field.name}
      ref={(select) => this.selectInput = select}
      value={this.props.field.value}>
      {
        this.props.selectFrom.map((option) => {
          const value = option[this.props.selectKey];
          return (
            <option key={option._id}
              value={value}>
              {TAPi18n.__(`${option[this.props.optionKey]}`)}
            </option>
          )
        })
      }
    </select>
  )
}
```

I hope someone has a hint how I can debug where the focus has gone or how I can solve the problem itself. Thank you in advance for your help.
Matthias

**Comment by fega** [comment]
Could you check if this is still an issue with the last version of both projects? also, can you provide a codepen or something similar?

Thanks

Closed due inactivity, feel free to reopen it if it is still necessary.
