### ISSUE TITLE
Parallax in header container

### ISSUE THREAD

**Issue by SaltyPotato** [Dogfalo/materialize#395]
So i want to put a parallax image in the header container
(In the template). But it doesnt work in any way you try.
So if there's a solution please share if not please fix it.

With best regards,

Salty

**Comment by tmd-uk** [comment]
Hi SaltyPotato,

Here's what I just did and it worked fine first go! 

```Html
<!-- Start Parallax Header -->
  <div class="parallax-container">

  <h1 class="header center orange-text">Starter Template</h1>

      <div class="row center">
        <h5 class="header col s12 white-text">A modern responsive front-end framework based on Material Design</h5>
      </div>

      <div class="row center">
        <a href="#" id="download-button" class="btn-large waves-effect waves-light orange">Get Started</a>
      </div>

    <div class="parallax"><img src="images/parallax1.jpg"></div>
  </div>
<!-- End Parallax Header -->
```
Assuming you have added your css and js, give this a try!

**Comment by SaltyPotato** [comment]
Thanks tmd!
See you are a fellow ubuntu user :)

With best regards,

Salty

**Comment by tmd-uk** [comment]
Most welcome Salty, have been for a while, but only for coding :) 

Regards 

Shane (TMD)

**Comment by braginteractive** [comment]
@tmd-uk Does your example work when you resize? The image is jumping below the text, was wondering if you are having the same results?

**Comment by tmd-uk** [comment]
@braginteractive Yeah I found the same results when testing mobile and tablets after the issue was closed. I'm not sure if I fixed it though, but I'll have a look.
