### ISSUE TITLE
inline input field restricted size

### ISSUE THREAD

**Issue by matteoformenti** [Dogfalo/materialize#3950]
### Description
An inline input-field doesn't take up all the available space, when "width: 100%" is applied, the input goes back to the new line
Using materializecss v0.97.8
### Repro Steps
```
<div class="col s12 m3 l2">
   <i class="material-icons" style="cursor: pointer">swap_vert</i>
   <div class="input-field inline">
      <input type="text" name="name" placeholder="placeholder">
   </div>
</div>
```
Inline, doesn't take up all the available space in the col.

```
<div class="col s12 m3 l2">
   <i class="material-icons" style="cursor: pointer">swap_vert</i>
   <div class="input-field inline" style="width:100%">
      <input type="text" name="name" placeholder="placeholder">
   </div>
</div>
```
Same as without the style definition.

**Comment by kmmbvnr** [comment]
Have you tried to add class `prefix` to the `<i class="material-icons"` ?

**Comment by matteoformenti** [comment]
Thanks! It works! For anybody interested, here's the working snippet
` <div class="col s12 m3 l2 input-field">
                <i class="material-icons prefix" style="cursor: pointer">swap_vert</i>
                    <input type="text" name="name" placeholder="placeholder">
            </div>`
