### ISSUE TITLE
materialize sideNav method integration with phonegap

### ISSUE THREAD

**Issue by Toomavic** [Dogfalo/materialize#3951]
Hi all

currently I am developing new project with phonegap and decided to choose materialize as UI for the project.

so after using $(".button-collapse").sideNav(); I found small issue 

when I set the property draggable: true , it creates <div class="drag-target"></div> 
when click on this div , menu disappers and changing opacity to 0
and setting style="transform: translateX(0px);  to your menu's <ul>

but here is the prblem :: 
when I tried dragging menu out , I found the layer keep arising. and to remove it I have to click on it.

After debugging I found that , while dragging out it changes style transform: translateX(-310px); to menu's <ul> , while it should be transform: translateX(-100%);

I tried changing it it the js file but I stuck .. so anyone could help ?!

**Comment by Toomavic** [comment]
I am trying to add $overlay.remove(); when user drag menu out

**Comment by Toomavic** [comment]
![1](https://cloud.githubusercontent.com/assets/10185045/20697229/86f615ca-b61d-11e6-88c7-30da86b8d2d8.png)

![2](https://cloud.githubusercontent.com/assets/10185045/20697233/8ea0e692-b61d-11e6-992b-4b4b19d7120b.PNG)

![3](https://cloud.githubusercontent.com/assets/10185045/20697236/92a5fce6-b61d-11e6-9736-62dc80a61b8a.png)

**Comment by Toomavic** [comment]
First image when I click on menu icon by draggin or clicking

second image when I drag out the menu and the slidenav-overlay still exist though it has opacity 0 ,but high z-index

third image after clicking on the overlay, it has been removed from DOM  by " $overlay.remove();"

**Comment by Toomavic** [comment]
Wohoo this is life !!!

Accidntly I found the solution and where to put $overlay.remove();

in materialize.js:: 
`         var removeMenu = function(restoreNav) {
          panning = false;
          menuOut = false;
          // Reenable scrolling
          $('body').css({
            overflow: '',
            width: ''
          });          
$('#sidenav-overlay').velocity({opacity: 0}, {duration: 200,
              queue: false, easing: 'easeOutQuad',
            complete: function() {
              $(this).remove();
            } });
          if (options.edge === 'left') {
            // Reset phantom div
            $dragTarget.css({width: '', right: '', left: '0'});
            menu_id.velocity(
              {'translateX': '-100%'},
              { duration: 200,
                queue: false,
                easing: 'easeOutCubic',
                complete: function() {
                  if (restoreNav === true) {
                    // Restore Fixed sidenav
                    menu_id.removeAttr('style');
                    menu_id.css('width', options.menuWidth);
                  }
// myEdit: added remove overlay here 
				  $('#sidenav-overlay').remove();
                }

            });
          }
          else {
            // Reset phantom div
            $dragTarget.css({width: '', right: '0', left: ''});
            menu_id.velocity(
              {'translateX': '100%'},
              { duration: 200,
                queue: false,
                easing: 'easeOutCubic',
                complete: function() {
                  if (restoreNav === true) {
                    // Restore Fixed sidenav
                    menu_id.removeAttr('style');
                    menu_id.css('width', options.menuWidth);
                  }
// myEdit: added remove overlay here 
				  $('#sidenav-overlay').remove();
                }
              });
          }
        };`

**Comment by tomscholz** [comment]
@Toomavic I like your profile picture

**Comment by JSMontoya** [comment]
I have the same issue, however the solution I found differ, in my case, the  $('#sidenav-overlay').remove(); line is in the section under de comment "Touch Event".
![image](https://cloud.githubusercontent.com/assets/8813145/21160775/10b394ae-c154-11e6-805a-cbe85e572571.png)

(Sorry my bad english...)

**Comment by Toomavic** [comment]
I tried to integrate the module outside in individual page alone , but I failed to create $dragTarget

so I am satisfied with the "toggle Side Nav" 

Only Solution I had done , 

`//handling side menu nav
function toggleSideMenu() {
    var menuUL = $("#slide-out");
    $("#menuBtn").click(function() {
        menuUL.css("transform", "translateX(0px)");
        menuUL.css("width", "260px");
        $("#sidenavOverlay").show();
    });
    $("#sidenavOverlay").click(function() {
        menuUL.css("transform", "translateX(-100%)");
        $("#sidenavOverlay").hide();
    });
}

`

**Comment by Toomavic** [comment]
you can say I had integrated it manually :(

**Comment by JSMontoya** [comment]
I found the cause behind the bug, and a simple solution, however the solution is in the materialize.js file (again).

[image](https://cloud.githubusercontent.com/assets/8813145/21224715/7ca54e6c-c29b-11e6-9ac4-2b8a06f482a5.png)

**Comment by Toomavic** [comment]
can you explain in details?

**Comment by JSMontoya** [comment]
Sometimes the sidenav-overlay element is present in the document, the line 2399 in image above creates a new sidenav-overlay element, and we not need two sidenav-overlay elements in the same document, when the drag event ends, one of the two sidenav-overlay elements dissapear, and the other persist.

The little fix check if the element sidenav-overlay is present, when is present it use the element for the panend event (end of the gesture), if not is present make a new sidenav-overlay and use them for the event.

(Sorry for my bad english, again)

**Comment by Toomavic** [comment]
Okey , That's good explanation :)

Do you know how can I fix it in code ?

**Comment by JSMontoya** [comment]
No :C

**Comment by Toomavic** [comment]
I can close it now by Applying JSMontoya's solution

**Comment by Toomavic** [comment]
Thanks a lot 👍
