### ISSUE TITLE
"fixed-action-btn" widgets getting over one another

### ISSUE THREAD

**Issue by imaia** [Dogfalo/materialize#3958]
### Description
I have a list of cards, where each has a fixed-action-btn with two actions. At the bottom right of my page, I have another fixed-action-btn with a single action. When scrolling, if one gets close to the other, one blocks the activation of the other. 

### Repro Steps
Create two fixed-action-btn close to each other. Try to activate the action each.

**Comment by tomscholz** [comment]
@imaia Codepen? Screenshot? Anything that explains the issue more specific?

**Comment by italomaia** [comment]
I probably messed up something. http://codepen.io/anon/pen/Rojpgd Someone close this issue, please.

**Comment by tomscholz** [comment]
Were you able to resolve the issue?

**Comment by imaia** [comment]
I altered the widget to another. Not really a solution, but, it worked.
