### ISSUE TITLE
Materialize Box caption not visible on latest Firefox due to a "left:0" missing

### ISSUE THREAD

**Issue by ciobamike** [Dogfalo/materialize#3959]
### Description
I use the materialize box with a `data-caption` attribute which is `position:fixed` at the bottom of the page.

On latest Firefox, I don't see the caption because it is somewhere far on right of the window.

The solution is simply to add `.materialbox-caption { left: 0; }` in this file : https://github.com/Dogfalo/materialize/blob/master/sass/components/_materialbox.scss

I'm not a developer so I can't help with a clean compiled pull request, sorry ;-)

**Comment by tomscholz** [comment]
@ciobamike https://github.com/tomscholz/materialize/commit/d9be67ae1f5408c3d9fd7a6b3aaf172bf58fa622 like this?

**Comment by acburst** [comment]
Can you post an example so I can reproduce this locally?

**Comment by Dogfalo** [comment]
Added in f59ca24. Seems to be a safe change.
