### ISSUE TITLE
Collapsible: spacing, identation and 'overriding' of span

### ISSUE THREAD

**Issue by Barntorcher** [Dogfalo/materialize#3962]
Long Texts in my sidebar /w collapsible cause big spaces between line breaks, strange indents and some kind of overwriting. I created a codepen for better understanding of the issue:
http://codepen.io/anon/pen/jVYqjx

Also here's a screenshot of all the Issues
https://i.stack.imgur.com/UPCUf.png

Shorter texts are unfortunately no option. I'm getting crazy by trying to fix this with a separate CSS.

**Comment by acburst** [comment]
Some general styles you can apply to make text not wrap into multiple lines:

```
white-space: nowrap;
overflow: hidden;
text-overflow: ellipsis;
```

Maybe this should be a general class? Or just something specific for collapsible? It definitely shouldn't be on by default, because overflow: hidden causes a lot of unintended issues.
