### ISSUE TITLE
HTML Links not working in Carousel

### ISSUE THREAD

**Issue by mukulmantosh** [Dogfalo/materialize#3965]
HTML Hyperlinks is not working in Carousel. When checking previous slides the hyperlinks are not working. But when slides are moving forward hyperlinks are working.
![new mockup 1](https://cloud.githubusercontent.com/assets/15572034/20830469/9a529fc2-b8a6-11e6-8f5c-f9632487c104.png)

**Comment by MrSourabh** [comment]
Can you please provide your code....

**Comment by mukulmantosh** [comment]
<!DOCTYPE html>
<html lang="en">
<head>
  <meta http-equiv="Content-Type" content="text/html; charset=UTF-8"/>
  <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1.0"/>

  <link href="css/materialize.min.css" type="text/css" rel="stylesheet" media="screen,projection"/>
</head>
<body>
 
 <div class="carousel">
    <a href="https://www.google.com" class="carousel-item" href="#one!"><img src="http://lorempixel.com/250/250/nature/1"></a>
    <a href="https://www.google.com" class="carousel-item" href="#two!"><img src="http://lorempixel.com/250/250/nature/2"></a>
    <a href="https://www.google.com" class="carousel-item" href="#three!"><img src="http://lorempixel.com/250/250/nature/3"></a>
    <a href="https://www.google.com" class="carousel-item" href="#four!"><img src="http://lorempixel.com/250/250/nature/4"></a>
    <a href="https://www.google.com" class="carousel-item" href="#five!"><img src="http://lorempixel.com/250/250/nature/5"></a>
  </div>

  
   <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.1.1/jquery.min.js"></script>
  <script src="js/materialize.js"></script>
  <script src="js/init.js"></script>

  </body>
</html>

**Comment by mukulmantosh** [comment]
![capture](https://cloud.githubusercontent.com/assets/15572034/20867800/6864e286-ba72-11e6-98cb-2543b8c38a6a.JPG)

**Comment by tomscholz** [comment]
@mukulmantosh Code...

**Comment by mukulmantosh** [comment]
@tomscholz  @MrSourabh  [code.txt](https://github.com/Dogfalo/materialize/files/632779/code.txt)

**Comment by acburst** [comment]
Your link isn't working. Try making a [codepen](http://codepen.io/Dogfalo/pen/xbzPQV) or use [pastebin](http://pastebin.com/)

**Comment by mukulmantosh** [comment]
@acburst http://pastebin.com/raw/DQBKNHwQ

**Comment by acburst** [comment]
Well basically, this happens because when you click on carousel items that aren't the center item, it will scroll to it. I'm not sure what a good solution is. Maybe an option that disables this behavior?

**Comment by mukulmantosh** [comment]
@acburst When we are moving the carousel items in left direction and the images are appearing in the center  the hyperlinks are still not working. But when moving in right direction all hyperlinks are working perfectly.

**Comment by ramanujamgond** [comment]
I would like to illustrate this error a bit. According to @mukulmantosh when we navigate the images from right side the links embedded behind the images are working but when we navigate it from left side the links embedded behind the images are not working. For better understating the error i am attaching a video kindly go through it to resolve the issue.

Code - http://pastebin.com/raw/DQBKNHwQ 

[![Carousel Error](http://i.imgur.com/NJDo4qv.png)](https://vimeo.com/194631609 "Carousel Error - Click to Watch!")

**Comment by MrSourabh** [comment]
Can anyone explicitly add z-index:9999 to elements and check again. This might solve issue. Sorry I'm traveling and don't have anything to test it. Appreciate your help

**Comment by ntoka** [comment]
Hi, just would like to bump this issue up - this is still a problem and I found not mentions of a fix in changelog or in other similar issues. The code I use is the following:
`<div class="row carousel">
        <div class="col s8 m4 carousel-item">
        <a href="newsentry.html">
          <div class="card horizontal"> 
            <div class="card-image valign-wrapper">
              <div class="left-align"><img class="foto1" src="images/test.jpg"></div>
            </div>
            <div class="card-stacked">
          <div class="card-content">
          <h6 class="header">News Entry1</h6>
              <p>I am a very simple card. I am good at containing small bits of information.</p>
          </div>
            </div>
          </div>
        </a>
        </div>
        <div class="col s8 m4 carousel-item">
        <a href="newsentry2.html">
          <div class="card horizontal">
            <div class="card-image valign-wrapper">
              <div class="left-align"><img class="foto1" src="images/test.jpg"></div>
            </div>
            <div class="card-stacked">
          <div class="card-content">
          <h6 class="header">News Entry2</h6>
              <p>I am a very simple card. I am good at containing small bits of information.</p>
          </div>
            </div>
          </div>
        </a>
        </div>
        <div class="col s8 m4 carousel-item">
        <a href="newsentry3.html">
          <div class="card horizontal">
            <div class="card-image valign-wrapper">
              <div class="left-align"><img class="foto1" src="images/test.jpg"></div>
            </div>
            <div class="card-stacked">
          <div class="card-content">
          <h6 class="header">News Entry3</h6>
              <p>I am a very simple card. I am good at containing small bits of information.</p>
          </div>
            </div>
          </div>
          </a>
        </div>
      </div>`
When swiping right - all items open the links correctly. When swiping left- link is ignored until you reach the starting item of the carousel.

**Comment by rosentoski** [comment]
Same problem. Watching for a solution.

**Comment by mukulmantosh** [comment]
On Monday, 24 April 2017 8:26 PM, Rory Osentoski <notifications@github.com> wrote:
 

 Same problem. Watching for a solution.—

**Comment by DanielRuf** [comment]
http://codepen.io/anon/pen/NjRYrB

**Comment by mukulmantosh** [comment]
@DanielRuf Thanks ! Problem Fixed

**Comment by rosentoski** [comment]
I use the cdnjs hosted version does this fix apply to them or do I need to download the files and incorporate them directly? I guess I'm not sure how to apply the fix.

**Comment by DanielRuf** [comment]
@rosentoski the fix in the PR is not yet merged. Just @acburst and @Dogfalo, the maintainers and owners, can merge it into master.

Only the next tagged release would contain the fix.


If you want to apply it now you have to change the file yourself, compile Materialize using Grunt and include the compiled files instead of the files from the CDN.

**Comment by jromerocastro** [comment]
@DanielRuf  Thank's !!!

**Comment by jromerocastro** [comment]
@rosentoski Edit materialize.js, function clic(e)  <-- line 7836 

       function click(e) {
          // Disable clicks if carousel was dragged.
          if (dragged) {
            e.preventDefault();
            e.stopPropagation();
            return false;

          } else if (!options.fullWidth) {
            var clickedIndex = $(e.target).closest('.carousel-item').index();
            var diff = (center % count) - clickedIndex;

            // Account for wraparound.
            if (!options.noWrap) {
                if (diff < 0) {
                    if (Math.abs(diff + count) < Math.abs(diff)) { diff += count; }
                } else if (diff > 0) {
                    if (Math.abs(diff - count) < diff) { diff -= count; }
                }
            }

            // Disable clicks if carousel was shifted by click
            if (diff !== 0) {
              e.preventDefault();
              e.stopPropagation();
            }
            cycleTo(clickedIndex);
          }
        }

**Comment by orientnews** [comment]
for mobile try to add this code
`var detectTap = false; 
var time = 0;
$('.carousel a').on('touchstart', function() {
    detectTap = true; 
    time = new Date().getTime();
});
$('.carousel a').on('touchmove', function() {
    detectTap = false; 
    time=0;
});
$('.carousel a').on('touchend', function(event) {
    var time1 = new Date().getTime();
    if (detectTap && time1-time<3000){
      if($(this).attr('target')=="_blank")
        window.open($(this).attr('href'),'_blank');
      else
        window.location.href = $(this).attr('href');
    }
    time =0;
});`

**Comment by orientnews** [comment]
var detectTap = false; 
var time = 0;
$('.carousel a').on('touchstart', function() {
    detectTap = true; 
    time = new Date().getTime();
});
$('.carousel a').on('touchmove', function() {
    detectTap = false; 
    time=0;
});
$('.carousel a').on('touchend', function(event) {
    var time1 = new Date().getTime();
    if (detectTap && time1-time<1000){
      if($(this).attr('target')=="_blank")
        window.open($(this).attr('href'),'_blank');
      else
        window.location.href = $(this).attr('href');
    }
    time =0;
});

**Comment by les113** [comment]
> http://codepen.io/anon/pen/GmjGPr

Fix has been removed from this codepen

**Comment by les113** [comment]
> @rosentoski Edit materialize.js, function clic(e) <-- line 7836
> 
> ```
>    function click(e) {
>       // Disable clicks if carousel was dragged.
>       if (dragged) {
>         e.preventDefault();
>         e.stopPropagation();
>         return false;
> 
>       } else if (!options.fullWidth) {
>         var clickedIndex = $(e.target).closest('.carousel-item').index();
>         var diff = (center % count) - clickedIndex;
> 
>         // Account for wraparound.
>         if (!options.noWrap) {
>             if (diff < 0) {
>                 if (Math.abs(diff + count) < Math.abs(diff)) { diff += count; }
>             } else if (diff > 0) {
>                 if (Math.abs(diff - count) < diff) { diff -= count; }
>             }
>         }
> 
>         // Disable clicks if carousel was shifted by click
>         if (diff !== 0) {
>           e.preventDefault();
>           e.stopPropagation();
>         }
>         cycleTo(clickedIndex);
>       }
>     }
> ```

Fix not incorporated into v1.0.0. Instructions out of date.

![Capture](https://user-images.githubusercontent.com/7949436/103535638-010c4700-4e89-11eb-85b5-2886296c02fc.PNG)
