### ISSUE TITLE
Issue with onOpen option in collapsible

### ISSUE THREAD

**Issue by praveeni2it** [Dogfalo/materialize#3966]
### Description
When the collapsible is triggered to open, onOpen option should be called in collapsible method.
But that is not happening as the onOpen option is not triggered.

**Comment by acburst** [comment]
Please provide some form of codepen or example so I can reproduce this issue locally. Try and put more effort into explaining your issue.

**Comment by AndyNovo** [comment]
I found this while trying to solve the problem, I just had to update to the latest version...  May or may not help some passerby.
