### ISSUE TITLE
Sidenav links not working on small screens

### ISSUE THREAD

**Issue by LucasPaganini** [Dogfalo/materialize#3969]
### Description

At 992px width the navbar transforms to be mobile, everything works just fine till it gets to less than 590px width. When it comes to that screen width, the sidebar links (inside `<li>`s) fail on their left side while the width gets lower. They are still clickable on their right side, but if you try to click near the left, they fail and the sidenav closes as if you were clicking outside it.

![header-error](https://cloud.githubusercontent.com/assets/24356697/20860402/6e03b2d6-b95e-11e6-920e-e21e220a162a.gif)

I don't know how to record my mouse to show in the .gif but I am <a href="http://webond.com.br/header-error.html">uploading here</a>, I'll leave it there for a while even after the problem is solved. You can enter there and resize to browser like i did in the .gif then hover your mouse on the links, you will see that they're not working on their left side and the problem gets bigger when the screen gets smaller.

**Comment by arpit1997** [comment]
@LucasPaganini  I got same kind of problem here but in my case sidenav links are not working even in 992px devices. I followed the example in docs but i can't get it working. Can you suggest me some solution ?. It would be very helpful

**Comment by LucasPaganini** [comment]
@arpit1997 sorry man, I'm still having the problem... I'm even questioning writing form scratch without the materialize framework :/

**Comment by arpit1997** [comment]
@LucasPaganini I have got some observations about this problem. when sidenav width is greater than 65% of the total screen and scren size is not enough then links in sidenav does not work correctly. for small scrrens you should use dynamic width.
```
  $('.button-collapse').sideNav({
      menuWidth: 300, // Default is 240
      edge: 'right', // Choose the horizontal origin
      closeOnClick: true, // Closes side-nav on <a> clicks, useful for Angular/Meteor
      draggable: true // Choose whether you can drag to open on touch screens
    }
  );
```
here instead of fixed menuWidth calculate the total screen width and put 65% of it.

**Comment by fega** [comment]
Please provide a way to reproduce it. like a [codepen](https://codepen.io/fega/pen/BWeZaG)

Closed due inactivity, feel free to reopen it if it is still necessary.
