### ISSUE TITLE
Display default inputs

### ISSUE THREAD

**Issue by levani** [Dogfalo/materialize#3975]
As I see only the select element supports the `browser-default` class to display the default select element. Is there a way to use this class on other form elements as well? I want to use the default text inputs and checkboxes in some parts of the app but can't find an 'official' way to do so...

**Comment by developeranirudhprabhu** [comment]
There is official thing for this requirement at present. Will add this and commit. For now you can add ":not(.browser-default)" to all the input types you wish to target at line 5700 in materialize.css. Present selector listed are

input:not([type]),
input[type=text],
input[type=password],
input[type=email],
input[type=url],
input[type=time],
input[type=date],
input[type=datetime],
input[type=datetime-local],
input[type=tel],
input[type=number],
input[type=search],
textarea.materialize-textarea

**Comment by developeranirudhprabhu** [comment]
@acburst Please merge the PR

**Comment by developeranirudhprabhu** [comment]
@Dogfalo Please merge my PR so that we can resolve this ticket

**Comment by mckenzieja** [comment]
Been struggling with the same issues. We need browser defaults for forms for increased flexibility.
