### ISSUE TITLE
Unable to access http://materializecss.com/grid.html at http://materializecss.com/

### ISSUE THREAD

**Issue by himanshushankhala** [Dogfalo/materialize#3976]
Its website related issue.
Unable to access  http://materializecss.com/grid.html since past few days.
Kindly resolve the same asap.

Thank you

**Comment by kmmbvnr** [comment]
It works for me right now.

Is it happens for you for the single page or the entire website?

**Comment by himanshushankhala** [comment]
I'm still facing this issue for this link specifically else rest of the website is working fine.

**Comment by himanshushankhala** [comment]
I'm accessing it from Geo location : India

![screen shot 2016-12-07 at 11 53 35 am](https://cloud.githubusercontent.com/assets/3745564/20957113/d7f8aaa8-bc73-11e6-9819-bc079d5579f1.png)
![screenshot at dec 07 11-53-11](https://cloud.githubusercontent.com/assets/3745564/20957114/d80dc60e-bc73-11e6-86c3-d8e979e0b3e8.png)

**Comment by kmmbvnr** [comment]
Have you tried another browser? May be it's adblock related problem.

**Comment by himanshushankhala** [comment]
I tried to access with Safari and Chrome on MAC OSX ElCaptain.
Chrome on Elementary OS Loki  (linux).

I do not use ad blocker on safari.

**Comment by acburst** [comment]
Not sure why this would happen. We use github hosting so I don't really know what else to say. It's working on my safari locally. You've navigated there through the side nav and directly?

**Comment by allsyed** [comment]
Working for me
