### ISSUE TITLE
Alignment of col elements with different heights within a row

### ISSUE THREAD

**Issue by matthenning** [Dogfalo/materialize#3980]
### Description
When using multiple col elements within a row the vertical alignment can create white spaces (see screenshots, for lack of better descriptive skills).

I guess it's a general problem with the grid system. Is there an elegant solution to achieve what I drew up in the Screenshots section?

### Repro Steps
```
<div class="row">
    <div class="col l4" style="height: 150px"> </div>
    <div class="col l4" style="height: 100px"> </div>
    <div class="col l4" style="height: 150px"> </div>
    <div class="col l4" style="height: 150px"> </div>
</div>
```

### Screenshots / Codepen
Actual behaviour: https://i.imgur.com/Y5nLEgP.png

Desired behaviour: https://i.imgur.com/BggPxbl.png

**Comment by acburst** [comment]
[Masonry.js](http://masonry.desandro.com/)

This is actually semi achievable in css with flexbox but it is not perfect and Masonry gives a lot more functionality.

**Comment by matthenning** [comment]
I've looked into flexbox but masonry seems to be exactly what I'm looking for, thank you.

**Comment by matthenning** [comment]
In case anyone else is looking for a solution, take a look at this: https://github.com/Dogfalo/materialize/tree/master/templates/masonry-template

**Comment by michelolvera** [comment]
It seems very **silly** to me that materialize does not have this solved...
