### ISSUE TITLE
Solution for "<select>" with icons "fontAwesome"

### ISSUE THREAD

**Issue by bitbuildes** [Dogfalo/materialize#3981]
### Description

In my case I used the fontawesome icons and wanted to insert them into a select. The solution I found is to modify the CSS of the input that shows the selection. And also add to the CSS of the ul li span lists the type of font to display.
And it stays that way.

### Result
![captura de pantalla 2016-12-07 a la s 19 10 17](https://cloud.githubusercontent.com/assets/23442644/20980569/5a2f23ca-bcb1-11e6-8aae-ff31b2995d0c.png)

![captura de pantalla 2016-12-07 a la s 19 10 04](https://cloud.githubusercontent.com/assets/23442644/20980581/6ede7ffa-bcb1-11e6-801b-a753d6e430e8.png)

### Screenshots / Codepen
![captura de pantalla 2016-12-07 a la s 19 15 58](https://cloud.githubusercontent.com/assets/23442644/20980663/b6b12c7e-bcb1-11e6-9f60-b3b38d86411f.png)
![captura de pantalla 2016-12-07 a la s 19 15 19](https://cloud.githubusercontent.com/assets/23442644/20980682/cc5c7be6-bcb1-11e6-9228-9f2466908f6f.png)
![captura de pantalla 2016-12-07 a la s 19 17 48](https://cloud.githubusercontent.com/assets/23442644/20980717/f3213b68-bcb1-11e6-896f-ae7f5c03868b.png)

A greeting, I hope it serves you

**Comment by uok** [comment]
Thanks for sharing! Reminds me of ideas #3299 and #2709 to allow html in select which whould be a great feature, e.g. for country flags/sprites
