### ISSUE TITLE
side-nav links doesn't works in fixed navbar

### ISSUE THREAD

**Issue by miguelkashir** [Dogfalo/materialize#3982]
I have a navbar with brand logo at left and links at right, and the sidenav function works perfect.
I tried to make the navbar fixed, but now the sidenav links doesn't works (the sidenav appears in grey color)

**Code**
```erb
  <div class="navbar-fixed">
    <nav class="green">
      <div class="nav-wrapper">
        <a href="/" class="brand-logo">
          <i class="material-icons">shopping_basket</i>
          macromeal
        </a>
        <a href="#" data-activates="mobile-demo" class="button-collapse">
          <i class="material-icons">menu</i>
        </a>
        <ul class="right hide-on-med-and-down">
          <%= render 'layouts/links' %>
        </ul>
        <ul class="side-nav" id="mobile-demo">
          <%= render 'layouts/links' %>
        </ul>
      </div>
    </nav>
  </div>
```

**Screenshot**
![image](https://cloud.githubusercontent.com/assets/16723342/20989125/e98b896a-bcd3-11e6-991c-ce5f2b8a9247.png)

**Comment by simonsmh** [comment]
Yes same problem.

**Comment by Thanood** [comment]
Please try moving the `side-nav` out of the `nav`. Like this:

```html
  <div class="navbar-fixed">
    <nav class="green">
      <div class="nav-wrapper">
        <a href="/" class="brand-logo">
          <i class="material-icons">shopping_basket</i>
          macromeal
        </a>
        <a href="#" data-activates="mobile-demo" class="button-collapse">
          <i class="material-icons">menu</i>
        </a>
        <ul class="right hide-on-med-and-down">
          <%= render 'layouts/links' %>
        </ul>
      </div>
    </nav>
  </div>
  <ul class="side-nav" id="mobile-demo">
    <%= render 'layouts/links' %>
  </ul>
```

Not exactly sure but in principle this works. :smiley:

**Comment by simonsmh** [comment]
wow its working

Daniel Bendel <notifications@github.com>于2016年12月8日周四 下午10:32写道：

**Comment by tomscholz** [comment]
Duplicate https://github.com/Dogfalo/materialize/issues/3844

**Comment by miguelkashir** [comment]
Thanks @Thanood ! I will try it.
Btw, I already fixed it by this way:

```jQuery
function initialize() {
  $('.button-collapse').sideNav();
  $('.button-collapse').click(removeOverlay);
}

function removeOverlay() {
  $('div[id^=sidenav-overlay]').remove();
}
```

Oops, sorry @tomscholz . I searched but I didn't find it

**Comment by tomscholz** [comment]
These issues are all duplicates:
https://github.com/Dogfalo/materialize/issues/1664
https://github.com/Dogfalo/materialize/issues/3918
https://github.com/Dogfalo/materialize/issues/4046
https://github.com/Dogfalo/materialize/issues/4231
https://github.com/Dogfalo/materialize/issues/437
https://github.com/Dogfalo/materialize/issues/4318
https://github.com/Dogfalo/materialize/issues/3982
https://github.com/Dogfalo/materialize/issues/2879
https://github.com/Dogfalo/materialize/issues/4187

For the future discussion, please use this issue instead.
https://github.com/Dogfalo/materialize/issues/3844
