### ISSUE TITLE
JQuery error in website of materializecss documentation

### ISSUE THREAD

**Issue by aaroncadillac** [Dogfalo/materialize#3985]
### Description
Components not working

### Screenshots / Codepen

![captura de pantalla 2016-12-08 a la s 17 05 48](https://cloud.githubusercontent.com/assets/17807311/21031393/d6379dc8-bd68-11e6-9e42-a6c06f67496c.png)

**Comment by MrSourabh** [comment]
@aaroncadillac I don't see any error. But looks like they left out Spanish translation for some part of the  page.

**Comment by aaroncadillac** [comment]
Ok, now is worked, strange mistake about JQuery
