### ISSUE TITLE
Missing Spanish Translation in website footer

### ISSUE THREAD

**Issue by MrSourabh** [Dogfalo/materialize#3987]
### Description
Spanish translation for sections  'Ayuda a crecer a Materialize' and 'Únete al debate' are missing, website is showing text in English in those areas. 

### Repro Steps

1. Go to materializecss.com 
2. Select Espanol from translation menu.

**Comment by tomscholz** [comment]
I guess you speak Spanish. What you can do:
1. Go here https://www.transifex.com/materialize/materialize/
2. Click  _Help Translate "Materialize"_
3. Create an account e.g. with Github
4. Request access to the project...
5. Translate the strings you mentioned

**Comment by Dogfalo** [comment]
Please follow the instructions @tomscholz has suggested. We cannot fix this issue on GitHub.
