### ISSUE TITLE
Material select renders wrong option when using optgroups

### ISSUE THREAD

**Issue by kinkinweb** [Dogfalo/materialize#3988]
When using select with optgroups, if two options from different optgroup have the same text but different value and you select the second one, the first one is visually selected on load.

Here is a fiddle  where two options from different group have the name "Project 2" and the second one has the "selected" attribute. After load, when you click the select, the first option with "Project 2" is visually selected.

https://jsfiddle.net/h7vu2nb1/

**Comment by Dmitrev** [comment]
This is pretty broken.

If you need a quick fix, just add the class `browser-default` to the `<select>` element
https://jsfiddle.net/h7vu2nb1/1/

**Comment by acburst** [comment]
Fixed in v1-dev
