### ISSUE TITLE
Datepicker language management

### ISSUE THREAD

**Issue by ybert** [Dogfalo/materialize#3989]
Hello,

I dont know where languages can be found.  It says that datepicker is based on pickadate.js but i cant find pickadate.js stuff like translations. 
How can i simply add one of these languages to my datepicker? : https://github.com/amsul/pickadate.js/tree/3.5.6/lib/translations

**Comment by tomscholz** [comment]
Try this: https://codepen.io/tomscholz/pen/YpjGWP

**Comment by ybert** [comment]
I saw this. But I think we should use translation from amsul pickadate.
Its really ugly to translate on each language like this....

Could someone integrate traduction from https://github.com/amsul/pickadate.js/tree/3.5.6/lib/translations in materialize framework?
It could be really great.

**Comment by tomscholz** [comment]
No offense. , but if you want that feature, than do it yourself and create a pull request. :)

**Comment by tomscholz** [comment]
You could download the language file you want, than add it to your project and in the end you include it via `<script src="lib/translations/ar.js"></script>`. But make sure, that you include it *after* the materialize.js file!
