### ISSUE TITLE
Problem with angular !

### ISSUE THREAD

**Issue by dinoonex** [Dogfalo/materialize#399]
Hi,
I really love this framework, and I think that you done a nice job. 

But I have problem when using it with angular (inside ui-view), none of the java script functionality works. 
As you can see only when I added Waves.displayEffect(); into my controller then wave effect started to work. Why I have to add this ?
Now on red button I want to show modal but it is not showing, I think it is the same problem as the wave effect, but how can I solve this one.
Here is my plunker demo:
http://plnkr.co/edit/2Xa3w3?p=preview

**Comment by will-hart** [comment]
There have been a few issues related to this. For instance see #194 and #250. Basically materialize doesn't yet play nicely with dynamically generated content.

**Comment by dinoonex** [comment]
OK,
Solve this by loading materialize.js again in my view. But this is a big problem, because what is the point of making this css framework if it doesn't work with most popular mv* framework as Angular :)

**Comment by will-hart** [comment]
It might be worth checking if there is something similar to [ember-cli-materialize](https://www.npmjs.com/package/ember-cli-materialize)  for Angular. Ideally a 3rd party library wouldn't be required but at least this could get rid of some of the heavy lifting.

**Comment by dinoonex** [comment]
Yeah,
Switched to bootstrap-material until these problems are solved(although I love this framework more )

**Comment by Dogfalo** [comment]
Waves should work on all dynamicly added components now

**Comment by httpJunkie** [comment]
I currently am using  v0.96.1 and all js and css are of this version. When I load angular along with MaterializeCss, the JavaScript doesn't work, but if I take Angular away, MaterializeCss works without fine.

**Comment by zeeshanjan82** [comment]
Has anyone found the solution to the issue of angularjs not working with materialize. I am facing a similar issue where I am not able to run ng-click inside the navbar dropdown menu in materialize and I really wonder whats causing this issue and what is the fix.

**Comment by dllanob** [comment]
This is the solution! http://krescruz.github.io/angular-materialize/#about

**Comment by zeeshanjan82** [comment]
@dllanob It only includes part of the controls and not all the controls which we have in materialize

**Comment by tilhari95** [comment]
Same problem, I have several directive component in my angular application and I need to include materialize.min.js on each template in order to make nav-tabs and other material component to run.
I am not able to just include it once  in my index.html where ng-view directive is being used.
Dynamically generated html seems to be not functioning properly.

**Comment by hanschrome** [comment]
I've solved it by saving all on a variable and calling it on each ngOnInit() {
Modify your .js file adding at the beggining:
`var materialInit = function () {';

And at the end...
`}; materialInit();`

And you can call materialInit(); each time you need. It's so quickly, even i don't notice it.
