### ISSUE TITLE
Update noUiSlider from 8.0.2 to latest (9.x)

### ISSUE THREAD

**Issue by jacobq** [Dogfalo/materialize#3990]
I am encountering some problems with the range/slider control, such as annoying round-off errors (e.g. 0.9999999999 or 1.00000 appearing instead of 1 for the tooltips). As I understand it, these have been fixed in the upstream package. Could you please update the forked version bundled with materialize?

**Comment by Dogfalo** [comment]
Updated to 9.1 in 7992168

**Comment by dipakchandranp** [comment]
Still there are issue with noUiSlider version bundled with materialize css, with scrolling. Which is not happening when using the latest version of the plugin (ver: 13.1.4). Could you please update the forked version bundled with materialize css?
