### ISSUE TITLE
Dropdown buttons + Responsive Table

### ISSUE THREAD

**Issue by gpressutto5** [Dogfalo/materialize#3991]
### Description
I can't use dropdown buttons within a responsive table. The dropdown menu stay inside the table.

### Screenshots + Codepen
![image](https://cloud.githubusercontent.com/assets/12385501/21056355/6f95f5ce-be1c-11e6-871b-5d22508bbf88.png)
### Solution
I think there are 3 solutions:
1. Add a class to make the dropdown go up, and auto assign it on small screens.
2. Make the dropdown menu appear outside the table with position absolute.
3. The hardest, but also the most prettiest: make responsible tables turn into cards in small screens, like this: http://codepen.io/zavoloklom/pen/IGkDz

**Comment by wackychocolatefactory** [comment]
Workaround: Remove `position: relative` from `@media only screen and (max-width: 992px)
table.responsive-table tbody`
