### ISSUE TITLE
.row .col padding creates unexpected padding on cards

### ISSUE THREAD

**Issue by bradgillap** [Dogfalo/materialize#3994]
### Description

While adding some cards to a row I noticed large gaps around the images which is caused by this class. I'm not sure if this is working as expected but I had to override it.

```
.row .col {
  float: left;
  box-sizing: border-box;
  padding: 0 0.75rem;
  min-height: 1px;
}
```

Here's a shot of the issue.

https://i.imgur.com/M7bLZPo.png

### Screenshots / Codepen
Add supplemental screenshots or code examples. Look for a codepen template in our Contributing Guidelines.

**Comment by arpit1997** [comment]
@bradgillap I don't think the unexpected padding on the cards is a fault of .row or .col class. These classes con not interfere with card's css.  Did you change the css of card? Can you share your full code to explain this problem in detail? A good demonstration of cards can be seen [here](http://anyaudio.in) Try to recheck you code once
:smile_cat: :smile_cat:

**Comment by bradgillap** [comment]
https://github.com/bradgillap/websites/blob/master/bradgillap-v2/src/index.html

I'm not sure if that will work. I'll come up with a better demo hopefully by the weekend for you. Just really busy with the holidays right now.

**Comment by Dogfalo** [comment]
The padding on grid is intended.
