### ISSUE TITLE
website links not working

### ISSUE THREAD

**Issue by astroanu** [Dogfalo/materialize#3996]
### Description
website links, components, css, etc not working...

### Repro Steps
on chrome latest

### Screenshots / Codepen
the console says "Uncaught TypeError: $ is not a function(…)" no jquery loaded ??

**Comment by tomscholz** [comment]
Is jQuery included in your file?

**Comment by astroanu** [comment]
hi, the bug refers to the http://materializecss.com/ website. Apparently it's working as of now.
