### ISSUE TITLE
Get FAB opening animation to go from left to right instead of right to left.

### ISSUE THREAD

**Issue by YOO629** [Dogfalo/materialize#3998]
### Description
For aesthetic purposes, I want to have my Horizontal FAB's opening animation go from left to right instead of the default right to left. Is there an easy way to achieve this?

**Comment by tomscholz** [comment]
Do you mean the FAB toolbar?

**Comment by YOO629** [comment]
Updated description to be more specific

**Comment by tomscholz** [comment]
No, currently not, but I am working on a Solution. Maybe in the next days a will create PR ;)

**Comment by YOO629** [comment]
If you modify the `openFABMenu` fn and take out the `reverse()`, it looks like you animate from left to right instead. Just need to re-position the FAB button to the left and have the list grow to the right instead of to the left

```
              $this.find('ul .btn-floating').reverse().each( function () {
	        $(this).velocity(
	          { opacity: "1", scaleX: "1", scaleY: "1", translateY: "0", translateX: '0px'},
	          { duration: 80, delay: time });
	        time += 40;
	      });
```

modify to...

```
              $this.find('ul .btn-floating').each( function () {
	        $(this).velocity(
	          { opacity: "1", scaleX: "1", scaleY: "1", translateY: "0", translateX: '0px'},
	          { duration: 80, delay: time });
	        time += 40;
	      });
```

PS sorry for the spacing

**Comment by fega** [comment]
@tomscholz did you create the PR? :smile:

**Comment by tomscholz** [comment]
@fega Lol, no unfortunately not. But I'll look if I still have the code somewhere

**Comment by poppinlp** [comment]
+1 want this feature :)

**Comment by acburst** [comment]
Added a direction option in the FAB plugin in af660d37.
This will be available in v1.
