### ISSUE TITLE
Sidenav links that have same behaviour as tabs when loading content on page

### ISSUE THREAD

**Issue by melaniecreates** [Dogfalo/materialize#4001]
How do I get the Sidenav links to have the same behaviour as tabs when loading content on page?

Currently, if the page links are not inside the tabs class, all the pages content will be listed one after the other. Rather than hidden, until its link has been clicked.

**Comment by JSMontoya** [comment]
Hi!
Maybe this pen can help you 
http://codepen.io/JSMontoya/pen/QGJLMQ
(Sorry for my bad english)

**Comment by ben-sykes** [comment]
@melaniecreates : I'm not really sure I understand what you're trying to accomplish here. What have you already tried yourself? Could you create a fiddle/codepen?

**Comment by fega** [comment]
Closed due inactivity, feel free to reopen it if it is still necessary.
