### ISSUE TITLE
Sidebar over footer

### ISSUE THREAD

**Issue by jbernardo95** [Dogfalo/materialize#401]
![screen shot 2015-01-05 at 18 27 53 1](https://cloud.githubusercontent.com/assets/6342528/5621282/fe4441fc-952b-11e4-827a-f95a18ce1b7f.png)

Website bug

If you scroll this page (for example http://materializecss.com/components.html) all the way to the end, the sidebar gets over the footer

**Comment by Dogfalo** [comment]
Should be fixed!
