### ISSUE TITLE
Proper way to import Materialize in requirejs module 

### ISSUE THREAD

**Issue by gg4u** [Dogfalo/materialize#4012]
### Description
I want to import Materialize in a requirejs module. 
Materialize is passed through define(), but then a Materialize.toast() function is not recognised.
If not using requirejs, but loading from <script>, it works fine. 

Am I doing wrong with config file? 

```
# main.js - require configuration file
require.config({
    paths : {
        'jquery' : 'lib/jquery-2.2.4',
        'hammer' : 'lib/hammer.min',
        'materialize' : 'lib/materialize',
    },

 shim: {
	'materialize': {
	      deps: ['jquery', 'hammer'],
	}
  }
});

require(["app/my_app"], function(awesome) {
    return awesome.main()
    console.log(awesome);
});
```

```
# my_app.js module:

define(["lib/vivagraph",
  "lib/hashTable",
  "lib/object-observe-lite",
  "hammer",
  "materialize",
  "jquery"], 
  function (Viva, ht, observe, Hammer, Materialize, $) {
 ...
   
 console.log('Materiealize', Materialize); # ok, it is imported

 # ok, it does not complain with noMoreChildren()
  function noMoreChildren(nodeId) {
    Materialize.toast('No more nodes for: '+ readCache(nodeId).name, 4000);

    $('#data-'+nodeId)[0]
      .attr('fill-opacity',0.5);
  };
  

 # it complains with alertUser() ?? Materialize.toast is not a function ?
  function alertUser(message, time) {
    Materialize.toast(message, time);
  };


...}

)}
```

### Error
`Materialize.toast is not a function:`

<img width="603" alt="screen shot 2016-12-19 at 12 32 30 pm" src="https://cloud.githubusercontent.com/assets/284214/21311434/79546816-c5e7-11e6-8fae-1aca566a37ad.png">

Could you also explain why do I need to use a shim even if I am importing jquery and hammer before materiliase, even if I am using define() to include dependencies in my_app module?
[](http://requirejs.org/docs/api.html#config-shim)

If not using a shim, I get:

<img width="864" alt="screen shot 2016-12-19 at 12 30 31 pm" src="https://cloud.githubusercontent.com/assets/284214/21311460/8e0edd9a-c5e7-11e6-9456-e5eca3831018.png">

**Comment by exnihilo-creatio** [comment]
@gg4u You have to require the specific library from materialize you want to use. Try the following config file for requirejs: 

```
paths: {
     // I'm assuming you have a JS folder, this sets the root to the JS folder. So you do not have to 
     // keep writing: 'materialize/js/{js_file}.js' everytime.
     materialize': 'libs/materialize/js'
},
shim: {
     'materialize/velocity.min': {
            deps: ['jquery'] 
     },
     // Some of these were needed in order to force a loading order.
      'materialize/global': ['jquery', 'materialize/velocity.min'],
        'materialize/jquery.easing.1.3': ['jquery'],
        'materialize/jquery.hammer': {
            deps: ['jquery', 'hammerjs'],
            exports: '$.hammer'
        },
        'materialize/tabs': ['jquery', 'materialize/global'],
        'materialize/buttons': ['jquery', 'materialize/global'],
        'materialize/dropdown': ['jquery', 'materialize/global', 'materialize/jquery.easing.1.3'],
        'materialize/sideNav': ['jquery', 'materialize/jquery.hammer'], 
}
```

**Comment by fega** [comment]
@gg4u Did you solve the problem?
Thanks

Closed due inactivity, feel free to reopen it if it is still necessary.

**Comment by tomscholz** [comment]
Duplicate of https://github.com/Dogfalo/materialize/issues/1422
