### ISSUE TITLE
v0.97.8 breaks Meteor

### ISSUE THREAD

**Issue by cope** [Dogfalo/materialize#4014]
I haven't touched my project in several weeks and I came back to it today, started meteor and I get this error in the client:
`Couldn't find a template named "welcome" or "welcome". Are you sure you defined it?`

And in the console:
```
Error: Scss compiler error: Undefined variable: "$medium-and-down".
TypeError: Package['materialize:materialize'] is undefined
Exception in callback of async function: isRegistered@http://localhost:3000/app/lib/router.js
```

After a few hours of trying to figure it out, since the welcome template *is* there and has been there as the very first template, I found out that removing materialize from the project removes this error. Of course, the site now looks awful...

As soon as I bring back materialize back, the same error shows up again.

Found a temporary solution [here](http://stackoverflow.com/a/32609708/271873):
```
meteor remove materialize:materialize
meteor add materialize:materialize@=0.97.7
```

**Comment by tomscholz** [comment]
Duplicate to #3905 
Just read the whole thing :D

**Comment by tomscholz** [comment]
And `Couldn't find a template named "welcome" or "welcome". Are you sure you defined it?` Has something todo with, I guess you are using Iron:router, your router. Definitely not materialize

**Comment by cope** [comment]
Yes, I am using Iron:router.
If removing materialize removes the problem, and changing materialize from latest v0.97.8 to v0.97.7 completely fixes it, then IMO materialize v0.97.8 is to blame, no?

**Comment by tomscholz** [comment]
Do you have a route called `welcome` ?

**Comment by cope** [comment]
Yes. The route is there, it is the first one I created, the welcome start page...

It all worked fine until materialize v0.97.8 was picked up.
The code did not change before that.
The code did not change before I reverted back to v0.97.7.
The code is the same as it was several months ago when I last worked on it and deployed it to production...

**Comment by Dogfalo** [comment]
As @tomscholz said, this is a duplicate issue of #3905
