### ISSUE TITLE
length attribute on text inputs for character counter

### ISSUE THREAD

**Issue by Boournz** [Dogfalo/materialize#4015]
Hi Team, 

the character counter on text inputs requires the length attribute be set. Using the zend framework 3 in php, the length attribute is considered non-standard on a text input, and is therefore filtered out. The zend framework does allow custom attributes starting with data-*, so our solution has been to modify the Materialize js to look for the data-length attribute. Any chance this could be changed formally so we can continue to update Materialize ?

**Comment by wackychocolatefactory** [comment]
+1 

`length` is not a valid attribute for the input element as per [w3 docs](https://www.w3.org/TR/html5/forms.html#the-input-element).

_HTML5 Range_ also uses invalid attributes min and max.

**Comment by tcrognon** [comment]
+1, this feature is also unusable with JSX and, therefore, many React projects.

maxLength is valid and seems appropriate. If there's not a reason against it, I think it's best to use maxLength instead of data-length.

https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input#attr-maxlength

**Comment by wackychocolatefactory** [comment]
One minor note about maxlength is that it prevents further input when the limit is reached.

**Comment by Dogfalo** [comment]
I agree, it is preferable that you can still type over the limit but the UI should tell you that you have gone over the limit.

**Comment by Dogfalo** [comment]
Fixed in 76a6ee4
