### ISSUE TITLE
Remove horizontal Scrollbar and stack tabs

### ISSUE THREAD

**Issue by Anthall** [Dogfalo/materialize#4017]
Is there a way to remove the automatic horizontal scroll bar I'm getting with my menu and replace it with the tabs stacking underneath instead.  I've re-created the issue here...

http://codepen.io/Hornetant/pen/zobrvG

Thanks
Anthony

**Comment by smeijer** [comment]
Like this?

```cs

**Comment by Anthall** [comment]
That's done it.

Great, 
Thanks
