### ISSUE TITLE
retina.js breaks materialize.js

### ISSUE THREAD

**Issue by BabyDead** [Dogfalo/materialize#4019]
Ok, so after HOURS of stressing out, I found out that my update to retina.js is what broke materialize.js!

Combining the 2 javascripts above, results in materialize.js stating:

> ### Uncaught ReferenceError: require is not defined
So, uhm... I have 0 clue why, but I thought it should be noted. I think more scripts could make this happen?

**Comment by tomscholz** [comment]
This is still a problem? can you check it please? If so, can you post a codepen to help us visualize the problem?
Closed due inactivity, feel free to reopen it if it is still necessary.
