### ISSUE TITLE
Year in datepicker does not change

### ISSUE THREAD

**Issue by deborahvandervegt** [Dogfalo/materialize#4020]
### Description
Opening the datepicker and changing the day or month prior to changing the year will result in only changing the day or month. The year is the same as the one you previously picked.

### Repro Steps
1. Open the datepicker on http://materializecss.com/forms.html
2. Change the day to (for example) 5.
3. Change the year to (for example) 2008.
4. Close the datepicker.
5. In the textarea the date will now be 5 December, 2016 instead of 5 December, 2008.

### Screenshots / Codepen
![screenshot from 2016-12-21 16-15-45](https://cloud.githubusercontent.com/assets/13642829/21394400/c9e3a186-c798-11e6-8d58-cff6cd028b4c.png)

![screenshot from 2016-12-21 16-15-52](https://cloud.githubusercontent.com/assets/13642829/21394403/ccb50864-c798-11e6-903c-54186e92ec64.png)

**Comment by ben-sykes** [comment]
I can confirm this is happening. 

If you need a quick work-around, I imagine you could call a pickadate [set method](http://amsul.ca/pickadate.js/api/#method-set) during the [onClose event](http://amsul.ca/pickadate.js/date/#events). Not sure which set method would work best for this scenario off the top of my head though.

**Comment by Dogfalo** [comment]
This is intended. Selecting a day is what causes the date to change, choosing year is just a method of browsing like clicking the left and right arrows for months.

You can see this behavior on the spec: https://material.io/guidelines/components/pickers.html#pickers-date-pickers

**Comment by JesseRWeigel** [comment]
I don't think this is the intended behavior. Reading the docs does not make it clear. 

The datepicker in the Google calendar app for Android is a good example of how it should act.

If you open the datepicker from within an event editing screen and select the day first, then the year (just as the op did). The correct year is displayed when you close the modal. That is the behavior that is expected and makes the most sense.

**Comment by JesseRWeigel** [comment]
Based on @ben-sykes suggestion, the function in this gist should give the input the correct year value even if it is selected after the day.

https://gist.github.com/JesseRWeigel/04e37cd5eb6f98f37c98870715be5721

**Comment by retorquere** [comment]
I'm getting a lot of complaints from my users that "the date picker doesn't work"; people are just used to first picking the month, then the day, then the year. Looking at the docs it makes sense that the day would not be retained when switching months, but (for my users at least), changing year but not month/day is different. The material.io docs don't really show what the by-design behavior should be for changing the year only, but as I said -- lots of confused users on my end.

Will try the workaround by @JesseRWeigel.

**Comment by retorquere** [comment]
@JesseRWeigel the gist snippet assumes only one picker on a page, correct? because `thisInputID` and `thisPickerID` are declared above `$('.datepicker').pickadate({`, but `$('.datepicker').pickadate({` will apply those sttings to all datepickers on the page.

**Comment by retorquere** [comment]
The datepicker for materializecss is based on [this](http://amsul.github.io/pickadate.js/date.htm) picker right? The behavior my users expect is the standard behavior for that component; can I just re-enable that somehow?

**Comment by JesseRWeigel** [comment]
@retorquere Yes, I originally created the gist for one date picker, but I think it should work with multiple date pickers as well.

Materialize uses pickdate.js v3.5.0. I am not sure if all the pickdate.js functionality is available or how difficult it would be to just use the default pickdate.js component.

**Comment by retorquere** [comment]
I have reworked the snippet for multiple pickers, but even for one picker I don't see any change in behavior. What should I be seeing?

**Comment by JesseRWeigel** [comment]
What you should see is that a user can pick a day first, then the year and it will be correctly displayed in the input field. 

Normally the Materialize datepicker will not update the year unless you click on the day after setting the year.

The gist makes it so that the date gets updated either way.
