### ISSUE TITLE
Issue with Checboxes

### ISSUE THREAD

**Issue by Toomavic** [Dogfalo/materialize#4023]
I tried to implement check-boxes as described in docs, it was very easy
`<input type="checkbox" id="test6" checked="checked" />
      <label for="test6">Yellow</label>`
but here is the problem , I can't get the value of selected check-boxes !!

**Comment by kmmbvnr** [comment]
Any code snippet how you tried to do that?

btw, it's better to ask questions here - https://gitter.im/Dogfalo/materialize

**Comment by Toomavic** [comment]
Dude no code required 

but this may explain more 
http://codepen.io/anon/pen/NbmJev#anon-login

**Comment by Toomavic** [comment]
I tried using jQuery (as usual) like

`$("input[type='checkbox']").change(function() {});`
but failed

**Comment by kmmbvnr** [comment]
Use `$(this).is(':checked') `

http://stackoverflow.com/questions/4813219/testing-if-a-checkbox-is-checked-with-jquery

**Comment by Toomavic** [comment]
Dude Thanks alot 
check this link as ref
http://codepen.io/anon/pen/NbmJev#anon-login
