### ISSUE TITLE
Fixed and Extended Nav w/ Tabs + Fixed SideNav pushes the Header the to right 

### ISSUE THREAD

**Issue by iamrudra** [Dogfalo/materialize#4029]
### Description
When using fixed side nav, the other adjacent components needs to have `300 px` padding [per the documentation.](http://materializecss.com/side-nav.html#!). But this results in the header continuing over beyond the screen as follows (notice the missing right icon links)- 
![screenshot from 2016-12-25 01-15-06](https://cloud.githubusercontent.com/assets/12117759/21470477/fa6c877e-ca3f-11e6-9e26-cc0ce2909c58.png)

### Repro Steps
Here's the code. It takes care of the issue where we need to put the sidenav out of fixed nave to make it clickable - 

Markup - 
```
<header>
    <div class="navbar-fixed">
        <nav class="nav-extended">
            <div class="nav-wrapper">
                <a href="#" class="brand-logo">Logo</a>
                <a href="#" data-activates="mobile-demo" class="button-collapse"><i class="material-icons">menu</i></a>
                <ul class="right hide-on-med-and-down">
                    <li><a href="sass.html"><i class="material-icons">search</i></a></li>
                    <li><a href="badges.html"><i class="material-icons">view_module</i></a></li>
                    <li><a href="collapsible.html"><i class="material-icons">refresh</i></a></li>
                    <li><a href="mobile.html"><i class="material-icons">more_vert</i></a></li>
                </ul>
                <ul class="tabs tabs-transparent">
                    <li class="tab"><a href="#test1">Test 1</a></li>
                    <li class="tab"><a class="active" href="#test2">Test 2</a></li>
                    <li class="tab disabled"><a href="#test3">Disabled Tab</a></li>
                    <li class="tab"><a href="#test4">Test 4</a></li>
                    <li class="tab"><a href="#test5">Test 5</a></li>
                </ul>
            </div>
        </nav>
    </div>
    <ul class="side-nav fixed" id="mobile-demo">
        <li><a href="#!">First Sidebar Link</a></li>
        <li><a href="#!">Second Sidebar Link</a></li>
        <li class="no-padding">
            <ul class="collapsible collapsible-accordion">
                <li>
                    <a class="collapsible-header">Dropdown<i class="material-icons">arrow_drop_down</i></a>
                    <div class="collapsible-body">
                        <ul>
                            <li><a href="#!">First</a></li>
                            <li><a href="#!">Second</a></li>
                            <li><a href="#!">Third</a></li>
                            <li><a href="#!">Fourth</a></li>
                        </ul>
                    </div>
                </li>
            </ul>
        </li>
    </ul>
</header>
```

### Screenshots / Codepen
This is the assumed header that should display [per the code from docs site](http://materializecss.com/navbar.html) - 
![screenshot from 2016-12-25 01-20-35](https://cloud.githubusercontent.com/assets/12117759/21470493/6bda293e-ca40-11e6-9e18-544492e5ad28.png)

**Comment by iamrudra** [comment]
When I remove the class `navbar-fixed` from the div that wraps the navbar, it works as expected

**Comment by iamrudra** [comment]
My primary investigation tells me it is because of [this piece of css](https://github.com/Dogfalo/materialize/blob/master/dist/css/materialize.css#L4194)

**Comment by iamrudra** [comment]
@acburst - Happy to discuss the fix and contribute with a PR.

**Comment by acburst** [comment]
I'd be happy to look at a PR with some explanation and examples

**Comment by iamrudra** [comment]
@acburst - Cool! Could you elaborate on what kind of examples/explanation is required?

**Comment by alexvilanovab** [comment]
Thank you, it was driving me crazy! could you post the code you used for the padding please?

**Comment by alexvilanovab** [comment]
@iamrudra thank you, it was driving me crazy! could you post the code you used for the padding please?

**Comment by crabmusket** [comment]
I'm working around this using something along the lines of:

```html
<div class="navbar-fixed-2">
    <header>
        <nav class="nav-extended">
            <div class="container">
                <div class="nav-wrapper col s12">
                    ...content...
```

and 

```css
.navbar-fixed-2 {
    position: relative;
    height: 56px;
    z-index: 997;
    position: fixed;
    width: 100%;
    top: 0;
}
```

**Comment by tomscholz** [comment]
Closed due inactivity. Feel free to reopen it, if it's still necessary.

**Comment by gimelg** [comment]
I'm having the same issue. Is there any solution to this?
