### ISSUE TITLE
Dropdown won't disappear after calling dropdown('open')

### ISSUE THREAD

**Issue by MeMyselfI** [Dogfalo/materialize#4030]
If a default dropdown is opened programatically calling dropdown('open') it stays opened even after clicking an item because no event handler on $(document) is added here.

So, only thing you might do is to open the dropdown and add your own listener:
`
$('.card a.btn-floating').dropdown ('open');
setTimeout (function () {
 $(document).one ('click', function () {
  $('.card a.btn-floating').dropdown ('close');
  });
 },10);
`

**Comment by arpit1997** [comment]
did you initilize jquery plugin of dropdown.
> If a default dropdown is opened programatically calling dropdown('open') it stays opened even after clicking an item because no event handler on $(document) is added here.
So, only thing you might do is to open the dropdown and add your own listener:
$('.card a.btn-floating').dropdown ('open'); setTimeout (function () { $(document).one ('click', function () { $('.card a.btn-floating').dropdown ('close'); }); },10);

**Comment by acburst** [comment]
Fixed in 425cd4e

**Comment by MeMyselfI** [comment]
Not sure why, but I replaced the new bin/.js file and now nothing happens calling dropdown('open').

**Comment by acburst** [comment]
Were you using the latest version before? you may have to fix some conflicts with the newest version
