### ISSUE TITLE
black-text class does not work

### ISSUE THREAD

**Issue by ash32911** [Dogfalo/materialize#4033]
### Description
adding a black-text class to a navbar does not work. text remains white always.

I have attached a codepen with my issue.

am i doing something wrong ?

https://codepen.io/ash32911/pen/jVoREa

**Comment by codeyash** [comment]
Because its a helper to text color . You need to use directly on element. Like in this case use it on a tags
 or
author can comment better :)

**Comment by ash32911** [comment]
@codeyash thanks for the reply. I did try it on the <li> tags and <ul> tags, it still did not work :(

**Comment by ash32911** [comment]
NVM it works if i give it to the < a  > tag. Thanks for the help
