### ISSUE TITLE
Inserting html after page complate

### ISSUE THREAD

**Issue by mehmetilker** [Dogfalo/materialize#4034]
When I add bootstrap.css+materialize.css+materialize.js, everything works as expected.

But when I insert a button (as html) for example, after page complete, some features does not work.
data-tooltip for example.

I guess there should be a way to reinitialize materialize.js again.

Is there a way to do that ?

**Comment by acburst** [comment]
You can instead just reinitialize tooltips.

```
$('.tooltipped').tooltip();
```

**Comment by mehmetilker** [comment]
@acburst Yes it works.
But my problem something else I guess.
Maybe it is because I am using the library inside of an iframe on Chrome Extension.
When I call it as following;
`$("boxSelector")[0].contentWindow.$('.tooltipped').tooltip();`
It works in a page containing Iframe. But somehow not in chrome extension.

There should be another way calling script in of an Iframe.
Exception is: "Cannot read property '$' of undefined"

By the way, if  I am not wrong, I should do this for every component I insert to the page later page complete.
Thank you.
