### ISSUE TITLE
Links/Buttons in the collapsible Header

### ISSUE THREAD

**Issue by dra14825** [Dogfalo/materialize#4036]
Hello,
I tried to use a link and a Modal in the Header of a collapsible.
It works but when i click on the link or the modal-trigger the collapsible expands.

Is there a possibility to interrupt the collabsible Event so that it will not expand when i click on the link?
Or maybe that it only expands when i click on a specific button?

**Comment by Dogfalo** [comment]
Try stop propagation

**Comment by developeranirudhprabhu** [comment]
@dra14825 Can you share your code? As mentioned by @Dogfalo you can stop immediate propagation of event. Let us know if it works for you

**Comment by dra14825** [comment]
@developeranirudhprabhu I tried and it worked for me, but i changed the layout afterwards so i didnt need it anymore. 
But this is the code I used:
`$('.collapsible-header').click(function(e){
    e.stopPropagation();
});`

It worked fine for me, but as I allready mentioned I had different requirements and changed it therefore.
