### ISSUE TITLE
Tooltips not showing after pagination

### ISSUE THREAD

**Issue by freddy-daniel** [Dogfalo/materialize#4039]
Hi ,
I'm using materializecss and knockout.js on my project. I have integrated a pagination with knockout js initial tooltips are showing but after paginating tooltips are not showing and models are not triggering.

**Comment by developeranirudhprabhu** [comment]
@freddy-daniel You would need to reinitialize the tool tips on pagination. Using something like 

` $('.tooltipped').tooltip({delay: 50});`

Details are given here: http://materializecss.com/dialogs.html. Let me know if it helps

**Comment by freddy-daniel** [comment]
Thanks. It's working now.

**Comment by bruceyue** [comment]
@freddy-daniel how you did it?

**Comment by freddy-daniel** [comment]
Yes we should reinitialize that plugin with
$('.tooltipped').tooltip();
