### ISSUE TITLE
Select option

### ISSUE THREAD

**Issue by rajuonraj** [Dogfalo/materialize#4042]
select option is not destroy on touch move

**Comment by acburst** [comment]
Please explain your issue more and add example code

**Comment by developeranirudhprabhu** [comment]
@rajuonraj Can you add more description regarding the issue?

**Comment by Santa444** [comment]
Confirmed.
Select option not destory on touch move, safari iOS 10.
![pciuq-6bhpu](https://cloud.githubusercontent.com/assets/25008494/21768061/a56ab3c2-d688-11e6-91cd-f947c977ee88.jpg)

**Comment by rajuonraj** [comment]
position of Select option is not destroy when zoom out at touch device.  position of select option is static not dynamic not as like datepicker. you can replicate this issue on touch device when zoom out the device then click select box in any model. that time position will be dis order. so please give me any update

**Comment by fega** [comment]
Hello @rajuonraj,The solution should be close the select menu when the zoom is modified? or what do you want to mean when you say destroy?

**Comment by tomscholz** [comment]
Closed due inactivity. Feel free to reopen it, if it's still necessary.
