### ISSUE TITLE
How to add triangle in top of dropdown content 

### ISSUE THREAD

**Issue by davodavodavo3** [Dogfalo/materialize#4043]
### Description
Does anyone know how to add an arrow to dropdovn content so that it appears first?
My problem is that when you add an arrow through the pseudo-element(to dropdown-content) or div with styles ,first appears  the dropdown content and then arrow shows.
### Screenshots / Codepen
Example:
http://jsfiddle.net/esjrhg5n/

Example with our loved Materialize CSS (look at arrow)
https://jsfiddle.net/sj2tm8cd/13/

Thank's!!!

**Comment by Dogfalo** [comment]
If you don't want to use material icons, you can use unicode characters. You use `::before` to make it appear before the element, https://jsfiddle.net/sj2tm8cd/17/

**Comment by davodavodavo3** [comment]
I am sorry but your example is not that i ask for.See drop down content top arrow,not button arrow

**Comment by davodavodavo3** [comment]
https://jsfiddle.net/sj2tm8cd/20/
