### ISSUE TITLE
Cannot do anything with nested modal

### ISSUE THREAD

**Issue by tavsta** [Dogfalo/materialize#4044]
### Description
When opening a modal inside another modal. I can't not do anything except closing modal by clicking on `.modal-overlay`

### Screenshots
![image](https://cloud.githubusercontent.com/assets/7478003/21560514/046b4484-ce93-11e6-93c6-6838283eb52a.png)

Open parent modal
![image](https://cloud.githubusercontent.com/assets/7478003/21560517/13ca7742-ce93-11e6-9007-8e694c73ef42.png)

Inside parent modal, I open other modal, so I cann't do anything...
![image](https://cloud.githubusercontent.com/assets/7478003/21560524/212059e8-ce93-11e6-9ba6-636fc676cb45.png)

**Comment by developeranirudhprabhu** [comment]
@tavsta Can you mention your exact requirement and if possible share the code. In one of my projects i had requirement which was very much similar to this. What i opted for was placing all the modal screens in a single modal and toggling their visibility as per requirement.

**Comment by tavsta** [comment]
I know your solution, but we can't open multiple modals with a single modal. I want they appear at the same time.
I think `materialize css` has problem with z-index in `.modal-overlay`. I worked around by setting all `.moda-overlay`s has same z-index.

**Comment by developeranirudhprabhu** [comment]
Can you share your code?

**Comment by acburst** [comment]
Take a look at the code for this http://materializecss.com/test/html/multiple_modals.html

**Comment by avrahamcool** [comment]
having all the modals in the same level of hierarchy is not an ideal solution.
I need to open a modal that can open another modal, and this modal can open a modal and so on infinitely..
putting all of this modals in a single level of hierarchy, will require all of my module to `know` about this modal structure. and I will lose the ability to have disconnected modules.
