### ISSUE TITLE
Cannot import sass file from meteor package

### ISSUE THREAD

**Issue by Kostronor** [Dogfalo/materialize#4045]
### Description
Add a detailed description of your issue.

I am trying to import the materialize.scss file in meteor and the file can not be found.

### Repro Steps
Layout the steps to reproduce your issue.

meteor add materialize:materialize

`@import "{materialize:materialize}/sass/materialize.scss";`

Error:
```
   While processing files with fourseven:scss (for target web.browser):
   /client/main.scss: Scss compiler error: File to import:
   {materialize:materialize}/sass/materialize.scss not found in file:
   ...{}/client/main.scss
```

I tried searching in the repo but there is no documentation on what path to use to import it...

**Comment by tomscholz** [comment]
Try this; https://github.com/Dogfalo/materialize/issues/2217#issuecomment-268100489

**Comment by Kostronor** [comment]
Hey @tomscholz I looked at that issue, but I had no problem compiling materialize, I have a problem importing it, oddly enough. 

I'll try your branch our and report back if that fixed it :)

**Comment by Kostronor** [comment]
Oddly enough applying your fix and then importing `@import "{tomscholz:materialize}/sass/materialize.scss";` works perfectly fine! Thanks a lot @tomscholz 

Weird that there were no errors compiling it, that were shown...

**Comment by NitroBAY** [comment]
Why did you close this issue ? We cannot import SASS files even tough @Dogfalo said in many issues he added this possibility. When I `@import "{materialize:materialize}/sass/components/color";` it also says `   {materialize:materialize}/sass/components/color not found in file:` so this issue is still a problem.

**Comment by Kostronor** [comment]
@NitroBAY it worked for me

**Comment by NitroBAY** [comment]
@Kostronor yes but you add to download the repository so the atmosphere package is broken, isn't it ?

**Comment by Kostronor** [comment]
whatevs @NitroBAY

**Comment by NitroBAY** [comment]
Thanks

**Comment by tomscholz** [comment]
@NitroBAY https://github.com/tomscholz/materialize-meteor-test Works for me

**Comment by NitroBAY** [comment]
I'm trying to switch to npm package.
