### ISSUE TITLE
Clicks (javascript events) not being responded with Angular 2

### ISSUE THREAD

**Issue by pragun16** [Dogfalo/materialize#4048]
### Description
I'm using this framework with angular 2. The problem that I'm facing is that the elements aren't responding to the clicks i make in navbar and other collection components such as an accordion. But then if i refresh the page, the entire thing seems to work fine until some time again.

The navbar element is static and the content below navbar is generated dynamically by the router in my case. What might be the issue? Might be some javascript load error.  I read somewhere that materialize css hasn't been able to cope with angular / angular 2 which generates dynamic dom elements.

**Comment by pragun16** [comment]
I managed to load the required js functions manually after onInit() {} in angular 2 but I really have no idea if its the best possible way to solve this issue.

**Comment by developeranirudhprabhu** [comment]
@pragun16 If any component is placed dynamically it would require explicit init as well. For example dropdowns, collapsible etc

**Comment by pragun16** [comment]
@developeranirudhprabhu  thank you.. I managed to do it that way :)

**Comment by developeranirudhprabhu** [comment]
@acburst @Dogfalo I think we can close this issue
