### ISSUE TITLE
Convert JavaScript files to TypeScript files

### ISSUE THREAD

**Issue by TheColorRed** [Dogfalo/materialize#4053]
I think that it would be a good idea to convert all the javascript files into typescript files.

This will allow for better coding practices, and can be compiled down into different source types, meaning that es6 code can run in browsers that only support es3, es4 and/or es5. It also does error checking upon compilation, much like sass meaning less runtime errors.

For example this `es6` code can be compiled into `es3` and/or `es5` code:

```ts
async function doSomething() {
    let content = await makeHttpRequest('http://example.com/do-something');
    console.log(content);
}
```

Most javascript files can already be converted to typescript files without issue since typescript is just a superset of javaScript.

I understand that this can take some time but in the long run I think it would be better for the code base.

**Comment by developeranirudhprabhu** [comment]
@Dogfalo Your comments?

**Comment by Dogfalo** [comment]
I like the thought, however I would rather keep the code base in plain Javascript so that it will remain simple and more accessible to people in the community.
