### ISSUE TITLE
Display table breaks IE responsive

### ISSUE THREAD

**Issue by verysame** [Dogfalo/materialize#4054]
### Description
Hi there,

I'm trying Materialize and I like it very much.
One thing I'm struggling with: with Boostrap, I can easily use display:table and hack the alignment of the table datas' content quite easily.
I can do the same with Materialize, only it doesn't work in IE11. In fact, it seems the page is not responsive anymore after display:table

### Repro Steps
    <div class="container ">
        <div class="row ">
            <div class="l12 ">
                <div style="display:table; width:100%; ">
                    <div style=" display: table-row; ">
                        <div style="display: table-cell; width: 60%; position: relative; ">
                            <img class="responsive-img " src="https://unsplash.it/1280/680 " alt=" " />
                            <div class="Rbottom45 "></div>
                        </div>
                        <div style="display: table-cell; width: 30%; vertical-align:bottom; position: relative; ">
                            <img class="responsive-img " src="https://unsplash.it/280/280 " alt=" " />
                        </div>
                        <div style="display: table-cell; width: 10%; "></div>
                    </div>
                </div>
            </div>
        </div>
    </div>

    .Rbottom45 {
        background-color: white;
        position: absolute;
        bottom: 0;
        width: 45%;
        height: 20%;
        z-index: 2;
    }

### Screenshots / Codepen

![01](https://cloud.githubusercontent.com/assets/22113312/21598972/4e93dde4-d11a-11e6-9c89-24246113546b.jpg)
---
![02](https://cloud.githubusercontent.com/assets/22113312/21598971/4e92c86e-d11a-11e6-867a-3bda83343c45.jpg)

**Comment by verysame** [comment]
Any hints?

**Comment by Dogfalo** [comment]
I tried putting in your code into the codepen, but it didn't really illustrate the problem to me. I'm unsure of what exactly you are trying to do with the layout, but I think you can use some of the grid classes for a cleaner layout.
