### ISSUE TITLE
there is a strange phenomenon on table's td tag with class "left" or "right"

### ISSUE THREAD

**Issue by 275761919** [Dogfalo/materialize#4055]
### Description
The table's td tag with class "left" or "right" cause the that the table cell's width will vary because of different word longth.

### Test source code
There is my test html:
```html
<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en">
<head>
<title>test</title>
<link rel="stylesheet" type="text/css" href="http://cdn.bootcss.com/materialize/0.97.8/css/materialize.css">
</head>
<body>
<table border="2" cellspacing="0" cellpadding="6" rules="groups" frame="hsides">
<colgroup>
<col  class="left" />
<col  class="left" />
<col  class="left" />
</colgroup>
<tbody>
<tr>
<td class="left">abcsdfjkdf</td>
<td class="left">sd</td>
<td class="left">c343</td>
</tr>
<tr>
<td class="left">df</td>
<td class="left">sdkfjslkdf</td>
<td class="left">d</td>
</tr>
</tbody>
</table>
</body>
</html>
```
### Screenshots
with class "letf":
<img width="261" alt="2017-01-03 11 26 28" src="https://cloud.githubusercontent.com/assets/14012127/21599454/90129796-d1a7-11e6-9675-0e160ec97b94.png">

remove class "left":
<img width="1432" alt="2017-01-03 11 28 42" src="https://cloud.githubusercontent.com/assets/14012127/21599474/d3adbed6-d1a7-11e6-86fd-5106e5be4092.png">

How to fixed it?

**Comment by ben-sykes** [comment]
`class="left"` represents the CSS `float: left;`. I don't believe you should ever need to float table cells... This is a problem with your code, not the Materialize library.
