### ISSUE TITLE
query builder icon is the same as the schedule icon

### ISSUE THREAD

**Issue by codypearce** [Dogfalo/materialize#4057]
### Description
The query_builder icon is the same as the schedule_icon, it should be a wrench.This is the same issue as on https://material.io/icons/, however, when you actually use the google material query builder icon it's a wrench and not a clock.

### Repro Steps
Go to http://materializecss.com/icons.html
And ctrl+f query_builder

### Screenshots / Codepen
![mquery](https://cloud.githubusercontent.com/assets/12564956/21602958/a9468a84-d156-11e6-9311-55203712082d.png)
![mschedule](https://cloud.githubusercontent.com/assets/12564956/21602959/ab13145e-d156-11e6-82e9-78492484fef7.png)

What it should look like:
![querywrench](https://cloud.githubusercontent.com/assets/12564956/21603029/546b1fd8-d157-11e6-9714-ac130092b9c7.png)

**Comment by Dogfalo** [comment]
Report this to https://github.com/google/material-design-icons as it is their icon font.
