### ISSUE TITLE
Callback for sidenav

### ISSUE THREAD

**Issue by weedandbleed** [Dogfalo/materialize#4059]
### Description
When opening and closing navbar there is no callback attached to it

**Comment by Dogfalo** [comment]
Do you mean the sidenav?

**Comment by weedandbleed** [comment]
yup

**Comment by leftdead7** [comment]
how can i check if the navbar is open or closed?

In a case, in mobile devices, when a user presses the device back button, i want to check if the sidenav is open before taking an action

**Comment by tomscholz** [comment]
Added in https://github.com/Dogfalo/materialize/commit/8a01666817bd6f6f69b7a5b08b1a3f1d1677f1ee
