### ISSUE TITLE
Icon Button in nav shifts down icon

### ISSUE THREAD

**Issue by retorquere** [Dogfalo/materialize#4061]
When I add a raised button with an icon (http://materializecss.com/buttons.html) in a nav (http://materializecss.com/navbar.html) the icon shifts down; see the button in [this fiddle](http://jsfiddle.net/mgbed790/).

**Comment by tomscholz** [comment]
I created a codepen cause your fiddle dosen't work for https://codepen.io/tomscholz/pen/YNzedG
The problem is that the icon has got the same height as the hamburger icon on mobile.

**Comment by acburst** [comment]
This was fixed in 9fcc379dce10353b425b9c4c8f71484ffba2a6a1.

You can use our master version or wait until we release a new version.

**Comment by retorquere** [comment]
Can I install the master version using bower?

**Comment by retorquere** [comment]
Should loading this stylesheet (from the commit you mentioned above) at the end fix this? It doesn't for me:

```
nav ul a.btn > .material-icons, nav ul a.btn-large > .material-icons, nav ul a.btn-large > .material-icons, nav ul a.btn-flat > .material-icons, nav ul a.btn-floating > .material-icons {
   height: inherit;
   line-height: inherit;
 }
 ```
