### ISSUE TITLE
Release the latest version to atmosphere 

### ISSUE THREAD

**Issue by idanwe** [Dogfalo/materialize#4063]
The v0.97.8 release doesn't include 2 important fixes:
 * [Added _badges.scss](https://github.com/Dogfalo/materialize/commit/b8f3aeeda1d905546c00772af0f33ff39094f951)
 * [Changed fonts path in packages.js
](https://github.com/Dogfalo/materialize/commit/72759961572d2a0e77c3a1e0aea9db646f66765f)

It prevent from me to upgrade to the latest version that include a lot of meaningful fixes and enhancements.

Is it possible to publish new release?

**Comment by acburst** [comment]
We are planning on releasing a new version within the month

**Comment by idanwe** [comment]
Ok, thanks for the update
