### ISSUE TITLE
Carousel slides misplace when are switched fast

### ISSUE THREAD

**Issue by anvart** [Dogfalo/materialize#4064]
### Description
When one sliding is not over yet and another one is initiated by clicking on indicator, slide position messes up.

### Repro
Go to [demo page](http://materializecss.com/carousel.html) and switch between slides: click every time different indicator before the sliding animation is over. Also works with double-clicks.

### Screenshot
![screenshot from 2017-01-04 16 03 00](https://cloud.githubusercontent.com/assets/363397/21646710/8a1ec238-d297-11e6-8704-e230b8c13b0b.png)

### Browsers
Does not work on any.

**Comment by ben-sykes** [comment]
I believe the interaction you're experiencing is related to the touch compatibility. Click slower an be more precise when clicking on the dots. Everything seems to work as expected. If you misclick (between the dots) the touch/sliding functionality seems to mess with things. It almost seems like there should be a "no-drag" block behind the clickable dots.

@anvart : Does this analysis seem to make sense with what you're experiencing?

**Comment by tomscholz** [comment]
![2017-01-04 17 43 01](https://cloud.githubusercontent.com/assets/20381749/21650483/5d3010b6-d2a5-11e6-9ce5-c4f813ecace1.gif)
Can reproduce

**Comment by acburst** [comment]
This is fixed on master from this PR: #3866 

You can either choose to use our latest build which may have other issues or wait for our next release.

**Comment by umervservices** [comment]
untill it's not updated i am using

$('.indicators li').addClass('disabled')
setTimeout(function(){
	$('.indicators li').removeClass('disabled');
},1500)

to disable click on indicators
