### ISSUE TITLE
Materialize Modal Flickers on iOS Chrome, Safari

### ISSUE THREAD

**Issue by PatDuJour** [Dogfalo/materialize#4068]
### Description
I have a materailizecss Modal(register) that causes flickers on Chrome & Safari, tested on iOS mobile devices on iOS 9&10.

The modal flicks when switching among input fields in the form in modal-body.

I don't know if this is the same flicker issue with bootstrap, which came up a lot in my search

**Comment by Dogfalo** [comment]
Can you provide us with a codepen so we can easily test and try to fix the issue?
