### ISSUE TITLE
Document onCycleTo Carousel option

### ISSUE THREAD

**Issue by clxy** [Dogfalo/materialize#4069]
### Description
Dose Carousel has some events, so we can put some callbacks into it.
Like onSlideStart, onSlideEnd, etc.

Maybe add customized 'carouselNext' and 'carouselPrev' ?

**Comment by DavisMiculis** [comment]
Having same question here. Would be nice to have events and callbacks!

**Comment by clxy** [comment]
@DavisMiculis Thank you very much! Because of gesture, I switched to WebView + ViewPager a while ago. But thanks anyway!

**Comment by dmattia** [comment]
I agree on re-opening this issue, such events should be documented on http://materializecss.com/carousel.html as a plugin option

**Comment by acburst** [comment]
Added in 42734619 and will be fleshed out more in the v1 dev branch

**Comment by Mithun1090** [comment]
materialize oncycleto is not working as expected in 1.0.0-beta.
 $('.carousel').carousel({onCycleTo: function(slide){console.log(slide);}}); 
i need it to get triggered when a new slide is cycled to. but its not happening.is there any way around to achieve it??

**Comment by devolution2409** [comment]
There is still no mention of what's inside the data object.
