### ISSUE TITLE
Can't click through a label for a textarea

### ISSUE THREAD

**Issue by AlexandreDecan** [Dogfalo/materialize#407]
I'm currently using Firefox 34.0 and Materialize 0.9. I've a (small) issue about using a label and a textarea. For "traditional" input fields, when you click on the label, the input field has the focus. But this is not the case with textarea's. 

I currently use the following workaround, which obviously will not work if you have a background set for the textarea: 
```
  .materialize-textarea {
    position: relative; /* Allow z-index */
    z-index: 2; /* Allow clicking through the label */
  }
  .input-field .materialize-textarea + label {
    z-index: 1; /* Allow clicking through the label */
  }
```

**Comment by acburst** [comment]
You can use the `for` attribute.

    <label for="textarea1">Textarea 1</label>
    <textarea id="textarea1" class="materialize-textarea"></textarea>

**Comment by AlexandreDecan** [comment]
Consider updating the documentation, as the only example with a textarea does not include a "for" attribute for its label. Thank you!

**Comment by uxitten** [comment]
please see this link
http://stackoverflow.com/a/19522921/3243488

**Comment by JeanPaulBeard** [comment]
This is my solution for bug
`.input-field label {
    pointer-events: all;
}`
