### ISSUE TITLE
Dropdown in <td> doesn't work

### ISSUE THREAD

**Issue by lordplagus02** [Dogfalo/materialize#4070]
I have a `dropdown-button` inside a `<td>` and the `<ul>` element right beneath it. When clicking or hovering on the button, the list does not appear. It seems that the button still gets the class `active` as if it was open but the menu is not visible. 

I am using the example straight from http://materializecss.com/dropdown.html but within a table cell.

**Comment by marc0tjevp** [comment]
Do you fill the table dynamically? If so, it's necessary to initialize the jQuery plugin.

See: http://materializecss.com/dropdown.html

**Comment by lordplagus02** [comment]
Nope, the table is loaded with the page

**Comment by marc0tjevp** [comment]
Could you share your code in a CodePen?

**Comment by retorquere** [comment]
I think I'm seeing the same issue. I'll try to bring my page down to a code-pen-sized chunk, but one thing I do see is that while the `<ul id='dropdown1' class='dropdown-content'>` is part of the page source when I request `View Source`, it's not there when I inspect page, and if I search for it using jquery, they are indeed not found.

**Comment by fega** [comment]
It's very difficult to solve what we cannot reproduce :/

**Comment by tomscholz** [comment]
Like @fega said.
Closed due inactivity. Feel free to reopen it, if it's still necessary.

**Comment by beigiz** [comment]
same issue here :(

**Comment by kixortillan** [comment]
Encountered this. The fix I did is to add a style to the <td> element. The td element container of the dropdown needs to have a position other than static (w/c is the default) because the dropdown <ul> element uses style position: absolute w/c uses the non-static parent container. In my case, I have none so I guess it uses the body tag as parent container.

**Comment by fega** [comment]
@kixortillan could you provide a snipped or make a PR? :)

**Comment by kixortillan** [comment]
@fega here is a fiddle [.](https://jsfiddle.net/8u0j59ay/6/) 

removing the style="position:relative;" in the td element will make the dropdown float at the upper left corner of the table.

**Comment by Pabsz** [comment]
@kixortillan Sadly this does not fix the issue. I've just added the style on my `<td>` and when I have one row it works fine, but when I have multiple rows the menu will render at the last row, on top of the dropdown button. 
![dropdown_issue](https://user-images.githubusercontent.com/5489059/37307717-31f7ae24-2612-11e8-8641-e44257ec0c00.png)

I clicked on the three dots button on the first row, and the menu renders on the second row. The same happens on the fiddle sample you gave. I added a new button to show the same fixed dropdown and it rendered on the last row.

**Comment by pengkong** [comment]
<td style="position: relative;"> works. @Pabsz you have to make sure data-activates and the <ul> id are unique.

**Comment by acburst** [comment]
Dropdown has been rewritten in 1.0.0 beta, it should be more reliable. If issues still arise in the latest version, please open a new issue.

**Comment by Sojer23** [comment]
Same issue using dropdown-trigger. any solution?

**Comment by RadouaneRoufid** [comment]
+1

**Comment by Pabsz** [comment]
Make sure that you have a unique ID for all the dropdown lists. My issue was that I was trying to recycle one <ul> dropdown list for all my rows. Once I made the ID unique for each <ul> in row and that it matches the dropdown-trigger, it worked fine.

**Comment by RadouaneRoufid** [comment]
a workaround : 

```
<td style="position: absolute">
    <a materialize="dropdown" class='dropdown-button'
       data-constrainWidth="false" data-belowOrigin="true"
       [attr.data-activates]="'id">
        <i class="material-icons" title="actions">more_vert</i>
    </a>

    <ul [id]="'id" class='dropdown-content'>
        <li>
            <a >Voir le profil</a>
        </li>

</td>
```

**Comment by jemedina112** [comment]
Entonces no hubo ninguna solución a esto?

**Comment by jshster** [comment]
> Entonces no hubo ninguna solución a esto?

Can you provide a JSFiddle that highlights the issue you are experiencing?   One of the other things that wasn't mentioned above (I think) is the use of the coverTrigger property on the drop down.  If you have coverTrigger set to false it will appear above or below the trigger button (eg. on the second row as described above).     If you can provide a JSFiddle then hopefully we can point you in the right direction.
