### ISSUE TITLE
On Meteor there are no scss, the build systems compiles them in css

### ISSUE THREAD

**Issue by giordanocardillo** [Dogfalo/materialize#4072]
### Description
I installed the package in Meteor, but i see no scss files in it, there is a folder named `sass` in which there are only two files: `materialize.scss.css` and `ghpages-materialize.scss.css`. 

How can I include SCSS inside the meteor package?

### Repro Steps
* Install package `meteor add materialize:materialize`
* Go to meteor package installation directory (e.g. `%LOCALAPPDATA%\.meteor\packages\materialize_materialize\0.97.8\web.browser\packages\materialize_materialize\sass`)
* Verify that there are no `.scss` in the `sass` directory.

**Comment by tomscholz** [comment]
Try this; https://github.com/Dogfalo/materialize/issues/2217#issuecomment-268100489
