### ISSUE TITLE
FAB in Ionic

### ISSUE THREAD

**Issue by obscurede** [Dogfalo/materialize#4076]
### Description
The icons are placed slightly offset from the top as seen in the screenshot. This was built in Ionic v 2.1.8 with Angular 1.5.3. 

On setting margin-top to 5px for the material-icons class, it helps, but not entirely. Will give feedback by tomorrow if I get anything more on this issue.

### Repro Steps
1) Start an Ionic App
2) Include the 
3) Include the layout for the FAB from the website in the file www/index.html

### Screenshots / Codepen
Screenshot: 
![photo_2017-01-07_14-52-36](https://cloud.githubusercontent.com/assets/10953578/21740757/f279dac2-d4e8-11e6-8c8f-60248131ecb5.jpg)

**Comment by fega** [comment]
Hello, I'm trying to get what could be the origin and how to solve it without break the behavior. but nothing comes to my mind

Did you know the origin of the issue? maybe is a problem with the web-view? could you suggest a way to fix it without break the normal behavior?

Thanks!

**Comment by tomscholz** [comment]
Closed due inactivity. Feel free to reopen it, if it's still necessary.
