### ISSUE TITLE
How to add triangle in top of dropdown content

### ISSUE THREAD

**Issue by davodavodavo3** [Dogfalo/materialize#4077]
Its possible to add trangle , and to show it first ,not before dropdown content open Dogfalo?
There is javascript animation on dropdown.js if I'm not mistaken.
// Show dropdown

 ```
 activates.stop(true, true).css('opacity', 0)
      .slideDown({
            queue: false,
            duration: curr_options.inDuration,
            easing: 'easeOutCubic',
            complete: function() {
              $(this).css('height', '');
            }
          })
    .animate( {opacity: 1}, {queue: false, duration: curr_options.inDuration, easing: 'easeOutSine'});
```
No one can't give the solution in stackoverflow.
Example:
https://jsfiddle.net/sj2tm8cd/20/

**Comment by Nohinn** [comment]
Hello @davodavodavo3, I have updated your example:
https://jsfiddle.net/sj2tm8cd/39/

To sum up. Put `display: none` to your `.dropdown-button::before` CSS declaration. Then add this:
`.dropdown-button.active::before {display: inline}`

**Comment by davodavodavo3** [comment]
Hello Nohinn))) I dont want to display none arrow taht is in the button, i wont to show arrow that is in the content menu top))))

**Comment by davodavodavo3** [comment]
Thank you but I have found a solution.
