### ISSUE TITLE
The order of dialog action buttons are flipped

### ISSUE THREAD

**Issue by codypearce** [Dogfalo/materialize#4078]
### Description
Dialog action buttons have a float: right on them which flips their order, which means it shows Agree on the left and Disagree on the right. This goes against material guidelines for [modal actions](https://material.io/guidelines/components/dialogs.html#dialogs-specs), which says that "Dismissive actions are always placed directly to the left of affirmative actions." This issue appears in the materialize documentation as well.

### Repro Steps
Go to http://materializecss.com/modals.html and click on either/both modal.

Or here's a live example http://codepen.io/codypearce/pen/LxVaZP

### Screenshots / Codepen
![material-dialog](https://cloud.githubusercontent.com/assets/12564956/21747212/de1c558a-d51c-11e6-985e-f508a8fb130e.png)

![materialize-modal](https://cloud.githubusercontent.com/assets/12564956/21747220/13aace66-d51d-11e6-9f4b-425457dd15d2.png)

![materialize-modal2](https://cloud.githubusercontent.com/assets/12564956/21747221/15c916da-d51d-11e6-8129-9d20d63735e1.png)

**Comment by DanielRuf** [comment]
Would this be a viable fix? https://codepen.io/anon/pen/wegqJM
