### ISSUE TITLE
how open collapasble on inner input filed fails at html5 validations?

### ISSUE THREAD

**Issue by avinashdvv** [Dogfalo/materialize#4081]
### Description
i have collapsible, in those i have input box with min,max html attribute when input value is fails to validate how to open the collapsible 

![2](https://cloud.githubusercontent.com/assets/11086981/21763212/bb9ee86c-d682-11e6-83ab-d75afb54ee08.png)

**Comment by developeranirudhprabhu** [comment]
@avinashdvv You can create a custom event for opening/closing each collapsible. Then call the specific event on failure of any field. Hope this helps

**Comment by avinashdvv** [comment]
if(!($("ID_OF_INPUT_TAGS")[0].checkValidity())){
      $("li .header").addClass("active");
      $('li .body').css(
        'display','block'
      )
    }else{
      $("li .header").removeClass("active");
      $('li .body').css(
        'display','none'
      )
    }

**Comment by avinashdvv** [comment]
`if(!($("ID_OF_INPUT_TAGS")[0].checkValidity())){
$("li .header").addClass("active");
$('li .body').css(
'display','block'
)
}else{
$("li .header").removeClass("active");
$('li .body').css(
'display','none'
)
}`
