### ISSUE TITLE
Error Badges Collection 

### ISSUE THREAD

**Issue by Anrahh** [Dogfalo/materialize#4083]
Impossible to overwrite badges collection style 
`div.collection { 
    background-color: red; 
}`

**Comment by acburst** [comment]
Are you looking to color the background of the badge? Look at the [docs](http://localhost:8000/badges.html#options). You can add our color classes to the badge directly

**Comment by developeranirudhprabhu** [comment]
@Anrahh Can you give some more details regarding what exactly are you trying to achieve?

**Comment by Anrahh** [comment]
I am developing a page in html. I use a sidebar with a badges, however, I can not override the class '.collection' style.
Code:

` <style>
            .sid-color {
                background-color: rgb(45, 38, 64);
            }
            .collection {
                background-color: transparent;
            }
 </style>
<code>
    <div class="col m2 l2 sidebar hide-on-small-only">
        <div class="sid-color collection transparent">
            < a href="/cliente" class="collection-item">Cliente</a>
            < a href="/fornecedor" class="collection-item">Fornecedor</a>
        </div>
    </div>
</code>`
The above code should change the '.collection' bgColor, but it does not work.
Note: I do not want to use the default colors of materialize. I want to use my own palette

**Comment by Anrahh** [comment]
Sorted out !
I did the following:
.collection .collection-item {}.
Thank you!
