### ISSUE TITLE
Select does not overlap the border of form tag

### ISSUE THREAD

**Issue by JPaulPunzalan** [Dogfalo/materialize#4084]
Hi All!

The select tag in materialize CSS does not seem to overlap the form materialize tag. I have 8 options in the select tag and I cannot see the other options due to the form tag.

Attached is the screenshot of my current progress. Thank you very much!

![onboarding](https://cloud.githubusercontent.com/assets/14859857/21791275/9a30b1f2-d71c-11e6-9362-f162d0c8f4e3.png)

**Comment by Dogfalo** [comment]
If you don't need `overflow: hidden` you can remove that on the form tag

**Comment by Dmitrev** [comment]
example of what @Dogfalo meant
https://jsbin.com/zogoqiyubu/edit?html,output
