### ISSUE TITLE
Slider glitches out when swiping vertically on a touch device

### ISSUE THREAD

**Issue by deanylev** [Dogfalo/materialize#4087]
On a touch device, if you swipe vertically (to scroll) over a slider, it freaks out and the image is pushed almost all the way over (check my screenshot).

Here's a CodePen to demonstrate the issue (please use Chrome Dev Tools to simulate a smartphone or laptop with touch): http://codepen.io/anon/pen/wgMjjx

All you do is swipe vertically over it and the issue will occur.

![image](https://cloud.githubusercontent.com/assets/22049511/21836069/4e75b9d8-d816-11e6-80db-42493b55b2d5.png)

**Comment by acburst** [comment]
Fixed in 71180ca
