### ISSUE TITLE
Add a [color]-border and border-lighten-[x], border-darken-[x]

### ISSUE THREAD

**Issue by AlexandreDecan** [Dogfalo/materialize#409]
We currently have [color] classes (for the background-color), text-[color] classes (for the foreground color) but we are unable to use one of those to customize the color of, for eg., blockquote or sidebar border.

It should probably be a good idea to consider adding a [color]-border and corresponding border-lighten-[x], border-darken-[x].

**Comment by Dogfalo** [comment]
I think this would add too much code for little benefit. text color and background color are most often used. If you want to use the color palette elsewhere, I would consider using Sass which makes this trivial.

**Comment by AlexandreDecan** [comment]
I partially agree, but I think that "too much code" is linked to another issue. Let me explain ;-) 

I think there's some work to do about how the color schemes are managed in MaterializeCSS. For example, I do not understand why all the color schemes must be provided in the CSS. If I follow Material Design's specification, I should choose 2, 3 or maybe 4 distinct colors/variations among the ones that are provided. The other colors are not useful. 

It should be possible to define some "core" colors, like "primary", "primary-text", "success", "success-text", etc. based on "intentions", and only have those colors in our resulting CSS (using Sass, for e.g.). This way, one could change the whole "theme" of its website by editing only a small part of its code. And this way, only some of color schemes need to be included in the outputted css (and you could, for e.g., use "primary-border" to define the "default" color of a blockquote, "success" to define the color of a validated input form, etc. without having to hard code "red" and "green" like it is at the moment). 

At least, I strongly believe that it could be interesting to have seperate materialize.(min.)css and full-color-schemes.(min.)css and give the people the possibility to easily generate their own-color-schemes.(min.)css if they are not satisfied with the colors you chose (for blockquote, sidebar, input field, etc.) by simply manipulating some variables (e.g.: by specifying that the "primary" color scheme is populated by, say, blue darken-2, that "success" color scheme is populated by "green lighten-1", etc.). 

So, to illustrate:
 - Define all the color schemes in a separate file (quite similar as it is right now) ;
 - Move the function that generate the CSS in another place ;
 - Add some "intention" schemes: primary, secondary, success, warning, error, muted, ... 
 - Define some "default" value for those schemes: primary is black, success is green, etc. Write in the documentation how the user can easily change this.
 - When the sass-compiler runs, use the intention schemes to populate the currently-hardcoded colors of Materialize
 - Include in the output classes like primary, success, warning, primary-text, success-text, warning-text, lighten-1, etc. (in fact, those classes are just an alias for the ones we currently have, like red, green, blue, etc.). 
 - Output another css file, say "color-schemes.css" with all the classes we currently have (like red, red-text, .red.lighten-1, etc.).

We then have:
 - Materialize.css which contains all the funny stuff you already wrote + a user-defined color scheme (or a default one) using intentions.
 - color-schemes.css which can be optionaly included by the developers in their websites if they need other colors than the ones that are defined using intentions in materialize.css

I'm not even sure I'm understandable^^

**Comment by mazzie14** [comment]
+1

**Comment by RaSeR** [comment]
Totally agree with @AlexandreDecan

**Comment by tomscholz** [comment]
tl:dr sry
