### ISSUE TITLE
How to get the focus carousel-item in javascript

### ISSUE THREAD

**Issue by MickaelH974** [Dogfalo/materialize#4090]
### Description
Add a detailed description of your issue.

Carousel items don't have active class or id to recognize them, so is there any way to get/select them whith javascript?

**Comment by Nohinn** [comment]
@MickaelH974 You can try and use this until there is something easier to use (if such a function is implemented ever):

`$('.carousel').find('.carousel-item[style*="z-index: 0"]')`

That will return the top most carousel-item (the active one).

**Comment by acburst** [comment]
Added active class to center carousel item in 7e51730

**Comment by MickaelH974** [comment]
Thanks, I've used Z-index and Opacity to get the top carousel-item. 

Happy to see that we have now an Active class, very good job ;-)
