### ISSUE TITLE
Textarea changes repaints the whole screen

### ISSUE THREAD

**Issue by AdamTyler** [Dogfalo/materialize#4091]
When typing inside of a textarea, the whole screen will repaint as opposed to just the textarea repainting.

You can see this in action on the http://materializecss.com/forms.html page.
In your browser dev tools turn on Paint Rendering ([How To on Chrome](https://developers.google.com/web/fundamentals/performance/rendering/simplify-paint-complexity-and-reduce-paint-areas)) and start typing in a regular text input and well as a textarea to see the difference.

### Input Paint:
![input-paint](https://cloud.githubusercontent.com/assets/2525253/21858022/25b14d06-d7ed-11e6-94a3-a7b3f992740c.gif)

### Textarea Paint:
![textarea-paint](https://cloud.githubusercontent.com/assets/2525253/21858010/1dd17ffc-d7ed-11e6-84c4-ae681f321129.gif)

**Comment by acburst** [comment]
Fixed in 6e5122e.

Changed the hiddendiv to position absolute which brings it out of the document flow which reduces the amount needed to repaint.
