### ISSUE TITLE
Footer truncated only on mobile screen 

### ISSUE THREAD

**Issue by danieleorlando** [Dogfalo/materialize#4096]
### Description
The footer is truncated on mobile screen

### Repro Steps
www.purecontactapp.com

### Screenshots / Codepen
![c17ewecxcaex8bt](https://cloud.githubusercontent.com/assets/7324970/21888779/0ad44388-d8c6-11e6-915e-aa87e9ed45b0.jpg)

**Comment by vishnu1991** [comment]
Looks like 
`.footer-copyright{overflow:hidden;...}`
 is truncating the text in footer.
@danieleorlando u can override this line from your materialize css file.

**Comment by danieleorlando** [comment]
Not exactly @vishnu1991 
The problem it's on the height and line-height of `.footer-copyright` that is fixed on 50px.

**Comment by Dogfalo** [comment]
Fixed in a7f4c87
