### ISSUE TITLE
FAB toolbar within a card not possible

### ISSUE THREAD

**Issue by gervik** [Dogfalo/materialize#4099]
Hi everybody,

is there a way to include a FAB toolbar into a card? I've tried to include the code from your site into the div "card-content", but I'm getting a button outside of the card. Do I have to wrap the FAB with a specific div?

Kind regards

**Comment by pixxx** [comment]
This is the standard code you can find in the materialize css
```
.fixed-action-btn {
  position: fixed;
  right: 23px;
  bottom: 23px;
  padding-top: 15px;
  margin-bottom: 0;
  z-index: 998;
}
```
You gonna have to override the code with yours, I got it working with the below code but I'm addressing the Click-only FAB, but I tried it also with the toolbar one and it worked.

```
.fixed-action-btn {
  float: right;
  position: relative;
  left: 0px;
  bottom: 0px;
}
```
Only thing I can't get to work is slide it out to the right or any side, right now it's right and slide out to top or left, and going in there changing it with little knowledge is not easy.

**Comment by gervik** [comment]
Worked for me! Thank you pixxx!

**Comment by HenintsoaAdri** [comment]
should update your materialize.css ! it worked with v0.98! 0.97 is deprecated
