### ISSUE TITLE
fonts from js

### ISSUE THREAD

**Issue by sajera** [Dogfalo/materialize#4100]
### Description
Really need to download fonts using js?

### It cannot be builded correctly
How should look like the building process with the transfer of files? Or add a hash to the file names?

![materialize](https://cloud.githubusercontent.com/assets/8238019/21929790/6d3262fa-d99b-11e6-8e8a-c00a136543a3.png)

**Comment by Dogfalo** [comment]
Fonts are not downloaded using js. Most likely you have your font files misplaced.
