### ISSUE TITLE
How to show a tab on click of a button?

### ISSUE THREAD

**Issue by shmshd12** [Dogfalo/materialize#4103]
Hey,

Im confused here. I need to show 2nd or third tab from first on click of the button inside the first tab. I tried to give # link of second tab  to the href but no change.

Could someone help?

**Comment by Nohinn** [comment]
With no more info the only thing we can recommend to you is to take a look at the documentation:

`$('ul.tabs').tabs('select_tab', 'tab_id');`

[http://materializecss.com/tabs.html#method](http://materializecss.com/tabs.html#method)
