### ISSUE TITLE
Toast position 'jumps' in Portrait mode on medium/large resolutions

### ISSUE THREAD

**Issue by Boournz** [Dogfalo/materialize#4104]
### Description
When displaying a Toast in Portrait mode on a medium to large resolution, the Toast appears on the bottom left of the screen, it then makes a small 'jump' to a new lower position before the timeout dismisses the Toast. This 'jump' in position is not evident in Landsacape mode.

**EDIT**
The issue is also reproducible with the 360x640 resolution in **Landscape** mode

### Repro Steps
The issue can be reproduced on the Materialize website (http://materializecss.com/dialogs.html) using Firefox (latest version 50.1.0). Open the developer tools and invoke the Responsive Design Mode. Set the resolution to 768x1024 (or larger), in Portrait mode. Click the Toast! button to invoke a Toast, watch it 'jump'.

**Comment by Dogfalo** [comment]
Fixed in 1f3377c
