### ISSUE TITLE
Installation woes

### ISSUE THREAD

**Issue by tomsutton** [Dogfalo/materialize#4105]
I'm having issues when installing.
I get the following errors in the console:

`C:\App>meteor add materialize:materialize
 => Errors while adding packages:

While loading package fourseven:scss@3.2.0:
error: Command failed:
C:\Users\Admin\AppData\Local\.meteor\packages\meteor-tool\1.4.2_3\mt-os.windows.x86_32\dev_bundle\bin\npm.cmd
rebuild --update-binary
module.js:327
throw err;
^

Error: Cannot find module 'is-property'
at Function.Module._resolveFilename (module.js:325:15)
at Function.Module._load (module.js:276:25)
at Module.require (module.js:353:17)
at require (internal/module.js:12:17)
at Object.<anonymous>
(C:\Users\Admin\AppData\Local\.meteor\packages\fourseven_scss\3.2.0\plugin.compileScss.os.windows.x86_32\npm\node_modules\meteor\compileScss\compileScss\node_modules\node-sass\node_modules\request\node_modules\har-validator\node_modules\is-my-json-valid\node_modules\generate-object-property\index.js:1:80)
at Module._compile (module.js:409:26)
at Object.Module._extensions..js (module.js:416:10)
at Module.load (module.js:343:32)
at Function.Module._load (module.js:300:12)
at Module.require (module.js:353:17)
at require (internal/module.js:12:17)

npm ERR! Windows_NT 10.0.14393
npm ERR! argv
"C:\\Users\\Admin\\AppData\\Local\\.meteor\\packages\\meteor-tool\\1.4.2_3\\mt-os.windows.x86_32\\dev_bundle\\bin\\node.exe"
"C:\\Users\\Admin\\AppData\\Local\\.meteor\\packages\\meteor-tool\\1.4.2_3\\mt-os.windows.x86_32\\dev_bundle\\lib\\node_modules\\npm\\bin\\npm-cli.js"
"rebuild" "--update-binary"
npm ERR! node v4.6.2
npm ERR! npm  v3.10.9
npm ERR! code ELIFECYCLE
npm ERR! node-sass@3.2.0 install: `node scripts/install.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the node-sass@3.2.0 install script 'node scripts/install.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the node-sass package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node scripts/install.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs node-sass
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls node-sass
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!
C:\Users\Admin\AppData\Local\.meteor\packages\fourseven_scss\3.2.0\plugin.compileScss.os.windows.x86_32\npm\node_modules\meteor\compileScss\compileScss\node_modules\.temp-1ljom5s\npm-debug.log
module.js:327
throw err;
^

Error: Cannot find module 'is-property'
at Function.Module._resolveFilename (module.js:325:15)
at Function.Module._load (module.js:276:25)
at Module.require (module.js:353:17)
at require (internal/module.js:12:17)
at Object.<anonymous>
(C:\Users\Admin\AppData\Local\.meteor\packages\fourseven_scss\3.2.0\plugin.compileScss.os.windows.x86_32\npm\node_modules\meteor\compileScss\compileScss\node_modules\node-sass\node_modules\request\node_modules\har-validator\node_modules\is-my-json-valid\node_modules\generate-object-property\index.js:1:80)
at Module._compile (module.js:409:26)
at Object.Module._extensions..js (module.js:416:10)
at Module.load (module.js:343:32)
at Function.Module._load (module.js:300:12)
at Module.require (module.js:353:17)
at require (internal/module.js:12:17)

npm ERR! Windows_NT 10.0.14393
npm ERR! argv
"C:\\Users\\Admin\\AppData\\Local\\.meteor\\packages\\meteor-tool\\1.4.2_3\\mt-os.windows.x86_32\\dev_bundle\\bin\\node.exe"
"C:\\Users\\Admin\\AppData\\Local\\.meteor\\packages\\meteor-tool\\1.4.2_3\\mt-os.windows.x86_32\\dev_bundle\\lib\\node_modules\\npm\\bin\\npm-cli.js"
"rebuild" "--update-binary"
npm ERR! node v4.6.2
npm ERR! npm  v3.10.9
npm ERR! code ELIFECYCLE
npm ERR! node-sass@3.2.0 install: `node scripts/install.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the node-sass@3.2.0 install script 'node scripts/install.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the node-sass package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node scripts/install.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs node-sass
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls node-sass
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!
C:\Users\Admin\AppData\Local\.meteor\packages\fourseven_scss\3.2.0\plugin.compileScss.os.windows.x86_32\npm\node_modules\meteor\compileScss\compileScss\node_modules\.temp-1ljom5s\npm-debug.log`

I've tried updating meteor and packages to their newest versions, but no luck.

Any help would be appreciated! :)

**Comment by tomscholz** [comment]
Have you tried using an older version of materialize?

**Comment by tomscholz** [comment]
And try this: https://github.com/Dogfalo/materialize/issues/2217#issuecomment-268100489
Maybe it works

**Comment by Dogfalo** [comment]
Please try the newest version v0.98.0

**Comment by Gsuz** [comment]
I'm getting similar error on mac os x with v. 0.98.0

`=> Started proxy.                             
=> Started MongoDB.                           
=> Errors prevented startup:                  
   
   While loading package fourseven:scss@3.2.0:
   error: Command failed:
   /Users/borkur/.meteor/packages/meteor-tool/.1.4.2_3.1rd9djy++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/bin/npm
   rebuild --update-binary
   Cannot download
   "https://github.com/sass/node-sass/releases/download/v3.2.0/darwin-x64-46_binding.node":
   HTTP error 404 Not Found
   gyp ERR! configure error 
   gyp ERR! stack Error: 404 status code downloading tarball
   gyp ERR! stack     at Request.<anonymous>
   (/Users/borkur/.meteor/packages/fourseven_scss/.3.2.0.lqs8zg++os.osx.x86_64+web.browser+web.cordova/plugin.compileScss.os.osx.x86_64/npm/node_modules/meteor/compileScss/compileScss/node_modules/node-sass/node_modules/pangyp/lib/install.js:251:14)
   gyp ERR! stack     at emitOne (events.js:82:20)
   gyp ERR! stack     at Request.emit (events.js:169:7)
   gyp ERR! stack     at Request.onRequestResponse
   (/Users/borkur/.meteor/packages/fourseven_scss/.3.2.0.lqs8zg++os.osx.x86_64+web.browser+web.cordova/plugin.compileScss.os.osx.x86_64/npm/node_modules/meteor/compileScss/compileScss/node_modules/node-sass/node_modules/pangyp/node_modules/request/request.js:1255:10)
   gyp ERR! stack     at emitOne (events.js:77:13)
   gyp ERR! stack     at ClientRequest.emit (events.js:169:7)
   gyp ERR! stack     at HTTPParser.parserOnIncomingClient
   (_http_client.js:433:21)
   gyp ERR! stack     at HTTPParser.parserOnHeadersComplete
   (_http_common.js:103:23)
   gyp ERR! stack     at TLSSocket.socketOnData (_http_client.js:322:20)
   gyp ERR! stack     at emitOne (events.js:77:13)
   gyp ERR! System Darwin 16.3.0
   gyp ERR! command
   "/Users/borkur/.meteor/packages/meteor-tool/.1.4.2_3.1rd9djy++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/bin/node"
   "/Users/borkur/.meteor/packages/fourseven_scss/.3.2.0.lqs8zg++os.osx.x86_64+web.browser+web.cordova/plugin.compileScss.os.osx.x86_64/npm/node_modules/meteor/compileScss/compileScss/node_modules/.temp-18o3c3k/node_modules/node-sass/node_modules/pangyp/bin/node-gyp"
   "rebuild" "--libsass_ext=" "--libsass_cflags=" "--libsass_ldflags="
   "--libsass_library="
   gyp ERR! cwd
   /Users/borkur/.meteor/packages/fourseven_scss/.3.2.0.lqs8zg++os.osx.x86_64+web.browser+web.cordova/plugin.compileScss.os.osx.x86_64/npm/node_modules/meteor/compileScss/compileScss/node_modules/.temp-18o3c3k/node_modules/node-sass
   gyp ERR! node -v v4.6.2
   gyp ERR! pangyp -v v2.2.1
   gyp ERR! not ok 
   Build failed
   
   npm ERR! Darwin 16.3.0
   npm ERR! argv
   "/Users/borkur/.meteor/packages/meteor-tool/.1.4.2_3.1rd9djy++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/bin/node"
   "/Users/borkur/.meteor/packages/meteor-tool/.1.4.2_3.1rd9djy++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/bin/npm"
   "rebuild" "--update-binary"
   npm ERR! node v4.6.2
   npm ERR! npm  v3.10.9
   npm ERR! code ELIFECYCLE
   npm ERR! node-sass@3.2.0 postinstall: `node scripts/build.js`
   npm ERR! Exit status 1
   npm ERR! 
   npm ERR! Failed at the node-sass@3.2.0 postinstall script 'node
   scripts/build.js'.
   npm ERR! Make sure you have the latest version of node.js and npm installed.
   npm ERR! If you do, this is most likely a problem with the node-sass
   package,
   npm ERR! not with npm itself.
   npm ERR! Tell the author that this fails on your system:
   npm ERR!     node scripts/build.js
   npm ERR! You can get information on how to open an issue for this project
   with:
   npm ERR!     npm bugs node-sass
   npm ERR! Or if that isn't available, you can get their info via:
   npm ERR!     npm owner ls node-sass
   npm ERR! There is likely additional logging output above.
   
   npm ERR! Please include the following file with any support request:
   npm ERR!
   /Users/borkur/.meteor/packages/fourseven_scss/.3.2.0.lqs8zg++os.osx.x86_64+web.browser+web.cordova/plugin.compileScss.os.osx.x86_64/npm/node_modules/meteor/compileScss/compileScss/node_modules/.temp-18o3c3k/npm-debug.log
   Cannot download
   "https://github.com/sass/node-sass/releases/download/v3.2.0/darwin-x64-46_binding.node":
   HTTP error 404 Not Found
   gyp ERR! configure error 
   gyp ERR! stack Error: 404 status code downloading tarball
   gyp ERR! stack     at Request.<anonymous>
   (/Users/borkur/.meteor/packages/fourseven_scss/.3.2.0.lqs8zg++os.osx.x86_64+web.browser+web.cordova/plugin.compileScss.os.osx.x86_64/npm/node_modules/meteor/compileScss/compileScss/node_modules/node-sass/node_modules/pangyp/lib/install.js:251:14)
   gyp ERR! stack     at emitOne (events.js:82:20)
   gyp ERR! stack     at Request.emit (events.js:169:7)
   gyp ERR! stack     at Request.onRequestResponse
   (/Users/borkur/.meteor/packages/fourseven_scss/.3.2.0.lqs8zg++os.osx.x86_64+web.browser+web.cordova/plugin.compileScss.os.osx.x86_64/npm/node_modules/meteor/compileScss/compileScss/node_modules/node-sass/node_modules/pangyp/node_modules/request/request.js:1255:10)
   gyp ERR! stack     at emitOne (events.js:77:13)
   gyp ERR! stack     at ClientRequest.emit (events.js:169:7)
   gyp ERR! stack     at HTTPParser.parserOnIncomingClient
   (_http_client.js:433:21)
   gyp ERR! stack     at HTTPParser.parserOnHeadersComplete
   (_http_common.js:103:23)
   gyp ERR! stack     at TLSSocket.socketOnData (_http_client.js:322:20)
   gyp ERR! stack     at emitOne (events.js:77:13)
   gyp ERR! System Darwin 16.3.0
   gyp ERR! command
   "/Users/borkur/.meteor/packages/meteor-tool/.1.4.2_3.1rd9djy++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/bin/node"
   "/Users/borkur/.meteor/packages/fourseven_scss/.3.2.0.lqs8zg++os.osx.x86_64+web.browser+web.cordova/plugin.compileScss.os.osx.x86_64/npm/node_modules/meteor/compileScss/compileScss/node_modules/.temp-18o3c3k/node_modules/node-sass/node_modules/pangyp/bin/node-gyp"
   "rebuild" "--libsass_ext=" "--libsass_cflags=" "--libsass_ldflags="
   "--libsass_library="
   gyp ERR! cwd
   /Users/borkur/.meteor/packages/fourseven_scss/.3.2.0.lqs8zg++os.osx.x86_64+web.browser+web.cordova/plugin.compileScss.os.osx.x86_64/npm/node_modules/meteor/compileScss/compileScss/node_modules/.temp-18o3c3k/node_modules/node-sass
   gyp ERR! node -v v4.6.2
   gyp ERR! pangyp -v v2.2.1
   gyp ERR! not ok 
   Build failed
   
   npm ERR! Darwin 16.3.0
   npm ERR! argv
   "/Users/borkur/.meteor/packages/meteor-tool/.1.4.2_3.1rd9djy++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/bin/node"
   "/Users/borkur/.meteor/packages/meteor-tool/.1.4.2_3.1rd9djy++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/bin/npm"
   "rebuild" "--update-binary"
   npm ERR! node v4.6.2
   npm ERR! npm  v3.10.9
   npm ERR! code ELIFECYCLE
   npm ERR! node-sass@3.2.0 postinstall: `node scripts/build.js`
   npm ERR! Exit status 1
   npm ERR! 
   npm ERR! Failed at the node-sass@3.2.0 postinstall script 'node
   scripts/build.js'.
   npm ERR! Make sure you have the latest version of node.js and npm installed.
   npm ERR! If you do, this is most likely a problem with the node-sass
   package,
   npm ERR! not with npm itself.
   npm ERR! Tell the author that this fails on your system:
   npm ERR!     node scripts/build.js
   npm ERR! You can get information on how to open an issue for this project
   with:
   npm ERR!     npm bugs node-sass
   npm ERR! Or if that isn't available, you can get their info via:
   npm ERR!     npm owner ls node-sass
   npm ERR! There is likely additional logging output above.
   
   npm ERR! Please include the following file with any support request:
   npm ERR!
   /Users/borkur/.meteor/packages/fourseven_scss/.3.2.0.lqs8zg++os.osx.x86_64+web.browser+web.cordova/plugin.compileScss.os.osx.x86_64/npm/node_modules/meteor/compileScss/compileScss/node_modules/.temp-18o3c3k/npm-debug.log`
