### ISSUE TITLE
Allow to programmatically open and close the SideNav

### ISSUE THREAD

**Issue by 255kb** [Dogfalo/materialize#411]
If I am not mistaking, the SideNav cannot be opened or closed programmatically. This could be very useful, for example when we use a framework like Angular or Meteor, when the page is not reloaded after a click on a link.

Current workaround is to use something like `$('#sidenav-overlay').trigger( "click" );`

**Comment by vamsivarikuti** [comment]
Yes, I had this problem. When a user clicks on a link in sidenav view loads in the background but the sidenav still remains over the content.

<b>Expected behavior:</b> Sidenav hides itself after clicking on a link.

**Comment by keyscores** [comment]
It's also not working as expected on the materializecss.com demo http://materializecss.com/templates/starter-template/preview.html#

**Comment by dhyegofernando** [comment]
@255kb I've tested what you said and this looks pretty ok.

Try to open manually the sidenav and let this code do the job for you:

```
    <script>
      $(function() {
        setTimeout(function() {
          $("#sidenav-overlay").trigger("click");
        }, 5000);
      });
    </script>
```

Tested in this [page](http://materializecss.com/side-nav.html#!). Is that it?

**Comment by acburst** [comment]
Added in a409efa5e12d054948a4554171d95ea598380317

```
// Show sideNav
$('.button-collapse').sideNav('show');
// Hide sideNav
$('.button-collapse').sideNav('hide');
```

**Comment by keyscores** [comment]
Can you post this in the documentation somewhere?

**Comment by acburst** [comment]
It is under sideNav.

**Comment by bhalalapj** [comment]
i am facing issue. while i host my website on server,

its working proper in local
$(...).sideNav is not a function.
is there any solution for that?

**Comment by Inventti-Marcel** [comment]
Hello everyone!

Trigger click on show and hide? But if I not want a button to show sidenav? This is my case =P
I want to show a sidenav with javascript (sidenav.show()), but I haven't a button. I open the sidenav based in navigation.

How I proceed?

**Comment by ElpySites** [comment]
I have the same question as the last one. I'm opening sidebar programmatically with some other buttons. In my case, i have some functions on click on main button, so when i open sidenav with other buttons (programmatically), all functions of main button are executed as well.
Any idea how to solve this?

**Comment by StayAt** [comment]
for me it worked like this:
<ul class="section table-of-contents">
		<li class="bold"><a onclick="$('.button-collapse').sideNav('hide');">Installation</a></li>
		<li class="bold"><a onclick="$('.button-collapse').sideNav('hide');" href="#betaghandling">Handling</a></li>
		<li class="bold"><a onclick="$('.button-collapse').sideNav('hide');" href="#betagbitcoin">bitcoins</a></li>
</ul>

**Comment by StayAt** [comment]
<a
onclick="$('.button-collapse').sideNav('hide');"
>bla</a>

**Comment by basiljose1** [comment]
(function($){
      $(function(){
        $('.button-collapse').sideNav({
          closeOnClick: true
        });
      });
    })(jQuery);


pass closeOnClick: true on SideNav initialization ..it will work

**Comment by jdkealy** [comment]
Same question as Inventti-Marcel ... Makes no sense that I need a button to open this .

**Comment by Native-Coder** [comment]
@jdkealy  What I did was make a button and set the display to "hidden". Initialize the button like you normally would via js. Then, use whatever you want to toggle the side-nav. In my case, I'm using the tilde key (~) to toggle the side-nav. Unfortunately, I can't find a way to detect whether it is open yet or not. So I created a global variable to keep the toggle state for me.
