### ISSUE TITLE
Center modal vertically

### ISSUE THREAD

**Issue by dima74** [Dogfalo/materialize#4116]
### Description
Could you please explain, how I can center modal vertically? If I set "ending_top: 50%" it isn't center vertically, it is a little lower.
Screenshot, black rectangle is the area where I want the modal to be:
![image](https://cloud.githubusercontent.com/assets/6505554/22163995/5115460c-df66-11e6-82a3-47577022d11b.png)
And here is where modal be if I set "ending_top: 50%":
![image](https://cloud.githubusercontent.com/assets/6505554/22164080/ae387fe8-df66-11e6-853d-f2abd90adfe5.png)

### Repro Steps
~~Sorry, I don't know, what I have to write here :(~~

### Screenshots / Codepen
http://codepen.io/anon/pen/dNvaQy

(Thank you for materializecss!)

**Comment by Dogfalo** [comment]
You would have to add `transform: translateY(-50%);` to the modal. This shifts it up by half of the modal's height. You may run into some problems of that style being overwritted by JS though. Maybe we will look into making this a bit easier.

**Comment by dima74** [comment]
@Dogfalo, thank you for answer!
I added `style="transform: translateY(-50%) !important;"` to modal div but it didn't work. Also I tried to do this from javascript: `$('#modal2').css('transform', 'translateY(-50%)');`, but this also didn't work. So as you say there is some problem with overwritting by JS. Could you please check that I did (http://codepen.io/anon/pen/WRjRxM) and maybe there is another solution? Thank you!

**Comment by Nohinn** [comment]
@dima74 right now, until there is some sort of option in the modal configuration for it, there are two options:

1) You should put that `$('#modal2').css('transform', 'translateY(-50%)');` into the ready callback of the modal to avoid the css overwrite.

`  $('#modal2').modal({ending_top: '50%', ready: function(modal) {modal.css('transform', 'translateY(-50%)'); }});`

But this option creates a non appealing effect as you will see the modal moving to it's position after being shown.

2) On your css (not on javascript).
`
#modal2 {
  transform: translateY(-50%) scaleX(1) !important;
}
`

**Comment by dima74** [comment]
@Nohinn, thank you a lot!
Your solution works.
Also I noticed, that if I only put `#modal2 { transform: translateY(-50%) !important; }` to css (not inline as I tried before) then It works too (http://codepen.io/anon/pen/PWjwmB).
Thanks again!
