### ISSUE TITLE
Slider does weird stuff when being touched while scrolling

### ISSUE THREAD

**Issue by Supremex** [Dogfalo/materialize#4121]
### Description
When you scroll down, and while you're scrolling touch the slider, the slider pops a bit to the left. I don't know why that happens.

### Repro Steps
Go to my website on a mobile device. www.evidegraphics.com
Keep scrolling down and when you see the slider, place your finger on it and scroll further. (Just like you would normally scroll down a website on the right side of the screen.)

### Screenshots / Codepen
I've send a .gif on Twitter. My username is Supremex11.

**Comment by acburst** [comment]
Fixed in 71180ca. You'll need to download our latest files to have access to the fix though
