### ISSUE TITLE
TextArea AutoResize and HiddenDiv

### ISSUE THREAD

**Issue by vinibiten** [Dogfalo/materialize#4123]
I had a problem with this part of code when there are other hiddenDivs in <body>.
The variable "hiddenDiv" gets my HiddenDiv (first()) and edit it. I didn't see any issue talking about this hiddenDiv.

I'm using the version 0.97.7

Using a hiddenDiv (with some content that will be used later) in body and trigger AutoResize of textarea.

// Textarea Auto Resize
        var hiddenDiv = $('.hiddendiv').first();
        if (!hiddenDiv.length) {
            hiddenDiv = $('<div class="hiddendiv common"></div>');
            $('body').append(hiddenDiv);
        }

**Comment by vinibiten** [comment]
+1

**Comment by fega** [comment]
Could you check if this is still an issue with the last version? And please provide a way to reproduce it. like a [codepen](https://codepen.io/fega/pen/BWeZaG) or  a snippet

**Comment by fega** [comment]
Closed due inactivity, feel free to reopen it if it is still necessary.

**Comment by vinibiten** [comment]
To work autoresize on version 0.98.2, I had to do this:

Comment   IF on this part of code
// Textarea Auto Resize
    var hiddenDiv = $('.hiddendiv').first();
    //if (!hiddenDiv.length) {
      hiddenDiv = $('<div class="hiddendiv common"></div>');
      $('body').append(hiddenDiv);
    //}

And add a new data on input (data_original_height = 0) https://github.com/Dogfalo/materialize/issues/4123
