### ISSUE TITLE
material_select() default text options on initializer

### ISSUE THREAD

**Issue by thalesmiguel** [Dogfalo/materialize#4124]
Hi. I'm wondering if there is a way to change material_select() default behavior directly on the initializer.
As for now, when I call `$("select").material_select()`, the first **`option`** on my **`select`** is always "_Select value_".
I'd like to change this text as I am initializing the select. Something like
`$("select").material_select(function(){
  placeholder: "Filter"
})`

**Comment by Nohinn** [comment]
`<div class="input-field col s12">
    <select>
      <option value="" disabled selected>Choose your option</option>
      <option value="1">Option 1</option>
      <option value="2">Option 2</option>
      <option value="3">Option 3</option>
    </select>
    <label>Materialize Select</label>
  </div>`

Changing the text of the disabled option. That is what material select should show by default after being initialized.
