### ISSUE TITLE
Close dropdown click handler fires every click even after the dropdown closed

### ISSUE THREAD

**Issue by jacobau** [Dogfalo/materialize#4129]
I am creating a script that allows a user to select multiple values from a `material_select()` select box and then trigger some code after the users presses outside the select box.

A close handler was added to the `input.select-dropdown` element and would keep triggering even though the select dropdown had already been closed.

I will update this issue later with a more detailed description/jsfiddle but for now the workaround to this issue is as follows:

Starting Line 630 in forms.js:
```
 $(window).on({
        'click': function () {
            if (options[0].classList.contains('active')) {
                console.log('is open');
                multiple && (optionsHover || $newSelect.trigger('close'))
            } else {
                console.log('is closed');
            }
        }
      });
```

**Comment by fega** [comment]
the multi select is already implemented
