### ISSUE TITLE
File Input is not working when the file is open

### ISSUE THREAD

**Issue by aravindcraj** [Dogfalo/materialize#4132]
`<div class="file-field input-field" style="width: 520px">
                    <div class="btn light-blue darken-2">
                        <span>Excel File</span>
                        <input type="file" width="120" name="file" multiple="multiple" id="fileXLS" accept=".xls,.xlsx">
                    </div>
                    <div class="file-path-wrapper">
                        <input class="file-path validate" type="text">
                    </div>
                </div>`

File is not selected and file-path field is empty when the selected file is open somewhere else.

**Comment by fega** [comment]
Please follow the [contributing guidelines](https://github.com/Dogfalo/materialize/blob/master/CONTRIBUTING.md)
