### ISSUE TITLE
scss to css failed with dart_sass_transformer

### ISSUE THREAD

**Issue by alescdb** [Dogfalo/materialize#4133]
### Description
Building scss with `dart_sass_transformer` (https://pub.dartlang.org/packages/dart_sass_transformer) via `pub build` failed because of the points (.) in the filenames of default.date.sass and default.time.sass.

Renaming files with an underscore (or a dash) resolve this issue.

### Screenshots / Codepen
```
Build error:
Transform Sass on project|web/sass/style.scss threw error: could not resolve import 'Instance of '_SassImport'' (tried [project|web/sass/materialize/components/date_picker/default.date, project|web/sass/materialize/components/date_picker/_default.date])
null
```

**Comment by kmmbvnr** [comment]
This sounds more like issue for `dart_sass_transformer`

**Comment by alescdb** [comment]
It seems to be. 
But it may happen with other scss tools, because the '.date'/'.time' can be mistaken for a file extension.
Also, all other scss files in materialize have a dash or an underscore, it might not cost a lot to rename this two files (it's only a suggestion).
