### ISSUE TITLE
tabs

### ISSUE THREAD

**Issue by Isapour** [Dogfalo/materialize#4135]
hi, i use rtl direction but why this happened?

![untitled](https://cloud.githubusercontent.com/assets/20435437/22301899/dbf5678c-e341-11e6-9adc-d1532ce97f39.jpg)

**Comment by stap123** [comment]
Can you post your html?

**Comment by Isapour** [comment]
`<!doctype html>
<html>
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="https://fonts.googleapis.com/icon?family=Material+Icons">
    <link rel="stylesheet" href="css/materialize.min.css">
    <link rel="stylesheet" href="css/materialize_rtl.css">
    <link rel="stylesheet" href="css/materialize_customize.css">
    <script type="text/javascript" src="https://code.jquery.com/jquery-2.1.1.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/0.97.3/js/materialize.min.js"></script>
    
    <title>Test Project</title>
    
</head>
<body style="background-color: #efebe9" dir="rtl">

<div>
    <div class="row">
        <div class="col s12">
            <ul class="tabs">
                <li class="tab col s3"><a href="#test1">Test 1</a></li>
                <li class="tab col s3"><a href="#test2">Test 2</a></li>
                <li class="tab col s3"><a href="#test3">Test 3</a></li>
                <li class="tab col s3"><a href="#test4">Test 4</a></li>
            </ul>
        </div>
        <div id="test1" class="col s12">Test 1</div>
        <div id="test2" class="col s12">Test 2</div>
        <div id="test3" class="col s12">Test 3</div>
        <div id="test4" class="col s12">Test 4</div>
    </div>
</div>

<script>
  $(document).ready(function(){
    $('ul.tabs').tabs();
  });
</script>
</body>
</html>`

**Comment by Isapour** [comment]
this is my code

![untitled](https://cloud.githubusercontent.com/assets/20435437/22363348/1785a404-e47f-11e6-82e1-02200b912ad2.jpg)

**Comment by tomscholz** [comment]
Can you pls create a codepen?

**Comment by Dogfalo** [comment]
rtl is not supported at this time
