### ISSUE TITLE
Links on Horizontal FAB buttons in mobile devices not working

### ISSUE THREAD

**Issue by giantas** [Dogfalo/materialize#4136]
I am using a click-only horizontal FAB (which functions as hover on pc) which opens up other FABs that point to external links. However, on mobile devices, the links just open up a new tab and that's all without opening up the link. Here is the code:

`<div class="fixed-action-btn horizontal">
            <a class="btn-floating btn-large red">
              <i class="fa fa-share-alt"></i>
            </a>
            <ul>
              <li>
                <a href="https://twitter.com/intent/tweet?text=Have+a+look+at+%23Memoir+%27aksblk-aisldj-oaosdp%27+at+&url=http%3A//127.0.0.1%3A8000/stories/plmb09j/view/aksblk-aisldj-oaosdp/"
                   rel="nofollow noreferrer"
                   target="_blank"
                   title="Share on Twitter"
                   class="btn-floating white">
                  <i class="fa fa-twitter blue-text"></i>
                </a>
              </li>
              <li>
                <a href="https://www.facebook.com/sharer/sharer.php?u=http%3A//127.0.0.1%3A8000/stories/plmb09j/view/aksblk-aisldj-oaosdp/"
                   rel="nofollow noreferrer"
                   target="_blank"
                   title="Share on Facebook"
                   class="btn-floating white">
                  <i class="fa fa-facebook fa-1g indigo-text text-darken-4"></i>
                </a>
              </li>
              <li>
                <a href="https://plus.google.com/share?url=http%3A//127.0.0.1%3A8000/stories/plmb09j/view/aksblk-aisldj-oaosdp/"
                 rel="nofollow noreferrer"
                 target="_blank"
                 title="Share on Google+"
                 class="btn-floating white">
                <i class="fa fa-google-plus red-text"></i>
              </a>
              </li>
            </ul>
          </div>`

**Comment by fega** [comment]
Please provide a way to reproduce it. like a codepen or  a fiddle snippet

Closed due inactivity, feel free to reopen it if it is still necessary.
