### ISSUE TITLE
active  preloader ?

### ISSUE THREAD

**Issue by juniorsatanas** [Dogfalo/materialize#4137]
How do I activate the loader? In a button event?

<div class="fixed-action-btn vertical">
    <div class="prefix" name="teste" id="teste">
        <div class="preloader-wrapper big ">
            <div class="spinner-layer spinner-red-only">
                <div class="circle-clipper left">
                    <div class="circle"></div>
                </div>
                <div class="gap-patch">
                    <div class="circle"></div>
                </div>
                <div class="circle-clipper right">
                    <div class="circle"></div>
                </div>
            </div>
        </div>

 <a class="btn-floating tooltipped green" onclick="teste" />

**Comment by Dogfalo** [comment]
It doesn't need activation, it's animation is done through CSS. Just show it and hide it appropriately in your app.
