### ISSUE TITLE
[Solved] Dropdown "belowOrigin" Option Doesn't Work Unless Text Is Given

### ISSUE THREAD

**Issue by MuhsinunCool** [Dogfalo/materialize#4138]
### Description
Title says it all. The dropdown's "belowOrigin" option doesn't work if there's no text in the entry or the "a" tag. I put a material icon with no text and it shows the icon and such. However, when I open the dropdown, the dropdown is displayed on top of the origin instead of showing up below it.

### Repro Steps
Simply use no text in the dropdown opening's "a" tag and instead just use a google material icon.

### Screenshots / Codepen
Code:
Button:
`
<li><a class="dropdown-button" data-beloworigin="true" data-hover="true" href="#" data-activates="messages"><i class="material-icons right">email</i></a></li>
`

Dropdown Structure:
`
<ul id="messages" class="dropdown-content">
			<li><a href="#">one</a></li>
			<li><a href="#">two</a></li>
			<li class="divider"></li>
			<li><a href="#">three</a></li>
		</ul>
`

Result:
![image](https://cloud.githubusercontent.com/assets/11369216/22313723/0401d546-e32c-11e6-9773-90ff8da9d228.png)

Solution:
Simply remove the "right" class from the dropdown opening button!

**Comment by Dogfalo** [comment]
This is because if you have no text and only an icon that is floated right, the dropdown has no height. The solution is to not float the icon inside or give the button a height.
