### ISSUE TITLE
0.98.0 NPM

### ISSUE THREAD

**Issue by oyed** [Dogfalo/materialize#4139]
### Description
0.98.0 hasn't been published to NPM yet.

**Comment by taorg** [comment]
Yes, please, npm it's become a standard to manage resources. 
Thx

**Comment by Dogfalo** [comment]
It is published now!

**Comment by mihaibogdan10** [comment]
Given the change to camelCase to the plugin options, this should've been a major version upgrade in my opinion. It's a serious breaking change.

**Comment by Dogfalo** [comment]
It is a breaking change, but it isn't changing fundamental about the framework, just renaming some of the option names. I understand the rules set forward by Semantic Versioning, and why you want this to have been a major version upgrade. However, SemVer has it's own problems. If major number revisions are used for every breaking change, then what denotes a fundamental breaking change in the framework as opposed to a minor breaking change such as the one we just released in this version. 

Here are some articles on the subject:
http://www.jongleberry.com/semver-has-failed-us.html
https://gist.github.com/jashkenas/cbd2b088e20279ae2c8e

**Comment by Thanood** [comment]
IMO not a reason to bump the major version since it's pre v1. It's "legal" in semver for pre releases to break things.
