### ISSUE TITLE
Materialize Modal Not Working On Laravel 5.4

### ISSUE THREAD

**Issue by nardsqq** [Dogfalo/materialize#4144]
### Description
I tried using Materializecss as a substitute for Bootstrap. I included the assets needed (stylesheets and scripts) on my app.blade.php file (master blade file) and yielded the content section from another blade file (index.blade.php).

### Screenshots / Codepen
  -app.blade.php
![1](https://cloud.githubusercontent.com/assets/21337635/22362925/7764a3da-e4a1-11e6-8b2a-05c53733f8aa.jpg)
 -index.blade.php
![2](https://cloud.githubusercontent.com/assets/21337635/22362928/802d0aca-e4a1-11e6-9122-707295c1bbfb.jpg)
-Page
![page](https://cloud.githubusercontent.com/assets/21337635/22363013/2295cff4-e4a2-11e6-9b03-f1f753e0c41d.jpg)

**Comment by kmmbvnr** [comment]
duplicate #4008

http://materializecss.com/modals.html 

```
  $(document).ready(function(){
    // the "href" attribute of .modal-trigger must specify the modal ID that wants to be triggered
    $('.modal').modal();
  });
 ```

**Comment by trentramseyer** [comment]
Not an issue with materialize, issue with your code.
