### ISSUE TITLE
textarea, can't write in it

### ISSUE THREAD

**Issue by Kravennagen** [Dogfalo/materialize#4147]
Hello, 
I use materialize, and I put the textarea into my HTML, it is displaying but I can't write ! And I really don't anderstand why.
I put the code:
`<li>
                <div class="collapsible-header"><span class="badge">Etape1</span><i class="material-icons">place</i>First</div>
                <div class="collapsible-body">
                  <div class="row">
                    <form class="col s12">
                      <div class="row">
                        <div class="input-field col s12">
                          <textarea id="textarea1" class="materialize-textarea" data-length="120"></textarea>
                          <label for="textarea1">Textarea</label>
                        </div>
                      </div>
                    </form>
                  </div>
                </div>
              </li>`
If you have any idea why it doesn't works ! 
thank you!

**Comment by Dogfalo** [comment]
Please recreate your bug in the codepen link that was given in the Issue template
