### ISSUE TITLE
place .chips in $(document).ready in order for it to work?

### ISSUE THREAD

**Issue by diegodesouza** [Dogfalo/materialize#4149]
### Description
I'm using trying to use chips feature in my Angular 1.X app, and the `.chip` class works as expected but not the `.chips`, well not until I place it in a `$( document ).ready(function({}` inside my controller, where I'm instantiating the chips. There should be a better way to handle this; and if there is please let me know. 

I'm using the version 0.98.0 materialize.

**Comment by Dogfalo** [comment]
Well you can probably also use the `angular.element(document).ready()` but yes this is required

**Comment by diegodesouza** [comment]
Correct. I normally use `angular.element` rather than `$` in my angular apps. Just though I this i was a bit cumbersome to get it working. Thanks for the prompt response though. @Dogfalo
