### ISSUE TITLE
Swipeable tabs swipe threshold

### ISSUE THREAD

**Issue by mchalakov** [Dogfalo/materialize#4151]
Can you add minimal swipe threshold for the swipeable tabs?
If you have an image slider in one of the tabs, it becomes unusable - it always switches to the next tab. 
An option for the minimal distance required before recognizing would be great.
Or an option to specify on which element the swipe gesture to switch tabs is active.

**Comment by Dogfalo** [comment]
I think instead the image slider should be stopping the propagation of the event. Are you using the carousel in materialize?

**Comment by mchalakov** [comment]
I'm using royalslider and another plugin for pinch to zoom a map(image) .
Very basic example of my structure:
```
<div id="tab1">
  <div class="slider"></div>
   <div id="news"></div>
</div>
<div id="tab2">
  ...
</div>
<div id="tab3">
  ....
</div>
<div id="tab4">
  <div class="pinchtozoom-map"></div>
</div>
```
If I could set swipe tab threshold to a certain value so it won't be triggered from the slider.Or if it could be triggered only on <div id="news"></div> .I think it would be useful either way cause now it's too sensitive.

**Comment by Dogfalo** [comment]
Try attaching a touch handler to `.slider` and prevent propagation.

**Comment by fega** [comment]
@mchalakov did you solve your problem?

Closed due inactivity, feel free to reopen it if it is still necessary.
