### ISSUE TITLE
Click Events

### ISSUE THREAD

**Issue by milonas115** [Dogfalo/materialize#4152]
I know this issue has been repeated over and over, but I just want to throw it out there again since I am staring at a mobile first framework with zero regard to mobile JavaScript.

**Click Events**

On iPhone/iPad Safari, half of your click handlers are NEVER called because the browser will not trigger them on non-link elements. Instead of doing proper mobile event handling (combining touchstart/end w/ click), you are only using **.click** or **.on('click'**. This makes one of your most important components totally worthless to half of the internet's users, your material select.  Yes I understand I can just set the class to force it as a default element, but that is a totally unacceptable answer, If it were an issue for Opera , nobody would blink an eye. But you are completely neglecting the most popular device in the US.

Are there ANY plans of having this actually designed properly?

**Comment by Dogfalo** [comment]
Yes we'll get these fixed for the next release. Which other components were not working for you besides material select?

**Comment by milonas115** [comment]
Decided to throw this together as in what this component SHOULD be doing (also following Google's Material Spec a tad bit closer)....

[https://jsfiddle.net/c6buv1j8/5/](https://jsfiddle.net/c6buv1j8/5/)

**Comment by milonas115** [comment]
@Dogfalo Also, wanted to make a comment that you guys have the velocity plugin built into your code base but I still see .animate() being used.

**Comment by acburst** [comment]
Fixed in 1d94110
