### ISSUE TITLE
button waves-effect is limited to certain colors

### ISSUE THREAD

**Issue by JCarran0** [Dogfalo/materialize#4154]
### Description
It looks like the flat button wave effect is limited to red, yellow, orange, purple, green and teal.
I'm using the deep-orange theme in my app and can't make use of flat button waves effect.

If there is not a reason these colors were limited, I'm happy to make a PR.

### Repro Steps
See Codepen

Use this Codepen to demonstrate your issue. http://codepen.io/JCarran0/pen/ygPmVv

**Comment by Thanood** [comment]
Waves built-in colors are limited. The documentation shows how to add new waves colors:
http://materializecss.com/waves.html#customization

deep-orange sample:
http://codepen.io/anon/pen/LxOwop

**Comment by JCarran0** [comment]
Got it, thanks!
