### ISSUE TITLE
when a button with wave-effect was clicked several times, the button become white

### ISSUE THREAD

**Issue by lx1054331851** [Dogfalo/materialize#4155]
# when a button with wave-effect was clicked several times, the button become white, check the html, i foud the some codes were added, i really don't know why?
## the button before clicked:
![image](https://cloud.githubusercontent.com/assets/12423206/22410322/a4b2ebbc-e6d1-11e6-998a-efa7fa81f32e.png)
## the button after clicked several times:
![image](https://cloud.githubusercontent.com/assets/12423206/22410334/c63ace62-e6d1-11e6-9351-887cf4885cbe.png)
## the button code before clicked: 
`<a class="waves-effect waves-light btn">Stuff</a>`
## the button code after clicked several times:
`<a class="waves-effect waves-light btn">Stuff<div class="waves-ripple " data-hold="1485741320758" data-scale="scale(10)" data-x="41.84375" data-y="1.71875" style="top:1.71875px;left:41.84375px;-webkit-transform:scale(10);-moz-transform:scale(10);-ms-transform:scale(10);-o-transform:scale(10);transform:scale(10);opacity:1;-webkit-transition-duration:750ms;-moz-transition-duration:750ms;-o-transition-duration:750ms;transition-duration:750ms;-webkit-transition-timing-function:cubic-bezier(0.250, 0.460, 0.450, 0.940);-moz-transition-timing-function:cubic-bezier(0.250, 0.460, 0.450, 0.940);-o-transition-timing-function:cubic-bezier(0.250, 0.460, 0.450, 0.940);transition-timing-function:cubic-bezier(0.250, 0.460, 0.450, 0.940);"></div><div class="waves-ripple " data-hold="1485741321124" data-scale="scale(10)" data-x="41.84375" data-y="0.71875" style="top:0.71875px;left:41.84375px;-webkit-transform:scale(10);-moz-transform:scale(10);-ms-transform:scale(10);-o-transform:scale(10);transform:scale(10);opacity:1;-webkit-transition-duration:750ms;-moz-transition-duration:750ms;-o-transition-duration:750ms;transition-duration:750ms;-webkit-transition-timing-function:cubic-bezier(0.250, 0.460, 0.450, 0.940);-moz-transition-timing-function:cubic-bezier(0.250, 0.460, 0.450, 0.940);-o-transition-timing-function:cubic-bezier(0.250, 0.460, 0.450, 0.940);transition-timing-function:cubic-bezier(0.250, 0.460, 0.450, 0.940);"></div><div class="waves-ripple " data-hold="1485741321483" data-scale="scale(10)" data-x="41.84375" data-y="0.71875" style="top:0.71875px;left:41.84375px;-webkit-transform:scale(10);-moz-transform:scale(10);-ms-transform:scale(10);-o-transform:scale(10);transform:scale(10);opacity:1;-webkit-transition-duration:750ms;-moz-transition-duration:750ms;-o-transition-duration:750ms;transition-duration:750ms;-webkit-transition-timing-function:cubic-bezier(0.250, 0.460, 0.450, 0.940);-moz-transition-timing-function:cubic-bezier(0.250, 0.460, 0.450, 0.940);-o-transition-timing-function:cubic-bezier(0.250, 0.460, 0.450, 0.940);transition-timing-function:cubic-bezier(0.250, 0.460, 0.450, 0.940);"></div></a>`

**Comment by smileytechguy** [comment]
What browser?  Doesnt happen for me on latest Safari, Chrome, or Firefox Developer Edition.

I am using the first button on [this](http://materializecss.com/buttons.html) page

**Comment by lx1054331851** [comment]
sorry, i found the problem
i import **materialize.min.js** and **materialize.js** in the same html file, so the situation happened!

**Comment by alexgilbertDG** [comment]
The same issue happen to me when I'm using my website inside an android webview! So I had to modify the show function inside the Waves Effect object (line: ~1754), I had to manually called a setTimeout to delete the ripple element after the effect was showed.
