### ISSUE TITLE
Preloader in modal causes to scrollbar appearing

### ISSUE THREAD

**Issue by dima74** [Dogfalo/materialize#4160]
Hello! Thank you for materializecss!

### Description
I create modal with circular preloader inside. Every few seconds scrollbar appears for a short time. In Chrome 56 scrollbar appears approximately every five seconds, in Firefox 51 scrollbar appears approximately every twenty seconds. (Both on Arch Linux)

### Repro Steps
http://codepen.io/anon/pen/egyyML

### Screenshots / Codepen
Video: https://youtu.be/RupAK9mYO94

**Comment by dima74** [comment]
Excuse me, is something wrong with my issue? You commit nothing to it. Thanks for materializecss, thanks if reply!

**Comment by dima74** [comment]
@kmmbvnr, please tell me, what is wrong with this issue?

**Comment by tomscholz** [comment]
Do Something like this? https://codepen.io/anon/pen/LWJRjr

**Comment by tomscholz** [comment]
Please close

**Comment by dima74** [comment]
@tomscholz, thank you a lot!
