### ISSUE TITLE
Select element closes on scrolling or click-holding

### ISSUE THREAD

**Issue by fysp11** [Dogfalo/materialize#4161]
I'm using materialize 0.98.0 and when I try to scroll my Select list, the element closes.

This is happening on chrome mobile only.

**Comment by fysp11** [comment]
I downgraded to 0.97.8 and the scrolling didn't close the select. So, that's a problem with the 0.98.0 version.

**Comment by vinibiten** [comment]
Hi, i don't believe that the problem occour just in new version.
I have the same problems with the 0.97.7 on Chrome mobile
Sorry if 0.97.8 fixed this.

**Comment by jrioromero** [comment]
That's right. Same issue here with 0.98.0 and Chrome mobile. The Select list closes when scrolling or click-holding.

The issue can be reproduced in http://materializecss.com/forms.html

**Comment by olivertylsar** [comment]
@jrioromero Facing this problem as well, now. 😆 Any tips how to get it work on mobile?

**Comment by fysp11** [comment]
@ollivertylsar yes. Use the 0.97.8 version.

**Comment by acburst** [comment]
Fixed in 1d94110
