### ISSUE TITLE
Bug with Bottom Sheet Modals y select

### ISSUE THREAD

**Issue by arg3ni5** [Dogfalo/materialize#4165]
Dont shot all item of the select
Should show more elements in the yellow area
![123](https://cloud.githubusercontent.com/assets/12776890/22484194/df3aee2a-e7c5-11e6-9b75-cd871204032d.PNG)
but the modal cut the items

**Comment by arg3ni5** [comment]
and normal modal 
![456](https://cloud.githubusercontent.com/assets/12776890/22484514/5eaa800c-e7c7-11e6-9729-987479440670.PNG)

**Comment by arg3ni5** [comment]
http://codepen.io/arg3ni5/pen/ygpZLx codepen

**Comment by Dogfalo** [comment]
Just add `overflow-y: visible` to the modal div if you want it to stick out of the modal

**Comment by arg3ni5** [comment]
and Bottom Sheet Modals??
