### ISSUE TITLE
modal('open')/modal('close') passing options and complete callback

### ISSUE THREAD

**Issue by vinibiten** [Dogfalo/materialize#4166]
I tried to pass the options with the method open.
Is it available yet?

I used to pass callback complete on modalClose to trigger some function, because the complete in openModal didn't trigger

$("#div-modal").modal('open',{
            dismissible: false
        });

**Comment by Nohinn** [comment]
No, you should do it this way:

```
$("#div-modal").modal({
    dismissible: false
});
$("#div-modal").modal("open");
```

**Comment by vinibiten** [comment]
Thanks!
