### ISSUE TITLE
The label for type="time" input-field won't get the class="active" when changed

### ISSUE THREAD

**Issue by Lopierdis** [Dogfalo/materialize#4168]
### Description
Createing a input-field with a label that's inside the input when un-touched, when editing the input-field the label should go active and pop above the field, when the type of the input-field is time the label won't pop up

### Repro Steps
http://codepen.io/anon/pen/PWRPgL

### Screenshots / Codepen
http://codepen.io/anon/pen/PWRPgL

**Comment by mbabker** [comment]
Stumbled across this today with the date input type.  At a quick glance, it seems like support is missing for all date/time input types.

**Comment by Dogfalo** [comment]
Fixed via 5676
