### ISSUE TITLE
Pushpin wrapping when header or footer scroll into view

### ISSUE THREAD

**Issue by wbarry55** [Dogfalo/materialize#4169]
The pushpin box wraps long strings when the header or footer are in view, but once you scroll into the center of the page, the pushpin gets "wider" and the text stops wrapping. This behavior can be seen on the Materialize website, on the Icons page.

My expectation is that the width would remain constant, either wrapping or not wrapping, but not changing as one scrolls. My own site has longer titles in our pushpin, so the behavior is much more noticeable.

### Repro Steps
Go to http://materializecss.com/icons.html
Scroll and watch the pushpin text "Search Google's Icons".
At the top and bottom of the page, the text will wrap.
Once the header scrolls out of view, the wrapping changes.
![pushpin1](https://cloud.githubusercontent.com/assets/25486554/22516755/d33d3948-e874-11e6-8ade-7c987e81b9c7.gif)
![pushpin2](https://cloud.githubusercontent.com/assets/25486554/22516756/d340d968-e874-11e6-8534-474ddc5f5c01.gif)

I have seen this behavior in MSIE and Chrome.

**Comment by Dogfalo** [comment]
We're simply adding a `position: fixed` to the element when it is pinned. The changes in width maybe be caused by the padding of its parent.

**Comment by Edd-G** [comment]
Confirmed.
See problem in action whit pushpin plugin:
https://jsfiddle.net/EddG/ve06586j/12/
How to resolve problem with pinned block?
If has class "pinned" break width.
