### ISSUE TITLE
Unable to scroll after closing a drawer

### ISSUE THREAD

**Issue by mitas1** [Dogfalo/materialize#4172]
When a drawer is opened and I try to scroll page content with my finger, the drawer closes and I am unable to scroll the page. Expected behaviour is to be able to scroll the page content after the drawer is closed by the touch event.

**Comment by developeranirudhprabhu** [comment]
@mitas1 Can you provide a codepen for above issue?

**Comment by mitas1** [comment]
I think it is not necessary. Just open http://materializecss.com/ on a mobile device and try to scroll the page content when a drawer is opened. I have had this issue with Android 7.1.1(NEXUS 5X) and Android 5.0.1 (Samsung) using Chrome 55.0.2883.91.

**Comment by leftdead7** [comment]
I have the same issue ,the sidenav-overlay is not hiding properly after touch is released, also the final opacity of the sidenav-overlay depends on the location where the touch ends, maybe touchend function requires some changes

**Comment by tomscholz** [comment]
Like this?  #4082

**Comment by leftdead7** [comment]
no, not after opeing, when u close the side nav by draggin, the overlay still remains, which does not allows the user to scroll

**Comment by tomscholz** [comment]
Come on guys! Then this is a duplicate! Search the issues for overlay remains or something like that. 
Duplicate: #3872
