### ISSUE TITLE
Tooltips Don't Work on Progress Bars

### ISSUE THREAD

**Issue by LunarGem** [Dogfalo/materialize#4173]
Hi! I'm working on a JavaScript game using your framework, and I thought using a tooltip to show the numerical value of a progress bar would be a good way to let the user know. Maybe it's just my ineptitude but I can't seem to get it to work. The same code works on a button (though without all of the bootstrap I'm using to facilitate changing the value of the progress bars). I'm using the latest version of Chrome.

 Codepen:  http://codepen.io/anon/pen/wgmYLy

If this isn't a feature you were looking to implement, that's fine, I'll find another way!

**Comment by Dogfalo** [comment]
It doesn't work because you added `width: 0%` on the progress bar.

**Comment by LunarGem** [comment]
Oh, I didn't think of that! Makes sense that that would be it. Thank you!
