### ISSUE TITLE
Doesn't work with wepack

### ISSUE THREAD

**Issue by Genuifx** [Dogfalo/materialize#4177]
### Description
when I use wepack to load materialize.js, it just show many error, likes: 
Uncaught TypeError: $overlay.velocity is not a function
    at openModal (materialize.js:962)

Uncaught ReferenceError: lStack is not defined
    at openModal (materialize.js:929)

and so on.

i have no idea to fix many of them, anyone can help me ?

### Repro Steps
main.js:
require(['jquery'], function($){
    require('./asset/materialize')
    $(document).ready(function(){
        $('.modal').modal()
    })
})

them, use webpack to package it and load in a html page.

**Comment by Dogfalo** [comment]
Duplicate of #1422
