### ISSUE TITLE
Very weird bug, card img size changed by 

### ISSUE THREAD

**Issue by Denly** [Dogfalo/materialize#4178]
### Description
This bug makes card's image size changes. The bug's trigger is a <a> tag without text in <nav> bar. Sorry I spent almost 2hr to find this bug and think about why it happens in my app, but I'm still not sure the root cause. 

p.s I didn't try to reproduce it in CodePen. I'm not 100% sure it's caused materialize

### Repro Steps
If I do 
`<li><a onClick={this.logout} className="grey-text"><i className="material-icons right">power_settings_new</i></a></li>`
It broken like this
![screen shot 2017-02-03 at 8 25 52 pm](https://cloud.githubusercontent.com/assets/7588279/22591564/2799b4a8-ea50-11e6-9a4d-eb317247be31.png)

If I put a 'x' in side <a>
`<li><a onClick={this.logout} className="grey-text"><i className="material-icons right">power_settings_new</i>x</a></li>`
It fixed. 

![screen shot 2017-02-03 at 8 25 10 pm](https://cloud.githubusercontent.com/assets/7588279/22591530/0da74858-ea50-11e6-8deb-9eca3bc4e6e0.png)

**Comment by fega** [comment]
Please provide a way to reproduce it. like a [codepen](https://codepen.io/fega/pen/BWeZaG) or  a snippet 
that very important for this kind of issues.
