### ISSUE TITLE
How do I create this table of contents component?

### ISSUE THREAD

**Issue by keyscores** [Dogfalo/materialize#418]
In your docs there's a nice table of contents component, but I don't see how to create it.
See image
![screenshot 2015-01-07 18 35 54](https://cloud.githubusercontent.com/assets/1364012/5655444/3926ab68-969c-11e4-8b54-9ef225b05172.png)

**Comment by acburst** [comment]
This is currently just for our documentation. We are planning on releasing this as an official component in the future.

**Comment by AlexandreDecan** [comment]
I hope the "border effect" will be the same as in the "tabs" component :-)

**Comment by acburst** [comment]
added in decfd0f37a4153fa3b91f058d87928c347c1783d. 

This will not be pushed live until the next release, so let me know if you have trouble using it.
