### ISSUE TITLE
Popout Collapsible unecissarily resizes after opening (Intermittent?)

### ISSUE THREAD

**Issue by Native-Coder** [Dogfalo/materialize#4180]
### Description
The first item of a Popout Collapsible does a jerky "resizing" thing after opening. I thought it was something I did on my project that caused the issue, but it is present [here](http://materializecss.com/collapsible.html) as well

### Repro Steps
Create a "Popout" collapsible. The first item "jerks" to a smaller size after the opening animation is finished. all other items behave as expected.

The issue is present on materializecss.com as well. [Here's](http://materializecss.com/collapsible.html) a link

I am using Chrome 55.0.2883.87 (Official Build) m (32-bit)

### NOTE
This issue is NOT present in chrome 56.0.2924.87 (Official Build) (64-bit) running on Linux Mint Cinnamon 16.04

I'm not sure if the issue is just with 32 bit Chrome, with Chrome version 55.0.2883.87, or with Materialize its-self. I'll install 64 bit chrome as well as the latest 32 bit chrome Monday morning and report back. (The issue arose on my work machine)

**Comment by Native-Coder** [comment]
I am still experiencing this issue even on the newest version of X64 Chrome. The Popout collapsible at http://materializecss.com/collapsible.html does it as well so I don't believe this issue is on my end.

Here's another example that I'm trying to use, but can't due to this issue.

http://codepen.io/anon/pen/VppBBV?editors=1100

**Comment by acburst** [comment]
You are misusing our grid system. When using columns you must ensure they are always directly wrapped by a row. 

https://codepen.io/anon/pen/BdaejO
