### ISSUE TITLE
Changing font size messes up data-error positioning for validated form fields

### ISSUE THREAD

**Issue by Native-Coder** [Dogfalo/materialize#4181]
### Description
If you override the font size for your project, it can mess up the spacing for the data-error attribute on validated form fields.

### Repro Steps

Override the font settings with a larger font size

### Codepen
Here's a [codepen](http://codepen.io/anon/pen/GrdBNv) showing the issue

### Possible Solution

I found that changing line 5994 in materialize.css to "top: 5em" fixes the issue, and works well with any font size. I'll make a PR with this change later tonight

**Comment by Native-Coder** [comment]
OK, I've never made a PR before. This is getting to be quite aggravating....

**Comment by Dogfalo** [comment]
Fixed in f8d896536dfae0a047c008bdcdb9d6d92bf6ad3a
