### ISSUE TITLE
input-field label loses left alignment when form is child-element of <center> tag

### ISSUE THREAD

**Issue by orion-pax** [Dogfalo/materialize#4182]
### Description
Placing an HTML form with input-field label within an HTML `<center>` or a `<div>` with equivalent CSS (margin: 3px auto 3px auto;) results in the label text being aligned at the center in materialize version 0.98.0. However using materialize 0.97.5 the text-alignment is left aligned perfectly.

### Repro Steps
To reproduce this issue visit this Codepen: http://codepen.io/T-P/pen/bpWqrr 
1) Change the materialize CSS reference  to   `<link rel="stylesheet" ref="https://cdnjs.cloudflare.com/ajax/libs/materialize/0.97.5/css/materialize.min.css">` and view the resulting output
2) Now use replace the reference with  `<link rel="stylesheet" type="text/css" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/0.98.0/css/materialize.min.css">
 `
![0 97 5](https://cloud.githubusercontent.com/assets/19870545/22615885/7627e4de-eaa8-11e6-9a2e-c8a293bd1cd5.png)
![0 98 0](https://cloud.githubusercontent.com/assets/19870545/22615888/985718ae-eaa8-11e6-8df3-5f6a6236b1f4.png)

**Comment by tomscholz** [comment]
@DanielRuf do you have a quick fix for this?

**Comment by DanielRuf** [comment]
@tomscholz currently looking into it

**Comment by DanielRuf** [comment]
The issue comes from the change that the label for fields with `.validate` have now a width of 100%.

Not sure about the fix.

https://github.com/Dogfalo/materialize/pull/4469

An alternative fix
```CSS
input.validate+label {
    text-align: initial;
}
```

**Comment by Dogfalo** [comment]
Fixed by 4df1e100dd1301cdba5b7b38046d739f52b2becc
