### ISSUE TITLE
[Feature Request] Customize only the tags parts of Materialize

### ISSUE THREAD

**Issue by gusbemacbe** [Dogfalo/materialize#4186]
We would like to customize and select only some parts of Materialize, for example, we want to use only cards tags and customize tags names (for example, renaming` .card-title `to `.materialize-card-title`) and unselect all the unwanted codes and tags, to download the file. It is like Bootstrap Customize (http://getbootstrap.com/customize/). 

It would be easy, light and quick and there would not be conflicts with other styles that have similar codes. 

A bad or good idea? Is it possible? 

We need urgently Materialize cards for news cards page.

**Comment by Dogfalo** [comment]
Right now we don't have plans in the near future to create a custom build downloader on the website. If you only need card styling, why not just take a look at the `_card.scss` and take the styles from there?

**Comment by gusbemacbe** [comment]
@Dogfalo , I am not expert in SCSS, but I converted SCSS to CSS, using SassMaster and it gave some error ("Undefined variable: "$card-padding"").

**Comment by Dogfalo** [comment]
look at `_variables.scss` also and you should be able to resolve the missing variables
