### ISSUE TITLE
0.97.8 and 0.98 break mobile side-nav, 0.96 works fine

### ISSUE THREAD

**Issue by jpwynn** [Dogfalo/materialize#4187]
For my Rails 5 app, the nav layout below (in HAML) works fine with 0.97.6 of the materialize (downloaded manually and added to assets folders), specifically the **mobile side-nav** works fine that is displayed when you click the hamburger icon when you make the browser window narrow.

However the exact same code displays a broken mobile side-nav when I upgraded the js and scss to 0.97.8 or 0.98. Downgrading the back to 0.97.6 made it work again.

Was there a breaking change to how side navs get rendered after 0.97.6? (Looking at the nav section of the current materializecss.com website I don't see a difference.)

Symptoms: side nav slides from the left as expected, but the side-nav background is gray (not white) and all of the links on the sidenav seem disabled... no highlighting on hover, nothing happens when click the link. (If I had to guess, it looks like the overlay that 'dims' the rest of the page when the mobile side-nav slides in is actually 'on top' of the side-nav too, dimming it and preventing hover and click events. Interestingly, the side-nav is fine if you add the 'fixed' class, though of course it's always-on in that case. Point being, there seems to be something related to the overlay that dims the rest of the page that's wonky.)

I went back and forth between versions a couple of times with zero other changes to the code case, it is definitely the  0.97.8 or 0.98 that breaks it.

**That said, if you do _not_ make the menu fixed, eg, if you remove %div.navbar-fixed THEN the mobile side-nav works for both 0.98 and 0.97.6.**

Behaves the same whether using Chrome and Safari under Mac OSX Sierra

    %body
        %header

          %div.navbar-fixed

            %nav
              %div.container.city_bg  # adds a bg image to top nav bar
                %div.nav-wrapper

                  %div.brand-logo
                    // Replace this with an image
                    = image_tag "jlogo1b.png", style: "height: 60px;"

                  %a{href: "#", class: "button-collapse", data: {activates: "mobile_side_menu"}}
                    %i.material-icons menu

                  // Normal NavBar that goes across the top
                  %ul#nav-mobile.right.hide-on-med-and-down

                    %li
                      =link_to "Link 1"
                    %li
                      = link_to "Link 2"
                    %li
                      = link_to "Link 3"

                    // Drop Down Menu
                    %li
                      %a{href: "#", class: "dropdown-button", data: {activates: "myDropdown"}}
                        = "Drop Down Menu"
                        %i.material-icons.right 
                          arrow_drop_down
                      %ul{id: "myDropdown", class: "dropdown-content"}
                        %li
                          = link_to "Drop Down Link 1"
                        %li
                          = link_to "Drop Down Link 2"
                        %li
                          = link_to "Drop Down Link 3"

                  // Mobile Sidebar
                  %ul#mobile_side_menu.side-nav

                    %li
                      = link_to "Link 1b"
                    %li
                      = link_to "Link 2b"
                    %li
                      = link_to "Link 3b"

                    // Drow Down Menu on the mobile sidebar
                    %li
                      %a{href: "#", class: "dropdown-button", data: {activates: "myDropDownSide"}}
                        = "Admin Menu"
                        %i.material-icons.right.fix-line-height
                          arrow_drop_down

                      %ul{id: "myDropDownSide", class: "dropdown-content dropdown-content-sidebar-fix"}
                        %li
                          = link_to "Drop Down Link 1b"
                        %li
                          = link_to "Drop Down Link 2b"
                        %li
                          = link_to "Drop Down Link 3b"

**Comment by jpwynn** [comment]
![jambocity](https://cloud.githubusercontent.com/assets/446451/22625010/a5bb4726-eb3f-11e6-90d1-b5ec557be7b2.png)

**Comment by jpwynn** [comment]
After discovering the interaction with %div.navbar-fixed while writing this up, I then found that the mobile side-nav will work correctly if you move the %ul#mobile_side_menu.side-nav outside of the %div.navbar-fixed, so it is no longer a sister node of the top nav %ul#nav-mobile.right.hide-on-med-and-down

**Comment by MacGyer** [comment]
see #4046 

Same for a Yii2 extension implementing Materialize

**Comment by tomscholz** [comment]
Duplicate https://github.com/Dogfalo/materialize/issues/3844

**Comment by jpwynn** [comment]
Thanks, Tom, yep it's a duplicate, sorry, I did search first but did not see the other ticket.

**Comment by tomscholz** [comment]
These issues are all duplicates:
https://github.com/Dogfalo/materialize/issues/1664
https://github.com/Dogfalo/materialize/issues/3918
https://github.com/Dogfalo/materialize/issues/4046
https://github.com/Dogfalo/materialize/issues/4231
https://github.com/Dogfalo/materialize/issues/437
https://github.com/Dogfalo/materialize/issues/4318
https://github.com/Dogfalo/materialize/issues/3982
https://github.com/Dogfalo/materialize/issues/2879
https://github.com/Dogfalo/materialize/issues/4187

For the future discussion, please use this issue instead.
https://github.com/Dogfalo/materialize/issues/3844
