### ISSUE TITLE
Tabs and Menu-Collapse-Mobile Is bugged

### ISSUE THREAD

**Issue by thiagosaadofficial** [Dogfalo/materialize#4189]
### Description

> 1) My "Menu-Collapse-Mobile" appears when it is as mobile, but clicking on the "burger" nothing happens.
> 
> 2) I inserted the Tabs when the page was blank and it worked perfectly, so I put the color as "transparent" the tab bugou and it does not open the contents anymore.

### Code
My code is in github
> Site: https://thiagosaadofficial.github.io/testing/
Code: https://github.com/thiagosaadofficial/testing

**Comment by tomscholz** [comment]
Have a look here, but everything on your page works for. To improve your sidenav you could initialize your sidenav with the closeOnClick option
```javascript
$('.button-collapse').sideNav({
      closeOnClick: true, // Closes side-nav on <a> clicks, useful for Angular/Meteor
   }
);
```
- http://materializecss.com/side-nav.html
