### ISSUE TITLE
Attaching change event to Select element!

### ISSUE THREAD

**Issue by ajrehman** [Dogfalo/materialize#419]
Unless I use the "browser default" class on the SELECT element, there is no way to attach a Jquery "Change" event to the materialized select element. Since the dropdown creates its own little span and it's a UL list of options rather than actual SELECT element options, it doesn't work, any idea how to accomplish that? Does the selector have those capabilities?

**Comment by Dogfalo** [comment]
Just use onchange on the original element

**Comment by ajrehman** [comment]
Yes I tried that as well but it didn't work. If I were to write a console.log statement upon the original select element after changing it:

console.log($("#select-name").val());

It will always return the new set value in the SELECT element, which is perfect and exactly what should happen. But what does not happen is that binding a "change" or "click" event to this same selector won't fire up, rendering the materialized select statement not optimal for situations like that.

**Comment by ajrehman** [comment]
It does work, thank you! My confusion was that, I was attaching a jquery change event to it which usually works for default SELECT elements but not for this one, for example:

$("#select-element").on("change", function(e) { .. });

Did not work, but instead if I added the "onchange" event like you mentioned:

<select onchange="..."></select>

Then it worked. I wondery why?

But thanks either way!

**Comment by Dogfalo** [comment]
See #369 which should allow both to work now.
