### ISSUE TITLE
Google Chrome DatePicker value not shown

### ISSUE THREAD

**Issue by LuigiPeace** [Dogfalo/materialize#4192]
### Description
I'm using Materialize for a project since few months now. I'm facing an issue regarding DatePicker. I'm not having a problem with the modal of the DatePicker it self. I have an issue with the input. I define a value to my `<input type="date" class="datepicker" value="05/03/2017">` which should be shown under my label.
I just encounter this problem today on Google Chrome (maybe an update of the browser ?). Otherwise on Edge and Firefox the value is shown on the input and the label is shown on top of it as expected.
I'm using the version 0.97.7 of Materialize, but the example below use the latest version 0.98.0.

### Repro Steps
Here a CodePen to test under Google Chrome to face the issue : http://codepen.io/Rayshader/pen/bgjNaZ

**Comment by vinibiten** [comment]
Here the same, but i change the type="date" to type="text". I don't know why use type="date"

**Comment by LuigiPeace** [comment]
Oh really strange, I've tested with type="text" instead of type="date" but it didn't fix it. And now it works. My bad.

**Comment by vinibiten** [comment]
I change the format of date too
2017-06-03 work's fine with type="date" (i believe that the chrome are testing the format)
