### ISSUE TITLE
It is unclear what data-field is used for in tables

### ISSUE THREAD

**Issue by mitar** [Dogfalo/materialize#4195]
Looking at documentation, tables use `data-field` attribute on `th` element, but it is unclear what is that used for? I have not found any reference to it in documentation.

**Comment by Dogfalo** [comment]
It doesn't do anything, thanks for bringing this to our attention, we'll be removing it

**Comment by Dogfalo** [comment]
Removed in 189722c9cac812f5e9b3b05299298e8d4e90d7c5. This change won't go on the live site immediately since it isn't critical, but it will make it's way there for the next release.
