### ISSUE TITLE
Modal href trigger won't work

### ISSUE THREAD

**Issue by thebiltheory** [Dogfalo/materialize#4196]
### Description
After using the right markup, initializing the modal as on the documentation seems the modal won't get fired using 

```html
<a class="waves-effect waves-light btn" href="#modal1">Modal</a>
```
I have tried upgrading Materialize and jQuery but the only thing that happend is that I got the # anchor working to go back to the top of the page

However it was working using:
```html
 <button data-target="modal1" class="btn">Modal</button>
```

Tho I didn't wanted to use a ```<button>``` I just added the data-target to my ```<a>``` tag

```html
<a class="modal-trigger waves-effect waves-light btn" data-target="modal1">modal</a>
```

I thought sharing the "issue". Maybe I missed a step.

Cheers.

**Comment by Dogfalo** [comment]
Initialize it: http://materializecss.com/modals#initialization

**Comment by thebiltheory** [comment]
@Dogfalo have you read my comment? 

``` After using the right markup, initializing the modal as on the documentation```

I am just pointing an issue that I had.

**Comment by Dogfalo** [comment]
http://codepen.io/Dogfalo/pen/MJqKNa
