### ISSUE TITLE
Search function on Materializecss.com does not work in Firefox

### ISSUE THREAD

**Issue by evertalbers** [Dogfalo/materialize#4197]
### Description
Nothing happens when I hit enter or click on the icon

I hope this is the right place to post this.

**Comment by kmmbvnr** [comment]
That's not actually a real search, that's "autocomplete" for page names.

So, it's not specific to the Firefox, and it's supposed to work such (not very convenient) way.

**Comment by evertalbers** [comment]
Ok then I'll close this. Is a bit confusing though.
