### ISSUE TITLE
Broken Navbar in Website

### ISSUE THREAD

**Issue by Shivang-Bhandari** [Dogfalo/materialize#4199]
@acburst 
### Description
Navbar breaks on devtools responsive check at a res of 1024px width

### Screenshots 
<img width="1280" alt="screen shot 2017-02-07 at 10 50 47 pm" src="https://cloud.githubusercontent.com/assets/16368588/22702928/53e3d2d8-ed88-11e6-8c38-5b15680696f8.png">

**Comment by tomscholz** [comment]
What behavior did you expect?

**Comment by Shivang-Bhandari** [comment]
The Brand logo (Logo) and a Menu item (Sass) are overlapping. Shouldn't it be adjusting the spacing according to the menu items?
