### ISSUE TITLE
Before Modal Close Hook

### ISSUE THREAD

**Issue by j1016h** [Dogfalo/materialize#4201]
Hi,
I just want to know if there is a "Before Modal Close Hook" in modals please?

**Comment by Dogfalo** [comment]
There is not, all the options are enumerated on the documentation

**Comment by j1016h** [comment]
Would be great if we can have this feature.

**Comment by j1016h** [comment]
I have implemented this feature and created a pull request for this enhancement. 
https://github.com/Dogfalo/materialize/pull/4249
