### ISSUE TITLE
Make scrollFire resettable [bug] [meteor]

### ISSUE THREAD

**Issue by NitroBAY** [Dogfalo/materialize#4202]
Hello,
### Description
Calling `scrollfire` again does not reinit the scrollfire function. A normal app doesn't need to recall scrollfire but with Meteor when you click on a link another template is created and the old one is destroyed.
Example I have a homepage template and a login one. The user scrolls and animations are working great (scrollfire triggers `showStaggeredList`). The user clicks on a link that leads to the login page from the homepage. He comes back to the homepage right after that but the problem is that even tough `scrollfire` is called again `scrollFire` doesn't triggers any animation anymore so half of the homepage is invisible.

### Pull request
For a possible implementation (I tested it)  :
 See #4206

**Comment by acburst** [comment]
ScrollFire is going to be removed in v1 due to lack of complexity and out of project scope. There are plenty of libraries that are more specialized to achieve the same thing but much more robustly.
