### ISSUE TITLE
The Date picker dont close on set

### ISSUE THREAD

**Issue by arg3ni5** [Dogfalo/materialize#4204]
### Description
The Date picker dont close on set date
 i use this option and dont work:
             `closeOnSelect: true`
codepen issue: http://codepen.io/arg3ni5/pen/vgzwOR

To fix this i use this code:
```
          onSet: function () {
            $('.picker__close').click();
          },
```
codepen fix: http://codepen.io/arg3ni5/pen/bgxydZ

**Comment by tomscholz** [comment]
Duplicate
- https://github.com/Dogfalo/materialize/issues/870
- https://github.com/Dogfalo/materialize/issues/324
- https://github.com/Dogfalo/materialize/issues/1331

**Comment by fega** [comment]
it can be closed?

**Comment by tomscholz** [comment]
https://github.com/Dogfalo/materialize/pull/4003

**Comment by tomscholz** [comment]
Added in https://github.com/Dogfalo/materialize/commit/b17ad0b2876739d4c18f38ba3051e8cc6cb89e8f
