### ISSUE TITLE
Datepicker inside a  'swipeable' tab keeps truncated inside container

### ISSUE THREAD

**Issue by alphadx** [Dogfalo/materialize#4209]
### Description
When i put a form input class datepicker inside a 'swipeable' tab, only the div goes darker and the calendar shows truncated.

### Screenshots / Codepen
USING $('#tabs-swipe-demo').tabs({ 'swipeable': true });
http://codepen.io/AlphaDx/pen/wgYdaQ

If i quite the swipeable control plugin, the problem vanish... but without swipe effect (http://codepen.io/AlphaDx/pen/BpqRgB).

**Comment by Dogfalo** [comment]
Please look through closed issues. #3968
