### ISSUE TITLE
Guidance Required

### ISSUE THREAD

**Issue by sabreking** [Dogfalo/materialize#421]
I am sorry for asking this here but i have a question.
I have been trying really hard but i cant figure our how on materializecss.com you made the main body of the webpage adjust according to the fixed sidenav. My fixed sidenav always overlaps the content, I would appreciate if you could point me in the right direction

**Comment by 255kb** [comment]
If you look at the CSS you will see that they added a left padding of 240px (default width of the sidenav) but only for big screen, while on small screens the Sidenav will be hidden. 
So you could use the following CSS assuming that your main content is in a `<main>` tag: 
    main{
        padding-left: 240px;
    }
    @media only screen and (max-width: 992px) {
        main,{
            padding-left: 0;
        }
    }

**Comment by sabreking** [comment]
Thank you so much :)

**Comment by sabreking** [comment]
It worked thanks :)

**Comment by Dogfalo** [comment]
For future reference @sabreking you can try asking in our chat room: https://gitter.im/Dogfalo/materialize
