### ISSUE TITLE
Don't include the Velocity library? Incompatible with velocity-react?

### ISSUE THREAD

**Issue by smeijer** [Dogfalo/materialize#4211]
This package seems to be incompatible with https://github.com/twitter-fabric/velocity-react, If I see it correctly; it's because materialize includes Velocity as well.

Is there anything we can do to make these two libraries work together?

Currently I'm receiving the error (on a simple `slideDown` animation):

> Uncaught (in promise) Error: Velocity: First argument (finishAll) was not a property map, a known action, or a registered redirect. Aborting.

**Comment by fega** [comment]
Did you solve this issue?

**Comment by smeijer** [comment]
Only by making sure that the correct velocity version is imported before materialize. Effectively ending up with multiple versions of velocity in my bundle. 

Materialize should not embed external libraries, but rather include them via npm. That's where npm is for, isn't it?

**Comment by Thanood** [comment]
> not embed external libraries, but rather include them via npm

You wouldn't believe how awesome that would be for me.. 😃 
You could still offer a bundled version over a CDN.

**Comment by fega** [comment]
@smeijer @Thanood I agree, 

I believe that it will be done with the module loader support feature, that was already approved @Dogfalo @acburst is this correct?

Due it was solved, closed
thanks @smeijer
