### ISSUE TITLE
Update velocity, 1.2.2 > 1.2.3 || 1.4.2

### ISSUE THREAD

**Issue by smeijer** [Dogfalo/materialize#4212]
Although 1.4.2 would be better, even the 1.2.3 release has a useful new method, called `finishAll`.

According to https://github.com/Dogfalo/materialize/pull/2252 , 1.2.3 should already be there, but I guess it has been rolled back some day.

**Comment by smeijer** [comment]
Refering to this line:

https://github.com/julianshapiro/velocity/blob/1.2.3/velocity.js#L2077

**Comment by tomscholz** [comment]
Pull requests are always welcome

**Comment by Dogfalo** [comment]
Updated to 1.4.2 in v1-dev
