### ISSUE TITLE
modal not opening on component initialization

### ISSUE THREAD

**Issue by crizzy9** [Dogfalo/materialize#4214]
/* COMPONENT */
import { Modal } from './../../common-components/modal/modal.model';
import { Buttons } from './playground.model';
import { Component, OnInit } from '@angular/core';
import template from "./playground.component.html";
import style from "./playground.component.scss";

declare var jQuery: any;
@Component({
    selector: 'app-playground',
    template,
    styles: [style]
})

export class PlaygroundComponent implements OnInit {
    vm = new Modal({
        id: 'vid-modal',
        customColor: '#F00',
        showHeader: true,
        showClose: true,
        dismissible: false
    });
    buttons = Buttons;
    constructor() {}
    ngOnInit() {
    }
    ngAfterViewInit() {
        this.vm.actions.emit({ action: 'modal', params: ['open']});
    }
    modalReady() {
        this.vm.actions.emit({ action: 'modal', params: ['open']});
    }
    openModal() {
        this.vm.actions.emit({ action: 'modal', params: ['open']});
    }

}

/* HTML */
<vc-button [button]="buttons.save_btn" (click)="openModal()"></vc-button>

<vc-modal [modal]="vm" (modalReady)="modalReady()">
    <vc-modal-body>
        WHAT IS GOING ON?
    </vc-modal-body>
</vc-modal>

I am trying to open a modal as soon as the page gets initialized using ngAfterViewInit.
I am also using an emitter inside the modal component which tells me when the modal has been initalized.
Even after all this i am unable to open the modal on initalization.
It only works on button click.

**Comment by crizzy9** [comment]
I think the problem lies with actions since it is a subject and not a replay subject it is getting initialized later and not allowing the modal to open.

**Comment by fega** [comment]
Please provide a way to reproduce it. like a [codepen](https://codepen.io/fega/pen/BWeZaG)
Closed due inactivity, feel free to reopen it if it is still necessary.
