### ISSUE TITLE
CSS error in Chips + Autocomplete multiline

### ISSUE THREAD

**Issue by arkkanoid** [Dogfalo/materialize#4216]
### Description
When you insert two lines of chips in Autocomplete input field, the horizontal black/green line is not well aligned.
It works fine using only Chips
### Repro Steps
You can try in the Materialize website:

### Screenshots / Codepen
<img width="565" alt="captura de pantalla 2017-02-10 a les 13 21 54" src="https://cloud.githubusercontent.com/assets/3811604/22826856/e996a874-ef94-11e6-95d3-2a666b40a06a.png">

**Comment by acburst** [comment]
Thanks for pointing this out!

Fixed in bc40172.
