### ISSUE TITLE
Cannot Pop Modal before Ajax call

### ISSUE THREAD

**Issue by nution101** [Dogfalo/materialize#4220]
### Description
If you try to open (show) a modal prior to an ajax call, it waits until the completion of the ajax call to fire the modal. Tried a bunch of different ways of doing it. Even adding a short "wait" function before firing the ajax, but no dice. 

### Codepen  
[Codepen  Example](http://codepen.io/nution/pen/jyQKBJ)  click the "do stuff" button in the top left corner.

**Comment by fega** [comment]
I cannot understand your codepen, for me it works well

**Comment by nution101** [comment]
Click the "do stuff" button. It works the first time, for some reason, but after that, it will not pop up the modal before hitting the js alert. Once the js alert shows, the modal never shows up.

**Comment by fega** [comment]
@nution101 I testing and playing with it, it appears that is a problem with the alert that is blocking the animation, so it couldn't end

it looks clear when you wrap the ajax call in a settimeout function 
http://codepen.io/fega/pen/wJZXxQ

I tested it on chrome.

**Comment by acburst** [comment]
You can use the callbacks provided here: http://materializecss.com/modals.html

Put the ajax under the complete function to ensure your modal opens fully first.
