### ISSUE TITLE
Weird looking time input

### ISSUE THREAD

**Issue by Croghs** [Dogfalo/materialize#4222]
### Description
The input field for times looks weird... The Buttons are way too high on the right side... Could you please fix this?

### Repro Steps
Just add type="time" to a input field.

http://codepen.io/croghs/pen/pRqozJ

### Screenshots / Codepen
![image](https://cloud.githubusercontent.com/assets/20151737/22857252/f5520272-f0a1-11e6-9615-22595d9c048c.png)

**Comment by Lopierdis** [comment]
Happens to me too, It does look good on mobile through.. there is another problem with this, the lable for such input won't go "dirty", check #4168

**Comment by Dogfalo** [comment]
Time input is now supported wth the time picker component
