### ISSUE TITLE
Collections Links, using elements inside by cols goes collapsed

### ISSUE THREAD

**Issue by alphadx** [Dogfalo/materialize#4223]
### Description
I tried to make a kind of row table lineable item, but i'm having problems with css. All rows shows collapsed.

### My Fix
If i force the **height** of **li.collection-header** shows better, but is not a standar solution.

### Screenshots / Codepen
http://codepen.io/AlphaDx/pen/MJZwpM

**Comment by acburst** [comment]
http://codepen.io/acburst/pen/JEwdOR

When using Rows and Cols, make sure that whenever you use a Row, it is IMMEDIATELY followed by a Col. You should never have any structure that looks like Row -> Row, or Col -> Col. If you want a nested grid, your structure needs to look like Row -> Col -> Row -> Col.

Hope that clears things up
