### ISSUE TITLE
Chip added to .card-action causes links to not to be vertically centered

### ISSUE THREAD

**Issue by ahmetb** [Dogfalo/materialize#4225]
### Description

When I add a chip (as span or div) to the `.card-action`, the link I have (`a.right`) is not vertically centered. See screenshot below

### Repro Steps

https://codepen.io/anon/pen/bgOeEP

### Screenshots / Codepen

> (See **"READ MORE &rarr;"** in both examples.)

![image](https://cloud.githubusercontent.com/assets/159209/22860793/1548c8f2-f0bd-11e6-85fb-1c977d46b70c.png)

**Comment by acburst** [comment]
You can add line-height to your `.card-action` to vertically center the text.
