### ISSUE TITLE
Drag-and-drop reordering of Chips (feature request)

### ISSUE THREAD

**Issue by mikewagz** [Dogfalo/materialize#4226]
### Description

An excellent feature would be the ability to make chips draggable to reorder.

### Repro Steps

Currently chips must be deleted and re-added to attain a desired order:

http://materializecss.com/chips.html

**Comment by Dogfalo** [comment]
Why do you need to drag and drop reorder them? Chips's don't need to be reordered.

**Comment by mikewagz** [comment]
For my use case the order is important.  I have a business app that professional inspectors use to describe deficiencies in building construction.  The chips UI seems like the best UI in the Materialize framework for assembling a list of words that are used for a sentence-builder.  The users are asking for the ability to put their most-used words at the top of the list.

Currently their only option is to delete everything and re-enter the words in the order they desire.  Every time they want to add a new word they have to do this again.  Obviously this is a poor user experience.

Would you consider re-opening this feature request to see if it gets voted up?  Out of the many uses for chips, I can't imagine I'm the only one that desires re-ordering.

Thanks for building an awesome framework!
