### ISSUE TITLE
Autocomplete, autoselect first element if exist part of a match 

### ISSUE THREAD

**Issue by alphadx** [Dogfalo/materialize#4228]
### Description
When a write part of a word and then press enter, auto select first item. But if i want build a search box with memory, it's usual to write part of other old searches.

### Repro Steps
If write "a", then shows "Apple".  But I might want to look up the word "a", so i press <enter key> and auto select Apple.

It is any attribute to disable this?

I was looking here in github and main page, but i can't see it.

### Screenshots / Codepen
http://codepen.io/AlphaDx/pen/xgmXgw (Main example)

**Comment by acburst** [comment]
Fixed in d8cce0d
