### ISSUE TITLE
Separate file for Material Design Icons

### ISSUE THREAD

**Issue by AlexandreDecan** [Dogfalo/materialize#423]
I think you should provide a separate file containing all the Material Design Icons (MDI) instead of merging them with the main materialize.min.css file. This way, one can easily use their own icon sets or providing their own MDI set. Btw, this also reduces the size of the main file. 

Combined with issue  #409, we could have:
 - materialize.css --> main CSS components, responsive utilities, etc. and a default color scheme using intentions. 
 - md_colors.css --> currently available color schemes that can be used to extend the default color scheme if needed. 
 - md_icons.css --> MDI set.

**Comment by tankerkiller125** [comment]
I can fully agree with this statement. The Main CSS is way to big and should not be as large as it is.

**Comment by dhawken** [comment]
+1.  I have found using other frameworks that also use MDI do not work with the embedded icons in the materialize css.

**Comment by tankerkiller125** [comment]
I might also want to add that if a user doesn't use the icons in the first place it would save bandwidth on the clients side to simply not load them at all...

**Comment by acburst** [comment]
We have included the newly released icons from google. So we will phase out the dependency in a couple of releases
