### ISSUE TITLE
Autocomplete and similar words 

### ISSUE THREAD

**Issue by arkkanoid** [Dogfalo/materialize#4230]
### Description
In an input field with names that one includes other (i.e. Google and Googles), if I write the whole name I want (Google), and press ENTER, the value selected is 'Googles'.

### Repro Steps
You can set 'Google' and 'Googles':
  $('.chips-autocomplete').material_chip({
    autocompleteData: {
      'Apple': null,
      'Microsoft': null,
      'Google': null,
      'Googles': null
    }
  });

Write in the input field 'Google' and press ENTER

**Comment by alphadx** [comment]
I'm agree, if we have an exact match of an element (word), it dissapear from list
so, pushing <enter>, the first element was selected [ISUE #4228](https://github.com/Dogfalo/materialize/issues/4228)
http://codepen.io/AlphaDx/pen/VPgLPK

**Comment by acburst** [comment]
Fixed in d8cce0d
