### ISSUE TITLE
Using fixed navbar causes issue in mobile view

### ISSUE THREAD

**Issue by ptmaroct** [Dogfalo/materialize#4231]
### Description
To make the navbar fixed, you have to add an outer wrapping div with the class navbar-fixed. This will offset your other content while making your nav fixed.
This works fine for desktop browsers but when mobile view is working on small screen devices and navbar becomes a sidebar, opening the sidebar causes a blackout of whole screen.
TLDR; navbar-fixed isn't compatible with mobile view.
### Repro Steps
I just wrapped the navbar from example given in docs, with a .navbar-fixed div
Here is a pen to demonstrate the issue.
http://codepen.io/ptmaroct/pen/vgvoqG

**Comment by tomscholz** [comment]
Duplicate: https://github.com/Dogfalo/materialize/issues/3844

**Comment by tomscholz** [comment]
These issues are all duplicates:
https://github.com/Dogfalo/materialize/issues/1664
https://github.com/Dogfalo/materialize/issues/3918
https://github.com/Dogfalo/materialize/issues/4046
https://github.com/Dogfalo/materialize/issues/4231
https://github.com/Dogfalo/materialize/issues/437
https://github.com/Dogfalo/materialize/issues/4318
https://github.com/Dogfalo/materialize/issues/3982
https://github.com/Dogfalo/materialize/issues/2879
https://github.com/Dogfalo/materialize/issues/4187

For the future discussion, please use this issue instead.
https://github.com/Dogfalo/materialize/issues/3844
