### ISSUE TITLE
webpack velocity issue when importing materializecss

### ISSUE THREAD

**Issue by persocon** [Dogfalo/materialize#4232]
I'm having this issue: `Uncaught TypeError: k.velocity is not a function at c`
![img](http://i.imgur.com/SVbfUki.png)

but only when I import via js, if I do insert the materializecss+jquery via CDN it works, like this:

```
<script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/jquery/2.2.4/jquery.min.js"></script>
<script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/materialize/0.98.0/js/materialize.min.js"></script>

```

on my index.js I'm importing materializecss this way:
```
import 'materialize-css/bin/materialize';
```

I'm using webpack to bake everything together.

**Comment by iv-mexx** [comment]
Yeah, I'm having the same issue.
I've searched and found some issues here, talking about adding an alias to Webpack ( #2690, #2681 ) but somehow I cant get this to work.

**Comment by tomscholz** [comment]
Closed due inactivity. Feel free to reopen it, if it's still necessary.
