### ISSUE TITLE
[Question] Is Transitions able to work with link collections

### ISSUE THREAD

**Issue by hudson6666** [Dogfalo/materialize#4233]
As the title,

Could *[Transitions](http://materializecss.com/transitions.html)* work with a collection using *div* and *a*?

Like this one,

``` HTML
<div class="collection">
        <a href="#!" class="collection-item">Alvin</a>
        <a href="#!" class="collection-item active">Alvin</a>
        <a href="#!" class="collection-item">Alvin</a>
        <a href="#!" class="collection-item">Alvin</a>
 </div>
```

Or if there is someway to retain both of the effects.

**Comment by alphadx** [comment]
You can try this:
http://codepen.io/AlphaDx/pen/NdoXPG
and it doesn't broke Materialize beauty

**Comment by fega** [comment]
@hudson6666 did you solve your issue?

**Comment by hudson6666** [comment]
Yes, it works! 
Sorry for the late response, I was a little busy these days.
It's brilliant! Very appreciate!
