### ISSUE TITLE
Tab menu not working inside a card panel

### ISSUE THREAD

**Issue by kamikazechaser** [Dogfalo/materialize#4236]
### Description
Attempting to include a tabbed menu inside a card panel. It just doesn't work, not sure if I have gotten my nesting wrong. Included a demo below.

### Repro Steps
Here is the code: https://jsfiddle.net/6zvkdfuj/

**Comment by champa720** [comment]
You need to include jquery in your external resources: https://code.jquery.com/jquery-2.2.4.min.js

https://jsfiddle.net/6zvkdfuj/14/

**Comment by kamikazechaser** [comment]
@champa720 aah simple mistake, thanks!
