### ISSUE TITLE
[Feature Request] Adding fixed languages selection dropdown and hamburger icon in the desktop

### ISSUE THREAD

**Issue by gusbemacbe** [Dogfalo/materialize#4237]
### Description
As I am a hyperglot translator, not just being a web designer, I need to have a fixed language selector dropdown to the right, in the navbar, both in the desktop and mobile. 

I also need to need to keep the same fixed hamburger icon at the left instead of menus, in the navbar, both in the desktop and mobile because I have many menus (items `li`). 

I do not know if it is possible to do it only with Materialize. 

### Examples
![materialize examples](https://cloud.githubusercontent.com/assets/2257024/22944790/018b93a8-f2d9-11e6-9be3-14102c25fe41.png)

**Comment by tomscholz** [comment]
There you go budy: https://codepen.io/tomscholz/pen/XpOvGP

**Comment by tomscholz** [comment]
And I guess you meant to not have any menu items inside your navbar and you want to have them instead inside the sidebar 🤔

**Comment by gusbemacbe** [comment]
Yes, because I have more than 10 menu items and 2 menus has 8 submenu items. The navbar can't afford this.

Your test is a bit buggy (if you add the link to the language, it will give large space and you can't open the link)

But I ask these new **official** features to the future release of Materialize.

**Comment by tomscholz** [comment]
I don't think that this is going to happen this is to application specific. A language picker isn't specified in the material design specifications or in other words If you want such a feature than build it yourself :)

**Comment by gusbemacbe** [comment]
Nor the feature request of hamburger icon in the desktop? If people want to build multilingual websites and websites with many menus,, using Materialize and miss these features?

**Comment by tomscholz** [comment]
You only have to add `show-on-large` to
```html
<a href="#" data-activates="slide-out" class="button-collapse show-on-large"><i class="material-icons">menu</i></a>
```

**Comment by tomscholz** [comment]
https://codepen.io/tomscholz/pen/XpOvGP Try this. The only thing that isn't perfect, is the american flag (the img tag) in the navbar

**Comment by gusbemacbe** [comment]
OK, thank you for the language picker feature. Sorry that language picker feature can't be added to future release of Materialize. I'll fix the problems. 

As for the RTFM that you told me, I have read http://materializecss.com/side-nav.html before, but I tried it many times, adding hamburger icon and languages pickers and it didn't work. I compared my codes to yours and now I understood that I missed Javascript codes, some codes and the nav codes.

From now, I close the issue as you do not intend to add this new feature of language picker.

**Comment by jojojok16** [comment]
Hello,
I'm trying to make own language picker which will be in the menu (in nav) and I have problems with it. Links are not working anymore. Could you please resend it / help me with it?

**Comment by gusbemacbe** [comment]
@jojojok16, he removed his pen. I rebuilt myself a language picker. Here is my pen: https://codepen.io/gusbemacbe/pen/EbKGdg. Please download the pen, and when you download it, please, advice me

**Comment by gusbemacbe** [comment]
If you prefer language picker dropdown, check: https://codepen.io/ulyanchesnokov/pen/xOWgaR

**Comment by gusbemacbe** [comment]
It seems that another pen is better than mine, for you: https://codepen.io/alexluz/pen/qdmBYY.

Tell me which one of these three pens you prefer more.

**Comment by jojojok16** [comment]
Hello, thank you for replay. Accually, I would like something like select box in menu where you can choose language (and also for price). I was trying to use and change select box styles from minimalize (I'm doing website using minimalize styles), but I have problems with pictures there. I just would like to have simple selectbox with options of languages in simple pictures like https://ctrlv.cz/shots/2017/11/05/B6RL.png and https://ctrlv.cz/shots/2017/11/05/O93J.png where you can choose language after click on language pic. you will see list on pictures of flags and choose language you want and that flag you will see always in menu.

**Comment by gusbemacbe** [comment]
@jojojok16 

Here is my pen: https://codepen.io/gusbemacbe/pen/ZaOGjy

But you need to use PHP and Javascript to switch.

**Comment by tomscholz** [comment]
@Dogfalo It seems @gusbemacbe hasn't read the Code of conduct. In his codepen he insulted me. Could you Please remove his comment. Thanks!

**Comment by gusbemacbe** [comment]
Tom, you also insulted me before.

**Comment by gusbemacbe** [comment]
@Dogfalo, Tom also has insulted me in his removed pen. He made fun of me and ridiculed me in his removed pen.

**Comment by acburst** [comment]
Let's all try and be civil. This is github not some random forum. Lets just focus on development
