### ISSUE TITLE
Make tables with many columns responsive 

### ISSUE THREAD

**Issue by keyscores** [Dogfalo/materialize#424]
There are different options like in this example for bootstrap:
http://elvery.net/demo/responsive-tables/

**Comment by acburst** [comment]
Added in de4bc0c7055d85859cd6fee16bac106ab3b623ee

Thanks a bunch for the link. It was very useful!

**Comment by keyscores** [comment]
That was fast! Awesome!
Can you please also look at this new ticket I started:
https://github.com/Dogfalo/materialize/issues/427

Lucas Geiger
