### ISSUE TITLE
Swipeable tabs don't initialize properly on popout collapsibles

### ISSUE THREAD

**Issue by martendegroot** [Dogfalo/materialize#4240]
This issue is closely related to #1723 . I noticed the mentioned fix will make tabs work well with focus and stuff, but when the swipeable option is set to true, the original width of the collapsible body is taken. As soon as the collapsible pops out (on select) the body becomes a bit wider and then shows a small part of the second tab already.

The workaround for this issue is to resize the window.

**Comment by alphadx** [comment]
Did you add properly "row" tag in class?
Have you any codepen?

> When using Rows and Cols, make sure that whenever you use a Row, it is IMMEDIATELY followed by a Col. You should never have any structure that looks like Row -> Row, or Col -> Col. If you want a nested grid, your structure needs to look like Row -> Col -> Row -> Col.


>

**Comment by martendegroot** [comment]
Thanks for your response!
I made a simplified example of my issue down here:

https://codepen.io/planthugger/pen/zNbEXO?editors=1111

**Comment by acburst** [comment]
Hmm you can add a setTimeout? not sure what the cleanest way to fix that would be.

**Comment by fega** [comment]
Closed due inactivity, feel free to reopen it if it is still necessary.
