### ISSUE TITLE
HTML Body Scrolls with Side-Nav on IOS

### ISSUE THREAD

**Issue by Shopified** [Dogfalo/materialize#4246]
Whenever you try and scroll the side-nav the HTML body behind the overlay occasionally scrolls with the side nav <ul> element.

Tested in Chrome and Safari on IOS 9.3.2. Works perfectly on Android

This issue is visible on [http://materializecss.com](http://materializecss.com) on mobile

Anyone know why this might be?

**Comment by mirshko** [comment]
It seems to be able to be solved with adding `position: fixed;` to the `<body>` of the page and then clearing it when dismissing the sidebar.

@acburst @Dogfalo not sure if this is good practice for the framework, any thoughts?

**Comment by mirshko** [comment]
Fix in `sideNav.js`

Line 91
``` javascript
$('body').css({
            overflow: '',
            width: '',
            position: ''
          });
```

Line 311 
``` javascript
 $body.css('overflow', 'hidden')
                 .css('position', 'fixed');
```

**Comment by Dogfalo** [comment]
adding fixed to body isn't a good practice.

This behavior you describe is as intended, although probably not optimal. We've tried adding `overflow 'hidden'` to body in the past but that causes undesirable behavior with scrollbar flickering and pushing page content.

**Comment by Shopified** [comment]
Hi Guys,

Another option to look at is to slide the body right by the amount of
pixels/% that the NAV slides right.

That way when you trigger the NAV to slide the body slides with it and you
won't be able to scroll on the body as it's off screen.

Not sure if that is best practice though.

Let me know your thoughts

**Comment by mirshko** [comment]
@Dogfalo You currently use overflow: hidden; inside of sideNav.js

**Comment by Dogfalo** [comment]
@Shopified That causes a shift in the background which can be distracting, depending on what is reflowed

**Comment by Shopified** [comment]
@dogfalo You might be able to overcome the distraction slightly with an overlay. In the end, I suppose comes down to distraction vs frustration.

**Comment by rayriffy** [comment]
Try this https://github.com/Dogfalo/materialize/issues/4622
