### ISSUE TITLE
Showing chips autocomplete dropdown without key entry

### ISSUE THREAD

**Issue by kylewill** [Dogfalo/materialize#4250]
Can't find where to set the autocomplete data to display without any entry. I have a list of ~20-30 items I need to display on focus since the user won't know the options available. 

Similar to how  [Harvest's Chosen jquery plugin works](https://harvesthq.github.io/chosen/)

Is this possible?

**Comment by acburst** [comment]
Added a minLength in d537f34

The default is set to 1, but if you set it to 0 it should do what you want. This will be on our master branch so if you want to use the code you will have to download from our repository or wait until our next release.

**Comment by kylewill** [comment]
Thanks! 👍

**Comment by hiteshsahu** [comment]
Hi ,

I have same query. I am unable to figure out how to display dropdown of autocompletion data on focusing of chip `div`.

`   <div class="chips chips-autocomplete chips-placeholder" ></div>`

Any help would be appreciated
