### ISSUE TITLE
SELECT is not scrollable on iOS with v0.98.0

### ISSUE THREAD

**Issue by stsmurfy** [Dogfalo/materialize#4251]
### Description
If I have a SELECT with a huge amount of data, the item container seems unscrollable. When I try to scroll down to see other items it closes itself. With the older v0.97.8 this problem disappears. I tried with an iPad (iOS 10.2.1)

### Repro Steps
```
<div class="input-field col s12">
  <select>
    <option value="" disabled selected>Choose your option</option>
	<option>Option 1</option>
	<option>Option 2</option>
	<option>Option 3</option>
	...
	<option>Option 30</option>
  <select>
  <label>Materialize Select</label>
</div>
```

### Screenshots / Codepen
http://codepen.io/st_smurfy/pen/LxoEGj

**Comment by kmmbvnr** [comment]
The was #3854 that fixed recently.

You can link `https://gitcdn.xyz/repo/Dogfalo/materialize/master/bin/materialize.js` to the codepen and check the git version.

**Comment by stsmurfy** [comment]
Thanks. It really works.

**Comment by Alluuu** [comment]
Not just iOS, all touchscreen platforms, if by broken you mean when you touch anywhere to scroll it takes focus off of the select and it collapses.

**Comment by hiteshsahu** [comment]
I had the same issue. After a day of head scratching, I found out I was using the older version of the library.

Please check CDN version from
http://materializecss.com/getting-started.html

I am sharing code snippet on as new as 27/03/2017. Hope it helps somebody.

<meta name="viewport" content="width=device-width, initial-scale=1.0"/>


<link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">



<link rel="stylesheet"
      href="https://cdnjs.cloudflare.com/ajax/libs/materialize/0.98.1/css/materialize.min.css">
<link rel="stylesheet" href="https://cdn.datatables.net/1.10.13/css/jquery.dataTables.min.css">

<script type="text/javascript" src="https://code.jquery.com/jquery-2.1.1.min.js"></script>


<script type="text/javascript"
        src="https://cdnjs.cloudflare.com/ajax/libs/materialize/0.98.1/js/materialize.min.js"></script>
