### ISSUE TITLE
Carousel : Remove indiacator and drag events if just only one item

### ISSUE THREAD

**Issue by l2aelba** [Dogfalo/materialize#4252]
Should be good if some carousel has **just one item** , So its will remove indiacator and dragable events by default ?

**Comment by acburst** [comment]
Why do you have a carousel with only 1 item? and why would it remove its functionality?

**Comment by l2aelba** [comment]
@acburst Yep I know, But for lazy ppl like me and its "CSS Framework" hehe.

So If just able to remove "dragable" function its will good for me.

**Comment by acburst** [comment]
Added in 85a57eb1
