### ISSUE TITLE
Select Dropdown won't work

### ISSUE THREAD

**Issue by silu44** [Dogfalo/materialize#4253]
dropdown lists wont work with this simple code

` 

      <link href="http://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
      <link type="text/css" rel="stylesheet" href="css/materialize.min.css"  media="screen,projection"/>

    <select>
      <option value="" disabled selected>Choose your option</option>
      <option value="1">Option 1</option>
      <option value="2">Option 2</option>
      <option value="3">Option 3</option>
    </select>	

      <script type="text/javascript" src="https://code.jquery.com/jquery-2.1.1.min.js"></script>
      <script type="text/javascript" src="js/materialize.min.js"></script>

        `

**Comment by Maybach91** [comment]
https://jsfiddle.net/6d7k5xj8/2/

**Comment by stsmurfy** [comment]
Look at the documentation: [http://materializecss.com/forms.html#select-initialization](url)
