### ISSUE TITLE
Chips should scape caracter '<'

### ISSUE THREAD

**Issue by taorg** [Dogfalo/materialize#4255]
### Description
I'm testing with version 0.98.
If you write a chip with '<' caracter it is interpreted as a tag begins, instead as part of chip's text

### Repro Steps

1) Just type a normal text chip "asdfadfadf" and everything goes ok, this is the HTML generated:
`<div id="tag_chips_id" class="chips chips-autocomplete" data-index="0" data-initialized="true">
       <div class="chip">asdfadfadf<i class="material-icons close">close</i></div>`

2) Then type "<zx<zxc<zxc<xc<zxc<xc<" and this chip has no text and
`<div class="chip">
      <zx<zxc<zxc<xc<zxc<xc<<i class="material-icons close">close</zx<zxc<zxc<xc<zxc<xc<<i></div>`

### Screenshots / Codepen
Here is a screencapture 
http://pasteboard.co/zsKp8ZohJ.png

**Comment by superamadeus** [comment]
More importantly, 
```html
<script type="text/javascript">alert('hello')</script>
```
will be executed if entered as a chip value.

I'm not sure if it is out of the scope of this project, and I know that you should always escape user-provided input when serving it, but I think it is important that this gets documented.

**Comment by acburst** [comment]
Fixed in 52c5b85
