### ISSUE TITLE
Navbar dropdown does not work correctly

### ISSUE THREAD

**Issue by tastexmaker** [Dogfalo/materialize#4256]
I got a dropdown link in my navbar, using `<a data-activates="submenu">`. I placed a `<p>` and a `<div>` for an avatar image into the `<a>` tag.

Since I've upgraded to the latest version of Materialize and updated my materialize.js with the dropdown bugfix (dropdown menus hide when they become touched on mobile devices, see #3854 and #4251), the dropdown does not appear anymore when clicking on the text or the avatar image which are placed inside the `<a>` tag. It still shows correctly when I click in the "empty" space of the list item (= NOT at the `<p>` or the `<div>`). The Waves-Effect works correctly; even when clicking the image.

Here's the full code:
```
<li style='line-height: 64px; width: auto;'>
    <a data-activates='submenu' style='height: 64px; padding: 0 15px; vertical-align: top;' class='dropdown-button waves-effect waves-light'>
        <p style='display: inline; vertical-align: top; margin-right: 20px;'>Your Name</p>
        <div width='44px' height='44px' style='width: 44px; height: 44px; border-radius: 50%; margin-top: 10px; background: url(img/image.jpg) no-repeat; background-size: 100% 100%; background-position: center center; background-color: #fff; display: inline-block;'></div>
        <i class='material-icons right'>keyboard_arrow_down</i>
    </a>
</li>
```

**Comment by stsmurfy** [comment]
For me the "stopPropagation: true" option solved this issue.

**Comment by tastexmaker** [comment]
Thanks a lot, it works!! :)

**Comment by hiteshsahu** [comment]
Can you please share some code. 

This is how I was trying to do

 ```
 document.getElementById("strCountryNameOption").onclick = function(e) {
            if(e && e.stopPropagation )
           {
            e.stopPropagation();
          }
        else {
          e = window.event;
          e.cancelBubble = true;
    }
```

**Comment by hiteshsahu** [comment]
It worked for me now. After a day of head scratching, I found out I was using the older version of the library. 
Please check CDN version from
http://materializecss.com/getting-started.html

I am sharing code snippet on as new as 27/03/2017. Hope it helps somebody.

<meta name="viewport" content="width=device-width, initial-scale=1.0"/>


<link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">



<link rel="stylesheet"
      href="https://cdnjs.cloudflare.com/ajax/libs/materialize/0.98.1/css/materialize.min.css">
<link rel="stylesheet" href="https://cdn.datatables.net/1.10.13/css/jquery.dataTables.min.css">

<script type="text/javascript" src="https://code.jquery.com/jquery-2.1.1.min.js"></script>


<script type="text/javascript"
        src="https://cdnjs.cloudflare.com/ajax/libs/materialize/0.98.1/js/materialize.min.js"></script>
