### ISSUE TITLE
In waves.js, classList must be replaced by className for IE9 compatibility

### ISSUE THREAD

**Issue by DWboutin** [Dogfalo/materialize#4257]
In IE9, classList doesn't exists. So i changed the file waves.js at line 265 from this:

```javascript
} else if (target.classList.contains('waves-effect')) {
```

To this:

```javascript
} else if (target.className.indexOf('waves-effect') > -1) {
```

**Comment by tomscholz** [comment]
https://github.com/Dogfalo/materialize#supported-browsers Materialize only supports IE10+

**Comment by DetlefPeters** [comment]
classList is neither defined in IE10 nor IE11

please reopen, problem exists in latest IE, too!

**Comment by tomscholz** [comment]
I guess you could just create a pr

**Comment by DetlefPeters** [comment]
Sorry, I don't know what 'pr' means- please explain.
