### ISSUE TITLE
Mulitple select - When submitting form it only get the last option value

### ISSUE THREAD

**Issue by IamHenryValdez** [Dogfalo/materialize#4258]
When i'm using the materialize select multiple attributes in a form and it have multiple options checked, it does send all the option, but they all have the same name in the Form Data and it result of PHP only getting the last element checked because it overwrite all the others.

Does someone has a solution on how to get all value in a single string separated by the ', ' like the materialized select display to the user ?

Eg. 'value1, value2, value3'

**Comment by stsmurfy** [comment]
Put [] after the name (e.g. name="colors[]"). On the server side you will receive colors as an array with the selected values.
