### ISSUE TITLE
Navbar mobile collapse not working with two <ul>

### ISSUE THREAD

**Issue by paladini** [Dogfalo/materialize#426]
Hi guys,

A few days ago I start developing a small project with this awesome framework and now I found I thing that maybe can be a bug, maybe can be a suggest to improvement.

I'm trying to add a "left side-nav" and a "right side-nav" in the same page and this currently works for larger devices, but don't work when I use navbar mobile collapse.

Check the following code:

```html
<nav class="orange darken-2">
    <div class="container">
        <div class="nav-wrapper">
            <ul id="nav-mobile" class="left side-nav">
                  <li><a href="index.html" alt="Página Inicial" title="Página Inicial"><i class="mdi-action-home left"></i>Página Inicial</a></li>
             </ul>
             <ul id="nav-mobile-second" class="right side-nav">
                  <li><a href="https://docs.google.com/forms/d/1hOiWd-MlsfZ-1n5EMOPjxnJ6l7_TcBgxtR49QY2Yxdg/viewform" target="_blank" rel="nofollow" alt="Envie uma sugestão de citação" title="Envia uma sugestão de citação">Enviar uma citação</a></li>
                  <li><a href="#" class="active" alt="Sobre o projeto" title="Sobre o projeto">Sobre</a></li>
             </ul>
             <a class="button-collapse" href="#" data-activates="nav-mobile nav-mobile-second"><i class="mdi-navigation-menu"></i></a>
        </div>
    </div>
</nav>
```

Some suggestion of how solve that or I must treat that as an improvement suggestion?

**Comment by Dogfalo** [comment]
Did you try 
```Javascript
$(".button-collapse").sideNav({edge: 'right'});
```

**Comment by paladini** [comment]
I'll try that now. Sorry, but how to use this Javascript function is not very clear in the documentation.

**Comment by Dogfalo** [comment]
You can't have two menus open with one button.

**Comment by paladini** [comment]
I actually don't want that two menus open, I just want one openned menu with the <li> contents of both <ul> (left and right). This isn't a good feature request?
