### ISSUE TITLE
Medium horizontal card with card-action doesn't work

### ISSUE THREAD

**Issue by Larspolo** [Dogfalo/materialize#4260]
### Description
When making a medium horizontal card with card-action, there are some problems. First of, the image becomes miss formed,  and second the card-content overflows the content and can cover the card-action.

### Repro Steps
This Codepen is used to demonstrate my issue: http://codepen.io/Dogfalo/pen/xbzPQV

**Comment by acburst** [comment]
The codepen is our empty boilerplate. You need to save or fork the codepen for your changes to appear permanently.
