### ISSUE TITLE
unstable SideNav scrollBar in the website 

### ISSUE THREAD

**Issue by kartikchauhan** [Dogfalo/materialize#4264]
The scrollbar in SideNav blinks when hovered over it. It doesn't scroll when you try for the first time.

**Comment by tomscholz** [comment]
Can you provide some more information (e.g. browser, system) and how to reproduce it?

**Comment by kartikchauhan** [comment]
Yes, i'm using Google Chrome version 56.0.2924.87

**Comment by tomscholz** [comment]
...and how to reproduce it? :D

**Comment by kartikchauhan** [comment]
I tried fixing it by removing class 'fixed' from ul element with id="nav-mobile".

**Comment by fega** [comment]
Please follow the [contributing guidelines](https://github.com/Dogfalo/materialize/blob/master/CONTRIBUTING.md)
