### ISSUE TITLE
Quick question about the showcase

### ISSUE THREAD

**Issue by djensen47** [Dogfalo/materialize#4267]
I submitted my site to the showcase a few weeks ago with no response. So, if I submit a PR with an updated Showcase, would it be accepted?

Also, I'm willing to add other sites that have been submitted while I'm at it if you include a list in this issue.

Thanks!

**Comment by acburst** [comment]
We get many showcase submissions and there is no guarantee that if you submit your site it will be accepted. We do not want it to become an endless list but rather a short and curated list

**Comment by djensen47** [comment]
🤔 Cool, cool, cool. Good to know. But it turns out this list is very out of date. Several sites don't exist, one is marked as malware, a few others don't even use Materialize any more.

Basically, I was just trying to help.

**Comment by djensen47** [comment]
I'm opening another issue with all the problem sites.

**Comment by djensen47** [comment]
#4275 Lists the problematic showcase sites
