### ISSUE TITLE
 Problem with animations and select

### ISSUE THREAD

**Issue by lukecorf** [Dogfalo/materialize#4269]
I'm using Angular 2 to program my web application. And I chose to use the Materialize Forms to make the interface look more beautiful. But I have some problems. 

This is my html file:

`<!DOCTYPE html>
  <html>
    <head>
      
      <link href="http://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
      
      <link type="text/css" rel="stylesheet" href="materialize\css\materialize.min.css"  media="screen,projection"/>
      
      <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    </head>

    <body>
        <div class="input-field col s6">
          <input placeholder="Placeholder" id="first_name" type="text" class="validate">
          <label for="first_name">First Name</label>
        </div>
        <div class="input-field col s12">
            <select>
                <option value="" disabled selected>Choose your option</option>
                <option value="1">Option 1</option>
                <option value="2">Option 2</option>
                <option value="3">Option 3</option>
            </select>
            <label>Materialize Select</label>
        </div>

    
    <script type="text/javascript" src="https://code.jquery.com/jquery-2.1.1.min.js"></script>
    <script type="text/javascript" src="materialize\js\materialize.min.js"></script>
    <script>
        $(document).ready(function() {
            Materialize.updateTextFields();
        });

        $(document).ready(function() {
            $('select').material_select();
        });

    </script>
    </body>
  </html>        `

When you do this, the forms look like this:

![untitled](https://cloud.githubusercontent.com/assets/22321349/23166184/57961e40-f81e-11e6-8459-accf032888bc.png)

The imput has no effect and the select does not work.

Can you help me, please?

**Comment by Dogfalo** [comment]
This is related to how plugins must be initialized with Angular which creates elements dynamically. Please search close issues.
