### ISSUE TITLE
Mobile Nav Bar is not closing on click/touch - 0.94.2 

### ISSUE THREAD

**Issue by keyscores** [Dogfalo/materialize#427]
When you click on a link with the mobile navbar it should close, correct? I think that is the expected behavior. Tested on different browsers, with same result.

**Comment by keyscores** [comment]
Possible duplicate: https://github.com/Dogfalo/materialize/issues/411

**Comment by keyscores** [comment]
@Dogfalo 
How can I help with this?

**Comment by keyscores** [comment]
I'm still having trouble with this on 1.95.1

**Comment by Dogfalo** [comment]
Added an option to control this in c5e00fea093f3252d223d1ddf6f244ef2a28e0b9
