### ISSUE TITLE
Showcase sites don't exist or don't use Materialize

### ISSUE THREAD

**Issue by djensen47** [Dogfalo/materialize#4275]
7 out or 23 showcase sites have problems. They either no longer exist or no longer use MaterializeCSS:

Broken links
- [ ] Emerald
- [ ] DLSU Hacker Cup
- [ ] The 100
- [ ] Caliber (security error)
- [ ] Jumpr.it

No longer uses Materialize
- [ ] Fedora Indonesia - look at the column definitions, they switched to something else
- [ ] Mako - they're using bootstrap
- [ ] Webonise - looks like they are using Bootstrap material design instead
- [ ] Kenya apps - looks like they are using Bootstrap

I was fairly liberal in my determination of use. If the materialize CSS was not including in the source, I looked for usage that is somewhat unique to materialize, particularly the `col` syntax or the use of `lighten-` or `darken-`.

**Comment by fega** [comment]
The 100 is now a broken link

**Comment by tomscholz** [comment]
> #4804 

down
- https://www.100xp.io/ 
- http://www.hackercup.co/
- http://www.straphq.com/
- http://www.jumpr.it/

malware 
- http://emerald.sekizgen.net/
- http://jumpcatch.com/srinivasan/caliber/

**Comment by DanielRuf** [comment]
@tomscholz it seems the documentation files are not regenerated as there are still the old showcases on the Materialize website.
