### ISSUE TITLE
i need searchable drop down for my new project. Guyz anybody have any idea about thiz=s

### ISSUE THREAD

**Issue by nibinnelson007** [Dogfalo/materialize#4276]
### Description
Add a detailed description of your issue.

### Repro Steps
Layout the steps to reproduce your issue.

Use this Codepen to demonstrate your issue. http://codepen.io/Dogfalo/pen/xbzPQV

### Screenshots / Codepen
Add supplemental screenshots or code examples. Look for a codepen template in our Contributing Guidelines.

**Comment by tomscholz** [comment]
Please close. https://github.com/Dogfalo/materialize/issues/4277
