### ISSUE TITLE
Searchable Dropdown

### ISSUE THREAD

**Issue by nibinnelson007** [Dogfalo/materialize#4277]
> Can anybody help me to find a searchable drop down .

 actually materialize have exactly same like feature under forms, but materialize autocomplete only shows the type related contents. But i need a drop down that has a search option. @Dogfalo

**Comment by stap123** [comment]
@nibinnelson007 I've posted a solution I am using in #3096 if it's of any use

**Comment by stap123** [comment]
#3096
