### ISSUE TITLE
Is it possible to change icon <i> color when <select> is open?

### ISSUE THREAD

**Issue by kiwo12345** [Dogfalo/materialize#4279]
I wonder if its possible to change the icon i color when select is open?

```
<div class="input-field col s4">
                            <i class="material-icons prefix">local_offer</i>
                            <select>
                            <option value="" disabled selected>Select offer</option>
                            <option value="1">Option 1</option>
                            <option value="2">Option 2</option>
                            <option value="3">Option 3</option>
                          </select>
                            <label>Offer</label>
                        </div>
```

So when I click on the <select> and my options show up I want to change the color of `<i class="material-icons prefix">local_offer</i>` as well

**Comment by tomscholz** [comment]
Could you provide some kind of codepen or image to illustrate your issue?

**Comment by Native-Coder** [comment]
Just change the color via javascript. If you have jquery, you could do something like `$('your_selector_here').addclass('blue-text')`

**Comment by kiwo12345** [comment]
@Native-Coder Thanks for the example. The only problem is that I dont know how to check if the <select> is open using jquery

**Comment by tomscholz** [comment]
Check this out https://learn.jquery.com/using-jquery-core/faq/how-do-i-test-whether-an-element-has-a-particular-class/
