### ISSUE TITLE
in asp.net i created a button and give the css style as waves-effect waves-light btn not getting the style 

### ISSUE THREAD

**Issue by gjgit** [Dogfalo/materialize#428]
in asp.net i created a button and give the css style as waves-effect waves-light btn ... but instead of getting the ripple effect i getting the dark gray shadow in the button text 

<asp:Button ID="Button1" CssClass="waves-effect waves-light btn" runat="server" Text="gjramanaa" />
![gj](https://cloud.githubusercontent.com/assets/2841150/5678296/cee457b0-9816-11e4-89a7-d56256431464.png)

**Comment by Dogfalo** [comment]
Use `<a>`  instead.
