### ISSUE TITLE
[Carousel] If you put an image into a carousel-item, the whole carousel's height gets resized to the height of the image.

### ISSUE THREAD

**Issue by lastnoob** [Dogfalo/materialize#4280]
### Description
When you add an <img> to the carousel-item it resizes the carousel's height to the image's height. If you edit the image's height it edits the carousel's. I found it impossible to set the height of the carousel, or the carousel-item with css.

### Repro Steps
Insert an image into a carousel item.

[Or check this Codepen](https://codepen.io/simii/pen/ryBGQm)

### Screenshots
![image](https://cloud.githubusercontent.com/assets/1821091/23220935/8476c8f0-f8f1-11e6-9cb5-9ad16a532855.png)
![image](https://cloud.githubusercontent.com/assets/1821091/23220947/8ee3aede-f8f1-11e6-9967-f00822e92b92.png)

**Comment by acburst** [comment]
Would you prefer if you could override the height of the carousel with a plugin option?

**Comment by tomscholz** [comment]
Closed due inactivity. Feel free to reopen it, if it's still necessary.

**Comment by wvicioso** [comment]
same issue. I'm trying to place multiple images inside a single carousel-item and the whole carousel keeps resizing

**Comment by helderfalcao** [comment]
Someone found the solution?

**Comment by lastnoob** [comment]
just give the carousel a fixed height with !important, seems like the easiest solution

**Comment by helderfalcao** [comment]
Tks @lastnoob ! I will try it

**Comment by phoebebright** [comment]
I am putting images of pages in the carousel and want to view them on maximum size for the screen/device so setting a hard height does not work for me.  What would be ideal is to have a "fullSize" option that resizes the carousel to fit the image, making it as large as possible given the constraints of the screen, but does not crop.
