### ISSUE TITLE
Modal not working for Meteor

### ISSUE THREAD

**Issue by jhochgreve** [Dogfalo/materialize#4281]
### Description
Using the documented modal initialization method I am getting "(...).modal is not a function"
I am wondering if the atmosphere package is out of date? 

Here is my code: 

```
  <!-- Modal Trigger -->
  <a class="waves-effect waves-light btn" href="#modal1">Modal</a>

  <!-- Modal Structure -->
  <div id="modal1" class="modal">
    <div class="modal-content">
      <h4>Modal Header</h4>
      <p>A bunch of text</p>
    </div>
    <div class="modal-footer">
      <a href="#!" class=" modal-action modal-close waves-effect waves-green btn-flat">Agree</a>
    </div>
  </div>
````

```
Template.OneClientFacilities.onRendered(function(){
  $('#modal1').modal();
});
```

### Repro Steps
Simply try to use the modal via the docs. I am noticing; however, the the .openModal method works just fine.

**Comment by tomscholz** [comment]
No, the atmosphere package should be not out of date. Do you have the latest materialize version and jQuery installed? For me it works. I created a very basic repo [here](https://github.com/tomscholz/materialize-modal-meteor). Please try to run it and tell me if it works :)

**Comment by TristanWiley** [comment]
Occurring for me, seemed to happen after a Meteor patch update.

**Comment by TristanWiley** [comment]
Temporarily fixed by downgrading to 0.97.0

`meteor add materialize:materialize@=0.97.0`

**Comment by jhochgreve** [comment]
Yes I did have the latest version of both. I installed via the atmosphere package. I didn't downgrade but was able to verify that when using the older model (from previous versions of Materialize) it does work. Which is fine but not optimal. Tristan I also tested going with the downgrade and your right it works also...though even without it the old method works.

**Comment by tomscholz** [comment]
But does the project I created work for you?

**Comment by jhochgreve** [comment]
Sorry I had not tried as using the older method worked. I just tried and can confirm that yes it does work.

**Comment by tomscholz** [comment]
Closed due inactivity, feel free to reopen it if it is still necessary

**Comment by pouyapanahandeh** [comment]
ok, I have the same issue and tried the way you mentioned but it's not working, do you have any other option to fix the problem?
