### ISSUE TITLE
waves-* not documented properly

### ISSUE THREAD

**Issue by ahmetalpbalkan** [Dogfalo/materialize#4282]
If I read http://materializecss.com/buttons.html I see that there is a class called `.waves-effect` and there's something called `.waves-light` always used with it.

1) I don't know if they MUST be used together all the time, or they work individually
2) I don't know if there are alternatives to `.waves-light` (like `.waves-strong`?)

This looks like a documentation gap.

**Comment by Dogfalo** [comment]
http://materializecss.com/waves.html

**Comment by ahmetalpbalkan** [comment]
@Dogfalo might be helpful to link to this page from /buttons.html as I have been reading the CSS portion and did not explore the "Javascript" section at all yet.
