### ISSUE TITLE
.col.right-align does not move button to right

### ISSUE THREAD

**Issue by ahmetalpbalkan** [Dogfalo/materialize#4284]
I have two divs: `.row > .col.[s6,s6]` the second one also has `.right-align`. However the `.btn` in it does not get aligned to the right.

http://codepen.io/anon/pen/wJwYLw

![image](https://cloud.githubusercontent.com/assets/159209/23235110/1aae428c-f909-11e6-81c4-81c6cfb07c39.png)

Shouldn't the blue button be on the right? The docs say:

> These classes are for horizontally aligning content. We have .left-align,  .right-align and .center-align

**Comment by tomscholz** [comment]
You have to apply the .right class to the button, not the column.
https://codepen.io/anon/pen/evOQZE?editors=1100
