### ISSUE TITLE
chips-autocomplete & chips-placeholder don't work together

### ISSUE THREAD

**Issue by ahmetalpbalkan** [Dogfalo/materialize#4285]
If `.chips-autocomplete` and `.chips-placeholder` were both set on a `.chip` the placeholder javascript code does not do anything visible. When you remove the `.chips-autocomplete`  it starts working again.

http://codepen.io/anon/pen/VpZVxJ

**Comment by acburst** [comment]
You are calling chips twice on the same element. When you init the chips autocomplete you are overriding your previous options. You can combine the options into one call.

**Comment by kartikchauhan** [comment]
@acburst can you show us how?

**Comment by DulcePC** [comment]
I think he try to say something like this:
$('.chips-autocomplete').chips({
  placeholder: "Escribenos tus sintomas aqui",

and then the autocomplete...

**Comment by DulcePC** [comment]
$('.chips-autocomplete').chips({
  placeholder: "Escribenos tus sintomas aqui"

i think he try to say this
