### ISSUE TITLE
Media Grid, maybe?

### ISSUE THREAD

**Issue by wildramen** [Dogfalo/materialize#4286]
Isn't actually an issue, but i recently have seen this: [Kube Media Grid](https://imperavi.com/kube/docs/grid/#h-media-grid) and i wondered why MaterializeCSS doesn't have one. 

I find it useful for blogs or galleries.

**Comment by fega** [comment]
I agree, creating a media grid is a pain in materialize, What about a plugin to solve this?

**Comment by wildramen** [comment]
I was trying to say that a native media grid like Masonry would be a huge boost for MaterializeCSS to help developers build blogs easier, especially Tumblr themes and Wordpress themes. :D

**Comment by tomscholz** [comment]
The materialize [Gallery theme ](https://themes.materializecss.com/) uses http://masonry.desandro.com/

**Comment by fega** [comment]
nice!

**Comment by tomscholz** [comment]
Actually there is even a masonry demo [here](https://rawgit.com/Dogfalo/materialize/master/templates/masonry-template/preview.html)
