### ISSUE TITLE
Input field problems in modals

### ISSUE THREAD

**Issue by CelticSLO** [Dogfalo/materialize#4287]
Im fairly new to all of this and ive been trying make a login modal. I have a lot of problems with the input fields inside the modal:
1. When I click on the field to enter text in it the label moves really high up outside of the modal.
2. The text and the bottom line in the field are white and not really visible

```
                  <div id="modal1" class="modal" >
                        <h4 style="color:black" align="center">Prijava</h4>
                        <div class="row">
                            <form class="col s12">
                                <div class="row">
                                    <div class="input-field col s6">
                                        <input id="input_text" type="text" data-length="10">
                                        <label for="input_text">Input text</label>
                                    </div>
                                </div>
                            </form>
                        </div>                        
                    </div>
```

This is what it looks like when the modal gets opened:
                    
![zajeta slika](https://cloud.githubusercontent.com/assets/25979814/23257248/4b3631a2-f9c3-11e6-8a1d-60287c093e8e.JPG)
</div>

When you click on the input, the label moves up and you dont really see that you can type cause everything is white:

![zajeta slika2](https://cloud.githubusercontent.com/assets/25979814/23257263/606d5d5c-f9c3-11e6-9ce0-b60e770c0929.JPG)

**Comment by acburst** [comment]
What browser and operating system are you using?

**Comment by fega** [comment]
Closed due inactivity, feel free to reopen it if it is still necessary.
