### ISSUE TITLE
input type="range" tooltip doesn't move with keyboard input

### ISSUE THREAD

**Issue by ahmetb** [Dogfalo/materialize#4288]
If I focus the range input from another input box with Tab key and use arrow keys to move the slider, the tooltip provided by Materialize does not follow the range slider:

### Screenshots / Codepen

Demo: http://codepen.io/anon/pen/LWYryW

If I use my mouse to drag the slider:

>  ![image](https://cloud.githubusercontent.com/assets/159209/23286809/d6609102-f9ee-11e6-973c-016d5510bc25.png)

If I use arrow keys to move the slider:

>  ![image](https://cloud.githubusercontent.com/assets/159209/23286821/e2c8c342-f9ee-11e6-8f59-98e92cde6818.png)

Note that I'm not using `noUISlider.{js,css}`.

**Comment by acburst** [comment]
Fixed in e5c2161

**Comment by ahmetb** [comment]
@acburst thanks. 🙌
