### ISSUE TITLE
Merge changes to dist/js/materialize.js

### ISSUE THREAD

**Issue by haojia321** [Dogfalo/materialize#4289]
Hi 
I have cloned from master into packages folder. I want to change something from /js/modal.js to fix some bugs. But I found it won't automatically update dist/js/materialize.js after I save /js/modal.js. So my changes won't reflect because of this.

So I just want to know what's the best way for other people who wants to fix some bug and create PR here?

Thanks

**Comment by acburst** [comment]
The dist files are only for our official version releases. Once we deem there have been enough fixes or progress to warrant a new release, we will update the dist. Take a look at our contributing.md to see more about writing PRs

**Comment by haojia321** [comment]
I had grunt monitoring.
I dont see /dist/js/materialize.js is updated after changed /js/modal.js
Is my grunt running correctly? This is grunt log from console:
>> File "js/modal.js" changed.
    
    Running "concat:temp" (concat) task
    File temp/js/materialize.js created.
    
    Running "uglify:bin" (uglify) task
    >> 1 file created.
    
    Running "notify:js_compile" (notify) task
    [BS] Reloading Browsers...
    
    Running "clean:temp" (clean) task
    >> 1 path cleaned.
    
    Running "watch:js" (watch) task
    Completed in 2.178s at Fri Feb 24 2017 23:48:22 GMT-0500 (EST) - Waiting...

**Comment by tomscholz** [comment]
First run `grunt monitor`then save the changes. Then it should work

**Comment by haojia321** [comment]
I'm using Meteor framework.
Local changes will only merge to bin/materialize.js NOT dist/js/materialize.js. So a work around I did was modify package.js from:
api.addFiles([
    'dist/js/materialize.js'
  ], 'client');
to
api.addFiles([
    'bin/materialize.js'
  ], 'client');
