### ISSUE TITLE
Quick improvement for webkit mobile browsers -webkit-tap-highlight-color: transparent

### ISSUE THREAD

**Issue by erkkaha** [Dogfalo/materialize#429]
There is a default tap-highlight-color on elements other than buttons, which results sometimes to not so nice tap highlight effects. For instance clicking on the burger icon to expand the side nav will result to blueish square to float above the side nav for a noticeable time. Quick fix for this would be to add 
-webkit-tap-highlight-color: transparent or -webkit-tap-highlight-color: rgba(0,0,0,0) to css under body or html selector.

**Comment by Dogfalo** [comment]
This is a good suggestion, but we do have to consider that reduced feedback for the user which may impact usability.

**Comment by erkkaha** [comment]
User feedback, where lost, could be better achieved through styling in onclick events. Tap highlighted area is not necessary same as the visible parts of the tapped element, which makes it appear buggy. This can be observed for example with card reveal component on android 4.3 chrome, both card title and handle are highlighted while the space between them is not.

**Comment by Dogfalo** [comment]
This has been added to our documentation site, but I think we will leave it up to the developer to handle it.
