### ISSUE TITLE
carousel resize not auto height

### ISSUE THREAD

**Issue by yang5664** [Dogfalo/materialize#4292]
### Description
when I resize browser view, the carousel height does not auto scale.
so I change same code part of materialize.js at line of 7958 make it work, but I still need a good suggestion.
```ruby
        $(window).on('resize.carousel', function() {
          if (options.fullWidth) {
            item_width = view.find('.carousel-item').first().find('img').first().innerWidth(); //<== this line
            item_height = view.find('.carousel-item').first().find('img').first().innerHeight();//<==
            dim = item_width * 2 + options.padding;
            offset = center * 2 * item_width;
            target = offset;
            view.css('height', item_height); //<== reassign height
          } else {
            scroll();
          }
        });
```
### Screenshots / Codepen
![2017-02-26_00-02-49](https://cloud.githubusercontent.com/assets/5953010/23333088/7bb698ae-fbc0-11e6-8c1b-0334f2aa7936.png)
<img width="479" alt="screen shot 2017-02-26 at 1 12 20 am" src="https://cloud.githubusercontent.com/assets/5953010/23333102/b3b57914-fbc0-11e6-9b48-757afa6febe0.png">

**Comment by acburst** [comment]
Added in 16513d56
