### ISSUE TITLE
materialboxed does not override max-height in .card-image

### ISSUE THREAD

**Issue by ahmetb** [Dogfalo/materialize#4293]
### Description

I have a `.card.image img` that has `.materialboxed` but I am limiting the height of the image with `max-height:150px` and using `object-fit`, `object-position` to show only the middle area of the image.

When I click to the image to open in Material Box, the image in the modal view keeps these properties so it still shows the cropped image.

If I add the `max-height` to `.card-image` that doesn't actually limit the image's size and it keeps overflowing. Any workarounds? Perhaps if I could catch some event I could remove the `max-height` and other properties temporarily.

### Codepen:
http://codepen.io/anon/pen/vxEVNy

**Comment by Dogfalo** [comment]
You can remove it on a regular click handler or add it to the materialbox function yourself, but it won't transition properly
