### ISSUE TITLE
materialize.js cannot work

### ISSUE THREAD

**Issue by willin** [Dogfalo/materialize#4295]
### Description

i want to make a gitbook theme, and require  materialize.js after jquery

<img width="1675" alt="wx20170227-162213 2x" src="https://cloud.githubusercontent.com/assets/1890238/23353762/12313fc0-fd09-11e6-9fcb-68737e955d95.png">

but it doesn't work.

### Repro Steps
Layout the steps to reproduce your issue.

source code: <https://github.com/willin/gitbook-plugin-theme-material/blob/master/src/js/core/index.js#L38>

i also tried to move the `require` statement to [Line 55](https://github.com/willin/gitbook-plugin-theme-material/blob/master/src/js/core/index.js#L55) still not work

Add supplemental screenshots or code examples. Look for a codepen template in our Contributing Guidelines.

<img width="1677" alt="wx20170227-162402 2x" src="https://cloud.githubusercontent.com/assets/1890238/23353906/bc7eebda-fd09-11e6-9b93-b1f70adbbe58.png">

but if i use getScript it works.

**Comment by kmmbvnr** [comment]
Looks relevant to #4232 #4012 #3812

@willin can you try that  https://github.com/Dogfalo/materialize/issues/3812#issuecomment-260183548 ?

**Comment by willin** [comment]
yes done. 

i don't know why, the jquery i require is the same version 2.2.4
and by default `node_modules/materialize-css/` does not have the folder `node_modules/materialize-css/node_modules` i need to `cd` into it and run `npm install`.

is there any method to solve it?

**Comment by Dogfalo** [comment]
Duplicate issue

**Comment by willin** [comment]
@Dogfalo ?
