### ISSUE TITLE
Date Picker doesn't grow with font size

### ISSUE THREAD

**Issue by Native-Coder** [Dogfalo/materialize#4298]
### Description
If you override the font size in your materialize project, the datepicker fails to grow with it. 

### Repro Steps
1: Increase the font size in your project.
2: Notice that the date picker is too small

### Screenshots / Codepen
Here is a codepen showing the issue http://codepen.io/anon/pen/vxOwey

**Comment by Native-Coder** [comment]
hmmm. The issue was perfectly reproducible until I hit the "fork" button at the top of the codepen... now it works perfectly as expected...interesting...

**Comment by tomscholz** [comment]
I would recommend to use sass when changing the font-size 🤔

**Comment by Dogfalo** [comment]
We designed it to match Material spec. If you want to customize font sizes, you can also increase the size of the picker to match.
