### ISSUE TITLE
Implicit whitespace browser behavior

### ISSUE THREAD

**Issue by jairodelgado** [Dogfalo/materialize#4300]
### Description
I have been playing around JSX with materialize and I have found a disturbing issue. For example:

``````` html
<button type="submit" class="btn waves-effect">Save</button>
<button class="btn waves-effect blue-grey">Cancel</button>
```````
The browser implicit behavior is to add a white-space for inline elements for the line-break. Now,  if JSX  inlines the code and [removes the white spaces](https://facebook.github.io/react/blog/2014/02/20/react-v0.9.html#jsx-whitespace) the buttons won't be rendered properly(I mean margins). Similar issues happens with other styles such as the counter option for inputs and I can imagine several others.

You may say: 

> Dude, that is a problem of the guys who makes JSX, go and tell them to add the white space as expected.

Well, the fact is that someone else already[ asked for it](https://github.com/facebook/react/issues/1643) and the answer seemed pretty convincing:

1. You should not relay on browser implicit behavior of adding a white space for each line break.
2. This is a style issue, a white space shouldn't be there at first place from a semantic point of view. Hence, there should be CSS rules for proper margins of each element.

I think the solution is to check each style of the library having this in mind. For the moment, the solution I have found is to add an explicit whitespace `&nbsp;` at the proper places.

**Comment by fega** [comment]
As you said this was already answered.
Thanks

**Comment by jairodelgado** [comment]
You should read carefully. The answer was from the JSX team and is something that you should consider in Materialize since this is actually not consistent. That means that for JSX sites Materialize wont be rendered as expected

**Comment by fega** [comment]
Oh, Jaja I didn't check the report name, sorry

Can you provide us a way to check how this is affecting the materialize-react integration?
