### ISSUE TITLE
Make the dropdown parent menu as a Link.

### ISSUE THREAD

**Issue by htlcode** [Dogfalo/materialize#4301]
### Description

```
<ul id="dropdown1" class="dropdown-content">
<li><a href="#!">one</a></li>
<li><a href="#!">two</a></li>
<li class="divider"></li>
<li><a href="#!">three</a></li>
</ul>
<nav>
<div class="nav-wrapper">
<a href="#!" class="brand-logo">Logo</a>
<ul class="right hide-on-med-and-down">
<li><a href="sass.html">Sass</a></li>
<li><a href="badges.html">Components</a></li>
<!-- Dropdown Trigger -->
<li><a class="dropdown-button" href="link.html" data-activates="dropdown1">Dropdown Menu Parent<i class="material-icons right">arrow_drop_down</i></a></li>
</ul>
</div>
</nav>
```

With the code above is not possible to use the "Dropdown Menu Parent" as a Link

### Repro Steps
When we click on the "Dropdown Menu Parent" the href link don't work.

### Request 
Is it possible to make it work like a link, and the dropdown menu activated on the arrow_drop_down icon ?

**Comment by fega** [comment]
Why are you trying to achieve that?, personally I believe that it should be confusing
Also, this is behavior is not in the material design specs

**Comment by beyzakilickol** [comment]
On materialize.min.js file, there is keydown event listener which is preventing default href functionality. I was having the same issue and found a work around by adding click event listener to dropdown trigger(parent) item. And inside the callback, doing:
`window.location = this.href;`
I know this is not an optimized way but at least meeting my target.
Thanks
