### ISSUE TITLE
 fixed navbar after scroll

### ISSUE THREAD

**Issue by life61** [Dogfalo/materialize#4304]
### Description
Add a detailed description of your issue.
how can I fix the navbar after a div with scrolling?
### Repro Steps
Layout the steps to reproduce your issue.

<div class="header-countdown">
    <div class="section red ">
        <div class="container">
            <article id="home"class="scrollspy">
                <div class="row">
                    <div class=" col s12 m4 l3 center-align white-text" id="startevento">
                    START EVENTO:
                    </div>
                        <center><div class=" col s12 m4 l6 white-text"id="countdown"><b>100 : 20 : 30 : 90</b></div></center>
                        <div class=" col s12 m4 l3 center-align white-text"><a href="index.php#contatti"><center><div id="btn-submitup">Rimani in contatto</a></div></center></div>
                </div>
            </article>
        </div>
    </div>
</div>
<nav>
   <div class="nav-wrapper white">
       <a href="#"data-activates="mobile-demo"class="button-collapse"><i class="material-icons red-text">menu</i></a>
          <ul class="right hide-on-med-and-down ">
              <li class="active"><a href="index.php#home"><div class="red-text">Home</div></a></li>
              <li><a href="index.php#cos'è?" class="red-text" >Che cos'è?</a></li>
              <li><a href="index.php#argomenti-trattati"class="red-text">Argomenti trattati</a></li>
              <li><a href="index.php#ospiti"class="red-text" >Gli ospiti</a></li>
              <li><a href="index.php#media"class="red-text" >Media</a></li>
              <li><a href="index.php#beneficenza" class="red-text" >La beneficenza</a></li>
              <li><a href="index.php#chi-siamo"class="red-text" >Chi siamo</a></li>
              <li><a href="index.php#contatti" class="red-text" >Contatti</a></li>
          </ul>
          <ul class="side-nav"id="mobile-demo">
              <li><a href="index.php#home" >Home</a></li>
              <li><a href="index.php#cos'è?" >Che cos'è?</a></li>
              <li><a href="index.php#argomenti-trattati" >Argomenti trattati</a></li>
              <li><a href="index.php#ospiti">Gli ospiti</a></li>
              <li><a href="index.php#media" >Media</a></li>
              <li><a href="index.php#beneficenza"  >La beneficenza</a></li>
              <li><a href="index.php#chi-siamo">Chi siamo</a></li>
              <li><a href="index.php#contatti">Contatti</a></li>
          </ul>
   </div>
</nav>

Use this Codepen to demonstrate your issue. http://codepen.io/Dogfalo/pen/xbzPQV

### Screenshots / Codepen
Add supplemental screenshots or code examples. Look for a codepen template in our Contributing Guidelines.
![2017-03-01 15_30_59-beautiful day ekis](https://cloud.githubusercontent.com/assets/20339547/23464235/a37187ba-fe94-11e6-9543-6a5759e6419e.png)

**Comment by acburst** [comment]
You can use our pushpin plugin: http://materializecss.com/pushpin.html
