### ISSUE TITLE
Select and Input doesn't work (Cordova problem?)

### ISSUE THREAD

**Issue by nidhoeggr09** [Dogfalo/materialize#4305]
I'm creating an Android/iOS app with Cordova and Visual Studio and would like to style the app with materialize. However there seems to be a problem with the initialization. I searched through the tutorials as well as the issues and wasn't able to find a solution. Basically there are two problems, but i think they have the same root problem.

**Problem #1: Input fields**
When i create an input field it first looks correct:
![1](https://cloud.githubusercontent.com/assets/1476386/23499601/0df09eee-ff2d-11e6-95a4-2786510736aa.png)
But when i enter text, the description does not move up as it should and then overlaps the text:
![2](https://cloud.githubusercontent.com/assets/1476386/23499602/0df2a41e-ff2d-11e6-9db4-2bdfb43f6cb3.png)

Here' the code: http://codepen.io/anon/pen/VpeqoR

**Problem #2: Combobox**
When i create a combo box (like the tutorial says) i get two of them. The lower one is just there and does not do anything. The upper one works, but cuts of the text if there are too many options. When trying to scroll, it collapses. I initialized the select component in the onDeviceReady() function.
Screenshot 1:
![3](https://cloud.githubusercontent.com/assets/1476386/23499603/0df9a6c4-ff2d-11e6-8812-5c418cad1b6f.png)

Screenshot 2:
![screenshot_20170302-093551](https://cloud.githubusercontent.com/assets/1476386/23499605/0e14a12c-ff2d-11e6-80e7-ba511de61af9.png)

Here's the code: http://codepen.io/anon/pen/RprEmm

Please note, that the scrolling doesn't work always on the page where i use these input fields.

These problems still occur if i disable all other css files.

**Comment by nidhoeggr09** [comment]
Same with switches. Is there nobody who had the same or a similar problem?

![Uploading Screenshot_20170304-181110.png…]()

**Comment by fsarachu** [comment]
Select boxes are not working in a simple html page rendering on Safari (iOS 10.2.1 ). 
I opened http://materializecss.com/forms.html and select boxes didn't work even there, in the official demos.

**Comment by Dogfalo** [comment]
None of your codepen's seem to be demonstrating the problem. Please update this and I will reopen
