### ISSUE TITLE
Select not working on iPhone

### ISSUE THREAD

**Issue by steveandrews01** [Dogfalo/materialize#4306]
There seems to be a problem with select on an iPhone. In my app, when I click the select it opens as normal. When I select an option it closes but does not show the selected item. I cannot then open the select again after.

I've also tried this on the Materialize website examples and get the same problem. 

It's an iPhone 7 using Safari browser. It's working ok on Android and desktop browsers.

Is this a known problem?

**Comment by waelrammo** [comment]
+1

**Comment by Thanood** [comment]
See also https://github.com/Dogfalo/materialize/issues/3790 (including a workaround).
Additionally you could try to redirect `touchstart` events to trigger a `click` event on iOS.

**Comment by waelrammo** [comment]
@Thanood this let's you select an option that is already in the viewport, but it's not so great if you need to scroll, but can't. Do you have a fix for that?

**Comment by waelrammo** [comment]
@Thanood nevermind, I didn't see that they'd posted a fix

**Comment by tomscholz** [comment]
These issues are all duplicates:
https://github.com/Dogfalo/materialize/issues/4413
https://github.com/Dogfalo/materialize/issues/4315
https://github.com/Dogfalo/materialize/issues/4306
https://github.com/Dogfalo/materialize/issues/3715
https://github.com/Dogfalo/materialize/issues/3171
https://github.com/Dogfalo/materialize/issues/630

For the future discussion, please use this issue instead.
https://github.com/Dogfalo/materialize/issues/3790
