### ISSUE TITLE
The chip-autocomplete not responsive when first typing

### ISSUE THREAD

**Issue by morinx** [Dogfalo/materialize#4311]
I recently noticed that the chip-autocomplete consistently ignores the first keyup for 2nd+ tag and won't show the list. It doesn't happen every time, I can say about 20% of the time. I would then have to backspace what I typed and start again, and the list shows up fine.

**Comment by fega** [comment]
I'm having a similar issue in the docs
http://materializecss.com/chips.html

**Comment by Dogfalo** [comment]
Not able to reproduce, what version were you using and can you check whether it is still happening on 1.0.0-alpha.3 ?

**Comment by morinx** [comment]
Closing since I haven't seen it recently.

**Comment by Dogfalo** [comment]
Thanks
