### ISSUE TITLE
card-panel does not display correctly

### ISSUE THREAD

**Issue by lx1054331851** [Dogfalo/materialize#4313]
The problem shows as below:
![image](https://cloud.githubusercontent.com/assets/12423206/23539703/e8bd7f7a-0017-11e7-9299-ca65f1b02dee.png)

I really do not know the reason, helping me!

**Comment by lx1054331851** [comment]
The problem shows as below:
![image](https://cloud.githubusercontent.com/assets/12423206/23539395/01767fb4-0016-11e7-8f85-3a1ec500d43d.png)
 my html code is as below:
`<div class="row">
        <div class="col s12 m3 l3"><div class="card"><div class="card_image"><div class="material-placeholder"><img class="materialboxed initialized" width="100%" src="https://malong.blob.core.chinacloudapi.cn/2017ssshow/%E7%94%B7%E8%A3%85/nicole-miller-springsummer-2017-original/04_Nicole_Miller_original_nic_nyc_ss17011.jpg"></div></div><div class="card-action" <p=""><input type="checkbox" id="0.46064236697715"><label for="0.46064236697715"></label><p></p></div></div></div><div class="col s12 m3 l3"><div class="card"><div class="card_image"><div class="material-placeholder"><img class="materialboxed initialized" width="100%" src="https://malong.blob.core.chinacloudapi.cn/2017ssshow/%E7%94%B7%E8%A3%85/chanel-springsummer-2017-original/12_Chanel_original_cha_prs_ss17_034.jpg"></div></div><div class="card-action" <p=""><input type="checkbox" id="0.45801584611244"><label for="0.45801584611244"></label><p></p></div></div></div><div class="col s12 m3 l3"><div class="card"><div class="card_image"><div class="material-placeholder"><img class="materialboxed initialized" width="100%" src="https://malong.blob.core.chinacloudapi.cn/2017ssshow/%E7%94%B7%E8%A3%85/frs-for-restless-sleepers-springsummer-2017-origin/29_F.R.S._For_Restless_Sleepers_original_frs_ss17_029.jpg"></div></div><div class="card-action" <p=""><input type="checkbox" id="0.45580825542673"><label for="0.45580825542673"></label><p></p></div></div></div><div class="col s12 m3 l3"><div class="card"><div class="card_image"><div class="material-placeholder"><img class="materialboxed initialized" width="100%" src="https://malong.blob.core.chinacloudapi.cn/2017ssshow/%E7%94%B7%E8%A3%85/house-of-holland-springsummer-2017-original%20%281%29/21_House_of_Holland_original_hoh_ldn_ss17_042.jpg"></div></div><div class="card-action" <p=""><input type="checkbox" id="0.45150559022018"><label for="0.45150559022018"></label><p></p></div></div></div><div class="col s12 m3 l3"><div class="card"><div class="card_image"><div class="material-placeholder"><img class="materialboxed initialized" width="100%" src="https://malong.blob.core.chinacloudapi.cn/2017ssshow/%E7%94%B7%E8%A3%85/alexander-mcqueen-springsummer-2017-original%20%281%29/10_Alexander_McQueen_original_amq_prs_ss17_030.jpg"></div></div><div class="card-action" <p=""><input type="checkbox" id="0.44689635653721"><label for="0.44689635653721"></label><p></p></div></div></div><div class="col s12 m3 l3"><div class="card"><div class="card_image"><div class="material-placeholder"><img class="materialboxed initialized" width="100%" src="https://malong.blob.core.chinacloudapi.cn/2017ssshow/%E7%94%B7%E8%A3%85/anna-sui-springsummer-2017-original/08_Anna_Sui_original_sui_nyc_ss17_023.jpg"></div></div><div class="card-action" <p=""><input type="checkbox" id="0.44365542325476"><label for="0.44365542325476"></label><p></p></div></div></div><div class="col s12 m3 l3"><div class="card"><div class="card_image"><div class="material-placeholder"><img class="materialboxed initialized" width="100%" src="https://malong.blob.core.chinacloudapi.cn/2017ssshow/%E7%94%B7%E8%A3%85/sportmax-springsummer-2017-original/22_Sportmax_original_spo_mil_ss17_065.jpg"></div></div><div class="card-action" <p=""><input type="checkbox" id="0.44250714678929"><label for="0.44250714678929"></label><p></p></div></div></div><div class="col s12 m3 l3"><div class="card"><div class="card_image"><div class="material-placeholder"><img class="materialboxed initialized" width="100%" src="https://malong.blob.core.chinacloudapi.cn/2017ssshow/%E7%94%B7%E8%A3%85/proenza-schouler-springsummer-2017-original/35_Proenza_Schouler_original_prz_nyc_ss17_103.jpg"></div></div><div class="card-action" <p=""><input type="checkbox" id="0.44194093477201"><label for="0.44194093477201"></label><p></p></div></div></div><div class="col s12 m3 l3"><div class="card"><div class="card_image"><div class="material-placeholder"><img class="materialboxed initialized" width="100%" src="https://malong.blob.core.chinacloudapi.cn/2017ssshow/%E7%94%B7%E8%A3%85/msgm-springsummer-2017-original%20%281%29/06_MSGM_original_msgm_mln_ss17_012.jpg"></div></div><div class="card-action" <p=""><input type="checkbox" id="0.44065058666658"><label for="0.44065058666658"></label><p></p></div></div></div><div class="col s12 m3 l3"><div class="card"><div class="card_image"><div class="material-placeholder"><img class="materialboxed initialized" width="100%" src="https://malong.blob.core.chinacloudapi.cn/2017ssshow/%E7%94%B7%E8%A3%85/house-of-holland-springsummer-2017-original%20%281%29/04_House_of_Holland_original_hoh_ldn_ss17_008.jpg"></div></div><div class="card-action" <p=""><input type="checkbox" id="0.43848011529579"><label for="0.43848011529579"></label><p></p></div></div></div><div class="col s12 m3 l3"><div class="card"><div class="card_image"><div class="material-placeholder"><img class="materialboxed initialized" width="100%" src="https://malong.blob.core.chinacloudapi.cn/2017ssshow/%E7%94%B7%E8%A3%85/anna-sui-springsummer-2017-original/15_Anna_Sui_original_sui_nyc_ss17_045.jpg"></div></div><div class="card-action" <p=""><input type="checkbox" id="0.43727151749051"><label for="0.43727151749051"></label><p></p></div></div></div><div class="col s12 m3 l3"><div class="card"><div class="card_image"><div class="material-placeholder"><img class="materialboxed initialized" width="100%" src="https://malong.blob.core.chinacloudapi.cn/2017ssshow/%E7%94%B7%E8%A3%85/peter-pilotto-springsummer-2017-original/18_Peter_Pilotto_original_ppt_lon_ss17_036.jpg"></div></div><div class="card-action" <p=""><input type="checkbox" id="0.43467961515316"><label for="0.43467961515316"></label><p></p></div></div></div><div class="col s12 m3 l3"><div class="card"><div class="card_image"><div class="material-placeholder"><img class="materialboxed initialized" width="100%" src="https://malong.blob.core.chinacloudapi.cn/2017ssshow/%E7%94%B7%E8%A3%85/gucci-springsummer-2017-original/30_Gucci_original_guc_mil_ss17_090.jpg"></div></div><div class="card-action" <p=""><input type="checkbox" id="0.43194137109619"><label for="0.43194137109619"></label><p></p></div></div></div><div class="col s12 m3 l3"><div class="card"><div class="card_image"><div class="material-placeholder"><img class="materialboxed initialized" width="100%" src="https://malong.blob.core.chinacloudapi.cn/2017ssshow/%E7%94%B7%E8%A3%85/sacai-springsummer-2017-original%20%281%29/27_Sacai_original_sac_par_ss17_053.jpg"></div></div><div class="card-action" <p=""><input type="checkbox" id="0.42927998678163"><label for="0.42927998678163"></label><p></p></div></div></div><div class="col s12 m3 l3"><div class="card"><div class="card_image"><div class="material-placeholder"><img class="materialboxed initialized" width="100%" src="https://malong.blob.core.chinacloudapi.cn/2017ssshow/%E7%94%B7%E8%A3%85/ermanno-scervino-springsummer-2017-original/07_Ermanno_Scervino_original_scv_s17_015.jpg"></div></div><div class="card-action" <p=""><input type="checkbox" id="0.42923706281756"><label for="0.42923706281756"></label><p></p></div></div></div><div class="col s12 m3 l3"><div class="card"><div class="card_image"><div class="material-placeholder"><img class="materialboxed initialized" width="100%" src="https://malong.blob.core.chinacloudapi.cn/2017ssshow/%E7%94%B7%E8%A3%85/philipp-plein-springsummer-2017-original/37_Philipp_Plein_original_ppl_mms17_074.jpg"></div></div><div class="card-action" <p=""><input type="checkbox" id="0.42841842782257"><label for="0.42841842782257"></label><p></p></div></div></div><div class="col s12 m3 l3"><div class="card"><div class="card_image"><div class="material-placeholder"><img class="materialboxed initialized" width="100%" src="https://malong.blob.core.chinacloudapi.cn/2017ssshow/%E7%94%B7%E8%A3%85/marco-de-vincenzo-springsummer-2017-original/15_Marco_de_Vincenzo_original_vcz_mln_ss17_029.jpg"></div></div><div class="card-action" <p=""><input type="checkbox" id="0.42710233736589"><label for="0.42710233736589"></label><p></p></div></div></div><div class="col s12 m3 l3"><div class="card"><div class="card_image"><div class="material-placeholder"><img class="materialboxed initialized" width="100%" src="https://malong.blob.core.chinacloudapi.cn/2017ssshow/%E7%94%B7%E8%A3%85/emilio-pucci-springsummer-2017-original/28_Emilio_Pucci_original_puc_mil_ss17_082.jpg"></div></div><div class="card-action" <p=""><input type="checkbox" id="0.42644912839627"><label for="0.42644912839627"></label><p></p></div></div></div><div class="col s12 m3 l3"><div class="card"><div class="card_image"><div class="material-placeholder"><img class="materialboxed initialized" width="100%" src="https://malong.blob.core.chinacloudapi.cn/2017ssshow/%E7%94%B7%E8%A3%85/frs-for-restless-sleepers-springsummer-2017-origin/10_F.R.S._For_Restless_Sleepers_original_frs_ss17_010.jpg"></div></div><div class="card-action" <p=""><input type="checkbox" id="0.42237069944551"><label for="0.42237069944551"></label><p></p></div></div></div><div class="col s12 m3 l3"><div class="card"><div class="card_image"><div class="material-placeholder"><img class="materialboxed initialized" width="100%" src="https://malong.blob.core.chinacloudapi.cn/2017ssshow/%E7%94%B7%E8%A3%85/dolce-gabbana-springsummer-2017-original/19_Dolce_%26_Gabbana_original_dol_mms17_058.jpg"></div></div><div class="card-action" <p=""><input type="checkbox" id="0.42040218871864"><label for="0.42040218871864"></label><p></p></div></div></div>    </div>`

**Comment by menasheh** [comment]
Having the source for this would be the first step in determining the problem - be it with your code or materialize's.

**Comment by lx1054331851** [comment]
`<!doctype html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel="stylesheet" href="css/materialize.css">
    <link rel="stylesheet" href="css/style.css">
    <script src="js/jquery-3.1.1.min.js"></script>
    <script src="js/materialize.js"></script>
    <title>Document</title>
</head>

<body>
    <div class="container">
        <h1>异幻次元</h1>
        <div class="row">
            <div class="col colorblock valign-wrapper" id="cncs0862804">
                <h5>CNCS0862804</h5>
            </div>
        </div>
        <h2>秀场图片</h2>
        <div class="row">
            <div class="col s12 m3 l3">
                <div class="card">
                    <div class="card_image"><img class="materialboxed" width="100%" src="https://malong.blob.core.chinacloudapi.cn/2017ssshow/%E7%94%B7%E8%A3%85/nicole-miller-springsummer-2017-original/04_Nicole_Miller_original_nic_nyc_ss17011.jpg"></div>
                </div>
            </div>
            <div class="col s12 m3 l3">
                <div class="card">
                    <div class="card_image"><img class="materialboxed" width="100%" src="https://malong.blob.core.chinacloudapi.cn/2017ssshow/%E7%94%B7%E8%A3%85/chanel-springsummer-2017-original/12_Chanel_original_cha_prs_ss17_034.jpg"></div>
                </div>
            </div>
            <div class="col s12 m3 l3">
                <div class="card">
                    <div class="card_image"><img class="materialboxed" width="100%" src="https://malong.blob.core.chinacloudapi.cn/2017ssshow/%E7%94%B7%E8%A3%85/frs-for-restless-sleepers-springsummer-2017-origin/29_F.R.S._For_Restless_Sleepers_original_frs_ss17_029.jpg"></div>
                </div>
            </div>
            <div class="col s12 m3 l3">
                <div class="card">
                    <div class="card_image"><img class="materialboxed" width="100%" src="https://malong.blob.core.chinacloudapi.cn/2017ssshow/%E7%94%B7%E8%A3%85/house-of-holland-springsummer-2017-original%20%281%29/21_House_of_Holland_original_hoh_ldn_ss17_042.jpg"></div>
                </div>
            </div>
            <div class="col s12 m3 l3">
                <div class="card">
                    <div class="card_image"><img class="materialboxed" width="100%" src="https://malong.blob.core.chinacloudapi.cn/2017ssshow/%E7%94%B7%E8%A3%85/alexander-mcqueen-springsummer-2017-original%20%281%29/10_Alexander_McQueen_original_amq_prs_ss17_030.jpg"></div>
                </div>
            </div>
            <div class="col s12 m3 l3">
                <div class="card">
                    <div class="card_image"><img class="materialboxed" width="100%" src="https://malong.blob.core.chinacloudapi.cn/2017ssshow/%E7%94%B7%E8%A3%85/anna-sui-springsummer-2017-original/08_Anna_Sui_original_sui_nyc_ss17_023.jpg"></div>
                </div>
            </div>
            <div class="col s12 m3 l3">
                <div class="card">
                    <div class="card_image"><img class="materialboxed" width="100%" src="https://malong.blob.core.chinacloudapi.cn/2017ssshow/%E7%94%B7%E8%A3%85/sportmax-springsummer-2017-original/22_Sportmax_original_spo_mil_ss17_065.jpg"></div>
                </div>
            </div>
            <div class="col s12 m3 l3">
                <div class="card">
                    <div class="card_image"><img class="materialboxed" width="100%" src="https://malong.blob.core.chinacloudapi.cn/2017ssshow/%E7%94%B7%E8%A3%85/proenza-schouler-springsummer-2017-original/35_Proenza_Schouler_original_prz_nyc_ss17_103.jpg"></div>
                </div>
            </div>
            <div class="col s12 m3 l3">
                <div class="card">
                    <div class="card_image"><img class="materialboxed" width="100%" src="https://malong.blob.core.chinacloudapi.cn/2017ssshow/%E7%94%B7%E8%A3%85/msgm-springsummer-2017-original%20%281%29/06_MSGM_original_msgm_mln_ss17_012.jpg"></div>
                </div>
            </div>
            <div class="col s12 m3 l3">
                <div class="card">
                    <div class="card_image"><img class="materialboxed" width="100%" src="https://malong.blob.core.chinacloudapi.cn/2017ssshow/%E7%94%B7%E8%A3%85/house-of-holland-springsummer-2017-original%20%281%29/04_House_of_Holland_original_hoh_ldn_ss17_008.jpg"></div>
                </div>
            </div>
            <div class="col s12 m3 l3">
                <div class="card">
                    <div class="card_image"><img class="materialboxed" width="100%" src="https://malong.blob.core.chinacloudapi.cn/2017ssshow/%E7%94%B7%E8%A3%85/anna-sui-springsummer-2017-original/15_Anna_Sui_original_sui_nyc_ss17_045.jpg"></div>
                </div>
            </div>
            <div class="col s12 m3 l3">
                <div class="card">
                    <div class="card_image"><img class="materialboxed" width="100%" src="https://malong.blob.core.chinacloudapi.cn/2017ssshow/%E7%94%B7%E8%A3%85/peter-pilotto-springsummer-2017-original/18_Peter_Pilotto_original_ppt_lon_ss17_036.jpg"></div>
                </div>
            </div>
            <div class="col s12 m3 l3">
                <div class="card">
                    <div class="card_image"><img class="materialboxed" width="100%" src="https://malong.blob.core.chinacloudapi.cn/2017ssshow/%E7%94%B7%E8%A3%85/gucci-springsummer-2017-original/30_Gucci_original_guc_mil_ss17_090.jpg"></div>
                </div>
            </div>
            <div class="col s12 m3 l3">
                <div class="card">
                    <div class="card_image"><img class="materialboxed" width="100%" src="https://malong.blob.core.chinacloudapi.cn/2017ssshow/%E7%94%B7%E8%A3%85/sacai-springsummer-2017-original%20%281%29/27_Sacai_original_sac_par_ss17_053.jpg"></div>
                </div>
            </div>
            <div class="col s12 m3 l3">
                <div class="card">
                    <div class="card_image"><img class="materialboxed" width="100%" src="https://malong.blob.core.chinacloudapi.cn/2017ssshow/%E7%94%B7%E8%A3%85/ermanno-scervino-springsummer-2017-original/07_Ermanno_Scervino_original_scv_s17_015.jpg"></div>
                </div>
            </div>
            <div class="col s12 m3 l3">
                <div class="card">
                    <div class="card_image"><img class="materialboxed" width="100%" src="https://malong.blob.core.chinacloudapi.cn/2017ssshow/%E7%94%B7%E8%A3%85/philipp-plein-springsummer-2017-original/37_Philipp_Plein_original_ppl_mms17_074.jpg"></div>
                </div>
            </div>
            <div class="col s12 m3 l3">
                <div class="card">
                    <div class="card_image"><img class="materialboxed" width="100%" src="https://malong.blob.core.chinacloudapi.cn/2017ssshow/%E7%94%B7%E8%A3%85/marco-de-vincenzo-springsummer-2017-original/15_Marco_de_Vincenzo_original_vcz_mln_ss17_029.jpg"></div>
                </div>
            </div>
            <div class="col s12 m3 l3">
                <div class="card">
                    <div class="card_image"><img class="materialboxed" width="100%" src="https://malong.blob.core.chinacloudapi.cn/2017ssshow/%E7%94%B7%E8%A3%85/emilio-pucci-springsummer-2017-original/28_Emilio_Pucci_original_puc_mil_ss17_082.jpg"></div>
                </div>
            </div>
            <div class="col s12 m3 l3">
                <div class="card">
                    <div class="card_image"><img class="materialboxed" width="100%" src="https://malong.blob.core.chinacloudapi.cn/2017ssshow/%E7%94%B7%E8%A3%85/frs-for-restless-sleepers-springsummer-2017-origin/10_F.R.S._For_Restless_Sleepers_original_frs_ss17_010.jpg"></div>
                </div>
            </div>
            <div class="col s12 m3 l3">
                <div class="card">
                    <div class="card_image"><img class="materialboxed" width="100%" src="https://malong.blob.core.chinacloudapi.cn/2017ssshow/%E7%94%B7%E8%A3%85/dolce-gabbana-springsummer-2017-original/19_Dolce_%26_Gabbana_original_dol_mms17_058.jpg"></div>
                </div>
            </div>
        </div>
        <script>
            $(document).ready(function () {
                $('.materialboxed').materialbox();
            });
        </script>
    </div>
</body>

</html>`

**Comment by lx1054331851** [comment]
I save the source code to the below index.txt file, please help me find where is the problem? Very thankful!
[index.txt](https://github.com/Dogfalo/materialize/files/816052/index.txt)

**Comment by UVLabs** [comment]
@lx1054331851 have you tried setting a minimum height for the card element? Try setting a min height equal to the height of your tallest card.
