### ISSUE TITLE
Cannot assign to read only property 'requestAnimationFrame' of object

### ISSUE THREAD

**Issue by AkshayCloudAnalogy** [Dogfalo/materialize#4314]
While using the start template in Salesforce Aura Component i got this Error.
Please help me.
![image](https://cloud.githubusercontent.com/assets/26162018/23566479/0bcadf84-0078-11e7-895b-8b3ee0259218.png)

**Comment by acburst** [comment]
Not really too familiar with Salesforce Aura. Can you explain your situation more? Are you sure you are including the assets correctly?

**Comment by fega** [comment]
Closed due inactivity, feel free to reopen it if it is still necessary.
