### ISSUE TITLE
How to make search box magnifying glass clickable?

### ISSUE THREAD

**Issue by mewdavinci** [Dogfalo/materialize#4317]
### Description
Hello, guys, I'm trying to build a clickable magnifying search box. Can I do it with Materializecss? Or I need to add an additional code?

### Repro Steps
We can see the example in 
https://blog.google

**Comment by stsmurfy** [comment]
These are the possibilities:

[Search Bar](http://materializecss.com/navbar.html#search-docs)
**FAB to Toolbar** in [Floating section](http://materializecss.com/buttons.html#floating)

**Comment by mewdavinci** [comment]
yes, I understand.
Did you mean to combine the FAB and search bar?
Let me try...

**Comment by Dogfalo** [comment]
You'll need to add some additional code depending on what exactly you want it to do.
