### ISSUE TITLE
sideNav with fixed desktop nav doesn't work correctly

### ISSUE THREAD

**Issue by evanhdc** [Dogfalo/materialize#4318]
### Description
I'd like to make a fixed Navbar for desktop view, as well as navbar for mobile view. This is what I did
https://fiddle.jshell.net/evanhdc/v1d7fk9h/

### Repro Steps
In the above fiddler, resize browser window so the mobile navbar shows up.
Click menu on top left so the sideNav pops up.

Problem is that in mobile view, when I clicked the menu button, sideNav shows up with a sidenav-overlay that covers the entire page including the sideNav so I can't click any option.

The fiddler works fine with materializecss ver 0.97.7 but the issue starts from v0.97.8, and is still happening in v0.98.0.

In order to make sidenav-overlay to cover only the correct portion of the page, I have to remove the outer div with class "navbar-fixed" but this way, the desktop navbar is not fixed anymore. 

### Screenshots / Codepen
Add supplemental screenshots or code examples. Look for a codepen template in our Contributing Guidelines.

**Comment by b-z** [comment]
I have the same problem, while using a fixed navbar.
Maybe it is caused by the z-index.

My solution is move this <ul> out of the navbar-fixed:
`<ul class="side-nav" id="slide-out">`

**Comment by tomscholz** [comment]
These issues are all duplicates:
https://github.com/Dogfalo/materialize/issues/1664
https://github.com/Dogfalo/materialize/issues/3918
https://github.com/Dogfalo/materialize/issues/4046
https://github.com/Dogfalo/materialize/issues/4231
https://github.com/Dogfalo/materialize/issues/437
https://github.com/Dogfalo/materialize/issues/4318
https://github.com/Dogfalo/materialize/issues/3982
https://github.com/Dogfalo/materialize/issues/2879
https://github.com/Dogfalo/materialize/issues/4187

For the future discussion, please use this issue instead.
https://github.com/Dogfalo/materialize/issues/3844
