### ISSUE TITLE
Pushpin destroy doesn't work properly

### ISSUE THREAD

**Issue by qantumthemes** [Dogfalo/materialize#4320]
### Description
Calling destroy method on pushpin doesn't work, as scroll method is not unbinded after page resize.

### Repro Steps
Want to bind a pushpin('destroy') after page resizes, but is like if the ID changes and the destroy method doesn't find any pushpin scroll to disable.
The classes are removed but the "scroll" binded to the pushpin is not deleted, so even thou it goes away after calling destroy, it comes back after scrolling, dotally destroyed in some cases.

I tried to use some html data attributes to maintain the "pushpin-id" stable but is impossible. Tried to purpose a change but is ineffective.

**Comment by acburst** [comment]
What exactly is changing the pushpin id? I'm not sure I understand how it is not being able to find the pushpin plugin

**Comment by qantumthemes** [comment]
Hello!
This is the thing: if you resize the browser switching to "mobile" size, and you want to disable Pushpin for mobile, this requires to call the destroy method. Until here all good, it works, but as soon as you scroll again, the function of the pushpin which is bent to the scroll starts working again and injecting classes to the html element. It doesn't happen if you don't resize the screen, looks like he can't find the ID of the pushpin cache object.
Thank you very much for checking this out ;)

**Comment by acburst** [comment]
Do you think you can recreate your situation in a codepen?

**Comment by qantumthemes** [comment]
It would be like normal pushpin, requires to manually resize the window size and then launch pushpin destroy, then scroll the page.
You'll see pushpin elements going back to their place, then on scroll the pushpin starts again even thou was destroyed. 
I don't know if a codepen is useful as is not pure code to recreate the issue.
BTW i love materializecss, replaced bootstrap forever :D

**Comment by fega** [comment]
@qantumthemes the codepen examples are really really helpful, and a good repro steps

**Comment by fega** [comment]
Closed due inactivity, feel free to reopen it if it is still necessary.

**Comment by davidbgeek** [comment]
I'm also experiencing this. As soon as you start to scroll, pushpin returns after being removed.

**Comment by levillayer-t** [comment]
Hi all. I have the same issue. Once I resize my screen, the pushpin still affects my element even though I used " $('#element).pushpin('remove')". The trick I use is to save the children of my element once it is created for the first time, delete the element that is pinned and append another element based on the initial element.
