### ISSUE TITLE
adding materialize.css to the page hides regular checkboxs

### ISSUE THREAD

**Issue by avrahamcool** [Dogfalo/materialize#4322]
the `materialize.css` file has a section that removes the regular checkbox from the page:

```
/* Remove default checkbox */
[type="checkbox"]:not(:checked),
[type="checkbox"]:checked {
  position: absolute;
  left: -9999px;
  opacity: 0;
}
```

this causes some issues:

1) we want to use other libraries that generate html that includes regular checkboxes and we don't have a way to modify their output (or we don't want to style those checkboxes as `materialize` checkboxes).

2) the `left: -9999px;` part causes unwanted scrolling when the relative container of the checkbox has `overflow: auto;` defined.
(`position: absolute;` and `opacity: 0;` should sufice to 'eliminate' the checkbox)

removing the regular checkbox should be done only on checkboxes that we **want** to style using `materialize`, and not for all.

**Comment by Dogfalo** [comment]
See #5004
