### ISSUE TITLE
Tabs indicator issue

### ISSUE THREAD

**Issue by kevzlou7979** [Dogfalo/materialize#4323]
Hi there, 

There was an issue on tab's indicator size calculation, whenever it's parent is changing it's size / padding / margin, it seems that the indicator is not updating it's size 
![tabs-issue](https://cloud.githubusercontent.com/assets/3138071/23636202/05e023ce-030f-11e7-8332-4e7917fddbde.gif)

**Comment by acburst** [comment]
Is this a scenario that will happen commonly? There is no good way to detect changes like this. If the element is resized normally through a browser resize it will adjust. I think this is simply an edge case that we cannot cover.

What you can do though, is whenever you do change properties like this programmatically, you can call .tabs() on your tabs element to recalculate the indicator position.
