### ISSUE TITLE
Materialboxed and colunm-count

### ISSUE THREAD

**Issue by GizmoIchitzo** [Dogfalo/materialize#4324]
Hi,

I encounter a probleme with materialboxed. I have 3 colums of pictures, created with css3 : column-count.
when I click on some picture, sometime it does not appear at the good position and I can't see it.

here a exemple of the issue : http://codepen.io/anon/pen/KWNPLN

the issue occurs with the second image (in the middle)

Can I fixed it with css properties ?

**Comment by acburst** [comment]
column-count is meant for text and I'm not sure what exactly it is doing to the images. Have you tried using our grid system to create your 3 columns?

**Comment by GizmoIchitzo** [comment]
Hi,

I'm not sur you understand my goal. I wanna to 3 columns to put my picture, but i don't want "row align". 
Your grid system create row, so if one of my picture is small, there will be a blank zone.
I try css section and column-width but the result is the same. (http://codepen.io/anon/pen/GWvgVg).

Is there any way to do something like that with materialboxed ?
