### ISSUE TITLE
Is it possible to use the carousel without the rest of the js? If so, how? 

### ISSUE THREAD

**Issue by lastnoob** [Dogfalo/materialize#4325]
I don't need anything else from the materialize JS, just the carousel. Can I use it alone? If so, how?

I tried to include stuff from the carousel.js found on this repo, but obviously its not working with just that.

Any ideas how to do it?

Thanks in advance.

P.S.: I want to use materialize's carousel for various reasons:
1) all the popular carousel plugins are 40-50kbs minified, I imagine materialize's carousel is less or the same.
2) I'm already familiar with it
3) I use the CSS framework so it makes sense
4) Yes, I need to use a carousel, I didn't make the design, client wants it.

**Comment by acburst** [comment]
Our javascript files are all separated by file. You can simply just use the carousel.js file and it should work standalone. You may need to write some extra css or copy our css styles for the carousel to make it look the way it does in Materialize

**Comment by lastnoob** [comment]
Thanks @acburst  . I actually tried it before opening an issue.

So whats wrong in [this codepen?](https://codepen.io/simii/pen/ZeJyzP)

**Comment by lukecr** [comment]
@lastnoob its this line;

var namespace = Materialize.objectSelectorString($(this));

of course Materialize. doesn't exist, but i'm not knowledgeable enough to know how to fix it :(

**Comment by lastnoob** [comment]
Exactly, I tried to tinker around but no success

**Comment by oliverfriedmann** [comment]
Seems good enough to replace this line by:
`      var objectSelectorString = function(obj) {
            var tagStr = obj.prop('tagName') || '';
            var idStr = obj.attr('id') || '';
            var classStr = obj.attr('class') || '';
            return (tagStr + idStr + classStr).replace(/\s/g,'');
        };


        //var namespace = Materialize.objectSelectorString($(this));
        var namespace = objectSelectorString($(this));
`
