### ISSUE TITLE
Please just make a damn tutorial!

### ISSUE THREAD

**Issue by DarianSteyn** [Dogfalo/materialize#4327]
I have looked everywhere on how to use this damn framework. There is such a little resources/info on this thing that it's almost impossible to use.

Make a simple tutorial on how to include the files, what is needed and how to simply add a swipe function to a HTML element. It's so damn annoying because there is none of that, anywhere. I have the same two errors - Uncaught ReferenceError: Hammer is not defined - when I use the jquery version. and Cannot read property 'addEventListener' of null - when I use the normal version... I mean, HELLLO! tell us how to use this damn thing, we aren't all really experienced like you are ^_^ 

Simply saying "It’s easy to use, just include the library and create a new instance.

var hammertime = new Hammer(myElement, myOptions);
hammertime.on('pan', function(ev) {
	console.log(ev);
});"

Literally means nothing haha. Just a simple tut.. Thats it.

**Comment by tomscholz** [comment]
I don't think, it is the creators task to teach you how to use HTML, CSS, JS.
Und you have Andy questions regarding hammerjs, check out the hammerjs documentation. And actually there is a getting started guide here http://materializecss.com/getting-started.html
