### ISSUE TITLE
Carousel starting off in a weird place

### ISSUE THREAD

**Issue by LunarGem** [Dogfalo/materialize#4328]
I don't know if it's because I have it inside a tab which is hidden at the beginning (from reading around I get the impression that this could cause problems) but I'm finding that the carousel (which is just a test version with code basically just copied from the website) starts off up in the corner. If you interact with it it centers itself and switching away from that tab and back to it it works fine, but it looks pretty weird. It also gets hidden behind some other content if I add some things to the page.

Here is my Codepen: http://codepen.io/anon/pen/PpWNdV

![image](https://cloud.githubusercontent.com/assets/24980690/23717709/ee585146-0402-11e7-8dd5-ba7b108972e8.png)

The text is for reference, it's centered on the page.

Thank you for making this framework and for reading!

**Comment by acburst** [comment]
Use the onShow callback to reinitialize the carousel. Something along the lines of:
```
  $('.tabs').tabs({
    onShow: function() {
      $('.carousel').carousel();
    }
  })
```

**Comment by LunarGem** [comment]
Thanks, it seems like that would work (it works in the pen), but for some reason on my actual site it never gets run. Any idea why that might be?

**Comment by acburst** [comment]
Not sure, when I add the code snippet to your codepen it works. Are you sure you are putting it in a document ready? Where you initialize all your other components?

**Comment by LunarGem** [comment]
Silly me, I didn't put it in the document.ready. Sometimes I think I  just forget how the languages I'm coding in work 😛. Additionally, did you guys make any major changes to the tooltips? I have some branches of my project where they work and some where they don't, and the only difference I can find (that would affect the tooltips, anyway) is that I updated the Materialize version.
