### ISSUE TITLE
Drop Down isn't working as expected

### ISSUE THREAD

**Issue by tgeorge1** [Dogfalo/materialize#4331]
I am creating a dynamic tabs button format,  Dropdown is working for one time , next time dropdown functionality is not coming ,

      <ul id="dropdown" class="dropdown-content ">
        <li><a id="menu1" href="#">Admin</a></li>
        <li><a id="menu2" href="#">User</a></li>
        <li><a id="menu3" href="#">System Admin </a></li>
      </ul>
      

  
  <nav class=" menu-bar green lighten-5">
    <div class="nav-wrapper "
      <ul id="menu-bar1" >
        
        <li>
          <a class=" dropdown-button" href="#" data-beloworigin="true" data-activates="dropdown"><img src="img/icons/ic_menu_black_24dp.png" alt=""></img><span>Admin <span>
              
            </a>
        </li>
        <li ><a href="#" ng-click="nextPage('')"><span> Creation User </span> </a>
        </li>
        <li><span>|</span></li>
        <li ><a href="#"><span> Commission </span> </a>
        </li>
        <li><span>|</span></li>
        <li ><a href="#"><span> Allocate Commission </span> </a>
        </li>
        
      </ul>
        
      

      <ul id="menu-bar2" >
        
        <li>
          <a class="dropdown-button" href="#" data-beloworigin="true" data-activates="dropdown"><img src="img/icons/ic_menu_black_24dp.png" alt="" class=""></img><span>User<span></a></li>
        <li><a href="#"><span>Role Creation</span></a>
        </li>
        <li><span>|</span></li>
        <li><a href="#"><span>User Creation</span></a></li>
        <li><span>|</span></li>
        
      </ul>

      <ul id="menu-bar3" >
      
        <li>
          <a class="dropdown-button" href="#" data-beloworigin="true" data-activates="dropdown"><img src="img/icons/ic_menu_black_24dp.png" alt="" class=""></img><span>System Admin<span></a>
        </li>
        <li><a href="#"><span>Permissions </span></a>
        </li>
        <li><span>|</span></li>
        <li><a href="#"><span>Monitoring</span></a></li>
      </ul>
     

    </div>
  </nav>
</header>

<script>
  $(document).ready(function () {
    
    $("#menu-bar1").hide();
    $("#menu-bar2").hide();
    $("#menu-bar3").show();
    

    $("#menu1")
      .click(
      function (e) {
        
        $("#menu-bar2").hide();
        $("#menu-bar3").hide();
        $("#menu-bar1").show();
      });
    $("#menu2")
      .click(
      function (e) {
       
        $("#menu-bar1").hide();
        $("#menu-bar3").hide();
        $("#menu-bar2").show();
      });
    $("#menu3")
      .click(
      function (e) {
       
        $("#menu-bar2").hide();
        $("#menu-bar1").hide();
         $("#menu-bar3").show();
      });

    $(".dropdown-button").dropdown({
      inDuration: 300,
      outDuration: 225,
      constrainWidth: false, // Does not change width of dropdown to that of the activator
      hover: true, // Activate on hover
      gutter: 0, // Spacing from edge
      belowOrigin: false, // Displays dropdown below the button
      alignment: 'left', // Displays dropdown with edge aligned to the left of button
      stopPropagation: false // Stops event propagation
    });

  });
 

</script>

**Comment by acburst** [comment]
can you explain how to reproduce your issue more? Maybe a codepen that can directly reproduce it. This is very little information to go on.

**Comment by tgeorge1** [comment]
I am tring to create a dynamic tabs, on dropdown selection. I am attaching full page.Why dropdown appear only one time. 


 <!DOCTYPE html>
  <html>
    <head>
      
      <link href="http://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
       
		<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/0.98.0/css/materialize.min.css">
      
      <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    </head>

    <body>
      
		<script type="text/javascript" src="https://code.jquery.com/jquery-2.1.1.min.js"></script>
       
		<script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/0.98.0/js/materialize.min.js"></script>
		
	 
      



  
  <nav class=" menu-bar green lighten-5">
    <div class="nav-wrapper " >
      
      
      <ul id="dropdown" class="dropdown-content ">
        <li><a id="menu1" href="#">Admin</a></li>
        <li><a id="menu2" href="#">User</a></li>
        <li><a id="menu3" href="#">System Admin </a></li>
      </ul>

      <ul id="menu-bar1" >
        
        <li>
          <a class=" dropdown-button" href="#" data-beloworigin="true" data-activates="dropdown">Admin<i class="material-icons left">menu</i>
              
            </a>
        </li>
        <li ><a href="#" ng-click="nextPage('')"><span> Creation User </span> </a>
        </li>
        <li><span>|</span></li>
        <li ><a href="#"><span> Commission </span> </a>
        </li>
        <li><span>|</span></li>
        <li ><a href="#"><span> Allocate Commission </span> </a>
        </li>
        
      </ul>
        
      

      <ul id="menu-bar2" >
        
        <li>
          <a class="dropdown-button" href="#" data-beloworigin="true" data-activates="dropdown">User <i class="material-icons left">menu</i></a></li>
        <li><a href="#"><span>Role Creation</span></a>
        </li>
        <li><span>|</span></li>
        <li><a href="#"><span>User Creation</span></a></li>
        <li><span>|</span></li>
        
      </ul>

      <ul id="menu-bar3" >
      
        <li>
          <a class="dropdown-button" href="#" data-beloworigin="true" data-activates="dropdown">System Admin <i class="material-icons left">menu</i></a>
        </li>
        <li><a href="#"><span>Permissions </span></a>
        </li>
        <li><span>|</span></li>
        <li><a href="#"><span>Monitoring</span></a></li>
      </ul>
     

    </div>
  </nav>
</header>

<script>
  $(document).ready(function () {
    
    $("#menu-bar1").hide();
    $("#menu-bar2").hide();
    $("#menu-bar3").show();
    

    $("#menu1")
      .click(
      function (e) {
        
        $("#menu-bar2").hide();
        $("#menu-bar3").hide();
        $("#menu-bar1").show();
      });
    $("#menu2")
      .click(
      function (e) {
       
        $("#menu-bar1").hide();
        $("#menu-bar3").hide();
        $("#menu-bar2").show();
      });
    $("#menu3")
      .click(
      function (e) {
       
        $("#menu-bar2").hide();
        $("#menu-bar1").hide();
         $("#menu-bar3").show();
      });


    $(".dropdown-button").dropdown({
      inDuration: 300,
      outDuration: 225,
      constrainWidth: false, // Does not change width of dropdown to that of the activator
      hover: true, // Activate on hover
      gutter: 0, // Spacing from edge
      belowOrigin: false, // Displays dropdown below the button
      alignment: 'left', // Displays dropdown with edge aligned to the left of button
      stopPropagation: false // Stops event propagation
    });

  });
 

</script>

	  
	  
	  
    </body>
  </html>

**Comment by vishnu1991** [comment]
@tgeorge1 pls make a codepen by using this http://codepen.io/Dogfalo/pen/xbzPQV

**Comment by tomscholz** [comment]
Please use this [codepen](http://codepen.io/Dogfalo/pen/xbzPQV) to visualize the problem
Closed due inactivity, feel free to reopen it if it is still necessary.
