### ISSUE TITLE
Please remove the obligatory use of an id for selector in sidenav's and another components

### ISSUE THREAD

**Issue by leandroluk** [Dogfalo/materialize#4332]
> (First of all sorry for my English, Google Translator helped me)

### Description

I really like MaterializeCSS because it already implements all Google Material Design features in a simple and practical way. The problem is that I had to reformulate the entire script library for element selection based on the natural selection form of jQuery (where I can pass classes, tags, or attributes as selection ...).

I understand that as you already use jQuery that has as native code the use of the standard `document.querySelectorAll()` method, it would be more functional and would give more freedom for the developer to use MaterializeCSS.

I identified this restriction and corrected my way (so far) using the sideNav component but had already noticed this in other projects. In the case of this component, the correction was very simple and did not affect in any other part of the project as you can see below:

 >  **Note:**
 > This is an excerpt from the unnamed function and found at line 2315 of the file materialize.js and is used to implement a sideNav component.

In select menu item and catch menu selector from attribute [data-activates] i make this change:

    //before
    var menuId = $this.attr('data-activates');
    var menu = $('#' + menuId); 

    //after
    var menuSelector = $this.attr('data-activates');
    var menu = $(menuSelector); 
    // I also solved the references for the variable menuId in the rest of the function

**Comment by smileytechguy** [comment]
I like what you are doing here, and think its a great idea!

**Comment by tomscholz** [comment]
You are welcome to send a PR

**Comment by Dogfalo** [comment]
I don't see why this would be necessary to have a trigger that could refer to more than one element.

**Comment by jacobq** [comment]
The problem isn't needing a trigger to refer to more than 1 element, it's that when using component templates it is inconvenient to need to generate unique IDs in the DOM.
