### ISSUE TITLE
Select component immediately close it's popup on mousedown/touchstart .

### ISSUE THREAD

**Issue by srdjanarsic** [Dogfalo/materialize#4335]
Form > Select component immediately close it's popup on mousedown/touchstart .
Device: Nexus 5, latest Chrome.
http://materializecss.com/forms.html

I try to use select with 30 elements, When I try to scroll select's popup list, it close immediately at mousedown/touchstart  event.

**Comment by Dogfalo** [comment]
This has been fixed on master branch
