### ISSUE TITLE
Side nav getting closed when clicked outside.  

### ISSUE THREAD

**Issue by sukheja-varun** [Dogfalo/materialize#4338]
### Description
I am using side-nav but when clicked on overlay it gets closed. I want to restrict it , something similar is provided in overlay for modal with property dismissible=true

**Comment by deprilula28** [comment]
You could overlay the overlay so it doesn't send the click event, even thought that's quite hacky...

**Comment by sukheja-varun** [comment]
@deprilula28  yes I am using the same as an alternate, but I am looking for a prominent solution

**Comment by Supremex** [comment]
http://materializecss.com/side-nav.html#options

**Comment by deprilula28** [comment]
@Supremex That's not what he meant I'm pretty sure... That closes the sidenav when you click an anchor button, he wants to stop closing when you click the overlay

**Comment by Dogfalo** [comment]
As this framework is geared towards providing good user experience through material design. I don't think this is a necessary addition as it goes against the metal model users have built up using other material side navs
