### ISSUE TITLE
On removing lean-overlay, page gets fixed 

### ISSUE THREAD

**Issue by sukheja-varun** [Dogfalo/materialize#4339]
### Description
On removing lean-overlay, scroll is disabled i.e page gets fixed
` $('#multiselect').openModal({                      
                                opacity: 0,
                                ready: function () {
                                    $('.lean-overlay').remove();
                                }
                            });`

**Comment by acburst** [comment]
Why would you remove the overlay? And it looks like you are on an older version

**Comment by sukheja-varun** [comment]
@acburst I am using bottom sheet modal as select or select all modal.
behind overlay there are images which needs to be selected or deselected.

Does new version have any such feature of removing overlay ?

**Comment by fega** [comment]
@sukheja-varun, no, maybe you should implement it using !important in the CSS class of the overlay

Also the latest version use modal() instead openModal(), check the docs
