### ISSUE TITLE
Close Fab Menu on mobile when out of focus or fab button is clicked

### ISSUE THREAD

**Issue by fullhdpixel** [Dogfalo/materialize#4341]
The fab menu is fantastic on desktop, but on mobile not so. It is disrupting users from their flow when they cannot easily close the fab menu. The Fab menu should close itself on touch devices when:
- Option in the menu is clicked ('click .fixed-action-btn.active > ul > li')
- Fab menu is out of focus

I have build a [maps application](https://myroutes.io) with bootstrap and some parts of materialize css. When the menu is open the user can navigate on the map, but the fab menu is still open. I prefer it to be closed directly when it is out of focus (e.g: user is swiping)

**Comment by fullhdpixel** [comment]
Is there any programmatic way to close the fab menu with the transition included?

**Comment by acburst** [comment]
$('.fixed-action-btn').openFAB();
  $('.fixed-action-btn').closeFAB();
