### ISSUE TITLE
init.js is required for select to work - this needs to be added to cdn and docs

### ISSUE THREAD

**Issue by louking** [Dogfalo/materialize#4342]
### Description
I try to use getting started code in http://materializecss.com/getting-started.html under CDN to initialize but this is insufficient to make select work. Probably this is a problem for other components as well

### Repro Steps
I created select per http://materializecss.com/forms.html#select but only label is shown. See http://codepen.io/louking/pen/rywYqM for broken version. 

I need to include code from init.js in order to make this work. See http://codepen.io/louking/pen/dvRZgd

In my application I use google apps script, so it is inconvenient to copy init.js to my applications space. In any case, since this is required this should be documented and init.js should be added to CDN for loading.

Alternately the init.js code should be compiled into the materialize.js code.

**Comment by Dogfalo** [comment]
See the initialization documentation on the select page

**Comment by louking** [comment]
Sorry I definitely missed that in the docs. Have been scratching my head for several hours on this one, too. Thanks.

**Comment by louking** [comment]
Er, suggest moving that to the top of the select section. Maybe that applies to other sections as well.

**Comment by tomscholz** [comment]
+1 This would be definitely a better for understanding components and especially better for starters, that aren't experienced with materialize

**Comment by 1silvertiger** [comment]
There's a similar problem with the collapsible navbar. Without `init.js`, the hamburger menu does nothing.
