### ISSUE TITLE
href button get white.

### ISSUE THREAD

**Issue by qblol** [Dogfalo/materialize#4344]
### Description
href button get white when clicked rapidly and dragged

### Screenshots / Codepen
![screen shot 2017-03-14 at 3 39 35 pm](https://cloud.githubusercontent.com/assets/8578170/23892681/2e63e79e-08ce-11e7-9b59-cfcac94dc3ec.png)

**Comment by Supremex** [comment]
Who even does that? And what is exactly the problem?

**Comment by tomscholz** [comment]
Very old bug. No Fix avaliable. Duplicate of https://github.com/Dogfalo/materialize/issues/686

**Comment by tomscholz** [comment]
Or lets just say, its the same problem

**Comment by DanielRuf** [comment]
Clicking multiple times applies the wave effect multiple times and combines the white effect.

**Comment by DanielRuf** [comment]
Please test #4472.

**Comment by DanielRuf** [comment]
When moving left or right while clicking very fast starts a drag event. While dragging, the (last) ripples are still applied. The new PR should improve / fix this.

**Comment by tomscholz** [comment]
Duplicate of https://github.com/Dogfalo/materialize/issues/2667
