### ISSUE TITLE
Input field label is bouncing/jumping [IOS/Safari]

### ISSUE THREAD

**Issue by leftdead7** [Dogfalo/materialize#4345]
### Description
You tube link .... [youtube](https://youtu.be/z1b6SiB9jLo)

When the input field gets focused, the label moves up, the the end of the transition there is a small dip, which makes it look odd.
Is this the intended behaviour...

I observed the same when browsing your website in safari browser. All input fields with floating labels react the same

**Comment by leftdead7** [comment]
http://codepen.io/leftdead/pen/oZeXoN 
the above code pen can be used as reference... also when u click the login button, the error text below first input field follows the same pattern as the floating label,
i tried to use set timeout in the same code (see commented lines in script of the pen) but the amout of delay varies from 200-400 ms in different platforms and browsers

**Comment by leftdead7** [comment]
hii guys sorry if i am bugging you, but please confirm on this as soon as possible , it is a blocker for me at the moment.

Thanks in advance

**Comment by emilmr** [comment]
I'v got the same issue in Safari. Behavior is fine in Chrome. There is a little jump in the label in Firefox as well, but not as noticeable as the one in Safari.

**Comment by fega** [comment]
@leftdead7 did you find a solution for your problem?

Sadly I don't have a way to test it, I have an ubuntu

**Comment by leftdead7** [comment]
No i haven't found a solution yet. still waiting for a solution or workarond

**Comment by Dogfalo** [comment]
Fixed in 81ab9ba3654fdbaca88d0f18a1a7f7998424e725
