### ISSUE TITLE
Cannot read property 'Manager' of undefined

### ISSUE THREAD

**Issue by erdysson** [Dogfalo/materialize#4347]
### Description
Previously I was getting error "anonymous define" related to hammerjs and I read the conversations in https://github.com/Dogfalo/materialize/pull/794 and I updated the library. Now I am consistently getting "**Cannot read property 'Manager' of undefined**" error. It points out line 258 in materialize.js :
`
Hammer.Manager.prototype.emit = (function(originalEmit) {
        return function(type, data) {
            originalEmit.call(this, type, data);
            $(this.element).trigger({
                type: type,
                gesture: data
            });
        };
    })(Hammer.Manager.prototype.emit);
`

I am using it with requirejs and sharing the related part of the config file :
`
paths: {
        // libs
        "angular": "lib/angular/angular",
        "angularAMD" : "lib/angularAMD/angularAMD",
        "angular-ui-router": "lib/angular-ui-router/angular-ui-router",
        "angular-file-upload": "lib/angular-file-upload/angular-file-upload",
        "angular-animate": "lib/angular-animate/angular-animate",
        "angular-translate": "lib/angular-translate/angular-translate",
        "angular-sanitize": "lib/angular-sanitize/angular-sanitize",
        "jquery": "lib/jquery/jquery",
        "materialize": "lib/materialize/materialize",
        "hammerjs": "lib/hammer/hammer",
        "picker": "lib/date-picker/picker",
        "picker-date": "lib/date-picker/picker.date",
        "pub-sub": "lib/pub-sub/pubsub",
        "emojione": "lib/emojione/emojione",
    },
    // modules that does not support AMD out of the box, put it in a shim
    shim: {
        "jquery": {
            exports: "$"
        },
        "angular": {
            deps: ["jquery"],
            exports: "angular"
        },
        "angular-ui-router": ["angular"],
        "angularAMD": ["angular"],
        "hammerjs": ["jquery"],
        "picker": ["jquery"],
        "picker-date": ["jquery"],
        "materialize": ["jquery", "hammerjs", "picker", "picker-date"],
        "angular-file-upload": ["angular"], 
        "angular-animate": ["angular"],
        "angular-translate": ["angular"],
        "angular-sanitize": ["angular"]
    },
`

**Comment by tomscholz** [comment]
Where you able to reslove the problem?

**Comment by tomscholz** [comment]
Closed due inactivity. Feel free to reopen it, if it's still necessary.

**Comment by mayankkataria** [comment]
I'm facing the same problem. How you fixed this issue?

**Comment by mayankkataria** [comment]
Ok I solved this issue by running command ```npm i --save-dev @types/hammerjs``` and adding ```import * as hammer from 'hammerjs';``` in code.
