### ISSUE TITLE
.col is adding extra line height

### ISSUE THREAD

**Issue by mhamri** [Dogfalo/materialize#4348]
### Description
columns(.col) is adding extra line at the bottom of an image 

### Repro Steps
http://codepen.io/anon/pen/evEVzr

`<div class="col m7" >`

if i add a line height to the column the empty line will remove 
http://codepen.io/anon/pen/JWypKx

`<div class="col m7" style="line-height: 0;">`

**Comment by acburst** [comment]
This is just how display: inline elements are. Make your image display: block and it should work. Or you can just add the z-depth-4 class to the image directly.
