### ISSUE TITLE
Collapsible close menu

### ISSUE THREAD

**Issue by vinibiten** [Dogfalo/materialize#4352]
I'm using two menus with collapsible. 
One of them is on a hiddendiv and just show when the site opens on a small device.
I did a method that triggers the click of the corresponding collapsible header on the other menu when this one is clicked, just to make the menus equal.

But, when I trigger the click and the menu is hidden, the closing doesn't work.

I found the code that is my problem:

```javascript
 // Close previously open accordion elements.
$panel_headers.not(object).parent().children('.collapsible-body').stop(true,false).each(function() {
    if ($(this).is(':visible')) {
       $(this).slideUp({
...
}
```

If I comment this "IF" clause, it works fine. 

Why do I have to know if the element body is visible? I'm doing a lot of tests without this clause, and everything is ok

**Comment by acburst** [comment]
could you make a codepen to more clearly demonstrate the problem?

**Comment by vinibiten** [comment]
http://codepen.io/anon/pen/XMGomx

Open the menu items, after click change button

**Comment by NonameSLdev** [comment]
@vinibiten It's unclear to me what you're trying to achieve here and what exactly is the problem.

**Comment by vinibiten** [comment]
The problem is when I have Two menus in my system
When I click and open one, the other one that is hidden doesn't have the same behavior. If a user accesses a page that shows this other menu, the collapses will be disorganized (never close the collapse-body, just open)

$panel_headers.not(object).parent().children('.collapsible-body').stop(true,false).each(function() {
if ($(this).is(':visible')) {

Just because of this part of the code.

I have to do two menus working equals

**Comment by vinibiten** [comment]
are There Some solution for this?

**Comment by Dogfalo** [comment]
Your codepen example isn't working and we are having a hard time understanding the issue. Please create a working codepen

**Comment by drown08** [comment]
Hi,

Vinibiten tried to explain that when a collapsible component is in a hidden block, the follow statement :
``if ($(this).is(':visible')) {`` couldn't work. It's make sens.

I think this case was not planned
