### ISSUE TITLE
Carousel inside Collapsible shows jumbled images until the first click

### ISSUE THREAD

**Issue by Masum06** [Dogfalo/materialize#4353]
When put inside a collapsible-body, the carousel doesn's behave as it is supposed to unless the carousel div is clicked for the first time. Exception is when the collapsible-header is put to .active, it displays fine. 
http://codepen.io/masum006/pen/xqXWKo
![image](https://cloud.githubusercontent.com/assets/14367438/23975177/78f12416-0a09-11e7-9e34-16f6c4e4b835.png)

**Comment by Masum06** [comment]
@acburst Could you please look into it?

**Comment by acburst** [comment]
You should use the callbacks in the collapsible plugin. 

$('.collapsible').collapsible({
    onShow: function() {
      $('.carousel').carousel();
    }
  })

**Comment by Masum06** [comment]
Thank you so much @acburst ! It solved the issue. I have another problem regarding Material box inside carousel. I am posting an issue in a minute. Please look into that as well.
And again thank you for materializing this AMAZING framework.
