### ISSUE TITLE
Material box zoomes to a side inside carousel

### ISSUE THREAD

**Issue by Masum06** [Dogfalo/materialize#4355]
I have applied material box property inside carousel images. But when any other image, except for the centered one in the carousel is clicked, the zoomed "material-placeholder" div goes to one side, instead of the middle. (Left side if the right image of carousel is clicked, and Right side if the left image is clicked)
http://codepen.io/masum006/pen/QpqBWa

I tried to implement the .materialbox class only when an item is on center, but the .materializebox didn't do its work. Almost all JQuery or JS solution I tried have failed.

**Comment by Masum06** [comment]
@acburst Could you please look into this as well. Thanks in advance!

**Comment by Supremex** [comment]
Well the slider isn't built for using Materialboxed with it. I would suggest using a different slider.

**Comment by acburst** [comment]
Added some extra classes that will help with the materialbox / carousel compatibility

in 29e4333
