### ISSUE TITLE
Materialize.updateTextFields() in shadow DOM

### ISSUE THREAD

**Issue by Jeffrey04** [Dogfalo/materialize#4356]
For `select` element we can call the method `material_select()` to initialize the widget, it would be nice if text-fields has an equivalent method too. I am trying to use materialize text fields within a shadow DOM, however I couldn't get `Materialize.updateTextFields()` to work properly within the shadow DOM because the selector within the method uses the parent document as the context.

**Comment by Dogfalo** [comment]
You will have to run the method once the input field is in the DOM because it relies on HTML5 browser validation to work properly
