### ISSUE TITLE
Shadow animation glitch using hoverable helper on chrome 58.0.3029.19 beta (64-bit) Windows 10

### ISSUE THREAD

**Issue by BlueInt32** [Dogfalo/materialize#4357]
When hovering an hoverable element on Chrome 58.0.3029.19 beta (64-bit) Windows 10, the shadow animation has a bad rendering. See example below occuring on materializecss website ([helpers page](http://materializecss.com/helpers.html))
This issue does not occur on recent versions of Firefox nor Edge. 

Sorry if this isn't an obvious issue with materializecss directly but I thought it was worth mentionning.

![giphy](https://cloud.githubusercontent.com/assets/2920038/24032224/253de3f2-0ae7-11e7-91ce-101f50912477.gif)

**Comment by Supremex** [comment]
Don't use the beta version?
