### ISSUE TITLE
Horizontal cards with image aren't placed properly

### ISSUE THREAD

**Issue by Supremex** [Dogfalo/materialize#4358]
### Description
Images in horizontal cards don't stay in place.
Happens on Safari, Android & Samsung browser as far as I've seen.

Link to one of the pages:
http://www.leukzwembad.com/sauna

![screenshot_20170316-125330](https://cloud.githubusercontent.com/assets/12481417/24043656/f2221d18-0b17-11e7-872c-ae4e110078b3.jpg)

**Comment by fega** [comment]
Your web page looks okay, 
Could you check if this is a browser related bug?

**Comment by tomscholz** [comment]
Closed due inactivity and missing feedback. Feel free to reopen it, if it's still necessary.
