### ISSUE TITLE
Responsive grid not responsive on print devices

### ISSUE THREAD

**Issue by olivierdalang** [Dogfalo/materialize#4359]
### Description
When printing a page, the responsive layout doesn't work. The layout is the same as on a small screen, even if the paper size is much bigger.
Changing paper from landscape to portait won't have any effect, while a responsive layout is also a great idea for prints as well.

From what I understood, the problem can be easily fixed by changing `@media only screen and (max-width: 992px) { ... } ` to `@media (max-width: 992px) { ... }` but I'm pretty sure this was there for a good reason.

### Repro Steps
Create a responsive grid. Print it through chrome : it will print with the small-screen layout.

**Comment by DanielRuf** [comment]
Afaik this is totally normal. Try setting some print stylesheets which set the width of the body to your desired width.
