### ISSUE TITLE
scale-transition with scale-out/scale-in not working within .halfway-fab

### ISSUE THREAD

**Issue by omensinger** [Dogfalo/materialize#4360]
### Description
The scale-transition effect using scale-out or scale-in does not work if the FAB is positioned with class halfway-fab, as seen in http://materializecss.com/cards.html.

### Repro Steps
Add class `scale-transition` to the FAB of the card in http://materializecss.com/cards.html, section "FABs in Cards", add `scale-out`, then remove `scale-out` and add `scale-in`, you will see no transition effect. Remove class `halfway-fab` and apply the classes again. Ok, the button is not positioned as desired, but the transition will work.

See also http://codepen.io/Chocoliver/pen/dvJyrM.

Maybe there is a workaround for positioning?

Thank you in advance!

**Comment by acburst** [comment]
Fixed in f4693a9

**Comment by omensinger** [comment]
Thank you very much for your fast reply! Let's test it...

**Comment by tomscholz** [comment]
Please close if you can confirm, that the fix is working

**Comment by omensinger** [comment]
It works like a charm, thank you very much!
