### ISSUE TITLE
Toast just not output HTML correctly.

### ISSUE THREAD

**Issue by Script47** [Dogfalo/materialize#4362]
### Description
If you add `HTML` to a toast, it does not add the spaces in correctly and merges the text either side of a tag.

### Live Example

[Example](http://codepen.io/anon/pen/jBYQRx)

### Screenshot

[Screenshot](https://gyazo.com/665cccadf71572290bf496d6e099a857)

**Comment by Dogfalo** [comment]
This is the behavior of adding HTML using javascript: http://stackoverflow.com/questions/10474696/how-to-preserve-whitespace-in-dynamically-added-javascript-dom-element
