### ISSUE TITLE
Waves effect does not fill up the whole height

### ISSUE THREAD

**Issue by itggot-arvid-nilber** [Dogfalo/materialize#4366]
### Description
Hi. I tried to add the waves-effect to a footer, but it doesn't fill up the whole height... 

### Repro Steps
Just click on any tab

### Screenshots / Codepen
http://codepen.io/avveawesome/pen/ZeroGm

**Comment by Dogfalo** [comment]
This is because the <a> tag you placed it on does not fill the whole height.

**Comment by itggot-arvid-nilber** [comment]
@Dogfalo Dont understand, how to fix?

**Comment by siburny** [comment]
Basically the height of `li` tags are smaller then the height of `ul` container. You just need to "float" `li` with `float:left;`
