### ISSUE TITLE
[Question] Autocomplete criteria for chips

### ISSUE THREAD

**Issue by JCarlosR** [Dogfalo/materialize#4367]
### Description
![question](https://cloud.githubusercontent.com/assets/3101238/24121606/e12d86ca-0d86-11e7-8ecb-04142c14b0f9.JPG)

When a user is looking for the "TOS" option, the autocomplete shows that option at the end.
There is a way to show "TOS" before "CETOSIS" when the search text is "TOS"?

### Screenshots / Codepen
Codepen to demonstrate my issue:
https://codepen.io/jcarlos17/pen/xqYzzX

Please give me some ideas to fix it.
Thank you in advance.

**Comment by fega** [comment]
I agree that that TOs should be the first in the list, followed with TOs cronica.

**Comment by DanielRuf** [comment]
Some weight calculation would be good. The results are currently alphabetically ordered. We have to calculate position of first match (from the start of the string), the length of the match and the length of the full string where the match is in.

**Comment by fega** [comment]
Or maybe a sort method could be provided in favor of more flexibility

**Comment by DanielRuf** [comment]
This is the sort method what I described (how it should work). The current sorting is what you can do with the native `sort()` methods for arrays ;-)

**Comment by fega** [comment]
I was talking about something like
```
$('.chips-autocomplete').material_chip({
    autocompleteOptions: {
      data: {
        'Apple': null,
        'Microsoft': null,
        'Google': null
      },
     sort: function(){
          //some code here.
     }
  });
```

**Comment by DanielRuf** [comment]
To overwrite or set a sort method?

Most developers and users probably await that libraries and frameworks have some sorting already included (which can be overwritten using some configuration like in your code example).

But the approach with your code example is definitely a good idea (to set / overwrite the sort method) and in the right direction.

**Comment by fega** [comment]
To overwrite it, the weight calculation should be set as default :smile:

**Comment by acburst** [comment]
Added compare function as an option for v1 in bf24cb7d
