### ISSUE TITLE
Tooltip is not working in materialize

### ISSUE THREAD

**Issue by prachi708** [Dogfalo/materialize#4369]
<div class="input-field col s12 m12 l12">
           
               <p>
                      <input name="CC1" type="radio" id="CC1"  value="CS"/>
                      <label for="err" style="font-size: smaller">CS</label>
                     
                      <a style="font-weight:bold "  class="btn tooltipped" data-position="right" id="err" data-delay="50" data-tooltip="I am tooltip"> </a>
              </p>
           </div>

CSS
.material-tooltip {
    padding: 5px 20px 20px;
    border-radius: 10px;
    background: rgba(37, 36, 36, 0.9);

    overflow: visible;

 
  
}

.material-tooltip .backdrop {
    display: none !important;
}

.material-tooltip:after {
    position: absolute;
    content: " ";
    top: 47.5%;
    left: 0%;
    margin-left: -12%;
    width: 0;
    height: 0;
    border-style: solid;
    border-width: 13px 0px 20px 13px;
    border-color: rgba(37, 36, 36, 0.9) transparent transparent transparent;

    
    border-top: 12px solid transparent;
    border-bottom: 12px solid transparent;
    border-right: 12px solid rgba(37, 36, 36, 0.9);  

}

SCRIPT
<script>
txt="Error";
	
  $(document).ready(function(){
    $('.tooltipped').tooltip({delay: 50, html : true});
    var anchorElement = $('#err');
    anchorElement.attr('data-tooltip', txt);
    anchorElement.tooltip();
  });
</script>

It is working fine in JSFiddle but not in my main code

**Comment by acburst** [comment]
If it is working in a jsfiddle and not your main code you should look into how you are calling your dependencies. Are you sure you don't have any errors?

**Comment by Nohinn** [comment]
In addition to what @acburst has said. Are you using any other UI framework that might be conflicting the tooltip function? like jQueryUI, ...

**Comment by CorentinMic** [comment]
I can't get tooltips to work neither. It was working for me in version 0.97.7 but when I change the materialize.js to version 0.98.1 tooltips are not working (no error).

**Comment by fega** [comment]
@prachi708 and @CorentinMic Please provide a codepen, is the best way to see what is exactly happening and how could be resolved

**Comment by CorentinMic** [comment]
Here is the codepen with the 0.98.1 version, it's not working: https://codepen.io/anon/pen/xqvJPO
If you change the js source with 0.97.8 version, it's working : https://codepen.io/anon/pen/QpeBmo

**Comment by CorentinMic** [comment]
After multiples attempts, I figured out that it was my sass command to update the css file in the new version that hadn't worked. So I was using the old version css file. Tooltips are working in 0.98.1. Sorry for the inconvenience.
