### ISSUE TITLE
Gray overlay on collapsible element on iOS on click

### ISSUE THREAD

**Issue by chris-ti8m** [Dogfalo/materialize#4370]
### Description
I have noticed a gray overlay over the collapsible element on iOS. The overlay does not appear with every click. The overlay remains for a short moment and then disappears. On desktop browsers like Chrome or FireFox, there is no such overlay present. 

### Repro Steps
GoTo [collapsible site](http://materializecss.com/collapsible.html) on materializecss.com on an iOS device. Open and close the collapsible element several times. You may notice the gray overlay, which appears for a split second over the element.

**Comment by DanielRuf** [comment]
Sounds like the `-webkit-tap-highlight-color` issue.

Can you make a codepen and add the code
```CSS
-webkit-tap-highlight-color: rgba(0,0,0,0);
```
so we can have a reproducible test and fix this?

See https://css-tricks.com/snippets/css/remove-gray-highlight-when-tapping-links-in-mobile-safari/

**Comment by chris-ti8m** [comment]
Hi Daniel
It is indeed the -webkit-tap-highlight-color. Thank you very much for your support!

**Comment by DanielRuf** [comment]
@fega do we have a PR which fixes this? I am not sure anymore.

**Comment by DanielRuf** [comment]
@chris-ti8m please reopen until this is also fixed in the master branch.
