### ISSUE TITLE
Selected on mobile

### ISSUE THREAD

**Issue by hainguyenhd** [Dogfalo/materialize#4373]
Thank you for updated! v0.98.1.
I downloaded and tested on my site. But seems not good.
The value is changed but the text not show. It seems is overlayed.

**Comment by acburst** [comment]
Please add a codepen example

**Comment by hainguyenhd** [comment]
Hi acburst,
Sorry. It only does not show on mobile. I tested on Iphone 4,5.
It does not show text (placeholder and changed value), always blank. But when i submited it still send new value. 
I hope you can understand. :)

**Comment by acburst** [comment]
Are you talking about the select component? I'm not really sure which component we are talking about.

**Comment by hainguyenhd** [comment]
Hi acburst ,
I updated the latest css code. It is working fine. 
Sorry for that and thank you so much!

**Comment by tomscholz** [comment]
![image](https://cloud.githubusercontent.com/assets/20381749/24308029/10f7f44e-10cf-11e7-9d03-a98ac8066d21.png)
![image](https://cloud.githubusercontent.com/assets/20381749/24308028/10f68456-10cf-11e7-9f46-838b7a22739e.png)
This is still kind of an issue to me. iPhone 5s IOS 9.3.4
