### ISSUE TITLE
Dropdown is not opened when clicked on icon, only on text.

### ISSUE THREAD

**Issue by jeroenqui** [Dogfalo/materialize#4376]
### Description
Dropdown is not opened when clicked on icon, only on text.

### Repro Steps
http://materializecss.com/navbar.html#navbar-dropdown

### Screenshots / Codepen
http://codepen.io/Dogfalo/pen/xbzPQV

**Comment by hainguyenhd** [comment]
You can set :
dropdown({stopPropagation: true});

**Comment by jeroenqui** [comment]
Excellent! Thanks a lot!

**Comment by jeroenqui** [comment]
It was not the way it should be, but already fixed in https://github.com/Dogfalo/materialize/commit/42051a56d2a35bdd8fbdffab739ee64859b186d4
