### ISSUE TITLE
Modal alignment in IE

### ISSUE THREAD

**Issue by carlosperate** [Dogfalo/materialize#438]
Modals are aligned to the left of the page when opened in IE (tested in IE11):

![modal](https://cloud.githubusercontent.com/assets/4189262/5698681/05c6891a-9a0b-11e4-98e8-1a843d75c51d.png)

Also, as a small note, I believe the material design specs indicate to have the affirmative action to the right: http://www.google.co.uk/design/spec/components/dialogs.html#dialogs-specs

**Comment by Dogfalo** [comment]
I will look into this. Thanks for alerting us.

**Comment by acburst** [comment]
fixed in c471dd4d5321fb604eba219ceabe05e6cbada99a

**Comment by acburst** [comment]
Fixed in 493ac5226e54374800c1bd6f1a5b99ae827f15b9
