### ISSUE TITLE
Listed items are broken in official Web-Site (materializecss.com)

### ISSUE THREAD

**Issue by OnrCan** [Dogfalo/materialize#4381]
In official web-site, when I write something in search-box, suggested pages are listed horizontally! Anyone faces also or just me ?
![screenshot from 2017-03-23 16-16-02](https://cloud.githubusercontent.com/assets/26151331/24249487/259669ec-0fdc-11e7-9f2c-d6ab784d2e81.png)

**Comment by Native-Coder** [comment]
I'm experiencing the same issue. It was working earlier this week. Strange.
