### ISSUE TITLE
@Html.CheckboxFor not working with materialize

### ISSUE THREAD

**Issue by Tripalio** [Dogfalo/materialize#4382]
Hello, 

I'm working with ASP.NET and Materialize but when i create a checkbox with razor syntax it's not working. I made this  : 

                                @Html.CheckBoxFor(m => m.YesNo)
                                @Html.LabelFor(m => m.YesNo)

And nothing appeared ! In the same project but in another view i've made the same and added this script to make it work : 

    $('input:hidden').each(function (index, element) {
        $(element).appendTo($(element).parent());
    });

Anyway this is not working on my new view, even with the script ! 

So ... What's wrong ?

**Comment by acburst** [comment]
What html does that compile to? not very familiar with razor
