### ISSUE TITLE
Toast has different width during appearing

### ISSUE THREAD

**Issue by dima74** [Dogfalo/materialize#4385]
### Description
I run `Materialize.toast(message, 4000);`, where message is a long string (50 symbols). Toast appears on the screen. For a very short time toast is a little wider then necessary. Then toast width become normal. It is not beautiful, so I expect that toast should have the same width all time.

### Repro Steps
http://codepen.io/dima74/pen/MpXwPN
In this codepen I print toast width immediately after toast appears, and after one second. I received: 375px and 320px.

### Screenshots / Codepen
Please, watch these video in slowmotion mode (speed 0.25): https://youtu.be/SGhrD1fCj9A

Here is screenshots from video. They show, that toasts have different width.
![image](https://cloud.githubusercontent.com/assets/6505554/24268509/0fb202c4-101f-11e7-8cfd-ad5b0b11300e.png)
![image](https://cloud.githubusercontent.com/assets/6505554/24268527/1858f5b8-101f-11e7-9ead-31f5f8c1fc70.png)

I use Chrome 57 on linux.
Thank you for materialize, thank if answer something!

**Comment by Dogfalo** [comment]
Is this happening for you if you trigger it on the materialize website? When I ran the code pen, it only showed a 4px difference

**Comment by dima74** [comment]
No, it isn't. I noticed, that problem is only with first toast on page, second and every next toast will have the same width during appearing. In Chrome bug is very reproducible (on codepen), widths differ about 50px almost every time.

**Comment by NonameSLdev** [comment]
@dima74 Perhaps it shows the same widths because you're using the generic `.toast` selector for all toasts? 
I tested it in Firefox **and** Chrome it's only 4px, same as @Dogfalo 's result.

**Comment by dima74** [comment]
I realized the problem. If I show toast in the beggining of the page loads, when fonts doesn't load yet, then toast text will have default browser font (DejaVu Sans Light in my case). And DejaVu Sans Light is a little more then Roboto Light (which is default Materialize font), so toast will have a little more width while appearing, until Roboto Light font loads. I think nothing can be done with this.

**Comment by dima74** [comment]
And there is another problem: Materialize for some reason loads Roboto-Light.woff2 not in the beginning of page loads, but when i show toast. Please, ses codepen: http://codepen.io/dima74/pen/jmBJKZ in developer tools. Page loads in about 5 seconds, but Roboto-Light.woff2 loads only at ten second, that is when i show toast. Any ideas how to fix this?

![image](https://cloud.githubusercontent.com/assets/6505554/25554199/d8c0f716-2ccf-11e7-8bf2-0071a36608ff.png)

**Comment by Dogfalo** [comment]
This is just because it is loading through the CDN I think, if you download it and use it in your project it wont happen

**Comment by dima74** [comment]
OK, thanks, but it is sadly.

**Comment by Dogfalo** [comment]
not happening on http://materializecss.com/

**Comment by dima74** [comment]
OK, thank you
