### ISSUE TITLE
Glitched Checkboxes.

### ISSUE THREAD

**Issue by mrzack506** [Dogfalo/materialize#4386]
### Description
Add a detailed description of your issue.
I **am** using for labels.
https://streamable.com/ed5a7
### Repro Steps
Layout the steps to reproduce your issue.
Created this:
![db](https://cloud.githubusercontent.com/assets/19736068/24270949/88e37dee-0fed-11e7-9769-045c0044c43f.PNG)

**Comment by Dogfalo** [comment]
must have unique ID's
