### ISSUE TITLE
Left Side and Right Side Menu and Center Logo are New Functionality Added

### ISSUE THREAD

**Issue by jajaljay** [Dogfalo/materialize#4388]
### Description
Add a detailed description of your issue.

### Repro Steps
Layout the steps to reproduce your issue.

Use this Codepen to demonstrate your issue. http://codepen.io/Dogfalo/pen/xbzPQV

### Screenshots / Codepen
Add supplemental screenshots or code examples. Look for a codepen template in our Contributing Guidelines.

**Comment by acburst** [comment]
Please fill out the issue template with relevant information
