### ISSUE TITLE
One New Added Suggestion Your Website Search Box Button added

### ISSUE THREAD

**Issue by jajaljay** [Dogfalo/materialize#4389]
### Description
Add a detailed description of your issue.

### Repro Steps
Layout the steps to reproduce your issue.

Use this Codepen to demonstrate your issue. http://codepen.io/Dogfalo/pen/xbzPQV

### Screenshots / Codepen
Add supplemental screenshots or code examples. Look for a codepen template in our Contributing Guidelines.

**Comment by acburst** [comment]
Do you realize you just posted a blank template issue?
