### ISSUE TITLE
Gallery Expand as a function (which's inside a carousel-wrapper)

### ISSUE THREAD

**Issue by matikbird** [Dogfalo/materialize#4392]
### Description
Hi.
I have a problem, and I can't seem to find my way out of this.

I would like to call gallery expand as a function, and not as an event listener; such as..
function(title, description, price) {
......
}

I don't quite understand where exactly you are opening the image with all it's contents in a full width/heigh modal; I could really use some helps guys.

### Repro Steps
https://mrkapl.science/mutual
There, in the carousels.
Works like a charm in the end, but I can't write that part inside a carousel item, like so:
`<div class="carousel-wrapper">
                  <div class="t" style="height: 250px;">
                    <a class="carousel-item gallery-expand" href="#one!"><img src="https://cdn.shopify.com/s/files/1/1775/8583/t/1/assets/geometric-sun.jpg?8426035549349607549" ></a>
                    <a class="carousel-item" href="#two!"><img src="https://cdn.shopify.com/s/files/1/1775/8583/t/1/assets/geometric-maze.jpg?8426035549349607549" ></a>
                    <a class="carousel-item" href="#three!"><img src="https://cdn.shopify.com/s/files/1/1775/8583/t/1/assets/geometric-ice.jpg?8426035549349607549" ></a>
                    <a class="carousel-item" href="#four!"><img src="https://cdn.shopify.com/s/files/1/1775/8583/t/1/assets/geometric-cave.jpg?8426035549349607549" ></a>
                    <a class="carousel-item" href="#five!"><img src="https://cdn.shopify.com/s/files/1/1775/8583/t/1/assets/geometric-grapefruit.jpg?8426035549349607549" ></a>
                  </div>
                </div>`

This would be the code:
```
 <div class="d hx hf gu gallery-item gallery-expand ce polygon">
            <div class="gallery-curve-wrapper">
              <a class="gallery-cover gray">
                <img class="responsive-img" src="https://cdn.shopify.com/s/files/1/1775/8583/t/1/assets/geometric-sun.jpg?8426035549349607549" alt="placeholder" >
              </a>
              <div class="gallery-header">
                <span>Sun</span>
              </div>
              <div class="gallery-body">
                <div class="title-wrapper">
                  <h3>Sun</h3>
                  <span class="gk">$9.99</span>
                </div>
                <p class="fi">
Literally venmo before they sold out, DIY heirloom forage polaroid offal yr pop-up selfies health goth. Typewriter scenester hammock truffaut meditation, squid before they sold out polaroid portland tousled taxidermy vice. Listicle butcher thundercats, taxidermy pitchfork next level roof party crucifix narwhal kinfolk you probably haven't heard of them portland small batch.</p>
                <p class="fi">
Ea salvia adipisicing vegan man bun. Flexitarian cupidatat skateboard flannel. Drinking vinegar marfa you probably haven't heard of them consequat post-ironic, shabby chic williamsburg raclette vaporware readymade selfies brunch. Venmo selvage biodiesel marfa. Tbh literally 3 wolf moon, proident elit raclette chambray consequat edison bulb four loko accusamus. Semiotics godard eiusmod, ex esse air plant quinoa vaporware selfies keytar. Actually yuccie ennui flannel single-origin coffee, williamsburg cardigan banjo forage pug distillery tumblr hexagon vinyl occaecat.</p>

                <div class="carousel-wrapper">
                  <div class="t">
                    <a class="carousel-item" href="#one!"><img src="https://cdn.shopify.com/s/files/1/1775/8583/t/1/assets/geometric-sun.jpg?8426035549349607549" ></a>
                    <a class="carousel-item" href="#two!"><img src="https://cdn.shopify.com/s/files/1/1775/8583/t/1/assets/geometric-maze.jpg?8426035549349607549" ></a>
                    <a class="carousel-item" href="#three!"><img src="https://cdn.shopify.com/s/files/1/1775/8583/t/1/assets/geometric-ice.jpg?8426035549349607549" ></a>
                    <a class="carousel-item" href="#four!"><img src="https://cdn.shopify.com/s/files/1/1775/8583/t/1/assets/geometric-cave.jpg?8426035549349607549" ></a>
                    <a class="carousel-item" href="#five!"><img src="https://cdn.shopify.com/s/files/1/1775/8583/t/1/assets/geometric-grapefruit.jpg?8426035549349607549" ></a>
                  </div>
                </div>
              </div>
              <div class="gallery-action">
                <a class="btn-floating btn-large waves-effect waves-light"><i class="material-icons">add_shopping_cart</i></a>
              </div>
            </div>
          </div>


```
### Screenshots / Codepen
URL: https://mrkapl.science/mutual

Screenshot without the gallery expand thing:
![screenshot from 2017-03-24 14-50-02](https://cloud.githubusercontent.com/assets/12424545/24306972/334d83c0-10a1-11e7-9d3d-e1ba3abecfb4.png)

Here's with the above code replacing just the <img> tag, inside the <a> tag:
![screenshot from 2017-03-24 14-53-04](https://cloud.githubusercontent.com/assets/12424545/24307117/aba072ba-10a1-11e7-9213-c6dbba98f27b.png)

As you can see, no more slider. Only one picture shows up. That's why I'm thinking on a function, instead of an event bind.
Oh, and let's go to the interest part. Let's click at it, and see what's happens.
![screenshot from 2017-03-24 14-55-40](https://cloud.githubusercontent.com/assets/12424545/24307204/f7635960-10a1-11e7-818e-90a531b062b7.png)

I tried everything I could, and I keep trying,
I could really use some help guys, 
thanks in advance!

**Comment by acburst** [comment]
We want to keep the theme support separate from our official repository. If you buy the theme you can join the private theme support repo.
