### ISSUE TITLE
FeatureDiscovery code examples don't work together because of different css class names

### ISSUE THREAD

**Issue by vladimir-dobrovolsky** [Dogfalo/materialize#4395]
### Description
As stated: in HTML example element's css class is 'tap-target', but in jQuery example it's 'tapTarget'.

### Repro Steps
http://materializecss.com/feature-discovery.html

**Comment by tomscholz** [comment]
What do you mean with "FeatureDiscovery code examples don't work together because of different css class names" ? With what doesn´t it work?

**Comment by tomscholz** [comment]
Ahh I get it. I fixed it here: https://github.com/Dogfalo/materialize/pull/4408

**Comment by tomscholz** [comment]
Merged
