### ISSUE TITLE
Right-aligned material boxed images don't pop up from their location in the page

### ISSUE THREAD

**Issue by MastaBaba** [Dogfalo/materialize#4398]
### Description
Right-aligned material boxed images don't pop up from their location in the page.

### Repro Steps
See https://inzim.com/s/ and filter on Polio (use the hamburger menu to select a category) to retrieve some stories with pictures that are right-aligned.

**Comment by acburst** [comment]
When you are using materialbox, try not to add to many properties to the image itself. If you wrap the image in a right floated wrapper it should work.

**Comment by MastaBaba** [comment]
Thanks. A bit of a band-aid solution, but good enough for me.
