### ISSUE TITLE
The hidden elements padding occupy space. 底部隐藏的元素占据了空间，导致底部出现空白和滚动条

### ISSUE THREAD

**Issue by hungtcs** [Dogfalo/materialize#4403]
### Description
The hidden elements padding occupy space ,cause bottom gap.<br />
当我在页面中添加`materialize.js`之后，页面底部出现了间隙。原因是隐藏元素的内边距占用了空间。

### Repro Steps
add materialize.js in html.<br />
当添加`materialize.js`到页面之后

### Screenshots / Codepen
![image](https://cloud.githubusercontent.com/assets/11692935/24330989/b1988460-125d-11e7-947d-4ad07360f4ce.png)

**Comment by tomscholz** [comment]
In english?

**Comment by hungtcs** [comment]
yes

**Comment by tomscholz** [comment]
Can you provide a codepen to reproduce your problem?
