### ISSUE TITLE
HTML5 ragne thumb issues

### ISSUE THREAD

**Issue by NonameSLdev** [Dogfalo/materialize#4406]
### Description
* The thumb in the HTML5 slider is off to the right, and not exactly above the circle. (Tested: Edge, Chrome, Firefox, on the materializecss.com site)
* _Less important,_ but in Edge there are two thumbs: the materialize one and the default one.

### Repro Steps
Simply creating a range field.
`<p class="range-field">
      <input type="range" id="test5" min="0" max="100" />
    </p>`

### Screenshots / Codepen
http://codepen.io/NonameSL/pen/peZxOx

**Comment by acburst** [comment]
Hmm interesting, it seems if the wrapper element has padding it throws off the positioning.

Fixed in 8cb4b6c.

**Comment by tomscholz** [comment]
Please close then ;)
