### ISSUE TITLE
Dropdown doesn't close on click with 0.98.1.

### ISSUE THREAD

**Issue by Thanood** [Dogfalo/materialize#4409]
### Description
The dropdown component doesn't close on click with 0.98.1. With 0.98.0 it worked as expected.

### Repro Steps
See this CodePen for a reproduction: http://codepen.io/anon/pen/XMBOpo
It also doesn't work on Materialize website.

**Comment by acburst** [comment]
This was fixed recently in 42051a56d2a35bdd8fbdffab739ee64859b186d4

**Comment by Thanood** [comment]
Oh okay, sorry. I've overlooked that. 😃
