### ISSUE TITLE
Offset is applied for all larger screens

### ISSUE THREAD

**Issue by TetianaP** [Dogfalo/materialize#4410]
### Description
Column offset is applied for specified screen and all larger ones.

### Repro Steps
Create simple row with 2 columns:
```
<div class="row">
	<div class="col s12 m6 offset-m3 l8"></div>
	<div class="col s12 m6 offset-m3 l4"></div>
</div>
```

### Expected
For **large** screen content is placed in 2 columns: l8 and l4.
`Offset-m3` is applied only for **medium** screen.

### Result
For **large** screen content is placed in 1 column with left-column-offset: `offset-m3`.
Is there some way to clear offset or specify something like: offset-l0?

**Comment by Y0lk** [comment]
Noticed the same thing, but it was fine in 0.98.0

**Comment by Y0lk** [comment]
Here's the PR that fixes it : https://github.com/Dogfalo/materialize/pull/4483

**Comment by acburst** [comment]
Hmm, I tried to do some refactoring which caused this bug. Sorry about that. Merged in a PR that fixes this

**Comment by TetianaP** [comment]
@Y0lk, @acburst, thank  you!
