### ISSUE TITLE
Select option variable 

### ISSUE THREAD

**Issue by savchukm** [Dogfalo/materialize#4414]
### Description
I am using @angular/compiler-cli 2.4.2, materialize-css 0.98.0, angular2-materialize 6.7.0
 I put variable from component to template like that:
```
    {{user?.fullName}}
    <div class="input-field">
        <select>
            <option value="DEFAULT_USER">DEFAULT_USER</option>
            <option value="1">{{user?.fullName}}</option>
        </select>
        <label>Book owner</label>
    </div>
```
As a result there is no view for second option.

### Screenshots 
![screen shot 2017-03-27 at 19 35 49](https://cloud.githubusercontent.com/assets/18600769/24364697/9efb4046-1324-11e7-8e32-844c0dcf8f4b.png)

**Comment by fega** [comment]
Maybe you have to use `$('select').material_select();`

Please confirm if this solved your issue 

More info: http://materializecss.com/forms.html

**Comment by savchukm** [comment]
Actually, i have to use angular2-materialize to work with materialize and angular 2. Problem was with it. Closed.
