### ISSUE TITLE
Collapsible Preselected Section doesn't work with active class since 0.98.1

### ISSUE THREAD

**Issue by ciminf** [Dogfalo/materialize#4417]
### Description
Since 0.98.1 collapsible section with "active" class are not open at start.

### Repro Steps
Create a collapsible structure with active elements.

Doesn't work in 0.98.1
http://codepen.io/anon/pen/GWXejv

Works in 0.98.0:
http://codepen.io/anon/pen/qrMvrZ

**Comment by jeroenqui** [comment]
Already fixed in https://github.com/Dogfalo/materialize/commit/b336331e851d5903ce684b55cfd3049042d87b28

**Comment by tomscholz** [comment]
Please close
