### ISSUE TITLE
Navbar Mobile Overlay

### ISSUE THREAD

**Issue by retox001** [Dogfalo/materialize#442]
H, i have spotted a small issue/bug in reference to the navbar nav when using the mobile option, when the screen size is decreased the mobile navigation kicks in and then when you press the hamburger the overlay opacity gets increased to 1 but if you do not close the navigation the ovelay stays at 1 even if you increase the screen size again is there a easy fix for this so when the window increases the opacity it reset to 0?

**Comment by retox001** [comment]
i have come up with a quick fix but not it is not ideal, bascially set the #sidenav-overlay to display "none"
by default but then have the class #sidenav-overlay to display "block" on @media #{$medium-and-down} but a better solution is probably out there :-)

**Comment by Dogfalo** [comment]
I am not quite sure what the problem you are describing is. In any case, it is likely we have fixed these problems. I can reopen this is you are still experiencing this on the newer builds.
