### ISSUE TITLE
initialize modal which id includes hyphen

### ISSUE THREAD

**Issue by morten-hogseth** [Dogfalo/materialize#4420]
### Description
When initializing a modal with an id that uses hyphens, the ready function will not run.

### Works
```javascript
$("#myModal").modal({
  ready: () => funcyTown()
});
```
### Does not Works
```javascript
$("#my-modal").modal({
  ready: () => funcyTown()
});
```

**Comment by acburst** [comment]
Hyphens are not a problem with ids. Make sure your trigger and your modal id match. Try recreating your issue in an isolated environment like a codepen to make sure it isn't something on your end.

**Comment by tomscholz** [comment]
Closed due inactivity. Feel free to reopen it, if it's still necessary.
