### ISSUE TITLE
Floating Button's `halfway-fab ` functionality breaks if card size is set to large 

### ISSUE THREAD

**Issue by hiteshsahu** [Dogfalo/materialize#4421]
### Description
Floating Button's `halfway-fab ` functionality breaks if card size is set to large using `large` property

### Repro Steps

Set class "large" to card 

 ```
<div class="col s12 m6 ">
      <div class="card hoverable large">
        <div class="card-image">
          <img class="responsive-img" style="max-height:300px; object-fit: cover;" src="http://www.bankingtech.com/files/2016/03/Vipps.jpg">
          <span class="card-title">Vipps</span>
          <a class="btn-floating halfway-fab waves-effect waves-light red" ><i class="fa fa-angle-right" aria-hidden="true"></i></a>
        </div>
        <div class="card-content">
          <p>Vipps is a Norwegian mobile payment application designed for smartphones developed by DNB.</p>
		  
		   <div class="chip">Android</div><div class="chip">Material design</div><div class="chip">GCM</div><div class="chip">Web Services</div>
        
        </div>
		
		 <div class="card-action">
              <a href="https://play.google.com/store/apps/details?id=no.dnb.vipps">View on Play Store</a>
         </div>
      </div>
    </div>
```

### Screenshots / Codepen
![blah](https://cloud.githubusercontent.com/assets/4076925/24411641/f80fa9ae-13f3-11e7-8d14-384ae553a41b.png)

**Comment by DanielRuf** [comment]
The problem is the overflow value

![image](https://cloud.githubusercontent.com/assets/827205/24503580/f0b253b8-1552-11e7-8c2e-4f55609f09bd.png)

![image](https://cloud.githubusercontent.com/assets/827205/24503716/95f75bb6-1553-11e7-9a8e-2dd85317d328.png)

Do we need the `overflow:hidden` here?
cc @tomscholz @acburst @Dogfalo

**Comment by hiteshsahu** [comment]
Thank you for your time, I solved this issue by manually assigning the height to the card block using CSS.  

**Cause :-**
   The card class `large` restrict card height to 500px, I guess that was not enough for my `card-contents `and `card- action` and resulting into cropping of the fab button. I have override card height to 560px and everything seems nice.

**Solution**
```
.card
{
height:560px;
}
```

**Result**

 You can see it in action at my website http://hiteshsahu.com/.

**Comment by DanielRuf** [comment]
@hiteshsahu per official Google documentation, cards should have no fixed height.

https://material.io/guidelines/components/cards.html#cards-behavior

![screenshot_20170330-160247](https://cloud.githubusercontent.com/assets/827205/24508091/b757d9b6-1562-11e7-9a36-68bb56da882e.png)

So the fixed height makes no sense to me (and the overflow value).

cc @tomscholz

**Comment by hiteshsahu** [comment]
Different card height will lead to different column height and then the Grid will not look consistent ie. lot of extra spaces and empty columns. This is already an issue - https://github.com/Dogfalo/materialize/issues/2089.

**Comment by hiteshsahu** [comment]
I  also found this https://material.io/guidelines/components/grid-lists.html#grid-lists-behavior

> Full-screen grid lists should use fluid image ratios with minimum and maximum widths, derived using the Ratio keylines. They should retain fixed heights, margins, and padding.
> 
> Centered grid lists have fluid margins with a minimum width. They maintain fixed image widths, heights, and padding.

**Comment by DanielRuf** [comment]
At least we still have the inconsistency.

**Comment by hiteshsahu** [comment]
If you don't want to hardcode card height you can use this JQuery plugin  https://github.com/liabru/jquery-match-height to match column heights. 

HTML	

```
<div class="row">
  <div class="col m4 s6 sample">
    <img src="http://lorempixel.com/580/250/nature/1" class = "responsive-img">
    <p>
    Looooong Looooong Looooong Looooong Looooong text
    </p>
  </div>
  <div class="col m4 s6 sample">
    <img src="http://lorempixel.com/580/250/nature/1" class = "responsive-img">
    <p>
      Short text
    </p>
  </div>
  <div class="col m4 s6 sample">
    <img src="http://lorempixel.com/580/250/nature/1" class = "responsive-img">
    <p>Short text</p>
  </div>

  <div class="col m4 s6 sample">
    <img src="http://lorempixel.com/580/250/nature/1" class = "responsive-img">
  </div>
</div>
```

Javascript
```
$(document.ready(function(){
   $('.sample').matchHeight();
});
```

**Comment by DanielRuf** [comment]
Or CSS flexbox which should be preferred.

**Comment by AlexVentura** [comment]
I have tried to solve it using ***flexbox*** but I get an issue, the cards in the last row are aligned to the right as shown in the image below.
Here you have my [codepen example](https://codepen.io/alexventura/pen/QpQrqB).

![screen shot 2017-06-28 at 15 33 21](https://user-images.githubusercontent.com/13169164/27658877-2e0e20ce-5c17-11e7-999a-ff48007c8b58.png)

@DanielRuf How can I fix this?
