### ISSUE TITLE
New js version (0.98.1) dropdown bug

### ISSUE THREAD

**Issue by MindRapist** [Dogfalo/materialize#4422]
A new bug has been found in materializecss framework about dropdown buttons. When a button's/link's content is not text, but an `<i />` element (used to display icons), the related dropdown is not showing. Browser console displays no errors or warnings. Buttons/links with normal text as content are working properly. Previous version (0.98.0) does not have this issue.

To reproduce, create a navbar while using the 0.98.1 version of the js file. Then inside the `ul` element create a link or a button and bind it to a dropdown `ul`. Click it and nothing will happen. Return to the previous version and all should work fine.

You can view a live demo of this bug in this [codepen](http://codepen.io/MindRapist/pen/MpPyNP).

**Comment by tomscholz** [comment]
Jesus, cant you look first, if the issue already existed?
Duplicate of https://github.com/Dogfalo/materialize/issues/4409 https://github.com/Dogfalo/materialize/issues/4418
And fixed in https://github.com/Dogfalo/materialize/commit/42051a56d2a35bdd8fbdffab739ee64859b186d4

**Comment by tomscholz** [comment]
Please close

**Comment by gfazioli** [comment]
when you release this patch?

**Comment by maniinus** [comment]
i updated to 0.98.1 version yesterday. i currently see this issue. unable to open dropdown content if i use <i> in side anchor tag. issue still exists

**Comment by tomscholz** [comment]
@gfazioli I don't release, but I guess it's going to be released very soon

**Comment by travisbotello** [comment]
@tomscholz 42051a5 doesn't fix the described problem by @MindRapist (dropdown trigger with `i`only)

IMHO the fixed #4409 is not related to this bug...but #4418 is definitely a duplicate.
