### ISSUE TITLE
Non disable components (in materialize.scss)

### ISSUE THREAD

**Issue by markstalker** [Dogfalo/materialize#4429]
When I disable any 'import' in materialize.scss and then compile this file, my tabs stop working (Don't appear in full width, colors become default)
![Image of problem](https://i.imgur.com/yVIC6nI.png)
If I return default .css file, problem persists.

**Comment by tomscholz** [comment]
Why did you do that?

**Comment by markstalker** [comment]
I don't need all functionality of the materialize. Moreover, I want to make my own design for forms, because I think that it will be easier to delete the code than to overlap it.

**Comment by tomscholz** [comment]
Some imports are required to let any component work. I created a [gist here ](https://gist.github.com/tomscholz/1837869e1a9131cb29121c0ea57e75ce) how your materialize.scss could look like. Then you can delete anything except for:
```
components/_mixins.scss
components/_ color.scss
components/_variables.scss
components/_ normalize.scss
components/_ tabs.scss
```

**Comment by tomscholz** [comment]
Does it work? If yes, then please close this issue

**Comment by markstalker** [comment]
No. Doesn't work. Even if I don't delete the import, but simply compile materialize.scss

**Comment by tomscholz** [comment]
@markstalker Try this repo: https://github.com/tomscholz/materialize-sass-demo

**Comment by markstalker** [comment]
Thank you so much!
