### ISSUE TITLE
Preopened Collapsible not working (0.98.1)

### ISSUE THREAD

**Issue by travisbotello** [Dogfalo/materialize#4431]
### Description
Adding an `active` class to `collapsible-header` is not causing the corresponding div to be preopened.

### Repro Steps

```
<ul class="collapsible" data-collapsible="accordion">
    <li>
      <div class="collapsible-header active"><i class="material-icons">filter_drama</i>First</div>
      <div class="collapsible-body"><span>Lorem ipsum dolor sit amet.</span></div>
    </li>
    <li>
      <div class="collapsible-header"><i class="material-icons">place</i>Second</div>
      <div class="collapsible-body"><span>Lorem ipsum dolor sit amet.</span></div>
    </li>
    <li>
      <div class="collapsible-header"><i class="material-icons">whatshot</i>Third</div>
      <div class="collapsible-body"><span>Lorem ipsum dolor sit amet.</span></div>
    </li>
  </ul>
```

http://codepen.io/anon/pen/RpeYzd

**Comment by DanielRuf** [comment]
Found the issue. Will create a PR in a few minutes.

**Comment by Dogfalo** [comment]
The current builds are in bin/

**Comment by DanielRuf** [comment]
And [here](https://github.com/Dogfalo/materialize/releases) ;-)

**Comment by travisbotello** [comment]
@DanielRuf Just built it from master and also used the release in bin/ . It it still not working for me...

**Comment by DanielRuf** [comment]
@travisbotelloyou are right. Thought this fixed it. In the file we have to add a `.parent('li')` in one line.

Will prepare a pull request.

@Dogfalo please reopen.

**Comment by DanielRuf** [comment]
@travisbotello please check it again. You should already have the fix in `/bin/materialize.js` which should be  `ion g(a,c){c||a.toggleClass("active"),`

**Comment by travisbotello** [comment]
Well done @DanielRuf Thanks for the fix!

**Comment by jessejamesrichard** [comment]
Curious to know if the atmosphere version is out of date.

**Comment by DanielRuf** [comment]
> Curious to know if the atmosphere version is out of date?

Why?

**Comment by tomscholz** [comment]
@jessejamesrichard It insn't

**Comment by jessejamesrichard** [comment]
I downloaded from Atmosphere this morning, and I'm having similar problems with modals. 

`$(...).closeModal is not a function`
`$(...).openModal is not a function`

I figured it might be out-of-date.

**Comment by acburst** [comment]
Your code is out of date. A couple versions back we changed the modal code to just be .modal()

**Comment by jessejamesrichard** [comment]
My mistake. I was transitioning from poetic and missed this. Thanks for the catch.
