### ISSUE TITLE
Problem in using google picker with API with materialize package

### ISSUE THREAD

**Issue by prachi708** [Dogfalo/materialize#4433]
I want to use google picker with materialize package in meteor but picker window is not displaying with it. While if I am using same google picker API code without materialize package, window of picker is displaying.

**Comment by tomscholz** [comment]
> We can not provide support for third party libraries. If you post an issue about a specific problem that is causing a conflict with a specific library we can look into it, but it is impossible to be perfectly compatible with everything - Acburst #4365

**Comment by prachi708** [comment]
https://github.com/Dogfalo/materialize/pull/2868
I am facing same problem as mentioned in it, but solution given in this link is not working for me. I even tried after deleting "_default.date.scss" file from web.browser and web.cordova still it is not working.

**Comment by tomscholz** [comment]
Seems like your problem has been solved here: https://github.com/Dogfalo/materialize/issues/1727 . Please close

**Comment by prachi708** [comment]
No, my problem is not yet completely resolved. .picker css given in issue #1727 is working only for materialize version 0.98.0 it is not working for materialize version 0.97.7. When I tried to update it to 0.98.0 it is showing error as mentioned in issue #4193. I am also working on windows not Mac.
