### ISSUE TITLE
Chip inside carousel does not render properly

### ISSUE THREAD

**Issue by meiao** [Dogfalo/materialize#4435]
### Description
Having a chip inside a carousel-item causes the chip to misrender.

It seems that this is caused by the rule:
`
.carousel .carousel-item img {
  width: 100%;
}
`
which overrides:
`
.chip img {
  width: 32px;
}
`

### Repro Steps

http://codepen.io/meiao/pen/wJYLRX

**Comment by NonameSLdev** [comment]
It appears that the `.carousel .carousel-item img` sets the width to 100% and overrides the `.chip img` selector. I'll look into it and post a PR.

**Comment by DanielRuf** [comment]
@meiao please test https://github.com/Dogfalo/materialize/issues/4437

**Comment by NonameSLdev** [comment]
@meiao @DanielRuf Don't worry, #4437 does fix it. I tested it myself (simply inspecting element and doing it myself :))
