### ISSUE TITLE
Center class not working for a nested button

### ISSUE THREAD

**Issue by Shivang-Bhandari** [Dogfalo/materialize#4439]
### Description
When a Submit button is a child to a div with class row the class center is giving the same result as class left whereas right works perfectly fine.

### Repro Steps
make a submit button a child to div tag.

```
<div class="row">
    <button class="btn waves-effect waves-light center" type="submit" name="action">Submit
        <i class="material-icons right">send</i>
    </button>
</div>
```

**Comment by DanielRuf** [comment]
The class `center` just applies `text-align: center`. For floating I see just `left` and `right` here: http://materializecss.com/helpers.html

Try using `center-align` or `center` on the `row` (the parent element / wrapper).

**Comment by Shivang-Bhandari** [comment]
@DanielRuf Thanks for helping me out but even after applying `.center-align` and `.center` on the parent wrapper the float doesn't seem to be fixed. Unable to place button in the center still.

**Comment by DanielRuf** [comment]
@Shivang-Bhandari can you provide a codepen of your code based on my codepen?

**Comment by Shivang-Bhandari** [comment]
@DanielRuf http://codepen.io/thegrim/pen/ryQJNm

**Comment by DanielRuf** [comment]
You forgot to remove the right class: http://codepen.io/anon/pen/peQagE

**Comment by Shivang-Bhandari** [comment]
@DanielRuf Thank you so much for helping me out

**Comment by DanielRuf** [comment]
You are welcome.
