### ISSUE TITLE
Select option color 

### ISSUE THREAD

**Issue by joandvgv** [Dogfalo/materialize#4447]
### Description
I can't change the color of the select option in forms.

### Repro Steps
I got this codepen where it shows how, and it works. But in my project it does not. 
http://codepen.io/CasperEngl/pen/NxzYXE

It uses sass but I use the compiled css and change the color to gray (the one I want) and it works.

```
.select-wrapper ul li>span {
    color: grey;
}
```

Also, by chrome dev tools I was able to find the main rule but it also does not work. 

```
.dropdown-content li > a, .dropdown-content li > span {
    color: #607d8b;
}

```
The worst part is that if I use that conde in the codepen, it also works. 
 What am I doing wrong?

Obviously the css isn't loading properly, but I was able to change all of my other inputs in the same .css file. 

note: I'm using Angular2. 

### Screenshots / Codepen

![image](https://cloud.githubusercontent.com/assets/19196871/24482155/33ca9cfa-14bd-11e7-8d94-46022af92873.png)

**Comment by acburst** [comment]
Make sure you are including the css files in the right order. You may be overriding your own custom styles.

**Comment by joandvgv** [comment]
@acburst  In Angular2, each component has its own style associated. In this case, I got something like:
form.component.ts and form.component.css.
So, all of the rules associated with that form are in that file.

I will try changing view encapsulations in angular2 to see what happens and let you know. 

Is there any chance other rule could work?

**Comment by joandvgv** [comment]
I had tried to add the rules to my main angular component (app.ts) but that did not work. 
But after @acburst wrote about the CSS files being in the right order, I came with the idea of changing the view encapsulation of my component. For anyone interested you can read more about it [here](https://angular.io/docs/ts/latest/guide/component-styles.html#!#view-encapsulation)

So, by adding this line to my component metadata, the problem was fixed:
`encapsulation: ViewEncapsulation.None.
`
What this does is adding the rules to the global styles.

Not sure why got to do this for inputs using jquery like date picker & select option and not for simple input text.

Thanks for your reply!
