### ISSUE TITLE
improve button hover effect

### ISSUE THREAD

**Issue by pedrazadixon** [Dogfalo/materialize#4448]
You can replace 
.btn:hover, .btn-large:hover {
      background-color: #2bbbad;
}
to 
.btn:hover, .btn-large:hover {
      filter: brightness(110%);
      -webkit-filter: brightness(110%);
      -moz-filter: brightness(110%);
      -o-filter: brightness(110%);
      -ms-filter: brightness(110%);
}
This allow change the button color with the color classes without losing the brightness hover effect.

**Comment by DanielRuf** [comment]
For what is this code? It looks wrong. If you think it fixes an issue / bug, open a pull request.

**Comment by Coder-Kev** [comment]
I am going through a Youtube Tutorial by Net Ninja to familiarize myself with Materialize.  I noticed right away that the color buttons didn't respond the same as the default color with the hover effect.  I added this CSS pedrazadixon provided above into https://github.com/iamshaunjp/materialize-playlist/tree/lesson-8 and it worked great for me.  However, I added darken-2 to the buttons and changed the CSS brightness to 130% to get the effect I would use if I decide to start using Materialize.

**Comment by DanielRuf** [comment]
1.0.0 final was released so beta is outdated

**Comment by Coder-Kev** [comment]
Yes, I replaced the tutorial code with CDN https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/ for css and js.  I came to this page because I got a google hit on "materialize buttons hover color".  If there is a different thread for this issue, please let me know and I will follow the correct one.

**Comment by DanielRuf** [comment]
It's better to create a new issue with a codepen link and explain the problem in detail.
