### ISSUE TITLE
carousel in tabs not working

### ISSUE THREAD

**Issue by markupbang** [Dogfalo/materialize#4450]
### Description
carousel in tabs not working

### Repro Steps
carousel in tabs notworking.

The carousel in the second tab does not work.
So I put the onShow option, but the problem still persists.

Use this Codepen to demonstrate your issue. 
[https://codepen.io/markupbang-1473322092/pen/jBQaGx?editors=1010](https://codepen.io/markupbang-1473322092/pen/jBQaGx?editors=1010)

Answer me. Plz..

**Comment by DanielRuf** [comment]
Your markup is not correct.

https://codepen.io/anon/pen/yMQqGG?editors=1010

But there is another issue with the initialization of the nonvisible carousel. Will check this.

**Comment by acburst** [comment]
Found some issues with reinitialization. Fixed in 6e317e2.

Let me know if that solves your problems.
