### ISSUE TITLE
FAB and Toasts parent

### ISSUE THREAD

**Issue by X3MWorks** [Dogfalo/materialize#4455]
### Description
I'm creating an interface which is contained inside a 320x480 div element .
The problem is, both the toasts and the FAB take the whole 'body' width when triggered.

So is there a way to set the default parent of these two components to my div ?
Thanks.

**Comment by DanielRuf** [comment]
Please provide a codepen.

What do you mean with FAB?

**Comment by NonameSLdev** [comment]
@X3MWorks As we don't know the steps to reproduce your problem, provide a codepen or the issue will be closed in a few.

**Comment by fega** [comment]
Closed due inactivity, feel free to reopen it if it is still necessary.
