### ISSUE TITLE
Problem in Side bar, can't check the checkbox in computer view

### ISSUE THREAD

**Issue by Heysoulnat88** [Dogfalo/materialize#4456]
SO in computer view I can't check the checkbox but when I resize it became a sidebar there's now a check in the checkbox?
![capture](https://cloud.githubusercontent.com/assets/26007085/24511955/3a5db33a-153b-11e7-8e73-a9807232dd56.PNG)
![capture1](https://cloud.githubusercontent.com/assets/26007085/24511956/3a96164e-153b-11e7-9ae2-865bd9f5d511.PNG)

this is the index code 
`
<div class="container-fluid">
    <div class="row" ng-controller="productController">
        <div class="col m3 s12 z-depth-0 hide-on-med-and-down" style="position:fixed">
            @*@Html.Partial("Partials/_SideMenu")*@         
                <form>
                    <div class="input-field" style="height:50px;">
                        <input type="search" style="font-size:13px;outline:none;" placeholder="Search" name="search" id="search" ng-model="search.$">
                        <label class="label-icon"><i class="material-icons">search</i></label>
                    </div>
                </form>        
            <h6 class="collection-header">Organization</h6>
            <br />
            <div style="margin-left:10px;" id="cbmenu">
                <p>
                    <input type="checkbox" id="academic1" ng-click="includetypeOfCustomer('Academic')" />
                    <label for="academic1">Academic</label>
                </p>
                <p>
                    <input type="checkbox" id="corporate" ng-click="includetypeOfCustomer('Corporate')" />
                    <label for="corporate">Business</label>
                </p>
                <p>
                    <input type="checkbox" id="government" ng-click="includetypeOfCustomer('Government')" />
                    <label for="government">Government</label>
                </p>
            </div>
                <div class="divider"></div>
                <h6 class="collection-header">Categories</h6>
                <br />
            <div style="margin-left:10px;" id="cbmenu">
                <p>
                    <input type="checkbox" id="off365" ng-click="includeCategoryName('Office 365')" />
                    <label for="off365">Office 365</label>
                </p>
                <p>
                    <input type="checkbox" id="DynamicsCRM" ng-click="includeCategoryName('Dynamics CRM')" />
                    <label for="DynamicsCRM">Dynamics CRM</label>
                </p>
                <p>
                    <input type="checkbox" id="EmailServices" ng-click="includeCategoryName('Email Services')" />
                    <label for="EmailServices">Email Services</label>
                </p>
                <p>
                    <input type="checkbox" id="Security" ng-click="includeCategoryName('Security')" />
                    <label for="Security">Security</label>
                </p>
            </div>
        
                <div class="divider"></div>
                <h6 class="collection-header">License Type</h6>
                <br />
            <div style="margin-left:10px;" id="cbmenu">
                <p>
                    <input type="checkbox" id="subscription" ng-click="includelicenseType('Subscription')" />
                    <label for="subscription">Subscription</label>
                </p>
                <p>
                    <input type="checkbox" id="services" ng-click="includelicenseType('Services')" />
                    <label for="services">Services</label>
                </p>
            </div>
                `

this the sidebar code(it is the layout form in mvc)

`
<ul class="side-nav" id="collapsenav" ng-controller="productController">
    
        @if (customer.User != null && customer.Company != null)
        {
            <li>
                <div class="userView">
                    <div class="background grey darken-4">
                    </div>
                    <span><i class="large material-icons" style="font-size:60px;color:white;">account_circle</i></span>
                    <span class="white-text" style="padding-bottom:0;height:20px;font-weight:300">@customer.Company.AccountName</span>
                    <a asp-controller="Account" asp-action="Index" class="dropdown-button white-text right-align" data-activates="dropdown2" data-beloworigin="true" style="font-size:13px;font-weight:300;">
                        @customer.User.FirstName @customer.User.LastName<i class="material-icons right" style="margin-top:3px;">arrow_drop_down</i>
                    </a>
                </div>
            </li>
        }
        else
        {
            <li><a asp-controller="Account" asp-action="SignIn" style="font-size:14px;">Sign up</a></li>
            <li><a asp-controller="Account" asp-action="SignIn" style="font-size:14px;">Sign in</a></li>
        }
        <li><a href="@Url.Action("Index","Cart")" class="waves-effect waves-light"><span class="new badge">@ViewBag.CartItemCount</span><i class="material-icons">shopping_cart</i></a></li>

    <li>
        <form>
            <div class="input-field" style="height:50px;">
                <input type="search" style="font-size:13px;outline:none;" placeholder="Search" name="search" id="search" ng-model="search.$">
                <label class="label-icon"><i class="material-icons">search</i></label>
            </div>
        </form>
        <h6 class="collection-header">Organization</h6>
        <br />
        <div style="margin-left:10px;" id="cbmenu">
            <p>
                <input type="checkbox" id="academic1" ng-click="includetypeOfCustomer('Academic')" />
                <label for="academic1">Academic</label>
            </p>
            <p>
                <input type="checkbox" id="corporate" ng-click="includetypeOfCustomer('Corporate')" />
                <label for="corporate">Business</label>
            </p>
            <p>
                <input type="checkbox" id="government" ng-click="includetypeOfCustomer('Government')" />
                <label for="government">Government</label>
            </p>
        </div>
        <div class="divider"></div>
        <h6 class="collection-header">Categories</h6>
        <br />
        <div style="margin-left:10px;" id="cbmenu">
            <p>
                <input type="checkbox" id="off365" ng-click="includeCategoryName('Office 365')" />
                <label for="off365">Office 365</label>
            </p>
            <p>
                <input type="checkbox" id="DynamicsCRM" ng-click="includeCategoryName('Dynamics CRM')" />
                <label for="DynamicsCRM">Dynamics CRM</label>
            </p>
            <p>
                <input type="checkbox" id="EmailServices" ng-click="includeCategoryName('Email Services')" />
                <label for="EmailServices">Email Services</label>
            </p>
            <p>
                <input type="checkbox" id="Security" ng-click="includeCategoryName('Security')" />
                <label for="Security">Security</label>
            </p>
        </div>

        <div class="divider"></div>
        <h6 class="collection-header">License Type</h6>
        <br />
        <div style="margin-left:10px;" id="cbmenu">
            <p>
                <input type="checkbox" id="subscription" ng-click="includelicenseType('Subscription')" />
                <label for="subscription">Subscription</label>
            </p>
            <p>
                <input type="checkbox" id="services" ng-click="includelicenseType('Services')" />
                <label for="services">Services</label>
            </p>
        </div>
    </li>
        
</ul>
`

**Comment by DanielRuf** [comment]
Can you provide a codepen? Also please check if some element lies above the check box using the inspect tool of the developer tools in your browser.

**Comment by Heysoulnat88** [comment]
what is this code pen?

**Comment by DanielRuf** [comment]
https://codepen.io

You can fork one of the codepens from the other new issues which include Materialize 0.98.1 for example.

**Comment by Dogfalo** [comment]
There is also a link in CONTRIBUTING.md and it was there in the issue template when you were creating this issue report

**Comment by Heysoulnat88** [comment]
My only problem is that I can check the checkbox but when I change the size of the screen and became  a side nav  i can't clicked the checkbox but it still functioning, the checkbox btw is a filter

**Comment by NonameSLdev** [comment]
@Heysoulnat88 Explaning your problem further wouldn't help. What we need is a live example, and that's what codepen is for - you can code in the web browser and it changes automatically and then you can share it with others. Enter http://codepen.io/Dogfalo/pen/xbzPQV, click Fork in the top navbar and insert your code there. Then send the link to the codepen here.

**Comment by fega** [comment]
Closed due inactivity and to not seek the contributing guidelines, feel free to reopen it if it is still necessary, but please provide a live example
