### ISSUE TITLE
modals and collapsible active don´t work on local mashine

### ISSUE THREAD

**Issue by cripiLP** [Dogfalo/materialize#4457]
### Description
When i use the code below on my local mashine (apache2 with php, installed with xampp), the modal and the collapsible active class won´t work. In the codepen, the code work like it should!

### Repro Steps
I used the code on my local appache (xampp) webserver. My browser is the current firefox.

### Codepen
 http://codepen.io/cripi/pen/VpqZgO

I hop that are enough Informations. When you need more, i´l try to help!

sincerely, Cripi

**Comment by DanielRuf** [comment]
Please see https://github.com/Dogfalo/materialize/issues/4431

**Comment by fega** [comment]
Can I close this?

**Comment by DanielRuf** [comment]
Seems to be another issue, probably not related to the other. Please check the console in your browser.
