### ISSUE TITLE
select input doesn’t work properly with ember-cli

### ISSUE THREAD

**Issue by PDXIII** [Dogfalo/materialize#446]
Hello! 
I don’t know why but it is somehow broken. When I submit a form with an select element, it always returns the default selection and if I add the `browser-default` class it converts it to the material select anyway.

When I disable the javascript-foo and change the css manually to the default, it works alright!

Maybe you can fix this, because I would like to use it so badly ;-)

System-Info:

OSX 10.9.5
Ember: 1.9.1
Ember Data: 1.0.0-beta.14.1
Handlebars: 2.0.0
jQuery: 2.1.3
Materialize: 0.93.1

**Comment by acburst** [comment]
How are you initializing the plugin?

**Comment by PDXIII** [comment]
Please take a look at this [gist.](https://gist.github.com/PDXIII/93edefe11b3fb1414c8e)

As you can see, I have a route called __contactform__ which handles the final _submission_ or _cancelation._
Inside __contactform__ there is the _component_ __contactform-component__ which collects all the input data and sends this to the _controller_ of __contactform.__

**Comment by PDXIII** [comment]
Filed this issue in the [Ember-CLI-Materialize Repo](https://github.com/sgasser/ember-cli-materialize), too.

**Comment by sgasser** [comment]
I think this is the same bug like #466 .
Updating the selected with javascript not works.

**Comment by carlosperate** [comment]
As https://github.com/Dogfalo/materialize/issues/466 is closed, I though I should mention here https://github.com/Dogfalo/materialize/issues/452, which is the currently open report for that issue.

**Comment by PDXIII** [comment]
Cool! Thank you!

**Comment by carlosperate** [comment]
@PDXIII just curious, are you still having this issue with the current master?

**Comment by PDXIII** [comment]
Haven’t tried it for quiet a while. But will let you know, when I updated my project.
