### ISSUE TITLE
Security Issue: jQuery XSS

### ISSUE THREAD

**Issue by DEKHTIARJonathan** [Dogfalo/materialize#4463]
**Security Issue Severity : high** !

> Jquery is a javascript library for DOM traversal and manipulation, event handling, animation, and Ajax.
> 
> When text/javascript responses are received from cross-origin ajax requests not containing the option dataType, the result is executed in jQuery.globalEval potentially allowing an attacker to execute arbitrary code on the origin.

This project requires jQuery >= 2.1.1, and unfortunately every version 2 jQuery lib is vulnerable.
**Vulnerable:** >=1.4.0 <=1.11.3 || >=1.12.4 <=2.2.4
**Patched:** >=3.0.0

I hope it won't be too hard to update the lib. I currently try to update my projects using materialize.
@acburst I tag you here, I hope you will be able to see this issue quite quickly.

More information available here : https://nodesecurity.io/advisories/328

**Comment by DanielRuf** [comment]
Theoretically changing it to `^3.2.1` should still work.
https://github.com/Dogfalo/materialize/blob/master/package.json

**Comment by DEKHTIARJonathan** [comment]
I do not have any error raised. 
However I don't know why the "load" event is not triggered... 
I will try to have a look tomorrow and create a jsfiddle.

**Comment by acburst** [comment]
Load was removed in jquery 3
https://jquery.com/upgrade-guide/3.0/#breaking-change-load-unload-and-error-removed

**Comment by DEKHTIARJonathan** [comment]
If i'm right, load is deprecated however, on('load', func() ... is not.

I do not have any error, the event is just not triggered.
I know it is not a problem with jQuery 3 because, without materialize it perfectly works.

JSFiddle showing the issue: https://jsfiddle.net/L143f26c/3/#&togetherjs=rzQ8sqHaux

**Comment by DEKHTIARJonathan** [comment]
It seems it was my fault I can't manage to reproduce the fault with a jsFiddle...

I was basically using the following code:
`$( document ).ready(function() {
    console.log( "ready!" );
});
$( window ).on( "load", function() {
    console.log( "window loaded" );
});`

**Comment by DanielRuf** [comment]
@DEKHTIARJonathan sure?

![image](https://cloud.githubusercontent.com/assets/827205/24553038/14a41d2a-1629-11e7-84a1-25c8796edb09.png)

**Comment by DEKHTIARJonathan** [comment]
@DanielRuf absolutely.

Be careful you need to set when your JS is triggered :

![image](https://cloud.githubusercontent.com/assets/10923599/24553148/73ca2448-1629-11e7-8be8-3fa18a652572.png)

**Comment by DanielRuf** [comment]
> Be careful you need to set when your JS is triggered

Right, outside of jsfiddle it should work. jsfiddle parses your JaaScript code and eecutes it with the defined load type.

**Comment by DanielRuf** [comment]
But we could change the major version number from 2 to 3 in the future =)

**Comment by benjaminaudet** [comment]
Looks like the problem is still here:
![image](https://user-images.githubusercontent.com/9674694/55282367-0008c600-5343-11e9-8f3a-44b4948a341b.png)
