### ISSUE TITLE
HTML 5 range selector v0.98.1 bug

### ISSUE THREAD

**Issue by DRoet** [Dogfalo/materialize#4464]
### Description
The label is no longer displaying correctly in Materialize v0.98.1, it seems to be worse when setting a lower min="" value.

### Repro Steps
See codepen below:

http://codepen.io/anon/pen/ryoygL

### Screenshots / Codepen
![range bug v98 1](https://cloud.githubusercontent.com/assets/7842510/24540702/b06a50e2-15f4-11e7-9cdd-2061ce3297e3.png)

**Comment by DanielRuf** [comment]
The linked PR should fix this
