### ISSUE TITLE
Javascript -> Models Modal With Fixed Footer Popup With Scroll Bar In New Suggection Is Scroll Bar Is Dozen In Window Screen.....

### ISSUE THREAD

**Issue by jajaljay** [Dogfalo/materialize#4465]
### Description
Add a detailed description of your issue.

### Repro Steps
Layout the steps to reproduce your issue.

Use this Codepen to demonstrate your issue. http://codepen.io/Dogfalo/pen/xbzPQV

### Screenshots / Codepen
Add supplemental screenshots or code examples. Look for a codepen template in our Contributing Guidelines.

**Comment by DanielRuf** [comment]
Please update your codepen and add your code

**Comment by acburst** [comment]
You keep making issues with no information other than a title. Please follow our issue guidelines
