### ISSUE TITLE
_Variables.scss Compilation Error

### ISSUE THREAD

**Issue by sadonay2** [Dogfalo/materialize#4467]
Simply when i try to change the default color on my project the compiler throws this:
"argument `$color` of `lighten($color, $amount)` must be a color "

Even when i just compile the file without a change.

**Comment by DanielRuf** [comment]
Did you compile materialize.scss? You should not directly compile _variables.scss.

**Comment by kmmbvnr** [comment]
the `_variables.scss` depends on `_color.scss` and `_mixins.css` You should include it first.

Generally, if you would like to create customized materialize build, you can create a scss file with context like [materialize.scss](https://github.com/Dogfalo/materialize/blob/master/sass/materialize.scss) and list only required things.

You can tune sass include path to override build in components files. Here is the sample for gulp build:

```javascript
gulp.task('materialize.django.scss', () => {
  return gulp.src('./mycustom/materialize.scss')
    .pipe(sass({
      includePaths: ['./node_modules/', './mycustom/']
    }).on(
      'error', sass.logError
    ))
    .pipe(postcss([
      autoprefixer({
        browsers: supportedBrowsers
      })
    ]))
    .pipe(gulp.dest(
      './output/'
    ))
})
```

Here is how my sass files for this sample:

https://github.com/viewflow/django-material/blob/master/material/static/material/sass/materialize.scss
https://github.com/viewflow/django-material/blob/master/material/static/material/sass/_variables.scss

**Comment by tomscholz** [comment]
Closed due inactivity, feel free to reopen it if it is still necessary.
