### ISSUE TITLE
Pulse only works well with circular buttons

### ISSUE THREAD

**Issue by RichardSaldias** [Dogfalo/materialize#4475]
### Description
Only works well with circular buttons but normal buttons do not line up.
This can be fixed with a simple margin, I leave it in case someone has any complication and if they could generate some module for this particular case.

### How to fix?
`.pulseFix::before {
  margin-left: -26px !important;
}
`

for example:
`<a class="waves-effect waves-light btn pulse pulseFix">button</a>`

### Demonstration
Demonstration. https://codepen.io/petirrojo/pen/qrgNrg

**Comment by DanielRuf** [comment]
There is no pulse for rectangular buttons according to the official Google documentation https://material.io/guidelines/motion/material-motion.html#material-motion-what-makes-a-good-transition

**Comment by tomscholz** [comment]
If pulses are not designed for rectangular buttons I think we should prevent that class from working on rectangular buttons.
