### ISSUE TITLE
Collapsible active class

### ISSUE THREAD

**Issue by ralpho00** [Dogfalo/materialize#4476]
### Description
Collapsible active class not working. I noticed also in your website that when i click a link on the collapsible side nav, when the page loads, there is no active collapsible, but on your previous website (which i downloaded for when i need it and i don't have internet connection) it was working, the version that was used there was 0.98.0.

### Repro Steps
Layout the steps to reproduce your issue.

Use this Codepen to demonstrate your issue. http://codepen.io/Dogfalo/pen/xbzPQV

### Screenshots / Codepen
Add supplemental screenshots or code examples. Look for a codepen template in our Contributing Guidelines.

**Comment by ralpho00** [comment]
duplicate

**Comment by believeZJP** [comment]
Is this fixed?

**Comment by fega** [comment]
@ralpho00 do you have the reference for the duplication?
