### ISSUE TITLE
Slider not show image in Chrome

### ISSUE THREAD

**Issue by adrian011494** [Dogfalo/materialize#4477]
### Description
Slider not show image in Chrome
![screenshot from 2017-04-01 23-43-26](https://cloud.githubusercontent.com/assets/19525321/24584024/954f99a0-172c-11e7-9ab7-d0928b631cfc.png)
### The solution
The solution is to delete these lines in slider.js or in materialize.js:
`$slides.find('img').each(function () {
          var placeholderBase64 = 'data:image/gif;base64,R0lGODlhAQABAIABAP///wAAACH5BAEKAAEALAAAAAABAAEAAAICTAEAOw==';
          if ($(this).attr('src') !== placeholderBase64) {
            $(this).css('background-image', 'url(' + $(this).attr('src') + ')' );
            $(this).attr('src', placeholderBase64);
          }
        });`

**Comment by NonameSLdev** [comment]
It's exclusive you, as it appears, it works fine for me on chrome. Care to reproduce your problem?

**Comment by DanielRuf** [comment]
The images are probably blocked by one if your browser extensions. Take a look at your browser console.

**Comment by NonameSLdev** [comment]
Please close the issue? Try @DanielRuf 's solution - perhaps you have an extension blocking it, or the connection timed out before the image could load.

**Comment by DanielRuf** [comment]
Take a look at the address bar on the right side next to the star / favourite icon. Click this small image icon with the red x.

Also what is the version of your Chrome browser (check chrome://version)?

**Comment by tomscholz** [comment]
Yup, this is clearly chromes/one of your extensions fault.
