### ISSUE TITLE
Color classes not working in specific browsers.

### ISSUE THREAD

**Issue by ReptoxX** [Dogfalo/materialize#4486]
### Description
I don't know, if i should use the @extend function anytime, but the color classes are not working on Safari, Firefox, IE. Only browser where it seems to work is Chrome.
I do not know, why this happend. Any help?

### Repro Steps
http://codepen.io/anon/pen/dvrbOV
Very basic classes used.
I am using webpack (laravel) to compile the sass files.

### Screenshots / Codepen

![Chorme Grey | Firefox Pink](https://cloud.githubusercontent.com/assets/13363890/24608400/b8aa1dc6-1876-11e7-9ce0-a95b7f74ca45.png)

**Comment by Nohinn** [comment]
Working on my side on Chrome, Firefox and Edge.

There's a typo in the codepen, should be grey not gray.

**Comment by ReptoxX** [comment]
You are right, but in my code it is "grey" just misspelled. As you can see on the screenshots the grey is correct (on Chrome).

**Comment by cbruyndoncx** [comment]
I noticed the same since a few weeks on my site, but thought I messed things up.
But on the materialize sample pages for instance the striped example table doesn't show any color at all (no striped effect). 
http://materializecss.com/table.html
using Firefox 52.0.2, using IE11 on Windows 7

**Comment by tomscholz** [comment]
Can you send a screenshot?

**Comment by cbruyndoncx** [comment]
I have been using firefox debugging and just found out the striped color applied is gray95 which is practically invisible on my screen.
table.striped > tbody > tr:nth-child(odd) {
  background-color: #f2f2f2;
}

So my report is bogus, question is, howcome only now this is showing. 
Not sure what changed when exactly.
