### ISSUE TITLE
Search Input

### ISSUE THREAD

**Issue by Rinum** [Dogfalo/materialize#449]
Like this: http://www.google.com/design/spec/patterns/search.html#

**Comment by alioygur** [comment]
:+1:

**Comment by Dogfalo** [comment]
added in 98c2b7bd8e981c2f18379284732d994756f52fb4

**Comment by RaSeR** [comment]
We should move to specific class for inputs instead of commits like this one. It will reduce a lot of css rules and make code looks like a bit cleaner.
