### ISSUE TITLE
Adding waves to a navbar anchor makes the link move by 1px

### ISSUE THREAD

**Issue by Braed** [Dogfalo/materialize#4495]
### Description
Adding "waves-effect waves-light" to a navbar anchor adds "display:inline-block;" which causes the anchor to move down 1 pixel. I'm not sure why the inline-block property is needed...

### Repro Steps
Add the "waves-effect waves-light" class to a navbar link.

### Screenshot
The link on the left has waves. You can see the positional difference.  
http://prntscr.com/esxpws

### Codepen
http://codepen.io/anon/pen/XMQvPo

**Comment by DanielRuf** [comment]
Can you provide a codepen?

**Comment by DanielRuf** [comment]
http://codepen.io/anon/pen/aJxeEX

**Comment by Braed** [comment]
https://codepen.io/anon/pen/GWLVGq

**Comment by fega** [comment]
Yeah, is a mere 1px but I still can notice it

**Comment by Braed** [comment]
It's not a big deal, just bothers me and could be easily fixed by removing the display property from the waves-effect class. 😄

**Comment by DanielRuf** [comment]
Looks duplicate with `btn`

**Comment by Braed** [comment]
Ah yes the inline block is being used with buttons.   
`a.wave-effect {display:block;}` should fix that, then?

**Comment by DanielRuf** [comment]
https://github.com/Dogfalo/materialize/pull/4496

**Comment by DanielRuf** [comment]
At least docs say
> To put the waves effect on buttons

**Comment by DanielRuf** [comment]
To be clear, your anchor is not a button.

**Comment by Braed** [comment]
Yes, sorry, button are using button not a. Ignore my last comment! Thank.

**Comment by DanielRuf** [comment]
```HTML
 <a class="waves-effect waves-light btn-large" ..
```

**Comment by DanielRuf** [comment]
But the PR should help

**Comment by Braed** [comment]
Yes, i'm talking about the anchor in the navbar, but buttons are also using anchors!
Ignore my last comment! :)

**Comment by Braed** [comment]
Thanks anyway. For now i'll just deal with the 1px as i presume it will be fixed in the next release?

**Comment by DanielRuf** [comment]
Add `btn` to the anchor. The docs say 
> To put the waves effect on buttons
```HTML
 <a class="waves-effect waves-light btn-large" ..
```
See http://materializecss.com/waves.html

**Comment by DanielRuf** [comment]
Please test the PR

**Comment by Braed** [comment]
It's not a button, it's a navbar link...
Sorry for my ignorance, i'm new to Github, how do i test the PR? I'm not using Github Desktop right now, but removing the display property will work just fine!

**Comment by DanielRuf** [comment]
You can test it with `.waves-effect{display: inherit;}` or `.waves-effect{display: initial;}` using the CSS window of codepen.

**Comment by Braed** [comment]
Yup, working! Thank you. My first Github issue 😇 .
