### ISSUE TITLE
[Feature Request] Borders

### ISSUE THREAD

**Issue by Braed** [Dogfalo/materialize#4499]
### Description
I'd like to see borders added with the same selectors as font and bg colours, "blue-border border-darken-2", for example.
Entering border colours manually defeats the purpose of using sass - i'd have to go through my css file and change all the border colours were I to change my design.
Thanks!

**Comment by fega** [comment]
I didn't see how this could fit with the "design of material design" do you understand what I mean? 
Also the color classes are one of the things that increase a LOT the size of the materialize.css file.

I cannot see a real benefit of adding this to the project.

**Comment by Braed** [comment]
Come to think of it, Material Design doesn't really use borders, you're right!
I suppose i could add it myself using sass if needed.
Thanks, fega.
