### ISSUE TITLE
TypeError: overlay.velocity is not a function

### ISSUE THREAD

**Issue by rsella** [Dogfalo/materialize#4501]
When including Materialize with webpack like this 
`import './bower_components/materialize/dist/js/materialize'`
and using in html the lightbox component like this
`<img src="image.png" class="responsive-img materialboxed" />`
I got this JS error in console:
`materialize.js:1163 Uncaught TypeError: overlay.velocity is not a function`

I already tried solutions proposed in other issues, like 
`window.jQuery = window.$ = require("./bower_components/jquery/dist/jquery.min");`
but without luck.

Any idea on how to solve that error?

Thanks in advance for any help

**Comment by DanielRuf** [comment]
Did you try the master branch?
Which version of Materialize do you use?
How does your webpack config look like?

Velocity should be part of Materialbox.
Do you import any other js files after `import './bower_components/materialize/dist/js/materialize'`?

**Comment by DanielRuf** [comment]
related issues
https://github.com/Dogfalo/materialize/issues/2949
https://github.com/Dogfalo/materialize/issues/3812

**Comment by rsella** [comment]
I resolved importing Materialbox like that:
`import './bower_components/materialize/js/materialbox'`

and it works like a charm.

I thought that importing materialize would import all components.

Thanks for help
