### ISSUE TITLE
Parallax placed inside a tab not working until window is resized

### ISSUE THREAD

**Issue by ericrayanderson** [Dogfalo/materialize#4504]
### Description
When a parallax enabled image is placed inside a tab that is not initially active, the window must be re-sized (bigger or smaller) in order for the parallax to display properly.

### Repro Steps
I have produced the issue here: (all HTML code):
http://codepen.io/ericrayanderson/pen/PpvRGx

**Comment by DanielRuf** [comment]
@ericrayanderson please test the linked pull request

**Comment by ericrayanderson** [comment]
I have tried using parallax.js from the commit : https://github.com/Dogfalo/materialize/tree/aeb959b09acf09e745d622fd1371ecaa0b376430, and I am still experiencing the same issue.

**Comment by DanielRuf** [comment]
Did you recompile the materialize.js file? Because I tested it locally and this fixed the issue on my side. Was the browser cache cleared?

**Comment by acburst** [comment]
You can also use the callbacks in tabs to initialize the parallax

**Comment by ericrayanderson** [comment]
Aside from using the callbacks, I am still experiencing the issue.

I hosted a test version of the parallax [here](http://materialparallaxtest.s3-website-us-east-1.amazonaws.com/ ), with the updated JS parallax code. Unless I missed something, I still appear to be having an issue.

**Comment by DanielRuf** [comment]
@ericrayanderson please create a codepen for better testing.

**Comment by ericrayanderson** [comment]
Pen created here https://codepen.io/ericrayanderson/pen/KmVWbB.

All of the code is in the HTML tab.

**Comment by tomscholz** [comment]
https://codepen.io/tomscholz/pen/LyGyZR
This one is cleaner

**Comment by ericrayanderson** [comment]
I'm not sure if LyGyZR is using the updated version of the parallax code.

**Comment by DanielRuf** [comment]
> I'm not sure if LyGyZR is using the updated version of the parallax code.

No, the PR is still unmerged.

**Comment by DanielRuf** [comment]
Did you recompile using grunt and use the new file in bin / dist?

**Comment by ericrayanderson** [comment]
I looked the changes in the code (the diffs from commit 95d02fa2d07520932d4aa46a31c08731a3d5e536), and manually replaced the parallax function.

[Done here](https://codepen.io/ericrayanderson/pen/KmVWbB)

I am not very familiar with recompiling javascript code using a grunt file...

**Comment by DanielRuf** [comment]
Please try https://codepen.io/anon/pen/xdZrWj

Took https://raw.githubusercontent.com/Dogfalo/materialize/master/dist/js/materialize.js and did the changes.

![image](https://cloud.githubusercontent.com/assets/827205/25186147/966980d4-251f-11e7-8dc5-58fc73aa325a.png)

**Comment by ericrayanderson** [comment]
The pen is working for me as well.

However, I tried downloading the files and running it locally, and I am still experiencing the issue...
<img width="1440" alt="parallax-test" src="https://cloud.githubusercontent.com/assets/16569985/25187463/1657cf46-24f1-11e7-8121-1c0507a62a5c.png">

**Comment by ericrayanderson** [comment]
Scrolling the or resizing the page makes the parallax function properly (on my local version).

**Comment by ericrayanderson** [comment]
Another view
<img width="1440" alt="screen shot 2017-04-19 at 11 19 00 am" src="https://cloud.githubusercontent.com/assets/16569985/25187802/14bbc6dc-24f2-11e7-999a-0e28c06ee309.png">

**Comment by ericrayanderson** [comment]
I made sure to clear the browser history, and I believe it is getting cleared out because after doing so, the page will take a little longer to load.

**Comment by ericrayanderson** [comment]
Last comment (this is what the page looks like after resizing (by any amount):
<img width="1411" alt="screen shot 2017-04-19 at 11 25 01 am" src="https://cloud.githubusercontent.com/assets/16569985/25188085/dd6acaa6-24f2-11e7-9fff-f310ab780a31.png">

**Comment by tomscholz** [comment]
@ericrayanderson Little tipp: http://stackoverflow.com/a/7000899

**Comment by ericrayanderson** [comment]
@tomscholz ty, looks useful

**Comment by DanielRuf** [comment]
> The pen is working for me as well.
> 
> However, I tried downloading the files and running it locally, and I am still experiencing the issue...

So the codepen works and solves your issue or not?
Which files exactly (commit hash / tag)?

**Comment by ericrayanderson** [comment]
Going to the codepen link worked, however I downloaded the files from that codepen (https://codepen.io/anon/pen/xdZrWj) and tried running them locally, and the issue still persists.

**Comment by ericrayanderson** [comment]
(downloaded, i.e., copy and pasted from the codepen xdZrWj)

**Comment by ericrayanderson** [comment]
I just tried exporting https://codepen.io/anon/pen/xdZrWj to zip, and running index.html locally, and I still get the issue.

Note* When running locally, if I click on Tab 2 while the tab is still loading (locally loading materialize js), the parallax will display correctly. If I let the page fully load (locally), and then go to Tab 2, the parallax does not display correctly.

**Comment by DanielRuf** [comment]
Found the issue, pushed a new commit to the PR. Thanks for catching this.

Please try this changen too https://github.com/Dogfalo/materialize/pull/4505/commits/0ea7298b8c9353359686ff35e337d710cdeb8e41

All changes: https://github.com/Dogfalo/materialize/pull/4505/files

I also moved the code into the update function to recalculate the height when the function is called (initialization, scrolling and resizing).

**Comment by ericrayanderson** [comment]
Working 👍

**Comment by Luke-Tan** [comment]
Does anyone still have problems with this? @DanielRuf s solution doesnt seem to work for me and stops the parallax effect from working completely

**Comment by DanielRuf** [comment]
@Luke-Tan the PR is not yet merged. Did you try to make the changes in the unminified materialize.js file and test it?

**Comment by DanielRuf** [comment]
@tomscholz can we merge the PR?

**Comment by Luke-Tan** [comment]
@DanielRuf yup i replaced the parallax function in my materialize.js file with the one you edited but it doesnt seem to work

**Comment by DanielRuf** [comment]
@Luke-Tan please provide a codepen with your code so I can take a look at it.
