### ISSUE TITLE
validation message wrong place on textarea  with dynamic content

### ISSUE THREAD

**Issue by venturion** [Dogfalo/materialize#4506]
### Description
hi, 
The validation message (data-success, data-error) position is not right with dynamic textareas content, they keeps the top in 60px like in the image below.

### Screenshots / Codepen
![textarea-bug](https://cloud.githubusercontent.com/assets/3776794/24780793/9134e400-1b10-11e7-8319-036ed5515761.png)

**Comment by fega** [comment]
I guess that this is the same #2697 is due of the same mechanism

**Comment by acburst** [comment]
Fixed in a2e10d9607b71e7ddc1c498e4820cb9f05dd6639
