### ISSUE TITLE
Implement new inputs types

### ISSUE THREAD

**Issue by fega** [Dogfalo/materialize#4507]
It looks that the material design guidelines implemented a new kind of text area also with another  input types
https://material.io/guidelines/components/text-fields.html#text-fields-field-variations

![image](https://cloud.githubusercontent.com/assets/6069807/24783847/6dbf6ffa-1b14-11e7-90c8-f1c8330014d1.png)

**Comment by tomscholz** [comment]
I personally have to say, that it looks like crap

**Comment by fega** [comment]
Hahaha, yeah I don't like this one too, but there another new inputs that are looking nicer

**Comment by bassie1995** [comment]
It looks off in the above screenshot, but the examples from the link in the OP are actually pretty nice.
Wonder if they fit into a desktop environment though?

**Comment by GGolov** [comment]
[These inputs](https://material.io/guidelines/components/text-fields.html#text-field-boxes-figure-caption-7) look better than the others above.

**Comment by vinibiavatti1** [comment]
I think it would be better, to have more kind of inputs to put there, or a input with full border like bootstrap. I have tried to make web systems instead of sites, but using the current input style it looks a little strange.

**Comment by bassie1995** [comment]
Doesn't that deviate from MD specs though?

**Comment by fega** [comment]
@vinibiavatti1 what do you mean?

**Comment by fega** [comment]
referenced on: #4553 

closing...
