### ISSUE TITLE
FeatureDiscovery is dupplicate on mobile view with wrong position

### ISSUE THREAD

**Issue by FarzanDalaeeBamilo** [Dogfalo/materialize#4510]
i have issue with FeatureDiscovery in mobile view the position is incorrect when its open.

this is output:
http://codepen.io/anon/pen/MpdMdJ

**Comment by tomscholz** [comment]
Fixed in https://github.com/Dogfalo/materialize/commit/132f71e33d88b669a91d3f941387ed67a723d009
