### ISSUE TITLE
Adding an 'active' class to the header of a collapsible, does not make it 'active'

### ISSUE THREAD

**Issue by tdecoy** [Dogfalo/materialize#4513]
Pretty straight forward:

http://materializecss.com/collapsible.html stipulates:

> **Preselected Section**
If you want a collapsible with a preopened section just add the active class to the collapsible-header. 

With an example of:

`<div class="collapsible-header active"><i class="mdi-maps-place"></i>Second</div>`

However, adding this does nothing. The "active" collapsible isn't active/expanded on page load. However, clicking it does expand it and adds the required 'active' class in the DOM.

Could it be that Materialize strips the class if pre-added?

**Comment by fega** [comment]
This is visible in the documentation example

**Comment by tdecoy** [comment]
What do you mean it's visible?

It isn't visible from where I'm sitting: https://i.imgur.com/RouPxt9.png

**Comment by fega** [comment]
Sorry I didn't express what I tried, I should say

"This problem is visible in the documentation example"

**Comment by acburst** [comment]
Duplicate of #4375

**Comment by tomscholz** [comment]
Will be fixed with the next release

**Comment by alan19031216** [comment]
<li class="active">
                   <div class="collapsible-header active"><i class="material-icons">face</i>User detail</div>
                   <div class="collapsible-body">
</li>

Don't forgot put "active" in first div class.
