### ISSUE TITLE
Undocumented (Unimplemented?) dropdown option `closeOnClick` used in `forms.js`

### ISSUE THREAD

**Issue by jacobq** [Dogfalo/materialize#4514]
The options [listed here](http://materializecss.com/dropdown.html#options) do not include `closeOnClick`, but the [code here](https://github.com/Dogfalo/materialize/blob/e45393d185e55f3745614660f4532f255ffc9338/js/forms.js#L587) passes this option. It doesn't look like this option is current supported since I don't [see it here](https://github.com/Dogfalo/materialize/tree/42051a56d2a35bdd8fbdffab739ee64859b186d4/js/dropdown.js#L12-L19).

1. If possible, could this option be implemented?
2. If it is not implemented, why is it being used in other code? (Looks like a mistake)

**Comment by acburst** [comment]
That is definitely a mistake probably from an old option that no longer exists.

Fixed in faafe84
