### ISSUE TITLE
Inputs stay active when reset is triggered

### ISSUE THREAD

**Issue by Clearwood** [Dogfalo/materialize#4515]
### Description
When a form is resetted via the the reset trigger the input fields stay active.
I believe in this case the active class should be removed from all input fields.
### Repro Steps
The following codepen triggers a reset when both 
input fields have the same value.
http://codepen.io/clearwood/pen/VpJNdR

**Comment by fega** [comment]
@Clearwood you should call  `Materialize.updateTextFields()` after edit the text field programmatically
look:

http://codepen.io/fega/pen/yMmjxM

**Comment by Clearwood** [comment]
@fega why can't we then add a trigger to the reset event then, something like:
object.addEventListener("reset", function(){
Materialize.updateTextFields();
});
I still believe this can be characterized as a bug not a question.

**Comment by fega** [comment]
@Clearwood Hello Clearwood, I cannot see any troubles in your codepen, all is working as expected, so it mean that your issue is a question, not a bug. 

Maybe an enhancement request.

could you provide me a clear example (codepen) where `addEventListener` isn't working?

**Comment by Clearwood** [comment]
@fega I never claimed to have a problem with this in person, it is just not what I would expect.
On a reset I would expect the labels to reset as well. I would say this is a bug not an enhancement request but this really depends on your point of view.
