### ISSUE TITLE
Add Offset-0 to stop offset propagation 

### ISSUE THREAD

**Issue by ArnaudPl** [Dogfalo/materialize#4516]
### Description
The offset value for medium is still active when on large screen and above. The expected behavior is that if we are using the class "l6", we don't use the class "offset-m2". We can't even set "offset-l0" to deny it.

### Repro Steps
Example on codepen : http://codepen.io/anon/pen/evqOXo

**Comment by fega** [comment]
Hello,  @ArnaudPl, In my opinion  Materialize is a "Mobile first" framework, it means that the changes propagate to "above", another framework works like bootstrap and foundation are also mobile first and you will find the same behavior

**Comment by fega** [comment]
you should use `offset-l0`
Example
http://codepen.io/fega/pen/wJVawz

**Comment by ArnaudPl** [comment]
Thanks for the answer @fega, but you were wrong on this. You told me to use the class "offset-l0" to deny the previously set offsets, but this class isn't defined in Materialize.

I don't see anything _to stop the propagation_ of the offset set for a smaller screen size.

I edited your CodePen to let you understand what I'm saying http://codepen.io/anon/pen/gWYPqV

I think that offset-#{size}0 should exist to allow the user to stop the propagation to above.

**Comment by fega** [comment]
Yeah, I made an error in the codepen

**Comment by fega** [comment]
Thanks @ArnaudPl

**Comment by ArnaudPl** [comment]
I just see now that the issue #4410 fixed this. It is just not already in the version 0.98.1. Problem fixed, sorry for this.
