### ISSUE TITLE
Allow to refresh a dropdown (dropdown and material selects)

### ISSUE THREAD

**Issue by 255kb** [Dogfalo/materialize#452]
When dynamically updating select's options or dropdown items, the dropdown created on the fly by the framework is not refreshed. 
It would be useful to allow one to do `material_select(true)`, where `true` would trigger a simple refresh of the element rather than a full rendering.

**Comment by carlosperate** [comment]
+1 
Just encountered this issue as well, a way to trigger a refresh would be very helpful.

**Comment by carlosperate** [comment]
I know you guys must be really busy, but I would really appreciate it if this could get looked into. Any eta for this feature fix?

**Comment by Cerealkillerway** [comment]
+1

**Comment by alexjp** [comment]
+1 for using it with Ember JS

**Comment by Dogfalo** [comment]
Added in a06d9a4bcf4b7913e1e58c5fa417bbb7b3279c46

**Comment by carlosperate** [comment]
I just downloaded the latest master, and recalling the plugging in my case will refresh the old `ul` element, but it still creates an additional one without removing the old.
So the main difference is that while before only the new `ul` element contained the correct value, now both do.

**Comment by Dogfalo** [comment]
I'm not seeing a second `ul` being created when I reinitialize.

**Comment by carlosperate** [comment]
In my case I replace the `select` element in the DOM using javascript. So the document already has a `select` menu, which then I get by Id and replace with a new `select` element with the same `name` and `id`. I do this by doing something along the lines of this:
```
oldSelect.parentNode.replaceChild(newSelect, oldSelect);
$('select').material_select();
```

**Comment by brendanoh** [comment]
For anyone working in Ember.js who finds this issue in the future here is how I solved the re-rendering of the select. Wrap it in a `{{#with}}{{/with}}`.

```
 {{#with filteredBusinessTypes as |types|}}
  <div class="row">
    <div class="input-field col s12">
      {{md-select content=types value=businessType label="Specific Business Type" prompt="Please choose..." optionLabelPath="content.name" optionValuePath="content"}}
    </div>
  </div>
 {{/with}}
```

Without the with it never updates. With it - it does.

**Comment by ramintagizade** [comment]
not possible with selects . It will close the window when added new options .
