### ISSUE TITLE
Question: How to unbind collapsible event listeners?

### ISSUE THREAD

**Issue by jacobq** [Dogfalo/materialize#4520]
I am making a long-lived application (e.g. electron desktop app) that uses materialize-css. When I render a view with a collapsible component it runs `$('.collapsible').collapsible();` after the element has been inserted. What should I run when it's about to be removed from the DOM? 

Looking at the current code it looks like I need to do something like `$('.collapsible').off('click.collapse')`, but it would be nice if I could so something like `$('.collapsible').collapsible(false);` If there's not already a way to do this, would you please consider adding one? (Otherwise it may lead to user code coupling to implementation details, like my example calling `.off`)

(I think this only applies to dynamically generated fields since [`.collapsible` is automatically called on DOM ready](https://github.com/Dogfalo/materialize/blob/b336331e851d5903ce684b55cfd3049042d87b28/js/collapsible.js#L173-L175).)

**Comment by jacobq** [comment]
This relates to https://github.com/Dogfalo/materialize/issues/4522

**Comment by acburst** [comment]
Added in 79cb76e
