### ISSUE TITLE
Destroy methods for major javascript components

### ISSUE THREAD

**Issue by acburst** [Dogfalo/materialize#4522]
In general, we do not have destroy methods for many of our javascript components which are helpful for more dynamic sites. I'll start a checklist of plugins that could use destroy methods.

- [x] Collapsible
- [x] Carousel
- [ ] Dropdown
- [ ] Modal
- [ ] Tabs
- [ ] Parallax
- [ ] Materialbox

Pull Requests welcome!

**Comment by fega** [comment]
what about the help-wanted label?

**Comment by acburst** [comment]
Collapsible destroy added in 79cb76e

**Comment by tomscholz** [comment]
See https://github.com/Dogfalo/materialize/pull/2428

**Comment by tomscholz** [comment]
Carousel destroy added in https://github.com/Dogfalo/materialize/commit/22c972980288dc07cb2ae16cd183f1c5035b9e95
