### ISSUE TITLE
Carousel is breaking when auto play is applied

### ISSUE THREAD

**Issue by rockyru** [Dogfalo/materialize#4523]
### Description
Hi, why is it that carousel is breaking when I click one of the indicators while there is an autoplay function to slide the carousel items.

### Repro Steps
Here's the living example of the bug http://bwsi.com.ph/. Try to click on the indicators until the carousel breaks.

Here's the js function to autoplay the carousel items : 
`window.setInterval(function() {
				$(".carousel").carousel('next')
			}, 4500);`

The rest, I'm using the default config for carousel (fullwidth) and I've forced the height of the carousel to 500px.

### Screenshots / Codepen
![screen shot 2017-04-11 at 9 49 04 am](https://cloud.githubusercontent.com/assets/13403945/24889364/201c3c7a-1e9c-11e7-86b6-2f0dc827f7e8.png)

**Comment by acburst** [comment]
If you are doing autoplay, the correct way to implement something like this would be to refresh the interval whenever the user interacts with the carousel. So you might have to add an extra handlers to refresh your global interval when changing slides.

**Comment by rockyru** [comment]
Oohh. I see. Thanks @acburst

**Comment by rockyru** [comment]
Is there any plan of implementing an autoplay for carousel in the future?

**Comment by magzoa** [comment]
Do you have an example of a handlers for it? I am using version 0.97 and it is difficult for me to update the whole project
