### ISSUE TITLE
Fixed sidenav on smaller screens

### ISSUE THREAD

**Issue by lukaskollmer** [Dogfalo/materialize#4525]
Hi!

I want the sideNav to be fixed and open on all screen sizes - not just large ones. How can I achieve this?

**Comment by lukaskollmer** [comment]
Just out of curiosity, why was this closed without any comment whatsoever? @tomscholz

**Comment by tomscholz** [comment]
Sorry that I didn't told you whats wrong with this issue, it must have been late that evening ;) Back to your issue. Can you provide some kind of screenshot or somethings else to illustrate what you mean? Just a quick reminder: If the sidenav is fixed and open at all time, then on mobile it isn't possible to view the site correctly. Thats why it is currently not possible without editing the source files. You can ask over at stackoverflow or gitter for help ;) gitter.im/Dogfalo/materialize
