### ISSUE TITLE
Selects with AngularJS not working

### ISSUE THREAD

**Issue by geovannyAvelar** [Dogfalo/materialize#4529]
When i try to fill a select using AngularJS the select is rendered like an empty element. 

By example, this code is not working to me. The select is rendered, but options aren't showed.

`        
<select ng-model="event.profile" ng-options="profile.name for profile in profiles" name="profile">
</select>
`

I checked and the profiles list isn't emtpy.

I'm using the latest release(v0.98.1)

**Comment by fega** [comment]
Usually Is extremely difficult solve this kind of questions without a live example, are you colling `$('select').material_select()`  after the render (or equivalent) hook?

**Comment by tomscholz** [comment]
@geovannyAvelar Have a look at [this community made](https://krescruz.github.io/angular-materialize/#select) materialize-angular version. Maybe it helps

**Comment by tomscholz** [comment]
Closed due inactivity, feel free to reopen it if it is still necessary.
