### ISSUE TITLE
Valign not working in Safari

### ISSUE THREAD

**Issue by Dogfalo** [Dogfalo/materialize#453]
![](http://i.imgur.com/cSJ1BVu.png)

**Comment by acburst** [comment]
Fixed in 84a8a7468c7529fcabaab0cc586b84cb5191f85c

**Comment by cskiwi** [comment]
Not working in IE9 (30/05/2015)

![image](https://cloud.githubusercontent.com/assets/847540/7414524/acb0d328-ef53-11e4-9f8c-8e5c696871f6.png)
