### ISSUE TITLE
Responsive menu content overlay when responsive menu is opened OR closed

### ISSUE THREAD

**Issue by boyanabo** [Dogfalo/materialize#4532]
### Description
Hi, I am doing my new portfolio site and i stuck on the responsive menu. 
I am going to send my code and screenshots of my site. Hope you can help me. 

![open](https://cloud.githubusercontent.com/assets/23018980/24978448/1c5829a8-1fa7-11e7-80c2-8116622c906d.jpg)
![screensh](https://cloud.githubusercontent.com/assets/23018980/24978449/1c5f4198-1fa7-11e7-913d-4a5a42bc58f4.jpg)

https://codepen.io/bojanaboki/pen/KmKZGw

**Comment by tomscholz** [comment]
I don't have the time to sort this wibadidibadidu code. Please create a proper [codepen](https://codepen.io/pen?template=KWJWKe) or this issue will be closed due violatining our contributing guidlines

**Comment by boyanabo** [comment]
Sorry for that. I update my issue with codepen link.

**Comment by fega** [comment]
But, what is the problem that you need to solve?

**Comment by boyanabo** [comment]
This id="js-overlay" content doesn't open when I click on the Menu.  I pushed this window to show because I wrote data-state="open", but it should be change by clicking on the Menu.

**Comment by tomscholz** [comment]
@boyanabo Your code has nothing todo with materialize itself
