### ISSUE TITLE
sidenav not clickable in combination with fixed navbar

### ISSUE THREAD

**Issue by DanielRuf** [Dogfalo/materialize#4533]
### Description
The sidenav in a fixed navbar is covered by the element with the transparent background and not clickable due to zindex issues

### Repro Steps
Create a fixed navbar with a sidenav and open the sidenav in a small view

### Screenshots / Codepen

https://codepen.io/anon/pen/ZKEvwp

![image](https://cloud.githubusercontent.com/assets/827205/24981560/9026b580-1fdd-11e7-81f5-0f07cb5b4a43.png)

**Comment by fega** [comment]
quick work around put the menu out of the div

https://codepen.io/fega/pen/ZKEovb

**Comment by tomscholz** [comment]
Have a look [here](https://github.com/Dogfalo/materialize/pull/4482)

**Comment by DanielRuf** [comment]
Ah ok, different markup and not just the wrapper. The code was from the demo template and added the `navbar-fixed` class like described in the documentation. So the markup in the demo template and docs is not correct?

Thanks, will try this later.
