### ISSUE TITLE
Search icon in nav search bar animates out of the text box

### ISSUE THREAD

**Issue by nowakca** [Dogfalo/materialize#4535]
### Description
The scene: Sidebar layout, with a title section, a search bar, and some section links
Lead actor: Magnifying glass icon in the search field

Action: The page renders as expected initially, with the icon in the left of the search field.  But it very quickly animates up out by a couple rows worth.  Using latest version of Chrome, Firefox and Safari on Mac OS 10.12.4.

### Repro Steps
The issue is reproduced here (with lots of fluff removed): https://codepen.io/nowakca/pen/jmOzev

In code pen, the animation may complete before rendering is complete, but the end result is the same... the magnifying glass has floated up into the teal title area.

Reproduces independently of JQuery version.
And the behavior goes back to the MaterializeCSS 0.95.1 in some for (here, it happens when you click in the search field, but shortly after it doesn't wait for a click)

**Comment by bassie1995** [comment]
You're missing the class `label-icon` on your label for the search field, that fixes it.

Apart from that your markup is a bit off from what [the navbar page](http://materializecss.com/navbar.html) says: your label is indented without needing to be and I'm not seeing a `nav` tag or `nav-wrapper` class, for example.

**Comment by GGolov** [comment]
It's a hack, but it works more or less...
Add this inside the form tag:
```
<div class="input-field row">
  <i class="material-icons prefix" style="margin-left: 2vh">search</i>
  <input id="search" type="search" class="col s12" placeholder="Search for an address">
  <i class="material-icons">close</i>
</div>
```
![result](https://cloud.githubusercontent.com/assets/1353711/25003512/08fd18ba-2050-11e7-8b3e-65da61a2ae01.jpg)

**Comment by nowakca** [comment]
I don't know how many times I compared my code to the sample that I copy-pasted it from originally and I still didn't see the label-icon, that did the trick.  Change blindness is apparently a thing.  Thank you! 

As for the Navbar tags, yeah, I removed those to try to simplify the test case.  Now to start layering things back in, thank you!

**Comment by bassie1995** [comment]
Figured you removed it for testing when I read that haha!

I actually had this same issue yesterday, took me a few reads as well :)
