### ISSUE TITLE
How to use key/value in autocomplete

### ISSUE THREAD

**Issue by ericlormul** [Dogfalo/materialize#4539]
Hi,

Following is the current data structure for autocomplete data
```
    data: {
      "Apple": null,
      "Microsoft": null,
      "Google": 'http://placehold.it/250x250'
    }
```
key used as label, value used as source of a image. How can I disable the behavior of using value as image src? and use value for other purpose?

**Comment by fega** [comment]
It looks as something that you should implement by yourself

**Comment by matthenning** [comment]
Did you find a solution yet? I'm facing the same problem.

**Comment by maguon** [comment]
I'm facing the same problem.
