### ISSUE TITLE
Dropdown Not Closed on Item Click

### ISSUE THREAD

**Issue by lee011** [Dogfalo/materialize#4540]
### Description
When a dropdown item is clicked, the dropdown containing it does not close.

### Screenshots / Codepen
- Screen recording of this issue: https://drive.google.com/file/d/0B1u3kCIncHeNUXIxMEdvcmNLQmM/view?usp=sharing
- This issue is demostrated here: https://jsfiddle.net/0wvt8nx9/1/
- [The example in the documentation of dropdown](http://materializecss.com/dropdown.html) also demostrating this issue.

**Comment by fega** [comment]
working in 9.8.0 😞 

https://codepen.io/fega/pen/aWzWZL?editors=1111

**Comment by acburst** [comment]
Duplicate of #4409
