### ISSUE TITLE
Carousel not working v0.98.1

### ISSUE THREAD

**Issue by Tsyklop** [Dogfalo/materialize#4541]
### Description
Add a detailed description of your issue.

I copy carousel example from docs and paste on my web site (simply html file).
Connect script and css.

And i get this - Screenshot.
 
carousel have 0 height. If i remove transform attribute from carousel-item blocks - they become visible.

i try create codepen, but there work fine;

### Repro Steps
Layout the steps to reproduce your issue.

My html:

```
<html>
<head>
    <title></title>
    <link rel="stylesheet" href="./css/materialize.css"/>
    <script type="text/javascript" src="./js/util/jquery-3.2.0.min.js"></script>
    <script type="text/javascript" src="./js/util/materialize.min.js"></script>
</head>
<body>
<div class="carousel carousel-slider center " data-indicators="true">
    <div class="carousel-fixed-item center">
        <a class="btn waves-effect white grey-text darken-text-2">button</a>
    </div>
    <div class="carousel-item red white-text" href="#one!">
        <h2>First Panel</h2>
        <p class="white-text">This is your first panel</p>
    </div>
    <div class="carousel-item amber white-text" href="#two!">
        <h2>Second Panel</h2>
        <p class="white-text">This is your second panel</p>
    </div>
    <div class="carousel-item green white-text" href="#three!">
        <h2>Third Panel</h2>
        <p class="white-text">This is your third panel</p>
    </div>
    <div class="carousel-item blue white-text" href="#four!">
        <h2>Fourth Panel</h2>
        <p class="white-text">This is your fourth panel</p>
    </div>
    <script>
        setTimeout(function () {
            $('.carousel.carousel-slider').carousel({fullWidth: true});
        }, 200);
    </script>
</div>
</body>
</html>
```

Use this Codepen to demonstrate your issue. http://codepen.io/Dogfalo/pen/xbzPQV

### Screenshots / Codepen
Add supplemental screenshots or code examples. Look for a codepen template in our Contributing Guidelines.
![default](https://cloud.githubusercontent.com/assets/6783568/25041194/149a0eea-2117-11e7-8a6b-378d4dd394ca.png)

**Comment by tomscholz** [comment]
Works for me https://codepen.io/tomscholz/pen/XRJzGw?editors=1010 (Your code) 
Please try this html structure. Load the css files in the head and the js files at the of your .html
Like this: https://pastebin.com/cHSSMyLU

**Comment by Tsyklop** [comment]
@tomscholz I test in codepen and there works fine. I tyred html from pastebin - not working.
Screenshot:
![default](https://cloud.githubusercontent.com/assets/6783568/25041727/b3371a68-211a-11e7-8830-1dd56f58aa73.png)

**Comment by tomscholz** [comment]
@Tsyklop Try this one https://pastebin.com/VdYKJ90Z . This uses the cdn version

**Comment by Tsyklop** [comment]
@tomscholz work. How to make so that it was not necessary to specify the link? But simply a local address.
For js this is not a problem. But for css the problem. I remove the elements that I do not need from the style, and if I connect them via an external link, then I will not be able to remove what I do not need.

**Comment by tomscholz** [comment]
@Tsyklop you can compile your own customized version of materialize via sass.

**Comment by Tsyklop** [comment]
@tomscholz But it will not work. It does not work if I specify a local reference.

**Comment by Tsyklop** [comment]
@tomscholz Hi. can you help me?

**Comment by tomscholz** [comment]
1. Make sure, that you include jquery 2.1.4 **before** the materialize.js
2. Make sure that you have initialized the carousel:
```
    $(document).ready(function(){
      $('.carousel').carousel();
    });
```
3. Make sure that you don't get any errors

**Comment by Tsyklop** [comment]
@tomscholz Yes, all these conditions are met.

**Comment by DanielRuf** [comment]
And all the scripts are at the bottom of the body?

**Comment by Tsyklop** [comment]
@DanielRuf No. in the head.

**Comment by DanielRuf** [comment]
They should be at the bottom of the body, see the get started and themes in the docs.

**Comment by Tsyklop** [comment]
@DanielRuf I try this - not working;

**Comment by DanielRuf** [comment]
```
<head>
//include materialize.css
<body>
//HTML code
//…
//include jQuery
//…
//include materialize.js
//…
//the JS code for carousel
//…
</body>
```

Please follow the get started page and check the console of your browser.

Also provide a codepen with your code if you can not solve this.

http://materializecss.com/getting-started.html

**Comment by Tsyklop** [comment]
@DanielRuf In codepen al work because `css` and `js` include with external link. but to me it does not fit.
Details are above.

**Comment by DanielRuf** [comment]
@Tsyklop this has nothing to do with this. Please check your browser console and the path / URL of the included files. Never use `//:` while on localhost, use `https://` or `http://`.
