### ISSUE TITLE
Chips not displaying the image

### ISSUE THREAD

**Issue by colingg** [Dogfalo/materialize#4546]
### Description
When switching to the 0.98.2 version my chip images stopped appearing

### Repro Steps
https://jsfiddle.net/zwmw81n3/
https://codepen.io/anon/pen/WjvRPX

**Comment by DanielRuf** [comment]
It seems `elem.image` was removed but not added again.

See https://github.com/Dogfalo/materialize/commit/52c5b850a67df72c6ffa813917918fd39dce755f

@acburst

**Comment by acburst** [comment]
Merged #4490
