### ISSUE TITLE
FileField after a lot of inputs makes the whole form clickable.

### ISSUE THREAD

**Issue by sridoodla** [Dogfalo/materialize#4558]
### Description

Not quite sure what I'm doing wrong but adding a file field at the end of the form sort of affects the whole page. No matter where I click, the file field gets activated.

### Repro Steps

Use this Codepen to demonstrate your issue. http://codepen.io/Dogfalo/pen/xbzPQV

### Screenshots / Codepen
Add supplemental screenshots or code examples. Look for a codepen template in our Contributing Guidelines.

http://codepen.io/anon/pen/NjxJbK

**Comment by DanielRuf** [comment]
Sounds related tohttps://github.com/Dogfalo/materialize/issues/1930

See my comments for a possible fix.

**Comment by Thanood** [comment]
Like shown in @DanielRuf's comment in #1930, this can be solved by setting `position: relative;` on the file-input button's parent. Also, I had a similar issue at work where `font-size` created a bigger box than expected. I set `font-size: 1px;` in addition to the above.
