### ISSUE TITLE
<ol> does not display decoration

### ISSUE THREAD

**Issue by gmerrall** [Dogfalo/materialize#456]
If you use <ol> in a page with or without type attribute the decoration associated with the tag does not display. That is to say, 1. or a. etc does not appear. 
e.g.
    `<ol> 
      <li>One</li>
      <li>Two</li>
    </ol>`

If I move the content outside of sections or the container the issue persists. Removing the link to the CSS resolves the issue

**Comment by gmerrall** [comment]
There's no entries related in the CSS
li {
  list-style-type: none; }

and 
ul {
  list-style-type: none; }

The li entry is the responsible party. I can fix my problem my commenting it out but not sure what impact this will have as currently not making heavy use of the library

**Comment by Dogfalo** [comment]
Fixed in 27baebc9af9ab3c1335d6c071149544d547816fd
