### ISSUE TITLE
Chip - auto complete not working after upgrade to v0.98.2

### ISSUE THREAD

**Issue by baole** [Dogfalo/materialize#4560]
It works with v0.98.0

Actual code:
    $selected_users.material_chip({
        data: selected_data,
        autocompleteData: search_data,
        placeholder: 'Type a name to add an attendant',
        secondaryPlaceholder: 'Type a name to add an attendant'
    });

**Comment by tomscholz** [comment]
Post a codepen to illustrate the problem and make read the [ISSUE_TEMPLATE](https://github.com/Dogfalo/materialize/blob/master/ISSUE_TEMPLATE.md) and the [CONTRIBUTING](https://github.com/Dogfalo/materialize/blob/master/CONTRIBUTING.md) guidelines. Otherwise we won't look into this.

**Comment by baole** [comment]
It's my bad. We should use 'autocompleteOptions' instead of 'autocompleteData'.

**Comment by DanielRuf** [comment]
It was changed to `autocompleteOptions.data` but this breaking change was not mentioned in the changelog but the docs were updated. http://materializecss.com/chips.html#properties

https://github.com/Dogfalo/materialize/commit/05c48b15c3e2f908769aaeb66db2834349a3831b

cc @acburst when he is back next week
