### ISSUE TITLE
Can't get Materialize work with Angular 4.

### ISSUE THREAD

**Issue by EddyVinck** [Dogfalo/materialize#4563]
I'm pretty new to this so please bear with me as I have been trying for hours.

I installed Angular 4 and Materialize.css using npm. How do I get the click effects on buttons and such to work? I cannot figure it out on my own.

I have seen some things on the internet but there doesn't seem to be a clear solution to this problem. It's also my first time using npm so I might be forgetting something.

**Comment by smileytechguy** [comment]
I'm not familiar with angular's specifics, but shouldn't you be able to use something along the lines of 
```js
$("#myButton").click(function() {
  // do stuff
});
```
where you have a button with id `myButton`

**Comment by tomscholz** [comment]
Also make sure to check out https://github.com/krescruz/angular-materialize

**Comment by EddyVinck** [comment]
I will take a look at your suggestions soon. It's getting late so I will give that a shot sometime in the weekend. Thanks guys.

**Comment by scote** [comment]
We did a wrap of Materialize with Angular 4 at https://github.com/sherweb/ng2-materialize.
Not all features have been wrapped.

**Comment by fega** [comment]
@scote thanks!
