### ISSUE TITLE
select layout add a option to config expand below the input,not cover the input.

### ISSUE THREAD

**Issue by believeZJP** [Dogfalo/materialize#4565]
### Description
Add a detailed description of your issue.
Hope the result like browser default expand.

### Repro Steps
Layout the steps to reproduce your issue.

Use this Codepen to demonstrate your issue. http://codepen.io/Dogfalo/pen/xbzPQV

### Screenshots / Codepen
Add supplemental screenshots or code examples. Look for a codepen template in our Contributing Guidelines.

**Comment by tomscholz** [comment]
Provide a real description. Screenshots examples etc

**Comment by tomscholz** [comment]
Provide a real description. Screenshots examples, full description of your issue, etc. Feel free to reopen once you done that

**Comment by believeZJP** [comment]
default is like this:
![image](https://cloud.githubusercontent.com/assets/15198091/25275047/cff85436-26c5-11e7-9d20-48fda18c587f.png)


what I want is like this:
![image](https://cloud.githubusercontent.com/assets/15198091/25300309/09ce13e8-273f-11e7-9fad-7e6f31d661f4.png)



Hope to add d config param to resolve this.
