### ISSUE TITLE
$.fn.autocomplete conflicts with many frameworks like jQuery.ui

### ISSUE THREAD

**Issue by qantumthemes** [Dogfalo/materialize#4567]
### Description
The name of the function conflicts with similar functions or other frameworks, like for instance tinyMCE or jQuery UI, as $.fn.autocomplete is too generic and should be changed to materialize_autocomplete

### Repro Steps
Load materialize forms.js within any form with also the jQuery UI or tinyMCE libraries, then call the autocomplete for another framework, and it will crush because it has the same function name, but other functions expects different parameters.

Just call it in another way to make it compatible with many more apps.
Thanks!

**Comment by fega** [comment]
@qantumthemes I agree with you

**Comment by qantumthemes** [comment]
Thanks @fega :) it took me about half hour to find the issue, what I don't understand is why the function was not already prefixed as instead **$.fn.material_select** which is the one right after the autocomplete.

I truly love Materialize and I use it for everything, so I just want to suggest a small improvement to increase the compatibility with the rest of old and consolidated js around.

Thanks!

**Comment by DanielRuf** [comment]
See #4574

**Comment by tomscholz** [comment]
also see https://github.com/Dogfalo/materialize/pull/1763

**Comment by acburst** [comment]
Autocomplete was been rewritten in alpha v1.0.0. You can also use the native javascript init to bypass any conflicts.
