### ISSUE TITLE
waves-circle messes up the shape of the element

### ISSUE THREAD

**Issue by UncleWalt** [Dogfalo/materialize#4568]
Hi,

as documentation suggests, I added "waves-circle" to a floating button:
http://codepen.io/anon/pen/PmNMNo

waves-circle seems to change the shape of the element, in this case the button becomes smaller and the icon isn't centered anymore.

Also, I do not see any difference compared to the default waves effect. Is this the right use case for circular waves??

**Comment by Dogfalo** [comment]
You can just add waves-effect,, waves-circle just enforces a circular shape for elements that are not already circular
