### ISSUE TITLE
how to import materialize.js in angular4?

### ISSUE THREAD

**Issue by joebnb** [Dogfalo/materialize#4569]
some error happend when import scripts into angular4 project.
index.html
```
<body>
    <my-app>loading our story of mayday</my-app>
	<script src="https://code.jquery.com/jquery-2.1.1.min.js"></script>
	<script src="//cdnjs.cloudflare.com/ajax/libs/materialize/0.98.2/js/materialize.min.js"></script>
        <script src="http://localhost:9090/bundle.js"></script>
</body>
```
in TSfile
```
declare var $:any;
declare var window:any
@Component({
  selector: 'md-nav',
  templateUrl: './library/header/navigator.template.html'
})

export class NavigatorComponent { 
	constructor(){
		setTimeout(()=>{
                        console.log($);
			console.log($(".button-collapse"));
			window.$(".button-collapse").slideNav() //or $(".button-collapse").slideNav() 
		})
	}
}

```
the $ or window is correctly consoled .and window.$(".button-collapse").slideNav() work in chrome debug(global),but it cannt run in angular4 component context,please teach me how can i solove this problem？

![image](https://cloud.githubusercontent.com/assets/1646883/25289804/baefe68e-26fd-11e7-8bec-e5a2c5982e6c.png)

**Comment by joebnb** [comment]
and why materialize installed by npm but not working like npm packages,it does not support import

**Comment by tomscholz** [comment]
Duplicate(s):
https://github.com/Dogfalo/materialize/issues/4563
https://github.com/Dogfalo/materialize/issues/4270
And have a look here:
https://github.com/Dogfalo/materialize/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aopen%20npm

**Comment by joebnb** [comment]
duplicate but no solves

**Comment by scote** [comment]
@joebnb Take a look at https://github.com/sherweb/ng2-materialize. We did a wrap with Angular 4.
