### ISSUE TITLE
scroll top not working in mobile view with swipe tab

### ISSUE THREAD

**Issue by vishalk367** [Dogfalo/materialize#4570]
### Description
Scroll TOP/Bottom and no any anchor tag works within in tab content with swipe tab.

### Repro Steps
Layout the steps to reproduce your issue.

Use this Codepen to demonstrate your issue. http://codepen.io/Dogfalo/pen/xbzPQV

### Screenshots / Codepen
Add supplemental screenshots or code examples. Look for a codepen template in our Contributing Guidelines.

**Comment by tomscholz** [comment]
Provide a real description. Screenshots, codepen, examples, full description of your issue, etc. Feel free to reopen once you done that.
