### ISSUE TITLE
Increase tabs swipe speed

### ISSUE THREAD

**Issue by vpezeshkian** [Dogfalo/materialize#4571]
My question is how to increase [tabs](http://materializecss.com/tabs.html) swipe speed, I can see that when swiping tabs the end is very slow, I want it to be smoother and tabs change faster.

I'm using `v0.98.0` for swipeable tabs, since `v0.98.2` does not work properly.

Thanks.

**Comment by DanielRuf** [comment]
The transition? You can't https://github.com/Dogfalo/materialize/blob/master/js/tabs.js#L31

**Comment by DanielRuf** [comment]
Possible solution would be to change the value, recompile the files using Grunt and use the new file.

**Comment by tomscholz** [comment]
Closed due inactivity, feel free to reopen it if it is still necessary.
