### ISSUE TITLE
Compile MaterializeCSS files

### ISSUE THREAD

**Issue by DanZeuss** [Dogfalo/materialize#4573]
### Description
I cannot reproduce the compilation according described on the Wiki running `grunt monitor`.

### Repro Steps
Run grunt monitor in the MaterializeCSS folder. It returns: **Fatal error: Unable to find Gruntfile.**

**Comment by tomscholz** [comment]
I guess you downloaded the folder from the materializecss.com website? Yeah, thats not possible. To be able to compile files, you need to clone or download the repo from github. Then it will work

**Comment by DanZeuss** [comment]
@tomscholz I used npm to install it. Is it possible?

**Comment by tomscholz** [comment]
Can you check if there is the file Gruntfile.js in the directory where you run the command?

**Comment by DanZeuss** [comment]
There isn't, so, I believe that is really impossible to run grunt when download it using npm. Thanks @tomscholz
