### ISSUE TITLE
Add user in transifex repo

### ISSUE THREAD

**Issue by pmargreff** [Dogfalo/materialize#4578]
### Description
Hey @Dogfalo @acburst, could you add me on Transifex repo? I already sent an email (two weeks ago) to the mail on readme file, but nobody answers me or added to the project.

I can help with Portuguese as well some Spanish too.  

Thanks for your attention.

**Comment by Dogfalo** [comment]
I just added you.

**Comment by pmargreff** [comment]
Thanks, in the future you can add some members like reviewers too, it could improve the quality and the project status is 0% reviewed.
