### ISSUE TITLE
$.fn.tooltip conflicts with many frameworks like jQuery.ui

### ISSUE THREAD

**Issue by stap123** [Dogfalo/materialize#4579]
### Description
The name of the function conflicts with similar functions or other frameworks, like for instance jQuery UI, as $.fn.tooltip is too generic and should be changed to materialize_tooltip

Just read #4567 and have come accross this issue in the past with the tooltip. Maybe the same should be carried out with this as well?

Thanks

**Comment by Dogfalo** [comment]
Maybe jQuery UI should prefix their plugin names then? In any case we'll prefix in v1

**Comment by stap123** [comment]
@Dogfalo completely agree! That's great. Could probably leave out the passive aggressive part of your reply tho. :/
