### ISSUE TITLE
Wave buttons outline bug in the Firefox

### ISSUE THREAD

**Issue by svartalf** [Dogfalo/materialize#458]
Steps to reproduce:
1. Open page http://materializecss.com/waves.html in the Firefox (for me it is a 28.0 linux)
2. Click any white button
3. Wait for wave ending
4. Move cursor out of the button bounds
5. Outline border is visible now

It is not reproducible for any blue buttons.

![button-wave-bug](https://cloud.githubusercontent.com/assets/1279564/5738957/e53b8d12-9c03-11e4-95ac-132a3abc1d94.png)

**Comment by Dogfalo** [comment]
Fixed in e063cf454e67944e4943b5ae2e6a01d4444e4869
