### ISSUE TITLE
MD Motion Animation Exhibited in Demo Website

### ISSUE THREAD

**Issue by pingshunhuangalex** [Dogfalo/materialize#4583]
Just wonder how the MD motion animation is achieved in Materialize's [Demo web page](https://themes.materializecss.com/pages/demo) when users click on a card.

I noticed no matter where the image is, when I click on it, it'll follow a curved path and smoothly moved to the same position. Just wonder if there's any easy way to achieve this and if this can be added to the MaterializeCSS collection. Thanks.

**Comment by bassie1995** [comment]
I looked at it and stumbled across this: https://themes.materializecss.com/pages/docs.

Top one :)

**Comment by pingshunhuangalex** [comment]
Awesome. Thanks @bassie1995 Exactly what I need. I'll dig into it. Thanks.

**Comment by acburst** [comment]
Yes, this is separate and not part of MaterializeCSS

**Comment by pingshunhuangalex** [comment]
@acburst So...
1. Is this plugin created and maintained by MaterializeCSS team?
2. Is this plugin available for the public to purchase?
3. If it is, how much will it cost?
4. The demo pages have some glitches (img out of the position when interacted in Chrome). Will it be fixed?
5. The demo page is broken in IE11. Things flashes and out of the position. Will it be fixed if the plugin is for sale?

Thanks.

**Comment by FoxInFlame** [comment]
While the main demo gallery page loads moves things nicely, the "Docs" page has glitches regarding the width of the white textbox.

How much will this plugin cost?

**Comment by tomscholz** [comment]
1. It is maintained by @acburst 
2. You can buy it [here](https://themes.materializecss.com/)
2. It costs 19$
4. You can send him an E-Mail regarding the bugs, [here](materializethemes@gmail.com)
