### ISSUE TITLE
select option layout issue

### ISSUE THREAD

**Issue by believeZJP** [Dogfalo/materialize#4584]
default select is like this:
![image](https://cloud.githubusercontent.com/assets/15198091/25275047/cff85436-26c5-11e7-9d20-48fda18c587f.png)

what I want is like this:
![image](https://cloud.githubusercontent.com/assets/15198091/25300309/09ce13e8-273f-11e7-9fad-7e6f31d661f4.png)

Hope to add d config parameter to resolve this.

**Comment by DanielRuf** [comment]
Resolve what exactly? No dropdown shows the first value twice. This is not how a dropdown should look like imho.

**Comment by believeZJP** [comment]
the Choose your option is a extra option,it can be deleted, if it deleted,then the first option is coverd on the select,I hope the option is below the select dom.

**Comment by DanielRuf** [comment]
That is not right. The first one is `disabled` and why should the option be visible twice?

**Comment by believeZJP** [comment]
in most case ,the first one disabled is not list ,most time is only select option ,like 
select 
 option 1
 option 2 
 option 3

 not like below:

select 
 option choose your option.
 option 1
 option 2 
 option 3

**Comment by DanielRuf** [comment]
I see no issue with the current implementation. Your example how you think it should look like is not correct (duplicate first entry).

See https://material.io/guidelines/components/menus.html#menus-behavior

![screenshot_20170424-095812](https://cloud.githubusercontent.com/assets/827205/25327557/d91bd7f2-28d4-11e7-898f-fadd750af5c1.png)

**Comment by believeZJP** [comment]
OK,I understand! The current implement is to avoid showing option twice ,so that the option can be list only once in any time, even if the option is checked.

**Comment by DanielRuf** [comment]
Exactly.

**Comment by believeZJP** [comment]
Thank you very much!
