### ISSUE TITLE
Click/Touch is not working on carousel item.

### ISSUE THREAD

**Issue by upreddy** [Dogfalo/materialize#4586]
I want to use Fancybox on carousel images, Facybox will open image on touch/click on mobile devices. But materialize js preventing touch/click functionality in tap function (On mobile devices only). How can we use fancybox effects with materializecss?

**Comment by DanielRuf** [comment]
Do not mix with other libraries/scripts which conflict with Materialize.

Materialize has its own MD spec lightbox http://materializecss.com/media.html

**Comment by upreddy** [comment]
Thank you @DanielRuf . It's working fine. I am unable to zoom the image with MD spec lightbox. Other libraries like fancybox providing zoom, flip, rotate, etc..

**Comment by DanielRuf** [comment]
Not sure if this should be possible by the MD spec.

Anyway, please fill out the issue template and provide a codepen so we can further discuss about this.

**Comment by DanielRuf** [comment]
Afaik the click / touch event is captured by the carousel and not bubbling up / propagating.

**Comment by upreddy** [comment]
If we comment e.preventDefault() line in tap() (line no. 7879 in materialize.js file), it will bubble up. I am using fancybox by commenting the same.

**Comment by DanielRuf** [comment]
You mean https://github.com/Dogfalo/materialize/blob/master/js/carousel.js#L343?

This solves it and is the only needed change?

**Comment by upreddy** [comment]
Yes. I am sorry to make you confused on line number.

**Comment by DanielRuf** [comment]
No problem. You just mentioned the line number in the generated file, not in the actual source file of the component ;-)

**Comment by DanielRuf** [comment]
Probably duplicate of https://github.com/Dogfalo/materialize/issues/4380
