### ISSUE TITLE
How can I get the value of select option?

### ISSUE THREAD

**Issue by Gunjan4542** [Dogfalo/materialize#4589]
### Description
Add a detailed description of your issue.

### Repro Steps
Layout the steps to reproduce your issue.

Use this Codepen to demonstrate your issue. http://codepen.io/Dogfalo/pen/xbzPQV

### Screenshots / Codepen
Add supplemental screenshots or code examples. Look for a codepen template in our Contributing Guidelines.

**Comment by DanielRuf** [comment]
Related: https://github.com/Dogfalo/materialize/issues/4582

Just use `.on('change'`  with `$(elem).val()`.

**Comment by DanielRuf** [comment]
Please always fork and fill out the codepen, you did not provide any code.
