### ISSUE TITLE
Collapsible on mobile

### ISSUE THREAD

**Issue by franckobe** [Dogfalo/materialize#4590]
### Description
Does anybody has a solution with the fact that when we click on a collapsible on a mobile, all collapsibles become black during a second as if we've selected them ? 

### Screenshot
![18136835_10213224426625679_320654923_n](https://cloud.githubusercontent.com/assets/11754497/25342351/1e1e1d56-290c-11e7-9770-ba796edad729.jpg)

**Comment by DanielRuf** [comment]
Does this change solve this?
https://github.com/Dogfalo/materialize/pull/4555/files

**Comment by franckobe** [comment]
I solve this with -webkit-tap-highlight-color: transparent; property. But I had to apply it on the parent element of the .collapsible. Because my .collapsible is in a .collection-item, so the effect was on the .collection-item. 

Thank you

**Comment by DanielRuf** [comment]
Can you provide a simple codepen so we can track down where we have to set this extly so wr can publish this fix in the next version?

**Comment by franckobe** [comment]
Here is a codepen with a simple collapsible : https://codepen.io/anon/pen/gWwJbb
And with my personnal code with collapsible in a collection : https://codepen.io/anon/pen/wdzbWz

**Comment by tomscholz** [comment]
Closed due inactivity. Feel free to reopen it, if it's still necessary.
