### ISSUE TITLE
FeatureDiscovery - location is changed on large screens / resolutions

### ISSUE THREAD

**Issue by Voyteck0** [Dogfalo/materialize#4591]
FeatureDiscovery lands in incorrect places on high-resolution screens / non-standard window ratios. 
Basic code shown here:
http://codepen.io/voyteck0/pen/EmgmPO

On Pen the button and FeatureDiscovery does not reposition itself incorrectly, but still the FeatureDiscovery is shown upside-down (without roundings visible). The repositionning problem was notified only on Chrome 58.0.3029.81 (64-bit) - Edge, IE and Mozilla looks correctly. Also the problem was spottend on 4k monitor with normal DPI (non-retina) on window sized 1415x1426 (repositioning happens once window reaches 1426 - on 1425 position is still correct).

The problem that might be connected is that even when position is still correct - the contents (text) of FeatureDiscovery falls down from viewport - isnot visible, but can be tracked by resising window or using developer tools.

**Comment by DanielRuf** [comment]
@inventti-leonardo any ideas as you have also worked more with the taptarget code? I guess some wrong calculations are problematic too.

**Comment by inventti-leonardo** [comment]
@Voyteck0, @DanielRuf 
I got it , try fix this changing the line 

`<div class="tap-target-content orange ascent-3">` 

to 

`<div class="tap-target-content">`

The class `tap-target-content` can not be filled with background-color because its only a layer text
http://codepen.io/anon/pen/mmrqQK

**Comment by Voyteck0** [comment]
Well - works in Pen, unfortunatelly does not solve initial problem that I am having problems in replicating on Pen...
@inventti-leonardo - maybe a session during which I would give you access to main page would help ? Would you be able to propose some timeslot for that ?

**Comment by inventti-leonardo** [comment]
@Voyteck0 

I can not understand your problem, can you take some prints?

It is difficult to prevent the best fit by default, because depends the size of text that you show inside a tap-target and other css applied in text that changes the size of text.

You can create your own media queries to control the size of tap-targets, and try best fit for screens that your users needs.

```
@media only screen and (max-width: 1280px) {
.tap-target-wrapper {
width:1280px;
height:1280px;
}
}

@media only screen and (max-width: 1920px) {
.tap-target-wrapper {
width:1920px;
height:1920px;
}
}
```

This helps you @Voyteck0 ?

**Comment by tomscholz** [comment]
Closed due inactivity. Feel free to reopen it, if it's still necessary.
