### ISSUE TITLE
Select - caret not clickable if i add background to input

### ISSUE THREAD

**Issue by gunnargj** [Dogfalo/materialize#4592]
### Description
Is this an issue with Materialize?
I add an white background to .select-dropdown class and z-index to .caret class. The caret is not clickable.
Any idea how to fix that?
![caret](https://cloud.githubusercontent.com/assets/8318581/25346978/f0bf25b0-2908-11e7-9e5c-1a4cd28a5ed8.jpg)

https://codepen.io/gunnargj/pen/ZKpvYO

**Comment by DanielRuf** [comment]
Can you provide a codepen with your code?

**Comment by gunnargj** [comment]
https://codepen.io/gunnargj/pen/ZKpvYO

**Comment by DanielRuf** [comment]
So far I can see in the sourcecode, that the click is just caught on the input but not on the caret: https://github.com/Dogfalo/materialize/blob/master/js/forms.js

(`$newSelect` is the input text field and it has focus and click listeners). You could add a click listener to the caret which calls `.trigger('open')` on the generated text input (traverse up using `jQuery.closest()`).

Normally the caret lies behind an element which catches the click event.

**Comment by DanielRuf** [comment]
What about $select-background in the variables?

https://github.com/Dogfalo/materialize/blob/master/sass/components/forms/_select.scss

https://github.com/Dogfalo/materialize/blob/master/sass/components/_variables.scss

**Comment by gunnargj** [comment]
I tried this:
$( ".pickuplocation .caret" ).click(function() {  
  $( ".pickuplocation .select-dropdown" ).trigger( "click" );
  return false; 
});

That works, except when i click on something in the dropdown, it doesn't get selected

**Comment by gunnargj** [comment]
I also tried to change $select-background variable to #fff then the caret is hidden except when i add z-index to it and then it's not clickable

**Comment by DanielRuf** [comment]
Seems we have to change this and also catch the click on the caret by default? Background be behind the caret imho.

**Comment by gunnargj** [comment]
Sounds good - do you have any workaround for me?

**Comment by DanielRuf** [comment]
Currently not, I am not on my place.

@fega @tomscholz do you have some ideas for the best solution?

**Comment by acburst** [comment]
Fixed in c44a4af08902ae209fff690fd84f33041056d424
