### ISSUE TITLE
Labels not raising on click

### ISSUE THREAD

**Issue by dkudriavtsev** [Dogfalo/materialize#4593]
### Description
Rails, `materialize-sass` gem, labels not raising on click.

### Repro Steps
Go to http://inventory.dk0.us

**Comment by DanielRuf** [comment]
Seems the JavaScript code is not initialized / executed?

Because when I add this again manually it works. The code is in your js file.

![image](https://cloud.githubusercontent.com/assets/827205/25351534/3374a7ca-2929-11e7-8140-942d502cb113.png)

**Comment by dkudriavtsev** [comment]
Oh wow, never thought of that, trying it now. Thanks!

**Comment by dkudriavtsev** [comment]
Placing JS at the end of the page does not resolve the issue.

**Comment by fega** [comment]
@dkudriavtsev you're using turbolinks? you need to use initialise after the DOM is reloaded again with `Materialize.updateTextFields();`

**Comment by dkudriavtsev** [comment]
@fega Says "not a function"

**Comment by dkudriavtsev** [comment]
Also happens on first page load

**Comment by fega** [comment]
you're usig jquery 1, Materialize need Jquery needs 2+

**Comment by dkudriavtsev** [comment]
@fega OMG THANK YOU I HAVE BEEN TRYING TO GET THIS SOLVED FOR MONTHS
