### ISSUE TITLE
Is there an "onBeforeSelectActive" function?

### ISSUE THREAD

**Issue by Native-Coder** [Dogfalo/materialize#4595]
I'm using the materialize select options to allows people to add products to a shopping cart. I would like make it so that they can't add the same item twice accidentally. (There's a separate quantity field anyway) To do this, I was hoping to update the options in the select right before the select actually opens. But I can't even do so much as capture a click on the select.

Does materialize keep the click events from propagating on the select elements or something?

**Comment by DanielRuf** [comment]
> I was hoping to update the options in the select right before the select actually opens.

Updating the original select and its options and then reinitializing the select should work.
Combine this with `$('select').on('change')`.
Do you have any code so far?

**Comment by Dogfalo** [comment]
Would recommend adding disabled attribute to the option then updating the select.

**Comment by Native-Coder** [comment]
Interesting solution @DanielRuf How would you capture the open event? 

Now, Lets say that the user has selected an option. And all of a sudden get a message from the server that the available inventory has updated. In theory, I would

Disable all selects
Update the options for the selects
Re-Initialize the selects

Would this not remove the users previously selected item?

The issue is that the number of selects varies. They click an "add item" button, and a new select is added so that they can choose which inventory item needs to go in that slot. It's kind of like a rudimentary shopping cart. But we have a very small inventory, so the drop down works.

**Comment by DanielRuf** [comment]
@Native-Coder get the values, reset and the the values again?

**Comment by Native-Coder** [comment]
that's quite ugly, but it'll have to do. And I'm assuming that there's an "open" event that fires right before the select opens?

**Comment by DanielRuf** [comment]
https://github.com/Dogfalo/materialize/issues/4595#issuecomment-296802384
https://github.com/Dogfalo/materialize/blob/master/js/forms.js#L620

**Comment by tomscholz** [comment]
Closed due inactivity. Feel free to reopen it, if it's still necessary.
