### ISSUE TITLE
How can I display data-icon from selected option in select input?

### ISSUE THREAD

**Issue by rockoff** [Dogfalo/materialize#4599]
### Description
Input(.select-dropdown) displays text from selected option(li.active), but doesn't display data-icon from it. How can I fix it? 
I didn't have problems with rendering icons in options, I want to render it in select root element, but I don't have any idea how can I do that.

**Comment by DanielRuf** [comment]
Can you provide a codepen of the code that you tried so far?

**Comment by DanielRuf** [comment]
I guess we just use `jQuery.text()` and so we only get the text from the original option elements.

Is an icon in a select option part of the md specs @tomscholz?

**Comment by rockoff** [comment]
I want to create select with icon like this
https://image.ibb.co/g9TDGQ/017.png

**Comment by fega** [comment]
Hello @rockoff as far as I know this wasn't implemented yet, so you should create your own implementation. maybe the `after` pseudo that should do the job

(something similar it's planned, but I cannot provide a release date)
