### ISSUE TITLE
$.fn.toast conflicts with many frameworks like toastr, jquery-toast

### ISSUE THREAD

**Issue by stap123** [Dogfalo/materialize#4600]
### Description
The name of the function conflicts with similar functions or other frameworks, like for instance Toastr or jquery-toast-plugin, as $.fn.toast is too generic and should be changed to materialize_toast

Just read #4567 and have come accross this issue in the past with the toast. Maybe the same should be carried out with this as well?

Thanks

**Comment by Thanood** [comment]
I didn't even know that this function exists.. 😮 
I'm using `Materialize.toast(...)` as mentioned in the docs. Maybe `$.fn.toast` could even be removed since it's not documented?

**Comment by DanielRuf** [comment]
Or prefixed like some other functions, `$.fn.material_toast`.

**Comment by stap123** [comment]
Alright I'm being an idiot, this doesn't exist. It was the css I had issues with. Apologies for creating this erroneously :(
