### ISSUE TITLE
Is it possible to create expanded popout items as seperate entities?

### ISSUE THREAD

**Issue by Native-Coder** [Dogfalo/materialize#4604]
I would like to use the popout accordion style as a card. Instead of having it only pop out when clicked on, have multiple items already "popped out" as if they were their own cards. is it possible without creating dozens of separate ULs?

**Comment by fega** [comment]
@I cannot understand you :/

**Comment by Native-Coder** [comment]
Sorry. I'll try to elaborate. Look at the "Popout" accordion shown [here](http://materializecss.com/collapsible.html). You see how the second one is "Popped out"? It's expanded, has a shadow, etc...

I would like to re-create that style separately. That is to say, I'd like to use the "popped out" style _outside_ of a collapsible. For instance, the style would be great for certain types of "Cards". 

I guess if I could just have more than one open at a time it would serve the same purpose...
![style](https://cloud.githubusercontent.com/assets/22647295/25498956/75a74bc0-2b4f-11e7-90ea-9690f4e87397.PNG)

**Comment by fega** [comment]
Hello @Native-Coder, I believe that you have two options

1) is implement by yourself a copy of the collapsible, looking in the collapsible CSS or clone it quickly with SASS.
2) use `data-collapsible="expandable"` to open more of one collapsible at the same time, but if  you don't need the collapsible behavior, you should use the first approach

**Comment by tomscholz** [comment]
Closed due inactivity. Feel free to reopen it, if it's still necessary.
