### ISSUE TITLE
Chips in Chips-Autocomplete can't be deleted via clicking

### ISSUE THREAD

**Issue by pingshunhuangalex** [Dogfalo/materialize#4606]
First I want to apologize that I can't provide a codepen or code example to isolate the issue cuz things are all connected in my Vue project and it's kind of too overwhelming.

If it's ok, could you please test the chips-autocomplete component to see if chips can be deleted via clicking the x on it. On my side, everything works fine except for this clicking behavior, and chips can be deleted via backspace.

Another issue I noticed is that when I click on my input area, it won't get focused (won't add focus class). It's only working when I really click on the starting region of the input area (where the actual input element sits).

The above 2 issues could be tied. Since the example on your website works perfectly, I'm guessing there's something wrong on my side, but I just can't pin-point it. Any advice/guess would be greatly appreciated. Thanks.

**Comment by DRoet** [comment]
The chip autocomplete seems to be working fine in my vuejs project, mine looks like this:

```
<template>
	<div class="chips chips-autocomplete"></div>
</template>
```

```
<script>
export default {
	mounted () {
		$(() => {
			$('.chips-autocomplete').material_chip({
				autocompleteOptions: {
					data: {
						'Apple': null,
						'Microsoft': null,
						'Google': null
					},
					limit: Infinity,
					minLength: 1
				}
			})
		})
	}
}
</script>
```

**Comment by pingshunhuangalex** [comment]
Thanks so much @DRoet for testing things out for me.
Testing in Vue project directly helps me narrow down the possible faulty area significantly. It turns out that the issue was caused by a @click.stop I set in a parent component previously. Thanks again.

**Comment by DRoet** [comment]
No problem, glad you have found the issue 👍
