### ISSUE TITLE
Not getting correct hidden tab height

### ISSUE THREAD

**Issue by Drvanon** [Dogfalo/materialize#4608]
### Description
I want to make all my tabs the same (max) height, so I call $(<insert the div here).height, but it is not the real height as when it is visible.

### Repro Steps
As clear as I could possibly get it
https://codepen.io/Drvanon/pen/XRNOGy?editors=1010

**Comment by DanielRuf** [comment]
https://codepen.io/anon/pen/Qvdreb

First toggle the visibility, get the height an toggle again.
Getting the height of a height:auto and hidden element is never very reliable.

**Comment by tomscholz** [comment]
Closed due inactivity. Feel free to reopen it, if it's still necessary.
