### ISSUE TITLE
Active indicator on tabs with side-nav

### ISSUE THREAD

**Issue by DoctorFitch** [Dogfalo/materialize#4610]
Hi, I wish you could help me here, here is my problem : 
I have a side-nav with a materialize tabs in it, but the problem is when I open my side-nav the active indicator of materialize tab take the whole length of the side-nav width. 

The only way for me to get back to the original length of the activate indicator is to click on a tab and it came back to normal.

**Here is the original position** 
![image](https://cloud.githubusercontent.com/assets/11684473/25443930/ad774902-2aa9-11e7-8829-7b25a68cbebb.png)

**After opening** 
![image](https://cloud.githubusercontent.com/assets/11684473/25443907/96ce255e-2aa9-11e7-9573-a25dfb80f0c7.png)

**After clicking on the first tab** 
![image](https://cloud.githubusercontent.com/assets/11684473/25443952/c103ccca-2aa9-11e7-9c91-0d9488c995b3.png)

Thank you in advance to any one who may be able to give me some ideas.

**Comment by DanielRuf** [comment]
Can you provide a simple codepen so we can reproduce and test it better?

**Comment by tomscholz** [comment]
Closed due inactivity. Feel free to reopen it, if it's still necessary.
