### ISSUE TITLE
js control select value

### ISSUE THREAD

**Issue by believeZJP** [Dogfalo/materialize#4614]
【select】
1. select option 1 is selected,
![image](https://cloud.githubusercontent.com/assets/15198091/25466536/d9ce16a6-2b3b-11e7-9998-41b7403686cd.png)

2. when I want to change the selected option by js， 
    $select.val('2')

but it didn't work,it still is 1 selected.
How to do with it ?

**Comment by tomscholz** [comment]
Duplicate https://github.com/Dogfalo/materialize/issues/4582

**Comment by believeZJP** [comment]
$select.val('2');
$('select').material_select();

just need to add a init method.
