### ISSUE TITLE
Velocity error while trying to display toast message

### ISSUE THREAD

**Issue by silvioiannone** [Dogfalo/materialize#4615]
I'm trying to display a message inside a toast using:

    Materialize.toast('Deals synchronized.', 3000);

But when the animation is supposed to begin and end the following message is returned:

> Velocity: First argument ([object HTMLDivElement]) was not a property map, a known action, or a registered redirect. Aborting.

I'm building my application using Laravel Mix (therefore Webpack) and this is the only thing not working.

**Comment by DanielRuf** [comment]
It should work: http://codepen.io/anon/pen/dWNebv

**Comment by silvioiannone** [comment]
Could it be a problem appearing when using Webpack?

**Comment by DanielRuf** [comment]
Possibly. The error comes from Velocity as it seems. did you integrate it separately?

**Comment by silvioiannone** [comment]
No, I'm just loading jQuery using Webpack config like this:

    plugins: [
        new webpack.DefinePlugin({
            // Required by materialize-css
            $: 'jquery',
            jQuery: 'jquery',
            'window.$': 'jquery',
            'window.jQuery': 'jquery',
        })
    ]

**Comment by DanielRuf** [comment]
related: https://github.com/Dogfalo/materialize/issues/305

**Comment by silvioiannone** [comment]
I'm not loading the JS files using the script tag. I'm loading the materialize-css JS using

    require('materialize-css');

I also tried requiring Velocity before materialize-css but I still have the same issue.

**Comment by DanielRuf** [comment]
Velocity is bundled in materialize.js

**Comment by tomscholz** [comment]
Closed due inactivity. Feel free to reopen it, if it's still necessary.

**Comment by turtlegood** [comment]
I have the exact same error!
