### ISSUE TITLE
onBlur event not triggered on dropdown close

### ISSUE THREAD

**Issue by Codebreaker101** [Dogfalo/materialize#4616]
### Description
As the title says, the event onBlur is not triggered when closing the multi-select dropdown. The event fires once on page load but not again after

### Repro Steps

**Working - browser default** - http://jsfiddle.net/m4ge2c3L/2/
 **Not working - materialize** - http://jsfiddle.net/77bdofd9/2/

**Comment by DanielRuf** [comment]
Catch the `close` event
https://github.com/Dogfalo/materialize/blob/master/js/forms.js#L652

http://codepen.io/anon/pen/xdgjyL
