### ISSUE TITLE
Dropdown popup list position in modal window

### ISSUE THREAD

**Issue by gewisser** [Dogfalo/materialize#4618]
### Description
The problem with the positioning of the pop-up list in the modal window.

### Repro Steps
https://codepen.io/anon/pen/verdMq

### Screenshots / Codepen
Add supplemental screenshots or code examples. Look for a codepen template in our Contributing Guidelines.
![image](https://cloud.githubusercontent.com/assets/5417292/25490829/b991dcca-2b76-11e7-9aa7-f94f5e0181d3.png)

**Comment by gewisser** [comment]
Can anyone be able to rework the component for a certain payment with the addition to the common repository?

You just need to implement a pop-up menu on top of everything and place it relative to the button and so that the menu display never depended on the location of the calling element in the DOM tree ...

**Comment by sumarlidason** [comment]
probably not an optimal solution; the current functionality assumes the direct parent to the button will contain the `scrollTop` data it needs for positioning. Here I am just passing the element that does have the correct data `scrollParent`: https://github.com/DigitalGlobe/materialize/commit/071ef855862f0a9b8fce1e4911ab7638e0085b7a

**Comment by gewisser** [comment]
sumarlidason, thank you! It works.

```javascript
$('.dropdown-button').dropdown({
   scrollParent: $('.modal').children().first()
});
```

**Comment by gewisser** [comment]
tomscholz, why the issue was closed. Is this fix already in the main branch?

**Comment by sumarlidason** [comment]
@tomscholz

**Comment by Dogfalo** [comment]
Fixed in v1-dev

**Comment by gewisser** [comment]
Yes, I saw that the component was redesigned in the new version, but when the new version comes out, I can not quickly adapt my set of [vuejs components](https://github.com/gewisser/materializecss-vuejs-component) that are used in many projects. In this regard, I very much ask you to issue the last v0.100.3 with the fixes.
