### ISSUE TITLE
Ajax Autocomplete doesn't work

### ISSUE THREAD

**Issue by IamHenryValdez** [Dogfalo/materialize#4619]
I'm trying to perform an autocomplete with an Ajax Request that fill the data options.
It doesn't work well. In fact it does the ajax request and execute the function. But it keep erasing the 
.dropdown-content element list.
The element list only append if I press the delete button.
    
    // Capture element on KeyUp
    $(document).on("keyup", "input.async-autocomplete", function(event) {

 		var $this = $(this);

 		if (event.which == 38 || 
 			event.which == 40 || 
 			event.which == 37 || 
 			event.which == 39 || 
 			event.which == 13) {
 			return;
 		}
 		// If the data href is there, it means we want to load the list from the server
 		if (typeof $this.data("href") !=  "undefined) {
 			
                        //  I ommitted the json parse. for this exemple but the data format is valid
 			$.ajax({
				url    : $this.data("href"),
				type   : "post",
				data   : "value=" + $this.val(),
				success: function(data) {
					$this.autocomplete({
						data     : data.autocomplete,
						limit    : 10,
					});
				}
 			}); // End Ajax
 			
 		}

 	});

**Comment by DanielRuf** [comment]
I guess you have to call `.trigger('close')` or `.trigger('open')` on the generated autocomplete after setting the new data.

**Comment by dellert** [comment]
@IamHenryValdez you can see here https://github.com/dellert/autocompleteajax

**Comment by IamHenryValdez** [comment]
Awesome! Thank you guys
