### ISSUE TITLE
Mobile Navbar doesn't work if Fixed Header used!

### ISSUE THREAD

**Issue by ajrehman** [Dogfalo/materialize#462]
If you declare the NAVBAR as a "fixed header", then after resizing for responsive by inserting this code:

 $(".button-collapse").sideNav();

the sidebar doesn't work, the gray overlay stays on top, making the sidebar links un-clickable.

If you remove the sidenav functionality, everything works fine. Any ideas?

**Comment by MaazAli** [comment]
Running into this issue as well. If I remove the fixed nature, it fixes it. However, the sidenav in general is fairly buggy for me.

**Comment by beeb** [comment]
Works fine for me in 0.95

**Comment by KBoisvert** [comment]
Just tried with the new version css and the collapse doesn't work anymore, which class have been changed?  I'm using the code in the website.  With the old version it works fine but without the navbar-fixed.

**Comment by acburst** [comment]
Should be fixed in 0.95
