### ISSUE TITLE
Scrolling disabled after close modals

### ISSUE THREAD

**Issue by rayriffy** [Dogfalo/materialize#4622]
When I click at picture it have 'MORE' button to open modal with bottom-sheet but after close modal I can't scrolling to anywhere. I don't know why it happened.
I reproduce issue here https://testtube.rayriffy.com/mat_issue

**Comment by DanielRuf** [comment]
The overflow value is removed, see https://github.com/Dogfalo/materialize/blob/master/js/modal.js#L34-L38

I will try to find a fix.

**Comment by DanielRuf** [comment]
Use the following code in the [complete callback](http://materializecss.com/modals.html) as workaround

```JavaScript
$('body').css({
    overflow: 'visible'
});
```

@tomscholz should we set `visible` in the code at https://github.com/Dogfalo/materialize/blob/master/js/modal.js#L34-L38 as this is the default value in CSS?

**Comment by rayriffy** [comment]
Yes, problem resolved. Thanks

**Comment by rayriffy** [comment]
Closing issue

**Comment by piotrkunicki** [comment]
I have still problem with that.. what fix should I use, because here: https://github.com/Dogfalo/materialize/commit/41f04c33acb8a808224d5c673649a9e4e86901cd#diff-452a8aa82569876ba89deba84331011c I can see scrolling is reverted.

**Comment by piotrkunicki** [comment]
I'm using version 1.0.0 latest release and still have problem. ```overflow: hidden;``` is not removed when I'm closing the modal.
