### ISSUE TITLE
DatePicker to support picking of year

### ISSUE THREAD

**Issue by tianhai82** [Dogfalo/materialize#463]
Currently, there is no other way to select a 'year' that is far away from the default date other click the 'next month' icon many many times.

**Comment by CoDEmanX** [comment]
True, not very convenient.

In Android 5, you can click on the year to change mode to year input:

![screenshot_2015-01-21-14-02-29](https://cloud.githubusercontent.com/assets/1309249/5836455/5432559e-a176-11e4-8d2b-1cd77461c303.png)

In day input mode, the months can be scrolled vertically btw:
![screenshot_2015-01-21-14-03-02](https://cloud.githubusercontent.com/assets/1309249/5836466/86ebf012-a176-11e4-8272-6c84c5214735.png)

**Comment by surfermicha** [comment]
Hope that this function will be added soon

**Comment by Dogfalo** [comment]
Added in 9979c14978aaa92f2857f9f0d5bf40d65b5c30ee
