### ISSUE TITLE
Modals

### ISSUE THREAD

**Issue by adsprosto** [Dogfalo/materialize#4632]
### Description
In modals after insert Carousel it is working not сorrectly
Error in translateX
After resize body Carousel is working normal
Fix please :) 👍

**Comment by DanielRuf** [comment]
Can you provide a codepen with an example where this happens?

**Comment by adsprosto** [comment]
https://codepen.io/anon/pen/eWRBjd

**Comment by DanielRuf** [comment]
Take a look at the ready callback for the modal: https://codepen.io/anon/pen/pPwRvE

**Comment by adsprosto** [comment]
https://codepen.io/anon/pen/eWRBjd
Thanks, but main problem with height in modal of @carousel carousel-slider@

**Comment by DanielRuf** [comment]
The padding (top and bottom)?

**Comment by adsprosto** [comment]
What?)

**Comment by tomscholz** [comment]
He means the height of the carousel is to big

**Comment by adsprosto** [comment]
i not understand

**Comment by tomscholz** [comment]
> Thanks, but main problem with height in modal of @carousel carousel-slider@

@adsprosto You have to explain what your problem is! Otherwise you can ask over at stackoverflow or gitter.

**Comment by adsprosto** [comment]
https://codepen.io/anon/pen/eWRBjd
height 0

**Comment by tomscholz** [comment]
@DanielRuf's codepen works. https://codepen.io/anon/pen/pPwRvE You have to use the ready callback of the modal to initialize the carousel.

**Comment by adsprosto** [comment]
I understood it, but height 0, how fix this?

**Comment by adsprosto** [comment]
ok i things it is problem)

**Comment by adsprosto** [comment]
I understood it ok not problems)

**Comment by adsprosto** [comment]
close issue)
