### ISSUE TITLE
Mobile modals

### ISSUE THREAD

**Issue by adsprosto** [Dogfalo/materialize#4633]
### Description
On mobile device in modals btn close closed modal sometimes on second click

**Comment by DanielRuf** [comment]
Not reproducible with the example from your other issue (Chrome 56 on Android 7 here).

Please always provide a codepen and some information about the used browser.

**Comment by tomscholz** [comment]
Not reproducible on: Win10 64bit Chrome, Edge, Firefox), Mac OsX 11.11(Chrome, Safari, Firefox) as well on ios and Android 7

**Comment by adsprosto** [comment]
ok i thought it is problem)
