### ISSUE TITLE
modal  starttingTop

### ISSUE THREAD

**Issue by believeZJP** [Dogfalo/materialize#4637]
when I use **modal** component,
startingTop doesn't work well.

![image](https://cloud.githubusercontent.com/assets/15198091/25646920/bf364aa8-2fef-11e7-96c9-d45ad8fe0991.png)

**Comment by rayriffy** [comment]
there is a mistake. you forget ; at the end
startingTop:'80%',  >>  startingTop:'80%';

**Comment by rayriffy** [comment]
remove , at the end, sorry.

**Comment by tomscholz** [comment]
Please be more specific what your problem is and [create a proper codepen](https://codepen.io/pen?template=YVwVqV).

**Comment by believeZJP** [comment]
I tried, but it's not working~~
https://codepen.io/believezjp/pen/zwEdBa

**Comment by fega** [comment]
Also, I believe that this feature need more documentation.

**Comment by tomscholz** [comment]
The modal components has been refactored and this issue fixed
