### ISSUE TITLE
Card reveal width bug

### ISSUE THREAD

**Issue by svartalf** [Dogfalo/materialize#464]
It doesn't scale well for a full width card.
`width: 100%;` for `.card .card-reveal` possibly should help.

![card-reveal](https://cloud.githubusercontent.com/assets/1279564/5754028/d77aa258-9ca3-11e4-87b0-827fa140052a.png)

**Comment by zigy** [comment]
yea width: 100% will fix it.

**Comment by Dogfalo** [comment]
Fixed in 21bf3457e9ac47eb501f23a5ae6f1648a4c69656
