### ISSUE TITLE
Dropown menu and Scrollspy not working

### ISSUE THREAD

**Issue by iRelease** [Dogfalo/materialize#4640]
Hi everyone,

I'm trying to use dropdown navbar and scrollspy.js working together, but it seems not working...

Howewer I already setup my anchor and use link with scrollspy and its works fine.

How can I do to solve my problem?

There is a screen of my code actually, scrollspy is initialized in my scripts..

**Comment by tomscholz** [comment]
I don't have the time and no desire to do that. Please be more specific what your problem is and [create a proper codepen](https://codepen.io/pen?template=YVwVqV). And please, never post a "screenshot of your code".

**Comment by iRelease** [comment]
When I use the fonction "dropdown" in the navbar, my anchor doesn't work with scrollspy to get a smooth scroll in the web page .

Howewer if my anchor is in the navbar but not in the dropdown it work.

I try to make work the smooth scroll with an anchor in a dropdown..

**Comment by tomscholz** [comment]
> Please be more specific what your problem is and [create a proper codepen](https://codepen.io/pen?template=YVwVqV).

As above.

**Comment by fega** [comment]
Closed due inactivity, feel free to reopen it if it is still necessary.
Please provide a way to reproduce it. like a [codepen](https://codepen.io/fega/pen/BWeZaG)
