### ISSUE TITLE
Separate modules / scripts from Grunt jobs

### ISSUE THREAD

**Issue by gitarno** [Dogfalo/materialize#4641]
The problem is the management of modules and support of _Gruntfile_ files, which end up generating conflicts over time when added new features to it.

For this it would be interesting to use a manager to dynamically load the configuration scripts of the grunt modules, leaving in _Gruntfile.js_ only the specific tasks. With this would give to have:

```
+- Gruntfile.js
+- grunt-tasks/
|    +- clean.js
|    +- connect.js 
|    +- sass.js
|    +- ....
```
 
When there was change in any of these configurations, would be isolated.
An NPM module that does this is: ```load-grunt-config```.  What do you think?

**Comment by Dogfalo** [comment]
We haven't really had a problem with conflicts in Grunfile.js.
