### ISSUE TITLE
Active collapsible not working

### ISSUE THREAD

**Issue by Robouste** [Dogfalo/materialize#4643]
### Description
`.active` class added to `.collapsible-header` not working. `.active` is removed from dom

### Repro Steps
[codepen](http://codepen.io/anon/pen/MmvPZY)

### Temporary fix
```JS
$('.collapsible').collapsible('open', 0);
```

**Comment by DanielRuf** [comment]
Do you mean this? https://github.com/Dogfalo/materialize/issues/4375#issuecomment-288558471

It was fixed in 0.98.2

**Comment by DanielRuf** [comment]
See http://codepen.io/anon/pen/YVxRed

**Comment by Robouste** [comment]
I was in `0.98.1`, after upgrading to `0.98.2`, it's now working as expected.

Thank you
