### ISSUE TITLE
Dropdown not working if clicked on material-icons 

### ISSUE THREAD

**Issue by Robouste** [Dogfalo/materialize#4645]
### Description
If we put a material-icons inside the trigger and we click on it, the dropdown is not working

### Repro Steps
[codepen](http://codepen.io/anon/pen/OmjaNG)

Click on the gear icon to test

**Comment by DanielRuf** [comment]
Catch the click on the icon and deliver the click event to the dropdown.

Is this example / case described in our docs (dropdown with icon)?

**Comment by Robouste** [comment]
Do you have an example ? 

I tried this : 
```js
$(".dropdown-button .material-icons").bind('click', function() {
    $(this).closest(".dropdown-button").trigger('click');
})
```

But it's not working. I also tried with `.click()` instead of trigger.

The selector is working, if I do a `.remove()` instead of trigger, the anchor disappear.

**Comment by tomscholz** [comment]
This was fixed in 0.98.2 
See: https://codepen.io/anon/pen/gWxQqY

**Comment by DanielRuf** [comment]
Try this: http://codepen.io/anon/pen/wdqQVG

**Comment by Robouste** [comment]
Thanks but upgrading to 0.98.2 worked :)
