### ISSUE TITLE
Materialize and TinyMce conflict 

### ISSUE THREAD

**Issue by franckobe** [Dogfalo/materialize#4646]
Hello, 

There is a conflict between TinyMce and MaterializeCss, when i want to insert link or image, the tinymce modal isn't large enough to display content. 
I didn't find where is the conflict to solve it properly. 

Here is a codepen sample : https://codepen.io/anon/pen/rmzoRR

And how it is including MaterializeCss: 
![capture](https://cloud.githubusercontent.com/assets/11754497/25699775/ee9e531e-30c4-11e7-823f-9c0b76dfe912.PNG)

How it is supposed to be : 
![capture2](https://cloud.githubusercontent.com/assets/11754497/25699785/fb234842-30c4-11e7-843a-53194464a428.PNG)

**Comment by franckobe** [comment]
Solved with that 

input.mce-textbox{
            width: auto;
            background: #fff;
            border: 1px solid #c5c5c5;
            display: inline-block;
            -webkit-transition: border linear .2s, box-shadow linear .2s;transition: border linear .2s, box-shadow linear .2s;
            height: 28px;
            resize: none;
            padding: 0 4px 0 4px;
            white-space: pre-wrap;
            color: #333;
        }

**Comment by mrfanatic** [comment]
hi @franckobe i'm having the exact issue with TinyMCE. Where do you used that css on your project? tinymce or materialize?

**Comment by mrfanatic** [comment]
Here is the TinyMCE fiddle link: http://fiddle.tinymce.com/6Ufaab

**Comment by Dogfalo** [comment]
http://fiddle.tinymce.com/6Ufaab/1
