### ISSUE TITLE
materialize multiple select cutting text when we choose all options

### ISSUE THREAD

**Issue by kushalpatel2010** [Dogfalo/materialize#4647]
### Description
when we choose all options, then options are not displayed properly

### Repro Steps
Layout the steps to reproduce your issue.

My issue. http://codepen.io/kushalpatel2010/pen/MmEove

**Comment by tomscholz** [comment]
That's actually not a bug, it's intentional. You can scroll through them.
![kapture 2017-05-05 at 8 17 12](https://cloud.githubusercontent.com/assets/20381749/25735397/4a1a516a-316b-11e7-85ff-8ed858520e4c.gif)

**Comment by kushalpatel2010** [comment]
I can't able to scroll options from left to right,
