### ISSUE TITLE
Modal complete function callbacks stack with lean-overlay click

### ISSUE THREAD

**Issue by fdev** [Dogfalo/materialize#465]
When using multiple modals, or re-using a single modal, each time you call `openModal(options)` a new overlay is created with `id='lean-overlay'`. Because the old overlay is not removed or re-used the old click handlers defined using `options.complete` get called again.

Either the overlay should be removed when the modal is closed, or the attached click event handler should be overwritten by the new modal.

A demonstration of the issue is available on http://plnkr.co/edit/yFRaQzVhUwkCLucydDAS?p=preview
As a workaround I currently have `$('#lean-overlay').remove()` at the end of my `options.complete` function.

**Comment by Dogfalo** [comment]
Good catch!
Fixed in 41763e00a337d326f24204255bb8d1dcf8a9dbf2
