### ISSUE TITLE
onAutoComplete callback not getting triggered

### ISSUE THREAD

**Issue by leenasn** [Dogfalo/materialize#4650]
I followed autocomplete setup as mentioned in the [Materialize CSS site](http://materializecss.com/forms.html).  But the onAutocomplete callback is getting fired. 

Use this Codepen to demonstrate your issue. 
http://codepen.io/leenasn/pen/ZKXxme

Can you help to fix the same? 

Thanks

**Comment by DanielRuf** [comment]
update to the latest release http://codepen.io/anon/pen/qmPYKG

**Comment by SurajMDurgad** [comment]
onAutocomplete not working even after updating to the latest release!

**Comment by DanielRuf** [comment]
Sure, it works. Take a look at https://codepen.io/anon/pen/jGoWmR which uses 0.100.2

**Comment by DanielRuf** [comment]
If not please provide a codepen with your code and check your browser console for any errors.

**Comment by SurajMDurgad** [comment]
Hi, I'm using coffescript.
This is the link to codepen -
https://codepen.io/SurajMDurgad/pen/dVEwKz

**Comment by DanielRuf** [comment]
@SurajMDurgad try `onAutoComplete` instead of `Autocomplete`.

**Comment by DanielRuf** [comment]
Also make sure to use uppercase `c`.

**Comment by SurajMDurgad** [comment]
Nope, same issue. I tried 'AutoComplete'.

**Comment by DanielRuf** [comment]
jQuery is not loaded in your example.

**Comment by SurajMDurgad** [comment]
$(document).ready ->

	countryArray = $('input.autocomplete').data("cities")
	dataCountry = {}

	i = 0
	while i < countryArray.length
		dataCountry[countryArray[i]] = null
		i++

	$('input.autocomplete').autocomplete
		data: dataCountry
		onAutoComplete: (val) ->
			console.log val
			return
		limit: 5
		minLenght: 5

This the actual code I'm using in my project!

**Comment by SurajMDurgad** [comment]
@DanielRuf Sorry about the jQuery. I've loaded it now!

**Comment by DanielRuf** [comment]
Meant lowercase c, sorry.

**Comment by DanielRuf** [comment]
https://codepen.io/anon/pen/KXLJba

It should work.

**Comment by SurajMDurgad** [comment]
When I implement in the project I face the above mentioned issues. I guess there might be some dependency issue from other modules. I think I'll try to implement some other gem.
Anyways thanks for replying on short notice.

**Comment by DanielRuf** [comment]
Did you include jQuery UI? Because this has its own `.autocomplete()` and conflicts with Materialize. Mixing UI libraries is never a good idea @SurajMDurgad

**Comment by Whypins** [comment]
How to use it in angular 4 by calling a rest url dynamically and display data to input as dropdown without using jQuery?

**Comment by DanielRuf** [comment]
@Whypins you mean some `.ajax()` replacement? Take a look at the native fetch API + polyfill.

**Comment by DanielRuf** [comment]
Or the query API in Angular. It should have its own solution for AJAx.

**Comment by Whypins** [comment]
Basically we are looking for solution like when user will type any character in material autocomplete input I will call [We can call a server rest url using angular and get a JSON data]. Now question is how will we set the value to **data** attribute of autocomplete instance dynamically.

**Comment by IranCanul** [comment]
I resolve a similar problem, I replace this:
```javascript
onAutocomplete: (input_caja_txt) => {
    // code here
}
```
with this:

```javascript
onAutocomplete: function(input_caja_txt) {
    // code here}
```

**Comment by DanielRuf** [comment]
> I resolve a similar problem, I replace this:

Well, this is ES6 so you just have to transpile it to ES5, then it also works in all browsers and so on. (fat) arrow functions are generally supported in ES6.
