### ISSUE TITLE
Dropdown does not work on macOS Safari

### ISSUE THREAD

**Issue by seandawn** [Dogfalo/materialize#4653]
### Description
Having a button that has a dropdown attached does not work using Safari. If you click the button the drop down briefly appears but then disappears. This also happens if you have hover enabled. Clicking and holding down on the button though does keep the menu there.

### Repro Steps
Create a button with a dropdown menu attached. Hover or click on the button whilst using Safari on a macOS based computer. Users have also reported this bug on Safari iOS.

**Comment by fega** [comment]
@seandawn, 
Please follow the [contributing guidelines](https://github.com/Dogfalo/materialize/blob/master/CONTRIBUTING.md) adding a codepen to reproduce the issue easily.

thanks
