### ISSUE TITLE
Request invitation to transifex translation project

### ISSUE THREAD

**Issue by dima74** [Dogfalo/materialize#4654]
Please, add me to transifex translation project. Email: diraria@yandex.ru, language: russian. Thank you a lot!

**Comment by dima74** [comment]
Please, add me. I think it isn't difficult. Thank you a lot.

**Comment by tomscholz** [comment]
There is nothing I can do about it. Keep sending him emails or write him on gitter.

**Comment by dima74** [comment]
Actually I received invitation few days ago. Thanks for it!
And I have one another question. When does translations appears on materializecss.com? I translate some strings few days ago (for example sentence `We are using...` from [here](http://materializecss.com/grid.html)), but on that page is still english sentence. Should translated strings pass some kind of review? Or what should happen in order to translated strings appear on materializecss.com? Thanks if answer something!

**Comment by Dogfalo** [comment]
The translations won't be updated immediately, Transifex has a manual push process that I perform once in a while. Thanks for helping out.
