### ISSUE TITLE
noUiSlider not materializing

### ISSUE THREAD

**Issue by ErraticFox** [Dogfalo/materialize#4655]
Hello, I'm using noUiSlider with Materialize and it looks the same other than the inner bar only being teal. The handles and default bar look the same though. In my html it's just a container > row > col > noUiSlider. Inspect element also shows that there's nothing trying to overwrite the styles of noUiSlider. I also looked into materialize.css and there's nothing that I seen that would overwrite noUiSlider.

The noUiSlider js and css links in the html file are placed under the materialize js and css links. What am I doing wrong? If the div needs a wrapper or specific class, I didn't see it in the documentation and I also seen a jsfiddle using noUiSlider materialize and it also didn't have a specific materialize class or wrapped in a specific tag.

html
```html
<div id="slider"></div>
```
js
```js
var slider = document.getElementById('slider');

noUiSlider.create(slider, {
    start: [20, 80],
    connect: true,
    step: 1,
    range: {
        'min': 0,
        'max': 100
    },
    format: wNumb({
        decimals: 0
    })
})
```

**Comment by tomscholz** [comment]
Read the documentation carefully! http://materializecss.com/forms.html#range

**Comment by ErraticFox** [comment]
I still need help, before posting this I worked on it for a hour. https://codepen.io/ErraticFox/pen/oWoZBQ is what I have and I used a older version of materialize with it and it worked perfectly fine, but using the current version it doesn't work.

**Comment by klombomb** [comment]
I am having the same issue?

**Comment by AlexVentura** [comment]
To do so it's pretty easy I just needed to override the following classes:

```
.noUi-connect {
  background: purple;
}
.noUi-horizontal .noUi-handle, .noUi-vertical .noUi-handle {
  background: purple;
}
.noUi-target.noUi-horizontal .noUi-tooltip {
  background-color: purple;
}
```

To get this:
![prueba](https://user-images.githubusercontent.com/13169164/27889950-68042e56-61b5-11e7-99c9-b8c16a89a7a4.png)

[Here it is my pen](https://codepen.io/alexventura/pen/pwZJMK)
I hope it could be useful for you!

**Comment by SoarynAC** [comment]
I'm having the same issue, and I'm using the materialize provided nouislider, but it looks default, and not materialize style

**Comment by AlexVentura** [comment]
@SoarynAC have you taken a look at my [pen](https://codepen.io/alexventura/pen/MqYboo)? It is working fine now even with the latest [MaterializeCSS](http://archives.materializecss.com/0.100.2) version `0.100.2`.

**Comment by SoarynAC** [comment]
@AlexVentura I have, I'm using version 1.0.0-rc.2 with the same setup you have, inside my page, but it just show the normal noUiSlider.
I'll try switching to version 0.100.2

**Comment by AlexVentura** [comment]
@SoarynAC Great!

**Comment by nofearOnline** [comment]
it half work to me in version 1 the slider is materialized but the handlers stuck on the left side and does not turn to toll tip which means it does not work

**Comment by phoebebright** [comment]
I too spent a long time on this and finally found where I went wrong.  noUiSlider DOES NOT take an input tag as the selection but a div.  ie. <input id="my_slider" .... does not work but <div id="my_slider" ... does.

**Comment by NPJigaK** [comment]
Can noUiSlider tooltips always be displayed?

Do I need to modify CSS or JS?

**Comment by Zaniyar** [comment]
Somehow the tooltip is not shown at all. No idea what I am missing. Tried every version from this thread.
