### ISSUE TITLE
Textarea wont auto resize in 0.98.2

### ISSUE THREAD

**Issue by haojia321** [Dogfalo/materialize#4657]
Hi 
Textarea will not auto resieze after upgrade to 0.98.2. It works after revert the version back to 0.98.1

**Comment by fega** [comment]
Please follow the [contributing guidelines](https://github.com/Dogfalo/materialize/blob/master/CONTRIBUTING.md)

and provide a way to reproduce it. like a [codepen](https://codepen.io/fega/pen/BWeZaG)

**Comment by DanielRuf** [comment]
Do you mean https://github.com/Dogfalo/materialize/issues/4613? Still not landed as release.
