### ISSUE TITLE
How to use waves with Tabs.

### ISSUE THREAD

**Issue by lee011** [Dogfalo/materialize#4658]
### Description
When a tab has `waves-effect` class applied, the tabs indicator will move to the start of the tabs container, instead of moving to the bottom of that tab.

### Repro Steps
1. Create some tabs and add `waves-effect` class to each tab, for example: 

````html
<ul class="tabs">
    <li class="tab waves-effect"><a href="#test1">Test 1</a></li>
    <li class="tab waves-effect"><a href="#test2">Test 2</a></li>
</ul>
<div id="test1" class="col s12">Test 1</div>
<div id="test2" class="col s12">Test 2</div>
````

2. Open the webpage and click on the tabs. The tab indicator will stay at the start of the tabs container.

### Screenshots / Codepen
Modified from the sample in the docs: https://jsfiddle.net/nu3sd4w0/2/ (For testing purpose, one of the tabs does not have `waves-effect` class applied)

**Comment by fega** [comment]
It works for me when I use waves inside the <a> tag.

https://jsfiddle.net/hojbec0m/

... but it should be in the documentation.

**Comment by DanielRuf** [comment]
Afaik the waves effect should be on the a tag.

**Comment by lee011** [comment]
Because I place the `waves-effect` class in the `<li>` tag since I started using Materialize and it works in older versions (< 0.98.0), so I thought that there is a bug when I upgraded to 0.98.2.

Thanks you all for helping me solve the problem.
