### ISSUE TITLE
How yo use Cards with Carousel

### ISSUE THREAD

**Issue by ajomadlabs** [Dogfalo/materialize#4659]
I wanted a carousel for cards. Is there any way to obtain it

**Comment by SerG-Y** [comment]
@ajomadlabs of course, it looks like 
`https://jsbin.com/rujejuhibi/5/edit?html,css,output`

**Comment by hiteshsahu** [comment]
Is this waht you want ?

https://codepen.io/hiteshsahu/pen/BmNePZ?editors=1000
