### ISSUE TITLE
All inputs on page being forcefully styled 

### ISSUE THREAD

**Issue by artur99** [Dogfalo/materialize#4661]
### Description
All the inputs on the page, even if they have no class, if the Materialize.css style is loaded, are styled with all those things: width, height, shadow, border-bottom on active, etc, etc.
So, if I'd want to build a different styled button, it would take a lot to replace the existing style (removing or replacing shadow, box-shadow, border, etc on all phases: hover, active, etc.)

So, it would be great if, by default, the input will have the default browser's style, and, if it would be inside an `.input-field` div, to get the materialize style.

### Screenshots / Codepen
https://codepen.io/artur99/pen/JNOqoV

**Comment by DanielRuf** [comment]
What about `.browser-default`?

**Comment by artur99** [comment]
@DanielRuf, but isn't that working only for the `<select>` tag?
It has no effect on the normal inputs, as I see: https://codepen.io/artur99/pen/JNOqoV

**Comment by fega** [comment]
@artur99 browser-default is the <select> tag.
also, personally, I like to have my inputs stylized by default because it means less markup and a material design look without effort.

**Comment by Braed** [comment]
browser-default does nothing to input tags. 
Styling can be applied to input tags with the following:
`
input[type=search]:focus {
    border-bottom: 1px solid #000;
    box-shadow: 0 1px 0 0 #000;
}
`

**Comment by fega** [comment]
@Braed yeah! thanks.
