### ISSUE TITLE
Tooltip and fixed action button

### ISSUE THREAD

**Issue by CorentinMic** [Dogfalo/materialize#4662]
When I put a tooltip on a fixed action button and when I scroll the page, the tooltip doesn't stay aside the action button.

![5rnhsfp](https://cloud.githubusercontent.com/assets/8841730/25797015/e65acb5a-33db-11e7-83c9-c70f226ae9b5.png)

Here is the codepen example : https://codepen.io/anon/pen/mmqYWE

**Comment by tomscholz** [comment]
Duplicate: https://github.com/Dogfalo/materialize/issues/1911 :)
