### ISSUE TITLE
Missing fonts in "main" description for bower.json

### ISSUE THREAD

**Issue by Ruluk** [Dogfalo/materialize#4663]
### Description
Since the framework requires certain fonts to be present, they should be included in the `"main"` property of the bower.json object. Only the CSS and JS files are being set at the moment. If any other file is required, it should be added too.

### Repro Steps
1. Use any tool or library that uses the `"main"` field of bower.json files to process the required files of the project.
1. Build your project.
1. Open the project in your browser.
1. Check your console. If not added otherwise, the files in "/fonts" should return 404.

**Comment by DanielRuf** [comment]
I've added a PR for this.

**Comment by DanielRuf** [comment]
I think we can close this @tomscholz
