### ISSUE TITLE
Halfway FAB with Card Reveal gets cutted

### ISSUE THREAD

**Issue by inseldesign** [Dogfalo/materialize#4664]
### Description
Halfway FAB on Card is "cutted" after card reveal is used.

### Repro Steps
Add a halfway FAB to card and add card reveal. Trigger the reveal and check the halfway fab button.

### Screenshots / Codepen
http://codepen.io/slichtenstein/pen/LyedWb

**Comment by DanielRuf** [comment]
I guess [this](https://github.com/Dogfalo/materialize/blob/master/js/cards.js#L19) is the issue

**Comment by DanielRuf** [comment]
Probably a working fix.
https://gist.github.com/DanielRuf/cb28243adf0707efd956ba3af9a7e0a4/revisions
http://codepen.io/anon/pen/JNMwyp

**Comment by inseldesign** [comment]
Thanks. This seems to work and should be somehow implemented 👍

**Comment by DanielRuf** [comment]
I've dded a PR.

**Comment by acburst** [comment]
Merged
