### ISSUE TITLE
Add a link solution for redirect to specific tab

### ISSUE THREAD

**Issue by zigy** [Dogfalo/materialize#467]
Please add the feature through which I can switch from any page to a specific tab.

*Example:*
Iam on *index.php* page and need to go on *about.php*, *second tab content* (#secondtab)
```<a href="about.php#secondtab">click</a>``` => this not working

Please add JS solution.. Thanx to help

**Comment by acburst** [comment]
This should be working.

If you go to this http://materializecss.com/tabs.html#test4
The 4th tab should be open
