### ISSUE TITLE
no toggle method for modal

### ISSUE THREAD

**Issue by huiyiqun** [Dogfalo/materialize#4670]
### Description
We can `open` or `close` modal from javascript, but there is no method `toggle` to open modal when it has been closed or close model when it has been opened.

What's more, there seems no attribute we could use to detect the state of the modal.

**Comment by DanielRuf** [comment]
The modal should have a class "open" if it is open

https://github.com/Dogfalo/materialize/blob/master/js/modal.js#L80

**Comment by tomscholz** [comment]
As @DanielRuf said.
