### ISSUE TITLE
Sudden problem with CORS

### ISSUE THREAD

**Issue by jschlieber** [Dogfalo/materialize#4671]
In my webapp using materialize for over a year now I suddenly have problems accessing fonts. I didn't change anything in my setup.

```
Access to Font at 'http://cdnjs.cloudflare.com/ajax/libs/materialize/0.97.8/fonts/roboto/Roboto-Regular.woff2' from origin 'http://localhost:3000' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://localhost:3000' is therefore not allowed access. The response had HTTP status code 522.
```
Never had this before. I hope this is just a temporal problem with cloudflare, but filing an issue anyway as this may affect many many people...

**Comment by DanielRuf** [comment]
This is probably a feature of your browser or framework / webapp. Did you try to not use localhost?

**Comment by jschlieber** [comment]
I'm working with the same setup for over a year now and it always worked. The error appeared when I started working today in the morning. It wasn't there when I stopped yesterday in the evening...

**Comment by DanielRuf** [comment]
The status code was 522 (connection timed out) which is currently not the case. 

Just as a sidenote: always try to use the local files and host the files yourself instead of relying on a CDN (for application critical assets).

Imho it makes more sense to apen an issue in the cdnjs repository.

**Comment by DanielRuf** [comment]
https://github.com/cdnjs/cdnjs/issues/11212

**Comment by DanielRuf** [comment]
It seems they resolved this, see https://github.com/cdnjs/cdnjs/issues/11212#issuecomment-300413878

**Comment by DanielRuf** [comment]
http://fallback.io and other fallback approaches / solutions might be a good idea.

**Comment by jschlieber** [comment]
Ok, thanks a lot for your immediate help!
