### ISSUE TITLE
overflow: hidden; not removed from .card element after .card-reveal is closed.

### ISSUE THREAD

**Issue by biskazz** [Dogfalo/materialize#4678]
When the `.card-reveal` element is slid up the screen, property `overflow: hidden;` is being dynamically added to the parent `.card` element to make it seem like it comes up the card itself, not the bottom of the screen. The `overflow: hidden;` property is not being removed from the said `.card` element after the `.card-reveal` element is closed.

**Comment by DanielRuf** [comment]
See #4668

**Comment by tomscholz** [comment]
Merged https://github.com/Dogfalo/materialize/pull/4668
