### ISSUE TITLE
Only one item in a carousel is not visible in Chrome

### ISSUE THREAD

**Issue by gubi** [Dogfalo/materialize#4679]
Hello, I found and solved a "bug" in carousel.

In Chrome browser, when there's only one image is not visible in the carousel.
The [`center` variable in line 164](https://github.com/Dogfalo/materialize/blob/master/js/carousel.js#L164) becomes **NaN** and so does not enter in [the `if` in line 189](https://github.com/Dogfalo/materialize/blob/master/js/carousel.js#L189).

Just fixed adding this if statement after the `center` instantiation:
``` javascript
if(isNaN(center)) {
    center = 0;
}
```

Please, add this in your source in order to allow us future updates.
Thanks in advance

**Comment by DanielRuf** [comment]
Can you create a PR for the fix? That eould be great. Thanks.

**Comment by tomscholz** [comment]
Should be fixed with https://github.com/Dogfalo/materialize/commit/85a57eb1a9cb8435896d5c9ff012eaa1dd785880
