### ISSUE TITLE
Add back to TOP 

### ISSUE THREAD

**Issue by zigy** [Dogfalo/materialize#468]
http://codyhouse.co/gem/back-to-top/

**Comment by matriphe** [comment]
+1 for this cool feature!

**Comment by pwmvx1289** [comment]
This would be useful to help developers simplify their work, I think I'm able to work on it.

**Comment by RaSeR** [comment]
This is not a part of Material Design.

**Comment by carloscarcamo** [comment]
Some days ago I made a little plugin for that (#323) and I added to materialize, but since this feature is not part of material design, it was not merged with the framework.

If you want to add this functionality, you can check the source code and try to implement it on your website.

**Comment by matriphe** [comment]
@carloscarcamo :+1: will try it up! thanks!
