### ISSUE TITLE
Modal repeats ajax calls

### ISSUE THREAD

**Issue by nalancer08** [Dogfalo/materialize#4680]
### Description
Hi, I have an issue with Modal component, basically, I create a modal, and open in a button click, and everything works fine, but, inside this modal, in the footer, I have a button to send an ajax post request, and the first time it works fine, and the if everything works okay, I close the modal.

But the problem that starts when you click the button again to open the modal and then the post ajax request, send two requests, and if you click again, the modal sends 3 ajax requests, and so it does Every time I open the modal, increase the count, and make that number of requests, I want to think that when the modal is closed, it does not remove it from the scope, and always creates a new one, and therefore, when I click, bubble Click on all the modal buttons and that causes, so many requests.

There is my code:

``
$('.modal').modal({
		dismissible: true,
		ready: function(modal, trigger) {
			
			$('.modal-create-task').on('click', function(e){

				var el = $(this);
				var textTask = $('.new_task').val();

				if ( textTask != "" ) {

					el.addClass('disabled');
					$.post("postURL", {
						variable: "",
					},

					function(data, status){

						if ( data.result == "success" ) { // API respond correctly

							var taskId = data.data.id;
							console.log("Id del task: " + taskId);

							$('.body-navegation').append("<div class=\"task\">" + "<p>" + "<input type=\"checkbox\" class=\"filled-in\" id=\"" + taskId + "\"/>" + "<label for=\""+ taskId + "\">" + textTask + "</label>" + "</p>" + "</div>");
							el.removeClass('disabled');
							 $('.new_task').val('');
							
						} else {

							alert("Error");
						}
					});

				}				
			});
		},
		complete: function() {
			//alert('Closed'); 
		} // Callback for Modal close
	}); 
`
Thank you so much, for everything.

**Comment by DanielRuf** [comment]
You have to use `.off('click').on('click', function(e)...` or `.one('click', function(e)...`

See http://api.jquery.com/one/

**Comment by DanielRuf** [comment]
Also bubbling up can be prevented by using `.stopPropagation()`. You attach a new click event listener every time the modal is opened. It also makes sense to remove the click event listener on close using `.off('click')`.

**Comment by tomscholz** [comment]
Closed due inactivity. Feel free to reopen it, if it's still necessary.
