### ISSUE TITLE
Modal not open

### ISSUE THREAD

**Issue by 0xPic0** [Dogfalo/materialize#4681]
### Description
I've recently updated my website with the last Materialize release and now, modal on my page doesn't seem to work anymore.

I've updated Materialize version from 0.97.7 to 0.98.2 and jQuery from 3.0.0 to 3.2.1.

I've tested to rollback in 0.97.7 with jQuery 3.2.1 and it's working. 

**New version :** (only add #xx on url)
`$('.modal-trigger').modal();`

**Old version :** (open modal)
`$('.modal-trigger').leanModal();`

### Repro Steps
I've tested many changes, with and without trigger on link who open modal. I don't know why this happen while it's working on your website with the same code.

Use Materialize 0.98.2 and jQuery 2.1.1 (in the doc) / 3.0.0 (my old version) / 3.2.1 (latest release) to reproduce

Codepen to reproduce problem : https://codepen.io/0xPic0/pen/zwjpgN

It can be my fault if i've missed something but i've changed my code in all sense during 3 days and now, i haven't no more ideas.

I hope a fix can be find.

Thanks by advance for your responses.

**Comment by DanielRuf** [comment]
And jQuery 2 did not work with this? No errors in the browser console?

**Comment by 0xPic0** [comment]
Has you can see in the codepen link, i use jQuery 2.1.1 as in the Materialize official documentation. Nothing change and nothing appear in the console.

**Comment by DanielRuf** [comment]
@0xPic0 https://codepen.io/anon/pen/OmZvKO

The initialization was not correct.

**Comment by DanielRuf** [comment]
See http://materializecss.com/modals.html#initialization

**Comment by 0xPic0** [comment]
Yep, i saw my error. My bad, i misunderstood the change.

Thanks for your help. I close this issue that wasn't one.
