### ISSUE TITLE
add button on the.Collapsible-header

### ISSUE THREAD

**Issue by KeJunMao** [Dogfalo/materialize#4682]
### add button on the.Collapsible-header
I tried to add dropdown to `.collapsible-header`, and when I clicked the dropdown button, collapsible closed so that I couldn't see `.dropdown-content`.

### Repro Steps
Layout the steps to reproduce your issue.

Use this Codepen to demonstrate your issue. http://codepen.io/Dogfalo/pen/xbzPQV

### Screenshots / Codepen
Add supplemental screenshots or code examples. Look for a codepen template in our Contributing Guidelines.

English is not my native language, sorry

**Comment by DanielRuf** [comment]
Please fork and fill out the codepen.
