### ISSUE TITLE
[Proposal] new css class `Link`

### ISSUE THREAD

**Issue by carusogabriel** [Dogfalo/materialize#4684]
Many times I see myself in the situation to show the user that an anchor tag is a link, and Materialize doesn't offers me out of the box. Soo, why not?

[Proposal]: create a `.link` class, that when the user `:hover` it, the text became underline.

What do you guys think?

**Comment by fega** [comment]
Hello @carusogabriel, 
This Idea comes from the material design specs?

**Comment by carusogabriel** [comment]
Oh @fega, that's true, Materialize follows Material Design Specs, I forget. I'll loop through the documentation and try to find it. 

Thanks

**Comment by fega** [comment]
Closed due inactivity, feel free to reopen it if it is still necessary.
