### ISSUE TITLE
Disabled Select Forms

### ISSUE THREAD

**Issue by ErraticFox** [Dogfalo/materialize#4685]
Hello, I cannot toggle select form disabled attributes. I've done stuff like `$("#quality").prop('disabled', false)` and if I do this in console.log it just gives me `[select#quality.initialized]` but nothing changes. I've tried a variety of other methods as well such as trying to use `.select-dropdown` being of one them. Still no avail. What am I doing wrong?

```html
<select id="quality" disabled>
	<option value="" disabled selected>Choose your option</option>
	<option value="1">Option 1</option>
	<option value="2">Option 2</option>
	<option value="3">Option 3</option>
</select>
```

**Comment by stsmurfy** [comment]
You must re-initialize with .material_select()

**Comment by pwill2** [comment]
@ErraticFox Do you have example code of making this work? I currently have the same problem.

**Comment by stsmurfy** [comment]
@pwill2 Take a look at the [documentation](http://materializecss.com/forms.html#select-initialization)

**Comment by Miki-AG** [comment]
@stsmurfy broken link

**Comment by stsmurfy** [comment]
> @stsmurfy broken link

Yes, because it was 2 years ago and since it changed a major version and this thread was for v0.100.2. But you can find here the old link: [http://archives.materializecss.com/0.100.2/forms.html#select-initialization](url)
