### ISSUE TITLE
How will the Material Design Components change MaterializeCSS?

### ISSUE THREAD

**Issue by FoxInFlame** [Dogfalo/materialize#4688]
So, Google now has their own official Components (called MDC-Web) with CSS codes and JavaScript and all that for Material Design.

[Link is here](https://material.io/components/web/).

How is this going to affect MaterializeCSS? Will it stop developing? Or is MDC-Web something that's not entirely in the same category as what MaterializeCSS is?

**Comment by fega** [comment]
Well, I prefer materialize because I found BEM Ugly and verbose

**Comment by Native-Coder** [comment]
MDC-Web is a framework just like MaterializeCSS. They aren't synonymous, they both just implement the material design philosophies put forth by google. That is to say they follow these same [guidelines](https://material.io/guidelines/#introduction-goals).

However, they are both seperate frameworks. Kind of like [Material Design Lite](https://getmdl.io/) or [Material UI](https://www.muicss.com/)

My guess is, nothing will change what so ever. MDC-Web is just a framework by Google that implements the guidelines I linked to above.. And I agree with @fega , it's a bit _too_ verbose. 

Materialize is quite simple.

**Comment by tomscholz** [comment]
I agree with @Native-Coder and @fega here
