### ISSUE TITLE
Update showcase (gallery) in documentation

### ISSUE THREAD

**Issue by smileytechguy** [Dogfalo/materialize#4689]
The showcase currently contains many out of date screenshots and websites, most of which are gone or do not use materialize.  I suggest we update these, and allow a better place for developers to add their site (maybe through GH issues).

Here are a few I've found:

https://www.bootstrapzero.com/ (Bootstrap themes (there is a joke here))
https://www.en.advertisercommunity.com/# (Google advertiser community)
https://csgolounge.com/ (CSGO lounge)

**Comment by tomscholz** [comment]
Please see: https://github.com/Dogfalo/materialize/issues/4275
