### ISSUE TITLE
Mobile Menu (Side-Nav) conflicts with the overlay.

### ISSUE THREAD

**Issue by Axiom1999** [Dogfalo/materialize#4692]
### Description
```
<nav> <!-- Is fixed. -->
    .. button-collapse here activates the side-nav below

    <ul class="side-nav" id="side-nav">
         ... stuff here
    </ul>
</nav>
```

### Repro Steps
Follow documentation on creating a mobile side-nav.
http://codepen.io/Axiom/pen/xdJgoe

### Screenshots / Codepen
http://i.imgur.com/bxaMgzv.png

**Comment by tomscholz** [comment]
See: https://github.com/Dogfalo/materialize/issues/3844
