### ISSUE TITLE
Weird shadow effect on Hover class (card)

### ISSUE THREAD

**Issue by tsuzukayama** [Dogfalo/materialize#4693]
### Description
Card with hover class on Chrome is behaving a little weird. Whenever I enter the card area with the pointer, the box shadow blinks for an instant, then transforms to its normal color.

I am using Chrome 58.0.3029.110, 64 bits, and Materialize v0.98.2

### Screenshots / Codepen
https://codepen.io/tiagosuzukayama/pen/EmpWyz

**Comment by apexlee** [comment]
This one has already been reported here:

https://github.com/Dogfalo/materialize/issues/4580

Workaround is in the above issue too.
