### ISSUE TITLE
Where is the Legacy Documentation?

### ISSUE THREAD

**Issue by Native-Coder** [Dogfalo/materialize#4695]
Would it be possible to provide legacy documentation? I just tried to lookup drop-downs on materializecss.com only to see that the implementation has changed. I like the new implementation better, but I can't just change to a new version mid-project. I have dozens of drop-downs using the "old" way. I'd have to re-write half of my project.

I'm using version 0.98.0

**Comment by tomscholz** [comment]
Please see: https://github.com/Dogfalo/materialize/issues/1586
