### ISSUE TITLE
Version stucked at 0.97.6 in NUGET

### ISSUE THREAD

**Issue by marcelsnews** [Dogfalo/materialize#4698]
### Description
Presently, it seems as the latest materialize version in NUGET (VS2017 ) including prerelease is stucked to 0.97.6.
Is there any plan to FIX this or is this normal behavior ?

### Repro Steps
Not related

### Screenshots / Codepen
nuget-materialize-stucked-in0 97 6
![nuget-materialize-stucked-in0 97 6](https://cloud.githubusercontent.com/assets/1772426/26121912/c750bbac-3a43-11e7-998a-f42050f1ba66.PNG)

**Comment by tomscholz** [comment]
We don't officially support a nuget version. This must be a thirdparty nuget thingy

**Comment by marcelsnews** [comment]
Thanks, 
It was a wee bit confusing as far as he was referring to the official website.
So the only way to include the official version for now is to download directly from the official website right ?
There is no plan to make the it accessible in NUGET ?

In fact, we are testing frameworks to compare which one to use in a project and yours seems to be winner. 

Realy thanks.

**Comment by tomscholz** [comment]
Can you post a link to that nuget package? I can look into it, but promise nothing

**Comment by marcelsnews** [comment]
Sure here are the info when you look through NUGET:

materialize 0.97.6: https://www.nuget.org/packages/materialize/0.97.6
Licence: https://github.com/Dogfalo/materialize/blob/master/LICENSE
**Project URL:**  http://materializecss.com/ . **This is the weird part !**

Here is how it looks in VS
![materialize-in-vs2017-nuget](https://cloud.githubusercontent.com/assets/1772426/26128296/f3880214-3a59-11e7-8a5b-ad8a142f89b0.PNG)

**Comment by tomscholz** [comment]
![bildschirmfoto 2017-05-16 um 23 07 21](https://cloud.githubusercontent.com/assets/20381749/26128350/721cb1b0-3a8c-11e7-998b-9edf0330395e.png)
I don't have a nuget account, but you could  try to contact the creator of this package.

**Comment by marcelsnews** [comment]
Sure,
I will download it in the official website for now while waiting to see if he can update the package. 

But i think you shouldn't allow someone re-using the official framework name like this without specifying if it is a fork or just a way to make it accessible on any platform. In fact we was blaming the official team and it appeared really weird to us because everything was pointing to the official website and github repo.

Thanks a lot for this quick and efficient replies.
