### ISSUE TITLE
datepicker modal automatically open

### ISSUE THREAD

**Issue by ericlormul** [Dogfalo/materialize#4700]
To reproduce:
1. go to http://materializecss.com/forms.html,
2. click the input of datepicker, and select a date, then click close
3. minimize the browser window
4. open the minimized browser window, then datepicker opens automatically. 

This behavior is weird. Is it a bug?

**Comment by GorgonsMaze** [comment]
+1 - This is happening on Chrome for me

**Comment by kinqsley** [comment]
This is happening too if changing tabs on browser

**Comment by adhirajsinghchauhan** [comment]
This is actually a [bug](https://github.com/amsul/pickadate.js/issues/160) with the [Pick a Date](http://amsul.ca/pickadate.js/) library that Materialize uses.

**Comment by tomscholz** [comment]
Closed since this as an issue not with materialize. See amsul/pickadate.js#160

**Comment by JelleBlaauw** [comment]
They're not fixing it, so you should.
