### ISSUE TITLE
Dropdown menu doesn't work in table

### ISSUE THREAD

**Issue by pingshunhuangalex** [Dogfalo/materialize#4701]
Dropdown component [here](http://materializecss.com/dropdown.html) only works when it's at the root div, and wouldn't work at a table context (wrapped by `<td></td>`)

**Comment by DanielRuf** [comment]
Generally it should work. Can you provide a codepen to illustrate the issue?

**Comment by pingshunhuangalex** [comment]
Thanks for the reply @DanielRuf 
Here is the [pen](https://codepen.io/pingshunhuangalex/pen/GmXRqL)

**Comment by DanielRuf** [comment]
Hm, it works here (on mobile): https://codepen.io/anon/pen/wdEvjM

**Comment by pingshunhuangalex** [comment]
It does work. I'll keep digging then. Thanks.

**Comment by pingshunhuangalex** [comment]
Found the reason @DanielRuf 
It's just a root reference issue when I'm using `this.$el` in Vue. Thanks.
