### ISSUE TITLE
Label doesn't go up on input focus

### ISSUE THREAD

**Issue by inventti-leonardosanto** [Dogfalo/materialize#4707]
### Description
Label doesn't go up on input focus

### Repro Steps
http://codepen.io/anon/pen/KmbNNQ

### Screenshots / Codepen
![image](https://cloud.githubusercontent.com/assets/20517026/26263681/16d878d6-3cb0-11e7-807f-03958565a39c.png)

**Comment by DanielRuf** [comment]
Please test the change of https://github.com/Dogfalo/materialize/pull/4709

**Comment by inventti-leonardosanto** [comment]
@DanielRuf it works now, thanks!
