### ISSUE TITLE
Update flexbox spec

### ISSUE THREAD

**Issue by tuxredux** [Dogfalo/materialize#4708]
Using [Lighthouse](https://developers.google.com/web/tools/lighthouse/) to test for [Progressive Web App](https://developers.google.com/web/progressive-web-apps/) support, and `materialize.css` fails the **Using modern CSS features** test.

**Solution:** https://developers.google.com/web/tools/lighthouse/audits/old-flexbox

**Comment by DanielRuf** [comment]
I don't see any box or box-flex reference in https://github.com/Dogfalo/materialize/blob/master/dist/css/materialize.css

Can you show us to the affected lines?

**Comment by tuxredux** [comment]
You are right, sorry about that! It seems Lighthouse 2.0.0 was just released and everything is good now, so it must have been a bug. Thanks!
