### ISSUE TITLE
Allow option or classes for using pickadate's default styles and functions

### ISSUE THREAD

**Issue by riliwanrabo** [Dogfalo/materialize#471]
Reason
-----------
1. Doesn't go inline with their docs e.g I tried as below
$('.datepicker').pickadate({
        selectMonths: true,
        selectYears: true
    });

I didn't get the expected result sad :(

**Comment by tianhai82** [comment]
I faced the same issue. If we want to use the datepicker to allow user to choose birthday, it will be very impractical as he has to click the next month or previous month button multiple time before he can find the correct year.

**Comment by Dogfalo** [comment]
Select in datepicker works now.

**Comment by riliwanrabo** [comment]
cool
