### ISSUE TITLE
#Sidenav-Overlay Covering up .Side-Nav

### ISSUE THREAD

**Issue by glovemasterflex** [Dogfalo/materialize#4710]
### Description
Out of the box, #sidenav-overlay's z-index is set to 997, and even though the .side-nav class' z-index is set to 999, it competes and ends up covering the .side-nav making it unclickable.

### Screenshots / Codepen
![sidenav-overlay](https://cloud.githubusercontent.com/assets/17298325/26276303/ea3a4da4-3d31-11e7-980b-df88d1e302ab.PNG)

### Recommended Fix
I've been able to set #sidenav-overlay to z-index:950; and that doesn't disrupt the function of the overlay covering the rest of the site while fixing the issue of allowing the .side-nav to be clickable.

**Comment by glovemasterflex** [comment]
I had this same problem on two different sites I built. Otherwise, I love this CSS framework. It's my go to.

**Comment by DanielRuf** [comment]
Did you already try to move the sidenav ul outside of its container(s)/wrapper(s)?
