### ISSUE TITLE
Checkbox Not Appearing In ASP.Net MVC Using Razor View

### ISSUE THREAD

**Issue by MithunAmalraj** [Dogfalo/materialize#4712]
### Description
Checkbox which is created using ASP.NET MVC does not appear in my web page. I know every input type "checkbox" needs a label tag. But when i create using Razor view checkbox it does not appear. Reason there is a hidden input field(automatically created) between checkbox and label. when it is removed using javascript my checkbox appears. But i cannot remove it in each one of my page. Need a solution
### My Coding
##Razor View Code
```
<div class="row">
        <div class="input-field col s12 m4 l12">
            @Html.EditorFor(model => model.RememberMe)
            @Html.LabelFor(model => model.RememberMe)
        </div>
 </div>
```
##My HTML Generated Code
```
 <input data-val="true" data-val-required="The RememberMe field is required." id="RememberMe" 
              name="RememberMe" type="checkbox" value="true" />
 <input name="RememberMe" type="hidden" value="false" />
 <label for="RememberMe">RememberMe</label>
```
##Summary
This hidden input appears in between label and checkbox which makes my checkbox invisible in webpage. Help Me. Thanks.

**Comment by DanielRuf** [comment]
Please provide a codepen. Is this directly related to Materialize?

**Comment by MithunAmalraj** [comment]
I'm not saying there is a problem with Materialize, but this is a unique case which you guys might not have encountered it till now. Here is my codepen link,
[https://codepen.io/MithunAmalraj/pen/KmbWBW?editors=1000](url)
Thanks for the immediate reply DanielRuf.

**Comment by Dogfalo** [comment]
The label is not appearing after the correct input, check the two html outputs and you will see.
