### ISSUE TITLE
Material Box: Link thumbnail to full image

### ISSUE THREAD

**Issue by ITfee** [Dogfalo/materialize#4715]
I want Material Box to open the high resolution version of my thumbnail. I've tried like that:

`<a class="materialboxed" href="http://domain.com/highres/picture.jpg"><img src="http://domain.com/thumbs/picture.jpg"></a>`

But that doesn't work.

Is there a workaround or is it simply not possible or a bug?

**Comment by tomscholz** [comment]
Duplictate of #2452

**Comment by ITfee** [comment]
There is another duplicate under #3407 
I've asked here again, because I found no answer to my question above.
Now I know.
