### ISSUE TITLE
Modal don't work

### ISSUE THREAD

**Issue by Despin** [Dogfalo/materialize#4718]
### Description
When I click the modal button, this no open. Stay here

### Repro Steps
Simply I paste the example by the page http://materializecss.com/modals.html

**Comment by DanielRuf** [comment]
You have to initialize it using `$('.modal').modal()`.

Please provide a codepen.

**Comment by krosoftware** [comment]
You need to add $('.modal').modal(); at your JavaScript (somewhere on documentReady etc.
