### ISSUE TITLE
Scrollbar problem in SideNav

### ISSUE THREAD

**Issue by grigorii-horos** [Dogfalo/materialize#4719]
### Description
I dont see bottom arrow of scrollbar in SideNav

Now:
![2017-05-23 14-51-15](https://cloud.githubusercontent.com/assets/4980269/26353198/e2e60212-3fc7-11e7-9424-8c791cc2e64d.png)

But when I delete [height: calc(100% + 60px)](https://github.com/Dogfalo/materialize/blob/28dce92d6a16d37eb0b1b41911e067bdcfae4b38/sass/components/_sideNav.scss#L9) and set [padding-bottom: 0](https://github.com/Dogfalo/materialize/blob/28dce92d6a16d37eb0b1b41911e067bdcfae4b38/sass/components/_sideNav.scss#L11) it look good

![2017-05-23 14-52-27](https://cloud.githubusercontent.com/assets/4980269/26353229/0f45a2ea-3fc8-11e7-8a18-1d766620a7ed.png)

**Comment by tomscholz** [comment]
Plesse post a codepen to illustrate the problem.

**Comment by horosgrisa** [comment]
Bad:
https://codepen.io/anon/pen/JNwqrq
Good
https://codepen.io/anon/pen/bWOyYR

**Comment by valerio-bozzolan** [comment]
I confirm the solution with the @horosgrisa's patch:

```
.sidenav {
    height: 100%;
    padding-bottom: 0;
}
```

**Comment by Smankusors** [comment]
This issue has been fixed on https://github.com/materializecss/materialize/pull/62.
