### ISSUE TITLE
Use passive event listeners

### ISSUE THREAD

**Issue by tuxredux** [Dogfalo/materialize#4720]
https://developers.google.com/web/tools/lighthouse/audits/passive-event-listeners

```javascript
7711            view[0].addEventListener('touchstart', tap, {passive: true});
7712            view[0].addEventListener('touchmove', drag, {passive: true});
```

**Comment by DanielRuf** [comment]
> However, in browsers that do not support passive event listeners, the third parameter is a boolean to indicate whether the event should bubble or capture. So, using the syntax above may cause unintended consequences.
> 
> See the polyfill in Feature Detection to learn how to safely implement passive event listeners.

http://caniuse.com/#feat=passive-event-listener

Generally a pull requestwith the needed changes would be great.

Do you know if there is some CI solution for Lighthouse so we could see a full audit and check each commit and PR with it?

**Comment by tuxredux** [comment]
@DanielRuf I am not a JavaScript developer myself, but if I have the time I will definitely make that pull request!

I just now noticed the [supported browsers](https://github.com/Dogfalo/materialize#supported-browsers), so it seems a polyfill or feature detection would need to be implemented. According to [these docs](https://github.com/WICG/EventListenerOptions/blob/gh-pages/explainer.md#feature-detection), that could be achieved relatively simply like so:

```javascript
var supportsPassive = false;
try {
  var opts = Object.defineProperty({}, 'passive', {
    get: function() {
      supportsPassive = true;
    }
  });
  window.addEventListener("test", null, opts);
} catch (e) {}

view[0].addEventListener('touchstart', tap, supportsPassive ? { passive: true } : false);
view[0].addEventListener('touchmove', drag, supportsPassive ? { passive: true } : false);
```

Yeah there is definitely a [Lighthouse CLI](https://github.com/GoogleChrome/lighthouse#node-cli-), but it is just a wrapper for launching Chrome. Although [headless support](https://developers.google.com/web/updates/2017/04/headless-chrome) just shipped with Chrome 59!

I am on Debian Linux, so I have been [unable to get it to work](https://github.com/GoogleChrome/lighthouse/issues/698). There is a [docker image](https://hub.docker.com/r/justinribeiro/lighthouse/) with a headless Chrome I still need to try though!

**Comment by DanielRuf** [comment]
Probably https://github.com/ebidel/lighthouse-ci might be useful in the future.

**Comment by tuxredux** [comment]
@DanielRuf Great find! Sorry, I misinterpreted CI as 'Command (Line) Interface' instead of the intended 'Continuous Integration'.

**Comment by Dogfalo** [comment]
We don't want to add polyfills for this, so when support for this improves we will consider supporting it

**Comment by Fauxil-Fox** [comment]
Any reconsiderations? @Dogfalo

**Comment by styfle** [comment]
I am trying out materialize 1.0.0 and getting this warning in Chrome 69 when using the sidenav feature.

It looks like the `passive` option is pretty [well supported](https://developer.mozilla.org/en-US/docs/Web/API/EventTarget/addEventListener#Browser_compatibility) by every browser.

**Comment by Dogfalo** [comment]
IE doesn't support it, which for the time being we are still supporting

**Comment by Dargmuesli** [comment]
To me this seems like an improvement for all other browsers. IE can stick to (not) support whatever it wants, for all other browsers passive event listeners should be used if that's possible

**Comment by MicheleLucini** [comment]
UP

**Comment by gabrielima** [comment]
It has been almost 2 years since this was opened. Any reconsiderations on this issue ? @Dogfalo

**Comment by ghost** [comment]
What if we removed all legacy support from the base framework, allowing us to work with the most up-to-date tools. Then move legacy support (including IE) to distinct micro-libraries that developers can choose to use or not. ([Similar to the way D3 can be easily "Frankensteined" into just the pieces  you need](https://github.com/d3))  Loading the library might look something like

```
<!-- This by itself only supports modern browsers-->
<script src="./vendor/materialize/materialize.min.js"></script>
<!-- This adds IE support-->
<script src="./vendor/materialize/materialize.ie.min.js"></script>
```

The same concept could work for styles and polyfills.

By modularizing the library in this way we can leave the legacy support to those who need/care about it, and improve performance for those who don't.

**Comment by DanielRuf** [comment]
This is still valid:
https://github.com/Dogfalo/materialize/issues/4720#issuecomment-335909670

v1 still supports IE.

**Comment by Smankusors** [comment]
in case anyone wondering, there's pull request for this. #6466
