### ISSUE TITLE
Classes do not work correctly "card-panel + hoverable"

### ISSUE THREAD

**Issue by hiromant** [Dogfalo/materialize#4728]
### Description
When you move the cursor over an element with the classes "hoverable + card", the animation is displayed incorrectly. 
This can be seen on your site in the "helpers" section.
Or: [https://codepen.io/anon/pen/oWOewW](url)

I use the browser: Chrome 58.0.3029.110.
In Mozilla Firefox - everything is displayed  correctly.

**Comment by DanielRuf** [comment]
Do you mean the shadow?

**Comment by hiromant** [comment]
yes

**Comment by DanielRuf** [comment]
See https://github.com/Dogfalo/materialize/issues/4580
