### ISSUE TITLE
Tabs indicator being set incorrectly due to scroll bar

### ISSUE THREAD

**Issue by PapsOu** [Dogfalo/materialize#4729]
### Description
The tab indicator is not well positioned when the current tab has a vertical scroll bar visible and the target tab doesn't.

### Repro Steps
Tab container is displayed as flex, tabs are flex-grow 1 to fit screen width.

Click the tabs that will have enough content to show a vertical scroll bar in the browser

Click the last tab on the right.

The tab indicator style value is right:-12px; it should be 0px;

12px value is the scrollbar width of my browser.

### Screenshots / Codepen
first tabs with scrollbar
![20170526-163026](https://cloud.githubusercontent.com/assets/5792207/26499219/1577986e-4232-11e7-942c-90a491ef579e.png)

last tabs without scrollbar
![20170526-163049](https://cloud.githubusercontent.com/assets/5792207/26499224/18e7ba7e-4232-11e7-91b5-32d275de982d.png)

The right css attr should be calculated after tab content is shown.

**Comment by DanielRuf** [comment]
A codepen would be very useful. Does this happen with Materialize 0.98.2?

**Comment by tomscholz** [comment]
And which browser are you using?

**Comment by DanielRuf** [comment]
> And which browser are you using?

According to the picture it should be Mozilla Firefox (stable) ;-)

**Comment by PapsOu** [comment]
I cannot create a code pen now.

Yes it is Firefox latest stable.

**Comment by tomscholz** [comment]
Closed due inactivity. Feel free to reopen it, if it's still necessary.
