### ISSUE TITLE
Addition of time picker

### ISSUE THREAD

**Issue by newmanw** [Dogfalo/materialize#473]
Not sure if this makes sense within existing date picker, or a separate element.  However it would be nice to be able to pick a date and time.

**Comment by syedsuhail** [comment]
It would be great if there was option for both a separate element and along with the existing date picker. Will this be implemented in the near future?

**Comment by CoDEmanX** [comment]
In Android 5, there's a separate dialog for time picking. It's very well designed, it looks like a clock with two rings of labels (1-12 and 13-24), or, if your locale uses 12h format, one label ring and two buttons for AM and PM:

![screenshot_2015-01-21-13-48-51](https://cloud.githubusercontent.com/assets/1309249/5836391/689c0ab2-a175-11e4-940b-e71b19c1c220.png)

![android_new_time_picker_1](https://cloud.githubusercontent.com/assets/1309249/5836343/8c3647cc-a174-11e4-9fef-460c33fefdc8.png)

After picking the hour, there's a transition of the label ring(s) to a label ring for the minutes, in 5 minute steps. You can either tap on one of them, or drag to enter a precise minute. A confirmation is required after picking the minute to close the dialog.

If you click on the hour at the top, it will return to the hour picking mode (also with a nice animation).

**Comment by syedsuhail** [comment]
This is great for mobile but there is no material design Date time picker for the web.

**Comment by serkandurusoy** [comment]
The original pickadate.js which materialize's is based on does have a time picker. So perhaps, that could be extended similarly.

**Comment by Dogfalo** [comment]
Echoing what @syedsuhail said, these time pickers are nice for mobile devices, but they do not work so well on desktop devices. More thought will have to go in to these.

**Comment by bimmlerd** [comment]
I'd love to see some sort of timepicker as well :+1: 

For the moment if would be great to add a little bit of styling to the time input, as it is currently completely unstyled.

**Comment by boustanihani** [comment]
:+1:

**Comment by carlosperate** [comment]
@Dogfalo It's been quite a while since this was suggested, are there any plans to implement some kind of time picker?

**Comment by larikitty** [comment]
@Dogfalo, I'd love to see some kind of time picker, as @carlosperate mentioned earlier.

**Comment by ABeltramo** [comment]
Heavily inspired from http://simeonc.github.io/md-date-time/ I develop this very simple time picker for my project. I'll try to keep it as simple as possible.
Require Materialize and jquery.
 
http://jsfiddle.net/kakamiokatsu/o3osy173/

Any feedback is welcome!

**Comment by boustanihani** [comment]
I found this one by chance, looks promising: https://github.com/weareoutman/clockpicker

**Comment by philipraets** [comment]
@ABeltramo : that one (md-date-time) is awesome and it has a date- and timepicker

**Comment by ABeltramo** [comment]
I see it but I need somenthing simpler and I don't want to include angular..

**Comment by aron-bordin** [comment]
:+1:

**Comment by san** [comment]
:+1:

**Comment by boustanihani** [comment]
This one also looks nice: https://github.com/mattkrick/lolliclock

**Comment by ricardodovalle** [comment]
:+1:

**Comment by benjamin79** [comment]
+1

**Comment by Neotrixsx** [comment]
:+1:

**Comment by kevohagan** [comment]
:+1:

**Comment by fabyeah** [comment]
:+1: I'm also all for the Android/Lolliclock implementation. Don't care if it's the same on web as on mobile.

**Comment by netm** [comment]
:+1:

**Comment by boustanihani** [comment]
this one also looks nice: http://material-ui.com/#/components/time-picker

**Comment by schrenkb1** [comment]
:+1: This along with date pick would be a great addition

**Comment by patrickgordon** [comment]
Any appetite for something like this @Dogfalo and co?

**Comment by oakmad** [comment]
:+1:

**Comment by titus88** [comment]
:+1:

**Comment by ckornaros** [comment]
:+1: Datetime picker would be a great improvement !

**Comment by szymonk92** [comment]
Best would be Date and Time picker as one component !

**Comment by thomaslarsson** [comment]
I second a combined date and time picker.

**Comment by byrnedo** [comment]
+1

**Comment by fcgomes92** [comment]
+1 on a datetime and a time picker (:

**Comment by crystalpal** [comment]
A combined datetimepicker would be very nice

**Comment by pikachuPokemon** [comment]
+1

**Comment by leejinhuey** [comment]
+1

**Comment by blinchi** [comment]
+1

**Comment by gustavoandrescabral** [comment]
+1

**Comment by mohamnag** [comment]
so if this makes a change, +1 from me too ;)

**Comment by damondicenzo** [comment]
+1

**Comment by sebastianLapcevic** [comment]
+1 We need this

**Comment by kingzbauer** [comment]
:+1:

**Comment by acenario** [comment]
+1 Where is the time support?

**Comment by zeeshanjan82** [comment]
+1

**Comment by tutotours** [comment]
+1 Time support would be awesome

**Comment by NikiShah** [comment]
Input type=type is there in css file What is the class and js required?

**Comment by tutotours** [comment]
Docs for timepicker are here : http://amsul.ca/pickadate.js/time/
Two things missing : datetime picker and timepicker with material

**Comment by YoshiYo** [comment]
Any solution ?

**Comment by chingyawhao** [comment]
I made a some modification to https://github.com/weareoutman/clockpicker
Now, it can be used as a addition clockpicker to materializecss

https://github.com/chingyawhao/materialize-clockpicker

**Comment by boustanihani** [comment]
@chingyawhao great work man, could you please make a pull request or maybe publish your work on atmosphere ?

**Comment by chingyawhao** [comment]
@boustanihani thanks, but I'm not too familiar with git...can you fork a branch..?

**Comment by boustanihani** [comment]
I'll take a look...

**Comment by boustanihani** [comment]
Forking is not an issue, but I never used grunt before :( so I guess we have to leave this for the material guys...

**Comment by chingyawhao** [comment]
I see...thanks for your help anyway

**Comment by qsvprogram** [comment]
Please add TimePicker and DatetimePicker like "Bootstrap Material DatePicker"
Demo: http://t00rk.github.io/bootstrap-material-datetimepicker/

**Comment by WebStar007** [comment]
+1

**Comment by Tobi042** [comment]
+1 for chingyawhao's design. Looks really good! :)

**Comment by chingyawhao** [comment]
Thanks @Tobi042...

**Comment by QuintinAdam** [comment]
+1

**Comment by SeyZ** [comment]
+1

**Comment by Tapjay** [comment]
Would love to know if there are any plans to implement the date/time picker and if so what the timeline is looking like.

**Comment by SuperDJ** [comment]
+1

**Comment by sillysachin** [comment]
+1

**Comment by lcdss** [comment]
+1

**Comment by BenjaminRosell** [comment]
+1

**Comment by Zyquivilly** [comment]
+1

**Comment by THPubs** [comment]
+1

**Comment by FelipeLimaM** [comment]
+1

**Comment by FelipeLimaM** [comment]
:+1:

**Comment by beforeadream** [comment]
+1 :laughing:

**Comment by FuzzyRhombus** [comment]
+1

**Comment by ababba15** [comment]
+1

**Comment by yzargari** [comment]
+1

**Comment by Nastrand** [comment]
+1

**Comment by cdagli** [comment]
+1

**Comment by cyberinferno** [comment]
+1

**Comment by ahmedtabrez** [comment]
+1

**Comment by lcdss** [comment]
Datetime Picker that you can opt use only Date Picker or Time Picker.

**Comment by muroshi** [comment]
This one is nice: http://jonthornton.github.io/jquery-timepicker/

**Comment by patricklindsay** [comment]
:+1:

**Comment by Kukks** [comment]
+1

**Comment by ahmedtabrez** [comment]
:+1:

**Comment by patricklindsay** [comment]
I ended up using @chingyawhao's [materialize-clockpicker](https://github.com/chingyawhao/materialize-clockpicker)

1) [Copy the JS and CSS into project](https://github.com/patricklindsay/integral/commit/a084f2fd74a9f5b968b60f3b9725e1f0d7fb16b7)
2) Create a text input which includes `timepicker` class
3) Add the following code to your `application.js` or wherever you fancy. This initialises the time picker as well as stop error styling being eagerly activated if you are using [client side validations](https://github.com/DavyJonesLocker/client_side_validations).

```
  $('.timepicker').pickatime({
    twelvehour: true,
    donetext: 'Done',
    beforeShow: function() {
      activeElement = $(document.activeElement)
      activeForm = activeElement.closest('form')[0]

      // Remove existing validation errors
      activeForm.ClientSideValidations.removeError(activeElement)

      // Prevent a validation error occurring when element un-focusses
      activeElement.disableClientSideValidations();
    },
    afterDone: function() {
      activeElement = $(document.activeElement)
      $(activeElement).enableClientSideValidations();
    }
  });
```

Thanks @chingyawhao !

**Comment by RoarG** [comment]
:+1:

**Comment by robertofabrizi** [comment]
@patricklindsay Dear Patrick, I've followed your suggestion but it when I click into a text field, it says: ncaught TypeError: Cannot read property 'removeError' of undefined, at line:
`activeForm.ClientSideValidations.removeError(activeElement)`
Can you help me? I think that I followed your solution to the letter :(

**Comment by jaitaiwan** [comment]
It looks like the above code doesn't seem to be working so well... seems to conflict slightly with the pickadate dom for me.

**Comment by artfable** [comment]
If you want, you can take my solution. 
[https://github.com/artfable/plugins/tree/master/timepicker](https://github.com/artfable/plugins/tree/master/timepicker)

**Comment by karray** [comment]
+1

**Comment by Queatz** [comment]
:+1:

**Comment by roccomuso** [comment]
+1

**Comment by nerogit** [comment]
:+1:

**Comment by rickyhopkins** [comment]
:+1:

**Comment by stints** [comment]
:+1:

**Comment by Dark1hp** [comment]
:+1:

**Comment by seifsay3d** [comment]
+1

**Comment by Aeseir** [comment]
:+1:

**Comment by clandestine8** [comment]
This is one i made a while ago, not to many options. It CSS Powered so its quick, not a lot of JS going on. If you want to fork and fix it up go for it. Theme is set for the project i was working on by everything is editable. Materialize or pickatime is not a dependency, just jQuery. Auto-initializing, just use the right class on a text field. 

[https://github.com/clandestine8/GMD-SimpleFancy-Timepicker](https://github.com/clandestine8/GMD-SimpleFancy-Timepicker )

**Comment by hootener** [comment]
I ended up using @chingyawhao 's as well. The styling and look are great, but I think if a solution is officially incorporated into materialize it would be served using the [pickatime](http://amsul.ca/pickadate.js/time/) library from Amsul. This would provide a consistent interface between date picking and time picking within materialize, which would be much more straightforward for developers adopting materialize as their front end framework of choice. 

If time permits, I'm considering trying to shoehorn @chingyawhao 's picker into materialize using the pickatime library instead of clockpicker. I think @chingyawhao 's picker really nails the look and feel of materialize, but the underlying JS library is a bit cumbersome compared to the simplicity and straightforward nature of pickatime.js. Is this something the materialize devs would be interested in me working into a PR? I hope to be able to do this, but once again, it all comes down to time for me. Hopefully I can make it happen.

**Comment by doodirock** [comment]
Wondering if this is going to happen at some point.  Seems like we really need a time picker

**Comment by jaitaiwan** [comment]
We resorted to using the timepicker that comes as an add on to the one used in the geeks lab materialise admin them. There's a demo used which you can use to see how it works



On Sun, Sep 4, 2016 at 7:19 PM +1000, "Joel Albert" <notifications@github.com> wrote:












Wondering if this is going to happen at some point.  Seems like we really need a time picker

**Comment by smileytechguy** [comment]
any update ? I really want one for a "X minutes from now" style

**Comment by albertogregoriophios** [comment]
+1..

Does some of the suggestions include a time-picker not referred to TimeOfDay, but TimePeriod instead?. Where it is possible to introduce something like this:

52:42:51 

or

00:00:00.123

**Comment by kfill27** [comment]
+1

**Comment by lunatolun** [comment]
+1

**Comment by mkoczka** [comment]
+1

**Comment by FillTheCup** [comment]
+1

**Comment by ReilySiegel** [comment]
+1

**Comment by Ganbin** [comment]
I'm not the only one who wish to see a timepicker in the materialize framework. 👍 

What you other are using for replacement for now?

**Comment by samuelzhouhe** [comment]
+1

**Comment by 3367894** [comment]
+1

**Comment by beshambher** [comment]
+1

**Comment by ask007java** [comment]
+1

**Comment by ryekerjh** [comment]
+1 We need this badly

**Comment by smileytechguy** [comment]
I'm gonna *start* working on this, but it might take me a while
Wish me luck

**Comment by Foonz** [comment]
+1

**Comment by smileytechguy** [comment]
Would you guys mind having moment.js added as a requisite?  its fairly light, however I'm going to extract the code needed

**Comment by jaitaiwan** [comment]
I know that pickatime.js is made by the same people that did the date picker so that could also be an option

Get Outlook for iOS




On Sun, Nov 20, 2016 at 11:47 AM +1000, "Noah Overcash" <notifications@github.com> wrote:












Would you guys mind having moment.js added as a requisite?  its fairly light, however I'm going to extract the code needed

**Comment by smileytechguy** [comment]
I'm looking at https://github.com/T00rk/bootstrap-material-datetimepicker (ignore the name, doesnt require bootstrap anymore)

**Comment by smileytechguy** [comment]
![image](https://cloud.githubusercontent.com/assets/8005215/20459751/39998354-ae9b-11e6-8097-663849d9a7f4.png)
That is pick a time.js

![image](https://cloud.githubusercontent.com/assets/8005215/20459753/44faab1a-ae9b-11e6-9393-6c8f0700ff30.png)
Heres what im working on

**Comment by jaitaiwan** [comment]
Yeah, I think in materialize admin they added a skin for pickatime 

Get Outlook for iOS




On Sun, Nov 20, 2016 at 12:01 PM +1000, "Noah Overcash" <notifications@github.com> wrote:














That is pick a time.js





Heres what im working on

**Comment by smileytechguy** [comment]
Alright, I'm preparing a pull request

**Comment by yanickrochon** [comment]
FWIW I think a time picker does also well on desktops with a mouse and keyboard. Users rather click and drag things than select a dropdown list or even type values.

:+1: for a time picker component.

**Comment by smileytechguy** [comment]
I'm getting a PR ready, but I'm short on time today.  Here's a JSFiddle (code's messy, couldn't get jQuery to load right)
https://jsfiddle.net/1yt7241c/

**Comment by smileytechguy** [comment]
Can anyone test the above link and provide some feedback before I implement?  Thanks

**Comment by jaitaiwan** [comment]
I did some tests, its a great first start. Here's my feedback:

- You can't drag the time pieces
- There are no animations or smooth transitions
- Bottom buttons should be centred

Just my 2c. Hope that helps!

**Comment by smileytechguy** [comment]
Thanks, ill work it

**Comment by smileytechguy** [comment]
I can't figure out quite how to make them draggable.  Any tips?

**Comment by smileytechguy** [comment]
I changed the buttons, hopefully they are better now.
![image](https://cloud.githubusercontent.com/assets/8005215/20540784/85f8ebde-b0c8-11e6-954b-b4debed5ceff.png)
![image](https://cloud.githubusercontent.com/assets/8005215/20540787/8b2e3a14-b0c8-11e6-8209-9733fd85b443.png)
![image](https://cloud.githubusercontent.com/assets/8005215/20540793/8f49a9f8-b0c8-11e6-8080-a7f7044e670c.png)

**Comment by jaitaiwan** [comment]
I feel like an SVG is the easier way to go… but you’d probably need to do some maths to get that to work and tie in with mouse x+y

**Comment by smileytechguy** [comment]
It's an SVG, I just dont know how to make the mouse interaction work.

**Comment by Ganbin** [comment]
Hello, Nice work. If I can give my 2 cent. The `OK` Button is not clear. I expect that the ok button will validate and not let us choose the minutes. Maybe a button which let us change the hours and the minute and then click `OK` only to validate the choice.

Maybe to click on the `hour` could allow us to choose the hour and to click in the `minute` will allow us to choose the minute.

**Comment by smileytechguy** [comment]
Would changing the OK button to "NEXT" on the hour picker work?

**Comment by smileytechguy** [comment]
https://jsfiddle.net/1yt7241c/3/ try this.

**Comment by jaitaiwan** [comment]
@smileytechguy To get dragging working, you'd need to setup:

1. When the clock is clicked (touchstart, mousedown) events, register an event handler on the window for the touchmove and mousemove events. These events will send the x,y coords of the mouse or finger which we can use to determine the angle around the circle.
2. When we setup our touchmove and mousemove events we'll also need to setup a touchend and mouseup event to cancel the event listeners.
3. To calculate the angle around the circle we need to get the center of the clock (x1, y1) and pass it into `Math.atan2`. The mouse position is (x2, y2) so we can get the angle of the mouse around the clock (in radians not degrees) by calculating `Math.atan2(y2-y1, x2-x1)`

From that you should have enough to work with to get the dragging working. The math might need a little tweaking and I'm sure someone more mathy than I will chime out if I've made any mistakes here :)

Hope that helps!

**Comment by smileytechguy** [comment]
Thanks for the tips, but I don't think I can do all that.  Maybe in a later PR.  For now, unless anyone thinks I need to change anything on https://jsfiddle.net/1yt7241c/3/, I'll make an initial PR.

**Comment by Ganbin** [comment]
Sorry to be so meticulous, but when clicking the 'next' button, the 'cancel' button should turn to 'back'. 

Also when we click 'next' the button change to 'OK' which is good, but if we click cancel to choose go back to hours, the 'OK' button should thenchange to 'next' again and not stay 'OK'.

**Comment by philipraets** [comment]
I've made a pr a while back: https://github.com/Dogfalo/materialize/pull/2732
Maybe the code can help you.
it's responsive and the timepicker is draggable.

**Comment by doodirock** [comment]
@philipraets This seems perfect. Why wasn't this merged in?  No movement from authors?

**Comment by philipraets** [comment]
I have no idea why it hasn't been merged yet.
If anyone wants to try, test, bugfix or update it to the latest code of materializecss and merge it, please do. I don't have time to maintain it, and my project hasn't been updated with the latest code from materializecss after I've made this, but the date-and timepicker are used on a daily basis at the company I work for.

**Comment by philipraets** [comment]
I've created a codepen so you can see it in action: http://codepen.io/anon/pen/woqevN

**Comment by jaitaiwan** [comment]
I just tested on a few phones, and laptops of varying os and browsers. It's practically flawless!
		_____________________________

**Comment by smileytechguy** [comment]
Looks great!  Someone needs to get @Dogfalo or another maintainer to approve the PR, probably a lot to merge now.

**Comment by kirtangajjar** [comment]
cc @acburst

**Comment by shigawaka** [comment]
Any updates on this guys?

**Comment by smileytechguy** [comment]
@shigawaka not afaik

**Comment by smileytechguy** [comment]
@shigawaka not afaik
Personally, I just forked his version and used it

**Comment by calitidexvii** [comment]
@smileytechguy Did you successfully merge the pickatime code into your fork of v0.97.8? I don't see the code in your master.

**Comment by smileytechguy** [comment]
@calitidexvii no i didnt, that fork is unrelated afaik.  havent messed with it in a while

**Comment by calitidexvii** [comment]
@smileytechguy Thanks.

Has anyone else worked on updating PR [2732](https://github.com/Dogfalo/materialize/pull/2732) for v0.97.8? I'd be willing to work on it if I could get a commitment from the maintainers to actually merge it, or an explanation of what's missing. It seems to be the most complete implementation and works great on desktop.

**Comment by fabyeah** [comment]
Like other people, I'm using materialize.clockpicker from @chingyawhao. Why not create a PR based on that? Visually at least it's very nice.

**Comment by taorg** [comment]
I do agree about it, it's vert nice, but it lacks some functionality
You can't change easly year  (current datepicker it's also a bit buggy about)
I would be nice to have a single datetime picker field.
And maybe a range picker.
Anyway this seems much better than current solution.

**Comment by Native-Coder** [comment]
Has this been implimented? There's no reason why @jaitaiwan's solution shouldn't be implimented. it's exactly like the built-in time picker in android.

**Comment by Native-Coder** [comment]
Has any time picker been implemented yet? Is there a reason some of the examples above can't be?

**Comment by philipraets** [comment]
I've created a new clean PR #4445 which is compatible with the latest code.

**Comment by tomscholz** [comment]
Added in https://github.com/Dogfalo/materialize/commit/12003cea3c932232d59c25560f0c2973ab46ec11
