### ISSUE TITLE
Unable to change nav background color via CSS

### ISSUE THREAD

**Issue by SirMaxime** [Dogfalo/materialize#4730]
### Description
Changing the background color of the nav isn't possible via CSS. 

### Repro Steps
Check out the codepen:

https://codepen.io/anon/pen/VbNXxv

**Comment by DanielRuf** [comment]
@SirMaxime the class `.blue` takes precedence over the rules of the element so you have to add the class to your CSS.

https://codepen.io/anon/pen/dWLeLJ

Because `.blue` also uses !important.

**Comment by DanielRuf** [comment]
Or add another class for the color.

**Comment by hiteshsahu** [comment]
If you like to change the theme of your website dynamically with Jquery:

<p data-height="265" data-theme-id="0" data-slug-hash="EXoPRq" data-default-tab="html,result" data-user="hiteshsahu" data-embed-version="2" data-pen-title="Materialize CSS Change Theme Color" class="codepen">See the Pen <a href="https://codepen.io/hiteshsahu/pen/EXoPRq/">Materialize CSS Change Theme Color</a> by Hitesh  Sahu (<a href="https://codepen.io/hiteshsahu">@hiteshsahu</a>) on <a href="https://codepen.io">CodePen</a>.</p>
<script async src="https://production-assets.codepen.io/assets/embed/ei.js"></script>
