### ISSUE TITLE
How to keep track of the current slide in a carousel?

### ISSUE THREAD

**Issue by MastaBaba** [Dogfalo/materialize#4731]
I want to know which carousel item is currently showing.

At any time, I can check what the active slide is, so I can have a recurring function check this. But, it would be more practical if I can fire a function after the carousel has been slid.

Is this information somehow available?

**Comment by DanielRuf** [comment]
Try the undocumented `onCycleTo` option:

https://codepen.io/anon/pen/Lyvwoj

@fega @tomscholz should we add this option to the docs?

**Comment by fega** [comment]
MmMm personally, I don't thing that 'onCycleTo' is an expressive way to name this option.

**Comment by NonameSLdev** [comment]
@fega Agreed. It needs a rename before being added to the docs.

**Comment by vitalishapovalov** [comment]
@DanielRuf of course! 
Few days ago i tried to find it in docs, then i started to google for it.
When I did not find anything i realized that this options SHOULD EXIST anyway and found it source code.

**Comment by MastaBaba** [comment]
ETA?

**Comment by DanielRuf** [comment]
@NonameSLdev @fega ideas for better names (if really needed) and some good description for the docs?

**Comment by NonameSLdev** [comment]
@DanielRuf Definitely `onSelectItem()` or `onItemSelect()`.
Description:

> **currentItem**
> Type: `function(JqueryObjectIGuess item)`
> The function to run when a new item is selected (_Does it only trigger on user input? If so:_ by the user _and if not:_ by user/code) where `item` is the new item selected.

**Comment by GhyslainBruno** [comment]
+1 @DanielRuf, should definitely be added to your doc guys. 

@NonameSLdev --> works with user AND code tiggering

**Comment by acburst** [comment]
In 1.0.0 alpha, you can access the property center to get the index of the center item. 

Added documentation of the property in 3d59ebf5
