### ISSUE TITLE
Component getting darker each click

### ISSUE THREAD

**Issue by luandr** [Dogfalo/materialize#4732]
Hey
When i click an "btn" component `<a class="waves-effect  btn-large">Content</a>`. 
It starts to darken and every click it gets darker i don't know how it happen, why it happen and how to solve.
Same happens with class `waves-effect waves-light` but obviously gets white. I don't demonstrated this but happens.
[imgur](http://i.imgur.com/Yq1Efj4.png)
:edit on this image i tried add a click more each element first 1 click, second 2 clicks...
Thanks. Have a delicious day!

**Comment by DanielRuf** [comment]
Can you provide a codepen?

**Comment by luandr** [comment]
Of course, but works fine, different from my prod/dev environment (imgur link) i tried build as prod and host my project with http-server and same problem appears.
[`https://codepen.io/luandr/pen/MmdYoM`](https://codepen.io/luandr/pen/MmdYoM)
Thanks @DanielRuf

**Comment by tomscholz** [comment]
See: https://github.com/Dogfalo/materialize/issues/2667

**Comment by DanielRuf** [comment]
Can you please test if https://github.com/Dogfalo/materialize/pull/4474 fixes this?
