### ISSUE TITLE
Design collapse on Chips autocomplete elements

### ISSUE THREAD

**Issue by jagansindia** [Dogfalo/materialize#4737]
### Description
When using multiple chips with autocomplete feature on the materializecss design, first chip element auto populated data collapses the design and moves the second chip element down the end of last auto populated of first chip element.

### Repro Steps
Using latest version v.0.98.2 [138be0b](https://github.com/Dogfalo/materialize/commit/138be0b945cc8e1ee24d76ab6c1240c3f3628565)

Use this Codepen to see the issue. https://codepen.io/anon/pen/XRwVLd

### Suggestion
Requesting fix so that chips elements will not collapse when used in form area. We can set z-index value higher for auto populated data element which is above the form elements. Thank you

**Comment by Dogfalo** [comment]
Fixed in c067007d8af021f8dfca5609ff79557c61a31983
