### ISSUE TITLE
0.98.2 in Meteor seems to block off lower 3rd or so of page when using Swipeable with Tabs

### ISSUE THREAD

**Issue by bmcgonag** [Dogfalo/materialize#4738]
### Description
I updated (successfully) from 0.97.6 to 0.98.2 using normal packages for Meteor, but I've seen this with a downloaded package added manually as well. 

The lower third of my page appears to be blocked off, hiding anything that goes below that point.  

Almost like a layer of white is on top of everything else.  When I inspect using chrome dev tools, there's nothing shown that might indicate a hidden div or anything.  I've now seen this in 2 different projects.

I noticed it in another project, and thought my code had to have been messed up somewhere, but that project started on the latest Materialize 0.98.2, where-as today I updated Materialize from 0.97.6 to try and get the swipeable tab transition, and noticed the table on the 2nd tab was completely covered below about halfway down the page.  Again, no div to be hiding from what I can tell. 

### Repro Steps
Layout the steps to reproduce your issue.

1. I simply updated from 0.97.6 to 0.98.2.
2. Setup a tabbed view with 2 tabs (on the original project 6 tabs). 
3. Add elements that should go the length of the page, and notice they are cut short. 
    a. On the original project, it was a drop-down list that is long.
    b. On the 2nd project it's a table.
4. I have not tried the newer version without the swipeable option to see if it's that, or just tabbed views in general, or if it's on any page. 

Use this Codepen to demonstrate your issue. http://codepen.io/Dogfalo/pen/xbzPQV
Done!  See Screenshot below.  

I added the table in a tab, and there should be 4 rows after the header row. 

You can see that the 3rd row is cut off however. 

### Screenshots / Codepen
Add supplemental screenshots or code examples. Look for a codepen template in our Contributing Guidelines.
![screen shot 2017-05-28 at 9 17 09 pm](https://cloud.githubusercontent.com/assets/7346620/26534552/1793009c-43eb-11e7-8bed-391cc44dcba4.png)

Swipeable removed from tabs
![screen shot 2017-05-28 at 9 19 42 pm](https://cloud.githubusercontent.com/assets/7346620/26534589/86c6043c-43eb-11e7-9ade-9bd311b46c4c.png)

Swipeable added back in (showing code)
![screen shot 2017-05-28 at 9 20 21 pm](https://cloud.githubusercontent.com/assets/7346620/26534594/8f6701f4-43eb-11e7-9885-b35ad45d588e.png)

**Comment by tomscholz** [comment]
The codepen you provided is the default one. Please make sure to hit save when filling out the codepen ;)

**Comment by bmcgonag** [comment]
Sorry about that. 

Try this one
https://codepen.io/bmcgonag/pen/PmvMOO

**Comment by bmcgonag** [comment]
To see all 5 rows, just remove the {'swipeable': true} portion from the tabs section in the javascript

**Comment by tomscholz** [comment]
https://github.com/Dogfalo/materialize/issues/4800
