### ISSUE TITLE
Side Nav Bottom Tab "hidden"

### ISSUE THREAD

**Issue by hktraz** [Dogfalo/materialize#4739]
### Description
Under Firefox (v 53.0.3), when the height of the window is smaller than the total heigh of the side menu, a part of the menu is hidden.

### Repro Steps
From the official website of Materialize framework (http://materializecss.com/), reduce the size of the window under the size of the tab "Showcase" and you're not able to acces the tab "Themes" anymore.

### Screenshots / Codepen
![sidenavissue](https://cloud.githubusercontent.com/assets/9659616/26542402/03dfca02-445a-11e7-9a55-dee767b280b1.png)

**Comment by hktraz** [comment]
Same issue as : #1074, #2112

**Comment by tomscholz** [comment]
Thanks =)
