### ISSUE TITLE
Is there a solution for this?

### ISSUE THREAD

**Issue by victordeassis** [Dogfalo/materialize#474]
Hi guys, first of all congrats for the latest updates on Materialize! It's awesome! Im having some issues with a dropdown and I think maybe you guys can help me, I will attach a picture of the trouble. Thanks!

![bug](https://cloud.githubusercontent.com/assets/6058804/5789811/ebdbb048-9e60-11e4-978e-b64c7c662aa0.png)

**Comment by Dogfalo** [comment]
I'm not sure what problem you are describing.

**Comment by victordeassis** [comment]
If I click on  the multiple dropdowns they will stay open, I wish that when I click on another the latest opened will close.

**Comment by kokakoola** [comment]
I agree. The normal dismiss-behavior is missing. (Thanks for repairing the postitioning)

**Comment by Dogfalo** [comment]
Fixed in 1051a423fe6aa74d984baedcad34d65557318831
