### ISSUE TITLE
showStaggeredList breaks "<select>" elements

### ISSUE THREAD

**Issue by balsoft** [Dogfalo/materialize#4740]
### Description
Using `Materialize.showStaggeredList()` on a list with `material_select()` elements inside breaks selects and animation. 

### Repro Steps
* Add a `<ul>` with `<li>` containing `<select>`
* `$('select').material_select()`
* `Materialize.showStaggeredList('ul')`
* Your `<select>` are under `<li>`, and animation is very slow.

### Screenshots / Codepen
Result:
https://codepen.io/balsoft/pen/dWELmO

### Solution
`element.find('<li>')` in the function `Materialize.showStaggeredList()` should find only the direct children of the element, not all `<li>` tags. Have no idea how to implement that.

**Comment by DanielRuf** [comment]
Probably `element.find('> li')`?

**Comment by balsoft** [comment]
Yes, but it solves only the animation speed issue. The `<select>` still looks awful. My solution (less efficient but working)
```
function showStaggeredList(selectorOrEl) {
    var element;
    if (typeof (selectorOrEl) === 'string') {
        element = $(selectorOrEl);
    } else if (typeof (selectorOrEl) === 'object') {
        element = selectorOrEl;
    } else {
        return;
    }
    element.find('>li').each((i, el) => {
        $(el).css('opacity', 0).css('left', -100)
        setTimeout(() => {
            $(el).animate({
                left: 0,
                opacity: 1
            }, {
                duration: 800,
                easing: 'easeInOutBack'
            })
        }, 120 * i)
    })
};
```
Should I create a pull request or not?

**Comment by DanielRuf** [comment]
A PR makes clear what the changes are that are needed to fix this.

My thought was that this is related to transitions or z-index or some position value (relative and so on).

**Comment by balsoft** [comment]
I dunno, I'm not a very experienced front-end developer. I messed around with z-index and position and couldn't fix it.

**Comment by jacobau** [comment]
This issue is caused by the `transform` property: https://stackoverflow.com/questions/20851452/z-index-is-canceled-by-setting-transformrotate

**Comment by DanielRuf** [comment]
> This issue is caused by the transform property: https://stackoverflow.com/questions/20851452/z-index-is-canceled-by-setting-transformrotate on each li
> 
> At the end of the animation it is transform: translateX(0px), it needs to be transform: none
> 
> Not sure if this is a Materialize issue or velocity issue

Not directly. This is a known CSS issue with transforms in most cases. We might change it to `transform: none` when a single list element has finished with its animation.

**Comment by Dogfalo** [comment]
ShowStaggeredList has been removed in v1-dev
