### ISSUE TITLE
Tooltip animation must be not there by default, and more granular control is needed

### ISSUE THREAD

**Issue by crtag** [Dogfalo/materialize#4741]
### Description
Tooltips show/hide animation is ugly and there needs to be a way to control it in a more granular way, ie as a developer, I want to be able to provide the animation type I want or entirely disable it. The short and effective solution would be an option to disable this ugly rounded border animation by default and provide a way to enable it if there's a need. Moreover, there's nothing about this kind of animation in MD specs at all.

**Comment by aschoenebeck** [comment]
This is quite subjective as I for one do like the tooltip animations. But you are right, if there would be an option for disabling animations everyone would be happy.

**Comment by tomscholz** [comment]
See: https://github.com/Dogfalo/materialize/issues/1877

**Comment by fega** [comment]
I agree with @crtag, it sounds as a pull request!

**Comment by tomscholz** [comment]
Closing this issue in favor for https://github.com/Dogfalo/materialize/issues/1877
