### ISSUE TITLE
Carousel: add a 'fade' transition option (override default sliding behaviour)

### ISSUE THREAD

**Issue by sigmatec** [Dogfalo/materialize#4747]
**Enhancement**

When the carousel is being used as a slider and `fullWidth: true` it would be nice to have an option for the slides to fade in/out (in place) rather than slide left to right: [CodePen](https://codepen.io/davidhc/pen/nLpJk)

Clicking the indicators and triggering `next` would also fade rather than slide.  However, swiping with a finger or dragging should still slide across if possible.

Would only apply when using:
```
$('.carousel.carousel-slider').carousel({fullWidth: true});
```

**Comment by andreagam** [comment]
+1

**Comment by acburst** [comment]
I feel like this is out of scope and feature creep

**Comment by leo-castro** [comment]
+2
