### ISSUE TITLE
Cannot set the menu width and the activation area width on the sideNav 

### ISSUE THREAD

**Issue by errorsmith** [Dogfalo/materialize#475]
The [docs](http://materializecss.com/mobile.html) say that 

> You can set the menu width and the activation area width.

while the sideNav plugin accepts options for *activationWidth* and *edge*. Also, the *activationWidth* is only present in the object literal of the settings, so passing custom *menuWidth* and *activationWidth* to the plugin won't have any effect.

```javascript
// menuWidth and activationWidth are ignored
$('.button-collapse').sideNav({menuWidth: 240, activationWidth: 70});
```

**Comment by acburst** [comment]
We are re working this plugin and we have not yet changed the docs to reflect that. Sorry for the confusion

**Comment by errorsmith** [comment]
Ok, thanks!
