### ISSUE TITLE
error while using tabs

### ISSUE THREAD

**Issue by anuragnagarkota** [Dogfalo/materialize#4750]
Hello

I am using this in meteor project. But I am getting following errors if I move from one tab to another
Uncaught TypeError: Cannot read property 'tweensContainer' of undefined
    at e (materialize.js:999)

Please help to solve this.

**Comment by tomscholz** [comment]
>Please help to solve this.

You have to post a codepen to help us visualize the problem.

**Comment by tomscholz** [comment]
Closed due inactivity. Feel free to reopen it, if it's still necessary.
