### ISSUE TITLE
Avoid dynamically chips to be closable by default

### ISSUE THREAD

**Issue by RadouaneRoufid** [Dogfalo/materialize#4754]
By default when creating chips dynamically, chip generated are closable. It would be very nice to have an option (css class) to void the default behavior. 

```
this.renderChip = function(elem) {
      if (!elem.tag) return;

      var $renderedChip = $('<div class="chip"></div>');
      $renderedChip.text(elem.tag);

      $renderedChip.append($('<i class="material-icons close">close</i>')); // <= this line optionally !
      return $renderedChip;
    };
```

**Comment by Dogfalo** [comment]
Maybe I am not fully understanding what you are talking about, but this doesn't like an option that promotes good UX if the user is not able to edit their own form by deleting chips they created
