### ISSUE TITLE
QUESTION: iPhone 6 - The 'more_items' button doesn't show on left - how can I adjust it.

### ISSUE THREAD

**Issue by bmcgonag** [Dogfalo/materialize#4758]
### Description
I have a navbar, with one <li> that holds the more_items icon.  I have placed it left on the navbar with logo brand centered using your examples online. 

Shows fine on browser, but if I use my iPhone 6 with safari, the icon is hidden at the very left edge of the screen.  I can somehow just barely touch it now and then, but anyone who didn't know it was there, would have no idea to touch there. 

Is there a way to get this to move slightly right, and make the brand logo text smaller on these devices, so the icon will show properly?

Here's the screenshot from the phone.
![2017-06-04](https://cloud.githubusercontent.com/assets/7346620/26762834/51339262-490e-11e7-8c01-d287d8ca338d.png)

Here's a screenshot from browser on mac.
![screen shot 2017-06-04 at 10 16 10 am](https://cloud.githubusercontent.com/assets/7346620/26762861/e21c7a28-490e-11e7-8c5e-7a2568ccd2e3.png)

I have an @media screen setting already, so maybe just need to adjust something in my css to fix this?

Thanks for any help!

**Comment by fega** [comment]
@bmcgonag please follow the guidelines and post a clear and simple codepen showing the issue.

**Comment by bmcgonag** [comment]
No worries.  I actually see the icon...it's there, it's just my Navbar heading (logo) is too long, so ti's covering the icon.  I'll do some research and figure out how to make the font shrink a bit, or how to change that logo when the screen width is smaller.  

You can close this issue as 'Clarification', or whatever equivalent you have.
