### ISSUE TITLE
Prevent Modal to close if form validation fails

### ISSUE THREAD

**Issue by pdas1** [Dogfalo/materialize#4759]
I have a modal form which needs to be validated before submitting. In case, the validation fails I want to keep the modal to remain open and display error messages. However every time I click the submit button the modal window closes.

**Comment by SpykeVibe** [comment]
did you figure this out ? I am having a similar issue

**Comment by stroykova** [comment]
Hello! Is there any solution?
Thanks!

**Comment by sergioburdisso** [comment]
Hi guys! just do not use the class "modal-close" with your modal's action button, this way Materialize won't handle the close event on your behalf and you will have to explicitally call the [modal.clase()](https://materializecss.com/modals.html#methods) method to manually close it after the validation process. Greets

**Comment by kianweelee** [comment]
Example:

**A log-in form in EJS**
```<div id="log-in-modal" class="modal">
  <div class="modal-content">
    <h5 style="text-align: center">Log in</h5>
    <form id="login-form">
      <div class="input-field">
        <input type="email" id="login-email" required />
        <label for="login-email">Email address</label>
      </div>
      <div class="input-field">
        <input type="password" id="login-password" required />
        <label for="login-password">Your password</label>
      </div>
      <button id="log-in-btn" class="btn z-depth-0">Login</button>
    </form>
    <br />
    <a href="#">Forgot your email or password?</a>
  </div>
</div>
```

By default, when you click on this log in button, the modal will close and page will refresh. To prevent this from happening, you need to use `e.preventDefault()` which prevent page refresh + modal closing.

So in JS:

```js
log_in_btn.addEventListener("click", function (e) {
    e.preventDefault();
// Continue coding...
  });
```
