### ISSUE TITLE
not all ripples hiding

### ISSUE THREAD

**Issue by mwsteb** [Dogfalo/materialize#476]
My setup: OSX Yosemite, chrome (Version 39.0.2171.99 (64-bit)) and firefox (version 36.0a2 (2015-01-08))
Issue: after clicking button with waves-effect class, only the first ripple fades. I suspected failed validation to be the culprit and tested it on a regular button - same effect. I stepped into the hide function and noticed that el.removeChild(ripple) is fired only once.

Buttons on official materialize website work fine.

Any idea what might be causing this? Please advise.

See video of the behaviour in the attachment:
http://screencast.com/t/MfzVWGfUD

**Comment by Dogfalo** [comment]
Does this happen on the new release?

**Comment by mwsteb** [comment]
Yes, I've upgraded to the 0.95.0 version, yet the problem remains unsolved.
http://screencast.com/t/jHhvcDkA

**Comment by Dogfalo** [comment]
Can you post your html here hastebin.com?

**Comment by mwsteb** [comment]
http://hastebin.com/xezomosigo.xml

**Comment by Dogfalo** [comment]
I don't see the <head> or script inclusion here

**Comment by mwsteb** [comment]
ah, of course, you wanted the generated html, my bad: http://hastebin.com/lejixeqovo.xml

**Comment by Dogfalo** [comment]
hmm, maybe it is another one of your js files interfering with it. It is not happening for me. what browser and OS are you on?

http://screencast-o-matic.com/watch/coVFoQeyvX

**Comment by mwsteb** [comment]
Very weird. Sadly, the problem persists after removing smooth scrolling js files and initialization.

**Comment by Dogfalo** [comment]
Make sure you are not including our js file twice somehow. We just came across another site with the same problem, but this one was caused by the inclusion of two `materialize.js`

**Comment by mwsteb** [comment]
Indeed, I've somehow managed to include bin/materialize.js AND all the separate js files the comprise it. A glimmer of hope! After removing the duplication there's a slight improvement. Now the final ripple fades upon mouseleave event. If you mouse leaves the button too soon however, it stays till next mouseleave event.

**Comment by mwsteb** [comment]
Soo it turns out that I had another materialize.min.js in a very unorthodox directory which I missed - after deleting it everything runs smoothly. D'oh!

**Comment by Dogfalo** [comment]
:)
