### ISSUE TITLE
Datepicker / date field always displayed as invalid when using validate class

### ISSUE THREAD

**Issue by sigmatec** [Dogfalo/materialize#4760]
When form type of `date` is used with `datepicker` and the class `validate` it always results in it being red underlined as though it is invalid.

![image](https://cloud.githubusercontent.com/assets/17182577/26766892/b264d86a-4991-11e7-9328-8920fb75c666.png)

Other fields such as number are working fine so I don't think it's my app.

**Comment by peabnuts123** [comment]
This appears to be because of the inclusion of the `readonly` attribute. Removing it seems to resolve the issue.

**Comment by Dogfalo** [comment]
Currently type="text" should be used with the datepicker

**Comment by usainicola** [comment]
Same here, even using `type="text"` and no `readonly` attribute:

<div class="input-field">
  <input type="text" class="datepicker validate" id="_date_of_birth" name="_date_of_birth">
  <label for="_date_of_birth">Date of Birth</label>
</div>
