### ISSUE TITLE
Password input's label not animating when using autofill

### ISSUE THREAD

**Issue by kendrickkesley** [Dogfalo/materialize#4761]
Hi, when using remember me feature on chrome / firefox, I can't animate the label in the input fields (email & password) using Materialize.updateTextFields()

**Comment by tomscholz** [comment]
Related:
https://github.com/Dogfalo/materialize/issues/3829
https://github.com/Dogfalo/materialize/issues/2249
https://github.com/Dogfalo/materialize/issues/194
Pull requests:
https://github.com/Dogfalo/materialize/pull/2108
https://github.com/Dogfalo/materialize/pull/1936
