### ISSUE TITLE
Dropdown is not closing after Selecting Value

### ISSUE THREAD

**Issue by NaitikKundalia** [Dogfalo/materialize#4763]
### Description
First of all i am using Materialize 0.98.2. I put dropdown(select) inside the tab. When i select any value, it is selected and highlighted but dropdown is not closing. It remains open until i click anywhere on page. 

### Repro

Codepen where you can find the code : https://codepen.io/naitik_kundalia/pen/bRNeaz
![untitled](https://cloud.githubusercontent.com/assets/29193394/26775016/a73d0674-49f0-11e7-821f-0a1b55d38103.png)

**Comment by DanielRuf** [comment]
Please use

```
$("select").material_select({
onSet: function () {
this.close();
},
});
```

This may be due to the tab catching the event which is not propagating to the generated select.

**Comment by kumaranvram** [comment]
I am facing the same issue, while using it on mobile browsers. It works well on Chrome/Safari on desktop browsers

**Comment by NaitikKundalia** [comment]
@DanielRuf  via using your code it works fine. I think it should be solved in future release so other programmer doesn't need to write this code.

@kumaranvram I am facing this issue on desktop browser.

**Comment by samfrjn11** [comment]
I'm having the issue in Chrome on iOS.. Single select closes fine, but multiselect doesn't close when clicking outside. Read a lot of posts already from more than a year a go, but can't find any solid answer or solution to this problem.

**Comment by NaitikKundalia** [comment]
@DanielRuf You are right. When i use tab swipe event then this bug is occur. Means Tab swipe event is propagating the event.

**Comment by DanielRuf** [comment]
@tomscholz @fega hm, we should check multiselect to but in this case there we have to keep it open to allow the selection of multiple values, especially on mobile browsers. Do we have a close bitton for the multiselect like for the datepicker?

**Comment by Dogfalo** [comment]
Fixed in v1-dev
