### ISSUE TITLE
Provide browser-default for all components (or avoid global styling)

### ISSUE THREAD

**Issue by djensen47** [Dogfalo/materialize#4764]
In order to avoid collisions with other CSS libraries, either provide browser-default for all elements affected or please avoid styling html components a class specific to Materialize is used. For instance in `sass/compoents/forms/_forms.scss`

```
select:focus {
  outline: $select-focus;
}

button:focus {
  outline: none;
  background-color: $button-background-focus;
}

label {
  font-size: $label-font-size;
  color: $input-border-color;
}
```

This literally makes it nearly impossible to use other CSS libraries. It actually looks like all of the forms components act this way.

**Comment by tomscholz** [comment]
Duplicate: https://github.com/Dogfalo/materialize/issues/4661

**Comment by djensen47** [comment]
It's not a duplicate. Using browser-default does not solve this problem/

**Comment by djensen47** [comment]
Wow, on top of that browser-default only works for one component, select lists.

**Comment by djensen47** [comment]
I updated the title to more accurately reflect the issue. 

It looks like browser-default only handles select and date-picker. It also does not reset the :hover behavior.

**Comment by tomscholz** [comment]
https://github.com/Dogfalo/materialize/pull/4041
