### ISSUE TITLE
Card Horizontal stacking on Mobile

### ISSUE THREAD

**Issue by darioalbanesi** [Dogfalo/materialize#4765]
### Description
Is there a clean possibility to make the horizontal card with img stacking on mobile?

### Screenshots / Codepen
here is what I mean:
https://codepen.io/italopupo/pen/bRNqZw

Horizontal Card Desktop
![horizontal card desktop](https://cloud.githubusercontent.com/assets/5655472/26783003/575c517c-49f6-11e7-92b5-9090b3c82c53.png)

Horizontal Card Mobile
![horizontal card mobile](https://cloud.githubusercontent.com/assets/5655472/26783004/575f1a60-49f6-11e7-8f6d-e27acd927876.png)

**Comment by tomscholz** [comment]
See https://github.com/Dogfalo/materialize/pull/4062

**Comment by darioalbanesi** [comment]
thanks @tomscholz 

closing issue -> duplicated
