### ISSUE TITLE
'Required' validation attribute not handled

### ISSUE THREAD

**Issue by EdenGottlieb** [Dogfalo/materialize#4768]
### Description
Validation of the required attribute is not being handled.

### Repro Steps

Create a form, put a text input inside (with appropriate Materialize classes and structures), put a "required" attribute on it, try to submit the form.
The browser handles 'required' being invalid by itself, while all other validation attributes are being handled by Materialize.

### Screenshots / Codepen
https://codepen.io/anon/pen/KqwbPw
<img width="326" alt="screen shot 2017-06-06 at 4 01 17" src="https://cloud.githubusercontent.com/assets/1867324/26809365/e17c25dc-4a6c-11e7-9848-74f235b26fe3.png">

**Comment by J-tt** [comment]
To override the default functon of the required attribute you need to add `novalidate` to the form tag.

But you are correct that materialize is not handling this, according to the docs there is no inbuilt validation, and it seems that it will not be added in (see [this](https://github.com/Dogfalo/materialize/issues/219)).
