### ISSUE TITLE
Range input not hide thumb when finish slide on mobile

### ISSUE THREAD

**Issue by nhattay** [Dogfalo/materialize#4769]

**Comment by thanhma** [comment]
@tomscholz I have same issue when finish slide the range, `touchleave` event seems not firing and the thumb remain `active`.
Is this resolved or not supported?
![2017-06-07_9-49-04](https://user-images.githubusercontent.com/6383907/26860149-973e47d4-4b66-11e7-9183-e7f60628c3e9.jpg)
