### ISSUE TITLE
drag-target div obscures left side of page when not using containers

### ISSUE THREAD

**Issue by frankwiles** [Dogfalo/materialize#477]
Thought I broke something in my app's JS which made a button no longer work, but turned out after upgrading to 0.95.0 the drag-target div floats over the left side of the page in desktop sized browsers. 

See attached screenshot. 
![screen shot 2015-01-17 at 4 18 47 pm](https://cloud.githubusercontent.com/assets/144159/5790572/c0405a5c-9e64-11e4-80ee-7ccf426d4d0b.png)

**Comment by Dogfalo** [comment]
Try updating again, this should not happen.

**Comment by Dogfalo** [comment]
Sorry I misspoke there, we decreased the size of the target so it should be better now. The drag target only takes up 15px. And it is expected that websites will have some content padding. You can fix it immediately on your site by using: 

```css
.drag-target {
  width: 15px;
}
```

**Comment by frankwiles** [comment]
Great thanks!
