### ISSUE TITLE
Update NoUiSlider version from 9.1.0 to 10.0.0

### ISSUE THREAD

**Issue by devAxeon** [Dogfalo/materialize#4772]
Please, update NoUiSlider to v10.0.0  to have a correct touch support on Android, iOS and Windows devices.

**Comment by tomscholz** [comment]
Pull requests are always welcome!

**Comment by flexbox** [comment]
@tomscholz 
What do you think to add it as a dependency is `bower.json` ?

```
  "dependencies": {
    "jquery": ">=3.2.1",
    "nouislider": "^10.0.0"
  },
```

**Comment by tomscholz** [comment]
We use a modified version of nouislider. Also we would have to add it to the package.json

**Comment by tomscholz** [comment]
@devAxeon Also see https://github.com/Dogfalo/materialize/issues/3707

**Comment by flexbox** [comment]
@tomscholz Great! I think we can close this issue because the problem is somewhere else 

![image](https://user-images.githubusercontent.com/360936/27409167-ffc90f56-56d7-11e7-9a8d-66049f74f3f3.png)
