### ISSUE TITLE
Option to show different amount of carousel-items rather than 5

### ISSUE THREAD

**Issue by lastnoob** [Dogfalo/materialize#4773]
### Description
Currently the carousel is showing 5 carousel-items (one active, 2 slightly faded on the sides, and 2 even more faded further on the sides). I'm looking for an option to show a different number, like 3. Only the active one and 2 slightly faded ones. When you swipe to either directions (changing the active slide), the other carousel-items still should show up.

Like here: http://materializecss.com/carousel.html

So, instead of this:
![materialize](https://user-images.githubusercontent.com/1821091/26846719-3e08738e-4ac0-11e7-8c81-938e30b8a9aa.JPG)

I want this:
![materialize2](https://user-images.githubusercontent.com/1821091/26846772-612f34b0-4ac0-11e7-9b12-640952fea024.JPG)

Again, this would just temporarily hide the 2 carousel-items at the sides, and when it's their turn to show up, they would.

Am I missing something and it's possible to do it without custom JS?

**Comment by lastnoob** [comment]
or any ways to dynamically target the left side carousel-item and the right side carousel-item to change its css?

**Comment by lastnoob** [comment]
@tomscholz any idea how to do this?

**Comment by tomscholz** [comment]
Only add 3 slides?

**Comment by lastnoob** [comment]
So it's not possible to add e.g. 8 slides, but only show 3 at any given moment? (and if you swipe one, obviously a new one comes up)

thanks

**Comment by acburst** [comment]
Added in cbb45236deb7b47fdcf31a6a739cc1daf058f2b8
