### ISSUE TITLE
An option to use Materialize without JQuery

### ISSUE THREAD

**Issue by sr229** [Dogfalo/materialize#4779]
I like the framework since its easy to do but theres one thing that hinders me. It's the requirement for JQuery for alot of custom elements.

Is there a way to use these elements without JQuery?

**Comment by tomscholz** [comment]
See https://github.com/Dogfalo/materialize/issues/877

**Comment by styfle** [comment]
> I'm going to lock this issue because it's very old and any new discussion should probably happen on a new issue!

Where is the new issue? I am also interested in materialize without jquery.

**Comment by Dogfalo** [comment]
https://github.com/Dogfalo/materialize/issues/5004

**Comment by styfle** [comment]
@Dogfalo Thanks! 1.0.0 is very exciting!
