### ISSUE TITLE
Outlined Buttons

### ISSUE THREAD

**Issue by Dsaint109** [Dogfalo/materialize#4781]
Would like to suggest adding outlined buttons, like bulma or bootstrap 4... I dont like having to do it myself for every single project

**Comment by DanielRuf** [comment]
The Material Design specification and guides do not define or offer outline buttons. Just raised or flat.

Bootstrap and Bulma do not follow these specs.

**Comment by JayHoltslander** [comment]
https://material.io/components/buttons/#outlined-button

**Comment by DanielRuf** [comment]
> **[DanielRuf](/DanielRuf) **[on 8 Jun 2017](#issuecomment-306992813)

This was 2 years ago ;-)

Things have changed since then.
Answering such outdated issues makes not much sense. Closed issues can be ignored.

**Comment by DanielRuf** [comment]
> **[DanielRuf](/DanielRuf)** [on 8 Jun 2017](#issuecomment-306992813)

This was 2 years ago ;-)

Things have changed since then.
Answering such outdated issues makes not much sense. Closed issues can be ignored.
