### ISSUE TITLE
Make $colors variable overwritable

### ISSUE THREAD

**Issue by DetlefPeters** [Dogfalo/materialize#4783]
The **first 4200 lines** of my CSS are generated by the `@each`-loop in materializecss's "_color.scss", containing every possible color shade from the MD palette.
The intention of MD colors, however, is to pick a primary color + an accent color -> 17 out of 19 colors are never needed once you have chosen 'your' colors.
My idea would be to overwrite the `$colors` variable with a list of only the needed colors.
But I can only overwrite variables which are declared as `!default`.

=> CHANGE REQUEST: please declare `$colors` in "_color.scss" as `!default`.

Regards,
  Detlef

**Comment by DanielRuf** [comment]
Please test #4784.

**Comment by tomscholz** [comment]
Is this a duplicate? Please check https://github.com/Dogfalo/materialize/issues/3612, https://github.com/Dogfalo/materialize/pull/4088 and https://github.com/Dogfalo/materialize/pull/4556

**Comment by DanielRuf** [comment]
Not a duplicate imo, just adds the default keyword.

**Comment by Dogfalo** [comment]
Closed via #4784
