### ISSUE TITLE
Can I clone a div content with 'select' inside and populate after?

### ISSUE THREAD

**Issue by luandr** [Dogfalo/materialize#4788]
Hey, I need copy a entire div block and my select breaks. I need populate using (I think) `$.each()` and I'm using `var things = ["thing1", "thing2"];` so when i add other select bellow the others this new select need be receive `things` content for each option. idk what i'm doing [here](https://codepen.io/luandr/pen/eRpxWG) if someone can help me with that, i'll be grateful. btw my english is rusty 😛 Thanks!
✏️ I was not clear, i need clone the entire `div` 'cause isn't just a `select` but also a `input` linked

**Comment by DanielRuf** [comment]
https://codepen.io/anon/pen/EXVqjV

Also please use the Gitter channel for such general questions as this is not a bug but an integration question.

**Comment by luandr** [comment]
Sorry about my mistake, i'm starting. Hey when I press Add button, using your code, generates 2 `select`, 1 empty and 1 normal, any tip about? Huge thanks @DanielRuf ! I posted here 'cause i saw others users questioning and i have no experience with Gitter. Materialize has a Gitter? How work this platform? ty again

**Comment by DanielRuf** [comment]
Sure, you clone a div which contains both selects at the top.

**Comment by luandr** [comment]
Thank you @DanielRuf ! I solve my problem with some adaptions, if anyone want know how, see bellow.

```var count = 1;
$('#add').on('click', function() { 
  novo = $('.content-select').append('<div class="row"><div class="input-field col s2 offset-s4" id="select' + count + '"><label>Produções não terminais</label></div><div class="col s1 center"><i class="material-icons md-48">trending_flat</i></div><div class="input-field col s2"><input class="ldir" type="text" class="validate"><label for="ldir">Lado direito</label></div></div>')
  $('#copy-select select').clone().prependTo('#select'+count);
  count += 1;
  populate();
  $('select').material_select();
```

**Comment by DanielRuf** [comment]
Where do you initialize the `count` variable?

**Comment by luandr** [comment]
`count` is global, 'cause can't be lost. `count` start with `1`.

**Comment by DanielRuf** [comment]
Well, you should at least declare the variable in the right scope to prevent unwanted side effects.

**Comment by luandr** [comment]
I get it, thanks I will do that, I realize i don't need a global for this purpose. Thanks! Have a great day!

**Comment by tomscholz** [comment]
Please move discussions like this one in the future to gitter. Everytime 997 people get a notification. Keep that in mind
