### ISSUE TITLE
change tab with jquery

### ISSUE THREAD

**Issue by ventouris** [Dogfalo/materialize#479]
I try to change a tab through JQuery when I submit a form on the first tab. However, even if I've tried a lot, I haven't found anything that could make it work.

I tried with `$("#tabs").tabs("option", "active", 2);` and with show function, but nothing. Is there any way to do it?

**Comment by Dogfalo** [comment]
Just trigger a click event.
if you have `id="test"` on your tab,
then you can do `$('#test').trigger('click')`
