### ISSUE TITLE
character-counter height

### ISSUE THREAD

**Issue by Braed** [Dogfalo/materialize#4791]
Can character-counter's height be reduced from 1px to 0px?  
I don't care to look into this right now but the 1px moves the rest of the form down which bothers me.

**Comment by DanielRuf** [comment]
Please test https://codepen.io/anon/pen/GEoMzR and let me know if it works like desired so I can create a pull request for the change.

**Comment by Braed** [comment]
Yeah that's perfect, thanks! For future reference, could I have made that pull request myself? I'm not too familiar with github. Cheers.

**Comment by DanielRuf** [comment]
Sure. Clone the repository to your account, (create a new branch based on master), make the change and commit it, go to the homepage of your repository and there should be a button at the top to create  a new pull request against the original repository.

**Comment by DanielRuf** [comment]
![image](https://user-images.githubusercontent.com/827205/26995010-c71bf39c-4d6a-11e7-9d8c-dfeaadfda7f1.png)

![image](https://user-images.githubusercontent.com/827205/26995032-dd23e1b8-4d6a-11e7-9f67-aac50cfcea6e.png)

![image](https://user-images.githubusercontent.com/827205/26995042-e8a7d148-4d6a-11e7-8eda-8afeacd1d5e7.png)

![image](https://user-images.githubusercontent.com/827205/26995053-f4a8f058-4d6a-11e7-844e-f86bf0d837f4.png)

**Comment by Braed** [comment]
That was really helpful and I'm very grateful, thank you.
