### ISSUE TITLE
Stray character under datepicker field on Firefox

### ISSUE THREAD

**Issue by deb761** [Dogfalo/materialize#4793]
#### Observed on:
- Mac Firefox 53.0.3 (64-bit) 
- Mac Firefox developer edition 54.0b11
- Linux (Ubuntu) Firefox 52.0.1 (64-bit)

### Repro Steps

1. Define an input of type "date" and class "datepicker"
1. Initialize the datepicker in the jQuery document ready function

See this Codepen that demonstrates the issue. https://codepen.io/Engelmeyer/pen/awdQmP

### Screenshots / Codepen

![screen shot 2017-06-09 at 12 59 51 pm](https://user-images.githubusercontent.com/9601218/26994887-aae31e72-4d1e-11e7-89a7-a5d28d1c4c16.png)

**Comment by DanielRuf** [comment]
It is the outline of the root picker element and this is the original position of it but the picker is moved out of it with position fixed and so the outline collapses on a line (no height). The PR https://github.com/Dogfalo/materialize/pull/4795 fixes this.
