### ISSUE TITLE
Can't click on Carousel's active element

### ISSUE THREAD

**Issue by EsmeeSW** [Dogfalo/materialize#4794]
The bug is in the script for the carousel object:
if you scroll to the right you can click on the 'active' object just fine, but if you first scroll to the left then it will ignore any click on the 'active' object.

The bug is in the code for the function "click" inside the carousel code:
In the line (https://github.com/Dogfalo/materialize/blob/master/js/carousel.js#L316):
     var diff = (center % count) - clickedIndex;
the (center % count) doesn't account for the wrap around
the line should read:
      var diff = wrap(center) - clickedIndex;
and the problem is fixed.

**Comment by DanielRuf** [comment]
Please see https://github.com/Dogfalo/materialize/pull/4596

**Comment by EsmeeSW** [comment]
lol I made this fix and commented the solution in the dogfalo chat back in Feb and didn't know about this at all.
and no offense, but I think my solution is 'cleaner'

**Comment by acburst** [comment]
Fixed in 87d8609.

Thanks for the cleaner solution. I'll close the PR
