### ISSUE TITLE
Make Slider more responsive

### ISSUE THREAD

**Issue by Dogfalo** [Dogfalo/materialize#480]

**Comment by P-Flores** [comment]
Please T-T i need advice what size of img for my slider. I moves a lot

**Comment by razvanioan** [comment]
The images within the slider can be easily made responsive, but the slider not as it relies too much on fixed height (css & js). I will try to figure it out a solution myself ...

**Comment by abds5** [comment]
Hi razvanioan, have you find out a solution to make the slider responsive?

**Comment by lewiss444** [comment]
in css add `// SLIDER
.slider {height: 500px;}
@media only screen and (max-width: 768px) {
.slider {height: 850px;}
}`
and in init.js add `if ($(window).width() < 768) {
	   $('.slider').slider({
		   height: 850,
		   duration: 500
	   }).css("height", "");

	} else {

	   $('.slider').slider({
		   height: 500,
		   duration: 500
	   }).css("height", "");
	 }`
