### ISSUE TITLE
image hiding in swipeable tab content

### ISSUE THREAD

**Issue by moghya** [Dogfalo/materialize#4800]
@Dogfalo 
I'm trying to use tabs and in tab content, I want to load a simple img but when I make tabs swipeable image becomes hidden as well as the content in all other tabs.

https://codepen.io/moghya/pen/mwPYdL see demo here

**Comment by DanielRuf** [comment]
I can see them when I use the swipeable option (desktop view, Chrome on Windows).

**Comment by moghya** [comment]
huh ? have you visited above link and uncommented line #22 for setting swipeable true. 
Because I'm not able to see images or content.

**Comment by DanielRuf** [comment]
Yes, that's what I did in the codepen.

**Comment by tomscholz** [comment]
This is a duplicate of https://github.com/Dogfalo/materialize/issues/4148. If not, do not hesitate to say so
