### ISSUE TITLE
Container width

### ISSUE THREAD

**Issue by krosoftware** [Dogfalo/materialize#4801]
Hello
where I can set width of container? I need to set it a bit wider.
Thank you.

**Comment by DanielRuf** [comment]
@krosoftware just overwrite `.container`, see https://github.com/Dogfalo/materialize/blob/master/sass/components/_grid.scss

**Comment by tomscholz** [comment]
@krosoftware Please use gitter for questions like this instead!!
https://gitter.im/Dogfalo/materialize

**Comment by krosoftware** [comment]
Awesome, thank you.
