### ISSUE TITLE
Many of the websites featured under showcase are down or point to malware

### ISSUE THREAD

**Issue by rohanp** [Dogfalo/materialize#4804]
down
- https://www.100xp.io/ 
- http://www.hackercup.co/
- http://www.straphq.com/
- http://www.jumpr.it/

malware 
- http://emerald.sekizgen.net/
- http://jumpcatch.com/srinivasan/caliber/

**Comment by tomscholz** [comment]
See: https://github.com/Dogfalo/materialize/issues/4275
