### ISSUE TITLE
List of icons out of date

### ISSUE THREAD

**Issue by EddyVinck** [Dogfalo/materialize#4812]
I'm trying to two icons for notifications.

When you have a notification I want to use 'notifications'. When you don't have any notifications I'm trying to use 'notifications_none'(found on https://material.io/icons/) however the second one isn't available. When I tried searching for an icon on the materialize website I noticed that icons that are already implemented are missing too, such as the first icon.

**Comment by shmshd12** [comment]
Materialize isn't hosting any icons. For icon reference you have to refer [material.io](https://material.io/icons). Icons are provided by Google. Using [CDN of Google](http://fonts.googleapis.com/icon?family=Material+Icons) will give you all icons shown in [material.io]( https://material.io/icons).

**Comment by DanielRuf** [comment]
@tomscholz @fega I suggest the following:
* replace the current list with https://github.com/google/material-design-icons/blob/master/iconfont/codepoints
* prominently link to the icons page (currently just in the nav on the right side) and describe the steps to get the desired text for the icon
* remove / update the icon count (740, currently 932 with duplicates)

**Comment by tomscholz** [comment]
@DanielRuf I think we should safely remove all the icon examples and just show how to use them and where to find them. Similar to this [documentation](http://www.material-ui.com/#/components/font-icon).

**Comment by DanielRuf** [comment]
@tomscholz this was my initial idea but then we have to describe where to click to get the embed code / text for the needed glyph.

**Comment by tomscholz** [comment]
In the getting started guide the icons are included by default.

**Comment by DanielRuf** [comment]
@tomscholz hm, where exactly? http://materializecss.com/getting-started.html

Also I mean some description like:
* go to https://material.io/icons
* input something in the search and (optionally)
* click on the needed icon
* click **icon font** on the blue toolbar at the bottom
* copy the content between `<i class="material-icons">` and `</i>` and paste it in the i tag in your layout

**Comment by tomscholz** [comment]
If our users are ~~too stupid~~, sorry not able to read the guide, on the material.io site, they shouldn't use this framework :trollface: . We should link them to material.io/icons and https://google.github.io/material-design-icons/#icon-font-for-the-web . There they get all the information that is needed to include the icons

**Comment by DanielRuf** [comment]
Well, most people need a quick overview and directly the information they are looking for instead of reading another full page about the icons and trying to find the needed text as it is a bit hidden ;-)

Not sure how many people would ask then how they can include the icons.

Think about a good UX when people read our docs and they await all the needed information there.

I guess we should hear the opinion of other developers and the rest of the community and then make decisions. Because removing things is probably not a big problem for intermediate and professional developers but makes it harder for beginners which are new to Materialize.

Just my opinion on this topic. Because the linked site contains much unneeded information and does not summarise it to a few important points. Keep it short and simple.

**Comment by Dogfalo** [comment]
The list just needs to be updated every so often. People familiar with MDI will understand that https://material.io/icons/ will always have the most up to date llisting, but the current icons documentation is still helpful as it gives an easily copy-pastable lookup table

**Comment by smileytechguy** [comment]
We could maybe list a few examples, such as very common ones (grade, account_circle, etc.) just like 4 or 5 to start with, and then link to the official page.  I like that it lists a small handful just for examples sake, as that is very helpful when teaching people how to use materialize (they get overwhelmed if i show them the full page at first, as there are so many, and will take 15 minutes picking one).
