### ISSUE TITLE
FEATURE REQUEST: Contact Bubbles

### ISSUE THREAD

**Issue by Native-Coder** [Dogfalo/materialize#4816]
I wonder how hard it would be to implement "contact bubbles" like the ones on Android?

Basically if the contact doesn't have a profile pic, it uses the first letter of their name inside a colored bubble? Like the ones pictured [here](https://i.stack.imgur.com/tuCTS.jpg) (to the left)

**Comment by tomscholz** [comment]
We are not looking to add this into our core framework. It is easy enough to customize yourself. Also do we currently only want to fix bugs, etc. and then we will look into adding new features again.

**Comment by DanielRuf** [comment]
As @tomscholz wrote, not part of the official Material Design guidelines. @arturheinze created something here: https://codepen.io/arturheinze/details/ZGvOMw

**Comment by smileytechguy** [comment]
@Native-Coder I looked at what @DanielRuf posted it and expanded it to match what you needed: https://codepen.io/anon/pen/owzQWM.  If the `img` element lacks a `src` attribute, it will add the avatar effect, otherwise it will just display the image as normal.

**Comment by Native-Coder** [comment]
@smileytechguy Thats pretty perfect! Thank you!
