### ISSUE TITLE
Two button  in a modal

### ISSUE THREAD

**Issue by tceydeliler** [Dogfalo/materialize#4818]
Hi, I have a form in a modal. and there is two button. One of them fur sending something to client. Second is to submit  form. 
But when I click on first one modal closed. WHat I want?
I want to modal close only when I click second button.

Fİrst button is :`input name="accept" type="button" value="Porola Al" onclick="sendData({telno: document.forms['gunubirlik_sms']['auth_no'].value,smskod: document.forms['gunubirlik_sms']['auth_SMS'].value})" class="btn" />`

Second button is: `<input name="accept" type="submit" value="Giriş" class="btn" />`
What should I do?

**Comment by DanielRuf** [comment]
@tceydeliler can you provide a codepen so that we can work with it? Probably you have to prevent the default action on the first button with preventDefault or similar.

**Comment by tceydeliler** [comment]
Ok now. i fixed.

**Comment by DanielRuf** [comment]
Generally please ask howto questions in our Gitter channel.

Is your issue solved? If yes, please close your issue.

**Comment by smileytechguy** [comment]
If anyone else has this issue, the problem most likely is your use of `.modal-close` buttons.  If you want to submit a form, use jQuery like so:

```js
$("#yourButtonId").click(function() {
    $("#yourFormId").submit();
});
```

**Comment by DanielRuf** [comment]
> If anyone else has this issue, the problem most likely is your use of .modal-close buttons. If you want to submit a form, use jQuery like so:
> 
> $("#yourButtonId").click(function() {
>     $("#yourFormId").submit();
> });

I would recommend using
```JS
$('.modal').on('#yourButtonId', 'click', function(e) {
    e.preventDefault();
    $("#yourFormId").submit();
});
```

**Comment by smileytechguy** [comment]
@DanielRuf the `.on` API is `.on( events [, selector ] [, data ], handler )`.  Why would you use the modal as the selected element?

**Comment by DanielRuf** [comment]
> @DanielRuf the .on API is .on( events [, selector ] [, data ], handler ). Why would you use the modal as the selected element?

Had the wrong order for the parameters, fixed the code snippet. Thanks =)
Because you do not have to bubble the event up the whole DOM tree, just until .modal (delegated event).

**Comment by smileytechguy** [comment]
Ah, I see.  Thanks, I didn't know that, all my code uses `.click` or similar!
