### ISSUE TITLE
Valign and responsivenes

### ISSUE THREAD

**Issue by davidsoderberg** [Dogfalo/materialize#482]
Hi,
Why does not s12 work when I have ```valign-wrapper``` on row div?
```
<div class="row no-mar valign-wrapper">
			<div class="col s12 m4">
				<img class="valign" src="http://lorempixel.com/g/400/200/" width="100%" alt=""/>
			</div>
			<div class="col s12 m8">
				<h2 class="no-mar">Välkommen</h2>

				<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Aliquam atque dolore enim error esse ipsum
					iusto laudantium nam numquam odio officia officiis, quasi ratione reiciendis sequi, sit ut veritatis
					voluptas?</p>

				<p>Asperiores, aspernatur delectus ducimus est fugiat ipsum natus, qui quis repellat sed suscipit
					tempore tenetur, unde. Dolor exercitationem incidunt molestiae, nisi obcaecati quis voluptatibus?
					Cumque hic magni maxime perferendis rem.</p>
			</div>
		</div>
```

**Comment by Dogfalo** [comment]
It looks like it is working ![](http://puu.sh/eGJ0x/91be6bac7f.png)

**Comment by davidsoderberg** [comment]
Try to resize the browser to a smaller browser...

**Comment by Dogfalo** [comment]
Looks fine to me ![](http://puu.sh/eMHil/bbba94c860.png)

**Comment by davidsoderberg** [comment]
Should it not stack?

**Comment by Dogfalo** [comment]
Not when you put the valign around it.

**Comment by davidsoderberg** [comment]
ok :smile:

**Comment by lukasziegler** [comment]
How is it possible to achieve the desired effect? To have the two columns valign'ed on medium and large screens, and on small screens to have the columns stacked? Is it possible to only valign the column, and not the entire row?
I would also have expected the layout to break on small screens.
