### ISSUE TITLE
Form in swipeable tabs

### ISSUE THREAD

**Issue by bert-w** [Dogfalo/materialize#4820]
Has anyone tried putting some materialize form elements into a tabs-component initialized with `.tabs({swipeable:true})`?

I've tried so and it bugs out completely and it is not useable at all

**Comment by DanielRuf** [comment]
@bert-w General questions should be asked in the Gitter channel. Please read the issue template when you create an issue. It would be good to have a codepen.

You might have to call `Materialize.updateTextFields();` in combination with `onShow()` of the tab component. But the change to make this work with `swipeable` is not yet available in a release but in the master branch, see https://github.com/Dogfalo/materialize/commit/8129f11bea975c46af391a28614f490d4fa6024e

Please prepare a codepen and post your question in the Gitter channel.
