### ISSUE TITLE
All Javascript Components should be initialized by the user

### ISSUE THREAD

**Issue by bert-w** [Dogfalo/materialize#4821]
### Feature request
I noticed that there are several javascript components that are being initialized by default. These include but are not limited to: `Tabs`, `Dropdown`, `Collapsible`.

Exclusions are: `Parallax`, `Carousel`.

I'm wondering what the potential overhead is of this. Imho all of these javascript components should be initalized manually when needed. Automatic initialization also takes away the possibility to pass options, for instance `$(...).tabs({swipeable: true})` would be a nice initializer if you want all tabs-components to be swipeable.

This might also solve potential issues with re-initializing js-components, for instance in a single-page app where everything is being loaded dynamically. In this scenario it is likely that some components might be initialized 2 times (depending on the DOM availability at page startup).

The goal here is to have any app do as little work as possible. I can see the benefit of loading various components that are used a lot, but there are solutions to load nothing at all AND make it easy for the programmer to load stuff manually, like `materialize.init('tabs', 'dropdown', 'collapsible')` (using the default options in this case)

**Comment by Native-Coder** [comment]
I disagree. I like being able to create a dropdown, and not have to write any javascript. If I need custom initialization, I'll throw it in `$(document).ready` 

When I load things dynamically, I just write an `initialize_material()` function and call it when needed.

**Comment by Dogfalo** [comment]
See #5004
