### ISSUE TITLE
How can you change slider indicator color?

### ISSUE THREAD

**Issue by frmdstryr** [Dogfalo/materialize#4829]
Looks like the [Slider](http://materializecss.com/media.html#slider) indicator active color is hardcoded to green. Is it possible to set this via adding "<color>-text"  class somehow?

Thanks!

**Comment by DanielRuf** [comment]
You can change it with `$slider-indicator-color`, see https://github.com/Dogfalo/materialize/blob/master/sass/components/_slider.scss#L87

**Comment by frmdstryr** [comment]
I don't really want to modify the css for each color (eg if there's different sliders on different pages that need different colors).  Would it be possible to make this adjustable by adding a class like other elements?

**Comment by DanielRuf** [comment]
@frmdstryr you can overwrite the CSS, see https://github.com/Dogfalo/materialize/blob/master/dist/css/materialize.css#L7933-L7943 or use thr Sass version.
