### ISSUE TITLE
Parallax responsiveness

### ISSUE THREAD

**Issue by JGibson98** [Dogfalo/materialize#483]
Parallax containers don't work well responsively, and end up looking silly as the device moves them down below the content centred on the parallax unit. 

The result is a bunch of white spaces and odd looking parallax images.

**Comment by CoDEmanX** [comment]
Are you referring to mobile phones? There is no parallax effect on my phone, which kinda makes sense for small screen sizes I guess.

**Comment by nahtnam** [comment]
Hey!

Just want to add to this. I am creating a website but parallax is really glitchy. If I load the page, it looks like this: http://i.imgur.com/veuNwkj.png (extra white space). It doesnt work until I force refresh it. At that point, it looks like this: http://i.imgur.com/mcQmOeB.jpg (normal)

Ubuntu 14.04, 1080p, Latest Chrome.

**Comment by mazzie14** [comment]
I have the same problem on one page, but not on another in the same app. Didn't make time yet to sort it out though ...

**Comment by acburst** [comment]
Fixed in bc0d1be4b5b1df39e1c759af08a6e7869b28e2db
