### ISSUE TITLE
Lever of Switch component not as per the Material Guideline

### ISSUE THREAD

**Issue by shmshd12** [Dogfalo/materialize#4831]
Lever of Switch provided by Materialize is 5px longer compared to the Switch from [material.io.](https://material.io/components/web/catalog/input-controls/switches/)

switch from Materialize
![switch_materialize](https://user-images.githubusercontent.com/11484121/27258930-910b46c2-5418-11e7-935a-bfda9af758fd.png)
Switch from material.io
![switch_material.io](https://user-images.githubusercontent.com/11484121/27258931-910b77f0-5418-11e7-80ff-fbe19429e38f.png)

**Comment by DanielRuf** [comment]
Generally I see no recommendations regarding the width at https://material.io/guidelines/components/selection-controls.html#selection-controls-switch

**Comment by shmshd12** [comment]
If that is the case, then they did not even mention border-radius of lever and the height of the of circle still Materialize team managed to create one similar. Goal of Materialize is to create every components look same as it is shown in Material Design Guideline right?

**Comment by Dogfalo** [comment]
Fixed in 0c48dc1b53b5cf10223701ac261b36d465c3e8b7
