### ISSUE TITLE
Reinitializing the same carousel generates multiple indicators

### ISSUE THREAD

**Issue by fjsuarez** [Dogfalo/materialize#4834]
When using the `carousel({indicators: true})` method to initialize an existing carousel, it creates a new `<ul>` with indicators instead of modifying the existing one.

Is there any method to destroy the existing carousel?

Link to fiddle reproducing the issue. https://jsfiddle.net/8tq4ycm3/10/

**Comment by DanielRuf** [comment]
@fjsuarez not sure why you remove the initialized class because this is needed to prevent this issue.

See https://github.com/Dogfalo/materialize/blob/master/js/carousel.js#L63-L71

So you bypassed this safeguard. Currently there is no cleanup / destroy / remove method.

**Comment by fjsuarez** [comment]
Because if the the `initialized` class is not removed, then one can't dynamically add new slides, or reconstruct the carousel for that matter.

Any suggestions on how to do this in the best way?

**Comment by DanielRuf** [comment]
So far you would have to remove ul.indicators to simulate your teardown / reinitialization method.

I think we need some check for the indicators and add them just once or replace them and/or support a proper reinitialization.

**Comment by DanielRuf** [comment]
See https://jsfiddle.net/u774mLrk/ for a temporary solution.

We should keep this issue open to track this problem.

**Comment by acburst** [comment]
Added a carousel destroy method in 22c972980288dc07cb2ae16cd183f1c5035b9e95

**Comment by tomscholz** [comment]
@acburst Is this https://github.com/Dogfalo/materialize/pull/2428 also covered?
