### ISSUE TITLE
Consistent helper classes for all breakpoints

### ISSUE THREAD

**Issue by rossjrw** [Dogfalo/materialize#4836]
### Description
Current hiding helpers:

    .hide			Hidden for all Devices
    .hide-on-small-only	Hidden for Mobile Only
    .hide-on-med-only	Hidden for Tablet Only
    .hide-on-med-and-down	Hidden for Tablet and Below
    .hide-on-med-and-up	Hidden for Tablet and Above
    .hide-on-large-only	Hidden for Desktop Only

Additional helpers for example .hide-on-large-and-down (or a new syntax to allow more dynamic hiding) would be useful

**Comment by DanielRuf** [comment]
Reference: #4459 #4594

**Comment by DanielRuf** [comment]
@tomscholz we should collect the information from all related issues and create an overview of missing helper classes.
