### ISSUE TITLE
Nested tabs indicator not initializing properly

### ISSUE THREAD

**Issue by travisbotello** [Dogfalo/materialize#4837]
### Description
Nested tabs indicator not initializing properly when child tabs component is in non-active parent tab.

### Repro Steps
1. Create parent tab component with at least two tabs
2. Add second level tab component in second/non-active tab container
3. Switch from first tab to second tab in parent tab component that holds nested tab component 
4. Indicator is not initialized properly. Have to run $('ul.tabs').tabs(); again to get correct layout

https://codepen.io/anon/pen/awJpwm

**Comment by tomscholz** [comment]
You can use the onShow option. See https://codepen.io/anon/pen/GEWrxB
