### ISSUE TITLE
Flickering by open SideNav

### ISSUE THREAD

**Issue by krosoftware** [Dogfalo/materialize#4838]
I see a problem by opening SideNav (your original example from here: http://materializecss.com/side-nav.html - but only when I use full screen.
With other words - when my browser is on full screen (Chrome) I see flickering when I click on "Side Nav demo" Button.
When I don't use full screen or when I use Edge (on any screen size) - flickering is gone.

**Comment by tomscholz** [comment]
I am not able to reproduce your problem. Can you provide a screencast or something else, that could help us to identify the problem

**Comment by krosoftware** [comment]
I have no place where I can upload it except to dropbox as ZIP.
Maybe I can solve it with increase of animation speed?
How can sidebar animation speed can be increased?

**Comment by ManuZiD** [comment]
possible duplicate: https://github.com/Dogfalo/materialize/issues/4635

**Comment by krosoftware** [comment]
It's not duplicate, on my case, sidebar tremble when opening.
I'm using full browser screen and this code to display sideNav:
    <a href="#" onclick="$('.dashboard_invoice_class').sideNav('show');" class="modal-action modal-close waves-effect waves-blue blue btn ">Side nav demo</a>
and this is sideNav
        <ul id="dashboard_invoice" class="side-nav">
            <div id="test16" class="col s12">
              <li><a href="#!">First Sidebar Link</a></li>
              <li><a href="#!">Second Sidebar Link</a></li>

              <div class="input-field col s12">
                <select id="select_shop" onChange="changecat(this.value);">
                  <option value="" disabled selected  >Choose your option</option>
                  <option value="1">Option 1</option>
                  <option value="2">Option 2</option>
                  <option value="3">Option 3</option>
                </select>
                <label>Select</label>
              </div>
            </div>
        </ul>
        <a href="#" data-activates="dashboard_invoice" class="dashboard_invoice_class"></a>

**Comment by krosoftware** [comment]
How to increase animation speed (I mean on animation by sideNav opening)?
Thank you.

**Comment by tomscholz** [comment]
Closed due inactivity. Feel free to reopen it, if it's still necessary.
