### ISSUE TITLE
responsive-table with custom tr/td height

### ISSUE THREAD

**Issue by troncomputers** [Dogfalo/materialize#4839]
### Description
Resposive-table not working when you set custom tr, td height

CodePen example:
https://codepen.io/anon/pen/vZxxXv

![table_screen](https://user-images.githubusercontent.com/29543667/27285760-048260be-54fe-11e7-91e1-b8b7f2c31c20.png)

**Comment by tomscholz** [comment]
https://codepen.io/anon/pen/pwedBJ
