### ISSUE TITLE
parallax images not showing on page

### ISSUE THREAD

**Issue by nanda248** [Dogfalo/materialize#4841]
I have 2 parallax images on the same page. Both are not working. Below is the screenshot of what i see in html of developer tools. So i can see the image there and so it means there is no issue with accessing the image.
![parallax not working](https://user-images.githubusercontent.com/19261650/27290979-6f02a898-5541-11e7-97ea-47761f0a20db.PNG)
![capture](https://user-images.githubusercontent.com/19261650/27291161-1881cef8-5542-11e7-9223-38e4a9255b70.PNG)
below is what i see when i console log "$('.parallax')".  
![console](https://user-images.githubusercontent.com/19261650/27291048-ae2f0110-5541-11e7-9a85-a4bb9dea585f.PNG)

**Comment by DanielRuf** [comment]
@tomscholz also looks like we have duplicate rules in the minified files. Is this the case?

**Comment by tomscholz** [comment]
Can you please a codepen to reproduce the issue

**Comment by tomscholz** [comment]
@DanielRuf No, he is just using both (`materialize.min.css` & `materialize.css`)

**Comment by DanielRuf** [comment]
Ah I see, sorry.

**Comment by ribsousa** [comment]
I have the same problem when I upgraded to **version 0.99.0**

```css
.parallax-container .parallax {
    position: absolute;
    top: 0;
    left: 0;
    right: 0;
    bottom: 0;
    z-index: -1;
}
```
The problem is the property **position: absolute;** in class **.parallax** when I remove it img parllax show correctlyl

**Comment by tomscholz** [comment]
@nanda248 @ribsousa Please provide a codepen that reproduces the issue!
