### ISSUE TITLE
dropdown-button with fixed position

### ISSUE THREAD

**Issue by bukibarak** [Dogfalo/materialize#4842]
Hi,

I have a fixed dropdown-button that "replace" the navbar on my site. The problem is that the position on the related dopdown-content is set as absolute. So if the page have a vertical overflow and you are not on the top of the document, you'll not see the dropdown-content.

Is there any way to easily set the position of the dropdown-content to fixed ? Because the only way i found to prevent this issue is to set a timeout function with 1ms (uncomment the line on codepen and it'll work as expected).

**[CodePen](https://codepen.io/anon/pen/QgpMGy)** 

Thanks :)
_sorry for my bad english, it's not my native language_

**Comment by DanielRuf** [comment]
See the following line: https://github.com/Dogfalo/materialize/blob/2746daeed242088a298fd4b0b06f6ce2c2242f6a/js/dropdown.js#L169

We need a fix for fixed parent elements as `position()` gets the wrong value, we probably need `offset()`.

https://stackoverflow.com/questions/26844757/offset-top-is-not-working-as-expected-in-if-parent-element-is-fixed

**Comment by bukibarak** [comment]
Just tested by changing the line with `top: origin.offset().top + verticalOffset + scrollYOffset,`.

With this method the dropdown-content is well positioned when you click the dropdown-button, but if the user scroll when the dropdown is opened, the button won't follow the scroll **but** the content will do it (because the content don't have a fixed position).
![2017-06-21 16_30_37-sw runes informations](https://user-images.githubusercontent.com/23739405/27389828-dc1205c8-569f-11e7-9ddc-b14dae990809.png)


I think the best fix should be to add a "dropdown-static" class or a data attribute that change the position of the dropdown-button and the dropdown-content to static.

**Comment by DanielRuf** [comment]
@bukibarak there are more lines probably. I'll prepare a modified version of the component and create a simple codepen and a PR for it.

**Comment by acburst** [comment]
Just don't make the button itself position fixed. If you wrap it in a fixed container everything should work fine.
