### ISSUE TITLE
Snackbar with action button not in Materialize

### ISSUE THREAD

**Issue by shmshd12** [Dogfalo/materialize#4846]
Snackbar (Toast) with action button not in Materialize which is mentioned in [Material Design Guideline.](https://material.io/guidelines/components/snackbars-toasts.html#snackbars-toasts-usage)

Example:
![snackbar_action](https://user-images.githubusercontent.com/11484121/27319208-5d9622a0-55a1-11e7-8dee-8c01d8a259d5.png)

**Comment by DanielRuf** [comment]
@shmshd12 sure, you can mix custom html, even flat buttos, with toasts, see https://codepen.io/anon/pen/awWWQr

**Comment by shmshd12** [comment]
@DanielRuf It is not about modifying any elements, there should be a build in components which are mentioned in MD Guidelines if Materialize is strictly focusing on MD Guidelines.

While you ignored this, [Dogfalo added the feature.](https://github.com/Dogfalo/materialize/commit/87373d6b4551917e9b6d5b96afd031d521a8a285).

**Comment by DanielRuf** [comment]
I did not ignore it but provided a viable solution as HTML was already allowed.

https://github.com/Dogfalo/materialize/issues/4553
