### ISSUE TITLE
Input .validate class messes with data-error and data-success

### ISSUE THREAD

**Issue by bert-w** [Dogfalo/materialize#4847]
### Description
The  `.validate` class for inputs seems to be a trigger to start validation for input elements (based on their "type" attribute i presume?). However, most times this automatic validation is not desired and the programmer needs to add the `.valid` or `.invalid` classes manually.

Check the reproduction steps below to see how an error or success message is not correctly displayed when leaving out the `.validate` class, using the properties `data-error` or `data-success`

### Repro Steps
Try the following html snippet:
```html
<div class="row">
  <div class="input-field col s12">
    <!-- Leaving out the .validate class here -->
    <input id="email" class="invalid" type="email">
    <label for="email" data-success="long success that results in various lines" class="active" data-error="long error that results in various lines">Email</label>
  </div>
</div>
```

( paste it in this codepen: http://codepen.io/Dogfalo/pen/xbzPQV )

**Comment by DanielRuf** [comment]
https://codepen.io/anon/pen/MomyVX

Thanks for reporting. Will chevk this later.

**Comment by DanielRuf** [comment]
@bert-w you have to call `validateField` on the needed element(s) to trigger the validation:

https://codepen.io/anon/pen/jwmmRx
https://codepen.io/anon/pen/XgRgrw

@tomscholz we do not have this documented. Should we add a section to the docs about manually triggering the validation on fields using `validateField`? Makes sense imo.

**Comment by acburst** [comment]
Error and success messages have been decoupled from the label element in aa03660a179d5824847a8179868ba19431605c0b on the v1-dev branch. These styling issues will be fixed for v1
