### ISSUE TITLE
replace PhantomJS with SauceLabs

### ISSUE THREAD

**Issue by DanielRuf** [Dogfalo/materialize#4851]
PhantomJS is not really actively developed anymore and we should run the tests on more browsers and platforms.

I think someone from @saucelabs wrote us in an issue or PR here.

How should we go about the Grunt file? Because for local tests people need PhantomJS (or a better alternative).

Let's collect possible alternatives for local testing and discuss the integration of SauceLabs for CI tests.

**Comment by Dogfalo** [comment]
Hheadless chrome is coming soon

**Comment by DanielRuf** [comment]
@Dogfalo it's shipped with Chrome 59 which was released this month afaik.

https://developers.google.com/web/updates/2017/04/headless-chrome

**Comment by DanielRuf** [comment]
Generally the pull and commit hooks should run the tests on multiple platforms.

For local testing we can use something like https://www.npmjs.com/package/run-headless-chromium, Karma https://github.com/karma-runner/karma/issues/2489 or some other solutions.

**Comment by Dogfalo** [comment]
Would prefer focusing on getting testing working with karma first before looking into SauceLabs

**Comment by tomscholz** [comment]
@DanielRuf It was BrowserStack

**Comment by DanielRuf** [comment]
Ah, but does it provide a table like SauceLab does or just the single success / failed indicator for pushes?
