### ISSUE TITLE
use <body> instead of separate wrapper div for navbar-fixed

### ISSUE THREAD

**Issue by Snewk** [Dogfalo/materialize#4852]
### Description
The materialize navbar handles a fixed navigation bar by creating a fixed wrapper div underneath the navbar. The extra div handles the page offset(via the height property) and z-index. 

This commit moves the z-index property to the actual `.navbar-fixed nav` element itself, and handles offset using `top`on both elements

### Repro Steps
1: create a `<nav>` element.
2: add `class="navbar-fixed"` to the parent element (`<body>`).
3: scroll down to see elements on top of the fixed navbar instead of underneath it.
4: page offset does not function in this case.

### Screenshots / Codepen
https://codepen.io/anon/pen/vZmWEy
![currently](https://user-images.githubusercontent.com/7945901/27712167-c2e99548-5cf3-11e7-818d-7c703cfb5f6a.png)

### Corrected
https://codepen.io/anon/pen/Kqmypx
![corrected](https://user-images.githubusercontent.com/7945901/27712223-fe966224-5cf3-11e7-8a49-f9a33b508c76.png)

NOTE: this is a correction on a previous PR for the same issue.

**Comment by Snewk** [comment]
PR https://github.com/Dogfalo/materialize/pull/4854/commits/d635420993672bab698698784b849074211e2574

**Comment by DanielRuf** [comment]
@Snewk did you try to add a wrapper div around the nav and give it the navbar-fixed class? Because this creates a separate block for the nav and sets the position for it.


https://codepen.io/anon/pen/xrdjbq

Generally your PR is good and moving the class to the body to toggle it easily is a good idea and an actual use case.

https://codepen.io/anon/pen/eRWrNZ

Can you update the docs (in the jade/page_contents directory) and change the paragraph in navbar.html, remove the wrapper div and update the wording to point at body.

Thanks for the PR. This should make the component more flexible.

I'll check the js component if there are any breaking changes.

**Comment by Snewk** [comment]
@DanielRuf When testing, I tried adding a wrapper div and giving it the class navbar-fixed. This correctly created a fixed navbar using a separate block for the nav (as you explained).

The only problem is the z-index gets applied to the wrapper div instead of the nav element itself. Since the nav doesn't get a z-index assigned to it, other elements on the page will appear on top of the navbar.

This PR will make the code for the navbar-fixed class work correctly as it is currently documented, so no changes to documentation should be required. 

The navbar-fixed property will still need to be applied using a wrapper div, but now the z-index will be applied to the nav element instead of the wrapper.

**Comment by DanielRuf** [comment]
@Snewk your PR makes sense for special use cases. Maybe I can identify and fix the issue in the js component to prevent issues and decouple it a bit more for a more modular approach in the future.

@tomscholz should we enforce our rules or give developers more freedom over this?

**Comment by DanielRuf** [comment]
> Also, in this case, is no way to offset the page content to a custom value. In fact, trying to adjust the height will increase the height of the body from the bottom instead of the top.

@Snewk Do you mean the `$navbar-mobile-height` variable or how did you do this?

**Comment by Snewk** [comment]
> Also, in this case, is no way to offset the page content to a custom value. In fact, trying to adjust the height will increase the height of the body from the bottom instead of the top.

@DanielRuf Yes, i meant by changing the `height` directly or by changing `$navbar-height-mobile`. Take a look at the following structure:
`<body>`
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;`<div class="navbar-fixed"`
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;`<nav></nav>`
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;`</div>`
`</body>`

Here, the div gets `z-index: 997;` as well as `height: $navbar-height-mobile;`. This div holds the navbar over the page content, and it pushes the page down by `$navbar-height-mobile`. Everything works.

BUT, if we use the following:
`<body class="navbar-fixed">`
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;`<nav></nav>`
`</body>`

The `z-index` and `height` cannot be assigned to the body in the same way. There is no element underneath the navbar to hold it above the content at `z-index: 997;` or to offset the page by `$navbar-height-mobile`.

If we want to allow developers the freedom to use `<body class="navbar-fixed">`, we should incorporate my PR. Unfortunately, this will still leave the issue of page content being hidden underneath the navbar. 

I would be happy to update the documentation to reflect this limitation if you decide to implement my change.

**Comment by Snewk** [comment]
After some more tinkering, I may have come up with a solution. 
https://codepen.io/anon/pen/Kqmypx
![screen shot 2017-06-21 at 4 25 19 pm](https://user-images.githubusercontent.com/7945901/27405137-691896d2-569e-11e7-9d03-3329d82d8d27.png)

instead of giving the navbar-fixed wrapper a `height: $navbar-height-mobile`, we can use `top: $navbar-height-mobile ` instead and then add `top: 0px` to the nav element.

**Comment by DanielRuf** [comment]
@Snewk ah right. I should tried the different offsetting solutions for fixed elements.

Cool. There is always a solution ;-)

Please also make the changes in the branch of your PR.

**Comment by Snewk** [comment]
glad to help. here is the PR
https://github.com/Dogfalo/materialize/pull/4859/commits/f3b3888099d78317eed31a97f9d0cfaabc989697

**Comment by DanielRuf** [comment]
Looks much better.

@acburst @tomscholz your opinions?

**Comment by Snewk** [comment]
@DanielRuf @tomscholz 

Found an issue with my PR so I closed it. Fixed it in a new PR. Here is the commit :
https://github.com/Dogfalo/materialize/pull/4915/commits/2bef95f2313aaecf59261da2b7ab9b2a5b4b86b5

**Comment by DanielRuf** [comment]
@Snewk you could push new commits to your (old) branch to update your PR.

**Comment by Snewk** [comment]
my bad. i am still pretty new to contributing to projects i use. will make sure to do that in the future.

**Comment by Snewk** [comment]
@DanielRuf i agree that we need to test this change to ensure things continue working as expected. 

I noticed the file `test/html/fixed_navbar.html` is this currently in use anywhere? reading the docs and code, it looks like jasmine only uses the `tests/` directory and not the `test/` dir.

 let me know if i can help testing or with writing a test for this component.

**Comment by gusbemacbe** [comment]
Then in the version 0.100, unfortunately `navbar-fixed` still suffered a bug.

**Comment by DanielRuf** [comment]
> Then in the version 0.100, unfortunately navbar-fixed still suffered a bug.

Which bug? Please be more precise, create a new issue and provide a new codepen.

**Comment by gusbemacbe** [comment]
Check my issue: https://github.com/Dogfalo/materialize/issues/4986, @DanielRuf.

**Comment by pvanheus** [comment]
@Snewk your description of the problem "the navbar ends up covering the top of the page content" is exactly what I'm seeing (see codepen https://codepen.io/pvanheus/pen/GORrJX adapted from the one you posted). Is 15b5ff4 meant to solve this problem?

**Comment by Dogfalo** [comment]
Move the sidenav ul out of the navbar as described in #3844
