### ISSUE TITLE
Replace the card reveal close icon with SVG or other

### ISSUE THREAD

**Issue by lastnoob** [Dogfalo/materialize#4857]
http://materializecss.com/cards.html#reveal

Once you reveal the content, a close icon (X) will come up on the top right corner.

However, with icon-fonts kinda becoming obsolete, me (and maybe many of us) would like to replace them with SVGs/whatever else. But once I do that, it of course loses functionality and unable to close the revealed content.

Thank you

**Comment by DanielRuf** [comment]
> However, with icon-fonts kinda becoming obsolete

That would be new to me. And you can also directly use the SVG files of the Material icons. Just insert the SVG and remove the pointer events on it (because an i tag also has no pointer events and the clicked icon should not get the event but the surrounding title):

https://codepen.io/anon/pen/QggjJz

This is not a bug in Materialize.

**Comment by tomscholz** [comment]
I don't know how mdl does it, but there they use icons without the cdn or icon font.

**Comment by DanielRuf** [comment]
@tomscholz they use it, see https://getmdl.io/started/index.html.

**Comment by tomscholz** [comment]
Yes, but it does work, even if you are not including the cdn

**Comment by DanielRuf** [comment]
@tomscholz as far as I can see this is only for combining classnames. I did not see any otger references which really include the font ;-)

**Comment by tomscholz** [comment]
![bildschirmfoto 2017-06-21 um 22 11 02](https://user-images.githubusercontent.com/20381749/27404497-92c76686-56ce-11e7-9e9b-326426088634.png)

**Comment by DanielRuf** [comment]
@tomscholz I can not reproduce this ;-)

![image](https://user-images.githubusercontent.com/827205/27405963-cd1f814c-56d3-11e7-971a-4afa45865de9.png)

![image](https://user-images.githubusercontent.com/827205/27406066-134d7f0c-56d4-11e7-886d-3ee99a2fa63a.png)

Anyway, the mentioned `pointer-events` fix should be sufficient.

**Comment by DanielRuf** [comment]
@tomscholz maybe you've installed the iconfont on your system?

https://github.com/google/material-design-icons/tree/master/iconfont

**Comment by tomscholz** [comment]
@DanielRuf ... 
![bildschirmfoto 2017-06-21 um 23 09 38](https://user-images.githubusercontent.com/20381749/27406891-baa4d384-56d6-11e7-84d4-d4863981fe60.png)

**Comment by DanielRuf** [comment]
\o/ Rick and Morty font =)

**Comment by tomscholz** [comment]
@lastnoob I guess you are refering to [this](https://github.com/Dogfalo/materialize/blob/master/js/cards.js#L13) line
