### ISSUE TITLE
Public methods to toggle or interact with javascript-enable components

### ISSUE THREAD

**Issue by beeb** [Dogfalo/materialize#486]
Hey everyone. 

Just thought it would be nice to have, as an improvement, the ability to open/close sidenav, collapsible, dropdown, tabs (and others that i forget) with public methods just like you have for Modals now (for tabs it would be to switch to one specific tab, by index or id I imagine).

Thanks

Extended issue compared to #411

**Comment by acburst** [comment]
These have been added

**Comment by smeijer** [comment]
@acburst, I'm not exactly sure how to use this. You say it is possible, but I can't find any way to do it.

Let's assume I have initialized a `collapsible` somewhere, and that specific collapsible has an `id` named `myCollapsible`. Now I wish to expand it using an event, somewhere else on the page, let's assume a button:

```html
<ul id="myCollapsible" class="collapsible collapsible-accordion">
  <li>
    <a class="title collapsible-header">header 1</a>
    <div class="content collapsible-body">
      <ul>
        <li>item 1</li>
      </ul>
    </div>
  </li>
</ul>

<hr />

<button id="toggle">toggle</button>
```

```js
$('#toggle').on('click', function(event) {
   // this line doesn't work, is there any way to do this?
   $('#myCollapsible').collapsible('toggle'); // or 'open', or 'close'
});
```

So, is there any way to do this with the current version?

**Comment by smeijer** [comment]
I've written a small helper for myself, that does exactly what I need. I thought sharing it here would make my point more clear, and perhaps it comes to use for someone else running against the same problem:

```js
jQuery.fn.extend({
  collapsible: (function() {
    _collapsible = jQuery.fn.collapsible;

    return function(action) {
      if (typeof action !== 'string') {
        return _collapsible.apply(this, arguments);
      }

      var $collapsible = $(this);
      var $header = $collapsible.find('.collapsible-header');
      var $body = $collapsible.find('.collapsible-body');

      action = action || 'toggle';
      if (action === 'toggle') {
        action = $collapsible.hasClass('active') ? 'close' : 'open';
      }

      var classHandler = (action === 'open') ? 'addClass' : 'removeClass';
      var animationHandler = (action === 'open') ? 'slideDown' : 'slideUp';

      $([$header[0], $collapsible[0]])[classHandler]('active');

      $body.stop(true, false)[animationHandler]({
        duration: 350,
        easing: "easeOutQuart",
        queue: false,
        complete: function() {
          $body.css('height', '');
        }
      });
    };
  }())
});
```

```js
// example usage, see post above for more details
$('#myCollapsible').collapsible('toggle');
```

**Comment by keyscores** [comment]
+1 would be very helpful to be able to trigger by header-id 

        $('#myCollapsible').collapsible('toggle', [header-id] );
