### ISSUE TITLE
Mobile Tabs

### ISSUE THREAD

**Issue by acburst** [Dogfalo/materialize#487]

**Comment by CoDEmanX** [comment]
Mobile tabs as in tabs for lateral navigation, so that you are able to switch tabs by swiping right / left?

**Comment by coldKingdom** [comment]
Any news on this? Would be nice to have some sort of responsive tabs.
http://codyhouse.co/gem/responsive-tabbed-navigation/ has a real nice way of doing it, at least for my taste. But it may not be the correct way to use with Material-design, I don't know.

**Comment by ecuanaso** [comment]
Has this issue been resolved? Not sure if it has or not. Thanks

**Comment by lepatlamass** [comment]
Hi guys got this problem with materialized css when I want to start using
it off line it doesn't work especially the js behind it e.g the modals and
the forms do not respond as it it's on the officials webpage thanks for the
help.

**Comment by truenorth** [comment]
this is not that hard to add to materialize. See the navbar at the top of [ember-cli-materialize](http://sgasser.github.io/ember-cli-materialize/)

**Comment by Dogfalo** [comment]
just letting you know it looks a bit weird on windows
http://puu.sh/i824z/e629535b79.png

On Sun, May 31, 2015 at 9:46 PM, Mike North <notifications@github.com>
wrote:

> this is not that hard to add to materialize. See the navbar at the top of
> ember-cli-materialize <http://sgasser.github.io/ember-cli-materialize/>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Dogfalo/materialize/issues/487#issuecomment-107303598>
> .
>



-- 
Doggy sends his greetings from Mars.

**Comment by navee7** [comment]
Have anyone  found a solution?

would be nice to implement below link type of scrolling tabs in materialize

http://www.jqueryscript.net/layout/Awesome-Scrolling-For-Wide-Tab-Interface-Applications-ScrollTabs.html

**Comment by CoDEmanX** [comment]
Works better than scrolling tabs in another material design framework I stumbled upon last week, but overall usability is still bad. It's not that bad for touch devices, but for mouse interaction it is (too much clicking/dragging).

**Comment by navee7** [comment]
Any other suggestions on how to make it work?

**Comment by ecuanaso** [comment]
Looks like this feature is a work in progress unless somebody has found a solution.

**Comment by CoDEmanX** [comment]
Well, not have that many tabs to avoid scrolling need.
Or go vertical, like in Google photos web.

**Comment by raitucarp** [comment]
I know this issue is still open. Any other suggestion guys?

**Comment by generalleger** [comment]
@raitucarp what do you think of Google's implementation at [getmdl.io](http://www.getmdl.io)?

**Comment by raitucarp** [comment]
@generalleger:

the specification support tabs more than 3, you can read here:
http://www.google.com/design/spec/components/tabs.html#tabs-usage

But I don't know mdl kit by google, implement it. I have not used it. What do you think?

**Comment by generalleger** [comment]
@raitucarp I think they did a great job of implementing it.  If you load up getmdl.io on a mobile device, you can see the tabs implementation right on their own page without navigating through the docs.

**Comment by ahlechandre** [comment]
I have more than 5 items and I was forced to truncate them
```css
.tabs .tab a 
{
   text-overflow: ellipsis;
}
```

**Comment by lwa** [comment]
Hey there!

Any news if this feature is going to be implemented in the next Versions?

Thanks,

Michael

**Comment by niels515** [comment]
Does somebody know how i can swipe between tabs? Is there any jquery I can use in combination or is there anything to swipe to next tab?

**Comment by isaachinman** [comment]
Was this ever resolved? Looks like in the documentation there is now a [scrolling tabs example](http://materializecss.com/tabs.html), but there are still horizontal scrollbars in FF.

**Comment by isaachinman** [comment]
@burnaDLX Uh... No. `-moz-scrollbars-none` is [deprecated](https://developer.mozilla.org/en-US/docs/Web/CSS/overflow).

**Comment by burnaDLX** [comment]
@isaachinman You're right! Nevermind
```
.tabs {
    overflow: hidden;
}
::-webkit-scrollbar {
    display: none;
}
```
does the same

**Comment by Grendizr** [comment]
@isaachinman : Agreed tabs are much better without scrollbar but would be nice to be able to scroll to the hidden elements .... like pagination

**Comment by jpt007** [comment]
Agree with @Grendizr . +1 vote.

**Comment by ugoindivirtual** [comment]
+1 vote

**Comment by ebecrm17** [comment]
Grendizr, nice idea, I tried to mix both of them but it didn't work

**Comment by pvaladez** [comment]
+1 vote - I would love to see this as well.  Mobile swipe functionality needed for tabs!
