### ISSUE TITLE
[0.99.0] NPM module missing some JS files

### ISSUE THREAD

**Issue by sabinrimni** [Dogfalo/materialize#4871]
### Description
npm module missing some files from the js folder.

### Repro Steps
- run `npm install materialize-css --save` (this was tested on version 0.99.0)
- with file explorer go to `node_modules` > `materialize-css` > `js` in yout project folder
- there are 3 js files missing compared to the zip downloaded from the git release page of the same version. Specifically the files are: `init.js`, `jquery.timeago.min.js` and `prism.js`

I've noticed this when building for AMD using require.js since it cannot find and map those files.

### Screenshots
GitHub zip:
![capture](https://user-images.githubusercontent.com/6349949/27445807-76f54e5c-577b-11e7-9a4c-e13d11dd252a.PNG)

NPM module:
![npm](https://user-images.githubusercontent.com/6349949/27445751-4694dcfa-577b-11e7-913d-bc0306e6e077.PNG)

**Comment by tomscholz** [comment]
These files are only necessary for our documentation. Thats why they aren't published anymore. What is requiring these files?

**Comment by sabinrimni** [comment]
well in setting up [materialize-css with aurelia](https://aurelia-ui-toolkits.gitbooks.io/materialize-bridge-docs/content/installation/aurelia-cli.html) it uses this [file](https://raw.githubusercontent.com/aurelia-ui-toolkits/aurelia-materialize-bridge/master/build/tools/rbuild.js) to create an AMD file with require.js.
In it, it maps the js files from the module, including `jquery.timeago.min.js` and `prism.js`.

Is it ok if I don't map those? The build got fixed once I copied those over...

**Comment by tomscholz** [comment]
I would recommend to open an issue over at the [aurelia-ui-toolkits/aurelia-materialize-bridge repo ](https://github.com/aurelia-ui-toolkits/aurelia-materialize-bridge/issues/new). These files aren't needed for production.

**Comment by tomscholz** [comment]
I guess we can close this now. If not do not hesitate to reopen it.

**Comment by Thanood** [comment]
@sabinrimni The files to create an AMD version are originally from another repo: https://github.com/noodny/materializecss-amd/

Since these files are only used in documentation it should be safe to remove them from the map.
Did you do that already? If so, would you mind sharing the files so I can update the materialize bridge docs? 😃

**Comment by sabinrimni** [comment]
@Thanood I opened an issue over there and pasted the working `rbuild.js` file.
