### ISSUE TITLE
0.99.0 breaks nav search bar

### ISSUE THREAD

**Issue by pingshunhuangalex** [Dogfalo/materialize#4873]
### Description
Nav search bar breaks after updating to 0.99.0

### Repro Steps
Layout the steps to reproduce your issue.

Just check the example on official website: http://materializecss.com/navbar.html

### Screenshots / Codepen
Add supplemental screenshots or code examples. Look for a codepen template in our Contributing Guidelines.

![image](https://user-images.githubusercontent.com/17170199/27467903-9d7d189e-5829-11e7-8d9a-028822c9ed0d.png)

**Comment by Almaju** [comment]
Solution is to remove every `:not(.browser-default)` from /components/forms/_input-fields.scss

**Comment by DanielRuf** [comment]
> Solution is to remove every :not(.browser-default) from /components/forms/_input-fields.scss

Or add it to the other rules
`:not(.browser-default)`
https://github.com/Dogfalo/materialize/blob/master/sass/components/_navbar.scss#L162
https://github.com/Dogfalo/materialize/blob/master/sass/components/forms/_input-fields.scss#L210

![image](https://user-images.githubusercontent.com/827205/27503914-ea626ada-5881-11e7-819c-fee2a303c189.png)

Some sort of regression. We just have to add the `not` pseudo class more rules as they take precedence over the rules without it.

**Comment by acburst** [comment]
Fixed in 3b1a69d9

**Comment by alexisdiel** [comment]
this commit brokes the input search
https://codepen.io/alexisdiel/pen/RgLqWX

**Comment by DanielRuf** [comment]
https://github.com/Dogfalo/materialize/commit/3b1a69d9296330f9c981c0a5a023ebb225b93594

Should be fixed in the current master branch.

**Comment by alexisdiel** [comment]
This brokes the input search when not on navbar

**Comment by alexisdiel** [comment]
Please review this commit.
This one broke the search input on other places on page
I created an codepen to show the problem
https://codepen.io/alexisdiel/pen/RgLqWX

And my PR: https://github.com/Dogfalo/materialize/pull/4893

**Comment by pingshunhuangalex** [comment]
Just to add to the pool, the search shouldn't have any lines in this nav bar when it's focussed. Sure, I can overwrite it with my own CSS, but a proper fix would be great. For now, I'm not leaving ver.0.98

**Comment by alexisdiel** [comment]
Take a look on the Codepen, if it's ok, i'll update the PR
https://codepen.io/alexisdiel/pen/RgLqWX

**Comment by tomscholz** [comment]
Should be fixed in https://github.com/Dogfalo/materialize/commit/9d78d7ba8f1470a2187e3d6938e3ae34ee6b132b

**Comment by pingshunhuangalex** [comment]
100.1 nav search bar still has a border at the bottom when focussed. This is just frustrating...

**Comment by fega** [comment]
@pingshunhuangalex  maybe I'm a fool, but I cannot see any problem, only the icon is misaligned.

**Comment by alexisdiel** [comment]
@fega , it goes against the material guideline

**Comment by pingshunhuangalex** [comment]
@fega Putting the icon issue aside, The teal bottom border there is what I'm talking about, not to mention @alexisdiel has already fixed it above and show in codepen. I don't understand how this end up going sideways in the actual update...
![image](https://user-images.githubusercontent.com/17170199/28718698-5a72cb8e-73ea-11e7-8b09-02a0b1cb67d6.png)

**Comment by alexisdiel** [comment]
@pingshunhuangalex, i had found the problem, and i'll fix again on the next days, cuz i see that search icon has misaligned on this version.

**Comment by alexisdiel** [comment]
I created a PR fixing this https://github.com/Dogfalo/materialize/pull/5049

updated my Codepen to show the fixes 
https://codepen.io/alexisdiel/pen/RgLqWX

**Comment by DanielRuf** [comment]
Awesome, thanks.

**Comment by einarenrique** [comment]
@alexisdiel Thank you, the fix works perfect in v0.100.2

**Comment by Dogfalo** [comment]
This has been fixed in v1-dev
