### ISSUE TITLE
Responsive-Table problem when td contains multiple lines

### ISSUE THREAD

**Issue by Vortilion** [Dogfalo/materialize#4875]
### Description
When I create a responsive-table and one or more of the tds contains line-breaks (br), the table-header doesn't fit the table-body anymore in mobile view.

### Screenshot
![unbenannt](https://user-images.githubusercontent.com/400503/27477303-fd6eb082-580b-11e7-8d13-f5983bac0a05.png)

**Comment by DanielRuf** [comment]
A codepen would be great.

**Comment by Vortilion** [comment]
Unfortunately thats not possible :-( But you can reproduce it on materializecss.com when you edit the table-content of one td and ad a "<br>". I created a screenshot for you:
![table](https://user-images.githubusercontent.com/400503/27539627-84ae016a-5a7d-11e7-9cf2-de681630ccd4.jpg)

**Comment by acburst** [comment]
Unfortunately this is a limitation of the responsive table. If you know for sure each column will have two lines you can get around this by adding `<br>&nbsp;` in the table header element (`<th>`)
