### ISSUE TITLE
modal function's name too generic. Why don't prefix function names?

### ISSUE THREAD

**Issue by jul6art** [Dogfalo/materialize#4885]
### Description
Hi, issue using the modal function in a system like wordpress or other cause a plugin can inject in front bootstrap.js, cause the modal function exists in the two js files... That's not a bug but if it could help someone solving an issue.

Great job for materialize that's the best css framework ever, awesome result!

**Comment by DanielRuf** [comment]
Right. Bootstrap and other frameworks conflict with Materialize. We'll try to prefix more components (if the function names are already defined).

**Comment by Dogfalo** [comment]
We're working on it. When we rename, it'll probably be across all our plugins.
