### ISSUE TITLE
btn class not responsive on long texts

### ISSUE THREAD

**Issue by Grezvany13** [Dogfalo/materialize#4886]
### Description
When adding longer texts in an element with the ```.btn``` class and watch the content in a smaller view (eg. within grid column or small screen) where the text is longer then the width of the button, the text will simply be cut off.

### Repro Steps
1. Create a button (```a.btn```, ```button.btn``` or ```input[type="submit"].btn```)
2. Add a long text/value to it
3. Watch behaviour in small parent element, or small screen

### Screenshots / Codepen
I created a Codepen which demonstrates the issue, and a potential fix:
https://codepen.io/anon/pen/KqXYRJ

### "Fix"
The issue is created due 2 problems:
1. The ```.btn``` class has a fixed height, so all content which flows to the next line will disapear.
2. The ```input``` element gets by default ```white-space: pre``` (by browser).

Removing the fixed height and adding a min-height will solve the first problem, and should work for both ```.btn``` and ```.btn-large```.

Adding ```white-space: pre-wrap```will make sure that the content will correctly wrap when necessary.
And adding ```word-wrap: break-word``` is optional for extreme long words, to ensure design won't break.

**Comment by DanielRuf** [comment]
Buttons should not have a flexible height. Either put less content inside of them or use `text-overflow:ellipsis` in some way.

**Comment by Dogfalo** [comment]
Buttons should only be one line
