### ISSUE TITLE
Side-nav onClose() is not called when swipe gesture occurs

### ISSUE THREAD

**Issue by nfgallimore** [Dogfalo/materialize#4887]
The newly added onClose() function that is set to be called whenever the side-nav closes and the onOpen() function respectively do not call the appropriate functions when a swipe gesture occurs.

**Comment by DanielRuf** [comment]
Hm... https://github.com/Dogfalo/materialize/blob/master/js/sideNav.js#L190-L193

Can you provide a codepen for testing?

**Comment by nfgallimore** [comment]
No need. See it is missing the call when the side-nav is fixed right in the complete statement. It would work if left fixed but the else statement is missing the call https://github.com/Dogfalo/materialize/blob/master/js/sideNav.js#L281-L311

**Comment by DanielRuf** [comment]
Ah right, we need another

```
// Run 'onClose' when sidenav is closed via touch/swipe if applicable
if (typeof(options.onClose) === 'function') {
    options.onClose.call(this, menu);
}
```

**Comment by acburst** [comment]
Merged
