### ISSUE TITLE
Use class for responsive tables

### ISSUE THREAD

**Issue by philipraets** [Dogfalo/materialize#489]
Now the tables are default responsive, but this gives problems with tables who shouldn't be responsive. I think it's better if you use a class for responsive tables. You can see it on the datepicker:
normal: 
![normal-datepicker](https://cloud.githubusercontent.com/assets/708011/5813996/474da77a-a086-11e4-9390-5c4c65855a60.png)
responsive:
![responsive-datepicker](https://cloud.githubusercontent.com/assets/708011/5813999/4ecc6428-a086-11e4-9faa-add8058bb71b.png)

I've also encounter this when using FullCalender (http://fullcalendar.io/) in my app:
normal:
![normal-fullcalendar](https://cloud.githubusercontent.com/assets/708011/5814014/a67cac1e-a086-11e4-851e-6e2058e2cdf9.png)
responsive:
![responsive-fullcalendar](https://cloud.githubusercontent.com/assets/708011/5814016/abe18ad0-a086-11e4-83dd-d531d5db2f77.png)

**Comment by acburst** [comment]
Fixed in 792e079eb2393e7ad00cf0d22520790dfc6a4d67

Now it is tied to the class .responsive-table
