### ISSUE TITLE
Autocomplete Field options can't be cleared

### ISSUE THREAD

**Issue by Jujunol** [Dogfalo/materialize#4892]
### Description
If you generate an autocomplete field's values, you're not able to deplete the values (using null or blank object). 

###  Codepen
https://codepen.io/anon/pen/dRJmqa?editors=1010

**Comment by DanielRuf** [comment]
Please fill out the codepen and save it (as anonymous).

**Comment by Jujunol** [comment]
Thanks for letting me know,
I thought I had but I guess I forgot to clear my clipboard.
I've updated the link to the saved pen

**Comment by acburst** [comment]
Fixed in 511639b8
