### ISSUE TITLE
Timepicker container option

### ISSUE THREAD

**Issue by rharasim** [Dogfalo/materialize#4900]
### Description
Materialize timepicker option container now working.

### Example
```
$('.timepicker').pickatime({
 container: '#div'
  });
```
### Solution
Is there any solution e.g. .appedTo('body') ?

**Comment by DanielRuf** [comment]
The container option is not supported in Materialize. https://github.com/Dogfalo/materialize/blob/master/js/date_picker/picker.time.js

**Comment by rharasim** [comment]
Oh sorry, thanks Daniel

### This work
```
$(document).on('click', '.timepicker', function () {
$(".clockpicker").detach().appendTo('body');
 });
```

**Comment by tomscholz** [comment]
Seems solved then

**Comment by brunoneumann** [comment]
Hi guys! The solution of @rharasim  works well.. but I'm using Meteor and there's no way to change compiled packages. There's a possibility in the future to add the container feature in timepicker? I need timepicker inside modals with appendTo('body').

Thanks in advance and congratulations for this package!

**Comment by safik222** [comment]
Thank you so much rharassment, it was exactly what i needed

**Comment by kezfran** [comment]
Hi guys! I tried the solution of @rharasim but it doesn't fix my problem!
Can you please add the "container:'body'" feature to timepicker?
Thanks

**Comment by Y0lk** [comment]
Just made a pull request with the fix from @rharasim, it works just fine.
