### ISSUE TITLE
0.99.0 - error on SVG path click

### ISSUE THREAD

**Issue by gh0c** [Dogfalo/materialize#4901]
Hi,

Since v0.99.0
`TypeError: c.className.indexOf is not a function`
JS error is thrown after SVG \<path\> element is clicked.

[https://codepen.io/anon/pen/EXoyWQ](https://codepen.io/anon/pen/EXoyWQ)

![image](https://user-images.githubusercontent.com/1114932/27635375-009b2b4c-5c07-11e7-8324-fe44712ae854.png)

This piece of code is inside `getWavesEffectElement()` method and `target.classList.contains('waves-effect')` was changed to `target.className.indexOf('waves-effect') !== -1`

**Comment by DanielRuf** [comment]
See https://github.com/Dogfalo/materialize/issues/2005
