### ISSUE TITLE
Having weird inline behavior when adding two **different** icons

### ISSUE THREAD

**Issue by Ernesto-Valdes** [Dogfalo/materialize#4903]
Description: 
Having weird inline behavior when adding two **different** icons. Expected one icon after the other. Using the same type of icon (example: both `mode_edit`) the icons display ok. This is not the case for different icon types. 

Repro Steps:
```html
<td>
  <a href="#">
    <i class="material-icons small ng-scope">mode_edit</i>
  </a>
  <a href="#">
    <i class="material-icons small ng-scope">mode_delete</i>
  </a>
</td>
```

Screenshots: 
These screenshots are from the table component at materializecss website. Using the above template added to the table cell. Once with similar icons and other with different icons. 

<img width="553" alt="screen shot 2017-06-28 at 12 21 29 pm" src="https://user-images.githubusercontent.com/4762763/27648377-5934a072-5bfc-11e7-9425-23f459329c3c.png">
<img width="565" alt="screen shot 2017-06-28 at 12 21 11 pm" src="https://user-images.githubusercontent.com/4762763/27648376-59348006-5bfc-11e7-94ef-ffbbb0448af2.png">

**Comment by DanielRuf** [comment]
Can you provide a codepen for us?

**Comment by Ernesto-Valdes** [comment]
Codepen example: https://codepen.io/anon/pen/gRoXpE

**Comment by Dogfalo** [comment]
I'm not sure where you saw `mode_delete` but it should just be `delete`

**Comment by DanielRuf** [comment]
> I'm not sure where you saw mode_delete but it should just be delete

Right. The `mode_` added invisible characters as this is not part of the Material Icons font
https://codepen.io/anon/pen/EXobEE

Confirmed, not a bug.
