### ISSUE TITLE
Carousel inside a form - Input and TextArea elements are not working

### ISSUE THREAD

**Issue by JessieSie** [Dogfalo/materialize#4905]
# Description
I am trying to use a `.carousel` inside a `<form>` element. The effect I need is a slider containing different input fields of the form.
The problem is that the text fields and text area elements somehow don't get activated when the user clicks on them. By that I mean: 

1. The transition/animation which causes the adjacent `label` to change color and the underline of `input[type=text]` and `textarea` to increase in thickness and change color, does not occur.
2. When I type using the keyboard, the text does not get written on the screen.

I [posted a question on SO](https://stackoverflow.com/questions/44777368/slider-inside-a-form-input-and-textarea-elements-are-not-working?noredirect=1#comment76580729_44777368), and someone solved (1) by adding the class `active` to sibling `label` elements when a `input[type=text]` or `textarea` is clicked. This solves problem 1 stated above.

But problem 2 described above remains unsolved.

# Repro Steps: 
Here is a code sample on codepen:  https://codepen.io/JessieSie/pen/vZppdK

Try clicking on the text fields and then typing using the keyboard. **The text you type will not be written on the screen.** That is the issue.

**Comment by tomscholz** [comment]
https://github.com/Dogfalo/materialize/issues/4380 Duplicate issue?

**Comment by JessieSie** [comment]
@tomscholz Nope. As you can see in the comments in my SO question, when I dynamically add the class `active` to the `<label>`  adjacent to the `<input>` element, the animations which are expected to happen when `<input>` is clicked do happen; but the problem is that the `<input>` does not receive user input, i.e. when I type on the keyboard the text I type is not written on the screen in the `<input>` element. 

You can see the PROBLEM REPRODUCED here: https://jsfiddle.net/Jesss/akn9baz3/3/

**Comment by acburst** [comment]
Fixed in 58224d7239399f05721cdbc2af90f2d73f6f6a78
