### ISSUE TITLE
Uncaught TypeError: target.className.indexOf is not a function

### ISSUE THREAD

**Issue by yangpu** [Dogfalo/materialize#4907]
Materialize 0.99 raise an exception:

`
Uncaught TypeError: target.className.indexOf is not a function  

materialize.js:2124 function getWavesEffectElement(e)
`

The issue is caused by cliking on SnapSvg node, and target.className is an instance of SVGAnimatedString which has no indexOf method.

To check the type of target.className before calling indexOf please.

**Comment by tomscholz** [comment]
Duplicate https://github.com/Dogfalo/materialize/issues/2005
