### ISSUE TITLE
Side Nav dropdown stays open when other dropdowns are clicked

### ISSUE THREAD

**Issue by VeeK727** [Dogfalo/materialize#4908]
I've noticed this since 0.98. In the sidenav, if you have multiple dropdowns in the sidenav and you click to expand, that's fine. But if you expand another one, the first stays open. On the materialize website, the other dropdowns collapse automatically but that's not what happens when I use it.

I have all the demo code from the website, currently using 0.99 and jquery 3.1.1

**Comment by tomscholz** [comment]
Please provide a codepen

**Comment by VeeK727** [comment]
For some reason I keep getting $ not defined error from materialize. See if you can make something of it please.

https://jsfiddle.net/VeeK727/8ocvhnbh/1/

**Comment by tomscholz** [comment]
You have to include jQuery **before** materialize.js
https://jsfiddle.net/zmgxz3o1/

**Comment by tomscholz** [comment]
We use the collapsible component on the materialize website

**Comment by VeeK727** [comment]
Tom, I have the exact same html as you are linking to and if you look at yours or my jsfiddle you can see if you open one dropdown then open another, the first one will not collapse

**Comment by Dogfalo** [comment]
This happens because you have 3 separate collapsibles

**Comment by VeeK727** [comment]
HI Dogfalo, I'm sorry but I didn't get your point.

**Comment by Dogfalo** [comment]
separate collapsibles don't close each other, they open/close `<li>` within themselves

**Comment by VeeK727** [comment]
Oh I see there is a difference in HTML I didn't know. This is not apparent by the example posted at your website http://materializecss.com/side-nav.html#variations.

I suggest you add one more dropdown so people like me can get an idea of the total structure.

Thanks for your help
