### ISSUE TITLE
Sidenav is hidden on orientation change to landscape on iPad

### ISSUE THREAD

**Issue by Cephalom** [Dogfalo/materialize#4914]
Sidenav is hidden on orientation change from portrait to landscape on iPad.

![img_1435 4563](https://user-images.githubusercontent.com/20730450/27702806-8e4f84ca-5d05-11e7-8003-57f98af04513.PNG)

**Comment by nfgallimore** [comment]
No iPad to test here. But looks okay in Chrome Dev tools at least.
![navbar](https://user-images.githubusercontent.com/4875906/27703017-14e05d02-5cd4-11e7-883a-9c2d2be5098d.PNG)

**Comment by DanielRuf** [comment]
> hidden on orientation change
Will take a look. Could be a resize event listener.

**Comment by mattgaspar** [comment]
This appears to be a long standing iOS Safari bug.
I was experiencing a related issue were the sidenav would be shown on page load when it should have been hidden (iPad/portrait) and the page was NOT offset with padding, so the left side was under the menu (as would be correct if the menu was hidden!) 
It appears that Google has even implemented the bug in Chrome dev tools when you set device emulation to iPad!
Basically window.innerWidth and window.innerHeight do not return the correct value when page elements are hidden out of the viewport. (but some time after initial page load they seem like they might be correct)
Setting additional values in the meta viewport tag seems to fix the issue, here's a combination of multiple fixes.
<meta name="viewport" content="width=device-width, initial-scale=1.0001, minimum-scale=1.0001, maximum-scale=1.0001, shrink-to-fit=no, user-scalable=no">

I haven't had any luck reproducing this in a simpler form (I'm using Aurelia and webpack)

Sources:
https://stackoverflow.com/questions/32840602/does-safari-ios9-returns-a-wrong-value-for-window-innerheight
https://www.reddit.com/r/web_design/comments/3la04p/psa_safari_on_ios9_has_a_media_query_bug/

**Comment by acburst** [comment]
This should be fixed on the latest alpha release.
