### ISSUE TITLE
Custom Error Message displayed within textarea field, not below the bottom border

### ISSUE THREAD

**Issue by kimfucious** [Dogfalo/materialize#4916]
### Description
When you combine a textarea with the .data-length (Character Counter) and .data-error (Custom Error Messages) and the textarea input exceeds the data-length threshold, the error message is displayed within the field and not below the bottom border.

### Repro Steps
Combine aforementioned elements in an input filed like this:

`<div class="row">
          <div class="input-field col s12 m6 offset-m3">
            <i class="material-icons prefix">mode_edit</i>
            <textarea id="form_message" class="materialize-textarea" data-length="140"></textarea>
            <label for="form_message" data-error="Please keep your message below 140 characters.">Message</label>
          </div>
        </div>`

### Screenshots / Codepen
[CodePen example is here](https://codepen.io/kimfucious/pen/gRvobb)

![materialize](https://user-images.githubusercontent.com/26792769/27720109-bc98afce-5d81-11e7-9ad4-5860e5afa40d.png)

**Comment by acburst** [comment]
Fixed in a2e10d96.

Also, make sure you add the class "validate" to your input element to ensure this works. This class is needed whenever you are using the error or success messages.
