### ISSUE TITLE
Custom Error Message not working with Date and Timepicker

### ISSUE THREAD

**Issue by Verbat** [Dogfalo/materialize#4917]
Custom Error Messages does not working with the Date and Timepicker. I tried to put the label before and after the input element but after initialisation, the label is not a direct child of the input anymore so the CSS rules won't apply. 

You can see it here that it does not work:
https://codepen.io/anon/pen/zzRjVX

**Comment by Dogfalo** [comment]
Time picker is already working, you just need to place label after the input.

For datepicker, I fixed the bug here: 016e251f
