### ISSUE TITLE
Materialize with Vue js

### ISSUE THREAD

**Issue by davodavodavo3** [Dogfalo/materialize#4920]
Modal doesn't open if create new vue instance.
I don know maybe there is other functionality that doesnt work.
Can anyone tell me why?
## Reproduce
https://jsfiddle.net/k2o7whu9/8/

1.Modal doesnt work.
2.Materialbox doesnt work.
3.Collapsible doesnt work.
4.And maybe all javascript functionality of Materialize  doesnt work(((((

And another question.
When issue with SVG(target.className.indexOf is not a function) icons will be fixed?

**Comment by inventti-leonardo** [comment]
I have been used Vue.js too. In every Vue.js component you need to initialize materialize in mounted function. The `$(document).ready` event occurs before Vue.js rendering.

```
var app = new Vue({
        el: '#app',
        mounted: function() {
        	$('.modal').modal();
        }
    });
```

**Comment by inventti-leonardo** [comment]
Try here https://jsfiddle.net/k2o7whu9/30/

**Comment by davodavodavo3** [comment]
Yes that work i checked in my project.
But why?
Why we need to mount all classes that whe use on page, there is many classes(and many custom classes)
I have pages that I dont include Vue js but i have materialize classes.. 
With Angular all works fine.
Why?))))))))))))

**Comment by davodavodavo3** [comment]
@inventti-leonardo do you think this is best solution?

**Comment by davodavodavo3** [comment]
With your solution on all pages that i use vue component i need to mount all this.
Without any methods , params and other stuff))))))))))))

```
var app = new Vue({
    el: '#app',
    mounted: function() {
        $(".button-collapse").sideNav();
        $(".parallax").parallax();
        $(".modal").modal({
                dismissible: true,
                opacity: .5,
                inDuration: 350,
                outDuration: 250,
                startingTop: '1%',
                endingTop: '15%',
            }
        );
        $("select").material_select();
        $(".dropdown-button").dropdown({closeOnClick: false,stopPropagation: false});
        $("ul.tabs").tabs();
        $(".header-dropdown").dropdown({
            constrainWidth: false,
            hover: true,
            gutter: 6,
            belowOrigin: true,
            alignment: 'right',
            stopPropagation: false,
            closeOnClick: false,
        });

        $('.datepicker').pickadate({
            labelMonthNext: 'След. Месяц',
            labelMonthPrev: 'Пред. Месяц',
            labelMonthSelect: 'Выберите Месяц',
            labelYearSelect: 'Select a year',
            monthsFull: [ 'Январь', 'Февраль', 'Март', 'Апрель', 'Май', 'Июнь', 'Июль', 'Август', 'Сентябрь', 'Октябрь', 'Ноябрь', 'Декабрь' ],
            monthsShort: [ 'Янв.', 'Фев.', 'Мар.', 'Апр.', 'Май', 'Июн.', 'Июл.', 'Авг.', 'Сен.', 'Окт.', 'Ноя.', 'Дек.' ],
            weekdaysFull: [ 'Воскресенье', 'Понедельник', 'Вторник', 'Среда', 'Четверг', 'Пятница', 'Суббота' ],
            weekdaysShort: [ 'Вс', 'Пн', 'Вт', 'Ср', 'Чт', 'Пт', 'Сб' ],
            weekdaysLetter: [ 'Вс', 'Пн', 'Вт', 'Ср', 'Чт', 'Пт', 'Сб' ],
            today: 'Сегодня',
            clear: 'Сброс',
            close: '<i class="material-icons">done</i>',
            selectMonths: true,
            format: 'd mmmm, yyyy',
            formatSubmit: 'yyyy-mm-d',
            min: new Date(),
        });

        $('#delivery_time').pickatime({
            default: 'now',
            autoclose: true,
            donetext: '<i class="material-icons">done</i>',
            cleartext: 'Сброс', // text for clear-button
            canceltext: 'Отмена', // Text for cancel-button
            twelvehour: false,
            vibrate: true,
        });
    }
});
```

**Comment by inventti-leonardo** [comment]
I don't known. Maybe it's because virtual dom of Vue.js, React and others. You can not use platform init events :(

They recomend you to create components instead, and init on "mounted" of each component.

**Comment by davodavodavo3** [comment]
Thanks @inventti-leonardo.
Maybe we will wait for the developers to see what they write.

**Comment by davodavodavo3** [comment]
Or maybe open issue in vue js page))))))))))

**Comment by Dogfalo** [comment]
Yes you need to initialize using mounted because the Vue adds to the Dom dynamically

**Comment by thiagodias63** [comment]
Thanks a lots
I was a month in this problem
Thanks <3
