### ISSUE TITLE
chip.select chip.deselect

### ISSUE THREAD

**Issue by afabros** [Dogfalo/materialize#4923]
Is there a way to trigger an event when a chip selected class is removed?

The function below is a not so good alternative :
```javascript
$( 'div.chip' ).click(function () {
  if ( $( this ).hasClass( "selected" ) ) {
```

**Comment by DanielRuf** [comment]
Currently there is no other way, your code is a possible way to get this implemented.

**Comment by afabros** [comment]
Kindly also include the 'id' in the div generated. Even if id is allowed in the data object, there's no way to choose the chip that has the selected attribute but to find the div that contains that value. ex. $( "div:contains('Sample Tag'). If there's a duplicate value of tag from the user other than the chips-initial, then it will be problematic. A unique id is better.
    data: [
            {
        tag: "Sample Tag",
        id: 1,
      },

**Comment by developeranirudhprabhu** [comment]
Well i think the chips API has events:
http://materializecss.com/chips.html#events

Which support events for add, delete and select. @afabros is that what you were asking for?

**Comment by DanielRuf** [comment]
These are internal events. You still have to trigger them programmatically like he planned to do it.

**Comment by afabros** [comment]
I'm not sure if the last request is already implemented in the new version. Haven't tried it yet though .There's still a bug on chips that's already fixed but not yet in the distribution.

Basically, the request needs to have the data in chips-initial same in chip data object. It can allow id.
so that it can be accessed in .selectChip(); Hopefully, chip can act the same as 'select' where we can select, deselect, and have multiple selects programmatically through it's id.

$('.chips-initial').chips({
    data: [{
      tag: 'Apple',
    }, {
      tag: 'Microsoft',
    }, {
      tag: 'Google',
    }],
  });

var chip = {
    tag: 'chip content',
    image: '', //optional
    id: 1, //optional
  };

**Comment by acburst** [comment]
Chips has been rewritten in v1.0.0 alpha. There are now event callbacks you can specify.
