### ISSUE TITLE
Switches CSS coloring does not apply correctly

### ISSUE THREAD

**Issue by terminalsamurai** [Dogfalo/materialize#4928]
### Description
When adding color styling to switches, generic functionality is different than styled; value of false should always result in a greyed out switch. A value of true should result in a colored switch. Also, the lever on the switch should carry over the requested color class (in this example indigo)

### CodePen
Reproduced here: https://codepen.io/terminalsamurai/pen/pwLqER

**Comment by acburst** [comment]
Our color classes aren't meant to work across every single one of our components. Especially with more complex things like our switches that use pseudo elements to help style things, making the color classes work adds a lot of overhead. Instead, its really easy to customize these colors with our Sass variables and should work as you describe.
