### ISSUE TITLE
bower.js references old main files in /bin

### ISSUE THREAD

**Issue by tbd-rsm** [Dogfalo/materialize#4930]
First of all: Nice work & Thanks.

## Expected Behavior
The main section of the bower.json should reference the correct js and css files.

## Current Behaviour
Currently listed are paths to the compiled files in the /bin directory, that do not exist anymore.

## Possible Solution
This should be changed to the files in /dist.

A workaround is to overwrite them in my own bower.json via:

```
{
  "overrides": {
    "materialize": {
      "main": [
          "dist/css/materialize.min.css",
          "dist/js/materialize.min.js",
          "fonts/roboto/Roboto-Bold.woff",
          "fonts/roboto/Roboto-Bold.woff2",
          "fonts/roboto/Roboto-Light.woff",
          "fonts/roboto/Roboto-Light.woff2",
          "fonts/roboto/Roboto-Medium.woff",
          "fonts/roboto/Roboto-Medium.woff2",
          "fonts/roboto/Roboto-Regular.woff",
          "fonts/roboto/Roboto-Regular.woff2",
          "fonts/roboto/Roboto-Thin.woff",
          "fonts/roboto/Roboto-Thin.woff2"
      ]
    }
  }
}
```

The problem with that workaround is that it is not future proof for possible changes on the main section in future releases.

I use this for asset-building via gulp and npm asset-builder that supports bower dependencies and seems to read the files to be included from bowser.json. (https://github.com/austinpray/asset-builder)

**Comment by tomscholz** [comment]
This makes sense. Fixed in https://github.com/Dogfalo/materialize/commit/78f64f5209f8befdb2587397b951c6a8015b8f02
