### ISSUE TITLE
Feature request - Option to make Fixed Action Button should disappear when scrolling down and reappear 

### ISSUE THREAD

**Issue by doubleOrt** [Dogfalo/materialize#4933]
This issue is particularly useful when you have a lot of data being presented on the screen, basically after you scroll down for a specific amount (of pixels?), your FAB disappears, and it will re-appear when you start scrolling up. Many materialize-design apps such as Viber and the Reddit app implement it (i believe Twitter too), all in all, i don't see why it wouldn't be a nice addition.  

You should be able to add a class to your FABs to control this, or perhaps you could add some data attributes to control the exact positions and offsets that determine the hide/show functionality of the FAB.

**Comment by tomscholz** [comment]
I am not sure if there are other libs that do this, but it seems like it is something that you could implement fairly quickly. Also see https://github.com/Dogfalo/materialize/issues/4470

**Comment by tomscholz** [comment]
https://codepen.io/anon/pen/rwKaMy?editors=0010

**Comment by doubleOrt** [comment]
@tomscholz Great! But it is not only used for back-to-top FABs, it can be used, new-post buttons, new-message buttons, etc... And there can be some extra options that it can take (such as scroll offset to disappear/reappear, a nice animation) that would make it a bit harder to implement. It would be nice if it were a materialize-automated task, since many Material-design apps out there use it, however i haven't seen any of the Google apps use it, so... But yes i do agree that it is a bit out of scope for the library since it is more useful for larger apps and hyper-useful for presenting data on smaller screens, which is only say 50% of how people view websites made with this library.

**Comment by doubleOrt** [comment]
@tomscholz BTW, the functionality i am talking about is different than the one you have implemented in the Pen, yours appears as soon as the user scrolls down 100px, what i am talking about is an FAB that disappears when you scroll down, and re-appears if you do a small scroll up 10px.

**Comment by tomscholz** [comment]
Try https://codepen.io/anon/pen/rwKaMy

**Comment by doubleOrt** [comment]
@tomscholz  The Pen is not working, the page just keeps refreshing forever. Happened to me when i tried to make one without an account.

**Comment by tomscholz** [comment]
That is not the case on my end. Seems more like a problem with codepen.io
