### ISSUE TITLE
Tooltip empty when used on form select element

### ISSUE THREAD

**Issue by sigmatec** [Dogfalo/materialize#4935]
If you add `class="tooltipped"` and `data-tooltip="Whatever"` to a `select` element, the tooltip appears but is empty, or it is potentially only displaying the `:after` element; not sure which, but it's broken.

Example: [JSFiddle](https://jsfiddle.net/wwd96kfa/3/)

**Comment by sigmatec** [comment]
`data-position` is also ignored - defaults to bottom: [JSFiddle](https://jsfiddle.net/wwd96kfa/6/)

**Comment by sigmatec** [comment]
It would also be useful, if `data-position="bottom"`, to make the tooltip hidden when the `select` menu opens.
Sorry for multiple comments.

**Comment by Dogfalo** [comment]
Select element is hidden, so instead I would advise you to put the tooltip on another wrapping element
https://jsfiddle.net/wwd96kfa/8/

**Comment by sigmatec** [comment]
Ok, thank you I thought that might be the case.
