### ISSUE TITLE
New approach for supporting RTL

### ISSUE THREAD

**Issue by JafarAkhondali** [Dogfalo/materialize#4936]
Hi, First of all i wanted to say thanks for this amazing framework :+1: 
As we know, RTL is not supported yet in Materializecss. There were some hacky tricks and repos but contributors stopped maintaining them, So i decided to share my solution with you and if you would agree i'll add RTL support and submit PR.

As far as i know, here are our options to support RTL:
1. Bootstrap didnt support RTL either, So people created unofficial **separate Css file**s which should load again in website and do overwriting.

Disadvantages of adding separate Css file:
----
- Dirty use of `!important`
- Hard to update code in future releases
- Increase load time
- Re-rendering most of DOMs in each request to website

2.Another method is to add extra class for RTL [like this](https://github.com/Dogfalo/materialize/pull/4391)
 Disadvantages of adding extra class:
---
- Hard to localize template, since we need another template for RTL languages
- Ambiguous syntax
- Sometimes dirty use of `!important`

I suggest add two variables in config of sass files which help setting directions, and deploy a file for LTR and one for RTL. I once used to use this method in a personal mini Css framework and it worked great.
Here is how:

config.sass:
```
$rol: left //Right Or left
$dir: ltr //Direction
```

Some exampels of usage:
```
.btn[class*="icon-"]
  color: $txtColor
  @if $rol == "left"
    padding: 25px 60px 25px 120px
  @else
    padding: 25px 75px 25px 25px
```

```
  /* checkbox aspect */
  & label:before, &:not(.filled-in) + label:after
    content: ''
    position: absolute
    top: 0
    #{$rol}: 0 // This will align label to left or right
```

```
/* Text Label Style*/
.input-check
  [type="checkbox"] 
    &+label
      padding-#{$rol}: 35px // Padding from left o right
```

**Comment by amin0256** [comment]
+1

**Comment by Mr0Null** [comment]
also I saw something like [rtlcss](https://github.com/MohammadYounes/rtlcss) package so you can add it to the gruntfile and generate both rtl and ltr files while building :)

**Comment by tomscholz** [comment]
Also have a look at [foundations](https://github.com/zurb/foundation-sites/blob/master/docs/pages/rtl.md) rtl integration.

**Comment by JafarAkhondali** [comment]
@Mr0Null Although it only works on Css not Sass/Scss, I've tested your suggestion on this [link](http://materializecss.com/forms.html), Here is the result:
Before:
![screenshot_20170705_163858](https://user-images.githubusercontent.com/11364402/27863757-defa7c32-61a0-11e7-9957-d61f24d2ea07.png)

After:
![screenshot_20170705_163315](https://user-images.githubusercontent.com/11364402/27863738-cdb1ce30-61a0-11e7-8d0c-b2360b50e21d.png)

**Comment by Mr0Null** [comment]
@JafarAkhondali well it's not like that to just give the css to rtlcss, and getting the output! you must use it's helpers wherever it's not needed to be reversed the direction (eg. the `code` block)

**Comment by JafarAkhondali** [comment]
@tomscholz I looked at their code, It looks like they are exactly using the method I've suggested:
![screenshot_20170705_170622](https://user-images.githubusercontent.com/11364402/27864733-fec9cadc-61a4-11e7-9bc4-d771aa500806.png)
![screenshot_20170705_170525](https://user-images.githubusercontent.com/11364402/27864739-0159a484-61a5-11e7-9585-1329f1dfbc0a.png)

**Comment by JafarAkhondali** [comment]
@Mr0Null Can create a working test? BTW in best case scenario we need [sass-rtl](https://www.sitepoint.com/manage-rtl-css-sass-grunt/).

**Comment by Dogfalo** [comment]
We aren't looking to support RTL in the near future as this is a large undertaking which will require maintenance

**Comment by MohammadYounes** [comment]
@JafarAkhondali Try it again on the same [link](http://materializecss.com/forms.html) and CHANGE the document direction to `rtl` to see the magic 😄.

![capture](https://user-images.githubusercontent.com/4712046/27913594-516c2856-6269-11e7-8848-3fe715c67bc2.PNG)

**Comment by JafarAkhondali** [comment]
@MohammadYounes Oops, my bad :sweat_smile:
