### ISSUE TITLE
documentation glitch: timepicker doesn't work with type="date"

### ISSUE THREAD

**Issue by Thanood** [Dogfalo/materialize#4937]
The example in the docs shows using a timepicker like this:

```html
<input type="date" class="timepicker">
```

```js
    $( document ).ready(function() {
      $('.timepicker').pickatime();
    });
```

## Expected Behavior

I'd expect this usage to work like in the example. 😃 

## Current Behavior

A date input is rendered with a placeholder of `tt.mm.jjjj` (OS language is set to German, it's probably `dd/mm/yyyy` on English systems).

![image](https://user-images.githubusercontent.com/677826/27854620-cf84b10c-6167-11e7-9880-7713fef57e4d.png)

The picker itself works. But if you pick a time, the value is not inserted because the value doesn't match any date format. A warning is raised in the console: `The specified value "12:00PM" does not conform to the required format, "yyyy-MM-dd".`

## Possible Solution

Change the docs to use an input of `type="text"` instead, which is already used in the sample on the page itself. 😃 

## Steps to Reproduce (for bugs)

Codepen: https://codepen.io/anon/pen/mwKXry

## Context

This is just an inconvenience, nothing groundbreaking.

## Your Environment

* Version used: v0.99.0
* Browser Name and version: Chrome 59
* Operating System and version (desktop or mobile): Windows 10 desktop

**Comment by tomscholz** [comment]
https://github.com/Dogfalo/materialize/pull/4868

**Comment by Thanood** [comment]
Oh great, that happens when I search issues but not PRs.. 😂 
Sorry..
