### ISSUE TITLE
Brand logo height surpass nav-wrapper in certain browsers

### ISSUE THREAD

**Issue by Tri125** [Dogfalo/materialize#4940]
I'm using ``v0.99.0``.
In my nav-wrapper I'm using an element with the brand-logo class. I've noticed that with Chrome Desktop it renders [fine](https://i.imgur.com/1MxMl5C.png) but on Firefox, it surpass the nav-wrapper like [so](https://i.imgur.com/LEY6P5S.png).

I don't know if related or not but the badge renders below on Firefox and at least Chrome on mobile, this is why I investigated it in the first place.

You can get a live test [here](https://gwentapi.com/) otherwise you can get the code [here](https://github.com/GwentAPI/GwentAPI.github.io/tree/33fb60102c0f20052f1f59e4e793f4bd4a7d4df7).

**Comment by acburst** [comment]
Hmm, I've removed white-space: nowrap in fc3c586d.

Let me know if that helps

**Comment by Altroo** [comment]
i had the same issue, solved it this morning by adding : `nav .brand-logo {
    white-space: nowrap;
}`

**Comment by Tri125** [comment]
``nav .brand-logo { white-space: nowrap; }`` is a style that is there by default in materialize.min.css (v0.99.0). Toggling the rule on/off in the inspector didn't seems to be changing the size or positioning of the elements.

This is however fixed in in v0.100.0.
