### ISSUE TITLE
Border-bottom style on disabled select and input are not the same

### ISSUE THREAD

**Issue by jfcere** [Dogfalo/materialize#4944]
Has you can see on this image (and on [materializecss.com](http://materializecss.com/forms.html)) the border-bottom style is not the same on the select and the input when disabled.

![image](https://user-images.githubusercontent.com/6987084/27972616-02ce572a-6325-11e7-8f8b-1f70fcb2bc05.png)

## Expected Behavior
Both select and input once disabled should have border-bottom style dotted

## Current Behavior
Disabled select bottom-border style is solid

## Possible Solution
See expected behavior

## Steps to Reproduce (for bugs)
See disabled input vs disabled select on demo page [here](http://materializecss.com/forms.html)

## Context
Having same style would unify the look and be less confusing in a disabled form

## Your Environment

* Version used: 0.98.2
* Browser Name and version: Chrome, FF, IE, Edge .. name it!
* Operating System and version (desktop or mobile): Windows 10
* Link to your project (if appropriate): irrelevant

**Comment by tomscholz** [comment]
Should be fixed with https://github.com/Dogfalo/materialize/pull/2841

**Comment by DanielRuf** [comment]
Looks like duplicate / unneeded style definitions:

https://github.com/Dogfalo/materialize/blob/033f036325c5f9ec8baec2ee9a5ce7b0b538b9f2/sass/components/forms/_select.scss#L78

https://github.com/Dogfalo/materialize/blob/033f036325c5f9ec8baec2ee9a5ce7b0b538b9f2/sass/components/forms/_select.scss#L73

**Comment by acburst** [comment]
Fixed in c678efba
