### ISSUE TITLE
Wave effect on button click doesn't retreat back to original color.

### ISSUE THREAD

**Issue by AnupamKhosla** [Dogfalo/materialize#4945]
I have been reading the [ripple/waves effect in Material Design]( http://materializecss.com/waves.html). What I observed is that if while pressing continually near the right end of the green wave button, if I suddenly start pressing continually near the left end, then the button goes completely white and never retreat to its original green color.

**Comment by tomscholz** [comment]
See https://github.com/Dogfalo/materialize/issues/2667
