### ISSUE TITLE
Materialize Button Going Dark on Hover when using in Angular 2 .

### ISSUE THREAD

**Issue by rahulrsingh09** [Dogfalo/materialize#4948]
![image](https://user-images.githubusercontent.com/17721520/27994493-f3210dc2-64dc-11e7-8674-4761b8b53759.png)

When on hover why does it turn black whereas it should glow right ?

**Comment by tomscholz** [comment]
Please fill out [the issue template ](https://github.com/Dogfalo/materialize/blob/master/.github/ISSUE_TEMPLATE.md) and also make sure to read out [contributing guidelines](https://github.com/Dogfalo/materialize/blob/master/CONTRIBUTING.md).

**Comment by DanielRuf** [comment]
@rahulrsingh09 do you use the `waves-white` class?
