### ISSUE TITLE
Truncate doesn't work when used within waves-effect

### ISSUE THREAD

**Issue by gauravjot** [Dogfalo/materialize#4950]
I want to do waves-effect on a card whose secondary text is truncate but that produce a weird outcome. Check these pens

- [With waves-effect](https://codepen.io/gauravjot/pen/RgeXvx): Truncate doesn't work at all
- [Without waves-effect](https://codepen.io/gauravjot/pen/rwqXRV): Truncate does work

Maybe I am missing something and there is a way around this or this is an actual issue needs to be solved.

Thank you!

**Comment by faruqisan** [comment]
i faced same problem , but mine is inside card content when using card horizontal

**Comment by acburst** [comment]
waves-effect adds inline-block, which is not compatible with truncate. You can override the display: inline-block; to display: block; and your truncate will work.
