### ISSUE TITLE
Box shadow broken on button elements in with Chrome Canary

### ISSUE THREAD

**Issue by dbauszus-glx** [Dogfalo/materialize#4951]
Using Google Chrome Canary for debugging I noticed that the box shadows are broken in the latest updated of Canary.

Version 61.0.3152.0 (Official Build) canary (64-bit)

Please have a look on the website with the build and the issue will become apparent.

![image](https://user-images.githubusercontent.com/22201617/28013642-9ea202c6-6561-11e7-86a6-bf808de97f0a.png)

This is the offending css:

```
.z-depth-1, nav, .card-panel, .card, .toast, .btn, .btn-large, .btn-floating, .dropdown-content, .collapsible, .side-nav {
    box-shadow: 0 2px 2px 0 rgba(0,0,0,0.14), 0 1px 5px 0 rgba(0,0,0,0.12), 0 3px 1px -2px rgba(0,0,0,0.2);
}
```
Perhaps you know of a css workaround for this issue.

**Comment by tomscholz** [comment]
No, we are currently not aware of any workaround. Try opening an issue [here]( https://bugs.chromium.org/p/chromium/issues/). Also these could help: #4580, #4357, #4651

**Comment by dbauszus-glx** [comment]
Cool. I didn't know this bug tracker. I opened a [report](https://bugs.chromium.org/p/chromium/issues/detail?id=740498) there. 

The same thing seems to happen as well on Google's own getmdl.io page.

![image](https://user-images.githubusercontent.com/22201617/28015518-379e6eaa-6568-11e7-9378-df39e4dc5597.png)

**Comment by Dogfalo** [comment]
If you use Canary, expect bugs and report it to the chrome team, not here.
