### ISSUE TITLE
Close sidenav by swiping on menu

### ISSUE THREAD

**Issue by bert-w** [Dogfalo/materialize#4953]
## Expected Behavior
When having an open sidenav, the sidenav should be closable by starting a swipe gesture anywhere on the screen. Currently, it only seems to trigger when starting the swipe from the part of the screen that is not occupied by the sidenav.

See animation on http://materializecss.com/mobile.html . This animation shows the (imo) incorrect behaviour for closing the menu. The swipe gesture starts at the very right of the screen, and will only trigger in this (darkened) area.

## Possible Solution
Have the swipe gesture trigger anywhere on the screen when the sidenav is expanded.

https://play.google.com/store/apps/details?id=com.microsoft.office.outlook seems to do it neatly.

## Your Environment
* Version used: 0.99
* Browser Name and version: Chrome 59 (tested on Android 7). But most likely applicable to any browser/system.
* Operating System and version (desktop or mobile): Android

**Comment by Dogfalo** [comment]
Added in v1-dev branch
