### ISSUE TITLE
Problem with dropdown and sidenav

### ISSUE THREAD

**Issue by Ravenclaw968** [Dogfalo/materialize#4958]
I have an issue that seems similar to other issues I have seen, but seems to have a slight difference.

So here's the issue I am having.

I have both a main nav bar and side nav. I want to have users use the main nav bar if they are on a desktop and I want to have users use the side nav bar if they are on a mobile device.

The number of links of both of main and side nav bar have been increasing and I want to use dropdowns to organize the links.

The problem is the dropdown only works in the sidenav but fails to work in the main nav bar.

Here is the code for my navbar:

```
<nav id = "nav-bar">
	<div class="nav-wrapper indigo darken-4">
	  <a href="#" data-activates="mobile-demo" class="button-collapse"><i class="hi hi-bars hi-2x"></i></a>
	  <ul id="nav-mobile" class="right hide-on-med-and-down">
                  <ul id="dropdown1" class="dropdown-content">
                           <li><a href="#!">one</a></li>
                           <li><a href="#!">two</a></li>
                           <li class="divider"></li>
                           <li><a href="#!">three</a></li>
                  </ul>
                  <li><a class="dropdown-button" href="#!" data-activates="dropdown1">Dropdown<i class="material-icons right">arrow_drop_down</i></a></li>
	  </ul>
	  <ul id="mobile-demo" class="side-nav">
	  	<ul id="dropdown1" class="dropdown-content">
                           <li><a href="#!">one</a></li>
                           <li><a href="#!">two</a></li>
                           <li class="divider"></li>
                           <li><a href="#!">three</a></li>
                  </ul>
                  <li><a class="dropdown-button" href="#!" data-activates="dropdown1">Dropdown<i class="material-icons right">arrow_drop_down</i></a></li>
	  </ul>
	</div>
</nav>
<script>
      $(document).ready(function()
      {
        $(".button-collapse").sideNav();
        $(".dropdown-button").dropdown();
      });
</script>
```

How would I go about fixing the issue so that the dropdown works in the main navbar for desktops and so that the dropdown works in the sidebar for mobile devices?

**Comment by storm1er** [comment]
Attributes `id` have to be unique
You can use & store `Materialize.guid()` to build your ids,
Or just change one of your `id="dropdown1"` to `id="dropdown2"` and, obviously, change his intier ;)

**Comment by Ravenclaw968** [comment]
@storm1er Thanks so much, it works!
