### ISSUE TITLE
Drag out menu not working with two sideNav

### ISSUE THREAD

**Issue by ak1132** [Dogfalo/materialize#496]
In the latest version I have implemented the left and right sideNav. While the nav bars work fine with buttons they failed to do the same while using the drag out menu.Right menu works fine while the left menu fails.

**Comment by ak1132** [comment]
I think the issue is not detecting whether the other menu is open.Thus the conflict

**Comment by acburst** [comment]
We currently don't support having both a left and a right sideNav. We may look into this later.
