### ISSUE TITLE
Navbar drop shadow is hidden by next element if it has a background color.

### ISSUE THREAD

**Issue by nrathi** [Dogfalo/materialize#4961]
## Expected Behavior
The navbar should always appear to be "above" the content that immediately follows. 

## Current Behavior
The navbar drop shadow is hidden by the next element if it has a background color.

## Possible Solution
I tried changing the z-index manually and it didn't work. Maybe absolute positioning?

## Steps to Reproduce (for bugs)
```
  <!-- Navigation -->
  <nav class='light-blue' role='navigation'>
    <div class='nav-wrapper container'><a href='#' class='brand-logo'><img src='assets/logo.svg'/></a>
      <ul class='right hide-on-med-and-down'>
        <li><a href='#'>Link</a></li>
        <li><a href='#'>Link</a></li>
        <li><a href='#'>Link</a></li>
      </ul>
      <ul id='nav-mobile' class='side-nav'>
        <li><a href='#'>Link</a></li>
        <li><a href='#'>Link</a></li>
        <li><a href='#'>Link</a></li>
      </ul>
      <a href='#' data-activates='nav-mobile' class='button-collapse'><i class='material-icons'>menu</i></a>
    </div>
  </nav>

  <!-- Intro -->
  <div class='light-blue lighten-5'>
    <div class='container'>
      <br><br>
      <div class='row'>
        <h5 class='col s12'>Title</h5>
      </div>
      <div class='row'>
        <div class='col s12 l8'>
          Some content goes here.
        </div>
      </div>
      <br><br>
    </div>
  </div>
```

## Your Environment
Downloaded the starter template here: http://materializecss.com/getting-started.html. Nothing besides that.

**Comment by Dogfalo** [comment]
Please provide a codepen

**Comment by nrathi** [comment]
https://codepen.io/anon/pen/QgowVq

**Comment by nrathi** [comment]
Furthermore, the navbar should stay above the content as the page scrolls, so maybe the solution I provided is correct... I updated the Codepen to account for the responsive navbar height.

**Comment by nrathi** [comment]
Sorry, this is my bad. I should use [navbar-fixed](http://materializecss.com/navbar.html#navbar-fixed).
