### ISSUE TITLE
UL style not applying with browserdefault class

### ISSUE THREAD

**Issue by camro** [Dogfalo/materialize#4962]
List style is not applied if browser default is in another ul

![screenshot](https://user-images.githubusercontent.com/785319/28199771-8e4d01ee-68ab-11e7-968f-4bab5ea7fbb0.png)

**Comment by Dogfalo** [comment]
Please add a Codepen

**Comment by acburst** [comment]
Fixed in a6703be4b709d8b94a1c26b43a4985179acf5a75
