### ISSUE TITLE
Input search in navbar with unwanted margin at version 0.99.0

### ISSUE THREAD

**Issue by rafael-atrixdevelopers** [Dogfalo/materialize#4964]
Chrome version: 59.0.3071.115

http://materializecss.com/navbar.html#search-docs

![materialize](https://user-images.githubusercontent.com/30170023/28200648-d1a3a4b0-6843-11e7-93cf-632bd7a8b84a.png)

After I add css property 
height: 65px !important; 
got corrected
![materialize2](https://user-images.githubusercontent.com/30170023/28200827-8db1de4c-6844-11e7-85c2-32386f23e5bc.png)

**Comment by Dogfalo** [comment]
Fixed, but not yet released
