### ISSUE TITLE
Tab active class not properly set on tab swipe

### ISSUE THREAD

**Issue by thorge** [Dogfalo/materialize#4965]
First of all thanks for materializecss, this is a great frontend framework.

While using swipeable tabs, I recognized that a tab's > li > a class 'active' is not properly set, when a tab is swiped. The class is only set on click.

There's no need for a fiddle, if you want to reproduce, just check the swipeable tab demo in [Materialize documentation](http://materializecss.com/tabs.html#swipeable)

Tested on Ubuntu 16.04 with Firefox 54.0 and Chrome 59.0.3071.86

**Comment by acburst** [comment]
Fixed in 3fa6faf9
