### ISSUE TITLE
drag-target from side menu makes right side of screen unreachable 

### ISSUE THREAD

**Issue by ventouris** [Dogfalo/materialize#497]
I use the side menu and I have a problem with the div with class "drag-target".

This div has a width of 10% and it is invisible. However, everything behind the div is unreachable. You cannot click a button if it is in the right 10% of the screen.

**Comment by Dogfalo** [comment]
Fixed in 456045fb66a48ace952e5a30349777cd219d6d9a

**Comment by BaronVonBraun** [comment]
Still seems like an issue - when dragging the side nav closed, the drag-target div winds up with a width of 10% instead of 10px, as would be expected.

Lines 199 and 214 of the sideNav.js seem to be the culprits.  Should they be setting the width to '' instead of '10%'?
