### ISSUE TITLE
exception noise when you click an svg

### ISSUE THREAD

**Issue by hypercross** [Dogfalo/materialize#4970]
So I noticed my console getting spammed by exceptions whenever I click on an SVG and after some digging it turns our that the code dealing with SVGs assumes that they have .className of type string, but instead SVGs have something like SVGAnimatedString {baseVal: string, animVal: string}.

relevent code: 
```
/**
     * Delegated click handler for .waves-effect element.
     * returns null when .waves-effect element not in "click tree"
     */
    function getWavesEffectElement(e) {
        if (TouchHandler.allowEvent(e) === false) {
            return null;
        }

        var element = null;
        var target = e.target || e.srcElement;

        while (target.parentElement !== null) {
            if (!(target instanceof SVGElement) && target.className.indexOf('waves-effect') !== -1) {
                element = target;
                break;
            } else if (target.className.indexOf('waves-effect') !== -1) {
                element = target;
                break;
            }
            target = target.parentElement;
        }

        return element;
    }
```

indexOf doesn't exist on SVGAnimatedString so can we have something like target.classList.contains instead? or since nobody cares about SVGs I can even live with a null returned.

**Comment by Dogfalo** [comment]
741d47a092ba4f09ce841c7fa98def1ce0dcfd2c
