### ISSUE TITLE
Dropdown option background color is showing as light blue for a while when user tap the option in android chrome browser. 

### ISSUE THREAD

**Issue by manikumar446** [Dogfalo/materialize#4976]
I am using materialize CSS dropdown. When user taps the option inside of dropdown, it's background color is showing up as light blue. I have attached touchstart and touchend events to override options default color to some other color. But still the default blue color is showing up for a sec and then my custom color is showing up. To replicate the same open http://materializecss.com/dropdown.html (dropdown example)  in androids chrome browser and tap and hold the dropdown options.

**Comment by manikumar446** [comment]
I am using materialize CSS dropdown. When user tap the option inside of dropdown, it's background color as light blue. I have attached touchstart and touchend events to override options default color to some other color. But still the default blue color is showing up for a sec and then my custom color is showing. To replicate the same open [dropdown example](To replicate the same, open ) in androids chrome browser.

**Comment by DanielRuf** [comment]
Do you mean the `-webkit-tap-highlight-color`? https://github.com/Dogfalo/materialize/pull/4555/files

Might need a PR / fix.

**Comment by manikumar446** [comment]
@DanielRuf Thanks for your reply. Yes, exactly I was looking for `-webkit-tap-highlight-color`. It's solved my problem,
