### ISSUE TITLE
Text inputs wider that input box can't be edited on IOS

### ISSUE THREAD

**Issue by NichUK** [Dogfalo/materialize#4977]
## Expected Behavior
If you enter text which is longer than the input box on IOS mobile, you should still be able to edit it by putting the caret within the text and running it to the right under the magnifier until you get to the section you want to edit. The entire box should scroll to the left to bring hidden text into view.

## Current Behavior
Currently, hidden text which is further to the right of the input string than the right of the box cannot be reached.
I don't have an Android device available to test. Scrolling to edit hidden text works correctly on Desktop.

## Steps to Reproduce (for bugs)
1. Navigate to http://materializecss.com/forms.html on IOS mobile
2. Enter a ridiculously long Last Name into the input field so that has to scroll to accept the input
3. Move to the next field and enter something
4. Go back and try and edit the Last Name somewhere near the end which is not shown

## Context
This is a problem with any mobile form, especially for small devices.

## Your Environment
IOS 10.3.2 (14F89)
iPhone 6 Plus
Builtin Safari Browser

**Comment by Dogfalo** [comment]
This is an iOS issue that needs to be addressed by Apple

**Comment by Dogfalo** [comment]
Even on google.com it does not work
