### ISSUE TITLE
Carousel Arrows

### ISSUE THREAD

**Issue by kezfran** [Dogfalo/materialize#4978]
Hi guys, is there any plan to add prev and next arrows option on Carousel?
Thanks

**Comment by DanielRuf** [comment]
You can easily achieve this by prepending and appending them with an onclick eventlistener and triggering prev/next.

**Comment by tomscholz** [comment]
I agree with @DanielRuf. It is easy enough to add it yourself and in addition to that not part of [the specs](https://material.io/guidelines/).
