### ISSUE TITLE
Carousel image only loads one time.

### ISSUE THREAD

**Issue by MiniSquash** [Dogfalo/materialize#4979]
Carousel images only loads one time for my website. After every subsequent refresh, there is no image shown. I can't detect what is the error so i suppose it is a bug. 

I think the carousel is reduced to 0px which results it to not being seen. I inspect element and saw
`<div class="carousel carousel-slider initialized" style="height: 0px;">`

Expected behaviour : Image loads every time.
The Code : https://github.com/MiniSquash/Testing
The page : https://minisquash.github.io/Testing/

**Comment by DanielRuf** [comment]
Please provide a full codepen.

**Comment by MiniSquash** [comment]
@DanielRuf Here it is.
https://codepen.io/anon/pen/dRERYX

**Comment by DanielRuf** [comment]
I just see 404s, the images do not exist.

**Comment by MiniSquash** [comment]
@DanielRuf The 404 image not found is the developer part. The carousel has the image just that the height is initialized to 0px height

**Comment by DanielRuf** [comment]
The https version of the images leads to a 404.

**Comment by MiniSquash** [comment]
The 404 kappa message is the one of Developers image. The carousel image i have already placed

**Comment by DanielRuf** [comment]
Please make your images available over https, the http images are blocked over https. And your https versions lead to 404s.

**Comment by MiniSquash** [comment]
Okay @DanielRuf Updated. Sorry for the inconvenience.

**Comment by Maqsyo** [comment]
Please test this on you local server!
i tried to get it work with images at ./images/ and they didn't worked as well
Just images with https from the web worked for this (locally)

The normal carousel is working, but if i try to use it as a full-width carousel, it stops to work (height:0px)

**Comment by DanielRuf** [comment]
@Maqsyo do you mean the mixed content warnings which block the downloads?
Full width carousel shoul normally work. It work in the documentation on http://materializecss.com/carousel.html

**Comment by Maqsyo** [comment]
Here you can see the test from your website
![test_website](https://user-images.githubusercontent.com/19644698/28332294-95b6eaf2-6bf4-11e7-8189-60d8ed314913.PNG)

This one is exactly the same good, but with local images in the same dir. The image gets loaded (you can see this in the dev-tool).
style="height:0px"
![test_website2](https://user-images.githubusercontent.com/19644698/28332298-99767d42-6bf4-11e7-8794-dc1ec5c34cd9.PNG)

This one is with the same images and the same code, but without the option full-width
![test_website3](https://user-images.githubusercontent.com/19644698/28332302-9ac3d30c-6bf4-11e7-8a34-fe622f86ce39.PNG)


i hope you can see the issue now..

**Comment by DanielRuf** [comment]
@Maqsyo the issue of @MiniSquash is solved as the images are shown now.

Please open a new issue for your issue. I guess it is related to jQuery or to one of these lines

https://github.com/Dogfalo/materialize/blob/master/js/carousel.js#L43
https://github.com/Dogfalo/materialize/blob/master/js/carousel.js#L45

**Comment by Maqsyo** [comment]
I chatted with @MiniSquash private and he had exactly the same issue. He just putted in online images to show it to you and with these ones they are working..
He just can't create good tickets ^^
But I'll open a new issue tomorrow. No problem :)
