### ISSUE TITLE
Bug: Carousel is not displaying images in full-width

### ISSUE THREAD

**Issue by Maqsyo** [Dogfalo/materialize#4982]
## Expected Behavior
http://materializecss.com/carousel.html#slider
The Full-Width Slider should work :P

## Current Behavior
@MiniSquash tried to use the Carousel in full-width.
He had the Problem, that his locally stored images are not shown, but loaded.
So i tested this and i had the same issue. 
In the pictures below you can see, that the normal slider is working, but if i'm adding the class .carousel-slider OR/and the config {fullWidth: true}, the pictures are not shown. 
The Wrapper container gets the style argument **height:0px**
Thats the working one:
![test_website](https://user-images.githubusercontent.com/19644698/28352610-c559c1fe-6c57-11e7-8f25-67a16f86e561.PNG)

This one is exactly the same, but with local images in the same dir.
You can see here, that no image is shown
The image gets loaded (you can see this in the dev-tool).
![test_website2](https://user-images.githubusercontent.com/19644698/28352638-e285f464-6c57-11e7-8bc3-51136ddc7104.PNG)

And here i'm testing the local stored images for you, with the normal slider:
![test_website3](https://user-images.githubusercontent.com/19644698/28352646-ee5c3172-6c57-11e7-9af7-bd3e9a2e8292.PNG)

So i tried a thing more: Online stored pictures.
And every image is working. Except of the local ones. Damn!

## Possible Solution
So i had a small "conversation" ( #4979 ) with @DanielRuf and he thinks, that this Problem is related to jquery or to one of following lines:
https://github.com/Dogfalo/materialize/blob/master/js/carousel.js#L42
https://github.com/Dogfalo/materialize/blob/master/js/carousel.js#L45

jQuery Prop definition (Stackoverflow) :
https://stackoverflow.com/questions/31700206/jquery-window-load-vs-window-propcomplete

### Workaround
You could set a fixed height in your own style.css as important.

## Steps to Reproduce (for bugs)
[test.html.txt](https://github.com/Dogfalo/materialize/files/1158156/test.html.txt)
So here's the test-code, so you don't have to type it again.
Just use a local stored image and you'll see the magic will begin ♥

## Your Environment
Materialize version: v0.99.0
Tested in following browsers: 

- Chrome
- FireFox
- Edge
- Safari

**Comment by leedoe** [comment]
I have the same problem but I used linked image files instead of local image files.

**Comment by tomscholz** [comment]
Related issues #3899 #4372

**Comment by Maqsyo** [comment]
@tomscholz sure.. Sorry haven't seen them before.
So the issue is older than v0.98.2 ^^

**Comment by AugmentBLU** [comment]
Setting the height in CSS is not really working since the item might be a lot bigger on mobile and require overflow. Using overflow on carousel items is not working, I see the scroll bar but seems the pointer events are not working.

**Comment by gusbemacbe** [comment]
I have the same problem too.

**Comment by gusbemacbe** [comment]
I solved the bug and it worked!

Copy the following codes:

`$('.carousel.carousel-slider').carousel({fullWidth: true}).style.height = window.innerHeight + "px";`

**Comment by DanielRuf** [comment]
@gusbemacbe this is not a clean fix imho.

**Comment by acburst** [comment]
Fixed the local image bug with 538f9dee04d7b8589b179cd78e1e20ad6a164787. Let me know if this works for cached images as well because I am having trouble reproducing it.

**Comment by gusbemacbe** [comment]
It worked nothing. 

I added carousel.js to my project and nothing worked.

**Comment by DanielRuf** [comment]
@gusbemacbe did you try recompiling the files using `grunt js_compile`? You should get a new materialize.js file.

**Comment by gusbemacbe** [comment]
@DanielRuf, no, I never used grunt. I use only node. i tried, but it gave an error:

```
npm materialize-css
cd materialize
npm install grunt
grunt js_compile
grunt: command not found
```

**Comment by DanielRuf** [comment]
No, you have to clone https://github.com/Dogfalo/materialize, run grunt and use the compiled files. npm uses tagged releases, not the masterby default (or use the dev / master / preferSource option).

**Comment by DanielRuf** [comment]
Also grunt should be globally installed using the `-g` flag.

**Comment by DanielRuf** [comment]
In your case you have just a local grunt in node_modules and you need the path to it and execute it with node.

**Comment by gusbemacbe** [comment]
It still gives some errors. 

```
cd node_modules/materialize_css
grunt -g
grunt -g jGruntfile.js
node grunt Gruntfie.js
node grunt -g Gruntfile.js
...
```

I tried more than 20 commands and nothing worked.

I am not familiar with Grunt. I am new to Grunt. It gave the following errors:

```
Loading "Gruntfile.js" tasks...ERROR
>> Error: Cannot find module 'autoprefixer'
```

**Comment by DanielRuf** [comment]
https://gruntjs.com/getting-started

**Comment by gusbemacbe** [comment]
I have already installed Grunt before one hour ago. But I discovered the problem, because folder materialize had folders bootstrap inside. I had to clean ad exclude, and reinstall materialize and run `grunt monitor`, it worked, I got `materialize.css` and `materialize.js` version 0.100, and the carousel worked now.

**Comment by Maqsyo** [comment]
So the fix is working and you can test the pull request? Yeihhh.
And still no version 1.x? :P

**Comment by DanielRuf** [comment]
Right, 0.100.0 was released today and fixed this.

I think we can close the issue.

**Comment by Maqsyo** [comment]
Mhpf. Updated materialize a few days ago xD
Okay. I'll test this!
See ya!

**Comment by DanielRuf** [comment]
@Maqsyo we have a release almost every month.

**Comment by jessegilbride** [comment]
FYI, I'm using v0.100.2 and I am having this issue.  *sigh*

**Comment by DanielRuf** [comment]
@jessegilbride please provide a codepen. I guess this is all related to image loading and when the DOM is ready.

**Comment by jessegilbride** [comment]
@DanielRuf I think you're right because if I put the carousel initialization inside the modal's 'ready' statement it works as expected (or close to it).  Here's the pen, as requested: 

https://codepen.io/jessegilbride/pen/EwdPyr

**Comment by DanielRuf** [comment]
@jessegilbride right, this should be done in the ready callback in the modal (and when the referenced images are available - testing with something like imagesloaded). That's how the DOM works and how it is solved in other frameworks too.

**Comment by gusbemacbe** [comment]
@DanielRuf do you mean those famous TypeError of undefined functions errors?

**Comment by DanielRuf** [comment]
@gusmacbe this is probably unrelated.
