### ISSUE TITLE
Dropdown with material design, but native options list

### ISSUE THREAD

**Issue by vulvulune** [Dogfalo/materialize#4983]
This is a feature request:

On safari mobile (iPhone and iPad), the dropdown menu is very powerful and, in my opinon, better than the material menu. And if it's a select field, the arrows to navigate between fields works (they don't work with the material dropdowns).

It should be nice to have the select menu with the material design, but when we click on it, let's the browser display the options list (in a popover on iPad, and on the bottom of the screen on iPhone). If I set the `browser-default` class, it works, but I have the select with the non-material native design.

In my opinion, we should split the `browser-default` class in 2 classes, one to define the design, and one to define the behavior.

What do you think about this request?

If you agree it, I can work on it and propose a PR.

**Comment by DanielRuf** [comment]
This is not an option for the components. You have to do this responsive adjustment yourself (adding `browser-default` on small viewports).

**Comment by vulvulune** [comment]
But if I add `browser-default` I have the native select design, and native select behavior to display the options. I would like to have the material design, but the default browser behavior when you open it.

I will provide a sample of what I want.

**Comment by inventti-leonardo** [comment]
@vulvulune I agree that `select.browser-default` is ugly and it does not combine with material design framework at all. I have been some "unexpected behaviors" using normal select of materialize with two-way data bind viewmodels (like knockout, vue, angular, etc). So I decide to use `select.browser-default` with a lot of css to be visually like others components. :)

**Comment by DanielRuf** [comment]
You can trigger a click on the select or place it over the css styled input, set opacity to 0 and it should open.

**Comment by vulvulune** [comment]
I've found a solution to have a native select with material design (when it is closed, because it's hard to style the options by css, but in my case I don't care because I want use it only on safari mobile).

Add this scss file:
`select.browser-default {
    border: none;
    border-bottom: $input-border;
    padding: 0;
    -webkit-appearance: none;
    -moz-appearance: none;
    appearance: none;
    outline: none;
    margin: $input-margin;

    option {
        font-size: 16px;
        color: $dropdown-color;
        line-height: 22px;

        &:hover {
            background-color: $select-option-hover;
        }


        &:disabled {
            background-color: transparent;
            color: $select-disabled-color;
        }
    }
}`

In your form, just add this code:
`<div class="input-field">
	<div class="select-wrapper">
		<span class="caret">▼</span>
		<select class="browser-default" >
			<option disabled>Select a value</option>
                        <option>Value 1</option>
			<option>Value 2</option>
			<option>Value 3</option>
                </select>
	</div>
	<label>Title/label>
</div>`
 
And you don't need to call `material_select()` to initialize it.

If you don't want to add the `select-wrapper` and the caret in your form, use this code:
`<div class="input-field">
	<select class="browser-default" >
		<option disabled>Select a value</option>
                <option>Value 1</option>
		<option>Value 2</option>
		<option>Value 3</option>
        </select>
	<label>Title/label>
</div>`

But you have to update the `material_select` function like this.
Replace here (https://github.com/Dogfalo/materialize/blob/64e7c0f53913d4908865f5b7947af9b67cc74216/js/forms.js#L492):
Before:
`if ($select.hasClass('browser-default')) {
  return; // Continue to next (return false breaks out of entire loop)
}`

After:
`if ($select.hasClass('browser-default')) {
    var wrapper = $('<div class="select-wrapper"></div>');
    wrapper.addClass($select.attr('class'));

    // Wrap Elements
    $select.wrap(wrapper);
    // Add Select Display Element
    var dropdownIcon = $('<span class="caret">&#9660;</span>');
    $select.before(dropdownIcon);
            
    return;
}`

**Comment by DanielRuf** [comment]
Why not use `@extend select` and so on?

This is not a viable option for other users.

**Comment by vulvulune** [comment]
Because the select isn't defined in the other scss file. I tried to reuse what already exist but it's pretty hard because dispatch between some other components.

I know it's not a viable solution. Just some idea to know what we should do if we want support select with CSS styling and without drop down. The implementation of Google offers this feature.

**Comment by acburst** [comment]
I'm sorry, but this is not something we are going to support.

**Comment by adick** [comment]
This is pretty easy to achieve actually. 

CSS:

```
/* force the native select field to overlay the material select */
.select-wrapper {
	position: relative;
}
.select-wrapper select {
	display: block;
	position: absolute;
	left: 0;
	right: 0;
	top: 0;
	bottom: 0;
	z-index: 10;
	opacity: 0;
}
```

JS for initialization: 

```
var selectFields = $('select');
selectFields.each(function () {
	var selectField = $(this);
	selectField.material_select();
	selectField.on('change', function () {
		// re-init when native field changes
		selectField.material_select();
	});
});
```
