### ISSUE TITLE
Materialize isn't compatible with jQuery.nicescroll. 

### ISSUE THREAD

**Issue by gusbemacbe** [Dogfalo/materialize#4984]
## Expected Behavior
I applied [jQuery.nicesroll](https://github.com/inuyaksa/jquery.nicescroll), using this framework and nothing got effect.

## Current Behavior
It seems that jQuery.nicescroll has conflict with materialize.js.

## Possible Solution
Turn compatible with jQuery.nicescroll. 

## Steps to Reproduce (for bugs)
1. You use only the jQuery.nicescroll
2. Apply the Javascript codes to initialise the nicescroll, using both `html` or `body`:

```
<script type="text/javascript">
$(function() {  
    $("body").niceScroll();
});
</script>
```

3. The browser scrollbar disappeared and dint get effect.

Also read the issue I open with jQuery.nicescroll's Github: https://github.com/inuyaksa/jquery.nicescroll/issues/682

## Your Environment

* Version used: 0.99
* Browser Name and version: Safari 10.0 and Chrome 59.0.3071.115
* Operating System and version (desktop or mobile): macOS Sierra 10.12
* Link to your project (if appropriate): https://codepen.io/gusbemacbe/pen/QgXzdR

**Comment by DanielRuf** [comment]
Not reproducible with the right JavaScript file.

https://codepen.io/anon/pen/YQoBKR

There were warnings in the console.

![image](https://user-images.githubusercontent.com/827205/28387778-ab88823c-6cd0-11e7-9a30-d8e5aac0b20b.png)

**Comment by gusbemacbe** [comment]
But in my browser, Chrome said that there was no errors. Strange!

**Comment by gusbemacbe** [comment]
I compared my pen and yours, but they are the same. How did you figure?

**Comment by Dogfalo** [comment]
https://codepen.io/Dogfalo/pen/awgXdY

**Comment by DanielRuf** [comment]
> https://codepen.io/Dogfalo/pen/awgXdY

That's generally what I posted ;-)

**Comment by gusbemacbe** [comment]
@DanielRuf , but this problem is still unsolved. Not just `html`, try to apply to `body` and to `side-nav` (if you have many items), you will see nothings works. It is absolutely incompatible.

**Comment by DanielRuf** [comment]
@gusbemacbe it definitely work in Chrome 59 (on Windows 10).

Will try it on macOS in a few hours and in Safari.

**Comment by gusbemacbe** [comment]
@DanielRuf, anther issue that gives reason to the incompatibility between jQuery.nicescroll and Materialize, for example.

Bootstrap has Javascript events, but does Materialize have events?

So see the codes, for example:

```
    $("#scrollcustom").on("shown.bs.dropdown",function(e){
      nicelist.show().resize();
    });

    $("#scrollcustom").on("hide.bs.dropdown",function(e){
      nicelist.hide();
    });
```
According to Materialize documentation - http://materializecss.com/side-nav.html:

Try to apply `show` and `hide` and nothing worked. Try to apply `click` and `data-activates` and nothing works. Also apply `.button-collapse` and `.side-nav`, `#nav-mobile` and `#slide-out` and nothing works. 

It is an issue of compatibility and not an issue of bug. I think the solution only is that Materialize add a compatibility support for jQuery.nicescroll or jquery.nicescrol add a support for Materialize.

**Comment by DanielRuf** [comment]
No, internally Materialize triggers and uses some custom events. But please do not mix multiple issues in this one.

Let's see if I can reproduce that or not.

**Comment by gusbemacbe** [comment]
OK, @DanielRuf!

**Comment by gusbemacbe** [comment]
You can get my quick pen and analyse the nicescroll problem applied to side-navbar, @DanielRuf:
https://codepen.io/gusbemacbe/pen/QgeWjO

**Comment by DanielRuf** [comment]
Works in Chrome and Safari on macOS. Not reproducible. The custom scrollbar is shown and works.

**Comment by DanielRuf** [comment]
The sidenav is another issue.

**Comment by gusbemacbe** [comment]
Do I have to create a new issue about side-nav with nicescroll?

**Comment by inuyaksa** [comment]
Sorry, I think your code contain many errors.
I made some fixes, now nicescroll showed  with sidebar.
There is a problem with greyed layout, but it's a page layout mistake or materialize issue .
https://codepen.io/anon/pen/Qgebrd?editors=0000
