### ISSUE TITLE
The navbar-fixed has still a bug in the version 0.100.0 :-/

### ISSUE THREAD

**Issue by gusbemacbe** [Dogfalo/materialize#4986]
Maintaining the nav-extended, because if not adding it, the navbar get misaligned or disarranged. Then if with nav-extended and using div and nav-fixed, thee is still a bug. When you click the menu, you will the transparent overlay everywhere, including the side-navbar. 

Check my pen (also included jquery.nicescroll applied to html (it works) and applied to side-navbar (not worked)):
https://codepen.io/gusbemacbe/pen/QgeWjO

**Comment by acburst** [comment]
There is a known fix to this. Move your side-nav element outside of the navbar and it will work.

**Comment by gusbemacbe** [comment]
Ah, it worked now.

**Comment by gusbemacbe** [comment]
But custom scroll is inside the navbar. :-/

**Comment by acburst** [comment]
I'm not exactly sure what nicescroll is and how it applies to the navbar?

**Comment by gusbemacbe** [comment]
Nicescroll is a Javascript and jQuery customisation of the scrollbar, making I compatible with all browsers, for the replacement of :: scrollbar which isn't supported on Firefox.

The nicescroll works only on the tag html, but doesn't work on the sidenav because it doesn't have events like Bootstrap does.

**Comment by gusbemacbe** [comment]
The problem is that you didn't include the events lists in the documentation or in the section of sidenav. The documentation needs to be complete.

**Comment by acburst** [comment]
We don't use events. We use the callbacks onOpen and onClose which are plugin options. I don't know how else to say it. Also it is not our job to vet every third party plugin in existence and make sure it can work perfectly in every way possible. That is unrealistic. If you find a simple fix that makes them compatible we are happy to merge it. But we won't go out of our way to write our components so they can accommodate third party plugins.
