### ISSUE TITLE
Bug: Modal options / open - Error Thrown

### ISSUE THREAD

**Issue by Maqsyo** [Dogfalo/materialize#4987]
## Expected Behavior
✨ Rewrote Modal Plugin ✨
- Modal open no longer initializes plugin
- Fixed bug where modal open did not use initialized options
i expected, that Modals are working now like in version 0.98.2

## Current Behavior
The Options aren't used with v0.100.0 and i get Errors (images below)
I cant put the options in $('.modal').modal({options}) neither in $('.modal').modal('open', {options})
So the Version v0.100.0 is unusable for me
![modal_open](https://user-images.githubusercontent.com/19644698/28402843-32b0b9f4-6d22-11e7-9356-26b08143a09f.PNG)
![modal_code](https://user-images.githubusercontent.com/19644698/28402846-34625a1e-6d22-11e7-9fb1-cba9727322b5.PNG)

## Possible Solution
I dont know.
What have you changed for this literally "breaking"-change?

## Steps to Reproduce (for bugs)
A Codepen will follow in a few minutes ♥

## Your Environment
* Version used: v0.100.0
* Browser Name and version: Chrome / Edge / Firefox / Safari
* Operating System and version (desktop or mobile): Android / Windows / iOS

**Comment by Dogfalo** [comment]
In my testing with the materialize.min.js downloaded from the website, I was not able to reproduce this yet. The problem could be arising because an element on your DOM is no longer available?

**Comment by Maqsyo** [comment]
I'm testing this..
Cant reproduce it in codepen yet xDD

**Comment by acburst** [comment]
Also, you can no longer use $('.modal').modal('open', {options})

**Comment by Maqsyo** [comment]
So idk why but i only have this error in my application...
The modal-functions triggers again, after i changed $(this) to $(modal)

I only have following error:
`Uncaught TypeError: Cannot read property 'M_Modal' of null`
`var modalInstance = document.getElementById(modalId).M_Modal;`
Line 1990

i think it's my fault and i'm sorry for the circumstances
so i have to search longer for my issue..

**Comment by Maqsyo** [comment]
https://codepen.io/MaqsYo/pen/VWowJp?editors=1010

HAHAHAHAA i found the issue :DDDD

i have an I-Tag in the button.
And here (Line 1988) he's trying to get the data-attribute.
BUT in this Version he thinks, that the i-tag is the e and not the button itself!
`modalId = e.target.getAttribute('data-target');`
so i have to do following to open modals:
```
<button class="btn-floating btn-large blue modal-trigger">
        <i class="fa fa-window-restore" aria-hidden="true" data-target="modal-list"></i>
</button>
```
And thaaaats kind of stupid :D

**Comment by Maqsyo** [comment]
https://github.com/Dogfalo/materialize/commit/fea1d65c1698ba3036a09eb82104f241b8c03bef

**Comment by Dogfalo** [comment]
New hotfix release v0.100.1 fixes this
