### ISSUE TITLE
Jquery wise selecting a tab

### ISSUE THREAD

**Issue by cskiwi** [Dogfalo/materialize#499]
hi,

I'm using angular and materialize.
And I'm making a list / detail tab, so when one selects an item it needs to switch to the detail tab.

but I don't know if this is an implemented feature or not?

**Comment by acburst** [comment]
Added in 4262d8e0b816ec0c28c651ea3b3efda6024b7c4b

You can now select a tab in jquery like:

```
 $('ul.tabs').tabs('select_tab', 'test2');
```

Where test2 is the id of the tab you are switching too.
