### ISSUE TITLE
Dropdown with data-alignment="right" opens in wrong position

### ISSUE THREAD

**Issue by DetlefPeters** [Dogfalo/materialize#4990]
In latest v0.100.0, when you define a dropdown with `data-alignment="right"`, the dropdown-menu opens in the wrong x position.
The right side of the menu should be aligned to the right side of the dropdown button, but instead it is placed completely to the right of the button.

Obviously the value of the `left `Attribute in the style is too high - the width of the menu has not been subtracted

**Comment by Altroo** [comment]
i don't know if we can call this a fix but it works for me : 
i changed those line in Materialize.js

`   // Constrain width Line 1667
        if (curr_options.constrainWidth === true) {
          activates.css('width', origin.outerWidth());
         // it was :
         // activates.css('width', originWidth);
        } else {
          activates.css('white-space', 'nowrap');
        }
       ...
       ...
       // Line 1735
       var offsetRight = origin.position().left + origin.outerWidth() - activates.outerWidth();
       // it was : 
       // var offsetRight = origin.position().left + originWidth - activatesWidth;
`
This is from the 0.99 version so the new lines made the issue i believe : 
`var originWidth = origin[0].getBoundingClientRect().width;
        var activatesWidth = activates[0].getBoundingClientRect().width;`

**Comment by Altroo** [comment]
in 0.100 version this did the trick working for left and right
/* Line 1664 */
`var originWidth = origin[0].getBoundingClientRect().width - 108;`

**Comment by Dogfalo** [comment]
Fixed in a1ee367b
