### ISSUE TITLE
Angular Js: Uncaught TypeError: Materialize.updateTextFields is not a function

### ISSUE THREAD

**Issue by Piyush95aadi** [Dogfalo/materialize#4995]
Hi, 
I am trying to use Materialize in my angular project , I am using the "ui-router" service for routing.
I get this error on the console:
 `Uncaught TypeError: Materialize.updateTextFields is not a function
    at HTMLDocument.<anonymous> (materialize.js:4362)
    at mightThrow (jquery.js:3583)
    at process (jquery.js:3651)`
I have just tried writing the html directly in the body tag , it works but not when I load the template using the ui router .

Can you please let me know what am I doing wrong ? I am new to both angular and Materialize. Please help

**Comment by Piyush95aadi** [comment]
@tomscholz Please tell me what is the issue here.
I could not figure out what's wrong. Can't I use Materialize with Angular

**Comment by Dogfalo** [comment]
You might be importing Materialize incorrectly. jQuery must be loaded before Materialize.
