### ISSUE TITLE
Input field errors broken in v0.100.0

### ISSUE THREAD

**Issue by davidbgeek** [Dogfalo/materialize#4998]
#### Expected Behavior

The error appears directly under the input field.

#### Current Behavior

While the field is selected, the error behaves as intended, however when not selected, the error enlarges and moves down similarly to how the field label moves back down when the field is empty.

#### Steps to Reproduce

Create an input field with validation.

**Comment by DanielRuf** [comment]
`Fields should also not be validated when empty.`

What about required fields?

**Comment by DanielRuf** [comment]
https://github.com/Dogfalo/materialize/pull/4883

**Comment by davidbgeek** [comment]
Edited, thanks.

**Comment by acburst** [comment]
We want to look into reworking the validation implementation and decouple it from the label in the future. For now we are thinking of rolling back the required empty validation code in the meantime.

**Comment by Dogfalo** [comment]
Added temporary fix here: 3f690159
