### ISSUE TITLE
Feature: Gallery plugin with meaningful transitions

### ISSUE THREAD

**Issue by Dogfalo** [Dogfalo/materialize#5]
http://material-design.storage.googleapis.com/videos/animations-meaningfultransitions-hierarchical_transitions_topLevel_large_xhdpi.webm

**Comment by carloscarcamo** [comment]
:+1:

**Comment by smileytechguy** [comment]
This issue was moved to smileytechguy/issueTesting#81

**Comment by smileytechguy** [comment]
Please ignore that, that was a test
