### ISSUE TITLE
different type of forms inputs

### ISSUE THREAD

**Issue by Dogfalo** [Dogfalo/materialize#50]

**Comment by grafa** [comment]
Hey guys, just run into this issue. Inputs with types email or url are pure text fields (unlike type number) and I think there is a strong need for adding these 2 selectors to the main style file.

**Comment by Dogfalo** [comment]
Added support for number and tel.

**Comment by grafa** [comment]
Cool. Can't wait for the release. Thank you mate.

**Comment by carloscarcamo** [comment]
something like input mask wuldbe great also :)

**Comment by matriphe** [comment]
input[type=url] pease!

**Comment by CoDEmanX** [comment]
URL and Email are quite handy on mobile devices, because you'll have a dedicated key on the keyboard for either a slash `/` oder the at sign `@` - no need to tab-hold the period and drag over to either of these characters.

**Comment by matriphe** [comment]
please merge this pull request #492 for URL input type

**Comment by victordeassis** [comment]
Hey @Dogfalo I tried to use <input type = "tel"> but my input lost the materialize style, can you help me please?

code:
<div class="row">
          <div class="input-field col s6">
            <i class="mdi-communication-phone prefix"></i>
            <input id="icon_telephone" type="tel" class="validate">
            <label for="icon_telephone">Telephone</label>
          </div>
</div>

![bug](https://cloud.githubusercontent.com/assets/6058804/5874238/3f31c6fe-a2e6-11e4-8756-7a4201b9518a.png)

**Comment by goatandsheep** [comment]
Please add `datetime-local`
