### ISSUE TITLE
Sidebar and long titles

### ISSUE THREAD

**Issue by ventouris** [Dogfalo/materialize#500]
When there is a big tittle on the side bar menu, the <li> phrase is splitted in half and there is a big space on the option. Is there any way to make the sidebar responsive and take a width to fit all the options? Or another CSS that will not create so much space between the two words on the phrase?

**Comment by Dogfalo** [comment]
Try class="flow-text" on it

**Comment by ventouris** [comment]
I tried it and it makes everything bigger :(

**Comment by Dogfalo** [comment]
well you would then just want to specifically style the title. Making the sidebar responsive would look bad if the title was long.
