### ISSUE TITLE
modal won't open with some HTML within the <a>

### ISSUE THREAD

**Issue by minnalOne** [Dogfalo/materialize#5000]
Hello materialize team, and thanks for your great work in this framework

Here's the issue, i'm facing:

## Expected Behavior
Modal should open even if there's some html within the `<a>`

## Possible Solution

```
  <!-- Modal Trigger works... -->
  <a class="waves-effect waves-light btn modal-trigger" href="#modal">Modal</a>

  <!-- but with some HTML within the <a> it breaks -->
  <a class="modal-trigger btn-floating btn-large waves-effect waves-light red" href="#modal">
    <i class="material-icons">add</i>
  </a>
```

## Steps to Reproduce (for bugs)
https://codepen.io/anon/pen/BdBBBE?editors=1001#0

## Your Environment
* Version used: 0.100
* Browser Name and version: firefox 54 and chromium
* Operating System and version (desktop or mobile): linux mint 18.2

**Comment by Dogfalo** [comment]
New hotfix release v0.100.1 fixes this
