### ISSUE TITLE
On change event not firing when changing Material Select

### ISSUE THREAD

**Issue by sigmatec** [Dogfalo/materialize#5001]
In v0.100.0 using jQuery v3.2.1, the `change` event is not fired on the hidden `<select>` element, when the `material_select` is changed.

It works fine with jQuery 2.2.4.

**Comment by Dogfalo** [comment]
It works for me. Please add a codepen

**Comment by sigmatec** [comment]
Apologies, so it does.  I had assumed because the only thing that had changed was the jQuery version that it was something to do with that.  It must be my code :-(

**Comment by junebug12851** [comment]
I'm having this issue as well, I've tried everything but change never fires. I even tried using browser defaults by adding the class "browser-default" to the select element but its still rendered and processed by materialize (I never get the browser version). Gave up last night after spending hours on this and back to work on it again today.

**Comment by junebug12851** [comment]
I figured it out, html typo in class attribute
