### ISSUE TITLE
Datepicker bug with year. 

### ISSUE THREAD

**Issue by 17tlhon** [Dogfalo/materialize#5005]
I found a weird behavior with the datepicker input.

Changing the year on the dropdown change the year in the date preview on the left even though a new date hasn't been selected.

The year should stay the same until a new date is selected.

I am using version beta release 0.100.

EDIT: when I say "the date preview", I am talking about the blue panel.
EDIT 2: I made a quick video to better illustrate the issue [https://vimeo.com/226567416](https://vimeo.com/226567416)

**Comment by gusbemacbe** [comment]
It happened with me too. I use the 0.100.1. 

![screen shot 2017-07-22 at 02 13 09](https://user-images.githubusercontent.com/2257024/28488581-940e227e-6e83-11e7-81d1-846a8e001972.png)

**Comment by DanielRuf** [comment]
And how do you preview where you are currently in the calendar?

**Comment by DanielRuf** [comment]
@philipraets

**Comment by 17tlhon** [comment]
@gusbemacbe I am describing a different issue.

**Comment by DanielRuf** [comment]
@17tlhon please provide screenshots, video / gif to show the exact issue.

**Comment by gusbemacbe** [comment]
@DanielRuf, were you asking me or to @17tlhon? 

If me, then I put the calendar inside the form, using s5 xl12. I could not see the year when I open the calendar. And if you touch everywhere or near the calendar in a page, the calendar always opens itself.

**Comment by DanielRuf** [comment]
@gusbemacbe see the handle (after @) in my comment. Regarding your issue, if it is not the same please open a new issue with more information.

**Comment by 17tlhon** [comment]
@DanielRuf I include a video see the original post.

**Comment by gusbemacbe** [comment]
I updated the latest commit, using terminal @Dogfalo solved the issue and I saw the moth and year now. It worked.

**Comment by Dogfalo** [comment]
The date and month will still change before any date has been selected, however now once a date has first been selected and either the month or year view is changed, the preview will not update until a new date has been selected
Fixed in befe826c45b07afe70c1b32bdce74ebf99161e59
