### ISSUE TITLE
.modal-trigger throwing "Cannot read property 'M_Modal' of null" Uncaught TypeError

### ISSUE THREAD

**Issue by zanozik** [Dogfalo/materialize#5007]
```html
<div id="modal" class="modal modal-fixed-footer"></div>
<a href="modal" class="modal-trigger">Open modal</a>
<script>
    $(document).ready(function() {
        $('#modal').modal();
    });
</script>
```

This will throw

```javascript
materialize.min.js:6 Uncaught TypeError: Cannot read property 'M_Modal' of null at HTMLDocument.value (materialize.min.js:6) 
value	@	materialize.min.js:6

```
and open a modal and execute all logic.

**This got broken in 0.100.0 and is still broken as of 0.100.1**

**Comment by Dogfalo** [comment]
You need to add a hash to the href 
https://codepen.io/Dogfalo/pen/qXWJQK

**Comment by AwaMelvine** [comment]
How about you programmatically trigger a click event on the Modal components trigger property. Like so:

```
<Modal
  trigger={<Button style={{ display: 'hidden' }} ref={button => this.modalButton = button}>MODAL</Button>}
>
  Lorem ipsum ...
</Modal>
```
Now anywhere in your component, you can programmatically click that hidden [trigger] button without needing to use jQuery. 
Like so:
`this.modalButton.click().`

This works perfect for me.
