### ISSUE TITLE
Input font size should be 16px on iPhone to prevent zoom-on-focus

### ISSUE THREAD

**Issue by daniel-nelson** [Dogfalo/materialize#5008]
## Expected Behavior
Focusing on a text input shouldn't change zoom.

## Current Behavior
Focusing on a text input on iPhone [changes the zoom](https://uxcellence.com/2014/01/15/quick-fix-increase-font-size-to-16px-to-fix-input-zoom).

## Possible Solution
Force text inputs to 16px on mobile devices, e.g.:

textarea,
input[type=text],
input[type=search],
input[type=number],
input[type=email],
input[type=password],
input[type=tel] {
  @media (max-width: 799px) {
    font-size: 16px !important;
  }
}

## Steps to Reproduce (for bugs)
1. Load http://materializecss.com/forms.html on iPhone (or xCode iPhone simulator)
2. Tap into one of the text fields to focus on it

## Context
Zooming turns the carefully crafted mobile layouts of Materialize into a sub-optimal experience. The user may not even notice that it has happened, so may continue interacting in the zoomed view. Or if the user does notice, then after every interaction with a text field, the user will need to pinch-zoom-out to restore the intended zoom.

**Comment by DanielRuf** [comment]
Not sure why it should be 16 on inputs and 14 / 14.5 or 16 on the body.

**Comment by DanielRuf** [comment]
Forcing it to 16px for all users of the framework is not a solution.

**Comment by flexbox** [comment]
`16px` on inputs is the only solution to fix the zoom issue on iOS. (There are plenty of articles about that)

Bootstrap had the same issue
https://github.com/twbs/bootstrap/issues/2159

I think it's one of the reasons why they moved default font-size from `14px` to `16px`
https://v4-alpha.getbootstrap.com/migration/

Maybe we can use another media query for this?

    @media screen and (-webkit-min-device-pixel-ratio:0)

**Comment by Dogfalo** [comment]
Fixed in c25dfe2
