### ISSUE TITLE
Modal stopped working after updating

### ISSUE THREAD

**Issue by InventivetalentDev** [Dogfalo/materialize#5009]
## Expected Behavior
I'm expecting the modal to open properly, just like it did before. Without receiving any errors.

## Current Behavior

I'm using [angular-modal-service](https://github.com/dwmkerr/angular-modal-service) to create dynamic modals, which worked absolutely fine in version 0.99.0. I now updated to version 0.100.1 and suddenly it no longer opens and I get the following error:
```
TypeError: Cannot read property 'open' of undefined
    at HTMLDivElement.<anonymous> (materialize.min.js:6)
    at Function.each (jquery-3.2.1.min.js:2)
    at r.fn.init.each (jquery-3.2.1.min.js:2)
    at r.fn.init.t.fn.modal (materialize.min.js:6)
    ...
```

## Steps to Reproduce (for bugs)

1. Update to version 0.100.1
2. Try to run the same code to open a modal as in version 0.99.0  

**Codepens**:
v0.99.0 (working): https://codepen.io/inventivetalent/pen/Xarwxa?editors=1111 
v0.100.1 (not working): https://codepen.io/inventivetalent/pen/QMLRBj?editors=1111

## Your Environment

* Version used: 0.100.1
* Browser Name and version: Chrome 58.0.3029.110
* Operating System and version (desktop or mobile): Windows 10

**Comment by Dogfalo** [comment]
We need better reproduction steps. Provide a codepen that cleanly shows this problem. Because the website is using 0.100.1 and is using the same open modal code that 0.99.0 used and is working.

**Comment by InventivetalentDev** [comment]
Working Codepen for version 0.99.0: https://codepen.io/inventivetalent/pen/Xarwxa?editors=1111 

Codepen for version 0.100.1 which stopped working: https://codepen.io/inventivetalent/pen/QMLRBj?editors=1111

**Comment by InventivetalentDev** [comment]
Since you've added the 'thirdparty' label: I'm pretty sure this is nothing to do with the angular-modal-service (etc.), since I only updated materialize. The modal service also only uses existing functions, and the `open` method still has to be called manually.

**Comment by InventivetalentDev** [comment]
Okay, got it to work by first calling `modal()` and then `modal("open")` 
after initializing it.  

But I still feel like this shouldn't be necessary.

**Comment by Dogfalo** [comment]
This is intended. First initialize the component before expecting to call any of its functions.

**Comment by InventivetalentDev** [comment]
Then it would be nice to update the documentation to make this more obvious (especially since it wasn't necessary before). It currently only states the separate initialization required for href-triggers.

**Comment by dicoka** [comment]
I had the problem, simple code with a button and jQuery Plugin Initialization (like in documentation example) stopped working after update from v0.99.0 to v0.100.1

**Comment by Thanood** [comment]
To be fair, it *is* documented in the release notes..
https://github.com/Dogfalo/materialize/releases/tag/v0.100.0
