### ISSUE TITLE
Date picker broken on Android phone

### ISSUE THREAD

**Issue by CoDEmanX** [Dogfalo/materialize#501]
On my Nexus 5, Android 5.0.1, the date picker displays like this:

![screenshot_2015-01-21-13-45-39](https://cloud.githubusercontent.com/assets/1309249/5836776/9a5916fe-a179-11e4-9239-ca306f16f03c.png)

Days go top to bottom instead of left to right. The circle that indicates the selected date is obviously broken.

A minor UX issue: the dialog doesn't fully fit the screen, I can scroll it like 10px up and down.

Compared to Android, there's no way to scroll the months vertically or to pick a year directly. On the other hand, I really like that you can reset to "today" and clear the date within the dialog.

**Comment by Dogfalo** [comment]
Fixed in 792e079eb2393e7ad00cf0d22520790dfc6a4d67
