### ISSUE TITLE
Clicking on link for modal scroll to top of site

### ISSUE THREAD

**Issue by Adit1313** [Dogfalo/materialize#5011]
I am making a website where I want to display a table in a modal. I have a link to open up a modal and display a table with data.

Now when I click on the link rather than opening the modal my browser instead scroll to the top of the webpage.

**Comment by DanielRuf** [comment]
Please provide a codepen wgich shows this issue.

**Comment by Dogfalo** [comment]
Try using a `<button>` instead of an `<a>` tag so you do not inherit other default browser functionality
