### ISSUE TITLE
Including Materialize in my project

### ISSUE THREAD

**Issue by AsenCME** [Dogfalo/materialize#5013]
OK so here's the deal!
I downloaded an HTML template online and I tried to integrate it into my Vue.JS project. My App.vue file is where I include all libraries so that I can use in them in my web application. The matter here is that the template I acquired is using bootstrap. I wanted to include to materialize for the tooptips and toast and other such awesome JS things (they really are amazing, you've done a good job guys!) I included it in my App.vue file, it said that it required jQuery and Hammer.js so I npm istalled them and now what happens is quite confusing to me. All the other javascript libraries I have are being ignored and it keeps throwing errors such as "$(...).something is not a function". On top of that the Materialize function still don't work as intended. Here is my App.vue file:
```
<script>
import './assets/css/bootstrap.css'
import './assets/css/animate.css'
import './assets/css/flexslider.css'
import './assets/css/icomoon.css'
import './assets/css/style.css'
import './assets/css/button.css'
import './assets/css/font-awesome.css'

import './assets/js/jquery.min.js'
import './assets/js/jquery.easing.1.3.js'
import './assets/js/bootstrap.min.js'
import './assets/js/jquery.waypoints.min.js'
import './assets/js/jquery.flexslider-min.js'
import './assets/js/main.js'
// import './assets/js/materialize.js'

import changeColorMixin from './mixins/changeColorMixin'
import Firebase from 'firebase'
import './firebaseApp'


export default {
  data(){
    return{
    }
  },
  methods:{
    changeColor: changeColorMixin
  },
  mounted(){
    Firebase.auth().onAuthStateChanged(function(user){
      console.log(user);
    });
    this.changeColor();
  }
}
```

**Comment by Dogfalo** [comment]
Are you using webpack? Do you have a clonable version of this so I can investigate further?

**Comment by DanielRuf** [comment]
Shouldn't materialize come before the main.js file?

**Comment by AsenCME** [comment]
Yes. I am using webpack. Here is a GitHub repo a threw for this: https://github.com/AsenCME/Problematic-Project

A for the place it should be included, I've tried it everywhere.

**Comment by Dogfalo** [comment]
@AsenCME Can you try this new file here? I've made some changes that should fix the problem.
[materialize.zip](https://github.com/Dogfalo/materialize/files/1168550/materialize.zip)

**Comment by Dogfalo** [comment]
I took a look at the github repo you linked, it I don't think Materialize is causing those errors, even with materialzie commented out. Your project is throwing errors.

**Comment by AsenCME** [comment]
@Dogfalo Way less errors now. Only issue now, which is a new one, is that it marks velocity as undefined! If I comment out the conflicting line of the code it will still say ".waypoint is not a function"
![image](https://user-images.githubusercontent.com/18069689/28523938-3b4ff2d8-7087-11e7-8baf-c41794ccc23f.png)

**Comment by Dogfalo** [comment]
Were you able to resolve the problem?
