### ISSUE TITLE
collapsible's programmatic 'open' behaves like a toggle

### ISSUE THREAD

**Issue by hushaohan** [Dogfalo/materialize#5014]
## Expected Behavior

For a collapsible, the programmatic open

`$('.collapsible').collapsible('open', 0);`

should just open it. I.e., if the collapsible was originally closed, it should be open after the call; if it was already open, it should stay open after the call.

## Current Behavior

The call currently behaves like a toggle, i.e., open -> closed, closed -> open. Here's a codepen link:

[https://codepen.io/anon/pen/RZwWeW](https://codepen.io/anon/pen/RZwWeW)

Notice that the 'close' call

`$('.collapsible').collapsible('close', 0);`

Behaves as expected (i.e., does not toggle).

**Comment by Dogfalo** [comment]
Agreed, this is currently being fixed / is fixed over on 85daa7c2e1e108c45540c65b9dc6c863731a9e06
