### ISSUE TITLE
Badges appearing wrong in tables when not paired with text

### ISSUE THREAD

**Issue by Nev3rGiveUp** [Dogfalo/materialize#5018]
## ...
While I understand that I may be using the badges how they are not supposed to work,  I think this change will only improve the awesome project that you guys work on. The only reason that I'm taking my time submitting that issue is that I really liked the framework. Thank you, keep up the good work.
## Expected Behavior

How it should be: https://prnt.sc/fzl55v

http://materializecss.com/badges.html

## Current Behavior

This is how badges are currently handled in tables: https://prnt.sc/fzl3do

### Solution one:
Materialize.css should detect if the badge is used alone in the parent tag or paired with text. If not paired, it should not have the float right and the margin-left properties, also, it should have a display: inline-block propery.

### Solution two:
Give us a class that will do all the above , just an option if using Badges standalone. 

## Your Environment

* Version used: v0.100.1
* Browser Name and version: Opera Last version
* Operating System and version (desktop or mobile): Windows 10 Pro
* Link to your project (if appropriate):

**Comment by DanielRuf** [comment]
Can you provide a codepen?

**Comment by Nev3rGiveUp** [comment]
Of course, here you are: https://codepen.io/pavelst/pen/QMwEbj

**Comment by acburst** [comment]
Fixed in 8467547f
