### ISSUE TITLE
chip.add event not fired on dynamic chip creation

### ISSUE THREAD

**Issue by Smialkowski** [Dogfalo/materialize#5019]
Hi,

I am using custom ajax autocomplete to dynamically create chips and noticed that 'chip.add' event is not fired on chip creation. 'Select' and 'delete' events work as expected. I have made a simple test case, which is basically an input for chip tag text, a buton to add the chip and a div for chips. Expected behaviour is 'chip.add' event triggered on 'Add chip' buton click.

[https://jsfiddle.net/gL52rb0k/21/](https://jsfiddle.net/gL52rb0k/21/)
[https://codepen.io/anon/pen/dzPGQp](https://codepen.io/anon/pen/dzPGQp)

IE 11.0.9600.18665
Chrome 59.0.3071.115

**Comment by Maqsyo** [comment]
Cant' open your fiddle

**Comment by Smelkopski** [comment]
jsfiddle is up again, at least for me. Added codepen as backup :)

**Comment by Thanood** [comment]
@Smelkopski You're essentially reinitialising the `chips` control and thus overwriting the chip's data (and events).
There's certainly a kind of `.add` method missing to change the chips in code. You could raise the event with a click on the button manually, though.

**Comment by developeranirudhprabhu** [comment]
@Smialkowski See if this helps
https://codepen.io/prabhuanirudh/pen/PObxrP

It is a slight modification of your code which does the job as expected.

**Comment by Smialkowski** [comment]
@developeranirudhprabhu nope, no 'chip.add' alert for me. Does it work for you?

**Comment by developeranirudhprabhu** [comment]
The chip.add event wont be triggered. I Just showed an alternative for same. I will check if v1 has added support for it.

**Comment by Dogfalo** [comment]
This is fixed in v1-dev
