### ISSUE TITLE
Datepicker onSet removes functionality month arrows

### ISSUE THREAD

**Issue by FangioD** [Dogfalo/materialize#5020]
## Problem
When you add custom onSet behaviour, the arrows next to month and year do not work anymore.

## Expected Behavior
If you click on the arrows, the month changes.
 * left arrow, previous month
 * right arrow, next month

## Current Behavior
If you click on the arrows left or right, the datepicker moves to the date of today, when you click on it again, nothing happens.

## Steps to Reproduce (for bugs)
` $('.datepicker').pickadate({    
      format: 'mmmm yyyy',         
      selectMonths: true,    
      selectYears: 15,       
      today: 'Today',            
      clear: 'Clear',             
      close: 'Ok',                
      onSet: function (arg) {                
        if (arg.highlight) {               
          var selectedMonth = parseInt(arg.highlight[1]);             
          var selectedYear = arg.highlight[0];              
          var selectedDate = arg.highlight[2];       
          var $input = $('.datepicker').pickadate();         
          var picker = $input.pickadate('picker');       
          picker.set('select', [selectedYear, selectedMonth, selectedDate, {format: 'yyyy/mm/dd'}]);     
        }      
      }      
    });`

## Context
Trying to make an monthpicker with year, so the onSet method, sets the value immediately even if you didn't select a day. 

## Your Environment
I use the above code in Angular 4 component with JQuery in ngOnInit.
Bug on newest versions of Chrome and Firefox

**Comment by Dogfalo** [comment]
```JavaScript
onSet: function (arg) {
                     if (arg.highlight) {
                         var selectedMonth = parseInt(arg.highlight[1]);
                         var selectedYear = arg.highlight[0];
                         var selectedDate = arg.highlight[2];
                         var $input = $('.datepicker').pickadate();
                         var picker = $input.pickadate('picker');
                         picker.set('select', [selectedYear, selectedMonth, selectedDate, {format: 'yyyy/mm/dd'}]);
                     }
                 }
```
You're reinitializing it inside onSet and that's why it's breaking

**Comment by FangioD** [comment]
Are you guys planning to upgrade the api with a monthpicker?
