### ISSUE TITLE
Hoverable class not working properly with striped tables 

### ISSUE THREAD

**Issue by DanLaizer** [Dogfalo/materialize#5021]
## Expected Behavior
I want to be able to add the "hoverable" class to a table row in a table with the "striped" class. I expect the shadow produced by the "hoverable" class to appear the same for all table rows. 

## Current Behavior
When adding the hoverable class to a table row in a table with the "striped" class the box shadow from hoverable is not working correctly on every other table row element. It appears that that the positioning of the box shadow is behind the sibling row element. The issue did not appear in firefox, but it is appearing in the most recent version of chrome. 

## Steps to Reproduce 
1. Use Google Chrome
2. Create a table with with the "striped" class
3. Add three or more table rows with the "hoverable" class
4. Try hovering over a table row and keep an eye on bottom shadow (issue appears on every other table row) 

attempt at a plunker live example: https://plnkr.co/edit/pxV1C0msohak4m0c6jhd?p=preview

## Your Environment
* Version used: v0.99.0
* Browser Name and version: Google Chrome  Version 59.0.3071.115  (64-bit)
* Operating System and version (desktop or mobile):Windows 10 Desktop (64-bit)

Please let me know if you need any more information. Thank you!

**Comment by Dogfalo** [comment]
You still have to work with z-indexes to make hoverable work in this particular scenario.
The `.hoverable` class only adds a box-shadow and transition to it, nothing else

**Comment by DanLaizer** [comment]
if this is an issue with z-indexes why would it be only effecting alternating rows? Also the issue is only occurs when i add the class "striped" to the table.

**Comment by Dogfalo** [comment]
because the white rows here have a transparent background

**Comment by DanLaizer** [comment]
Ahh ok. Thanks!
