### ISSUE TITLE
Add new and missing tests

### ISSUE THREAD

**Issue by tomscholz** [Dogfalo/materialize#5023]
We want to provide new and more tests for our components. If you want to help, check out our [jasmine testing guide][1]. If you have any questions or feedback, don't hesitate to use the comment function ;) 

Theses components are lacking any tests:
- [ ] Carousel
- [ ] Slider
- [ ] Breadcrumb
- [ ] Pagination
- [ ] SideNav
- [ ] FeatureDiscovery
- [ ] Pushpin
- [ ] Forms
  - [ ] DatePicker
  - [ ] TimePicker
  - [ ] Checkboxes
  - [ ] Switches
  - [ ] Input fields

[...]

[1]: https://github.com/Dogfalo/materialize/blob/master/CONTRIBUTING.md#jasmine-testing-guide

**Comment by storm1er** [comment]
@tomscholz I'll do some, but since this is from July, is it up to date ?
I'm checking sources & PR . . .
