### ISSUE TITLE
Webpack import Materialize object

### ISSUE THREAD

**Issue by Denly** [Dogfalo/materialize#5026]
Hi I have struggle to import Materialize properly for a long time. Now it works with jQuery, but I still cant import the Materialize global object or window.Materialize. How can I do it? If we can have an official tutorial for webpack will be great (it's why I post here. Looks a lot ppl struggle too). Thank you!

Here is my setting:

in webpack
```
new webpack.ProvidePlugin({
      $: 'materialize-css/node_modules/jquery/dist/jquery',
      jQuery: 'materialize-css/node_modules/jquery/dist/jquery',
      'window.$': 'materialize-css/node_modules/jquery/dist/jquery',
      'window.jQuery': 'materialize-css/node_modules/jquery/dist/jquery',
      "Hammer": "hammerjs/hammer",
      Materialize: 'materialize-css/dist/js/materialize.js',
      "window.Materialize": 'materialize-css/dist/js/materialize.js',
    }),
```

In my index.js

```
import 'materialize-css/dist/css/materialize.css';
import 'materialize-css/dist/js/materialize.js'

```

**Comment by Dogfalo** [comment]
See #5013

**Comment by Denly** [comment]
Thank you. What version it'll be. Replacing file doesn't seem legit.

**Comment by Dogfalo** [comment]
Replacing the file is a temporary solution that will help us determine if the fix is working. If it is, then we will add it to the next release.

**Comment by isabisa** [comment]
@Dogfalo I have this exact same issue and replacing the file worked for me (after disabling eslint for that file). Would appreciate it being included in the next release!

**Comment by Dogfalo** [comment]
Great to hear, thanks for reporting it.

**Comment by G-J** [comment]
@isabisa I'm still having problems with this. This is my current setup:
In `webpack.config.js`:
```javascript
new webpack.ProvidePlugin({
    $: 'jquery',
    jQuery: 'jquery',
    'window.jQuery': 'jquery'
}),
```
And in my main js file:
```javascript
require('../../node_modules/materialize-css/bin/materialize');

$(document).ready(function() {
    $('.modal').modal();
});
```
But I am still getting the error: `$(...).modal is not a function`

How did you get it to work exactly?

**Comment by Dogfalo** [comment]
Try something like this
```javascript
require('materialize-css');


$( document ).ready(function() {
  console.log(Materialize);
  Materialize.toast('hi', 5000);
  $('#modal1').modal();
});
```

**Comment by G-J** [comment]
@Dogfalo I updated the version to v0.100.2. 
The Materialize object is known and the toast works. 
The modal however still gives the error `$(...).modal is not a function`. Same goes for the tabs. Do I need to configure this in the webpack.config?

**Comment by Armour** [comment]
Hi @G-J I have maintained my [boilerplate](https://github.com/Armour/express-webpack-react-redux-typescript-boilerplate) for using materialize-css with webpack and more (like react, typescript, hot module reload), and there is a [working exampe](https://express-react-typescript.herokuapp.com/), wonder if that will help you in some way :)

**Comment by dev-aitch** [comment]
@Dogfalo Thanks worked for me 👍, will update here If I get more issues.
otherwise enjoying the shit out of it :-D ;-)
