### ISSUE TITLE
Timepicker doesn't have fade-in/fade-out animation

### ISSUE THREAD

**Issue by scote** [Dogfalo/materialize#5027]
On Materialize form page, the timepicker doesn't have a fade-in/fade-out animation.

## Expected Behavior
Fade-in/Fade-out animation like Datepciker

## Current Behavior
No animation when a timepicker is opened or closed.

## Steps to Reproduce (for bugs)
1. Go to http://materializecss.com/forms.html
2. Click on timepicker demo.

## Your Environment
* Version used: 0.100.1
* Browser Name and version: Chrome 59
* Operating System and version (desktop or mobile): Windows 10

**Comment by Dogfalo** [comment]
Fixed in v1. Timepicker now leverages Modal
