### ISSUE TITLE
Modals are broken

### ISSUE THREAD

**Issue by bert-w** [Dogfalo/materialize#5029]
Modals dont open anymore since 0.100.1.

See JSfiddles (both should open the modal):
- 0.99.0 https://jsfiddle.net/fb6u00ts/
- 0.100.1 https://jsfiddle.net/xhrhn23d/

### Exception
```
jQuery.Deferred exception: this.M_Modal is undefined t.fn.modal/<@https://cdnjs.cloudflare.com/ajax/libs/materialize/0.100.1/js/materialize.min.js:6:67443
each@https://cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.min.js:2:2713
each@https://cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.min.js:2:1001
t.fn.modal@https://cdnjs.cloudflare.com/ajax/libs/materialize/0.100.1/js/materialize.min.js:6:67422
window.onload/<@https://fiddle.jshell.net/_display/:59:2
j@https://cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.min.js:2:29997
g/</k<@https://cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.min.js:2:30313
 undefined
```

**Comment by tomscholz** [comment]
https://jsfiddle.net/vd1xpyd7/
See: https://github.com/Dogfalo/materialize/blob/master/CHANGELOG.md#v01000-july-19th

**Comment by bert-w** [comment]
The changelog is too terse, im using code from the docs, see:

http://materializecss.com/modals.html#!

**Comment by tomscholz** [comment]
We are aware of that and we will update the documentation soon. https://github.com/Dogfalo/materialize/issues/5009

**Comment by bert-w** [comment]
thank you.

Forgive me for reporting issues that are apparently already reported, but I dont expect a release when the docs havent been updated accordingly yet
