### ISSUE TITLE
Datepicker select fields are not visible when it's enclosed in an .input-field container

### ISSUE THREAD

**Issue by ignisf** [Dogfalo/materialize#5030]
## Expected Behavior
The Datepicker should display drop-down menus for selecting a year and a month.

## Current Behavior
The fields for selecting year and month are hidden and not clickable.

## Possible Solution
Make the selector for [these](https://github.com/Dogfalo/materialize/commit/dbdd869bc929cf124757eb22d3694dc5d746c7e0) styles more specific as to not include the Datepicker selects.

## Steps to Reproduce (for bugs)
See https://jsfiddle.net/tkxku3sa/

## Context
Was trying to use the Datepicker via the materialize-form gem with Ruby on Rails.

## Your Environment

* Version used: 0.100.1
* Browser Name and version: Firefox 54
* Operating System and version (desktop or mobile): Arch Linux on Desktop
* Link to your project (if appropriate): Not published

**Comment by gusbemacbe** [comment]
Here is my last comment, check: https://github.com/Dogfalo/materialize/issues/5028

**Comment by Dogfalo** [comment]
Yep, we will fix this in an upcoming bugfix release

**Comment by PierreCapo** [comment]
Hey guys, any news about this ? It seems there is still the bug in the current bersion ?
By the way, thanks a lot for  all your good job :)

**Comment by Dogfalo** [comment]
It is fixed in the latest version
https://codepen.io/Dogfalo/pen/rzXmWo
