### ISSUE TITLE
Transition is missing on text area and some form labels when the they are <unfocused> in 0.100.1

### ISSUE THREAD

**Issue by pingshunhuangalex** [Dogfalo/materialize#5032]
http://materializecss.com/forms.html

I noticed recent updates break things very frequently... Looks like you guys have serious CSS conflict issues.

**Comment by DanielRuf** [comment]
I see the transitions (the labels) when I tab through the fields. Can you describe in detail what's broken and how it should be?

**Comment by fega** [comment]
@DanielRuf 
try clicking in the textarea component and after that clicking elsewhere, that change from active to normal hasn't an appropriate animation, I just tested in chrome latest.

**Comment by DanielRuf** [comment]
@fega you mean the animated label and color? I still see the animation. Tested on Chrome mobile 58.

Please test it in Firefox and other browsers. This should still work.

**Comment by fega** [comment]
> @fega you mean the animated label and color? I still see the animation. Tested on Chrome mobile 58.

yep, here I see the issue in both mobile and desktop, you'll see that the text size change properly but the position change in a "pop"

**Comment by DanielRuf** [comment]
Did you test in Chrome 58? Still not reproducible here.

**Comment by fega** [comment]
chrome 60 in desktop, 59 in mobile.

are you sure?, I didn't notice it at the first time :sweat_smile:

**Comment by DanielRuf** [comment]
I just see some jump in the textarea but it has transition on all properties.

Tested on Chrome 59 on MacOS. But still no issues with the normal inputs.

**Comment by pingshunhuangalex** [comment]
I'm using Chrome 60 (previously 59) on desktop. @fega described it pretty clear. It's the movement of the label when the input is being unfocused. Just on the official website, you can see a clear jump on the transition comparing let's say forms in `input field` section at the top of the page and the `textarea` sections.

If you still can't tell the difference, then maybe never mind? Currently, I'm overrideing all labels in the textarea with `transition: all .3s`, which solves the issue.

**Comment by DanielRuf** [comment]
This might be the problem:

https://github.com/Dogfalo/materialize/blob/72f2e944b9a600b8df49dcd0e2e404c48689aae8/dist/css/materialize.css#L6366-L6367

**Comment by pingshunhuangalex** [comment]
I'm just confused why every time an update is pushed, these fundamental components would get broken... It's not like you guys are adding more features to those building blocks or switching to a new style...

**Comment by DanielRuf** [comment]
Take a look at https://github.com/Dogfalo/materialize/commit/81ab9ba3654fdbaca88d0f18a1a7f7998424e725

**Comment by acburst** [comment]
We are constantly fixing bugs on all of our fundamental components. With a large framework, even small tweaks to a component can have a lot of unforeseen consequences. Unfortunately automated testing for visual things like this is very hard to do. We do have a label rework that should make these components more stable in the future.

**Comment by DanielRuf** [comment]
I guess we need some regression testing or similar as part of the CI workflow.

**Comment by DanielRuf** [comment]
Probably the transition should be on more values, why not use it on all properties?

**Comment by DanielRuf** [comment]
`transition: transform .2s ...` should include the transition for the top value and probably some more ;-)

**Comment by acburst** [comment]
We do need help writing jasmine tests. It's a pretty big priority to expand our tests while we are refactoring our plugins

**Comment by Dogfalo** [comment]
Fixed in v1-dev by a rework of the helper text system
