### ISSUE TITLE
default input without type="text" floating label not working

### ISSUE THREAD

**Issue by rafael-atrixdevelopers** [Dogfalo/materialize#5033]
In the 2017.2 version of PhpStorm it suggests to me to remove the type = "text", but when I do this the floating label does not work

![floating label error](https://user-images.githubusercontent.com/30170023/28674109-d1b0d8f2-72ba-11e7-899f-002389a60e82.PNG)

Using MaterializeCSS Version 0.100.1
Browser: Chrome 59

![floating label error 2](https://user-images.githubusercontent.com/30170023/28674177-0a34e452-72bb-11e7-8b43-50f55100dc70.PNG)

![floating label error 3](https://user-images.githubusercontent.com/30170023/28674223-2ccab4c4-72bb-11e7-8728-716ea14562c5.png)

type="text" Is the default when not specified

**Comment by DanielRuf** [comment]
An input should have the (correct) type.
Relying on browser defaults is not a good solution.

This means we have somewhere in the Sass a rule for `type=text` but missed the missing type declaration.

**Comment by DanielRuf** [comment]
@fega should we cover this case in the Sass code?
