### ISSUE TITLE
Input Character count (data-length) grid error

### ISSUE THREAD

**Issue by rafael-atrixdevelopers** [Dogfalo/materialize#5035]
Before:
![grid l4 design](https://user-images.githubusercontent.com/30170023/28687860-4aa64aaa-72e6-11e7-98dd-5374c5b7ec26.PNG)

![grid l4 code](https://user-images.githubusercontent.com/30170023/28687893-657f14e2-72e6-11e7-894e-905dd4ce747d.PNG)

After I Add data-length="10"

![grid l4 design error](https://user-images.githubusercontent.com/30170023/28687914-76d4aae0-72e6-11e7-8d96-9af9f6be02fb.PNG)

![grid l4 code error](https://user-images.githubusercontent.com/30170023/28687917-790a95a4-72e6-11e7-86e3-451a2aed9d4f.PNG)

MaterializeCSS Version: 0.100.1
Browser: Chrome 59

**Comment by fega** [comment]
@rafael-atrixdevelopers 
I think that a best approach is separate the "data de nacimiento" input field in a different `.row` tag

**Comment by DanielRuf** [comment]
You should create a new row after the third l4 element.

Please provide a codepen.
