### ISSUE TITLE
Pagination does not work for me

### ISSUE THREAD

**Issue by fdenzer** [Dogfalo/materialize#5036]
The list of sub-pages does not work for me on the official demo sites:

1. [Materialized](http://demo.geekslabs.com/materialize/v2.3/layout03/ui-pagination.html) 

2. [Materialize](http://materializecss.com/pagination.html)(css)

Neither navigation bar changes the _active_ page number (or content). Both websites use `materialize css`.

For an example, just click one of these links and confirm or prove me wrong please. Changing from Chrome 60 to Firefox 54 did not help. No content blockers are installed on Firefox.

Any ideas, if or why the framework has is erroneous?
Which browser plugin or corporate network feature could cause this?
Also posted to:
https://stackoverflow.com/questions/45352789/pagination-of-custom-materialize-projects-does-not-work-for-me

**Comment by tomscholz** [comment]
The pagination is css only. It does not come with any functionality.

**Comment by fdenzer** [comment]
ty
