### ISSUE TITLE
personalize the font

### ISSUE THREAD

**Issue by Nek-** [Dogfalo/materialize#5038]
## Expected Behavior

I should be able to choose a font.

## Current Behavior
Roboto is hardcoded.

## Possible Solution
Add a variable with font name!

**Comment by tomscholz** [comment]
#4797 #5004

**Comment by Nek-** [comment]
@tomscholz can you reopen the issue please? My point is not about issues you mentioned.

You can externalize roboto if you want, but I want to use another font, which doesn't mean the same. I just want a variable I can override with the name of the font.

**Comment by tomscholz** [comment]
See #4620

**Comment by Nek-** [comment]
That's the fix to this issue indeed!

**Comment by Dogfalo** [comment]
Roboto has been removed in v1-dev and a variable called $font-stack has been added
