### ISSUE TITLE
Cannot read property 'M_Modal' of null

### ISSUE THREAD

**Issue by gewisser** [Dogfalo/materialize#5039]
## youtube:
https://youtu.be/GM1g4upv_No

## codepen
https://codepen.io/anon/pen/PKPddN
(Click Plus button)

**Comment by tomscholz** [comment]
Please make sure to fill out the ISSUE_TEMLATE and read out CONTRIBUTING GUIDELINES!

**Comment by Dogfalo** [comment]
Your codepen is missing the href tag, see the modal documentation and code example
