### ISSUE TITLE
Using Table in view, can't make the table fill the view height - bottom of page is "blocked" off.

### ISSUE THREAD

**Issue by bmcgonag** [Dogfalo/materialize#5040]
## Expected Behavior

I have a simple div with no preset height restriction, and have added a simple table with classes 'striped' and 'highlight'

`<table class="striped highlight">`

The table should go to or past the bottom of the screen until a height restriction is imposed on it.

## Current Behavior

The table will not go to the bottom of the screen.  I have checked to see if any element exists below it, but nothing exists in the view.  I have no classes set on the table to limit the height of it.

## Steps to Reproduce (for bugs)

1. Using meteor 1.5, and Materialize 0.98.2, add a table to a view,
2. the table should have 8 or more rows,
3. the table should start about 1/3 of the way down the view

## Context

I would like the table to fill the rest of the viewable height. Currently it leaves unwanted white space in the view.

## Your Environment

* Version used: 0.98.2
* Browser Name and version: Chrome latest, Safari Latest
* Operating System and version (desktop or mobile):  Mac OS Sierra
* Link to your project (if appropriate): No Link available at this time.

**Comment by bmcgonag** [comment]
Just as an FYI - I set the view inside a container div <div class="container">, and the bottom of the view is still blocked in the browser, but no element exists there.  I can turn on the developer tools, and hover that blank area, and the whole page is highlighted except that area, which says the dev tools think the mouse is at some parent main element at that point like <body>. 

I also noticed, that with a 4 column table, the width of the table looks to be 100%, but the columns don't fill the full width, it's like a ghost column is out to the right.  Once I added the container div, it did get rid of the extra column space to the right, but the height is still an issue.

**Comment by Dogfalo** [comment]
Please create a codepen for this

**Comment by bmcgonag** [comment]
I'm closing this because I'm an idiot!  OMG - it's so embarrassing I hate to post it, but I must.  I set the height on a completely different view with a table, and erased the class specifier when I did it, so all tbody tags were getting the height limited...same for width on td...ugh!  

So sorry.
