### ISSUE TITLE
Error display radio button

### ISSUE THREAD

**Issue by EnziinSystem** [Dogfalo/materialize#5041]
I use radio button in Rails 5.

In the page view, radio button error as attach image.

Thanks.
![p1](https://user-images.githubusercontent.com/25495466/28742150-fcbfdb9e-7452-11e7-82e0-cd4419d8b362.jpg)
![p2](https://user-images.githubusercontent.com/25495466/28742151-fcc10352-7452-11e7-90e3-a71745cb6378.jpg)

**Comment by Dogfalo** [comment]
Please don't ignore the issue template.
