### ISSUE TITLE
Forms Broken (Am I doing something wrong?)

### ISSUE THREAD

**Issue by jakeob28** [Dogfalo/materialize#5044]
I am pretty new to Materialize, and I just copied the code for forms to try to make my own. (The code I used can be found [here](https://goo.gl/Gjyzq2). It looked right at first, but when I started to type, the label transitions didn't work, and they just stayed inside the text field. This is running on a WAMP server with default configurations, and nothing changed other than the pages in the www directory.

A screenshot:
![image](https://user-images.githubusercontent.com/15847045/28755073-9cadca12-7520-11e7-8381-26834410222f.png)
Info:
Windows 7, 64 bit
WAMP server 3.0.6
Materialize v 0.99.0

I can provide any other needed information.

**Comment by tomscholz** [comment]
You forgot to include jQuery aswell as the materialize.js. Next time try asking in [our gitter channel](https://gitter.im/Dogfalo/materialize).
