### ISSUE TITLE
Why we not implement using html5 data-* to initial and options js plugins?

### ISSUE THREAD

**Issue by zinzinday** [Dogfalo/materialize#5048]
+ data-toggle="pluginName" . To auto initial pluginName replacement for the initialization $(selector).pluginName(settings)
+ data-option-name="value" for plugin settings pluginName.settings.[option-name]=value

**Comment by DanielRuf** [comment]
Autoinitializing components is planned to be removed in 1.0.0.

We may add this to override default values but it is currently not on the roadmap to 1.0.0. Let's keep the API stable so far and come to this back at a later time.

**Comment by zinzinday** [comment]
Yep 1+)
Please implement assignees, labels, milestone to this repo for disscounts.

**Comment by DanielRuf** [comment]
We already have these, take a look at the other issues.
