### ISSUE TITLE
<b> tag inside card-panel display wrong vertical-align

### ISSUE THREAD

**Issue by zigy** [Dogfalo/materialize#505]
My code:
```
<div class="card-panel">
    <i class="mdi-alert-warning left"></i>
    <i class="mdi-alert-warning right"></i>
    <span>Pro funkčnost webu je nutné <b>povolit JavaScript</b>.<br> Zde jsou <a href="http://www.enable-javascript.com/cz/" target="_blank"> instrukce jak povolit JavaScript ve Vašem webovém prohlížeči</a>.</span>
</div>
```

<b> tag have bad vertical-align (in CSS: span b)...

How fix it?
```
change: vertical-align: middle;
to: vertical-align: baseline;
```

**Comment by Dogfalo** [comment]
Can you screenshot the problem you're encountering? Everything seems fine ![](http://puu.sh/ePioj/3c9874ace0.png)

**Comment by zigy** [comment]
![x](https://cloud.githubusercontent.com/assets/4948416/5840849/c5bd0b42-a198-11e4-8e21-83bd224d76bc.jpg)

**Comment by acburst** [comment]
We don't have any stylings on any b tag. Where are you seeing this?

**Comment by zigy** [comment]
http://diskforyou.com/ on main page. I have apply fix on b (vertical-align: baseline;)
```<b>vývoje a ALPHA testování</b>```

**Comment by Dogfalo** [comment]
We looked into the issue, this is a style that you added in your main.css
