### ISSUE TITLE
[BUG?] Window sometimes flickers on long select close

### ISSUE THREAD

**Issue by markonose** [Dogfalo/materialize#5056]
Hi.

I've a select element with quite a few option elements. When the select dropdown is closed it flickers sometimes. I've narrowed it down to to the hideDropDown function

```
      function hideDropdown() {
        // Check for simultaneous focus and click events.
        isFocused = false;
        activates.fadeOut(curr_options.outDuration);//.promise().done(function(){activates.css('max-height', '');});
        activates.removeClass('active');
        origin.removeClass('active');
        $(document).unbind('click.'+ activates.attr('id'));
        setTimeout(function() { activates.css('max-height', ''); }, curr_options.outDuration);
      }
```

More specifically

`        setTimeout(function() { activates.css('max-height', ''); }, curr_options.outDuration);`

Above you can see a commented out promise. If i comment the setTimeOut and replace it with a promise, I haven't seen the same issue. My question is why not use a promise or a call back function on the fadeOut in the first place? The whole point is to set max-height to none after the animation ends right?

**Comment by Dogfalo** [comment]
Select now stays within the bounds of the screen so this will no longer happen.
