### ISSUE TITLE
Modals doesn't close properly in IE11

### ISSUE THREAD

**Issue by creatingo** [Dogfalo/materialize#5057]
## Current Behavior
I've tested modals using IE11 and while modals open fine, they don't seem to close properly.
Body style - overflow:hidden - is not removed. JS error cause that page is completely broken.

## Steps to Reproduce (for bugs)
1. Check http://materializecss.com/modals.html in IE11
2. Open and close a modal

## Environment
* Version used: 0.100.1
* Browser Name and version: Internet Explorer 11
* Operating System and version (desktop or mobile): Windows7 desktop

**Comment by markonose** [comment]
Hi. Can you try version v0.97.7 in your own environment? I've used that version for a project at my internship and if I open the website it doesn't break when you close the modal. But I was also told to include

`<script src="https://cdnjs.cloudflare.com/ajax/libs/es6-promise/4.0.5/es6-promise.min.js"></script>`

it's included sometime after materialize.js

**Comment by Dogfalo** [comment]
Please search issues. #5017
