### ISSUE TITLE
Can't install materialize with `meteor add materialize:materialize`

### ISSUE THREAD

**Issue by stinnett-casey** [Dogfalo/materialize#5060]
According to the documentation [here](http://materializecss.com/getting-started.html#third-party-options), to add Materialize to Meteor all you have to do is run `meteor add materialize:materialize`, which has worked for me previously. 

I just ran that command today and it gave me the following error:
<img width="627" alt="screen shot 2017-08-02 at 10 22 51 am" src="https://user-images.githubusercontent.com/3304283/28883711-9ad00946-776c-11e7-86e6-045954f67dfb.png">

I even tried it for version 0.99.0 and got the same error. Am I doing something wrong or is this a bug?

**Comment by Dogfalo** [comment]
Duplicate #5010
