### ISSUE TITLE
Chips autocomplete

### ISSUE THREAD

**Issue by guilhermemaranhao** [Dogfalo/materialize#5067]
Hello everybody,

I am using multi value materialize chips input and I have a specific issue concerning the addition of a new chip when there is already an element in my autocomplete data which contains the word I need to insert. For instance, my autocomplete data contains the phrase "Chilli Beans" and I need to insert a new chip that is just "Chilli". 
How can I force to dispatch de 'chip.add' event when the user presses ENTER after typing "Chilli"? The problem is that the autocomplete keeps enabled and I can't to select the word "Chilli".
Is it somehow possible?

Thank you very much,

Guilherme

**Comment by DanielRuf** [comment]
> How can I force to dispatch de 'chip.add' event when the user presses ENTER after typing "Chilli"

Did you try adding a keypress event handler which triggers the `chips.add` event when they keycode is thw one of `enter`?

**Comment by guilhermemaranhao** [comment]
Hi, 

Thanks for the answer. Yes, I've tried adding a keypress event handler, but I couldn't trigger the `chips.add` event. How can I do it? I'm new to js....

Thank you again

**Comment by penguoir** [comment]
Could you share a codepen so we could further understand your problem?

**Comment by guilhermemaranhao** [comment]
Thank you, guys! I did it here!

**Comment by guilhermemaranhao** [comment]
Yes! I did the `chips.add` event trigger and it works.

Thanks

**Comment by CharlieIGG** [comment]
I'm going to have to bump this. I have the same issue, however when I call
```
$('.chips').trigger('chip.add');
```
Nothing happens. Can you share your solution @guilhermemaranhao ?
