### ISSUE TITLE
Chips and Textarea Problem

### ISSUE THREAD

**Issue by emin-karadag** [Dogfalo/materialize#5073]
Hello everybody,

When I use materializecss chips and textarea together, the writings I write into the textarea are automatically written into chips and the chips disappear?
Interesting to me?

![untitled-1](https://user-images.githubusercontent.com/7556164/28995235-941572b2-79ec-11e7-94fd-c21401892ad5.png)

**Comment by DanielRuf** [comment]
Please provide a codepen so we can reproduce and test this.
