### ISSUE TITLE
Velocity error when toasting

### ISSUE THREAD

**Issue by turtlegood** [Dogfalo/materialize#5074]
When using `Materialize.toast`, I get the error:

> Velocity: First argument ([object HTMLDivElement]) was not a property map, a known action, or a registered redirect. Aborting.

How I import(build) the js:

In order to reduce the size of materialize js file, I make a customized build. That means, I download the source, edit the `gruntfile.js`, and then run such tasks:

    grunt.registerTask(
      'default',[
        'lint',
        'sass:expanded',
        'postcss:expanded',
        'concat:dist',
        'babel:dist',
        'clean:temp',
      ]
    );

So I get get a `materialize.js` file.
Then I just import it in `app.js` like 

    import './libs/materialize.js';

I am using `WebPack` with `Laravel` (therefore, the `Laravel Mix` which is a webpack wrapper for laravel). It will bundle my files into manifest.js, vendor.js and app.js. 

By the way, if I just don't customize the materialize.js, but download your version in your website, then the problem still remains!

Seems to be almost the same as #4615 , but that issue has not been solved yet either...

Any help will be appreciated!

**Comment by Dogfalo** [comment]
What line in materialize.js is it coming from?

**Comment by turtlegood** [comment]
@Dogfalo 

Wow you guys are so fast!!

Here is the part of code in `velocity` of materialize.js. The line I have a arrow is giving me error.

					H = j.delay || 0;return j.backwards === !0 && (g = f.extend(!0, [], g).reverse()), f.each(g, function (e, t) {
					parseFloat(j.stagger) ? j.delay = H + parseFloat(j.stagger) * e : m.isFunction(j.stagger) && (j.delay = H + j.stagger.call(t, e, w)), j.drag && (j.duration = parseFloat(E) || (/^(callout|transition)/.test(y) ? 1e3 : h), j.duration = Math.max(j.duration * (j.backwards ? 1 - e / w : (e + 1) / w), .75 * j.duration, 200)), b.Redirects[y].call(t, t, j || {}, e, w, g, k.promise ? k : a);
				}), e();
    ----------->}var N = "Velocity: First argument (" + y + ") was not a property map, a known action, or a registered redirect. Aborting.";return k.promise ? k.rejecter(new Error(N)) : console.log(N), e();
		}A = "start";}var L = { lastParent: null, lastPosition: null, lastFontSize: null, lastPercentToPxWidth: null, lastPercentToPxHeight: null, lastEmToPx: null, remToPx: null, vwToPx: null, vhToPx: null },
	R = [];f.each(g, function (e, t) {
	m.isNode(t) && n.call(t);

**Comment by Dogfalo** [comment]
Do you have a repo I can take a look at? This isn't quite enough information for me to really understand the problem.

**Comment by turtlegood** [comment]
@Dogfalo Sorry it is a private project... I will extract the relevant files to a new public project and give it to you. Plz wait for a minute. Thanks for your help!

**Comment by turtlegood** [comment]
@Dogfalo I finished extracting it. 

The zip: [here](https://drive.google.com/open?id=0B4QIOq5fpoq4QkxaRHhwYzBpUVk)

How to use it:
1. `npm install`
2. `npm run dev`
3. visit the website. (you should let your apache `directory` points to `/MaterializeIssueExample/public`, as this is a routine of laravel project.
4. In chrome console input `Materialize.toast("hi", 1000)` then you can see the problem yourself.

I have found where the problem lies:
In `app.js`, if you commented this line, then materialize works well.

    window.$ = window.jquery = window.jQuery = $;

However, I don't know how my other components will work well without this line...

Thanks for your help!

**Comment by turtlegood** [comment]
Solved.
Change the line `window.$ = window.jquery = window.jQuery = $;` to `window.$ = $;`
However I still don't know why it works.

**Comment by queenvictoria** [comment]
I also have this error. However I'm compiling with rollup and others and my import statement looks like this.
```javascript
  var jQuery = require('jquery');
```

No amount of `window.$ = $` or `window.$ = jQuery` or similar approaches seem to fix the issue. Do we know what the underlying cause is? PS I can solve it by editing `materialize.js` and changing the two instances of `Vel(newToast, {...` to `$(newToast).velocity(...`

**Comment by Dogfalo** [comment]
@queenvictoria What version are you using?

**Comment by queenvictoria** [comment]
My bower says ^0.97.8 but I'll check when I'm back at my desk.

**Comment by queenvictoria** [comment]
Ok yes it was that version. I've upgraded to `0.100.2`. I still get the same error. The toast appears but doesn't animate in nor does it dismiss after the timeout. And I get the error on instantiation, on the timed dismissal, and at the manual dismissal.

```
Velocity: First argument ([object HTMLDivElement]) was not a property map, a known action, or a registered redirect. Aborting.
```
