### ISSUE TITLE
Badges in Collapsibles

### ISSUE THREAD

**Issue by max918** [Dogfalo/materialize#5077]
## Expected Behavior

The badges in collapsibles should position on right, that is no problem on version 0.99.0 but 0.100.1

## Current Behavior
The Badges in Collapsibles is now on left.

## Steps to Reproduce (for bugs)
bug also affected document site.
[document site](http://materializecss.com/badges.html#collapsible)

## Your Environment
* Version used: 0.100.1
* Browser Name and version: Chrome 60.0.3112.90
* Operating System and version (desktop or mobile): Desktop
* Link to your project (if appropriate):

**Comment by jeroenqui** [comment]
See https://github.com/Dogfalo/materialize/issues/5016
