### ISSUE TITLE
Date and Time Picker doesn't work in mobile.

### ISSUE THREAD

**Issue by chanyap92** [Dogfalo/materialize#5079]
chrome version 59,
how to reproduce problem: just go to Form section in materializecss.com and try the date and time picker.
nothing come out after click

**Comment by Dogfalo** [comment]
What phone OS?

**Comment by jlebonzec** [comment]
Both the Date and Time pickers work for me on Firefox 54 and Chrome 59 on Android 5.1

**Comment by chanyap92** [comment]
OnePlus 3, Android 7.1.1, Chrome 59..
