### ISSUE TITLE
Chips input (Basic css is done, add more javascript functionality)

### ISSUE THREAD

**Issue by lukaspijak** [Dogfalo/materialize#508]
![tags_input](https://cloud.githubusercontent.com/assets/2571714/5852660/ae300f10-a21a-11e4-9faa-b6697a69e96a.png)
![tags_input_1](https://cloud.githubusercontent.com/assets/2571714/5852661/ae312828-a21a-11e4-825d-2b25e1c2809d.png)

**Comment by CoDEmanX** [comment]
They are called "Chips" in the Material design docs:
http://www.google.com/design/spec/components/chips.html

**Comment by willemx** [comment]
+1!

**Comment by Sithdown** [comment]
+1

**Comment by Kestanous** [comment]
:+1:

**Comment by ecarreras** [comment]
:+1:

**Comment by lukaspijak** [comment]
https://github.com/B1naryStudio/md-chips

**Comment by patrickgordon** [comment]
:+1: Would absolutely love this.

**Comment by tankerkiller125** [comment]
:+1:

**Comment by boustanihani** [comment]
:+1:

**Comment by kevohagan** [comment]
+1

**Comment by patrickgordon** [comment]
Any interest in this @Dogfalo

**Comment by truenorth** [comment]
Some custom CSS could probably be added to [selectize.js](https://github.com/brianreavis/selectize.js) for this. I took a stab at it for some very basic "chips" in one of my apps

see:  https://github.com/yahoo/druid-dashboard/blob/0b022d0d55c05ace3123593cbf05f279f4e5b31d/app/styles/components/md-selectize.scss

**Comment by jasonhargrove** [comment]
+1 chips / tags

**Comment by patrickgordon** [comment]
Highly suggest checking out this library:
http://henrychavez.github.io/materialize-tags/examples/

Works perfectly for us on our materializecss + rails app

**Comment by acburst** [comment]
No functionality at this point, but i've started a basic css structure in 19b2219b21fe138280de9bb0cfdec8e3f1eadeb3

**Comment by nelreina** [comment]
+1

**Comment by SuperDJ** [comment]
Maybe a nice adition would be to add the images aswell. And to add something like: [images in select](https://github.com/Dogfalo/materialize/pull/2198) and or [autocomplete](https://github.com/Dogfalo/materialize/pull/2253) to get something similar to:
![image](https://cloud.githubusercontent.com/assets/6484766/10999559/0c9b325e-849d-11e5-812e-f41f7175c2fa.png)

**Comment by skeltoras** [comment]
+1

**Comment by markmooibroek** [comment]
Would love to have this in materialize! I currently have made something myself, but its not nearly as beautifull as the components you guys make =) 

<img width="393" alt="screen shot 2015-12-22 at 07 50 00" src="https://cloud.githubusercontent.com/assets/1412238/11949550/cb8476ba-a880-11e5-9c15-cc64d85a79b5.png">

**Comment by sushain97** [comment]
+1

**Comment by acburst** [comment]
Merged in chips plugin here 1fdf905514966bad6b07a73a3b7a84fab91aaac0.

**Comment by iNilo** [comment]
Thanks for this!
