### ISSUE TITLE
Modal: IE 11 - After close scrolling is not possible

### ISSUE THREAD

**Issue by pharindoko** [Dogfalo/materialize#5084]
Hey,

I tried the new master with the latest fixes today.
Following behaviour happens after last fix in IE.
When I open and close a modal => 
The controls definitely work - but scrolling is not possible anymore.

Do you have a short term solution ?

**Comment by Dogfalo** [comment]
Fixed in 157f8728481fe8d759e07e7e6c99ae5597fe4955
