### ISSUE TITLE
dropdown alignment issues

### ISSUE THREAD

**Issue by bnayagrawal** [Dogfalo/materialize#5085]
The alignment works when hover is set true, but doesn't when it is set false.

**Comment by penguoir** [comment]
I can't reproduce this issue. Could you share a codepen that would show the problem?

**Comment by bnayagrawal** [comment]
Try playing with alignment and hover options.
https://codepen.io/bnayagrawal/pen/wqJxbz

**Comment by Dogfalo** [comment]
Fixed in v1-dev
