### ISSUE TITLE
autocomplete events fire twice

### ISSUE THREAD

**Issue by jhefreyzz** [Dogfalo/materialize#5086]
Is it normal for the autocomplete to fire twice on trigger change.
I made changes to   $input.trigger('change'); and set it to   $input.trigger('change', [count]);

upon selecting an element it returns the following:
first: index (ex. 0, 1, 2)
second: undefined 

When you search for "es" see what the console.log output
codepen: https://codepen.io/nullstrike/pen/ZJKaNX

**Comment by penguoir** [comment]
Could you share a codepen to illustrate your problem?

**Comment by DanielRuf** [comment]
Not reproducible in Chrome 59 and 60 on mobile devices,

**Comment by jhefreyzz** [comment]
would this be sort of bug? 
i just want to get the number of result per query

**Comment by DanielRuf** [comment]
Where did you make your change related to `trigger()`? Please do not change core files of Materialize.

I'm not sure what you do there. Do you reinvent the autocomplete component?

Please test with jQuery 3.2.1 and Materialize 0.100.1.

**Comment by jhefreyzz** [comment]
I don't make any changes in the materialize core files.  I didn't reinvent the autocomplete component you can see that on the codepen.

**Comment by miklblitz** [comment]
android 6 firefox 53, strange behavior in autocomplete:  first time typing letters - nothing happen, tap second time - show autocomplete result

**Comment by DanielRuf** [comment]
@miklblitz this sounds like an othet issue. Please create a new issue.

**Comment by developeranirudhprabhu** [comment]
@jhefreyzz Can you provide steps to reproduce the problem. Even with the code pen you provided I'm not able to figure out the exact problem

**Comment by developeranirudhprabhu** [comment]
@jhefreyzz Can you provide steps to reproduce the problem. Even with the code pen you provided I'm not able to figure out the exact problem

**Comment by developeranirudhprabhu** [comment]
I think it is reproducible. I tried the codepen provided. When i click on the autocomplete result shown. I see the result triggered twice. However when i use the keyboard its not reproducible. Attaching the screenshot for reference
![screen shot 2017-11-19 at 11 43 29 am](https://user-images.githubusercontent.com/10301434/32987940-1d4a20ca-cd1f-11e7-84ba-f93471b4aab3.png)

**Comment by acburst** [comment]
Autocomplete has been rewritten for v1.0.0 alpha. If this issue is still a problem, then make a new issue for the latest version.
