### ISSUE TITLE
Can't use anchors of nested tabs

### ISSUE THREAD

**Issue by markstalker** [Dogfalo/materialize#5087]
Hello! I use tabs in tabs. If I use anchor on external tab, it is working.  But If I try to use anchor on nested tab, it doesn't work. (Anchor on nested tab works only if external tab have "active" class)
Is it possible to fix this?
Thank you in advance.

**Comment by penguoir** [comment]
How are you nesting your tabs? What "doesn't work"? Could you share a codepen to illustrate your problem?

Thanks!

**Comment by markstalker** [comment]
@penguoir, https://codepen.io/anon/pen/ZJedRJ
1. Try adding anchor '#control' to end of link. Reload page. Will open '#control' tab.
2. Try replace '#control' on '#invite'. After page reloading, will open default tab with class="active" - #table

**Comment by penguoir** [comment]
@markstalker thanks for the codepen. I'll work on this tomorrow and give you an answer then.

**Comment by markstalker** [comment]
@penguoir thanks too.

**Comment by penguoir** [comment]
The problem is with Materialize tabs. When a tab is activated through the hash URL, it doesn't activate the parent tab so you can't see it. I've written some code to solve this problem and I hope this helps:
```js
// With nested tabs, activate the parent tab if the nested tab is active.
if ($active.length > 0) {
  var id = $(this).parent().attr('id');
  $('a[href="#'+id+'"]').trigger('click');
}
```

I'm opening a pull request now.

**Comment by markstalker** [comment]
@penguoir thank you, its work. 
But I have a some bug: [screenshot](http://i.imgur.com/l5P86mH.png).
If I use anchor on nested tab, horizontal scrollbar appears.

**Comment by penguoir** [comment]
I think that might have something to do with your CSS.

I haven't tested this but try using something like:
```css
.tabs {
  overflox-x: hidden;
}
```
Glad I could help!

**Comment by markstalker** [comment]
Yes, it work. (I already found this solution, but forgot to write) Thank you.
There is one bug with the width of the indicator: [Screenshot](http://i.imgur.com/KYQIjmo.png)

**Comment by penguoir** [comment]
Been looking for a solution for a while and I can't find one. I'm not sure if I'm missing something...
