### ISSUE TITLE
Re-writing some components with css grid feature.

### ISSUE THREAD

**Issue by penguoir** [Dogfalo/materialize#5091]
With the new [`grid`](https://css-tricks.com/snippets/css/complete-guide-grid/) feature added, many components could be rewritten such as cards, collections, navbar, pagination, collapsible, dropdowns, models, side nav, tabs, grid and more.

Using the grid feature would make these components more accurate and much less prone to breaking. Not to mention their CSS would be much easier to maintain and to add new features too.

Also, the CSS grid feature means it's much easier to have responsive components (using`grid-template-areas`)

Once the grid feature has wider support amongst browsers (although it has [good support](https://caniuse.com/#search=grid) right now) and is production-ready, should the grid feature be implemented into Materialize?

**Comment by DanielRuf** [comment]
At least we would still need fallbacks for browsers that do not support it.

**Comment by Dogfalo** [comment]
Maybe in the future, but it's too early right now
