### ISSUE TITLE
Mobile Tabs Scaling is Broken

### ISSUE THREAD

**Issue by Cathal02** [Dogfalo/materialize#5093]
When switching tabs on mobile the scale completely breaks, either they get squished beside each other or they expand further than the page should prohibit them
## Expected Behavior

Tab scale should stay the same when switching

## Current Behavior

Instead of the tab length staying the same it changes to either to long or too short. This only happens when using responsive meta tags for mobile.

## Possible Solution

When adding overflow-x: hidden; to tabs-fixed width this fixes the issue. Apparently this was already fixed but I still got this issue.

## Steps to Reproduce (for bugs)

1. Include two tabs make them fixed-width
2. Add mobile resonpsive meta tags
3. Check for Desktop functioncality which works
4. Switch to mobile and change tabs
6. They will begin to change scale and ruin page layout

## Context

My website layout is completely ruined on mobile as it starts to push things off center

## Your Environment

* Version used: Latest
* Browser Name and version: Safari & Latest
* Operating System and version (desktop or mobile) Mobile:
* Link to your project (if appropriate):

**Comment by DanielRuf** [comment]
Please provide a codepen which shows the described issue.
