### ISSUE TITLE
Waves too sensitives at scroll

### ISSUE THREAD

**Issue by Lolincolc** [Dogfalo/materialize#5095]
## Expected Behavior

Waves on button should not react when user is scrolling

## Current Behavior

Waves are too sensitives. When user scroll, waves gets activated. That bug do not happen in the original Waves library (http://fian.my.id/Waves/)

## Possible Solution

Maybe update Waves library (currently integrated in version v0.6.0) to the lastest version: 0.7.4.
## Steps to Reproduce (for bugs)

Here is a comparison video between the original library and the Materialize integration: https://goo.gl/photos/eDgpny7cqjFTVbhs7

## Your Environment

* Version used: v0.100.1
* Browser Name and version: Chrome (Mobile-Android) 59.0.3071.125
* Operating System and version (desktop or mobile): Android

**Comment by DanielRuf** [comment]
0.7.5 is the latest version. We may have to port our changes when we update as the integrated version has bugfixes and some other changes so we have to rebase this part / file.

**Comment by tomscholz** [comment]
Duplicate of #4027
