### ISSUE TITLE
IE11: textarea - not possible to use newline

### ISSUE THREAD

**Issue by pharindoko** [Dogfalo/materialize#5096]
I tested the demo with the latest master.
1. Write something into the testarea
2. Press "enter" key
==> In IE 11 no newline will be created.

I already experimented how this can be changed in the code but wasn`t successful....

forms.js - line 187 an event call happens when a change occurs.... body keydown ...

````
        
$('body').on('keyup keydown autoresize', text_area_selector, function(e) {

            if (e.which == 13) {
                this.innerHTML = this.innerHTML + '\n';
                this.innerText = this.innerText + '\n';
            }

            textareaAutoResize($(this));
        });

````

Someone has a clue how to fix this ?

**Comment by Kronen** [comment]
Just use "\r\n" for new lines?

**Comment by pharindoko** [comment]
I checked it again.
The whole issue occurs only in the materialize css demo.
http://materializecss.com/forms.html

If I try it in my application it works without problems.
Seems like an additional javascript at the end of the forms.html in the demo changes the textarea.
