### ISSUE TITLE
Sidenav closing/opening on window resizing doesn't call the 'onClose' or 'onOpen' option

### ISSUE THREAD

**Issue by SMWLucasO** [Dogfalo/materialize#5097]
When you create a sidenav you can add the options 'onClose' or 'onOpen' but when you resize the browser, it will automatically open/close, however this does not call these functions. It should execute it because it is either getting closed or opened.

**How i came across this issue**
My sidenav is automatically opened at the beginnning (would be nice if you can specify that as a sidenav option too to avoid a sliding-open effect to keep it open at the beginnning)

I have a div that holds content that needs to be pushed depending on if the sidenav is open or not, so that is why i am using the onOpen and onClose events of the sidenav, this is how i found out about this issue.

**My sidenav code**
        
      $(document).ready(function() {

        let sideNav = $('.side');

        sideNav.sideNav({
            menuWidth: 300, // Default is 300
            edge: 'left', // Choose the horizontal origin
            closeOnClick: false, // Closes side-nav on <a> clicks, useful for Angular/Meteor
            draggable: false, // Choose whether you can drag to open on touch screens,
            onOpen: function(el) {
                if($(window).width() >= 992) {
                    $('#displayer').css('marginLeft', 340);
                }
                }, // A function to be called when sideNav is opened
            onClose: function(el) {
                if($(window).width() >= 992) {
                    $('#displayer').css('marginLeft', 40);
                }
                }, // A function to be called when sideNav is closed
        });

        $('body').resize(function() {
           if( $('body').css('overflow') === 'hidden' ) {
               $('#displayer').css('marginLeft', 40);
           } else {
               $('#displayer').css('marginLeft', 340);
           }
        });

        if($(window).width() >= 992) {
            sideNav.sideNav('show'); // open it at the start
        }
    });

PS: would really be great, once again, if you can specify if it is open at the beginning or not.

**Comment by Dogfalo** [comment]
Fixed in v1-dev
