### ISSUE TITLE
sideNav Not Working with RequireJS using CDN dependencies

### ISSUE THREAD

**Issue by thaddeusdiamond-smartercloud** [Dogfalo/materialize#5098]
Using the SideNav component on Chrome 59.0. Simple Spring application, with a single app.js file included using RequireJS in HTML.  The HTML tag is:

```
<script data-main="/assets/js/app" src="https://cdnjs.cloudflare.com/ajax/libs/require.js/2.3.4/require.min.js" integrity="sha256-Ae2Vz/4ePdIu6ZyI/5ZGsYnb+m0JlOmKPjt6XZ9JJkA=" crossorigin="anonymous"></script>
```

The javascript code in `app.js` is as follows:

```
require.config({
    'paths': {
        'hammerjs': '//cdnjs.cloudflare.com/ajax/libs/hammer.js/2.0.8/hammer.min',
        'jquery': '//cdnjs.cloudflare.com/ajax/libs/jquery/2.2.4/jquery.min',
        'jquery-hammerjs': '//bowercdn.net/c/jquery-hammerjs-1.0.11/jquery.hammer-full.min',
        'materialize': '//cdnjs.cloudflare.com/ajax/libs/materialize/0.100.1/js/materialize.min',
        'velocity': '//cdnjs.cloudflare.com/ajax/libs/velocity/1.5.0/velocity.min'
    },
    'shim': {
        'materialize': {
            deps: ['hammerjs', 'jquery', 'jquery-hammerjs', 'velocity']
        }
    }
});

require(['jquery', 'materialize'], function($) {

    // NOTE: Behavior is the same with or without this line
    window.jQuery = window.$;

    // NOTE: Behavior is the same whether call is wrapped in the jQuery DOM function or not
    $(function() {

        /**
         * The following section initializes the sideNav for all mobile pages.  See the MaterializeCSS Framework
         * documentation for more information.
         */
        $('.button-collapse').sideNav();

    });

});
```

The page loads and the sideNav element works, but when I click the shaded area to close the sideNav, the shading goes away but the sideNav element stays fixed at left.  I can see the transition occurring in Chrome Inspector, but it instantly resets to `translateX(0px)`. Using a non-minified version of materialize.js does not change the issue.

In the console I see the message:

```
Velocity is already loaded. You may be needlessly importing Velocity again; note that Materialize includes Velocity.
```

Though that may be a red herring.

If I remove the velocity dependency from my RequireJS shim, I get the following error message in console:

```
materialize.min.js:6 Uncaught TypeError: o.velocity is not a function
    at HTMLAnchorElement.<anonymous> (materialize.min.js:6)
    at HTMLAnchorElement.dispatch (jquery.min.js:3)
    at HTMLAnchorElement.r.handle (jquery.min.js:3)
```

For the un-minified version of materialize, the error is:

```
materialize.js:4037 Uncaught TypeError: menu.velocity is not a function
    at HTMLAnchorElement.<anonymous> (materialize.js:4037)
    at HTMLAnchorElement.dispatch (jquery.min.js:3)
    at HTMLAnchorElement.r.handle (jquery.min.js:3)
```

So it seems like a catch-22 of loading just once somehow.

Closed issues referencing RequireJS issues seem to not touch on how to use RequireJS with CDNs.  I don't see a CDN hosting smaller individual modules for Materialize, so just importing the sideNav.js file is not an option.

**Comment by thaddeusdiamond-smartercloud** [comment]
Works when v1.2.3 of Velocity is used instead of 1.5.0.  Would still be curious to hear why the decision was made to package VelocityJS inside of min.js.  Would prefer that dependency to be broken out explicitly.

**Comment by brycesenz** [comment]
I would like to re-open this, as it's still an issue.  Manually fixing it inside of my `materialize.js` or `materialize.min.js` file isn't really a sustainable solution.
