### ISSUE TITLE
Select is not updating its value

### ISSUE THREAD

**Issue by pingshunhuangalex** [Dogfalo/materialize#5102]
Need to quickly build a select form only to find the component is not responding to change event at all. Is there a way to pass the selected value or I'm using it the wrong way?

I'm using 0.100.1

http://materializecss.com/forms.html

**Comment by tomscholz** [comment]
The issue template is meant to be filled out!

**Comment by pingshunhuangalex** [comment]
Sorry, I did it in a very sloppy way cuz there are already half a dozen issues open on this topic and some of them are quite old. Just do this to grab your attention. Thanks.

**Comment by tomscholz** [comment]
Duplicate of #4562
Use the search function to avoid duplicate issues!
