### ISSUE TITLE
Material Box should enlarge the image to natural size when clicked.

### ISSUE THREAD

**Issue by bnayagrawal** [Dogfalo/materialize#5103]
# A feature request
(**not a bug** as per documentation)

If we are using thumbnail images and have set image max-(height/width), then when the thumbnail image is clicked, material box is showing the image without enlarging it. So there should be an option to show the image in its natural size when clicked.

**Comment by tomscholz** [comment]
Possible duplicate #3164 ?

**Comment by bnayagrawal** [comment]
I think it is. But is there a workaround for this problem?

**Comment by tomscholz** [comment]
Not as far as i know. Please you the other issue for discussions and possible solutions

**Comment by apudiu** [comment]
Who designed it? he/she should have common sense that we shouldn't enlarge an image too much, I used 200 px image as thumbnail (when not enlarged) & when it enlarges on 4k display.... 

U got it... how nice that would be.. 

Hope this issue will be fixed ASAP

Thanks

**Comment by hudsantos** [comment]
Closed issue but not sure if this is already fixed.

Anyway, this answer provides a related workaround https://stackoverflow.com/questions/51389307/lightbox-onclick-change-src-then-change-back/65556831#65556831
