### ISSUE TITLE
Toasts on mobile phone shouldn't use rounded corners

### ISSUE THREAD

**Issue by CoDEmanX** [Dogfalo/materialize#511]
On Android 5, there's no rounding for toasts which are displayed at the bottom of the screen (above the back / home / overview buttons):

![screenshot_2015-01-21-22-00-12](https://cloud.githubusercontent.com/assets/1309249/5854369/56584420-a22d-11e4-91b5-6f61b4b8c130.png)

In MaterializeCSS, there's a slight rounding, which leads to very few pixels that show through from the background - which looks really odd especially if it's white:

![screenshot_2015-01-22-11-58-06](https://cloud.githubusercontent.com/assets/1309249/5854450/1a4281b6-a22e-11e4-981c-3cae7701b940.png)

**Comment by Dogfalo** [comment]
fixed in b2acb8b93683627e5bd9779b6b55160183f554d2
