### ISSUE TITLE
IE11: parallax - jitter effect

### ISSUE THREAD

**Issue by pharindoko** [Dogfalo/materialize#5110]
Hey,

sorry for not using the template. I updated it...

**Expected Behavior**
Parallax effect with smooth scrolling effect like in Chrome Browser.

Current Behavior
When scrolling a site that uses parallax effect for images a jitter effect happens on the images in IE 11

**Possible Solution**
So far I wasn`t able to find a good fix for this issue to make a pull request.

**Steps to Reproduce (for bugs)**
http://materializecss.com/parallax-demo.html

**Context**
Trying to use Materialize CSS in an enterprise (IE 11 needed)

**Your Environment**

Version used:
Current master / V100.1

Browser Name and version:
Internet Explorer 11

Operating System and version (desktop or mobile):
Windows 7, 64Bit,

**Comment by tomscholz** [comment]
The issue template is meant to be filled out!

**Comment by Dogfalo** [comment]
Not seeing the issue in my testing here.

**Comment by ClosetMonkey** [comment]
Also happening in chrome 60.0.3112.116 on Android 5.1.1

**Comment by swapster** [comment]
Also happening in Microsoft Edge 40.15063.0.0

**Comment by rille111** [comment]
Also seeing this, and now it's 2019. We paid for this and expect it to work.

**Comment by polishcode** [comment]
I experience that on windows 10 too, depending on browser (each latest version):
- edge, chrome, opera: jittery
- firefox: smooth

This depends on performance/appearance system setting:
properties of My Computer -> Advanced tab -> Perfomance/Settings...

When adjusted for best appearance all browsers (e, c, o, f) are more or less smooth.
When adjusted for best performance only firefox is smooth, the rest is jittery.
(when testing do restart browser after applying system changes)

Trying to figure out if scrolling can be smooth in all scenarios...

**Comment by polishcode** [comment]
Enabling smooth scrolling for chrome independently from system setting:
chrome://flags/
Smooth Scrolling -> Enabled
