### ISSUE TITLE
Hyperlink in anchor not working inside tabs of Sub View with HTML5 mode with hashPrefix(!)

### ISSUE THREAD

**Issue by rupakrockthecse100** [Dogfalo/materialize#5113]
The tab hyperlinks just changing the tabs but not rendering the sub view content when the hyperlink is clicked inside a sub view to navigate to another sub view.
From Main view it's working fine.
![image](https://user-images.githubusercontent.com/30334358/29318608-797ea752-81ee-11e7-9426-2cfbef2f315e.png)

**Comment by tomscholz** [comment]
Please use [the correct markup for markdown](https://guides.github.com/features/mastering-markdown/) and make sure to properly fill out the [issue template](https://github.com/Dogfalo/materialize/blob/master/.github/ISSUE_TEMPLATE.md)! Thanks.

**Comment by rupakrockthecse100** [comment]
Comment updated
