### ISSUE TITLE
Open modal using floating button

### ISSUE THREAD

**Issue by BrunoPace96** [Dogfalo/materialize#5114]
Current Behavior:
When I try to open the modal using floating button the modal doesn't open, but if I use a normal button like in the modals documentation the modal open.

Expected Behavior:
Modal open when click on floating button

Here is the Codepen with the two buttons:
https://codepen.io/anon/pen/xLPgwK

Version used: 0.100.1
Browser Name and version: Google Chrome  60.0.3112.90
Operating System and version (desktop or mobile): Windows 8.1 (desktop)

**Comment by Dogfalo** [comment]
Add `modal-trigger` class to button

**Comment by tomscholz** [comment]
https://codepen.io/anon/pen/mMqRQp?editors=1010
