### ISSUE TITLE
To switch slider between fullscreen and non-fullscreen 

### ISSUE THREAD

**Issue by Denly** [Dogfalo/materialize#5115]
I switch slider's mode between fullscreen and non-fullscreen by changing the class name, but looks different mode has different init function, so It cause rendering fail after switch. I have tried init again every time I switched, but It doesn't work too! How to fix it? Thank you.

p.s Hope to keep the index of photo user is viewing, so I can't have independent slider to show/hide

Thank you!

**Comment by DanielRuf** [comment]
Did you destroy and reinit the component?

Please provide a codepen.
