### ISSUE TITLE
How to modify data error in forms using jquery

### ISSUE THREAD

**Issue by peejay06** [Dogfalo/materialize#5116]
I want to programatically change and display different errors on my form
ex.
Login
for username input field there could be 3 errors
-Don't leave this empty
-Username not found
-No special characters allowed

How can I set it using jquery?

**Comment by peejay06** [comment]
` $(document).ready(function()
 {

	
 	$('#btn_login').click(function(event) {

 		var username = $('#username').val();
		var password = $('#password').val();

		if(String(username) == "" )
		{
			    
			    	$("error_username").attr('data-error','The name field is required');
			    	$("#username").addClass("invalid");
			    	$("#username").removeClass("valid");
			    	$("#username").focus();			
		}else
		{
			    $("#username").removeClass("invalid");
		 		$("#username").addClass("valid");
		}
 	});

 	

 });`

By the way I tried using the code above. It worked when I pressed the button, but when I click other input field the error message also disappeared.

**Comment by Dogfalo** [comment]
To change the error message, just modify the `data-error` attribute

**Comment by peejay06** [comment]
Hello sir @Dogfalo !

I was able to modify the data-error attribute on my javascript. The only problem is when I click another input field, the error message is gone too.

**Comment by peejay06** [comment]
https://youtu.be/I765WIsZtl4

^ 

Example of whats happening.
