### ISSUE TITLE
onOpen and onClose callbacks not fired on 'open' and 'close' programmatic methods use

### ISSUE THREAD

**Issue by Smialkowski** [Dogfalo/materialize#5118]
## Expected Behavior
onOpen and onClose callbacks fired on 'open' and 'close' programmatic methods use.

## Current Behavior
onOpen and onClose callbacks not fired on 'open' and 'close' programmatic methods use.

## Steps to Reproduce (for bugs)
https://jsfiddle.net/0e032cav/2/

1. Click 'Open Second' button - onOpen callback not fired
2. Click any collapsible - onOpen callback fired

## Context
Open collapsible based on ID passed from backend.

## Your Environment

* Version used: jquery 3.2.1, materialize 0.100.1
* Browser Name and version: IE11 11.0.9600.18665, Chrome 60.0.3112.90 (x64)
* Operating System and version (desktop or mobile): Windows 7 x64

**Comment by tomscholz** [comment]
The collapsible plugin has been refactored in the v1-dev branch. See https://github.com/Dogfalo/materialize/issues/5004
