### ISSUE TITLE
No automatically scroll in select 

### ISSUE THREAD

**Issue by yagami271** [Dogfalo/materialize#5120]
with version v0.97.6 when we have select with many option, we have like autocomplte who scroll in option items like here [auto scroll work](https://jsfiddle.net/yddvykfa/2/), but when i update to v0.100.1 the scroll didn't work like here [auto scroll not work](https://jsfiddle.net/jandwhwt/1/).

Plz help, it's a bug ? thank you

**Comment by acburst** [comment]
I'm sorry, I don't quite understand what the problem is. Are you talking about scrolling to the currently selected option? We changed the centering of it, but it should still work.

**Comment by yagami271** [comment]
yes, i talk about scrolling to the currently selected option when you write (like autocomplete) you can see i make 2 jsfiddle to show the probleme, 

thanks, sorry for my english

**Comment by tomscholz** [comment]
Not reproducible
