### ISSUE TITLE
wrong condition in materialize.js

### ISSUE THREAD

**Issue by mfemail8** [Dogfalo/materialize#5126]
wrong condition in materialize.js
if (object.is(':valid') && hasLength && len <= lenAttr || object.is(':valid') && !hasLength) {
should be
if ((object.is(':valid') && hasLength && len <= lenAttr) || (object.is(':valid') && !hasLength)) {

**Comment by DanielRuf** [comment]
Please check the current code, it is right: https://github.com/Dogfalo/materialize/blob/master/js/forms.js

**Comment by mfemail8** [comment]
Still wrong in dist, would you publish it to cdnjs.cloudflare.com, thanks  |

**Comment by DanielRuf** [comment]
I still see the right code with (() ...()), not sure what you mean. Did you try the latest release?

**Comment by DanielRuf** [comment]
Just as a sidenote, rhe dist file is automatically generated and && binds stronger than ||.

**Comment by DanielRuf** [comment]
See the precedence in the table https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Operator_Precedence
