### ISSUE TITLE
Modal overlay overlaps body vene when closed

### ISSUE THREAD

**Issue by shudhpandit** [Dogfalo/materialize#5127]
I was just cross checking compatibilty of this framework on sveral Browsers. Just found an Issue ono IE 11 (Version 11.0.10240.17443). I clicked to open a Modal, upon closing Modal is gone but its overlay is still there having "opacity:0;" and "display:block;"

![materialcss](https://user-images.githubusercontent.com/8871502/29447098-c1aefa9c-840d-11e7-8994-1483e19a3d0d.PNG)

**Comment by Dogfalo** [comment]
Fixed on master branch already
