### ISSUE TITLE
Max Chips

### ISSUE THREAD

**Issue by neutron92** [Dogfalo/materialize#5129]
Please how to define max number of chips tagged

![screenshot--2017-08-18-17-41-34](https://user-images.githubusercontent.com/6135555/29468515-7ff70a66-843c-11e7-991d-0d693f712955.png)

**Comment by Dogfalo** [comment]
Not currently supported

**Comment by allsyed** [comment]
I would be better if it is configurable via initialization object

**Comment by acburst** [comment]
Planning on adding this to Chips in v1.0.0

**Comment by acburst** [comment]
This feature was added as the limit option in our new chips plugin
