### ISSUE TITLE
problem with v0.95 dropdown menu collapse

### ISSUE THREAD

**Issue by KBoisvert** [Dogfalo/materialize#513]
With this version of css: Materialize v0.94.2 the dropdown menu works but I can't have fixed menu.

With this one : Materialize v0.95.0  the dropdown doesn't work at all
using: materialize.min.css   file
I've added the js line as mentionned :  $(".button-collapse").sideNav(); and works with 0.94

my HTML code:

		<section id="menu">
		    <nav>
			    <div class="nav-wrapper red darken-2">
					<ul id="nav-mobile" class="right side-nav">
						<li><a href="#accueil" class="scroll">ACCUEIL</a></li>
						<li><a href="#presentation" class="scroll">PRÉSENTATION</a></li>
						<li><a href="#portfolio" class="scroll">PORTFOLIO</a></li>
						<li><a href="#contact" class="scroll">CONTACT</a></li>
					</ul>
					<a class="button-collapse" href="#" data-activates="nav-mobile"><i class="mdi-navigation-menu black"></i></a>
			    </div>
		    </nav>
		</section>

version with fixed nav menu I add it there

		<section id="menu" class="navbar-fixed">

Any idea?

**Comment by Dogfalo** [comment]
It works for me when I tried your code.

**Comment by KBoisvert** [comment]
ok thanks, I'll try again
