### ISSUE TITLE
Tab swipeable div contracts when inserting an image

### ISSUE THREAD

**Issue by HC-Isma** [Dogfalo/materialize#5130]
Help please... !!
Tab swipeable does not accept to insert an image, at the moment of inserting the div it is contracted hiding everything.
I'm with version 0.99.0

**Comment by Dogfalo** [comment]
Please make a codepen illustrating your issue

**Comment by HC-Isma** [comment]
1).-

<ul id="tabs-swipe-demo" class="tabs">
    <li class="tab col s3"><a href="#test-swipe-1">Test 1</a></li>
    <li class="tab col s3"><a class="active" href="#test-swipe-2">Test 2</a></li>
  </ul>
  <div id="test-swipe-1" class="col s12 blue">
          <ul class="collection">
                 <li class="collection-item avatar">
                         <img src="/images/icons/error.png" alt="" class=" circle">
                          <span class="title">Title</span>
                           <p>First Line <br>
                             Second Line
                           </p>
                          <a href="#!" class="secondary-content"><i class="material-icons">grade</i></a>
                   </li>
            </ul>
</div>
  <div id="test-swipe-2" class="col s12 red">Test 2</div>
 2) .-
<ul id="tabs-swipe-demo" class="tabs">
    <li class="tab col s3"><a href="#test-swipe-1">Test 1</a></li>
    <li class="tab col s3"><a class="active" href="#test-swipe-2">Test 2</a></li>
  </ul>
<div id="test-swipe-1" class="col s12 blue">
    <img src="/images/icons/error.png" alt="" class=" ">
</div>
 <div id="test-swipe-2" class="col s12 red">Test 2</div>

**Comment by HC-Isma** [comment]
<ul id="tabs-swipe-demo" class="tabs">
    <li class="tab col s6 blue">
        <a href="#test-swipe-1">Test 1</a>
    </li>
    <li class="tab col s6"><a class="active" href="#test-swipe-2">Test2</a></li>
</ul>
<div id="test-swipe-1" class="col s12 blue test-swipe">
    <img src="/images/icons/error.png" alt="" class=" circle">
</div>
<div id="test-swipe-2" class="col s12 red test-swipe">
    hello
</div>

**Comment by HC-Isma** [comment]
![captura](https://user-images.githubusercontent.com/11790877/29490917-94cf46f0-8519-11e7-84cd-4a6abf0f5fb3.PNG)

**Comment by Dogfalo** [comment]
Please read the CONTRIBUTING.md and use the Codepen link

**Comment by HC-Isma** [comment]
`<ul id="tabs-swipe-demo" class="tabs">
    <li class="tab col s6 blue">
        <a href="#test-swipe-1">Test 1</a>
    </li>
    <li class="tab col s6"><a class="active" href="#test-swipe-2">Test2</a></li>
</ul>
<div id="test-swipe-1" class="col s12 blue test-swipe">
    <img src="/images/cars/toyota.jpg" alt="" class=" circle">
</div>
<div id="test-swipe-2" class="col s12 red test-swipe">
    hello
</div>`

**Comment by HC-Isma** [comment]
> <div>
    <ul id="tabs-swipe-demo" class="tabs">
        <li class="tab col s6 blue">
            <a href="#test-swipe-1">Test 1</a>
        </li>
        <li class="tab col s6"><a class="active" href="#test-swipe-2">Test2</a></li>
    </ul>
    <div id="test-swipe-1" class="col s12 blue test-swipe">
        <img src="/images/cars/toyota.jpg" alt="" class=" circle">
    </div>
    <div id="test-swipe-2" class="col s12 red test-swipe">
        hello
    </div>
</div>

**Comment by DanielRuf** [comment]
This is not a codepen.
