### ISSUE TITLE
Datepicker issue with keyboard in forms

### ISSUE THREAD

**Issue by bop10** [Dogfalo/materialize#5137]
Hey, i have a form with some inputs, one of them is a date picker.

The problem is using the form with the keyboard, when i use TAB to move between the inputs.
When i reach the datepicker, the datepicker displays as normal, but after selecting a date, i cant use the TAB again to keep moving inside the form (to the next input), is like i lost the focus on the input.

Example:

```
<input id="input_1" type="text">
<input id="input_2" type="text">
<input id="input_3" type="text" class="datepicker">
<input id="input_4" type="text">
```

Steps to reproduce the problem:

1. I can move between input_1 -> input_2 using TAB. 
2. Using TAB while input_2 is focused makes the datepicker display.
3. After selecting the date, i cant reach input_4 using TAB

**Comment by MaximBalaganskiy** [comment]
The reason is several dozen hidden elements which are all focusable. If you keep tabbing you'll reach your other controls. I tried setting `tabindex=-1` on the whole tree but it gets reset. Still looking for solution...

**Comment by erlike** [comment]
I found one solution for this. 

Add  $('.picker *').attr("tabindex","-1" )   to remove focus of whole tree:

  $('.datepicker').pickadate({
          selectMonths: true, 
          selectYears: 15,
          today: 'Today',
          clear: 'Clear',
          close: 'Ok',
          closeOnSelect: true
          onClose: function(){
            $('.picker *').attr("tabindex","-1" );
          }

**Comment by erlike** [comment]
You can use $('.picker__holder *')   instead of  $('.picker *')

To keep focus of the days when the calender is open:

onOpen: function() {
            $('.picker__day').attr("tabindex","0");
          }

**Comment by Dogfalo** [comment]
Fixed in v1-dev
