### ISSUE TITLE
Gap between dropdown button and dropdown content on Google Chrome if I set the dropdown button to `belowOrigin: true` and `hover: true` and zoom out to 67%

### ISSUE THREAD

**Issue by nratter** [Dogfalo/materialize#5138]
If I set the dropdown's options to `belowOrigin: true` and `hover: true`, and zoom out to 67% and refresh the page on Chrome, I see a big gap between the dropdown button and the dropdown content, which prevents me from dragging the cursor down to the dropdown content.

![image](https://user-images.githubusercontent.com/3020810/29574432-8d34a238-872f-11e7-963a-933466733166.png)

Any ideas?

Environment:
Chrome 60.0.3112.101 (have experienced this on various versions of Chrome)
OSX El Capitan
Materialize v0.100.1

**Comment by tomscholz** [comment]
Read the [CONTRIBUTING guidelines](https://github.com/Dogfalo/materialize/blob/master/CONTRIBUTING.md#bug-reports)!
> Isolate the problem — create a reduced test case using our Codepen template.

**Comment by Dogfalo** [comment]
Not seeing the issue: https://codepen.io/Dogfalo/pen/WEJLQO

**Comment by nratter** [comment]
I was able to fix this in my environment by setting `border-box: unset` on the enclosing tag.
