### ISSUE TITLE
TypeError: Cannot read property 'swing' of undefined

### ISSUE THREAD

**Issue by Denly** [Dogfalo/materialize#5139]
TypeError: Cannot read property 'swing' of undefined
(anonymous function)
node_modules/materialize-css/dist/js/materialize.js:42

```
  39 | })(function ($) {
  40 | 
  41 |   // Preserve the original jQuery "swing" easing as "jswing"
> 42 |   $.easing['jswing'] = $.easing['swing'];
  43 | 
  44 |   var pow = Math.pow,
  45 |       sqrt = Math.sqrt,

```

"jquery": "^3.2.1", "materialize-css": "^0.100.1",

```
new webpack.ProvidePlugin({
      $: "jquery",
      jQuery: "jquery",
      'window.jQuery': "jquery",
      'window.$': "jquery",
      "Hammer": "hammerjs/hammer",
      Materialize: 'materialize-css/dist/js/materialize.js',
      "window.Materialize": 'materialize-css/dist/js/materialize.js',
    }),

```

**Comment by Denly** [comment]
I fund I don't need to import by web pack.ProvidePlugin, just list the .js in index.js (entry) solved the issue. Probably because of it was loading before jQuery loading.

**Comment by gabrilr** [comment]
you were right, find out what the problem was and it's simpler than many explain: c

Thank Denly :'D from Mexico
