### ISSUE TITLE
Enable strict mode

### ISSUE THREAD

**Issue by matthieusieben** [Dogfalo/materialize#5141]
Bundling materialize-css with other libraries inside a `'use strict'` javascript environment has caused several issues (#5092, #5140, more ?).

The entire code should be written with `'use strict'`.

**Comment by Dogfalo** [comment]
This will be the case in v1. In the meanwhile, I would avoid using use strict in a global context

**Comment by matthieusieben** [comment]
Until v1 is actually released, this is *still* an issue. Could you merge #5140 and publish a bugfix release please?
