### ISSUE TITLE
Modal doesn't work in version 0.100.1

### ISSUE THREAD

**Issue by salmanulkhair** [Dogfalo/materialize#5142]
i have just updated from version 0.98.2 to 0.100.1 and the modal stop working . i reverted back to version 0.98.2 and it start working again

**Comment by tomscholz** [comment]
Please fill in the [issue template](https://github.com/Dogfalo/materialize/blob/master/.github/ISSUE_TEMPLATE.md) and make sure to read our [CONTRIBUTING guidelines](https://github.com/Dogfalo/materialize/blob/master/CONTRIBUTING.md) carefully!
