### ISSUE TITLE
Tabs with swipeable enabled lose the ability to set a default Tab

### ISSUE THREAD

**Issue by ghost** [Dogfalo/materialize#5144]
Tabs with `swipeable` enabled lose the ability to set `class="active"`.

## Expected Behavior
Active Tab is set to Tab with `class="active"`

## Current Behavior
Active Tab is set to the First Tab

## Possible Solution
Adding a starting index to Carousel, so `.tab({` can pass it to `.carousel({` when creating Tabs with `swipeable` enabled. Debugging it seems that the disparity between the Active Tab and Carousel it's what cause it the error.

## Steps to Reproduce
The problem is demonstrated on the website; if you inspect the source, `id="test-swipe-2"` as `class="active"` but as soon as the page load it swipes to `id="test-swipe-1"`.

It's easy to find where does this occur. While in http://materializecss.com/tabs.html#swipeable, open the DevTools and add break on attribute modifications to `href="#test-swipe-2"`, reload to view the Call Stack in action.

Chrome sometimes decides to not halt the execution, if so add a breakpoint at line 2674 of http://materializecss.com/bin/materialize.js, then just step call by call.

## Context
I was using the normal Tabs, but going through website I saw the `swipeable` option, so I implemented it to add transitions between the Tabs.

## Environment
* Version used: v0.100.2
* Browser Name and version: Chrome, 60.0.3112.101 (64 bits)
* Operating System and version (desktop or mobile): Windows 10

**Comment by DanielRuf** [comment]
A codepen would be great.

**Comment by Robotit** [comment]
@DanielRuf what should the Codepen include, I'm unsure what to do.

In http://materializecss.com/tabs.html#swipeable you can see the markup for `href="#test-swipe-2"` but still `href="#test-swipe-1"` is selected on load.

**Comment by acburst** [comment]
If possible, do you think you could try testing this issue with our v1-dev branch? This includes a rewritten tabs plugin that I think should solve the issue.

**Comment by Robotit** [comment]
@acburst okey, even though I'm not really sure how to do that.

**Comment by acburst** [comment]
Are you familiar with compiling the javascript? The dist is still the old file, you would need to compile yourself. We will look into hosting a compiled version for testing soon

**Comment by Robotit** [comment]
@acburst sorry, I'm not sure how to do that.

**Comment by acburst** [comment]
Fixed in 7012d5fa
