### ISSUE TITLE
0.99 modal: complete callback works only when closed via .modal-close

### ISSUE THREAD

**Issue by florian-senn** [Dogfalo/materialize#5146]
## Expected Behavior
When closing a modal, regardless how it is done, the complete callback should be called.

## Current Behavior

Right now, complete is only called, when the modal is closed via modal trigger close

There should be a callback, regardless if modal is closed with click on dismissible layer, ESC, etcl.
## Possible Solution

While debugging intensively, I could see modals being initialized with proper options on document ready, but when clicking modal triggers, options didn't show up again.

Tried a own solution by "injecting" a third callback "onClose" to a position that should be always called. This is the code you can see on my page (sourcemap included for easier inspection)

## Steps to Reproduce (for bugs)

- see [www.bannholzhof.at](https://www.bannholzhof.at)
- Open Modal (e.g. "Anfahrt") -> URL changes to [www.bannholzhof.at/anfahrt](https://www.bannholzhof.at/anfahrt)
- Close Modal via "Schließen" -> URL will return to [www.bannholzhof.at](https://www.bannholzhof.at)
- Dismiss Modal otherwise (ESC, Overlay) and URL will stay the same

## Context

Added routing to my site and I need the URL to be changed, basing on open/closing modals. Right now, router only gets called when clicking on "Schließen (close)"

`        $('.modal').modal({
            complete: onModalCloseNavigateToRoot
        });`
...
`function onModalCloseNavigateToRoot() {
    router.navigate('/');
}`

## Your Environment

* Version used: 0.99
* Browser Name and version: 

- Google Chrome Version 60.0.3112.101 (Offizieller Build) (64-Bit)
- FireFox 54.0.1 (32-bit)
- Microsoft Edge 40.15063.0.0

* Operating System and version (desktop or mobile): Windows 10 Pro Version 1703
* Link to your project (if appropriate): [www.bannholzhof.at](https://www.bannholzhof.at)

**Comment by Dogfalo** [comment]
This has been fixed in v.100.0
