### ISSUE TITLE
Multiple Select Initializes with Wrong Value

### ISSUE THREAD

**Issue by CameronSumpter** [Dogfalo/materialize#5148]
## Summary
When initializing a `select` with already-selected options inside of `optgroup`s, the wrong options are selected.

## Expected Behavior
`option`s with `selected` attribute should be selected.

## Current Behavior
An earlier `option` is selected because the selected item's index refers to its position within the `optgroup` and not its position in the sequence of all `options` under the given `select`.

## Possible Solution
On Line 4997 (v0.100.1), changing `$(this).index()` to `this.index` resolves the issue.

## Steps to Reproduce
Use this HTML:
```
<select multiple>
    <optgroup label="X">
        <option value="1">A</option>
        <option value="2">B</option>
    </optgroup>
    <optgroup label="Y">
        <option value="3">C</option>
        <option value="4" selected>D</option>
        <option value="5">E</option>
    </optgroup>
</select>
```
And execute `$('select').material_select();`. Though 'D' should be selected, 'B' is selected instead.

## Your Environment
* **Version Used:** Materialize v0.100.1; jQuery 3.2.1
* **Browser Name and Version:** Chrome 60.0.3112.113
* **Operating System:** Windows 10

**Comment by acburst** [comment]
Fixed in 1170d261.

Thanks for your solution!
