### ISSUE TITLE
materialize-css and bootstrap $colors variable collision

### ISSUE THREAD

**Issue by RadouaneRoufid** [Dogfalo/materialize#5153]
## Problem

While using `materialize-css` along with `Bootstrap 4` in **sass** mode, a collision occurs on the sass variable` $colors`.  Both frameworks have an overridable variable named` $colors` (Materialize-css have it in : **materialize-css/sass/components/_color.scss** and Bootstrap in **bootstrap/scss/_variables.scss**). 

Importing the two frameworks together provoke a compilation error : 
```
@import "../node_modules/bootstrap/scss/bootstrap";
@import "../node_modules/materialize-css/sass/materialize";

Compilation error : 

$button-background-focus: lighten($secondary-color, 4%) !default;
                         ^
      Argument `$color` of `lighten($color, $amount)` must be a color

Backtrace:
        node_modules/materialize-css/sass/components/_variables.scss:60, in function `lighten`
        node_modules/materialize-css/sass/components/_variables.scss:60

```
This is due to the fact that `$secondary-color: color("teal", "lighten-1") `returns a **null** value since it look for the _teal_ color in the Bootstrap `$colors` which does not exist. 

It would be nice to prefix the name of ` $colors` variable by mc or something specific to your framework.

## Possible Solution

A workaround is to redefine the `$colors` as below :

```
@import "../node_modules/bootstrap/scss/bootstrap";

@import "../node_modules/materialize-css/sass/components/color";
$colors: (
        "materialize-red": $materialize-red,
        "red": $red,
        "pink": $pink,
        "purple": $purple,
        "deep-purple": $deep-purple,
        "indigo": $indigo,
        "blue": $blue,
        "light-blue": $light-blue,
        "cyan": $cyan,
        "teal": $teal,
        "green": $green,
        "light-green": $light-green,
        "lime": $lime,
        "yellow": $yellow,
        "amber": $amber,
        "orange": $orange,
        "deep-orange": $deep-orange,
        "brown": $brown,
        "blue-grey": $blue-grey,
        "grey": $grey,
        "shades": $shades
);

@import "../node_modules/materialize-css/sass/materialize";
```

## Steps to Reproduce

1. Create a SASS project 
2. Install materialize-css version 0.100.1 or up and bootstrap version 4
3. Import materialize-css and bootstrap sass files. 
4. Compile your project

## Environment

Version used
- **"bootstrap": "^4.0.0-beta"**
- **"materialize-css": "0.100.2"**

**Comment by DanielRuf** [comment]
Generally it is not meant to mix both frameworks.

@tomscholz what do you think? Should we prefix as many variables as possible? This might be good. Also prefixing / namespacing methods in the JS files.

**Comment by Dogfalo** [comment]
we're not going to fix compatibility issues when using bootstrap and materialize together.

**Comment by esmaei1** [comment]
if you only need  materialize css colors you can use this:
https://github.com/esmaei1/materializecolors
