### ISSUE TITLE
Class active inside slider messes navigation up

### ISSUE THREAD

**Issue by camo-f** [Dogfalo/materialize#5154]
## Expected behavior
Slider should go to the next slide

## Current behavior
Slider jumps to the first element with `active` class found, even though it is not a slide.
It implies wrong initialization, and also `active` class is not removed from the previous active slide.

## Possible solution
The quickest fix is to change the class `active` to `active-slide` (for example). It will avoid all conflicts if slides have their own active class.

## Steps to reproduce
Add any element with `active` class inside a slider.
Here's a codepen : https://codepen.io/anon/pen/jLeajN

## Context
I'm using a slider with a form on each slide, and I noticed an issue with the active class dynamically added to a text-field label. When firing `prev` or `next` functions, the slider jumps to a wrong slide because of the false `active` index of the label.

## Environment
Version used : 0.99 of Materialize (though the code of slider hasn't changed in newer versions)
Browser : Firefox 54 (64-bit)
OS : Linux Mint 18 Sarah Xfce 64-bit

**Comment by drnasin** [comment]
works for me if I put "active" on list element, which makes more sense anyway...

`<li class="active"><p>Slide 4</p></li>`

**Comment by acburst** [comment]
Made active check more specific.

Fixed in 05e2cfc1
