### ISSUE TITLE
Select with multiple is not align well

### ISSUE THREAD

**Issue by brisfernando** [Dogfalo/materialize#5155]
In the documentation, the select dropdown with multiple is not align well..
https://goo.gl/photos/ev2EMErHAgfu9juP6

Thank you..

**Comment by DanielRuf** [comment]
https://github.com/Dogfalo/materialize/commit/81ab9ba3654fdbaca88d0f18a1a7f7998424e725

I'll prepare a PR.

**Comment by Dogfalo** [comment]
Duplicate of #5083
