### ISSUE TITLE
comment on materializecss

### ISSUE THREAD

**Issue by malorus** [Dogfalo/materialize#5156]
Hi guys, 

just want to give a short feedback as a user of materializecss. Materializecss has some really great features with an awesome userinterface. But I wished you would have developed it in pure javascript instead of on basis of jquery. I know jquery still is a popular library for javascript development, but in times where lots of frontend-frameworks are out there, like angular, the appearance of ES2015, and the availability of other script languages that transpile to javascript (like typescript) there is less the need of libs like jquery. There could be an additional version of materializecss that is written in jquery for those ones interested in  of course, why not. But, as to my personal opinion, the initial version should be in pure javascript, so that working with it does not require to use jquery. 

There is nothing faster than working with pure javascript... see for a comparison on http://vanilla-js.com/

**Comment by Dogfalo** [comment]
Please search issues, this has been discussed before. Also see https://github.com/Dogfalo/materialize/issues/5004
