### ISSUE TITLE
Please add tooltip "show" method to manual usage

### ISSUE THREAD

**Issue by PaulMaly** [Dogfalo/materialize#5157]
Example:

```
$el.tooltip({}); // init
...
$el.tooltip('show'); // manual show
...
$el.tooltip('remove'); // remove
```

**Comment by Dogfalo** [comment]
Available in v1

**Comment by PaulMaly** [comment]
@Dogfalo Is v1 already available?

**Comment by tomscholz** [comment]
@PaulMaly Nope

**Comment by obama** [comment]
ill ask here first: can you add a `.tooltip('hide')` like in jQueryUI? it will not remove the tooltip completely but just hide it on demand (when an event moves the tooltipped item away from mouse)
atm i circumvented it by setting delay to 0 and setting it to 350 again.

**Comment by Dogfalo** [comment]
@obama This is added in v1 when it releases
