### ISSUE TITLE
Modals opened programmatically don't adhere to custom settings

### ISSUE THREAD

**Issue by Deedee101** [Dogfalo/materialize#5159]
Modals being called using this code:

`$('#modal1').modal('open');`

doesn't adhere to custom setting but adheres to the default setting within the framework.

Custom setting:

```
  $('.modal').modal({
        dismissible: false, 
        opacity: 1, // Opacity of modal background
        inDuration: 300, // Transition in duration
        outDuration: 200, // Transition out duration
        startingTop: '4%', // Starting top style attribute
        endingTop: '10%', // Ending top style attribute
    });
```

The setting work whenever the modal is opened using a trigger. Example:
`
<a class="waves-effect waves-light btn modal-trigger" href="#modal1">Modal</a>`

Example: Instead of it looking like [this](https://ibb.co/jpEbU5), it looks like [this](https://ibb.co/jsc8bk)

**Comment by DanielRuf** [comment]
Please provide a working codepen.

**Comment by Deedee101** [comment]
@DanielRuf In creating the codepen I noticed it worked there. Then I began to go through the code and checked my references. So it works using this link https://cdnjs.cloudflare.com/ajax/libs/materialize/0.100.2/js/materialize.min.js provided within the documentation but it doesn't work with neither the materialize.min.js or materialize.js files provided within the documentation.

**Comment by DanielRuf** [comment]
> but it doesn't work with neither the materialize.min.js or materialize.js files provided within the documentation.

Can you provide the URLs of these files?

**Comment by Deedee101** [comment]
https://github.com/Dogfalo/materialize/releases/download/v0.100.2/materialize-v0.100.2.zip

My code:

```
<!DOCTYPE html>
<html>

<head>
  <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
  <link type="text/css" rel="stylesheet" href="css/materialize.min.css" media="screen,projection" />

  <meta name="viewport" content="width=device-width, initial-scale=1.0" />
</head>
<body>
  <div id="modal1" class="modal cyan">
    <div class="row">
      <div class="col s8 offset-s2 center">
        <div class="modal-content" style="padding-top: 50px;
        padding-bottom: 50px;">
        <div><i class="material-icons large">school</i></div>
        <span id="testTitle"></span>
        <p>Quiz</p>
        <h6 id="duration"></h6>

        <a onclick="startTest()" class="modal-action modal-close waves-effect blue-grey darken-4 btn">Start</a>
        <a href="#!" class="modal-action modal-close waves-effect blue-grey darken-4 btn">Cancel</a>
      </div>
    </div>
  </div>
</div>
<script type="text/javascript" src="https://code.jquery.com/jquery-3.2.1.min.js"></script>
<script type="text/javascript" src="js/materialize.min.js"></script>
<script>
  $(document).ready(function() {
            // the "href" attribute of the modal trigger must specify the modal ID that wants to be triggered
            $('.modal').modal({
        dismissible: false, // Modal can be dismissed by clicking outside of the modal
        opacity: 1, // Opacity of modal background
        inDuration: 300, // Transition in duration
        outDuration: 200, // Transition out duration
        startingTop: '4%', // Starting top style attribute
        endingTop: '10%', // Ending top style attribute
      });
            
            $('#modal1').modal('open');
          });
        </script>
      </body>
      </html>
```

**Comment by Deedee101** [comment]
@DanielRuf You can ignore the onclick events. I've just sent you the important parts of my code that relates to my issue.

**Comment by DanielRuf** [comment]
The file on the CDN in the zip file should be the same. 

Here is a codepen:
https://codepen.io/anon/pen/WEYZWX

And so far the options work. Opacity 1 is solid.

**Comment by DanielRuf** [comment]
Please check if something overrides the CSS for `.modal-overlay`.

**Comment by DanielRuf** [comment]
The cdn and zip files are identical

https://www.diffchecker.com/SsfKQRCI
