### ISSUE TITLE
Cannot read property M_modal of undefined

### ISSUE THREAD

**Issue by robbiemilejczak** [Dogfalo/materialize#5163]
## Expected Behavior
I guess technically everything is working, but it's a little annoying to see errors in my console.

So the expected behavior is a console free of errors

## Current Behavior
When clicking an anchor element with the class modal-trigger, and no assigned href attribute, I see the above error in my console. 

I am using jQuery to open the modal programatically ($('#modalid').modal('open')), and I am opening different modals based on conditions on the page. If I assign the modal-trigger an href attribute, the console error disappears but then I have a modal opening when I don't want it to. If I remove the href attribute, my page functions as I would expect (the modals open correctly based on their assigned conditions) but I have the above error in my console. If I remove the class "modal-trigger" from my anchor element, the modals no longer open on click.

## Steps to Reproduce (for bugs)
You can see the behavior here (open the console to see the error obviously, not the best example but it works well enough)

https://jsfiddle.net/5f528dgp/

When you click the button, the code decides whether to open modal1 or modal2 based on specified conditions. This works as expected, but produces an unnecessary console error. 

If you set the href attribute of the anchor to either modal1 or modal2, the specified modal will always open and the other modal may also open based on the conditions. This removes the console error, but is undesired behavior.

## Context
I get why this error exists, as I'm sure most users are simply assigning the buttons to specific modals. It really is inconsequential in the grander scheme, since I can get the desired behavior without issue. It's just seriously annoying to see that console error when I know it doesn't need to be there. If I'm doing something wrong please correct me, and I'm sorry for wasting anyone's time. I love love LOVE this CSS framework, it is gorgeous and a joy to use. Keep up the excellent work!

## Your Environment
Just an HTML file, with jQuery 3.2.1, materialize.css, and materialize.js loaded through CDNs.

**Comment by robbiemilejczak** [comment]
Just realized that if I set the href attribute to the modal I want to open at the same time I call .modal('open') the console error disappears. That might be helpful in fixing this bug (if it is a bug and I'm not an idiot lol)

**Comment by Dogfalo** [comment]
The modal trigger is meant to be tied with a `data-target` or `href` if you don't plan to use any of those and open modals problematically. Try just using a plain `<button>` and bind your click handler as you do.

**Comment by tcb1978** [comment]
Testing the TechListModal.js after adding it to App.js; when clicking the list button I am getting the error 'materialize.min.js:2035 Uncaught TypeError: Cannot read property 'M_Modal' of null
    at HTMLBodyElement.value (materialize.min.js:2035)' without any other helpful console errors. Anyone else encounter this?
