### ISSUE TITLE
npm + browserify: Materialize.toast is not a function

### ISSUE THREAD

**Issue by gg4u** [Dogfalo/materialize#5178]
I am using npm and browserify;  I am importing materialise in my index.js as:

```
var jquery = require('jquery');
var Materialize = require('materialize-css');

// test
window.Materialize = Materialize;
Materialize.toast(message, time);
```

Materialize.toast is not a function.

Cannot figure out why ...

window.Materialize.toast is also undefined.

**Comment by Dogfalo** [comment]
Please send me a zip or github repo of the project so I can take a look and create a fix if necessary

**Comment by gg4u** [comment]
by the project do you mean the index.js file?

**Comment by Dogfalo** [comment]
as well as the package.json and any other things relevant to the setup with Materialize

**Comment by gg4u** [comment]
thank you @Dogfalo for helping out - i iupload a folder and kept the relevant structure.
see in attachment!
[debug.zip](https://github.com/Dogfalo/materialize/files/1290036/debug.zip)

**Comment by Dogfalo** [comment]
After looking at the project files, there were many random syntax errors I encountered in it. After fixing them I still wasn't presented with the error you described in the issue. I can reopen this again if you can provide a cleaner reproduction of the issue.

**Comment by gg4u** [comment]
@Dogfalo Hi Alvin, sorry to hear that. Would you mind to share you corrected version so that I can see if it works ok with me too and also help me understand which may be the issue for which I can't see Materialize.toast working in the npm bundle?
The code I provided was a simplified version of what I worked on, which compiles with no errors but Materialize.toast does not fire.

**Comment by Dogfalo** [comment]
Here is a working version
[materialize-browserify-issue.zip](https://github.com/Dogfalo/materialize/files/1450809/materialize-browserify-issue.zip)
