### ISSUE TITLE
Materialize doesn't comply to accessibility standards

### ISSUE THREAD

**Issue by ChildishGiant** [Dogfalo/materialize#5179]
Text color contrast doesn't fit within either WCAG guidelines. #9E9E9E and #FFFFFF together have a contrast ratio of 2.67 : 1, not high enough for any of the standards. This means the text may be difficult or impossible to read for people with low vision or color-blindness.
![image](https://user-images.githubusercontent.com/13716824/30244855-f28dd2ce-95be-11e7-9c42-4ea340210e2f.png)
The same goes for #039be5 and #FFFFFF.
![image](https://user-images.githubusercontent.com/13716824/30244866-4d546060-95bf-11e7-97c8-0900ae018be3.png)

 [More info on the standards](https://dequeuniversity.com/rules/axe/2.3/color-contrast)

**Comment by Dogfalo** [comment]
I don't really know what colors you're talking about but #9e9e9e is the body text color on our site. And in your project you are free to choose whatever colors to comply with any standards you wish.

**Comment by ChildishGiant** [comment]
I just think that a massive library the thousands use, should also let blind people use sites by default 😛

**Comment by Dogfalo** [comment]
Well the default font color is rgba(0, 0, 0, 0.87) and that is perfectly visible on white backgrounds
