### ISSUE TITLE
Select input display hidden option

### ISSUE THREAD

**Issue by bsulyan** [Dogfalo/materialize#5184]
The hidden property does not work, style="display:none;" not working too.

**Comment by Aiden01** [comment]
Try to inspect element, probably you used an !important somewhere.

**Comment by developeranirudhprabhu** [comment]
@bsulyan Can you share a codepen for this issue? Also elaborate what you are trying to achieve?

**Comment by bsulyan** [comment]
https://codepen.io/Sunasty/pen/YEYLxG

I try to hide options

**Comment by henriqueneves** [comment]
Materialize hides your Select and create a new structure. Why do not you remove the items before executing the inicialization?

//Remove itens
 $('select').material_select();

**Comment by jpic** [comment]
> Why do not you remove the items before executing the inicialization?

Because then the page would be static and they want dynamic behaviour.
