### ISSUE TITLE
nav search expandable

### ISSUE THREAD

**Issue by buutqn** [Dogfalo/materialize#5185]
I've found myself with a little problem, I wanted to use the search form in navbar but couldn't use the brand icon also the nav menu because the form was full-width, then i made this little changes to works as expandable search as the gif shows

![search-expandable](https://user-images.githubusercontent.com/15644387/30286351-ad661faa-96f7-11e7-9191-0672290943b8.gif)
![search-expandable-mobile](https://user-images.githubusercontent.com/15644387/30286355-b002baca-96f7-11e7-98cb-bd6d0a1640c4.gif)

jsfiddle with the code: https://jsfiddle.net/buutqn/udjthdd7/

Isn't really an issue, is more about something i wanted and couldn't do...
Not sure if im posting in the right section, I just wanted to share this...

But, i would appreciate if there was something like it

**Comment by acburst** [comment]
This seems out of scope for materialize, but it looks interesting!
