### ISSUE TITLE
Option to count white spaces for characterCounter()

### ISSUE THREAD

**Issue by sigmatec** [Dogfalo/materialize#5186]
Suggestion for an enhancement in a future version...

Currently, characterCounter() doesn't have any options.  We would find it very useful to have an option something like `countSpaces`, which would be `true` by default.  When changed to `false` it would only count characters that are not white spaces.

This would allow the counter to be used for additional scenarios, such as inscriptions on a product, where you're allowed up to a certain amount of letters but the spaces are of no relevance.

**Example**
String in the text field of: "Hello, World!"
With `countSpaces: true` = 13
With `countSpaces: false` = 12

**Comment by developeranirudhprabhu** [comment]
@acburst You think this enhancement is valid and can be taken up? If its ok I can try to work on it.

**Comment by sigmatec** [comment]
Also when `countSpaces: false` it should probably ignore any space-type characters, including line breaks if it was a textarea.

**Comment by Dogfalo** [comment]
This sounds like a reasonable addition, however, right now we're more focused on just getting the core of 1.0 out in a stable manner. Enhancements aren't priority right now and can be focused on later after the release.
