### ISSUE TITLE
Expandable jump transition with JQuery 3.2.1

### ISSUE THREAD

**Issue by KilianB** [Dogfalo/materialize#5188]
The expandable's collapsible-body component's height during transition is at some point bigger than the final height of the component. This leads to jump in the container height at the end of the transition while using JQuery 3.2.1 all other version are working fine.

**Comment by JayhawkZombie** [comment]
I can confirm I can reproduce this, but also JQuery version 3.2.0.
JQuery 3.1.1 does not produce the issue in my setup.

**Comment by Dogfalo** [comment]
We've reworked the collapsible in v1 so it does not rely on jQuery, so this will be fixed when the release comes out
