### ISSUE TITLE
Bower Components missing fonts directory, causing 404s

### ISSUE THREAD

**Issue by spkellydev** [Dogfalo/materialize#5189]
I saw there were similar issues opened and closed for npm, but I wanted to let the devs know that the bower package still has 404s from missing fonts. I understand the reasoning for doing away with fonts in the package, but I don't believe leaving the source in the css files is a good idea.

**Comment by peabnuts123** [comment]
Here because of this, I am confused. Do I need to go and manually download the fonts…? Do I need them… ? Seems like either they should be included in the package OR removed from the SASS sources

**Comment by mwarrier** [comment]
Same issue here. Reverted to version 0.98.2 for now.

**Comment by sebdah** [comment]
I'm facing the same issue and cloned the fonts manually for the time being. Reverted to 0.99.0 for now.

**Comment by Dogfalo** [comment]
The fonts have been removed in 1.0 alpha
