### ISSUE TITLE
SideNav fixed don't change color text

### ISSUE THREAD

**Issue by danielmadu** [Dogfalo/materialize#519]
When I put the class blue-text to change color text, the SideNav don't change. When I try force the color, also don't works.

	  <ul class="side-nav fixed blue-grey darken-3 text-blue " style="color: #e3f2fd !important; ">
	    <li><a href="#!">First Sidebar Link</a></li>
	    <li><a href="#!">Second Sidebar Link</a></li>
	  </ul>

**Comment by mazzie14** [comment]
You've used the class text-blue,  but the correct class is blue-text

**Comment by acburst** [comment]
Also you would have to override the color on the a tags. It won't inherit
