### ISSUE TITLE
Import specific SCSS components rather than full sass library

### ISSUE THREAD

**Issue by IAMtheIAM** [Dogfalo/materialize#5192]
QUESTION:

I am wondering if there is a preferred way to import specific scss components rather than the entire library. The primary reason is that I want to use another library `toastr`, but these styles conflict with the styles that come with toastr. 

I know I can create my own scss imports file and pick only what I want, I did this and it works great.

But is this the recommended solution? Thanks

**Comment by storm1er** [comment]
see #5024

**Comment by IAMtheIAM** [comment]
I went ahead and created my own @imports for materializecss and picked only the modules i wanted. works fine.
