### ISSUE TITLE
Materialize.updateTextFields is not a function

### ISSUE THREAD

**Issue by IAMtheIAM** [Dogfalo/materialize#5194]
## Expected Behavior

Materialize.updateTextFields() should be loaded with the rest of functions, not inside $(document).ready()

## Current Behavior

I have jquery properly imported

When using materializecss with angular 2, there is a lifecycle hook on angular called `ngAfterViewInit()` which is basically the same as jquery's $(document).ready(). However, the ng hook gets called BEFORE $(document).ready(). Therefore this code fails because the function isnt' available.

```
   ngAfterViewInit() {
      /**
       * The ngAfterViewInit lifecycle hook makes sure the view is rendered, useful so
       * jQuery can know when to do it's thing
       *
       * This is where you put all your "$(document).ready()" code
       * Example: this.loadDataTables();
       **/
      //==== AppComponent Initializations ====//

      // Materialize Prefilled Text Inputs
      // This prevents labels overlapping prefilled input content. You can also add class="active" to the label.
      Materialize.updateTextFields();

      // Materialize Select
      // $('select').material_select();

      //==== End AppComponent Initializations ====//

   }
```

However, almost imediately after, the jquery document ready code fires, and then adds `updateTextFields` to the function, but its too late. However, the next time it runs, like after nagivating to a new component, it works fine.

## Possible Solution
Move updateTextFields() into the main body of the materialize js function. What is the purpose of putting it in document ready?

I have confirmed in my test of editing the js, that moving Materialize.updateTextFields function just one line above the `$(document).ready` located in `forms.js` allows the function to be available at the time the ng lifecycle hook is called. For example, I [submitted a PR](https://github.com/Dogfalo/materialize/pull/5195) to show where i put it, but you may have a better location for it.

## Steps to Reproduce (for bugs)

1. Create angular 4+ app
2. put `      Materialize.updateTextFields();` inside the ngAfterViewInit() {} lifecycle hook
3. load app
4. see error in console

## Context

Prefilled text gets overlapped by labels. 

## Your Environment

* Version used:
* Browser Name and version: Chrome, Firefox (latest)
* Operating System and version (desktop or mobile): desktop, win10
* Link to your project (if appropriate):

[Link to Reproduce here](http://atlas-dashboard-dev.azurewebsites.net/)
Open console to view error.

**Comment by IAMtheIAM** [comment]
Well team, what do you think?

**Comment by Dogfalo** [comment]
Yea it shouldn't be wrapped in a ready().

**Comment by Dogfalo** [comment]
Fixed here 7c7a9fd8062a18c17adabf6ae47edbe142bf8393

**Comment by IAMtheIAM** [comment]
Great, I see that it is fixed in [v1-dev](https://github.com/Dogfalo/materialize/blob/v1-dev/js/forms.js#L3). Just curious what the possible timeline until release for that branch is? I know its hard to say for sure.

**Comment by tomscholz** [comment]
@IAMtheIAM Please see #5004
