### ISSUE TITLE
Autocomplete input in collection-item shows the autocompletefield behind collection item and moves over other elements.

### ISSUE THREAD

**Issue by SherinBloemendaal** [Dogfalo/materialize#5197]
Hello,

When i add a input(autocomplete) into a collection-item the other elements move down when autocompletefield is visible. 

Code when it goes wrong:
`                    <div class="row">
                        <div class="col s6">
                            <ul class="collection">
                                <li class="collection-item avatar">
                                    <img src="/img/new-job/ObjectIcon.png" class="circle">
                                    <div class="row">
                                        <div class="input-field col s12">
                                            <input type="text" name="object-input" id="object-input" placeholder="Object (Naam/Nummer)" class="autocomplete">
                                            <label for="object-input">Object</label>
                                        </div>
                                    </div>
                                </li>`

When i set the input outside the collection item, it works fine.

It this a bug? or is it my fault?

Screenshots: 
[http://prntscr.com/gldymt](http://prntscr.com/gldymt)
[http://prntscr.com/gldyv9](http://prntscr.com/gldyv9)

Thanks
Sherin

**Comment by SherinBloemendaal1** [comment]
Any update about this?

**Comment by SherinBloemendaal1** [comment]
Well???

**Comment by redjohn360** [comment]
I got the same issue, so I think it's a bug...

**Comment by ray007** [comment]
I think `autocomplete` needs a parameter for dropdown options to pass on, like `Select` now has.
Then we could anchor the dropdown in `document.body` which should help things...

Personally I think _everything_ looking like a new layer _always_ should go in `document.body`

**Comment by acburst** [comment]
Container option was added to dropdown in 1.0.0 alpha

You can set the options for the select dropdown in the dropdownOptions option for select.
