### ISSUE TITLE
Dropdown close via dropdown-button adds hash to url

### ISSUE THREAD

**Issue by thorge** [Dogfalo/materialize#5198]
When I close a dropdown by clicking the same dropdown-button that opened the dropdown, it adds its anchor href attribute hash to the URL. Is this expected behaviour?
You can reproduce this issue by using the demo code with `data-originBelow=true` attribute (so the dropdown won't hide your button):

    <!DOCTYPE html>
    <html >
    <head>
      <meta charset="UTF-8">
      <title>MaterializeCSS Dropdown Hash</title>
     
      <link rel='stylesheet prefetch' href='https://fonts.googleapis.com/icon?family=Material+Icons'>
      <link rel='stylesheet prefetch' href='https://cdnjs.cloudflare.com/ajax/libs/materialize/0.100.2/css/materialize.min.css'>

    </head>

    <body>
      
      <a class='dropdown-button btn' href='#' data-activates='dropdown1' data-belowOrigin='true'>Drop Me!</a>

      
      <ul id='dropdown1' class='dropdown-content'>
        <li><a href="#!">one</a></li>
        <li><a href="#!">two</a></li>
        <li class="divider"></li>
        <li><a href="#!">three</a></li>
        <li><a href="#!"><i class="material-icons">view_module</i>four</a></li>
        <li><a href="#!"><i class="material-icons">cloud</i>five</a></li>
      </ul>
      <script src='https://code.jquery.com/jquery-3.2.1.min.js'></script>
    <script src='https://cdnjs.cloudflare.com/ajax/libs/materialize/0.100.2/js/materialize.min.js'></script>

    </body>
    </html>

**Comment by neelkirit** [comment]
You can prevent adding hash to the URL by removing the href attribute of anchor tag without impacting any other functionality.
