### ISSUE TITLE
When pushpin is pinned, content goes behind

### ISSUE THREAD

**Issue by EclairOChocola** [Dogfalo/materialize#5203]
## Expected Behavior
When a element is pinned, we should see the text under that element.
In the demo we cant see it because there is no text.

## Current Behavior
When a pushpin element is pinned, the content goes behind the nav. 
So, if we want to put some text under the nav. I don't know if there is possible

## Steps to Reproduce (for bugs)

There is a codepen with exactly the code of the demo. I hust add some text under the nav.
https://codepen.io/anon/pen/QqbZPG

**Comment by acburst** [comment]
When using pushpin you have to make sure the element you are making fixed is in a container with a fixed height. The act of making it fixed takes it out of the flow of the document causing the content jump.

**Comment by vladimir-dobrovolsky** [comment]
Maybe you can update pushpin documentation page with this info? I just spent some time trying to get over this issue too. My solution was to simply add padding to div next to pinned nav that equals the pinned nav's height like this:

`            .pinned + div {
                padding-top: 64px; /* height of pinned navbar */
            }`

Like this: https://codepen.io/anon/pen/zpzJWy


This way it doesn't jump when scrolling and content stays where it was supposed to be. Also it doesn't matter what the content's height is.
