### ISSUE TITLE
ReferenceError during DatePicker initialization while running Javascript in strict mode

### ISSUE THREAD

**Issue by geoff-wasilwa** [Dogfalo/materialize#5204]
I believe this occurs due to the missing commas [here](https://github.com/Dogfalo/materialize/blob/master/js/date_picker/picker.date.js#L1164) and [here](https://github.com/Dogfalo/materialize/blob/master/js/date_picker/picker.date.js#L1172)

**Comment by DanielRuf** [comment]
What exactly is the error that you get? A PR is very welcome?

**Comment by geoff-wasilwa** [comment]
Here's the stack trace:
```
Uncaught ReferenceError: createDayLabel is not defined
    at DatePicker.nodes
    at createWrappedComponent
    at PickerInstance.start
    at new PickerInstance
    at new PickerConstructor
    at HTMLInputElement.<anonymous>
    at Function.each
    at jQuery.fn.init.each
    at jQuery.fn.init.$.fn.(anonymous function) [as pickadate] 
```

**Comment by Dogfalo** [comment]
You should run `use strict` inside a function instead of applying it at a global level. We will be reworking Date Picker soon as well which will fix this issue

**Comment by DanielRuf** [comment]
@Dogfalo I guess this is automatically done by some things like Babel.
