### ISSUE TITLE
Meteor 1.6 common.gypi not found

### ISSUE THREAD

**Issue by KoenLav** [Dogfalo/materialize#5207]
On Meteor 1.6 beta 27, while node-gyp is building node-sass in:
materialize_materialize\\0.100.2\\npm\\node_modules\\.temp-3nmk2a.l4ujd\\node_modules\\node-sass\\build'

common.gypi is not found in:

1.6.0-beta.27\mt-os.windows.x86_32\**dev_bundle**\common.gypi 

However common.gypi is present in:

materialize_materialize\0.100.2\npm\node_modules\.temp-3nmk2a.l4ujd\node_modules\node-sass\common.gypi

It seems that, while building node-sass, node-gyp **loses track of the current path** and reverts to the meteor npm default path.

Using version 0.100.2 on Windows 10 x64.

I realize Meteor 1.6 is in Beta, but just wanted to make mention of this, should anyone else be running into the same problem (took me some time to pinpoint).

Also I am not sure whether this bug should be filed here, or its is a result of some of the dependencies of this package (fourseven:scss or node-sass).

**Comment by DanielRuf** [comment]
This issue should be reported in the node-sass project.
