### ISSUE TITLE
add space before AM/PM timepicker

### ISSUE THREAD

**Issue by poltographer6** [Dogfalo/materialize#5209]
How can I modify the format that timepicker displays when I pick a time. I cannot parse the time because there is no space between the time and AM/PM

**Comment by developeranirudhprabhu** [comment]
@poltographer6 Can you provide a codepen for this? And also elaborate what exactly you are trying to achieve?

**Comment by Dogfalo** [comment]
In 1.0.0 alpha, it is already like this.
