### ISSUE TITLE
a.waves-effect forcing behavior z-index over modal

### ISSUE THREAD

**Issue by rubenscd** [Dogfalo/materialize#5211]
## Expected Behavior
modal-trigger button (with class .waves-effect) doesn't overing modal 

## Current Behavior
modal-trigger button (with class .waves-effect) overing modal 

## Possible Solution
possible behavior is the attribute "position: relative;" in .waves-effect class ?

## Steps to Reproduce (for bugs)
1. a.btn.waves-effect.modal-trigger clicked
2. modal open
3. a.btn.waves-effect over actual modal

## Context
I trying remove .waves-effect class

## Your Environment

* Version used: 0.100.2
* Browser Name and version: Safari 10.1.2 (12603.3.8)
* Operating System and version (desktop or mobile): macOS Sierra 
* Link to your project (if appropriate): sorry, still in development 
![screenshot 8 - error](https://user-images.githubusercontent.com/40513/30563431-31c63316-9c98-11e7-8075-fc8fe03b62f3.png)

**Comment by tomscholz** [comment]
Can you provide a codepen?

**Comment by rubenscd** [comment]
Sorry, my mistake!

I was starting the modal by .modal-trigger (as in materialecss 0.97.7) but now it's otherwise, I'm reviewing my coding.
