### ISSUE TITLE
Button Design Bug

### ISSUE THREAD

**Issue by DapDallas** [Dogfalo/materialize#5213]
Hi,

When clicking on the button, the white click effect appears (intended). However, if you click very close to the side of the button, the whole button will not be white anymore.

**Comment by Dogfalo** [comment]
Can't reproduce, please add a codepen

**Comment by DapDallas** [comment]
![image](https://user-images.githubusercontent.com/32094083/30637705-6c8a877e-9df9-11e7-99da-af0a227f0b57.png)


If I am clicking here, you will see in left top corner the problem.

**Comment by DanielRuf** [comment]
Thats because the waves effect has a specific length / size. You can probably overwrite it with some custom CSS.
