### ISSUE TITLE
Google Map API JS invisible controls SOLVED

### ISSUE THREAD

**Issue by Darkinuyasha** [Dogfalo/materialize#5218]
Hello, I encountered a bug where the control buttons on the map (like zoom, etc...) where invisible.
I searched a solution and found what was causing it.

At line 3967 of the 0.100 there is this line:
```
.waves-effect img {
position: relative;
z-index: -1; }
```

to fix che problem, do this:
```
#map-container img{
     z-index: 1;
 }
```

Don't know how to solve the problem in a more general way, but if someone got stuck in this problem, here's the solution!

**Comment by DanielRuf** [comment]
A PR is very welcome.

**Comment by Darkinuyasha** [comment]
What is a PR?

Sorry I'm a little noob about git

**Comment by DanielRuf** [comment]
A pull request. Clivk the fork button and fork it to your account, make the changes in the sass files and then click the green pull request button on the page of your fork at the top.

**Comment by tdotholla** [comment]
Does your map container have the 'waves-effect' class in it?
I don't understand why this issue occurs.

**Comment by tomscholz** [comment]
Please close if resolved

**Comment by Darkinuyasha** [comment]
Sorry I forgot about this.
The fix is this and I already made a commit
.gm-style img{
    z-index: 1;
}

**Comment by DanielRuf** [comment]
Can you link the PR?

**Comment by Darkinuyasha** [comment]
How I do that?
Anyway it's in  materialize/sass/components/_waves.scss

**Comment by DanielRuf** [comment]
There should be a button to create a PR against the original project.

https://github.com/Darkinuyasha/materialize

**Comment by tomscholz** [comment]
Please close, if resolved
