### ISSUE TITLE
Combination of Vue.js and Carousel gives Division by zero

### ISSUE THREAD

**Issue by kkufieta** [Dogfalo/materialize#5220]
https://github.com/Dogfalo/materialize/blob/9bc43a1199ad5dfb78d58ba47726ab039218a939/js/carousel.js#L180

I am using Vue.js to fill the links / images in the carousel like this:

```
<div class="carousel">
  <a class="carousel-item" v-for="book in books" v-bind:href="book.title">
    <img v-bind:src="book.imgSrc">
  </a>
</div>
```

The width of those unfilled images was zero which causes division by zero on line 180. I fixed the issue temporarily by setting a `min-width` on the `a.carousel-item`, but it would be great if this case could be handled by the carousel instead.

**Comment by Dogfalo** [comment]
Fixed in v1-dev branch 
https://github.com/Dogfalo/materialize/blob/v1-dev/js/carousel.js#L63
