### ISSUE TITLE
Scroll in modal

### ISSUE THREAD

**Issue by guilherme90** [Dogfalo/materialize#5221]
I using modal, but when insert content inside in body, display scroll...

Why? How correct that?
![bug-scroll-modal-mdcss](https://user-images.githubusercontent.com/2879939/30721860-68589f68-9f04-11e7-875f-c2c6a24cbb29.png)

**Comment by flexbox** [comment]
Have you tried __Modals with Fixed Footer__?
http://materializecss.com/modals.html

And can you give an online example on codepen.io ?

**Comment by guilherme90** [comment]
Yes, with fixed footer. I'll show you the code later.
