### ISSUE TITLE
Container selection for timepicker

### ISSUE THREAD

**Issue by ltoenjes** [Dogfalo/materialize#5225]
There is a known issue that date- and timepickers have trouble being opened within a modal. The datapicker supports the selection of it's container, which fixes this problem. The timepicker doesn't. Would be quite nice if this is added!

**Comment by Dogfalo** [comment]
I think the feature was added, but we left out documentation for the `container` option.

**Comment by Dogfalo** [comment]
Fixed in 1.0 alpha
