### ISSUE TITLE
Switches not working and not displaying correctly

### ISSUE THREAD

**Issue by DEKHTIARJonathan** [Dogfalo/materialize#5229]
Hello,

I encounter some problems using "switches" with Materialize 0.100.2.
With version 0.99.0 or less it was perfectly working and now, since 0.100.0 switches refuses to "switch" on and off.

I have created a fiddle to show this:
https://jsfiddle.net/d4Lp1vmb/1/

Feel free to fork and update if I'm doing anything wrong ;)

Thanks a lot

**Comment by DanielRuf** [comment]
Don't use the `input-field` class, see https://jsfiddle.net/ruyum5ye/

**Comment by DEKHTIARJonathan** [comment]
Perfect thanks !
