### ISSUE TITLE
minified css with grunt

### ISSUE THREAD

**Issue by sahina** [Dogfalo/materialize#523]
I am using materialize with and angular app (generated with the yeoman angular fullstack generator). App looks and works as expected. The only issue is with forms. I don't see any other issues with the prod build.

Attached are two images: dev and dist builds.

Did anyone come across with this? If not, any ideas to why this may be happening?
![mcss-bad](https://cloud.githubusercontent.com/assets/2219825/5894089/23ad085a-a4c9-11e4-9bf0-5d6a207fcb9e.png)

![mcss-good](https://cloud.githubusercontent.com/assets/2219825/5894090/2f314448-a4c9-11e4-8c4b-c498570b9df2.png)

**Comment by acburst** [comment]
Im not exactly sure, but at first glance it seems the first example is missing type="text"

**Comment by sahina** [comment]
This grunt plugin "grunt-angular-templates" has an htmlmin option section. The options are below. This option "removeRedundantAttributes" removes that type="text" attribute.

    htmlmin: {
    collapseBooleanAttributes:      true,
    collapseWhitespace:             true,
    removeAttributeQuotes:          true,
    removeComments:                 true, 
    removeEmptyAttributes:          true,
    removeRedundantAttributes:      true,
    removeScriptTypeAttributes:     true,
    removeStyleLinkTypeAttributes:  true
    }

I'll play with these optimizations and see it any one of them is a possible culprit.

**Comment by sahina** [comment]
Turning all of them fixed the issue. I won't investigate any further to see which one is the reason. I compared the optimized and non-optimized js, diff is small. This works for me.

Thanks for the pointer.
