### ISSUE TITLE
file input is uploading just file name

### ISSUE THREAD

**Issue by usmanhafeez147** [Dogfalo/materialize#5235]
Hello Everybody
I'm Back-end PHP Developer. I purchased a html theme that is implemented by materializeJs and marterializeJs. I made a form with input type is file but I think materializeJs not letting to upload file but only String of file name and when I use php function files_get_content to show file params it give error.

**Comment by tomscholz** [comment]
Fill out the issue template, located [here](https://github.com/Dogfalo/materialize/blob/master/.github/ISSUE_TEMPLATE.md)

**Comment by kirthick** [comment]
please use this function json stringfy

**Comment by DanielRuf** [comment]
What is in $_FILES?

**Comment by shmshd12** [comment]
Since you did not explain your issue properly I guess youve missed enctype="multipart/form-data".
