### ISSUE TITLE
Fonts folder is not included in project with bower install

### ISSUE THREAD

**Issue by vitorbarros** [Dogfalo/materialize#5236]
Hello everyone.

When I install materialize with `npm install` It's getting all the project folders. But with `bower install` the fonts folder is not included.

Here the print.

`bower install` result

![image](https://user-images.githubusercontent.com/16783250/30992221-215e26e8-a47f-11e7-8f4e-09c5eae3a42a.png)

`npm install` result

![image](https://user-images.githubusercontent.com/16783250/30992250-4b8fda2e-a47f-11e7-90f0-d7f5297d1b0e.png)

bower and npm version 

![image](https://user-images.githubusercontent.com/16783250/30992267-62d447ba-a47f-11e7-901a-7f2565520286.png)

**Comment by Dogfalo** [comment]
Duplicate issue
