### ISSUE TITLE
Slider not working properly

### ISSUE THREAD

**Issue by smotru** [Dogfalo/materialize#524]
Sometimes large (in width) images are scaled to half of the screen. 

I've tried to figure out why is that happening. I've found that removing height: 400px; from sass would solve it. 

But still this might not be the fix since I've forked your repo and replaced in media.html with my image and your little slider is working ok. I will paste my code maybe I did something wrong.

```
// This is between body tags. Without any navigation bar, so it's bassically width: 100% of browser window.
 <div class="row">
      <div class="col s12 no-padding">
        <div class="slider">
          <ul class="slides">
            <li>
              <img src="http://www.hanspeterporsche.com/files/hpptw/user_uploads/sammlung.jpg">
              <div class="caption">
                <h3>Random</h3>
                <h5 class="light grey-text text-lighten-3">Here's our small slogan.</h5>
              </div>
            </li>
            <li>
              <img src="https://scontent-a-ams.xx.fbcdn.net/hphotos-xpf1/v/t1.0-9/10885104_454774411343105_9005172253976169596_n.jpg?oh=afbb37a917b3109a39629d5e3b3de168&oe=555EF5C7"> <!-- random image -->
              <div class="caption left-align">
                <h3>Left Aligned Caption</h3>
                <h5 class="light grey-text text-lighten-3">Here's our small slogan.</h5>
              </div>
            </li>
          </ul>
        </div>
      </div>
    </div>
```

And JS file: 
```
(function($) {
	$('.slider').slider({full_width: true, indicators: false});
})(jQuery);
```

**Comment by acburst** [comment]
I've tried your code and I'm not sure what you are looking for. Are you talking about how half the image is cut off? The reason the slider needs a fixed height is to make the slides look uniform.

You are free to change it to your own custom height but without it, each slide will have different heights.

**Comment by smotru** [comment]
Please see the problem here:
![Slider Problem](http://my.jetscreenshot.com/demo/20150126-8xtx-160kb.jpg)

**Comment by acburst** [comment]
Oh, this was a bug fixed on master but is not yet released I think. Did you say it was working when you recently forked?

**Comment by smotru** [comment]
I could not reproduce it on the forked version, yes. I'm really curious what was the fix since I've spent 20 mins trying to fix it myself :)

**Comment by acburst** [comment]
I wrote a javascript fix that detects the image width

**Comment by smotru** [comment]
I'll try to include the javascript file from the forked version, I'll tell you if this still persists.

**Comment by smotru** [comment]
I still have the same issue. I'll give you one more hint about my problem:
It happens more often if I use: 
```<img src="<?php echo bloginfo('template_url');?>/assets/images/slide.jpg">```

Instead of
```<img src="http://www.hanspeterporsche.com/files/hpptw/user_uploads/sammlung.jpg">```

but is exactly the same picture.

ps. i've sent you my skype address via email if you want to have a deeper look into it.

**Comment by acburst** [comment]
Hmm, it could have something to do with the order of things loading. Maybe Wordpress adds the image after the javascript tries to correct the width. I'm not sure though
