### ISSUE TITLE
Problem with sidenav (component:SideNav)

### ISSUE THREAD

**Issue by drycrushader** [Dogfalo/materialize#5243]
## Expected Behavior
Sidenav won't be opened after close sidenav with "pan / slide".

## Current Behavior
Sidenav will open and close immediately when open (with click not pan or slide) via menu button.
I even test it with "http://materializecss.com/", and the bug is there too.

## Possible Solution
What I've done so far to eliminate this issue is by adding `removeMenu();` on "panend" event before this line:
`// Slide menu closed`

## Steps to Reproduce (for bugs)

1. Click sidenav button to open sidenav.
2. Close sidenav by dragging or panning the overlay but don't drag more than 50% from your device width. You can do a fast slide, and it will be closed.
3. Then, click sidenav button again. You'll see that sidenav only opened for about 10 - 20px and then closed again. But if try to click sidenav button again, it will be opened normally.
So, the first click won't open it.

## Your Environment
* Version used: latest
* Browser Name and version: Chrome 61.0.3163.100 (Official Build) (64-bit)
* Operating System and version (desktop or mobile): Windows 10 x64

**Comment by Dogfalo** [comment]
Fixed in v1-dev
