### ISSUE TITLE
Request: Smarter autocomplete

### ISSUE THREAD

**Issue by ChildishGiant** [Dogfalo/materialize#5244]
At this point in time, autocompletesuggestions are ordered by the underlying JSON (In my case that's alphabetical) This means that if I enter Vi, DeviantArt and JustGiving come before Vimeo since they are alphabetically first.
![image](https://user-images.githubusercontent.com/13716824/31056020-688df034-a6c3-11e7-9cef-7b06a1adf28c.png)

I'm proposing that in this case Vimeo should come first since it starts with Vi. After that it could be alphabetical/using the JSON again. This'd help the element actually function as an autocomplete.

**Comment by Dogfalo** [comment]
This is the case in v1
