### ISSUE TITLE
Cannot set initial value of Timepicker following pickadate.js documentation

### ISSUE THREAD

**Issue by jfcere** [Dogfalo/materialize#5247]
## Expected Behavior
Following [pickadate.js API documentation](http://amsul.ca/pickadate.js/api/#method-set), we should be able to initialize the timepicker with a selected value like this:

```javascript
// Using arrays formatted as [HOUR,MINUTE].
picker.set('select', [3,0])
````

## Current Behavior
When trying to use `set()` method on the `picker` using Materialize CSS I get the following error:

```
Uncaught TypeError: picker.set is not a function
````

## Possible Solution
After taking a look at the original pickadate.js library, I noticed they do have the `set` method (of course) declared here [picker.time.js](https://github.com/amsul/pickadate.js/blob/master/lib/picker.time.js#L144).

When I look in to Materialize [picker.time.js](https://github.com/Dogfalo/materialize/blob/master/js/date_picker/picker.time.js) file included with Materialize, the `set` method is not declared.

## Steps to Reproduce (for bugs)
See [Plunkr](https://plnkr.co/edit/Y36KczvFkPLGTgffStfu?p=preview) for demonstration (open console to see the error)

## Context
Having a method to initialize the input value is pretty essential :)
Is there any plan to include more fonctionnality or update `picker.time.js` in Materialize repository?
Am I missing something?

## Your Environment
* Version used: 0.100.2
* Browser Name and version: Chrome 61.0.3163.100
* Operating System and version (desktop or mobile): Windows 10
* Link to your project (if appropriate): [Plunkr](https://plnkr.co/edit/Y36KczvFkPLGTgffStfu?p=preview)

**Comment by wendellpereira** [comment]
Happening the same here:
`angular.min.js:122 TypeError: timePicker.pickadate.set is not a function
    at eventInfoCtrl.vm.onUpdateEvent (eventinfo.controller.js:176)`

**Comment by wendellpereira** [comment]
I just realized that the timerPicker is not based in the PickaDateJs, but in the [ClockPicker](http://weareoutman.github.io/clockpicker/); as seeing in: materialize/js/date_picker/picker.time.js:

`/*!`
` * ClockPicker v0.0.7 (http://weareoutman.github.io/clockpicker/)`
` * Copyright 2014 Wang Shenwei.`
` * Licensed under MIT (https://github.com/weareoutman/clockpicker/blob/gh-pages/LICENSE)`
` *`
` * Further modified`
` * Copyright 2015 Ching Yaw Hao.`
` */ `

**Comment by jfcere** [comment]
So basically, I guess we have to initialize the time picker with `pickatime()` which is from pickadate.js but use ClockPicker to set the value and communicate with the API...

It seems to work with my updated [Plunker](https://plnkr.co/edit/QxHHA3972Ex3JxkUp0T4?p=preview).

Would be great to have some documentation on that matter.

**Comment by wendellpereira** [comment]
Exactly this.

**Comment by Dogfalo** [comment]
Timepicker is not based off pickatime, this will be made clear in the documentation updates coming with 1.0

**Comment by jfcere** [comment]
Thanks we figured it out.
I guess I should probably remove my PR then if it is already documented in 1.0 ...
