### ISSUE TITLE
jQuery Error on sideNav open

### ISSUE THREAD

**Issue by promijn** [Dogfalo/materialize#5253]
When I ope the sideNav I get the an error in the console:
`Uncaught Error: Syntax error, unrecognized expression: [name=]`

This happens with my own code, but also with copied example on the website
http://materializecss.com/side-nav.html

Any thoughts?

**Comment by tomscholz** [comment]
Fill out the ISSUE TEMPLATE and provide a codepen. Otherwise we are not going to look into this

**Comment by Dogfalo** [comment]
Closing until a codepen is provided
