### ISSUE TITLE
Materialize not defined

### ISSUE THREAD

**Issue by immertroll** [Dogfalo/materialize#5254]
Hello I try to use Materialize and jQuery this. The most simple solution but the label will not be updated with the `active` class.

The console sais that Materialize is not defined caused by jQuery. What is the problem. I can't see it. Thank you very much.

Codepen:
https://codepen.io/immertroll/pen/pWpgZd

**Comment by tomscholz** [comment]
You cannot use the slim version. https://codepen.io/tomscholz/pen/MErOze

**Comment by LuisPaGarcia** [comment]
Use jquery.min.js instead  jquery.slim.min.js.

**Comment by immertroll** [comment]
Thank you very much. Sometimes you can't see the forest for the trees. ;-)
Thank you a lot.

**Comment by anhkhoa91280** [comment]
For some reasons, you have to include jquery and materialize js files at the end of <body> tag as below

<!doctype html>
<html lang="en">
<head>  
    
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet"> 

    
    
    <link rel="stylesheet" href="assets/materialize/css/materialize.min.css">

    
    
    <script src="assets/materialize/js/materialize.min.js"></script>

    
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>

    <link rel="stylesheet" type="text/css" href="assets/themify-icons-font/themify-icons/themify-icons.css">
  <meta charset="utf-8">
  <title>Storkwhite</title>
  <base href="/">

  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="icon" type="image/x-icon" href="favicon.ico">
</head>
<body class="intro-2 home">    
  <app-root></app-root>
  
<script type="text/javascript" src="https://code.jquery.com/jquery-2.1.1.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/0.98.2/js/materialize.min.js"></script>  
</body>
</html>
