### ISSUE TITLE
Bug in radio button because its label is not clickable

### ISSUE THREAD

**Issue by Kianoosh76** [Dogfalo/materialize#5256]
Hi
I've recently updated my materialize to 0.100 and noticed that the radio buttons in my form are not functioning.
After so much try I realized that the label is not clickable and it is raised from the css file which sets `pointer-events: none` for `input-field label`
You can see the image for clarification:
![2017-10-06 20 21 26](https://user-images.githubusercontent.com/13102646/31289080-76a7a1dc-aad4-11e7-99ab-7cce9e000f07.jpg)

**Comment by Dogfalo** [comment]
checkboxes and radio buttons are not meant to be in input-fields which is meant for text inputs. We realize this was not entirely intuitive. We've reworked forms in v1 to solve this problem
