### ISSUE TITLE
characterCounter() doesn't work after dynamically adding

### ISSUE THREAD

**Issue by amovsisyan** [Dogfalo/materialize#5257]
Hi All
Question is about dinamically appending characterCounter part.
Yes I know that I should initialize after dynamically adding, but it doesn't work 
my input parts adding dynamically like this 

```
var clone = SMTHING.cloneNode(true);
clone.getElementsByClassName('sm-class')[0].innerHTML = 'smth';
.
.
SOMETHINGELSE.appendChild(clone);
```

good, but 
before appending `$(clone).find('#textarea1').characterCounter();`
or after appending `$('#textarea1').characterCounter();`
it doesn't work 
it works correctly when I doesn't add dynamically,
Also I can see the added span.character-counter  , but js part (on focus or on blur) doesn't work , 

thanks in advance

**Comment by developeranirudhprabhu** [comment]
Hi @amovsisyan Can you share a code pen for this? May be i can help you

**Comment by amovsisyan** [comment]
Hi @developeranirudhprabhu 
thanks for response and sorry for delay 
[https://jsfiddle.net/vtzapt0g/4/](characterCounterJSFIDDLE)
does this have the info you asked ?

**Comment by developeranirudhprabhu** [comment]
Hi @amovsisyan let me check and get back

**Comment by developeranirudhprabhu** [comment]
@amovsisyan I found the issue that was stopping dynamic initialisation of the plugin and have provided a pull request. Kindly have a look at the suggested changes

**Comment by developeranirudhprabhu** [comment]
@amovsisyan i have checked that this issue is not seen in v1. So with the new release this should work flawlessly

**Comment by amovsisyan** [comment]
hi @developeranirudhprabhu 
thanks for update , will check woon and let you know
