### ISSUE TITLE
fixed side-nav seems misaligned since ver 0.97.6

### ISSUE THREAD

**Issue by rikyperdana** [Dogfalo/materialize#5266]
I made a side-nav menu with ver 0.100.2 and this is how it looks like. Everything is misaligned
![with 0 100 2](https://user-images.githubusercontent.com/11875540/31452236-865d231a-aed8-11e7-8e8c-796842e25c00.png)

But when I revert it back to 0.97.6, everything is back and fine
![with 0 97 6](https://user-images.githubusercontent.com/11875540/31452069-104ddaca-aed8-11e7-8e17-e7fd948f0b22.png)

And now I'm stuck with the old version which don't provide material modal. What should I do?

**Comment by tomscholz** [comment]
You should read our contributing guidelines
