### ISSUE TITLE
Slide 'method does not exist' message is wrong

### ISSUE THREAD

**Issue by G-Rath** [Dogfalo/materialize#5269]
https://github.com/Dogfalo/materialize/blob/da2376efd2f749aa1616f6803e1a173ded342f46/js/slider.js#L321

From my understanding, this should read `on jQuery.slider`, not `on jQuery.tooltip`.

**Comment by Dogfalo** [comment]
Fixed here: ced8318fd0aab674b50e7605816b427d91a10ef1
