### ISSUE TITLE
Materialize Select not render when do the page responsive

### ISSUE THREAD

**Issue by JockerGG** [Dogfalo/materialize#5274]
Following the documentation I wrote the select tags as follows:

```
<div class="row" id="sub1">
        <div class="input-field col s12" id="ds1">
          <select name="s1" id="s1" required>
            <option value="" disabled selected>Elige una opción</option>
          </select>
          <label>Subcategoría 1</label>
      </div>
    </div>

```
in my <script> i wrote :

`$( "#s1" ).material_select();
`
and in a normal page the select looks like this: 

![image](https://user-images.githubusercontent.com/6700974/31504454-1208d68e-af38-11e7-997f-0173e7757e22.png)

but when I make my page responsive and refresg the page the select looks like this: 

![image](https://user-images.githubusercontent.com/6700974/31504993-71478554-af39-11e7-95d7-fd418e26f4cd.png)

Can you help me with this.

Thanks!

**Comment by Dogfalo** [comment]
wrap your code in a document.ready function in jQuery

**Comment by JockerGG** [comment]
the code is into document.ready

![image](https://user-images.githubusercontent.com/6700974/31509675-f56cf216-af47-11e7-986c-52a042eb0135.png)

**Comment by JockerGG** [comment]
and the problem continues

**Comment by Dogfalo** [comment]
Then if you believe there is a bug with the library, please make a codepen illustrating it
