### ISSUE TITLE
Scrollspy does not move with scroll

### ISSUE THREAD

**Issue by reyou** [Dogfalo/materialize#5277]
## Expected Behavior
http://materializecss.com/scrollspy.html
Scrollspy table of contents should scroll along with scroll down/up. 

## Current Behavior
Scrollspy table of contents sticks where it is initialized.

## Possible Solution
Maybe fixed position can be added corresponding class?

## Steps to Reproduce (for bugs)

See live demo at https://codepen.io/anon/pen/qPyzgz 
 
## Your Environment
Windows 10
Chrome Version 60.0.3112.113 (Official Build) (64-bit)

## Sources
https://cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.min.js
https://cdnjs.cloudflare.com/ajax/libs/materialize/0.100.2/js/materialize.min.js
https://cdnjs.cloudflare.com/ajax/libs/materialize/0.100.2/css/materialize.min.css

**Comment by Nemental** [comment]
Hello reyou,
my solution is this: https://codepen.io/anon/pen/wrRXrP
You can try this with your code, I hope it works! :)

**Comment by reyou** [comment]
Hello @Dogfalo, could you please let me know why this is closed? It this a wrong/invalid issue?

**Comment by Dogfalo** [comment]
This is just a How-to question and not a bug, look at the Pushpin plugin, that is what you need.

**Comment by AndriyGo** [comment]
@Dogfalo I am struggling with this issue myself. I am using materialize v1 and followed the setup instructions for scrollspy. However, it doesn't scroll. The pushpin plugin lists instructions for jquery which I am not using.

**Comment by ValeriZamulin** [comment]
https://materializecss.com/pushpin.html
