### ISSUE TITLE
Too many select options can't select the last few options

### ISSUE THREAD

**Issue by recallhyx** [Dogfalo/materialize#5278]
I have encounter a problem ：I dynamic generate option in my web,but it has too many option and I found that I can't select the last few options , and more stranger , the last few options can be selected on mobile phone
Just like this on pc :
![image](https://user-images.githubusercontent.com/23056574/31529017-1a69a584-b009-11e7-98d7-b7186ff88204.png)
It can't select the last few options
Here is my website :
http://recallhy.xin:8080/homework/homework.jsp

**Comment by devansh1110** [comment]
You can use `.browser-default` for the time being, until this issue is confirmed/fixed. 

Thanks,
Devansh

**Comment by Dogfalo** [comment]
Fixed in v1-dev
