### ISSUE TITLE
Tabs Footer Issue

### ISSUE THREAD

**Issue by vilinfield** [Dogfalo/materialize#528]
- On mobile tabs have to be done differently to prevent overlapping such as aligned vertically
  This needs to be addressed 
- While using tabs the Footer stays under the content and not directly on the bottom in some cases

**Comment by acburst** [comment]
1: According to Material Design principles, tabs should never be vertically aligned. If you cant fit tabs neatly in a mobile setting, you should use a different component to organize your content, like a Dropdown or something else.

2: We will look into this

**Comment by vilinfield** [comment]
Thanks. Would you have a suggestion for better mobile navigation?

**Comment by yutarochan** [comment]
How about using a pagination based method of displaying a mobile navigation?
Something similar to this: https://material.angularjs.org/#/demo/material.components.tabs

**Comment by tomscholz** [comment]
@vilinfield I can't seem to reproduce the second problem, can you post a codepen that illustrates the issue? Anyhow, I will close this issue for now :)
