### ISSUE TITLE
Checkbox

### ISSUE THREAD

**Issue by Teh64** [Dogfalo/materialize#5280]
First off I just wanted to say I'm new to GitHub Issues and I'm sorry if I did this wrong. But I was looking through the checkbox designs, and realized the effects don't work with my browser. Check out my Material Checkboxes [Here](https://teh64.github.io/md-chk) and email me at teh.picix@gmail.com if you would like to add them to Materialize.

Thanks in advance.

**Comment by Dogfalo** [comment]
We aren't interested sorry.
