### ISSUE TITLE
unsupported pseudo: valid

### ISSUE THREAD

**Issue by jack2ky** [Dogfalo/materialize#5281]
I have a textarea in IE and when I click on it it shows error : `Syntax error, unrecognized expression: unsupported pseudo: valid` 
<textarea id="review_text" class="materialize-textarea validate" autocomplete="off" minlength="50" maxlength="1500" data-length="1500" pattern=".{30,1500}"></textarea>

using <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/0.100.1/js/materialize.js"></script>

I'm using IE11

```
          object.removeClass('invalid');
        }
      } else {
        if (object.hasClass('validate')) {
          // Check for character counter attributes
          if (object.is(':valid') && hasLength && len <= lenAttr || object.is(':valid') && !hasLength) {
```

**Comment by acburst** [comment]
The current version is 0.100.2

**Comment by developeranirudhprabhu** [comment]
@jack2ky Can you use the current version and share it on codepen or so?

**Comment by jack2ky** [comment]
I moved passed this. sorry I forgot what I did. I think it was because of this.
`<!--<META http-equiv="X-UA-Compatible" content="IE=9"> -->`
