### ISSUE TITLE
modal.js: nested modals

### ISSUE THREAD

**Issue by mche** [Dogfalo/materialize#5282]
One modal inside other modals didnt shows through overlay.

## Expected Behavior
 Nested modals must be shown.

## Current Behavior
Codepen [here](https://codepen.io/anon/pen/EwOpKZ) 

## Possible Solution
Move modal element to document.body if it has closest('.modal').length

(after the current [line code](https://github.com/Dogfalo/materialize/blob/master/js/modal.js#L294))

```
      if (this.$el.closest('.modal').length) body.appendChild(this.$el[0]);
```

Regards

**Comment by mche** [comment]
Oh, sorry solution, classname can be diffrent.

**Comment by mche** [comment]
`if (this.$el.parents().filter(function(){  return $( this ).css('position') == 'fixed'; }).length) $("body").append(this.$el);`

**Comment by mche** [comment]
find parents positions: fixed || absolute || ?

**Comment by Dogfalo** [comment]
Why don't you fix the nesting in your own code? 

All I did here was place the second modal outside of the first one: https://codepen.io/Dogfalo/pen/aLXORo

**Comment by mche** [comment]
Because, according to modern component style programming modals come up inside own component.

Dont worry, I did my fix.
