### ISSUE TITLE
Utilize html5 <section> tag

### ISSUE THREAD

**Issue by petri** [Dogfalo/materialize#5286]
HTML5 has added several useful tags that provide improved semantic structure to HTML, such as the `<section>` tag.

It would be good to be able to use that as an alternative or replacement to `<div class="section">` .

**Comment by Dogfalo** [comment]
If you wish to create a pull request fixing this, we can look into merging it. But as it stands, it is not really causing enough of a problem to warrant us to spend time changing it.
