### ISSUE TITLE
Utilize <hr/> tag instead of <div class="divider"></div>

### ISSUE THREAD

**Issue by petri** [Dogfalo/materialize#5287]
The `<hr/>` tag has been defined in html5 as having a semantic meaning of 'thematic break', ie. a divider. It would make sense to use that as an alternative or replacement to ` <div class="divider"></div>`.

**Comment by idealadarsh** [comment]
@petri I'd like to work on this project.

**Comment by tomscholz** [comment]
You can use the .divider class on `<hr/>` tags.

**Comment by penguoir** [comment]
Couldn't you just use the `.divider` class on an `<hr>` element?
```html
<hr class="divider" />
```
