### ISSUE TITLE
Add feature to collapse FAB programmatically

### ISSUE THREAD

**Issue by Saggar112** [Dogfalo/materialize#5288]
Hi there, I am trying to close a Fixed Action Button programmatically, but cannot seem to do so.
This is different from the click-to-toggle class, because although it enables the programmatic behaviour, it requires a click to open, which I do not want.

The behaviour I am requesting is that the FAB open on hover, close when the mouse leaves (these 2 things already happen), and also be able to be closed through Javascript. What I am trying to accomplish is have a button inside the FAB, which will close the FAB when it is clicked. The button inside the FAB also has a tooltip.

It would be the same as the currently existing closeFAB function, but should work on FABs that open/close on hover as well, not just click-to-toggle ones.

Example markup of FAB with button inside to close FAB.
```
<div id="action-button" class="fixed-action-btn">
    <a class="btn-floating btn-large waves-effect waves-light black"><i class="large material-icons">mode_edit</i></a>
    <ul>
      <li><a id="cancel-button" class="btn-floating red tooltipped" data-tooltip="Clear your selection" onclick="$('action-button').closeFAB()"><i class="material-icons">cancel</i></a></li>
    </ul>
</div>
```

Thank you very much for your help.

**Comment by acburst** [comment]
Made FAB a plugin with more robust programmatic options in af660d37.
This will be available in v1.
