### ISSUE TITLE
Materialize.objectSelectorString is not a Function

### ISSUE THREAD

**Issue by Crowes** [Dogfalo/materialize#5289]
## Expected Behavior
I've literally only called .sideNav(). I'm assuming this is something to do with initialisation.

## Current Behavior
![image](https://user-images.githubusercontent.com/13123486/31855436-45ad100a-b6a3-11e7-8ab1-5cd173d917c4.png)

## Steps to Reproduce (for bugs)

1. Use Materialize through NPM, in an Electron window.
2. Set window.$, window.Hammer, and window.Materialize to the appropriate dependencies.
3. Run the Electron app.

## Context
I created my design in Brackets with linked dependencies to a CDN beforehand. It worked completely fine.

**Comment by Crowes** [comment]
Solution: https://github.com/electron/electron/issues/254

**Comment by Dogfalo** [comment]
We've removed the need for these dependencies in 1.0 alpha so this shouldn't be a problem in the future
