### ISSUE TITLE
"Round" wave not working in Safari

### ISSUE THREAD

**Issue by JasperVercammen** [Dogfalo/materialize#529]
When you have a round button (like the floating button) the ripple goes out of the round in Safari. 
See the images for the difference in chrome and Safari:
![ripple_chrome](https://cloud.githubusercontent.com/assets/2750271/5901679/9edc00b6-a574-11e4-819f-a839df6a3edf.png) ![ripple_safari](https://cloud.githubusercontent.com/assets/2750271/5901685/b056cb50-a574-11e4-9972-0dc7b8a56a89.png)

I'm working on OSX Yosemite 10.10.1, chrome version 39.0.2171.99 and Safari version 8.0.2
I've changed nothing in the code, just a copy of the examples.

**Comment by acburst** [comment]
Its not currently in our documentation which I will fix but to you need to add the  ```waves-circle``` class to your circular floating buttons

**Comment by acburst** [comment]
Added in docs in 1f11a1dfd4a30aace2777a11aa713d5e114e0a48
