### ISSUE TITLE
select browser-default

### ISSUE THREAD

**Issue by neokeats** [Dogfalo/materialize#5294]
Hi, 
with version 0.100.2
there is an issue with selects that have class set to browser-default

![image](https://user-images.githubusercontent.com/148858/31879357-7ca910b4-b7dd-11e7-8c9f-0d76ec16d533.png)

It seems that the opacity and positionning of the materialize behaviour are still applied, resulting on the selects not shown...

**Comment by tomscholz** [comment]
Are you still trying to initialize the select?

**Comment by neokeats** [comment]
the html/js is exactly the same as before (0.98.1). basically just class="browser-default"
for it to still working with 0.100.2  the workaround is to add to custom.css: 

```
select.browser-default {
    position: static;
    pointer-events: all;
    opacity: 1;
    background-color: rgba(255,255,255,0.9) !important;
    width: 100% !important;
    padding: 5px !important;
    border: 1px solid #f2f2f2 !important;
    border-radius: 2px !important;
    height: 3rem !important;
}
```

**Comment by tomscholz** [comment]
Could you please post a codepen that illustrates your issue? I think I know where the problem in your code is. Also make sure to read our [Contributing guidelines](https://github.com/Dogfalo/materialize/blob/master/CONTRIBUTING.md) and next time make sure to fill out the [issue template](https://github.com/Dogfalo/materialize/blob/master/.github/ISSUE_TEMPLATE.md)!

**Comment by ray007** [comment]
Current `v1-dev` status (`alpha-3`) shows the select tag and a materialize rendering in the DOM.

**Comment by ray007** [comment]
Changing the selector `.input-field select` to `.input-field select:not(.browser-default)` in `materialize.css` fixes this.
Wrapping with a `<div class="select-wrapper">` is still needed.
Want/need a PR for this?

**Comment by Dogfalo** [comment]
#5176
