### ISSUE TITLE
.flow-text should not have font-weight specified

### ISSUE THREAD

**Issue by IAMtheIAM** [Dogfalo/materialize#5296]
This tag is applied in [_typography.scss](https://github.com/Dogfalo/materialize/blob/master/sass/components/_typography.scss#L48)

```
.flow-text {
    font-weight: 300;
}
```

However it doesn't make sense. There is already `.thin` and `.light` classes which allow a user to set font-weight conditionally. 

The user should determine the font-weight in their own stylesheet, not the framework. Mainly because a user may want to use flow-text where `h1-h6` tags occur, which effectively removes the bold from all `h1-h6` tags. This forces setting font weight on them using `!important` which is not a good practice, or override it by explicitly setting 

```scss
h1 {
      font-weight: 700;
      &.flow-text {
         font-weight: 700;
   }
}
```
which is redundant and overly verbose.

# Proposed solution
Remove the font-weight declaration from .flow-text all together.

**Comment by IAMtheIAM** [comment]
I can make a PR if this is approved suggestion, let me know.

**Comment by Dogfalo** [comment]
Removed in b34f1dff8fa6a966b7fc7a26af417cc8845d9141
