### ISSUE TITLE
Navbar not collapsing (only sometimes)

### ISSUE THREAD

**Issue by urecio** [Dogfalo/materialize#530]
You can see the bug here: http://materializecss.com/navbar.html
Steps to reproduce: 
* resize the window enough to start seeing the menu icon
* Click on it

It will show the sidenav
* try to hide it by clicking on the right half of the page

**It won't collapse.**
This is only happening with the main sidenav of the site and in this page. If you try on another page or with the button of the last example, it works.

**Comment by acburst** [comment]
Fixed in c87b47dc1fe9119d31b4ae52b70ce58cf32ddb98
