### ISSUE TITLE
Select dropdown does not work in container with overflow-y:hidden

### ISSUE THREAD

**Issue by kiwo12345** [Dogfalo/materialize#5303]
I have a container with this css in order to make it scrollable sideways and not up and down.

`overflow-y: hidden;  overflow-x: scroll;`

But now my materializecss <select> dropdown wont work, it gets clipped instead of showing outside  the container. 

I have both tried **overflow-y: visible;** but this will make the container scrollable in all directions which I dont want. I also tried to up the `z-index` on the dropdown and lower it on the container but no luck.

![bs](https://user-images.githubusercontent.com/10579811/32033591-93a38e16-ba0d-11e7-9184-f6488bddf08a.png)
![bs](https://user-images.githubusercontent.com/10579811/32033623-be4f1fd6-ba0d-11e7-85ba-9e4cde1ad2d4.png)

**Comment by developeranirudhprabhu** [comment]
@kiwo12345 Can you please share a codepen for same?

**Comment by acburst** [comment]
Container option added in 42aa7476.

You can specify `document.body` as the container of the dropdown to pull the dropdown out of the modal.

**Comment by timothymarois** [comment]
I'd like to point out this did not work at least not for my materialize select box dropdown. Using the container option. Is this fix specific to a version? I'm currently on `v0.99.0`
