### ISSUE TITLE
Tabs active class

### ISSUE THREAD

**Issue by sahina** [Dogfalo/materialize#531]
When tabs with active class loads as shown, the active applies to left aligned location by default. After clicking a tab, active applies correctly.

![tabs](https://cloud.githubusercontent.com/assets/2219825/5903249/95ad827e-a54e-11e4-9817-fdf8e91a0671.png)

**Comment by acburst** [comment]
The issue here is because you still have s3 defined on your tabs, so the indicator is adjusting to the initial width. If you update those cols to have s4 it should work.

**Comment by sahina** [comment]
Doh! Thanks.
