### ISSUE TITLE
sideNav: destroy doesn't remove resize event

### ISSUE THREAD

**Issue by ruant** [Dogfalo/materialize#5311]
## Expected Behavior
Resize event should be removed when sideNav('destroy') is called

## Current Behavior
Even after destroy has been called the resize event is being fired on window resize.

## Possible Solution
Remove the resize event in destroy.
This solution can be used:
https://stackoverflow.com/a/13268437/4334577

## Your Environment
* Version used:
* Browser Name and version: Chrome Version 61.0.3163.100 (Official Build) (64-bit)
* Operating System and version (desktop or mobile): Windows 10

**Comment by Dogfalo** [comment]
Fixed in 1.0 https://github.com/Dogfalo/materialize/blob/v1-dev/js/sidenav.js

**Comment by ruant** [comment]
Yes, I just saw that now 👍 

However, I forked and fixed in in my fork to get my project working.
PR is made if you want to merge it, but I recon v1 is so close that it's not needed.  
https://github.com/Dogfalo/materialize/pull/5312

Keep up the good work! 😃
