### ISSUE TITLE
autocomplete url?

### ISSUE THREAD

**Issue by CatalinRadoi** [Dogfalo/materialize#5314]
I've checked the .js and I've seen no implementation for an autocomplete with url. Really? =)

**Comment by penguoir** [comment]
Could you explain the expected behaviour?

**Comment by fnowacki** [comment]
@penguoir I understand point of @CatalinRadoi's view. He want download data field in autocomplete from 3rd party source e.g. ajax. I got the same problem.

**Comment by bassie1995** [comment]
This has been an issue for a long time, and there's already an issue on this. See https://github.com/Dogfalo/materialize/issues/4086...

**Comment by tomscholz** [comment]
Duplicate of #4086 @Dogfalo Please close
