### ISSUE TITLE
Web site should not recommend href="#!" for dropdown menus

### ISSUE THREAD

**Issue by jouvin** [Dogfalo/materialize#5321]
The documentation (web site) about the [navbar](http://materializecss.com/navbar.html) suggests to define `href="#!"` for the anchor adding the dropdown arrow. I think the correct recommendation would be to omit `href` in this context as it is not required (see [W3 cos](http://w3c.github.io/html/links.html#links-created-by-a-and-area-elements)). The current suggestion creates a non-existent reference (this is the goal!) that is considered as an error by HTML checker like `html-proofer`.

**Comment by DanielRuf** [comment]
This should be ok. Future versions may use preventDefault. But this is the approach to solve it without JavaScript.

**Comment by jouvin** [comment]
@DanielRuf I'm not sure to understand your reply? Do you mean that my suggestion to remove the `href=#!` should be ok? Or that `html-proofer` will be able to deal with this in the future (as for now if can only deal with `href=#` to go to the top of the page? The whole point, AFAIK, is that `href=#!` is coming from old version of HTML but that in HTML v5, there is no reason to define a `href` attribute in a `<a>` element if you don't want to create an hyperlink. In this particular case of dropdown menus, the `<a>` element is processed by the CSS but its action is to trigger the dropdown menu, not to open an hyperlink.

**Comment by DanielRuf** [comment]
You are free to add `return false` or `preventDefault`. It's not forbidden to use the hashbang afaik.

**Comment by Dogfalo** [comment]
Please help make a pull request for this so we can fix it
