### ISSUE TITLE
Error Minifying Modal.js using Closure Compiler

### ISSUE THREAD

**Issue by lyh424** [Dogfalo/materialize#5329]
Using Google's Closure Compiler, I get the following error with trying to minify modal.js:

"JSC_CANNOT_CONVERT: This code cannot be converted from ES6. ES5 getters/setters (consider using --language_out=ES5)"

The part in question that triggers the error (line 72):

`    static get defaults() {
      return _defaults;
    }
`

You can reproduce the error here: https://closure-compiler.appspot.com/

**Comment by Dogfalo** [comment]
Our code is transpiled to ES5 through babel.
