### ISSUE TITLE
Cannot tap out of an open tap target (feature discovery) on iOS Safari

### ISSUE THREAD

**Issue by kileyhykawy** [Dogfalo/materialize#5330]
## Steps to Reproduce (for bugs)
1. On an iOS device, open Safari and go to http://materializecss.com/feature-discovery.html
2. Tap on the 'open tap target' button so the tap target opens
3. Tap anywhere else other than the "target" button of the tap target

## Expected Behavior
When you tap on the page, it should close the tap target (this happens successfully on Android Chrome, OSX Safari and OSX Chrome)

## Current Behavior
The tap target is not closed unless you actually click on the button that is the "target" of the tap target

## Possible Solution
Maybe related to #2319 where tap out only reacts to `click` events but those don't happen on iOS?

## Your Environment
* Version used: 0.100.2
* Browser Name and version: Safari on iOS 11.0
* Operating System and version (desktop or mobile): Mobile iOS 11.0

**Comment by Dogfalo** [comment]
Fixed in afdb12a
