### ISSUE TITLE
tabs indicator disapper when route change

### ISSUE THREAD

**Issue by recallhyx** [Dogfalo/materialize#5333]
I encounter a problem ,the tabs indicator is normal at first but when I change the route and change back, the tabs indicator will disappear,
first time it is normal:
![default](https://user-images.githubusercontent.com/23056574/32321341-c3b8535e-bffb-11e7-8d07-2f2151efa6a4.png)
after changing route and go back:
![default](https://user-images.githubusercontent.com/23056574/32321374-e14a7a28-bffb-11e7-968e-4ffd01733a9b.png)
the indicator disapper

**Comment by BonfaceKilz** [comment]
Same here. Have you found a solution?

**Comment by recallhyx** [comment]
sorry ,I  haven't found the solution yet

**Comment by Dogfalo** [comment]
This happens whent he tabs are initialized when it is not visible, so the indicator can't be positioned correctly. There is now a function to call that updates the tab indicator position `updateTabIndicator()`. 67b147997f8657a538f25ca21ec48a151915a969
