### ISSUE TITLE
Multiple checkbox select

### ISSUE THREAD

**Issue by andreintm** [Dogfalo/materialize#5335]
I am using materializecss v0.100.2 and I have an issue with select.
How to fix it?
![screen shot 2017-11-03 at 11 11 28](https://user-images.githubusercontent.com/2091718/32366776-55da9e9a-c088-11e7-871e-bece7aac97e1.png)

here is my html:

               <div class="input-field col s6">

                    <select multiple>

                        <option value="" disabled selected>Choose your option</option>

                        <option value="1">Option 1</option>

                        <option value="2">Option 2</option>

                        <option value="3">Option 3</option>

                    </select>

                    <label>Groups</label>

                </div>

**Comment by smileytechguy** [comment]
Can you please make a codepen? I am unable to reproduce your issue

**Comment by developeranirudhprabhu** [comment]
@andreintm can you create a codepen and share it here? That would be helpful

**Comment by andreintm** [comment]
Sorry, that was my fault. I set 100% width for labels.
