### ISSUE TITLE
Datepicker mobile (iOS)

### ISSUE THREAD

**Issue by WouterGoossenss** [Dogfalo/materialize#5339]
My datepicker is not showing properly on iPad (running iOS 10) and iPhone (running iOS 11) while on desktop it is working fine.

![img_0357](https://user-images.githubusercontent.com/33450561/32488827-436a5a92-c3ae-11e7-9802-0454638f9e4f.PNG)

**Comment by Dogfalo** [comment]
Provide a Codpen as the Issue template states.
