### ISSUE TITLE
Card Reveal Not Covering Entire Image

### ISSUE THREAD

**Issue by nahtnam** [Dogfalo/materialize#534]
Hey! I found a bug!

Basically if you create card reveal and put less than one line of text, it only covers part of the image...

EX:

![](http://i.imgur.com/muM2TtK.png)

**Comment by nahtnam** [comment]
One other bug.

Create a reveal card, press the image and bring up this screen: http://i.imgur.com/EN1fDlj.png

Then click anywhere else on the screen. I would expect that it minimizes, but it doesnt.

Hope that makes sense.

**Comment by acburst** [comment]
Hmm, can I see your code? I'm pretty sure we make the card reveal stretch to fit the card always.

**Comment by acburst** [comment]
Also we do not intend to make it close by clicking elsewhere on the screen because it doesn't interfere with any part of the page while it is open. This is by design and can be seen on google sites.

**Comment by nahtnam** [comment]
https://gist.github.com/nahtnam/e57b3065a697f114ad9a
