### ISSUE TITLE
[1.0.0-alpha.1] Select with circle image not working 

### ISSUE THREAD

**Issue by quienti** [Dogfalo/materialize#5343]
## Expected Behavior

Select with circle image working

## Current Behavior

Select with circle image not working

## Steps to Reproduce (for bugs)

Just see doc
http://next.materializecss.com/select.html

**Comment by SamWillson** [comment]
The problem is that the class applied to the option is not being inherited to the List Item that is being generated.

**Comment by Dogfalo** [comment]
This functionality has been removed. The select will no longer copy the class attribute on each <option> el to the <img> for the icon in the generated select.

**Comment by quienti** [comment]
So, maybe you should delete that from the doc?
