### ISSUE TITLE
The search bar in the documentation redirects to the old documentation

### ISSUE THREAD

**Issue by JuanJoseGonGi** [Dogfalo/materialize#5345]
When you search for something in the search bar and click on it, **it opens [materializecss.com](http://materializecss.com) instead of [next.materializecss.com](http://next.materializecss.com)**

**Comment by MorganMarshall** [comment]
The "Get Started" button also goes to old materializecss instead of next

**Comment by acburst** [comment]
Fixed in cc87d218
