### ISSUE TITLE
Sidenav not working

### ISSUE THREAD

**Issue by scriptify2** [Dogfalo/materialize#5346]
The Sidenav is not working even on the new Starter Template Provided there  were always Null Errors

Uncaught TypeError: Cannot read property 'M_Sidenav' of null at HTMLBodyElement._handleTriggerClick (materialize.js:5479) 
_handleTriggerClick @ materialize.js:5479

![unbenannt](https://user-images.githubusercontent.com/33605148/32702093-9313ba8e-c7e1-11e7-837c-534c12db8a04.PNG)

**Comment by Dogfalo** [comment]
What version?

**Comment by matugm** [comment]
You can see the error on this page:

http://next.materializecss.com/templates/starter-template/preview.html

Stretch the page until the menu shows & then click to reproduce.

**Version**: 1.0.0 Alpha-1

**Comment by matugm** [comment]
I get this error with Firefox using 1.0.0 Alpha-1:

```javascript
Empty string passed to getElementById().  materialize.js:5479:32
```

I did some debugging I found out the problem:

The function ` getIdFromTrigger` expects the ` data-target`  attribue to be available, but the documentation example uses ` data-activates` .

Changing ` data-activates` to ` data-target` fixed this error & the menu is working.

**Comment by peecaboo** [comment]
Same issue on 1.0.0 Alpha-1. Should we get back to .100?

**Comment by matugm** [comment]
@peecaboo Try changing your `data-activates` attribute on the `sidenav-trigger` class element to `data-target`. I believe that will fix the problem for you.

Here's a picture:

![image](https://user-images.githubusercontent.com/1369748/32725655-3c507706-c876-11e7-8b7c-29a4ca358f0b.png)

https://github.com/Dogfalo/materialize/blob/v1-dev/js/global.js#L261

**Comment by peecaboo** [comment]
@matugm It worked! You are a real savior. I thank you

**Comment by xsama** [comment]
@matugm  I thank you too  XD

**Comment by Dogfalo** [comment]
This is already the case in the newest templates

**Comment by stefancata92** [comment]
@
<img width="2382" alt="screenshot at apr 18 17-03-14" src="https://user-images.githubusercontent.com/22393523/38936844-6e1c2c60-432a-11e8-96a8-a7f2c3c986f2.png">

same error even if i have data-target.... any ideas ?

**Comment by Dogfalo** [comment]
@stefancata92 Please create a new issue illustrating your example with a Codepen

**Comment by hanssonfredrik** [comment]
@stefancata92 you get this error message if you have another id on your side menu. Make sure you are using mobile demo on both places.

<a href="#!" data-target="mobile-demo" ... ></a>

<ul id="mobile-demo">

**Comment by irisbune** [comment]
Have the same issue and noticed this:
![](https://img.springe.st/20190119-dhmiy.png)

Am I missing something here? 

My html : 

```
<nav>
  <div class="nav-wrapper">
    <a class="brand-logo" href="/">Name</a>
    <a data-target="mobile-demo" class="sidenav-trigger" href="#">
      <i class="material-icons">menu</i>
    </a>
    <ul class="right hide-on-med-and-down" id="nav-mobile">
      .. li elements ..
    </ul>
  </div>
</nav>
```

**Comment by darqwski** [comment]
i've got this error, but only in situation when trigger={element} was not <a/>
Try to wrap your trigger component into <a> link :
<a><Icon>menu</Icon></a>

**Comment by krishmodi** [comment]
Still giving me a problem

**Comment by GeorgesGITHUB** [comment]
This issue is still not resolved

**Comment by pwcreative** [comment]
@GeorgesGITHUB live example or codepen please, so we can help.

**Comment by gatallahx** [comment]
> @GeorgesGITHUB live example or codepen please, so we can help.

nvm, it was a simple mistake. Works good

**Comment by sazzad-sat** [comment]
Try to set the id attribute in sidenav ul

```html
<div>
    <ul class="sidenav" id="left-sidebar">
        <li><a href="/">Home</a></li>
        <li class="active"><a href="/">QA Bank</a></li>
        <li><a href="#">Blog</a></li>
    </ul>
</div>
```

**Comment by ArtyPrince-01** [comment]
> I get this error with Firefox using 1.0.0 Alpha-1:
> 
> ```js
> Empty string passed to getElementById().  materialize.js:5479:32
> ```
> 
> I did some debugging I found out the problem:
> 
> The function ` getIdFromTrigger` expects the ` data-target` attribue to be available, but the documentation example uses ` data-activates` .
> 
> Changing ` data-activates` to ` data-target` fixed this error & the menu is working.

ua a star,l got it

**Comment by ArtyPrince-01** [comment]
bravo
