### ISSUE TITLE
Many bugs with Datepicker [1.0.0-alpha.1]

### ISSUE THREAD

**Issue by multiwebinc** [Dogfalo/materialize#5352]
I'm testing out 1.0.0-alpha.1 and noticed a few issues with the datepicker. I'm using Opera on Linux in case that makes any difference:

- [x] `format` option does not work: https://codepen.io/multiwebinc/pen/pdwNqK (output for me: https://imgur.com/a/tnWJc)
- [x] Selecting months/years from the dropdown has no effect
- [x] Selecting today's date renders the date number invisible
- [x] Selecting any date produces errors in the console: https://imgur.com/a/ChjmS
- [x] Vertical screen real estate is wasted: https://imgur.com/a/qGe5Q
- [x] Setting an `onSelect` function produces an error when selecting: https://codepen.io/multiwebinc/pen/BmZpxP
- [x] Does not play well with `<input type="date">`: https://imgur.com/a/L3266 (source: https://codepen.io/multiwebinc/pen/wPegQQ)
- [x] Using a Date object to set the minimum date sets it off by one day: https://codepen.io/multiwebinc/pen/EbXWVW (output for me: https://imgur.com/a/WJMil)

**Comment by Dogfalo** [comment]
Thanks for the detailed report with examples.

**Comment by bmla** [comment]
Selecting months and year:
https://imgur.com/a/zCQDz

**Comment by Dogfalo** [comment]
`format` option has been fixed and updated with documentation: 1f7f03489edd023c3962dd8966b44d8a356a81c4

**Comment by multiwebinc** [comment]
@bmla I was actually in the process of posting that very thing. pickadate.js puts the scroll on the entire overlay, not just the calendar, which I think is more intuitive and would probably fix the bug you mention as well as the wasted screen real estate point I mentioned earlier.

**Comment by Dogfalo** [comment]
> Does not play well with <input type="date">
Similar to the previous version, the datepicker is meant to work with type="text" only

**Comment by bassie1995** [comment]
The popup has been an issue for while now, in Selects too. It should just overlay everything instead of pushing all of the stuff under it down.

**Comment by multiwebinc** [comment]
> Similar to the previous version, the datepicker is meant to work with type="text" only

What about this? If it's `type="date"` use JS to change it to `type="text"`, and that way it would even work as expected for browsers with JS disabled.

**Comment by DanielRuf** [comment]
`type="date"` should be used by default

**Comment by obama** [comment]
why cant you input with keyboard like in the firefox `type="date"` input? 
there is dis oddity that the input field is still focused after opening the datepicker and you can type and than a click on the datepicker will update it to the inputed date. but it would be better if the UI of the datepicker would respond directly

**Comment by multiwebinc** [comment]
@obama As you'll notice from @Dogfalo's comment above:

> Similar to the previous version, the datepicker is meant to work with type="text" only

**Comment by Dogfalo** [comment]
Fixed select issue in datepicker where years and months did not update 309e932e89ca40140a6badf23809a1960bcc391e

**Comment by bmla** [comment]
> "We use a modified version of pickadate.js"

Why not implement the d format? (http://amsul.ca/pickadate.js/date/#formatting-rules)

**Comment by bmla** [comment]
> "We use a modified version of pickadate.js"
Why not implement the d and m format? (http://amsul.ca/pickadate.js/date/#formatting-rules)
Currently dd and mm function as d and m respectively. This only leads to confusion :)

https://en.wikipedia.org/wiki/Date_format_by_country

d: function () {
return _this39.date.getDate();
},
dd: function () {
return ("0" + _this39.date.getDate()).slice(-2);
},
...
m: function () {
return _this39.date.getMonth() + 1;
},
mm: function () {
return ("0" + (_this39.date.getMonth() + 1)).slice(-2);
},
...

**Comment by Dogfalo** [comment]
We no longer use pickadate in 1.0.0

**Comment by bmla** [comment]
Alright, but it's still a modified version. Any reason single digit day and month are removed/not implemented?
It's not possible to use [CLDR](http://cldr.unicode.org/translation/date-time-patterns) if there is no single digits.
