### ISSUE TITLE
Always point to the second tab

### ISSUE THREAD

**Issue by BilalDja** [Dogfalo/materialize#5356]
## Expected Behavior

I expect that the first tab gonna be selected

## Current Behavior

Actually the second one who's selected instead!
## Steps to Reproduce (for bugs)

Just go to the documentation the problem is obvious there [http://materializecss.com/tabs.html](http://materializecss.com/tabs.html)

**Comment by Dogfalo** [comment]
http://materializecss.com/tabs.html#preselecting

**Comment by BilalDja** [comment]
One more question please! how can I change the tabs from within a angularJs controller I tryed this but didn't work form me:

`$timeout(function () {
  angular.element('ul.tabs').tabs('select_tab', 'tabId');
});`
