### ISSUE TITLE
Floating label select option

### ISSUE THREAD

**Issue by ThakurNiteshkumarSingh** [Dogfalo/materialize#5359]
Dear, There is no option for floating label in select box. I want same look like input text box floating label if value select or not

**Comment by Dogfalo** [comment]
Sorry we do not have that option

**Comment by ThakurNiteshkumarSingh** [comment]
Sorry but can you add this option in future

**Comment by ThakurNiteshkumarSingh** [comment]
Need your help, please.

**Comment by Dogfalo** [comment]
Just because you need it for your personal use, doesn't mean it is required for the framework. This is the first time we've received a feature request related to this, so it is not highly requested. As such, there are many other important issues for us to focus on.

**Comment by ThakurNiteshkumarSingh** [comment]
Ok Thanks
