### ISSUE TITLE
Modal footer for buttons

### ISSUE THREAD

**Issue by lukaspijak** [Dogfalo/materialize#536]
![Image](http://material-design.storage.googleapis.com/publish/v_2/material_ext_publish/0Bx4BSt6jniD7S21qWlJveU12aWM/components_dialogs_1.png
)

**Comment by carlosperate** [comment]
+1
This is definitely a feature I would appreciate being implemented.

**Comment by acburst** [comment]
Added in 91485ba52a8eeef7f6f84b754e02a111dcf0dacf
