### ISSUE TITLE
Select options is not scroll-able when inside an small container, like small modal

### ISSUE THREAD

**Issue by apudiu** [Dogfalo/materialize#5362]
## General summary of the issue
I have some modals, most of them are small, Like:
![image](https://user-images.githubusercontent.com/22303487/32778863-bfa89008-c965-11e7-9a50-24917ccf4eb6.png)

When I try to open the select:
![image](https://user-images.githubusercontent.com/22303487/32779528-5051fff2-c968-11e7-9539-dc9d0acf7c06.png)

In there, I have a select & 5-10 options, It seems that when I open the modal & then the select there's no scrollbar to scroll through all options, But there's all options has been rendered, I checked it by inspecting element.

## Expected Behavior
That select dropdown should display an scrollbar & open in a reasonable size, so I can see 3-5 options at once & scroll, as I have plenty of space, because the small modal is in the center of the screen.

## Steps to Reproduce (for bugs)
code to reproduce
1. Make a tiny modal of any type
2. Place a material select element in there
3. That select should have plenty of options 
4. Refresh the page & try to open the select, Bam... You seen a big bug.

**Please dont close this issue before it fully fixed, (I seen few issues closed without a really useful solution)

**Comment by cannect** [comment]
Which version are you running?

**Comment by acburst** [comment]
Container option added in 42aa7476.

You can specify `document.body` as the container of the dropdown to pull the dropdown out of the modal.
