### ISSUE TITLE
materializecss v1.0

### ISSUE THREAD

**Issue by onion878** [Dogfalo/materialize#5363]
![1](https://user-images.githubusercontent.com/25260101/32814828-99ee8d64-c9eb-11e7-944a-ce15e0b0e202.png)

**Comment by DanielRuf** [comment]
Can not reproduce. Please check the console of the developer tools in your browser.

**Comment by DanielRuf** [comment]
Possibly related to https://github.com/Dogfalo/materialize/issues/5352

**Comment by Dogfalo** [comment]
Duplicate of #5352
