### ISSUE TITLE
Clicking multiple time wave-effect button gets fade(Materializecss)

### ISSUE THREAD

**Issue by Chirag-bhavsar** [Dogfalo/materialize#5365]
I am using angular js 2 with materializescss frame work. As we know it has default class waves-effect and waves-light. Clicking multiple times simultaneously buttons gets dimmed or fade. I have not added materialize js multiple times. Does anyone have solutions rather than giving solution numbers. It would be great help!

**Comment by DanielRuf** [comment]
This should be already fixed in the latest releases. Which version of Materialize do you use?

**Comment by hoomb** [comment]
having exact same issue with Materializecss@Alpha.3, how did you fixed your issue?

**Comment by DanielRuf** [comment]
Please provide a codepen which shows the issue and describe how we can reproduce it.
It was fixed in waves.js

**Comment by hoomb** [comment]
Please check the code under https://github.com/Dogfalo/materialize/issues/5611

If I remove the line with "import * as M from 'materialize-css';", the code works properly. The Question is how can I define "M" to initialize the select and avoid double running the materialize code.

**Comment by DanielRuf** [comment]
> If I remove the line with "import * as M from 'materialize-css';", the code works properly.

That is not a solution. M is the namespace. window.M should be set when Materialize is included.

**Comment by hoomb** [comment]
Ok, I've got it. Replaced 

```javascript
import * as M from 'materialize-css';
```

with 

```javascript
declare var M: any;
```

has solved the problem. Thank you again for your help.
