### ISSUE TITLE
pulse not working on IE10/11

### ISSUE THREAD

**Issue by peter3** [Dogfalo/materialize#5366]
The pulse button doesn't work when using IE10/11.

Suggested fix is to change the .pulse property "overflow:initial" to "overflow:visible". 

I've verified that this works in Chrome 61.0.3163.100, Firefox 57.0 (Quantum) and IE 11

[Jsfiddle](https://jsfiddle.net/peter3/43aped80/)

**Comment by DanielRuf** [comment]
Which version of Materialize do you use?

**Comment by acburst** [comment]
Fixed in 37a82c0f
