### ISSUE TITLE
Suggestion: dragging to re-order list of chips

### ISSUE THREAD

**Issue by smileytechguy** [Dogfalo/materialize#5367]
This is a feature request to add a way to allow dragging of chips in order to re-order them.  

## Possible Solution
I used https://github.com/Shopify/draggable's Sortable plugin to do this:
In my example I had a div `social-chips` wrapping all my chips.

```js
new Draggable.Sortable($('.social-chips')[0], {
	draggable: '.social-chips > a, .social-chips > .chip',
	appendTo: '.social-chips'
}).on("sortable:stop", function() {
	// do some stuff with the new arrangement, for me this was to make a server ajax call for rearrangement
});
```

## Context
I use chips to show a user's social media networks in the following way:
![image](https://user-images.githubusercontent.com/8005215/32850946-a67d815a-ca01-11e7-95d1-fe909319470f.png)
Allowing them to rearrange them would be helpful, as with the current method they would have to remove several and re-add in the order they wish.

## Your Environment
I used latest materialize (from git) for this.

Tested on: Laptop with touchscreen, Laptop with trackpad, Desktop with mouse, iPhone.

I found is the clear icons were hard to tap/click, not sure how to fix this.
Also, the library adds some draggable-- classes and whatnot.  For my AJAX call I had to create a timeout for 100ms then act from there - this may be resolvable through use of different handlers.

**Comment by Dogfalo** [comment]
Reordering chips is not something we want to implement for now
