### ISSUE TITLE
How to button "today" in datepicker put value date now in input element

### ISSUE THREAD

**Issue by joelalves** [Dogfalo/materialize#5368]
## Current Behavior
 when clik in button today open datepicker. I would want, case if is possible, when click today open datepicker and set value input with value date now

## Your Environment
* Version used: django-material==1.1.1
* Browser Name and version: Chrome Version 64.0.3265.0 (Official Build) canary (64-bit)
* Operating System and version (desktop or mobile): desktop

**Comment by Dogfalo** [comment]
This is already the default behavior unless I'm misunderstanding you.
