### ISSUE TITLE
datepicker doesn't work with ng-repeat

### ISSUE THREAD

**Issue by BilalDja** [Dogfalo/materialize#5370]
Hi, I'm using materialize 0.98.2 with AngularJS 1.6.6
I have an array of objects that I need to set the date to every entry in it. I used ngRepeat on my page with input.datepicker materialize control. I expected to have for every entry a working datepicker. Instead I got a datepicker but doesn't popup! I initialized the datepicker with pickadate() function. I created a specific class for those fields but the same results occurred.

Same HTML structure generated. I tryed to add those classes to the generated _div_ **picker--focused picker--opened** it shows the datepicker but it was disabled!

**Comment by Dogfalo** [comment]
This is a very old version, please check with the newest version and also please check other issues on how to use materialize with Angular.
