### ISSUE TITLE
still many jQuery references

### ISSUE THREAD

**Issue by DanielRuf** [Dogfalo/materialize#5372]
I found jQuery.timeago and other places where jQuery is still referenced. I guess it should be now Cash.

**Comment by tomscholz** [comment]
@Dogfalo What about a `v1` label? Then you could differentiate between issues regrading v1 or other

**Comment by Dogfalo** [comment]
timeago is used just for the documentation website.

**Comment by DanielRuf** [comment]
> timeago is used just for the documentation website.

I did not mean timeago but the components in general and their method signatures.

**Comment by Dogfalo** [comment]
We have methods that make it easier for people who still want to use jQuery
