### ISSUE TITLE
Textarea broken in new Firefox 57. Does not display the full characters.

### ISSUE THREAD

**Issue by Verbat** [Dogfalo/materialize#5374]
If you check http://next.materializecss.com/text-inputs.html with the new Firefox 57 which was released recently you can see that text at the textarea is more then half ovelayed with a white area. It only shows the top part of the characters in a single line:
https://screenshots.firefox.com/HSyAzLkKw1KagoNs/next.materializecss.com

On mutliple lines (ie 3 Lines) its missing one of of it completely and only shows 2 lines
https://screenshots.firefox.com/Om3hpyFOasO7uoUA/next.materializecss.com

In Chrome or IE it's working as intended.

**Comment by Queatz** [comment]
I got around this for now by using `box-sizing: initial;` on the `textarea`.

**Comment by acburst** [comment]
Fixed in 08780250.
