### ISSUE TITLE
The input isn't being generated by M.Chips

### ISSUE THREAD

**Issue by AmitJoki** [Dogfalo/materialize#5379]
I just upgraded to 1.0 and `new M.Chips` wasn't working as expected. The error was that, `<input></input>` was not generated by Materialize as was the case < 1.0

I use jQuery 3.2.1 if that's of any use. I overcame this error by including the `<input></input>` in the snippet itself.

So instead of `<div class="chips chips-placeholder"></div>`, I had to write,
`<div class="chips chips-placeholder"><input/></div>` and bam! It started to work just fine.

**Comment by acburst** [comment]
Fixed in 14ad8937. 

The input is now generated correctly when not included.

**Comment by afabros** [comment]
I encountered this error as well. I tried to copy and paste the fix but something went wrong. Is it possible to have this change in the dist?
