### ISSUE TITLE
Dropdown does not close by clicking outside on iPad

### ISSUE THREAD

**Issue by theberengersniper** [Dogfalo/materialize#5383]
## Expected Behavior
The dropdown menu should close when a click is detected outside the dropdown, on selection of a menu item or when a click is detected over the dropdown trigger.

## Current Behavior
The dropdown menu will only close on selection of a menu item or when a click is detected over the dropdown trigger. The menu will _not_ close on clicking outside.

* Defect appears to affect the iPad only
* Does not affect other touch devices available to me to test with, e.g. Galaxy S6
* Affects all browsers on the iPad (tested with Safari, Chrome and Firefox)
* Affects Materialize' own site as well as my own

## Steps to Reproduce (for bugs)
Materializecss.com's own Dropdown demo is affected.

## Your Environment

* Version used: Current
* Browser Name and version: iOS Safari, iOS Chrome and iOS Firefox
* Operating System and version (desktop or mobile): iOS (latest)

**Comment by Dogfalo** [comment]
Fixed in 60bdf0d7
