### ISSUE TITLE
[1.0.0-alpha.1] Time Picker - time doesn't change

### ISSUE THREAD

**Issue by BrunoPace96** [Dogfalo/materialize#5384]
Expected Behavior

When clicking on the clock the time next to the clock should change

Current Behavior

Time doesn't change
![timepickerbug](https://user-images.githubusercontent.com/24843627/33030248-01f840e8-ce02-11e7-9f73-cfe13296c621.gif)

Steps to Reproduce (for bugs)

This bug can be seen in the documentation on pickers:
http://next.materializecss.com/pickers.html

Your Environment

Version used: 1.0.0-alpha.1
Browser Name and version: Chrome  62.0.3202.94
Operating System and version (desktop): Windows 8.1

**Comment by Dogfalo** [comment]
This was due to an issue with the Translation library we were using. We temporarily disabled it for the alpha documentation.
