### ISSUE TITLE
SideNav not a function - Not compatible with jquery 3.2.1

### ISSUE THREAD

**Issue by gg4u** [Dogfalo/materialize#5385]
Hi , would like to contribute notify that:

1.0.0 alpha release likely not compatible with jquery (SideNav not a function error) instead solved here:
https://stackoverflow.com/a/46770554/305883

**Comment by Dogfalo** [comment]
I don't understand, the comment you linked is merely restating a snippet from our documentation site

**Comment by RmK9** [comment]
Had the same issue, this is due to outdated documentation on materialize, use "$("elem").sideNav();" instead of ".sidenav();" - also please get the documentation fixed to avoid further issues like this.

**Comment by Dogfalo** [comment]
I don't see that issue here: http://next.materializecss.com/sidenav.html

**Comment by RmK9** [comment]
I do the see issue here: http://next.materializecss.com/sidenav.html

The documentation for the jQuery alternatives makes calls to the non-existent function "sidenav" - this has been refactored to "sideNav" (capital N). You can check this by downloading latest 1.0 code or the parallax template.

Hope that helps!

**Comment by Dogfalo** [comment]
The lastest call is sidenav, not sideNav

**Comment by RmK9** [comment]
Now it is, at the moment of writing this was not the case using latest build as well as parallax template. Thanks for aligning up the documentation and the script!
