### ISSUE TITLE
Unaligned checkbox's and text's baseline in dropdown

### ISSUE THREAD

**Issue by cjwchonjac** [Dogfalo/materialize#5386]
## Expected Behavior
<img width="157" alt="2017-11-20 4 55 58" src="https://user-images.githubusercontent.com/10153090/33049959-c9c7a39a-cea5-11e7-84f5-9fb09e5cbd27.png">

Baseline of checkbox and text are aligned.

## Current Behavior
Baseline of checkbox and text are unaligned.

<img width="159" alt="2017-11-20 4 55 34" src="https://user-images.githubusercontent.com/10153090/33049965-ce7ed890-cea5-11e7-8782-8e2fa2fca965.png">

## Steps to Reproduce (for bugs)
1. create `select` component with `multiple` option
2. open dropdown menu by clicking select component

## Your Environment

* Version used: 1.0.0-alpha.1
* Browser Name and version: safari 11.0.1(13604.3.5)
* Operating System and version (desktop or mobile): macOS High Sierra 10.13.1

**Comment by Dogfalo** [comment]
Are you seeing this issue on next.materializecss.com?

**Comment by cjwchonjac** [comment]
I closing this issue because it does not happening on next.materializecss.com.

**Comment by italomaia** [comment]
Is there a workaround?
