### ISSUE TITLE
1.0 docs uses system UI font instead of Roboto.

### ISSUE THREAD

**Issue by tomscholz** [Dogfalo/materialize#5391]
## Expected Behavior

Docs should use Roboto
## Current Behavior

Docs use System UI font

This commit caused the change: https://github.com/Dogfalo/materialize/commit/27bd03288b38428726c8a03a4a6f8c1ffacd382e
## Your Environment

* Version used: Release: 1.0.0-alpha.1
* Browser Name and version: Chrome 62
* Operating System and version (desktop or mobile): Mac OS X 10.11
* Link to your project (if appropriate): http://next.materializecss.com/

**Comment by Dogfalo** [comment]
The docs don't need to use Roboto. Having it like this also better reflects what the framework is going to be like out of the box.
