### ISSUE TITLE
Autocomplete documentation has wrong example

### ISSUE THREAD

**Issue by justinxreese** [Dogfalo/materialize#5392]
## Expected Behavior

1.0 documentation needs a vanilla JS example of initializing autocomplete forms.

## Current Behavior

The [1.0 documentation for Autocomplete](http://next.materializecss.com/autocomplete.html) shows code for initializing Carousels in the plain JS example. jQuery example is fine.

<img width="603" alt="image" src="https://user-images.githubusercontent.com/150839/33084332-adefdcb4-ceaf-11e7-92dc-8256c5242bdc.png">

## Possible Solution

Just need to update the docs. I can put a PR in if someone gives me a good example in the comments. I'm not sure how to do it.

**Comment by acburst** [comment]
This has already been fixed in e22cf50, The documentation will be updated when we update the alpha

**Comment by justinxreese** [comment]
👍 I'll close this since it's already in the pipeline.
