### ISSUE TITLE
Collapsible itens from side nav are with no padding.

### ISSUE THREAD

**Issue by joaofrassetto** [Dogfalo/materialize#5393]
When a collapsible item is opened showing its child items, in a side nav, the items have no padding to the right.

## Expected Behavior
This is the expected behavior, with padding : https://codepen.io/bobmarksie/pen/zZYgPe

## Current Behavior
Current behavior, with no padding: https://codepen.io/JoaoFrassetto/pen/qVooxo

## Context
The version of materialize is different. Is any version wrong?

**Comment by acburst** [comment]
You are using an older version. Try out our latest release

**Comment by joaofrassetto** [comment]
Yes, as I said, the two example uses different versions. Which one is correct? Padding or no padding?

**Comment by acburst** [comment]
no padding
