### ISSUE TITLE
jquery reference in Sidenav.getInstance

### ISSUE THREAD

**Issue by DanielRuf** [Dogfalo/materialize#5397]
```javascript
   /**
     * Get Instance
     */
    static getInstance(el) {
      let domElem = !!el.jquery ? el[0] : el;
      return domElem.M_Sidenav;
    }
```

**Comment by DanielRuf** [comment]
Generally it is in all `getInstance` occurrences. Shoudln't we fully drop support for jQuery or is this meant as migration helper?

**Comment by DanielRuf** [comment]
Imo we should cath undefined `el`s and throw a meaningful error or exception.

This should also prevent many issues/tickets from the start.

**Comment by Dogfalo** [comment]
Although we've dropped it as a dependency, a lot of people still use it, so this is meant to make use with jquery easier.
