### ISSUE TITLE
Second entry on chip is not getting through.

### ISSUE THREAD

**Issue by afabros** [Dogfalo/materialize#5398]
<img width="374" alt="screen shot 2017-11-23 at 17 37 12" src="https://user-images.githubusercontent.com/805713/33164208-2ac56210-d075-11e7-881d-1304f2645f46.png">
you can test at http://next.materializecss.com/chips.html

**Comment by Dogfalo** [comment]
Chips have to be unique, so if you are entering the same thing twice it will only make one chip

**Comment by afabros** [comment]
oh... makes sense^^ thank you!!!
