### ISSUE TITLE
Select multiple 

### ISSUE THREAD

**Issue by ffscalco** [Dogfalo/materialize#540]
Is there any support for select with `multiple` tag?

I've tried to use `$('select').material_select()` in `<select multiple>` but it's render the single select type.

**Comment by acburst** [comment]
We do not support that at the moment. You could use checkboxes?

**Comment by ffscalco** [comment]
Sure, It's pretty amazing =D
Thanks for the answer!

**Comment by ricardodovalle** [comment]
Do you know another stylized component that does the same?
I need to use select multiples because I have a large collection data.
Thanks
