### ISSUE TITLE
Global declaration 'M' not supported by Typescript

### ISSUE THREAD

**Issue by andyrichardson** [Dogfalo/materialize#5402]
Typescript doesn't seem to support global declarations of variables with a single capital letter.

##  Reproduction
Declare the materialize variable in your typescript file as follows

    declare const M: any;

## Expected result
Linters and editors see declaration as valid.

## Actual result
Linters and editors see declaration as invalid.

**Linter error**
    
    Cannot find namespace 'M'.

**Imports compared on Atom Editor using Typescript Language**

![screenshot from 2017-11-24 10-04-22](https://user-images.githubusercontent.com/10779424/33205444-e0d6ee32-d0fe-11e7-81dc-31e779c50c3b.png)
_As you can see from the screenshot, a single letter declaration seems to be unsupported._

## Other information
* Using Typescript v2.5.3
* Maybe it would be a better idea to use more than one letter such as `Mat`, `Materialize` etc.

**Comment by Dogfalo** [comment]
We don't use typescript.

**Comment by andyrichardson** [comment]
No interest in supporting it? 

Most Angular projects will be using typescript.

**Comment by Dogfalo** [comment]
Is this something that we fix in the library or something that can only be fixed in the client code?

**Comment by Antonyselt** [comment]
I'm triying to make M works with Typescript. But neither jquery functions works with typescript

**Comment by andyrichardson** [comment]
@Dogfalo I suspect the way to fix this would be to use any global naming scheme that isn't a single capital letter (such as `Mat`, `Materialize` etc.).

This would also reduce the likelihood of conflicts with other packages.

**Comment by huww98** [comment]
I have successfully added typescript support for M.

`typings/materialize-css/index.d.ts` (not completed):
````ts
export as namespace M;

export class Sidenav{
    public constructor(elem: Element, options?: SidenavOptions);

    public static getInstance(elem: Element): Sidenav;
    public open(): void;
    public close(): void;
    public destroy(): void;
}

export interface SidenavOptions {
    edge: string
}
````

Then add the following things to your `tsconfig.json`:
````json
{
  "compilerOptions": {
    "baseUrl": ".",
    "paths": {
      "*": ["typings/*", "*"]
    },
    "typeRoots": [
      "./node_modules/@types",
      "./typings"
    ]
  }
}
````

Now you should able to use `M` in any way you like. e.g. as a global variable, or `import * as M from 'materialize-css'`

**Comment by Dogfalo** [comment]
I believe @huww98 has the correct solution for integrating Materialize with Typescript.

**Comment by ademidun** [comment]
You can also use the [Materialize Typings npm package](https://www.npmjs.com/package/@types/materialize-css):

`npm install --save @types/materialize-css`

**Comment by AlisonVilela** [comment]
Include `"types": ["materialize-css"]` in your tsconfig.app.json file

**Comment by deser1** [comment]
> 
> 
> Include `"types": ["materialize-css"]` in your `tsconfig.app.json` file

I Have add for u solution but not work variable line `export = M` in @types/materialize-css/index.d.ts
What can i do? TypeScript not see this variable M but how? I have use dropdown but no know to use or add my app.component for now working. Did u know to make? 
I install @types/materialize-css and materialize-css but dropdown not working. I add materialize.min.js and css to header and again not work this script. Very hard problem starting on this framework. How?

**Comment by basudebpalfreelancer** [comment]
You need to install @types/materialize-css and then 

import * from "materialize-css";

M.AutoInit();

works.....
I also included "types": ["materialize-css"] in my tsconfig.app.json file as suggested by @deser1

**Comment by ZeCarlosCoutinho** [comment]
For me, the solution was installing `@types/materialize-css` and then prepending `global.` before every `M`.
For example:
```typescript
global.M.updateTextFields()
```

This was the only way I could get it working.
Doing `import M from 'materialize-css` would mess things up. The `M` object would not have the same properties as the `global.M` object, which would lead to errors like `updateTextFields() is not a function`.


EDIT: Actually the above didn't work, but for some reason TS didn't complain at the time.
What my colleagues did instead was the following:
```typescript
declare let M: any
(...)
M.updateTextFields()
```
