### ISSUE TITLE
Where did the `white-space: nowrap;` of `nav .brand-logo` go?

### ISSUE THREAD

**Issue by catscarlet** [Dogfalo/materialize#5403]
Hi guys.

I just update from v0.97.5 to v0.100.2.

I know a lot things changed such as modal.

I wonder why `nav .brand-logo` doesn't has the attribute `white-space: nowrap;`. It makes me very confused, and I didn't find any issues about that.

My site before update:

![snap1021](https://user-images.githubusercontent.com/10594035/33208590-1b975e46-d14d-11e7-9afa-df1ac63c8cfa.png)

After update:
![snap1022](https://user-images.githubusercontent.com/10594035/33208610-2e07acf2-d14d-11e7-9f20-88e4799a95ba.png)

Is that a thing, or just a bug?

**Comment by Dogfalo** [comment]
It was causing a bug in Firefox so we removed it.
