### ISSUE TITLE
Npm libraries are not update

### ISSUE THREAD

**Issue by Antonyselt** [Dogfalo/materialize#5406]
## Expected Behavior
Installing the lastest update from materialize

## Current Behavior
Version installed 100.2

**Comment by Dogfalo** [comment]
materialize-css@next is the alpha version.

**Comment by Antonyselt** [comment]
Then you should update the documents

**Comment by Dogfalo** [comment]
Updated it here: 52db4b9d50e8e837fc6e1f281f4f699cdf19d159
