### ISSUE TITLE
TypeError: Cannot read property '-1' of undefined     

### ISSUE THREAD

**Issue by damogongzi** [Dogfalo/materialize#5410]
this.deleteChip = function (chipIndex, $chips) {                                                                   // 5753
      var chip = $chips.data('chips')[chipIndex];                                                                      // 5754
      $chips.find('.chip').eq(chipIndex).remove();                                                                     // 5755
                                                                                                                       // 5756
      var newData = [];                                                                                                // 5757
      var oldData = $chips.data('chips');                                                                              // 5758
      for (var i = 0; i < oldData.length; i++) {                                                                       // 5759
        if (i !== chipIndex) {                                                                                         // 5760
          newData.push(oldData[i]);                                                                                    // 5761
        }                                                                                                              // 5762
      }                                                                                                                // 5763
                                                                                                                       // 5764
      $chips.data('chips', newData);                                                                                   // 5765
      $chips.trigger('chip.delete', chip);                                                                             // 5766
      self.setPlaceholder($chips);                                                                                     // 5767
    };             

The line  var chip = $chips.data('chips')[chipIndex];        generates the error TypeError: Cannot read property '-1' of undefined   at jQuery.fn.init.deleteChip (materialize_materialize.js?hash=e69bc7be2cfa7671c49705c6482043784d010064:5784)

**Comment by damogongzi** [comment]
$chips.data('chips') return undefined.

**Comment by acburst** [comment]
It looks like you are on an older version

**Comment by sharebooks** [comment]
I am using 0.100.2 which is the latest version? 

It does not happen all the time, it only happens after I submit the form, but the form was processed by jquery validator.

**Comment by DanielRuf** [comment]
Can you provide a codepen to show this issue?

**Comment by jfcere** [comment]
This bug is present on the demo page: http://materializecss.com/chips.html .... simply click the close icon of the tag with _Tag_ text.

You'll get the following error:
```
materialize.js:5769 Uncaught TypeError: Cannot read property '0' of undefined
    at r.fn.init.selectChip (materialize.js:5769)
    at HTMLDivElement.<anonymous> (materialize.js:5546)
    at HTMLDocument.dispatch (jquery-3.2.1.min.js:3)
    at HTMLDocument.q.handle (jquery-3.2.1.min.js:3)
```
