### ISSUE TITLE
Error in Safari v1 SyntaxError (DOM Exception 12): The string did not match the expected pattern. Cash

### ISSUE THREAD

**Issue by mangakid** [Dogfalo/materialize#5413]
When I require 'materialize-css/dist/js/materialize.js' (1.0.0-alpha.1)
In safari (11.0.1 ) when the app initialises I get the error: SyntaxError (DOM Exception 12): The string did not match the expected pattern.

This seems to be caused by the cash library.
at context.querySelectorAll in the find function.

I'm using webpack@3.5.4

**Comment by mishingo** [comment]
same issue here

**Comment by acburst** [comment]
This has been fixed on the latest version. We will be releasing a new alpha version today.
