### ISSUE TITLE
Using Swipeable Tab Materialize - Release: 1.0.0-alpha.1

### ISSUE THREAD

**Issue by matthewmario10** [Dogfalo/materialize#5415]
version of materialize alpha -> branch -> 'v1-dev' (as of 27/11/2017)

# Code 
var options = {
     responsiveThreshold: 100,
     swipeable: true,                           
};
var elem = document.querySelector('.tabs');
var instance = new M.Tabs(elem, options);

# Error
Uncaught ReferenceError: options is not defined

<img width="672" alt="responsivetaberror" src="https://user-images.githubusercontent.com/34055065/33331078-88e80c94-d458-11e7-92f7-7458f393fb7e.png">

**Comment by Dogfalo** [comment]
Already fixed
