### ISSUE TITLE
<a> elements inside of carousel items don't work properly

### ISSUE THREAD

**Issue by coolreader18** [Dogfalo/materialize#5416]
[Codepen](https://codepen.io/anon/pen/gXBXOP/)
As you can see, they cause the entire element to bug outside of the carousel and get stuck behind it, taking the size properties of the window and not working in general, card images don't show up, some other things I'd assume. This disallows card actions in carousels, as well as many other things, I'd assume.

**Comment by acburst** [comment]
This is because you are nesting block level elements inside an anchor tag which is an inline element. If you inspect element you can see that the browser moves your div outside the anchor tag which is whats causing these issues.

**Comment by coolreader18** [comment]
OHH okay. I was under the impression that carousel items had to be <a> elements. Thanks.
