### ISSUE TITLE
Tabs not retaining active tab after tab change via jquery.

### ISSUE THREAD

**Issue by asaadmahmood** [Dogfalo/materialize#542]
I have given these tabs inside a div which is originally hidden via display: none; so when the tabs are loaded initially they are hidden.

I have tried doing $('ul.tabs').tabs(); after opening that div, even with a setTimeout and the only thing it does is highlight which tab is active but the content connected to that tab remains hidden.

![screen shot 2015-01-27 at 10 24 14 pm](https://cloud.githubusercontent.com/assets/7103043/5923199/6b3a2f08-a673-11e4-9216-9b8238766510.png)
![screen shot 2015-01-27 at 10 25 28 pm](https://cloud.githubusercontent.com/assets/7103043/5923198/6b38a99e-a673-11e4-8d5c-ef519015d370.png)

**Comment by Dogfalo** [comment]
How are you changing tabs using jQuery?

**Comment by asaadmahmood** [comment]
// Side navigation
	$('.side-nav-inner').on('click', 'a', function(e){
		e.preventDefault();
		var target = $(this).attr('href');
		$('.side-nav__content .tab').removeClass('active').hide();
		$('.side-nav__content ' + target).fadeIn('fast').addClass('active');
	})

**Comment by Dogfalo** [comment]
Why are you applying your own click handler?

**Comment by asaadmahmood** [comment]
Do let me know if there is a better way to do it.
I have created a custom sidebar like the one in the screenshot, and I've used that code for that sidebar click events. I'm not sure if there is a built in event that let us do that in this library but do let me know if there's a solution to this issue.

![screen shot 2015-01-28 at 12 24 45 am](https://cloud.githubusercontent.com/assets/7103043/5925314/7b9d7f7e-a684-11e4-87e6-795cc40cc644.png)

**Comment by Dogfalo** [comment]
Just use the function we provide in the tab documentation. or you can trigger a click on the tab element.

**Comment by asaadmahmood** [comment]
I tried to tell you that I did try "$('ul.tabs').tabs();"
I even tried at the end of the click event.
setTimeoutsetTimeout(function(){
	$('ul.tabs').tabs();
},1000);

**Comment by Dogfalo** [comment]
If you are just trying to change tabs, you should be using `$('ul.tabs').tabs('select_tab', 'tab_id')`

**Comment by asaadmahmood** [comment]
I'm not trying to change any tabs, they're working fine. I'm just trying to display which ever tab has the active class by default:
"<li class="tab col s3"><a class="active" href="#test2">Test 2</a></li>"

I need to do that because I'm just testing it out, if it would be possible I would be using these tabs in a lot of places, I would probably want the default tab opened by default if I have added the "active" class.

**Comment by Dogfalo** [comment]
What I am saying is that instead of adding a class="active" to change tabs, you should be using the method I stated above. This will add active as well as show the content.

Adding class="active" only works when tabs is initialized. There is no event to monitor the adding of classes

**Comment by asaadmahmood** [comment]
I see. Well I did this:
```	var checkTabs = function(){
		var active = $('ul.tabs .active').attr('href');
		$('ul.tabs').tabs('select_tab', active);
		console.log(active);
	}
```

And it doesn't work and the active is giving me the correct id too.

```	var checkTabs = function(){
		$('ul.tabs').tabs();
		var active = $('ul.tabs .active').attr('href');
		$('.tabs-content ' + active).show();
	}
```

This works ^.

**Comment by eliaslebid** [comment]
asdadasd
