### ISSUE TITLE
Dropdown below origin options not working

### ISSUE THREAD

**Issue by pavlito** [Dogfalo/materialize#5421]
Can someone confirm that beloworigin option is working on materialize 1.0 alpha?

**Comment by Dogfalo** [comment]
Do you have an example of it not working?

**Comment by Dogfalo** [comment]
In the various test examples we have here: http://next.materializecss.com/test/html/dropdown.html

It seems to be working.

**Comment by pavlito** [comment]
@Dogfalo thanks on help.
Works now.

belowOrigin option is the name before 1.0 version.
Now it is coverTrigger. 

Did not saw that.
