### ISSUE TITLE
Dropdown constrainWidth option only works with hover enabled

### ISSUE THREAD

**Issue by DeehSlash** [Dogfalo/materialize#5422]
I'm using a dropdown which has an icon and some text at the right-side of the screen, but it is breaking the line between the icon and the text. Tried setting "constrainWidth" as true but it doesn't work, but I realized that if I set "hover" as true, then "constrainWidth" starts to work, see CodePen:

https://codepen.io/DeehSlash/pen/POyrzz

**Comment by Dogfalo** [comment]
This has already been fixed in 1.0.0-alpha.1
