### ISSUE TITLE
[1.0.0-alpha1] Passing swipeable to tabs options causes plugin crash

### ISSUE THREAD

**Issue by Magiczne** [Dogfalo/materialize#5424]
## Current Behavior
If we pass options object with swipeable option, tabs crash.

## Possible Solution
Line 252 in tabs.js
`if (window.innerWidth > options.responsiveThreshold) {`
probably should be
`if (window.innerWidth > this.options.responsiveThreshold) {`

## Steps to Reproduce (for bugs)
CodePen: [https://codepen.io/anon/pen/POxGZO](https://codepen.io/anon/pen/POxGZO)

## Your Environment

* Version used: 1.0.0 alpha
* Browser Name and version: Chrome 62.0.3202.94
* Operating System and version (desktop or mobile): Windows 10

**Comment by acburst** [comment]
You are absolutely right. Thanks for catching this. Fixed in 7bb0b612.

Oddly enough, this does not error when using the jQuery wrapper to initialize which is why I never noticed.

**Comment by firelizzard18** [comment]
It does error when using the jQuery wrapper, as that's how I was using it when I reported #5426. My setup might be different - I'm using JSPM which is pulling from NPM.
