### ISSUE TITLE
[1.0.0-alpha1] Setting twelveHour option to false timepicker crashes

### ISSUE THREAD

**Issue by Magiczne** [Dogfalo/materialize#5425]
## Current Behavior
If we set twelveHour option to false timepicker crashes.

Console says _Cannot read property 'toggleClass' of undefined_

## Steps to Reproduce (for bugs)

CodePen: [https://codepen.io/anon/pen/mqQrgK](https://codepen.io/anon/pen/mqQrgK)

## Your Environment

* Version used: 1.0.0 alpha
* Browser Name and version: Chrome 62.0.3202.94
* Operating System and version (desktop or mobile): Windows 10

**Comment by Dogfalo** [comment]
Fixed in 10df5e3
