### ISSUE TITLE
Date Picker doesn't work with type="date"

### ISSUE THREAD

**Issue by joshuaadickerson** [Dogfalo/materialize#5427]
## Expected Behavior
When you use `<input type="date" class="datepicker">` it should render the same as `type="text"` so browsers will gracefully degrade if there's an issue with the datepicker JS

## Current Behavior
A placeholder is generated (mm/dd/yyyy) which overlaps the label

## Steps to Reproduce (for bugs)

1. `<input type="date" class="datepicker">`
2. `$('.datepicker').datepicker()

## Context
I just used text as the type instead of date

## Your Environment
* Version used: 1.0.0 alpha 1
* Browser Name and version: Chrome 
* Operating System and version (desktop or mobile): Mac OS High Sierra, desktop
* Link to your project (if appropriate):

**Comment by Dogfalo** [comment]
As stated in previously closed issues, this is something that we could look into later, but is not a big concern to us currently. 
If you want native date selection, use the date type with no JavaScript, or if you want the material picker use the text type. This is how most datepicker plugins I've seen on the internet work.

**Comment by twentytwokhz** [comment]
@Dogfalo This actually helped me a lot!! I was not sure what was causing my input to show the browser style as well as the material style. I though I was going insane. I wanted to create an issue but lucky enough I saw your comment. All I needed was to change the type from 'date' to 'text'
Woohoo! 🕺
