### ISSUE TITLE
cash looks dead

### ISSUE THREAD

**Issue by DanielRuf** [Dogfalo/materialize#5429]
Cash like Slick slider looks dead and unmaintained.

https://github.com/kenwheeler/cash/tree/master/dist

There are also bugs with IE11.

**Comment by DanielRuf** [comment]
I would recommend https://github.com/franciscop/umbrella if we want to avoid all the bugs in cash without creating and maintaining our own fork.

**Comment by Dogfalo** [comment]
We can just fix the issues we encounter in cash

**Comment by DanielRuf** [comment]
For example https://github.com/kenwheeler/cash/pull/157

**Comment by DanielRuf** [comment]
In the Gitter chatroom there was at least one report abput this which breaks it in IE11.

**Comment by sank3** [comment]
This is also breaking the [Materialize site](http://next.materializecss.com/modals.html) in IE11 and Edge browsers.

**Comment by DanielRuf** [comment]
The parameter can be also `null`.

**Comment by DanielRuf** [comment]
@sank3 you are the one that I referred to from the chat.

**Comment by Dogfalo** [comment]
Create an issue relating to errors and we can track and fix them
