### ISSUE TITLE
constrainWidth false forces dropdown to have narrow ul

### ISSUE THREAD

**Issue by SeanVowles** [Dogfalo/materialize#5430]
If a dropdown has constrainedWidth set to false, the object does not span the width of the content it contains. 

## Expected Behavior

If a user doesn't want to constrain the width of an object it's typically because we want the object to span with the content it contains.

## Steps to Reproduce (for bugs)

<img width="170" alt="screen shot 2017-11-30 at 20 59 13" src="https://user-images.githubusercontent.com/17815894/33455003-99802210-d612-11e7-8f97-a2cc3f69b4ad.png">

```JavaScript
var options = {
    coverTrigger: false,
    constrainWidth: false,
};

var elem = document.querySelector('.dropdown-trigger');
var dropdown = new M.Dropdown(elem, options);
```

## Context

Wanted a dropdown UL to span the width of the longest item in the list

## Your Environment

Laravel 5.5 / Homestead / Webpack
"materialize-css": "^1.0.0-alpha.1",

* Version used: ^1.0.0-alpha.
* Browser Name and version: Chrome / FF/ Safari
* Operating System and version (desktop or mobile): MacOS
* Link to your project (if appropriate):

**Comment by Dogfalo** [comment]
Not able to recreate: https://codepen.io/Dogfalo/pen/YYKXjo
Please create a codpen with the issue and I will reopen this.
