### ISSUE TITLE
Uncaught ReferenceError: anime is not defined 1.0.0-alpha.2

### ISSUE THREAD

**Issue by mangakid** [Dogfalo/materialize#5432]
In 1.0.0-alpha.2

`(cash, anime);
;(function ($, anim) {
  'use strict';`

* Chrome, Firefox and Safari on Mac

**Comment by Dogfalo** [comment]
Please fill out the issue template, the information you provided is not very helpful

**Comment by mangakid** [comment]
## Expected Behavior
App should initialise and not crash

## Current Behavior
App crashes on initialisation with the above message in console.

## Possible Solution
Perhaps anime is not defined, the import might be broken, the wrong version used?
In materialize-css/js/ there is the file: anime.min.js
Perhaps it needs to be: anime.js

## Steps to Reproduce (for bugs)
It happens when:
require('materialize-css/dist/js/materialize.js');

## Your Environment

* Version used: 
1.0.0-alpha.2
* Browser Name and version: 
Chrome : Version 62.0.3202.94
Safari: Version 11.0.1 
* Operating System and version (desktop or mobile):
Mac OS Sierra 10.12.6

**Comment by Dogfalo** [comment]
What build system?

**Comment by mangakid** [comment]
We're installing with npm@5.3.0
And using webpack : 3.5.4
webpack-dev-server : 2.7.1

I hope that helps. Thanks for looking into it.

**Comment by ansgarS** [comment]
Solved this issue for now by using a cdn:
`<script src="https://cdnjs.cloudflare.com/ajax/libs/animejs/2.2.0/anime.min.js"></script>`

**Comment by Magiczne** [comment]
It happens when you import parts of materialize by yourself, for example like that:

`import 'materialize-css/js/cash'`
`import 'materialize-css/js/anime.min'`
`// import 'animejs'`
`import 'materialize-css/js/global'`
`// import 'materialize-css/js/autocomplete'`

then I get the
`Uncaught ReferenceError: anime is not defined` in the last line of the buttons.js file

**Comment by Dogfalo** [comment]
Fixed in 735df9040031ea9fac8f99bdfc4dd051e7e4c0ae

**Comment by komali2** [comment]
When is planned release? Is there a fix we can use until then or should we simply not use materialize 1? I'm not understanding if it simply isn't usable right now lol.

**Comment by Dogfalo** [comment]
1.0 is in alpha so sometimes it will have bugs. Either use 1.0.0-alpha.1 or wait for alpha 3 if you're encountering the problem
