### ISSUE TITLE
textarea won't resize onload version 1.0.0-alpha.2

### ISSUE THREAD

**Issue by leDebutant** [Dogfalo/materialize#5438]
It seems like the problem encountered here persists:

https://github.com/Dogfalo/materialize/issues/4613

can someone confirm this or it is just me. I have a text that is longter than the normal textarea but the resize on load does not work:

`$(document).ready(function(){
    $('#user_edit_about_me').trigger('autoresize');
});
`

Again this is version 1.0.0-alpha.2

https://codepen.io/ensayofr/pen/NwoBWK

**Comment by acburst** [comment]
This is an error in the docs. You should be using the function:

`M.textareaAutoResize($('#textarea1'));`

Fixed in 36f97281a12e1cc00dd6eb0833ae5ca5da433fbf.
