### ISSUE TITLE
SideNav implementation differs from google concept

### ISSUE THREAD

**Issue by dsentker** [Dogfalo/materialize#544]
The SideNav Component is in my opinion misleading. In Googles concept, there can be a LEFT sidebar, which is implemented correctly here. A RIGHT sidebar, instead, will slided in UNDER the Header / Navbar as described [described here](http://www.google.com/design/spec/layout/structure.html#structure-ui-regions-guidance)  .

Maybe we need to calculate the height of a right sidebar slightly.

**Comment by Dogfalo** [comment]
This can be changed on a per-app-basis by the developer
