### ISSUE TITLE
Add a context menu

### ISSUE THREAD

**Issue by flyingangel** [Dogfalo/materialize#5440]
It is possible to improve the Dropdown plugin to make it acts like a context menu?

Add a class `dropdown-trigger-context` and disable the default behavior of the browser for the right click. Allow dynamic event attachment on `ul` or `table` element. Ex:

```
<ul class="dropdown-trigger-context" data-event-source="li.aFile">
    <li class="aFile" data-id="1" data-type="file">File 1</li>
</ul>
```

Dynamic event help improving performance.

On dropdown open, because each list item could have different context menu, add to the callback `onOpenStart` 2 parameters : the current clicked element and the list of context items. Then we can loop for the context items to decide which one should be `.disabled` or `.hidden`

Item click triggers `onItemClick: function($menuItem)` callback

Use case: a file browser with Copy/Cut/Paste context

https://swisnl.github.io/jQuery-contextMenu/

**Comment by Dogfalo** [comment]
Since this is a pretty small use case, we most likely won't be adding it. However, you can add your own right click handler and open the dropdown programatically to emulate this behavior
