### ISSUE TITLE
HTTP error 404 Not Found on "meteor add materialize:materialize"

### ISSUE THREAD

**Issue by VenomCLC** [Dogfalo/materialize#5441]
As the title implies.
Trying to install the package for meteorjs

meteor add materialize:materialize
 => Errors while adding packages:

While loading package materialize:materialize@0.100.2:
error: Command failed: C:\Windows\system32\cmd.exe /c C:\Users\claudiu\AppData\Local\.meteor\packages\meteor-tool\1.6.0\mt-os.windows.x86_64\dev_bundle\bin\npm.cmd rebuild --update-binary
Cannot download "https://github.com/sass/node-sass/releases/download/v4.5.2/win32-x64-57_binding.node":

HTTP error 404 Not Found

**Comment by Dogfalo** [comment]
Please search existing issues
