### ISSUE TITLE
Raises JS error in IE

### ISSUE THREAD

**Issue by jelofson** [Dogfalo/materialize#5447]
https://github.com/Dogfalo/materialize/blob/ecf8335b4c4d5191b4407e847587960c4bbbd33c/js/select.js#L158

IE 11 says you must pass argument here. This line seems like it doesn't do anything so either remove or pass null to the add() method. 

I have fixed this locally if you want a pull. Didn't run any tests, however.

**Comment by Dogfalo** [comment]
Removed in 7c4fc58. Thanks!
