### ISSUE TITLE
It would be nice to have a versioned docs website

### ISSUE THREAD

**Issue by jacobq** [Dogfalo/materialize#5449]
This is a documentation feature request.

Currently both materializecss.com and next.materializecss.com refer to a single version of materialize (i.e. that latest one). However, it is often useful to be able to easily refer back to a previous version because it is not always practical to use the latest version on all projects (sometimes it is not even in one's own control due to arrangements with customers). For example, [node](https://nodejs.org/dist/latest-v8.x/docs/api/) and [ember](https://emberjs.com/api/ember) both do this. Starting with the release of v1.0.0, could we do this for materialize also?

**Comment by acburst** [comment]
We plan on having an archive for stable versions. This doesn't mean we'll have documentation for every single release but releases that we deem stable. When 1.0.0 is released, 0.100.2 will be the first archived docs.

**Comment by jacobq** [comment]
I'm not sure what you mean by an "archive" but it sounds like you're at least taking this into consideration, which was the reason I mentioned it.

Ideally, all available versions of the docs pages would be accessible online without having to go through a cumbersome process to view them (e.g. clone repo, checkout some version, run local webserver, and browse locally to see docs for an older version).
