### ISSUE TITLE
Add activate deactivate metods to collapsible

### ISSUE THREAD

**Issue by sahina** [Dogfalo/materialize#545]
Hi,

Can you add methods to activate and deactivate and "activated" and "deactivated" events to collapsible? It is useful to programmatically interact with collapsible.

Thanks

**Comment by mylastof** [comment]
Need this feature, call by using link or another way.

**Comment by ayoubgdah** [comment]
+1

**Comment by oli107** [comment]
+1

**Comment by ritdaw** [comment]
+1

**Comment by miquelferrerllompart** [comment]
+1

**Comment by mikilukasik** [comment]
+1

**Comment by rockysimkonis** [comment]
+1

**Comment by acburst** [comment]
Added open and close methods to collapsible in b6d3188
