### ISSUE TITLE
Initializing SideNav when loading it using AJAX

### ISSUE THREAD

**Issue by haideralipunjabi** [Dogfalo/materialize#5450]
I use [MaterializeCSS](http://materializecss.com/) on my portfolio website. I have stored my header + navbar in a file ` header.html ` and load it on every page using [jQuery load](https://api.jquery.com/load/). (I know this is bad for SEO)

**Problem:**  
The sideNav doesn't open on mobile sometimes, even though I initialize it properly.  

Here is my code:  

header.html

    
    <header class="header deep-purple center-align">
    <div class="row valign-wrapper">
      <div class="col s6 right-align">
        <img class="responsive-img circle" src="/assets/media/profile.png" alt="" >
      </div>

        <div class="col s6 left-align">
          <img class="responsive-img" src="/assets/media/logo_main_light.svg" alt="">
        </div>

    </div>
    <h1 style="font-size: 4.2rem;">Haider Ali Punjabi</h1>

    <nav>
    <div class="nav-wrapper deep-purple darken-2">
      <a href="#" data-activates="mobile-demo" class="button-collapse"><i class="material-icons">menu</i></a>
      <ul class="hide-on-med-and-down">
        <li><a href="/index.html">About Me</a></li>
        <li><a href="/resume.html">Resume</a></li>
        <li><a href="/projects.html">Projects</a></li>
        <li><a href="/photography">Photography</a></li>
      </ul>
      <ul class="side-nav deep-purple darken-2" id="mobile-demo">
        <li><a href="/index.html">About Me</a></li>
        <li><a href="/resume.html">Resume</a></li>
        <li><a href="/projects.html">Projects</a></li>
        <li><a href="/photography">Photography</a></li>
      </ul>
    </div>
  </nav>
</header>

index.js

    jQuery(document).ready(function($) {

      $("#header").load("/header.html",function(){
        $(".button-collapse").sideNav();

      });
    });

I know I am initializing it properly, and after the navbar has been loaded, so I don't see why this doesn't work.

**Comment by Dogfalo** [comment]
My guess is that `#header` isn't always available at the run time of the script which leads to the event not being set. I don't think this is a bug related to the library.
