### ISSUE TITLE
Select box is still not showing up when using Materialize

### ISSUE THREAD

**Issue by NewBo1234** [Dogfalo/materialize#5451]
I have a jsGrid on a page with Materialize providing CSS.  Whenever I use Materialize, the grid itself will show up, but the "select" type fails to show up.  If I take out Materialize, the select will render correctly.

I keep seeing this as a question.  Please could the documentation be updated to show a short example where these two will render correctly?  As far as I can tell (see http://demo.geekslabs.com/materialize-v1.0/table-jsgrid.html) it can be done, but so far there has not been a concerted effort to document how.  Does it require extra libraries?  Extra coding?

**Comment by Dogfalo** [comment]
Search closed issues first please.
