### ISSUE TITLE
Range slider is missing the tooltip above the slider while dragging

### ISSUE THREAD

**Issue by ansgarS** [Dogfalo/materialize#5455]
## Expected Behavior
If you drag the range slider (with 	tooltips: true), it is expected to see the number in a tooltip above the slider.

## Current Behavior
No tooltip is displayed.

## Possible Solution
Might be an issue with noui-slider.

## Steps to Reproduce (for bugs)
Just use the example code from your docs:
```
  var slider = document.getElementById('test-slider');
  noUiSlider.create(slider, {
   start: [20, 80],
   connect: true,
   step: 1,
   tooltips: true,
   orientation: 'horizontal', // 'horizontal' or 'vertical'
   range: {
     'min': 0,
     'max': 100
   },
   format: wNumb({
     decimals: 0
   })
  });
```

## Context
Design issue

## Your Environment

* Version used: alpha-2
* Browser Name and version: Chrome and Safari
* Operating System and version (desktop or mobile): Mac OS

**Comment by acburst** [comment]
Our range doesn't have any tooltips. The thumb transforms into a sort of tooltip showing the value tho? I'm not exactly sure what you are expecting

**Comment by DanielRuf** [comment]
Also we ship the noUiSlider with Materialize afaik. There should be only the greenish bubble at the top.

**Comment by PQALAB** [comment]
I'm seeing the thumb is missing in the latest alpha version  v1.0.0-alpha.4

**Comment by mckenzieja** [comment]
This shouldn't have been closed.

The docs reference noUISlider however some options do not pass through. 

An example would be if you want to display tooltips at all times and not just when the user interacts with the slider.
