### ISSUE TITLE
Opening modal out of modal opens it in background of first modal

### ISSUE THREAD

**Issue by Knochenmark** [Dogfalo/materialize#5457]
## Expected Behavior
So I have following scenario:
I open a modal which essentially shows some options/buttons which itself trigger different actions.
One of the actions will open another modal. The behavior was that the second modal opens above
the original modal and allows for a quick action before closing the second and returning to the original modal.

## Current Behavior
Currently, might be introduced in a recent update, the second modal opens in the background and it is
not possible to access it. This forces you to close the intial modal to access the second modal.

## Possible Solution
A quickfix for me of course is to close the intial modal, but this doesnt really solve the problem for nesting modals. So I ask you to have a look if you might have changed something regarding z-indices or similar in the recent updates.

Thanks guys, keep up the good work.

**Comment by acburst** [comment]
Can you post an example?

We have some basic html scenarios that seem to work: http://next.materializecss.com/test/html/multiple_modals

**Comment by Dogfalo** [comment]
Fixed in fafeb0a

**Comment by Knochenmark** [comment]
Thanks, this was quick :+1:
