### ISSUE TITLE
bug on latest version  sass files

### ISSUE THREAD

**Issue by madrigal1** [Dogfalo/materialize#5459]
![image](https://user-images.githubusercontent.com/30615210/33807168-7e8d436e-ddf8-11e7-8a74-18c21879e43c.png)

**Comment by madrigal1** [comment]
No edit was made
The error was on compilation 
PLz help

**Comment by Dogfalo** [comment]
We aren't having an issue with compilation on sass. Make sure you're not using a very old version of the compiler.
