### ISSUE TITLE
Navbar search on enter key pressed

### ISSUE THREAD

**Issue by Kseg97** [Dogfalo/materialize#5461]
Hi, I've my code as suggested on [http://materializecss.com/navbar.html](url) for the search bar, and I've seen many solution on how to get the inputText value, but there is not actual documentation for this precise component, as the desired action is to get a text value from the input when user hits enter key.

By now, and as on the documentation for the navbar, if any text is written on the bar and the 'enter' key is pressed, the page will redirect to  "/?" (for example if I'm on the main localhost, it will redirect to localhost/?) and the search bar will be closed as normally.

Is there a way of controlling this through jQuery? (I'm using Angular with angular2-materilize, but their documentation only provides with example on simple inputs, and is not related with pressing the 'enter' key as they do not require this characteristic.

**Comment by Dogfalo** [comment]
This may help you: https://stackoverflow.com/questions/13987300/how-to-trigger-enter-key-press-of-textbox

For how-to questions, please use StackOverflow.
