### ISSUE TITLE
Input type=radio in collapsable-header breaks the accordion

### ISSUE THREAD

**Issue by Kris0** [Dogfalo/materialize#5462]
If i use a accordion and putting a input type=radio into the collapsable-header it breaks the accordion. It simply don't open nor close anymore if i click on the input. Clicking somewhere in the free area next to the input works like expected.

## Expected Behavior
I would like to click on the input (select an option) and open/close the accordion.

## Current Behavior
Clicking on the input it seems like the events are triggered, as if you look closely at the bottom border of the section, the animation seems to start but it don't open. 

## Steps to Reproduce
https://codepen.io/anon/pen/NXWrZY

## Your Environment
The CodePen is a fork of the CodePen from the documentation, so:
* Version used: 0.100.2
* Chrome 62.0.3202.94, FireFox 58.0b10 DEV
* Windows 10 Desktop

**Comment by Dogfalo** [comment]
This is caused by event bubling as a default behavior of input and labels. See here: https://stackoverflow.com/questions/24501497/why-the-onclick-element-will-trigger-twice-for-label-element

**Comment by Kris0** [comment]
Nope. Did you saw the codepen? I did not nested the input inside of a Label. Also canceling the bubbling on the label, does not fix the Problem.

**Comment by Kris0** [comment]
Canceling the Click event on the Input neither helps, worse i cannot activate the Label anymore.
