### ISSUE TITLE
Textfield – height not automatically adapted on initialization

### ISSUE THREAD

**Issue by vuhrmeister** [Dogfalo/materialize#5465]
While typing the behavior is as expected. But given a field which is pre-filled it shows just one line (and a half or so). Though when you start typing then it adapts again properly.

<img width="569" alt="bildschirmfoto 2017-12-12 um 15 14 08" src="https://user-images.githubusercontent.com/2188790/33889106-6c09e19a-df4f-11e7-8cfb-38e79a622272.png">

## Your Environment
* Version used: 1.0.0-alpha.2
* Browser: at least Chrome, Firefox

**Comment by acburst** [comment]
Fixed in 52cb1566.

If you are adding textareas dynamically, keep in mind you will have to call M.textareaAutoResize on it manually.

**Comment by vuhrmeister** [comment]
Nice, thx. 

Didn't know about that method. It's not documented, should be added then.

**Comment by acburst** [comment]
It is in the documentation below the markup for the textarea.

**Comment by vuhrmeister** [comment]
I just updated to alpha 3 and what should I say: Doesn't work as expected! So I have to roll back to alpha 2 until this is fixed 😞 

Now the textarea gets a calculated height of 742px even though it has only one line of text!

**Comment by vuhrmeister** [comment]
Okay, so it seems that it works under "normal" conditions.

It doesn't work when put into a collapsible which is initially folded. 
In that case the height is (line height * character count). So If the field has only one Character, all looks fine. With three characters the field has a height of 76px!

**Comment by olinations** [comment]
This still hasn't been fixed. Working in react, not sure how to fix it.

**Comment by ghost** [comment]
I'm on the same page. It does not work and not sure how to fix it.
