### ISSUE TITLE
Select carets not showing with form background color

### ISSUE THREAD

**Issue by daslani** [Dogfalo/materialize#5466]
## Expected Behavior
The `.select-wrapper .caret` element should display the SVG path of the caret in a materialize-css styled select box regardless of the background of the form.

## Current Behavior
The SVG caret that's shown appears behind the `.select-wrapper` as instructed by `.select-wrapper .caret` style: `z-index:-1` and is not displayed when the form or parent div has a non-transparent background.

## Possible Solution
Perhaps attach a listener to the `.caret` wrapper

## Steps to Reproduce (for bugs)
https://codepen.io/anon/pen/JMjeja

## Your Environment
* Version used: 1.0.0-alpha-2
* Browser Name and version: Chrome 62.0.3202.94 
* Operating System and version (desktop or mobile): Desktop

## Other Remarks
Issue# [4592](https://github.com/Dogfalo/materialize/issues/4592) isn't the solution I'm considering as it's not changing the background of the select. I'm simply changing the background of the container any select would be in.

**Comment by acburst** [comment]
This has been fixed in c44a4af08902ae209fff690fd84f33041056d424.

It will be included in the next release.
