### ISSUE TITLE
Uncaught TypeError: $(...).pickatime is not a function

### ISSUE THREAD

**Issue by guboi72** [Dogfalo/materialize#5467]
It seems there is something broken with a few components. 

I've got this error using 
```<script type="text/javascript" src="https://code.jquery.com/jquery-3.2.1.min.js"></script>```
```<script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/0.100.2/js/materialize.min.js"></script>```.

At first I thought I messed up but it seems to affect https://react-materialize.github.io/#/forms as well. You can see it by looking into the console.

scrollspy also does this.

**Comment by robbiemilejczak** [comment]
http://materializecss.com/ and https://react-materialize.github.io/#/forms are not the same thing. You ca see that the time picker at http://materializecss.com/forms.html is working correctly.

Can you post your code? I am confident the issue is on your end.

**Comment by Dogfalo** [comment]
Please search closed issues first

**Comment by guboi72** [comment]
Thank. I'll try to solve this issue with react-materialize since we both use react.
