### ISSUE TITLE
How To Get Data In Chips.

### ISSUE THREAD

**Issue by weakestlee** [Dogfalo/materialize#5468]
I'm using the latest Materialize.

I like the *[Chips](http://next.materializecss.com/chips.html)* Component, but I don't know how to get data from chips. There seems to be no explanation for it in document.

In the old version, maybe it's work like this: 
```
$('.chips-initial').material_chip('data');
```

But it is not work now, there is an error in console
> $(...).material_chip is not a function

How To Get Data In Chips?

**Comment by fewtaeyeon** [comment]
Without more information (like the code you are running), it is difficult to say what is causing the problem.

**Comment by acburst** [comment]
First off, the plugin is now just .chips

Next, getting the data is no longer a method but an attribute. You can get the data by doing: 
```
M.Chips.getInstance($('.chips-initial')).chipsData;
```

This is explained in the methods section. Under the properties section, you can see all the properties you have access to.
