### ISSUE TITLE
modal position and size

### ISSUE THREAD

**Issue by ray007** [Dogfalo/materialize#5471]
The defaults for `M.Modal` are nice for most cases, but I'm having a really hard time with some things:

- have the modal show up in the fixed position. Especially `top` is always overridden with the opening animation. So I can get this to work by setting `startingTop` and `endingTop` to the desired value.
- have the dialog take its size from the contents. For non-IE browsers I can make this work by forcing `width: fit-content;`, but the only way I've found so far for IE is settings `display: table;`, and doing this in the `ready` callback is a bit late and looks ugly.
- setting x position is also off due to `margin: auto;` on modals.

Is this a missing feature, or do I just miss an example to copy?

**Comment by Dogfalo** [comment]
See my comment on #5493
