### ISSUE TITLE
Datepicker disappear when I make any click event

### ISSUE THREAD

**Issue by BilalDja** [Dogfalo/materialize#5475]
When I try to choose a year or month or when I press on the arrows the datepicker made the operation then disappear! when I click to open it again I see the change made!
Well, this problem happens on chrome, and it's not consistent, sometimes . On firefox the Datepicker seems to work.
I'm using materializecss v0.100.2
AngularJS 1.5.11

**Comment by BilalDja** [comment]
materialize apparently, because when I opened my app with _incognito_ the datepicker works fine, that leaves me with the conclusion that the problem probably related to one of my extensions!

**Comment by boussadjra** [comment]
Hello,
are you binding your fields to a model? i have the same problem with Vuejs v-model, but when i work with pure js code it works

**Comment by BilalDja** [comment]
Well I'm using angular materialize.

**Comment by boussadjra** [comment]
so try to get fields value with jquery or with pure js, i said that my problem was the v-model of Veujs, and i solved that with jquery

**Comment by BilalDja** [comment]
Sorry, I wasn't clear. Yes ofcours I'm binding my model to materialize datepicker, & I don't know Vue.js

**Comment by boussadjra** [comment]
Vuejs is like Angular and they use the same notion, for example in model and inputs binding

**Comment by BilalDja** [comment]
I think you need to create a new issue mate
