### ISSUE TITLE
Multiple Tooltip

### ISSUE THREAD

**Issue by Ketcap** [Dogfalo/materialize#5476]
## Expected Behavior
Normally on tooltip with jquery, it makes all tooltips but when it's in pure javascript it only initializes 1 tooltip.

## Current Behavior
This returns 1 item maybe thats why.  var elem = document.querySelector('.tooltipped');

## Possible Solution
getElementsByClassName should be used I think.

## Steps to Reproduce (for bugs)
Made pen for it.
https://codepen.io/anon/pen/GypyaW

When you are using jquery, it works but pure js version just initialize for the first item 

## Your Environment

* Version used: 1.0.0-alpha.2
* Browser Name and version: Chrome 63.0.3239.84
* Operating System and version (desktop or mobile): Desktop - Mac Os

**Comment by acburst** [comment]
In our next release we have changed the way you init to support multiple initialization with javascript

**Comment by Dogfalo** [comment]
use `querySelectorAll()` for multiple items.
