### ISSUE TITLE
Way to disable parallax on mobile

### ISSUE THREAD

**Issue by Darkinuyasha** [Dogfalo/materialize#5478]
Hello, the parallax element is lacking an effective way to substitute it with static images.
On mobile parallaxes don't work well, there isn't a way?

In the meantime, who knows a substitute for this problem?

**Comment by acburst** [comment]
We can add a responsive threshold, which we've done for a couple of our plugins. It would be a pixel value that below it would disable the effect. Would something like that work?

**Comment by Darkinuyasha** [comment]
It could, maybe an option to set  it or not.
A way to disable the parallax without removing it and without doing complex or unefficient workaround. 

Thank you, I super love your works :)

**Comment by acburst** [comment]
Added in d90f1049
