### ISSUE TITLE
Materialize Select is not focusable with key tab

### ISSUE THREAD

**Issue by kevinliteon** [Dogfalo/materialize#548]
Tested on this page http://materializecss.com/forms.html

**Comment by robinbortlik** [comment]
:+1:

**Comment by zen6** [comment]
:+1:

**Comment by acburst** [comment]
The following elements support the tabindex attribute: A, AREA, BUTTON, INPUT, OBJECT, SELECT, and TEXTAREA.

I'm not sure how we would solve this issue atm, sorry.

**Comment by robinbortlik** [comment]
Can you please reopen this task. I'm working on this functionality and it is almost done. I will create a pull request in few days.
Thank you.

**Comment by robinbortlik** [comment]
Here is promised pull request https://github.com/Dogfalo/materialize/pull/582
