### ISSUE TITLE
button shouldn't be on top of drop down list

### ISSUE THREAD

**Issue by msman** [Dogfalo/materialize#5482]
HI,

I observed that `.waves-effect` class of the button component shouldn't have` z-index: 1` . Why? Because in case a dropdown menu renders its list, the button becomes on top of the list where it should be covered by the list. It happened with me while using [react-select ](https://github.com/JedWatson/react-select)

The second thing is that, I face a problem when used materialize with React, please see the problem description [here](https://stackoverflow.com/questions/47853137/materialize-reactjs-menu-item-sometimes-work-sometimes-does-not?noredirect=1#comment82670578_47853137).

**Comment by acburst** [comment]
Can you provide a code example?
