### ISSUE TITLE
M.textareaAutoResize Issue v1.0.0-alpha.2

### ISSUE THREAD

**Issue by bab2683** [Dogfalo/materialize#5484]
Hi, 
I just noticed that if you call M.textareaAutoResize(document.querySelector(".some-textarea-selector"))
it gives you an error since the function expects a jQuery Obj

## Current Behavior
Error line:
![image](https://user-images.githubusercontent.com/25367013/34201256-34ca9cda-e574-11e7-95c1-55a621ee1ac8.png)

Console error:
![image](https://user-images.githubusercontent.com/25367013/34201420-b8ca539a-e574-11e7-87af-c466201e3189.png)

## Possible Solution
Using the getComputedStyle method:

var styles = getComputedStyle($textarea);
var fontFamily = styles['font-family']; // or styles.fontFamily;

## Context
I'm using Angular and I update the textarea value dynamically for edits. Since it doesn't resize automatically, I looked up the documentation and found this:
![image](https://user-images.githubusercontent.com/25367013/34201831-1a714e22-e576-11e7-9d3b-a60ddf1d6edb.png)

Since I don't use jQuery I searched if there was already a method for autoresizing textareas and found the M.textareaAutoResize method.

## Your Environment
I don't use jQuery
* Version used: Materialize v1.0.0-alpha.2

Best regards

**Comment by acburst** [comment]
Fixed in f76204b2
