### ISSUE TITLE
v1.0.0-alpha.2 onChipDelete does not get the current chip

### ISSUE THREAD

**Issue by KK66** [Dogfalo/materialize#5486]
![unbenannt](https://user-images.githubusercontent.com/11517256/34213163-b5e0ecb4-e59e-11e7-90f0-cee2b3653099.PNG)

Hello, if I want to delete a chip, I need the current data, but $chip[0] is undefined. And with the other parameters, I do not get the data, too.

**Comment by acburst** [comment]
Can you provide a codepen or something?
