### ISSUE TITLE
radio buttons and checkboxes move up the entire content

### ISSUE THREAD

**Issue by HIRANO-Satoshi** [Dogfalo/materialize#5488]
Hi,

When a radio button or a checkbox is pressed in a collapsible, the entire content is moved up and a large blank appears under the content. There are safe cases and bad cases. 

This issue was introduced in 0.100.0 since 0.99.0 was okay.

I think[ this commit](https://github.com/Dogfalo/materialize/commit/57423d86a611909bb6bcc73659bcdc22bfa3c104) was wrong.

If I add the following workaround in my css, this issue disappears.
```
[type="radio"]:not(:checked),
[type="radio"]:checked {
  position: absolute;
  opacity: 0;
  pointer-events: none;
  left: -9999px;      /* added */
}
/* Remove default checkbox */
[type="checkbox"]:not(:checked),
[type="checkbox"]:checked {
  position: absolute;
  opacity: 0;
  pointer-events: none;
  left: -9999px;      /* added */
}
```

**Comment by Dogfalo** [comment]
since it is `position: absolute` already, there should be no difference. Check your code to make sure that you didn't inadvertently change the position property of the checkbox

**Comment by HIRANO-Satoshi** [comment]
Thanks for your reply. I confirmed there is no other position.

Without left: -9999px, if position: absolute is enabled, the content is moved up.
If I disabled left:-9000px and position: absolute, it was okay.
This occurs on Chrome and does not on Safari.

![2017-12-25 8 54 44](https://user-images.githubusercontent.com/1736529/34329798-61481c34-e951-11e7-9001-1211d3211f01.png)

**Comment by Dogfalo** [comment]
Not seeing this on the current 1.0.0-alpha.2 version

**Comment by ermarkar** [comment]
Setting the `position` to `relative` of **input** element helped.

**Comment by ZakAttakk** [comment]
I had this same problem.  It was terrifying, as I thought I would need to remove Materialize from my entire project.  Fortunately, the `left: -9999px;` worked.  Thank you so much!

**Comment by HIRANO-Satoshi** [comment]
@ermarkar Thanks. You are right. `  position: relative;` works and `left: -9999px` does not with 1.0.

I experienced alignment problem with the following pattern.

    [type="checkbox"]:not(:checked),
    [type="checkbox"]:checked {
      position: relative;
    }

This is better than the above for me. My dialog is not moved up.

      <div style="position: relative;">
        <label>
             <input type="checkbox">
             <span>Delivery</span>
        </label>
