### ISSUE TITLE
Select is not showing up

### ISSUE THREAD

**Issue by Skuriles** [Dogfalo/materialize#5491]
The input select and the options of the select are in DOM in dev tools, but the whole select is not showing up. 
I found some closed issues, but beside a solution to manually update Materialize Inputs I didn't find anything.
First I thought it was due to using Angular (ngIf or ngFor for options) but I removed every angular reference and added a simple form:

https://plnkr.co/edit/K8pppKJRdx8RpKjBq2xa?p=preview

## Expected Behavior

Select should be displayed with options

## Current Behavior

Select has widht, height and opacity 0. The whole transformation to the materialize select is not started somehow

## Steps to Reproduce (for bugs)
1. Build a simple form with a select
2. See that select is not showing up
3.

## Your Environment

* Version used: 1.0.0-alpha.2 Release
* Browser Name and version: Chrome 63 latest version
* Operating System and version (desktop or mobile): Desktop, Win 10

**Comment by Dogfalo** [comment]
You have to initialize them, please see documentation

**Comment by Dogfalo** [comment]
http://next.materializecss.com/select.html#initialization

**Comment by Skuriles** [comment]
Thanks, missed that. 
For me it is little bit a hacky solution, especially if you use frameworks like Angular 2+ with Typescript and want to use directives like ngFor or ngValue with dynamic options.
You have to write 6 or 7 lines of code just for a simple select.
Nevermind, still a real good css lib!!
