### ISSUE TITLE
timepicker twelveHour mode incomplete

### ISSUE THREAD

**Issue by ray007** [Dogfalo/materialize#5495]
## Expected Behavior

Timefields should accept preset times in am/pm format - at least when the `twelveHour` option is set.

## Current Behavior

Initializing a timepicker with a value of '08:00 pm' shows an input-field without a set time.
Initializing it with a 24-hour timestamp works fine if one ignores the wrong initial string.

**Comment by ray007** [comment]
The timepicker could also use a `set` and/or `update` method to set a new value from outside (like all other components?)

**Comment by Dogfalo** [comment]
Please create a codepen illustrating your scenario and please read issue guidelines and at least state the version number

**Comment by ray007** [comment]
Sorry, my bad, seemed so trivial.
Found a scripting problem on my side, fixed now.

Only 1 thing remaining: the am/pm detection in `_updateTimeFromInput()` is case-sensitive, so it doesn't recognize lower-case am/pm and also fails to parse the minutes.
Do you want me to make a PR for that?

**Comment by Dogfalo** [comment]
Fixed in 8facfe470d96adeaf9b6e2097c648512fb11877e

Currently not supporting i18n for am pm. i18n is mainly for the language used in the UI in the picker.
