### ISSUE TITLE
Dynamic Generated Content not Working

### ISSUE THREAD

**Issue by wendicui** [Dogfalo/materialize#5496]
Hi guys,

I am trying to generate both the modal trigger and modal dynamically. I have added the href attribute on the modal trigger, yet nothing shows up when I click it.

modal_000001, which is not dynamically generated works. So the issue is only for dynamic generated ones. Any ideas?

Thanks!

## Expected Behavior

Modal to show up for dynamically generated items

## Current Behavior

After I clicked the modal-trigger, nothing happens

* Browser Name and version:chrome
* Operating System and version (desktop or mobile):mac 

<img width="543" alt="screen shot 2017-12-27 at 12 44 41 pm" src="https://user-images.githubusercontent.com/29441592/34389163-1eba84cc-eb06-11e7-81e7-7a5a607bb39c.png">

**Comment by Dogfalo** [comment]
You need to initialize them, see documentation and also follow issue guidelines please

**Comment by tekamolo** [comment]
This is not very well explain. In the documentation we don't know if the initialization is a trigger or just that an initialization...

**Comment by Dogfalo** [comment]
```Javascript
// Step 1: Get element
var modalElement = $('.modal');

// Step 2: Initialize modal
modalElement.modal();
```
