### ISSUE TITLE
[1.0.0 alpha.2] Initialize tabs will error if there is no tab

### ISSUE THREAD

**Issue by cuoilennaocacban** [Dogfalo/materialize#5500]
## Expected Behavior
I have a page with a simple filter to filter out items which is grouped in tabs.
If there is some items, then the tab work perfectly
But if there is none, the tab initialize will fail, making all other initialize fail too

I'm using JQuery

```javascripts
$(document).ready(function(){
    $(".tabs").tabs();
}
```

Currently, the work around I'm using is

```
var isSetTab = _check for your data if you have any group here_
        $(document).ready(function () {
            if (isSetTab) {
                $(".tabs").tabs();
            }
        });
```

**Comment by Dogfalo** [comment]
I was not able to reproduce the issue, please create a codepen that illustrates the problem cleanly.
