### ISSUE TITLE
Inconsistent margins for checkbox inside a card

### ISSUE THREAD

**Issue by WrDX** [Dogfalo/materialize#5502]
## Expected Behavior

Margins for form elements should be consistent.

## Current Behavior

A <p> tag inside a form has margin-bottom of 10px:

```
form p {
    margin-bottom: 10px;
}
```

But when using a checkbox inside a card, this margin gets reset:

```
.card .card-content p {
    margin: 0;
}
```

**Comment by acburst** [comment]
You are correct. This seems to be some old code that is no longer needed.

Removed in b928a60c
