### ISSUE TITLE
add flexbox in the grid

### ISSUE THREAD

**Issue by marketinsider** [Dogfalo/materialize#5505]
please add flexbox to the grid for more flexibility to layout

**Comment by Dogfalo** [comment]
It will be added later after 1.0.0

**Comment by marketinsider** [comment]
ok

**Comment by jacobq** [comment]
@Dogfalo Now that v1.0.0 has been released where can this be tracked? I would really like to be able to order items from top to bottom then left to right in multiple columns. Here's an [example showing what I'm trying to do](https://jsbin.com/defobex/edit?html,css,output)

![image](https://user-images.githubusercontent.com/1633459/45721294-25836e80-bb6d-11e8-8e16-9dbe7815334d.png)

**Comment by OriAmir** [comment]
@Dogfalo @jacobq @marketinsider 
There is something new about flexbox in the grid ? 
tnx

**Comment by Joci933** [comment]
Any news?

**Comment by gviegas91** [comment]
Any news on Flexbox? We are already in 2021..
