### ISSUE TITLE
SASS roboto import, relative patch problem

### ISSUE THREAD

**Issue by filipkroca** [Dogfalo/materialize#5507]
when
import 'materialize-css/sass/materialize.scss';

there is a problem with relative patch in :
materialize-css/sass/components/_variables.scss

#156 $roboto-font-path: "../fonts/roboto/" !default;

the good patch is

$roboto-font-path: "../dist/fonts/roboto/" !default;

Thanks.

**Comment by Dogfalo** [comment]
fonts have been removed in 1.0.0 alpha

**Comment by abenezerabebe** [comment]
Hey, @Dogfalo it doesn't look like fonts have been removed in 1.0.0-alpha.3

What is the plan with fonts?

![image](https://user-images.githubusercontent.com/18615104/34822753-47e0fa66-f6c8-11e7-8bd7-49f7a4ab1890.png)
