### ISSUE TITLE
Tabs Trigger Attribute - Change from HREF to something else ?

### ISSUE THREAD

**Issue by RichieMcMullen** [Dogfalo/materialize#5508]
Apologies if this has been discussed, but I cant seem to find an appropriate answer or solution.

 I'm looking for a way to trigger 'Tabs' with an attribute other than 'HREF'. The problem I'm having is that when I select a tab too quickly (before page is fully loaded) it appends the trigger ID to the url. Refreshing the page afterwards the triggers that particular tab but displays blank content as the tab is not fired from the refresh.

Ideally I dont want to use the HREF attr as I dont want the url to be appended with the ID.

Is there a solution for this or an easy fix ?

**Comment by DanielRuf** [comment]
Please provide a codepen where we can see this.
Generally tabs work with ids and the hash-id href value which does not trigger a page reload.
