### ISSUE TITLE
Form label animation does not fire on password fields when form is auto filled by the browser.

### ISSUE THREAD

**Issue by joearcher** [Dogfalo/materialize#551]
Affecting Linux Chrome Version 40.0.2214.93 (64-bit), Firefox 35.0.1 (64bit)

![screenshot](https://cloud.githubusercontent.com/assets/1125046/5954893/3e1e0cd8-a795-11e4-9fda-facfba2cefb8.png)

**Comment by zippoxer** [comment]
I experience this too when dynamically creating a text input with a value.

**Comment by Dogfalo** [comment]
Can you post code, we can't debug it eitherwise.

**Comment by zippoxer** [comment]
This doesn't affect me anymore. I'm not sure if I was misusing Materialize or an update has fixed this. Anyway, I would consider it closed. Worst case someone else reports similar issue, then we'll get more info.

**Comment by quangv** [comment]
i have this problem too, on Chrome 42.0.2311.90 (64-bit) OSX

when you "save password", then go to the login form again.

![screenshot](http://i.imgur.com/2LNFFZj.png)

my HTML here: https://jsfiddle.net/uop5rqd7/
