### ISSUE TITLE
Can I put an html page in the same directory into collapsible?

### ISSUE THREAD

**Issue by sonyayahab** [Dogfalo/materialize#5518]
I'm using this library for my data maps projects and love much.

I've thought and tried to put a maps html page in the same directory into Collapsible, but I've not done yet. This is the prototype that I fork and edit.
https://codepen.io/anon/pen/RxZOpz

and this is my html data maps project.
http://jar.sonyw.xyz

So how to do that?

**Comment by Dogfalo** [comment]
You can use templating systems so that you're just importing HTML partials or you can try an iframe on your external HTML
