### ISSUE TITLE
BUG REPORT: Compatibility between materialize modals and dropdown selects.

### ISSUE THREAD

**Issue by Riz-waan** [Dogfalo/materialize#5520]
I have a materialize modal with a drop down in it. I am using this: http://materializecss.com/forms.html#select The problem is that since my select options are long it adds a scroll to the modal. It doesn't look professional, it looks like an iframe insert instead. But instead if I use `class="browser-default"` the drop down jumps out of the modal like I want but there is not select styling, which I need. I believe this will be something that will make it look materialized is the compatibility between different materialize components.

**Comment by DanielRuf** [comment]
Please provide a codepen where we can see this.

**Comment by Riz-waan** [comment]
@DanielRuf Here is the code pen. https://codepen.io/Riz-waan/pen/yppBNX It is better to use the full page viewing to see the difference easier.

**Comment by Riz-waan** [comment]
@DanielRuf I also sent a link in gitter, it is easier to see the difference in gitter.

**Comment by DanielRuf** [comment]
Just overwrite the max-height value for the overlay. It uses `max-height: 70%;` by default.

**Comment by DanielRuf** [comment]
Other possible solutions are `position:absolute`, `overflow: visible` and so on but that will break the design.

**Comment by Riz-waan** [comment]
@DanielRuf Can you please show how to do that in a codepen?

**Comment by Riz-waan** [comment]
Thank you I have fixed it. I really appreciate it. I will rename the title as it was not a bug report.

**Comment by Riz-waan** [comment]
@DanielRuf I used `overflow:visible` How does that break the design?

**Comment by DanielRuf** [comment]
If this works without any problems it should be ok.

**Comment by ray007** [comment]
`overflow: visible` does not work in a dialog with scrolling content area.
