### ISSUE TITLE
DatePicker has-event class

### ISSUE THREAD

**Issue by GreWull** [Dogfalo/materialize#5524]
I'm using the 1.0.0-alpha.3.

I was trying to use the events options of the datepicker, which adds the class "has-event" to the dates in the array. Everything works correctly, but there is no "has-event" class defined in the css.

Is this how is supposed to be and we should implement our own css or the class is supposed to exists?

**Comment by Dogfalo** [comment]
It is connected to the `events` setting which allows you to custom style certain dates of your choosing
