### ISSUE TITLE
DatePicker for jalalia( shamsi,persian ) calendar

### ISSUE THREAD

**Issue by monajafi** [Dogfalo/materialize#5525]
This framework is the most complete and easy to use among other material frameworks.
Just if Datepicker supports other calendar types such as jalali(shamsi) we will love it more.
the localization settings just change the week and month labels,but jalali calendar is different than
gregorian, I wonder how can I tweak Datepicker and compile it to main materlize.js file

**Comment by Dogfalo** [comment]
We're not supporting other calendar types

**Comment by ray007** [comment]
It's not supported now.
But why not leave it open as feature request?

**Comment by Dogfalo** [comment]
Because we aren't interested in maintaining several types and the Gregorian calendar is the most popular.

**Comment by ray007** [comment]
Hmm, I suspect I'll need this sooner or later for a customer.
Data should (mostly) be available from `Intl.DateTimeFormat` I think.
I'll open a new issue when I get there...

**Comment by milad-tensy** [comment]
Hi guys
A framework that examines all aspects is a good framework.
Not having a Persian datepicker is a flaw.
I searched  and I found this: https://github.com/sms1989/persian-materialize-datepicker ; But it does not work;
