### ISSUE TITLE
Feature Request: Add chips on mouse blur?

### ISSUE THREAD

**Issue by KeithNdhlovu** [Dogfalo/materialize#5528]
```javascript
      self.$document.off('blur.chips-add', SELS.CHIPS + ' ' + SELS.INPUT).on('blur.chips-add', SELS.CHIPS + ' ' + SELS.INPUT, function(e){
        var $target = $(e.target);
        var $chips = $target.closest(SELS.CHIPS);
        var chipsLength = $chips.children(SELS.CHIP).length;

        e.preventDefault();
        self.addChip({tag: $target.val()}, $chips);
        $target.val('');
        return;
      })

**Comment by KeithNdhlovu** [comment]
The Challenging part of this is determining the mode of adding a chip, like choosing between "pressing enter to add chip" and "just click away to add a chip", would be nice if as a developer i could supply such a mode on the initialization of the chips' options

**Comment by Dogfalo** [comment]
From the implementations we've seen, we don't think it needs to chip on mouse blur.

**Comment by robdg80** [comment]
Here is a use-case when it's relevant. User does not know that he needs to click enter to add a chip. When users clicks "Send email", no email has been captured:
![image](https://user-images.githubusercontent.com/12692680/35576699-f15fa80a-05df-11e8-8b03-ccbc02fe6460.png)

Another use-case is similar in thius case the user can press save or save and close, but the entered "test" will not be saved:
![image](https://user-images.githubusercontent.com/12692680/35576793-2f105294-05e0-11e8-8268-bf0e70b6dcdc.png)

**Comment by egarcia-add** [comment]
`$('#id').find('input').on('blur', function() {
          let value =  $('#id').find('input').val();
          if ( value != '') {
              $('#id').find('input').val('');
              $('#id').chips('addChip', {tag: value});
          }
      });`
