### ISSUE TITLE
[Textfield] M.textareaAutoResize() does not include all scenarios

### ISSUE THREAD

**Issue by vuhrmeister** [Dogfalo/materialize#5529]
Calling `M.textareaAutoResize()` on a field whose height is bigger than expected doesn't have any effect.

## Expected Behavior
Resize should also happen if new height is smaller than the current height.

## Current Behavior
The problem comes when the Field was initially hidden (in my case by collapsible component). The height is then calculated wrong and results in a way to high value. If the field gets visible I call `M.textareaAutoResize()` but it doesn't lower the height.

If the content is smaller the current height is taken. But in given case the current height is wrong or not what we need.

https://github.com/Dogfalo/materialize/blob/f76204b23e02647c4c90b0c304a0ebdb36f17224/js/forms.js#L106
In my case `data-original-height` is not set but the `style.height` is set and this is the value which is taken for comparison later in the code. 

The height should be just re-calculated independent of any initial value. 

## Your Environment
* Version used: 1.0.0-alpha.2

**Comment by acburst** [comment]
Fixed in 9506120c

**Comment by vuhrmeister** [comment]
Cool, thx. Will test that tomorrow in my app.

Btw: you mean this commit: 8a56a9a4922202db0140d7781a8f078247bd0e4f
