### ISSUE TITLE
Headers padding right 

### ISSUE THREAD

**Issue by Nabu-thinker-ru** [Dogfalo/materialize#553]
Why all headers have tiny padding-right? It broke a grid a little bit. There are no padding in google guidelines. ![Image of guidelines](http://material-design.storage.googleapis.com/publish/v_2/material_ext_publish/0Bx4BSt6jniD7TFF1Y3VibWJUMG8/style_typography_styles_lineheight2.png)
http://www.google.com/design/spec/material-design/introduction.html

**Comment by acburst** [comment]
Please give code examples and more concrete information. This is too little to investigate any issue.

**Comment by Nabu-thinker-ru** [comment]
![mattirial](https://cloud.githubusercontent.com/assets/5621752/5972061/833f8936-a885-11e4-90ce-127aaf49705e.png)

**Comment by Nabu-thinker-ru** [comment]
```
<!DOCTYPE html>
<html>
<head>
<meta charset="UTF-8">
<title>Insert title here</title>

<link type="text/css" rel="stylesheet" href="{% static "css/materialize.min.css" %}"  media="screen,projection"/>
</head>
<body>

<div class="container"><div class="row"><div class="col s12">
  <h1>H11111111111111111111</h1>
  <p>Hsdadalsdkalsdjadslaj</p>
</div></div></div>
      <script type="text/javascript" src="https://code.jquery.com/jquery-2.1.1.min.js"></script>
      <script type="text/javascript" src="{% static "js/materialize.min.js" %}"></script>     
</body>
</html>
```

**Comment by Dogfalo** [comment]
I don't see any padding

**Comment by Dogfalo** [comment]
This is how the browser renders larger type. This is not something we added.
