### ISSUE TITLE
Show-on-small class does not work

### ISSUE THREAD

**Issue by alanneese** [Dogfalo/materialize#5531]
When asking general "how to" questions:

- Please do not open an issue here!
- Instead, ask for help on [StackOverflow](stackoverflow.com/questions/tagged/materialize) or in our [Gitter](https://gitter.im/Dogfalo/materialize) channel.

- Read the [CONTRIBUTING document](https://github.com/Dogfalo/materialize/blob/master/CONTRIBUTING.md) Any issues that are violating the contributing guidelines, will be closed!
- [Search for duplicate or closed issues](https://github.com/Dogfalo/materialize/issues?utf8=%E2%9C%93&q=is%3Aissue) and make sure to go through our [labels](https://github.com/Dogfalo/materialize/labels).
- Prepare a [reduced test case](https://css-tricks.com/reduced-test-cases/) for any bugs.

## Steps to Reproduce (for bugs)

1. https://codepen.io/alanneese/pen/ZvvmjN
2.
3.

## Your Environment

* Version used: materialize/0.100.2/css
* Browser Name and version: Chrome 63
* Operating System and version (desktop or mobile): Windows 10 desktop
* Link to your project (if appropriate): https://codepen.io/alanneese/pen/ZvvmjN

**Comment by acburst** [comment]
Please fill out the issue template with more information. Also your codepen link doesn't work

**Comment by alanneese** [comment]
https://codepen.io/alanneese/pen/QamMbV




<http://www.lockerroomtech.com>

**Comment by acburst** [comment]
The class itself doesn't hide, it only applies display block on small screens. Its up to you to apply the styles to hide the element on default however you see fit.

**Comment by alanneese** [comment]
The doc says "Show for Mobile Only".  The doc infers that the class will
hide on everything higher than mobile.




<http://www.lockerroomtech.com>

**Comment by Andruso** [comment]
Agreed with @alanneese, it's a bug in either documentation or code.

IMO, the behaviour in documentation would be more useful i.e. "show-on-X-only" would complement "hide-on-X-only" very nicely.

**Comment by briavers** [comment]
Still not fixed :(
