### ISSUE TITLE
Forms.html page - the 'Initialize' of <select> requirement needs to be at the top of the section

### ISSUE THREAD

**Issue by paul-hammant** [Dogfalo/materialize#5533]
Speed readers and avid copy/pasters are going to miss that advice for `<select>`. They were productive already w/ Materialize and just thought to paste in one more section of example code :(

![image](https://user-images.githubusercontent.com/82182/34694198-34b2f01a-f494-11e7-941c-3d2901fef5d5.png)

**Comment by Dogfalo** [comment]
The upcoming documentation is like this: http://next.materializecss.com/select.html
