### ISSUE TITLE
Suggestion for "Today" button on DatePicker (v 1.0)

### ISSUE THREAD

**Issue by devsware** [Dogfalo/materialize#5535]
I was testing the new 1.0 version and I found a possible glitch with the "Today" button when using a minDate in the future (or a maxDate in the past).

I created a DatePicker which allows the user to select only dates in the future (i.e. for picking an appointment); by default, clicking on the "Today" button makes the DatePicker close and puts the current date inside the input field (breaking the rule I added with a minDate "starting from tomorrow").

## Expected behaviour
The date should not be picked since it's out of range.

## Actual behaviour
It's possible to select an out-of-range date.

## Workaround
Having only one calendar on the page I could override this behaviour by adding

`onOpen: function()
            {
                $(".datepicker-today").addClass('disabled');
                return;
            }`

The same thing could happen using a maxDate on the past, allowing the user to select the "today" date even if the day itselft is not enabled on the calendar.

Having something like a "disableTodayButton" (boolean) option could be useful to prevent this possible flaw on a "per DatePicker" basis without using `onOpen` and adding extra code to target the correct button to disable.

**Comment by Dogfalo** [comment]
Good point, maybe the today button should disappear when it is not within the bounds of the min and max date

**Comment by Dogfalo** [comment]
Sure, please make sure to read over the contributing guidelines and work off the v1-dev branch

**Comment by Dogfalo** [comment]
We removed the today button in d613187735a908b28682ed85ddcab91929d99d75
