### ISSUE TITLE
dropdown with icons not wide enough

### ISSUE THREAD

**Issue by ray007** [Dogfalo/materialize#5538]
A dropdown menu with icons from a menu-button in a navbar is not wide enough to display its content without scrolling.

## Expected Behavior

Dropdown container is wide enough to display its content

## Current Behavior

Dropdown container has horizontal scrollbar at the bottom

## Steps to Reproduce (for bugs)
see https://codepen.io/anon/pen/WdzxLz

## Context
I'm trying to have a nice menu dropping down from a button at the right edge of the navbar.

## Your Environment
checked on several desktop browsers under Windows

**Comment by StephenMP** [comment]
You can always turn off `constrainWidth` and set your own width for the `.dropdown-content`

https://codepen.io/anon/pen/GQOpVJ

**Comment by ray007** [comment]
Turning off `constrainWidth` does not help, and setting the width is not so easy since the strings in my app are localized.

**Comment by light-flight** [comment]
```
.dropdown-content {
  width: auto !important;
  li a {
    white-space: nowrap;
  }
}
```
worked for me.
Materialize version is 1.0.0-alpha.3

**Comment by StephenMP** [comment]
Really? Because turning off constrainWidth works with the pen:

https://codepen.io/anon/pen/GQOpVJ

**Comment by light-flight** [comment]
It doesn't work with
```
.dropdown-content {
  white-space: nowrap;
}
```

**Comment by StephenMP** [comment]
Why would you need the `nowrap`? If you turn off `constrainWidth` the width should auto-adjust to the length of the content within it. So you wouldn't need `nowrap` since it wouldn't wrap the text to begin with.

**Comment by light-flight** [comment]
If you don't use any icons everything is ok. But if you use an icon, you probably need it on the same line as word..
![image](https://user-images.githubusercontent.com/10468814/36398341-af201d14-15d7-11e8-8d62-3c61e029174e.png)

**Comment by cafeTechne** [comment]
What is the current status of this issue? Does anyone have any quick fixes that work? I can't seem to wrangle the icon onto the same line with CSS!

**Comment by acburst** [comment]
This pen works on alpha 4. If you add constrainWidth: false it should work.
