### ISSUE TITLE
Range slider in Chrome for Android broken

### ISSUE THREAD

**Issue by CoDEmanX** [Dogfalo/materialize#554]
The slider does not show the value on my Nexus 5 (Android 5.0). At most, the background for the label shows for a second if you tap (doesn't have the correct shape however):

![screenshot_2015-01-26-20-24-20](https://cloud.githubusercontent.com/assets/1309249/5955787/cbe736d2-a7a6-11e4-82b0-f4b598cc9b0f.png)

It does not show at all if you swipe.

**Comment by acburst** [comment]
Yes, the range slider is not exactly the best. We are still planning on either improving this one heavily or just making a new one from scratch

**Comment by Dogfalo** [comment]
Duplicate of #436
