### ISSUE TITLE
Materialize Icons not working when deployed to GitHub Pages

### ISSUE THREAD

**Issue by lch2001** [Dogfalo/materialize#5541]
I deployed my create-react-app that uses Materialize to GitHub Pages. The icons work in local enviroment but when I deploy them they use show up as text.

I have added this to my index.html:
`<link rel="stylesheet" href="http://fonts.googleapis.com/icon?family=Material+Icons">`

**Comment by DanielRuf** [comment]
Please use `https://fonts.googleapis.com/icon?family=Material+Icons`.
