### ISSUE TITLE
The current approach of working with select elements is wrong

### ISSUE THREAD

**Issue by newpen** [Dogfalo/materialize#5544]
After adding materialize to my website, all the select elements disappeared. 

I have to read through the whole documents to know that I have to initialize it first! What else should be also initialized first when using the library? I only want to add some of the material effects to my website, not expecting it to break any other features that are already working properly on my website!

**Comment by WrDX** [comment]
I recon you're using the V1 alpha release, it's not done yet so please don't expect it, nor it's documentation, to be perfect.

As far as I understand it the auto-init code is being removed for most, if not all, elements that might require initialisation. This seems to me as a good thing.

There will probably be a file you can include or a function you can run at some point before the final release to initialize everything that needs initialization.

**Comment by newpen** [comment]
It have tried different releases but its implementation is about the same. The removal of auto-init is surely a good thing, but if I don't initialize it, the css in the materialize library made all those select fields hidden.

And it's not just my opinion, this was from several years ago:
https://stackoverflow.com/a/28259097/2335065

The thing is even if I add "browser-default" class to my select fields, it would still destroy all my existing layouts. It added many unnecessary css styles to my fields. It added width, paddings, border, and "display: block" to the fields, but the browser default styling to select is "display: inline-block". All of them making the whole library unusable, though I love all the other parts of the library. It seems to me that this implementation has been in this way for years, not just in this alpha release or so.

**Comment by WrDX** [comment]
I think issue #5294 is a (partly) duplicate

**Comment by Dogfalo** [comment]
In the future we will be making changes to relax the styling on base elements, select will also be a target in these changes. But for now 1.0 stability is the primary concern
