### ISSUE TITLE
Javascript: too much recursion with parallax

### ISSUE THREAD

**Issue by ng-galien** [Dogfalo/materialize#5549]
### Every browser trigs this error when using parallax js function
 
I have two parallax images like in the sample

![mat 3](https://user-images.githubusercontent.com/33391039/34910881-2e2f45a8-f8be-11e7-89ea-55d588becd8a.jpeg)

**Comment by TmThvnn** [comment]
I have the same problem

**Comment by Dogfalo** [comment]
Fixed here 13b1cdfb14b2746a56d45176704d0587f0ef443c
