### ISSUE TITLE
Example promotion table (CSS Grid) not mobile-compatible

### ISSUE THREAD

**Issue by CoDEmanX** [Dogfalo/materialize#555]
The headlines are cutoff and thus not working on mobile phone screens. Shouldn't such tables be responsive to screen width by default?

![screenshot_2015-01-21-14-53-15](https://cloud.githubusercontent.com/assets/1309249/5955874/cfeb0294-a7a7-11e4-8dd9-0311311e2760.png)

**Comment by joearcher** [comment]
It quite clearly states in the docs, that the examples at that point are not responsive for simplicity.
