### ISSUE TITLE
New features request

### ISSUE THREAD

**Issue by Ardutronico** [Dogfalo/materialize#5552]
As of v1.0.0 alpha, these are still not available. I'd like to know if you're planning on implementing these and when.

## Expected Behavior
1. All the [progress indicators](https://material.io/guidelines/components/progress-activity.html).
2. [Non-modal bottom sheets](https://material.io/guidelines/components/bottom-sheets.html).
3. [Expansion panels](https://material.io/guidelines/components/expansion-panels.html).
4. [Steppers](https://material.io/guidelines/components/steppers.html)

## Current Behavior
1. Buffer and query linear and determinate and integrated circular indicators are missing.
2. Overlay is mandatory.

3 & 4 are completely missing.

## Possible Solution
There's already a library for [steppers](https://kinark.github.io/Materialize-stepper/).

## Context
Right now I implement non-modal bottom sheets with a dirty hack in JS (removing the overlay after opening it). The progress indicators are interesting for allowing users to know more exactly what's happening.

**Comment by Dogfalo** [comment]
Our focus is currently getting 1.0 stable

**Comment by ray007** [comment]
Not that I need it now, but why not keep the issue open for post-1.0?

**Comment by Ardutronico** [comment]
Yes, that's what I was thinking when writing the issue: know if and when they'll implement it, not if they'll do it now.
