### ISSUE TITLE
.brand-logo in navbar left position is 0

### ISSUE THREAD

**Issue by jennydaman** [Dogfalo/materialize#5553]
This is what it **should** look like

![image](https://user-images.githubusercontent.com/20404439/34923903-e8bd1de6-f96d-11e7-97d5-bd1c0e2a453b.png)

So the example at http://materializecss.com/navbar.html#right is correct. However, everywhere else on the page shows this

![image](https://user-images.githubusercontent.com/20404439/34923927-167ad886-f96e-11e7-8049-7c2906d9a40f.png)

`left: 0`
For example: http://materializecss.com/navbar.html#mobile-collapse

Flaw exists with most recent npm version v0.100.2.

I tried visiting http://materializecss.com/navbar.html on chromium Chromium 63.0.3239.132, Firefox 57.0.4, and Epiphany (gnome-web) 3.26.5.1. Same result.

**Comment by acburst** [comment]
We suggest you use a container or some sort of wrapper div to set a margin. Adding styles to the element itself can make writing css unintuitive. We try and keep margins on individual elements to a minimum to allow proper alignment when using the grid system and other containers.

**Comment by jennydaman** [comment]
While my own project was affected by this, I'm more concerned with the fact that this bug exists on materializecss.com itself.

**Comment by carlostighe** [comment]
In terms of this the first example has a padding because its a column within a row. The rest of the examples are just navs.   
I added the padding like in the first example by doing this:  

```
<div class="navbar-fixed">
  <div class="row">
    <nav>
      <div class="nav-wrapper bg-dark">
        <div class="col s12">
          <a href="" class="brand-logo">
            Logo
          </a>
          <a href="#" data-target="mobile-demo" class="sidenav-trigger">
            <i class="material-icons">menu</i>
          </a>
          <ul class="right hide-on-med-and-down">
            <li>
              <a href="">link</a>
            </li>
          </ul>
        </div>
      </div>
    </nav>
  </div>
</div>

<ul class="sidenav" id="mobile-demo">
  <li>
    <a href="">link</a>
  </li>
</ul>
```
