### ISSUE TITLE
[1.0.0-alpha.3] TypeError: Cannot read property 'jquery' of null

### ISSUE THREAD

**Issue by andrey-helldar** [Dogfalo/materialize#5554]
I'm using MaterializeCSS + VueJS with Laravel Webpack.

## Expected Behavior
Initializing the form when the component is loaded.

## Current Behavior
```
[Vue warn]: Error in mounted hook: "TypeError: Cannot read property 'jquery' of null"
```

![2018-01-15 09-53-03 developer tools - http localhost 3000 sales-spec](https://user-images.githubusercontent.com/10347617/34930300-ef17de6c-f9d9-11e7-814b-f95cf2efb73c.png)

## Steps to Reproduce (for bugs)
```javascript
//...
data() {
  return {
    modalId: 'modal-order'
  }
},
mounded() {
  this.init();
},
methods: {
  init() {
    let elem = document.querySelector(`#${this.modalId}`);
    this.instance = M.Modal.init(elem, {
        onOpenStart: () => {
            this.show();
        },
        onCloseEnd: () => {
            this.resetForm();
        }
    });
  }
}
```

## Possible Solution
If you execute the code after jQuery is loaded, the error disappears:

```javascript
//...
data() {
  return {
    modalId: 'modal-order'
  }
},
mounded() {
  this.init();
},
methods: {
  init() {
    $(document).ready(() => {
        let elem = document.querySelector(`#${this.modalId}`);
        this.instance = M.Modal.init(elem, {
            onOpenStart: () => {
                this.show();
            },
            onCloseEnd: () => {
                this.resetForm();
            }
        });
    });
  }
}
```

## Your Environment
* Version used: 1.0.0-alpha.3
* Browser Name and version: All latest browsers (Google Chrome, Mozilla Firefox, Microsoft Edge, Opera)
* Operating System and version (desktop or mobile): Windows 10 Pro desktop, Windows 7 desktop.

**Comment by Dogfalo** [comment]
`"TypeError: Cannot read property 'jquery' of null"` sounds like the element reference is null at the point of execution and doesn't have anything to do with jquery.

**Comment by andrey-helldar** [comment]
Why? If you execute the code, an error occurs:
```javascript
let elem = document.querySelector(`#modal-order`);
M.Modal.init(elem);
```

And when you execute
```javascript
$(document).ready(() => {
  let elem = document.querySelector(`#modal-order`);
  M.Modal.init(elem);
});
```
 there are no errors.

**Comment by Dogfalo** [comment]
Because it says cannot read property 'jquery' of null, meaning the null reference of the element is the problem not the jquery property

**Comment by Dogfalo** [comment]
Try using https://vuejs.org/v2/api/#ref instead of query selector in Vue

**Comment by andrey-helldar** [comment]
Hmm ... I did not think about it, thanks :)
