### ISSUE TITLE
Checkboxes in multiple select not aligned with text

### ISSUE THREAD

**Issue by mrHJS** [Dogfalo/materialize#5555]
Hello,

I have been using MaterializeCSS for more than a year now on my website. In the beginning everything was fine, but over the time (it was one update and I don't know which one) the select multiple part got broken and is still broken.

The problem is: The checkbox and the text are not aligned. It does not even work in the documentation. See this screenshot
https://picload.org/view/ddcgagdr/screenshot.jpg.html

I am using the v.0.100.2 version. I tried to update to the latest alpha-03 release, however this completely breaks my design and even with the update tutorial there is much more work to be done.

So my question is: How can I align the checkboxes and the text in multiple selects?

Thank you very much!

**Comment by chadingles** [comment]
I used this to hack in a fix for this issue:

    .multiple-select-dropdown label {
      top: -10px !important;
    }

**Comment by acburst** [comment]
We are not planning on releasing anymore to the v0.100.x version. We are focusing all our attention on v1.0.0. This issue is currently fixed on our Alpha version
