### ISSUE TITLE
Modals do not respond on different layouts Rails

### ISSUE THREAD

**Issue by mau5ken** [Dogfalo/materialize#5559]
Im using Bottom Sheet Modals in a Ruby on Rails application.
I have 4 layouts or .html.erb views in it.
Im using the new version gem for materializecss. 

These models display images like a gallery, I used it like this in order to make it UX friendly and to not take out the user to another web page.

The problem comes when in one layout I test the modals. When I switch in to another layout that has the exactly modals with different images. The modal stops working.

I was using
`  <a class="waves-effect waves-light btn modal-trigger" href="#modal1">Modal</a>
`
but then I swicth it to 
`  <button data-target="modal1" class="btn modal-trigger">Modal</button>
`

And it stills dosent work. It only works in one layout but when I got another layout my modal dosent work. The only way to make it workk its just refreshing, but im not going to display a message to the user to refresh the page in order to view the button model to show..

Hope can help with this!

**Comment by Dogfalo** [comment]
Modals need to be initialized if created dynamically
