### ISSUE TITLE
Sidebar active state highlighting not full width / offset

### ISSUE THREAD

**Issue by CoDEmanX** [Dogfalo/materialize#556]
When you click on a menu entry, the blue background (active state) does not span over the entire row and has some offset. Would be nicer if it were just like the reddish background for the current page.

![screenshot_2015-01-29-11-11-28](https://cloud.githubusercontent.com/assets/1309249/5955901/196ccd3a-a7a8-11e4-8919-e781e02cfb0a.png)

**Comment by Dogfalo** [comment]
This is the tap active state chrome puts on. We are not going to remove it for now.
