### ISSUE TITLE
picker buttons

### ISSUE THREAD

**Issue by ray007** [Dogfalo/materialize#5561]
There's 2 things I'm missing for date- and timepicker:
- option to get rid of the clear button
- add a cancel button to the datepicker

The docs at https://material.io/guidelines/components/pickers.html do not show clear-buttons at all.
Not sure where to best fit "cancel" with "today" in the datepicker, but I'll try to come up with a PR for this if nobody else beats me to it.

**Comment by Dogfalo** [comment]
Added in d613187735a908b28682ed85ddcab91929d99d75
