### ISSUE TITLE
datepicker today

### ISSUE THREAD

**Issue by ray007** [Dogfalo/materialize#5568]
When using the `today` button of the datepicker, the date is selected and the dialog closed.
When the dialog is reopened, the selected date is marked differently than after selecting a date and clicking `ok`.
I'd also argue that `today` should not close the dialog, but that's a matter of taste I guess...

**Comment by DanielRuf** [comment]
Please provide a screenshot of this and the used version.

**Comment by ray007** [comment]
Using the "today" button and reopening the picker:
![image](https://user-images.githubusercontent.com/126712/35086638-868f897a-fc2d-11e7-9b86-496cae7b750e.png)
Picker with properly selected date:
![image](https://user-images.githubusercontent.com/126712/35086703-decd46a4-fc2d-11e7-890a-4aca3988c42e.png)

All with tip of `v1-dev` branch with my changes for the buttons applied.

**Comment by Dogfalo** [comment]
We may remove the today button, so not fixing this issue until we decide on that.

**Comment by DanielRuf** [comment]
@Dogfalo why? This would hurt the a11y and UX as there is no easy option to select the current date like it is in the native datepicker.

**Comment by ray007** [comment]
As I already wrote above: I'd be most happy if "today" selected the current day but didn't close the dialog.

**Comment by DanielRuf** [comment]
> As I already wrote above: I'd be most happy if "today" selected the current day but didn't close the dialog.

The buttons at the top all close the dialog of the date/timepicker so this is still consistent imo.

**Comment by ray007** [comment]
How about pushing the today-button into the area showing the currently selected date?

**Comment by DanielRuf** [comment]
> How about pushing the today-button into the area showing the currently selected date?

How do you make clear UX wise that the date on the left is currently not the current date but the button updates it to the current date?

**Comment by ray007** [comment]
Not yet sure, which is why I keep presenting ideas.
Maybe that's also the reason the google docs don't show a today-button for the date picker?
But I'd already be happy if the selection-issue after using "today" was fixed...

**Comment by DanielRuf** [comment]
> Maybe that's also the reason the google docs don't show a today-button for the date picker?

In this case https://github.com/Dogfalo/materialize/issues/5568#issuecomment-359082117 makes much sense to be consistent with the official Google Material specifications.

**Comment by ray007** [comment]
With this argument, you'd have to remove the clear buttons in both pickers too.

**Comment by Dogfalo** [comment]
Removed today btn and added option for clear btn in d613187735a908b28682ed85ddcab91929d99d75
