### ISSUE TITLE
Failing to start in windows: 404 for fsevents-binaries.s3-us-west-2.amazonaws.com/v1.0.15

### ISSUE THREAD

**Issue by Imogynn** [Dogfalo/materialize#5570]
Having problem starting my team's project, didn't immediately see a fix in the other issues.

It looks to me like the win32 for the binaries may be gone?

Thanks!

=> Errors prevented startup:

   While loading package materialize:materialize@0.98.2:
   error: Command failed:
   C:\Users\desma\AppData\Local\.meteor\packages\meteor-tool\1.5.1\mt-os.windows.x86_32\dev_bundle\bin\npm.cmd
   rebuild --update-binary
   node-pre-gyp ERR! Tried to download(404):
   https://fsevents-binaries.s3-us-west-2.amazonaws.com/v1.0.15/fse-v1.0.15-node-v46-win32-ia32.tar.gz
   node-pre-gyp ERR! Pre-built binaries not found for fsevents@1.0.15 and
   node@4.8.4 (node-v46 ABI) (falling back to source compile with node-gyp)
   Traceback (most recent call last):
   File
   "C:\Users\desma\AppData\Local\.meteor\packages\meteor-tool\1.5.1\mt-os.windows.x86_32\dev_bundle\lib\node_modules\node-gyp\gyp\gyp_main.py",
   line 16, in <module>
   sys.exit(gyp.script_main())
   File

**Comment by Imogynn** [comment]
Starting to look like this is a dupe of [https://github.com/Dogfalo/materialize/issues/4193](url)

Going to try various tricks in there, but that claims to be closed/fixed. So may be a reoccurence. 

Apologies if this a dupe.

**Comment by DanielRuf** [comment]
Please close this issue as it is resolved. 0.98.2 is very old and we have no control over the binaries of dependencies.
