### ISSUE TITLE
sideNav only works with .min.css/js files.

### ISSUE THREAD

**Issue by Hovsky** [Dogfalo/materialize#5576]
as the title suggests,

sideNav only works with minimal files of both CSS and JS. I tried duplicating the problem by chaging files names and the problem still occured. Any answer why? 
How long untill sidenav will be available on normal, editable part of files.

Thank you

**Comment by acburst** [comment]
My local test files are using unminified versions. Not sure whats causing your problems

**Comment by DanielRuf** [comment]
How is your project setup? Do you use webpack, ugligyjs or some other build setup?

Are there any errors in your browser console?

**Comment by DanielRuf** [comment]
Hm, why was this closed without any comments @Dogfalo?

**Comment by Dogfalo** [comment]
We were unable to reproduce the and will wait for a response, in the case that there is no response we do not have to sift through issues and close them.

**Comment by DanielRuf** [comment]
Ok. And what about (very) old open issues regarding 0.x?

**Comment by Dogfalo** [comment]
We will have to go through all the issues and determine which are deprecated and which are still relevant

**Comment by Hovsky** [comment]
I still don't understand what I'm doing wrong. I have downloaded materialize anew, and started new folder and new project. test file includes only sidenav and nothing else (besides head part and initialization). I gave up and made jscript sidenav for current project. 
In conclusion, code isn't changed at all in test project, and sidenav is still only working with .min.css and .min.js

I'm sorry for slow reply.

**Comment by DanielRuf** [comment]
@Hovsky is this a pure html project without any bundlers or other thingd which transform files? Also are there any errors in your browser console?

**Comment by Hovsky** [comment]
test file is pure html with added materialize files and initialization jscript file.
There aren't any errors except standard $ is not defined, document is not defined etc.
If it helps, I'm using brackets for coding and opening it on google chrome latest version

**Comment by DanielRuf** [comment]
> There aren't any errors except standard $ is not defined, document is not defined etc.

These are not standard. jQuery and so on should be included. Please provide a link to the example. You can use GitHub pages for example.

**Comment by Hovsky** [comment]
![head file](https://user-images.githubusercontent.com/32835549/35196164-9c058568-fece-11e7-9f19-1d976b265cc0.png)
![js initializatioin](https://user-images.githubusercontent.com/32835549/35196163-9be376f8-fece-11e7-811a-57bcb9babaf8.png)

this is my current project. Not the test file. Although it is giving me many errors, they're always the same. $, document etc not defined, warnings "expected "whitespace" between ({" and similar. But everything is working even thought warnings still persist

**Comment by DanielRuf** [comment]
Move the script tags right before `</body>` and after them your own code.

**Comment by DanielRuf** [comment]
The other things are ESLint related.

**Comment by Hovsky** [comment]
`</body>` is the end of the code?
so are you saying I should add script tags at the beggining, near the `<body> `and before my code, or at the end near `</body>` and after my code?

`<body>`
`my code`
`</body>`
`</html>`

**Comment by DanielRuf** [comment]
> or at the end near </body> and after my code?

There

**Comment by Hovsky** [comment]
![not working](https://user-images.githubusercontent.com/32835549/35196382-a1ca1d4e-fed1-11e7-9c21-9c7bda49df01.png)
![working](https://user-images.githubusercontent.com/32835549/35196383-a1e78cda-fed1-11e7-83d7-dd2750f5f3f2.png)

Here you can see the error. I didn't manage to snapshot, but it will only work if both .css and .js are minified versions

**Comment by DanielRuf** [comment]
Please try to open the file directly fro the filesystem that you see on the left side. You are clearly using some dev server and this does probably not deliver all files.

**Comment by Hovsky** [comment]
![not working](https://user-images.githubusercontent.com/32835549/35196498-15994686-fed3-11e7-8798-c0edbb6f17e5.png)

i opened directly from file directory, into google chrome. Now both, minified and non minified version are showing the same error. It shouldn't be a problem, since everything else was working perfectly from materialize, and I do have to say it is fantastic :)

**Comment by DanielRuf** [comment]
please check the file paths and the browser console for 404 errors

**Comment by Hovsky** [comment]
Everything is referenced correctly in project and i can't find the problem there

**Comment by DanielRuf** [comment]
I bet that there are 404s or something else. Please check the network tab in your browser console.

**Comment by Hovsky** [comment]
If it's not much of a hassle, could you help me and say how to do that?

**Comment by Nrde** [comment]
If you have Chrome of Firefox, hit F12 (on windows) or ctrl-shift-i, cmd-shift-i and then select network tab. (you may have to reload the page to get up to date info). This is basic thing when doing web development so I also suggest you look into developer tools in more detail when you have time.

**Comment by DanielRuf** [comment]
The developer tools of the browser. You can access them also with right click - inspect. There is also the console that I mean.

**Comment by Hovsky** [comment]
![screenshot_1](https://user-images.githubusercontent.com/32835549/35215542-dde84538-ff64-11e7-8b3d-488e0fc1d627.png)

**Comment by DanielRuf** [comment]
@Hovsky please move your script tag with your sidenav initialization and the other things after jquery.js and materialize.js.

```
your markup
jquery
materialize
your code
</body>
```

**Comment by Hovsky** [comment]
It is in that order. I just added async and defer on script tags, after pointing out the flaw in my code.

This picture is from reply before, but it is still in that order

![35196382-a1ca1d4e-fed1-11e7-9c21-9c7bda49df01](https://user-images.githubusercontent.com/32835549/35216055-94a15372-ff66-11e7-83b8-2710781e91b1.png)

**Comment by DanielRuf** [comment]
Please upload the files to GitHub pages or provide a zip with your files.

**Comment by Hovsky** [comment]
[website test.zip](https://github.com/Dogfalo/materialize/files/1651638/website.test.zip)

**Comment by DanielRuf** [comment]
[website_fixed.zip](https://github.com/Dogfalo/materialize/files/1651689/website_fixed.zip)

I guess you used the old docs for the new version. The new docs are on http://next.materializecss.com

**Comment by Hovsky** [comment]
it works. Could you explain what you did?

I started working with old materlialize, but as soon as 1.0 came out, I upgraded and modified the code

**Comment by Nrde** [comment]
easiest is to use a diff tool like for example https://www.diffchecker.com/

**Comment by DanielRuf** [comment]
it should be `sidenav` instead of `sideNav`

**Comment by Hovsky** [comment]
@DanielRuf It works fine on test file, but doesn't work when i put it together with parallax effect. I found some free hosting service, here is the link
https://jedantest.000webhostapp.com/Stranice/EN/index.html
Unfortunately, I uploaded yesterday so there isn't sidenav included.



@Nrde thank you, it is really helpful 👍

**Comment by DanielRuf** [comment]
Did you consult the new docs, also for parallax?

**Comment by DanielRuf** [comment]
I guess we can lock this issue here. We should move this conversation to https://gitter.im/Dogfalo/materialize

cc @Dogfalo
