### ISSUE TITLE
Radio buttons not working

### ISSUE THREAD

**Issue by asaadmahmood** [Dogfalo/materialize#558]
When I click on radio buttons, they don't work. They work if I click on the actual radio buttons by removing their css.
I am using these inside wordpress so maybe that's causing some issues. I don't get any console errors though.
![screen shot 2015-01-29 at 7 42 12 pm](https://cloud.githubusercontent.com/assets/7103043/5959329/166fda72-a7ef-11e4-834c-1963d59c4eba.png)
![screen shot 2015-01-29 at 7 42 29 pm](https://cloud.githubusercontent.com/assets/7103043/5959330/1674b42a-a7ef-11e4-9f84-4339b7465537.png)

**Comment by asaadmahmood** [comment]
The label is also not triggering the default radio button too. So the label isn't working.

**Comment by Dogfalo** [comment]
This is not a problem on our end

**Comment by asaadmahmood** [comment]
Okay.

**Comment by Neotriz** [comment]
If anyone is wondering how to solve this, simply add a custom css and adjust the html's radio button accordingly.

I had similar problem using Redux-Form, but was able to solve it as so:

http://stackoverflow.com/questions/41025124/redux-form-v6-materialize-css-s-radio-button-not-working

**Comment by Revannath** [comment]
You can Use below css:

[type="radio"]:not(:checked), [type="radio"]:checked {
    left: 0 !important;
    visibility: visible !important;
	opacity:0;
}
[type="radio"]:focus + label::before{
	box-shadow: 0 0 10px #285278 !important;
}

**Comment by coolternet** [comment]
not working atm
