### ISSUE TITLE
collapsible callback functions don't pass the li element [v1.0]

### ISSUE THREAD

**Issue by jakalan** [Dogfalo/materialize#5582]
## Expected Behavior

collapsible options onOpenStart, onOpenEnd, onCloseStart, onCloseEnd should pass the li element that was opened or closed as an argument, as described in the docs for collapsible options.

## Current Behavior

the callback functions passes an empty object.

## Steps to Reproduce (for bugs)

1. use first collapsible on docs page collapsible.html
2. include callback function with console.log the passed argument

## Your Environment

* Version used: 1.0.0.3 (same in earlier 1.0 Versions)
* Browser Name and version: all Browsers
* Operating System and version (desktop or mobile):
* Link to your project (if appropriate):

**Comment by acburst** [comment]
Can you provide a codepen reproducing this? I just tested this locally and it works for me.

**Comment by jakalan** [comment]
thank you.
Here is the codepen: https://codepen.io/anon/pen/opKGVW#anon-signup

**Comment by acburst** [comment]
JSON stringify is not needed. If you just change your alert functions to console.log and just log the el element itself, you can see it passes back the correct html element.
