### ISSUE TITLE
Feature Request: Discourage use of bower

### ISSUE THREAD

**Issue by jacobq** [Dogfalo/materialize#5586]
As [the bower home page](https://bower.io/) itself even states in a prominent banner, "...psst! While Bower is maintained, we recommend using Yarn and Webpack for front-end projects read how to migrate!" I think it would be best to remove mention of bower in the "Getting Started" guide, i.e. delete:

> Bower
> You can also get the latest release using bower. This release contains source files as well as the
> compiled CSS and JavaScript files.

Of course, I'm not suggesting that materialize no longer work with bower as that could impact a number of users who have used materialize in existing projects. However, I think steering new users away from bower would be the kindest course of action. It's not that bower is "bad" but rather that it's really no longer necessary and has been becoming less relevant and less supported for quite some time now. In other words, it's just extra, unnecessary complexity that new projects have no use for.

See also:
* https://snyk.io/blog/bower-is-dead/
* https://www.reddit.com/r/javascript/comments/5ls30m/is_bower_dead_should_we_start_using_other/
* https://bower.io/blog/2017/how-to-migrate-away-from-bower/

**Comment by Dogfalo** [comment]
Merged PR
