### ISSUE TITLE
this._handleInputFocusBound seems never defined in select.js

### ISSUE THREAD

**Issue by MathieuDerelle** [Dogfalo/materialize#5589]
is it normal that this._handleInputFocusBound is never defined in select.js ?

https://github.com/Dogfalo/materialize/blob/69fc408639d4ac3a87916942d230b8cb1089a573/js/select.js#L91

has it been removed and this piece has been forgotten ?

**Comment by Dogfalo** [comment]
Removed in ed4ae6f810ebc10463647a1e20fa6efa21d653d8. Thanks!
