### ISSUE TITLE
RE: Issue with Tabs Jumping Scroll Position #3955

### ISSUE THREAD

**Issue by nfgallimore** [Dogfalo/materialize#5590]
Hi I am not sure if my comment on the closed issue will be seen. But this issue is reoccurring: https://github.com/Dogfalo/materialize/issues/3955
Thank you.

TLDR:

Try clicking the tabs on an iPhone on: http://codepen.io/johann_abraham/pen/yVPJme

**Comment by reckerswartz** [comment]
Hey Nick Gallimore,
the issue is solved in latest release please follow codepen https://codepen.io/anon/pen/jYRXJd
with the updated version (tested on Mac and iPhone , browser safari).

**Comment by reckerswartz** [comment]
issue confirmed.

**Comment by acburst** [comment]
The version you are using in your codepen is 0.97.8. We can't retroactively fix bugs. You will have to try a newer version to see if this issue still exists.

**Comment by reckerswartz** [comment]
@acburst also test on latest release 1.0alpla3 https://codepen.io/anon/pen/jYRXJd still issue is there at iPhone Safari.
