### ISSUE TITLE
photoCaption isn't working in alpha

### ISSUE THREAD

**Issue by Tajnymag** [Dogfalo/materialize#5594]
## Expected Behavior
After clicking on the second sample image, it should open in a materialboxed and have a caption.

## Current Behavior
When clicked, the whole page freezes and I get a `TypeError: this.$photoCaption is undefined` printed to the console

## Possible Solution
Rewrite one more jQuery method to vanilla.js

## Steps to Reproduce (for bugs)
1. Open [media section of next.materializecss.com](http://next.materializecss.com/media.html)
2. Click on an image in **Captions** section

## Context
I was searching for a way to nicely present my images and didn't want to include jQuery in my project. Went through docs and found this bug.

## Your Environment
* Version used: 1.0.0-alpha.3 (doesn't work on this version in my project, not sure what version is used in the docs)
* Browser Name and version: Mozilla Firefox 60
* Operating System and version (desktop or mobile): Windows 10 64bit
* Link to your project (if appropriate):

**Comment by Dogfalo** [comment]
Fixed in 83c33e9da85869294f1822c210d1840f0a579aec
