### ISSUE TITLE
scrollSpy not working

### ISSUE THREAD

**Issue by edwardsharp** [Dogfalo/materialize#5596]
banging my head trying to figure out why scrollSpy (v0.100.2) is not working for me. are there particular (major?) versions of jQuery this works (or does not work) with??

with jQuery 3.2.1 **NOT-WORKING** https://jsfiddle.net/edwardsharp/a7yrdude/1/

with jQuery 2.1.3 **WORKING** https://jsfiddle.net/edwardsharp/a7yrdude/2/ 

with jQuery 2.2.4 **NOT-WORKING** https://jsfiddle.net/edwardsharp/a7yrdude/3/

**Comment by acburst** [comment]
The version you are using in all of these fiddles is 0.97.3

**Comment by edwardsharp** [comment]
oh yes, thanks for noticing! switched to v0.100.2 and jQuery 3.2.1 fiddle is working. 

...whipped up these examples quick to try to reproduce this not working in my app. ended up using https://github.com/thesmart/jquery-scrollspy
