### ISSUE TITLE
Sidenav is laggy in mobile v1

### ISSUE THREAD

**Issue by mrdimaan** [Dogfalo/materialize#5599]
Hi there is a problem with sidenav in smartphones the animation is not smooth and makes me to avoid using materialize for most of my projects please tell me is there a way to fix this?
see this [website ](https://mrdimaan.com) on smartphone it shows the problem perfectly.
the other thing about this is that animation gets more smooth when u go down in website
i mean when i am at the middle or bottom of the page (footer) the sidenav animation is perfect!!! but not on header

**Comment by Dogfalo** [comment]
Not seeing any noticeable lag on my end. Sidenav already uses transform for animation so there isn't any way to improve performance in a significant manner.
