### ISSUE TITLE
Material box on card image does not open window in 1.0 Alpha 3

### ISSUE THREAD

**Issue by andymcr** [Dogfalo/materialize#5601]
## Expected Behavior

Applying the materialboxed class to a card image should show a spy glass when hovering over the image and then the image is clicked an overlay showing a larger version of the image.

## Current Behavior

When hovering over the image a spy glass is displayed. However, when the image is clicked, no overlay is displayed.

## Steps to Reproduce (for bugs)
A demonstration of the effect is available here [http://sps4d.andycarpenter.me.uk/materialbox-1.0a3.html](http://sps4d.andycarpenter.me.uk/materialbox-1.0a3.html)

An second version of the file that differs only by importing Materialize 0.100.2 files is available here [http://sps4d.andycarpenter.me.uk/materialbox-0.100.html](http://sps4d.andycarpenter.me.uk/materialbox-0.100.html). This functions as expected.

## Your Environment
The code is deployed on an Apache server and is executing using php 7.1
Tested using clients Chrome on Android and Windows and IE on Windows

**Comment by wvansl** [comment]
I have the same problem and I dont seem to find a solution. Any luck?

**Comment by desperateCoder** [comment]
For me the basic functionality works, but the styling for the overlay seem a little odd... 
See here (page of a customer of mine):

> http://czihal-gk.de/wordpress/fertigungsverfahren/

The overlay actually opens up, but the image is cropped somehow... 

Sorry for asking, but are you sure, you have initialized the component properly (JavaScript)?

**Comment by acburst** [comment]
Materialbox is no longer automatically initialized. You have to initialize the plugin like any other plugin.

**Comment by desperateCoder** [comment]
@acburst Sorry for bothering you, but what about the styling issue i mentioned? Should i open a new issue?

**Comment by DanielRuf** [comment]
> Should i open a new issue?

Yes please do this.
