### ISSUE TITLE
FAB Toolbar isn't working anymore.

### ISSUE THREAD

**Issue by AmitJoki** [Dogfalo/materialize#5603]
## Expected Behavior

The FAB Toolbar isn't working as it used to do in 0.98

## Current Behavior

![sketch](https://user-images.githubusercontent.com/5158554/35440321-e4284124-02c4-11e8-9fd2-f6ac5a8886b7.png)

## Steps to Reproduce (for bugs)

1. Add `.toolbar` class to FAB
2. Initialize with `toolbarEnabled: true`
3. Click the FAB

## Your Environment

* Version used: 1.0.0.alpha-3
* Browser Name and version: Opera, Chrome, Edge
* Operating System and version (desktop or mobile): Desktop, Windows 10 Enterprise

**Comment by acburst** [comment]
Fixed in baf872f7
