### ISSUE TITLE
Collapsibles only work inside a <li> element

### ISSUE THREAD

**Issue by teddyward** [Dogfalo/materialize#5606]
I would like to create a materialize table with collapsible rows. Because the Materialize [collapsible code](https://github.com/Dogfalo/materialize/blob/16a742700bb5dc87a0edbd838324604f8246b417/js/collapsible.js) is pretty well hard-coded to only look for collapsibles within `<li>`s (why?), each row needs to be within its own `<li>`. But that breaks the strict formatting that HTML tables require.

So far, the best-looking solution that I've come across looks something like this.

```
    {{#each rows as row}}
        <ul ref:row id="details{{row.id}}">
            <li>
                <div class="collapsible-header">
                    <table class="highlight">
                        <tr>
                            {{#each columns as column}}
                                <td>content</td>
                            {{/each}}
                        </tr>
                    </table>
                </div>
                <div class="collapsible-body">
                  Row details
                </div>
            </li>
        </ul>
    {{/each}}
```

Where essentially, I'm creating a new table and collapsible for every table row. This seems like an absurd waste, caused only because a `<tr>` is not allowed to be a collapsible-header.

Would it be possible to either get some insight into the rationale behind this, or to accept more kinds of collapsibles? Or, does anyone know of a better way to accomplish what I'm talking about?

**Comment by Dogfalo** [comment]
Collapsibles are a component that is created on an `ul` element which only accepts `li` children. You can use this if you want to toggle table rows: http://api.jquery.com/slidetoggle/

**Comment by ray007** [comment]
It only works with ul/li now, but there's no reason to keep forcing that instead of working with classes.

**Comment by sudghosh** [comment]
A collapsible table cell is a great Idea
