### ISSUE TITLE
Tall expanded <select> elements get hidden under bottom-sheet modal window

### ISSUE THREAD

**Issue by MrJohnLocke** [Dogfalo/materialize#5610]
If the height of an expanded <select> list is larger than the height of a bottom-sheet modal window, the list becomes partially hidden under the modal frame.  See my codepen for an example:

https://codepen.io/MrJohnLocke/pen/RxXeWG

feature link: http://materializecss.com/modals.html

## Expected Behavior
When you expand a <select> list, it should be able to go on top of the modal window if it's too tall for the frame.

## Current Behavior
An expanded <select> list can sometimes be obstructed by the modal frame if the list's height is too great.

## Possible Solution
I would assume this is an overflow issue?  That's my best guess.

## Steps to Reproduce
1. Add a bottom-sheet modal to a page
2. Add a <select> element within the modal, and give it several options (ten for good measure)
3. Open the modal, then expand the list -- some of your options should now be hidden under the top of the modal frame

## Context
I liked the idea of using the bottom-sheet modal for a specific form on my application.  It looks nice and clean, however my form contains a <select> element, which is why I'm creating this issue.

## Your Environment
* Version used: 0.100.2
* Browser Name and version: Firefox 59, Chrome 60, Edge
* Operating System and version (desktop or mobile): Windows 10 desktop
* Link to your project (if appropriate): local

**Comment by Dogfalo** [comment]
This should be fixed by 0c703faa0fd60c96d5232ba7e33d36309b943698, can you test your case against the v1-dev branch?

**Comment by MrJohnLocke** [comment]
Unable to test until Monday.  Out of office for the weekend.  Will report back as soon as I can

**Comment by PistonPL** [comment]
Bug still exists in 1.000  alpha 3

**Comment by Dogfalo** [comment]
The commit that fixes it occurs after alpha 3
