### ISSUE TITLE
Materialize Next: e is null

### ISSUE THREAD

**Issue by sr229** [Dogfalo/materialize#5615]
## Expected Behavior
Normal Initialization

## Current Behavior
Console returns an error 

![image](https://user-images.githubusercontent.com/14976516/35513900-767791f2-053f-11e8-91ca-cf01bca760bd.png)

## Steps to Reproduce (for bugs)
1: Go to [the affected site](http://demo.sayori.headbow.stream/)
2: Open Dev tools > Console

## Context
We were using Materialize Next to circumvent the stable version's JQuery requirement.
It was working fine until this happened.

## Your Environment
* Version used: 1.0.0-alpha.3
* Browser Name and version: Firefox 59 (Developer Edition)
* Operating System and version (desktop or mobile): Windows 10
* Link to your project (if appropriate): [Link](https://github.com/MonikaDesu/Sayori.DemoFrontEnd)

**Comment by Dogfalo** [comment]
Please create a Codepen with a reduced use case.

**Comment by Dogfalo** [comment]
Although it just looks like to me that the DOM isn't loaded yet when running your code.

**Comment by sr229** [comment]
@Dogfalo yep, looks like defining it inside the ``head`` tag does this. Marking fixed as putting it inside the body worked
