### ISSUE TITLE
Datepicker selects (year & month) bugs 

### ISSUE THREAD

**Issue by buutqn** [Dogfalo/materialize#5617]
I'm using the release: 1.0.0-alpha.3 and found this bug in datepicker
Following configuration is used in the example above.
```
var instance = M.Datepicker.init(programacaoDia, {
    container: 'body',
    showDaysInNextAndPreviousMonths: true,
    yearRange: 10,
    firstDay: 1,
    closeOnSelect: true,
    i18n: {
        today: 'Hoje',
        clear: 'Limpar',
        done: 'Ok',
        nextMonth: 'Próximo mês',
        previousMonth: 'Mês anterior',
        weekdaysAbbrev: ['D', 'S', 'T', 'Q', 'Q', 'S', 'S'],
        weekdaysShort: ['Dom', 'Seg', 'Ter', 'Qua', 'Qui', 'Sex', 'Sáb'],
        weekdays: ['Domingo', 'Segunda-Feira', 'Terça-Feira', 'Quarta-Feira', 'Quinta-Feira', 'Sexta-Feira', 'Sábado'],
        monthsShort: ['Jan', 'Fev', 'Mar', 'Abr', 'Mai', 'Jun', 'Jul', 'Ago', 'Set', 'Out', 'Nov', 'Dez'],
        months: ['Janeiro', 'Fevereiro', 'Março', 'Abril', 'Maio', 'Junho', 'Julho', 'Agosto', 'Setembro', 'Outubro', 'Novembro', 'Dezembro']
    },
    format: 'dd/mm/yyyy'
});
```

![datepicker_1](https://user-images.githubusercontent.com/15644387/35539014-0b280b96-0537-11e8-9d06-8828a0441cce.png)
![datepicker_2](https://user-images.githubusercontent.com/15644387/35539030-1d44cd50-0537-11e8-9319-89b4eaacbb19.png)
![datepicker_3](https://user-images.githubusercontent.com/15644387/35539031-1d678aac-0537-11e8-8199-9718d277ec01.png)
![datepicker_4](https://user-images.githubusercontent.com/15644387/35539026-1cd9d860-0537-11e8-95e7-a202eb5c1289.png)
![datepicker_5](https://user-images.githubusercontent.com/15644387/35539027-1cfac70a-0537-11e8-9759-51a0bf5901d1.png)
![datepicker_6](https://user-images.githubusercontent.com/15644387/35539028-1d206474-0537-11e8-88a3-879b2b2cbab3.png)

I will try to solve this and if I do, I will update here...

**Comment by Dogfalo** [comment]
Fixed in 0c703faa0fd60c96d5232ba7e33d36309b943698
