### ISSUE TITLE
Sidenav onOpenStart called to late when dragging

### ISSUE THREAD

**Issue by ray007** [Dogfalo/materialize#5619]
## Expected Behavior

When starting to drag out the sidebar, `onOpenStart` should be called so the callback can be used the set the sidebar's content

## Current Behavior

`onOpenStart` is called when the sidebar is at least half out (from the width of old content), so old or non-existent content is show.

## Possible Solution

Call `onOpenStart` as soon as the dragging begins, or offer an option to do so.

## Context

I want to fill the sidebar with appropriate content when needed, not before.

**Comment by ray007** [comment]
Solution for me in PR #5627

**Comment by acburst** [comment]
I don't think this is how onOpenStart should work because you can drag the sidenav a little bit and it will snap back to closed. You could try adding a callback to just drag instead.

**Comment by ray007** [comment]
Yes, if you look at my PR, I did at a callback `onDragStart`.

**Comment by Dogfalo** [comment]
For now we are not adding onDragStart since you can just add a regular html touchstart event listener to achieve the same functionality.

**Comment by ray007** [comment]
`touchstart` is not the same as starting to drag, and it's an element managed by materialize.
