### ISSUE TITLE
SideNav left offset

### ISSUE THREAD

**Issue by asaadmahmood** [Dogfalo/materialize#562]
Hi, I would like to change the offset of the sidenav when it closes. Currently it takes left: -250px when closed and left: 0px when open, but since I'm using wordpress I would like to change any one of that value by default.
![screen shot 2015-01-29 at 11 55 26 pm](https://cloud.githubusercontent.com/assets/7103043/5963981/772a25e8-a812-11e4-858f-6c17c8d4ad34.png)

Let me know from where I can do that.

**Comment by asaadmahmood** [comment]
Or if I can just add a class to the sidebar when it is open and remove it when it is closed, that would be great too.

**Comment by asaadmahmood** [comment]
Found out where to modify the script.

**Comment by Honzys** [comment]
Hi, I have the exact same problem 2 years later.
Do you happen to remember what fixed your issue back then?
Thanks a lot
