### ISSUE TITLE
Doc / Code inconsistency for radio buttons

### ISSUE THREAD

**Issue by devin-liu** [Dogfalo/materialize#5620]
For checked radio buttons in the docs I can see this is the code in the linked doc page

[Forms](http://materializecss.com/forms.html)

`[type="radio"]:not(:checked)+label, [type="radio"]:checked+label {
    position: relative;
    padding-left: 35px;
    cursor: pointer;
    display: inline-block;
    height: 25px;
    line-height: 25px;
    font-size: 1rem;
    -webkit-transition: .28s ease;
    transition: .28s ease;
    -webkit-user-select: none;
    -moz-user-select: none;
    -ms-user-select: none;
    user-select: none;
}`

But in alpha 3 I can see it uses spans

`[type="radio"]:not(:checked) + span,
[type="radio"]:checked + span {
  position: relative;
  padding-left: 35px;
  cursor: pointer;
  display: inline-block;
  height: 25px;
  line-height: 25px;
  font-size: 1rem;
  transition: .28s ease;
  user-select: none;
}`

When will the radio buttons be updated?

**Comment by Dogfalo** [comment]
1.0.0 is in alpha, you can find the documentation for that version here: next.materializecss.com
