### ISSUE TITLE
Feature Request: FAB to sheet of material transformation

### ISSUE THREAD

**Issue by aleha1999** [Dogfalo/materialize#5624]
## Expected Behavior
The floating action button should have the ability to turn into a sheet of paper on click. Usually it would turn into a form of sorts. This is a great design feature that looks and feels good in an application, especially desktop ones.

[Material design specification](https://material.io/guidelines/components/buttons-floating-action-button.html#buttons-floating-action-button-transitions)
[More specifically this animation](https://storage.googleapis.com/material-design/publish/material_v_12/assets/0B8v7jImPsDi-Mk9EVk5DRVN1cmc/components-buttons-fab-transition-card-01.mp4)

## Current Behavior
Not currently implemented (that i can tell at least)

## Context
It's a design feature that expresses a result of an action, for example an add action, much more clearly than just a modal. Personally i use this on almost all of my applications (a custom implementation. I'm new to Materialize and I'm looking forwards to using it loads in the future), and it's a beautiful, simple, and useful design feature. I don't think it's that hard to implement considering it can be pretty primitively done in 80 lines of CSS and some pretty basic JS.

## Example of implementation
I cooked up a quick little [Codepen](https://codepen.io/kilopoint/pen/eVNyKz) example to illustrate what i mean, and how it can be implemented. It doesen't use Materialize's FAB, and it instead uses something i quickly made myself because it'd be more predictable and easy to implement behavior wise.

**Comment by jeroenqui** [comment]
This is a great idea.
In my opinion, the modal should have an option to make it transform from the clicked object, but I don't know if that's possible.

**Comment by aleha1999** [comment]
@jeroenqui I suppose that would be one possible solution, and I guess that would be the best for users of the library, but code wise it would make more sense to be able to add a div underneath the fixed-action-button div. This would make implementing it a lot easier. Though then having to sacrifice a lot of the functionality that comes with modals (even if that might even be a positive thing since modals and the transform target behave quite differently?)

**Comment by jeroenqui** [comment]
Well, they implemented it in the themes. Although not exactly like we wish. Guess they don't want to include it in the project.
