### ISSUE TITLE
`new Component()` uses cash, but `Component.init()` does not accept cash results

### ISSUE THREAD

**Issue by firelizzard18** [Dogfalo/materialize#5625]
This issue is the cause of #5515

## Expected Behavior
This works: `$(<selector>).chips({ ... })`, when the options include autocompletion.

## Current Behavior
It fails, with a pretty useless error message.

## Possible Solution
The `Component` constructor sets `this.$el = cash(el)`. `Chips._setupInput()` then sets `this.$input = this.$el.find('input')`. `Chips._setupAutocomplete()` calls `M.Autocomplete.init()`: `this.autocomplete = M.Autocomplete.init(this.$input, this.options.autocompleteOptions)[0]`. This causes an error that the result does not have property 0, because the autocomplete init call returns null. This is because `this.$input` is a cash object (`Init`), but autocomplete init does not handle cash objects.

**This can be fixed by** replacing `else if (!!els.jquery || els instanceof NodeList)` with `else if (!!els.jquery || !!els.cash || els instanceof NodeList)` in [line 36 of js/component.js](https://github.com/Dogfalo/materialize/blob/16a742700bb5dc87a0edbd838324604f8246b417/js/component.js#L36)

**Comment by acburst** [comment]
Fixed in b5e426f9
