### ISSUE TITLE
can we control which parent element a toast is appended to?

### ISSUE THREAD

**Issue by 75lb** [Dogfalo/materialize#5629]
I'm using v1.0.0-alpha.3.

When i add a toast with `M.toast({html: 'something' })` it is appended to `<body>`.  If i make an element within the body fullscreen using the [Fullscreen API](https://developer.mozilla.org/en-US/docs/Web/API/Fullscreen_API), toasts no longer display because they are not within the fullscreened area. If toasts were appended within my fullscreened area they would show correctly.

Is there are way to specify which parent element the toast is appended to? If not, i'll engineer my own solution for now.

**Comment by Dogfalo** [comment]
You can't change the parent element, but you can change the css of the toast container to fit your screen bounds better

**Comment by 75lb** [comment]
when using Fullscreen API you can't use CSS to fix this issue, but thanks
anyway

On 10 Feb 2018 01:57, "Alvin Wang" <notifications@github.com> wrote:

Closed #5629 <https://github.com/Dogfalo/materialize/issues/5629>.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/Dogfalo/materialize/issues/5629#event-1467823962>, or mute
the thread

**Comment by DanielRuf** [comment]
Currently not possible, see https://github.com/Dogfalo/materialize/blob/v1-dev/js/toasts.js#L76

**Comment by 75lb** [comment]
no, it's not possible - that's why i raised an issue. The person that closed the ticket didn't understand the issue, thinking it could be solved with CSS. Currently, I can't use toasts within my app's full-screened area so I'm rolling my own toast solution.

**Comment by DanielRuf** [comment]
That's what I wrote.
> Currently not possible, see https://github.com/Dogfalo/materialize/blob/v1-dev/js/toasts.js#L76

**Comment by DanielRuf** [comment]
But you can move them maybe with some JS or clone the repo and extend the toasts.js file and compile your custom Materialize version.

**Comment by DanielRuf** [comment]
> but you can change the css of the toast container to fit your screen bounds better

And yes, this would also work in most cases.
