### ISSUE TITLE
I have a relevant Sass function you might want to include.

### ISSUE THREAD

**Issue by SmileyJames** [Dogfalo/materialize#563]
I have created a Sass function that generates data URIs for material design icons, take a look:
https://github.com/SmileyJames/sassy-google-icons

If you want to include the code in your project please feel free.

I was told you guys might be interested in it on reddit:
http://www.reddit.com/r/webdev/comments/2u2gve/i_created_a_material_design_sass_file_for_anyone/co4kl4n

**Comment by Dogfalo** [comment]
People are more accustomed to the icons as text because this is how Font Awesome does it. This would also break alot of styling as we have it now for little gain.

**Comment by SmileyJames** [comment]
Could you include the option of both?
