### ISSUE TITLE
Scrolling enable when closing a modal inside a modal

### ISSUE THREAD

**Issue by scote** [Dogfalo/materialize#5633]
## Expected Behavior

It should keep the scroll overflow hidden on the body when we close a modal inside a modal.

## Current Behavior
The scrolling is enabled on the first modal.

## Steps to Reproduce (for bugs)
http://next.materializecss.com/test/html/multiple_modals
1. Click on Fixed modal header. 
2. Click on Modal 
3 Close Modal
4. You can scroll ouside the Fixed modal header

## Your Environment

* Version used: Any
* Browser Name and version: Chrome 63
* Operating System and version (desktop or mobile): Windows 10
* Link to your project (if appropriate):

**Comment by acburst** [comment]
Fixed in ef90dbd3.

Thanks for pointing this out!
