### ISSUE TITLE
.show/.hide helper classes for print media

### ISSUE THREAD

**Issue by benwa** [Dogfalo/materialize#5634]
For users who wish to print a page (be it a long tabled report or otherwise), certain elements should be hidden.
`.hide-on-print` and `.show-on-print` could be used to display elements only when appropriate.

**Comment by DanielRuf** [comment]
So far we have no specific print styles or helpers for the print version. This might be out of scope of the goals of aterialize as this would also request more needed helpes and settings (eg disable background / set backgrounds to transparent and other settings).

**Comment by DanielRuf** [comment]
Also see https://github.com/BafS/Gutenberg

**Comment by Dogfalo** [comment]
This is out of scope for Materialize
