### ISSUE TITLE
IE picker troubles

### ISSUE THREAD

**Issue by ray007** [Dogfalo/materialize#5636]
When reducing the width of the browser to 600px or less, which makes the pickers go into portait mode, they collapse in internet explorer (IE11 tested here).

## Expected Behavior

Pickers should be visible in portrait mode like the other browsers.

## Current Behavior

The picker modal collapses to a small block, doesn't take height from its content.

## Steps to Reproduce (for bugs)
see https://codepen.io/ray007/pen/VQKwZy

## Your Environment

* Version used: alpha 3
* Browser Name and version: IE11
* Operating System and version (desktop or mobile): Windows 7

**Comment by Dogfalo** [comment]
Fixed in 4dcde597f6a71a132b451821314f260c512f888b
