### ISSUE TITLE
Timepicker error when selecting minutes

### ISSUE THREAD

**Issue by epanfile** [Dogfalo/materialize#5637]
- Materialize Release: 1.0.0-alpha.3
- Chrome Version 64.0.3282.140 (Official Build) (64-bit)
- Windows 10 desktop

When selecting minutes in Timepicker component initialized in the following way:

`M.Timepicker.init(inputElement, {
    "autoClose": true,
    "twelveHour": false
});`

Timepicker throws the following uncaught exception: 

Uncaught TypeError: this.minutesView.addClass is not a function at Timepicker._handleDocumentClickEnd (materialize.js?36ce:9357)

It appears that in _handleDocumentClickEnd method, this.minutesView is an instanceof Element and, therefore, does not have an addClass method.  As a result, the following line fails:

`this.minutesView.addClass('timepicker-dial-out')`

**Comment by epanfile** [comment]
Hi. Is there any need of further details for this issue to get looked at?

**Comment by Dogfalo** [comment]
no, thanks for reporting the issue

**Comment by Dogfalo** [comment]
Fixed in cafc9724220ae48fdaab1d85e1f27a81a51a9859
