### ISSUE TITLE
"Sticky hover" for collection-item on mobile with <a> tag

### ISSUE THREAD

**Issue by ExoMemphiz** [Dogfalo/materialize#5641]
When hovering over collection-item like in the provided codepen, it highlights it, and moving the mouse away also removes the "greyed" hover effect.

On mobile, if you click on a collection-item, it stays highlighted until you click something else.
I would like to find a way to "unhover" this. (As an example, the user presses on the area, it lights up grey, 300ms later it fades back to the original colour).

I've tried loads of different jQuery methods, and it seems the main problem stems from that it has a ":hover" (css) attached to it, and mobiles don't have mice.

https://codepen.io/ExoMemphiz/pen/YeWZVX

Best Regards

**Comment by acburst** [comment]
This is a common problem with hovers on mobile and I don't see how this is a problem with collection-item. You can remove the :hover style on mobile devices but I don't think there is a clean programmatic way of removing the "hover" state

**Comment by ExoMemphiz** [comment]
@acburst Is it possible you could fork my codepen to show how you could remove the hover style for mobile devices?

Thanks in advance!
