### ISSUE TITLE
IE11 icons wont show up

### ISSUE THREAD

**Issue by eddieedease** [Dogfalo/materialize#5643]
We build an app with this great framework, however, in IE11 the icons won't render on all our workstations at work. I've read somewhere that is has to do with IE security settings. (On personal laptops with IE11 evertyhing runs wel). Question: What info can I give our IT department? They already said that font downloading is available. Screenshot below, any ideas?

![knipsel](https://user-images.githubusercontent.com/5286310/35910636-89bedcfc-0bf7-11e8-8ce9-8228116d4b8e.png)

**Comment by DanielRuf** [comment]
Please provide a codepen. Also this is possibly related to the font files from material-icons by Google.

**Comment by eddieedease** [comment]
Above screenshot is from the Materializecss homepage (icons). I cannot provide codepen because everything works fine on personal laptops. It's the buisness network infrastructure where it fails. So I'm guessing it must be a security settings on IE11 of the IT department (big hospital).

**Comment by DanielRuf** [comment]
> So I'm guessing it must be a security settings on IE11 of the IT department (big hospital).

You can open the developer console in IE11 and check what happens in the network tab or console.

**Comment by eddieedease** [comment]
Thank you, but it won't show anything. I'm closing this here as I think you're right and it has more to do with material-icons by Google. Their guide also just show the names instead of the names on our workstations.
