### ISSUE TITLE
sortFunction Autocomplete documentation

### ISSUE THREAD

**Issue by arkkanoid** [Dogfalo/materialize#5644]
Hi, 
Could you provide an example of how to use the sortFunction on autocomplete?
Thanks

**Comment by acburst** [comment]
Added in d033b10f.

You can read more about what a compareFunction is and how to write your own here: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/sort

**Comment by ChildishGiant** [comment]
Is the default sorting supposed to be alphabetical as in the past? I've been getting this
![image](https://user-images.githubusercontent.com/13716824/38054298-71eb85b4-32ce-11e8-87b3-436740674a03.png)
If I remove that entry it chooses an adjacent entry
![image](https://user-images.githubusercontent.com/13716824/38054437-ded604e2-32ce-11e8-84c4-2af0a412292a.png)

**Comment by Dogfalo** [comment]
It is not currently alphabetical by default

**Comment by ChildishGiant** [comment]
Why is a random one at the start? Is there a way to just cancel the sorting method and use the JSON for the order?

**Comment by Dogfalo** [comment]
It does use the normal traversal order of javascript objects

**Comment by ChildishGiant** [comment]
![image](https://user-images.githubusercontent.com/13716824/38055767-8d3e32f4-32d2-11e8-8b7e-d8cc2572870c.png)
Here's the start of the JSON I'm using but it puts the middle key first. Currently I have 124 entries and lloyds is the 62nd. If I remove that entry it still happens, just with the new middle.

**Comment by Dogfalo** [comment]
Can you provide your test case in a codepen so I can take a look?

**Comment by ChildishGiant** [comment]
https://codepen.io/ChildishGiant/pen/XEEqWB/ Sorry it took me a while, I was rather busy.

**Comment by Dogfalo** [comment]
In your codepen example, the order seems to be working fine

**Comment by ChildishGiant** [comment]
![image](https://user-images.githubusercontent.com/13716824/38148936-6b07849a-3450-11e8-9621-c3e148304ef3.png)

I'm running Chrome Version 65.0.3325.181 (Official Build) (64-bit)

**Comment by acburst** [comment]
The order of JSON objects is not guaranteed

**Comment by ChildishGiant** [comment]
Well I've fixed it with this sort function.

```
if (a < b) {
  return -1;
}
if (a > b) {
  return 1;
}
// a must be equal to b
return 0;
}
```

**Comment by ChildishGiant** [comment]
I've been trying to make it so it cares about if it starts with the inputString and I can't get it working.
