### ISSUE TITLE
Fixed Sidenav on iPad 10.3.3 scrolls with content and disappears

### ISSUE THREAD

**Issue by Albiwalbi** [Dogfalo/materialize#5645]
## Expected Behavior

The fixed sidenav should remain fixed and scroll sperately from the content

## Current Behavior

The sidenav dissapears when your swipe is a bit orientated to the left.

[YouTube video](https://www.youtube.com/watch?v=3Wflt4H7C8Y)

## Your Environment

* Version used: Alpha 3 of version 1.0.0
* Browser Name and version: safari, 10.3.3
* Operating System and version (desktop or mobile): iPad

Ps: Please let me know what code you need for investigating the issue :)

**Comment by acburst** [comment]
Fixed in 298a87f4
