### ISSUE TITLE
Why Wrapping Extra div in Form inputs?

### ISSUE THREAD

**Issue by hlaporthein** [Dogfalo/materialize#5647]
![screen shot 2018-02-08 at 5 52 37 pm](https://user-images.githubusercontent.com/1018870/35970516-fcc47624-0cf8-11e8-9db3-a84d2fb92927.png)
Why do materializecss documentation show **.row , .col & .s12** nested again and again? I can't figure out why we need to add those class again and again even for one input field. I don't feel any difference using like below.

```
<div class="input-field">
  <input id="email" type="email" class="validate">
  <label for="email">Email</label>
  <span class="helper-text" data-error="wrong" data-success="right">Helper text</span>
</div>
```
That would be great to add those classes when we actually need it.

**Comment by DanielRuf** [comment]
The grid adds gutters and the input-field has to be wrapped.

You can compare it [here](https://codepen.io/DanielRuf/pen/wygKVb).

**Comment by Dogfalo** [comment]
You can layout your forms however you want. The example showcases the grid system which is documented here: http://materializecss.com/grid.html
