### ISSUE TITLE
passing an incomplete i18n object breaks datepicker

### ISSUE THREAD

**Issue by franktopel** [Dogfalo/materialize#5663]
Using 1.0.0.alpha3, I ran into several issues regarding i18n of the datepicker.

## Expected Behavior
When passing an options object that has an `i18n` property like

```
var options = {
      format: 'dd.mm.yyyy',
      firstDay: 1,
      i18n: {
        clear: 'delete'
      }
    };
```

you get a datepicker component with the clear button's text set to 'delete'.

## Current Behavior
Datepicker does not open at all and dev tools console shows error message:
`Uncaught TypeError: Cannot read property '4' of undefined`

## Possible Solution
`console.log(instance.options.i18n)` in the [codepen](https://codepen.io/connexo/pen/zRPNNE) shows the cause of the problem:

`{
  clear: "delete"
}`

All the _default_ i18n object properties are gone.

Make sure the default `i18n` property is not overwritten by passing an "incomplete" i18n object. Instead use `Object.assign(defaultOptionsI18n, passedOptionsI18n)` internally and keep defaults for non-passed properties of i18n object.

## Steps to Reproduce (for bugs)
https://codepen.io/connexo/pen/zRPNNE

**Comment by franktopel** [comment]
Fixed in https://github.com/Dogfalo/materialize/pull/5664

**Comment by Dogfalo** [comment]
Merged
