### ISSUE TITLE
Tooltip content element not removed from DOM when tooltip instance destroyed

### ISSUE THREAD

**Issue by epanfile** [Dogfalo/materialize#5666]
- Materialize Release: 1.0.0-alpha.3
- Chrome Version 64.0.3282.140 (Official Build) (64-bit)
- Windows 10 desktop

When a Tooltip is initialized it creates a `<div class="material-tooltip">...</div>` element where it keeps content for the tooltip.  However, when the anchor element (and its Tooltip instance) is removed/destroyed from DOM, the material-tooltip element is left in the DOM.  Normally, UI components should clean up DOM of unused elements after they are destroyed.

**Comment by stewx** [comment]
Experiencing the same thing

**Comment by Dogfalo** [comment]
Did you use the destroy method?

**Comment by stewx** [comment]
My workaround: ` $('.tooltipped').trigger('mouseleave.tooltip');`

**Comment by Dogfalo** [comment]
Before you destroy the origin element, you should deinitialize using the destroy method described here: http://next.materializecss.com/tooltips.html#methods
