### ISSUE TITLE
Datepicker 'mmmm' format options returns month in short form

### ISSUE THREAD

**Issue by epanfile** [Dogfalo/materialize#5667]
- Materialize Release: 1.0.0-alpha.3
- Chrome Version 64.0.3282.140 (Official Build) (64-bit)
- Windows 10 desktop

When initializing Datepicker with "format" option "dd mmmm yyyy", instance.toString() method returns "15 Feb 2018", for example.  

The problem appears to be in _setupVariables method where you have:

`mmmm: () => {
     return this.options.i18n.monthsShort[this.date.getMonth()];
}`

instead of:

`mmmm: () => {
     return this.options.i18n.months[this.date.getMonth()];
}`

**Comment by Dogfalo** [comment]
It was added after 1.0.0-alpha.3 release.  It will be available in the next alpha version
