### ISSUE TITLE
dropdown touch troubles

### ISSUE THREAD

**Issue by ray007** [Dogfalo/materialize#5669]
the dropdown closes already with the `touchstart` event, a `click`-eventhandler for the items triggers on the wrong element since the close-animation is already running.

## Expected Behavior

dropdown closes only after the click is completed.

## Possible Solution

change the handler from `touchstart` to `touchend` or rely on the `click` event also for touch

**Comment by Dogfalo** [comment]
Fixed in ce5c727d1beeccf1d320f878ac3181bd63135778
