### ISSUE TITLE
Uncaught range error: maximum call stack size exceeded (Parallax)

### ISSUE THREAD

**Issue by brandoncanaday** [Dogfalo/materialize#5670]
## Current Behavior

Similar to an already-closed issue, however I still receive an the error specified in the issue title.

## Context

I'm just trying to use some parallax images on a static html page similar to one in a template you provide on your site.

## Environment

* Version used: 1.0.0-alpha.3
* Browser Name and version: Chrome, Version 64.0.3282.167 (Official Build) (64-bit)
* Operating System and version (desktop or mobile): MacOS Sierra, Version 10.12.6
* Link to your project (if appropriate): https://tippextension.com

## Error Screenshot

![screen shot 2018-02-16 at 12 36 42 pm](https://user-images.githubusercontent.com/15020865/36321294-4d036496-1317-11e8-873a-1d31c10fb40b.png)

**Comment by Dogfalo** [comment]
see #5549
