### ISSUE TITLE
Only first tooltip displays corectly

### ISSUE THREAD

**Issue by troncomputers** [Dogfalo/materialize#5673]
I have both tooltips aligned to right but only first works:
[CODEPEN](https://codepen.io/anon/pen/PQEpEz)

**Comment by acburst** [comment]
I can't seem to reproduce this issue locally. Is this happening to you only on codepen?

**Comment by troncomputers** [comment]
This is happening locally too. I'd use codepen to show you where is the problem.

**Comment by troncomputers** [comment]
@developeranirudhprabhu Yes and even if you add more, only first displays correctly.

**Comment by acburst** [comment]
Is this happening on the latest alpha release?

**Comment by troncomputers** [comment]
Yes and no. It's not working when there is no other content on the website. If you put only fixed sidenav with tooltipped items then should work only first like I wrote before.
[CodePen](https://codepen.io/anon/pen/OQZYMP)
There is a comment in HTML section from where you should remove content for test.

**Comment by Dogfalo** [comment]
This seems to happen when the html and body element are smaller than the content, not sure if there is a good fix for this besides either having content in the page or having html and body set to 100% height

**Comment by troncomputers** [comment]
Yes but how about Angular where you can have component with sidenav only

**Comment by acburst** [comment]
Fixed in c00c954f
