### ISSUE TITLE
Parallax Uncaught RangeError: Maximum call stack size exceeded

### ISSUE THREAD

**Issue by Shinseiten** [Dogfalo/materialize#5674]
The version is the latest. 1.0 Alpha 3.

Sometimes I have this error.
It's random, I can't understand when and why it happen, an F5 slot machine.

> materialize.min.js:6 Uncaught RangeError: Maximum call stack size exceeded.
>     at HTMLImageElement.<anonymous> (materialize.min.js:6)
>     at k (materialize.min.js:6)
>     at g.each (materialize.min.js:6)
>     at g.trigger (materialize.min.js:6)
>     at HTMLImageElement.<anonymous> (materialize.min.js:6)
>     at k (materialize.min.js:6)
>     at g.each (materialize.min.js:6)
>     at n.value (materialize.min.js:6)
>     at HTMLImageElement.<anonymous> (materialize.min.js:6)
>     at k (materialize.min.js:6)

Here's the codepen:
https://codepen.io/Shinseiten/pen/bLaRdZ

**Comment by Dogfalo** [comment]
It is fixed for the next release
