### ISSUE TITLE
CDN down 

### ISSUE THREAD

**Issue by kevinsalinas** [Dogfalo/materialize#5679]
CDN down

I´m trying to import materialize css by using cdn but I get 404 

![capture](https://user-images.githubusercontent.com/13041804/36394825-a9877d86-157b-11e8-821c-7bb38b3568fa.PNG)

**Comment by Dogfalo** [comment]
It seems it is back up now. We also do not control the servers for CDN hosting.

**Comment by DanielRuf** [comment]
That's why you should host them locally / on your server.
