### ISSUE TITLE
How to remove all css of specific  div elements ?

### ISSUE THREAD

**Issue by akshgods** [Dogfalo/materialize#5680]
How to remove all css of specific  div elements?
i have div with id="home" , i don't want to apply any css from materialize css on that div. is there any class available so materialize css can't apply on that div and elements of that div?

I used some other css where material overriding theme.
material css can be removed by commenting this material css lines

/* Text inputs */
input:not([type]), input[type=text]:not(.browser-default), input[type=password]:not(.browser-default), input[type=email]:not(.browser-default), input[type=url]:not(.browser-default), input[type=time]:not(.browser-default), input[type=date]:not(.browser-default), input[type=datetime]:not(.browser-default), input[type=datetime-local]:not(.browser-default), input[type=tel]:not(.browser-default), input[type=number]:not(.browser-default), input[type=search]:not(.browser-default), textarea.materialize-textarea {
    /* background-color: transparent; */
    /* border: none; */
    /* border-bottom: 1px solid #9e9e9e; */
    /* border-radius: 0; */
    /* outline: none; */
    /* height: 3rem; */
    /* width: 100%; */
    /* font-size: 1rem; */
    /* margin: 0 0 20px 0; */
    /* padding: 0; */
    /* -webkit-box-shadow: none; */
    /* box-shadow: none; */
    /* -webkit-box-sizing: content-box; */
    /* box-sizing: content-box; */
    /* -webkit-transition: all 0.3s; */
    /* transition: all 0.3s; */
}

specially my problem for input types which is different than material css , i dont want to use this material inputs css on my div style.

**Comment by tamsamani** [comment]
`materialize` can affect changes to a **_div_** if you add specific classes defined by _materialize.css_, so you can add normally your **_div_**, if your div under any of specific classes then you can initialize it by **css** properties by default, the major take `initial` value

**Comment by akshgods** [comment]
this is my code, shall i remove container class?

```
<div id="home" class="home">
<div class='container'>
    <div class='expenses'>
        <input id='totalMonth'  placeholder='Your balance' type='text'>
<input id='expenseName'  placeholder='Expense name' type='text'>
<input id='expensePrice' placeholder='Expense price' type='text'>
        <div class='total'>
            <h1>Money left over</h1>
            <h2></h2>
        <button id='add' type='submit'><i class="fa fa-inr"></i> Add expense</button>                     
        </div>
        <div class='expenseList'>
            <table>
                <th>Expense</th>
                <th>Price</th>
                <th>Delete</th>
            </table>
        </div>
    </div>
    <!-- <div id="variefy">
        <input type="number" id="mobile" placeholder="+91">
        <buttun id="sms">submit</buttun>
    </div>
<div id="gototp">
    <input type="number" id="otp" placeholder="OTP">
</div> -->
</div>

</div>
```

**Comment by Dogfalo** [comment]
For now, you have to set initial to the CSS property that you want to reset. We plan to make improvements for this in the future. Please search existing and closed issues

**Comment by akshgods** [comment]
ok thanks @tamsamani  and @Dogfalo  :+1:
