### ISSUE TITLE
2 autocomplete inputs with different data - only one works

### ISSUE THREAD

**Issue by troncomputers** [Dogfalo/materialize#5681]
Hi... again 😃 
I'm going to have multiple autocomplete inputs on my form. Now I have only 2 and it seems to only one works corectly and shows hints.
  
[CodePen](https://codepen.io/anon/pen/aqYYLN)

**Comment by acburst** [comment]
The input field container is required for the autocomplete to function

**Comment by troncomputers** [comment]
-.-' sorry, I'm an idiot. Works fine.
