### ISSUE TITLE
Feature request: display date picker calendar not in a modal

### ISSUE THREAD

**Issue by testwisely** [Dogfalo/materialize#5682]
Currently the date picker is shown in a modal window. I would like just display calendar as a widget, like JQuery UI datepicker: 
`<div id="datepicker-calendar"></div>`
`$( "#datepicker-calendar" ).datepicker({ ...`

Is it possible? I like the design of Materialize Calendar, so it will be good if it can support this, thanks. 

PS. I posted the question on Gitter, unable to get answer.

**Comment by Dogfalo** [comment]
This feature is not currently supported

**Comment by ray007** [comment]
Until it is supported, create a picker per script and move the elements wherever you want them to be...
