### ISSUE TITLE
[1.0.0@alpha-3]`instance.destroy()` doesn't respect outDuration

### ISSUE THREAD

**Issue by kounelios13** [Dogfalo/materialize#5683]
When asking general "how to" questions:

- Please do not open an issue here!
- Instead, ask for help on [StackOverflow](stackoverflow.com/questions/tagged/materialize) or in our [Gitter](https://gitter.im/Dogfalo/materialize) channel.

- Read the [CONTRIBUTING document](https://github.com/Dogfalo/materialize/blob/master/CONTRIBUTING.md) Any issues that are violating the contributing guidelines, will be closed!
- [Search for duplicate or closed issues](https://github.com/Dogfalo/materialize/issues?utf8=%E2%9C%93&q=is%3Aissue) and make sure to go through our [labels](https://github.com/Dogfalo/materialize/labels).
- Include a [reduced test case](https://css-tricks.com/reduced-test-cases/) in the form of a Codepen when reporting bugs unless it is not applicable, otherwise your issue will be closed.

Hello .I am working on a project in which I need to create modals on the fly.I initialize them using an `inDuration` and an `outDuration`.After done using them I want to close them and destroy them.However It seems that when I call the `instance.destroy()` before `instance.close()` the modal will close but without fading out using the `outDuration`.However If I don't destroy the modal instance and just close it everything works fine
## Expected Behavior
When `instance.destroy()` is called the modal being destroyed should fade out using the `outDuration`

## Current Behavior

The modal doesn't fade out when `destroy()` is called.It just gets removed

## Steps to Reproduce (for bugs)

1. See the bug here: https://codepen.io/kounelios13/pen/YeLKgq
2. Click the `Modal with bug` and wait 5-6 seconds

## Your Environment

* Version used:
* Browser Name and version:
* Operating System and version (desktop or mobile):
* Link to your project (if appropriate):

**Comment by Dogfalo** [comment]
Destroy delinitializes the modal, it's job is not to transition out.

**Comment by kounelios13** [comment]
@Dogfalo I don't disagree however I thought that because  I am calling `close()` that things would go smooth
