### ISSUE TITLE
Possible issues with Card Actions in 1.0.0

### ISSUE THREAD

**Issue by Jac21** [Dogfalo/materialize#5691]
Recently upgraded my personal site to version **1.0.0-alpha.4,** and noticed an issue with the card component "card actions" that apply my site, and seem to also be reproducible within the http://next.materializecss.com/cards.html page. 

For comparison's sake, the left is the "next" site's examples of small and medium cards, and the right is the classical Materialize site's same examples, wherein you can see that the card actions section overlaps with the card content itself on the 1.0.0 documentation site: 

![image](https://user-images.githubusercontent.com/1449455/36564973-b02c4714-17e4-11e8-8889-c8cc2d9c913e.png)

This happens regardless if the wrapping card is a "sticky" card or not, as well.

**Comment by Jac21** [comment]
Upon further investigation, this may be related to the following commit - 

https://github.com/Dogfalo/materialize/commit/7b13e4998290225367c2f08a8b357d677307a4d9#diff-b0c0ad49416f94d519f89abfe23a4708

wherein the inherited background-color was removed from the class. I'd raise a PR, but I'm not sure what the approach for inherited members is as of this recent release.

**Comment by Dogfalo** [comment]
Fixed via #5695
