### ISSUE TITLE
Sidenav close issues

### ISSUE THREAD

**Issue by dxc111** [Dogfalo/materialize#5692]
I used the fixed sidenav.
When the screen width less than 992px, the sidenav is hidden, then I use the sidenav-trigger and the sidenav is opened. Then do not close the sidenav, set the screen width bigger, close the sidenav, as a result, the shadow mask is still on, sidenav should be left, but not.

**Comment by Dogfalo** [comment]
Please read and use the issue template and add the version number

**Comment by Dogfalo** [comment]
Your issue should be fixed by 298a87f401dbbde5e48e2108e58a4feda2420ef4
