### ISSUE TITLE
Dropdown.destroy() doesn't remove related dropdown-content nodes

### ISSUE THREAD

**Issue by i-a-n** [Dogfalo/materialize#5693]
- Test case: https://codepen.io/ianm/pen/vdazvR/

## Expected Behavior
When calling `instance.destroy()` on a `Dropdown` instance, the associated `.dropdown-content` node should also be removed.

## Current Behavior
When calling `instance.destroy()` on a `Dropdown` instance, the associated `.dropdown-content` node is not removed, leaving it orphaned in the DOM.

## Possible Solution
Calling `instance.dropdownEl.remove()` at some point in the destroy method should work. I think that's here: https://github.com/Dogfalo/materialize/blob/v1-dev/js/dropdown.js#L96 - see my codepen for one solution.

## Steps to Reproduce (for bugs)
See codepen above. Just instantiate a dropdown, then destroy it, and check the DOM: the content node is still there after destroy.

## Context
On single page apps these begin piling up and can affect each other in unpredictable ways as multiple orphaned nodes with the same ID and different content can coexist.

## Your Environment
* Version used: `1.0.0-alpha.4`
* Browser Name and version: Chrome, most recent
* Operating System and version (desktop or mobile): n/a
* Link to your project (if appropriate): n/a

**Comment by acburst** [comment]
In general, we only remove elements from the DOM on destroy when they were generated by the plugin. In the case of dropdown, the user created the dropdown-content element so we don't remove it. This also allows them to reinit the plugin easily.

**Comment by i-a-n** [comment]
Okay, makes sense. Thanks!
