### ISSUE TITLE
s12 and valign are not able to work together.

### ISSUE THREAD

**Issue by maxisme** [Dogfalo/materialize#5694]
## Expected Behavior

That when I view with a smaller width (`.s12`) the video (`.col`) becomes 100% width of the screen and the second `.col` drops below. Naturally on a wider width it works as expected.

## Steps to Reproduce (for bugs)

See [codepen](https://codepen.io/anon/pen/KQBJZM)

## Your Environment
See [codepen](https://codepen.io/anon/pen/KQBJZM)

**Comment by Dogfalo** [comment]
valign works with flexbox which cannot be used on the same items as the grid classes. Please search closed issues
