### ISSUE TITLE
Dismiss dismissable content only if it still has the class 'dismissable'

### ISSUE THREAD

**Issue by nmolinski** [Dogfalo/materialize#5696]
## Expected Behavior

If I toggle off the dismissable class, to make a collection item stop moving, I can accidentally still dismiss it with a swipe gesture. This should not happen as this way I can interact with a temporarily non-moving collection item, which gets messy when overflowY is scrollable, and then re-add the dismissable class when I am done interacting.

## Current Behavior
If you temporarily remove the dismissable class, it is still able to be swiped away. Code does not perform a check whether or not the content is still dismissable.

## Possible Solution
Somewhere in materialize.js wrap the trigger to the event in..
```
if (element.classList.contains("dismissable")){
  // propagate dismissible events
}
```

## Steps to Reproduce (for bugs)
Make sure you are in a touch enabled debug mode, such as a phone/web browser debug touch mode.
1. https://jsfiddle.net/aemqq3tq/8/

## Context
When editing dismissable content on mobile, I wish to disable the translation and accidental dismissal of collection items.

## Your Environment
Any

**Comment by Dogfalo** [comment]
This has been removed in v1-dev
