### ISSUE TITLE
Istances on querySelector and querySelectorAll

### ISSUE THREAD

**Issue by Shinseiten** [Dogfalo/materialize#5698]
In 1.0.0 alpha3 and alpha4 it appears that you can initialize with querySelectorAll all the elements, but Instances work only with querySelector. 

Initialize everything and use getInstance comes handy, but it shouldn't be too much difficult to handle everything correctly with querySelectorAll.

P.S: If "swipeable:true", it sets the tabs at 400px height with JS, why? Can it be removed and\or set it if needed?

**Comment by Dogfalo** [comment]
It does work, but they are in an Array instead
