### ISSUE TITLE
sidenav: instance.close() not working

### ISSUE THREAD

**Issue by netoper** [Dogfalo/materialize#5701]
class .sidenav .sidenav-fixed
instance.close() not working
https://jsbin.com/coduwuqowu/edit?output
then is not possible closing menu on large screen

menu is not visible, ok there (for small screen)
https://jsbin.com/coduwuqowu/edit?html,output

I just want to imitate something like this:
https://material-components-web.appspot.com/drawer/persistent-drawer.html

options like `noHide` and `noOverlay` would be useful.

**Comment by netoper** [comment]
ok, i create my own persistent type of sidenav. it can also help someone else..

when is screen >= as 992px then sidenav is visible. when you click at the menu button, menu hide. this state continue although page is reloaded.. is used localStorage for storing state this info.
https://jsbin.com/qesasisuqa/edit?output

when page < 992px then siden is as standart mobile sidenav. is hiding and after click to menu button it show with bg overlay.
https://jsbin.com/qesasisuqa/edit?html,css,js,output

**Comment by Dogfalo** [comment]
Sidenav doesn't support that feature, if the sidenav is fixed, then it will not close unless it is on a screen size below large
