### ISSUE TITLE
Wrong menu behavior when it is on the right edge

### ISSUE THREAD

**Issue by rfiedler** [Dogfalo/materialize#5708]
[**MATERIALIZE SIDENAV**](http://materializecss.com/side-nav.html)

When sidenav are in right edge and dragable is true, touch event to open menu make animation start at around 50% of screen. 

## Expected Behavior

Sidenav should open from right edge from screen width size.

## Current Behavior

Sidenav open around 50% of screen width. (360x640 Galaxy S5 - S7 - S8)

## Possible Solution
**(ORIGINAL CODE**) - Around line **3932**:
` var rightPos = x - options.menuWidth / 2;`

**(SOLUTION CODE)** 
` var rightPos = x - (window.innerWidth - options.menuWidth) ;`   

## Steps to Reproduce (for bugs)
1. Add javascript:
```
 $('.button-collapse').sideNav({
       menuWidth: 360,
       edge: 'right',
       draggable: true,
       closeOnClick: false,
 });
```
2. Try drag menu to open it.

## Your Environment

* Version used: **Materialize v0.100.2**
* Browser Name and version: **Google Chrome  63.0.3239.132  64 bits**
* Operating System and version (desktop or mobile): **Desktop W7 Professional, Mobile Samsung S8 Android 7.0**

**Comment by acburst** [comment]
We are no longer maintaining the 0.100.2 branch. Try to see if your issue persists on the latest beta version and you can reopen your issue.
