### ISSUE TITLE
datepicker does not cleanup its select-dropdown

### ISSUE THREAD

**Issue by ray007** [Dogfalo/materialize#5710]
After opening a datepicker and closing it again, the select-dropdown `ul` elements for the month and year selectors are still there, even after calling `destroy()` on the datepicker instance.

**Comment by ray007** [comment]
Related to this: an option to use browser-default selects for month and year selector would be nice.

**Comment by Dogfalo** [comment]
Fixed in bc0b261b3e4b28dfe5b4f0f06553e1e8686283c8

**Comment by ray007** [comment]
Is that a no to the browser-default or a maybe later, but not in the bugfix?

**Comment by hnordberg** [comment]
This wasn't enough to fix the issue for me. I had to also call destroySelects() from close(), after adding guards like:
`var sel = M.FormSelect.getInstance(oldYearSelect);
  if( sel)
     sel.destroy();`
