### ISSUE TITLE
select-dropdown on mobile doesn't work

### ISSUE THREAD

**Issue by castroCrea** [Dogfalo/materialize#5712]
In version 1.0.0 aplha 4
The select-dropdown on select form field doesn't work on mobile.

If the list is too long and you try to scroll into it, the select dorp down close.
I couldn't do a gif to show you.
But you can try by going on my website [https://coin2be.com](url) with you mobile, you register and then try to go on buy coin and scroll down to see the bottom of the list you cannot it closed.

**Comment by Dogfalo** [comment]
Fixed in dd7f0d6fd4e6d7fb0cf820afbb1aedb0b57a8afd
