### ISSUE TITLE
waves are not workign

### ISSUE THREAD

**Issue by sagiegurari** [Dogfalo/materialize#5714]
## Expected Behavior
Added the waves css classes but the waves are not working for me.
I created a very simple codepen which just includes your css and js and a link from your example at:
https://codepen.io/sagiegurari/pen/YeMgVp

```html
<a href="#!" class="btn waves-effect waves-teal">Send</a>
```

I do see the link styled as a material button but the waves are not showing up while clicking the button.

* Version used: Latest 0.100.2
* Browser Name and version: Chrome 64
* Operating System and version (desktop or mobile): Desktop
* Link to your project (if appropriate): https://codepen.io/sagiegurari/pen/YeMgVp

**Comment by Dogfalo** [comment]
You didn't add jQuery

**Comment by sagiegurari** [comment]
Now I did and still didn't work.
please give a second before you close it to check.

**Comment by sagiegurari** [comment]
Can you please reopen the issue?

**Comment by Dogfalo** [comment]
Please read the HTML setup section in the documentation http://materializecss.com/getting-started.html#setup

**Comment by ray007** [comment]
I thought v1 doesn't need jquery anymore?

**Comment by sagiegurari** [comment]
I didn't update here, because my issue is closed, but the issue for me is that I included the js with async which broke waves or something.
not sure why it breaks due to that, but the "fix" was to remove the async.

**Comment by Dogfalo** [comment]
@ray007 it's required for v0.100.2
