### ISSUE TITLE
minDate allows user to select Today even if before minDate

### ISSUE THREAD

**Issue by jelofson** [Dogfalo/materialize#5716]
Hello,
I was just testing the minDate config option and it seems to work fine. The only issue I found was that I was able to select Today, even though today is less than the min date.

Same issue exists with maxDate. Today will select a date past the maxDate.

**Comment by jelofson** [comment]
BTW this is alpha 4

**Comment by Dogfalo** [comment]
Are you sure? The today button no longer exists in alpha 4

**Comment by jelofson** [comment]
Pretty sure but I will pull down a fresh copy of the source and double check. 
My js file shows this:

```
/*!
 * Materialize v1.0.0-alpha.4 (http://materializecss.com)
 * Copyright 2014-2017 Materialize
 * MIT License (https://raw.githubusercontent.com/Dogfalo/materialize/master/LICENSE)
 */
```

**Comment by jelofson** [comment]
https://github.com/Dogfalo/materialize/blob/1.0.0-alpha.4/dist/js/materialize.js#L8521

https://github.com/Dogfalo/materialize/blob/1.0.0-alpha.4/js/datepicker.js#L199

And in the dev branch dist

https://github.com/Dogfalo/materialize/blob/v1-dev/dist/js/materialize.js#L8521

But dev branch's datepicker.js is ok.

**Comment by Dogfalo** [comment]
It will be changed in the next release then to be more similar to the one found on android phones
