### ISSUE TITLE
Expand content like theme demo

### ISSUE THREAD

**Issue by kamov** [Dogfalo/materialize#5720]
How to make the content expand like in this theme demo:

https://themes.materializecss.com/pages/demo

Also this seem a Shopify theme, but you said html template.

**Comment by acburst** [comment]
This is a specialized effect made for the theme. That is also the html theme. There is a separate shopify theme demo. But more importantly, we want to keep this repo focused on just Materialize. 

If you have further questions about themes you can email us at materializethemes@gmail.com
