### ISSUE TITLE
Conflict of <strong> style

### ISSUE THREAD

**Issue by weasteam** [Dogfalo/materialize#5721]
I just realized all my bold style is gone after using `1.0.0-alpha.4`. I found conflict style for `<strong>`.

## Expected Behavior
`<strong>dd</strong>` should be bold

## Current Behavior
`<strong>dd</strong>` is not bold

## Possible Solution
In materialize.min.css:6, the first strong style overwrite the second one. 
```
strong {
    font-weight: 500;
}

b, strong {
    font-weight: bolder; 
}
```

## Your Environment
* Version used: 1.0.0-alpha.4

**Comment by acburst** [comment]
This style hasn't changed in a long time. It shouldn't be new in alpha 4. Also `font-weight: 500` is still bold. Normal font-weight is 400. Its just not as bold.

**Comment by weasteam** [comment]
I fixed it by adding the below code to index.css

```
/*temp strong style*/
strong{
    font-weight: bolder !important;
}
```
