### ISSUE TITLE
Autocomplete not working in 1.0.0-Alpha.4

### ISSUE THREAD

**Issue by dealloc** [Dogfalo/materialize#5728]
When asking general "how to" questions:

- Please do not open an issue here!
- Instead, ask for help on [StackOverflow](stackoverflow.com/questions/tagged/materialize) or in our [Gitter](https://gitter.im/Dogfalo/materialize) channel.

- Read the [CONTRIBUTING document](https://github.com/Dogfalo/materialize/blob/master/CONTRIBUTING.md) Any issues that are violating the contributing guidelines, will be closed!
- [Search for duplicate or closed issues](https://github.com/Dogfalo/materialize/issues?utf8=%E2%9C%93&q=is%3Aissue) and make sure to go through our [labels](https://github.com/Dogfalo/materialize/labels).
- Include a [reduced test case](https://css-tricks.com/reduced-test-cases/) in the form of a Codepen when reporting bugs unless it is not applicable, otherwise your issue will be closed.

## Expected Behavior

(Assuming same setup as described in the documentation, autocompletions "Google", "Apple", ...).
When clicking on the input and typing in "g" I expect a dropdown showing me "Google"

## Current Behavior

Currently the "ul" and "li" elements required for autocompletion are created but are not shown in the interface.
This is because it has a display: none from the dropdown, and the display: block was removed from the input_fields in https://github.com/Dogfalo/materialize/commit/df297b1e75070db64f330da1e789dc4c12f06d03

## Possible Solution

Either the CSS or the plugin itself should override the display property because now it remains on display none.

## Steps to Reproduce (for bugs)

1. Install v1.0.0-Alpha.4
2. Follow documentation

## Your Environment

* Version used:
* Browser Name and version:
* Operating System and version (desktop or mobile):
* Link to your project (if appropriate):

**Comment by dealloc** [comment]
The issue suddenly dissapeared and I am unable to reproduce it.
Closing.

**Comment by dealloc** [comment]
Issue seems to occasionally reoccur, I haven't found a pattern yet.
But whenever I downgrade back to Alpha.3 the issue seems to dissapear instantly.

**Comment by acburst** [comment]
can you post a codepen?

**Comment by acburst** [comment]
I've rewritten autocomplete so it now uses dropdown to show its options, meaning it should be more robust.

Changed in 1e81583466d3373092f1bedfeb699448782eeb48.

If it still persists on the latest version you can open a new issue.

**Comment by dealloc** [comment]
Apologies for lack of response, it's been terribly busy.
I haven't been able to reproduce the issue in a reliable way, so I'm assuming that it was either a configuration error on my side or that 1e81583 fixed the issue.
