### ISSUE TITLE
Parallax issue on mobile

### ISSUE THREAD

**Issue by luismgz** [Dogfalo/materialize#573]
Looking at the parallax template, I see that when the screen size is small, the contents of the parallax (text and button) flow below the image. They not remain contained within the parallax.
Is this the intended behavior?

It looks weird, because the text line inside the parallax, which is white, is no longer visible when it appears below the background image. Please look at the parallax template and resize the screen to see know what I mean.

I wonder if it's possible to make the text and button responsive inside the parallax container, so that they resize along while reducing the screen size (or using mobile).

**Comment by acburst** [comment]
This is due to the image sizes. We added a min-height attribute to the containers that you can tweak but I can look into a better fix later.

**Comment by Cipherwraith** [comment]
![screen shot 2015-01-31 at 12 02 31 pm](https://cloud.githubusercontent.com/assets/5457807/5986727/096513ac-a942-11e4-9d44-bf6f1bf25ac3.png)

I have also ran into this problem. I have attached a screenshot of the buggy responsiveness.

**Comment by Cipherwraith** [comment]
Heres another example of mobile resolution having buggy responsiveness:

![screen shot 2015-01-31 at 12 14 03 pm](https://cloud.githubusercontent.com/assets/5457807/5986760/1730ca5c-a943-11e4-931d-101fc88927ea.png)

**Comment by luismgz** [comment]
That's exactly how I see it. 
What's weird, too, is that the "Get Started" button looks cut in half.

I hope you guys find a fix for this, because parallax is really cool effect.

**Comment by richerlariviere** [comment]
As a quick fix, you can add some css to a media-query which is triggered on mobile devices, @luismgz, but I agree with you : an official fix could be great!

**Comment by Bahtx** [comment]
@richerlariviere Could you go a little more in depth about the quick fix? I really hope this is fixed soon. Really ruins the template.

**Comment by acburst** [comment]
Fixed in d377f418373b55c60c252bcfcc2fc13e8021d7df

The changes won't show up on the template until we release however which should be soon hopefully.

**Comment by luismgz** [comment]
Thank you!
