### ISSUE TITLE
Materialize package for Meteor not update to v1.0 alpha

### ISSUE THREAD

**Issue by OlivierJM** [Dogfalo/materialize#5731]
When installing materialize in meteor with `meteor add materialize:materialize` as recommended from the getting started section of the documentation only installs v0.100 which still depends on jQuery, installing via npm doesn't work well for me as I had issues initializing things like select, modals, etc ...
When is the meteor package likely to get updated?
Thanks for the good work @Dogfalo

**Comment by Dogfalo** [comment]
We aren't adding the alpha versions to meteor, we will likely add beta versions to meteor to have them tested before going to 1.0
