### ISSUE TITLE
Filled in checkbox with Safari 11.0.3

### ISSUE THREAD

**Issue by GitHub-Mike** [Dogfalo/materialize#5732]
We have problems with the filled in checkbox and Safari 11.0.3.
Activation works, but not the filled in effect.

Is safari supported up to version 11.0.3?

```
<input type="checkbox" class="filled-in" id="cb1">
<label for="cb1"></label>
```

**Comment by Dogfalo** [comment]
Can you create a gif of what you're seeing? Seems to have no issue on our end

**Comment by GitHub-Mike** [comment]
Sorry, is not a safari problem.

Is a problem with the last collapsible only. Checkbox in other collapsibles have no problem!

Checkbox is checked, but css is not working this pattern.

```
<!-- last collapsible -->
<ul class="collapsible" data-collapsible="expandable">
<li>
<div class="collapsible-header">Name</div>
<div class="collapsible-body">
     <ul class="collection">
         <li class="collection-item">
             <input type="checkbox" class="filled-in toggle_item" id="cb1">
             <label for="cb1"></label>
         </li>
    </ul>
</div>
</li>
</ul>
```
```
$('.toggle_item').on('change', function (e) {
    var $elem = $(this);
    if ($elem.prop('checked')) {
        console.log('checked');
    } else {
        console.log('unchecked');
    }
});
```

**Comment by acburst** [comment]
Are you on the latest beta version? We switched to a label wrapping structure.

http://materializecss.com/checkboxes.html
