### ISSUE TITLE
time picker and date picker don't work inside modals

### ISSUE THREAD

**Issue by BlackTango** [Dogfalo/materialize#5734]
When asking general "how to" questions:

- Please do not open an issue here!
- Instead, ask for help on [StackOverflow](stackoverflow.com/questions/tagged/materialize) or in our [Gitter](https://gitter.im/Dogfalo/materialize) channel.

- Read the [CONTRIBUTING document](https://github.com/Dogfalo/materialize/blob/master/CONTRIBUTING.md) Any issues that are violating the contributing guidelines, will be closed!
- [Search for duplicate or closed issues](https://github.com/Dogfalo/materialize/issues?utf8=%E2%9C%93&q=is%3Aissue) and make sure to go through our [labels](https://github.com/Dogfalo/materialize/labels).
- Include a [reduced test case](https://css-tricks.com/reduced-test-cases/) in the form of a Codepen when reporting bugs unless it is not applicable, otherwise your issue will be closed.

## Expected Behavior

the time and date picker should open even inside modals

## Current Behavior

all the screen go dim like it's supposed to do (background) but the picker never appear. It is initialised using Jqery.

## Steps to Reproduce (for bugs)

1.
2.

![image](https://user-images.githubusercontent.com/15683321/37268064-5b0a4e3e-259a-11e8-9464-a5517251e02b.png)

## Your Environment

* Version used: Materialize v1.0.0-alpha.4 
* Browser Name and version: chrome Version 65.0.3325.146 (Official Build) (64-bit)
* Operating System and version (desktop or mobile): win 10
* Link to your project (if appropriate):

**Comment by Dogfalo** [comment]
Did you try the `container` option?

**Comment by Dogfalo** [comment]
In my test, it worked fine even without the container option. In the future, please read Issue Guidelines
