### ISSUE TITLE
'closeonselect' option in date picker

### ISSUE THREAD

**Issue by leftdead7** [Dogfalo/materialize#5735]
This option was quite handy in the beta versions. Is it expected to come in future releases?

**Comment by YuManZz** [comment]
I use the 1.0.0-alpha.4 and I need it too, possible to add this in the alpha.5 ?

Thanks

**Comment by Dogfalo** [comment]
Added in d7288d3ba63e448b11f0ed869830bd52a3b2dcf1

**Comment by leftdead7** [comment]
Thank you

**Comment by reustle** [comment]
@leftdead7 The `autoClose` option wasn't working for me either, so I just used this in my initialization options for the datepicker.

```
onSelect: function() {
    this._finishSelection()
}
```
