### ISSUE TITLE
dont work collapsible on jquery 1.7.2

### ISSUE THREAD

**Issue by lexuspro** [Dogfalo/materialize#5736]
I use a Materialize v0.97.8 on jquery 1.7.2
Materialize v0.97.8 fully working on this version of jquery but collapsible not working, when clicking nothing happens!
There are no errors in the browser console, everything else works.
Is there a solution to using collapsible for jquery 1.7.2?

**Comment by acburst** [comment]
This is an old version. Try updating to a more current version to see if the problem persists.

**Comment by lexuspro** [comment]
Thank You! My CMS uses this version without the upgrade option(
