### ISSUE TITLE
How can i change the dimension of checkbox ?

### ISSUE THREAD

**Issue by R2D2-fwks** [Dogfalo/materialize#5737]
I am not able to change the dimension of the checkbox . 
```
input[type="checkbox"]{
  width:0.5em;
  height: 0.5em;
  position: relative;
}
```

This is how i am trying to do . Please help .

Thanks

**Comment by Dogfalo** [comment]
You can either modify it using Sass or you can modify the CSS properties of the `:before` and `:after` elements
