### ISSUE TITLE
Crash Materialize 'removeChild' of null after dimissing toast

### ISSUE THREAD

**Issue by Albiwalbi** [Dogfalo/materialize#5738]
While I'm uploading some data to server I show a toast. After the data is successfully uploaded I'll dismiss the Toast programmatically. Now when the user swipes away the toast before the server has uploaded the code, Materialize will crash. This is because it can't remove the child anymore

## Possible Solution
Check for children before dismissing

## Steps to Reproduce (for bugs)
1. Create a toast
2. Set a timer to dimiss toasts after 5 seconds
3. dismiss toast before 5 seconds
4. watch it crash

## Your Environment

* Version used: 1.0.0 Alpha 4
* Browser Name and version: Chrome
* Operating System and version (desktop or mobile): Mac

**Comment by acburst** [comment]
Why don't you clear the timer when you dismiss the toast? Or just check if the timer still exists in your timer code.

**Comment by Albiwalbi** [comment]
I don't create a timer, that was just a way to reproduce the issue.

**Comment by Dogfalo** [comment]
Fixed in ff6f9fbd8ecd399a409f2ab9e59c4b1b303fd91c
