### ISSUE TITLE
Autocomplete pushes down content

### ISSUE THREAD

**Issue by dealloc** [Dogfalo/materialize#5739]
## Expected Behavior

When I open the dropdown, I would expect it to open as on the screenshot below:
![2018-03-13 13_44_50-gcdb](https://user-images.githubusercontent.com/2164354/37342812-f9cd7cf4-26c5-11e8-825a-96ae715cabd3.png)
(note the input below autocomplete is behind the dropdown)

## Current Behavior

When I currently open the autocomplete however, I get this:
![2018-03-13 13_46_48-gcdb](https://user-images.githubusercontent.com/2164354/37342854-24f6b544-26c6-11e8-989f-b94804c8bcfb.png)
(note that the input below autocomplete is being pushed down).

## Possible Solution

I managed to get the desired behaviour by adding the following CSS to the `<ul>`:
![2018-03-13 13_45_49-developer tools - http___localhost_8080_](https://user-images.githubusercontent.com/2164354/37342891-43706a10-26c6-11e8-8069-ce58a1460212.png)

## Steps to Reproduce (for bugs)

1. 
2.

## Your Environment

* Version used: v1.0.0-alpha.4  2f33425ee6b98ed77f1fdd9135685181a2b28d5c
* Browser Name and version: Chrome 64
* Operating System and version (desktop or mobile): Windows 10 (desktop)
* Link to your project (if appropriate):

**Comment by Dogfalo** [comment]
This was fixed after alpha.4
