### ISSUE TITLE
Label go out with a float element

### ISSUE THREAD

**Issue by RomainLanz** [Dogfalo/materialize#574]
Hi,

When you put a float element before the input you can see that the label go out.
You can see that here : http://jsfiddle.net/847eLkj5/

One solution is to add a "clearfix" after the element but it's ugly. Maybe you have a better solution?

**Comment by acburst** [comment]
Hmm, I would recommend using a clearfix. I just added a clearfix class that I've been meaning to add for a while.

**Comment by RomainLanz** [comment]
Oh perfect, need to wait for the gem on rails :+1:
