### ISSUE TITLE
Sidebar closing when clicking on input tag while on mobile.

### ISSUE THREAD

**Issue by Shinseiten** [Dogfalo/materialize#5741]
I tryed to copy your sidebar on next.materializecss.com because I think it's beautiful (the css is slighty different), but I found a problem.
When I click on the search input on mobile, it closes the sidebar.
The original doesn't have this behavior, but I don't understand what it's causing it. Can someone help me?

I'm using alpha4, here's the codepen: https://codepen.io/Shinseiten/pen/dmGNZv

Thank you very much in advance.

**Comment by Dogfalo** [comment]
I'm not seeing the problem in the codepen, any additional steps to reproduce?

**Comment by acburst** [comment]
I believe this is the same issue as #5677. This has been fixed and will be included in the next release

**Comment by Shinseiten** [comment]
Yes, I think it's the same. Sorry I didn't find that. I'll wait for the patch.
Thank you with your hard work. You're amazing!
