### ISSUE TITLE
 overlay preloader like Android swipe refresh

### ISSUE THREAD

**Issue by ghozien** [Dogfalo/materialize#5745]
How to create overlay preloader like Android swipe refresh?

**Comment by acburst** [comment]
Have you taken a look at http://next.materializecss.com/preloader.html?

**Comment by ghozien** [comment]
Yes, but how to make preloader overlay other view like a floating action button?

**Comment by Dogfalo** [comment]
You'll have to take care of doing the positioning yourself, we don't provide a component for specifically for that
