### ISSUE TITLE
When a modal is opened, the Tab key press starts focusing on background input fields

### ISSUE THREAD

**Issue by apoorvsukumar** [Dogfalo/materialize#5746]
When a modal is opened, the Tab key press starts focusing on background input fields. It means that if a modal opens and I start doing Tab press, after the last element in modal, the focus shifts to background selection. So I can enter a value in input field which is at background layout, even if the modal is opened.

## Expected Behavior

I think, if the modal is opened and Tab key is pressed repeatedly, we should allow navigation only inside modal fields. Once the modal gets closed, then only Tab press of background page should work. Elaborating, the Tab key press should work for active views only.

Like [BootStrap Modal](https://getbootstrap.com/docs/4.0/components/modal/)

## Current Behavior

Open [Materialize modal demo](http://materializecss.com/modals.html), and start pressing Tab from keyboard. After selecting all the focus-able fields inside modal, the Tab selection goes in background page. The Tab should always select the current focus-able element. But it doesn't happens here.

## Possible Solution
While working with materialize modal, I assigned **tabindex='-1'** to all the body element in current page except **modal** class. And while closing modal, I reassigned the **tabIndex** of all body elements to 0.

Making the **tabIndex=-1** automatically made all the background html element as non-focusable. 

But if any of my element was having default/predefined **tabIndex** property, I lost all those values.
So my solution was approximate and 50% temporary hack.

## Your Environment

* Materialize Version used: v0.100.2
* Browser Name and version: Version 64.0.3282.186 (Official Build) (64-bit)
* Operating System and version (Desktop): Windows 10

**Comment by acburst** [comment]
Fixed in da3f1483. This will be available in the next release
