### ISSUE TITLE
Datepicker don't work on modal with fixed footer

### ISSUE THREAD

**Issue by YuManZz** [Dogfalo/materialize#5749]
Hello,

When I use a modal with the class "modal-fixed-footer", datepickers inside don't work.

**Comment by Dogfalo** [comment]
Please read over Issue Guidelines and add a codepen

**Comment by YuManZz** [comment]
Oups sorry..

This is the codepen : https://codepen.io/anon/pen/LdbLow

**Comment by dev-plus** [comment]
Hello

Just add             
$('.datepicker').pickadate({
                **container: 'body'**
            });

To the datepicker initializer.

**Comment by acburst** [comment]
That is correct @dev-plus. Using the container option, you can choose the parent container where the picker is appended to. You should specify `container: 'body'` whenever you are putting the datepicker inside anything with restricted overflow.

**Comment by schneiderbruno** [comment]
work for my. thx
