### ISSUE TITLE
Feature request (.truncate)

### ISSUE THREAD

**Issue by JayHoltslander** [Dogfalo/materialize#5752]
This scrolling overflow would be a nice addition to ``.truncate``

### GIF:
![](https://media.giphy.com/media/uFj8RM4Tc79NMwMko6/giphy.gif)

### Demo
[JSFiddle](http://jsfiddle.net/amyseqmedia/2gKZF/)

### Source:
<http://eng.wealthfront.com/2013/03/04/dynamically-scroll-long-tab-titles/>

**Comment by JayHoltslander** [comment]
[An experiment I did](https://codepen.io/j_holtslander/pen/wmgKea) to test the above with Materialize. It really doesn't play well with columns because of their fluid widths. 😞

**Comment by JayHoltslander** [comment]
I came up with [a working version](https://codepen.io/j_holtslander/pen/vRgyvr). Not perfect. Not pure css. But it does the job. Posting this in case anyone ever stumbles across this while Googling for a way to achieve this.

**Comment by Dogfalo** [comment]
We won't be adding this to the core library, but hopefully people stumble across this code if they're interested in achieving this effect
