### ISSUE TITLE
Feature Request: Mini Sidenav

### ISSUE THREAD

**Issue by ryanrapini** [Dogfalo/materialize#5753]
Building off of the existing sidenav, it would be great to support this proposed menu from the material design guidelines.

https://material.io/guidelines/patterns/navigation-drawer.html

<img src="https://storage.googleapis.com/material-design/publish/material_v_12/assets/0Bx4BSt6jniD7ZVZzVEhrbF9YWk0/patterns-navdrawer-behavior-persistent4.png" width="200">

My main complaint with the current "responsive" menu is that when the sidenav turns into a hamburger menu it is a little vague to users how they can navigate through the app - they have to find the hamburger menu in the top corner on their own.

This looks fine, until you scroll down or add more clutter to the page, and then it can be easy to miss.
<img src="https://storage.googleapis.com/material-design/publish/material_v_12/assets/0Bx4BSt6jniD7NzRVc2pDbXRuVzg/patterns-navdrawer-behavior-persistent1.png" width="200">

Any thoughts?

**Comment by Dogfalo** [comment]
This idea is already captured in #2304, however we're focused first on releasing 1.0 in a good state

**Comment by ryanrapini** [comment]
Thank you for all your work on this project!
