### ISSUE TITLE
Datepicker not showing defaultDate

### ISSUE THREAD

**Issue by Lucarus** [Dogfalo/materialize#5755]
My Code:

> M.Datepicker.init(document.querySelector("#datepicker_von"), {
>              setDefaultDate: true,
>                defaultDate: moment()
>            });

If I open the site the Datepicker is empty.
But if I open the Datepicker Dialog I can see, that the selected Date is today (just the number is written in green, no circle around it).
Clicking "Ok" doesnt select the Date either.

> M.Datepicker.getInstance(document.querySelector("#datepicker_von")).setDate(moment());

Seems like setDate() is also not working to set the displayed Date

Another thing I discovered is that, if you use
>onSelect: function (date) {
>M.Datepicker.getInstance(document.querySelector("#datepicker_von")).close();
>}

its also not displaying the selected Date.

I am using MaterializeCSS Version 1.0 Alpha-4
Browser is IE11, Vivladi and Chrome

**Comment by Dogfalo** [comment]
Fixed in d6b78e054cc2ff10346f3bc80f3b9241339fb173.
