### ISSUE TITLE
Select List - Select All Option

### ISSUE THREAD

**Issue by stap123** [Dogfalo/materialize#5756]
Would it be possible to investigate adding a new feature to the select list.

It would be great to have the ability to turn on a "select all" option that would appear the top of a multi select list, allowing the user to select/deselect all options in a single click.

**Comment by Dogfalo** [comment]
We'll be adding some enhancements after 1.0

**Comment by ncovercash** [comment]
@stap123 why was this closed?

**Comment by stap123** [comment]
project is dead and I was clearing old issue that will never be dealt with. You're welcome to re-open and keep it around if you want but with no commits for 18 months and no release since 2018 I think it's pretty safe to say this isn't going anywhere at the moment 👍
