### ISSUE TITLE
TimePicker no longer has afterDone option

### ISSUE THREAD

**Issue by enriquedfa** [Dogfalo/materialize#5768]
## Expected Behavior
In the previous beta version of Materialize (0.100.2) I could use the afterDone option to make something else after closing the timepicker.
Something like this:
`$('.timepicker').pickatime({
    afterDone: function( {
        console.log("tp closed");
    }
  });`

## Current Behavior
Since Materialize 1.0 timePicker no longer has the afterDone option, only the DatePicker does have something similar (onClose).

## Context
I used to have 2 inputs for dates, 1 enabled and the other disabled, after picking a time on the enabled field, the disabled one would be updated with the timepicker time plus 7 hours added.

## Your Environment
* Version used: 1.0.0 Beta
* Browser Name and version: Chrome v65
* Operating System and version (desktop or mobile): Windows 10

**Comment by Dogfalo** [comment]
Added 5 callbacks to Timepicker a86631d67e66a42dbda0a1229b86e087bba1a408
