### ISSUE TITLE
Field data-success and data-error are not shown when the input has validity-related classes

### ISSUE THREAD

**Issue by smileytechguy** [Dogfalo/materialize#5770]
## Expected Behavior
If the field's label has a `data-success` attribute and the input is valid (e.g. has `valid` class), the `data-success` text is shown below it.  If the field's label has a `data-error` label and the input is invalid (e.g. has the `invalid` class), the `data-error` text is shown below it.

## Current Behavior
The field is colored green or red in accordance with the validity, however the text is not shown as it did previously (v0.99.0)

## Possible Solution
Will look into this later.

## Steps to Reproduce (for bugs)
https://codepen.io/anon/pen/aYEbvR
Or attempt the example provided on the docs, same issue.

## Context
My field validation solution no longer works as expected.

## Your Environment
* Version used: 1.0.0-beta
* Browser Name and version: Google Chrome Stable v65.0.3325.181 (64-bit)
* Operating System and version (desktop or mobile): Windows 10 Desktop, with touchscreen

**Comment by smileytechguy** [comment]
Looking at the source, it seems like 97c450bb23c02dca2016b3e6bf72717ce25024c2 is what broke everything.

**Comment by Dogfalo** [comment]
New markup for the helper text in 1.0
https://codepen.io/Dogfalo/pen/aYEzvz

**Comment by smileytechguy** [comment]
~~ew~~ alright, i'll update the title to mark this as a documentation issue.

**Comment by smileytechguy** [comment]
Do we need to include the `span` if we only want error/success messages, not the helper text?

**Comment by Dogfalo** [comment]
Please look at the documentation here: http://materializecss.com/text-inputs.html
