### ISSUE TITLE
Compiling CSS from SASS excludes Pulse class

### ISSUE THREAD

**Issue by stigeebus** [Dogfalo/materialize#5771]
When compiling CSS for Materialize 0.100.2 from SASS, the resulting CSS does not contain the .pulse, ,pulse:before, @-webkit-keyframes pulse-animation, or @keyframes pulse-animation CSS definitions.

I compiled the SASS using Koala 2.3.0 for Windows from the Materialize source package linked for download at https://github.com/Dogfalo/materialize/releases/download/v0.100.2/materialize-src-v0.100.2.zip

I'm not sure if there is anything else missing, because pulse was all I was looking for, but it may be possible that other CSS is left out as well.

You can manually add the definitions to your CSS file:
`.pulse{
    overflow:initial;
    position:relative
}
.pulse::before{
    content:'';
    display:block;
    position:absolute;
    width:100%;
    height:100%;
    top:0;
    left:0;
    background-color:inherit;
    border-radius:inherit;
    -webkit-transition:opacity .3s, -webkit-transform .3s;
    transition:opacity .3s, -webkit-transform .3s;
    transition:opacity .3s, transform .3s;
    transition:opacity .3s, transform .3s, -webkit-transform .3s;
    -webkit-animation:pulse-animation 1s cubic-bezier(0.24, 0, 0.38, 1) infinite;
    animation:pulse-animation 1s cubic-bezier(0.24, 0, 0.38, 1) infinite;
    z-index:-1
}
@-webkit-keyframes pulse-animation{
    0%{
        opacity:1;
        -webkit-transform:scale(1);
        transform:scale(1)
    }
    50%{
        opacity:0;
        -webkit-transform:scale(1.5);
        transform:scale(1.5)
    }
    100%{
        opacity:0;
        -webkit-transform:scale(1.5);
        transform:scale(1.5)
    }
}
@keyframes pulse-animation{
    0%{
        opacity:1;
        -webkit-transform:scale(1);
        transform:scale(1)
    }
    50%{
        opacity:0;
        -webkit-transform:scale(1.5);
        transform:scale(1.5)
    }
    100%{
        opacity:0;
        -webkit-transform:scale(1.5);
        transform:scale(1.5)
    }
}`

**Comment by Dogfalo** [comment]
Please check for errors in your Sass tool, because we are compiling CSS from Sass as well with no problems.
