### ISSUE TITLE
Uncaught TypeError: Cannot read property 'textContent' of undefined  on using the scroll bar in an autocomplete.

### ISSUE THREAD

**Issue by ChildishGiant** [Dogfalo/materialize#5776]
I can scroll just fine using the mousewheel but whenever I click anywhere on the scrollbar, including the top and bottom arrows, I get an error of `Uncaught TypeError: Cannot read property 'textContent' of undefined`
https://gfycat.com/SoupyComplexEeve
![soupycomplexeeve-size_restricted](https://user-images.githubusercontent.com/13716824/38056579-b789bc84-32d4-11e8-9a80-252ad5c7ab00.gif)

## Your Environment
* Currently using prepros to minify and local host everything.
* Version used: 1.0.0-beta
* Browser Name and version:  Google Chrome | 65.0.3325.181 (Official Build) (64-bit) (cohort: Stable)
* Operating System and version (desktop or mobile): Windows 10

**Comment by acburst** [comment]
Autocomplete was using old handlers due to it not using dropdown before. It should now use dropdown click handlers.

Fixed in 553fb8f7.
