### ISSUE TITLE
Sidenav is not responsive

### ISSUE THREAD

**Issue by rster2002** [Dogfalo/materialize#5781]
When asking general "how to" questions:

- Please do not open an issue here!
- Instead, ask for help on [StackOverflow](stackoverflow.com/questions/tagged/materialize) or in our [Gitter](https://gitter.im/Dogfalo/materialize) channel.

- Read the [CONTRIBUTING document](https://github.com/Dogfalo/materialize/blob/master/CONTRIBUTING.md) Any issues that are violating the contributing guidelines, will be closed!
- [Search for duplicate or closed issues](https://github.com/Dogfalo/materialize/issues?utf8=%E2%9C%93&q=is%3Aissue) and make sure to go through our [labels](https://github.com/Dogfalo/materialize/labels).
- Include a [reduced test case](https://css-tricks.com/reduced-test-cases/) in the form of a Codepen when reporting bugs unless it is not applicable, otherwise your issue will be closed.

## Expected Behavior

Adding a sidenav to a page should be displayed right on mobile.

It should use for example 'em' instead of 'px' and '%' or 'vw' instead of 'px'. Couldn't find a material specification for it, but it is pretty self explainatory.

## Current Behavior

Adding a sidenav to a page uses fixed values that make mobile suport hard.

Now the sidenav always is 300px wide and the font is always 14px. It should adapt to the screen.

## Possible Solution

For the font use 'em' or 'rem' instead of 'px' and for the size of the sidenav, use '%' or 'vw'/'vh' instead of 'px'.

## Steps to Reproduce (for bugs)

1. Add a sidenav to a page and view the page using chromes devices tab. To find this in chrome, click press F12 and in the corner left you'll find a icon that looks like a mobile device in front of a tablet. Click on that to see what I mean.
2.

## Context

Recently added a sidenav tomy webside, but it wasn't mobile friendly.

Most page views come from mobile, so making sure a website is mobile friendly is crucial. So making sure components work on mobile is quite importand

## Your Environment

Chrome (desktop and mobile)

* Version used: 1.0.0
* Browser Name and version: Chrome v: 65.0.3325.181 (official build) (64-bits)
* Operating System and version (desktop or mobile): Windows (desktop), android (mobile)
* Link to your project (if appropriate): https://rster2002.github.io/dnd

**Comment by Dogfalo** [comment]
Sidenavs aren't meant to be responsive in width. Instead it acts as a drawer that comes in and out when needed

**Comment by leftdead7** [comment]
However according to material design specs

**Comment by leftdead7** [comment]
currenly the '.sidenav' class has width =  300px

**Comment by leftdead7** [comment]
![scv_15226641609267966170061961401248](https://user-images.githubusercontent.com/23002003/38233290-b362e11e-3737-11e8-8fa4-f84aece59064.jpg)
On ~4 inch mobile screen its does not looks good to have  a 300px side nav.

**Comment by leftdead7** [comment]
Also wanted to add the browser support for calc (just in case)
IE 9+
Edge 12+
Firefox 4+
Chrome 19+
Safari 6+
opera 15+
