### ISSUE TITLE
Tooltip misplaced if there is another absolute position element

### ISSUE THREAD

**Issue by italomaia** [Dogfalo/materialize#5784]
Well, just bumped into this. I made myself a navbar with some links, added data-tooltip to them, initialized the code, tooltips show on hover, nive. Now, If I add a absolute position image below, in another component, tooltips are rendered at the bottom of the page. Anyone facing that?

**Comment by acburst** [comment]
Can you provide some source code?

**Comment by acburst** [comment]
This might be the same issue as c00c954f. Try updating to the latest github version and see if the bug is still happening.
