### ISSUE TITLE
Google Smartlock (saved login) causes weird bug with placeholders

### ISSUE THREAD

**Issue by StayCoolDK** [Dogfalo/materialize#5787]
[This gallery](https://imgur.com/a/aNq0G) explains it all.

When saving a login (Google Smartlock), the next time the form is loaded the input fields placeholders are acting like there are no values in the input, except there is.

The expected behaviour is that the placeholders should be above the input fields, like in the 2nd image in the gallery. Which they are after a single click anywhere on the page.

Version used:  1.0.0-beta
Google Chrome, 65.0.3325.181 (64-bit)
MacOS 10.13.4

**Comment by Dogfalo** [comment]
Added a fix for this here: 573e754a822c1cbf963f50d5ae6c0a249787b607
