### ISSUE TITLE
A border bottom appears as you type in text inputs in mobile devices

### ISSUE THREAD

**Issue by yammadev** [Dogfalo/materialize#5795]
When you start typing in a text input in a mobile device, it adds like a border in the bottom of the text you are typing. 

## Expected Behavior
The same behavior in mobile than in desktop. When you type something it shouldn't have to add any border in the bottom. 

## Current Behavior
Appears a border in the bottom of the text you are typing in a text input in mobile devices. 

![Imgur](https://i.imgur.com/k5RUFi9.png)

## Possible Solution
No idea, I've tried with `&:focus` and with element `&` itself, with no favorable result. 
 
## Steps to Reproduce (for bugs)
1. Open http://materializecss.com/text-inputs.html in chrome for Android
2. Type something in a text input

## Context
That border doesn't look good in mobile devices. It's breaking the mobile design of the project. I'm aware that this should be an issue, because it doesn't fit the materialize guideliness. 

## Your Environment
* Version used: 1.0.0-beta
* Browser Name and version: Google Chrome v65.0.3325.181 (64 bits)
* Operating System and version (desktop or mobile): Windows 8.0 & Android 7.0.0

**Comment by Dogfalo** [comment]
This seems like something added by Chrome as it also happens on the Google homepage.

**Comment by yammadev** [comment]
Oh, I didn't notice it before.  So, as this is a non-framework related issue, then I think I can close this issue now. Thanks for your time.
