### ISSUE TITLE
Show only one toast

### ISSUE THREAD

**Issue by CyberMike97** [Dogfalo/materialize#5796]
how can I display only one toast at a time? is there a method, for example, to replace the toast?

**Comment by ShtHappens796** [comment]
I don't think there is such a method built-in.

You could set a variable to true when a toast appears and while it's true do not let any other toasts show up. Once the toast dismisses then set it back to false.

**Comment by Dogfalo** [comment]
You can call `  M.Toast.dismissAll();` before creating a new toast
