### ISSUE TITLE
Datepicker not binding with ngModel

### ISSUE THREAD

**Issue by d-mance** [Dogfalo/materialize#5802]
I'm using angular 5.2 and materialize 0.100.2

## Expected Behavior

The model linked with ngModel to the date picker field should reflect the changes made with the picker.

I have created a git repository to show that behaviour: https://github.com/d-mance/angularmaterializebehaviour

## Current Behavior

I have an object with a date field linked with ngModel to a date picker field.

At the loading it displays correctly the date and when the picker opens it shows correctly the date.

When change the date it reflects it ok in the input field but the ngModel is not updated.

## Steps to Reproduce (for bugs)

I do not know how to recreate in a plunker or codepen with both angular and materialize so I paste the relevant code here.

1.
`<tr *ngFor="let dataSource of dataSources; let i = index">
      <td>{{dataSource.name}}</td>
      <td>{{dataSource.cv.name}}</td>
      <td>
        <input type="text" name="startDate{{i}}" class="datepicker" [(ngModel)]="dataSource.guideSet.startDate">
      </td>
      <td>
        <input type="text" name="endDate{{i}}" class="datepicker" [(ngModel)]="dataSource.guideSet.endDate">
      </td>
      <td>
        <button type="button" (click)="check()">Check</button>
      </td>
    </tr>`

2.
dataSources: any[] = [
    {"id":58,"name":"Instrument 1","apiKey":"40f878b4-9d2c-448e-aaf3-f883ff320d1c","guideSet":{"startDate":"2018-02-13","endDate":"2018-02-19"},"cv":{"id":1,"name":"Turbo analyzer 2000","category":{"id":1,"name":"Gas analyzer"},"enabled":true}},
    {"id":61,"name":"Instrument 2","apiKey":"bb26e2da-4108-41cf-bb4e-e6877898c134","guideSet":{"id":null,"startDate":null,"endDate":null},"cv":{"id":55,"name":"Turbo analyzer 2100","category":{"id":1,"name":"Gas analyzer"},"enabled":true,}}
  ];
// I enable the pickers with this function
datePickers: any = [];
  private initializeDatePickers(): void {    
    let datePickers = document.getElementsByClassName('datepicker');
    for (var i = 0; i < datePickers.length; i++) {
      let options = {
        format: 'yyyy-mm-dd',
        firstDay: 1,
        setDefaultDate: false
      }
      let instance = M.Datepicker.init(datePickers[i], options);
      this.datePickers.push(instance);
    }
  }
// with this function I check if the model is updated or not
  check(): void {
    console.log(this.dataSources);
  }

## Your Environment

* Version used: 0.100.2
* Browser Name and version: chrome 65 
* Operating System and version (desktop or mobile): ubuntu mate 16.04

**Comment by Dogfalo** [comment]
In the old version 0.100.2 you can set the model in an event: 
http://amsul.ca/pickadate.js/api/#method-on-callback-options
