### ISSUE TITLE
Overlay overlaps sidebar when using navbar-fixed

### ISSUE THREAD

**Issue by aexvir** [Dogfalo/materialize#5804]
There are two issues already created but they are poorly explained and it's hard to understand the issue.

When using a fixed navbar the grey overlay overlaps the sidebar menu making it impossible to use. I've made a jsfiddle showing the issue [here](https://jsfiddle.net/alexviscreanu/oc6601e7/).

<img width="378" alt="screen shot 2018-04-08 at 10 42 00" src="https://user-images.githubusercontent.com/8055505/38465219-8c644b62-3b19-11e8-98cc-a37d2996aca7.png">

~Only with changing the z-index of the sidenav-overlay to 996 fixes the issue but I'm not sure it's the correct solution.~

If it matters I'm on Chrome 65.0.3325.181 (Official Build) (64-bit) on macOS 10.13.4

The issues related to this problem are #5205 and #5750

**Comment by aexvir** [comment]
Duplicate of #5205

**Comment by aexvir** [comment]
Duplicate of #5750

**Comment by aexvir** [comment]
Changing the z-index of the overlay to 996 is not a good solution. The nav is over it, but the whole nav, not only the sidenav.

**Comment by Dogfalo** [comment]
Please read #3844
