### ISSUE TITLE
Native example code for JS components is not equivalent with JQuery alternative

### ISSUE THREAD

**Issue by melvyn-sopacua** [Dogfalo/materialize#5805]
## Expected Behavior
The native code examples provided should work without modifications and be equivalent to their JQuery counterpart.

## Current Behavior
The current examples that should work on multiple document fragments use `document.querySelector` instead of `document.querySelectorAll()`. In addition there is no document ready wrapper.

## Possible Solution
I should be able to come up with a PR.

## Context
When copying the native code, parallax stopped working which triggered me to look into it.

## Your Environment
Not relevant.

**Comment by melvyn-sopacua** [comment]
This is how I'd fix parallax. If that's OK, I'll fix the rest of the examples accordingly and create a PR.

```diff
diff --git a/jade/page-contents/parallax_content.html b/jade/page-contents/parallax_content.html
index 4ac65b35..14e58cfa 100644
--- a/jade/page-contents/parallax_content.html
+++ b/jade/page-contents/parallax_content.html
@@ -20,8 +20,12 @@
       <div id="initialization" class="scrollspy section">
         <h3 class="header">Initialization</h3>
         <pre><code class="language-javascript">
-  var elem = document.querySelector('.parallax');
-  var instance = M.Parallax.init(elem, options);
+  document.addEventListener('DOMContentLoaded', function(event) {
+    var coll = document.querySelectorAll('.parallax');
+    coll.forEach(function(pxe, idx, lst) {
+      M.Parallax.init(pxe, options);
+    });
+  });

   // Or with jQuery
```

**Comment by acburst** [comment]
The init method supports querySelectorAll so you don't need to use a forEach.

**Comment by Dogfalo** [comment]
Updated JS init code to use querySelectorAll in 1ce0d324e110da31aba7cabd36232870b0e63e3b
