### ISSUE TITLE
Toasts inDuration option is not respected

### ISSUE THREAD

**Issue by alantsui09** [Dogfalo/materialize#5808]
Please look at the Codepen https://codepen.io/alantsui09/pen/oqmagW.

## Expected Behavior
Transition in duration should be 10s.

## Current Behavior
While transition out is correct, transition in is not. I suspect that it is still the default value 300ms.

## Your Environment
* Version used: 1.0.0-beta
* Browser Name and version: Chrome 65
* Operating System and version (desktop or mobile): macOS High Sierra Version 10.13.4
* Link to your project (if appropriate): https://codepen.io/alantsui09/pen/oqmagW

**Comment by acburst** [comment]
Good catch, thanks.

Fixed in 6ea957f8
