### ISSUE TITLE
Feature Request: Badges for collapsibles

### ISSUE THREAD

**Issue by jhuenges** [Dogfalo/materialize#581]
Would be a nice to have.

**Comment by Dogfalo** [comment]
Badges exist

**Comment by jhuenges** [comment]
Yeah ... But I had some strange behaviour with them in my sidebar navigation. Got it now :P

![image](https://cloud.githubusercontent.com/assets/7192165/5992148/c6d806c2-aa1b-11e4-98e2-9186fc4a3445.png)

Is there a way to make it look more like the badge in combination with the "collection" component?

**Comment by jsduffy** [comment]
Badges also display incorrectly in collapsible header divs.  This just became an issue in 0.97.0

**Comment by developeranirudhprabhu** [comment]
@jhuenges please share the code
