### ISSUE TITLE
bug browser-default class on new 1.0.0-alpha.4

### ISSUE THREAD

**Issue by GregoryMonteiro** [Dogfalo/materialize#5811]
bug browser-default class on new 1.0.0-alpha.4
![image](https://user-images.githubusercontent.com/10130025/38629492-16a170ae-3dac-11e8-9420-908f2dd89376.png)

old version without bug
![image](https://user-images.githubusercontent.com/10130025/38629597-6779e54c-3dac-11e8-9cf1-237f8982f877.png)

**Comment by acburst** [comment]
Have you tried on 1.0.0-beta?

**Comment by ray007** [comment]
Does not work inside a "div" with class "input-field" also sounds like a bug to me.

**Comment by acburst** [comment]
Tested on 1.0.0-beta and it seems to be working fine.

**Comment by GregoryMonteiro** [comment]
work fine on beta
don't work on alpha
