### ISSUE TITLE
how to update select form?

### ISSUE THREAD

**Issue by GregoryMonteiro** [Dogfalo/materialize#5812]
When i click on button i change value from select inside card. but it no change
![image](https://user-images.githubusercontent.com/10130025/38629766-dc52e6e8-3dac-11e8-95b3-ac064b3eb612.png)

when i click on select show value select..
![image](https://user-images.githubusercontent.com/10130025/38629865-24be9b34-3dad-11e8-9754-0b81b0605829.png)

**Comment by Dogfalo** [comment]
Please create a Codepen that illustrates your problem

**Comment by GregoryMonteiro** [comment]
When I click on button the value displayed no change
[https://codepen.io/anon/pen/YaMLLX](url)

if i try use 'material_select' console.log return:
Uncaught TypeError: $(...).material_select is not a function

if i use 'destroy' according site console.log return:
Uncaught TypeError: $(...).des is not a function

but I found solution how to use that
https://codepen.io/anon/pen/GxLGxy

I think the explanation on [http://materializecss.com/select.html](url) is not easy to understand...
If u change that is fine

**Comment by Dogfalo** [comment]
Please use this to call the instance methods
```

  var instance = M.FormSelect.getInstance(elem);

  /* jQuery Method Calls
    You can still use the old jQuery plugin method calls.
    But you won't be able to access instance properties.

    $('select').formSelect('methodName');
    $('select').formSelect('methodName', paramName);
  */
```
