### ISSUE TITLE
[Feature Request] Use CSS variables to allow easier overriding of colors and other global constants

### ISSUE THREAD

**Issue by smileytechguy** [Dogfalo/materialize#5815]
## Expected Behavior

This isn't part of MD spec, but relates instead to application.  I'm not sure if this is possible just by using SASS' compiler directly or if there would be edits needed to Materialize itself.

It would be useful to me and others to be able to easily override certain variables like color (or, if possible, all of https://github.com/Dogfalo/materialize/blob/v1-dev/sass/components/_variables.scss) easily in CSS through CSS variables.

This would allow easy overriding when using the CDN, and allows component-level styling (for example, coloring only buttons one color, or recoloring a section of the page) as well.

## Current Behavior

A user must add icky CSS overrides to their own custom stylesheet, or re-build materialize from source (which is outside of many beginner's skillset).

## Possible Solution

See above.  Potentially changing the way SASS compiles to store its variables as CSS variables (I am unsure if this is possible), or refactoring materialize in such a way.

## Context

I have seen many issues where beginners have struggled to change a variable in materialize, most notably color.  They are not able to recompile the SASS code due to a lack of knowledge/experience.  Additionally, CDN users cannot use their recompiled SASS with the CDN benefits either.

## Your Environment

* Version used: `1.0.0-beta`

Before anyone asks, [it is supported by everything semi-relevant](https://caniuse.com/#feat=css-variables).  However, it is not everything listed in the README.  It may be time for that to get bumped, especially as of the 1.0.0 release, and for you guys to fully take advantage of new CSS features.

**Comment by Dogfalo** [comment]
We aren't looking to drop IE 11 support just yet as its browser share is still relevant. When that happens we can make some of these changes.

**Comment by smileytechguy** [comment]
@Dogfalo Perhaps, if IE 11 is still needed, you guys could provide an alternate legacy build, like Shopify/draggable does.  If this can be done in the SASS engine itself this shouldn't be too difficult.
