### ISSUE TITLE
Multiple modals on same page do not work.

### ISSUE THREAD

**Issue by iFreedive** [Dogfalo/materialize#5816]
## Expected Behavior
Add two modals to the same page.

 ` <a class="waves-effect waves-light btn modal-trigger" href="#modal1">Modal 1</a>

          
          <div id="modal1" class="modal">
            <div class="modal-content">
              <h4>Modal Header</h4>
              <p>A bunch of text</p>
            </div>
            <div class="modal-footer">
              <a href="#!" class="modal-action modal-close waves-effect waves-green btn-flat">Agree</a>
            </div>
          </div>

          <a class="waves-effect waves-light btn modal-trigger" href="#modal2">Modal 2</a>

          
          <div id="modal2" class="modal">
            <div class="modal-content">
              <h4>Modal Header</h4>
              <p>A bunch of text</p>
            </div>
            <div class="modal-footer">
              <a href="#!" class="modal-action modal-close waves-effect waves-green btn-flat">Agree</a>
            </div>
          </div>`

Initialized using the following.

`var options = {};
var elem = document.querySelector('.modal');
var instance = M.Modal.init(elem);`

Tap on the modal buttons and both should popup, this works fine on the materialize modals page
In my case only the first modal is displayed when tapping the button.

I appears initialisation has to be performed for each modal. 
I have also repeated this behaviour with select drop downs and date pickers on the same page.
Initialization only works for the first control.

I got round this with the selects and date pickers by creating initialisations for each control by using an id as these controls on the particular page are static.

The problem I have with the modals on this particular page is these are created dynamically when the page loads.
Only the first modal ever pops up.

This is a page I am converting from using bootstrap to materialize and works fine for multiple modals in bootstrap.

I have tried downloading the starter template and just adding two modals above and initialisation to the index page  to see if it was something wrong on my page but I can reproduce the same behaviour on there too.

I can't figure what I am doing wrong and guess you shouldn't have to initialise every control on the page?

**Comment by iFreedive** [comment]
Hi All

Just figured it out.
For them to work in general I have to add them to init.js

So for example in the starter template, adding the modal, they all display without any initialisation.

(function($){
  $(function(){

    $('.sidenav').sidenav();
    $('.modal').modal();
  }); // end of document ready
})(jQuery); // end of jQuery name space

**Comment by Dogfalo** [comment]
You can also use `document.querySelectorAll('.modal');` or `M.AutoInit(document.body)`
