### ISSUE TITLE
Error: Method undefined does not exist on jQuery.tap-target

### ISSUE THREAD

**Issue by ledevinchi** [Dogfalo/materialize#5818]
I'm using the http://materializecss.com/feature-discovery.html, But the 'tap-target' is not working.

My code:
`        $(document).ready(function () {
            $('.tap-target').tapTarget();
        });`

     <div class="fixed-action-btn">
        <a id="dwn" class="btn-floating btn-large red">
            <i class="large material-icons">file_download</i>
        </a>
        
        <div class="tap-target" data-target="dwn">
            <div class="tap-target-content">
                <h5>Title</h5>
                <p>A bunch of text</p>
            </div>
        </div>
    </div>

When I run the page the is an error: `Error: Method undefined does not exist on jQuery.tap-target` (I'm using Google Chrome)

I also tried couples of jQuery versions. currently I use this: https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js.

**The jquery loaded before materialize.js**

**Comment by alexwbaumann** [comment]
Your code is working in a [CodePen](https://codepen.io/anon/pen/bMbKjg) with v1.0.0. If you are using an old version you may need to use `$('.tap-target').tapTarget('open');`
