### ISSUE TITLE
Angular wrapper

### ISSUE THREAD

**Issue by neo-xy** [Dogfalo/materialize#5821]
any plans for angular 4+ wrapper for 1.0.0. beta ?

**Comment by Dogfalo** [comment]
No plans for a angular wrapper, but we've created a angular materialize boilerplate

**Comment by neo-xy** [comment]
@Dogfalo can't find it:S -could You pls link it to it - would be very thankfull(y)

**Comment by Dogfalo** [comment]
Still finalizing it, will likely be released alongside 1.0 stable.

**Comment by neo-xy** [comment]
great! ty for information (y)

**Comment by tcd** [comment]
@Dogfalo Was that something that was ever released or published anywhere?
