### ISSUE TITLE
All calls M.(*).init(*) have a problem

### ISSUE THREAD

**Issue by GregoryMonteiro** [Dogfalo/materialize#5823]
people, on site of materialize all calls os that instance have a problem because `document.querySelector` get only first occurrence of selector
If you want instance all occurrences of selector without jQuery do this

`var instance = [];`
`document.querySelectorAll('select').forEach(function(elem) {`
`	instance.push(M.FormSelect.init(elem));`
`});`

**Comment by Dogfalo** [comment]
The init method supports querySelectorAll so you don't need to use a forEach.

**Comment by tomscholz** [comment]
Please close

**Comment by DorianLovera** [comment]
if you downloaded your package via npm it is not the updated version so take materialize.js from the official website (leading to old function not supported)

**Comment by Dogfalo** [comment]
Updated JS init code to use querySelectorAll in 1ce0d324e110da31aba7cabd36232870b0e63e3b
