### ISSUE TITLE
Prevent collapsible header to open/close

### ISSUE THREAD

**Issue by AlbertoDrusiani** [Dogfalo/materialize#5825]
I have this code, with click handler on <i> tags.
I want to prevent collapsible to open when I click on `<i>` tags.
I've tried event.stopPropagation() and "return false" inside `<i>` click handler but the issue persists.

THE CODE
```
<div class="collapsible-header">
    <div class="userHeader">
        Antonio Pezzati
    </div>
    <div>
        <i class="material-icons">create</i>
        <i class="material-icons" >remove_circle</i>
        <i class="material-icons">delete</i>
    </div>
</div>
```

Materialize 1.0.0-beta

**Comment by acburst** [comment]
event.stopPropagation should work. How did you try implementing it?

**Comment by AlbertoDrusiani** [comment]
I tried to put it in the onclick handler of <i> but it doesn't work.
https://codepen.io/anon/pen/YLzNoZ

**Comment by Dogfalo** [comment]
https://codepen.io/Dogfalo/pen/aGbjLr
Don't use a delegated handler

**Comment by AlbertoDrusiani** [comment]
Those <i> tags are created dinamically, that's why I use delegated handler. Is there a workaround?

**Comment by Dogfalo** [comment]
You can add event handlers dynamically or try using the `useCapture` option as described here: https://developer.mozilla.org/en-US/docs/Web/API/EventTarget/addEventListener
