### ISSUE TITLE
Toast does not wordwrap on small screens

### ISSUE THREAD

**Issue by VoordeMensen** [Dogfalo/materialize#5827]
Toast does not wordwrap, it breaks the word on the edge of the screen and continues on the next line without wrapping. Wrapping the message in a div that explicitly wordwraps doesnt work.

Overriding the CSS works, not sure why this is in the CSS anyway.

``.toast {
	word-break: normal !important;
}``

Steps to reproduce:
```
data.message = "A message of more than five or six words will look bad on mobile";
M.toast({html: '<div style="word-wrap: normal !important;">'+data.message+'</div>'});``

**Comment by Dogfalo** [comment]
Allow normal word-break on Toasts in  18cc5dbbc82f853ea1b400fa4e33c19807b20880
