### ISSUE TITLE
What is the use of the class `modal-action`?

### ISSUE THREAD

**Issue by StephenChips** [Dogfalo/materialize#5829]
I read the documentation and found the example HTML code of modal:
```HTML
<!-- Modal Trigger -->
  <a class="waves-effect waves-light btn modal-trigger" href="#modal1">Modal</a>

  <!-- Modal Structure -->
  <div id="modal1" class="modal modal-fixed-footer">
    <div class="modal-content">
      <h4>Modal Header</h4>
      <p>A bunch of text</p>
    </div>
    <div class="modal-footer">
      <a href="#!" class="modal-action modal-close waves-effect waves-green btn-flat ">Agree</a>
    </div>
  </div>
        
```
And I mentioned that there is a class `modal-action` beside the class 'modal-close' in the `a` element. Since it is prefixed with the component's name, I guessed it probably will effects the bahaviour or apperance of the component itself, like `modal-close`, but I didn't find any introduction about it in the article, also, I didn't found the relative word in modal's JavaScript implementation file. Could someone willing to tell me what does it being used for?

**Comment by Dogfalo** [comment]
@StephenChips You are right, the modal-action class is no longer used and I have removed it from the documentation in 8605f945dabb018e5ad0fe89ea419ce0c6791041
