### ISSUE TITLE
Feature Request: [Cards] Medium and Large Sizes

### ISSUE THREAD

**Issue by jett0423** [Dogfalo/materialize#583]
I'm trying to display people for my reveal cards. It'd be nice to have cards for medium and large too

![issue card](https://cloud.githubusercontent.com/assets/10791201/5992263/9fe09566-aa5c-11e4-8461-7a56e864c4ad.PNG)

**Comment by Dogfalo** [comment]
Very true. We will add this, but in the meantime you can set height
yourself to achieve the effect

**Comment by jett0423** [comment]
okay. thanks for the heads up!

**Comment by Dogfalo** [comment]
It is better to leave this open so we don't forget to add this

**Comment by jett0423** [comment]
oops! sorry. I'm new here. thanks for correcting :)

**Comment by acburst** [comment]
Added in ebe13c2835e631a3c801bbcb8d666691b732e88b

**Comment by jett0423** [comment]
Hi! I'm opening this up again for a bug I found with the reveal cards.

![bug](https://cloud.githubusercontent.com/assets/10791201/6004530/6653419e-ab3e-11e4-8eb0-f9ee724fec50.PNG)

**Comment by jett0423** [comment]
I think the issue's more on cropping the image and scaling its height based on each size for the card. 

![bug2](https://cloud.githubusercontent.com/assets/10791201/6004716/b713a7ee-ab3f-11e4-9ad6-cc37ab9bdd81.PNG)
