### ISSUE TITLE
Option to define width in SideNav

### ISSUE THREAD

**Issue by omarmallat** [Dogfalo/materialize#5830]
I tried to ask on [stackoverflow](https://stackoverflow.com/questions/49844142/initializing-sidenav-width-in-materializecss-1-0), but there was no response. I wish I can have an answer here.

Worrying if this is against Material Design, but for small screens, I used to set the sidenav `width` to the full width of the screen during initialization by using `menuWidth: $(window).width();`

And to allow user to close without selection, I add a close button that call `$('.button-collapse').sideNav('hide');`

also, in fixed sidenav, I prefer to set `width` to some percentage of the screen width instead of fixed 300px.

after upgrading to the version 1.0 I could not pass that parameter. So is it still possible to define width in the new version?

**Comment by Dogfalo** [comment]
Yes, just change the width is css and it will work
