### ISSUE TITLE
Dropdown: border between first two options is missing

### ISSUE THREAD

**Issue by serkandurusoy** [Dogfalo/materialize#584]
As can be seen on the screenshot:

![image](https://cloud.githubusercontent.com/assets/4649948/5992600/0cd69446-aa39-11e4-9178-30df28a0260d.png)

I've tested this on latest firefox and chrome on ubuntu 14.04 64bit.

**Comment by Dogfalo** [comment]
Border is not added by default

**Comment by serkandurusoy** [comment]
Ok then please reopen this because there is a border after the second item.

So there clearly is an inconsistency here. You should either add the border to the first item, or remove the border on the second item.

**Comment by RaSeR** [comment]
There is no real border. There is li.divider added to just show an option how to do that border.

**Comment by serkandurusoy** [comment]
Oh! Thank you for the clarification.

For what its worth, compared to other frameworks such as bootstrap, foundation, semantic-ui etc I seem to keep myself having similar problems across materialize css. The documentation is kind of sparse among a few sentences and some code samples.

Now, I'm not saying that I should not be doing my homework, indeed I should.

Nonetheless, a more complete documentation, at least short list of pointers would go a long way.

In retrospect, it would be great if there were some vetted repository of documentation, a wiki perhaps, that we could contribute to. And perhaps in time, some of that could make their way into the official docs.

What's the best way to go about this? I see that wiki is enabled on this repo, but it is empty. Could we utilize that? Would one or more people be able to review contributions?

**Comment by RaSeR** [comment]
You can help framework and do pull request with some wiki docs))

**Comment by serkandurusoy** [comment]
Yes, I know that.

Since the github wiki has never been used so far, I'm asking if it is what the repository owner prefers.

And there are no official wiki article guidelines posted. So I don't know in what format and outline the wiki contributions should be.

So in order to actually help, rather than throw in random pull requests, I would like to learn and go by the suggested standards.

I hope you understand.

**Comment by RaSeR** [comment]
Sure i do. @Dogfalo answer plz something.

**Comment by serkandurusoy** [comment]
Great! Thanks. I'm actually eager to get going with this.

**Comment by acburst** [comment]
This actually sounds like a great idea! Feel free to start making wiki pages and we'll check them periodically and try and incorporate more detailed things into our documentation.

**Comment by serkandurusoy** [comment]
Ok, I'll go ahead and try to lay out an outline that I feel makes sense and send in a PR.

Hope this gets some traction and picks up.

**Comment by serkandurusoy** [comment]
It appears github wikis do not go through pull requests. I was able to add two pages without a review requirement.

https://github.com/Dogfalo/materialize/wiki/

Are you sure this is OK with you guys? I mean anyone can add/edit anything.

**Comment by acburst** [comment]
Yeh it's fine. We can moderate it hopefully

**Comment by serkandurusoy** [comment]
Ok then. Thanks.
