### ISSUE TITLE
Tooltip data-position bottom appears at bottom of page

### ISSUE THREAD

**Issue by jwbowles** [Dogfalo/materialize#5840]
## Expected Behavior
The tooltip should appear just below the tooltip button

## Current Behavior
The tooltip appears at the bottom of the containing div when the tooltip button is hovered.
https://codepen.io/anon/pen/RyNeoY

## Steps to Reproduce (for bugs)
https://codepen.io/anon/pen/RyNeoY

## Your Environment
* Version used: 1.0.0-beta
* Browser Name and version: All
* Operating System and version (desktop or mobile): OSX 10.13.3

**Comment by apazacoder** [comment]
Hi, 
A quick fix is to change the styles:
```
    html, body{
      width: 100%; height: 100%;
    }
```
and probably it's solved in:
[https://github.com/Dogfalo/materialize/commit/c00c954f04ad58bb5e274e9d410811c38492c808?diff=split](url)

I hope it helps!

**Comment by jwbowles** [comment]
Thanks @apazacoder that does indeed fix the issue! One thing to note as that issue #5784 mentions the condition of an element being absolute positioned. The codepen I shared has no absolute positioning and still demonstrates the issue.
