### ISSUE TITLE
Click outside of dropdown when dropdown is closed will trigger the 'close' event

### ISSUE THREAD

**Issue by frostless** [Dogfalo/materialize#5846]
So if I replicate a multi-selected drop-down in a iFrame environment like codePen or jsFiddle, when I click anywhere in the document, the dropdown will trigger a 'close' event even when the dropdown is already closed. But if I mimic this is a local html enviroment, this behaviour does not exist. At first I suspect the z-index property of the dropdown but it does not seem to be the case.

Any idea of the cause of this behavior?
Ref:
https://jsfiddle.net/xpvt214o/141955/
https://codepen.io/anon/pen/xdgjyL
Sorry if this question has been asked.

**Comment by acburst** [comment]
This is a pretty old version of Materialize. You should first try updating and see if the problem persists.

**Comment by frostless** [comment]
Thanks so much. I was not aware of the version. Got it updated and fixed.
