### ISSUE TITLE
Multiple select autocomplete

### ISSUE THREAD

**Issue by jpic** [Dogfalo/materialize#5848]
Currently, MaterializeCSS has text input autocomplete.

This issue requests a multiple select autocomplete widget. It should maintain a hidden multiple select field with options when new options are selected / removed.

Example, click "Autocomplete" on the left of: https://sharlaan.github.io/material-ui-superselectfield/

In addition to our regular donation, @YourLabs is willing to make a one-time donation of 1000$ for this component, plus another 1000$ for ajax support to fetch options from an API.

**Comment by Dogfalo** [comment]
Hey @jpic,
Thanks for the continued sponsorship. This does seem like it would be helpful to have. We'll have to do some work to rework autocomplete so that it can handle both Dropdowns as well as multi selects. 

What are you imagining for the Ajax support? Let me know what you think of the below:

A url option that takes either a url string or a function.

URL string  (One time ajax call to populate autocomplete data):
```JavaScript
url: 'api/countries.json'
``` 

Function (A different response is received depending on the search phrase):
```JavaScript
url: function(phrase) {
  return "api/countries?phrase=" + phrase;
},
```

**Comment by jpic** [comment]
This possibility works, but i think is just an implementation detail. Also, we can leverage OOP and consider that users could extend the autocomplete class if they want to change the default url generation method ? Honnestly I don't mind, let your creativity guide you :)

Anything will work for me really as long as it maintains a hidden select and looks material. Here's what my own past work looks like:

- to make a text input autocomplete : https://github.com/yourlabs/jquery-autocomplete-light/blob/master/src/autocomplete.js
- to maintain a hidden multiple select : https://github.com/yourlabs/jquery-autocomplete-light/blob/master/src/widget.js

**Comment by btecu** [comment]
It doesn't seem like Autocomplete should be concerned with data retrieval. It should provide useful hooks so that the developer can debounce or fetch data when needed.

**Comment by jpic** [comment]
Ok, we can do with a custom script on chips.

Thanks, keep up the great work !

**Comment by ugoQ** [comment]
> Ok, we can do with a custom script on chips.
> 
> Thanks, keep up the great work !

Hi,
Do you mind to share the script (or the tips) to adapt the chips system with a multiple select ?

Thanks in advance !
