### ISSUE TITLE
Native RTL support

### ISSUE THREAD

**Issue by Nefcanto** [Dogfalo/materialize#5851]
Hi guys

I read through your guidelines and I found nothing regarding "feature request". Thus I decided to write it as simple as possible.

Could you please support RTL out of the box?

There are some RTL forks for your repo, but they are old and are not well maintained.

RTL support for example means that in small devices, the menu icon (hamburger button) appears on the right side of the screen and the drawer is opened from the right panel left-wards.

**Comment by ray007** [comment]
Why not leave it open as feature request for post 1.0?
