### ISSUE TITLE
Could you please update your npm package? 

### ISSUE THREAD

**Issue by DorianLovera** [Dogfalo/materialize#5852]
Could you please update your npm package? 
It will save everyone's time 😄

**Comment by Dogfalo** [comment]
What do you mean? You want a new release or you want us to stop using the `next` tag on releases?

**Comment by DorianLovera** [comment]
I don't know but after "npm install materialize-css" some functions were not supported. I installed materialize.js by downloading from your documentation and everything worked fine I suppose that it was not the last version on npm?

**Comment by Dogfalo** [comment]
This is currently the npm command that should be shown in the documentation on http://materializecss.com/getting-started.html. The next tag will be removed when 1.0 goes out of beta.

`npm install materialize-css@next`
