### ISSUE TITLE
Datepicker not showed inside a modal

### ISSUE THREAD

**Issue by CyberMike97** [Dogfalo/materialize#5854]
I have a modal with some fields and one of this is a date field. When i try to open the datepicker, the picker background is transparent and the content is invisible, but the modal itself is created.
The datepicker works great outside the modal.

**Comment by alexwbaumann** [comment]
Here is a [CodePen](https://codepen.io/anon/pen/vjGaWr) that shows this working. This CodePen uses v1.0.0-beta. So if you are using this version, it should be working. Check your code to ensure everything is being initialized, HTML is structured properly, and your modal is not positioned above the datepicker.

**Comment by Dogfalo** [comment]
It is also preferable to use the container option to allow the datepicker to show outside of the small modal
