### ISSUE TITLE
feature request: simply inline-lists, multilevel menu, ajax modal

### ISSUE THREAD

**Issue by Dontorpedo** [Dogfalo/materialize#586]
Hi,
i like your framework very much but i miss some things with are standard in other frameworks.
it would be good to have just simple inline-lists, possibility for multivel menu and a ajax modal. that would be really great..

regards

**Comment by acburst** [comment]
Please be more specific. Maybe give more examples or details about what you are suggesting. There are a lot of feature request issues and if they are more in depth and well thought out, its easier for us to address them.

**Comment by Dogfalo** [comment]
Why can you not currently achieve an ajax modal?

**Comment by Dontorpedo** [comment]
so, ok.

I have converted one of my projects from zurb foundation to materialize, all worked well but i have seen that i miss some of the functions from zurb like a simple inline list (just a horizontal list)

inline-lists:
http://foundation.zurb.com/docs/components/inline_lists.html

than a multilevel dropdown menu:
with materialize navigation it's only possible to make onelevel dropdown 
but many sites have more then one level in the menu, so i thought it would be important to provide the possibility of multilevel navigation or something.

ajax modal:

i like the way your modals work but i miss (ok this is something i need for my own, but i think it would be a good component) something like firing a  modal with ajax content..

like in zurbs framework:
<a href="http://some-url" data-reveal-id="myModal" data-reveal-ajax="true">
    Click Me For A Modal
</a>


sorry for my bad english :S

**Comment by Dogfalo** [comment]
We can add an inline list, but an ajax modal can just be achieved through a regular modal?

**Comment by Dontorpedo** [comment]
ok thanks, i found a workaround

**Comment by bkrajendra** [comment]
Then please share with us..

**Comment by zeeshanjan82** [comment]
Is the inline list available?

**Comment by sajjadhossain** [comment]
/* Inline List */
.inline li{
    display: inline;
    list-style-type: none;
    padding-right: 20px;
}

**Comment by openface** [comment]
In case it's not clear to newcomers how to setup the initial modal content, and populate it with AJAX content, here is what's working for me:

```javascript
<div id="some_modal" class="modal modal-fixed-footer">
  <div class="modal-content"></div>
</div>

<script>
$(document).ready(function() {
        $('.some_modal_trigger').click(function() {
                $.get("/path/to/ajax/content", function(data) {
                        $('#some_modal .modal-content').html(data);
                        $('#some_modal').openModal();
                });
        });
});
</script>
```
