### ISSUE TITLE
Autocomplete dropdown strange behavior Materialize version 1.0 beta

### ISSUE THREAD

**Issue by MicheleLucini** [Dogfalo/materialize#5861]
I have an autocomplete with minimum number of characters before autocomplete starts set at 0 and on focus the dropdown doesn't appear, or appear for a fraction of a second before disappearing. 

## Expected Behavior
The autocomplete dropdown should appear right away on focus since the number of chars before autocomplete start is set at 0.

## Steps to Reproduce (for bugs)
[Codepen example.](https://codepen.io/Aozora/pen/JvKMGp)

## Your Environment
Happens both on chrome and firefox (both last version).

Sorry for my poor english.

**Comment by acburst** [comment]
Fixed in 25f7b21f
