### ISSUE TITLE
materialize select does not work in my symfony4 project

### ISSUE THREAD

**Issue by valdanioDanio** [Dogfalo/materialize#5863]
this is my code 

<div class="input-field col s12">
                        <select>
                            <option value="" disabled selected>Choose your option</option>
                            <option value="1">Option 1</option>
                            <option value="2">Option 2</option>
                            <option value="3">Option 3</option>
                        </select>
                        <label>Materialize Select</label>
</div>

$(document).ready(function () {
    $('select').material_select();
});

**Comment by Dogfalo** [comment]
`material_select()` was renamed to `formSelect()` in the newest version

**Comment by valdanioDanio** [comment]
Iven like that does not works.

**Comment by Dogfalo** [comment]
Please read over contributing guidelines and add the necessary information

**Comment by valdanioDanio** [comment]
Ok.
