### ISSUE TITLE
Classes when deselecting items in multi select

### ISSUE THREAD

**Issue by alexwbaumann** [Dogfalo/materialize#5869]
When selecting options in a multi select, the classes selected and active are added to the list items. If I select an item, then deselect the item, the selected class remains until I close the multi select then reopen it. If I deselect an option that was automatically selected, the active class is added to that option and stays there even after closing and reopening the multi select.

## Expected Behavior
Once I deselect an item, I'd expect the selected class to be removed.
After closing and reopening the multi select, I'd think that the active class would be removed.

## Current Behavior
The selected class is only removed once the multi select is re-opened. 
The active class remains on a list item until it is clicked again.

## Possible Solution
Not too familiar with everything, but maybe at the end of _activateOption we call _setSelectedStates in select.js? Then maybe during close() in dropdown.js, we remove all of the active classes.

## Steps to Reproduce (for bugs)
I've created this [CodePen](https://codepen.io/anon/pen/gzLvYN). The select on the left is all of the standard styles. Then on the right, I tried to make it so all of the styles could easily be seen.

## Context
While deselecting an item correctly makes the checkmark disappear, the highlight provided by the CSS sticking around is odd. 

## Your Environment
* Version used: 1.0.0-beta

**Comment by Dogfalo** [comment]
Fixed in 42a8bbc0ca7f0bea7bbecdca7acac4c27f15f5cf
