### ISSUE TITLE
issue: material box doesnt work

### ISSUE THREAD

**Issue by Dontorpedo** [Dogfalo/materialize#587]
Hi there, it seems that the material box doesnt work at my page, i dont know what i am doing wrong, i tried it with and without initializing, but it simply doenst work. the image class changes to "materialboxed initialized" but on click it opens like there is no lightbox

**Comment by RaSeR** [comment]
Show us what are you doing.

**Comment by Dontorpedo** [comment]
at first i added the materialboxed class to the image, and added the initialization code  "$('.materialboxed').materialbox();" but it doesnt work..

here you can see it (its my testpage) :

http://demo4.shopthemes.at/product_info.php?products_id=1

**Comment by RaSeR** [comment]
Its work with me. Chrome 40

**Comment by Dontorpedo** [comment]
yes, i found the error, i had the image in a "a" tag, didnt know it is not possible to do that.. sorry

**Comment by RaSeR** [comment]
It's ok)) Close issue))

**Comment by apudiu** [comment]
@RaSeR Nope..! this is an issue, The image should open inside `a` tags, nearly 50% of the time our images resides inside `a` tag

So Please continue to solve this.

My problem is it shows images partially. L( what I can do to fix it?
Check the attachment
![image](https://user-images.githubusercontent.com/22303487/32605783-ff6a5056-c57c-11e7-95c3-295849b103dd.png)
