### ISSUE TITLE
Modal Closing with any click

### ISSUE THREAD

**Issue by lipfreitas** [Dogfalo/materialize#5870]
I'm having a problem with modals, it closes on any click, even inside the modal

` <div id="enviar-modal" class="modal">
                                    <div class="modal-content">
                                      <h4>Enviar Email</h4>
                                        <div class="row">
                                         <div class="input-field col s12 m6">
                                            <input id="email-send" value="${email}" type="text">
                                            <label class="active" for="email-send">Email para envio</label>
                                        </div>
                                        <div class="input-field col s12 m6">
                                            <input id="subject" value="[Boleto ABCFARMA]" type="text">
                                            <label class="active" for="subject">Assunto</label>
                                        </div>
                                        <div class="input-field col s12 m6">
                                            <input id="anexo-link" value="${attach}" type="text" readonly>
                                            <label class="active" for="anexo-link">Link Boleto</label>
                                        </div>
                                        </div>
                                         <div class="row">
                                            <form class="col s12">
                                              <div class="row">
                                                <div class="input-field col s12">
                                                  <textarea id="texto" class="materialize-textarea"></textarea>
                                                  <label for="texto">Conteúdo do Email</label>
                                                </div>
                                              </div>
                                            </form>
                                          </div>
                                      </div>
                                    <div class="modal-footer">
                                      <a id="send" class="green modal-action modal-close white-text waves-effect waves-green btn-flat">Enviar</a>
                                      <a href="#!" class="red modal-action modal-close white-text waves-effect waves-green btn-flat">Cancelar</a>
                                    </div>
                                  </div>
`

`$('#enviar-modal).modal({ dismissible: false})`

if I click anywhere, even the inputs, modal closes

**Comment by lipfreitas** [comment]
![image](https://user-images.githubusercontent.com/21109081/39381327-1a5d1516-4a38-11e8-8e42-59c74facbda7.png)

isOpen returns true, but it isn't showing

**Comment by Dogfalo** [comment]
Please fork this codepen and recreate your issue: https://codepen.io/Dogfalo/pen/qYqWOQ

**Comment by lipfreitas** [comment]
On codepen worked, must be something wrong with my environment

Thx
