### ISSUE TITLE
Page slows when opening modal with form inside

### ISSUE THREAD

**Issue by corybolles** [Dogfalo/materialize#5876]
Not sure if this is specific to my scenario or not. I'm experiencing significant slowdowns of web pages when I open a modal that has a form in it. The page, other than that, includes no images and the form itself is just a form with the materialize classes.

Scrolling, selecting inputs, etc. becomes very slow, but once the modal is closed it resumes to normal speeds.

## Steps to Reproduce (for bugs)
Put a form inside a modal.

## Context
Part of an in-house CRM-esque system we are using. The form is used to add new leads to the database and submits to an external file for processing. (it DOES use Ajax, but the issue happens before submit as well)

## Your Environment
* Version used: 1.0.0
* Browser Name and version: Chrome 66.0.3359.139
* Operating System and version (desktop or mobile): Windows 10, most current updates

**Comment by alexwbaumann** [comment]
[CodePen](https://codepen.io/anon/pen/aGJwPg) with simple form in modal, no issue. Can you create or modify the mentioned CodePen to where it experiences the issue?

**Comment by Dogfalo** [comment]
I don't think I'm experiencing this issue, at least not to the extent that you are. I have a few suggestions of things you could try:
`M.Modal.init(elem, {preventScrolling: false});`
This will prevent page reflow on body and could help performance.

`backface-visibility: hidden;`
Add to `.modal` maybe will also help with transition performance.

I see slight slowdown during animation, but don't see the slow scroll performance you describe.

**Comment by corybolles** [comment]
Okay, thanks for the suggestions. If it's not an issue for everyone I'll go ahead and move the question over to SO if I can't figure out what's going on. Thanks!

**Comment by pirex360** [comment]
Still the transition animation for the modal is slow... any fix ? the .modal css backface-visibility: hidden; dont help reducing the slowliness.
