### ISSUE TITLE
Datepicker autoClose doesnt work

### ISSUE THREAD

**Issue by dokuzbir** [Dogfalo/materialize#5879]
## Current Behavior
When select a date picker doesnt close automatically.

## Steps to Reproduce (for bugs)

https://codepen.io/anon/pen/qYrLBE

```
var elem = document.querySelector('.datepicker');
var options = {autoClose: true, format: "dd-mm-yyyy"};
var instance = M.Datepicker.init(elem,options);
```

**Comment by Dogfalo** [comment]
It will be working in the release coming out today, it was added after the last beta release.

**Comment by tdbs** [comment]
This is still happening on 1.0.0

**Comment by axettone** [comment]
Still happening on 1.0.0... bump! 👍

**Comment by 007amitgarg** [comment]
Auto Close is still not working!!

**Comment by Darkmift** [comment]
I love this framework but properly applying datepicker logic is extremly frustrating as its not registering events properly at all.

autoclose, datechange do notworks as documented

**Comment by Nick-Riggs** [comment]
Do any of the events work? I don't think options are being applied at all to DatePicker.

**Comment by Nick-Riggs** [comment]
This issues should be reopened. 

'this' in `_handleClick`: https://github.com/Dogfalo/materialize/blob/1122efadad8f1433d404696f7613e3cc13fb83a4/js/datepicker.js#L818

Doesn't seem to be the same instance that is initialized here: https://github.com/Dogfalo/materialize/blob/v1-dev/js/datepicker.js#L120

At least the options are completely different in the handler. `this.options` in the handler seem to be the default options even tho the options passed in seemed to be applied correctly in the constructor.

**Comment by Nick-Riggs** [comment]
Alright, I decided I would create a PR to fix this and figured out I didn't need to. I think the issue is that `npm` has a broken build. It needs to be updated. If you change your package.json to reference the 1.0.0 tag in github, it will work: `"materialize-css": "github:dogfalo/materialize#1.0.0",`
