### ISSUE TITLE
Features request: a lot of good stuff

### ISSUE THREAD

**Issue by RaSeR** [Dogfalo/materialize#588]
I'm very excited in material design and im making a good website with your framework, but a lot of stuff still not added to materialize. Here is a links on what we, i think, should do, cause Material Design concept having it:
- Bottom Sheets
  - https://www.google.com/design/spec/components/bottom-sheets.html
  - https://material.angularjs.org/#/demo/material.components.bottomSheet
- Lists
  - https://www.google.com/design/spec/components/lists.html
  - http://ui.lumapps.com/css/lists
- SubHeaders
  - https://www.google.com/design/spec/components/subheaders.html
  - https://material.angularjs.org/#/demo/material.components.subheader
- Switch
  - https://www.google.com/design/spec/components/switches.html
  - https://material.angularjs.org/#/demo/material.components.switch

There are many another stuff that i think should be done, but its about web components, not really about Material Design components.

I've already done list component for my project, but its not rly so good to make pull request))

And i think that required libraries like velocity and etc, should not be added inside framework, but bower requirments.

**Comment by KoltonG** [comment]
+1 for Switches!

**Comment by alexjp** [comment]
Can i add a DateTime picker ?
Something like : http://simeonc.github.io/md-date-time/ ( has date and time )

**Comment by Dogfalo** [comment]
Switches added, Subheaders exist, Lists exist as "collections"
