### ISSUE TITLE
https for docs

### ISSUE THREAD

**Issue by DanielRuf** [Dogfalo/materialize#5882]
GitHub now supports https for custom domains (which was previously only possible with Cloudflare and other solutions):

https://blog.github.com/2018-05-01-github-pages-custom-domains-https/

**Comment by Dogfalo** [comment]
We're in the process of adding it now. Currently waiting on this step:
```
Not yet available for your site because the certificate has not finished being issued 
```

**Comment by Dogfalo** [comment]
Certificate has been issued and https is now enforced!
