### ISSUE TITLE
Don't open Modal in new window

### ISSUE THREAD

**Issue by vibingopal** [Dogfalo/materialize#5899]
Hi Team,

I am trying to implement an existing feature where on click of card it will expand with more data and have the ability to close the same once the card is expanded.

Ex: https://tympanus.net/Development/AnimatedGridLayout/ 

Now i tried an approach where on click of card a modal will be opened with data.But i donot want to open the modal in a new window i just want to expand my card in the same page instead of showing modal as pop up .Any ideas?

**Comment by Dogfalo** [comment]
It's just a matter of perspective mainly. If you remove the box-shadow and overlay color, then it will seem as if the card has opened in the same area

**Comment by vibingopal** [comment]
Thanks for the response. I tried removing box shadow from the modal but still on click of card, modal is getting opened in window . Can you provide me an example?

**Comment by acburst** [comment]
This is more of a specific usecase / customization which is not really appropriate as an issue. You can try stackoverflow or gitter.
