### ISSUE TITLE
Dismissing toasts crashing framework

### ISSUE THREAD

**Issue by kasperrt** [Dogfalo/materialize#5903]
When trying to dismiss toasts, sometimes this crashes the framework, stopping all further operations from it, forcing the client to do a page-reload to get it to work again.

## Expected Behavior
Toasts to be dismissed

## Current Behavior
Whole materializecss framework crashing on dismissing too many toasts/or dismissing too often.

Chrome error
```
Uncaught TypeError: Cannot read property 'removeChild' of null
    at Object.complete (materialize.min.js:6)
    at o (materialize.min.js:6)
    at r (materialize.min.js:6)
    at Object.D.v.tick (materialize.min.js:6)
    at e (materialize.min.js:6)
```

Firefox error
```
TypeError: t.el.parentNode is null[Learn More]
materialize.min.js:6:74966
complete
https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0-beta/js/materialize.min.js:6:74966
o
https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0-beta/js/materialize.min.js:6:25634
r
https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0-beta/js/materialize.min.js:6:26182
D/v.tick
https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0-beta/js/materialize.min.js:6:26558
e
https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0-beta/js/materialize.min.js:6:29747
```

## Steps to Reproduce (for bugs)

1. Run this code in the console 
```
for(var i = 0; i < 3; i++) {
    var toast = document.querySelector(".toast");
    if(toast != null) {
    var instance = M.Toast.getInstance(toast);
        if(instance.timeRemaining > 0) {
            instance.dismiss();
        }
    }
    M.toast({html: "testing", displayLength: 4000})
}
```
or this
```
for(var i = 0; i < 3; i++) {
    M.Toast.dismissAll();
    M.toast({html: "testing", displayLength: 4000})
}
```

## Context

I'm trying to just keep one toast at screen at any given time following the material.io (https://material.io/guidelines/components/snackbars-toasts.html#snackbars-toasts-usage) guidelines.

## Your Environment

* Version used: 1.0.0-beta and 1.0.0-rc.1
* Browser Name and version: Chrome 66.0.3359.139 and Firefox 59.0.2
* Operating System and version (desktop or mobile): desktop and mobile

**Comment by kasperrt** [comment]
As stated in https://github.com/Dogfalo/materialize/issues/5809 that it is fixed in <a href="ff6f9fb">https://github.com/Dogfalo/materialize/commit/ff6f9fbd8ecd399a409f2ab9e59c4b1b303fd91c</a>, it still persists in 1.0.0-rc.1

**Comment by Dogfalo** [comment]
I was able to run that code on materializecss.com without problems.

**Comment by kasperrt** [comment]
Seems it was fixed after all, I'll close the issue.
