### ISSUE TITLE
Tooltip methods not working except destroy

### ISSUE THREAD

**Issue by MAProsper** [Dogfalo/materialize#5908]
`const tooltip = M.Tooltip.getInstance(document.querySelector('.tooltipped'));`

## Expected Behavior
When there's no open Tooltip, calling the following method should display the Tooltip:
`tooltip.open();`

When there's a open Tooltip, calling the following method should hide the Tooltip:
`tooltip.close();`

## Current Behavior
Both methods act as the weren't called at all and also freeze the object, not reacting to a normal hover interaction. When the hover is finished and rehovering for a second time, the normal hover trigger responds again.

## Steps to Reproduce

1. Access [https://materializecss.com/tooltips.html](url).
2. `const tooltip = M.Tooltip.getInstance(document.querySelector('.tooltipped'));`
3. `tooltip.open()` will not respond and also freeze the object.
4. Hover the element with the mouse (or touch it in mobile), it will not respond.
5. Hover a second time, now it's working again.

## Context
I was adding a timeout on a `touchend` event, to close it on mobile after a while (as #963 suggested).

## Environment
* Version used: v1.0.0-beta
* Browser Name and version: Chrome 66.0.3359.139 and 66.0.3359.158 (Build oficial) (64 bits) 
* Operating System and version: Windows 10 Home, 1803; Android, 8.1

**Comment by acburst** [comment]
Fixed in 47a6037e
