### ISSUE TITLE
focus issue w/ input texts on angularjs

### ISSUE THREAD

**Issue by lightshire** [Dogfalo/materialize#591]
```html
<div class="input-field">
         <input name="state" id="state" type="text" class="validate" ng-model="user.state">
         <label for="state">State / Province</label>
 </div>
```

this apparent field when pre-filled with scope data overlaps with the current label. trying to trigger the `.focus()` won't do anything. The only way you can trigger a change would be focusing the input with the keyboard itself.

Any work around with this?

**Comment by lightshire** [comment]
#GMG

**Comment by Dogfalo** [comment]
When prefilling data in angular you have to also change the class="active" for the label
