### ISSUE TITLE
v1, how can I focus a select field?

### ISSUE THREAD

**Issue by minhna** [Dogfalo/materialize#5916]
I'm using version 1.0.0-rc.1, I used `.focus()` to focus the field but it doesn't work.

**Comment by alexwbaumann** [comment]
It's not clear what your tried or your exact goal. Here is a [CodePen](https://codepen.io/anon/pen/bMjaxv) that will hopefully help you. I put some comments into the JS area to which you'll want to pay attention.

**Comment by judasane** [comment]
It is not an issue, but a question about how to code, so it should be on stackoverflow, not here #

**Comment by acburst** [comment]
Personally I don't like overwriting built in functions so I don't think we will implement this. A couple extra lines shouldn't be too bad
