### ISSUE TITLE
MS edge icon bug

### ISSUE THREAD

**Issue by bfss** [Dogfalo/materialize#5917]
I used the materializecss icon in my website:
bfss.github.io
The bug is that the icon can't show, instead , it showed the text.
For example, I have used the app icon, it showed 'app'

My edge vresion is Microsoft Edge 42.17134.1.0, Microsoft EdgeHTML 17.17134.

Thanks for your work.

**Comment by MAProsper** [comment]
`app` doesn't seem to be an icon in the [Material Icons](https://material.io/tools/icons/) font, search for icons on the website and copy the correct code.

Make sure you imported the font by placing the following in the `head`:
`<link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">`

Also check if you encapsulated the icon ID as follows (e.g. for ID: apps).
`<i class="material-icons">apps</i>`

**Comment by bfss** [comment]
emmm....
I followed what you said, but nothing changed.
The icon works well in chrome, ie and firefox, except edge.
If possible, you could use edge to access [https://bfss.github.io/software.html](https://bfss.github.io/software.html) to see it.

**Comment by Dogfalo** [comment]
Open an issue on the google material icons repo
