### ISSUE TITLE
change colored text from default Teal on input[type=text]:focus

### ISSUE THREAD

**Issue by yejodido** [Dogfalo/materialize#592]
I'm able to change the underline color on the animation but not the text color:

input[type=text]:focus{
  border-bottom: 1px solid black;
  box-shadow: 0 1px 0 0 black;
}

**Comment by Dogfalo** [comment]
This is trivial to do in Sass. But we have added more explanation on how to do this in pure CSS.
Added more documentation in ebdce3bee395f1255c57f8a0fde5ac71a59cca3f
