### ISSUE TITLE
[Bug]Medium and Large Sizes for Card Reveal and Cards 

### ISSUE THREAD

**Issue by jett0423** [Dogfalo/materialize#593]
My reveal cards no longer hide additional info. 

I think the issue's more on cropping the image and scaling its height based on each size for the card.

maybe this helps https://github.com/blueimp/JavaScript-Load-Image

![bug](https://cloud.githubusercontent.com/assets/10791201/6004862/f4605ac4-ab40-11e4-8d6d-0c53064b74bc.PNG)
![bug2](https://cloud.githubusercontent.com/assets/10791201/6004863/f495efd6-ab40-11e4-9f02-9cadb8175e01.PNG)

**Comment by acburst** [comment]
Can I see your code? i'm not sure what's going wrong here

**Comment by jett0423** [comment]
<div class="container">
    <div class="section">

      <div class="row">
        <div class="col s12 center">
          <h3><i class="mdi-av-volume-up brown-text"></i></h3>
          <h4>Possible Plenary/Panel Speakers</h4>
        </div>
      </div>

      
      <div class="row">
        
        <div class="col s12 l4">
          <div class="card ">
            <div class="card-image waves-effect waves-block waves-light">
              <img class="activator" src="http://www.slate.com/content/dam/slate/articles/health_and_science/new_scientist/2012/07/120727_NEWSCI_peterhiggsEX.jpg.CROP.rectangle3-large.jpg">
            </div>
            <div class="card-content">
              <span class="card-title activator grey-text text-darken-4">Peter Higgs<i class="mdi-navigation-more-vert right"></i></span>
              <p>British Theoretical Physicist</p>
            </div>
            <div class="card-reveal">
              <span class="card-title grey-text text-darken-4"><b>Peter Higgs</b><i class="mdi-navigation-close right"></i></span>
              <p>Peter Ware Higgs CH FRS FRSE is a British theoretical physicist, Nobel Prize laureate and emeritus professor at the University of Edinburgh.</a></p>
              <p><b>Born:</b> May 29, 1929 (age 85)</p>
              <p><b>Nationality:</b> British</p>
              <p><b>Awards:</b> Nobel Prize in Physics, Hughes Medal, Wolf Prize in Physics, Dirac Medal of the Institute of Physics</p>
              <p><b>Education:</b> Cotham School, King's College London</p>          
            </div>
          </div>
        </div>

        
        <div class="col s12 l4">
          <div class="card medium">
            <div class="card-image waves-effect waves-block waves-light">
              <img class="activator" src="http://upload.wikimedia.org/wikipedia/commons/b/b3/Roger_Penrose-6Nov2005.jpg">
            </div>
            <div class="card-content">
              <span class="card-title activator grey-text text-darken-4">Roger Penrose<i class="mdi-navigation-more-vert right"></i></span>
              <p>English Mathematical Physicist</p>
            </div>
            <div class="card-reveal">
              <span class="card-title grey-text text-darken-4"><b>Roger Penrose</b><i class="mdi-navigation-close right"></i></span>
              <p>English mathematical physicist, mathematician and philosopher of science. He is the Emeritus Rouse Ball Professor of Mathematics at the Mathematical Institute of the University of Oxford, as well as an Emeritus Fellow of Wadham College.</a></p>
              <p><b>Born:</b>August 8, 1931 (age 83)</p>
              <p><b>Nationality:</b> English</p>
              <p><b>Awards:</b>Copley Medal, Royal Medal, Albert Einstein Medal, Wolf Prize in Physics, De Morgan Model, Dirac Medal of the Institute of Physics, Dirac Medal for the Advancement of Theoretical Physics</p>
              <p><b>Education:</b>University College London, University College School, St John's College, Cambridge, University of Cambridge</p>          
            </div>
          </div>
        </div>

        
        <div class="col s12 l4">
          <div class="card medium">
            <div class="card-image waves-effect waves-block waves-light">
              <img class="activator" src="http://mcweb1thumbnails.s3.amazonaws.com/393574-L.jpg">
            </div>
            <div class="card-content">
              <span class="card-title activator grey-text text-darken-4">Evelyn Fox Keller<i class="mdi-navigation-more-vert right"></i></span>
              <p>American Physicist</p>
            </div>
            <div class="card-reveal">
              <span class="card-title grey-text text-darken-4"><b>Evelyn Fox Keller</b><i class="mdi-navigation-close right"></i></span>
              <p>American physicist, author and feminist, Professor Emerita of history and Philosophy of Science at the MIT.</a></p>
              <p><b>Born:</b>August 8, 1931 (age 83)</p>
              <p><b>Nationality:</b> English</p>
              <p><b>Awards:</b>Copley Medal, Royal Medal, Albert Einstein Medal, Wolf Prize in Physics, De Morgan Model, Dirac Medal of the Institute of Physics, Dirac Medal for the Advancement of Theoretical Physics</p>
              <p><b>Education:</b>University College London, University College School, St John's College, Cambridge, University of Cambridge</p>          
            </div>
          </div>
        </div>
      </div>

      
      <div class="row">
        
        <div class="col s12 l4">
          <div class="card">
            <div class="card-image waves-effect waves-block waves-light">
              <img class="activator" src="http://static.eventfinder.co.nz/uploads/events/transformed/272908-146456-7.jpg?v=2">
            </div>
            <div class="card-content">
              <span class="card-title activator grey-text text-darken-4">Peter McLeish<i class="mdi-navigation-more-vert right"></i></span>
              <p>Canadian born, International Multimedia Artist and Scientist</p>
            </div>
            <div class="card-reveal">
              <span class="card-title grey-text text-darken-4"><b>Peter McLeish</b><i class="mdi-navigation-close right"></i></span>
              <p>Canadian born, International Multimedia Artist and Scientist</a></p>
              <p><b>Born:</b> </p>
              <p><b>Nationality:</b> </p>
              <p><b>Awards:</b> </p>
              <p><b>Education:</b> </p>          
            </div>
          </div>
        </div>

        
        <div class="col s12 l4">
          <div class="card">
            <div class="card-image waves-effect waves-block waves-light">
              <img class="activator" src="http://www.puckergallery.com/artists/bak_index/Bak%20Headshot_images.jpg">
            </div>
            <div class="card-content">
              <span class="card-title activator grey-text text-darken-4">Samuel Bak<i class="mdi-navigation-more-vert right"></i></span>
              <p>Jewish painter and writer who survived the Holocaust</p>
            </div>
            <div class="card-reveal">
              <span class="card-title grey-text text-darken-4"><b>Samuel Bak</b><i class="mdi-navigation-close right"></i></span>
              <p>Jewish Painter and Writer, Holocaust Survivor</a></p>
              <p><b>Born:</b> </p>
              <p><b>Nationality:</b>  </p>
              <p><b>Awards:</b> </p>
              <p><b>Education:</b> </p>          
            </div>
          </div>
        </div>

        
        <div class="col s12 l4">
          <div class="card">
            <div class="card-image waves-effect waves-block waves-light">
              <img class="activator" src="http://static.rappler.com/images/12302012ManoloQuezon.JPG">
            </div>
            <div class="card-content">
              <span class="card-title activator grey-text text-darken-4">Manuel Quezon III<i class="mdi-navigation-more-vert right"></i></span>
              <p>Filipino Writer, TV Host and Grandson of President Manuel L. Quezon</p>
            </div>
            <div class="card-reveal">
              <span class="card-title grey-text text-darken-4"><b>Manuel Quezon III</b><i class="mdi-navigation-close right"></i></span>
              <p>Filipino writer, television host and grandson of President Manuel L. Quezon</a></p>
              <p><b>Born:</b> </p>
              <p><b>Nationality:</b> Filipino</p>
              <p><b>Awards:</b> </p>
              <p><b>Education:</b> </p>          
            </div>
          </div>
        </div>
      </div>

      
      <div class="row">

        
        <div class="col s12 l4">
          <div class="card">
            <div class="card-image waves-effect waves-block waves-light">
              <img class="activator" src="http://2.bp.blogspot.com/-u4xf2NeCg4k/UKOTb4nA1mI/AAAAAAAAMsM/TABvU2Q8458/s1600/DSC_6458.JPG" >
            </div>
            <div class="card-content">
              <span class="card-title activator grey-text text-darken-4">Reynabelle Reyes<i class="mdi-navigation-more-vert right"></i></span>
              <p>Ateneo de Manila, Expert on Cosmology and General Relativity</p>
            </div>
            <div class="card-reveal">
              <span class="card-title grey-text text-darken-4"><b>Reynabelle Reyes</b><i class="mdi-navigation-close right"></i></span>
              <p>Ateneo de Manila, Expert on Cosmology and General Relativity</a></p>
              <p><b>Born:</b> </p>
              <p><b>Nationality:</b> Filipino</p>
              <p><b>Awards:</b> </p>
              <p><b>Education:</b> </p>          
            </div>
          </div>
        </div>

        
        <div class="col s12 l4">
          <div class="card">
            <div class="card-image waves-effect waves-block waves-light">
              <img class="activator" src="http://upd.edu.ph/images/chancellor/tsanselor_posadas.jpg">
            </div>
            <div class="card-content">
              <span class="card-title activator grey-text text-darken-4">Roger Posadas<i class="mdi-navigation-more-vert right"></i></span>
              <p>UP, Relativity Physics</p>
            </div>
            <div class="card-reveal">
              <span class="card-title grey-text text-darken-4"><b>Roger Posadas</b><i class="mdi-navigation-close right"></i></span>
              <p>UP, Relativity Physics</a></p>
              <p><b>Born:</b> </p>
              <p><b>Nationality:</b> Filipino</p>
              <p><b>Awards:</b> </p>
              <p><b>Education:</b> </p>          
            </div>
          </div>
        </div>

        
        <div class="col s12 l4">
          <div class="card">
            <div class="card-image waves-effect waves-block waves-light">
              <img class="activator" src="http://mcweb1thumbnails.s3.amazonaws.com/393574-L.jpg">
            </div>
            <div class="card-content">
              <span class="card-title activator grey-text text-darken-4">Gerold Garcia<i class="mdi-navigation-more-vert right"></i></span>
              <p>Ateneo de Manila</p>
            </div>
            <div class="card-reveal">
              <span class="card-title grey-text text-darken-4"><b>Gerold Garcia</b><i class="mdi-navigation-close right"></i></span>
              <p>Ateneo de Manila</a></p>
              <p><b>Born:</b> </p>
              <p><b>Nationality:</b> Filipino</p>
              <p><b>Awards:</b> </p>
              <p><b>Education:</b> </p>          
            </div>
          </div>
        </div>
      </div>

      
      <div class="row">

        
        <div class="col s12 l4">
          <div class="card medium">
            <div class="card-image waves-effect waves-block waves-light">
              <img class="activator" src="http://mcweb1thumbnails.s3.amazonaws.com/393574-L.jpg">
            </div>
            <div class="card-content">
              <span class="card-title activator grey-text text-darken-4">Robert Roleda<i class="mdi-navigation-more-vert right"></i></span>
              <p>DLSU, Expert on Quantum Theory</p>
            </div>
            <div class="card-reveal">
              <span class="card-title grey-text text-darken-4"><b>Robert Roleda</b><i class="mdi-navigation-close right"></i></span>
              <p>DLSU, expert on Quantum Theory</a></p>
              <p><b>Born:</b> </p>
              <p><b>Nationality:</b> </p>
              <p><b>Awards:</b> </p>
              <p><b>Education:</b> </p>          
            </div>
          </div>
        </div>
      </div>

    </div>
  </div>

**Comment by jett0423** [comment]
when I collapse them, they do work. As I implemented them in Roger Penrose and Evelyn Fox Kellers' reveal cards
![bug3](https://cloud.githubusercontent.com/assets/10791201/6005151/070d4d42-ab43-11e4-8138-6e2113658d87.PNG)

**Comment by acburst** [comment]
So what is the problem? They look fine on my computer

**Comment by jett0423** [comment]
the reveal cards are no longer hiding after I updated my materialized.css file. I'm not sure I missed something from the update. It's just the material.css file that's been updated, isn't it?

![bug4](https://cloud.githubusercontent.com/assets/10791201/6005246/bfd149e6-ab43-11e4-965e-3c4fda2b73e1.PNG)

**Comment by acburst** [comment]
Yes, you got the latest version from Github? What browser / OS are you using

**Comment by jett0423** [comment]
I'm using Chrome right now. I'll try internet explorer

**Comment by jett0423** [comment]
Here's a grab from my internet explorer and a clearer view of the issue
![bug5](https://cloud.githubusercontent.com/assets/10791201/6005318/7935bbce-ab44-11e4-84a3-3de0d46cb07c.PNG)

**Comment by jett0423** [comment]
here's my pull command from git too 

![git pull](https://cloud.githubusercontent.com/assets/10791201/6005431/409c62bc-ab45-11e4-8a81-8f1c39fdd822.PNG)

**Comment by acburst** [comment]
Oh right, you need to update your js file as well

**Comment by jett0423** [comment]
zomg! works now. thanks! :) sorry for the trouble!
