### ISSUE TITLE
Failed to Execute "getComputedStyle" on Dropdown for Large Screen Dimension

### ISSUE THREAD

**Issue by CodexLink** [Dogfalo/materialize#5930]
## Introduction
Hi, I'm in the process of recreating my website while in the process of migration from v0.100.2 to v1.0rc.1. After hours of migration process, I have stumble upon dropdown component. This is where the issue starts. The dropdown initialization is fine, meanwhile in the process of executing `getComputedStyle` during dropdown function, is failed.

## Expected Behavior
- The dropdown will show up without any errors.

## Current Behavior
- The dropdown doesn't show up due to failure execution of `getComputedStyle`
- Dropdown does only work on small screen or lets say ranging <999px width. Technically speaking that the dropdown works only on small screens only. While in larger screens, it doesn't work as expected.

## Test Case // Codepen and Website
https://codepen.io/CodexLink/pen/Xqxvzq
https://codexlink.github.io/

### Debug Mode View of CodePen 
https://s.codepen.io/CodexLink/debug/Xqxvzq/NQkzYqOKoOdA

### What area that holds the function?
The problem is on the navbar on the right corner. If you see the bell, then that is the one that holds the dropdown function.

### Description for CodePen
There are two buttons that holds the trigger for dropdown content. One is the bell and one is the center that I have taken from the Materialize Documentation. The Button that I took, is working. And for the bell is not working for larger screens, but except to small screens.

## Reproducing the bug
Just resize your browser width in small dimensions, a width of `999px` with any height value. Hover to the bell both on large and small screen and check the difference.

## Context
The issue affects me the inability to provide incoming people to check for website updates through dropdown list that I can serve. The thing that am trying to accomplish is a notification like dropdown component with hover so that people will know what is currently happening.

## My Environment
* Version used: Materialize Release v1.0.0-rc.1
* Browser Name and version: Chrome 66.0.3359.139
* Operating System and version : Windows 10 64bit Arch, ver1703 (Creators Update)
* Link to your project: https://codexlink.github.io/     // Main Website that has Bug
https://github.com/CodexLink/codexlink.github.io // For File

## Files that affects some Materialize Components
- ColorStyleScheme.css // Custom CSS that Overrides some Materialize Components (Few)
- External_JavaScript/CodexLink_JQ_Dependency_CustomCode.js // JQuery Components
- External_JavaScript/CodexLink_JQ_NonDependency.js // JS Materialize Component Initializers

## Remarks / Note
- I almost have zero knowledge on JavaScript so debugging it by myself is somewhat confusing.
- I have tried initializing the process through console and it's same error shows up. This is the code: `'var dropdown_compatibility = window.getComputedStyle(dropdown_main, null);'`
- The Dropdown is part of AppBar Component.
- The dropdown only works on small screens <999px. (Custom Dimension for Small Device)

## Technical Detail for the Error
```
Uncaught TypeError: Failed to execute 'getComputedStyle' on 'Window': parameter 1 is not of type 'Element'.
    at Object.M.checkPossibleAlignments (materialize_v1rc.1.min.js:6)
    at s.value (materialize_v1rc.1.min.js:6)
    at s.value (materialize_v1rc.1.min.js:6)
    at s.value (materialize_v1rc.1.min.js:6)
    at s.value (materialize_v1rc.1.min.js:6)
```

**Comment by acburst** [comment]
This is a pretty confusing edgecase. So what our dropdown does by default is move the dropdown to right after the dropdown trigger. In this case, it is moving it after the trigger that is hidden on larger screens. The dropdown will not work when it is hidden. 

To fix this you can either try reworking your markup to make sure you only 1 dropdown trigger and it is always visible. 

You could also manually specify the container parameter as the nav-wrapper element. This will override the movement of the dropdown to the specified container element instead.

**Comment by CodexLink** [comment]
Thanks for the reply, I just fixed the issue just now. Reworking and observation is just what I need. Following the format on documentation seems to be great. The process that I did is to make two dropdown content for small and large scale device.
Hence, `web_ver-historical` id raises two ids `web_ver-historical_small` and `web_ver-historical_large`.
Which this concludes that I made two seperate dropdown content both exclusively for small and large scale device.

## Realization
### Warning : Poor Explaination
Although in the process of recreating my work, I found out that using only one dropdown content both for small and large scale device seems that it will likely to fail to calculate or to execute `getComputedStyle` due of complex reasons. Although I can't explain it yet because I don't know how would I said it. But to make clue it seems the 'getComputedStyle' only execute contents on one side-device scale. It cannot compute for both large and small scale, but only one type (large or small) for the content. So in overall, I cannot initiate it both for small and large (because I think it is confusing case and for the function as well), but only for <insert specific device scale> only. Which concludes the raise of two IDs that I stated from above. One for Large Scale and one for Small Scale.

## In reply response
I'm not sure that two button holders for dropdown would interfere from calculating the style. Anyway, specifying `container` class wouldn't resolve the problem I guess, I tried and it doesn't override the movement.

Thank you for reply and I would likely to apologize for constructing poor explanation or statement but I hope you would understand. I will close the issue now since I fixed it.
