### ISSUE TITLE
Uncaught ReferenceError: cash is not defined     at forms.js:275

### ISSUE THREAD

**Issue by lexuspro** [Dogfalo/materialize#5931]
My site uses jQuerty.

I connected the forms.js and cash.js component, but the forms do not work, in the browser console the error is:

`Uncaught ReferenceError: cash is not defined     at forms.js:275`

Please tell me what to do!

**Comment by acburst** [comment]
Do you have any sample code? It would be helpful to narrow down where the problem comes from

**Comment by tomzi** [comment]
Hello, 
I have the same problem but for the file autocomplete.js
![capture d ecran 2018-12-28 a 13 43 31](https://user-images.githubusercontent.com/4091451/50515885-a379de80-0aa7-11e9-9162-c1f79ee34a70.png)

I think the problem comes from the materialize.js.map.
Could you help me please ?

Thanks
