### ISSUE TITLE
Modal has focused background on 1.0.0-beta and 1.0.0-rc1

### ISSUE THREAD

**Issue by Persanix** [Dogfalo/materialize#5934]
After upgrading from 0.1 to 1.0.0-beta, we noticed that all of our modals now have some sort of highlighting around the edges. On Chrome (Version 66.0.3359.139 (Official Build) (64-bit)), this manifests as an orange background. 

![chrome](https://user-images.githubusercontent.com/15693673/40267798-06ee803c-5b31-11e8-9dcc-87fe52de5967.png)

On Firefox (60.0 (64-bit)), this manifests as a dotted border. 

![firefox](https://user-images.githubusercontent.com/15693673/40267801-0faa0e26-5b31-11e8-900e-d5280484ea61.png)

The issue is apparent in the sample modals on the [materializecss website](https://materializecss.com/modals.html).

**Comment by Dogfalo** [comment]
Thanks for upgrading, hope you are liking the new version.

This issue will be fixed in the next release. See https://github.com/Dogfalo/materialize/issues/5927
