### ISSUE TITLE
[Request] - Contributors List

### ISSUE THREAD

**Issue by ConsoleTVs** [Dogfalo/materialize#594]
Hello Alvin or Alan

What do you think about adding a page like a "Thanks" page and put a list of the contributors or the most contributors, i think it's a good idea, what do you think?

**Comment by carloscarcamo** [comment]
+1

**Comment by ConsoleTVs** [comment]
I really consider it a good option...

**Comment by Dogfalo** [comment]
I'll add [this](https://kovshenin.com/2012/how-to-get-a-list-of-contributors-from-a-github-project/) when I have some time

**Comment by carloscarcamo** [comment]
A list of translation contributors would be good too :)

**Comment by ConsoleTVs** [comment]
"A list of translation contributors would be good too :)"

+1 :)

**Comment by tomscholz** [comment]
There are other priorities right now. I will close this issue for now. When we are back on track we will look into it :)
