### ISSUE TITLE
Hovering on Tooltips and then resizing the browser screen cause scrollbar on the body

### ISSUE THREAD

**Issue by atindra** [Dogfalo/materialize#5946]
This behavior can be seen on the materialize site's tooltips page itself.  To replicate the issue, hover on the tooltips first and then resize screen. Horizontal scrollbar will appear.

https://materializecss.com/tooltips.html
![capture](https://user-images.githubusercontent.com/36465695/40594135-3e0bbf1e-61fb-11e8-874a-10ac3cad47b5.PNG)

I had this problem in previous version of materialize as well (0.9) and avoided it by using body { overflow: hidden; } but would like to know if this can be resolved.

**Comment by Dogfalo** [comment]
I can't see resizing the window while opening tooltips as a common issue. If you want you can just dismiss tooltips on resize

**Comment by ntutchton** [comment]
I was seeing this issue on a site with navigation between pages of different widths.  `{ overflow: hidden; }` wasn't an option - I had to destroy tooltips prior to navigation and recreate them after to avoid the horizontal scroll bar while allowing tooltips to persist a browser resize/navigation event.

**Comment by jeicoo** [comment]
Been experiencing this problem. The problem happens when you load the page in a big screen and resizing to a much smaller screen. 

Tooltips retain their original position and will cause the horizontal scrollbar to appear. This breaks the responsiveness of the page.

**Comment by ntutchton** [comment]
Yeah I think it would be worth it to add a resize event listener to open tooltips to prevent this

**Comment by Conrekatsu** [comment]
I had a similar problem, and my issue was I had a div with a max height and the window was also scrollable. the tooltip was moving all over the place so this is what I did.

on the "_repositionWithinScreen" in materialize.js

I changed the old 
```
key: "_repositionWithinScreen",
      value: function _repositionWithinScreen(x, y, width, height) {
        var scrollLeft = M.getDocumentScrollLeft();
        var scrollTop = M.getDocumentScrollTop();
        var newX = x - scrollLeft;
        var newY = y - scrollTop;

        var bounding = {
          left: newX,
          top: newY,
          width: width,
          height: height
        };

        var offset = this.options.margin + this.options.transitionMovement;
        var edges = M.checkWithinContainer(document.body, bounding, offset);

        if (edges.left) {
          newX = offset;
        } else if (edges.right) {
          newX -= newX + width - window.innerWidth;
        }

        if (edges.top) {
          newY = offset;
        } else if (edges.bottom) {
          newY -= newY + height - window.innerHeight;
        }

        return {
          x: newX + scrollLeft,
          y: newY + scrollTop
        };
      }
```
to
```
key: "_repositionWithinScreen",
      value: function _repositionWithinScreen(x, y, width, height) {
        var scrollLeft = M.getDocumentScrollLeft();
        var scrollTop = M.getDocumentScrollTop();
        var origin = this.el;
        var tooltip = this.tooltipEl;
        var newX = x - scrollLeft;
        var newY = y /*- scrollTop*/;
        var targetTop = origin.getBoundingClientRect().top + M.getDocumentScrollTop();
        targetTop += origin.offsetHeight / 2 - tooltip.offsetHeight / 2;

        
        var bounding = {
          left: newX,
          top: newY,
          width: width,
          height: height
        };

        var offset = this.options.margin + this.options.transitionMovement;
        var edges = M.checkWithinContainer(document.body, bounding, offset);

        if (edges.left) {
          newX = offset;
        } else if (edges.right) {
          newX -= newX + width - window.innerWidth;
        }

        if (edges.top) {
          newY = offset + targetTop;
        } else if (edges.bottom) {
          newY -= newY + height - window.innerHeight + targetTop;
        }

        return {
          x: newX + scrollLeft,
          y: newY /*+ scrollTop*/
        };
      }
```
