### ISSUE TITLE
MaterialboxInstance.destroy() does not remove material-placeholder element

### ISSUE THREAD

**Issue by blazer82** [Dogfalo/materialize#5948]
Calling `destroy()` on an instance of Materialbox does not remove the `<div class="material-placeholder">` created by `M.Materialbox.init()`

You can test this by executing the following javascript on https://materializecss.com/media.html

```javascript
document.querySelectorAll('.materialboxed').forEach((e) => { M.Materialbox.getInstance(e).destroy() })
```

**Comment by Dogfalo** [comment]
Fixed in ec8be5d1cee72c71a2118b3cfbf843eb569524ff
