### ISSUE TITLE
Materialise - FastClick - iOS - Cordova

### ISSUE THREAD

**Issue by hgroupetech** [Dogfalo/materialize#5954]
Hi ! I'm using Materialize CSS, JS along with jQuery, jQuery Mobile, for Cordova PhoneGap apps.
If on **Android there is no 300ms** delay issue, well on **iOS thing are way different**.

So to solve the issue well I can use Fastclick.js but that's the thing **radio button** and **checkbox** doesn't work anymore, I can't find out why...

So if anybody have encounter this problem, or maybe have a solution what I can delete or modify anywhere, I'd be greatfull and really happy !

Thanks

**Comment by Dogfalo** [comment]
This seems like something you should raise with fastclick
