### ISSUE TITLE
Triggering two clicks events on checkbox check, radio check, switches component.

### ISSUE THREAD

**Issue by pnikolov** [Dogfalo/materialize#5957]
When checking a checkbox or radio or "switches" **two click events** are fired on the _document_ object. This results in a variety of side effects among various UI controls.

## Expected Behavior

Checking a checkbox, or choosing a radio button, or flipping the "switches" control should fire only **one click event** on the _document_ object.

## Current Behavior

Checking a checkbox, or choosing a radio button, or flipping the "switches" control results in firing *two click events* on the _document_ object.

## Steps to Reproduce (for bugs)

**Simplified example**
1. Attach click even on the _document_ which logs when it is triggered.
2. See the log, on each checkbox / radio / "switches" change it will be fired twice, see the CodePen - https://codepen.io/pnikolov/pen/RJNzmM

How to reproduce a side effect causing *Feature Discovery* (_tapTarget_) to be closed immediately:
1. By Using checkboxes/ radio / "switches" attach an event on "change" to open a _tapTarget_
2. Click the checkbox / radio / "switches", the _tapTarget_ **will be opened and closed immediately** as it listens for document click event to close itself. **So the unexpected second document click event closes the _tapTarget_.**

## Context

It affects _Feature Discovery_ component - as the component adds a document click event listener on the document (clicking somewhere on the page closes the opened _Feature Discovery_), so in the case you want to show feature discovery on checkbox change / "switches" change / radio "change" the effect is that the Feature Discovery is immediately closed after opened. (**not shown at all**).

## Your Environment

* Version used: `1.0.0-rc.1`
* Browser Name and version: `Safari 11.1`, `Firefox 60.0.1`
* Operating System and version (desktop or mobile): `macOS High Sierra`

**Comment by acburst** [comment]
This is actually a browser feature. When you click on a label for any input, the browser will trigger a second click on the input which is what allows it to focus the input when you click it's associated label. This is not something we can control. 

I'd suggest filtering the target of the click event to more accurately capture the click you are looking for.

**Comment by pnikolov** [comment]
I see your point, but actually in the most common case you are listening for *change* event, for example:
```js
$('input[type="checkbox"]').on('change', function() {
    $('.feature').tapTarget('open')
})
```
In this case the tapTarget will be opened and closed immediately, due to the second document click event. I've demonstrated here: https://codepen.io/pnikolov/pen/aKvbpe

You can actually see that this also results in broken "switches" animation state.

Maybe the Feature Discovery _tapTarget_ component should filter the target of the click of at least provide a configuration option to disable this behaviour.
