### ISSUE TITLE
Card Reveal not working with column-count

### ISSUE THREAD

**Issue by seijimaddog** [Dogfalo/materialize#596]
Cards on the right column won't reveal the content when I click it, and won't show the card image if either `.card-image` or `.card-image img` have *position* set to *relative*. If you have `.waves-effect` on `.card-image`, you have to remove `will-change: opacity, transform;`. .

I cannot reproduce any of these problems in Firefox 35.0.1 nor IE 11, only Chrome 40.0 seems to be affected, and only on cards displayed in the right column. 

Can anyone reproduce this problem? 

```html
<div style="-webkit-column-count: 2; -moz-column-count: 2; column-count: 2;">

    <div class="card">
        <div class="card-image waves-effect waves-block waves-light">
            <img src="images/office.jpg">
        </div>
        <div class="card-content">
            <span class="card-title activator grey-text text-darken-4">Card Title <i class="mdi-navigation-more-vert right"></i></span>

            <p><a href="#!" class="activator">This is a link</a>
            </p>
        </div>
        <div class="card-reveal">
            <span class="card-title grey-text text-darken-4">Card Title <i class="mdi-navigation-close right"></i></span>
            <p>Here is some more information about this product that is only revealed once clicked on.</p>
        </div>
    </div>

    <div class="card">
        <div class="card-image waves-effect waves-block waves-light">
            <img src="images/office.jpg">
        </div>
        <div class="card-content">
            <span class="card-title activator grey-text text-darken-4">Card Title <i class="mdi-navigation-more-vert right"></i></span>

            <p><a href="#!" class="activator">This is a link</a>
            </p>
        </div>
        <div class="card-reveal">
            <span class="card-title grey-text text-darken-4">Card Title <i class="mdi-navigation-close right"></i></span>
            <p>Here is some more information about this product that is only revealed once clicked on.</p>
        </div>
    </div>

</div>
```

**Comment by Dogfalo** [comment]
Just wondering, why not use the grid instead of column count?

**Comment by seijimaddog** [comment]
I would have to wrap half the items in a div and do the same to the other half in the server side, while using columns-count this is done client-side, I just wrap everything in a single div on my template file. With column-width set, it will fall back to a single column on phones, so I thought it would be easier to implement.

But yeah, as it may be a bug in Chrome itself, I may end up using the grid system. At least it would have better compatibility with older browsers, I guess (:

**Comment by Dogfalo** [comment]
I'm gonna close this for now. If this is a big problem for people it can be reopened.
