### ISSUE TITLE
Navbar-fixed causes overlay in sidenav

### ISSUE THREAD

**Issue by Antonyselt** [Dogfalo/materialize#5970]
## Expected Behavior
No overlay when using navbar-fixed on sidenav

## Current Behavior
This is the current behavior
![bug](https://user-images.githubusercontent.com/13181287/41055413-e263162e-6986-11e8-9575-1d1d3b81b50e.gif)

## Steps to Reproduce (for bugs)
1. Put a nav inside parallax
2. Use only the side nav o large screens
3. Use class "navbar-fixed"
4. 
![navbar](https://user-images.githubusercontent.com/13181287/41055605-60571616-6987-11e8-913f-804346b43396.png)

## Your Environment
* Version used: Materialize 1.0.0-rc.1 this issue exist in 0.100.2
* Browser Name and version: Google Chrome lastest version
* Operating System and version (desktop or mobile): Windows 10

**Comment by Antonyselt** [comment]
Here is the solution
![code](https://user-images.githubusercontent.com/13181287/41182295-a44ffafe-6b3a-11e8-8e10-2f10156e5466.png)

**Comment by juanhuerta** [comment]
Your solution worked for me, but I don't think it is a final solution, is it? the documentation don't mention nothing about it, I think it is only a workaround.

**Comment by Antonyselt** [comment]
@juanhuerta I believe that happen because side-nav does not take part in parallax. But I asked that question in gitter and they give me this solution and I put it here for others that had the same problem.
