### ISSUE TITLE
input[type=text].validate+label bug

### ISSUE THREAD

**Issue by Computerleiche** [Dogfalo/materialize#5975]
The following input-field causes a horizontal scrollbar to appear:

```
<div class="row">
  <div class="input-field col s6">
    <input class="" id="test1" type="text">
    <label for="test1">Test1</label>
  </div>
  <div class="input-field col s6">
    <input class="validate" id="test2" type="text">
    <label for="test2">Test2</label>
  </div>
</div>
```

https://codepen.io/anon/pen/zaogYP

It comes from the class "validate".
When disabling `width: 100%;` of `input[type=text].validate+label` the scrollbar disappears like as in issue #3018 and #3021. So it's also happening without prefix. What is this 100% for?
It is only happening at the end of a column when it hits the visual border. 

* Version used: 1.0.0-beta and 1.0.0-rc.1

**Comment by acburst** [comment]
When combining the grid divs and other components, unexpected things happen. Try this:

```
<div class="row">
  <div class="col s6">
    <div class="input-field">
      <input class="" id="test1" type="text">
      <label for="test1">Test1</label>
    </div>
  </div>
 
  <div class="col s6">
    <div class="input-field">
      <input class="validate" id="test2" type="text">
      <label for="test2">Test2</label>
    </div>
  </div>
</div>
```

**Comment by Computerleiche** [comment]
The combination of `col` and `input-field` really was the problem.
Maybe it was one pixel too much because of rounding up and the `label` was 100% of its parent.
The `row` has a width of x.y px and a `col` has a.b px. When y and  is bigger or equal 5 maybe it's rounded up. This causes two `col`s being 1 px widther than 1 `row`. Because of there padding it doesn't matter. An `input-field` inside a `col` just pushes inside the padding so it also doesn't matter.
