### ISSUE TITLE
Carousel.next() does not stop on last Element

### ISSUE THREAD

**Issue by Unrealrussian** [Dogfalo/materialize#5977]
[CodePen Example](https://codepen.io/anon/pen/dKNrJV)

When invoking .next() function on an instance of Carousell with the nowrap option set to true on the last picture scrolls to an empty space
## Expected Behavior

When invoking function on last picture there should be no movements at all, like the .prev() function

## Current Behavior

Scrolls further into an empty space

## Possible Solution

Testing for the right index failed at some point

## Steps to Reproduce

1. create a carousel with nowrap enabled
2. invoke .next() function in some way on last picture
3. ...
4. Profit

## Your Environment

* Browser Name and version: Mozilla Firefox v60.0.2
* Operating System and version (desktop or mobile): Desktop

**Comment by acburst** [comment]
Fixed in d6837988.

Thanks for pointing this out!
