### ISSUE TITLE
Pushpin Overlapping [IE11]

### ISSUE THREAD

**Issue by janfriedli** [Dogfalo/materialize#5979]
## Expected Behavior
When I use the IE11 and scroll down and then back to the top of the page, the pushpin menu on the right doesn't go back to its initial position. 

## Current Behavior
The  fixed table of contents on the right doesn't stop at its top position. It overlaps with the objects on top of it.

![screen shot 2018-06-11 at 21 45 06](https://user-images.githubusercontent.com/7932500/41253895-02d0735e-6dc2-11e8-849e-2c69b5f89d28.png)
## Steps to Reproduce (for bugs)

1. Open https://materializecss.com/pushpin.html with IE11
2. Scroll down
3. Scroll back to the top

## Context
I'm trying to use this feature in combination with IE11.

## Your Environment

* Version used: 1.0.0.-rc.1
* Browser Name and version: IE11
* Operating System and version (desktop or mobile): Win 8.1 (Virtual Box)

**Comment by acburst** [comment]
Good catch. Fixed in f8419cce

**Comment by janfriedli** [comment]
thx 👍
