### ISSUE TITLE
Select change is trigger when value is not changed

### ISSUE THREAD

**Issue by quienti** [Dogfalo/materialize#5981]
If you look here : https://codepen.io/anon/pen/qKXjMB

## Expected Behavior

In materialize select, if I select a value already selected, the change event is trigger.
But, if I use an classic select, if I select a value already selected, the change event is not trigger

## Current Behavior

- When a value is already selected, and when we click on the same value, event change is trigger

## Current Behavior

- When a value is already selected, and when we click on the same value, event change is trigger

## Steps to Reproduce (for bugs)
1. Click on option 1 on the materialize select in my codepen
2. An alert is show
1. Click on option 1 on the basic select in my codepen
2. An alert is not show

## Your Environment
* Version used: Materialize 1.0.0-rc1
* jQuery version used: 3.3.1
* Browser Name and version: Firefox
* Operating System and version (desktop or mobile): Windows 10
* Link to your project (if appropriate):

**Comment by acburst** [comment]
Good catch.

Fixed in 1fff8142
