### ISSUE TITLE
Tooltip on mobile

### ISSUE THREAD

**Issue by eliteSchwein** [Dogfalo/materialize#5984]
Hey when you use tooltip, on the mobile device, it will show but never remove. And i have a solution for that:

Just add:

@media (pointer:none), (pointer:coarse) {
   .material-tooltip{ 
        z-index:0; 
        width:0px;
        height: 0px; 
        left:-100000000px; 
        position: fixed; 
        padding:0px; 
    } 
}

I hope this code will be implementet to the materialze.css file...

**Comment by robertguetzkow** [comment]
That seems like a rather crude fix. It's better to toggle the tooltip visibility when the mouse leaves the control or when it is pressed. However I agree that this should be fixed since currently the tooltips don't disappear, even when the control is no longer in focus.
`var tooltipped = $('.tooltipped');

    tooltipped.mousedown(function(){
        $('.material-tooltip').css("visibility", "hidden");
    });

    tooltipped.mouseleave(function(){
        $('.material-tooltip').css("visibility", "hidden");
    });`

**Comment by robertguetzkow** [comment]
It seemed like there was a bug in the auto initialization at first, since I witnessed the described behavior as well. For some reasons it works now, but I'll have to check what changes made a difference.

**Comment by Dogfalo** [comment]
It is a problem with mobile and how mouseleave works on it. We'll need a mobile threshold to add different behavior for touch devices.

**Comment by mozfet** [comment]
The demo does not work on iOS using Safari. No tooltips are showing on https://materializecss.com/tooltips.html#! when hovering over the buttons... after a while, an iOS 'open link' popup appears to open the link in another window, but alas no tooltips.
