### ISSUE TITLE
Date picker month name cut off

### ISSUE THREAD

**Issue by robertguetzkow** [Dogfalo/materialize#6002]
## Expected Behavior
The month name should be displayed along-side of the year with enough space and padding.

## Current Behavior
The month name is currently cut off because it is overlapping with the year.

## Possible Solution
The width could be increased to 100% (or another relative size) of the parent.  A fixed width is generally undesirable because it hinders support for other languages.

```
.datepicker-controls .select-month input {
  width: 100%;
}
```

## Steps to Reproduce (for bugs)
https://codepen.io/TheHole/pen/eKKoEz

## Context
The context is a simple form that requires date selection.

## Your Environment
* Version used: 1.00 rc2

**Comment by drewrwilson** [comment]
I've updated from `v1.0.0-rc1` to `v1.0.0` and the end of the month is still being cut off for September and other months. 

![image](https://user-images.githubusercontent.com/4324656/53517695-1b528e00-3a84-11e9-8f68-10917a3e5600.png)

Any advice?

**Comment by robertguetzkow** [comment]
@drewrwilson I haven't been keeping track of the development, so I'm not sure if there's been a regression in the code. What you could do to fix this yourself is edit the scss and manually patch with either my quick and dirty suggestion from above or the fix suggested by @hnordberg.

**Comment by drewrwilson** [comment]
@robertguetzkow thanks for the help. hmm it didn't work for me. I added those two css lines to the end of my `materialize.min.css` and `materialize.css` files and it appears to be the same problem... hmmm

**Comment by drewrwilson** [comment]
@robertguetzkow but your css did! 🎉 🎉 🎉 🎉

**Comment by robertguetzkow** [comment]
@drewrwilson Glad it worked. The clean way of doing the modification is to edit the [_datepicker.scss](https://github.com/Dogfalo/materialize/blob/47b53e908413755b30eb60bec616ef64be85b821/sass/components/_datepicker.scss#L44) and compile it to the css file using a [SASS](https://sass-lang.com/) compiler.

**Comment by roman02** [comment]
Is this going to be fixed by the team?
