### ISSUE TITLE
Swipeable Tabs not working

### ISSUE THREAD

**Issue by TheBusyBiscuit** [Dogfalo/materialize#6006]
Tabs that have been initialized with the options:
{
  swipeable : true
}
do no longer work and throw an error right away.

I have included a codepen, try switching swipeable to false and back, you will see that it only breaks when it's set to true.
By "breaking" I mean that it behaves like a normal list of elements and also no longer features the white selection bar beneath the tab element.
Nor does swiping work at all.

Codepen: https://codepen.io/thebusybiscuit/pen/zaJpBx
Console Error: https://pastebin.com/F3S7cFum

## Environment
* Version used: 1.0.0-rc.2
* Browser Name and version: Chrome 67
* Operating System and version (desktop or mobile): Windows 10

**Comment by EnzoBaldisserri** [comment]
According to the [documentation](https://materializecss.com/tabs.html), to initialize the tabs, you can either do :

```
// Plain javascript
M.Tabs.init(document.querySelectorAll('.tabs'), { swipeable: true });

// Or with jQuery
$('.tabs').tabs({ swipeable: true });
```

But not combine both !

**Comment by TheBusyBiscuit** [comment]
@EnzoBaldisserri 

Previously I used $(".tabs")[0] to access it as a DOM element, same result.
I also tried $(".tabs").tabs(...) same result.
Also for M.Tabs.init(document.querySelectorAll(".tabs")

I have also just tested each case in the codepen and it still produces the outcome explained in the post.
I have updated to use the pure jQuery version to avoid further confusion.

**Comment by EnzoBaldisserri** [comment]
Ok, I found out there are 2 problems with the CodePen.
First, tabs need a content to be swipeable. Here you just have the tabs, there is actually nothing to swipe. See the [example in the documentation](https://materializecss.com/tabs.html#swipeable).
Second, more related to CodePen than to the code : you put the link to materialize's scripts in the head of your html, and add jQuery in CodePen scripts, which are added at the end of the body of the document.
What's important here is that materialize is loaded before jQuery, thus you aren't able to use jQuery to initialize any of materialize's components.

**Comment by TheBusyBiscuit** [comment]
@EnzoBaldisserri 
 I see.

You are right I set up the codepen in the wrong order, didn't think about that when creating it but my html doc is properly set up.

And yeah, it works when I give it content, it is strange that it doesn't even render or throws an exception that hints at the missing components, but anyway, thank you very much, it works now.
