### ISSUE TITLE
spinning loader in button

### ISSUE THREAD

**Issue by jpic** [Dogfalo/materialize#6017]
It would be great if materialize css could offer a button state with a loader on the side, for user feedback.

At least, provide a smaller spinner because this is ugly: https://jsfiddle.net/tbsgvn6z/

**Comment by storm1er** [comment]
@Dogfalo or @acburst take a look at this (quite old) PR: #4942

**Comment by jpic** [comment]
Thank you so much for your reply, I've seen this and I will follow the material recommendation, blanking the whole form and showing a spinner in the middle :joy:
