### ISSUE TITLE
Updated version, errors in the old plugin

### ISSUE THREAD

**Issue by SilenC** [Dogfalo/materialize#6026]
Hi, everyone. Thanks in advance.

I have been check some webs referring to web development, and I found a "plugin" wich it needs a old version of Materialize, when I try to use with the newer version the console give me an error from a inexistent function (M.throttle). I found the function in the .js archive, but I don't understand where is the problem.
Attached some captures:
![image](https://user-images.githubusercontent.com/21129336/42419562-da5c9174-8274-11e8-9959-1b50d975267b.png)
![image](https://user-images.githubusercontent.com/21129336/42419569-02122b66-8275-11e8-9901-c8df3cad9dd9.png)

And, the plugin call to this function in this  part:
![image](https://user-images.githubusercontent.com/21129336/42420036-f81f92d0-827c-11e8-8d9d-fbb0c1bef439.png)

Can I helpme, please :)

**Comment by acburst** [comment]
If this plugin you are using is a thirdparty plugin we cannot do anything to help. Unless they update it to be compatible with the latest versions, you will have to use whichever old version this plugin supports.
