### ISSUE TITLE
Carousel not working on mobile devices ( 2018 )

### ISSUE THREAD

**Issue by Oyshoboy** [Dogfalo/materialize#6028]
Carousel not working on mobile devices. Even on official documentation page, using chrome dev tools.

Can debug it like:
1) Go to https://materializecss.com/carousel.html
2) Ctrl+Shift+J ( open console )
3) Ctrl + Shift + M ( switch mobile )

**Comment by SilenC** [comment]
It's work for me on my mobile.

**Comment by Oyshoboy** [comment]
Also it's very laggy sometimes. I'm using npm package for Materialize, so , everything works fine, exept of Carousel. It's begin to lag randomly time to time, and when it's lagging - it's become to spin not properly, like something is getting broket, but nothing in developing console. So after refresh - everything is just going fine and fast, untill lags comes ones again...

Here is my code:
```
<div class="carousel coins-carousel">
    <a class="carousel-item" href="" data-coin="1"><img src="/coins.png"></a>
    <a class="carousel-item" href="" data-coin="2"><img src="/coins.png"></a>
    <a class="carousel-item" href="" data-coin="3"><img src="/coins.png"></a>
    <a class="carousel-item" href="" data-coin="4"><img src="/coins.png"></a>
    <a class="carousel-item" href="" data-coin="5"><img src="/coins.png"></a>
    <a class="carousel-item" href="" data-coin="6"><img src="/coins.png"></a>
    <a class="carousel-item" href="" data-coin="7"><img src="/coins.png"></a>
</div>
```

Initializing:
```
$('.carousel').carousel({
        onCycleTo: function(ele, dragged) {
            Session.set('selectedCurr', $('.coins-carousel > .active')[0].dataset.coin);
        }
    });
```

**Comment by orlando-noda** [comment]
@Oyshoboy, your problem is when trying swip image on mobile? I am having the same trouble, but touching on bullets it works. Is it the same problem you have?

**Comment by Oyshoboy** [comment]
It guess yes, carousel is bit unstable, trying to find out reason

**Comment by estefijacobo** [comment]
I reproduced the error on Chrome trying the mobile version of the console and it works just fine. I tested it with a mobile device and it also worked, though it takes longer to load.
