### ISSUE TITLE
Character counter not working in 1.0.0-rc.2

### ISSUE THREAD

**Issue by cheesemarathon** [Dogfalo/materialize#6029]
## Expected Behavior
Should show a character counter after entering a text field. Should check the validity after entering each character.

## Current Behavior
No character counter is shown when using marterialize.min.js version 1.0.0-rc.2 with the example code found [here](https://materializecss.com/text-inputs.html#character-counter)

Validity is never calculated

## Steps to Reproduce (for bugs)
Link to [codepen](https://codepen.io/cheesemarathon/pen/JBjEMe) to reproduce

**Comment by acburst** [comment]
You need to initialize it with javascript. If you scroll down on the docs page you will see it.

**Comment by cheesemarathon** [comment]
Thank you. You may want to change the wording on your website as the current wording makes it seem optional. Only needed if the fields are dynamically added rather than necessary for it to work
