### ISSUE TITLE
Navbar does not display icons nor links

### ISSUE THREAD

**Issue by carlosperate** [Dogfalo/materialize#603]
In the current master (6f158db4ebd977c0eb2f781e6e0b00e8d2fc7a34) the links in the navbar are not displayed. This is a screenshot of the current navbar.html file:

![navbar links](https://cloud.githubusercontent.com/assets/4189262/6027444/20dba6a0-abda-11e4-9682-a4beecbcb4db.png)

**Comment by sahina** [comment]
I observed the same issue.

**Comment by acburst** [comment]
Thanks for pointing this out.

Fixed in 7aaec877830b32b0ee3ed322d2dfe2ee14cafbab

**Comment by carlosperate** [comment]
All fine now, thanks!
