### ISSUE TITLE
Alignment of search icon in navbar

### ISSUE THREAD

**Issue by GermaVinsmoke** [Dogfalo/materialize#6037]
## Expected Behavior

In documentation of version 1.0.0-rc.2, the search icon is properly aligned. So, the icon should be aligned like this.
![image](https://user-images.githubusercontent.com/32815509/42816086-3add4e66-89e7-11e8-8d26-257ea496c702.png)

## Current Behavior

But in Codepen or browser, search icon isn't properly aligned.

![image](https://user-images.githubusercontent.com/32815509/42816355-2ac107ce-89e8-11e8-9d96-bc311a2705d8.png)

## Steps to Reproduce (for bugs)

In `.input-field > label` class -
```
.input-field > label {
  color: #9e9e9e;
  position: absolute;
  top: 0;
  left: 0;
  font-size: 1rem;
  cursor: text;
  -webkit-transition: color .2s ease-out, -webkit-transform .2s ease-out;
  transition: color .2s ease-out, -webkit-transform .2s ease-out;
  transition: transform .2s ease-out, color .2s ease-out;
  transition: transform .2s ease-out, color .2s ease-out, -webkit-transform .2s ease-out;
  -webkit-transform-origin: 0% 100%;
          transform-origin: 0% 100%;
  text-align: initial;
  -webkit-transform: translateY(12px);
          transform: translateY(12px);
}
```

1. Removing these two aligns it properly -
     ```
         -webkit-transform: translateY(12px);
          transform: translateY(12px);
     ```

    ![image](https://user-images.githubusercontent.com/32815509/42816992-49e41afe-89ea-11e8-9e60-217b57d38e5b.png)

2. Using this, aligns it properly - 
      ```
        .input-field label {
            -webkit-transform: translateY(0px) !important;
            transform: translateY(0px) !important;
        }
      ```

3. [Codepen Solution for Proper Alignment of Search Icon in Navbar](https://codepen.io/germavinsmoke/pen/VBaOYg)

![image](https://user-images.githubusercontent.com/32815509/42817130-c104793a-89ea-11e8-9ae6-97cbbc047681.png)

## Context

Improper alignment of search icon in navbar.

## Your Environment

* Version used: 1.0.0-rc.2
* Browser Name and version: Google Chrome 67.0.3396.99
* Operating System and version (desktop or mobile): Windows 10 Home

**Comment by acburst** [comment]
The css you are using in the codepen is from v0.100.2. If you update it to the latest css it works as intended
