### ISSUE TITLE
Modal with fixed footer broken in IE11

### ISSUE THREAD

**Issue by carlosperate** [Dogfalo/materialize#604]
The current version of the modal footer is displayed as shown in the screenshot below:

![modal footer](https://cloud.githubusercontent.com/assets/4189262/6027828/a989aa22-abdc-11e4-8c22-709da918beb6.png)

The white rectangle at the bottom of the window is the actual modal-footer div.

**Comment by carlosperate** [comment]
Just wanted to confirm that this issue is still present in v0.95.2 and can be tested in the http://materializecss.com/modals.html page with the same results as the screenshot.

**Comment by Dogfalo** [comment]
Hmm we will have to look into fixes for this. It may not be possible to do this in IE
