### ISSUE TITLE
Modal with fixed footer scroolbar

### ISSUE THREAD

**Issue by carlosperate** [Dogfalo/materialize#605]
In firefox and chrome the current modal with fixed footer has the bottom part of the scroolbar hidden by the modal-footer div.
Additionally, in chrome there is some kind of extra thickness in the bottom border, which stops at the point where the scrollbar would be displayed if there was no fixed footer.
![modal footer scrollbar](https://cloud.githubusercontent.com/assets/4189262/6027978/bec36ff8-abdd-11e4-9fa3-b3b72f14f553.png)

**Comment by mylastof** [comment]
+1

**Comment by acburst** [comment]
This is not happening for me. What browser and OS?

**Comment by carlosperate** [comment]
Windows 8.1 (desktop with a touch screen), the scrollbar position happens in firefox and chrome (IE is completely broken as shown in a different issue). It also happens in Chrome on Android. 

The additional bottom border thickness happens in chrome for Windows 8.1.

**Comment by mradzinski** [comment]
+1, Happening on latest versions of Chrome and Firefox on a Win7 environment.

**Comment by carlosperate** [comment]
Just to emphasise that, at least on firefox in win8, this also causes the
bottom content of the modal to be covered by the fixed footer.

**Comment by carlosperate** [comment]
This has been fixed for a while now.
