### ISSUE TITLE
latest 1.0.0-rc.2 does not trigger modals actions while old version 0.99 does

### ISSUE THREAD

**Issue by ctrngk** [Dogfalo/materialize#6054]
I want to trigger modals actions in vuejs but 1.0.0-rc.2 min.js does not work as expected.
see 
https://jsfiddle.net/ctrngk/k2o7whu9/124/
After I swap with version 0.99 min.js, it works.
https://jsfiddle.net/ctrngk/k2o7whu9/125/

**Comment by pepyta** [comment]
You're just initializing with this.
You should call the method which is "open".

$('.modal').modal('open');

**Comment by acburst** [comment]
Pepyta is correct. In 1.0.0 we decoupled initialization from the open action. Now you should only initialize the modal once and call the specific methods on the modal instance.
