### ISSUE TITLE
Character Counter not working in rc.2, but does in 97.

### ISSUE THREAD

**Issue by gregoryagu** [Dogfalo/materialize#6057]
No matter how I try, I cannot get the character counter to work in rc2.

I created this gist to show
https://gist.run/?id=7031cc832f07307adc99b3e626fcd83e

And I know that the new way in rc 2 is to use data-length='5' instead of length='5' which is the way it is done in .97

**Comment by gregoryagu** [comment]
I did some more testing, and 98.7 is the last version it works in.

**Comment by acburst** [comment]
In the newest versions, we treat character counter like any other javascript component so you will have to initialize it in javascript.
