### ISSUE TITLE
Can't use Modal as a component with WebPack

### ISSUE THREAD

**Issue by geosenna** [Dogfalo/materialize#6061]
I am using materialize and webpack together. I have some issue with the modal and sidenav initilization:

`import 'materialize-css/js/cash.js';`
`import 'materialize-css/js/component.js';`
`import 'materialize-css/js/global.js';`
`import 'materialize-css/js/anime.min.js';`
`import 'materialize-css/js/modal.js';`

This is not working, I get this error:

`Uncaught ReferenceError: Component is not defined`

When I look at the compiled JS, the error is coming from this line:

`class Modal extends Component {`

Any though on this?

**Comment by geosenna** [comment]
It's been a while since I flag this issue. Am I the only one to not want to load the all the materialize library (180ko) to use a couple of components?
More gloably, updates of the repo are are increasingly rare, and pull requests are overstocking... Is there some king of a break in materialize development?

**Comment by Dogfalo** [comment]
We're most likely releasing 1.0 this weekend. And being in release candidate build, yes we're not adding anything that's not critical for release.

**Comment by Dogfalo** [comment]
This is also a duplicate issue. We'll be refactoring some of the components after 1.0 so they can be imported as modules.

**Comment by Levdbas** [comment]
Can you link to the duplicate issue @Dogfalo so I can follow the progress? I really want to use the modular approach as well 👍

**Comment by wtoalabi** [comment]
@Dogfalo @geosigno @Levdbas @klcantrell
Do we have solutions to this yet?
I loving what I am seeing playing around with this project!
Coming back from Mobile, I feel more  at home with Material Designs.
But somehow, I don't feel comfortable loading the whole components, especially if I can help it.

For me, and my use-case, going modular would make more sense.
So, had there been any solution yet?

Thanks all!

**Comment by geosigno** [comment]
There is no official solution for now and I seriously doubt there will be one day...
What I did, I forked the repo and manually comment all components that I will not use in the grunt file. Then I can rebuild the project with only component that I need, and reduce the compiled JS weight.
