### ISSUE TITLE
Misbehaving search icon in nav

### ISSUE THREAD

**Issue by JayHoltslander** [Dogfalo/materialize#6071]
Search input's icon repositions and scales oddly when input's autocomplete suggestions are hovered over.

* Materialize v1.0.0-rc.2
* Chrome v67.0.3396.99 (Official Build) (64-bit)

Reproducible on official docs page [here](https://materializecss.com/navbar.html#search-docs).

* **Example video:** <http://take.ms/WRuEr>
* **Screenshot**
![](http://take.ms/0tIm0)

**Comment by acburst** [comment]
Fixed in ca9beaf1
