### ISSUE TITLE
Dropdown-button

### ISSUE THREAD

**Issue by Maxou29** [Dogfalo/materialize#608]
I've got a problem with Dropdown-button (http://maximelb.fr/ We can look here with "Réseaux sociaux" on the right top corner
Go on many times and we can see the dropdown don't run

**Comment by Dontorpedo** [comment]
hi, i don't know if this is a framework problem and beacuse i had the same problem, my fix for that was:
adding this to my style.css

.dropdown-content {
    height: auto !important;
}

it worked for me.

**Comment by Dogfalo** [comment]
Fixed in ac116d6b8a633835cb655b460f2a67a5efdf666c
