### ISSUE TITLE
Example radio buttons on website should be updated

### ISSUE THREAD

**Issue by arjancwidlak** [Dogfalo/materialize#6080]
The example in the documentation on the website [here](https://materializecss.com/radio-buttons.html) should be corrected, by taking the input tag out of the label tags. 
The issue is discussed on stackoverflow and answered [here](https://stackoverflow.com/questions/49757521/materialize-css-radio-buttons-not-visible#50556305). 
In the CONTRIBUTING document it says [here](https://github.com/Dogfalo/materialize/blob/master/CONTRIBUTING.md#user-content-documentation) that for the documentation one should edit the master branch. However I could not find the page radio_buttons_content.html in the master branch.

**Comment by acburst** [comment]
That issue on stackoverflow is discussing an old version. Nesting the input inside the label is the right way to do it now.
