### ISSUE TITLE
Modal parameter for "top" positioning

### ISSUE THREAD

**Issue by beeb** [Dogfalo/materialize#609]
Would be great to have a "top" positioning parameter for modals that is not hardcoded to 10%, but can be set in the settings.

**Comment by RaSeR** [comment]
On my opinion it should be css parameter, not even js one.

**Comment by cruxiality** [comment]
+1 would be great if there's a way to configure the position

**Comment by Dogfalo** [comment]
Parameter exists now `startingTop: '4%'`

**Comment by stychu** [comment]
@Dogfalo its not working
