### ISSUE TITLE
Component loading error [ Checkbox and Radio Button ] - Materialize version ^0.100.2

### ISSUE THREAD

**Issue by RafaelMarinho96** [Dogfalo/materialize#6094]
When using the materialize version "^0.100.2" I noticed an error in loading the elements [Radio button and check box].

The radio and check are not displayed on the screen, I can only use those components in the "^1.0.0-rc.2" version.

**Comment by Dogfalo** [comment]
Did you check: http://archives.materializecss.com/0.100.2/
