### ISSUE TITLE
How do I init a Select with options?

### ISSUE THREAD

**Issue by simkessy** [Dogfalo/materialize#6097]
I want to load my options through code and not html, the document does a really bad job explaining how to do this. Actually it doesn't address it at all. Is it possible?

**Comment by apkrieg** [comment]
I assume you're talking about the Dropdown.

```javascript
document.addEventListener('DOMContentLoaded', function() {
    var elems = document.querySelectorAll('.dropdown-trigger');
    var instances = M.Dropdown.init(elems, options);
});
```

Documentation can be found here: https://materializecss.com/dropdown.html#initialization

**Comment by simkessy** [comment]
I am talking about Select dropdown `<options></options>` grammatically
