### ISSUE TITLE
materialize.js and materialize.min.js seems broken

### ISSUE THREAD

**Issue by evildog1** [Dogfalo/materialize#6101]
I spend 1 hour trying to figure it out why .js is not loading. I tried many ways to fix but nothing changed.
So i ended up downgrading .js to Materialize v0.100.2 that i had on my backup and **it worked**!
The latest version Materialize v1.0.0-rc.2 seems broken but there is no errors in console. I'm unsure how to debug it correctly but i'll keep old version for now

**Comment by Dogfalo** [comment]
See the upgrade guide here: https://github.com/Dogfalo/materialize/blob/v1-dev/v1-upgrade-guide.md

**Comment by evildog1** [comment]
Seems confused. I don't understand what "initialize it manually as shown in documentation" means
I'll stick to v0.100.2 for now on
