### ISSUE TITLE
Some components are not correctly assigned to M namespace

### ISSUE THREAD

**Issue by lpkruse** [Dogfalo/materialize#6104]
...resulting in a "M.Dropdown is not a constructor" error, which I think is because the Component is not being initialised correctly. The following components:
  Sidenav,
  Dropdown,
  Tabs
are being initialised differently from all other components, as:
  window.M.Dropdown = Dropdown
  window.M.Sidenav = Sidenav
  window.M.Tabs = Tabs
and not as
  M.Dropdown = Dropdown
  M.Sidenav = Sidenav
  M.Tabs = Tabs

**Comment by Dogfalo** [comment]
Fixed in 80c6881181c94f10def31d97cfc71941d94b104f
