### ISSUE TITLE
Align a select and an input on bottom

### ISSUE THREAD

**Issue by ventouris** [Dogfalo/materialize#611]
I created a form which in every line, I have one select and one number input. The problem is that I cannot make them align on the bottom and while the label of the number input is lower until you add a value, it looks like it is not align at all.

```
<div class="row">
          <div class="col l6 m6 s12">
            <select name="formation" class="browser-default">
              <option selected="" disabled="" value="">Choose the option</option>
              <option>option 1</option>
              <option>option 2</option>
            </select>
          </div>

          <div class="input-field  col l4 m6 s12">
            <input type="number" value="" class="validate" max="180" min="1">
            <label for="minutes">Minutes</label>
          </div>
</div>
```

I tried to add style of `display:inline-block` and `vertical-aling:bottom` but it doesn't work

**Comment by acburst** [comment]
Fixed in ae38b2907af92f310a3df08c9542ae48e6468b7a
