### ISSUE TITLE
Active tab indicator wrong size when used in modal

### ISSUE THREAD

**Issue by dealloc** [Dogfalo/materialize#6111]
## Expected Behavior

When you create a modal which contains tabs in it, you expect it to render like this:
![2018-09-12 15_21_47-js-ka8zxq - stackblitz](https://user-images.githubusercontent.com/2164354/45427669-ad660600-b69f-11e8-8837-25248605ecea.png)

## Current Behavior

Currently however, when you place tabs in a modal; you get the following behaviour:
![2018-09-12 15_21_58-js-ka8zxq - stackblitz](https://user-images.githubusercontent.com/2164354/45427694-c1116c80-b69f-11e8-8a94-7c375413a17d.png)

## Possible Solution

We currently work around this by delaying the initialization of the tabs until the modal is done rendering; however this introduces a lot of boilerplate code and complexity.

## Steps to Reproduce (for bugs)
I created a [StackBlitz](https://stackblitz.com/edit/js-ka8zxq?file=index.html) that demonstrates the problem.

## Context
We have complex web applications that often contain dialogs with multiple tabs (ex: viewing and editing tabs in a dialog).

## Your Environment

* Version used: v1.0.0 (latest at the time of writing)
* Browser Name and version: Chrome 69 & Firefox 61
* Operating System and version (desktop or mobile): Windows 10 (Desktop)

**Comment by roskelld** [comment]
This is due to the tab initializing before the modal, so the data its collecting to initialize isn't right.

There's a crappy work around I've found which is to delay the `updateTabIndicator()` by using a timeout.

`        setTimeout( () => {
            instance.updateTabIndicator();
        }, 500);`

This means you do see it update, if the timer is reduced it can screw up in other ways.

**Comment by acburst** [comment]
You can use the onOpenEnd callback on modal to update the tab indicator so it renders properly.

**Comment by ermarkar** [comment]
I am facing the same issue. There is heavy data rendering on the tab content.  I am using setTimeout(), any other way to solve this problem? How ccan I use this onOpenEnd?

**Comment by nateleavitt** [comment]
Putting this here for others. As mentioned above, you can use the onOpenEnd callback on the modal:

```
  // update tabs in modal after opening
  var modalOpts = { onOpenEnd: () => { tabInst.updateTabIndicator() } };
  M.Modal.init(modalElement, modalOpts);
```
