### ISSUE TITLE
What are the benefits of upgrading from v0.100.2 to v1.0.0?

### ISSUE THREAD

**Issue by newpen** [Dogfalo/materialize#6113]
Seems I have to change quite a large amount of my codes if I have to upgrade. What are the benefits? Is there any performance improvements?

**Comment by Dogfalo** [comment]
We removed the need for jQuery.
More consistency across components in terms of callbacks.
Many bug fixes especially in the FormSelect plugin.

Here is an upgrade guide if you are looking to upgrade: https://github.com/Dogfalo/materialize/blob/v1-dev/v1-upgrade-guide.md
