### ISSUE TITLE
Migration docs wrong for dropdown

### ISSUE THREAD

**Issue by AdamTyler** [Dogfalo/materialize#6116]
https://github.com/Dogfalo/materialize/blob/v1-dev/v1-upgrade-guide.md

Under dropdown section, it says `Call plugin on .dropdown-content instead of .dropdown-button`

If you use the `.dropdown-content` class, the function within dropdown.js `getIdFromTrigger` will fail and cause issues later when trying to access `dropdownEl`

Docs at https://materializecss.com/dropdown.html example shows using `dropdown-trigger` which will work properly

**Comment by acburst** [comment]
Thanks for catching this
