### ISSUE TITLE
What is the mechanism of select-drop-down close in V1.0.0

### ISSUE THREAD

**Issue by frostless** [Dogfalo/materialize#6120]
In previous version v100.02 every time a select-drop-down closes a "close" event is triggered.
My app has event handler to execute some code on that event.
$('.select-dropdown').on('close', function() {
   // ...
});
With the new version the event seems to disappear, can I still listen to similar event? It seems to me that the new version does not use Jquery to trigger events anymore. The element has its own 'close' function in `_handleDocumentClick` But I dont think I should listen to document click?

**Comment by acburst** [comment]
You can use the dropdownOptions option in select to set a callback on the underlying dropdown component
