### ISSUE TITLE
Chips init function throws TypeError when there is a label

### ISSUE THREAD

**Issue by cranndarach** [Dogfalo/materialize#6124]
When initializing a div with the `chips` class, if there is a label in that div, the init function raises a TypeError. As far as I can tell, this has a quick fix, and I plan to submit a pull request shortly.

## Expected Behavior

If there is already a label element present in the chips div, the initialization function should set its `for` attribute equal to the `id` of the input element.

## Current Behavior

The function `_setupLabel()` (in the init function) throws a `TypeError: this.$label.setAttribute is not a function`.

## Possible Solution

`Chips.$label` is created from `Chips.$el.find("label")`, which returns an array. `setAttribute()` expects a single element. Since there should only be one label element, it should be safe to set `Chips.$label` to `Chips.$el.find("label")[0]`.

## Steps to Reproduce (for bugs)

[See this Codepen](https://codepen.io/cranndarach/pen/BOOVME)

## Context

I am hoping to use this for adding tags in an Electron app I'm working on.

## Your Environment

* Version used: 1.0.0-rc.2 from npm
* Browser Name and version: Electron v2.0.8
* Operating System and version (desktop or mobile): Manjaro
* Link to your project (if appropriate): https://github.com/cranndarach/lifetracker/tree/tags

**Comment by acburst** [comment]
Merged
