### ISSUE TITLE
Maintain repository ?

### ISSUE THREAD

**Issue by jpic** [Dogfalo/materialize#6127]
Hello,

Are you going to maintain MaterializeCSS ?

Thanks in advance for your reply

![2018-09-17-214410_810x587_scrot](https://user-images.githubusercontent.com/94636/45646200-ef89b000-bac2-11e8-9c39-d9a57fd88c55.png)

**Comment by Dogfalo** [comment]
Yes we are. Curing the RC builds, we don't merge non-essential fixes. Since we have now released 1.0. We will merge PR's that are are clear in what they fix and also contain a codepen as an example of the current bug.
