### ISSUE TITLE
DatePicker Dropdowns breaking page

### ISSUE THREAD

**Issue by simkessy** [Dogfalo/materialize#6128]
I'm important materializecss into my project like this: 

```
.myapp{
    @import "materialize-css/sass/materialize.scss";
}
```

This allows me to namespace my application within another site without styles clashing 

However when I load the date picker and click on the Month or Year, the options are loaded to the body and essentially breaks the app. 

Any way to fix this? 

I've set the container for the date picker to load into a div within my application hoping that the options would be scoped to that container but that's not what's happening. 

Looking at source this might be where things might be causing the problem: 

      // Init Materialize Select
      let yearSelect = this.calendarEl.querySelector('.orig-select-year');
      let monthSelect = this.calendarEl.querySelector('.orig-select-month');
      M.FormSelect.init(yearSelect, {
        classes: 'select-year',
        dropdownOptions: { container: document.body, constrainWidth: false }
      });
      M.FormSelect.init(monthSelect, {
        classes: 'select-month',
        dropdownOptions: { container: document.body, constrainWidth: false }
      });

But i'm not entirely sure.

**Comment by simkessy** [comment]
@DanielRuf  any insight on this, I'm a bit stuck.

**Comment by Dogfalo** [comment]
Can you create a Codepen that recreates the problem so we can take a look?

**Comment by DanielRuf** [comment]
Not sure why I was tagged here.

**Comment by simkessy** [comment]
Hi @Dogfalo 

I create the codepen: https://codepen.io/anon/pen/bxPxqL

Essentially my scss file does this:

```
.myapp {
    @import "materialize-css/sass/materialize.scss";
}
```

My application lives within another site so I needed to prevent materialize from override that sites styling. This has mostly worked well, I've overridden some things myself where needed. However the picker dropdowns are giving me issues. 

When you click on the datepicker it immediately appends the month/year lists to the body, then when I click on the months/year in the picker, well it just breaks essentially. 

@DanielRuf sorry, you seemed active on the project so I was hoping you could take a look but if you can't that's fine. Thank you.

**Comment by simkessy** [comment]
```
            onDraw: function() {
                $("body > ul.select-dropdown")
                    .detach()
                    .appendTo("#datepicker-container");
            }
```

This worked.
