### ISSUE TITLE
Select dropdown pushes to make space for itself

### ISSUE THREAD

**Issue by VeeK727** [Dogfalo/materialize#6129]
I'm using v1 of materializecss and I encountered this problem where my select tag is in a cramped space. When I click on the tag, the options pushes to expand the container to make  space for itself.

I believe [this video](https://youtu.be/7il5NssMuPE) would be much better in explaining what I mean.

As you can see, for the dropdown alongside it, I used the `container` option to provide it with `$('body')` and it works as intended, overlapping the other content but such an option is not abvailable with select. How do I get around it?

**Comment by acburst** [comment]
in v1, Select has an option called dropdownOptions which you can pass an object of options for the underlying dropdown. If the container option fixes your issue you can try doing this for select as well.

**Comment by VeeK727** [comment]
It worked. Thanks. How did I not notice that option there :p

```
$('select').formSelect({
	dropdownOptions: {
		container: $('body')
	}
});
```
