### ISSUE TITLE
Hammerjs not found

### ISSUE THREAD

**Issue by raytaylorlin** [Dogfalo/materialize#613]
I use require.js and materialize.js v0.95.1, and it reports `Uncaught Error: Script error for: hammerjs`.
It seems that you use the `jquery.hammer.js` which has a dependency with `hammerjs.js`, but the dependency is not included in the release file.

**Comment by acburst** [comment]
we have the minified file in the distribution.
hammer.min.js

**Comment by raytaylorlin** [comment]
[dist/js/materialize.js](https://github.com/Dogfalo/materialize/blob/master/dist/js/materialize.js) has no hammer.min.js.
I have to download and import it manually, that means
```
<script src="scripts/lib/hammer.min.js"></script>
<script src="scripts/lib/materialize.min.js"></script>
```
Why not concat the file into the distribution?

**Comment by Dogfalo** [comment]
It is already

**Comment by raytaylorlin** [comment]
I am sorry, but which line defines the `Hammer` in [dist/js/materialize.js](https://github.com/Dogfalo/materialize/blob/master/dist/js/materialize.js)?

**Comment by Dogfalo** [comment]
Line 213

**Comment by imcaffrey** [comment]
@Dogfalo When I was using materialize.js for my html in an electron project, the browser showed me with `Uncaught ReferenceError: Hammer is not defined`. Wonder what I can do to fix this?

I tried to use `require('path-to-materialize.js')` as I did for jQuery, but it didn't help.

**Comment by kalpetros** [comment]
@imcaffrey I confirm it works by adding **hammer.min.js**. I used `<script src="scripts/hammer.min.js"></script>` instead of **require** because the latter didn't work.

**Comment by imcaffrey** [comment]
@kalpetros Thanks for informing, `require` worked on my electron project, don't quite know your condition.
