### ISSUE TITLE
Bugs: Removal of Multiple Pushpins

### ISSUE THREAD

**Issue by Dargmuesli** [Dogfalo/materialize#6135]
## Expected Behavior
When calling `M.Pushpin.getInstance(element).destroy();` only the Pushpin instance of the element should be destroyed. All other pushpins should continue to work.

## Current Behavior
The event handler for all pushpin updates is removed: https://github.com/Dogfalo/materialize/blob/4a68ebd12c85b81e188988760ec6f16899864da3/js/pushpin.js#L80
Thus no pushpin works when destroying one pushpin instance.
Also the `M_Pushpin` property that is set here: https://github.com/Dogfalo/materialize/blob/c9363571a1fe60168d3833bf2b139b52723b5b04/js/pushpin.js#L25 is never removed. That means this line: https://github.com/Dogfalo/materialize/blob/c9363571a1fe60168d3833bf2b139b52723b5b04/js/component.js#L17 is executed eventhough `M.Pushpin.getInstance(element).destroy();` was already executed before.

## Version
1.0.0

**Comment by acburst** [comment]
Thanks for finding this! Fixed in b3233253
