### ISSUE TITLE
Dropdowns break when included in a Tab

### ISSUE THREAD

**Issue by Abourass** [Dogfalo/materialize#6138]
## Expected Behavior

A drop down that drops from the tab. 

## Current Behavior

When I click the anchor that should cause the dropdown to open, instead it stays the same size and becomes scrollable. 

## Possible Solution

I was able to fix this by adding a div beneath the tabs with an id of 'blankSpace' then adding the following code on initializations:
```
document.addEventListener('DOMContentLoaded', function() {
          var elems = document.querySelectorAll('.dropdown-trigger');
          var blank = document.getElementById('blankSpace');
          let options = {
            coverTrigger: false,
            hover: true,
            container: blank,
          }
         var instances = M.Dropdown.init(elems, options);
```
If this is expected behavior, maybe add a section on adapting for tabs to the documentation.

## Steps to Reproduce (for bugs)

1. Here's a link to a codepen with the relevant issue - https://codepen.io/ModAbaccus/pen/RYmgaN
2. To replicate it on your own, simply add a drop down to a tab. 

## Context

I'm dynamically generating the navigation menu depending on users permission level, and I need to the navigation to have dropdowns. I'd already been using tabs, so I simply tried inserting one into a tab, and found it broken. 

## Your Environment

* Version used: 1.0.0
* Browser Name and version: Chrome, Version 69.0.3497.100 (Official Build) (64-bit)
* Operating System and version (desktop or mobile): Windows 7, 64 Bit
* Link to your project (if appropriate):

**Comment by acburst** [comment]
In 1.0.0 there is no longer automatic initialization, so first off your dropdown isn't initialized. Second, because tabs has overflow properties on it, you will want to move your dropdown content out of there. Then you can specify the container where it is kept to stop the plugin from moving the dropdown content. Then it should work. I've editted your codepen to demonstrate it:

https://codepen.io/anon/pen/EdGMQL
