### ISSUE TITLE
i want to contribute for translation

### ISSUE THREAD

**Issue by tormahiri** [Dogfalo/materialize#614]
hello materialize team
i want contribute for translation materialize home site to my own language 
how i can contirbute for this purpose?please guid me

**Comment by Dogfalo** [comment]
What language?

**Comment by acburst** [comment]
Please post your language in this issue
https://github.com/Dogfalo/materialize/issues/233

**Comment by tormahiri** [comment]
we are using uyghur language on every day life
uyghur language like this : ئەسسەلامۇ ئەلەيكۇم ،مەن materialize نى تەرجىمە قىلماقچى 
mean of that sentence is hello ,i want to translate materialize
