### ISSUE TITLE
Toast not showing `<i class='fa fa-location'></i>` icon class

### ISSUE THREAD

**Issue by monu080** [Dogfalo/materialize#6146]
I am also tested in this toast to show icons css class file in toast for turning on location notify for users and I am also find a bug in this is a mobile web app for improving ux
Types
Toast is not rendering
 `<a onClick="M.toast({'icon class is not worked and showed in toast <i class='fa fa-loaction-arrow'></i>')}"></a>`
Css Icon class why this

**Comment by EnzoBaldisserri** [comment]
There is no uppercase 'C' in "onclick", you need to put the key "html" before your text, and you inverted the end parenthese with the end bracket. Also, if your <a> doesn't have a "href" attribute, you'd better use a <button>.

```
<button onclick="M.toast({ html: 'your text' })></button>
```

**Comment by TheComputerM** [comment]
The only problem is that you have not referenced the html property of toast
It is M.toast({html: "Content"})
and not M.toast({"Content"})
