### ISSUE TITLE
Feature request: color picker

### ISSUE THREAD

**Issue by jacobq** [Dogfalo/materialize#6159]
A few years ago (in #3811) you stated that there was no interest in designing a color picker for Materialize. Now that v1.0 has shipped, please reconsider adding a color picker component. Although I could not find a specific reference to this idea on `material.io` (I also couldn't seem to find the "Pickers" section except [via archive](https://web.archive.org/web/20180223140409/http://material.io/guidelines/components/pickers.html)), there is an Android implementation that I found [on materialdoc.com](https://materialdoc.com/components/pickers/#color-picker), which seems to have the appearance and behavior that I'd like.

Of course, there are many existing color picker components, such as [`spectrum`](https://bgrins.github.io/spectrum/) and [`colpick`](https://github.com/mrgrain/colpick), but there seem to be few options that fit the MD style / theme.

There are also examples of this in Google's Gmail & Docs apps, which would also be OK.
![tmp-color-pallette](https://user-images.githubusercontent.com/1633459/46743968-cac2cb80-cc6f-11e8-94ce-33d5b321751e.png)
![tmp-label-color](https://user-images.githubusercontent.com/1633459/46744220-5177a880-cc70-11e8-8fcf-ec0a4c5e7a31.png)

**Comment by aspekt23** [comment]
@acburst @Dogfalo Is it still open ? I could work on this.

**Comment by Dogfalo** [comment]
No, sorry this isn't something we are looking to add.

**Comment by jacobq** [comment]
Looks like PR #6079 seeks to implement something like this.
