### ISSUE TITLE
allow use buttons (left and right) in navbar without disappear in the mobile screen

### ISSUE THREAD

**Issue by tinchoz49** [Dogfalo/materialize#616]
Hi guys, this is an enhancement for the navbar.

Example:

http://www.google.com/design/spec/layout/structure.html#structure-app-bar

**Comment by acburst** [comment]
Not sure what you mean by this. You can already do this

**Comment by tinchoz49** [comment]
Oh, sorry i didn't know that. The documentation has an example?

**Comment by Dogfalo** [comment]
Documentation for what?

On Wed, Feb 4, 2015 at 10:55 PM, tinchoz49 <notifications@github.com> wrote:

> Oh, sorry i didn't know that. The documentation has an example?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Dogfalo/materialize/issues/616#issuecomment-72990205>.
>



-- 
Doggy sends his greetings from Mars.

**Comment by snow01** [comment]
@Dogfalo - It's not documented, I would probably add soon.

@tinchoz49 - If you need to show some buttons both in desktop and mobile - do not enclose them in "side-nav" container. For example those 3 icons on right (shown in link http://www.google.com/design/spec/layout/structure.html#structure-app-bar) will **not** be inside a ul that has class "side-nav".

**Comment by tinchoz49** [comment]
thanks @snow01! 

Ticket closed!
