### ISSUE TITLE
Mobile Collapse Navbar Button not working

### ISSUE THREAD

**Issue by carlosperate** [Dogfalo/materialize#617]
Cannot get the mobile collapsible navigation bar hamburger button to work when it is displayed.
Pressing the button will show the dark overlay, but the left side menu does not appear.

The example from the latest navbar.html works within the page (git cloned 763c0e5113d0753983286acfa3253b66eacdac6d), but the example code copied and pasted into the following test does not work:

https://gist.github.com/carlosperate/6e0a592cbf8b7993d5c3

This is using the css and js from the bin folder.

Tested in Windows 8.1 with Chrome, Firefox and IE11.

**Comment by RaSeR** [comment]
As i remember ```html <ul id="nav-mobile">``` should have class ```css side-nav```. Try it.

**Comment by carlosperate** [comment]
Ok, so the new changes modified that in the documentation to be just the `hide-on-med-and-down` class (plus `right` for alignment). 

Now, if I set the class to `right hide-on-med-and-down side-nav`, it does not work change my initial report. is the same as setting it to `right hide-on-med-and-down`, the list is displayed horizontally in large resolutions but the button does not work in low resolutions.

And if I set it to `right side-nav` the button works in low resolutions, but the list is not displayed horizontally in the large resolutions.

**Comment by acburst** [comment]
The way we restructured our nav is that the horizontal and side-nav menus are now separate.

You will have to copy and paste and make 2 ULs with the same links but have one be a side-nav and the other have the hide class

**Comment by carlosperate** [comment]
Can the documentation please be updated to reflect this change. My gist test is the example code still present in the master documentation, so right now it breaks all previous implementation of mobile navbars without any indication of how to fix them.
