### ISSUE TITLE
materialize 1.0.0 Modal (No Jquery)

### ISSUE THREAD

**Issue by TheLoverVI** [Dogfalo/materialize#6173]
```
var elems = document.querySelectorAll('.modal');
var instances = M.Modal.init(elems, {});
var instance = M.Modal.getInstance(elems);
```

works fine through the UI, **BUT** **not working** if i want to `instance.close()` / `instance.open()` through javascript. 
am i missing something?

**added info**: `M.Modal.getInstance(elems) ` is not working/returning anything to the var `instance`

**Comment by TheLoverVI** [comment]
since it hasnt been replied, got a fast work around.
if you got a close button to trigger the modal to close, put an id on it and called click() event on it.
`(document.getElementById("entryProjectCancel")).click()`  i named my id as **entryProjectCancel**, u can change it to anything(obviously).

![image](https://user-images.githubusercontent.com/22610742/47014309-1267bc80-d174-11e8-8aef-3d41327e7990.png)
![image](https://user-images.githubusercontent.com/22610742/47014352-39be8980-d174-11e8-8d2f-cbaa6a7c1d72.png)

**Comment by Dogfalo** [comment]
Use the methods from here:
https://materializecss.com/modals.html#methods

Call it on the instance object like so:
```javascript
instance.open();
```

**Comment by Dogfalo** [comment]
You can't get instance from an array like object. Check what elems contains and pass in a single elem to get instance from

**Comment by qhoirulanwar** [comment]
> You can't get instance from an array like object. Check what elems contains and pass in a single elem to get instance from

please give an example,
I really don't understand

**Comment by KirkBushman** [comment]
I'm having this issue as well, 

    var instance = M.Modal.getInstance(element);
    instance.open();

Sometimes it works sometimes it doesn't (instance is undefined)
