### ISSUE TITLE
Dropdown menu in navbar in IE

### ISSUE THREAD

**Issue by carlosperate** [Dogfalo/materialize#618]
The drop-down menu in the navigation bar does not display the down arrow in IE.

Firefox screenshot:
![firefox](https://cloud.githubusercontent.com/assets/4189262/6052354/d50d6e66-acc9-11e4-8ec4-115a6e3e9ab7.png)
IE screenshot:
![ie](https://cloud.githubusercontent.com/assets/4189262/6052356/de21c1b4-acc9-11e4-8fa3-0de754814feb.png)

This screenshot from my project shows that the arrow is just jumping to the second line:
![ie2](https://cloud.githubusercontent.com/assets/4189262/6052375/2a0aa37a-acca-11e4-9ba3-376d546141bf.png)

**Comment by acburst** [comment]
Hmm, should be fixed now in f1ee5f45618cf21344e3873220dc27e39bb32384
