### ISSUE TITLE
Materialize swipe tabs not working in modal

### ISSUE THREAD

**Issue by bahmanpm** [Dogfalo/materialize#6180]
## Summary
Hi. The problem is that Materialize swipe tabs not working properly and it doesn't show swipe effect. This situation occurs after loading page but if you change tabs after resizing browser screen, swipe feature works properly. 

## Expected Behavior
Expecting to swipe tabs works like materialize example : 
[https://materializecss.com/tabs.html](https://materializecss.com/tabs.html)

## Current Behavior
Swipe feature not work properly : 
[issue in stackoverflow](https://stackoverflow.com/questions/52903051/materialize-swipe-tabs-not-working-in-modal)

## Steps to Reproduce (for bugs)

1. I tried to change modal size with jquety after loading page, but it not changed. Only after resizing browser windows swipe feature works. It seems to after "resize event" some values change and it causes to solving the problem.

## Your Environment

* Version used: Materialize 1.0.0 & Materialize 1.0.0-rc.2
* Browser Name and version: FireFox 62.0.3 & Chromium  69.0.3497.81
* Operating System and version (desktop or mobile): Ubuntu 16.04

**Comment by acburst** [comment]
Because the modal is hidden by default, normal initialization of tabs within modals won't work. You can use callbacks like onOpenEnd to reinitialize your tabs so that they render correctly once the modal is fully opened.

**Comment by bahmanpm** [comment]
Thanks. Your solution worked.
