### ISSUE TITLE
How to handle a modal isOpen event?

### ISSUE THREAD

**Issue by PinkyRabbit** [Dogfalo/materialize#6188]
Hello! I tried to use a modals on my website. I need to resize nested `div`'s after modal will open. But there is no any guide or example. Only "if you want you can use `leanModal`'s `ready` option". But why I cant find any guide for simple method `isOpen`? Or this is such easy as don't need any documentation? Thanks!

**Comment by Dogfalo** [comment]
Sounds like you need to use the `onOpenEnd` option when you initialize the modal
