### ISSUE TITLE
Publish to NPM

### ISSUE THREAD

**Issue by amchang** [Dogfalo/materialize#619]
Hey guys,

Great framework. Do you think you can publish to NPM also? I know you guys do bower, but if I am going to use materialize, then I'd have to install bower just for this.

Thank you

**Comment by tinchoz49** [comment]
:+1:

**Comment by piuccio** [comment]
would be great indeed

**Comment by lee-40square** [comment]
+1 I'm looking for this as well.

**Comment by Dogfalo** [comment]
https://www.npmjs.com/package/materialize-css
