### ISSUE TITLE
jQuery.Deferred exception: Cannot set property 'tabIndex' of null TypeError: Cannot set property 'tabIndex' of null

### ISSUE THREAD

**Issue by ilyas2016** [Dogfalo/materialize#6192]
I just cloned the git repo and run the documentation locally.
i am trying to migrate my project from previous version to latest.
i downloaded the js minified.
after adding js to my project i am getting the error.

jQuery.Deferred exception: Cannot set property 'tabIndex' of null TypeError: Cannot set property 'tabIndex' of null

how can i fix that?

**Comment by acburst** [comment]
Its erroring without you calling anything? Can you share more of your project or where exactly its erroring on?

**Comment by tranxactive** [comment]
I figured that out, since i was migrating from version 0 to 1, this error was occurring while data-activates attribute is used, when i changed that to data-target error resolved.

**Comment by ilyas2016** [comment]
I figured that out, since i was migrating from version 0 to 1, this error was occurring while data-activates attribute is used, when i changed that to data-target error resolved.
