### ISSUE TITLE
How about add listener at Floating Action Button?

### ISSUE THREAD

**Issue by SuhwanCha** [Dogfalo/materialize#6194]
Hello.

To use Floating Action Button, 

 document.addEventListener('DOMContentLoaded', function() {
    var elems = document.querySelectorAll('.fixed-action-btn');
    var instances = M.FloatingActionButton.init(elems, options);
  });

  // Or with jQuery

  $(document).ready(function(){
    $('.fixed-action-btn').floatingActionButton();
  });

(https://materializecss.com/floating-action-button.html)

### There is no call back function!!

I wanted to add when I click ".fixed-action-btn", background is changed.
So I tried add click event listener at ".fixed-action-btn" and ".btn-floating". Both method are perfectly worked at Chrome 69 and Safari (macOS mojave) but I found it doesn't work at IOS, safari (IOS 12.0.1, iPhone X)
 
So I edit materialize.js at :8508

      value: function _animateInFAB() {
###         // add something I want to run
        var _this49 = this;
        this.$el.addClass('active');

        var time = 0;
        this.$floatingBtnsReverse.each(function (el) {
          anim({
            targets: el,
            opacity: 1,
            scale: [0.4, 1],
            translateY: [_this49.offsetY, 0],
            translateX: [_this49.offsetX, 0],
            duration: 275,
            delay: time,
            easing: 'easeInOutQuad'
          });
          time += 40;
        });
      }

I think if there is something callback function(it's optional) when floating action button is opened or closed.

Thanks!
If you think it's good idea, I'll pull request

**Comment by acburst** [comment]
This sounds reasonable. If you want to take a crack at a PR, go ahead
