### ISSUE TITLE
Floating button breaks when placed inside a side-nav class.

### ISSUE THREAD

**Issue by PraveenAsh** [Dogfalo/materialize#6195]
The shape and the icon of the `btn-floating` class for `<a>...</a>` distorts when inside the side nav. Tried to override the default CSS but didn't work on resizing the side nav. Width is inherited which is affecting the shape, especially in `small` and `medium` class of `btn`. CSS needs a fix! 
![128](https://user-images.githubusercontent.com/21225726/47809565-31b33c00-dd67-11e8-8a63-0c765ba97e8a.PNG)
![129](https://user-images.githubusercontent.com/21225726/47810014-493ef480-dd68-11e8-85d8-a977653c57c6.PNG)

**Comment by acburst** [comment]
Fixed in bafde665
