### ISSUE TITLE
browser(s) back button is not managed on Gallery materializecss theme ?

### ISSUE THREAD

**Issue by hasle1** [Dogfalo/materialize#6196]
Hi, [https://themes.materializecss.com/pages/demo](url)
The "back" button on browser is not managed.
You can only use the "back" HTML `button: <class = "back-btn">` on `<id = "placeholder-navbar">`
On this temple is the Back button of the browser works perfectly : [https://materialize-shopify-themes.myshopify.com/collections/all-products#none-selected](url)
) 
Is there a solution to this problem ? (I'm a beginner)

**Comment by acburst** [comment]
This is not the place for anything to do with the themes. You can either use the theme support repo or email directly to materializethemes@gmail.com
