### ISSUE TITLE
Incorrect active tab underlined on initial page load when tabs are in collapsible.

### ISSUE THREAD

**Issue by cercos** [Dogfalo/materialize#6199]
If you take the collapsible example straight from the docs and place a set of tabs, using the example in the docs, in the collapsible body, all tabs are marked as the currently active tab on initial page load, but the right tab is loaded for the content.  if you click a tab it starts working normally.

**Comment by acburst** [comment]
Because collapsibles content is hidden onload, you will need to reinitialize the tabs indicator when the collapsible is opened. Look at the onOpenEnd callback and call updateTabIndicator on the tabs to readjust the indicator
