### ISSUE TITLE
Top class

### ISSUE THREAD

**Issue by LucasNaja** [Dogfalo/materialize#6203]
Add **top** class to top most component when mouse hover

This:
![screenshot_20181110_194338](https://user-images.githubusercontent.com/13838273/48306515-0546af00-e521-11e8-8a9d-f361c86c4a3b.png)

Instead this:
![screenshot_20181110_194530](https://user-images.githubusercontent.com/13838273/48306519-3de68880-e521-11e8-98a1-4fb6d16ae35d.png)

Code:
`.top:hover { position: sticky }`

**Comment by acburst** [comment]
This seems simple enough for you to add on your own? I'm not sure a global class is needed

**Comment by LucasNaja** [comment]
For beginner people, maybe harder to do this... I'm beginner too, i had to keep looking and testing this attribute on css file using VSCode intelliSense.
How much more easy, is better
