### ISSUE TITLE
Collapsible with Expandable setting breaks with even number of list elements

### ISSUE THREAD

**Issue by james-peel** [Dogfalo/materialize#622]
Taking the example on the website, if you change the 'Expandable' demo to 2 or 4 list items, the expandables no longer work.

Going to have a quick debug now, looks like click events are being triggered for all the headers, not just the current target.

**Comment by james-peel** [comment]
Line 68/69 of collapsible.js

```javascript
          // Event delegation to open collapsible section
          $this.on('click', '.collapsible-header', function (e) {
```

This will fix the issue:

```javascript
          // Event delegation to open collapsible section
          $(this).on('click', function (e) {
```

**Comment by Dogfalo** [comment]
Already been fixed in master
