### ISSUE TITLE
Breadcrumb breaks icon position

### ISSUE THREAD

**Issue by DMGPage** [Dogfalo/materialize#6224]
Code below:
```
<nav>
    <div class="nav-wrapper">
      <div class="col s12">
        <a href="#!" class="breadcrumb"><i class="material-icons">home</i> First</a>
        <a href="#!" class="breadcrumb"><i class="material-icons">star</i> Second</a>
        <a href="#!" class="breadcrumb">Third</a>
      </div>
    </div>
  </nav>
```

generates this type of breadcrumb:
![Image of Breadcrumb](https://failiem.lv/thumb_show.php?i=64szyb3a)

As you can see, icons are moved away from text.
I'm using Materialize v1.0.0

**Comment by acburst** [comment]
Good catch.

Fixed in 4e0ed3616c8c4ab18286b7b44cdc626ca354b975
