### ISSUE TITLE
Dragging space for opening Sidenav is too narrow

### ISSUE THREAD

**Issue by stefan-niedermann** [Dogfalo/materialize#6225]
When asking general "how to" questions:

- Please do not open an issue here!
- Instead, ask for help on [StackOverflow](stackoverflow.com/questions/tagged/materialize) or in our [Gitter](https://gitter.im/Dogfalo/materialize) channel.

- Read the [CONTRIBUTING document](https://github.com/Dogfalo/materialize/blob/master/CONTRIBUTING.md) Any issues that are violating the contributing guidelines, will be closed!
- [Search for duplicate or closed issues](https://github.com/Dogfalo/materialize/issues?utf8=%E2%9C%93&q=is%3Aissue) and make sure to go through our [labels](https://github.com/Dogfalo/materialize/labels).
- Include a [reduced test case](https://css-tricks.com/reduced-test-cases/) in the form of a Codepen when reporting bugs unless it is not applicable, otherwise your issue will be closed.

To open the Sidenab with a swipe geasture on a smartphone, the swipe has to *start* at the very left side of the website. It is nearly impossible for me (and many of my customers) to start on the **very** left side. It seems like if one is starting more than 1px from the left side, nothing happens.

## Expected Behavior

When touching roghly in the left 25% of a smartphone and drag to the right side, it should opem the sidenav. Angular Material goes the other way around by enabling the swipe geasture at the whole body (using hammer js) - this would not even be necessairy, bht at least give users 20px to start the swipe geasture :)

## Steps to Reproduce (for bugs)

1. 
2.

## Your Environment

* Version used: 1.0.0
* Browser Name and version: Firefox for Android, iOS Safari
* Operating System and version (desktop or mobile): All mobile
* Link to your project (if appropriate): https://beta.gaestehaus-vogel.de/ (will remove the link after you were able to confirm)

Thank you in advance!

**Comment by acburst** [comment]
You can tweak the width of the drag target to what suits you with css
