### ISSUE TITLE
Navbar dropdown documentation is missing plain javascript initialization

### ISSUE THREAD

**Issue by khalyomede** [Dogfalo/materialize#6227]
## Expected Behavior
[Navbar dropdown documentation](https://materializecss.com/navbar.html#navbar-dropdown) containing plain javascript alternative for the Dropdown initialization.

## Current Behavior
No plain javascript alternative found.

## Possible Solution
Instead of :

```javascript
$(".dropdown-trigger").dropdown();
```

Do (like the Dropdown own documentation):

```javascript
document.addEventListener('DOMContentLoaded', function() {
  var elems = document.querySelectorAll('.dropdown-trigger');
  var instances = M.Dropdown.init(elems, options);
});

// Or with jQuery

$('.dropdown-trigger').dropdown();
```

## Your Environment
* Version used: 1.0.0

**Comment by acburst** [comment]
Fixed in 0bdc6399
