### ISSUE TITLE
Dropdown event onOpenEnd doesnt work

### ISSUE THREAD

**Issue by SaliMike** [Dogfalo/materialize#6231]
## Expected Behavior

Dropdown event **onOpenEnd** should execute function.

## Current Behavior

Dropdown event **onOpenEnd** doesnt execute function.

## Steps to Reproduce (for bugs)

https://codepen.io/anon/pen/yGeWRe

**Comment by acburst** [comment]
This was a select specific bug. Thanks for catching this.

Fixed in 1b53bdec

**Comment by jkevingutierrez** [comment]
Hi,

Any plans of releasing a new version with this bug fixed?
