### ISSUE TITLE
Parallax Position

### ISSUE THREAD

**Issue by Davos95** [Dogfalo/materialize#6235]
The parallax's CSS have a  problem.
The position is absolute, when it loaded it appear white (or whatever color have the div) while if the position is static the image's parallax appear and it works perfectly.

My CSS
.parallax-container .parallax {
        position: static !important;
}

**Comment by MeteorCoder** [comment]
Do you know how to submit a PR?

**Comment by acburst** [comment]
Please provide a code example or more explanation of the issue. Proposing a solution like this isn't helpful if not fully tested.
