### ISSUE TITLE
Can't use Leaflet Maps inside Tab

### ISSUE THREAD

**Issue by CloudPower97** [Dogfalo/materialize#6238]
I'm trying to use [Leaflet](https://leafletjs.com/) inside a `Tab` but the map is not showing correctly when it's a `Tab` other than the first one.

## Expected Behavior

The map should work without problems, regardless of the `Tab` where it's placed.

## Current Behavior

When the map is contained in the first `Tab` it works without problems, otherwise it doesn't work correctly.

I've a "working" example of this strange behavior [on CodePen](https://codepen.io/CloudPower97/pen/QzpOaV?editors=1010).

Can someone kindly help me out?
Am I doing something wrong?

Thanks in advance and keep up the good work!

**Comment by roiLeo** [comment]
You've added the same marker on the first map.
Anyway here is an explanation : https://stackoverflow.com/questions/36246815/data-toggle-tab-does-not-download-leaflet-map/36257493#36257493
