### ISSUE TITLE
Bootstrap compatibility

### ISSUE THREAD

**Issue by unsafecode** [Dogfalo/materialize#624]
What about adding Bootstrap classes as aliases? Most people have already many components and structures built with BS, so it would be problematic and time-consuming to clone them and migrate all classes (grids, forms, etc..). It is unfortunate as this is a wonderful project!

**Comment by Dontorpedo** [comment]
Why should a framework integrate another framework??

there is allready a Material Ui for Bootstrap

**Comment by unsafecode** [comment]
Not sure, just thinking about side aspects like cross compatibility, integration in existing projects or easier adoption.Negligible features, probably.

Besides, other "Material Ui for Bootstrap" projects all feature some kind of downfalls: incomplete documentation, missing components, licesing, etc...
