### ISSUE TITLE
Is Materialize being maintained?

### ISSUE THREAD

**Issue by L1ghtn1ng** [Dogfalo/materialize#6243]
Is this still being maintained as there has not been any meaningful changes in several months and would love to see this grow more and love how easy it is to make a responsive site from the gecko

**Comment by ronaldohoch** [comment]
I don't know, but here is the last commit: 

https://github.com/Dogfalo/materialize/commit/8af73e2fd50a2209a9ace3abebe97d6fe2af0c72

**Comment by Praveen-Rai** [comment]
@L1ghtn1ng It seems to be the case now. the last code change was in Jan 19. Since then just the monthly Patreon update. And there are multiple pull requests that are pending.

@Dogfalo Can you please shed some light ?

**Comment by CodexLink** [comment]
@acburst (Sorry to ping you, I'm concerned to this repository as well you are one of the maintainers of this project as well) )added  in hopes that we could get the answer regarding this issue.

**Comment by Dogfalo** [comment]
Hey everyone, we're just having a small break after the big release for 1.0. We'll be doing some planing for upcoming changes and reviewing PR in the coming week.

**Comment by Chrisx84** [comment]
@Dogfalo pretty huge break of 2 years of no updates. wish i could take a 2 year vacation from coding, i dont even get 1 day to play minecraft.

**Comment by pwcreative** [comment]
@Chrisx84 I guess people who make stuff for free (and then give it away for free) are entitled to set their own holiday schedule 😂
