### ISSUE TITLE
When the label of the input field is long enough the label are not aligned properly.

### ISSUE THREAD

**Issue by lacc** [Dogfalo/materialize#6255]
Hi,

I have opened a new issue as this is still not working properly for me: https://jsfiddle.net/dqf26a3q/2
I've tested in Chrome and IE. 
I even tried to edit the label text in the developer tool on the demo site, same issue:
https://materializecss.com/text-inputs.html

Any idea how to workaround this?

Thanks

_Originally issue:_
https://github.com/Dogfalo/materialize/issues/2697

**Comment by Jncocontrol** [comment]
Add the class of "truncate" it's a small workaround, take it as you will.

**Comment by lacc** [comment]
I am afraid it is not working correctly on Input labels. The label disappears when clicking on the input.
Here is an example on https://materializecss.com/text-inputs.html :

- I amended the text of the Email label:
<img src="https://user-images.githubusercontent.com/4140831/51268375-e26cc700-19b7-11e9-9ffe-55cb5b3a4378.png" height="200">

- After clicking on the input:
<img src="https://user-images.githubusercontent.com/4140831/51268499-2b248000-19b8-11e9-8af0-6b78a8f85996.png" height="200">

I still would like to have a fix on this with break instead of truncate. I've spent some time on the fix but couldn't figure it out. 

Thanks

**Comment by lacc** [comment]
I'm just going to leave some image here about the original issue:

![image](https://user-images.githubusercontent.com/4140831/51269115-8a36c480-19b9-11e9-930e-7c3084262a47.png)

![image](https://user-images.githubusercontent.com/4140831/51269191-bb16f980-19b9-11e9-9209-6f3dfbaa7e67.png)

**Comment by welsen** [comment]
Hi lacc,

please try to add the `.truncate` to the label not the whole, and maximize the length of your label.

[HTML]

```html
<div class="row">
  <div class="input-field">
    <input id="map-name" class="invalid" maxlength="250" type="text">
    <label class="truncate" for="map-name" data-error="Please enter a value.">This is a very long label to test how the error behaves. Ideally the error should be below the input field. But what happens now is it comes up and does not look good.</label>
  </div>
</div>
```

[CSS]
```css
label.truncate {
  max-width: 100%;
}
```

bests

[check here (jsfiddle)](https://jsfiddle.net/p0bj1fxz/)

**Comment by welsen** [comment]
According to the material you should not do the above described solution, or any. You could separate long labels from the input as hint.

[Material: Text fields: Anatomy > Label text](https://material.io/design/components/text-fields.html#anatomy)

Bests

**Comment by lacc** [comment]
yes you right, I used HelpText instead.
Thanks!
