### ISSUE TITLE
Dropdown doesn't work in nav

### ISSUE THREAD

**Issue by cams03** [Dogfalo/materialize#6262]
Hi there !

I have an issue with dropdown in nav element. The dropdown doesn't work and I have an error in my console. Here's my HTML code : 

    <nav>
		<div class="nav-wrapper">
		   	<a href="#" data-target="mobile-nav" class="sidenav-trigger"><i class="material-icons">menu</i></a>
			 <ul id="nav-mobile" class="left hide-on-med-and-down">
			     	<li class="active"><a href="#" title="Accueil">Accueil</a></li>
			        <li class=""><a href="#" title="Téléchargement" class="dropdown-trigger" href="#!" data-target="dropdown_download">Téléchargement</a></li>
			        <li class=""><a href="#" title="Streaming">Streaming</a></li>
			        <li class=""><a href="#" title="Karaoke">Karaoké</a></li>
			        <li class=""><a href="#" title="Clips">Clips</a></li>
			  </ul>
		</div>
	</nav>
       <ul id="dropdown_download" class="dropdown-content">
		<li><a href="#!">Playlists</a></li>
		<li class="divider"></li>
		<li id="dropdown_styles" class="dropdown-content"><a href="#!" class="dropdown-trigger" href="#!" data-target="dropdown_styles">Styles Musicaux</a></li>
	</ul>

And I have initialized the whole framework with this JS snippet:

    <script>
			M.AutoInit();
    </script>

Here is the error i get in my console:

Uncaught DOMException: Failed to execute 'insertBefore' on 'Node': The new child element contains the parent.
    at HTMLLIElement.<anonymous> (https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/js/materialize.min.js:6:9400)
    at k (https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/js/materialize.min.js:6:2277)
    at g.each (https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/js/materialize.min.js:6:5223)
    at HTMLAnchorElement.<anonymous> (https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/js/materialize.min.js:6:9381)
    at k (https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/js/materialize.min.js:6:2277)
    at g.each (https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/js/materialize.min.js:6:5223)
    at g.insertAfter (https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/js/materialize.min.js:6:9325)
    at g.after (https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/js/materialize.min.js:6:8848)
    at new n (https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/js/materialize.min.js:6:35712)
    at Function.value (https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/js/materialize.min.js:6:11812)

Does someone know where is the problem please?

**Comment by BorthakurUnmilon** [comment]
The anchor tag should be removed in the last second line.
`<nav>
	<div class="nav-wrapper">
	   	<a href="#" data-target="mobile-nav" class="sidenav-trigger"><i class="material-icons">menu</i></a>
		 <ul id="nav-mobile" class="left hide-on-med-and-down">
		     	<li class="active"><a href="#" title="Accueil">Accueil</a></li>
	<li class=""><a title="Téléchargement" class="dropdown-trigger" href="#!" data-target="dropdown_download">Téléchargement</a></li>
		        <li class=""><a href="#" title="Streaming">Streaming</a></li>
		        <li class=""><a href="#" title="Karaoke">Karaoké</a></li>
		        <li class=""><a href="#" title="Clips">Clips</a></li>
		  </ul>
	</div>
</nav>
   <ul id="dropdown_download" class="dropdown-content">
	<li><a href="#!">Playlists</a></li>
	<li class="divider"></li>
	<li id="dropdown_styles" class="dropdown-content">Styles Musicaux</li>
</ul>`

**Comment by BorthakurUnmilon** [comment]
The anchor <a> tag should be removed from the last second line as it is of no use.
`<nav>
	<div class="nav-wrapper">
	   	<a href="#" data-target="mobile-nav" class="sidenav-trigger"><i class="material-icons">menu</i></a>
		 <ul id="nav-mobile" class="left hide-on-med-and-down">
		     	<li class="active"><a href="#" title="Accueil">Accueil</a></li>
	<li class=""><a title="Téléchargement" class="dropdown-trigger" href="#!" data-target="dropdown_download">Téléchargement</a></li>
		        <li class=""><a href="#" title="Streaming">Streaming</a></li>
		        <li class=""><a href="#" title="Karaoke">Karaoké</a></li>
		        <li class=""><a href="#" title="Clips">Clips</a></li>
		  </ul>
	</div>
</nav>
   <ul id="dropdown_download" class="dropdown-content">
	<li><a href="#!">Playlists</a></li>
	<li class="divider"></li>
	<li id="dropdown_styles" class="dropdown-content">Styles Musicaux</li>
</ul>`

**Comment by BorthakurUnmilon** [comment]
The anchor tag should be removed in the last second line as it is of no use.
```<nav>
	<div class="nav-wrapper">
	   	<a href="#" data-target="mobile-nav" class="sidenav-trigger"><i class="material-icons">menu</i></a>
		 <ul id="nav-mobile" class="left hide-on-med-and-down">
		     	<li `class="active"><a` href="#" title="Accueil">Accueil</a></li>
	<li class=""><a title="Téléchargement" class="dropdown-trigger" href="#!" data-target="dropdown_download">Téléchargement</a></li>
		        <li class=""><a href="#" title="Streaming">Streaming</a></li>
		        <li class=""><a href="#" title="Karaoke">Karaoké</a></li>
		        <li class=""><a href="#" title="Clips">Clips</a></li>
		  </ul>
	</div>
</nav>
   <ul id="dropdown_download" class="dropdown-content">
	<li><a href="#!">Playlists</a></li>
	<li class="divider"></li>
	<li id="dropdown_styles" class="dropdown-content">Styles Musicaux</li>
</ul>```

**Comment by acburst** [comment]
your data-target seems to be wrong. Make sure it matches the id of your dropdown content.
