### ISSUE TITLE
For open collapsible change class name to "open" from "active"

### ISSUE THREAD

**Issue by snow01** [Dogfalo/materialize#627]
Hey @Dogfalo - For collapsible's open state, can we change the class name from "active" to "open" ?

**Reason for this suggestion** --
I have collapsible menu items in side bar - by default I keep some level of items open. Now if I use "active" class for this purpose - I also get "active" highlighting for all the open items. 

By keeping "open" class for opened state and keeping "active" synonymous to an active link or similar - we would not face such issue.

Please let me know.

**Comment by snow01** [comment]
Any answers to this ?

**Comment by Dogfalo** [comment]
Our site uses a collapsible in the sidebar and the active class is working well there so I don't see the problem.
