### ISSUE TITLE
When using Tabs, I encountered a problem

### ISSUE THREAD

**Issue by MisterWhoDevelopers** [Dogfalo/materialize#6281]
![gif](https://user-images.githubusercontent.com/24573712/52103455-ba6c9d00-2620-11e9-814b-797271bf872e.gif)

When you maximize the window, there is a residual image

**Comment by CodexLink** [comment]
This seems to be your graphics issue because I saw glitches at the beginning of the gif. Materialize does only render those properties but it doesn't handle rendering of the whole browser or the display. Also, it seems it was not the problem of the Materialize in the end.

**Comment by MisterWhoDevelopers** [comment]
@CodexLink I think that after setting the tab item, I also need to update the item style.
_setTabsAndTabWidth => _updateItemStyle  =>  translateX
