### ISSUE TITLE
logo isnt visible on chrome iphone5

### ISSUE THREAD

**Issue by acburst** [Dogfalo/materialize#63]

**Comment by mccraveiro** [comment]
Is this still an issue? Can you provide more details?

**Comment by chifreaigle** [comment]
@mccraveiro  I dont think its an issue now, @Dogfalo  any updates on this?

**Comment by developeranirudhprabhu** [comment]
@Dogfalo and @acburst Can you confirm if there is an issue? If not mark this closed? Or atleast add some details regarding the issue

**Comment by Dogfalo** [comment]
This is no longer an issue
