### ISSUE TITLE
Dropdown select click triggers keyboard in iOS

### ISSUE THREAD

**Issue by carlosperate** [Dogfalo/materialize#630]
I've tested this in iOS 7, in both chrome and safari.
Touching on a select element dropdown will trigger the iOS keyboard and place the text edit cursor on the text behind the div class `select-wrapper` created by materialized.

**Comment by acburst** [comment]
In the latest release? or on our current master version

**Comment by carlosperate** [comment]
Tested on the master version at the time of posting.
I just tested the materialize website example and it is working fine there.

**Comment by CWLye** [comment]
Hello, the text edit cursor appears in iOS safari and while just a minor issue, I would appreciate if someone has a workaround or solution to this otherwise perfect framework. Thanks!

**Comment by ElpySites** [comment]
Hello,

Did you solve this somehow? I have the same problem and i didn't find solution yet.

**Comment by CWLye** [comment]
Hello,

Instead of a materialize drop down list, I used a usual html drop down list and applied my own styling. 

Regards,
Chuan Wee

**Comment by fega** [comment]
@carlosperate @CWLye @ElpySites Can someone can check if this isn't fixed yet?

Thanks

**Comment by tomscholz** [comment]
These issues are all duplicates:
https://github.com/Dogfalo/materialize/issues/4413
https://github.com/Dogfalo/materialize/issues/4315
https://github.com/Dogfalo/materialize/issues/4306
https://github.com/Dogfalo/materialize/issues/3715
https://github.com/Dogfalo/materialize/issues/3171
https://github.com/Dogfalo/materialize/issues/630

For the future discussion, please use this issue instead.
https://github.com/Dogfalo/materialize/issues/3790
