### ISSUE TITLE
Tooltip positions shifted in horizontally scrolling table

### ISSUE THREAD

**Issue by akemd** [Dogfalo/materialize#6306]
I have a very wide table that uses tooltips in many cells. The table is wider than can be displayed in a browser window so only about half the columns are visible at a time. When the page is scrolled fully to the left, all visible tooltips function properly. When scrolled to the right to reach the other columns, those tooltips will always be displayed at the far right of the screen no matter where the tooltip trigger is.

## Expected Behavior
When scrolling horizontally, tooltips should continue to function properly being displayed next to their trigger.

## Current Behavior
Tooltips that are initially outside the viewport when a page is loaded will display at the far right side of the viewport regardless of the position of its trigger.

## Possible Solution
Issue #5790 was similar to this, but dealing with vertical placement of the tooltips instead of horizontal. A fix was done here: https://github.com/Dogfalo/materialize/commit/c00c954f04ad58bb5e274e9d410811c38492c808

A similar fix can be applied within the checkWithinContainer function in materialize-v1.0.0.js at line 1264. Just after line 1274, I added:

`var containerRight = container === document.body ? Math.max(containerRect.right, window.innerWidth) : containerRect.right;`

Then I changed the current line 1287 to this:

`if (scrolledX + bounding.width > containerRight - offset || scrolledX + bounding.width > window.innerWidth - offset) {`

With that, everything works as expected.

## Steps to Reproduce (for bugs)
https://codepen.io/akemd/pen/GeOMvj
1. Size window so only half the table columns are seen. Tooltips work as expected for the visible triggers when scrolled to the left.
2. Scroll to the right and hover over those tooltip triggers. The tooltip is displayed to the far right.

## Your Environment

* Version used: 1.0.0
* Browser Name and version: Firefox 65.0.2, Chrome 72.0.3626.121
* Operating System and version (desktop or mobile): Windows 10 desktop

**Comment by ValeriaCobianISW** [comment]
Hi @akemd , are you working on this issue? I would like to contribute :D

**Comment by ValeriaCobianISW** [comment]
Hi @akemd , are you working to resolve this issue? I would like to help and contribute :D

**Comment by akemd** [comment]
Sorry for the slow response. Been very busy here. I do not know what more
needs doing. The changes I mentioned in that post are all that are
required. I made the modifications on our installation here and all works
well. I thought the developers would pick it up and incorporate it. Is
there something more needed? Maybe there is an official process to go
through, but this is all new to me. If you know what that process is and
want to take that next step, I would appreciate that. I'm happy to do what
I can and what needs doing to make this small fix a part of the next
materialize release.  -Edward.

**Comment by valeriacobian** [comment]
Thank you for your explanation @akemd , I'm going to try to resolve this issue with your steps.

**Comment by valeriacobian** [comment]
Hi @akemd, I did a pull request for this issue and I used your possible solution and I think it works perfectly!

**Comment by acburst** [comment]
Merged in 1498e0c5
