### ISSUE TITLE
Float label aren't triggered on form edit.

### ISSUE THREAD

**Issue by sturoid** [Dogfalo/materialize#631]
When I enter a form, in edit mode where the form values are pre-filled, the float labels stay in the input until I click inside each input. Is there a way to tell the inputs that there is already a value and the label should be floated? I am on a Mac with Yosemite, and using Chrome.

![screen shot 2015-02-05 at 11 39 27 pm](https://cloud.githubusercontent.com/assets/805554/6075470/47700ccc-ad90-11e4-9796-fb340a6f4bb6.png)

**Comment by Dogfalo** [comment]
Prefilled values will work if they are in the html, but if you are having problems add active to the label class
