### ISSUE TITLE
Select Menu Issue - 2 Mouse Clicks Required to Open Menu

### ISSUE THREAD

**Issue by RichieMcMullen** [Dogfalo/materialize#6318]
I've noticed on Chrome ```Version 73.0.3683.86``` the select menus need 2 mouse clicks to open. On the first mouse click, it flickers and fails to open. It then opens normally on the second mouse click.

This issue can be replicated directly on the materialise website:
[Click to View Issue](http://archives.materializecss.com/0.100.2/forms.html#select)

**Environment Details**
Web Browser: ```Chrome Version 73.0.3683.86```
Materialise Version: ```0.100.2```
OS: ```macOS Mojave Version 10.14.2``` (Desktop)
My Project: https://ardeecc.club/register

Tested this on Firefox & Opera, no issues. 

![ezgif com-video-to-gif](https://user-images.githubusercontent.com/8255180/55293510-31d76680-53ef-11e9-9dba-6c6a8ac8db7c.gif)

**Comment by DeehSlash** [comment]
I'm suffering from the same issue on my project. Does anyone have a quick fix for this?

**Comment by RichieMcMullen** [comment]
Gently bumping this issue!

Very keen to have this issue resolved of will mean having to change framework, something I'd rather not have to do if at all possible.

Thanks in advance!

**Comment by websiteinfo** [comment]
I have the same problem, well, for now mdbootstrap is better option :/

**Comment by Sebastriani** [comment]
The same for me together with #6312 it seems the Chrome update 73 broked a lot of things in materializeccs

**Comment by Dogfalo** [comment]
If upgrading to 1.0.0  is possible for your project, this is currently the best solution for the issue.

**Comment by Sebastriani** [comment]
@Dogfalo Not possible, I'm using v0.98.1 and I customized the hell out of it with SCSS, I would have to diff each file I changed...

**Comment by DanielRuf** [comment]
This is a duplicate issue about a Chrome regression. Also see https://bugs.chromium.org/p/chromium/issues/detail?id=941910#c6

**Comment by websiteinfo** [comment]
> 
> 
> If upgrading to 1.0.0 is possible for your project, this is currently the best solution for the issue.

Ver. 1.0.0 (beta?) without jquery has other problems too :/

**Comment by RichieMcMullen** [comment]
I've reported the issue to ```Chrome Bugs```. There seems to be some activity on the topic, so hopefully they find and fix the issue soon.

Bug Report Tracker: https://bugs.chromium.org/p/chromium/issues/detail?id=947874#c3

**Comment by DanielRuf** [comment]
There was already https://bugs.chromium.org/p/chromium/issues/detail?id=941910#c6

**Comment by websiteinfo** [comment]
Fix in js file (line 1774) add value 100: 

`
        // Add click close handler to document
        setTimeout(function () {
          $(document).on('click.' + activates.attr('id'), function (e) {
            hideDropdown();
            $(document).off('click.' + activates.attr('id'));
          });
        }, 100);
`

**Comment by DanielRuf** [comment]
This is no right fix. Debounce it for example. See https://github.com/amsul/pickadate.js/pull/1140

**Comment by RichieMcMullen** [comment]
> Fix in js file (line 1774) add value 100:
> 
> `// Add click close handler to document setTimeout(function () { $(document).on('click.' + activates.attr('id'), function (e) { hideDropdown(); $(document).off('click.' + activates.attr('id')); }); }, 100);`

That has worked for me. Happy days!
