### ISSUE TITLE
Collapsible documentation error

### ISSUE THREAD

**Issue by jacobq** [Dogfalo/materialize#6332]
The documentation (website) for the "collapsible" component says that the `active` class should be added to the `.collapsible-header` but actually it should be added to the `li` that is the parent of said `.collapsible-header`.

https://github.com/Dogfalo/materialize/blob/c9363571a1fe60168d3833bf2b139b52723b5b04/jade/page-contents/collapsible_content.html#L83

## Steps to Reproduce (for bugs)

1. Do what the documentation says (though not what it actually does)

Example here: https://codepen.io/jacobq_/pen/bJqmZo

## Context

This type of subtle mistake often confuses me and leads to incorrect code.

## Your Environment

* Version used: 1.0.0

**Comment by acburst** [comment]
Fixed in 36ef3493
