### ISSUE TITLE
Carousel fullwidth and indicators not initializing with vanilla java-script

### ISSUE THREAD

**Issue by singhragnar** [Dogfalo/materialize#6341]
Here is my HTML code:

    <h5>Slider Carousel</h5>
    <div class="carousel carousel-slider">
        <a class="carousel-item" href="#one!"><img src="images/1_Farm.jpeg" alt=""></a>
        <a class="carousel-item" href="#two!"><img src="images/2_Herder.jpeg" alt=""></a>
        <a class="carousel-item" href="#three!"><img src="images/8.vegetable.jpg" alt=""></a>
    </div>

And here is my js script:
   <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/js/materialize.min.js"></script>

    <script>
        M.AutoInit();
        var instance = M.Carousel.init ({fullWidth: true, indicators: true});
    </script>

Everything is working fine with jquery though.

**Comment by acburst** [comment]
The Component Init function takes in 2 parameters (elems, options);

try this instead:
```
var carouselEl = document.querySelector('.carousel');
var instance = M.Carousel.init(carouselEl, {fullWidth: true, indicators: true});
```
