### ISSUE TITLE
Field filling via Angular ajax

### ISSUE THREAD

**Issue by ronaldohoch** [Dogfalo/materialize#6347]
when I automatically update a form via angular, Materialize does not verify whether the field is filled or not.

For I can make the label work, I need to focus on the field and the Angular is very expensive and nothing automatic.

See the image below:
![image](https://user-images.githubusercontent.com/2287371/56923551-2ab08080-6aa1-11e9-9ce2-97e5672eae54.png)

## Expected Behavior
Any way to set class "active" when input is filled?

## Current Behavior
The label keep in same place
![image](https://user-images.githubusercontent.com/2287371/56924305-f0e07980-6aa2-11e9-9a13-d887cfdda6be.png)

## Context
Whent editing an ajax form.

## Your Environment

* Version used: 1.0.0.rc.2 in Angular 6
* Browser Name and version: Chrome last
* Operating System and version (desktop or mobile): Windows 10

**Comment by acburst** [comment]
Call `M.updateTextFields();` after your ajax update
