### ISSUE TITLE
Optional push effect for the off canvas sidenav?

### ISSUE THREAD

**Issue by keyscores** [Dogfalo/materialize#635]
Consider having the menu be off canvas, with push effect like here:
http://jasny.github.io/bootstrap/examples/navmenu-push/
and
https://github.com/christophery/pushy
(hass css and jquery fallbacks)

**Comment by Dogfalo** [comment]
We won't be supporting this. It isn't material design and generally has poor performance on mobile devices.

**Comment by dandv** [comment]
In case you want to reconsider this, looks like there's been an update, because http://www.christopheryee.ca/pushy/ specifically mentions "smooth performance on mobile devices".
