### ISSUE TITLE
Select Validation Does Not Display Error

### ISSUE THREAD

**Issue by coding-native** [Dogfalo/materialize#6354]
## Expected Behavior

When given an empty value, the materialize select box should display the red underlining, like the other inputs on a form, and prevent form submit.

## Current Behavior

When given an empty value, the materialize select box only prevents form submit. It does not give any indication to the user that their selection was invalid.

## Steps to Reproduce (for bugs)

1. Either set the Dropdown to invalid, or do nothing
2. Hit submit

Link: https://codepen.io/DigitalShamanism/full/NmQbgq
## Context

Display a placeholder in the options, but trigger the red underlining if the user attempts to submit a form with the placeholder selected.
## Your Environment

* Version used: 1.0.0-rc2
* Browser Name and version: Firefox 66.0.3; Google Chrome 74.0.3729.131
* Operating System and version (desktop or mobile): Windows 7
* Link to your project (if appropriate):

**Comment by ruant** [comment]
Yes please! 😃

**Comment by sparsh-99** [comment]
@jordanParamo I think your JS validation is incorrect. It doesn't have any validation for the invalid input!!!!

**Comment by TravelTimN** [comment]
Custom jQuery and vanilla JS code I've created to fix this issue for my own projects.
Both work like a charm, but it would be fantastic to get proper validation similar to this on the actual framework source code.

https://codepen.io/traveltimn/full/QWyoVOm

**Comment by coding-native** [comment]
> @jordanParamo I think your JS validation is incorrect. It doesn't have any validation for the invalid input!!!!

That makes total sense. I've since gone with a different approach for forms. It seems that I misunderstood what the validation option would allow for, I figured that the default behavior would check that it exists at the very least.

> Custom jQuery and vanilla JS code I've created to fix this issue for my own projects.
> Both work like a charm, but it would be fantastic to get proper validation similar to this on the actual framework source code.
> 
> https://codepen.io/traveltimn/full/QWyoVOm

I like this solution, I think people with the same problem can benefit from reading this code.
