### ISSUE TITLE
Version 1.0.0 - Autocomplete option "limit" bug

### ISSUE THREAD

**Issue by MicheleLucini** [Dogfalo/materialize#6361]
## Expected Behavior
When I set "limit" I expect to see only the desired number of results AND that the results are sorted correctly in relation to the complete list of autocomplete

## Current Behavior
The autocomplete stops at the first "limit amount" positive results of the sort function without looking for possible more relevant elements.

## Possible Solution
Sort the entire list and then show the top "limit amount" of elements.

## Steps to Reproduce (for bugs)
[Pen that shows this behavior](https://codepen.io/Aozora/pen/EzVwra), this autocomplete contains all the countries ordered with this priority:

- Nation name starts with input string
- Nation name contains input string
- Nation with larger population
- Nation name alphabetically

The autocomplete has no "limit".
Try searching for italy by checking the results letter by letter.
Now try setting "limit" to 5 and do the same, the results are completely different.

**Comment by acburst** [comment]
Fixed in e6395fa0
