### ISSUE TITLE
'people' and 'group' icons are the same

### ISSUE THREAD

**Issue by creyD** [Dogfalo/materialize#6362]
# 'people' and 'group' icons are the same
## Expected Behavior
Either separate pictures or only one tag.
*Edit* Same goes for clear and close

## Current Behavior
Both icons are the same as shown on the [icons page](https://materializecss.com/icons.html).

## Possible Solution
Maybe updating one of the icons or possibly removing one tag.

## Steps to Reproduce (for bugs)
1. `<i class="material-icons">people</i>`
2. `<i class="material-icons">group</i>`
3. Both are same, you see?

## Your Environment

* Version used: Current version
* Browser Name and version: Chrome
* Operating System and version (desktop or mobile): Desktop (Windows 10)

**Comment by sawyerbivens** [comment]
yeah, they are because people is basically a group, as people is plural.

**Comment by creyD** [comment]
Yeah, I know the English language myself (as far as this goes), but I don't think that this is a good practice. I mean: it's not like there were multiple of each icon with synonyms or their plurals. Just this one. But if you say this is how it should be...
