### ISSUE TITLE
Text and texarea not working correctly on wrapping label

### ISSUE THREAD

**Issue by icyd** [Dogfalo/materialize#6370]
When working with textarea and textfields, using the input-label element (to make use of the animation), and the label is too long for the line and it wraps around it, the label and the input text overlaps. I think is related with the label being absolute position, kind I workaround it by increasing the _input_ and _textarea_ padding-top value (really dirty fix). There is something I'm missing?

**Comment by acburst** [comment]
You can add the `.truncate` class to the label and it will restrict it to 1 line with ellipsis overflow
