### ISSUE TITLE
How to change header color?

### ISSUE THREAD

**Issue by rust2** [Dogfalo/materialize#6372]
Please, I don't like pink color

**Comment by newavatar00** [comment]
use any color as the class name,

Example : `<nav class="red">   
                </nav> `

**Comment by acburst** [comment]
You can also change the primary color in the sass variables:

https://materializecss.com/sass.html

**Comment by LukeSavefrogs** [comment]
As an alternative to @newavatar00's answer, you can style the element using `background-color`, which is what the `red` class he used internally do like this:

`<nav style="background-color: red"> </nav>`
