### ISSUE TITLE
Changing primary color

### ISSUE THREAD

**Issue by gerharddt** [Dogfalo/materialize#638]
Hi I'm working with materialize and I'm trying to not touch your code, so that I can just upgrade it when a new version arrives, but I want to change the primary color and I can't find an easy way to just switch the whole thing to say the blue palette.

Am I missing something?

**Comment by Dogfalo** [comment]
Look at the variables in Sass

**Comment by jezmck** [comment]
An example in the documentation would be useful. e.g.

    $primary-color: color("blue", "base");

**Comment by Dogfalo** [comment]
This has already been created and will be pushed live at a later date 5317085dda7bfdbb89d02029aea4c3ed7cffe559
