### ISSUE TITLE
drag-target positioned wrong when body using centred flex.

### ISSUE THREAD

**Issue by ChildishGiant** [Dogfalo/materialize#6386]
## Expected Behavior
drag-target shouldn't be affected by the use of flex.

## Current Behavior
drag-target is centred when the body uses flex and `justify-content: center`. This also blocks elements beneath being clicked. Occurs when sidenav is open and closed.

## Possible Solution
This seems to fix the issue for me
```
.drag-target {
  left: 0;
}

```
## Steps to Reproduce (for bugs)
[CodePen](https://codepen.io/ChildishGiant/pen/xNowjX) with a simple example
```
body {
  display: flex;
  justify-content: center;
}
```

## Context
I have centred items on my page but the drag target blocks clicking them.
https://gfycat.com/FrailYellowishIberianchiffchaff
![](https://thumbs.gfycat.com/FrailYellowishIberianchiffchaff-size_restricted.gif)

## Your Environment
* Version used: 1.0.0
* Browser Name and version: Brave 0.64.77
* Operating System and version (desktop or mobile): (Windows 10 17134.472, Desktop & Mobile affected)

**Comment by acburst** [comment]
Fixed in 0573d853
