### ISSUE TITLE
Datepicker opens even with readonly attribute in place

### ISSUE THREAD

**Issue by apazadevlegacy** [Dogfalo/materialize#6398]
Summary:
My datepicker has the attribute readonly, but it doesn't have effect to make it "readonly"

Expected Behaviour:
With readonly in place I expect that the modal doesn't open up.

Current Behavior:
I'm preloading a value, even with a datepicker with "readonly" in place the modal of datepicker opens up, and furthermore when a date gets selected the value changes.

Is there a workaround to make a datepicker truly readonly?

Here a fiddle 
[https://jsfiddle.net/alcidesapaza/ka48jtLw/6/](url)

**Comment by enjoyurrlty** [comment]
Hey!
Just add disabled attribute to your input and you should be fine.
Here is your fiddle forked and with attribute added. 
https://jsfiddle.net/tp21ok6r/

**Comment by apazadevlegacy** [comment]
@enjoyurrlty  that's a great workaround, thanks!
