### ISSUE TITLE
Navbar incorrectly scales

### ISSUE THREAD

**Issue by hazel0177** [Dogfalo/materialize#6402]
When asking general "how to" questions:

- Please do not open an issue here!
- Instead, ask for help on [StackOverflow](stackoverflow.com/questions/tagged/materialize) or in our [Gitter](https://gitter.im/Dogfalo/materialize) channel.

- Read the [CONTRIBUTING document](https://github.com/Dogfalo/materialize/blob/master/CONTRIBUTING.md) Any issues that are violating the contributing guidelines, will be closed!
- [Search for duplicate or closed issues](https://github.com/Dogfalo/materialize/issues?utf8=%E2%9C%93&q=is%3Aissue) and make sure to go through our [labels](https://github.com/Dogfalo/materialize/labels).
- Include a [reduced test case](https://css-tricks.com/reduced-test-cases/) in the form of a Codepen when reporting bugs unless it is not applicable, otherwise your issue will be closed.

## Expected Behavior
The navbar should scale for mobile

## Current Behavior
Itll only keep "logo"
![image](https://user-images.githubusercontent.com/42550681/60201644-a54b1180-9840-11e9-9608-55e786ba5372.png)

## Possible Solution
unsure
## Steps to Reproduce (for bugs)
Zoom in or open page on mobile

## Context
I'm working on a site and I need users to be able to access different parts of the page via the navbar

## Your Environment

* Version used: 1.0(?)
* Browser Name and version: Firefox (latest
* Operating System and version (desktop or mobile): doesnt matter
* Link to your project (if appropriate): tojiru.pw

**Comment by Maqsyo** [comment]
Your drop-down has the class "hide-on-med-and-down", so it hides on medium-screens and down.
https://materializecss.com/navbar.html

If you'd like to inspect a mobile device on firefox, please press F12 to open the developer tools. On the right-side there is a button to test multiple screen-sizes (Ctrl + Shift + M). There you can check multiple devices without zooming.

**Comment by hazel0177** [comment]
The issue is, even the login and register buttons dont show and they dont have it, so...

**Comment by Maqsyo** [comment]
They have it, because of the parent-ul
![image](https://user-images.githubusercontent.com/19644698/60942400-c270ed00-a2e2-11e9-9743-a931ccca1faa.png)

You have there a "nav-mobile", which has the class "sidenav". But the sidenav should be outside of the <nav> and you dont provide a navbar-trigger for mobile, so your users cant trigger the navbar :)

Please check out the documentation
https://materializecss.com/navbar.html
https://materializecss.com/sidenav.html

**Comment by Maqsyo** [comment]
So this isn't an issue und it would b e cool if you could close this one. Also you could ask your questions here more easily: https://gitter.im/Dogfalo/materialize

**Comment by hazel0177** [comment]
I thought it did it automatically, my apologies.
