### ISSUE TITLE
Slider duration not working

### ISSUE THREAD

**Issue by abooks23** [Dogfalo/materialize#6406]
if set `duration: 100` nothing happens
```
$(document).ready(function(){
    $('.slider').slider({    
      indicators: false,
      duration: 100
});
  });
```

**Comment by Maqsyo** [comment]
https://materializecss.com/carousel.html

Materialize only has a Carousel.
Hope that helps you

**Comment by abooks23** [comment]
this https://materializecss.com/media.html ?

**Comment by Maqsyo** [comment]
Ahh sorry. haven't seen this...

is there any error-message?

**Comment by nezerk** [comment]
I use duration option without any problem.
Note that,
duration is used for 3 animations:
- slide transition
- indicator transition
- caption transition

There is also "interval" which sets the time  between each slides.
(May be that is what you are looking for)

Both of these options are defined in ms , and 100 is only 0.1 second.
your reference setting  should behave as:
- make each slide appear in 0.1 seconds (you will not see this transition)
- move caption in 0.1 seconds to it's aligned place
- start a new slide every 6100 ms (default value 6000 + 100)

if this resolves your problem, please close this issue.

**Comment by abooks23** [comment]
thanks
