### ISSUE TITLE
Dropdown error: Error: javascript:; is not an HTML Element

### ISSUE THREAD

**Issue by NicolasMelin** [Dogfalo/materialize#6411]
Hi everyone,

I have recently decided to migrate my project in materialize 1.0.0 (before it was in materialize v0.100.2).

I have read and apply the migration documentation from materialize official github repository : https://github.com/Dogfalo/materialize/blob/v1-dev/v1-changelog.md

In the user point of view it's seem to be ok, but I have an error in my web développement console: "Error: javascript:; is not an HTML Element"

![Capture](https://user-images.githubusercontent.com/13767020/61130723-af634600-a4b7-11e9-9119-2047b02d06cc.JPG)

My HTML code is :

```html
<ul>
   <li style="display: none;"></li>
   <li>
        <a href="javascript:;" class="dropdown-trigger family" data-target="mytarget" unselectable="on">
            <i class="fa" unselectable="on">ICON</i>
        </a>
        <ul id="ID" class="dropdown-content" tabindex="0">
            <li tabindex="0">
                <a href="#!" title="" unselectable="on">
                    <i class="fa" unselectable="on"></i>
                    <span>LABEL</span>
                </a>
            </li>
            <li tabindex="0"></li>
        </ul>
    </li>
</ul>
```

And my javascript trigger is :

```javascript
$(document).ready(function(){
            let dropdownTrigger = document.querySelectorAll('.dropdown-trigger');

            M.Dropdown.init(dropdownTrigger, {
                inDuration: 300,
                outDuration: 225,
                constrainWidth: false, // Does not change width of dropdown to that of the activator
                hover: true, // Activate on hover
                gutter: 0, // Spacing from edge
                belowOrigin: false, // Displays dropdown below the button
                alignment: 'left', // Displays dropdown with edge aligned to the left of button
                stopPropagation: false // Stops event propagation
            });
});
```

So, functionally it's ok, it's works, but I want understand why I have this error and fix it !

Thanks by advance for your help.

Best regards.

**Comment by Maqsyo** [comment]
Please change your href in your a-tag to `href='#'` and try it out again
https://materializecss.com/dropdown.html

**Comment by NicolasMelin** [comment]
> Please change your href in your a-tag to `href='#'` and try it out again
> https://materializecss.com/dropdown.html

Hi Maqsyo,

Thanks for your response.

I have try this, but have the same error : `Error: # is not an HTML Element`.
I have also try to remove the href and I have again the same error : `Error:  is not an HTML Element`.


I don't understand the error !

If you have another idea, I'll take it :).

**Comment by Maqsyo** [comment]
oh yeah.. i made a codepen and could figure it out really fast
https://codepen.io/anon/pen/zVVdxb?editors=1010

data-target="mytarget" has to be the id of your dropdown
so it should be data-target="ID"

**Comment by Dogfalo** [comment]
You are using the init on the array and not the HTML element

**Comment by NicolasMelin** [comment]
Hi all,

Thanks for your responses, but I have again the problem.

I think it's caused by "dropdown" because I have a similar error when I call : `M.FormSelect.init(elems, options); ` and my select doesn't work. The issue in console is: `Error: [object HTMLSelectElement] is not an HTML Element`.
The first option is displayed, but when a click on it, the dropdown options is not displayed :/.

Have you a similar issue ?

**Comment by NicolasMelin** [comment]
Hello,

I found my problem. I had a js/css conflict with an other lib called "Rapael.js".
