### ISSUE TITLE
Float label don't work if text change from javascript code

### ISSUE THREAD

**Issue by rootflood** [Dogfalo/materialize#6416]
hi, thanks for awesome and simple ui

in fact when i write a text into text box via java script then float label don't go up
i put a sample in here: https://github.com/rootflood/materializeSample

## Environment
* Version used: materialize v1.0.0
* Mozilla Firefox quantum 68.0.1 (64-bit)
* win 7 desktop

**Comment by acburst** [comment]
Try using `M.updateTextFields();` when programmatically updating fields
