### ISSUE TITLE
SideNav's 'full' not working?

### ISSUE THREAD

**Issue by jett0423** [Dogfalo/materialize#642]
I've been browsing the documentation (http://materializecss.com/side-nav.html) and I'm not really sure on this one since it doesn't have any screenshot. But in my understanding, it should show the hamburger icon all the time for all screen sizes to make it 'openable', right?

On top of that, I'm trying to implement a fixed navbar

Here's my code if necessary.
http://pastebin.com/5VjGK4TH

**Comment by mylastof** [comment]
element '.navbar-fixed' make collapse sideNav() not work

**Comment by jett0423** [comment]
solved in the latest release. you guys are awesome :)
