### ISSUE TITLE
Anchor button disappeared M.FloatingActionButton on collapsible div

### ISSUE THREAD

**Issue by weasteam** [Dogfalo/materialize#6426]
## Expected Behavior
When I put a FAB inside a collapsible div, the anchor button disappeared after I click or hover on to it. It supposes to stay as demonstrated at https://materializecss.com/floating-action-button.html.
See the example code:
```
                <ul class="collapsible">
                  <li class="active">
                    <div class="collapsible-header"><i class="material-icons">filter_drama</i>First</div>
                    <div class="collapsible-body">

                        <div class="fixed-action-btn">
                          <a class="btn-floating btn-large red">
                            <i class="large material-icons">mode_edit</i>
                          </a>
                          <ul>
                            <li><a class="btn-floating red"><i class="material-icons">insert_chart</i></a></li>
                            <li><a class="btn-floating yellow darken-1"><i class="material-icons">format_quote</i></a></li>
                            <li><a class="btn-floating green"><i class="material-icons">publish</i></a></li>
                            <li><a class="btn-floating blue"><i class="material-icons">attach_file</i></a></li>
                          </ul>
                        </div>
                    </div>
                  </li>
                  <li>
                    <div class="collapsible-header"><i class="material-icons">place</i>Second</div>
                    <div class="collapsible-body"><span>Lorem ipsum dolor sit amet.</span></div>
                  </li>
                  <li>
                    <div class="collapsible-header"><i class="material-icons">whatshot</i>Third</div>
                    <div class="collapsible-body"><span>Lorem ipsum dolor sit amet.</span></div>
                  </li>
                </ul>
```

## Current Behavior
The Anchor button disappeared together with other child buttons. I guess the code tread all `btn-floating` inside a `ul` as child buttons. In other words, the `<ul class="collapsible">` make the code not able to find the correct child buttons.

## Possible Solution
Update the searching query for the child buttons at button.js for `ul .btn-floating`

## Steps to Reproduce (for bugs)
1. Copy the above code to a html
2. add javascript to trigger `M.FloatingActionButton.init` as described at https://materializecss.com/floating-action-button.html
3. Mouse over and the anchor button will disappear

## Your Environment
* Version used: 1.0.0
* Browser Name and version: Chrome
* Operating System and version (desktop or mobile): Mac

**Comment by acburst** [comment]
Fixed in 235e9ec7
