### ISSUE TITLE
[Bug] overflow: hidden remain when twice init modal then invoke close 

### ISSUE THREAD

**Issue by Matrixbirds** [Dogfalo/materialize#6429]
I was using modals module. and I defined two buttons and each of them has it's own event callback like below.
```javascript
$(function () {
  M.Modal.init();
  $("#button_a").on("click", function (event) {
     M.Modal.init($("#same_modal")[0]).close();
  });
  $("#button_b").on("click", function (event) {
     M.Modal.init($("#same_modal")[0]).close();
  });
})
```
and i click the `button_a` or `button_b` both would close the modal. but the body attributes="overflow: hidden" will not be removed.

**Comment by acburst** [comment]
You are not invoking the methods correctly. First off you need to pass an element to the Modal init, then you need to store the instance and call the close method from that:

```
$(function () {
  var instance = M.Modal.init($("#same_modal"))[0];
  $("#button_a").on("click", function (event) {
     instance.close();
  });
  $("#button_b").on("click", function (event) {
     instance.close();
  });
})
```
