### ISSUE TITLE
Missing Syntax

### ISSUE THREAD

**Issue by choraria** [Dogfalo/materialize#6437]
### Forms > [Select](https://materializecss.com/select.html) > Options > dropdownOptions

Here, the **dropdownOptions** is supposed to be an object; however, what's the format of this object? Can't find it on the documentation.

Unlike that of [Chips](https://materializecss.com/chips.html) where we have a similar parameter called **autocompleteOptions** - which too accepts an object -  **dropdownOptions** is not accepting the following:

```
data: {
  'Apple': null,
  'Microsoft': null,
  'Google': null
}
```

- replaced `data` with `option` & `options` but that doesn't work either
- removed the `data` part altogether and it still doesn't work

This is how I'm structuring the select **options** without the `data` part:
```
var selectOptions = {
 dropdownOptions: {
    'Apple': null,
    'Microsoft': null,
    'Google': null
  }
}
```

### Requirement
Instead of creating hard coded options within html (as below) -
```
<option value="1">Option 1</option>
<option value="2">Option 2</option>
<option value="3">Option 3</option>
```
I want to dynamically feed in option and their values from a spreadsheet.

**Comment by mxdpeep** [comment]
populate the <select> DOM structure programmatically like here: https://www.geeksforgeeks.org/html-dom-select-object/

**Comment by choraria** [comment]
@mxdpeep - thanks for the assist but I also tried adding <option> tags programatically but for some reason, it doesn't initialise for materialize **select**.

Hoping to simply use the **options > dropdownOptions** that's been referred to here - https://materializecss.com/select.html

Just need the syntax for it :)

**Comment by choraria** [comment]
A colleague of mine helped me with this instead -

```
$.each(optionsJSON, function(index, data) {
    $('#optionsSelect').append($('<option/>', {
        value: data,
        text: data
    }));
});
```

An application of this can be found [here](https://github.com/schoraria911/google-apps-script/blob/master/Materialize%20CSS/Autocomplete/Index.html#L55).

Worked like a charm but I still hope that there's an official solution on how to make use of `dropdownOptions` directly too (like we do it in Chips).

**Comment by DanielRuf** [comment]
According to the code it should be a selector or DOM collection.

**Comment by acburst** [comment]
the dropdownOptions object is supposed to be used to customize the dropdown the select uses. So the syntax would be the options from the dropdown component. It is not used to define the actual option elements.
