### ISSUE TITLE
[Request] Another screen size

### ISSUE THREAD

**Issue by MarhyCZ** [Dogfalo/materialize#644]
Hi, is it possible to add another screen size for 1200px and larger? It would allow better responsive design. Thanks :)

**Comment by linusodenring** [comment]
+1 I would also like it!

**Comment by MarhyCZ** [comment]
Now we are two :D

**Comment by KBoisvert** [comment]
On my side I would like a xs for phone, 600px is more for tablet.  I would say 360px or something around that.  Thanks!

**Comment by carlosperate** [comment]
I think that is the whole point, below 600px will be a phone, between 600 and 990 (or whatever it is) it would be tablets.

**Comment by KBoisvert** [comment]
ok I might be using a wrong way to test when I just resize my browser.  When I see my site at 500 for exemple, it doesn't make sense to have my box align on one column but at this size it would be a phone in a landscape size so it make sense then.  Thanks, I'll see it differently now :)

**Comment by MarhyCZ** [comment]
Just want to make my request clear :) - that interval 900-1200px would be for pc with smaller screens, because there are still 1024x768 out there(especially in my school where I want to use it).

**Comment by Licorb** [comment]
Imo the limit for desktop is right there, 1024. The number of display resolutions above 1366 is growing fast. 992px is way to small for a desktop, would be nice to have a xl (maybe above 1280 or 1366)

"As of today, 99% of our visitors have a screen resolution of 1024x768 pixels or higher:" W3Schools.com

**Comment by Dogfalo** [comment]
A 600px cutoff allows it to encompass all phones (iPhone5 has a width of 568px). We may look into extra large screen size

**Comment by Amonstyle** [comment]
@MarhyCZ  i can create large screen size :p 
Demo here http://jsfiddle.net/mxzuuknz/

Screen size with .sl = large size > 1200px
.s .m .l .sl

**Comment by MarhyCZ** [comment]
Nice! That's exactly what I intended. Great work! :)

**Comment by Amonstyle** [comment]
just wrong link sorry demo here http://jsfiddle.net/mxzuuknz/1/

**Comment by ramijarrar** [comment]
+1 for an extra large size

**Comment by yaserjarrar** [comment]
+1 This would be neat.

**Comment by serkandurusoy** [comment]
+1 for both an `xl` and an `xs` size for `>1200` and `<360` respectively.

**Comment by MarhyCZ** [comment]
Altough @Amonstyle  solution is working, it would be nice to have it baked right into the official materializecss :)

**Comment by CNSKnight** [comment]
+1
> +1 for both an xl and an xs size for >1200 and <360 respectively.

**Comment by Bana0615** [comment]
+1

**Comment by foocp** [comment]
+1

**Comment by codeshards** [comment]
+1

**Comment by WebStar007** [comment]
Thanks for CNSKnight..
+1 for both an xl and an xs size for >1200 and <360 respectively.

**Comment by RoarG** [comment]
+1

**Comment by zanechua** [comment]
+1

**Comment by Bana0615** [comment]
+1 for both an xl and an xs size for >1200 and <360 respectively. this fw would be so much better if the grid was updated. Keep up the good work!!

**Comment by gabga** [comment]
+1

**Comment by ingmferrer** [comment]
+1

**Comment by radarsu** [comment]
+1, difference between 1000px and 1200px is huge.

**Comment by mayvazyan** [comment]
+1

**Comment by zanechua** [comment]
Not sure why this still isn't default.

**Comment by GorgonsMaze** [comment]
+1

**Comment by sebastienvermeille** [comment]
+1 do it please !

**Comment by jansent** [comment]
+1

**Comment by niittymaa** [comment]
+1...

**Comment by damian483** [comment]
+1

**Comment by AGPDev** [comment]
+1

**Comment by acburst** [comment]
Added in 104da64

**Comment by agarwalvinit** [comment]
Hi is the screen size customizable ? I mean can I create my own grid for screen size 1300px and above ? If yes how ? If no then what tweak can I use to achieve that. Thanks!

**Comment by sebastienvermeille** [comment]
@agarwalvinit would be nice to create a dedicated topic for your question.

1) It is not related to this feature request
2) Everybody that talked on this thread is notified for nothing because of **your laziness**.

**Comment by karthiksen92** [comment]
I face problem in lower size device compared to higher size. I feel, to solve the problem if there is smaller size option like bootstrap will be good. 

- Extra Small
- Small
- medium
- Large
- Extra Large
