### ISSUE TITLE
Mac Safari - No centering for icons inside navbar 

### ISSUE THREAD

**Issue by diegogarciar** [Dogfalo/materialize#6450]
The icons using <i class="material-icons" > are not centered vertically on a navbar while using safari on a mac

The icon should be centered vertically as in Chrome

Here is my codepen, It works on any browser it. But not when I copy the code into an html file and open it on safari
https://codepen.io/diegogarciar/pen/BaBbMre

**Comment by Dnguye92** [comment]
Can you take a screenshot of what you're seeing in Safari because everything seems centered for me.

**Comment by diegogarciar** [comment]
Sure! BTW I'm using Safari 13.0.1 on Mac. I also tried on iOS 13 safari and had the same issue.

<img width="1438" alt="Screen Shot 2019-09-26 at 7 27 55" src="https://user-images.githubusercontent.com/17276155/65692068-2fb53400-e02f-11e9-8f78-6f27c3c37ccd.png">

**Comment by pwcreative** [comment]
@diegogarciar 

You got some crazy markup going on here which is causing your problems. You have a floating button inside a li - which is not documented anywhere in the docs.

The class of btn-floating is specifically used to allow an a tag to overhang it's container. So it is not a problem with Safari or Materialize but your own code.

A quick fix in safari would be to display flex on the ul:


```
ul {
display: flex;
align-items: center;
}
```

**Comment by diegogarciar** [comment]
Thanks for the help @pwcreative. I was actually following a [tutorial](https://youtu.be/R3-jcIVW4og?t=39). I'm glad its not a bug then.
