### ISSUE TITLE
Autocomplete dropdownOptions

### ISSUE THREAD

**Issue by rmountjoy92** [Dogfalo/materialize#6457]
So with select fields I can init with: 
`$('select').formSelect({
    dropdownOptions:{
      container: document.body,
    }
  });`

which makes it so if the select is in a modal, it doesn't clip the dropdown/ affect the modal's size. Here's a screenshot of this working correctly:
![image](https://user-images.githubusercontent.com/34513134/66255566-05602680-e753-11e9-974f-3aab72441db0.png)

When trying the same with autocomplete, the dropdownOptions option is ignored. Here is the init i am using:
`$(this).autocomplete({
        data: options_list,
        dropdownOptions:{
          container: document.body,
        }
      });`

Which results in this:
![image](https://user-images.githubusercontent.com/34513134/66255579-32acd480-e753-11e9-87c2-2f342168e461.png)

How do we set the dropdown container for autocomplete elements?

**Comment by pwcreative** [comment]
@rmountjoy92 - a word of advice: modals are meant for small amounts of content, and you will run into trouble on some devices displaying lengthy complex content like this. What does this look and feel like on mobile? If you are in a situation where you need to scroll inside a modal, then you need to consider having the content displayed on a page in a standard way. Some touchscreen devices won't recognise the scroll at all. Sometimes simple is better. Sometimes boring is better!

That said, if you must use a modal in this way, you'll need to show a live example or code pen. It is purely a styling issue.

**Comment by rmountjoy92** [comment]
I use modals for forms all throughout my app and they work great for that purpose, they are a great solution for content that I need to pop up and hide when done. The only thing I am struggling with is autocomplete dropdowns. Though most of my site works well on mobile (including my modal forms), I have a different solution for mobile access to my app, so it is not my priority. Here is a pen to demonstrate what I am explaining in my original post (press 'a' in the autocomplete field):
https://codepen.io/rmountjoy/pen/xxxxrGx

**Comment by pwcreative** [comment]
They might work great for you but they might not work great for every user. You have been warned! ;)

I'm not 100% sure what you're trying to achieve but if you want the content of the dropdown to flow outside of the modal, you need to add this rule:

```
.modal {
  overflow: visible !important;
}
```

Forked amended Codepen:

https://codepen.io/doughballs/pen/QWWWgMZ

**Comment by pwcreative** [comment]
@rmountjoy92 did this fix the issue for you?

**Comment by acburst** [comment]
Added dropdownOptions to autocomplete component in cee8eac2
