### ISSUE TITLE
Add color palette generation function

### ISSUE THREAD

**Issue by Dogfalo** [Dogfalo/materialize#646]
Would it be useful to people if you could create a palette using a Sass function?

ex: pass in a hex color (#9c27b0) to generate a custom palette
![](http://puu.sh/fE4QH/6698c90d12.png)

**Comment by jhuenges** [comment]
+1

**Comment by Dontorpedo** [comment]
yes

**Comment by zigy** [comment]
+1

**Comment by linusodenring** [comment]
+1

**Comment by Sithdown** [comment]
+1

**Comment by kanle485** [comment]
+1

**Comment by Dogfalo** [comment]
Will not be added.
