### ISSUE TITLE
$color_type missing...

### ISSUE THREAD

**Issue by AndrewDurocher** [Dogfalo/materialize#6460]
When compiling the scss with grunt ; grunt throws:
`Error: Invalid CSS after ".blue.": expected class name, was "#007bff"
        on line 14 of ../_materializecss/_color-classes.scss`

Line 14 reads:
`      .#{$color_name}.#{$color_type} `

I have scanned all folders for the text $color_type and no definition exists, only exists in the _color-classes.scss which is trying to use the variable. 

As you can see its trying to append an additional class to $color_name without defining the variable.  So as a result you cannot compile the scss using the provided files within version/download on the main website at this specific time.   For now I'll have to use the entire package, pre-compiled and minified css for my project.  Hoping to change this in the future to trim things down a bit.

**Comment by doughballs** [comment]
Why are you using grunt to compile sass? If you use vscode or coda you can compile your css that way. You can choose which components to use and then include them at the top of your sass file and then compile it all down into one stylesheet. Let me know if you need any more in depth instructions.

**Comment by AndrewDurocher** [comment]
Node is used to install grunt.. Its a cli. I'm on a windows machine. It's not really that uncommon 
https://www.npmjs.com/package/grunt-sass
With 88k weekly downloads.  I can comment and uncomment as u suggested. 

The variable is not defined.

**Comment by doughballs** [comment]
I’ll try to recreate your issue but I’m on a Mac.

I know it’s not uncommon to use grunt to compile sass, but from a workflow point of view, it makes sense to me to compile css in the editor as I go along. I’m in the editor, building the site, creating my stylesheet...this stylesheet is getting compiled down from sass to css a lot of times, as I progress. Maybe there’s a better way but this works for me. If this is a genuine issue though then it should stay open but I can’t replicate on mac.

**Comment by pwcreative** [comment]
@AndrewDurocher I think the error could be on your side - colour_type refers to the base value for each colour in _color-variables.scss. Every time I compile Sass it calls this function and works fine for me. Have you made changes to  _color-variables.scss? I ran into a similar issue when trying to strip out all the extra color classes (which I never use), and figured out you can delete everything apart form the base - that will break the compilation. Keep as follows fro reach color, and keep all references to shade:

> $materialize-red: (
>   "base":       #e51c23
> );

**Comment by AndrewDurocher** [comment]
I took a fresh copy and it seems to be working now, strange. Possibly due to a corrupted installation initially.  Thanks to all.

**Comment by zourite** [comment]
I have a same error i found not solution

**Comment by AndrewDurocher** [comment]
> I have a same error i found not solution

@zourite simply download/install it again worked for me, consider removing it from your project before reinstalling.
