### ISSUE TITLE
Tooltips default options

### ISSUE THREAD

**Issue by HugoGGuerrier** [Dogfalo/materialize#6468]
In the doc of 1.0.0 the tooltips default exitDelay is 0 but in fact it's 200. On the same way, the tooltips default enterDelay should be 200 but it's 0.

## Expected Behavior

```
let tooltip = M.Tooltip.init(elem);
console.log(tooltip.options.enterDelay);
console.log(tooltip.options.exitDelay);
```

shows

```
200
0
```

## Current Behavior

```
let tooltip = M.Tooltip.init(elem);
console.log(tooltip.options.enterDelay);
console.log(tooltip.options.exitDelay);
```

shows

```
0
200
```

## Possible Solution

Change the default value or the doc.

**Comment by acburst** [comment]
Good catch
