### ISSUE TITLE
characterCounter not working by following documentation

### ISSUE THREAD

**Issue by w3bdesign** [Dogfalo/materialize#6487]
# Expected Behavior
Expect the characterCounter to work by following the documentation.

## Current Behavior
It is not working, it is saying that characterCounter is not a function.

## Possible Solution
I eventually got it to work by using this code:
```
var textNeedCount = document.querySelectorAll('.validate.center-align.inputfield');
M.CharacterCounter.init(textNeedCount);
```

## Steps to Reproduce (for bugs)
```
<!-- Compiled and minified JavaScript -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/js/materialize.min.js"></script>    
    <script src="https://code.jquery.com/jquery-3.4.1.min.js"
        integrity="sha256-CSXorXvZcTkaix6Yvo6HppcZGetbYMGWSFlBw8HfCJo=" crossorigin="anonymous"></script>
    <script>
        $(document).ready(function () {          
            $('.validate.center-align.inputfield').characterCounter();           
        });
    </script>
```

**Comment by arnaumanyosa** [comment]
It's a problem loading the libs, add jQuery first

```
<!-- Compiled and minified JavaScript -->
<script src="https://code.jquery.com/jquery-3.4.1.min.js"
        integrity="sha256-CSXorXvZcTkaix6Yvo6HppcZGetbYMGWSFlBw8HfCJo="crossorigin="anonymous">
<script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/js/materialize.min.js"></script>    </script>
<script>
   <!-- my code blablabla -->
</script>
```

**Comment by w3bdesign** [comment]
> 
> 
> It's a problem loading the libs, add jQuery first
> 
> ```
> 
> <script src="https://code.jquery.com/jquery-3.4.1.min.js"
>         integrity="sha256-CSXorXvZcTkaix6Yvo6HppcZGetbYMGWSFlBw8HfCJo="crossorigin="anonymous">
> <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/js/materialize.min.js"></script>    </script>
> <script>
>    
> </script>
> ```

@arnaumanyosa Is it possible to do it without jQuery and just vanilla Javascript, or is jQuery a requirement?

**Comment by arnaumanyosa** [comment]
> @arnaumanyosa Is it possible to do it without jQuery and just vanilla Javascript, or is jQuery a requirement?

I'm totally new on this but I guess is not necessary. Anyway you should always check the documentation

https://materializecss.com/getting-started.html

(and close this issue :D )
