### ISSUE TITLE
tooltip mot working in electron

### ISSUE THREAD

**Issue by edazpotato** [Dogfalo/materialize#6490]
I'm using materialize in my `electron` + `node.js` program, and everything except tooltips are working for me.

here is my code:
```html
<a onclick="newItem()" class="btn tooltipped waves-effect center" data-position="bottom" data-tooltip="CTRL + N">Add Target</a>
```
```js
        //some stuff for matarialize
        document.addEventListener('DOMContentLoaded', function() {
            var elems = document.querySelectorAll('.tooltipped');
            var instances = M.Tooltip.init(elems, options);
        });
```

**Comment by Treverix** [comment]
Can't confirm - I do the same with electron and tooltips work as expected (materializecss version: 1.0.0)

Maybe we can help if you provide more information, like versions and if there's errors on the devtools console.
