### ISSUE TITLE
Evaluation of materialize

### ISSUE THREAD

**Issue by fabienrohrer** [Dogfalo/materialize#6491]
Hi everyone,

I'm trying to evaluate the use of Materialize for many of the websites I maintain. I mainly have 2 fears:
1. Development seems to be stagnating, there are only a few recent commits on GitHub, and many unanswered open issues.
2. I saw several bugs in the examples when trying from my iPhone SE up-to-date (overlapping menu icon, bad position of the FeatureDiscover, Parallax flickering, etc.)

Can you reassure me on these 2 points?

**Comment by cbastienbaron** [comment]
view #6331 , this pkg seems abandonned :sob:

**Comment by fabienrohrer** [comment]
Thank you for the answer.

OMG this is a pity, it was a so good alternative to bootstrap...
