### ISSUE TITLE
date picker only goes back 10 years

### ISSUE THREAD

**Issue by nh916** [Dogfalo/materialize#6499]
the date picker only goes back 10 years at a time. It shows years from 2020 to 2010. The hack i found around it is to pick a date and then reopen and go back another 10 years. That is not intuitive and users would be lost and frustrated easily. The years should go back more than 10 years easily

**Comment by pwcreative** [comment]
@nh916 did you read the documentation?

https://materializecss.com/pickers.html

You can initialize the datepicker with options, one of which is yearRange, which by default is 10.

`$('.datepicker').datepicker({yearRange: 20});`
