### ISSUE TITLE
Select dropdown stays contained in parallax section

### ISSUE THREAD

**Issue by ReevMich** [Dogfalo/materialize#6504]
## Expected Behavior

What i think should happen is the select dropdown should be opened outside the containing parallax wrapper div, so it doesnt move the other content within that div.

## Current Behavior

In the example i have select that has many options just to reproduce. Plus a H2 tag above the select dropdown. When the select dropdown is opened, it pushes the H2 tag outside the view of the div.
![image](https://user-images.githubusercontent.com/7333415/72228603-cc172e00-356d-11ea-8570-854ab6001ce6.png)
After Select dropdown was opened (notice the H2 element is no longer in view)
![image](https://user-images.githubusercontent.com/7333415/72228615-e3eeb200-356d-11ea-81e5-2c7cebc346f0.png)

## Steps to Reproduce (for bugs)

1. Reproduced CodePen: https://codepen.io/ReevMich/pen/mdyKJzw?editors=1010
2. Create a Parallax Section
3. Place Select Dropdown with a long list of options
4. Open Select dropdown and it will push the content up in the div.

## Your Environment

* Version used: 1.0.0
* Browser Name and version: Chrome
* Operating System and version (desktop or mobile): Windows 10
* Link to your project (if appropriate):

**Comment by pwcreative** [comment]
I don't think this is a bug.

You can't have the select dropdown 'open outside the containing parallax wrapper div' as you request. Parallax containers have overflow set to hidden, which is how they work - the have a restricted height (500px default), and the rest of the content outside of this height is hidden, and is only seen on scroll, through the 500px 'window'. Anything you put inside a parallax container is subject to overflow:hidden.

Quick solution is to restrict the height of .dropdown-content. Doesn't make sense to have a huge scrollable list anyway - would be pretty terrible on mobile.

https://codepen.io/doughballs/pen/QWwBjGz

**Comment by ReevMich** [comment]
@pwcreative thanks for the suggestion
