### ISSUE TITLE
Materialize doesn't work for those following the download and setup steps.

### ISSUE THREAD

**Issue by JordanPritt** [Dogfalo/materialize#6509]
## Expected Behavior
Materialize CSS to work as shown on the documentation page, such as: modals popping up, tabs with indicators, hover-able items to appear on hover, etc...

## Current Behavior
Most of the component's functionality are severely lacking or not working all together.

## Possible Solution
Not sure why the downloadable version doesn't work, no JS or CSS errors in console. Can't really suggest more than to just *fix* it.

## Steps to Reproduce (for bugs)
example code pen with tabs and modal: https://codepen.io/CoderLee/pen/xxbvNWQ
1. Download materialize zip folder.
2. Extract files and follow setup steps for adding to an HTML document.
3. Serve document or open in browser directly.
4. With document in browser try to use any of the functionality that's expected.

## Context
This is stopping my use of Materialize CSS on all application development.

## Your Environment
* Version used: 1.0.0
* Browser Name and version: Edge, Chrome, FireFox, Brave
* Operating System and version (desktop or mobile): Windows 10 and MacOS Mojave
* Link to your project (if appropriate): https://codepen.io/CoderLee/pen/xxbvNWQ

**Comment by roiLeo** [comment]
Please read [this](https://materializecss.com/auto-init.html) page.

**Comment by pwcreative** [comment]
Yeah it always helps to read the instructions first 😂

Alternatively, you can initialize components on a per component basis, as per the docs. Check the page for the component you're using to see if you need to initialize.

https://materializecss.com/modals.html

```
$(document).ready(function(){
    $('.modal').modal();
  });
```

https://materializecss.com/tabs.html


```
  $(document).ready(function(){
    $('.tabs').tabs();
  });
```

**Comment by JordanPritt** [comment]
The Doc's **_Getting Started_** should probably have a "page setup" explanation too, but I digress. Thanks for pointing out what I missed!

**Comment by pwcreative** [comment]
@JordanPritt the docs could sure use a bit of work
