### ISSUE TITLE
Development

### ISSUE THREAD

**Issue by Chrisx84** [Dogfalo/materialize#6515]
is anyone actually developing this framework anymore? its been over a year since the last update and the only commits to it since have been for patreon.

So what is going on with the development of Materialize?

**Comment by Maqsyo** [comment]
https://github.com/Dogfalo/materialize/issues/6441
https://github.com/Dogfalo/materialize/issues/6319
https://github.com/Dogfalo/materialize/issues/6243

i think this says enough 🤷‍♂

**Comment by pwcreative** [comment]
It's a funny one...

One the one hand, a new release would be so, so good for everyone involved:

People like new things
The old things need fixing (eg [iOS Select](https://github.com/Dogfalo/materialize/issues/6464))

Also it would be really great to have the team active - jumping on issues, growing the community etc.

But, on the other hand...it already gives me everything I need. Even in this partially-abandoned state it is preferable to Bootstrap, IMO. Just take a second to process the gravitas of that statement...

Would I like an update? Yes. Do I need one? No.

I live in hope 🤞

**Comment by Chrisx84** [comment]
June and still nothing. Not even a F OFF from the dev team.

**Comment by DanielRuf** [comment]
https://github.com/Dogfalo/materialize/issues/6438#issuecomment-623013486

Additional maintainers and contributors are very welcome. I plan to move this forward as the current maintainers of materializecss showed no real interest to cooperate or bring things forward together.

**Comment by ChildishGiant** [comment]
There's since been 29 commits to [materializecss/materialize](https://github.com/materializecss/materialize) and it seems that that will be the place for all future developments.
