### ISSUE TITLE
Scrollable tabs

### ISSUE THREAD

**Issue by Sithdown** [Dogfalo/materialize#654]
Tabs should be [scrollable](http://www.google.com/design/spec/components/tabs.html#tabs-types-of-tabs).

>The maximum number of tabs is limited by the view’s width. Fixed tabs have equal width, based on the widest tab label. To navigate between fixed tabs, touch the tab or swipe the content area left or right.

**Comment by Sithdown** [comment]
It might be the same issue as in #487.

**Comment by Dogfalo** [comment]
Yes it is a duplicate.
