### ISSUE TITLE
move away from jQuery?

### ISSUE THREAD

**Issue by trymeouteh** [Dogfalo/materialize#6559]
Will Materialize move away from jQuery? I know it is useful but I think it is better if Materialize had no dependencies and JavaScript has come a long ways, making it so jQuery is not needed for developing JS quickly.

Or even to have Materialize not require jQuery and have a optional jQuery integration JS script to allow people to use jQuery with Materialize if they wish.

**Comment by Dogfalo** [comment]
jQuery has already been removed

**Comment by trymeouteh** [comment]
Does Materialize require any dependencies?

**Comment by doughballs** [comment]
@trymeouteh no dependencies. You can serve materialize.js and away you go.
