### ISSUE TITLE
Multilanguage badge "new" or common use badge

### ISSUE THREAD

**Issue by lukaspijak** [Dogfalo/materialize#656]
like bootstrap labels http://getbootstrap.com/components/#labels

**Comment by jnthas** [comment]
@lukaspijak I think create a i18n "new badge" is a little difficult to implement, you need to detect the browser language and have a translated word list "new" in each language. But, as you suggested, create a "label" like bootstrap is a great idea and easy to implement.  

You just need add the follow CSS in your style.css:
<pre>
<code>
span.label {
  padding: 0.25em;
  border-radius: 0.25em;
  margin: 0.25em;
}
</code>
</pre>

And then, use like this:


```
<h5>Lollipop <span class="label blue white-text">New</span></h5>
```

@Dogfalo What do you think support this feature in Materialize?

**Comment by j6k4m8** [comment]
Absolutely :+1: to this. Why should I need a `new` every time I just want something to look like a twbs `label`?
