### ISSUE TITLE
Active tab indicator on any list

### ISSUE THREAD

**Issue by maechler** [Dogfalo/materialize#657]
It would be nice if the active tab indicator would work on any ul without triggering a content container's visiblity. I would like to have the underline animation on my navigation. Additionally to the tabs implementation this component should work on different list element sizes. The animation could be triggered on click or on hover depending on a configuration.

![screen shot 2015-02-10 at 22 52 14](https://cloud.githubusercontent.com/assets/4113819/6137238/8a4f4f68-b177-11e4-940c-093837800a70.png)

possible usage:

``` html
<ul class="nav">
  <li>short</li>
  <li class="active">but the text could also be longer</li>
  <li>and than shorter again</li>
  <li>still getting shorter</li>
</ul>
```

``` javascript
$(document).ready(function(){
  $('ul.nav').underline();
});
```

**Comment by tomscholz** [comment]
You could use a combination of http://materializecss.com/navbar.html#navbar-tabs and http://materializecss.com/tabs.html#external
