### ISSUE TITLE
Navbar Dropdown does not work for both desktop and phone

### ISSUE THREAD

**Issue by nh916** [Dogfalo/materialize#6573]
I have a navbar with a dropdown that works in desktop but when I also add the dropdown to the mobile version it works in the mobile but does not work in the desktop version. The desktop version still has the icon but nothing drops down when clicking on it. When I remove the dropdown from the mobile part, the desktop dropdown works again.

**Comment by Tchekda** [comment]
Hi, you need to set a different Id for the mobile dropdown and so change the data-target accordingly

**Comment by nh916** [comment]
can you please give me a small example because im not sure exactly what you mean. thank you i really appreciate your help

**Comment by Tchekda** [comment]
Hi @nh916 here is a [codepen](https://codepen.io/tchekda/pen/abdjjOv) where you can see the difference.
Look at the dropdown's id, you will see when it's working, when it's not.

**Comment by nh916** [comment]
oh i see. I got what you mean! 
Thank you for taking the time and helping me see how to make it work!
looking at it now its clearer. I dont think I would have figured this out if i struggled a few more hours without your help. Thanks again!
