### ISSUE TITLE
Datepicker not using existing value of input field

### ISSUE THREAD

**Issue by uok** [Dogfalo/materialize#6575]
I'm using the datepicker (with format: dd.mm.YYYY) on a form that already has input field values
Materialize 1.0.0

Example
`<input type="text" class="datepicker" name="start" value="05.07.2020" />`

Result
Firefox: datepicker shows month "July", but the day is not hightlighted/set to "5"
Chrome: datepicker shows month "May"

Thanks for the help!

**Comment by doughballs** [comment]
@uok `value="05.07.2020"` is not the correct way to set a date. Please see the [documentation](https://materializecss.com/pickers.html).

What you need is `defaultDate` and `setDefaultDate`.

Also, this is not an issue - issues are bugs that can be replicated. Any advice on how to use components, please ask in the [Gitter](https://gitter.im/Dogfalo/materialize) channel :)

**Comment by uok** [comment]
Thanks!

I changed it to `<input type="text" class="datepicker" name="start" data-default="05.07.2020" />`
and then used javascript to read this data attribute and set it for `defaultDate` option

Would be great to use the value="" for that - or have a built-in data-value="" function :wink:
