### ISSUE TITLE
Using icons needs internet connection

### ISSUE THREAD

**Issue by vahid18u** [Dogfalo/materialize#6576]
The onliest way to use icons is using CDN and it is not possible to use in offline electron apps.

**Comment by doughballs** [comment]
@vahid18u did you do any research before opening an issue?

https://stackoverflow.com/questions/37270835/how-to-host-material-icons-offline

**Comment by vahid18u** [comment]
well of course it is possible!! but it is not gently!I mean why don't you have something like @material-ui/icons ?

**Comment by doughballs** [comment]
Again, this is not an issue, possibly a feature request. I'm not involved with the project just trying to help.

**Comment by kethan1** [comment]
Materialize Icons has a NPM module installable with this: `npm install material-design-icons --save`
