### ISSUE TITLE
XSS on Toast, AutoComplete, and ToolTip  features 

### ISSUE THREAD

**Issue by SpaYco** [Dogfalo/materialize#6582]
![image](https://user-images.githubusercontent.com/11758151/88975462-21205480-d2b2-11ea-8cba-b49ffc1aa7b2.png)
please add a patch

**Comment by Smankusors** [comment]
Duplicate of #6286

**Comment by SpaYco** [comment]
i looked and didn't find, so many issues prob i lost it.
