### ISSUE TITLE
Update jQuery to 2.1.3

### ISSUE THREAD

**Issue by coliff** [Dogfalo/materialize#659]
Minor thing, but to be up-to-date it'd be good to update the site to use the latest version of jQuery (2.1.3)

**Comment by Dogfalo** [comment]
I think it may be good to for us to leave it on 2.1.2 to ensure that it works on this version and above. But if you want to use jQuery 2.1.3 you should be able to do so without any problem

**Comment by coliff** [comment]
I'd recommend checking yourself with 2.1.3. It's a patch release so shouldn't break anything and this fixes a bug with Safari.
Info here: http://blog.jquery.com/2014/12/18/jquery-1-11-2-and-2-1-3-released-safari-fail-safe-edition/
