### ISSUE TITLE
MaterializeCSS Modal isn't working in Python - Django + HTML

### ISSUE THREAD

**Issue by dhavalveera** [Dogfalo/materialize#6597]
Hello

I was trying to Implement MaterializeCSS Modal for my Website which is based on HTML, Python - Django.

  
  <button data-target="modal1" class="btn modal-trigger">Modal</button>
    

  <div id="modal1" class="modal">
    <div class="modal-content">
      <h4>Modal Header</h4>
      <p>A bunch of text</p>
    </div>
    <div class="modal-footer">
      <a href="#!" class="modal-close waves-effect waves-green btn-flat">Agree</a>
    </div>
  </div>

document.addEventListener('DOMContentLoaded', function() {
    var elems = document.querySelectorAll('.modal');
    var instances = M.Modal.init(elems, options);
  });

  // Or with jQuery

  $(document).ready(function(){
    $('.modal').modal();
  });

but when I am trying to click on the Button Event, unfortunately, nothing is working. can you please help me in this case.

**Comment by khashashin** [comment]
Is there any error in your browser console?

**Comment by dhavalveera** [comment]
No, I am not getting any Error in Chrome Console.

**Comment by khashashin** [comment]
There should be actually nothing that conflicts with django. Try to use data-target instead of `href`

```
<!-- Modal Trigger -->
  <button data-target="modal1" class="btn modal-trigger">Modal</button>

<!-- Modal Structure -->
  <div id="modal1" class="modal">
    <div class="modal-content">
      <h4>Modal Header</h4>
      <p>A bunch of text</p>
    </div>
    <div class="modal-footer">
      <a href="#!" class="modal-close waves-effect waves-green btn-flat">Agree</a>
    </div>
  </div>

<!-- Modal Initialization -->
  <script>
    document.addEventListener('DOMContentLoaded', function() {
      var elems = document.querySelectorAll('.modal');
      var instances = M.Modal.init(elems, {});
    });
  </script>
```

**Comment by dhavalveera** [comment]
Let me check & get back to this Issue.

**Comment by dhavalveera** [comment]
it worked.
