### ISSUE TITLE
Dropdown buttons in collapsible headers don't work

### ISSUE THREAD

**Issue by beeb** [Dogfalo/materialize#663]
A dropdown placed in a collapsible header doesn't drop down on click. Instead, it opens the collapsible body.

**Comment by beeb** [comment]
sorry was a mistake of mine.

**Comment by olivermaldonado** [comment]
What was your mistake? I'm trying to have buttons on the header, but I can't avoid the body from opening when activating these buttons.

**Comment by beeb** [comment]
Here's a snippet

    <div class="card-panel grey lighten-2">
        <div class="row">
            <div class="col s9">
                <h4 class="header">Header</h4>
            </div>
            <div class="col s3 right-align">
                <a class="dropdown-button btn-flat btn-large" href="#" data-activates="dropdown-1"><i class="mdi-navigation-more-vert"></i></a>
                <ul id="dropdown-1" class="dropdown-content">
                    <li><a href="#">foo</a></li>
                </ul>
            </div>
        </div>
        <ul class="collapsible" data-collapsible="accordion">
            <li>
                <div class="collapsible-header row waves-effect waves-dark">
                    <div class="col s3 m2 l1">
                        content
                    </div>
                    <div class="col s7 m8 l9">
                        content
                    </div>
                    <div class="col s2 right-align">
                        <a class="dropdown-button btn-flat" href="#" data-activates="dropdown-2"><i class="mdi-navigation-more-vert"></i></a>
                        <ul id="dropdown-2" class="dropdown-content">
                            <li><a href="#">bar</a></li>
                        </ul>
                    </div>
                </div>
                <div class="collapsible-body grey lighten-4">
                    content
                </div>
            </li>
        </ul>
    </div>
