### ISSUE TITLE
When will the next release of MaterializeCSS come out?

### ISSUE THREAD

**Issue by manuthecoder** [Dogfalo/materialize#6631]
I've been using Materialize for a really long time now, and I've been waiting a long time for the next release. 
Here are a few things I'm looking forward to: 
* Swipeable bottom sheet modals
* Bottom navigation
* Sliders
* Slide sheets (https://material.io/components/sheets-side), Similar to modal/sidenav
* Navigation rail (https://material.io/components/navigation-rail)
* Image Lists (https://material.io/components/image-lists#behavior) (Read behavior section! )
* And banners (https://material.io/components/banners)

Although it is very easy for me to make some of these, I would still like it if it was included in Materialize CSS

**Comment by leonardorafael** [comment]
This project was moved to another repository, see https://github.com/Dogfalo/materialize/issues/6615 for more details 👍
