### ISSUE TITLE
Value change of select does not affect visuals

### ISSUE THREAD

**Issue by ghost** [Dogfalo/materialize#6632]
### Problem
Changing selected value of a `<select>` with Javascript does not change the visual selection. 

I am using Javascript to change a selected value of a `<select>`, getting the select element by id and setting it's value to a different option value.
This works just fine, but the visual selection in the select input-field does not change. Clicking afterwards on it, shows the new selected value and will then display it correctly in the input-field. 

Is it possible to change the visual selection, if the selected value changes programmatically? For my usecase, I need to show the change of the selection immediately.

### Reconstruction:

[CodePen](https://codepen.io/witzler/pen/JjEdrJQ)

**Comment by jshster** [comment]
Simply call the formSelect() method again after setting the value programmatically.  That should do the trick.

**Comment by ghost** [comment]
> Simply call the formSelect() method again after setting the value programmatically. That should do the trick.

Thanks! This did the trick. I just found out that the "onchange" event does not fire and this seems to be the problem of javascript.
