### ISSUE TITLE
Is it dead?

### ISSUE THREAD

**Issue by rahultrivedi180** [Dogfalo/materialize#6646]
Is this a dead project now? No further updates.

**Comment by jamesdwalker** [comment]
It is on this repo, version `1.1.0` is currently in alpha over on the [new repo](https://github.com/materializecss/materialize), which is hosted on [https://materializecss.github.io/materialize/](https://materializecss.github.io/materialize/).
It's only a minor version, so don't expect a huge set of new features, but the last commit was 3 days ago so it is at least in active development :)

**Comment by Tronic247** [comment]
I think it is  : ( 
Perhaps you may like [this](https://tronic247.com/material/)

**Comment by Tronic247** [comment]
@rahultrivedi180 and @jamesdwalker I think it is  : ( 
Perhaps you may like [this](https://tronic247.com/material/)

**Comment by Tronic247** [comment]
@btjanaka why **down vote** ?

**Comment by btjanaka** [comment]
@Tronic247 my bad - didn't realize I mis-clicked

**Comment by leonardorafael** [comment]
Sad with this all. The project has been forked. Now I'm trying to help another open source project called [beercss.com](https://www.beercss.com).
If has beer, I like. Maybe you like it too 😁🍺

![cover](https://user-images.githubusercontent.com/12979016/124483667-fa4f8580-dd80-11eb-8928-fa8d715bde77.png)

**Comment by Tronic247** [comment]
@leonardorafael the framework is ugly.

**Comment by rahultrivedi180** [comment]
Seems like no more major updates will be there in the future. It is a good library for quick prototyping though.
