### ISSUE TITLE
card reveal in new version 0.95.2

### ISSUE THREAD

**Issue by alexjp** [Dogfalo/materialize#665]
Hi,
Thanks for materializecss !

I was using version 0.95.1 with alot of card reveal widgets. When upgraded to version 0.95.2, all the cards had the reveal display "visible".

I noticed that the card example on the webpage, has a special style="overflow: hidden". 
When i created a .card { overflow: hidden; } rule on my sass, it worked.

**Comment by jett0423** [comment]
hi! I used to have the same problem. update your materialize.js file

**Comment by alexjp** [comment]
Hi, I removed all my bower_components folder and checked in the browser the materialize.js file. It says its 0.95.2 
I am still unable to make it work without modifications. :(

**Comment by acburst** [comment]
Yes there was a change in the javascript. It is working on our end.

**Comment by alexjp** [comment]
Figured what was the problem. I checked the change 3 days ago into cards.js

Debugginfg javascript ( i had the latest materialize.js ) i noticed that the jquery :
`
 $('.card > .card-reveal').each(function() {
      $(this).parent().css('overflow', 'hidden');
    });
`
was not finding any results.

The issue is that i am using Ember JS, it seems that when that jquery document ready is ran, the cards are not there yet.

Manually triggering the jquery code, it hides the reveal section as it should.

I guess this is a non issue, since Ember JS compability is not on the goals, i think.

**Comment by Dogfalo** [comment]
In certain JS frameworks, there will be some issues due to how the DOM may be rendered. Although we try to have events delegate when it is possible.

**Comment by alexjp** [comment]
Yeah, Dogfalo, sorry for the "bad issue report" :(

may i ask if its possible to make a revel hook, kinda like tooltip and select, so that in Ember when can put a "when rendered do element.revealCard();" ?

I got it to work ( with javascript, by copying the content of the card.js code that handles this ) and works fine, but other people may miss this. If its documented in the docs, it should be easy and nice for Ember users ( or other frameworks ).

Thanks for the great work, if you are interested, i can report on materializecss <-> emberjs issues
