### ISSUE TITLE
Col classes "m" and up adds a huge left margin

### ISSUE THREAD

**Issue by devtrix** [Dogfalo/materialize#6650]
When asking general "how to" questions:

- Please do not open an issue here!
- Instead, ask for help on [StackOverflow](stackoverflow.com/questions/tagged/materialize) or in our [Gitter](https://gitter.im/Dogfalo/materialize) channel.

- Read the [CONTRIBUTING document](https://github.com/Dogfalo/materialize/blob/master/CONTRIBUTING.md) Any issues that are violating the contributing guidelines, will be closed!
- [Search for duplicate or closed issues](https://github.com/Dogfalo/materialize/issues?utf8=%E2%9C%93&q=is%3Aissue) and make sure to go through our [labels](https://github.com/Dogfalo/materialize/labels).
- Include a [reduced test case](https://css-tricks.com/reduced-test-cases/) in the form of a Codepen when reporting bugs unless it is not applicable, otherwise your issue will be closed.

Any <div = "col s12">  aligns left.  <div = "col s12 m4"> inserts a huge space to the left or "start".

## Expected Behavior

It should defult to the "start" or left.

## Steps to Reproduce (for bugs)

1.
2.

## Your Environment

* Version used: 1.0.0
* Browser Name and version: All
* Operating System and version (desktop or mobile): Win 10 Pro desktop
* Link to your project (if appropriate):

**Comment by Posandu** [comment]
@devtrix this library is no longer being maintained maybe you could use this framework https://material.pages.dev/
