### ISSUE TITLE
Unmaintained library, support this project instead !

### ISSUE THREAD

**Issue by Posandu** [Dogfalo/materialize#6659]
This is an Unmaintained framework, support [this framework](https://github.com/Tronic247/material) instead!

**Comment by jshster** [comment]
Mate, let it go.  The project is continuing on at https://github.com/materializecss/materialize. Plenty going on at https://gitter.im/Dogfalo/materialize too.  For those of us already using the framework any thoughts of moving to a new framework are nigh on impossible.

**Comment by Posandu** [comment]
If you say so
