### ISSUE TITLE
There is no search button for material icons

### ISSUE THREAD

**Issue by Saswat689** [Dogfalo/materialize#6663]
## Current Behavior

To get a icon we have to search for hours! There is no search option to find relevant icons as there is in the material design library or other popular ones. The icon library is great but it would be better if we had a search option. Then people like me, did not have to scratch our heads finding a single icon from such a long list.

## Possible Solution

There should be a search functionality implemented at this page so that the user can search for keywords matching the icon name. For example if a user searches for **add** then he should be provided with the add icon and similar matching keywords. Link to the page: [icons materialize](https://materializecss.com/icons.html)

## Context

I had to find icon for a toolbox and analytics. But i had to search for approximately half an hour just to get the two from the list.

![Screenshot (42)](https://user-images.githubusercontent.com/78579824/143825455-13b97ac2-f2f7-45cf-9b5c-b166dc0441fb.png)

## Steps to Reproduce (for bugs)

1. Add a search input to the page just before the list of icons (grid)
2. Add a search functionality that **includes** or **exactly matches** the keywords typed by the user.

## Your Environment

* Version used: 1.0,0
* Browser Name and version: Chrome (latest)

**Comment by SAM-AEL** [comment]
Ctrl + F , Search for "search" . click next till you find the icon you want.

or 

you could head to [Google Material Icons](https://material.io/icons/) Page and search easier on their own search bar.

**Comment by Saswat689** [comment]
@SAM-AEL  The search is pretty functonal, but I think you should also implement a UI component for users like me who don't know shortcuts.
