### ISSUE TITLE
Keep tooltip open

### ISSUE THREAD

**Issue by kuza2010** [Dogfalo/materialize#6667]
Hello, I am wondering how to keep tooltip open when hovering over tooltip content?

**Comment by jshster** [comment]
Hey Kuza, can you explain further?  Are you saying the tooltips are just flashing up then disappearing or do you mean you want them to remain visible for a period after the mouseout event?

**Comment by kuza2010** [comment]
Hello, @jshster 
I can demonstrate what I want.
![close-when-mouse-out-of-the-box](https://user-images.githubusercontent.com/32107577/161236491-a5cc06c6-54af-4107-ba75-444afc32d2df.gif)

You can observe that when mouse over the popup it does not closes. 

I took a look at [this](https://stackoverflow.com/questions/42881671/making-materialize-css-tooltips-stay-when-hovering-over-them). But probably there are another ways? Or code examples for Vue.js

**Comment by LoganTann** [comment]
Hello @kuza2010 

Materialize tooltip is not designed for such layout, and maybe you'll have to program it by yourself.

Moreover, you're saying that would like code examples for Vue.Js.   
As materialize manipulates the DOM, I strongly advise against using it on your vue project. Maybe Vuetify is more suited for your needs (https://vuetifyjs.com/en/components/tooltips/)


If you need help, feel free to reply in this thread

**Comment by kuza2010** [comment]
@LoganTann thanks for your comment. Yeah, I realized it after some time working around this. I just connect the following library: [vue-tooltip](https://floating-vue.starpad.dev/)
