### ISSUE TITLE
Horizontal cards

### ISSUE THREAD

**Issue by Dogfalo** [Dogfalo/materialize#668]

**Comment by Pantic14** [comment]
And... How to create horizontal cads? I am looking but I do not find it

**Comment by Dogfalo** [comment]
This is an open issue, which means it is not implemented yet

**Comment by Pantic14** [comment]
Ok. Sorry. I'm go to implement :D

**Comment by nasr18** [comment]
please make horizontal cards like, instead of card image up and content down, make image left side and content right side.

**Comment by marfago** [comment]
+1

**Comment by acburst** [comment]
Basic version finally added in d93533e606dd2cd6db53ce31047fa6fddefcb52e
