### ISSUE TITLE
[Request] nav brand-logo center option for large screens

### ISSUE THREAD

**Issue by jett0423** [Dogfalo/materialize#669]
I'm trying to make the desktop-size navbar similar to the ones in mobile devices wherein the logo centers automatically. the 'center' class currently available can't seem to do that. Maybe a new 'center-logo' class or something?

**Comment by FKSI** [comment]
It would be great indeed :)

**Comment by Dogfalo** [comment]
`class="center"` on brand-logo
Added in 591a8e70c2b9ab7775df3292601dbb595bf7e56e
