### ISSUE TITLE
Add instructions for how to build materialize.js

### ISSUE THREAD

**Issue by owencm** [Dogfalo/materialize#670]
The readme.md doesn't include any instructions on how to build materialize.js after making changes. I'm changing the source files in the js folder and some copy paste lines to set up and run grunt would be appreciated.

**Comment by Dogfalo** [comment]
I agree, we can do a better job here. For now, if you haven't moved anything after cloning, you can run `grunt monitor`

**Comment by owencm** [comment]
Turns out I was using node 0.12 which is incompatible with node-sass and hence grunt was giving me problems and I was wondering if I missed a key step somewhere.

**Comment by IagoLast** [comment]
@owencm I had the same problem with sass.
You can install node v0.10.30 using n https://github.com/tj/n in order to fix that.

After that you should be able to run the grunt task without problems.

**Comment by Dogfalo** [comment]
This has been added to the readme

**Comment by gg4u** [comment]
I would like to compile js and css skipping modules that I do not use.
Could you provide in the readme a guide about dependencies used from each module?
You did a great job creating an html example page for each component, it would be great to add a couple of lines saying which CSS and JS a component require.

First time I use grunt to automate: first

```
npm install grunt --save-dev
```

then:

I commented out a couple of packages (datepicker.js) on  ```Gruntfile.js``` and tried to compile:
```
grunt
```
but it does not install packages recursively.
```>> Local Npm module "grunt-contrib-watch" not found. Is it installed?```

What should I do to simply chain and minify selected js?

**Comment by tlchatt** [comment]
I get the error "/usr/bin/grunt no such file or directory" after installing grunt globally via NPM and running grunt monitor. Would really save me a lot of time to pass some more info to the material-box plugin, want to replicate the data-caption functionality but add some more details for my images.
