### ISSUE TITLE
Material Design Icons

### ISSUE THREAD

**Issue by kestutis-stalmokas** [Dogfalo/materialize#671]
Would you consider removing query string when referring icon fonts in CSS (@font-face) and instead use version identifier in the filenames? There are a couple of issues with query strings:

1. [Some proxies don’t cache resources with a query string](http://www.stevesouders.com/blog/2008/08/23/revving-filenames-dont-use-querystring/)

2. One of my build task generates AppCache manifest file by including all the files that exist in certain directory. Although it includes font files it has no way to know the current query string and AppCache fails to properly cache the fonts.

**Comment by acburst** [comment]
fixed in 128fc65fa0ea11788229d44b37144684b5103b46
