### ISSUE TITLE
Navbar in desktop mode

### ISSUE THREAD

**Issue by r1si** [Dogfalo/materialize#673]
Hi guys,
first of all thanks for sharing your project, it's awesome...
I'm trying to write a desktop application with nw.js and I use you library for GUI.
All work perfect (except color that are hardcoded) but I have a problem with navbar.
If nw windows is smaller than 900 px materialize load responsive mode (hide icon and show mobile menu)
there is some way to load dekstop mode? 
I think it's right place a css class call "desktop-mode" on navabr that override the mobile code and place icon at the right top.
Here an example:
![top_desktop_mode](https://cloud.githubusercontent.com/assets/6353773/6166990/3a4cf868-b2b6-11e4-806d-dff466a1900d.png)

**Comment by Dogfalo** [comment]
Try the media queries here http://materializecss.com/sass.html
