### ISSUE TITLE
Navbar mobile does not work with wave-effect.

### ISSUE THREAD

**Issue by naveenshaji** [Dogfalo/materialize#674]
If we add a wave-effect class to the navbar, or on a div surrounding the navbar, then the mobile version navbar fails to work. The slide-out menu from the left does not open in full, like this -
![1](https://cloud.githubusercontent.com/assets/10815281/6170852/6cd27dde-b2fd-11e4-8ce4-8685dc2f578a.PNG)
Instead of -
![2](https://cloud.githubusercontent.com/assets/10815281/6170859/79f447ea-b2fd-11e4-8c91-85acdae3c8ae.PNG)
The issue is easy to replicate by adding the wave-effect class on any div surrounding the navbar. I know it works if I add the effect inside a container inside the nav, but I want the wave-effect to be full width. so. Here is the code

```
<header class="site-header">
    <div class="navbar-fixed">
        <nav class="{{ site.css }} darken-2 waves-effect waves-light">
            <div class="nav-wrapper">
               <div class="container">
                <a internal href="/" class="brand-logo"><i class="mdi-communication-chat"></i> naveenshaji</a>
                <ul id="nav-mobile" class="right side-nav">
                    <li><a internal href="/">Blog</a>
                    </li>
                    <li><a internal href="/">Projects</a> 
                    </li>
                    <li><a internal href="/about/">About</a>
                    </li>
                    <li><a href="http://github.com/naveenshaji/" target="_blank">GitHub</a>
                    </li>
                </ul>
                <a class="button-collapse" href="#" data-activates="nav-mobile"><i class="mdi-navigation-menu"></i></a>
            </div>
            </div>
        </nav>
    </div>
</header>
```

**Comment by Dogfalo** [comment]
The waves effect is not meant to be used to wrap whole components. Rather use it to wrap smaller  things. So we will not be making any changes to the CSS. However, if you want to make it work on this particular instance. Remove will-change, overflow:hidden, and z-index from the element.
