### ISSUE TITLE
nav should have overflow hidden

### ISSUE THREAD

**Issue by rma4ok** [Dogfalo/materialize#680]
For some reason you have this code only for gh-pages
https://github.com/Dogfalo/materialize/blob/master/sass/style.scss#L22
It should be a part of nav styling 
https://github.com/Dogfalo/materialize/blob/master/sass/components/_navbar.scss

Screenshot of Nav with Icon Links with mouse over an item
![screen shot 2015-02-12 at 6 45 45 pm](https://cloud.githubusercontent.com/assets/470292/6179497/c5d5dcd4-b2e7-11e4-9e5b-0d51b79425b1.png)

**Comment by Dogfalo** [comment]
Added in 591a8e70c2b9ab7775df3292601dbb595bf7e56e
