### ISSUE TITLE
Clean console.log from code

### ISSUE THREAD

**Issue by rma4ok** [Dogfalo/materialize#681]
[Code where it left](https://github.com/Dogfalo/materialize/search?utf8=%E2%9C%93&q=console.log)

**Comment by tjoskar** [comment]
:+1:

**Comment by venil7** [comment]
this issue gets my vote, it's ridiculous to see `console.log` in minified build

**Comment by Dogfalo** [comment]
Gone, we we have a grunt script that removes them from any distributed release
