### ISSUE TITLE
Input label overlaps if value='exits'

### ISSUE THREAD

**Issue by Kestanous** [Dogfalo/materialize#682]
If this is defined:
```html
      <div class="input-field">
        <input id="name" name="name" type="text" class="validate" value='exits'>
        <label for="name">Name</label>
      </div>
```
you get this:
![my_bus_app](https://cloud.githubusercontent.com/assets/1283884/6181871/e2a33c74-b307-11e4-8609-e8e0b9ca0166.png)

**Comment by Dogfalo** [comment]
This doesn't happen for me when I used your HTML code. It will only happen if you are using Angular or something similar.

**Comment by bromanv** [comment]
i have this problem when set the input value using jquery and the input is hidden or never before has focused

**Comment by Dogfalo** [comment]
Just add the class active to the label

**Comment by Havock94** [comment]
Setting the active class to the input doesn't seem to fix the issue. I'm using AngularJS but I'm setting the value via jQuery.

**Comment by Dogfalo** [comment]
To the `<label>`

**Comment by Havock94** [comment]
Oh yes sorry. I'm actually doing it with 
$(input).focus() and then $(input).blur(), I'll try with the class when I can.

**Comment by ChJJin** [comment]
@Havock94 ,  you could do it with ```$(input).change()``` as the [source code](https://github.com/Dogfalo/materialize/blob/ddd05e4094ff947d6ee4443be9888c870a94d19e/js/forms.js#L24) has told us how it change the style. :)

**Comment by XcodeJunkie** [comment]
You can solve this in angular with a ng-class directive like:

    <label for="ctrl.foo" ng-class="{ active: ctrl.foo }">Foo title</label>
    <input type="text" ng-model="ctrl.foo" class="form-control" id="foo" />

**Comment by jshafee** [comment]
Use 
 $("#inputId").select();

**Comment by vaishali-ghayal** [comment]
@XcodeJunkie 
<label for="ctrl.foo" ng-class="{ active: ctrl.foo }">Foo title</label>
<input type="text" ng-model="ctrl.foo" class="form-control" id="foo" />
Working for me
