### ISSUE TITLE
Height of textarea in modal is wrong

### ISSUE THREAD

**Issue by philipraets** [Dogfalo/materialize#684]
If I have a form with a textarea in a modal popup, the height gets wrongly calculated, because the original element is hidden from the DOM.

![textarea-modal](https://cloud.githubusercontent.com/assets/708011/6187984/38009092-b38d-11e4-96ee-03afa1699eee.png)

Is there a way I can work around that problem?

**Comment by FKSI** [comment]
Same issue inside "cards"

**Comment by carlosperate** [comment]
Currently the modal height seems to be set to 70%, independently of the content inside:
https://github.com/Dogfalo/materialize/blob/master/bin/materialize.css#L5928
Unless there is some js to recalculate the height I'm not sure that is a feature.

**Comment by Dogfalo** [comment]
The height is only for fixed footer modals. regular modals scale in height

On Thu, Feb 19, 2015 at 11:15 AM, Carlos <notifications@github.com> wrote:

> Currently the modal height seems to be set to 70%, independently of the
> content inside:
>
> https://github.com/Dogfalo/materialize/blob/master/bin/materialize.css#L5928
> Unless there is some js to recalculate the height I'm not sure that is a
> feature.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Dogfalo/materialize/issues/684#issuecomment-75080736>.
>



-- 
Doggy sends his greetings from Mars.

**Comment by philipraets** [comment]
The height of the modal window is not the issue, it is the height of the textarea in the modal which is calculated wrong, because the hidden div to calculate seems to be only 100px wide.

If you want to have modals with fixed footer and dynamic height you could try to add this to the css (this is for now the only solution I have found but it is with fixed max-height - 380px seems to be a reasonable max-height for all devices):
.modal {
    overflow-y: scroll;
}
.modal .modal-content {
    display: block;
    max-height: 380px !important;
    overflow: scroll;
    text-overflow: ellipsis;
}
.modal .modal-footer {
    border-top: 1px solid rgba(0, 0, 0, 0.1);
}

**Comment by acburst** [comment]
I just tested textareas in both cards and regular modals and they both seem to be working correctly. If you are still having an issue let us know specifics

**Comment by FKSI** [comment]
With release 0.95.2 files?

**Comment by philipraets** [comment]
I've noticed it with 0.95.2 (I don't know if it happened before). I've created a jsfiddle with the problem:
http://jsfiddle.net/3e5fgfzo/

**Comment by FKSI** [comment]
Still the same issue on 0.95.3 , Thanks @SmileyChris for the fix!

**Comment by acburst** [comment]
Fixed in e7d7d150de6b49a045b1d999b1bd16170f56d4aa
