### ISSUE TITLE
Pushpin dynamic height

### ISSUE THREAD

**Issue by jakewhiteley** [Dogfalo/materialize#685]
I have a pushpin element which changes height after a user action (a scenario I can see a genuine need for in web applications, creating user content such as a mail box).

As the height has changed, the bottom property also has to change.
As the current implementation uses `$(this).css('top', options.bottom - $original_offset);`, it seems that re initializing pushpin on resize, uses the current top position, and so when the new bottom scroll position is reached, the element shoots back up to the top of the page.

How can this be overcome?

**Comment by falconmick** [comment]
nobody??

**Comment by nevnein** [comment]
I had a similar issue where I needed to update the pushpin properties on window resize, and I solved it removing and reinitializing pushpin, don't know if it's the best way but works for me.

```javascript
function resetPushpin() {
    $("your-element").pushpin('remove');
    $("your-element").pushpin({
        //update the properties
        top: /*recalculate value*/,
        bottom: /*recalculate value*/,
        offset: /*recalculate value*/
    });
}

//I update the values on window resize, I guess you can bind this to every change you need but haven't tested
$( window ).resize(resetPushpin);
```
