### ISSUE TITLE
Two Finger Tap Causes Button Wave to not Disappear

### ISSUE THREAD

**Issue by alanjames1987** [Dogfalo/materialize#686]
When tapping a button with two fingers the only one wave animation fades away.

**Comment by tomscholz** [comment]
Still an issue!

**Comment by tomscholz** [comment]
These issues are all duplicates:
https://github.com/Dogfalo/materialize/issues/1314
https://github.com/Dogfalo/materialize/issues/3642
https://github.com/Dogfalo/materialize/issues/686

For future discussion, please use this issue instead.
https://github.com/Dogfalo/materialize/issues/4344
