### ISSUE TITLE
Tooltips remains visible after the element is removed from the DOM

### ISSUE THREAD

**Issue by Cerealkillerway** [Dogfalo/materialize#692]
The tooltips remains visible after the element they are associated to is removed from the DOM by ajax;
this happens for example in a single page application, when clicking on a button with a tooltip that triggers a new template to be rendered in place of the current one (ex changing route);
is there a way to avoid this behaviour without having to remove all the tooltips manually after every template render?

**Comment by Cerealkillerway** [comment]
A possible solution would be also to have tooltips created with an id that references their "tooltipped DOM element"; in that way it would be possible to remove tooltips when the template is destroyed;

right now tooltips only have a "material-tooltip" class, so when a template is destroyed can only remove ALL tooltips (also the ones referencing elements in other templates that remain visible)

**Comment by Cerealkillerway** [comment]
I've made a little variation of the materialize's tooltip function that supports a container argument (to append the tooltips to) and calculates position corrections if the container (or any ancestor) is positioned by CSS "position" rule:

https://gist.github.com/Cerealkillerway/0dece72eece0aec32878

maybe someone can find this useful

**Comment by emd2009** [comment]
Do you have a jfiddle demoing this

**Comment by Cerealkillerway** [comment]
You just need to add the file to your project, and then activate the tooltips:

   $('.tooltipped').ckTooltip({delay: 10, container: this.$('desiredContainerIdOrClass')});

In this way you can try if it works for you without editing the materialize's source

**Comment by Roundaround** [comment]
@Cerealkillerway, I'd encourage you to implement your gist as a proper pull request (I see it has a different changeset than your previous solution), and perhaps use http://jsfiddle.net/ or http://plnkr.co/ to demonstrate your new addition.  That way people would be more willing to accept that your solution is a good one.  Right now, there are too many differences between your version and the head (running through a diff breaks all over in places it really shouldn't).  Resolve these and come back and we can work from there.

Cheers.

**Comment by Cerealkillerway** [comment]
well, I've made that gist just for sharing that possibility, that I use in my project; it's not perfect and 360° tested but it's a starting point; This is why i've not made a pull request yet; for example: it corrects the position when the container where you append the tooltips is inside a css-positioned element; but if between that container and the inner element that will have the tooltip there are other css-positioned elements, I guess it will fail (it will need another correction); I will try to implement it as soon as I will have the time ;)

**Comment by Roundaround** [comment]
So while looking for cleaner solutions to this issue, I came across this:
http://stackoverflow.com/questions/2200494/jquery-trigger-event-when-an-element-is-removed-from-the-dom/10172676#10172676

```javascript
$.event.special.destroyed = {
    remove: function(o) {
        if (o.handler)
            o.handler();
    }
}
```

With the addition of this event, we can add a third event handler to the tooltip host for 'destroyed' that either mimics the behaviour of mouseleave or just destroys the tooltip - up to you.  I feel like this might be a much cleaner solution

**Comment by Cerealkillerway** [comment]
Yes, if it works, would be a good solution in my opinion; Have you tried to implement this?
In general this can be a solution also for other materialize's components that add shadow DOM to the page's body;

**Comment by Cerealkillerway** [comment]
What you suggested works like a charm for me, so I've made a pull request with this feature:
https://github.com/Dogfalo/materialize/pull/1685

**Comment by carlosperate** [comment]
Would this commit have helped at all on this issue? https://github.com/Dogfalo/materialize/commit/30b2e1d525c5c4a721c9c84f2e33524831331e9a

**Comment by Dahkon** [comment]
```javascript
		$.event.special.destroyed = {
			remove: function(o) {
				if (o.handler) {
					o.handler();
				}
			}
		};
		origin.bind('destroyed', function() {
			newTooltip.remove();
		});
```

This worked for me.
Using parent element not always work. (due to size and overflow for exemple)

**Comment by tomscholz** [comment]
Tooltips can be explicitly removed now
