### ISSUE TITLE
Bower install gets stuck

### ISSUE THREAD

**Issue by bbdstar** [Dogfalo/materialize#695]
Hi,

When installing with bower the install seems to get stuck at 84% and wants to continue downloading.

===============================================================
bower materialize#*           progress Receiving objects:  84% (252/298), 51.57 MiB
===============================================================

Is anyone else having the same issue?

Cheers,
BBD

**Comment by binoy14** [comment]
![screenshot at feb 16 21-10-51](https://cloud.githubusercontent.com/assets/6476108/6222373/61c759f2-b620-11e4-8244-6f17613f143c.png) 

Tried installing using bower this issue does not occur, maybe you might have internet issues.

**Comment by bbdstar** [comment]
Yes I let it run this time and it worked.  I didn't realize this was a 73MB file and the internet is quite slow lately as well.

Thank you.

**Comment by Dogfalo** [comment]
Yes, we've removed that from bower so the next release will not take so long.

**Comment by Dogfalo** [comment]
Yes, we've removed that from bower so the next release will not take so
long.

On Mon, Feb 16, 2015 at 11:08 PM, bbdstar <notifications@github.com> wrote:

> Yes I let it run this time and it worked. I didn't realize this was a 73MB
> file and the internet is quite slow lately as well.
>
> Thank you.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Dogfalo/materialize/issues/695#issuecomment-74614518>.
>



-- 
Doggy sends his greetings from Mars.
