### ISSUE TITLE
vertical alignment of button sizes combined with waves

### ISSUE THREAD

**Issue by lesleyblankendal** [Dogfalo/materialize#698]
Default the buttons vertically align correctly
`<a class="btn-large">Large button</a>`
`<a class="btn-flat">default or flat button</a>`

But when adding the waves-effect class the vertical alignment isn't working properly and is aligned to the bottom...
`<a class="btn-large waves-effect">Large button</a>`
`<a class="btn-flat waves-effect">default or flat button</a>`

The culprit seems to be `overflow: hidden`

**Comment by Dogfalo** [comment]
not sure if this is a good fix, but try adding vertical-align: middle

**Comment by lesleyblankendal** [comment]
Yep, that does the trick! Maybe add it as a default for the buttons in a future release?

**Comment by Dogfalo** [comment]
I'll leave this open so we don't forget.

**Comment by Dogfalo** [comment]
Fixed in 05f444c2fc57dc627d2ce9f2c4ebcfad9a8e1e7c
