### ISSUE TITLE
Toggle dropdown buttons

### ISSUE THREAD

**Issue by anyway** [Dogfalo/materialize#702]
Is there any easy way to toggle dropdowns if there is more than one dropdown button (I have 4)? Closing one dropdown if clicking another one. Can you please add that function?

I'have tried this, but it disables "hover: false, // Activate on click" of the plugin initialization.

	$("a.dropdown-button").click(function(ev) {
		$("a.dropdown-button").dropdown("toggle");
		return false;
	});
	$("ul.dropdown-content").click(function(ev) {
		$("a.dropdown-button").dropdown("toggle");
		return false;
	});

**Comment by carlosperate** [comment]
+1 
This is a feature I would also appreciate.

**Comment by Dogfalo** [comment]
I don't understand what you are requesting. 4 buttons which all toggle the same dropdown?

**Comment by carlosperate** [comment]
What I personally meant was having a select element close if a different one is open. I have just realised this feature has already been implemented (didn't notice when this was introduced). I assumed that is what @anyway meant at the time, but I do not know.

**Comment by Dogfalo** [comment]
This was opened one day ago, but the issue you are talking about was closed
a while ago so I will need some clarification @anyway on what you are
talking about

On Wed, Feb 18, 2015 at 5:52 PM, Carlos <notifications@github.com> wrote:

> What I personally meant was having a select element close if a different
> one is open. I have just realised this feature has already been implemented
> (didn't notice when this was introduced). I assumed that is what @anyway
> <https://github.com/anyway> meant at the time, but I do not know.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Dogfalo/materialize/issues/702#issuecomment-74965996>.
>



-- 
Doggy sends his greetings from Mars.

**Comment by anyway** [comment]
@Dogfalo What I meant is, how Foundation or Bootstrap handle the behavior of dropdowns. Here are examples:

http://foundation.zurb.com/docs/components/dropdown.html
http://getbootstrap.com/javascript/#dropdowns

Just closing the last open dropdown, when opening another one. Like a menu, but with single dropdown elements.
Currently they open on click but I have to click somewhere else on the page to close the dropdown/s.

**Comment by carlosperate** [comment]
Currently if you have several dropdowns, you can click one to open it, and then if you click a second one to open it (without closing the first), the first one closes at the same time the second one opens. Is that what you mean?

**Comment by Dogfalo** [comment]
Fixed in 966cf07bb654c05692989cbd971a5be019d547a1
