### ISSUE TITLE
Fixed action buttons don't works

### ISSUE THREAD

**Issue by alearcy** [Dogfalo/materialize#703]
Hi guys! I tried to put a fixed action buttons within my homepage.
When I try to hover with mouse, nothing happens: the smaller buttons remains in opacity 0. 
Then, the smaller buttons is always clickable, but instead should be hidden and no clickable until I hover or click the big fixed action button. 
I tried Chrome, Firefox and Safari.
Thanks!

**Comment by mankindsoftware** [comment]
There is a bug with the "fixed-action-btn" in that Materialize's own definition of the "reverse()" function into JQuery seems to screwed up by the time it gets to the minification file.
What should be:

> jQuery.fn.reverse = [].reverse **;** $(".fixed-action-btn").each(function (i) { ...

(note the semi-colon between statements),
gets minified to:

> jQuery.fn.reverse = [].reverse **,** a(".fixed-action-btn").each(function() {...

(with a comma separation instead).
For a quick, valid workaround, I would use the "dist/js/materialize.js" file.
Searching for the string "// jQuery reverse" in the file will lead you to the right part of the code to confirm that the semi-colon is used.

**Comment by Dogfalo** [comment]
I don't think that is the error, however we are looking in to this issue. If anyone who has had this problem could give some information as to what the actual error message is, it would be helpful.

**Comment by alearcy** [comment]
Hi @Dogfalo, no errors. Simply small buttons don't appears. I inspect with Chrome your example in the Materialize web site and I noticed that in the HTML node transictions effects appears. Not in my code.

**Comment by virtual-dev** [comment]
Hi same problem here. No error in consoles just the smaller buttons not displaying.
Note that I use Angular. Others components are documented to be initialised via javascript but not this one. I thinks this is were lies the problem.
For exemple to init tabs: `$('.tabs').tabs();`
There is no such thing for the FAB in the doc.

**Comment by alearcy** [comment]
I use 0.95.2 and it don't works....I'm on Meteor. Maybe @virtual-dev suggestion to initialise the javascript is a good idea.

**Comment by Dogfalo** [comment]
The event is delegated I believe

**Comment by virtual-dev** [comment]
@alearcy It worked for me on hover without JS initialisation.
But I wanted the toggle the FAB on click.
Besides I didn't want the children (cascading little fabs) to simply be transparent (opacity: 0) but to be really hidden (display: none).

This is the code I have in my controller. I know this is not the "Angular way" but this is a convenient hack while waiting for the real implementation.
```javascript
var fab = $('.fixed-action-btn');
var fabState = "off";
fab.off( "mouseenter mouseleave" ); // Disable FAB on hover

// the function you will call from ng-click directive
$scope.onFabClick = function(){
    if(fabState == "off"){
        var time = 0;
        fab.children('ul').css('display','block');
        fab.find('ul a.btn-floating').reverse().each(function () {
            $(this).velocity(
                { opacity: "1", scaleX: "1", scaleY: "1", translateY: "0"},
                { duration: 100, delay: time });
            time += 40;
        });
        fabState = "on";
    }
    else{
        var time = 0;
        fab.find('ul a.btn-floating').velocity("stop", true);
        fab.find('ul a.btn-floating').velocity(
            { opacity: "0", scaleX: ".4", scaleY: ".4", translateY: "40px"},
            {
                duration: 100,
                complete: function(){
                    setTimeout(function () {
                        fab.children('ul').css('display','none');
                    }, 50);
                }
            });
        fabState = "off";
    }
}
```

**Comment by Dogfalo** [comment]
The fixed action button works,depending on what js framework you are using, you may have to tweak some things.
