### ISSUE TITLE
Wrong text position in button

### ISSUE THREAD

**Issue by tthanh** [Dogfalo/materialize#708]
![screenshot from 2015-02-18 11 26 10](https://cloud.githubusercontent.com/assets/8962973/6242426/08016bbe-b761-11e4-957a-6935ec540a84.png)

In my site, with demo button on materialize website, everything ok but with middleman link_to helper, text always not inline with icon or like demo button.

Sorry for my poor english.

**Comment by Dogfalo** [comment]
add `right` or `left` to the `<i>`
See the documentation here http://materializecss.com/buttons.html
