### ISSUE TITLE
Icon in mobile nav broken

### ISSUE THREAD

**Issue by 19Gerhard85** [Dogfalo/materialize#709]
Hey guys,

if you add an icon to a navigation item, it breaks on mobile:
![mobile-nav-bug](https://cloud.githubusercontent.com/assets/1492978/6243995/40fd390c-b74d-11e4-9b5d-79fccd174cbb.png)

**Comment by Dogfalo** [comment]
Can you show code?

**Comment by 19Gerhard85** [comment]
@Dogfalo 
Hey Alivin, that's the code:

```html
<nav class="red darken-4">
    <div class="container">
        <div class="nav-wrapper">
            <a class="brand-logo right" href="/">
                <img class="brand-img hide-on-small-only" src="/images/logo-v1.png">
                <span class="hide-on-med-and-up">Brand</span>
            </a>
            <ul id="nav-mobile" class="left hide-on-med-and-down">
				<li class="active">
					<a href="/">
						<i class="fa fa-home left"></i> Home
					</a>
				</li>
				<li class="">
					<a href="/rc">
						<i class="fa fa-gears left"></i> RC's
					</a>
				</li>
            </ul>

            <ul id="slide-out" class="side-nav" style="left: 0px;">
				<li class="active">
					<a href="/">
						<i class="fa fa-home left"></i> Home
					</a>
				</li>
				<li class="">
					<a href="/rc">
						<i class="fa fa-gears left"></i> RC's
					</a>
				</li>
            </ul>

            <a class="button-collapse" href="#" data-activates="slide-out">
                <i class="mdi-navigation-menu"></i>
            </a>
        </div>
    </div>
</nav>
```

**Comment by LaserLock** [comment]
also just clickable where the text is, instead of the whole line as expected

**Comment by acburst** [comment]
Add either ```left``` or ```right``` to the icon. As for the links, you can add ```width: 100%``` to the anchor tags.

**Comment by 19Gerhard85** [comment]
@acburst 
The class ```left``` is already on the icon element which works great for the desktop mode. If ```left``` is added in mobile mode it looks like in the screenshot above. I removed ```left``` in the mobile mode and it worked.

Thanks for the hint with the width.

**Comment by LaserLock** [comment]
i made the "left" work with this code (maybe it can be done better, but i'm not a css master)

@media only screen and (max-width: 600px) {
    li > a > i {
        padding-top: 1.5rem;
    }
}
