### ISSUE TITLE
Iterate checbox, ID problem

### ISSUE THREAD

**Issue by alearcy** [Dogfalo/materialize#710]
Hi guys,
I use Materialize within Meteor application. 
Inside an {{#each}} template, I create a list with checkboxes.
I noticed that checkbox style is releated to ID and label. But with {{#each}} I can't increment ID in each checkbox.
How can I do it?
Thanks

**Comment by jshimko** [comment]
This isn't really a Materialize issue.  It's more of a Meteor thing.  

Assuming you're iterating over a collection of items in your database, you could simply put each document's id in the id of the input element like this:

```handlebars
{{#each items}}
  <input type="checkbox" id="{{_id}}" />
  <label for="{{_id}}">A Name</label>
{{/each}}
```

**Comment by alearcy** [comment]
@jshimko thanks!

**Comment by ericvrp** [comment]
if you have multiple checkboxes you need to prefix or postfix a string to make them unique. I ended up using a simple helper function for that.

Template.adminUsers.helpers({
  myId: function (prefix) {
    return prefix + this._id;
  }
});

So in my template I can now use:
<input type="checkbox" class="toggleC"  id={{myId "C"}} />
<label for={{myId "C"}}></label>
