### ISSUE TITLE
select renders as input type='text' only

### ISSUE THREAD

**Issue by abigtoe** [Dogfalo/materialize#715]
I'm using materialize with autoform with meteor.  For the most part, the two work very well together, well done guys!

I did notice an issue with the div wrapper materialize adds to a select box. Essentially it always assume that the input type is text, whereas the field could be boolean, number etc.  

Any suggestions on how to pass a parameter for the input type (or can one remove it altogether?)

**Comment by Dogfalo** [comment]
The input that is added is only for keyboard control purposes. What problem is this causing?

**Comment by abigtoe** [comment]
The issue relates to how autoform renders the input.  Because materialize renders the select box as a text input, Autoform expects that the values of the options should be strings as well. 

But if the model is a boolean, number or anything other than a string, the select box doesn't render at all.  I had to add the class browser default in order to render non-string select boxes.  

I 'solved' the issue by changing the schema of all of the affected fields to strings (data-validation isn't very important in my case) but over the long-term, allowing us to configure the select box would be very helpful.

**Comment by rynam0** [comment]
The fact that just a text input is present also makes it impossible to bind to any object in ember.  Between this and the default display: none on select elements makes it less than desirable in an ember app as well.
It would be fantastic if these two frameworks played nicely together in regards to select inputs. Thanks for all the hard work.

**Comment by Dogfalo** [comment]
I still don't understand why the select box would not render. in regular `<select>` a type is not specified and the input that is created by our function doesn't get submitted, our dropdown propagates the change to the original <select> element.
