### ISSUE TITLE
Ember app + Materialize CSS: dropdown issues

### ISSUE THREAD

**Issue by albertpak** [Dogfalo/materialize#717]
Working on Ember app and followed instructions to add materializecss to ember: 
```
# install via npm
$ npm install ember-cli-materialize --save-dev
# make ember-cli fetch internal dependencies
$ ember g ember-cli-materialize
```

When i include materialize.min.js version - i get an error with text field: ```materialize.min.js:8 Uncaught TypeError: Cannot read property 'html' of undefined```,

But then when i include non-min version, no error on textfield, but dropdowns don't work.

**Comment by Dogfalo** [comment]
You should open this here: https://github.com/sgasser/ember-cli-materialize
