### ISSUE TITLE
Email form field passing validation for invalid emails

### ISSUE THREAD

**Issue by kevgathuku** [Dogfalo/materialize#720]
In a form, the email field is showing successful validation even when an invalid email is input.
e.g. entering an email without the TLD is showing that this is a valid email
Here is a screenshot that demonstrates the error
![email-validation](https://cloud.githubusercontent.com/assets/3721994/6263983/d66eed04-b82f-11e4-82ea-074eb9ae231c.png)

**Comment by acburst** [comment]
That's just how the email input field is built. We haven't changed any of the validation functionality
