### ISSUE TITLE
browser compatability

### ISSUE THREAD

**Issue by leemason** [Dogfalo/materialize#723]
The docs are very vauge in this regard.

Im looking into using this really nice framework soon, however it would be nice to know a little more than the "currently supported browsers" sentence.

for example is the framework "accessible" in ie8/9 im aware everything wont look/work as expected which is fine, but it would be nice to know if its still usable from an end user point of view.

**Comment by Dogfalo** [comment]
It will depend I what components you use. Complex components will likely
not work on IE 8. IE 9 will have a few odd issues.

**Comment by carlosperate** [comment]
There are a couple of things currently broken in IE11 as well, so keep an eye for that.
