### ISSUE TITLE
Meteor package issue with click/touch

### ISSUE THREAD

**Issue by keyscores** [Dogfalo/materialize#727]
Yay for the official meteor package!
However, I think it needs a specific change to allow the the sidenav to close on click/touch.

**Comment by Dogfalo** [comment]
There is an option. Take a look at the documentation

**Comment by keyscores** [comment]
Yes, but shouldn't that be default in the materialize official package?

**Comment by keyscores** [comment]
Also, I wish you would warn us of breaking changes in the implementations. For example side nav now needs a separate ul list and id="mobile-demo".

**Comment by Dogfalo** [comment]
The Readme, which you should always read before updating, states these
changes. Also the close on click behavior is not desired in static pages
where clicking a link already transitions the page. Adding the transition
in those scenarios is not only distracting, but also slows down the browser.
On Fri, Feb 20, 2015 at 5:44 PM, keyscores <notifications@github.com> wrote:

> Also, I wish you would warn us of breaking changes in the implementations.
> For example side nav now needs a separate ul list and id="mobile-demo".
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Dogfalo/materialize/issues/727#issuecomment-75333399>.
>



-- 
Doggy sends his greetings from Mars.

**Comment by keyscores** [comment]
I agree it may not be desirable. Closed. 
However I don't see anything in the Readme about the implementation changing. I know it's alpha stage, but I've spent a lot of time trying to find out why things are broken when upgrading.

**Comment by Dogfalo** [comment]
-

   v0.95.2 (Feb 10, 2015)
   - Switches added
      - Transition animation functions added
      - ScrollFire Plugin added (fires functions dependent on scroll
      position)
      - Responsive Video tag added
      - Custom File Input Button added
      - Modals has a fixed footer option
      - SideNav implementation changed (needs 2 UL menus)
      - Slider Responsive Fixes


On Fri, Feb 20, 2015 at 6:55 PM, keyscores <notifications@github.com> wrote:

> I agree it may not be desirable. Closed.
> However I don't see anything in the Readme about the implementation
> changing. I know it's alpha stage, but I've spent a lot of time trying to
> find out why things are broken when upgrading.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Dogfalo/materialize/issues/727#issuecomment-75341311>.
>



-- 
Doggy sends his greetings from Mars.

**Comment by keyscores** [comment]
Ok my bad, I see it now.
