### ISSUE TITLE
0.95.2 .card-reveal div not being hidden?

### ISSUE THREAD

**Issue by keyscores** [Dogfalo/materialize#728]
Has anything changed to .card, especially .card-reveal?
I'm having a strange bug where the card-reveal div is NOT hidden. It's covering other content.
See here how it is not hidden (appears under card title):
https://www.dropbox.com/s/hr29zp5mux2rb8o/Screenshot%202015-02-20%2019.08.30.png?dl=0

There was no issue in 0.95.1 . I see no issue when I use plain HTML, the error happens in my Meteor templates.

**Comment by keyscores** [comment]
@Dogfalo 
Just FYI,  the only way to fix this was to override with a new selector and overflow setting.
Something has changed from 0.95.1 to 0.95.2 , can you point me to that change? I would like to use the new and correct implementation.

**Comment by Dogfalo** [comment]
Fixed in 91d4c19691b41584438781f6ee58e9ab52047294
