### ISSUE TITLE
Fixed-action-button children can be triggered by hovering a (supposedly) empty area

### ISSUE THREAD

**Issue by dot-louis** [Dogfalo/materialize#729]
If you hover on the area over the FAB, you'll trigger the animation revealing the children action-buttons.
This behaviour is confusing and can be problematic if there is something (a link for exemple) in this area because the buttons jumps out of nowhere.

I made a [plunkr](http://plnkr.co/edit/LwMphTE9ITOrn7TLRLUp?p=preview) to illustrate this issue

Indeed the reveal animation is triggered by hovering on the `.fixed-action-button` class which wraps the FAB and its children.
Besides, the animations are only making the children buttons transparent (`opacity:0`) but does not prevent any user action on it.

**Comment by Dogfalo** [comment]
This is the behavior on http://inbox.google.com/, so for now I'm not convinced this is undesirable.

**Comment by virtual-dev** [comment]
Oh I didn't noticed inbox had this behavior.
Anyway this is not a problem for inbox because there is no element behind the FAB.
However if you resize the browser window to be small enough for the FAB to overlap the content, then you'll see the behaviour has changed not to interfere with the underlying content (well, at least not at the same height)

**Comment by kabaka** [comment]
This behavior seems to have been recently removed from Inbox.

Observations of my users and my personal preference seems to agree: it is odd for the menu to appear when hovering in this area.

**Comment by philipraets** [comment]
I've added these 2 lines to my css file:
.fixed-action-btn ul {display:none;}
.fixed-action-btn:hover ul {display:block;}

this way it still pops up when you hover over the big button, but not when you hover over the red area.

**Comment by philipraets** [comment]
the red area is a reference to #1572

**Comment by kabaka** [comment]
Never mind [what I said](https://github.com/Dogfalo/materialize/issues/729#issuecomment-115392590). Inbox brought the behavior back! I think it is a good idea to keep this library in line with Google's products. Hopefully this time they have settled on something.
