### ISSUE TITLE
[documentation] Error in Mobile Collapse Button section ?

### ISSUE THREAD

**Issue by VincentLoy** [Dogfalo/materialize#731]
Hello there !

I think there is a little error in the code example for **Mobile Collapse Button** in components/navbar section.

![navbar materialize](https://cloud.githubusercontent.com/assets/7996741/6314717/0e6874a8-b9ea-11e4-8675-c01a0bb4aca2.png)

NB : Materializecss is awesome :D :+1:

**Comment by acburst** [comment]
Fixed in d17bd8428c530a5c4be6a90684def9675b144b8b
