### ISSUE TITLE
Toast not working with meteor

### ISSUE THREAD

**Issue by binoy14** [Dogfalo/materialize#734]
Due to the way meteor handles global variables, toast is not working.

**Comment by Cerealkillerway** [comment]
if you put materialize's javascript file into /client/compatibility folder, it will work

**Comment by aviadbd** [comment]
Is this the recommended way to install the meteor/materialize package? I would imagine the package installer would do whats needed?

**Comment by scotta** [comment]
Just to be clear; you place the **non Meteor version** of the library into the `client/compatibility` directory after installing the Meteor package. Don't copy the version installed by Meteor.

**Comment by aviadbd** [comment]
That's what I've done and it worked, of course. I was just wondering if it's considered a workaround for a problem to be solved or part of what is a normal installation procedure of Materialize.

**Comment by Dogfalo** [comment]
Can a change in `package.js` fix this?
Or is there a way to make functions global in meteor? I have a lack of experience in Meteor, so I will need some guidance here if I am to fix it.

**Comment by aviadbd** [comment]
I think the way is to create an exported variable that encapsulates these methods. So it wont be a call to toast() but to, say, Materialize.toast().

**Comment by donaldaverill** [comment]
I submitted a pull request for this: #824. It should work as @aviadbd suggested.

**Comment by pajasevi** [comment]
Hi, I am trying to use toast() or Materialize.toast() which was merged in #824 but it still doesn't work. (Yes, I have tha latest package). Can please someone confirm, that this is still an issue or just my local problem?

**Comment by LuisHerranz** [comment]
I think the version of the package is the latest official release of materialize (0.95.3) and the fix for the toast in Meteor is newer.

There's been 102 commits after the release of the 0.95.3 release so I don't know when is @Dogfalo  going to do the next one. I hope is soon.

**Comment by pajasevi** [comment]
Thank you @LuisHerranz :+1:

**Comment by dcworldwide** [comment]
+1

**Comment by ForsakenHarmony** [comment]
broken again?
