### ISSUE TITLE
Parallax on document ready

### ISSUE THREAD

**Issue by chukitow** [Dogfalo/materialize#735]
I had an issue using parallax initializing it on the document ready callback

$(document).ready(function(){
  $('.parallax').parallax();
});

![error](https://www.dropbox.com/s/cysgc8x0adk4yf9/Screen%20Shot%202015-02-21%20at%209.38.05%20PM.png?dl=1)
in order to solve the issue what I did was to initialize it in window load

$(window).load(function(){
  $('.parallax').parallax();
});

![solution](https://www.dropbox.com/s/yscout40r7fukr2/Screen%20Shot%202015-02-21%20at%209.38.24%20PM.png?dl=1)

**Comment by acburst** [comment]
This should be fixed in the latest release
