### ISSUE TITLE
.btn i  =>  vertical-align: middle

### ISSUE THREAD

**Issue by mediasota** [Dogfalo/materialize#737]
= button_tag type: 'submit', name: 'commit', value: 'Search', class: 'waves-effect waves-light btn btn-block' do
  %i.mdi-action-search
  Search

.btn i {
	vertical-align: middle;
}

.btn-block {
	display: block;
	width: 100%;
}

**Comment by Dogfalo** [comment]
What is the problem you are describing?

**Comment by mediasota** [comment]
is not a problem, it's the desire to add to css

**Comment by acburst** [comment]
please be more specific when describing the feature you want.
