### ISSUE TITLE
Bug "Parallax Jumps On Load #628" not fixed using Firefox and Chromium in Ubuntu 14.10

### ISSUE THREAD

**Issue by brunomiguel** [Dogfalo/materialize#738]
Bug #628 not fixed using Firefox and Chromium in Ubuntu 14.10.

**Comment by brunomiguel** [comment]
the js file in bin/ has the fix, but the js file in dist/ doesn't. replaced and fixed

**Comment by carloscarcamo** [comment]
ooh, it a dirty fix, is supposed that the dist/ folder is for production. The core team should take a closer look in the way they're fixing all bugs.

**Comment by Dogfalo** [comment]
I'm not sure what this means, but the one is dist/ is always related to the latest release, while bin/ is the daily build

**Comment by carloscarcamo** [comment]
That means that the fix is not on release files yet?

**Comment by Dogfalo** [comment]
It was fixed in v0.95.3
