### ISSUE TITLE
showStaggeredList delay issue

### ISSUE THREAD

**Issue by tomatlscomm** [Dogfalo/materialize#739]
Hi.

Issue detected on function showStaggeredList().
When you call this function several time, the delay is constantly increased by 120 msec.

Correction to apply :
- file materialize.js
-- line 2978 - 2979 replace : 

showStaggeredList = function(selector) {
      $(selector).find('li').velocity(

by

showStaggeredList = function(selector) {
      time = 0;
      $(selector).find('li').velocity(

Regards

**Comment by acburst** [comment]
Fixed in a1303d9814dd2c1f09ef726a0f1c12d09e580236

Thanks for pointing this out!
