### ISSUE TITLE
slider bug?

### ISSUE THREAD

**Issue by Dontorpedo** [Dogfalo/materialize#741]
i cant upload images here, but it seems that the slider has a bug, after updating to 0.95.2 it looks like this on my testpage:

http://demo4.shopthemes.at/?MODsid=27fede554fbfdffe0627f527fc573b8f

what can be the problem?

after adding display:block to the slider img in css it works but still shows the content from the "alt" tag on the image

**Comment by acburst** [comment]
This is fixed on the latest commit, but not yet released

**Comment by Dontorpedo** [comment]
ok, thank you :)
