### ISSUE TITLE
Form label wrong position when input have default value

### ISSUE THREAD

**Issue by tthanh** [Dogfalo/materialize#744]
![screenshot from 2015-02-24 21 26 55](https://cloud.githubusercontent.com/assets/8962973/6351195/0f5b9c6c-bc6c-11e4-8cb0-5576c605e264.png)

**Comment by EatSalad** [comment]
i got the issues too.

i use this everytime : 
```
		$('input').each(function(index, el) {
			if ($(this).val() != '') {
				$(this).next('label').addClass('active');
			}
		});
```

**Comment by tthanh** [comment]
@EatSalad nice solution, I forgot I can use javascript. Input tag always need before label tag?

**Comment by EatSalad** [comment]
if you're using my code yep, you can also put input inside labels probably. I didn't try ...

**Comment by Dogfalo** [comment]
If you are loading something with a value, just add active to the label as well.
