### ISSUE TITLE
Font artifacts

### ISSUE THREAD

**Issue by tchaecker** [Dogfalo/materialize#745]
On my Win7 computer I have issues with artifacts on the fonts with IE, Safari and Mozilla while it worked fine on Chrome and my Android phone. Example: http://prntscr.com/6975v0

I could fix this by using the google fonts css: 
```<link href='http://fonts.googleapis.com/css?family=Roboto:400,500,700,300' rel='stylesheet' type='text/css'>```

I asked in the gitter chat and some people I know and the Win7 users (not Win8 / Linux however) reported the same issue. I'm not sure if it's not a config problem but I think it's worth bringing this up to see if other Win7 users have the same issue.

Edit: The same issue is on the materialize documentation page: http://prntscr.com/69als0

**Comment by RaSeR** [comment]
Confirm win7 same issue, same fix. mac os, linux and win8 - don't have this problem. Its about OS font rendering. I think we should just recompile font files.

**Comment by Dogfalo** [comment]
What do you mean recompile? These are the font files Google distributes

**Comment by tchaecker** [comment]
I think the fix would be to include different file types for the fonts (woff, eot, svg). For example if I open the page with the Google fonts css I get 

a .woff2 file in Chrome and Mozilla
a .woff file in Internet Explorer 11
a .ttf file in Safari

I did not check older IE versions or Opera. Google based files can cause issues in many countries (China being a prime example). So it would be nice to have a working option for locally stored files. A start would be to include .woff and .woff2 files and add them to the css in that order.

As far as I understand browsers use the first font version they understand. Something like this could work:
```font-family: 'Roboto';
font-style: normal;
font-weight: 400;
src: url('Roboto-Regular-webfont.woff') format('woff'),
url('Roboto-Regular-webfont.woff2') format('woff2'),
url('Roboto-Regular-webfont.ttf') format('truetype');```

**Comment by Dogfalo** [comment]
The other formats for Roboto 2 aren't available and I'm not sure if converting the files is a good solution.

**Comment by tchaecker** [comment]
Changing the user agent with Chrome UA Spoofer allows to download the different versions. You can download them with the urls available from the CSS files.

**Comment by Dogfalo** [comment]
From what URL?

**Comment by tchaecker** [comment]
.woff2 file urls can be found here: http://fonts.googleapis.com/css?family=Roboto:400,500,700,300

For Regular (400), latin: http://fonts.gstatic.com/s/roboto/v15/CWB0XYA8bzo0kSThX0UTuA.woff2

They need to be renamed.

Everything but .woff2 can be downloaded there (click on WebFontKit): http://www.fontsquirrel.com/fonts/roboto

**Comment by Dogfalo** [comment]
But this is just Roboto and not Roboto 2

**Comment by tchaecker** [comment]
Where did you get the Roboto 2 .ttf files?

**Comment by Dogfalo** [comment]
http://www.google.com/design/spec/style/typography.html

**Comment by tchaecker** [comment]
Found it: http://fonts.googleapis.com/css?family=Roboto2:bold,regular,italic,thin,light,bolditalic,black,medium&lang=en

Change the user agent to get the different versions.

**Comment by Dogfalo** [comment]
Ah great, We'll add this soon and hopefully that will increase compatibility. Thanks for finding this!

**Comment by tomByrer** [comment]
[Google Fonts is hosting the Roboto 2014 version](https://code.google.com/p/googlefontdirectory/issues/detail?id=351).  It was named "Roboto" last I checked.  I'm not sure if Google of the font designer called it 'v2', & what the differences are.  v2 has round-dots for `i` & `j` IIRC, old version was square.

Either way, I hope WOFF2 fonts are included in the CSS.  http://caniuse.com/#feat=woff2

Honestly, I think Google Fonts CDN host is best for deployed sites.  I can see including them for ease of development, but might be better to download fresh versions as part of your 'build' script?

**Comment by RaSeR** [comment]
Great news :)

**Comment by Dogfalo** [comment]
Added in 9436ca4ef2ae7d4a1b3d734d085abdb6cb85b243

For now we won't use a google hosted version, because it isn't part of Google Fonts yet. We don't want to include an unstable CDN since It could be removed or changed at any time.
