### ISSUE TITLE
ASP.Net MVC Checkbox

### ISSUE THREAD

**Issue by edokan** [Dogfalo/materialize#746]
Hi,

When using ASP.Net MVC Checkbox helper, it creates an additional hidden input after original element which causes css rule what displays the check tick does not match.

```html
<input id="RememberMe" name="RememberMe" type="checkbox" value="true">
<input name="RememberMe" type="hidden" value="false">
<label for="RememberMe">Remember me?</label>
```

**Comment by Dogfalo** [comment]
If you can't find a way to prevent the insertion of the hidden field, you will have to use JavaScript to move these extra elements.

**Comment by LoRdPMN** [comment]
I know this is old, but I had the same problem and I want to share my solution using the SASS version:

In the file /forms/_checkboxes.scss, everywhere you see a "+ label" change to "~ label", you can do a replace all if you want.
Just be aware that the parent HTML node can't have another label element.

I think this should be corrected in the library, but it's up to the owners.
