### ISSUE TITLE
Collapsible Preselected documentation update

### ISSUE THREAD

**Issue by carlosperate** [Dogfalo/materialize#748]
Download latest release today (https://github.com/Dogfalo/materialize/commit/6e611105cd599fd12ad8b7b2a6b7c141858734d6) to try the preselected collapsible, however I cannot get it to work.

I've tried the following gist with both accordion and expandable, but it seems like as soon as the page is opened it is expanded but something else is making it close immediately:
https://gist.github.com/carlosperate/6e0a592cbf8b7993d5c3

Tested in Windows 8.1 Firefox, Chrome and IE11.

**Comment by Dogfalo** [comment]
Don't initialize the collapsible twice

**Comment by carlosperate** [comment]
Are the two initialisations these?
```
<ul class="collapsible" data-collapsible="accordion">
```
```
$('.collapsible').collapsible({accordion : true });
```

If the `$('.collapsible').collapsible({accordion : true });` is only required when the collapsible is added dynamically, it's a bit confusing that the example code is written within the `$(document).ready(function(){});`.

**Comment by Dogfalo** [comment]
Yes, sorry about that. We'll try and remove some of those so it is less confusing. Perhaps change the title of the issue now so we remember to fix the docs.

**Comment by carlosperate** [comment]
Ok, thanks for the clarification. I have updated the title as well.

**Comment by acburst** [comment]
This should now be in the documentation
