### ISSUE TITLE
Mobile Collapse Button brand-logo vertical alignment at low resolutions

### ISSUE THREAD

**Issue by carlosperate** [Dogfalo/materialize#749]
Downloaded the latest release today (6e61110) and copied and pasted the 'Mobile Collapse Button' example code from the latest documentation. When the page resolution is low enough to trigger the hamburger icon, the 'brand-logo' title vertical position goes too high asshown in the screenshot below.

Code: https://gist.github.com/carlosperate/6e0a592cbf8b7993d5c3
Tested in Windows 8.1 Firefox, Chrome and IE11.

![logo](https://cloud.githubusercontent.com/assets/4189262/6363038/46124afc-bc8b-11e4-9bbe-c7ba1681ba31.png)

**Comment by Dogfalo** [comment]
We fixed the documentation, nav-wrapper should a direct descendent of `<nav>`
