### ISSUE TITLE
Sass workflow and folder structure

### ISSUE THREAD

**Issue by smichaelsen** [Dogfalo/materialize#751]
This is more a general question/discussion than an issue. Hope it's okay to have it in here.

I changed my materialize based project to use SASS and I was wondering what the _proper_ way is. Here is what I did:
- Instead of using the shipped `materialize.scss` with all the includes I copied the file over to another folder and commented out all components which I'm currently not using in my project.
- I included my own `_variables.scss` after the one from materialize to overwrite certain options.

So this is what I ended up with:

```
@charset "UTF-8";

// Mixins
@import "../materialize/sass/components/prefixer";
@import "../materialize/sass/components/mixins";
@import "../materialize/sass/components/color";

// Variables;
@import "../materialize/sass/components/variables";
@import "variables";

// Reset
@import "../materialize/sass/components/normalize";

// components
@import "../materialize/sass/components/global";
@import "../materialize/sass/components/icons-material-design";
@import "../materialize/sass/components/grid";
@import "../materialize/sass/components/navbar";
@import "../materialize/sass/components/roboto";
@import "../materialize/sass/components/typography";
@import "../materialize/sass/components/cards";
//@import "../materialize/sass/components/toast";
//@import "../materialize/sass/components/tabs";
//@import "../materialize/sass/components/tooltip";
@import "../materialize/sass/components/buttons";
//@import "../materialize/sass/components/dropdown";
@import "../materialize/sass/components/waves";
//@import "../materialize/sass/components/modal";
//@import "../materialize/sass/components/collapsible";
//@import "../materialize/sass/components/materialbox";
//@import "../materialize/sass/components/form";
//@import "../materialize/sass/components/table_of_contents";
//@import "../materialize/sass/components/sideNav";
//@import "../materialize/sass/components/preloader";
//@import "../materialize/sass/components/slider";
//@import "../materialize/sass/components/date_picker/default.scss";
//@import "../materialize/sass/components/date_picker/default.date.scss";
//@import "../materialize/sass/components/date_picker/default.time.scss";
```

This way I can customize materialize without making changes to its code base which lies in a git submodule in my project. Please feel free to point me to any better solutions or best practices. Thanks.

**Comment by tchaecker** [comment]
Good idea. I think one problem is that not only the _variables.scss needs changes but for example different colors need to be added or font-sizes adjusted. Updates on materialize overwrite these changes. 

SASS overwrites double declarations as far as I know. (for example h1 {font-size:20px} in _first.scss followed by h1 {font-size:24px} in _second.scss -- only h1 {font-size:24px} is in the output css).

The best option seems to clone the .scss files and include them after the original files in a new materialize.scss file. So all manual changes overwrite/complement the originals but updates do not overwrite changes. 

Obviously if bigger changes are made the manual updates still would need a rework but that's unavoidable during alpha.

**Comment by Dogfalo** [comment]
@tchaecker Take a look at [this](http://sass-lang.com/documentation/file.SASS_REFERENCE.html#variable_defaults_)

**Comment by tchaecker** [comment]
Thank you, I didn't think about that. 

However I'm still not sure what happens without the !default. I need to overwrite some font-sizes for example because I want the navbar to include the h1 sometimes. Other times I need to change the font-size to vw values to compensate the liquid grid. 

The question is which value is taken for the output file if I include two different font-sizes without the !default. 

Or to state the question better: What's best practice if I want to change the style of things that aren't declared with !default in the original materialize files. Does this depend on the sass compiler or is it a general rule?

**Comment by Kikketer** [comment]
I believe I'll be doing the same maneuver stated originally in this defect report.  I'm not sure how SASS handles multiple declarations, but I know LESS basically works through all the variables, taking the last.  Then compiles everything that uses them.  This tends to work better when overriding things in libraries such as this.

My build process does not include the source of this library in the repository, so I can't modify the source.  I'm going to have to recreate the entire files of any item i wish to override that doesn't use the !default.

Anyone thinking of porting to LESS?  ;)
