### ISSUE TITLE
Fixed nav with Overflow hidden causes sidenav to be cut off

### ISSUE THREAD

**Issue by Dogfalo** [Dogfalo/materialize#757]

**Comment by pfafman** [comment]
+1.  You probably know this but this was not an issue in version 95.2.

**Comment by Dogfalo** [comment]
yep.

On Thu, Feb 26, 2015 at 12:42 PM, Timothy Pfafman <notifications@github.com>
wrote:

> +1. You probably know this but this was not an issue in version 95.2.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Dogfalo/materialize/issues/757#issuecomment-76226247>.
>



-- 
Doggy sends his greetings from Mars.

**Comment by Dogfalo** [comment]
Fixed in  f841772a15984df753b79d55da16c478467fd83c
