### ISSUE TITLE
Checkboxes and radio buttons not working in rails 4

### ISSUE THREAD

**Issue by kockok** [Dogfalo/materialize#758]
![screen shot 2015-02-26 at 2 30 19 pm](https://cloud.githubusercontent.com/assets/232541/6387295/0b595416-bdc4-11e4-97df-e4792c63d9bc.png)
```
  %p
    %input{:type => "radio"}
    %label{:for => "test5"} Red
  %p
    %input{:type => "checkbox"}
    %label{:for => "test5"} Red
  %p
    %input#test6{:checked => "checked", :type => "checkbox"}/
    %label{:for => "test6"} Yellow
```

I use the sass version.

when I click the two unchecked boxes, no change in their state.
However, When I click the checked one, it works.

**Comment by Dogfalo** [comment]
Your first radio button and checkbox do not have id's

**Comment by Dogfalo** [comment]
Your first two checkboxes don't have id's

On Thu, Feb 26, 2015 at 1:34 AM, Jason Wong <notifications@github.com>
wrote:

> [image: screen shot 2015-02-26 at 2 30 19 pm]
> <https://cloud.githubusercontent.com/assets/232541/6387295/0b595416-bdc4-11e4-97df-e4792c63d9bc.png>
>
>   %p
>     %input{:type => "radio"}
>     %label{:for => "test5"} Red
>   %p
>     %input{:type => "checkbox"}
>     %label{:for => "test5"} Red
>   %p
>     %input#test6{:checked => "checked", :type => "checkbox"}/
>     %label{:for => "test6"} Yellow
>
> I use the sass version.
>
> when I click the two unchecked boxes, no change in their state.
> However, When I click the checked one, it works.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Dogfalo/materialize/issues/758>.
>



-- 
Doggy sends his greetings from Mars.
