### ISSUE TITLE
requesting option: show parent link in dropdown

### ISSUE THREAD

**Issue by Dontorpedo** [Dogfalo/materialize#760]
once the screen is reduced to small/medium view, the menu's parent items click through to display the sub menu items . But what if one want to allow the user to access the parent menu item's link?

i know it would be possible to make a category without a link, but this is problematic in many cms.. and 
from a usability point-of-view there should be an option to display the parent item's link in the dropdown (especially for mobile devices)

**Comment by Dogfalo** [comment]
Look at the dropdown options, this is already included

**Comment by Dontorpedo** [comment]
o sorry, didnt know that, cant find it in the options, which one is it??

 ``` $('.dropdown-button').dropdown({
      inDuration: 300,
      outDuration: 225,
      constrain_width: false, // Does not change width of dropdown to that of the activator
      hover: false, // Activate on click
      alignment: 'left', // Aligns dropdown to left or right edge (works with constrain_width)
      gutter: 0, // Spacing from edge
      belowOrigin: false // Displays dropdown below the button
    }```

**Comment by Dogfalo** [comment]
`belowOrigin`, but if you want a parent link, just add one in the html markup in the dropdown.
