### ISSUE TITLE
[Meteor] Wrong Github repo for Atmosphere package 

### ISSUE THREAD

**Issue by jshimko** [Dogfalo/materialize#761]
The Github repo defined in the package.js of [the Materialize Meteor package][1] should be the repo for the package itself, not this repo.  That said, it's unclear where the source is for the Meteor package.  It doesn't appear to be in this Github account.

[1]: https://atmospherejs.com/materialize/materialize

**Comment by Dogfalo** [comment]
It is this repo!

**Comment by jshimko** [comment]
Ha!  Oops.  

 I saw all the other unrelated stuff and assumed this was just the main project.  My bad.
