### ISSUE TITLE
Using 0.95.3, I get an error about scrollFire

### ISSUE THREAD

**Issue by chrisronline** [Dogfalo/materialize#764]
```
Uncaught ReferenceError: scrollFire is not defined
```

Using both downloaded 0.95.3 and off [the CDN](https://cdnjs.cloudflare.com/ajax/libs/materialize/0.95.3/js/materialize.js)

Looks like the grunt dependency order for the js files is wrong. Will fix in PR

**Comment by chrisronline** [comment]
False alarm. Something wrong in my env

**Comment by Dogfalo** [comment]
For future reference, what was the problem?

**Comment by chrisronline** [comment]
I'm not too sure - I'm resurrecting a site that I made years ago and I had some lazy loading logic to load my scripts instead of simply including them on the html page. It was something with that because when I removed it and just put <script> tags, it worked fine. If I have time later today, I'll dig more into it and see if I can come up with a better explanation
