### ISSUE TITLE
cropped Logo for container in nav on mobile

### ISSUE THREAD

**Issue by tobeportable** [Dogfalo/materialize#766]
- From the starter template : http://materializecss.com/templates/starter-template/preview.html
- Reproducible in firefox mobile mode or on my phone
- The logo gets cropped on mobile as seen here : ![](http://i.imgur.com/hpxKoOG.jpg)

**Comment by carlosperate** [comment]
Documentación issue reported in https://github.com/Dogfalo/materialize/issues/749 I guess the template needs to be updated as described in there.

**Comment by Dogfalo** [comment]
Yes, we'll fix this.

**Comment by Dogfalo** [comment]
Fixed in 78a28a40f40ee9d13243fefc5124756b0d688a45

**Comment by tobeportable** [comment]
much :heart:  soo :zap:  +1
Definitely pushing me to move this app from :b:ootstrap to :m:aterialize
