### ISSUE TITLE
consider using semver for library versioning

### ISSUE THREAD

**Issue by devoncarew** [Dogfalo/materialize#772]
Have you thought about using semver (http://semver.org/) for your versioning? The idea behind it is that the version ranges tell users something about the versions they can reliably depend on. So, I can depend on `>=1.0.0 <2.0.0` (or `>=0.9.0 < 0.10.0`), and know that within that range the library will be API compatible with my application.

You're close currently (`x.95.x`), but went from `0.8.0` to `0.9.0` to `0.91` instead of `0.10.0`, and I don't believe are using your minor version like semver would want (pre-1.0).

**Comment by Dogfalo** [comment]
We realize we messed up the versioning for the early releases. Also I think it's adherent enough now. In alpha any minor version increment will mean that there are either significant additions to the framework or incompatible implementation changes.
