### ISSUE TITLE
Ability to modify fixed button

### ISSUE THREAD

**Issue by lee-40square** [Dogfalo/materialize#774]
Beautiful button and the effect is perfect! I'd love to be able to have some options to modify it. For instance, I can move it to the top right, but the drawer then open backwards. I see the button.js file but short of recompiling all the js I don't see any other way to modify this. It seems like the materialize.js is mostly minified as well so kinda hard to play around in there.

**Comment by Dogfalo** [comment]
This is one of the newer features, so we will have to work on some enhancements/customization options. However it would be more helpful if your issue/feature request was more specific.

**Comment by lee-40square** [comment]
To keep things simple to start, a positioning option for the child buttons drawer relative to the parent: left, right, top, bottom. Regardless of the position, the effect should always be from the parent outward.

I hope this project translates into big things for you guys. It's honestly some of the best work I've seen in this area. The Angular Material team could learn a few things from you guys.
