### ISSUE TITLE
Tooltip conflicting with Fixed Action Button

### ISSUE THREAD

**Issue by EatSalad** [Dogfalo/materialize#775]
Yay !

I tried many time, but i can't managed this : When adding tooltip on the first button of Fixed Action Button, the tooltip appair correctly, but other button doesn't appair until your mouse 'hover' the shadow of it. and this, no matter where your tooltip class is on the first button (<a> or <i> of Fixed Action Button).

Here the exemple in inbox from google (i triggered :hover via chrome inspector) : 
http://image.noelshack.com/fichiers/2015/09/1425027670-tooltip-on-inbox.png

here what i got from materializecss : 
-> if i'm going a little too fast on the fixed button
http://image.noelshack.com/fichiers/2015/09/1425028028-tooltip-in-materializecss-1.png

-> if i'm going slowing on it, so hover the shadow before
http://image.noelshack.com/fichiers/2015/09/1425028028-tooltip-in-materializecss-2.png

Here the code : 
```
<div class="fixed-action-btn hide-on-small-only" style="bottom: 24px; right: 24px;">
	<a class="btn-floating btn-large light-green darken-1 tooltipped"
	data-position="left" data-tooltip="Open nothing :'(">
		<i class="large mdi-action-info-outline">
			<!-- If i put the tooltip on the <i>, the problem remains -->
		</i>
	</a>
	<ul>
		<li class="feedback">
			<a class="btn-floating red tooltipped" target="_blank"
				data-position="left" data-tooltip="J'ai trouvé un bug → avertir les développeurs">
				<i class="large mdi-communication-email"></i>
			</a>
		</li>
		<li>
			<a class="btn-floating yellow darken-1 tooltipped" href="http://<?=_DOMAIN_?>"
				data-position="left" data-tooltip="L'une des catégories est inaccessible → Rafraichir la page">
				<i class="large mdi-av-replay"></i>
			</a>
		</li>
	</ul>
</div>
```

**Comment by Dogfalo** [comment]
Works for me, http://codepen.io/Dogfalo/pen/YPvEdx

**Comment by EatSalad** [comment]
O.o 
Ok, i'll try to see why and put the answer here. It could be anything now :/
