### ISSUE TITLE
Why not able change automatically dropdown into dropup ?

### ISSUE THREAD

**Issue by mylastof** [Dogfalo/materialize#780]

**Comment by acburst** [comment]
There is not enough information here. Please don't just open an issue with no description. Give us more information on what you mean.

**Comment by 19Gerhard85** [comment]
What @mylastof probably means is:
When there is not enough space in the view port, to display the select dropdown items (without scrolling), the items should drop up.

![image](https://cloud.githubusercontent.com/assets/1492978/6437949/c1c9195e-c0c4-11e4-9739-fec8d0bc6642.png)

**Comment by rizkiandrianto** [comment]
Any answer?

**Comment by Dogfalo** [comment]
Dropdown does this now. Closing deprecated issue
