### ISSUE TITLE
Bottom Sheet style Modal

### ISSUE THREAD

**Issue by Dogfalo** [Dogfalo/materialize#781]
https://www.google.com/design/spec/components/bottom-sheets.html#bottom-sheets-specs
![](https://material-design.storage.googleapis.com/publish/v_2/material_ext_publish/0Bx4BSt6jniD7NHNBU0lmRXJNb2s/components_bottomsheets_specs5.png)

**Comment by acburst** [comment]
Added in c5ecd43aa543e4b83decd07e2b17d288fab176ef
