### ISSUE TITLE
Repository line endings pain

### ISSUE THREAD

**Issue by SmileyChris** [Dogfalo/materialize#784]
When looking at the repository in ubuntu, I get a bunch of files that are considered different due to the repository line endings setting. This causes an issue trying to switch branches or committing in general. It seems this is a problem on mac too (see #767).

The fix that works for me is to remove the `* text=auto` initial line from `.gitattributes`. Do we really need this setting hard coded?

**Comment by Dogfalo** [comment]
This way everything that is committed will have LF ending. [Take a look](http://stackoverflow.com/questions/21472971/what-is-the-purpose-of-text-auto-in-gitattributes)
