### ISSUE TITLE
Allow toast() to accept templates in Meteor

### ISSUE THREAD

**Issue by aviadbd** [Dogfalo/materialize#786]
The examples for toast() show how to use HTML code in a toast; however, I think that in Meteor it'll be more natural to specify a template to be shown. Can this be a feature for future releases of the meteor package?

**Comment by aviadbd** [comment]
For now, I just use Blaze.toHTMLWithData() to render the HTML - what I meant before is that this can be wrapped to be more native.

**Comment by Dogfalo** [comment]
toasts support html
