### ISSUE TITLE
Parallax: Glitchy With Scroll Wheel

### ISSUE THREAD

**Issue by danielhickman** [Dogfalo/materialize#787]
http://youtu.be/sUhbyaWIXwo

**Comment by Dogfalo** [comment]
Not happening for me, what is your browser and OS?

**Comment by danielhickman** [comment]
Chrome 42.0.2305.3 dev-m (64-bit); Windows 8.1

**Comment by danielhickman** [comment]
It works perfectly on Firefox, I didn't check it until now.

**Comment by Dogfalo** [comment]
Hard to pin down what this might, but let me know if adding `-webkit-transform: translate3d(0,0,0);` on the `.parallax` class fixes it

**Comment by danielhickman** [comment]
No it didn't. I know smooth scrolling is a problem with Google Chrome. There should be a way around it. www.boy-coy.com Works fine on Chrome but isn't Materialize.

**Comment by Chrisspitz** [comment]
I am also having the same problem. On Chrome on a Mac. Chrome version 41.02272.

**Comment by fahim-bakhtiar** [comment]
is there a fix for this problem at all?? -_-
i have tried the newest version, the glitch still is present

**Comment by williamfligor** [comment]
I see the same jitteriness on Safari 8.0.3 on Yosemite. Using magic mouse and the trackpad to scroll both produce the same jitteriness

**Comment by danielhickman** [comment]
Safari is also webkit based if I am correct. I think animating in between
scrolls would be the best option.

**Comment by acburst** [comment]
We hope this commit 3f3a19f9e0771729f91be4a25ea4f4764a05066f fixes these issues. Can we get anyone who experienced jitteriness before to confirm?

**Comment by carlosperate** [comment]
Still experiencing this problem in IE11 on Windows 8.1 with the new v0.96.0

**Comment by weiliank** [comment]
Works fine on Firefox but not Chrome.

**Comment by bruceCzK** [comment]
Maybe using the "background-position" way will have a better perfomance.

**Comment by LorenzoGangi** [comment]
I noticed some jittes in chrome when using the mousewheel. I fixed it by adding a mousewheel handler that  kills the native scroll and sets it consistently. Here is my solution http://ironlasso.com/materializecss-parallax-mousewheel-jitters-fix/

**Comment by Dogfalo** [comment]
Just as an FYI to anyone else reading, scroll hijacking can be very annoying to the user if overdone or not done well.
