### ISSUE TITLE
Card's card-reveal searchable in destructive ways

### ISSUE THREAD

**Issue by aviadbd** [Dogfalo/materialize#788]
Using Safari on a Mac, but I have a feeling this will reproduce elsewhere (I can try and check if needed):

Using the browser's search I've searched for a text that happens to appear on the card-reveal section of a card. The reveal area was found, and was shown, with no option to close it. 

The card:
![screen shot 2015-03-01 at 6 49 02 am](https://cloud.githubusercontent.com/assets/1906300/6429507/59b09c10-bfdf-11e4-95f7-17f660502b04.png)

The card after the search:
![screen shot 2015-03-01 at 6 48 43 am](https://cloud.githubusercontent.com/assets/1906300/6429509/66ca15e8-bfdf-11e4-8f84-c7a4371dd077.png)

**Comment by Dogfalo** [comment]
Fixed in c3f3cc25a127055fdaebb152c69e7a11fa8c98b7

**Comment by aviadbd** [comment]
Great, thanks!
