### ISSUE TITLE
Navbar brand-logo wrong position in small screen

### ISSUE THREAD

**Issue by tthanh** [Dogfalo/materialize#790]
![screenshot from 2015-03-01 17 11 53](https://cloud.githubusercontent.com/assets/8962973/6430298/483736fe-c036-11e4-8711-fc36415f73eb.png)
I'm using materialize version 0.95.3 bower package.

**Comment by yowkah** [comment]
your side-nav should not be inside the anv element. It loooks like that is the thing pushing your brand logo down. The button-collapse is absolute-positioned so it doesn't have that issue.

**Comment by tthanh** [comment]
I just do like Materialize Demo Navbar and on demo page nav work well

**Comment by yowkah** [comment]
ill make you a new example when im home, not able to type much on this thing xD

**Comment by tthanh** [comment]
@yowkah Thank you so much for help.

**Comment by Dogfalo** [comment]
Move the container class to its parent div. We have also update the templates.
