### ISSUE TITLE
empty tooltips

### ISSUE THREAD

**Issue by olivier67** [Dogfalo/materialize#791]
Possibly something I missed, but tiptools are empty in my app --- they show up correctly but with no data inside. I am using materialize-v0.95.3 in a rails app.
Any ideas ?

**Comment by Dogfalo** [comment]
Did you set the `data-tooltip` attribute?

**Comment by olivier67** [comment]
yes.

**Comment by Dogfalo** [comment]
What does your html look like?

**Comment by olivier67** [comment]
This is one of the a tags -- I have many on the page :

    <a class="waves-effect waves-light btn shift modal-trigger tooltipped" data-delay="50" data-position="bottom" data-toolip="duration : 6h" href="/shifts/259/edit?locale=fr">12:00 - 18:00 </a>

Near the bottom of my body end tag I have my initializers (after jquery) : 

    <script>
      $('.dropdown-button').dropdown({
          inDuration: 300,
          outDuration: 225,
          constrain_width: false, // Does not change width of dropdown to that of the activator
          hover: false, // Activate on click
          alignment: 'left', // Aligns dropdown to left or right edge (works with constrain_width)
          gutter: 0, // Spacing from edge
          belowOrigin: false // Displays dropdown below the button
        }
      );
      $(document).ready(function(){
        $('.tooltipped').tooltip({delay: 50});
        $('select').material_select();
      });
      </script>


And right after that I have multiple copies div elements : 

     <div class="material-tooltip"><span></span><div class="backdrop" style="top: 0px; left: 0px;"></div></div>

**Comment by Dogfalo** [comment]
It is misspelled "data-toolip"

**Comment by olivier67** [comment]
how embarrassing. Apologies I wasted your time.
