### ISSUE TITLE
Rails + Materialize: select doesn't select proper "selected" option

### ISSUE THREAD

**Issue by albertpak** [Dogfalo/materialize#797]
Using Materialize in my Rails 4.2 app, and having a problem with select to show proper "selected" option after form has been saved.

I've checked logs and variable does get saved.

I've tried:

```ruby
<%= f.select :state, options_for_select(apply_us_states, :selected => params[:state]) %>
```
and also tried
```ruby
<%= f.select :state, options_for_select(apply_us_states, params[:state])%>
```

Select works and shows options as it should, but won't select previously saved value.

**Comment by albertpak** [comment]
Nvm, got it sorted out.

This is what i had to do:

```ruby
<%= f.select :state, apply_us_states %>
```

```apply_us_states``` is a helper

hope this helps someone else

**Comment by RicardoG2016** [comment]
Can we see the helper you used for the options?
