### ISSUE TITLE
Parallax not working on mobile screen size

### ISSUE THREAD

**Issue by luismgz** [Dogfalo/materialize#798]
It's better now than before since the contents (text and button) remain within the background image while resizing.
But the parallax effect doesn't work on small screen size. The background image remains fixed, static.

Just check this website's parallax demo. Reduce the browser width and try scrolling down. 
The effect does not work.

**Comment by Dogfalo** [comment]
It will be laggy on any mobile device, I don't know if someone would actually want to use parallax on mobile

**Comment by acburst** [comment]
This is the intended effect.
