### ISSUE TITLE
Range Slider shows old value

### ISSUE THREAD

**Issue by kaelumania** [Dogfalo/materialize#801]
When clicking on any point on the slider the bubble shows the old value of the slider.

**Comment by Kestanous** [comment]
:+1:

**Comment by zenzire** [comment]
:+1:

![ezgif com-crop](https://cloud.githubusercontent.com/assets/363651/6985177/cbe3e9fc-da30-11e4-8cce-662da3ddf96f.gif)

**Comment by carlosperate** [comment]
Fixed in https://github.com/Dogfalo/materialize/commit/78a48bb064d03073c0f9525e6fd8dbf522ce4fcd
