### ISSUE TITLE
Get active tab

### ISSUE THREAD

**Issue by kalitk0** [Dogfalo/materialize#802]
How to get the active tab ID?

**Comment by acburst** [comment]
Using jQuery you can do a $('.tab').find('.active') and then find the ID

**Comment by YamilBracho** [comment]
Hi
I tried to do this but still it does not work, I have 3 tabs in a modal and an OK button, when this code:

`function processLogin() {
                var currentTab = $('ul.tabs').find('.active'); 
                console.log("currentTab = " + JSON.stringify(currentTab));
}`

But I always got the same json code and no info about to what is the current tab.

Would you mind to extend your explanation ...

TIA
Yamil
