### ISSUE TITLE
Callback for dismissable collection item

### ISSUE THREAD

**Issue by kalitk0** [Dogfalo/materialize#803]
Is there a callback to get the dismissed element ?

**Comment by acburst** [comment]
How would you want this callback to be structured?

**Comment by Dogfalo** [comment]
Added in 85cf36992fda00595f2fa4a7cb3db44eab7b2a85

**Comment by dvbondoy** [comment]
Hi! do we have this callback for dismissable collection. Like when i dismiss an item..i can call my function to also delete that item in my database.. thanks

**Comment by dvbondoy** [comment]
Hey everyone! I found this workaround and using it for the time being. I'm posting this for others that need this hack. I found this in StackOverflow..here's is the link http://stackoverflow.com/questions/2200494/jquery-trigger-event-when-an-element-is-removed-from-the-dom

I love this framework..I'll definitely donate when I sold my first app using Materializecss..Keep it up!

```javascript
(function() {
    var ev = new $.Event('remove'),
        orig = $.fn.remove;
    $.fn.remove = function() {
        $(this).trigger(ev);
        return orig.apply(this, arguments);
    }
})();

$('#some-element').bind('remove', function() {
    console.log('removed!');
    // do pre-mortem stuff here
    // 'this' is still a reference to the element, before removing it
});

// some other js code here [...]

$('#some-element').remove();
```

**Comment by morgler** [comment]
Thanks for the workaround.

It would be fantastic, if materialize could provide us with a callback. I'd need to know the element that has been swiped and the direction (left or right), so I can trigger a different action accordingly.

**Comment by tomscholz** [comment]
PR: https://github.com/Dogfalo/materialize/pull/2957

**Comment by acburst** [comment]
transitions.js has been removed for 1.0
