### ISSUE TITLE
Meteor renders form strangely

### ISSUE THREAD

**Issue by tobinharris** [Dogfalo/materialize#806]
Nice framework guys :)

Whenever meteor dynamically renders the form, it collapses the input field as if it doesn't have a value.

![image](https://cloud.githubusercontent.com/assets/25578/6447105/ad3b1ea4-c107-11e4-9aa3-42bbc660b384.png)

Example code below, but I've also tried copying the code directly from the example with the same results.

Any ideas welcome. 

    <div class="row">
        <form id="add_deal" class="" method="post" onsubmit="return false">

            <div class="col s12">
                <h5>Edit Deal</h5>
                <input type="hidden" name="deal_id" value="{{_id}}"/>
            </div>

            <div class="input-field col s12">
                <input type="text" id="account_name" name="account_name" class="validate"
                       value="{{accountName}}"/>
                <label for="account_name">Account Name</label>
            </div>

            <div class="input-field col s12">
                <input type="text" id="deal_name" name="deal_name" class="validate" value="{{dealName}}">
                <label for="deal_name">Deal Name</label>
            </div>

            <div class="input-field col s12">
                <input type="text" id="deal_value" name="deal_value" class="validate" value="{{dealValue}}">
                <label for="deal_value">Value</label>
            </div>

            <div class="input-field col s12">
                <input type="text" id="deal_status" name="deal_status" class="validate" value="{{dealStatus}}">
                <label for="deal_status">Status</label>
            </div>

            <div class="input-field col s12">
                <input type="text" id="deal_percent_chance_of_winning" name="deal_percent_chance_of_winning"
                       class="validate" value="{{dealPercentOfWinning}}">
                <label for="deal_percent_chance_of_winning">Confidence</label>
            </div>

            <div class="input-field col s12">
                <label for="deal_date_received">Received</label>
                <input type="text" id="deal_date_received" name="deal_date_received" class="datepicker"
                       value="{{dateReceived}}">

            </div>

            <div class="input-field col s12">
                <label for="dateClosed">Closed</label>
                <input type="text" id="dateClosed" name="dateClosed" class="datepicker" value="{{dateClosed}}"/>
            </div>

            <button class="btn waves-effect waves-light" type="submit" name="action">Save
                <i class="mdi-content-save right"></i>
            </button>

        </form>
    </div>

**Comment by Dogfalo** [comment]
Add `class="active"` to the labels. It will work

**Comment by tobinharris** [comment]
Worked like a charm. Thanks :)

#buy_that_man_a_beer
