### ISSUE TITLE
MegaMenus!

### ISSUE THREAD

**Issue by acburst** [Dogfalo/materialize#808]

**Comment by danielhickman** [comment]
:+1:

**Comment by tomscholz** [comment]
Are you referring to Cascading menus? https://material.io/guidelines/components/menus.html#menus-usage

**Comment by danielhickman** [comment]
@tomscholz  take a look through [this](https://www.google.com/search?q=mega+menu+wordpress&prmd=vin&source=lnms&tbm=isch&sa=X&ved=0ahUKEwiWw9CohoTTAhVC1mMKHT-kB6AQ_AUICCgC&biw=412&bih=604). They're desktop focused menus that are full width an contain practically site maps or images.

**Comment by tomscholz** [comment]
Yeah, I see. But how do you imagine such a mega menu, within the specifications of material design?
