### ISSUE TITLE
DatePicker looking funky in Meteor

### ISSUE THREAD

**Issue by tobinharris** [Dogfalo/materialize#810]
Using meteor to dynamically show a form with the date picker in it. I get...

![image](https://cloud.githubusercontent.com/assets/25578/6450215/3726533e-c11e-11e4-8741-3e15e6930979.png)

...instead of...

![image](https://cloud.githubusercontent.com/assets/25578/6450287/c43f9c94-c11e-11e4-9ec6-7c782b1635e4.png)

Form has this code at the bottom (a bit smelly this).

    <script>
        $('.datepicker').pickadate({
            selectMonths: true, // Creates a dropdown to control month
            selectYears: 3 // Creates a dropdown of 15 years to control year
        });
    </script>

Any thoughts appreciated folks :)

**Comment by Dogfalo** [comment]
A script in the bottom will be run when it is parsed, in meteor, if you generate it dynamically, it will most likely be created after the `<script>` is run. So the fix is to run this code when you generate the date picker.
