### ISSUE TITLE
Problem UX on cell phone

### ISSUE THREAD

**Issue by JuanLopezDev** [Dogfalo/materialize#811]
Hello, In the forms section, the effect of the box, is not fluent in the cell phone has second pause, the animation runs very slow. It would be nice to see other alternatives or exchange it for a more subtle. My cell phone is a Moto G 1st version

I really like your bookstore, I would use it for a dashboard of a system, but there are issues to be corrected. When is the official release? Thanks in advance Regards

**Comment by Dogfalo** [comment]
If you don't want the animation, just add class="active" to the labels.

I don't know what you mean by bookstore.

Don't have a release date for 1.0.0, but it will happen when we think it is time.
