### ISSUE TITLE
Mobile Nav issue with navbar-fixed?

### ISSUE THREAD

**Issue by keyscores** [Dogfalo/materialize#813]
Seems like there is a conflict between mobile side-nav and navbar-fixed. 

See this image, where the menu is incomplete. Seems to be rendering only within the nav div. 
![screenshot 2015-03-02 18 50 02](https://cloud.githubusercontent.com/assets/1364012/6453531/f71c8b66-c10c-11e4-8f6d-d24837112b2a.png)

FYI: I've simply used the template html,  in a Meteor project. Mobile nav works fine without the navbar-fixed class.

**Comment by Dogfalo** [comment]
This has been fixed in the dev builds, but right now you will just have to remove the`overflow:hidden`

**Comment by boustanihani** [comment]
@Dogfalo We have to remove ```overflow:hidden``` from where?
