### ISSUE TITLE
Fixed side nav does not reappear following drawer toggle and window resizing

### ISSUE THREAD

**Issue by thomaspaulin** [Dogfalo/materialize#817]
If the screen is below 'medium' width, the nav drawer is brought out, and then the viewport increased in width, the nav bar disappears until the width hits 'large' (1200px). This happens in Firefox 36 and Chrome 40 in both Windows and Linux.

Normal view:
![firefox-36-materialize-normal-nav](https://cloud.githubusercontent.com/assets/7918983/6462340/179982b2-c20d-11e4-8eee-420f071b789b.PNG)

Same page after opening the nav then increasing the viewport width to between 993px and 1200px:
![firefox-36-materialize-no-nav](https://cloud.githubusercontent.com/assets/7918983/6462341/17e26568-c20d-11e4-8eb9-6f7c128896c9.PNG)

**Comment by Dogfalo** [comment]
Fixed in a049f3bb9297b6f999d4bedb06e5f8fcb5a9fb57
