### ISSUE TITLE
Improperly styled regular (small) floating button

### ISSUE THREAD

**Issue by fegemo** [Dogfalo/materialize#820]
Hi,

I've just noticed that if I use .btn-floating in a button element (not an anchor tag) without the .btn-large class, the styling applied to the button is incorrect.

Consider this example for a quick visualization of the issue: https://jsfiddle.net/fegemo/0rumpgsu/

From the examples, I see that the .btn-floating class is supposed to be used with &lt;a&gt;s, not with &lt;button&gt;s. However, I think it's useful to be able to use real <button>s so we can have "submit"s, "reset"s etc.

Thanks!

**Comment by fegemo** [comment]
I also noticed from that same example (on jsfiddle) that the regular (small) button that uses &lt;a&gt; also lacks some styling (e.g., the color change upon hovering).

If I use .btn (instead of .btn-large), it fixes both cases.

If this is the intention (to always use either .btn or .btn-large), I think it's worth pointing out in the documentation.

If PRs are welcome, I can look into it.


Thanks again!

**Comment by acburst** [comment]
Fixed in 23e28ec21f753c48ac59dabe37a9ef19f86ad65d
