### ISSUE TITLE
Icon on left misaligns mobile menu accordian item

### ISSUE THREAD

**Issue by MichaelOber** [Dogfalo/materialize#821]
If you have an accordian/dropdown in your mobile nav menu with an icon on the left, the sizing and alignment of that particular menu item doesn't match the rest of the menu. This only seems to happen if the icon is on the left. In the example below, removing the caret on the right of "Settings" didn't change anything.

This issue only crops up when the window is resized to the "small" breakpoint. On Med or Large, it doesn't happen.

I have attached a screen shot below with the HTML.

![image](https://cloud.githubusercontent.com/assets/6620895/6470579/9b19b810-c1b2-11e4-81b0-88c2f013c4ca.png)

**Comment by Dogfalo** [comment]
Can you post code for this in [here](http://codepen.io/Dogfalo/pen/xbzPQV)?

**Comment by MichaelOber** [comment]
I put the relevant code here: http://codepen.io/moberegger/full/JoamxB/

And you can see the full screen here: http://s.codepen.io/moberegger/fullpage/JoamxB?

In order to get the issue to appear, the library had to be changed to 0.95.2. The issue seems to be resolved in 0.95.3.

**Comment by Dogfalo** [comment]
It is also fine on master ![](http://puu.sh/gts7N/0eab00e76d.png)
