### ISSUE TITLE
Roboto czech charset bug on last GIT versions

### ISSUE THREAD

**Issue by lukaspijak** [Dogfalo/materialize#823]
![error](https://cloud.githubusercontent.com/assets/2571714/6472189/cad10aac-c1f0-11e4-9f6d-7017dece9eac.png)

**Comment by Dogfalo** [comment]
What OS and browser? I didn't see this on my windows 8.1 chrome

**Comment by lukaspijak** [comment]
Windows 8.1 and Chrome 40. Do you test it on last git pull? On last version 0.95.3 it"s ok.

**Comment by Dogfalo** [comment]
I did test it on the latest commits.

**Comment by lukaspijak** [comment]
Do you try czech language?

**Comment by Dogfalo** [comment]
Yes I did.

**Comment by lukaspijak** [comment]
Its a strange...
![alvin](https://cloud.githubusercontent.com/assets/2571714/6499948/01ee2d4e-c304-11e4-9d73-e4cde6313b4b.png)

**Comment by Dogfalo** [comment]
Hey @lukaspijak, can you download the newest version on master and tell me if this problem still occurs? I am using different Roboto files now.

**Comment by lukaspijak** [comment]
Great solved :-) Its ok :-)

**Comment by Dogfalo** [comment]
Thanks for confirming!
