### ISSUE TITLE
Materialbox inside a card

### ISSUE THREAD

**Issue by royletron** [Dogfalo/materialize#825]
#568 seems to be happening again in `v0.95.3`

**Comment by Dogfalo** [comment]
We reverted the change because it creates problems with card-reveal. So we will not be supporting it. If you do not use card-reveal, you can just take off the `overflow: hidden`

**Comment by macsupport** [comment]
Can materialbox be opened from a link within a card rather than clicking on the image itself or is there no option to use it in a card at all?

**Comment by Dogfalo** [comment]
if you do not use card-reveal you can use materialbox on images.

**Comment by macsupport** [comment]
I assume you are saying that an image can not be opened using materialbox from a separate link.

**Comment by Dogfalo** [comment]
Well if you want a link to open it, you can just have the link trigger a click on the image.
