### ISSUE TITLE
Media Queries on showing HTML Elements not working

### ISSUE THREAD

**Issue by kockok** [Dogfalo/materialize#826]
Using sass version on Rails 4.2

```
.hide-on-small-only
  Not to be shown in small screens.
.show-on-small
  To be shown in small screens.
```

![screen shot 2015-03-04 at 5 13 29 pm](https://cloud.githubusercontent.com/assets/232541/6480774/4eda3354-c292-11e4-8e70-99adc5701cdd.png)
![screen shot 2015-03-04 at 5 13 43 pm](https://cloud.githubusercontent.com/assets/232541/6480775/4fe93a7e-c292-11e4-8c50-fe48a38de768.png)

The bottom element is supposedly showing only in small screens, but it does appearing on all types of screen.

**Comment by Dogfalo** [comment]
`.show-on-small` is not meant to make it only visible on small. It is to override any `display:none` for small screens.
