### ISSUE TITLE
Waves effect don't working inside owl-carousel plugin

### ISSUE THREAD

**Issue by genethic** [Dogfalo/materialize#827]
I know this is not a real issue but maybe someone had previusly had the same problem and can help me. It will be great if you would help me or give me a hint about and maybe it can also help improving this awesome framework.

I have use the floating button with waves for the Owl carousel jquery plugin navigation buttons, and for some reason the waves effect doesn't work. I supouse that something in the owl carousel css or js is interfering but I can't find it.

This is my code:

```javascript
("#intro-slider").owlCarousel({
	navigation : true, // Show next and prev buttons
	navigationText: ['<a class="btn-floating btn-black btn-large waves-effect waves-light animated" data-animation="zoomIn"><i class="mdi-hardware-keyboard-arrow-left"></i></a>','<a class="btn-floating btn-black btn-large waves-effect waves-light animated" data-animation="zoomIn"><i class="mdi-hardware-keyboard-arrow-right"></i></a>'],
	slideSpeed : 300,
	paginationSpeed : 400,
	singleItem:true,
	autoPlay : 5000,
});
```

Thanks in advance!

**Comment by Dogfalo** [comment]
Owl Carousel is probably capturing the click event.

**Comment by morshedx** [comment]
Solution is

```
$("#intro-slider").owlCarousel({
	pagination:true,
	touchDrag: false
});
```
