### ISSUE TITLE
Phantomjs error - node-webshot

### ISSUE THREAD

**Issue by Dallas62** [Dogfalo/materialize#828]
Hi!

Was using `node-webshot` to take a screenshot of a webpage when a bug append (black-screen).

After investigating, that is coming from Materialize:

```
TypeError: 'undefined' is not a function (evaluating 'document.querySelectorAll.bind(document)')

   http://127.0.0.1:8080/vendor/materialize/bin/materialize.js : 3
   http://127.0.0.1:8080/vendor/materialize/bin/materialize.js : 3
```
Then:
``` 
    TypeError: 'undefined' is not a function (evaluating '$('select').material_select()')
```

PS:
To display those errors in `node-webshot`, add this in `webshot.phantom.js` :
```
page.onError = function(msg, trace) {
    console.log(msg);
    trace.forEach(function(item) {
        console.log('  ', item.file, ':', item.line);
    });
};

page.onConsoleMessage = function(msg, lineNum, sourceId) {
  console.log('CONSOLE: ' + msg + ' (from line #' + lineNum + ' in "' + sourceId + '")');
};
```

**Comment by Dallas62** [comment]
`.bind()` not supported in PhantomJS
You can add a polyfill for `.bind()` or just close this issue, has you want.

**Comment by meichenblatt** [comment]
I am also getting errors when running phantomJS and materialize together.

Can I confirm that Materialize doesn't work with PhantomJS?

**Comment by Dallas62** [comment]
@meichenblatt you can use a polyfill to make it works. But I do not use phantomjs with Materialize anynore. We left Materialize for a custom style more appropriate for our needs.

**Comment by meichenblatt** [comment]
Thanks for your help!

I inserted the snippet of polyfill code from mozilla into the Meteor startup function. It didn't seem to do the trick. I got it from here: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Function/bind#Polyfill

Am I missing a step?

**Comment by Dallas62** [comment]
Have you tried with es-shim?
https://github.com/es-shims/es5-shim

**Comment by xxryan1234** [comment]
@Dallas62 es5-shim worked out for me. Thanks man.
