### ISSUE TITLE
can we use mithril as js lib instaed of jq 

### ISSUE THREAD

**Issue by ginus** [Dogfalo/materialize#829]
http://lhorie.github.io/mithril/
Mithril is a client-side MVC framework - a tool to organize code in a way that is easy to think about and to maintain.

Light-weight
Only 5kb gzipped, no dependencies
Small API, small learning curve
Robust
Safe-by-default templates
Hierarchical MVC via components
Fast
Virtual DOM diffing and compilable templates
Intelligent auto-redrawing system

**Comment by ginus** [comment]
bennifit are:
light-weight fit for mobile
fastest than jq
ui compenents

**Comment by Dogfalo** [comment]
This is an MVC framework, I don't see how it is meant as a replacement for JQuery. In any case we have no plans to switch.
