### ISSUE TITLE
It's very easy to get the fixed button menu "stuck" in a broken state.

### ISSUE THREAD

**Issue by skyhighwings** [Dogfalo/materialize#835]
A video demo is included below, but first...

1. Mouse over the fixed button area (above the fixed button)
2. Before the button is fully expanded, remove your mouse quickly.

The buttons will be in a broken state that is only repaired upon page reload.

![Relevant](http://i.imgur.com/6ueTWJi.gif)

**Comment by Dogfalo** [comment]
This does not happen for us. Please recreate it here http://codepen.io/Dogfalo/pen/xbzPQV

**Comment by skyhighwings** [comment]
It turns out the issue was due to accidentally including `materialize.js` twice in our application. Sorry for the frivolous bug report!
