### ISSUE TITLE
Dropdown not hiding properly with hover option

### ISSUE THREAD

**Issue by apolzon** [Dogfalo/materialize#837]
If you have a dropdown with `belowOrigin: true` and `hover: true`, and you mouseout of the activation element without touching the dropdown-content, the dropdown does not hide.

i.e. If you have a navbar with multiple dropdowns, and you drag your mouse along it, you end up with multiple visible dropdowns.
![screen shot 2015-03-04 at 3 08 25 pm](https://cloud.githubusercontent.com/assets/223493/6495585/5f62e8a4-c280-11e4-8f21-c20d59b09ce5.png)

**Comment by Dogfalo** [comment]
This has been fixed in one of the recent commits on master
