### ISSUE TITLE
CSS3 Transitions for SideNav

### ISSUE THREAD

**Issue by ianserlin** [Dogfalo/materialize#840]
Just want to point out that using something like:

```
transition: 0.2s ease-out;
transform: translateX(-250px);
	&.open {
		transform: translateX(0);
	}
```

has visual performance advantages over animating the `left/right` css property.

There might be a good reason you're animating left/right, but I also didn't see a issue tracked around this before.

**Comment by Dogfalo** [comment]
We need in between states as well when users drag with hammer handlers.
