### ISSUE TITLE
Cool Collapsible like Google Inbox

### ISSUE THREAD

**Issue by lukaspijak** [Dogfalo/materialize#841]
Google Inbox (New Gmail)

I can send invitation for inspiration. :-)

![inbox](https://cloud.githubusercontent.com/assets/2571714/6500673/19a096ce-c30f-11e4-9523-e734032d3e16.png)

**Comment by digitalcraftsman** [comment]
+1

**Comment by kabaka** [comment]
This concept is present in an increasing number of Google/Material Design products as the means of displaying basically all content. Definitely a necessity.

**Comment by Dogfalo** [comment]
Added in c211e1b5fe5da724f1f2eb3391ef86888a07dcc8
