### ISSUE TITLE
Lots of unneeded Vendor prefixed CSS (can be removed)

### ISSUE THREAD

**Issue by coliff** [Dogfalo/materialize#843]
There are lots of unneeded vendor prefixed CSS in the materialize.css file. Shall I open a PR with them removed? There is no need at all for
-moz-opacity (has never been needed in a shipping version of Firefox)
-moz-border-radius (has not been needed since Firefox 3.6 - 33 releases ago)
-moz-transition (not needed since Firefox 15)
-ms-transition (has never been needed)

There's also some Konqueror prefixed CSS but that browser has a >0.01% marketshare and isn't supported according to the project ReadMe. I'd suggest the -khtml- stuff can be removed too.

REF: http://caniuse.com/

**Comment by bobrocke** [comment]
Is the original source for Materialize Sass? If so, perhaps the CSS could be built using Autoprefixer so that each update would remove more and more prefixes as they became obsolete?

**Comment by Dogfalo** [comment]
Just let me know here what else does not need prefixing and I'll make the change.

**Comment by Dogfalo** [comment]
Removed opacity, border-radius, box-shadow.

**Comment by fega** [comment]
Hello guys, this is still valid? it looks solved.
please reopen if it is necessary
