### ISSUE TITLE
fix modal explorer 10...

### ISSUE THREAD

**Issue by LuisGerardoRC** [Dogfalo/materialize#847]
Overflow content, not working properly

**Comment by Dogfalo** [comment]
Either give a screenshot or code.

**Comment by carlosperate** [comment]
Maybe he's referring to https://github.com/Dogfalo/materialize/issues/604 , which has not been working for over a month now.

**Comment by LuisGerardoRC** [comment]
yes exactly #604, There will be some solution in the future?

**Comment by Dogfalo** [comment]
Duplicate
