### ISSUE TITLE
Support :indeterminate checkboxes

### ISSUE THREAD

**Issue by cvrebert** [Dogfalo/materialize#852]
See https://developer.mozilla.org/en-US/docs/Web/CSS/:indeterminate
Indeterminate checkboxes are basically in a "partially checked" state. E.g. If you have a tree of checkboxes and only some of the descendant checkboxes are checked, then the parent checkbox might be put in an indeterminate state by the JavaScript managing the form.

**Comment by Dogfalo** [comment]
Added in f1a42dddb11637b27b543265bb80c3738fd30937
