### ISSUE TITLE
Select and prefix icons

### ISSUE THREAD

**Issue by philipraets** [Dogfalo/materialize#853]
Is there an option for having prefix-icons with selects? 

This is what happens now:
![select with prefix](https://cloud.githubusercontent.com/assets/708011/6523809/87354696-c3f3-11e4-94e6-b4df866d3ace.png)

**Comment by EeKay** [comment]
+1 on prefix icons working for select... also for browser-default type selects if possible.
Can't quite get it right easily right now

**Comment by Licorb** [comment]
I solved this manually, with this solution you can't have selects without prefix in your pages (but you can create another classe tough)

In form.scss, from line 458, added
    width: 92%;
    width: calc(100% - 3rem);
    margin-left: 3rem;
and the media queries after display:block:
    @media #{$medium-and-down} {
        width: 86%;
        width: calc(100% - 3rem);
        }

    @media #{$small-and-down} {
        width: 80%;
        width: calc(100% - 3rem);
    }

**Comment by encubos** [comment]
Same issue here. 
I create a jsFiddle to illustrate. https://jsfiddle.net/rz0zk5u6/8/

**Comment by cbruyndoncx** [comment]
adding this css to the current input-field prefix settings for input and textarea seems to work for me,
```
.input-field .prefix ~ div.select-wrapper 
```

so section becomes
```
  .input-field .prefix ~ input, .input-field .prefix ~ textarea , .input-field .prefix ~ div.select-wrapper {
    margin-left: 3rem;
    width: 92%;
    width: calc(100% - 3rem); }
```

**Comment by felixcheruiyot** [comment]
Same case here https://monosnap.com/file/tF1v6ODDdnKMKAGHh8pU1dbVTZEFc4 

What is the progress on this? See also the error message display issue on image. I think it will be proper if we can have a help message class and it should be well indented whenever an prefix icon is used.

**Comment by Sajonara** [comment]
Can confirm this. I'd be glad if this would be fixed. I'm using the materialize-sass gem for my rails projects. This would benefit, too.

**Comment by zhangfei614** [comment]
I think it should be fixed.

**Comment by Queatz** [comment]
+1 still seems to not behave correctly.

**Comment by kmmbvnr** [comment]
Fixed - https://jsfiddle.net/va9afvoo/

Can you please close the issue?

**Comment by TenaciousDan** [comment]
This is not quite finished. When opening/closing the select, the class "active" should be toggled on the prefix icon. This will make the prefix icon consistent with other inputs.

**Comment by TenaciousDan** [comment]
I'm fairly new to MaterializeCSS, so please forgive me if i'm incorrect.  
After examining [select.js](https://github.com/Dogfalo/materialize/blob/v1-dev/js/select.js), I believe all that is needed is to add the following line to beginning of `_handleInputClick()`:  
```javascript
$(this.wrapper).prevAll("i.prefix").toggleClass('active');
```
