### ISSUE TITLE
Select down arrow does not trigger dropdown

### ISSUE THREAD

**Issue by tchaecker** [Dogfalo/materialize#854]
Clicking on the down arrow to the right does not trigger the dropdown. The whole area to the left works. 

Tested with Windows 7 Chrome, IE11, Safari and Mozilla.

**Comment by Dogfalo** [comment]
This was fixed, but is not in a release build yet.

**Comment by MattgyverHub** [comment]
I got it to work by giving the select wrapper i element a z-index:-1. Try this, it won't work in all situations, and you may have to have a relative positioned div to keep the visuals from going behind the page:

    .select-wrapper i {
        z-index: -1;
    }
