### ISSUE TITLE
Datepicker doesn't work in chrome.

### ISSUE THREAD

**Issue by Pantic14** [Dogfalo/materialize#855]
Hi. I am creating a form that has a datepicker, I do but doesn't work in chrome, I just try firefox and here if it works, when I select the field in chrome does not emerge any datepicker.

**Comment by dhawken** [comment]
What happens if you go to the docs for Datepicker in Chrome?  It works fine for me, both there and in my apps.

**Comment by Dogfalo** [comment]
I haven't yet seen an issue of datepicker not working in chrome.
