### ISSUE TITLE
sidenav bug on form resize

### ISSUE THREAD

**Issue by IliasDeros** [Dogfalo/materialize#858]
I found a bug where the sidenav does not appear when resizing window :
![materialize-sidenav-bug_capture](https://cloud.githubusercontent.com/assets/9534435/6531568/3098a34a-c408-11e4-8ed2-7eff5cf4a3e7.PNG)

Steps to reproduce:
1- Open a small html page with sidenav navigation as of http://materializecss.com/
2- Expand the sidenav (top-left icon in materializecss website)
3- Enlarge window's width

**Comment by Dogfalo** [comment]
Fixed in a049f3bb9297b6f999d4bedb06e5f8fcb5a9fb57

**Comment by riiccardo** [comment]
just wwtf
