### ISSUE TITLE
Select value not bind with scope.

### ISSUE THREAD

**Issue by nandhagam** [Dogfalo/materialize#860]
Hi, I am new to materialize. I create a modal using materialize and angularjs. And I placed a select in that. The options are selected but the ng-model won't get the selected value. Please help me.

**Comment by Dogfalo** [comment]
Please search existing/close issues.

**Comment by nandhagam** [comment]
Hi friend, will you please give me any link about that issue. because I already searched in our forum

**Comment by viniciusmelquiades** [comment]
I have created a modal in Angularjs. It was a bit of code to write, and it requires a good understanding of scopes. I decided to create a [gist](https://gist.github.com/viniciusmelquiades/3654a3520ecda1d198f4) with my code. As for the `select`, see issue #706

**Comment by nandhagam** [comment]
Thank you viniciusmelquiades. You gave best response than Dogfalo.

**Comment by viniciusmelquiades** [comment]
@nandhagam  I just happen to be developing an app using materialize. It's no big deal. I think I'll write a angular lib for materialize. At least the controls (such as the select) and the modal.

**Comment by pradeepb6** [comment]
Can i get any help regarding this issue? I tried with browser default. it works fine. but it looses material design, 

http://stackoverflow.com/questions/29402495/values-not-showing-up-in-select-button
