### ISSUE TITLE
Datepicker reopens when changing tab

### ISSUE THREAD

**Issue by piuccio** [Dogfalo/materialize#864]
Happens on Chrome on this page http://materializecss.com/forms.html

* Click on datepicker
* Click somewhere else, the datepicker closes correctly
* Switch to another tab or window
* Go back to the previous page and the datepicker is open

Shouldn't it stay closed?

**Comment by danielhickman** [comment]
You're right it's still sending some sort of intent (although that probably isn't the word for it in web development)

**Comment by Dogfalo** [comment]
See https://github.com/amsul/pickadate.js/issues/160
