### ISSUE TITLE
Problems with Assigning Styles to Cards

### ISSUE THREAD

**Issue by danielhickman** [Dogfalo/materialize#865]
If I assign a display style to `initial` (some others may also trigger it) on a card div, it clears the background and shadows. I am not sure if this is a bug but the easy work around is to assign that value to a containing div.

**Comment by Dogfalo** [comment]
This is because you are essentially changing it to `display: inline` instead of `display: block`. I don't think box-shadow is supported for `display: inline`

**Comment by danielhickman** [comment]
Thanks for helping me out!
