### ISSUE TITLE
What is the best way to customize sass + js files but by getting latest fixes from master?

### ISSUE THREAD

**Issue by surjithctly** [Dogfalo/materialize#866]
I have downloaded and tweaked some settings in Sass and Js files. But Now I noticed there are many fixes added to the master. 

But I cannot replace the new one because I have edited it in my end. Is there any good way to keep my changes also your changes?

How to use this properly?

**Comment by bobrocke** [comment]
Great question! And one I have too. Is there some sort of inheritance pattern that would allow local customizations while still keeping the base Materialize code untouched and easily replaced with new versions?

**Comment by Mark-Creeten** [comment]
git stash
git pull --rebase
git stash pop

sounds logical, not?

**Comment by surjithctly** [comment]
@Mark-Creeten No Idea how this commands works. Yes. I'm a newbie in git. Using the Windows GUI. Works better.

Can you explain what does that do and how to use it with Materialize? Any help would be appreciated.

**Comment by Mark-Creeten** [comment]
@surjithctly those are the command line commands to set your changes aside (git stash), getting the new updated version of Materialize (git pull --rebase), and applying your changes again on to the updated version (git stash pop).
Maybe you have this option too in the GUI?

**Comment by bobrocke** [comment]
I think the broader question is not so much how do you move the code around, but how is it best to structure it? The `git stash pop` may break something if the "wrong" files get overwritten.

Is there a place in Materialize where it's recommended to keep customizations that will not be overwritten by framework updates?

**Comment by surjithctly** [comment]
Oh.. great. Will there be any conflict when updating?

Its not in GUI, I think.

And, Is there any other Modular way do you recommend for those who don't
have git ?

**Comment by Mark-Creeten** [comment]
a better approach would be, not to work on the "git/download/original/to be updated" version, but rather on a copy of that, so eliminating the problem of having changes that can not be overwritten by frameworks update.

Also a good habit is a separate file to over-rule certain css you need to change, in this case the framework can be updated without problems.

**Comment by bobrocke** [comment]
Here's the scenario I'm after. I'm using the Sass version of Materialize. I want to change some framework options by changing the value of customization variables. If I make those changes in `website/materialize.scss`, they will be overwritten on the next revision to Materialize.

Is there a safe place to make those changes to Sass variables?

**Comment by jezmck** [comment]
Create your own file which imports the sass components.

Mine is like this:

```
@charset "UTF-8";

// Mixins
@import "components/prefixer";
@import "components/mixins";
@import "components/color";

// Variables;
$h1-fontsize: 3.00rem;
$h2-fontsize: 2.25rem;
$primary-color: color("blue", "base");
$secondary-color: color("grey", "base");
$link-color: $primary-color;
@import "components/variables";

// Reset
@import "components/normalize";

// components
@import "components/global";
@import "components/icons-material-design";
@import "components/grid";
@import "components/navbar";
//@import "components/roboto";
@import "components/typography";
@import "components/cards";
//@import "components/toast";
//@import "components/tabs";
//@import "components/tooltip";
@import "components/buttons";
@import "components/dropdown";
@import "components/waves";
//@import "components/modal";
@import "components/collapsible";
@import "components/materialbox";
@import "components/form";
@import "components/table_of_contents";
@import "components/sideNav";
//@import "components/preloader";
//@import "components/slider";
//@import "components/date_picker/default.scss";
//@import "components/date_picker/default.date.scss";
//@import "components/date_picker/default.time.scss";

/* My Styles */
html {
  font-family: GillSans, Calibri, Trebuchet, sans-serif;
}
/* ... */
```

Just uses the bits I need and doesn't overwrite Materialize's files.

You may want to move it elsewhere and adjust the paths.

**Comment by Dogfalo** [comment]
It really depends what you are changing, if you are editing variables, you can create an overrides file where you define the same variables and add that to the import. It will work if you import it before or after the original `_variables.scss` file.

**Comment by surjithctly** [comment]
Not just variables, But other component styles and some javascript..

**Comment by Dogfalo** [comment]
You can try to cherry pick changes or merge the two yourself.

**Comment by baraamashaal** [comment]
@Dogfalo 
i heat merging 
so !? 
is there is any way that i can know what have been changed from version to version !!

**Comment by jezmck** [comment]
Compare tags here on github.

**Comment by zjaml** [comment]
Not exactly the way I'd like it to be, but I found @jezmck's way the best.
