### ISSUE TITLE
sidnav does not disappear after clicking links to on-page anchors

### ISSUE THREAD

**Issue by bobrocke** [Dogfalo/materialize#867]
If the links in the side menu go to anchors on the same page such as `<li><a href="#top">Top</a></li>`, the sidenav does not disappear even though the link works and the page scroll.

**Comment by Dogfalo** [comment]
There is an option for this. `closeOnClick`

**Comment by bobrocke** [comment]
That works, and thanks.

But I would have expected this to be the default behaviour.

I did not need the `closeOnClick` open if the link was of the form:
```
<a href="/modular">Modular</a>
```

only if it was:
```
<a href="#top">Top</a>
```

**Comment by Dogfalo** [comment]
We can't handle every possible scenario. For those with Angular they may also want it to close on those type of links.

**Comment by bobrocke** [comment]
Perhaps it should always close on any targeted link, as the default. Use the option to override. Right now it's inconsistent.
