### ISSUE TITLE
Android Support

### ISSUE THREAD

**Issue by Marcel85** [Dogfalo/materialize#868]
Materialize dosn't support the Android browser. For example the modals with and without fixed footer are wrong positioned and the content is cutted in top (no full headline), the toasts are wrong positioned on small screen, the middle line of range bar isn't shown, the number of range isn't shown on sliding, and so on... Cause of the material design is defined by Google, thereforce I think Materialize should be supporting also Android. Is this browser support planed? If no I think Materialize is not usable for Android apps. If yes I would be glad.

**Comment by Dogfalo** [comment]
the modal is working, it is just because it is scrolling that it seems it is cut off. The toasts are also working. Range slider has a few bugs which are already being tracked. These are not issues relating to the android browser.

**Comment by Marcel85** [comment]
I use Android 4.3.

The toast is shown for less than one second along the whole width of the page and then it shows so how in the screenshot:

![screenshot_2015-03-08-22-42-47](https://cloud.githubusercontent.com/assets/11378617/6547850/1408674a-c5e5-11e4-8ee5-8b60cf7bf9aa.png)

When I scroll a modal without fixed footer to the end of bottom it shows so:

![screenshot_2015-03-08-22-42-31](https://cloud.githubusercontent.com/assets/11378617/6547865/52cb82a0-c5e5-11e4-8726-391e2ad88d2c.png)

An modal with fixed footer has not displayed foot and no headline:

![screenshot_2015-03-08-22-42-16](https://cloud.githubusercontent.com/assets/11378617/6547871/92d79e06-c5e5-11e4-9160-e842757d5f63.png)

**Comment by Dogfalo** [comment]
I guess it is just due to 4.3. These all work on my android browser with 5.0

**Comment by carlosperate** [comment]
Don't want to sound demanding, but taking in consideration that lollipop
has a 3.3% penetration rate, not making it compatible with at least 4.4
makes this framework unsuitable for android html apps.

**Comment by Dogfalo** [comment]
Well 4.4+ uses chrome webviews by default. so it is compatible with 4.4

**Comment by carlosperate** [comment]
That's great to know, probably also explains why I couldn't find the default browser in my kitkat test devices.

**Comment by mischaserlin** [comment]
Modals are definitely broken on anything native android below 4.4

**Comment by carlosperate** [comment]
It really does look like it, and I wouldn't count on support for that platform.

**Comment by mischaserlin** [comment]
it would be awesome to see a supported list on the getting started page. or somewhere. anywhere...

**Comment by carlosperate** [comment]
Their readme in this repository states the following:
```
Supported Browsers:
Chrome 35+, Firefox 31+, Safari 7+, IE 10+
```
Just not mobile browsers.
