### ISSUE TITLE
Input Forms Don't Move the Title with 'autofocus'

### ISSUE THREAD

**Issue by danielhickman** [Dogfalo/materialize#869]
The title doesn't leave the text box when you start typing on a preselected input.
```html
<input id="start-color" type="text" autofocus></input>
<label for="start-color">Your Color</label>
```
`Your Color` in this case will be stuck as the placeholder and doesn't animate to a title.

**Comment by Dogfalo** [comment]
Fixed in 87e0a031351aec0d40374cbda090b8a97c3189a5

**Comment by uok** [comment]
I tried the code above but the title does not move. 
Also tried `autofocus="autofocus"` (HTML4) - same result
and setting a blank space as the field's default value - which works but then you have a leading space which you need to trim everywhere...

Can somebody confirm that this is working?

**Comment by coniel** [comment]
+1 Not working for me either. As a workaround for now I use jQuery's focus() when the form is rendered to focus on the element I want. Using that works.

**Comment by ZyzioZiom** [comment]
Still not working!
