### ISSUE TITLE
Datepicker - pick -> close

### ISSUE THREAD

**Issue by grafa** [Dogfalo/materialize#870]
Hi,

it would be great if we had possibility (an option) to close datepicker when date was selected. It's shortcut to "select date" -> "click Close".

Thanks.

**Comment by ciencia** [comment]
It seems latest datepicker already does this by default, and provides an option to leave the picker open after selecting the date: http://amsul.ca/pickadate.js/date/#close-on-action

**Comment by Dogfalo** [comment]
This is how it was originally, but its behavior was changed to match Google's date picker.

**Comment by grafa** [comment]
@ciencia You are right, thank for the hint

@Dogfalo Thanks, I get that. Anyway if there would be the option, like in original pickadate.js is, it would be great. Frankly, when you choose a date, you don't need the calendar anymore -> close it.

**Comment by OminStyle** [comment]
@Dogfalo I also prefer the original behavior as well. What do you think about having the option to enable it with
```
$('.datepicker').pickadate({
  closeOnSelect: true
})
```

**Comment by harpster604** [comment]
+1

**Comment by harpster604** [comment]
@Dogfalo I would also like the option to have it close once the date is selected.

**Comment by mitramcc** [comment]
Yeah @Dogfalo closeOnSelect: true  would be great... does anyone have a work arround for this?

**Comment by ivanklun** [comment]
Workaround:
```javascript
$('.datepicker').pickadate({
	onSet: function( arg ){
		if ( 'select' in arg ){ //prevent closing on selecting month/year
			this.close();
		}
	}
});
```

**Comment by lebart** [comment]
@ivanklun thanks for the workaround. 
This should be mention in the docs if the closeOnSelect is not chosen. It's hard to find this in the closed issues.

**Comment by jvitorcarvalho** [comment]
thanks for the workaround, works fine

**Comment by simonsmiley** [comment]
Could you reconsider opening this? I don't think having the option to autoclose the picker would harm anyone

**Comment by lebart** [comment]
You should try the workaround @ivanklun suggested.

**Comment by carand315** [comment]
`$('.datepicker').pickadate({        
        onSet: (context) => {
            $('button[data-close]').click()
        }
    });`

**Comment by carand315** [comment]
`$('.datepicker').pickadate({        
        onSet: (context) => {
            $('button[data-close]').click()
        }
    });`

**Comment by jacek213** [comment]
I'm grateful for @ivanklun solution but that's still a hacky workaround - why is this issue closed without a proper solution?

**Comment by robertoradical** [comment]
After much research this has worked for me!!! version materialize 0.98.2

jQuery(document).ready(function(){
   $('#optDate').pickadate({format: 'yyyy-mm-dd'})
                      .on('change', function(){
                              $(this).next().find('.picker__close').click();
                      });
});

**Comment by fabo49** [comment]
@robertoradical great workaround, works for me thanks!
To implement the close on select functionality on **all** the datepickers just use this code based on @robertoradical solution.
```
    $('.datepicker').on('change', function(){
        $(this).next().find('.picker__close').click();
    });
```

**Comment by darckyn** [comment]
plz make the option to closeOnSelect work :)
