### ISSUE TITLE
Dropdown

### ISSUE THREAD

**Issue by cskiwi** [Dogfalo/materialize#875]
Hi, 

I'm having the issue, that when you click on a dropbox that it shows the content.but:
- It won't disappear if you click somewhere in the DOM or if you click on an item.
- It does disappear when you first click on an item in from the box and then somewhere in the DOM

I have an SPA with angular, so when I use the dropdown when switching views, the dropdown stays were it is (until you click somewhere else)

Any idea on why this behavior is happening?
EDIT: this is only on mobile

**Comment by Dogfalo** [comment]
Can you test the version on master? I think this issue has been fixed.

**Comment by cskiwi** [comment]
Yep, this is indeed correct,  my apologies!
