### ISSUE TITLE
Collapsible stopped working correctly on master

### ISSUE THREAD

**Issue by carlosperate** [Dogfalo/materialize#879]
I'm am not quite sure which update has cause this, but downloading the latest master (https://github.com/Dogfalo/materialize/commit/cec8a7ab9ea92f06d2cc79c0c716447150e4b3a) has cause the collapsible accordion effect to maintain more than one collapsible open (the opened `li` element does not close when a new one is clicked). Also, the latest expandable collapsible example from `collapsible.html` does not open any of the `li` elements at all.

Tested it on Windows 8 Firefox, Chrome and IE11

**Comment by serranoarevalo** [comment]
Same here, or sometimes when I collapse and uncollapse once it works, when I try to do it again it stops working.

**Comment by Dogfalo** [comment]
I'll look into it tomorrow.

**Comment by serranoarevalo** [comment]
Thank you :)

**Comment by Dogfalo** [comment]
Fixed in 6bad1c805134299b70796c762d2957e95320af1b
