### ISSUE TITLE
Input validation error for attribute required

### ISSUE THREAD

**Issue by ghost** [Dogfalo/materialize#882]
Hello @Dogfalo 

I am integrating jquery validation with materialize framework, I recognize that I have problem with validation on required field.

In materialize.js file, line 2271, you checked if the input was empty and has class **"invalid"**, we should remove both **"invalid"** & **"valid"** attributes. I think this is a problem, let assumption that, if the user didn't enter this field, we should keep the **"invalid"** class here.

Maybe we can change this line by

```
if (object.val().length === 0) {
    if (object.hasClass('validate')) {
        object.removeClass('valid');
        object.removeClass('invalid');
    }
}
```

=>

```
if (object.val().length === 0) {
    if (object.hasClass('validate') && typeof object.attr('required') !== typeof undefined) {
        object.removeClass('valid');
        object.removeClass('invalid');
    }
}
```

Best regards

**Comment by RogerAntonio** [comment]
Yes, I was looking around for something in the documentation on required fields, but found nothing.
Would be cool if it gets implemented in a way

**Comment by benelliott** [comment]
Hi @Dogfalo - I have the same issue. Do you have any thoughts on this?
