### ISSUE TITLE
Problem with phone verification

### ISSUE THREAD

**Issue by aimadnet** [Dogfalo/materialize#883]
I have a problem with the phone input validation, the field accept any value (eg : "xyz", "@@"..)

<input id="phone_number" name="phone_number" type="tel" class="validate">

Can you fix this ?

Thanks

**Comment by Dogfalo** [comment]
We just use HTML5 validation, so this is not possible.

**Comment by dhawken** [comment]
What's your input markup look like?  Its straight html5, so shouldn't be any different than any other framework.

**Comment by aimadnet** [comment]
@Dogfalo  ok thanks
@dhawken  < input name="phone_number" type="tel" class="validate">

**Comment by Dogfalo** [comment]
Use the pattern attribute, see [here](http://www.the-art-of-web.com/html/html5-form-validation/)

**Comment by aimadnet** [comment]
@Dogfalo Thanks :+1:
