### ISSUE TITLE
Navbar logo positioning problem on Chrome Android

### ISSUE THREAD

**Issue by otstrel** [Dogfalo/materialize#884]
Looks like logo alignment is being ignored with current Chrome Android, please see below screenshots taken at http://materializecss.com/navbar.html:

IE11 desktop:
![logo_right_desktop_ie11](https://cloud.githubusercontent.com/assets/3508928/6581892/e4e693a6-c76a-11e4-9aa6-c412325f75d2.png)

Chrome Android:
![logo_right_android_chrome](https://cloud.githubusercontent.com/assets/3508928/6581898/ea6a847c-c76a-11e4-9233-0ee56000de52.png)

**Comment by Dogfalo** [comment]
All logos are meant to be centered on mobile, you will have to override this if you want to change it.
