### ISSUE TITLE
Select as Dropdown: add function to recreate options

### ISSUE THREAD

**Issue by djhi** [Dogfalo/materialize#889]
**Use case: localization**

In my app (using Meteor), users can change current language. Thanks to Meteor templating engine, the select options update accordingly. But not the materialize dropdown which has already been created.

I need either a function to destroy the materialize_select behaviour (and remove dropdown) or a function to force it to recreate the dropdown.

Thanks !

**Comment by Dogfalo** [comment]
Duplicate of #819
