### ISSUE TITLE
Backbone marionette dropdown

### ISSUE THREAD

**Issue by T00rk** [Dogfalo/materialize#890]
In my project, I use materialize with Backbone Marionette.
I have a problem with dropdowns.

When I call `$('.dropdown-button').dropdown()` , the ul element is created at the end of the document, just before the end of `body` element.

This is a problem for two reasons. First, I can't bind events on dropdown buttons in my view because they're not located inside my view element and secondly because when I change window location, the ul element created by `$('.dropdown-button').dropdown()` is not destroyed. Everytime I call the view another ul element is added at the end of the document.

**Comment by Dogfalo** [comment]
They are now created as siblings.
