### ISSUE TITLE
Align navbar icons properly on mobile

### ISSUE THREAD

**Issue by digitalcraftsman** [Dogfalo/materialize#893]
I want to align a few icons inside the navbar on the right, if the content goes mobile (tablet and smartphone size). I tried to use the `right-align` helper class, but it does not seem to work properly.

You can find the code (here)[http://codepen.io/anon/pen/KwGmyd?editors=100]

**Comment by Dogfalo** [comment]
The correct class is `right`

**Comment by digitalcraftsman** [comment]
My fault. Thanks for the quick response and thanks for this awesome project. Keep going!
