### ISSUE TITLE
Adding larger navbars with integrated tabs

### ISSUE THREAD

**Issue by digitalcraftsman** [Dogfalo/materialize#894]
I would suggest to add support for larger navigations with different sizes like in Material, which also include tabs. You can find a demo from Project Polymer [here](https://www.polymer-project.org/0.5/components/paper-tabs/demo.html). Take a look at demo G.

**Comment by NitroBAY** [comment]
Yes

**Comment by acburst** [comment]
Added in 8be878359048e84c6494a3682d10a966766536b2
