### ISSUE TITLE
btn-floating not hiding uppon click mobile

### ISSUE THREAD

**Issue by cskiwi** [Dogfalo/materialize#898]
Hi,

I have a Fab and when hovering it reveals 2 other fab's but when I click on it on my tablet, the buttons stay visible (until you click somewhere else) I tried setting the focus somewhere else. but no luck.
This doesn't happen on Desktop.

Could someone give me a fix / suggestion for fixing this issue?

**Comment by Dogfalo** [comment]
touch devices have no :hover state, so this is why it is not working is you would expect.

**Comment by ryanbuiltthat** [comment]
@Dogfalo what do you think would be the best workaround for that? Adding a callback with a delay to hide the buttons a few hundred ms after firing?

**Comment by mazzie14** [comment]
Any ideas /updates about this??

**Comment by kampfkeks** [comment]
Yeah adding a callback after a few seconds to hide again the fabs is propably your best bet.

**Comment by cskiwi** [comment]
I added the following:

```javascript
        $(".sub-fab").click(function () {
            $(".fixed-action-btn").mouseleave();
            $(".tooltipped").mouseleave();
        });
```

**Comment by Dogfalo** [comment]
Duplicate of #963 which has a better name/description.
