### ISSUE TITLE
File field input is bigger than container

### ISSUE THREAD

**Issue by kmmbvnr** [Dogfalo/materialize#899]
![screenshot from 2015-03-12 18 07 10](https://cloud.githubusercontent.com/assets/282529/6617430/6dc23ba6-c8da-11e4-861b-ab41e9666627.png)

input have width: 100% and margin-left:100px This breaks some layouts.

What you think about fixing it, by using the same trick as for icon prefix "margin-left:100px; width; calc(100% - 100px)" ?

**Comment by Dogfalo** [comment]
What layouts does it break on?

**Comment by kmmbvnr** [comment]
![screenshot from 2015-03-13 11 43 14](https://cloud.githubusercontent.com/assets/282529/6633664/f010bd6a-c96d-11e4-8d68-10c470a0166b.png)

the border-bottom of file input is bigger, than other input fields.

**Comment by acburst** [comment]
fixed in 64c5a3b6d4bec356687dde53a69d2d4e11f073c2
