### ISSUE TITLE
Tab hash in url causing page jump

### ISSUE THREAD

**Issue by Dogfalo** [Dogfalo/materialize#90]

**Comment by Splintex** [comment]
It still working bad. Do you have any solution of this problem?

**Comment by ariedov** [comment]
Same for me in 2016

**Comment by smileytechguy** [comment]
Do you mean a "example.com/#" causing a jump?

**Comment by ariedov** [comment]
This is the page: https://github.com/getman-studio/devsite/blob/gh-pages/index.html

I am using tabs: 
`<div class="col s12 l12">
       <ul class="tabs z-depth-1">
	        <li class="tab col s2 l2"><a class="active" href="#sculpture">Скульптура</a></li>
		<li class="tab col s2 l2"><a href="#wpaint">Настінний розпис</a></li>
		<li class="tab col s2 l2"><a href="#painting">Живопис</a></li>
		<li class="tab col s2 l2"><a href="#molding">Декорації</a></li>
		<li class="tab col s2 l2"><a href="#graphics">Графіка</a></li>
		<li class="tab col s2 l2"><a href="#drawing">Арт</a></li>
	</ul>
</div>`

And the `drawing` one is causing the jump to top. When I remove it, or change the id to non-existent, all works ok.

**Comment by ariedov** [comment]
It happened because I was calling 
```
$(document).ready(function(){
    $('ul.tabs').tabs();
});
```

No issue now.

**Comment by smileytechguy** [comment]
That is due to the size of the content reducing.  The browser handles that

**Comment by smileytechguy** [comment]
Not much you can do, besides making a fixed height buffer inside #drawing (as in a div that is 600px or so tall).

**Comment by smileytechguy** [comment]
You could, also, preload the images.  They aren't loaded until shown, at least for me, so the page jumped.  Once I cached them, all was good.  Just a `<img src="image" width="1px" />` at the bottom (outside tabs) would do, or even using data: images

**Comment by ariedov** [comment]
Thank you very much!

**Comment by smileytechguy** [comment]
Did it work?

**Comment by ariedov** [comment]
Unfortunately haven't change to check it, I used js to fix the issue. Thanks!
