### ISSUE TITLE
Is it possible to use sidebar with top navbar ?

### ISSUE THREAD

**Issue by colus001** [Dogfalo/materialize#900]
Among the most common way of making admin panel, we have both sidebar and top navbar.
Top nav for user info, sidebar for practical use. But I couldn't find the best way to do this.
Sidebar is always hidden until I click the button. Am I just missing something here? 

![screen shot 2015-03-12 at 10 05 55 pm](https://cloud.githubusercontent.com/assets/2831540/6618203/3c152530-c904-11e4-9dda-adc7d18880c3.png)

**Comment by Torcado** [comment]
This type of sidebar you are talking about is being realized with the grid.

**Comment by Dogfalo** [comment]
See documentation for sidenav.
