### ISSUE TITLE
Icons tiny on Samsung webView

### ISSUE THREAD

**Issue by corbindavenport** [Dogfalo/materialize#905]
I recently released an app using the Materialize framework and one of my users reports the floating button has a small icon. The user is running Samsung's Android 4.4 ROM. This appears normally on stock Android webView (tested on 4.0+) and all other browsers, and I have been unable to find the problem.

This is the code:

```
<a class="btn-floating btn-large waves-effect waves-light modal-trigger theme" id="settings-trigger" href="#"><i class="mdi-action-settings"></i></a>
```

![screenshot_2015-03-13-09-09-10](https://cloud.githubusercontent.com/assets/3879063/6638939/28ba7fdc-c961-11e4-8e67-ff760b18bd2d.png)

**Comment by danielhickman** [comment]
Using HTML and this amazing framework to make Android Apps :+1:

**Comment by Dogfalo** [comment]
I will need browser information as well if I am to attempt to fix it.

**Comment by danielhickman** [comment]
webView is the built in Android viewer
https://play.google.com/store/apps/details?id=com.google.android.webview

**Comment by Dogfalo** [comment]
Right, but webview uses Chrome

**Comment by danielhickman** [comment]
Ah

**Comment by corbindavenport** [comment]
webView on anything earlier than Android 4.4 is based on WebKit, not Chrome. From version 4.4 onwards, it used an old build of Chrome, and 5.0+ use the latest version of Chrome.

**Comment by Dogfalo** [comment]
We can't help with fixing this because there is just not enough information provided here. And we were not able to reproduce it
