### ISSUE TITLE
ul.tabs javascript error

### ISSUE THREAD

**Issue by alioygur** [Dogfalo/materialize#907]
there is my tabs

    <div class="container">
        <div class="row">
            <div class="col s12">
                <ul class="tabs">
                    <li class="tab col s4"><a href="#!/tips/trending-up"><i class="mdi mdi-trending-up"></i> Trending Up</a></li>
                    <li class="tab col s4"><a href="#!/tips/most-recent"><i class="mdi mdi-clock"></i> Most Recent</a></li>
                    <li class="tab col s4"><a href="#!/tips/most-popular"><i class="mdi mdi-star"></i> Most Popular</a></li>
                </ul>
            </div>
        </div>
    </div>

but i am getting this error
    
    Uncaught Error: Syntax error, unrecognized expression: #!/tips/most-recent

**Comment by Dogfalo** [comment]
Your hrefs are not valid.

**Comment by alioygur** [comment]
@Dogfalo how can i make it valid ?

**Comment by Dogfalo** [comment]
Remove '!'

**Comment by alioygur** [comment]
i have tried it but still not working

**Comment by alioygur** [comment]
@Dogfalo 

     Uncaught Error: Syntax error, unrecognized expression: #/tips/trendingup

**Comment by alioygur** [comment]
i am using this url for ajax crawable 

[here](http://ajax.rswebanalytics.com/seo-for-ajax/#!ajax-crawling-scheme) is says use like this "#!"
