### ISSUE TITLE
side-nav fixed + navbar-fixed

### ISSUE THREAD

**Issue by goeroe** [Dogfalo/materialize#911]
Is there a way to combine the two without messing up one of them?

```<nav><ul id="slide-out" class="side-nav fixed"> ... </ul></nav>```

![side-nav_001](https://cloud.githubusercontent.com/assets/4172138/6644974/abc29da4-c9b8-11e4-977f-81406f857523.jpg)
![side-nav_002](https://cloud.githubusercontent.com/assets/4172138/6644975/abc2e7f0-c9b8-11e4-8f6d-d736d931be3d.jpg)

```<div class="navbar-fixed"><nav><ul id="slide-out" class="side-nav fixed"> .. </ul></nav></div>```

![side-nav_and_navbar-fixed_001](https://cloud.githubusercontent.com/assets/4172138/6644976/abc3f5d2-c9b8-11e4-9ba0-98cf5ab4ee98.jpg)

```<nav><ul id="slide-out" class="side-nav fixed"> ... </ul><nav>```
```<div class="navbar-fixed"><nav><ul> ... </ul></nav></div>```

![side-nav_and_navbar-fixed_seperate_001](https://cloud.githubusercontent.com/assets/4172138/6644977/abc48a24-c9b8-11e4-8ce7-af6008b1978c.jpg)
![side-nav_and_navbar-fixed_seperate_002](https://cloud.githubusercontent.com/assets/4172138/6644978/abc58636-c9b8-11e4-8d13-c0957f0fed31.jpg)

**Comment by Dogfalo** [comment]
Please use this [codepen] (http://codepen.io/Dogfalo/pen/xbzPQV) to illustrate your issue as I do not understand what is happening in these pictures.

**Comment by goeroe** [comment]
[Codepen | side-nav fixed + navbar-fixed](http://codepen.io/anon/pen/zxmXVv )

**Comment by Dogfalo** [comment]
See https://github.com/Dogfalo/materialize/issues/813
