### ISSUE TITLE
.scrollTo()/.filter() issue with .material_select()

### ISSUE THREAD

**Issue by Dallas62** [Dogfalo/materialize#912]
Hi,

Was investigating on a strange error with .material_select():
```
Uncaught TypeError: Cannot read property 'top' of undefined  
 a.fn.scrollTo                                                  materialize.js:2  
 a.ready.a.fn.material_select.a.each.activateOption             materialize.js:3
 (anonymous function)                                           materialize.js:3
 jQuery.event.dispatch                                            jquery.js:4430 
 jQuery.event.add.elemData.handle                                 jquery.js:4116 
```

The first one is that there is no check if the element exist at https://github.com/Dogfalo/materialize/blob/a6c4a6acd6e7774ff391afdfeb5f1c60b94a450d/js/dropdown.js#L6 ( Cannot read property 'top' of undefined )

The second one is in https://github.com/Dogfalo/materialize/blob/cd3b02d0661b9a78fbdddd81ad95eed632cb4c0c/js/forms.js#L288

Because the Exception appear ONLY if you do something like this (with new lines/spaces):

```
        <option ng-repeat="sample in samples" value="{{ sample.id }}">
                {{ sample.name }}
        </option>
```

The following syntax works well (without new lines/spaces):

```
        <option ng-repeat="sample in samples" value="{{ sample.id }}">{{ sample.name }}</option>
```

Thanks.

PS: The Exception is Throwing when you click on a <option> with new lines/spaces.

v0.95.3

**Comment by Dallas62** [comment]
http://jsfiddle.net/z4eo725e/

**Comment by fourpixels** [comment]
Yeah, it seems like a bad one :) Maybe submit pull request?
A good thing to do is cache the $(this) call, as it can be expensive.

**Comment by donwojtallo** [comment]
This one seems to be already fixed. Proof:
http://jsfiddle.net/z4eo725e/4/
I faced this problem today using Meteor package (Materialize v0.97.0)
