### ISSUE TITLE
<optgroup> breaks Materialize Select in forms

### ISSUE THREAD

**Issue by olivier67** [Dogfalo/materialize#914]
When I add optgroup to my option list in a select, the Materialize Select js does not work. It does work when using 'browser-default' class.

**Comment by dhawken** [comment]
Did you initilialize the select?

**Comment by olivier67** [comment]
yes, and I tested on codepen

**Comment by dhawken** [comment]
can you post it or a link?

**Comment by olivier67** [comment]
http://codepen.io/olivier67/pen/QwJLvX

or https://gist.github.com/olivier67/7a8ce0f1f65e93c96dcb

**Comment by dhawken** [comment]
Oh ya, i see it now. Thanks.  That happens in my app also.  Only elements specified outside the opt-group are rendered unless you use the browser-default class on the select.

**Comment by Dogfalo** [comment]
<optgroup> is not yet supported, for now I would either use the browser-default or use the dividers to divide groups as shown in the demo

**Comment by gmmarc** [comment]
+1 to this functionality ;)

**Comment by acburst** [comment]
Added in b2fe432
