### ISSUE TITLE
Modal not acting as real modal

### ISSUE THREAD

**Issue by algoj** [Dogfalo/materialize#920]
Modal component still allow other elements to be clicked/hovered/focused even if it is already open.

**Comment by dcworldwide** [comment]
Agree.. I don't think we should be about to scroll the parent window whilst a modal is open.

**Comment by rynam0** [comment]
+1

**Comment by Dogfalo** [comment]
Scrolling is now disabled 2c25e17037a45531bdca373d1702b646d6cb2b3c
