### ISSUE TITLE
Enhancement: Use These Material Design Icons

### ISSUE THREAD

**Issue by bobrocke** [Dogfalo/materialize#921]
There is a project that you probably already know about creating a larger set if material design icons: http://materialdesignicons.com

Perhaps it would be worthwhile to include that evolving set in MaterialCSS?

**Comment by dhawken** [comment]
Aren't the md icons already included?

**Comment by bobrocke** [comment]
Many are. But that project is constantly adding more community contributed icons for a consistent style as so has many more choices already, and growing.

**Comment by dhawken** [comment]
I think i see what you mean now - the mdi icons were included in the dist at a recent release I believe. They used to be separate - i think there's a separate issue #423 that would bring them back out.

**Comment by lukaspijak** [comment]
:+1:

**Comment by Dogfalo** [comment]
We just want to stick with the official set.

**Comment by carloscarcamo** [comment]
:+1:

**Comment by ritdaw** [comment]
Such a shame, the official set is not broad enough.
