### ISSUE TITLE
improvement : better custom selectYears in pickadate

### ISSUE THREAD

**Issue by olivier67** [Dogfalo/materialize#926]
Currently, the variable selectYears permits to delimit the number of years in the select menu, with current year being the center of the span -- i.e. if selectYears is set to 10, and we're in 2015, the select menu will show years from 2005 to 2025.
In most cases, this is not useful. For example, in the case of date of birth, you'd need to set selectYears to a high value like 180 in order to accommodate ages up to 90 years old, while have a looooong select list up to year 2105...
Wouldn't it be better to use 2 variables : selectYearStart and selectYearEnd ?

**Comment by Dogfalo** [comment]
Please see http://amsul.ca/pickadate.js/date/
