### ISSUE TITLE
Enhacement: Slider

### ISSUE THREAD

**Issue by torreslucas13** [Dogfalo/materialize#927]
Good Night,

A feature to sliders could be added . Something as simple as the [Unslider](http://unslider.com/ "Unslider"). Just add the images and start the plugin. However , congratulations for the project. It's all very easy and useful.

**Comment by Dogfalo** [comment]
What is the enhancement?

**Comment by torreslucas13** [comment]
Sorry, enhancement***

**Comment by Dogfalo** [comment]
No I mean, I don't understand what enhancement you are suggesting.

**Comment by torreslucas13** [comment]
I just suggested a feature like the one above .

**Comment by Dogfalo** [comment]
We have a slider already.
