### ISSUE TITLE
Footer buttons in modal dialogs have no horizontal margin

### ISSUE THREAD

**Issue by ciencia** [Dogfalo/materialize#929]
Screenshot from the current http://materializecss.com/modals.html page, changing css class from btn-flat to btn to display buttons with background:
![modalbuttons](https://cloud.githubusercontent.com/assets/44133/6662799/12c9d360-cbc0-11e4-8eec-3cb1ffceb087.png)

Maybe the design pattern recommend to use flat buttons inside dialogs, where the issue is not visible (because you don't see in flat buttons where are their bounds), but if we use normal buttons they appear too close with each other

**Comment by kmmbvnr** [comment]
Seems fixed.
![modals materialize](https://cloud.githubusercontent.com/assets/282529/20557214/cf1fe840-b194-11e6-8b6a-92c7c22a88e1.png)

**Comment by ciencia** [comment]
@kmmbvnr No, it isn't. Please read description and not only look at the image.

**Comment by kmmbvnr** [comment]
Ups, but actually the Design guidelines uses only flat buttons in the dialogs - https://material.google.com/components/dialogs.html#dialogs-specs

So I think that incorrect usage of buttons inside modals should not be fixed.

**Comment by tomscholz** [comment]
As @kmmbvnr says. It's incorrect usage
