### ISSUE TITLE
Fonts seem to have a problem on desktop browser

### ISSUE THREAD

**Issue by nmstoker** [Dogfalo/materialize#93]
Good work bringing this all together!

Roboto is a lovely font, but something about your example pages seems to cause them to look terrible on my desktop browser - lumpy and not crisp at all. Am not getting this effect with other similar sites (and I have an internal one using Roboto w/o issue)

Have you perhaps only got small versions of the underlying font files?

The effect is present on my desktop browser (Chrome) and seems to apply to all sizes from the smallest to the larger headlines.  I can't see the browser complaining of not being able to load any font files (which seemed a potential cause).  It seems okay on mobile.

I've included a screenshot below (but you need to expand it to see the effect; the mini version is smoothed in a way that doesn't reflect how it really looks)

![image](https://cloud.githubusercontent.com/assets/3694484/5032057/e17486de-6b52-11e4-8901-48d958368eba.png)

**Comment by kmmbvnr** [comment]
I have to add some js/css to switch to older roboto font version. It's still better than ugly rendering

      if (navigator.appVersion.indexOf("Win")!=-1) {
           document.write('<link rel="stylesheet" type="text/css" href="robotofix.css">');
      }


robotofix.css

    @font-face {
        font-family: 'Roboto';
        font-style: normal;
        font-weight: 300;
        src: url(http://themes.googleusercontent.com/static/fonts/roboto/v10/Hgo13k-tfSpn0qi1SFdUfT8E0i7KZn-EPnyo3HZu7kw.woff) format('woff');
    }

    @font-face {
        font-family: 'Roboto';
        font-style: normal;
        font-weight: 400;
        src: url(http://themes.googleusercontent.com/static/fonts/roboto/v10/2UX7WLTfW3W8TclTUvlFyQ.woff) format('woff');
    }

    @font-face {
        font-family: 'Roboto';
        font-style: normal;
        font-weight: 500;
        src:   url(http://themes.googleusercontent.com/static/fonts/roboto/v10/RxZJdnzeo3R5zSexge8UUT8E0i7KZn-EPnyo3HZu7kw.woff) format('woff');
    }

    @font-face {
        font-family: 'Roboto';
        font-style: normal;
        font-weight: 700;
        src: url(http://themes.googleusercontent.com/static/fonts/roboto/v10/d-6IYplOFocCacKzxwXSOD8E0i7KZn-EPnyo3HZu7kw.woff) format('woff');
    }
