### ISSUE TITLE
Badge in dropdown not aligned with text on Firefox

### ISSUE THREAD

**Issue by Krazitchek** [Dogfalo/materialize#930]
Badges in dropdown are not aligned with text on Firefox (tested on 36, 37).
Seems to be ok on Chrome.
See screenshot please.
![badges](https://cloud.githubusercontent.com/assets/11500208/6664519/b7ee924e-cbd0-11e4-83dd-9c377c1d346b.png)

**Comment by Dogfalo** [comment]
I tested this in firefox and did not see the issue. Maybe someone else can confirm this?

**Comment by carlosperate** [comment]
I'm having the same issue in Firefox 36.0.4 on Win8.1

**Comment by acburst** [comment]
Fixed in f8b55f4f893065f0c4453b0d77c8b1dc632663ec

**Comment by ryanswapp** [comment]
I am having the same issue in firefox but not in chrome.

![screen shot 2015-07-07 at 8 49 26 am](https://cloud.githubusercontent.com/assets/4509676/8548967/53ff788a-2485-11e5-9823-bb122e1b952a.png)
![screen shot 2015-07-07 at 8 50 17 am](https://cloud.githubusercontent.com/assets/4509676/8548971/57f2967a-2485-11e5-97e0-7020202dbfd4.png)
