### ISSUE TITLE
Slider: missing image (gif) after initialization

### ISSUE THREAD

**Issue by jvv** [Dogfalo/materialize#933]
I am working with the slider, and am coming a long way. The problem I face is that, after the code replaces the src value to a background image (CSS) - I get a missing picture (as the SRC attribute is empty). When I check the examples on materializecss - I notice that a 1x1 transparent gif is being added to the HTML code. 

    src="data:image/gif;base64,R0lGODlhAQABAIABAP///wAAACH5BAEKAAEALAAAAAABAAEAAAICTAEAOw=="

I don't get this in my code. Is this something that has been recently added? I can't seem to find any record of this in slider.js code.

**Comment by jvv** [comment]
I solved it btw using a simple spacer.png file, calling the following after the slider has been initalized. However - this should not be needed.

    $('.slider img').attr('src','/img/spacer.png');

**Comment by Dogfalo** [comment]
You're likely on an old build. This was added recently
