### ISSUE TITLE
floating buttons can be clicked in mobile while are hidded

### ISSUE THREAD

**Issue by Lloople** [Dogfalo/materialize#939]
When I'm on mobile and I click in the area I think my button will be, it makes the action anyway. I'm clicking an invisible button. This is a problem for me because I have big buttons in a mobile screen so the users can tap in that place without knowing this just for targeting a input or something.

**Comment by ryanbuiltthat** [comment]
I'm just getting started with this package but came across this....if you inspect the button do you see `display:none`? or just `visibility:hidden` ?

**Comment by Lloople** [comment]
I see opacity 0, I already inspect the js code to see the behavior, but
can't imagine how to solve it.

**Comment by ryanbuiltthat** [comment]
It seems like that would be a bug then in the css no? Traditionally aren't
hidden elements styled with `display:none;visibility:hidden;` ?

Can you add a style after all the stylesheets with those attributes to see
if that accomplishes what you're looking for? Seems like just hiding the
button with the opacity isn't really "hiding" it in the traditional sense.

Again, apologies to anyone if I'm way off base but I'm just now getting
around to using this as a complete package and thus far has just
cannibalized it to fit my need.

**Comment by Lloople** [comment]
I solved the problem adding a `.css("display", "none");` in the `mouseleave` event and a `.css("display", "block");` when `mouseenter`, concatenated to the `.velocity()`methods. I need to do more testing about this but seems it works as I need.

**Comment by gmmarc** [comment]
Hi,

I can confirm this too. I think the problem is that the ```<ul>``` containing the other buttons is visible and inside ```.fixed-action-btn```, so ```mouseenter``` is fired.

I've managed to solve it without modifying core.

Add to your css:
```css
.fixed-action-btn ul {
	display: none;
}
```
Add to your javascript:
```javascript
$(document).ready(function(){
    $(document).on('mouseenter.fixedActionBtn', '.fixed-action-btn', function(e) {
      var $this = $(this);

      $this.find('ul').velocity("stop", true);
      $this.find('ul').velocity(
        { opacity: "1"},
        { duration: 0, display: "block" });
    });

    $(document).on('mouseleave.fixedActionBtn', '.fixed-action-btn', function(e) {
      var $this = $(this);

      $this.find('ul').velocity(
        { opacity: "0"},
        { duration: 80, delay: 240, display: "none" });
        // Note: a delay is needed, otherwise buttons disappear abruptly (don't really know why...)
    });
});
```

**Comment by Dogfalo** [comment]
This is now the default behavior since d2deb3bb8353a4be201da835e39d533fce896dc1
