### ISSUE TITLE
Dropdown closing is not looking aligned with material design priciple

### ISSUE THREAD

**Issue by rohith-m** [Dogfalo/materialize#942]
Drop down componenet is good, when I open it up isee dropd down animation, but when closing it is just fade out, shouldnt that be like going up and fading to have consistant animation style.

**Comment by acburst** [comment]
http://www.google.com/design/spec/components/menus.html#menus-usage

In material design, the in animation is more important, but the out animation should be quicker because the users focus is already leaving for something else.

The fade out is perfectly in line with material design
