### ISSUE TITLE
Dropdown - changing number of items in list

### ISSUE THREAD

**Issue by solgarius** [Dogfalo/materialize#946]
Hi, I've noticed that if the number of items in the list for a dropdown changes, the height is not recalculated when opening/closing the dropdown. It appears to be because 'dropdownRealHeight' is only set when the dropdown is first initialized.

So say you have 3 list items initially, then later that list changes to 2, if you then open the dropdown it will appear with space for 3 and won't have resized to be just the 2 items. The same problem happens in reverse, and a scrollbar is added for the extra item. 

Workaround obviously is to recreate the dropdown every time the list changes, however this feels a little bit hacky and prone to unnecessary GC and possible memory leaks (considering the dropdown is keeping references to DOM elements).

**Comment by dcworldwide** [comment]
I also have this issue. I use materialize with meteor to bind a data model to the dropdown. The dropdown doesn't resize its content on data model change.

**Comment by fega** [comment]
Hello, I tested it and it works fine, please re-open if you are still having troubles
