### ISSUE TITLE
Calendar picker is aligned right on IE 10+

### ISSUE THREAD

**Issue by ad-mca-mk** [Dogfalo/materialize#948]

**Comment by ciencia** [comment]
works for me, although the calendar is aligned to the left side of the screen instead of centered

**Comment by carlosperate** [comment]
I can confirm that in my setup (win8 IE11) it also works, but it is aligned
to the left as well.

**Comment by ad-mca-mk** [comment]
I meant to write that it's not aligned properly...
My mistake, sorry about that.

**Comment by Dogfalo** [comment]
We've fixed this in a recent commit
