### ISSUE TITLE
Improve internal SCSS structure

### ISSUE THREAD

**Issue by brandonjmckay** [Dogfalo/materialize#949]
I was looking through the folder structure, and I found it difficult to locate some of the modules I was trying to edit.

I was thinking maybe splitting up some of the bigger files into a more obvious folder structure would help newcomers to the codebase.

I was thinking things like `.hide-on-small-only` which now lives in `sass/components/global`, would be better in `sass/globals/_media-queries.scss`.

@Dogfalo what do you think?

**Comment by brandonjmckay** [comment]
I could make these changes, and submit a PR if you like the idea.

**Comment by Dogfalo** [comment]
We've since separated out forms.scss which was a very large file before into several components. For now we will still use global to hold CSS that holds things that span multiple components. We may change this in the future if the size grows much further.
