### ISSUE TITLE
sideNav click handler is preventing other (delegated) events

### ISSUE THREAD

**Issue by fegemo** [Dogfalo/materialize#950]
The click event of the toggler button of the sideNav plugin has a `return false`, which `preventDefault()` and `stopPropagation` at the same time. 

But the `stopPropagation()` (implicitly) there makes other delegated events on the same toggler element not to trigger, which prevents people to have event delegation AND sideNav happening on the same element.

A simple example showing the behavior: http://codepen.io/fegemo/pen/ByGgvj/
## To reproduce the issue on that example

Use a small screen width (about 600px) so the hamburguer menu icon appears at the left.
Then click the icon.

Two things should happen:
1. The side nav should open
1. An alert should appear

However, the alert is not being shown.
## A possible fix

I believe that just by changing the `return false;` in https://github.com/Dogfalo/materialize/blob/master/js/sideNav.js#L310 to `e.preventDefault();` should fix it.

**Comment by davidabsilva** [comment]
Well, I guess is a bit late but I was cruising around and found your pen and fixed it. 

http://codepen.io/anon/pen/MKvbpo
