### ISSUE TITLE
Badge effect without "new"

### ISSUE THREAD

**Issue by ask007java** [Dogfalo/materialize#952]
How to have a badge effect without appending new to the badge ?
![image](https://cloud.githubusercontent.com/assets/6759476/6715156/b4fa3732-cd6a-11e4-8274-f997798d419a.png)

**Comment by TheRinseM** [comment]
Remove the "new" text.

**Comment by ask007java** [comment]
Do you mean remove new from the class name ?

The class used to get the teal box badge effect is "new badge" but if I remove new and use only "badge" then I won't get the teal box badge effect.

How to get the teal box badge effect without appending new ?

**Comment by ask007java** [comment]
Its very easy I figure it out. Thanks

**Comment by andela-celisha-wigwe** [comment]
Hi. I just came across this. How did you figure it out. I am a bit new to Materialize CSS. @ask007java

**Comment by TheRinseM** [comment]
There should be an element with "New" text in your html. remove it.

**Comment by alexanderathomas** [comment]
its pretty easy, just remove the following script from materialize css file

**span.badge.new:after{content:" new"}**

**Comment by Blitzlord** [comment]
# Official Solution:
To remove the "new" text, use the **data-badge-caption** Attribute.
Either set an empty String inside `data-badge-caption=""`.
Or use it for your text
`<span class="new badge red" data-badge-caption="MY TEXT GOES HERE"></span>`

**Comment by VickG** [comment]
I am getting more and more tired of working with materialize design with these illogical implementations
