### ISSUE TITLE
Donation

### ISSUE THREAD

**Issue by nahtnam** [Dogfalo/materialize#954]
I know its not much @Dogfalo but $1 is better than nothing, isnt it @changetip?

**Comment by nahtnam** [comment]
Lol, it didnt work.

@Dogfalo $1 @changetip

**Comment by changetip** [comment]
Hi @dogfalo, @nahtnam sent you a Bitcoin tip worth 3,921 bits ($1.00), and I'm here to deliver it ➔ **[collect your tip](https://www.changetip.com/collect/648895)**.


**[Learn more about ChangeTip](https://www.changetip.com/tip-online/github)**

**Comment by Dogfalo** [comment]
Wow, ChageTip seems cool. Thanks for the donation!

**Comment by nahtnam** [comment]
Np. Enjoy.

P.S. Ill donate more sometime soon.
