### ISSUE TITLE
screensize for responsive tables

### ISSUE THREAD

**Issue by philipraets** [Dogfalo/materialize#956]
Great framework and the responsive tables are great, but it would be great to have a small-responsive and a med-responsive class.

Use case:
if a table is small enough for medium screens but too large for small screens.

**Comment by thecotne** [comment]
to keep it simple it will be nice to have bootstrap like grid
xs sm md lg 
http://getbootstrap.com/css/#grid-options

**Comment by Dogfalo** [comment]
Duplicate of #644

**Comment by Amonstyle** [comment]
@thecotne i fixed like bootstrap with large size > 1200px
Demo http://jsfiddle.net/mxzuuknz/1/
