### ISSUE TITLE
Switched don't change checkbox value

### ISSUE THREAD

**Issue by taromero** [Dogfalo/materialize#961]
When you click on a switch it changes its visual state (yo see the circle moving), but it doesn't change the related checkbox value (it's always on).

I had to add custom event listeners to manually change the value of the input.

Reproduction case: Go to materialize forms sections, click on a switch and see how the checkbox value is alwats "on".

**Comment by Dogfalo** [comment]
The switch does change the checkbox state, the transition itself relies on `:checked`. Just use `.prop('checked')` to get a value

**Comment by taromero** [comment]
Thanks! It's worth documenting that though.

**Comment by Dogfalo** [comment]
This is how all checkboxes work. Not specific to materialize

**Comment by taromero** [comment]
Ohh silly me, sorry for the inconvenience.
