### ISSUE TITLE
materialize website

### ISSUE THREAD

**Issue by ganySA** [Dogfalo/materialize#966]
Recently when going to the website i have the following error , i believe its something to do with the location of the jquery loading. 

Failed to load resource: net::ERR_TOO_MANY_REDIRECTS
http://materializecss.com/bin/jquery-2.1.1.min.js Failed to load resource: the server responded with a status of 404 (Not Found)

I would think google CDN would be good for this.

**Comment by Dogfalo** [comment]
This should only happen if you are not connected to the internet.
