### ISSUE TITLE
input within a modal

### ISSUE THREAD

**Issue by ganySA** [Dogfalo/materialize#967]
When you place an input-field on a modal. Clicking on the input becomes very difficult because for some or other reason when clicking on the label it doesn't select the underlying text box. 

you have to click on the text box where the label doesnt overlap it.

    <div id="modal1" class="modal">
		<div class="modal-content">
			<h4>Select your region</h4>
			<div class="row">
				<div class="col-sm-10 offset-s1 input-field">
					<input placeholder="" id="autocomplete" style="text-align:center" type="text" class="form-control">
					<label style="text-align: center; width: 100%;" for="searchquery">Enter your city name</label>
				</div>
			
			</div>
			
		</div>
		<div class="modal-footer">
			<a href="#" class="waves-effect waves-green btn-flat modal-action modal-close">Agree</a>
		</div>
	</div>

I fixed it by adding:
pointer-events: none to the label, 
however i am not sure how browser friendly this is!

**Comment by Dogfalo** [comment]
This is probably either due to the fact that you have `col-sm-10` which isn't a class, or one of your own styles, because I was unable to recreate the problem in the codepen on the README. If you can recreate it for us, I can reopen this issue.

**Comment by ganySA** [comment]
Hi

The solution to this was a copy and paste error. What is not explicit in the documentation is that for on the label must match the id of the input. In the above it doesnt hence it doesnt work.

Cheers
