### ISSUE TITLE
meteor: tooltipped 

### ISSUE THREAD

**Issue by ganySA** [Dogfalo/materialize#968]
Tooltips dont seem to fire in meteor automatically? I have tried using 

$('.tooltipped').tooltip({ delay: 50 }); 

in template.rendered event however this does nothing. 

If i type $('.tooltipped').tooltip({ delay: 50 }); in the console window, the tooltip fires.

Any ideas?

**Comment by Blahah** [comment]
@ganySA how did you get them to fire in rendered? I've got this in my `.onRendered()`:

```js
  $(this.firstNode).find('.tooltipped').tooltip({
    delay: 0,
    position: 'bottom'
  });
```

The selector works, but the tooltips are not initialized.

**Comment by FreefallGeek** [comment]
I would also like to know how you were able to get them to fire ganySA. I'm having the same issues as Blahah.

**Comment by Blahah** [comment]
@FreefallGeek I managed to get it working. I have the following (non-essential stuff removed)...

```html
<template name="taskList">
  {{#each tasks}}
    {{> taskPopout}}
  {{/each}}
</template>
<template name="taskPopout">
  <i class="material-icons tooltipped" data-tooltip="toggle edit mode">edit</i>
</template>
```

and on the client...
```js
Template.taskPopout.onRendered(function() {
  // initialise tooltips
  $('.tooltipped').tooltip({
    delay: 0
  });
});
```

and in my css (because at one point tooltips were hiding under things)...
```css
.material-tooltip {
  z-index: 1501;
}
```

**Comment by FreefallGeek** [comment]
Weird. I still cannot get it to work. In my client/a.html file I have...
```
<head>
    <title>TEST</title>
</head>
<body class="white darken-4">
    <div class="container">
        {{>mainContent}}
    </div>
</body>

<template name="mainContent">
    <div class="row" style="padding-top: 40px">
        <div class="col s6 offset-s3">
            <a class="btn tooltipped center" data-position="bottom" data-delay="50" data-tooltip="test test">TEST</a>
        </div>
    </div>
</template>
```

And in my client/a.js file I have
```
Template.mainContent.onRendered(
    function() {
        $('.tooltipped').tooltip({delay: 0});
    }
);
```

And I don't get anything. If I put a test alert() in my Template.mainContent.onRendered() it fires, so I know we're getting there, its just not rendering the tooltip().

**Comment by FreefallGeek** [comment]
Figured it out. I had linto:jquery-ui package installed and it was conflicting. Removed packaged and it started working.

**Comment by Digital-Thor** [comment]
None of the above worked for my code.  However, delaying initialization in the rendered function solved the problem:

```
  setTimeout(function(){
    $('.tooltipped').tooltip({ delay: 50 });
  }, 500 );
```

A more robust solution is probably to incorporate a session reactive var.  I haven't tried it, but you could look at [this link](http://stackoverflow.com/a/15315864/1406028) for such an approach.
