### ISSUE TITLE
Modal with fixed footer has a fixed height of 70%

### ISSUE THREAD

**Issue by jaimevent** [Dogfalo/materialize#971]
It would be better if the modal would calculate dynamically the height. Otherwise in the case you just have less content you'll see a huge nearly empty modal.

**Comment by Dogfalo** [comment]
It doesn't work work percentages

**Comment by jaimevent** [comment]
Sorry, I can't understand your answer. Do I have to change something to make it work?

**Comment by Dogfalo** [comment]
This type of modal cannot have a variable height such as a percentage.

**Comment by BaurainO** [comment]
Can we put a width or height in px or em ? If yes, how to do it ?
