### ISSUE TITLE
side-nav 

### ISSUE THREAD

**Issue by jssuzanne** [Dogfalo/materialize#972]

**Comment by jssuzanne** [comment]
See the example https://github.com/Dogfalo/materialize/wiki/SideNav. 

and the navbar:
     <header>
         <nav>
             <div class="nav-wrapper">
                 <ul class="right">
                     <li><a>First menu</a></li>
                     <li><a>Second menu</a></li>
                 </ul>
             </div>
         </nav>
     </header>

**Comment by jssuzanne** [comment]
I doesn't reproduce it on codepen.io

**Comment by Dogfalo** [comment]
If it doesn't reproduce then it is something in your code. It would also be helpful if the title of your issue stated what the problem was.

**Comment by jssuzanne** [comment]
I reproduce it at http://codepen.io/Dogfalo/pen/xbzPQV
