### ISSUE TITLE
card-image + material box

### ISSUE THREAD

**Issue by zion822** [Dogfalo/materialize#973]
I would like to use the card-image and material box combined.
![card-image](https://cloud.githubusercontent.com/assets/5521002/6770876/7f3f3d4c-d0ce-11e4-9fc6-6c3692fad0ad.PNG)
After clicking the image this is the result:
![material-box](https://cloud.githubusercontent.com/assets/5521002/6770877/7f6323ba-d0ce-11e4-8485-ab843eaa5220.PNG)

Is it "fixable", or is it not possible to use both of them together?

**Comment by Dogfalo** [comment]
See #825
