### ISSUE TITLE
contributing

### ISSUE THREAD

**Issue by throrin19** [Dogfalo/materialize#979]
Hello,
After see your material bootstrap, i've been excited by your work.
I've start to create this bootstrap too but i've not the time to finish it. I've create others material components (slider, checkbox, radio, ...) and I would be very grateful if you can get them (wherever possible) to your bootstrap.

This is some examples : 

Tabs : 

![20140923-100607_capture](https://cloud.githubusercontent.com/assets/1394778/6776136/1bd5d492-d13b-11e4-8024-b3f393ededee.gif)

Sliders : 

![selector_slider](https://cloud.githubusercontent.com/assets/1394778/6776140/2981d9ce-d13b-11e4-9505-59232e50d3ef.gif)

This is my repository url : https://github.com/throrin19/materialBootstrap

**Comment by digitalcraftsman** [comment]
I would appreciate such features in this framework, especially the scolling tabs for smaller screens.

**Comment by throrin19** [comment]
it's ie9+ ready ;)

**Comment by Dogfalo** [comment]
We aren't a material bootstrap.
