### ISSUE TITLE
Provide the ability to trigger a materialbox'd image modal manually.

### ISSUE THREAD

**Issue by MichaelOber** [Dogfalo/materialize#980]
Right now, it's only possible to have a meterialbox'd image expand when clicked on. I think it would be nice to provide the ability to trigger the expand manually.

For example, instead of clicking the image to expand it, the user would click a nearby icon or button.

The use case for this would be if the image is a link, or if the image already has another event attached to it, but you still want the user to be able to expand the image.

**Comment by fourpixels** [comment]
I already posted question about modular packages here: https://github.com/Dogfalo/materialize/issues/915

No comments at all. Currently I'm struggling with forms, because they are initialized only once, so if I fill the input with value after that initialization - nothing happens....

**Comment by Dogfalo** [comment]
You can have the link trigger a click on the image.

**Comment by MichaelOber** [comment]
Simply initiating a click on the image will cause other side effects.

Like I said in my original comment, if the image already has an event handler on it or if the image is a link to another page, having the image expand on a click isn't an option.
