### ISSUE TITLE
Float button with different z-index by default

### ISSUE THREAD

**Issue by digitalcraftsman** [Dogfalo/materialize#981]
I combined a modal and a floating button for my current project. Is it intended, that the floating button as 'main button' is intended to be visible, even if a modal was opened and the other content is hidden by a semi transparent layer?

Here is a screenshot of my project: 
![](http://picpaste.com/pics/aDELOMlq.1427137971.PNG) 

And here an example of the google inbox app for android:
![](https://cms-images.idgesg.net/images/article/2014/10/inbox-google-bundles-100526378-large.idge.jpg)

**Comment by acburst** [comment]
Can you post a code example

**Comment by Dogfalo** [comment]
Fixed in 125a91583d8130a9e88a4c1c7ca22111dc969345
