### ISSUE TITLE
3 Problems ?

### ISSUE THREAD

**Issue by BaurainO** [Dogfalo/materialize#984]
Hi everyone,
i have three problems :/
check this video : https://www.youtube.com/watch?v=U2w2M7z9HgM&feature=youtu.be
- When i open my modal, the active tab doesn't have the indicator
- when i clic on the forms there is a problem
- And sometimes i have a background nav who appear, i know it's a nav background and i know who to change the color, but just why it appear like that.

Thx

Here my modal (or you can check my repository : https://github.com/BaurainO/merterialize_Website) : 

      <div id="modal1" class="modal white">
        <div class="modal-content">
          <div class="row">
            <div class="col s12">
              <ul class="tabs">
                <li class="tab col s3"><a class="active blue-text text-darken-2" href="#test1">Connexion</a></li>
                <li class="tab col s3"><a class="blue-text text-darken-2" href="#test2">Inscription</a></li>
              </ul>
            </div>
              <div id="test1" class="col s12 grey-text text-darken-3">
                <div class="col s10 offset-s2 input-field">
                          <input id="last_name" type="text" class="validate">
                          <label for="last_name">Last Name</label>
                </div>
              </div>
              <div id="test2" class="col s12 grey-text text-darken-3">
                
              </div>
          </div>
        </div>

        <div class="modal-footer">
          <a href="#" class="waves-effect waves-green btn-flat modal-action modal-close">Agree</a>
        </div>
      </div>

**Comment by Techworker** [comment]
Had the same issue with the tabs and resolved it by  activating the tab in the ready callback of the modal.

```
$('.modal-trigger').leanModal({
    ready: function() {
        $('.modal-tabs).tabs('select_tab', 'your-tab');
    }
});
```

(written from mobile..)

**Comment by BaurainO** [comment]
OK ! thx <3

**Comment by BaurainO** [comment]
<3
