### ISSUE TITLE
The internals of class="modal" are not removed on closeModal()

### ISSUE THREAD

**Issue by osleg** [Dogfalo/materialize#985]
Reproduction:
Taking code from documentation
```
    <div id="modal1" class="modal">
        <div class="modal-content">
            <h4>Modal Header</h4>
            <p>A bunch of text</p>
        </div>
        <div class="modal-footer">
            <a href="#" class="waves-effect waves-green btn-flat modal-action modal-close">Agree</a>
        </div>
    </div>
```

opening modal by js
```
var mId = '#modal1'
// open modal
$(mId).openModal({dismissable: false});
// wait for something here
setTimeout(function(){}, 3000);
// close modal
$(mId).closeModal();
```
Expected behaviour:
After some delay modal should be complitely close including the content

What does happen now:
Modal background disapearing though content stay on screen and even more, it ignores click and does not respond at all

**Comment by Dogfalo** [comment]
This does not reproduce on the documentation page

**Comment by osleg** [comment]
https://gist.github.com/osleg/b715082fad240f386f4f
Here is complete code I'm using,
the /get_gif path returning json with `{'success': true, 'file': 'filename.gif'}`
on `openModal({dismissible: true);`
http://storage4.static.itmages.ru/i/15/0324/h_1427166001_1357066_df8b8c1d47.png
On `closeModal();` this is what happening
http://storage1.static.itmages.ru/i/15/0324/h_1427166018_8476242_0ea445cb17.png

**Comment by osleg** [comment]
Not a bug, my mistake wasn't passing modal ID to function on setTimeout()
