### ISSUE TITLE
select box not inline in other fields

### ISSUE THREAD

**Issue by nicopenaredondo** [Dogfalo/materialize#986]
![test](https://cloud.githubusercontent.com/assets/3615451/6796733/4a86c988-d233-11e4-81a2-32e49d486696.JPG)

I've copied the code in the documentation and it always show like this. Is there any fix on this or related issue ?

**Comment by nicopenaredondo** [comment]
````html
<div class="row">
  <div class="input-field col m3 s12">
    <input id="city" type="text" class="validate">
    <label for="city">City</label>
  </div>
  <div class="input-field col m3 s12">
    <input id="state" type="text" class="validate">
    <label for="state">State</label>
  </div>
  <div class="input-field col m3 s12">
    <input id="zip_code" type="text" class="validate">
    <label for="zip_code">Zip Code</label>
  </div>
  <div class="input-field col m3 s12">
    <label>Materialize Select</label>
    <select>
      <option value="" disabled selected>Choose your country</option>
      <option value="1">Country # 1</option>
      <option value="1">Country # 1</option>
      <option value="1">Country # 1</option>
      <option value="1">Country # 1</option>
    </select>
  </div>
</div>
````

**Comment by beriahthebee** [comment]
Its because there is a conflict between what a select replacement is doing and the use of the .input-field class on the div containing the replacement. The CSS doesn't know how to properly handle the label.

I have provided some SASS that will line them up correctly for you, but you need to replace the .input-field on the div with the select with .select-field.

```sass
.select-field {
	@extend .input-field;

	label {
		@extend label.active;
	}

	.select-wrapper {
		margin-top: 0;
	}
}
```

**Comment by acburst** [comment]
We meant for alignment with selects to be without labels. If you remove the label, everything should align. If you want labels as well you need to have some custom styles
