### ISSUE TITLE
 'btn-floating' is higher than other?

### ISSUE THREAD

**Issue by mylastof** [Dogfalo/materialize#988]
I want to create a group button between <code>.btn</code> and <code>.btn-floating</code>, but there which made no equal with regular <code>.btn</code>.
![floatmat](https://cloud.githubusercontent.com/assets/2387514/6801044/f4a1cf62-d256-11e4-9cf4-86d18d2a4a77.png)

I don't know how to fixed it.

**Comment by Dogfalo** [comment]
fixed in ae5d79b1a485ac395f569f531c22b1983c5c579a
