### ISSUE TITLE
Typography strong is not really strong.

### ISSUE THREAD

**Issue by fourpixels** [Dogfalo/materialize#990]
Don't know if this is a bug or not, but I found this in the code:

```css
strong { font-weight: 500; }
```
Why?

**Comment by Dogfalo** [comment]
The design spec says not to use 700 font-weight as it is too heavy to be easily readable.

**Comment by fourpixels** [comment]
This is only true for tall, and it's said that it's 'recommended' (again for tall). From specs (http://www.google.com/design/spec/style/typography.html#typography-standard-styles):

```Tall: Language scripts that require extra line height to accommodate larger glyphs. Includes South and Southeast Asian and Middle-Eastern languages, like Arabic, Hindi, Telugu, Thai, Vietnamese.```

```
Tall:
Weight: Use Regular weight, as Medium weight is unavailable in Noto. In addition, Google recommends avoiding Bold weight, based on feedback from native speakers that Bold is too heavy.
```
