### ISSUE TITLE
toast - wrap in global object?

### ISSUE THREAD

**Issue by ganySA** [Dogfalo/materialize#991]
Hi

I have not been able to access toast in meteor js, i think its because of the closures that meteor uses.
I got around this by including a global object wrapper:

Toast = (function(){
     var toaster = {};

      toast.[[materialize js]
   

     return toaster;
}())

Not sure if anyone else any other workarounds.

**Comment by Dogfalo** [comment]
Already fixed for next release

**Comment by snorlaxPokemon** [comment]
awesome. I was having the same issue
