### ISSUE TITLE
Scrollable list of checkboxes scrolls on click

### ISSUE THREAD

**Issue by korolyovvalentin** [Dogfalo/materialize#992]
Hi!
After some experiments with materialize we figured out, that scrollable div with list of checkboxes behaves strange. After click one of checkboxes div will scroll down.
Here's fiddle: jsfiddle.net/ak0on6kL/

Steps to reproduce:
1) Scroll div couple times;
2) Click any visible checkbox.

Thanks!

**Comment by Dogfalo** [comment]
The fix is to add visibility: hidden on these elements. For now it would be easier for you to add position: relative to the parent container.
Fixed in b96f7d5ea9dcd937a39f614561e99f564e1c9409

**Comment by korolyovvalentin** [comment]
Thank you very much for quick response!

**Comment by alejodev76** [comment]
Hi,

I am experiencing the same error and according to the issue it was fixed on v 0.98 and that's the version I am using but it does not seem to have this fix for either the radio nor the checkbox css. 

Would you accept a PR to get the fix in? Unfortunately making the parent's position relative is not an option for my app.

Thanks!

**Comment by woutervanwijk** [comment]
This is indeed not fixed in 100.2. visibility: hidden fixes it

**Comment by litera** [comment]
I was facing the same problem in my app and the `position: relative` has resolved it. But I'm wondering what is the root case of this behaviour? Is this a browser (i.e. webkit) bug or is this some specified behaviour that I'm not aware of?

**Anyone has any info on this?**
