### ISSUE TITLE
getWavesEffectElement incorrect handling of path elements

### ISSUE THREAD

**Issue by ilazarte** [Dogfalo/materialize#996]
Using materializecss in an application where part of the dom is being generated by nvd3.  Clicking the nvd3 chart triggers the getWavesEffectElement check which executes 

    if (target.className.indexOf('waves-effect') ..

The problem is that the element clicked on (svg "path")  does not have an indexOf method. This produces a "Uncaught TypeError: undefined is not a function error". Fix would be to do a check for indexOf method first.

Thanks!  Loving the framework so far.  Using it in a clojurescript app with reagent (react).  Just looks great.

**Comment by slawkacz** [comment]
+1

**Comment by Dogfalo** [comment]
Should be fixed by 49db61b.

**Comment by ilazarte** [comment]
Tried it out, works great!  thanks!
