### ISSUE TITLE
Radio and Check Box Does not work with NG-repeat

### ISSUE THREAD

**Issue by Novashock** [Dogfalo/materialize#998]
I am trying to make the radio button work with ng-repeat, and passing a function via ng-change. Unfortunately, this is not working for me! I do not know if I am doing something wrong of this is one of the issues that can be helped resolve in the future release.

**Comment by Dogfalo** [comment]
The label should go after the input. and you should tie them together with id and for

**Comment by Novashock** [comment]
Thanks, I have tried this, and still is not working. The problem is how do you make the id, and for Dynamic. I am pushing Data into list from the Database. It works with Materialize, but one I activate materialize, the radio will not display.

**Comment by Dogfalo** [comment]
Checkout this jsbin that someone else made: http://jsfiddle.net/ak0on6kL/
